{
  "abstract": [
    {
      "text": "Update your apps to use new features, and test your apps against API changes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.macOS-Release-Notes/documentation/macos-release-notes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.macOS-Release-Notes/documentation/macOS-Release-Notes/appkit-release-notes-for-macos-13"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "role": "article",
    "roleHeading": "Article",
    "title": "AppKit Release Notes for macOS Ventura 13"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "AppKit in macOS Ventura 13 includes new features, as well as API changes and deprecations.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "New-Features",
          "level": 3,
          "text": "New Features",
          "type": "heading"
        },
        {
          "anchor": "NSColorWell",
          "level": 4,
          "text": "NSColorWell",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Color wells have a modernized appearance and two new styles in macOS 13. See the new ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSColorWell/colorWellStyle",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property and associated ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSColorWell/Style",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " type for more information on configuring a color well’s style.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The two new color well styles, ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSColorWell/Style/minimal",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSColorWell/Style/expanded",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", offer a pull-down capability. By default, interacting with the well displays a popover with a palette of color choices for quick picking. Applications can customize this interaction using the new ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSColorWell/pulldownTarget",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSColorWell/pulldownAction",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " properties.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Borderless color wells will be deprecated in a future release. The ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSColorWell/isBordered",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property has been annotated as such.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "NSComboButton",
          "level": 4,
          "text": "NSComboButton",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "macOS 13 introduces a new type of control: ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSComboButton",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". NSComboButton provides the functionality of a pull-down menu along with a primary action.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "NSComboButton is configurable with two styles, ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSComboButton/Style-swift.enum/split",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSComboButton/Style-swift.enum/unified",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". Refer to the class documentation for guidance on the appearance and behavior of each case.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "NSNib",
          "level": 4,
          "text": "NSNib",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The ",
                      "type": "text"
                    },
                    {
                      "text": "doc://com.apple.documentation/documentation/appkit/nsnib/1547299-initwithcontentsofurl",
                      "type": "text"
                    },
                    {
                      "text": " initializer (deprecated since 10.8) now throws an assertion. Use ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSNib/init(nibNamed:bundle:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " instead.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "NSTableView-and-NSOutlineView",
          "level": 4,
          "text": "NSTableView and NSOutlineView",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "On macOS 13 and higher, changing the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSTableView/autosaveName-swift.property",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property from one value to another will automatically persist autosave data for the old value before changing to the new value. Setting ",
                      "type": "text"
                    },
                    {
                      "code": "autosaveName",
                      "type": "codeVoice"
                    },
                    {
                      "text": " to ",
                      "type": "text"
                    },
                    {
                      "code": "nil",
                      "type": "codeVoice"
                    },
                    {
                      "text": " removes the persistence data for the previously set ",
                      "type": "text"
                    },
                    {
                      "code": "autosaveName",
                      "type": "codeVoice"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "NSTableView and NSOutlineView now automatically estimate row heights for view-based table views whose delegates implement ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSTableViewDelegate/tableView(_:heightOfRow:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and provide variable row heights. This provides performance improvements for table views with large numbers of rows by reducing the frequency of the calls to ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSTableViewDelegate/tableView(_:heightOfRow:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "To get the benefit of row height estimation, the table view must be view-based and not override ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/AppKit/NSTableView/rect(ofRow:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/AppKit/NSTableView/row(at:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", or ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/AppKit/NSTableView/rows(in:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "For cell-based table views, checking Autosave Column Information in Interface Builder now correctly persists column information for columns that have automatic column identifiers.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "For apps linked against the macOS 13 SDK, ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSTableRowView",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and subclasses that override ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSTableRowView/drawSeparator(in:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " now draw their separators correctly, even when displayed as floating group rows.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Deprecations",
          "level": 3,
          "text": "Deprecations",
          "type": "heading"
        },
        {
          "anchor": "NSToolbar",
          "level": 4,
          "text": "NSToolbar",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Placing an NSToolbarItem item taller than the toolbar height is not supported and will result in clipping. When drawing a custom badge, use alignmentRectInsets of the control to describe where the button is and draw within the inset area.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/AppKit/NSColorWell/Style": {
      "abstract": [
        {
          "text": "Constants that specify the appearance and interaction modes for a color well.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Style"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSColorWell/Style",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSColorWell.Style",
      "type": "topic",
      "url": "/documentation/AppKit/NSColorWell/Style"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSColorWell/Style/expanded": {
      "abstract": [
        {
          "text": "A style that supports a color picker popover for fast interactions, and adds a dedicated button to display the color panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "expanded"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSColorWell/Style/expanded",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSColorWell.Style.expanded",
      "type": "topic",
      "url": "/documentation/AppKit/NSColorWell/Style/expanded"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSColorWell/Style/minimal": {
      "abstract": [
        {
          "text": "A style that adds minimal adornments to the color well.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minimal"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSColorWell/Style/minimal",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSColorWell.Style.minimal",
      "type": "topic",
      "url": "/documentation/AppKit/NSColorWell/Style/minimal"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSColorWell/colorWellStyle": {
      "abstract": [
        {
          "text": "The appearance and interaction style to apply to the color well.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "colorWellStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColorWell",
          "text": "NSColorWell"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSColorWellStyle",
          "text": "Style"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSColorWell/colorWellStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "colorWellStyle",
      "type": "topic",
      "url": "/documentation/AppKit/NSColorWell/colorWellStyle"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSColorWell/isBordered": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the color well has a border.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isBordered"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSColorWell/isBordered",
      "kind": "symbol",
      "role": "symbol",
      "title": "isBordered",
      "type": "topic",
      "url": "/documentation/AppKit/NSColorWell/isBordered"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSColorWell/pulldownAction": {
      "abstract": [
        {
          "text": "The action to perform when someone clicks in the color area of the color well.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pulldownAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8SelectorV",
          "text": "Selector"
        },
        {
          "kind": "text",
          "text": "? { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSColorWell/pulldownAction",
      "kind": "symbol",
      "role": "symbol",
      "title": "pulldownAction",
      "type": "topic",
      "url": "/documentation/AppKit/NSColorWell/pulldownAction"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSColorWell/pulldownTarget": {
      "abstract": [
        {
          "text": "The target object that defines the action you want to perform when someone interacts with the color well.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "weak"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pulldownTarget"
        },
        {
          "kind": "text",
          "text": ": AnyObject? { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSColorWell/pulldownTarget",
      "kind": "symbol",
      "role": "symbol",
      "title": "pulldownTarget",
      "type": "topic",
      "url": "/documentation/AppKit/NSColorWell/pulldownTarget"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSComboButton": {
      "abstract": [
        {
          "text": "A button with a pull-down menu and a default action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSComboButton"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSComboButton",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSComboButton",
      "type": "topic",
      "url": "/documentation/AppKit/NSComboButton"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSComboButton/Style-swift.enum/split": {
      "abstract": [
        {
          "text": "A style that separates the button’s title and image from the menu indicator people use to activate the button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "split"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSComboButton/Style-swift.enum/split",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSComboButton.Style.split",
      "type": "topic",
      "url": "/documentation/AppKit/NSComboButton/Style-swift.enum/split"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSComboButton/Style-swift.enum/unified": {
      "abstract": [
        {
          "text": "A style that unifies the button’s title and image with the menu indicator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unified"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSComboButton/Style-swift.enum/unified",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSComboButton.Style.unified",
      "type": "topic",
      "url": "/documentation/AppKit/NSComboButton/Style-swift.enum/unified"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSNib/init(nibNamed:bundle:)": {
      "abstract": [
        {
          "text": "Returns an `NSNib` object initialized to the nib file in the specified bundle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "nibNamed"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "nibName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNib",
          "text": "NSNib"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNibName",
          "text": "Name"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "bundle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSBundle",
          "text": "Bundle"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSNib/init(nibNamed:bundle:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(nibNamed:bundle:)",
      "type": "topic",
      "url": "/documentation/AppKit/NSNib/init(nibNamed:bundle:)"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSTableRowView": {
      "abstract": [
        {
          "text": "The view shown for a row in a table view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTableRowView"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSTableRowView",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTableRowView",
      "type": "topic",
      "url": "/documentation/AppKit/NSTableRowView"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSTableRowView/drawSeparator(in:)": {
      "abstract": [
        {
          "text": "Draws the horizontal separator between table rows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "drawSeparator"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "dirtyRect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSTableRowView/drawSeparator(in:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "drawSeparator(in:)",
      "type": "topic",
      "url": "/documentation/AppKit/NSTableRowView/drawSeparator(in:)"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSTableView/autosaveName-swift.property": {
      "abstract": [
        {
          "text": "The name under which table information is automatically saved.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "autosaveName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTableView",
          "text": "NSTableView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTableViewAutosaveName",
          "text": "AutosaveName"
        },
        {
          "kind": "text",
          "text": "? { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSTableView/autosaveName-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "autosaveName",
      "type": "topic",
      "url": "/documentation/AppKit/NSTableView/autosaveName-swift.property"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSTableView/rect(ofRow:)": {
      "abstract": [
        {
          "text": "Returns the rectangle containing the row at the specified index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "ofRow"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "row"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSTableView/rect(ofRow:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "rect(ofRow:)",
      "type": "topic",
      "url": "/documentation/AppKit/NSTableView/rect(ofRow:)"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSTableView/row(at:)": {
      "abstract": [
        {
          "text": "Returns the index of the row the specified point lies in.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "row"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "point"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSTableView/row(at:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "row(at:)",
      "type": "topic",
      "url": "/documentation/AppKit/NSTableView/row(at:)"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSTableView/rows(in:)": {
      "abstract": [
        {
          "text": "Returns a range of indexes for the rows that lie wholly or partially within the vertical boundaries of the specified rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rows"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "rect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSTableView/rows(in:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "rows(in:)",
      "type": "topic",
      "url": "/documentation/AppKit/NSTableView/rows(in:)"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSTableViewDelegate/tableView(_:heightOfRow:)": {
      "abstract": [
        {
          "text": "Asks the delegate for the height of the specified row.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "optional"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tableView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "tableView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTableView",
          "text": "NSTableView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "heightOfRow"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "row"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSTableViewDelegate/tableView(_:heightOfRow:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "tableView(_:heightOfRow:)",
      "type": "topic",
      "url": "/documentation/AppKit/NSTableViewDelegate/tableView(_:heightOfRow:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.macOS-Release-Notes/documentation/macos-release-notes": {
      "abstract": [
        {
          "text": "Learn about changes to the macOS SDK.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.macOS-Release-Notes/documentation/macos-release-notes",
      "kind": "article",
      "role": "collection",
      "title": "macOS Release Notes",
      "type": "topic",
      "url": "/documentation/macos-release-notes"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSTableView~1row(at:)/title",
          "value": "rowAtPoint:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSTableView~1row(at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSInteger",
              "text": "NSInteger"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "rowAtPoint:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSPoint",
              "text": "NSPoint"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "point"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSComboButton~1Style-swift.enum~1unified/title",
          "value": "NSComboButtonStyleUnified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSComboButton~1Style-swift.enum~1unified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSComboButtonStyleUnified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSTableRowView~1drawSeparator(in:)/title",
          "value": "drawSeparatorInRect:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSTableRowView~1drawSeparator(in:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "drawSeparatorInRect:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSRect",
              "text": "NSRect"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "dirtyRect"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSColorWell~1isBordered/title",
          "value": "bordered"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSColorWell~1isBordered/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "getter"
            },
            {
              "kind": "text",
              "text": "="
            },
            {
              "kind": "identifier",
              "text": "isBordered"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "bordered"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:heightOfRow:)/title",
          "value": "tableView:heightOfRow:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:heightOfRow:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CGFloat",
              "text": "CGFloat"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "tableView:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSTableView",
              "text": "NSTableView"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "tableView"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "heightOfRow:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSInteger",
              "text": "NSInteger"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "row"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSTableView~1rows(in:)/title",
          "value": "rowsInRect:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSTableView~1rows(in:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@_NSRange",
              "text": "NSRange"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "rowsInRect:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSRect",
              "text": "NSRect"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "rect"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSTableRowView/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSTableRowView"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSView",
              "text": "NSView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSColorWell~1Style/title",
          "value": "NSColorWellStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSColorWell~1Style/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSColorWellStyle"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSInteger",
              "text": "NSInteger"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSComboButton~1Style-swift.enum~1split/title",
          "value": "NSComboButtonStyleSplit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSComboButton~1Style-swift.enum~1split/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSComboButtonStyleSplit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSComboButton/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSComboButton"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSControl",
              "text": "NSControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSColorWell~1Style~1minimal/title",
          "value": "NSColorWellStyleMinimal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSColorWell~1Style~1minimal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorWellStyleMinimal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSColorWell~1pulldownAction/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SEL",
              "text": "SEL"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "pulldownAction"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSColorWell~1colorWellStyle/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "assign"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSColorWellStyle",
              "text": "NSColorWellStyle"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "colorWellStyle"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSColorWell~1pulldownTarget/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "weak"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "keyword",
              "text": "id"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "pulldownTarget"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSTableView~1rect(ofRow:)/title",
          "value": "rectOfRow:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSTableView~1rect(ofRow:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSRect",
              "text": "NSRect"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "rectOfRow:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSInteger",
              "text": "NSInteger"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "row"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSTableView~1autosaveName-swift.property/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "copy"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSTableViewAutosaveName",
              "text": "NSTableViewAutosaveName"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "autosaveName"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSColorWell~1Style~1expanded/title",
          "value": "NSColorWellStyleExpanded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSColorWell~1Style~1expanded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorWellStyleExpanded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSNib~1init(nibNamed:bundle:)/title",
          "value": "initWithNibNamed:bundle:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSNib~1init(nibNamed:bundle:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "keyword",
              "text": "instancetype"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "initWithNibNamed:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSNibName",
              "text": "NSNibName"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "nibName"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "bundle:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSBundle",
              "text": "NSBundle"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "bundle"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
