{
  "abstract": [
    {
      "text": "Update your apps to use new features, and test your apps against API changes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.macOS-Release-Notes/documentation/macos-release-notes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.macOS-Release-Notes/documentation/macOS-Release-Notes/macos-mojave_10_14_4-release-notes"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "role": "article",
    "roleHeading": "Article",
    "title": "macOS Mojave 10.14.4 Release Notes"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The macOS 10.14.4 SDK provides support for developing apps for Macs running macOS Mojave 10.14.4. The SDK comes bundled with Xcode 10.2 available from the Mac App Store. For information on the compatibility requirements for Xcode 10.2, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Xcode-Release-Notes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Accessibility",
          "level": 3,
          "text": "Accessibility",
          "type": "heading"
        },
        {
          "anchor": "Known-Issues",
          "level": 4,
          "text": "Known Issues",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "VoiceOver may no longer be able to access web content when moving backward or forward through the current Safari tab’s history. (48831713)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                },
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Workaround:",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " In Safari, select Preferences > Advanced > “Show Develop menu in menu bar”, then deselect Develop > Experimental Features > “Swap Processes on Cross-Site Navigation”.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "App-Store",
          "level": 3,
          "text": "App Store",
          "type": "heading"
        },
        {
          "anchor": "Promoting-Your-Subscriptions-with-New-Offers",
          "level": 4,
          "text": "Promoting Your Subscriptions with New Offers",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "StoreKit now supports subscription offers in addition to introductory offers, so apps with auto-renewable subscriptions can provide a discounted price for a specific duration for existing and previously subscribed customers. You can use subscription offers to help win back subscribers who have canceled their subscriptions or promote an upgrade to another subscription at a special price. Customers can accept the offer even if they’ve already completed an introductory offer.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "StoreKit introduces a new array of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/StoreKit/SKProductDiscount",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects within the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/StoreKit/SKProduct",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class to display offers within your app to eligible customers. Add a new ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/StoreKit/SKPaymentDiscount",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object within the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/StoreKit/SKPayment",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class to allow these offers to be accepted by the customer.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "News",
          "level": 3,
          "text": "News",
          "type": "heading"
        },
        {
          "anchor": "New-Features",
          "level": 4,
          "text": "New Features",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Apple News is available in Canada with macOS 10.14.4. Apple News in Canada supports both English and French. Readers can access a bilingual experience when they follow a channel in a second language.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Safari",
          "level": 3,
          "text": "Safari",
          "type": "heading"
        },
        {
          "anchor": "Known-Issues",
          "level": 4,
          "text": "Known Issues",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "After updating to Safari 12.1 from Safari 10.1.2, web pages might not display. (47335741)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                },
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Workaround:",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " Run the following command in Terminal: ",
                      "type": "text"
                    },
                    {
                      "code": "defaults delete com.apple.Safari",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                },
                {
                  "content": [
                    {
                      "inlineContent": [
                        {
                          "text": "You will lose your previous Safari settings after running the command",
                          "type": "text"
                        },
                        {
                          "text": " ",
                          "type": "text"
                        },
                        {
                          "text": "above.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ],
                  "name": "Warning",
                  "style": "warning",
                  "type": "aside"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/StoreKit/SKPayment": {
      "abstract": [
        {
          "text": "A request to the App Store to process payment for additional functionality that your app offers.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKPayment"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/SKPayment",
      "kind": "symbol",
      "role": "symbol",
      "title": "SKPayment",
      "type": "topic",
      "url": "/documentation/StoreKit/SKPayment"
    },
    "doc://com.apple.documentation/documentation/StoreKit/SKPaymentDiscount": {
      "abstract": [
        {
          "text": "The signed discount to apply to a payment.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKPaymentDiscount"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/SKPaymentDiscount",
      "kind": "symbol",
      "role": "symbol",
      "title": "SKPaymentDiscount",
      "type": "topic",
      "url": "/documentation/StoreKit/SKPaymentDiscount"
    },
    "doc://com.apple.documentation/documentation/StoreKit/SKProduct": {
      "abstract": [
        {
          "text": "Information about a registered product in App Store Connect.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKProduct"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/SKProduct",
      "kind": "symbol",
      "role": "symbol",
      "title": "SKProduct",
      "type": "topic",
      "url": "/documentation/StoreKit/SKProduct"
    },
    "doc://com.apple.documentation/documentation/StoreKit/SKProductDiscount": {
      "abstract": [
        {
          "text": "The details of an introductory offer or a promotional offer for an auto-renewable subscription.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKProductDiscount"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/SKProductDiscount",
      "kind": "symbol",
      "role": "symbol",
      "title": "SKProductDiscount",
      "type": "topic",
      "url": "/documentation/StoreKit/SKProductDiscount"
    },
    "doc://com.apple.documentation/documentation/Xcode-Release-Notes": {
      "abstract": [
        {
          "text": "Learn about changes to Xcode.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Xcode-Release-Notes",
      "kind": "article",
      "role": "collection",
      "title": "Xcode Release Notes",
      "type": "topic",
      "url": "/documentation/Xcode-Release-Notes"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.macOS-Release-Notes/documentation/macOS-Release-Notes/macos-mojave-10_14-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.macOS-Release-Notes/documentation/macOS-Release-Notes/macos-mojave-10_14-release-notes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "macOS Mojave 10.14 Release Notes",
      "type": "topic",
      "url": "/documentation/macos-release-notes/macos-mojave-10_14-release-notes"
    },
    "doc://com.apple.macOS-Release-Notes/documentation/macOS-Release-Notes/macos-mojave-10_14_2-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.macOS-Release-Notes/documentation/macOS-Release-Notes/macos-mojave-10_14_2-release-notes",
      "kind": "article",
      "role": "article",
      "title": "macOS Mojave 10.14.2 Release Notes",
      "type": "topic",
      "url": "/documentation/macos-release-notes/macos-mojave-10_14_2-release-notes"
    },
    "doc://com.apple.macOS-Release-Notes/documentation/macOS-Release-Notes/macos-mojave-10_14_3-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.macOS-Release-Notes/documentation/macOS-Release-Notes/macos-mojave-10_14_3-release-notes",
      "kind": "article",
      "role": "article",
      "title": "macOS Mojave 10.14.3 Release Notes",
      "type": "topic",
      "url": "/documentation/macos-release-notes/macos-mojave-10_14_3-release-notes"
    },
    "doc://com.apple.macOS-Release-Notes/documentation/macOS-Release-Notes/macos-mojave-10_14_5-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.macOS-Release-Notes/documentation/macOS-Release-Notes/macos-mojave-10_14_5-release-notes",
      "kind": "article",
      "role": "article",
      "title": "macOS Mojave 10.14.5 Release Notes",
      "type": "topic",
      "url": "/documentation/macos-release-notes/macos-mojave-10_14_5-release-notes"
    },
    "doc://com.apple.macOS-Release-Notes/documentation/macOS-Release-Notes/macos-mojave-10_14_6-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.macOS-Release-Notes/documentation/macOS-Release-Notes/macos-mojave-10_14_6-release-notes",
      "kind": "article",
      "role": "article",
      "title": "macOS Mojave 10.14.6 Release Notes",
      "type": "topic",
      "url": "/documentation/macos-release-notes/macos-mojave-10_14_6-release-notes"
    },
    "doc://com.apple.macOS-Release-Notes/documentation/macos-release-notes": {
      "abstract": [
        {
          "text": "Learn about changes to the macOS SDK.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.macOS-Release-Notes/documentation/macos-release-notes",
      "kind": "article",
      "role": "collection",
      "title": "macOS Release Notes",
      "type": "topic",
      "url": "/documentation/macos-release-notes"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "macOS-1014",
      "generated": true,
      "identifiers": [
        "doc://com.apple.macOS-Release-Notes/documentation/macOS-Release-Notes/macos-mojave-10_14_6-release-notes",
        "doc://com.apple.macOS-Release-Notes/documentation/macOS-Release-Notes/macos-mojave-10_14_5-release-notes",
        "doc://com.apple.macOS-Release-Notes/documentation/macOS-Release-Notes/macos-mojave-10_14_3-release-notes",
        "doc://com.apple.macOS-Release-Notes/documentation/macOS-Release-Notes/macos-mojave-10_14_2-release-notes",
        "doc://com.apple.macOS-Release-Notes/documentation/macOS-Release-Notes/macos-mojave-10_14-release-notes"
      ],
      "title": "macOS 10.14"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1StoreKit~1SKPaymentDiscount/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SKPaymentDiscount"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1StoreKit~1SKPayment/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SKPayment"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1StoreKit~1SKProductDiscount/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SKProductDiscount"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1StoreKit~1SKProduct/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SKProduct"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
