{
  "abstract": [
    {
      "text": "Update your apps to use new features, and test your apps against API changes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.macOS-Release-Notes/documentation/macos-release-notes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.macOS-Release-Notes/documentation/macOS-Release-Notes/macos-big-sur-11_1-release-notes"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "role": "article",
    "roleHeading": "Article",
    "title": "macOS Big Sur 11.1 Release Notes"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The macOS 11.1 SDK provides support to develop apps for Macs running macOS Big Sur 11.1. The SDK comes bundled with Xcode 12.3, available from the Mac App Store. For information on the compatibility requirements for Xcode 12.3, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Xcode-Release-Notes/xcode-12_3-release-notes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "AppKit",
          "level": 3,
          "text": "AppKit",
          "type": "heading"
        },
        {
          "anchor": "Resolved-Issues",
          "level": 4,
          "text": "Resolved Issues",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSToolbar",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " controls now draw the background correctly when you click or roll over them. (71592628)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Mac-Catalyst",
          "level": 3,
          "text": "Mac Catalyst",
          "type": "heading"
        },
        {
          "anchor": "New-Features",
          "level": 4,
          "text": "New Features",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "iOS & iPadOS apps with non-resizable windows can now enter full-screen mode. (70103920)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Known-Issues",
          "level": 4,
          "text": "Known Issues",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "When you present a view controller with page sheet or form sheet presentation style, the size of the view controller’s root view is, by default, determined by the value returned from the presented view controller’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIViewController/preferredContentSize",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " method and the view is not resizable. You can arrange for the presented view controller to be resizable by using Auto Layout to specify the maximum and minimum sizes of its root view. To enable this, set the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIWindow/canResizeToFitContent",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property of the application’s main window to YES. One way to do this is to override the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIView/willMove(toWindow:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " or ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIView/didMoveToWindow()",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " methods of a view in the main view controller. (65254666)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                },
                {
                  "inlineContent": [
                    {
                      "text": "For example:",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                },
                {
                  "code": [
                    "- (void)willMoveToWindow:(UIWindow *)newWindow {",
                    "    [super willMoveToWindow:newWindow];",
                    "    newWindow.canResizeToFitContent = YES;",
                    "}"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/AppKit/NSToolbar": {
      "abstract": [
        {
          "text": "An object that manages the space above your app’s custom content and either below or integrated with the window’s title bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSToolbar"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSToolbar",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSToolbar",
      "type": "topic",
      "url": "/documentation/AppKit/NSToolbar"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIView/didMoveToWindow()": {
      "abstract": [
        {
          "text": "Tells the view that its window object changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didMoveToWindow"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIView/didMoveToWindow()",
      "kind": "symbol",
      "role": "symbol",
      "title": "didMoveToWindow()",
      "type": "topic",
      "url": "/documentation/UIKit/UIView/didMoveToWindow()"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIView/willMove(toWindow:)": {
      "abstract": [
        {
          "text": "Tells the view that its window object is about to change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "willMove"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "toWindow"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "newWindow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIWindow",
          "text": "UIWindow"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIView/willMove(toWindow:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "willMove(toWindow:)",
      "type": "topic",
      "url": "/documentation/UIKit/UIView/willMove(toWindow:)"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIViewController/preferredContentSize": {
      "abstract": [
        {
          "text": "The preferred size for the view controller’s view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredContentSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIViewController/preferredContentSize",
      "kind": "symbol",
      "role": "symbol",
      "title": "preferredContentSize",
      "type": "topic",
      "url": "/documentation/UIKit/UIViewController/preferredContentSize"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIWindow/canResizeToFitContent": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the window’s constraint-based content determines its size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canResizeToFitContent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIWindow/canResizeToFitContent",
      "kind": "symbol",
      "role": "symbol",
      "title": "canResizeToFitContent",
      "type": "topic",
      "url": "/documentation/UIKit/UIWindow/canResizeToFitContent"
    },
    "doc://com.apple.documentation/documentation/Xcode-Release-Notes/xcode-12_3-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Xcode-Release-Notes/xcode-12_3-release-notes",
      "kind": "article",
      "role": "article",
      "title": "Xcode 12.3 Release Notes",
      "type": "topic",
      "url": "/documentation/Xcode-Release-Notes/xcode-12_3-release-notes"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.macOS-Release-Notes/documentation/macOS-Release-Notes/macos-big-sur-11_0_1-ios-ipados-apps-on-mac-release-notes": {
      "abstract": [
        {
          "text": "Considerations for running iPhone and iPad apps on Macs with Apple silicon.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.macOS-Release-Notes/documentation/macOS-Release-Notes/macos-big-sur-11_0_1-ios-ipados-apps-on-mac-release-notes",
      "kind": "article",
      "role": "article",
      "title": "macOS Big Sur 11.0.1 iOS & iPadOS Apps on Mac Release Notes",
      "type": "topic",
      "url": "/documentation/macos-release-notes/macos-big-sur-11_0_1-ios-ipados-apps-on-mac-release-notes"
    },
    "doc://com.apple.macOS-Release-Notes/documentation/macOS-Release-Notes/macos-big-sur-11_0_1-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.macOS-Release-Notes/documentation/macOS-Release-Notes/macos-big-sur-11_0_1-release-notes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "macOS Big Sur 11.0.1 Release Notes",
      "type": "topic",
      "url": "/documentation/macos-release-notes/macos-big-sur-11_0_1-release-notes"
    },
    "doc://com.apple.macOS-Release-Notes/documentation/macOS-Release-Notes/macos-big-sur-11_0_1-universal-apps-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to support Macs with Apple silicon.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.macOS-Release-Notes/documentation/macOS-Release-Notes/macos-big-sur-11_0_1-universal-apps-release-notes",
      "kind": "article",
      "role": "article",
      "title": "macOS Big Sur 11.0.1 Universal Apps Release Notes",
      "type": "topic",
      "url": "/documentation/macos-release-notes/macos-big-sur-11_0_1-universal-apps-release-notes"
    },
    "doc://com.apple.macOS-Release-Notes/documentation/macOS-Release-Notes/macos-big-sur-11_2-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.macOS-Release-Notes/documentation/macOS-Release-Notes/macos-big-sur-11_2-release-notes",
      "kind": "article",
      "role": "article",
      "title": "macOS Big Sur 11.2 Release Notes",
      "type": "topic",
      "url": "/documentation/macos-release-notes/macos-big-sur-11_2-release-notes"
    },
    "doc://com.apple.macOS-Release-Notes/documentation/macOS-Release-Notes/macos-big-sur-11_3-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.macOS-Release-Notes/documentation/macOS-Release-Notes/macos-big-sur-11_3-release-notes",
      "kind": "article",
      "role": "article",
      "title": "macOS Big Sur 11.3 Release Notes",
      "type": "topic",
      "url": "/documentation/macos-release-notes/macos-big-sur-11_3-release-notes"
    },
    "doc://com.apple.macOS-Release-Notes/documentation/macOS-Release-Notes/macos-big-sur-11_4-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.macOS-Release-Notes/documentation/macOS-Release-Notes/macos-big-sur-11_4-release-notes",
      "kind": "article",
      "role": "article",
      "title": "macOS Big Sur 11.4 Release Notes",
      "type": "topic",
      "url": "/documentation/macos-release-notes/macos-big-sur-11_4-release-notes"
    },
    "doc://com.apple.macOS-Release-Notes/documentation/macOS-Release-Notes/macos-big-sur-11_5-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.macOS-Release-Notes/documentation/macOS-Release-Notes/macos-big-sur-11_5-release-notes",
      "kind": "article",
      "role": "article",
      "title": "macOS Big Sur 11.5 Release Notes",
      "type": "topic",
      "url": "/documentation/macos-release-notes/macos-big-sur-11_5-release-notes"
    },
    "doc://com.apple.macOS-Release-Notes/documentation/macos-release-notes": {
      "abstract": [
        {
          "text": "Learn about changes to the macOS SDK.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.macOS-Release-Notes/documentation/macos-release-notes",
      "kind": "article",
      "role": "collection",
      "title": "macOS Release Notes",
      "type": "topic",
      "url": "/documentation/macos-release-notes"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "macOS-11",
      "generated": true,
      "identifiers": [
        "doc://com.apple.macOS-Release-Notes/documentation/macOS-Release-Notes/macos-big-sur-11_5-release-notes",
        "doc://com.apple.macOS-Release-Notes/documentation/macOS-Release-Notes/macos-big-sur-11_4-release-notes",
        "doc://com.apple.macOS-Release-Notes/documentation/macOS-Release-Notes/macos-big-sur-11_3-release-notes",
        "doc://com.apple.macOS-Release-Notes/documentation/macOS-Release-Notes/macos-big-sur-11_2-release-notes",
        "doc://com.apple.macOS-Release-Notes/documentation/macOS-Release-Notes/macos-big-sur-11_0_1-release-notes",
        "doc://com.apple.macOS-Release-Notes/documentation/macOS-Release-Notes/macos-big-sur-11_0_1-universal-apps-release-notes",
        "doc://com.apple.macOS-Release-Notes/documentation/macOS-Release-Notes/macos-big-sur-11_0_1-ios-ipados-apps-on-mac-release-notes"
      ],
      "title": "macOS 11"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIView~1didMoveToWindow()/title",
          "value": "didMoveToWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIView~1didMoveToWindow()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "didMoveToWindow"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIViewController~1preferredContentSize/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@CGSize",
              "text": "CGSize"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "preferredContentSize"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSToolbar/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSToolbar"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIView~1willMove(toWindow:)/title",
          "value": "willMoveToWindow:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIView~1willMove(toWindow:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "willMoveToWindow:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIWindow",
              "text": "UIWindow"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "newWindow"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIWindow~1canResizeToFitContent/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "setter"
            },
            {
              "kind": "text",
              "text": "="
            },
            {
              "kind": "identifier",
              "text": "setCanResizeToFitContent:"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "canResizeToFitContent"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
