{
  "abstract": [
    {
      "text": "An object that defines the video attributes for an asset variant.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant/VideoAttributes-swift.class"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AVFoundation",
    "externalID": "c:objc(cs)AVAssetVariantVideoAttributes",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "VideoAttributes"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VideoAttributes"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "AVAssetVariant.VideoAttributes"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "VideoAttributes"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant": {
      "abstract": [
        {
          "text": "An object that represents a bit rate variant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetVariant"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetVariant"
        }
      ],
      "role": "symbol",
      "title": "AVAssetVariant",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetvariant"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant/AudioAttributes-swift.class": {
      "abstract": [
        {
          "text": "An object that defines the audio attributes for an asset variant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioAttributes"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant/AudioAttributes-swift.class",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioAttributes"
        }
      ],
      "role": "symbol",
      "title": "AVAssetVariant.AudioAttributes",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetvariant/audioattributes-swift.class"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant/VideoAttributes-swift.class": {
      "abstract": [
        {
          "text": "An object that defines the video attributes for an asset variant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VideoAttributes"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant/VideoAttributes-swift.class",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VideoAttributes"
        }
      ],
      "role": "symbol",
      "title": "AVAssetVariant.VideoAttributes",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetvariant/videoattributes-swift.class"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant/VideoAttributes-swift.class/LayoutAttributes": {
      "abstract": [
        {
          "text": "Attributes that describe the layout of video content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LayoutAttributes"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant/VideoAttributes-swift.class/LayoutAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LayoutAttributes"
        }
      ],
      "role": "symbol",
      "title": "AVAssetVariant.VideoAttributes.LayoutAttributes",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetvariant/videoattributes-swift.class/layoutattributes"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant/VideoAttributes-swift.class/codecTypes": {
      "abstract": [
        {
          "text": "The video sample codec types present in the variant’s renditions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "codecTypes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant/VideoAttributes-swift.class/codecTypes",
      "kind": "symbol",
      "role": "symbol",
      "title": "codecTypes",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetvariant/videoattributes-swift.class/codectypes"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant/VideoAttributes-swift.class/nominalFrameRate": {
      "abstract": [
        {
          "text": "The nominal frame rate of the variant’s renditions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nominalFrameRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant/VideoAttributes-swift.class/nominalFrameRate",
      "kind": "symbol",
      "role": "symbol",
      "title": "nominalFrameRate",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetvariant/videoattributes-swift.class/nominalframerate"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant/VideoAttributes-swift.class/presentationSize": {
      "abstract": [
        {
          "text": "The presentation size of the variant’s renditions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "presentationSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant/VideoAttributes-swift.class/presentationSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "presentationSize"
        }
      ],
      "role": "symbol",
      "title": "presentationSize",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetvariant/videoattributes-swift.class/presentationsize"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant/VideoAttributes-swift.class/videoLayoutAttributes": {
      "abstract": [
        {
          "text": "Attributes that describe the layout of the video content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "videoLayoutAttributes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAssetVariant",
          "text": "AVAssetVariant"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAssetVariantVideoAttributes",
          "text": "VideoAttributes"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAssetVariantVideoLayoutAttributes",
          "text": "LayoutAttributes"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant/VideoAttributes-swift.class/videoLayoutAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "videoLayoutAttributes"
        }
      ],
      "role": "symbol",
      "title": "videoLayoutAttributes",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetvariant/videoattributes-swift.class/videolayoutattributes"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant/VideoAttributes-swift.class/videoRange": {
      "abstract": [
        {
          "text": "The video range of the variant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "videoRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVVideoRange",
          "text": "AVVideoRange"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant/VideoAttributes-swift.class/videoRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "videoRange"
        }
      ],
      "role": "symbol",
      "title": "videoRange",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetvariant/videoattributes-swift.class/videorange"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant/audioAttributes-swift.property": {
      "abstract": [
        {
          "text": "The audio rendition attributes for the variant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audioAttributes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAssetVariant",
          "text": "AVAssetVariant"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAssetVariantAudioAttributes",
          "text": "AudioAttributes"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant/audioAttributes-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "audioAttributes"
        }
      ],
      "role": "symbol",
      "title": "audioAttributes",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetvariant/audioattributes-swift.property"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant/videoAttributes-swift.property": {
      "abstract": [
        {
          "text": "The video rendition attributes for the variant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "videoAttributes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAssetVariant",
          "text": "AVAssetVariant"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAssetVariantVideoAttributes",
          "text": "VideoAttributes"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant/videoAttributes-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "videoAttributes"
        }
      ],
      "role": "symbol",
      "title": "videoAttributes",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetvariant/videoattributes-swift.property"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariantVideoAttributes/codecTypes": {
      "abstract": [
        {
          "text": "The video sample codec types present in the variant’s renditions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "codecTypes"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariantVideoAttributes/codecTypes",
      "kind": "symbol",
      "role": "symbol",
      "title": "codecTypes",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetvariantvideoattributes/codectypes"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariantVideoAttributes/nominalFrameRate": {
      "abstract": [
        {
          "text": "The nominal frame rate of the variant’s renditions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "nominalFrameRate"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariantVideoAttributes/nominalFrameRate",
      "kind": "symbol",
      "role": "symbol",
      "title": "nominalFrameRate",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetvariantvideoattributes/nominalframerate"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoRange": {
      "abstract": [
        {
          "text": "Constants that describe a video variant’s dynamic range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVVideoRange"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoRange"
        }
      ],
      "role": "symbol",
      "title": "AVVideoRange",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideorange"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-Attributes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant/audioAttributes-swift.property",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant/AudioAttributes-swift.class",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant/videoAttributes-swift.property"
      ],
      "title": "Configuring Attributes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Inspecting-the-Attributes",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant/VideoAttributes-swift.class/codecTypes",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant/VideoAttributes-swift.class/nominalFrameRate",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant/VideoAttributes-swift.class/presentationSize",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant/VideoAttributes-swift.class/videoRange",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoRange",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant/VideoAttributes-swift.class/videoLayoutAttributes",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant/VideoAttributes-swift.class/LayoutAttributes"
      ],
      "title": "Inspecting the Attributes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVAssetVariantVideoAttributes"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetVariantVideoAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetVariantVideoAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Inspecting-the-Attributes",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariantVideoAttributes/codecTypes",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariantVideoAttributes/nominalFrameRate",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant/VideoAttributes-swift.class/presentationSize",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant/VideoAttributes-swift.class/videoRange",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoRange",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant/VideoAttributes-swift.class/videoLayoutAttributes",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant/VideoAttributes-swift.class/LayoutAttributes"
              ],
              "title": "Inspecting the Attributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-Attributes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant/audioAttributes-swift.property",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant/AudioAttributes-swift.class",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetVariant/videoAttributes-swift.property"
              ],
              "title": "Configuring Attributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVAssetVariantVideoAttributes"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetVariant~1videoAttributes-swift.property/title",
          "value": "videoAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetVariant~1videoAttributes-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "videoAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetVariant~1AudioAttributes-swift.class/title",
          "value": "AVAssetVariantAudioAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetVariant~1AudioAttributes-swift.class/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetVariantAudioAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetVariant~1AudioAttributes-swift.class/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetVariantAudioAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetVariant~1VideoAttributes-swift.class~1presentationSize/title",
          "value": "presentationSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetVariant~1VideoAttributes-swift.class~1presentationSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "presentationSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetVariant~1VideoAttributes-swift.class/title",
          "value": "AVAssetVariantVideoAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetVariant~1VideoAttributes-swift.class/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetVariantVideoAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetVariant~1VideoAttributes-swift.class/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetVariantVideoAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetVariant/title",
          "value": "AVAssetVariant"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetVariant/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetVariant"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetVariant/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetVariant"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoRange/title",
          "value": "AVVideoRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoRange/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetVariant~1VideoAttributes-swift.class~1LayoutAttributes/title",
          "value": "AVAssetVariantVideoLayoutAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetVariant~1VideoAttributes-swift.class~1LayoutAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetVariantVideoLayoutAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetVariant~1VideoAttributes-swift.class~1LayoutAttributes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetVariantVideoLayoutAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetVariant~1VideoAttributes-swift.class~1videoLayoutAttributes/title",
          "value": "videoLayoutAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetVariant~1VideoAttributes-swift.class~1videoLayoutAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "videoLayoutAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetVariant~1audioAttributes-swift.property/title",
          "value": "audioAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetVariant~1audioAttributes-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "audioAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetVariant~1VideoAttributes-swift.class~1videoRange/title",
          "value": "videoRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetVariant~1VideoAttributes-swift.class~1videoRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "videoRange"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avassetvariant/videoattributes-swift.class"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avassetvariant/videoattributes-swift.class"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
