{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.opendirectory/documentation/OpenDirectory",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODConfiguration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODConfiguration/trustUsesKerberosKeytab-c.ivar"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ODConfiguration@trustUsesKerberosKeytab",
    "fragments": [
      {
        "kind": "identifier",
        "text": "trustUsesKerberosKeytab"
      }
    ],
    "modules": [
      {
        "name": "Open Directory"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "trustUsesKerberosKeytab"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Variable",
    "symbolKind": "ivar",
    "title": "trustUsesKerberosKeytab"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "trustUsesKerberosKeytab"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory": {
      "abstract": [
        {
          "text": "Authenticate users, and search for contact information in Open Directory and LDAP directories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory",
      "kind": "symbol",
      "role": "collection",
      "title": "Open Directory",
      "type": "topic",
      "url": "/documentation/opendirectory"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODConfiguration": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODConfiguration"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODConfiguration"
        }
      ],
      "role": "symbol",
      "title": "ODConfiguration",
      "type": "topic",
      "url": "/documentation/opendirectory/odconfiguration"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODConfiguration/trustUsesKerberosKeytab-c.ivar": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "trustUsesKerberosKeytab"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODConfiguration/trustUsesKerberosKeytab-c.ivar",
      "kind": "symbol",
      "role": "symbol",
      "title": "trustUsesKerberosKeytab",
      "type": "topic",
      "url": "/documentation/opendirectory/odconfiguration/trustuseskerberoskeytab-c.ivar"
    },
    "doc://com.externally.resolved.symbol/c:@T@BOOL": {
      "abstract": [
        {
          "text": "Type to represent a Boolean value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
      "kind": "symbol",
      "role": "symbol",
      "title": "BOOL",
      "type": "topic",
      "url": "/documentation/objectivec/bool"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODConfiguration/title",
          "value": "ODConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODConfiguration"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/opendirectory/odconfiguration/trustuseskerberoskeytab-c.ivar"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
