{
  "abstract": [
    {
      "text": "Identifiers for media group types in the Aperture media source. These constants are used to specify a media group’s ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/typeIdentifier",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " attribute.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.medialibrary/documentation/MediaLibrary",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/medialibrary-constants"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.medialibrary/documentation/MediaLibrary/aperture-media-group-type-identifiers"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Media Library"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Aperture Media Group Type Identifiers"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary": {
      "abstract": [
        {
          "text": "Access read-only collections of the user’s multimedia content.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Library",
      "type": "topic",
      "url": "/documentation/medialibrary"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureAllPhotosTypeIdentifier": {
      "abstract": [
        {
          "text": "The media group that represents all photos in Aperture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLApertureAllPhotosTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureAllPhotosTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLApertureAllPhotosTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLApertureAllPhotosTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlapertureallphotostypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureAllProjectsTypeIdentifier": {
      "abstract": [
        {
          "text": "The media group that represents all projects in Aperture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLApertureAllProjectsTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureAllProjectsTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLApertureAllProjectsTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLApertureAllProjectsTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlapertureallprojectstypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureFacebookAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a Facebook album that is visible in Aperture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLApertureFacebookAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureFacebookAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLApertureFacebookAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLApertureFacebookAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlaperturefacebookalbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureFacebookGroupTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a Facebook user account in Aperture. A Facebook user account contains one or more Facebook albums.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLApertureFacebookGroupTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureFacebookGroupTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLApertureFacebookGroupTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLApertureFacebookGroupTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlaperturefacebookgrouptypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureFacesAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a Faces album in Aperture. Individual Faces albums are nested in the main Faces album.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLApertureFacesAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureFacesAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLApertureFacesAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLApertureFacesAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlaperturefacesalbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureFlaggedTypeIdentifier": {
      "abstract": [
        {
          "text": "The media group that represents the album of flagged media in Aperture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLApertureFlaggedTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureFlaggedTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLApertureFlaggedTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLApertureFlaggedTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlapertureflaggedtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureFlickrAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a Flickr album that is visible in Aperture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLApertureFlickrAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureFlickrAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLApertureFlickrAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLApertureFlickrAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlapertureflickralbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureFlickrGroupTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a Flickr user account in Aperture. A Flickr user account contains one or more Flickr albums.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLApertureFlickrGroupTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureFlickrGroupTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLApertureFlickrGroupTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLApertureFlickrGroupTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlapertureflickrgrouptypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureFolderAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a folder in Aperture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLApertureFolderAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureFolderAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLApertureFolderAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLApertureFolderAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlaperturefolderalbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureLastImportAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "The media group that represents the last import album in Aperture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLApertureLastImportAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureLastImportAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLApertureLastImportAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLApertureLastImportAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlaperturelastimportalbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureLastNMonthsAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "The media group that represents the recent content album in Aperture, known as the Last ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "N",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " Months album. The value for ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "N",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " is usually 12 (settable in Aperture > Preferences > General).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLApertureLastNMonthsAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureLastNMonthsAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLApertureLastNMonthsAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLApertureLastNMonthsAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlaperturelastnmonthsalbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureLastViewedEventAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "The media group that represents the last viewed event in Aperture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLApertureLastViewedEventAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureLastViewedEventAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLApertureLastViewedEventAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLApertureLastViewedEventAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlaperturelastviewedeventalbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureLightTableTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a light table in Aperture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLApertureLightTableTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureLightTableTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLApertureLightTableTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLApertureLightTableTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlaperturelighttabletypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLAperturePhotoStreamAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a photo stream in Aperture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLAperturePhotoStreamAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLAperturePhotoStreamAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLAperturePhotoStreamAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLAperturePhotoStreamAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlaperturephotostreamalbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLAperturePlacesAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "The media group that represents the Places album in Aperture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLAperturePlacesAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLAperturePlacesAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLAperturePlacesAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLAperturePlacesAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlapertureplacesalbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLAperturePlacesCityAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a Places album for a city in Aperture. A city album is nested in a province or state album.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLAperturePlacesCityAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLAperturePlacesCityAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLAperturePlacesCityAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLAperturePlacesCityAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlapertureplacescityalbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLAperturePlacesCountryAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a Places album for a country or region in Aperture. A country or region album is nested in the main Places album.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLAperturePlacesCountryAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLAperturePlacesCountryAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLAperturePlacesCountryAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLAperturePlacesCountryAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlapertureplacescountryalbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLAperturePlacesPointOfInterestAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a Places album for a point-of-interest in Aperture. A point of interest album is nested in a city album.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLAperturePlacesPointOfInterestAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLAperturePlacesPointOfInterestAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLAperturePlacesPointOfInterestAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLAperturePlacesPointOfInterestAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlapertureplacespointofinterestalbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLAperturePlacesProvinceAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a Places album for a province or state in Aperture. A province or state album is nested in a country or region album.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLAperturePlacesProvinceAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLAperturePlacesProvinceAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLAperturePlacesProvinceAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLAperturePlacesProvinceAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlapertureplacesprovincealbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureProjectAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a project in Aperture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLApertureProjectAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureProjectAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLApertureProjectAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLApertureProjectAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlapertureprojectalbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureProjectFolderAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a folder within a project in Aperture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLApertureProjectFolderAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureProjectFolderAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLApertureProjectFolderAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLApertureProjectFolderAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlapertureprojectfolderalbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureRootGroupTypeIdentifier": {
      "abstract": [
        {
          "text": "The root media group for Aperture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLApertureRootGroupTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureRootGroupTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLApertureRootGroupTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLApertureRootGroupTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlaperturerootgrouptypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureSlideShowTypeIdentifier": {
      "abstract": [
        {
          "text": "The media group that represents a slideshow in Aperture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLApertureSlideShowTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureSlideShowTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLApertureSlideShowTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLApertureSlideShowTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlapertureslideshowtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureSmugMugAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a SmugMug album that is visible in Aperture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLApertureSmugMugAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureSmugMugAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLApertureSmugMugAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLApertureSmugMugAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlaperturesmugmugalbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureSmugMugGroupTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a SmugMug user account in Aperture. A SmugMug user account contains one or more SmugMug albums.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLApertureSmugMugGroupTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureSmugMugGroupTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLApertureSmugMugGroupTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLApertureSmugMugGroupTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlaperturesmugmuggrouptypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureUserAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a user-created album in Aperture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLApertureUserAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureUserAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLApertureUserAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLApertureUserAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlapertureuseralbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureUserSmartAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a user-created smart album in Aperture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLApertureUserSmartAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureUserSmartAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLApertureUserSmartAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLApertureUserSmartAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlapertureusersmartalbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/typeIdentifier": {
      "abstract": [
        {
          "text": "An identifier for the media group’s type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "typeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/typeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "typeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "typeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediagroup/typeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppFoldersKey": {
      "abstract": [
        {
          "text": "Specifies one or more relative paths inside the caller’s app bundle in which to search for media files. The value for this key is an array of strings (relative paths inside the caller’s app bundle).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaLoadAppFoldersKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppFoldersKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaLoadAppFoldersKey"
        }
      ],
      "role": "symbol",
      "title": "MLMediaLoadAppFoldersKey",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmedialoadappfolderskey"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppleLoops": {
      "abstract": [
        {
          "text": "Identifies the folder containing audio loops from Apple.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaLoadAppleLoops"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppleLoops",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaLoadAppleLoops"
        }
      ],
      "role": "symbol",
      "title": "MLMediaLoadAppleLoops",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmedialoadappleloops"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadExcludeSourcesKey": {
      "abstract": [
        {
          "text": "Defines which media sources to exclude when loading. This option is processed after ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadIncludeSourcesKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ". The value for this key is an array of strings (media source identifiers). For a list of valid media source identifiers, see ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/media-source-identifiers",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaLoadExcludeSourcesKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadExcludeSourcesKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaLoadExcludeSourcesKey"
        }
      ],
      "role": "symbol",
      "title": "MLMediaLoadExcludeSourcesKey",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmedialoadexcludesourceskey"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadFoldersKey": {
      "abstract": [
        {
          "text": "Specifies the well-known folders that should be searched for media files. If this key is not present, none of the well-known folders will be provided. The value for this key is an array of strings (identifiers that correspond to well-known folder locations). For a list of well-known folder identifiers, see ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/well-known-folder-identifiers",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaLoadFoldersKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadFoldersKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaLoadFoldersKey"
        }
      ],
      "role": "symbol",
      "title": "MLMediaLoadFoldersKey",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmedialoadfolderskey"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadIncludeSourcesKey": {
      "abstract": [
        {
          "text": "Defines which media sources to include when loading. If not present, load all available media sources. This option is processed after ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadSourceTypesKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ". If ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadIncludeSourcesKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " is present but ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadSourceTypesKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " is not, then only those sources specified here will be loaded. This is useful for loading a single media source. When both keys are present, this is useful for adding one or more media sources that normally would not appear for the requested library type. The value for this key is an array of strings (media source identifiers). For a list of valid media source identifiers, see ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/media-source-identifiers",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaLoadIncludeSourcesKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadIncludeSourcesKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaLoadIncludeSourcesKey"
        }
      ],
      "role": "symbol",
      "title": "MLMediaLoadIncludeSourcesKey",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmedialoadincludesourceskey"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadMoviesFolder": {
      "abstract": [
        {
          "text": "Identifies the user’s Movies folder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaLoadMoviesFolder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadMoviesFolder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaLoadMoviesFolder"
        }
      ],
      "role": "symbol",
      "title": "MLMediaLoadMoviesFolder",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmedialoadmoviesfolder"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadSourceTypesKey": {
      "abstract": [
        {
          "text": "Defines which sources to load based on library type. If not present, this will load all sources. The value for this key is a media source type. For a list of valid media source types, see ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceType",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaLoadSourceTypesKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadSourceTypesKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaLoadSourceTypesKey"
        }
      ],
      "role": "symbol",
      "title": "MLMediaLoadSourceTypesKey",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmedialoadsourcetypeskey"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceApertureIdentifier": {
      "abstract": [
        {
          "text": "The media source providing content from Aperture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaSourceApertureIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceApertureIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaSourceApertureIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLMediaSourceApertureIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediasourceapertureidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceAppDefinedFoldersIdentifier": {
      "abstract": [
        {
          "text": "The media source for app-defined folders. This identifies a media source created from a relative path inside the caller’s app bundle. This source provides data when ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppFoldersKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " is provided in the options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaSourceAppDefinedFoldersIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceAppDefinedFoldersIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaSourceAppDefinedFoldersIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLMediaSourceAppDefinedFoldersIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediasourceappdefinedfoldersidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceCustomFoldersIdentifier": {
      "abstract": [
        {
          "text": "The media source for custom folders. Currently, the only custom folder is the folder containing audio loops from Apple. This source provides data when ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadFoldersKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " is provided with the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppleLoops",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaSourceCustomFoldersIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceCustomFoldersIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaSourceCustomFoldersIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLMediaSourceCustomFoldersIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediasourcecustomfoldersidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceFinalCutIdentifier": {
      "abstract": [
        {
          "text": "The media source providing content from Final Cut Pro.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaSourceFinalCutIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceFinalCutIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaSourceFinalCutIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLMediaSourceFinalCutIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediasourcefinalcutidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceType": {
      "abstract": [
        {
          "text": "Specifies the source type associated with a particular media source. Source type reflects the primary type of media within the source. These constants are used to specify values for ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadSourceTypesKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " in the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLibrary/init(options:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLibrary",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaSourceType"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaSourceType"
        }
      ],
      "role": "symbol",
      "title": "MLMediaSourceType",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediasourcetype"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/final-cut-pro-media-group-type-identifiers": {
      "abstract": [
        {
          "text": "Identifiers for media group types in the Final Cut Pro media source. These constants are used to specify a media group’s ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/typeIdentifier",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " attribute.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/final-cut-pro-media-group-type-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Final Cut Pro Media Group Type Identifiers",
      "type": "topic",
      "url": "/documentation/medialibrary/final-cut-pro-media-group-type-identifiers"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/folders-media-group-type-identifiers": {
      "abstract": [
        {
          "text": "Identifiers for media group types in folder-based media sources. These constants are used to specify a media group’s ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/typeIdentifier",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " attribute.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/folders-media-group-type-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Folders Media Group Type Identifiers",
      "type": "topic",
      "url": "/documentation/medialibrary/folders-media-group-type-identifiers"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/garageband-media-group-type-identifiers": {
      "abstract": [
        {
          "text": "Identifiers for media group types in the GarageBand media source. These constants are used to specify a media group’s ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/typeIdentifier",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " attribute.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/garageband-media-group-type-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GarageBand Media Group Type Identifiers",
      "type": "topic",
      "url": "/documentation/medialibrary/garageband-media-group-type-identifiers"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/logic-media-group-type-identifiers": {
      "abstract": [
        {
          "text": "Identifiers for media group types in the Logic media source. These constants are used to specify a media group’s ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/typeIdentifier",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " attribute.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/logic-media-group-type-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Logic Media Group Type Identifiers",
      "type": "topic",
      "url": "/documentation/medialibrary/logic-media-group-type-identifiers"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/media-source-identifiers": {
      "abstract": [
        {
          "text": "Identifiers for media sources which correspond to apps used to manage groups of media objects. Used with ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/load-options-keys",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/media-source-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Media Source Identifiers",
      "type": "topic",
      "url": "/documentation/medialibrary/media-source-identifiers"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/medialibrary-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/medialibrary-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MediaLibrary Constants",
      "type": "topic",
      "url": "/documentation/medialibrary/medialibrary-constants"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/well-known-folder-identifiers": {
      "abstract": [
        {
          "text": "Identifiers for well-known media folders used to specify the value for ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadFoldersKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/well-known-folder-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Well-Known Folder Identifiers",
      "type": "topic",
      "url": "/documentation/medialibrary/well-known-folder-identifiers"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.medialibrary/documentation/MediaLibrary/final-cut-pro-media-group-type-identifiers",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/folders-media-group-type-identifiers",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/garageband-media-group-type-identifiers",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/logic-media-group-type-identifiers",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppFoldersKey",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppleLoops",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadExcludeSourcesKey",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadFoldersKey",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadIncludeSourcesKey",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadMoviesFolder",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadSourceTypesKey",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceApertureIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceAppDefinedFoldersIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceCustomFoldersIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceFinalCutIdentifier"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureRootGroupTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureUserAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureUserSmartAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureProjectAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureFolderAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureProjectFolderAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureAllProjectsTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureAllPhotosTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureLastViewedEventAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureLastImportAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureLastNMonthsAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureFlaggedTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureLightTableTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureSlideShowTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLAperturePhotoStreamAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureFacesAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLAperturePlacesAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLAperturePlacesCountryAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLAperturePlacesProvinceAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLAperturePlacesCityAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLAperturePlacesPointOfInterestAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureFacebookAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureFacebookGroupTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureFlickrAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureFlickrGroupTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureSmugMugAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureSmugMugGroupTypeIdentifier"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureRootGroupTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureUserAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureUserSmartAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureProjectAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureFolderAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureProjectFolderAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureAllProjectsTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureAllPhotosTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureLastViewedEventAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureLastImportAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureLastNMonthsAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureFlaggedTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureLightTableTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureSlideShowTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLAperturePhotoStreamAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureFacesAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLAperturePlacesAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLAperturePlacesCountryAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLAperturePlacesProvinceAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLAperturePlacesCityAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLAperturePlacesPointOfInterestAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureFacebookAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureFacebookGroupTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureFlickrAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureFlickrGroupTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureSmugMugAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureSmugMugGroupTypeIdentifier"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.medialibrary/documentation/MediaLibrary/final-cut-pro-media-group-type-identifiers",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/folders-media-group-type-identifiers",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/garageband-media-group-type-identifiers",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/logic-media-group-type-identifiers",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppFoldersKey",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppleLoops",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadExcludeSourcesKey",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadFoldersKey",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadIncludeSourcesKey",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadMoviesFolder",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadSourceTypesKey",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceApertureIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceAppDefinedFoldersIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceCustomFoldersIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceFinalCutIdentifier"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceType/title",
          "value": "MLMediaSourceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaSourceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaSourceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureSmugMugAlbumTypeIdentifier/title",
          "value": "MLApertureSmugMugAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureSmugMugAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLApertureSmugMugAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceCustomFoldersIdentifier/title",
          "value": "MLMediaSourceCustomFoldersIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceCustomFoldersIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaSourceCustomFoldersIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadAppFoldersKey/title",
          "value": "MLMediaLoadAppFoldersKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadAppFoldersKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaLoadAppFoldersKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureSmugMugGroupTypeIdentifier/title",
          "value": "MLApertureSmugMugGroupTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureSmugMugGroupTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLApertureSmugMugGroupTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLAperturePhotoStreamAlbumTypeIdentifier/title",
          "value": "MLAperturePhotoStreamAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLAperturePhotoStreamAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLAperturePhotoStreamAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLAperturePlacesCityAlbumTypeIdentifier/title",
          "value": "MLAperturePlacesCityAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLAperturePlacesCityAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLAperturePlacesCityAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadSourceTypesKey/title",
          "value": "MLMediaLoadSourceTypesKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadSourceTypesKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaLoadSourceTypesKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureRootGroupTypeIdentifier/title",
          "value": "MLApertureRootGroupTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureRootGroupTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLApertureRootGroupTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureProjectFolderAlbumTypeIdentifier/title",
          "value": "MLApertureProjectFolderAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureProjectFolderAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLApertureProjectFolderAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureFolderAlbumTypeIdentifier/title",
          "value": "MLApertureFolderAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureFolderAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLApertureFolderAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureFacebookAlbumTypeIdentifier/title",
          "value": "MLApertureFacebookAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureFacebookAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLApertureFacebookAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadAppleLoops/title",
          "value": "MLMediaLoadAppleLoops"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadAppleLoops/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaLoadAppleLoops"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceAppDefinedFoldersIdentifier/title",
          "value": "MLMediaSourceAppDefinedFoldersIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceAppDefinedFoldersIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaSourceAppDefinedFoldersIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureUserSmartAlbumTypeIdentifier/title",
          "value": "MLApertureUserSmartAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureUserSmartAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLApertureUserSmartAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLAperturePlacesAlbumTypeIdentifier/title",
          "value": "MLAperturePlacesAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLAperturePlacesAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLAperturePlacesAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadIncludeSourcesKey/title",
          "value": "MLMediaLoadIncludeSourcesKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadIncludeSourcesKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaLoadIncludeSourcesKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureFacesAlbumTypeIdentifier/title",
          "value": "MLApertureFacesAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureFacesAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLApertureFacesAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceApertureIdentifier/title",
          "value": "MLMediaSourceApertureIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceApertureIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaSourceApertureIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLAperturePlacesCountryAlbumTypeIdentifier/title",
          "value": "MLAperturePlacesCountryAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLAperturePlacesCountryAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLAperturePlacesCountryAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureAllProjectsTypeIdentifier/title",
          "value": "MLApertureAllProjectsTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureAllProjectsTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLApertureAllProjectsTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureFacebookGroupTypeIdentifier/title",
          "value": "MLApertureFacebookGroupTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureFacebookGroupTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLApertureFacebookGroupTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureFlickrAlbumTypeIdentifier/title",
          "value": "MLApertureFlickrAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureFlickrAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLApertureFlickrAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureLastViewedEventAlbumTypeIdentifier/title",
          "value": "MLApertureLastViewedEventAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureLastViewedEventAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLApertureLastViewedEventAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureFlaggedTypeIdentifier/title",
          "value": "MLApertureFlaggedTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureFlaggedTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLApertureFlaggedTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureLightTableTypeIdentifier/title",
          "value": "MLApertureLightTableTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureLightTableTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLApertureLightTableTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureLastNMonthsAlbumTypeIdentifier/title",
          "value": "MLApertureLastNMonthsAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureLastNMonthsAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLApertureLastNMonthsAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureLastImportAlbumTypeIdentifier/title",
          "value": "MLApertureLastImportAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureLastImportAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLApertureLastImportAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLAperturePlacesPointOfInterestAlbumTypeIdentifier/title",
          "value": "MLAperturePlacesPointOfInterestAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLAperturePlacesPointOfInterestAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLAperturePlacesPointOfInterestAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadExcludeSourcesKey/title",
          "value": "MLMediaLoadExcludeSourcesKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadExcludeSourcesKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaLoadExcludeSourcesKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureFlickrGroupTypeIdentifier/title",
          "value": "MLApertureFlickrGroupTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureFlickrGroupTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLApertureFlickrGroupTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadFoldersKey/title",
          "value": "MLMediaLoadFoldersKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadFoldersKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaLoadFoldersKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceFinalCutIdentifier/title",
          "value": "MLMediaSourceFinalCutIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceFinalCutIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaSourceFinalCutIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLAperturePlacesProvinceAlbumTypeIdentifier/title",
          "value": "MLAperturePlacesProvinceAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLAperturePlacesProvinceAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLAperturePlacesProvinceAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadMoviesFolder/title",
          "value": "MLMediaLoadMoviesFolder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadMoviesFolder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaLoadMoviesFolder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureAllPhotosTypeIdentifier/title",
          "value": "MLApertureAllPhotosTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureAllPhotosTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLApertureAllPhotosTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureProjectAlbumTypeIdentifier/title",
          "value": "MLApertureProjectAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureProjectAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLApertureProjectAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureSlideShowTypeIdentifier/title",
          "value": "MLApertureSlideShowTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureSlideShowTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLApertureSlideShowTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureUserAlbumTypeIdentifier/title",
          "value": "MLApertureUserAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureUserAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLApertureUserAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaGroup~1typeIdentifier/title",
          "value": "typeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaGroup~1typeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "typeIdentifier"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/medialibrary/aperture-media-group-type-identifiers"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/medialibrary/aperture-media-group-type-identifiers"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
