{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.medialibrary/documentation/MediaLibrary/garageband-media-group-type-identifiers"},"kind":"article","topicSections":[{"title":"Constants","anchor":"Constants","identifiers":["doc://com.apple.medialibrary/documentation/MediaLibrary/MLGarageBandRootGroupTypeIdentifier","doc://com.apple.medialibrary/documentation/MediaLibrary/MLGarageBandFolderGroupTypeIdentifier"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/medialibrary/garageband-media-group-type-identifiers"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/medialibrary/garageband-media-group-type-identifiers"]}],"sections":[],"metadata":{"modules":[{"name":"Media Library"}],"title":"GarageBand Media Group Type Identifiers","roleHeading":"API Collection","role":"collectionGroup"},"abstract":[{"text":"Identifiers for media group types in the GarageBand media source. These constants are used to specify a media group’s ","type":"text"},{"type":"reference","identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/typeIdentifier","isActive":true},{"text":" attribute.","type":"text"}],"seeAlsoSections":[{"title":"Constants","identifiers":["doc://com.apple.medialibrary/documentation/MediaLibrary/aperture-media-group-type-identifiers","doc://com.apple.medialibrary/documentation/MediaLibrary/final-cut-pro-media-group-type-identifiers","doc://com.apple.medialibrary/documentation/MediaLibrary/folders-media-group-type-identifiers","doc://com.apple.medialibrary/documentation/MediaLibrary/logic-media-group-type-identifiers","doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppFoldersKey","doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppleLoops","doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadExcludeSourcesKey","doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadFoldersKey","doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadIncludeSourcesKey","doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadMoviesFolder","doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadSourceTypesKey","doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceApertureIdentifier","doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceAppDefinedFoldersIdentifier","doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceCustomFoldersIdentifier","doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceFinalCutIdentifier"],"anchor":"Constants","generated":true}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.medialibrary/documentation/MediaLibrary","doc://com.apple.medialibrary/documentation/MediaLibrary/medialibrary-constants"]]},"references":{"doc://com.apple.medialibrary/documentation/MediaLibrary/MLGarageBandFolderGroupTypeIdentifier":{"navigatorTitle":[{"kind":"identifier","text":"MLGarageBandFolderGroupTypeIdentifier"}],"url":"/documentation/medialibrary/mlgaragebandfoldergrouptypeidentifier","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"MLGarageBandFolderGroupTypeIdentifier","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","abstract":[{"type":"text","text":"A media group that represents a folder in GarageBand."}],"identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/MLGarageBandFolderGroupTypeIdentifier","title":"MLGarageBandFolderGroupTypeIdentifier","kind":"symbol"},"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadMoviesFolder":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"MLMediaLoadMoviesFolder"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadMoviesFolder","title":"MLMediaLoadMoviesFolder","abstract":[{"text":"Identifies the user’s Movies folder.","type":"text"}],"url":"/documentation/medialibrary/mlmedialoadmoviesfolder","role":"symbol","navigatorTitle":[{"text":"MLMediaLoadMoviesFolder","kind":"identifier"}]},"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppFoldersKey":{"identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppFoldersKey","kind":"symbol","role":"symbol","type":"topic","url":"/documentation/medialibrary/mlmedialoadappfolderskey","abstract":[{"type":"text","text":"Specifies one or more relative paths inside the caller’s app bundle in which to search for media files. The value for this key is an array of strings (relative paths inside the caller’s app bundle)."}],"navigatorTitle":[{"text":"MLMediaLoadAppFoldersKey","kind":"identifier"}],"title":"MLMediaLoadAppFoldersKey","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MLMediaLoadAppFoldersKey","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://com.apple.medialibrary/documentation/MediaLibrary/folders-media-group-type-identifiers":{"identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/folders-media-group-type-identifiers","kind":"article","role":"collectionGroup","type":"topic","url":"/documentation/medialibrary/folders-media-group-type-identifiers","abstract":[{"text":"Identifiers for media group types in folder-based media sources. These constants are used to specify a media group’s ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/typeIdentifier"},{"text":" attribute.","type":"text"}],"title":"Folders Media Group Type Identifiers"},"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceType":{"identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceType","kind":"symbol","role":"symbol","type":"topic","url":"/documentation/medialibrary/mlmediasourcetype","abstract":[{"text":"Specifies the source type associated with a particular media source. Source type reflects the primary type of media within the source. These constants are used to specify values for ","type":"text"},{"type":"reference","identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadSourceTypesKey","isActive":true},{"text":" in the ","type":"text"},{"type":"reference","identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLibrary/init(options:)","isActive":true},{"text":" method of ","type":"text"},{"type":"reference","identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLibrary","isActive":true},{"text":".","type":"text"}],"navigatorTitle":[{"text":"MLMediaSourceType","kind":"identifier"}],"title":"MLMediaSourceType","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MLMediaSourceType","kind":"identifier"}]},"doc://com.apple.medialibrary/documentation/MediaLibrary/aperture-media-group-type-identifiers":{"identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/aperture-media-group-type-identifiers","kind":"article","role":"collectionGroup","type":"topic","url":"/documentation/medialibrary/aperture-media-group-type-identifiers","abstract":[{"text":"Identifiers for media group types in the Aperture media source. These constants are used to specify a media group’s ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/typeIdentifier"},{"text":" attribute.","type":"text"}],"title":"Aperture Media Group Type Identifiers"},"doc://com.apple.medialibrary/documentation/MediaLibrary/MLGarageBandRootGroupTypeIdentifier":{"type":"topic","url":"/documentation/medialibrary/mlgaragebandrootgrouptypeidentifier","identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/MLGarageBandRootGroupTypeIdentifier","kind":"symbol","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MLGarageBandRootGroupTypeIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"MLGarageBandRootGroupTypeIdentifier"}],"abstract":[{"text":"The root media group for GarageBand.","type":"text"}],"title":"MLGarageBandRootGroupTypeIdentifier"},"doc://com.apple.medialibrary/documentation/MediaLibrary/medialibrary-constants":{"url":"/documentation/medialibrary/medialibrary-constants","type":"topic","title":"MediaLibrary Constants","role":"collectionGroup","kind":"article","identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/medialibrary-constants","abstract":[]},"doc://com.apple.medialibrary/documentation/MediaLibrary":{"kind":"symbol","title":"Media Library","abstract":[{"type":"text","text":"Access read-only collections of the user’s multimedia content."}],"type":"topic","deprecated":true,"url":"/documentation/medialibrary","identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary","role":"collection"},"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceApertureIdentifier":{"role":"symbol","identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceApertureIdentifier","url":"/documentation/medialibrary/mlmediasourceapertureidentifier","abstract":[{"text":"The media source providing content from Aperture.","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"MLMediaSourceApertureIdentifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"title":"MLMediaSourceApertureIdentifier","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MLMediaSourceApertureIdentifier"}],"kind":"symbol"},"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceAppDefinedFoldersIdentifier":{"title":"MLMediaSourceAppDefinedFoldersIdentifier","identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceAppDefinedFoldersIdentifier","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"MLMediaSourceAppDefinedFoldersIdentifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[{"text":"The media source for app-defined folders. This identifies a media source created from a relative path inside the caller’s app bundle. This source provides data when ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppFoldersKey"},{"text":" is provided in the options.","type":"text"}],"navigatorTitle":[{"text":"MLMediaSourceAppDefinedFoldersIdentifier","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","url":"/documentation/medialibrary/mlmediasourceappdefinedfoldersidentifier"},"doc://com.apple.medialibrary/documentation/MediaLibrary/well-known-folder-identifiers":{"role":"collectionGroup","abstract":[{"text":"Identifiers for well-known media folders used to specify the value for ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadFoldersKey"},{"text":".","type":"text"}],"identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/well-known-folder-identifiers","url":"/documentation/medialibrary/well-known-folder-identifiers","kind":"article","title":"Well-Known Folder Identifiers","type":"topic"},"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/typeIdentifier":{"url":"/documentation/medialibrary/mlmediagroup/typeidentifier","abstract":[{"text":"An identifier for the media group’s type.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"typeIdentifier"}],"identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/typeIdentifier","title":"typeIdentifier","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"typeIdentifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]},"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceFinalCutIdentifier":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"MLMediaSourceFinalCutIdentifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceFinalCutIdentifier","title":"MLMediaSourceFinalCutIdentifier","abstract":[{"text":"The media source providing content from Final Cut Pro.","type":"text"}],"url":"/documentation/medialibrary/mlmediasourcefinalcutidentifier","role":"symbol","navigatorTitle":[{"text":"MLMediaSourceFinalCutIdentifier","kind":"identifier"}]},"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppleLoops":{"url":"/documentation/medialibrary/mlmedialoadappleloops","abstract":[{"text":"Identifies the folder containing audio loops from Apple.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MLMediaLoadAppleLoops"}],"identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppleLoops","title":"MLMediaLoadAppleLoops","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MLMediaLoadAppleLoops"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]},"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadFoldersKey":{"title":"MLMediaLoadFoldersKey","identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadFoldersKey","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"MLMediaLoadFoldersKey","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Specifies the well-known folders that should be searched for media files. If this key is not present, none of the well-known folders will be provided. The value for this key is an array of strings (identifiers that correspond to well-known folder locations). For a list of well-known folder identifiers, see "},{"type":"reference","identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/well-known-folder-identifiers","isActive":true},{"type":"text","text":"."}],"navigatorTitle":[{"text":"MLMediaLoadFoldersKey","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","url":"/documentation/medialibrary/mlmedialoadfolderskey"},"doc://com.apple.medialibrary/documentation/MediaLibrary/media-source-identifiers":{"identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/media-source-identifiers","kind":"article","role":"collectionGroup","type":"topic","url":"/documentation/medialibrary/media-source-identifiers","abstract":[{"text":"Identifiers for media sources which correspond to apps used to manage groups of media objects. Used with ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/load-options-keys"},{"text":".","type":"text"}],"title":"Media Source Identifiers"},"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadIncludeSourcesKey":{"url":"/documentation/medialibrary/mlmedialoadincludesourceskey","abstract":[{"type":"text","text":"Defines which media sources to include when loading. If not present, load all available media sources. This option is processed after "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadSourceTypesKey"},{"type":"text","text":". If "},{"identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadIncludeSourcesKey","isActive":true,"type":"reference"},{"text":" is present but ","type":"text"},{"identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadSourceTypesKey","isActive":true,"type":"reference"},{"text":" is not, then only those sources specified here will be loaded. This is useful for loading a single media source. When both keys are present, this is useful for adding one or more media sources that normally would not appear for the requested library type. The value for this key is an array of strings (media source identifiers). For a list of valid media source identifiers, see ","type":"text"},{"identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/media-source-identifiers","isActive":true,"type":"reference"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"MLMediaLoadIncludeSourcesKey","kind":"identifier"}],"identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadIncludeSourcesKey","title":"MLMediaLoadIncludeSourcesKey","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MLMediaLoadIncludeSourcesKey","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"identifier":"doc://com.apple.documentation/documentation/technologies","kind":"technologies","type":"topic","role":"overview"},"doc://com.apple.medialibrary/documentation/MediaLibrary/final-cut-pro-media-group-type-identifiers":{"title":"Final Cut Pro Media Group Type Identifiers","identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/final-cut-pro-media-group-type-identifiers","abstract":[{"type":"text","text":"Identifiers for media group types in the Final Cut Pro media source. These constants are used to specify a media group’s "},{"type":"reference","identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/typeIdentifier","isActive":true},{"type":"text","text":" attribute."}],"type":"topic","kind":"article","role":"collectionGroup","url":"/documentation/medialibrary/final-cut-pro-media-group-type-identifiers"},"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceCustomFoldersIdentifier":{"identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceCustomFoldersIdentifier","kind":"symbol","navigatorTitle":[{"text":"MLMediaSourceCustomFoldersIdentifier","kind":"identifier"}],"type":"topic","url":"/documentation/medialibrary/mlmediasourcecustomfoldersidentifier","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MLMediaSourceCustomFoldersIdentifier","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"MLMediaSourceCustomFoldersIdentifier","abstract":[{"text":"The media source for custom folders. Currently, the only custom folder is the folder containing audio loops from Apple. This source provides data when ","type":"text"},{"identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadFoldersKey","type":"reference","isActive":true},{"text":" is provided with the ","type":"text"},{"identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppleLoops","type":"reference","isActive":true},{"text":" value.","type":"text"}]},"doc://com.apple.medialibrary/documentation/MediaLibrary/logic-media-group-type-identifiers":{"identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/logic-media-group-type-identifiers","kind":"article","role":"collectionGroup","type":"topic","url":"/documentation/medialibrary/logic-media-group-type-identifiers","abstract":[{"type":"text","text":"Identifiers for media group types in the Logic media source. These constants are used to specify a media group’s "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/typeIdentifier"},{"type":"text","text":" attribute."}],"title":"Logic Media Group Type Identifiers"},"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadExcludeSourcesKey":{"identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadExcludeSourcesKey","kind":"symbol","role":"symbol","type":"topic","url":"/documentation/medialibrary/mlmedialoadexcludesourceskey","abstract":[{"text":"Defines which media sources to exclude when loading. This option is processed after ","type":"text"},{"identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadIncludeSourcesKey","isActive":true,"type":"reference"},{"text":". The value for this key is an array of strings (media source identifiers). For a list of valid media source identifiers, see ","type":"text"},{"identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/media-source-identifiers","isActive":true,"type":"reference"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"MLMediaLoadExcludeSourcesKey","kind":"identifier"}],"title":"MLMediaLoadExcludeSourcesKey","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"MLMediaLoadExcludeSourcesKey","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadSourceTypesKey":{"identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadSourceTypesKey","kind":"symbol","role":"symbol","type":"topic","url":"/documentation/medialibrary/mlmedialoadsourcetypeskey","abstract":[{"text":"Defines which sources to load based on library type. If not present, this will load all sources. The value for this key is a media source type. For a list of valid media source types, see ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceType"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"MLMediaLoadSourceTypesKey","kind":"identifier"}],"title":"MLMediaLoadSourceTypesKey","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"MLMediaLoadSourceTypesKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"title":"Constants","anchor":"Constants","identifiers":["doc://com.apple.medialibrary/documentation/MediaLibrary/MLGarageBandRootGroupTypeIdentifier","doc://com.apple.medialibrary/documentation/MediaLibrary/MLGarageBandFolderGroupTypeIdentifier"]}],"op":"replace","path":"/topicSections"},{"value":[{"generated":true,"identifiers":["doc://com.apple.medialibrary/documentation/MediaLibrary/aperture-media-group-type-identifiers","doc://com.apple.medialibrary/documentation/MediaLibrary/final-cut-pro-media-group-type-identifiers","doc://com.apple.medialibrary/documentation/MediaLibrary/folders-media-group-type-identifiers","doc://com.apple.medialibrary/documentation/MediaLibrary/logic-media-group-type-identifiers","doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppFoldersKey","doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppleLoops","doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadExcludeSourcesKey","doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadFoldersKey","doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadIncludeSourcesKey","doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadMoviesFolder","doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadSourceTypesKey","doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceApertureIdentifier","doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceAppDefinedFoldersIdentifier","doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceCustomFoldersIdentifier","doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceFinalCutIdentifier"],"title":"Constants","anchor":"Constants"}],"op":"replace","path":"/seeAlsoSections"},{"path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLGarageBandFolderGroupTypeIdentifier/title","op":"replace","value":"MLGarageBandFolderGroupTypeIdentifier"},{"path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLGarageBandFolderGroupTypeIdentifier/fragments","op":"replace","value":[{"text":"MLGarageBandFolderGroupTypeIdentifier","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadMoviesFolder/title","op":"replace","value":"MLMediaLoadMoviesFolder"},{"path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadMoviesFolder/fragments","op":"replace","value":[{"text":"MLMediaLoadMoviesFolder","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadAppFoldersKey/title","op":"replace","value":"MLMediaLoadAppFoldersKey"},{"path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadAppFoldersKey/fragments","op":"replace","value":[{"kind":"identifier","text":"MLMediaLoadAppFoldersKey"}]},{"path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceType/title","op":"replace","value":"MLMediaSourceType"},{"value":[{"text":"MLMediaSourceType","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceType/fragments"},{"value":[{"text":"MLMediaSourceType","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceType/navigatorTitle"},{"value":"MLGarageBandRootGroupTypeIdentifier","op":"replace","path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLGarageBandRootGroupTypeIdentifier/title"},{"value":[{"kind":"identifier","text":"MLGarageBandRootGroupTypeIdentifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLGarageBandRootGroupTypeIdentifier/fragments"},{"value":"MLMediaSourceApertureIdentifier","op":"replace","path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceApertureIdentifier/title"},{"value":[{"text":"MLMediaSourceApertureIdentifier","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceApertureIdentifier/fragments"},{"value":"MLMediaSourceAppDefinedFoldersIdentifier","op":"replace","path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceAppDefinedFoldersIdentifier/title"},{"value":[{"text":"MLMediaSourceAppDefinedFoldersIdentifier","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceAppDefinedFoldersIdentifier/fragments"},{"value":"typeIdentifier","op":"replace","path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaGroup~1typeIdentifier/title"},{"value":[{"kind":"identifier","text":"typeIdentifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaGroup~1typeIdentifier/fragments"},{"value":"MLMediaSourceFinalCutIdentifier","op":"replace","path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceFinalCutIdentifier/title"},{"value":[{"text":"MLMediaSourceFinalCutIdentifier","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceFinalCutIdentifier/fragments"},{"value":"MLMediaLoadAppleLoops","op":"replace","path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadAppleLoops/title"},{"value":[{"kind":"identifier","text":"MLMediaLoadAppleLoops"}],"op":"replace","path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadAppleLoops/fragments"},{"value":"MLMediaLoadFoldersKey","op":"replace","path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadFoldersKey/title"},{"value":[{"kind":"identifier","text":"MLMediaLoadFoldersKey"}],"op":"replace","path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadFoldersKey/fragments"},{"value":"MLMediaLoadIncludeSourcesKey","op":"replace","path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadIncludeSourcesKey/title"},{"value":[{"text":"MLMediaLoadIncludeSourcesKey","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadIncludeSourcesKey/fragments"},{"value":"MLMediaSourceCustomFoldersIdentifier","op":"replace","path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceCustomFoldersIdentifier/title"},{"value":[{"text":"MLMediaSourceCustomFoldersIdentifier","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceCustomFoldersIdentifier/fragments"},{"value":"MLMediaLoadExcludeSourcesKey","op":"replace","path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadExcludeSourcesKey/title"},{"value":[{"kind":"identifier","text":"MLMediaLoadExcludeSourcesKey"}],"op":"replace","path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadExcludeSourcesKey/fragments"},{"value":"MLMediaLoadSourceTypesKey","op":"replace","path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadSourceTypesKey/title"},{"value":[{"text":"MLMediaLoadSourceTypesKey","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadSourceTypesKey/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}