{
  "abstract": [
    {
      "text": "Identifiers for media group types in the iPhoto media source. These constants are used to specify a media group’s ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/typeIdentifier",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " attribute.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.medialibrary/documentation/MediaLibrary",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/medialibrary-constants"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.medialibrary/documentation/MediaLibrary/iphoto-media-group-type-identifiers"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Media Library"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "iPhoto Media Group Type Identifiers"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary": {
      "abstract": [
        {
          "text": "Access read-only collections of the user’s multimedia content.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Library",
      "type": "topic",
      "url": "/documentation/medialibrary"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/typeIdentifier": {
      "abstract": [
        {
          "text": "An identifier for the media group’s type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "typeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/typeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "typeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "typeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediagroup/typeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppFoldersKey": {
      "abstract": [
        {
          "text": "Specifies one or more relative paths inside the caller’s app bundle in which to search for media files. The value for this key is an array of strings (relative paths inside the caller’s app bundle).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaLoadAppFoldersKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppFoldersKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaLoadAppFoldersKey"
        }
      ],
      "role": "symbol",
      "title": "MLMediaLoadAppFoldersKey",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmedialoadappfolderskey"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppleLoops": {
      "abstract": [
        {
          "text": "Identifies the folder containing audio loops from Apple.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaLoadAppleLoops"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppleLoops",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaLoadAppleLoops"
        }
      ],
      "role": "symbol",
      "title": "MLMediaLoadAppleLoops",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmedialoadappleloops"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadExcludeSourcesKey": {
      "abstract": [
        {
          "text": "Defines which media sources to exclude when loading. This option is processed after ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadIncludeSourcesKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ". The value for this key is an array of strings (media source identifiers). For a list of valid media source identifiers, see ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/media-source-identifiers",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaLoadExcludeSourcesKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadExcludeSourcesKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaLoadExcludeSourcesKey"
        }
      ],
      "role": "symbol",
      "title": "MLMediaLoadExcludeSourcesKey",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmedialoadexcludesourceskey"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadFoldersKey": {
      "abstract": [
        {
          "text": "Specifies the well-known folders that should be searched for media files. If this key is not present, none of the well-known folders will be provided. The value for this key is an array of strings (identifiers that correspond to well-known folder locations). For a list of well-known folder identifiers, see ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/well-known-folder-identifiers",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaLoadFoldersKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadFoldersKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaLoadFoldersKey"
        }
      ],
      "role": "symbol",
      "title": "MLMediaLoadFoldersKey",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmedialoadfolderskey"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadIncludeSourcesKey": {
      "abstract": [
        {
          "text": "Defines which media sources to include when loading. If not present, load all available media sources. This option is processed after ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadSourceTypesKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ". If ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadIncludeSourcesKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " is present but ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadSourceTypesKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " is not, then only those sources specified here will be loaded. This is useful for loading a single media source. When both keys are present, this is useful for adding one or more media sources that normally would not appear for the requested library type. The value for this key is an array of strings (media source identifiers). For a list of valid media source identifiers, see ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/media-source-identifiers",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaLoadIncludeSourcesKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadIncludeSourcesKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaLoadIncludeSourcesKey"
        }
      ],
      "role": "symbol",
      "title": "MLMediaLoadIncludeSourcesKey",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmedialoadincludesourceskey"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadMoviesFolder": {
      "abstract": [
        {
          "text": "Identifies the user’s Movies folder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaLoadMoviesFolder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadMoviesFolder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaLoadMoviesFolder"
        }
      ],
      "role": "symbol",
      "title": "MLMediaLoadMoviesFolder",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmedialoadmoviesfolder"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadSourceTypesKey": {
      "abstract": [
        {
          "text": "Defines which sources to load based on library type. If not present, this will load all sources. The value for this key is a media source type. For a list of valid media source types, see ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceType",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaLoadSourceTypesKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadSourceTypesKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaLoadSourceTypesKey"
        }
      ],
      "role": "symbol",
      "title": "MLMediaLoadSourceTypesKey",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmedialoadsourcetypeskey"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceApertureIdentifier": {
      "abstract": [
        {
          "text": "The media source providing content from Aperture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaSourceApertureIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceApertureIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaSourceApertureIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLMediaSourceApertureIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediasourceapertureidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceAppDefinedFoldersIdentifier": {
      "abstract": [
        {
          "text": "The media source for app-defined folders. This identifies a media source created from a relative path inside the caller’s app bundle. This source provides data when ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppFoldersKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " is provided in the options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaSourceAppDefinedFoldersIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceAppDefinedFoldersIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaSourceAppDefinedFoldersIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLMediaSourceAppDefinedFoldersIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediasourceappdefinedfoldersidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceCustomFoldersIdentifier": {
      "abstract": [
        {
          "text": "The media source for custom folders. Currently, the only custom folder is the folder containing audio loops from Apple. This source provides data when ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadFoldersKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " is provided with the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppleLoops",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaSourceCustomFoldersIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceCustomFoldersIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaSourceCustomFoldersIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLMediaSourceCustomFoldersIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediasourcecustomfoldersidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceType": {
      "abstract": [
        {
          "text": "Specifies the source type associated with a particular media source. Source type reflects the primary type of media within the source. These constants are used to specify values for ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadSourceTypesKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " in the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLibrary/init(options:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLibrary",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaSourceType"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaSourceType"
        }
      ],
      "role": "symbol",
      "title": "MLMediaSourceType",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediasourcetype"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents an album in iPhoto.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiPhotoAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiPhotoAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiPhotoAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mliphotoalbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoEventAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents an event in iPhoto.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiPhotoEventAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoEventAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiPhotoEventAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiPhotoEventAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mliphotoeventalbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoEventsFolderTypeIdentifier": {
      "abstract": [
        {
          "text": "The media group that represents the Events album in iPhoto.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiPhotoEventsFolderTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoEventsFolderTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiPhotoEventsFolderTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiPhotoEventsFolderTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mliphotoeventsfoldertypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoFacebookAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a Facebook album that is visible in iPhoto.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiPhotoFacebookAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoFacebookAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiPhotoFacebookAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiPhotoFacebookAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mliphotofacebookalbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoFacebookGroupTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a Facebook user account in iPhoto. A Facebook user account contains one or more Facebook albums.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiPhotoFacebookGroupTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoFacebookGroupTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiPhotoFacebookGroupTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiPhotoFacebookGroupTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mliphotofacebookgrouptypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoFacesAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a Faces album in iPhoto. Individual Faces albums are nested in the main Faces album.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiPhotoFacesAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoFacesAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiPhotoFacesAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiPhotoFacesAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mliphotofacesalbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoFlaggedAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "The media group that represents the album of flagged media in iPhoto.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiPhotoFlaggedAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoFlaggedAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiPhotoFlaggedAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiPhotoFlaggedAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mliphotoflaggedalbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoFlickrAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a Flickr album that is visible in iPhoto.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiPhotoFlickrAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoFlickrAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiPhotoFlickrAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiPhotoFlickrAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mliphotoflickralbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoFlickrGroupTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a Flickr user account in iPhoto. A Flickr user account contains one or more Flickr albums.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiPhotoFlickrGroupTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoFlickrGroupTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiPhotoFlickrGroupTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiPhotoFlickrGroupTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mliphotoflickrgrouptypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoFolderAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a folder in iPhoto.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiPhotoFolderAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoFolderAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiPhotoFolderAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiPhotoFolderAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mliphotofolderalbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoLastImportAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "The media group that represents the Last Import album in iPhoto.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiPhotoLastImportAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoLastImportAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiPhotoLastImportAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiPhotoLastImportAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mliphotolastimportalbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoLastNMonthsAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "The media group that represents the recent content album in iPhoto, known as the Last ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "N",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " Months album. The value for ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "N",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " is usually 12 (settable in iPhoto > Preferences > General).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiPhotoLastNMonthsAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoLastNMonthsAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiPhotoLastNMonthsAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiPhotoLastNMonthsAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mliphotolastnmonthsalbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoLastViewedEventAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "The media group that represents the last viewed event in iPhoto.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiPhotoLastViewedEventAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoLastViewedEventAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiPhotoLastViewedEventAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiPhotoLastViewedEventAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mliphotolastviewedeventalbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoLibraryAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "The media group that represents the Photos album in iPhoto.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiPhotoLibraryAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoLibraryAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiPhotoLibraryAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiPhotoLibraryAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mliphotolibraryalbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoPhotoStreamAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a photo stream in iPhoto.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiPhotoPhotoStreamAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoPhotoStreamAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiPhotoPhotoStreamAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiPhotoPhotoStreamAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mliphotophotostreamalbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoPlacesAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "The media group that represents the Places album in iPhoto.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiPhotoPlacesAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoPlacesAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiPhotoPlacesAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiPhotoPlacesAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mliphotoplacesalbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoPlacesCityAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a Places album for a city in iPhoto. A city album is nested in a province or state album.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiPhotoPlacesCityAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoPlacesCityAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiPhotoPlacesCityAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiPhotoPlacesCityAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mliphotoplacescityalbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoPlacesCountryAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a Places album for a country or region in iPhoto. A country or region album is nested in the main Places album.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiPhotoPlacesCountryAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoPlacesCountryAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiPhotoPlacesCountryAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiPhotoPlacesCountryAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mliphotoplacescountryalbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoPlacesPointOfInterestAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a Places album for a point-of-interest in iPhoto. A point of interest album is nested in a city album.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiPhotoPlacesPointOfInterestAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoPlacesPointOfInterestAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiPhotoPlacesPointOfInterestAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiPhotoPlacesPointOfInterestAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mliphotoplacespointofinterestalbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoPlacesProvinceAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a Places album for a province or state in iPhoto. A province or state album is nested in a country or region album.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiPhotoPlacesProvinceAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoPlacesProvinceAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiPhotoPlacesProvinceAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiPhotoPlacesProvinceAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mliphotoplacesprovincealbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoRootGroupTypeIdentifier": {
      "abstract": [
        {
          "text": "The root media group for iPhoto.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiPhotoRootGroupTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoRootGroupTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiPhotoRootGroupTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiPhotoRootGroupTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mliphotorootgrouptypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoSlideShowAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a slideshow album in iPhoto.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiPhotoSlideShowAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoSlideShowAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiPhotoSlideShowAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiPhotoSlideShowAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mliphotoslideshowalbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoSmartAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a smart album in iPhoto.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiPhotoSmartAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoSmartAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiPhotoSmartAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiPhotoSmartAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mliphotosmartalbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoSubscribedAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a subscribed album in iPhoto.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiPhotoSubscribedAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoSubscribedAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiPhotoSubscribedAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiPhotoSubscribedAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mliphotosubscribedalbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/aperture-media-group-type-identifiers": {
      "abstract": [
        {
          "text": "Identifiers for media group types in the Aperture media source. These constants are used to specify a media group’s ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/typeIdentifier",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " attribute.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/aperture-media-group-type-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Aperture Media Group Type Identifiers",
      "type": "topic",
      "url": "/documentation/medialibrary/aperture-media-group-type-identifiers"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/final-cut-pro-media-group-type-identifiers": {
      "abstract": [
        {
          "text": "Identifiers for media group types in the Final Cut Pro media source. These constants are used to specify a media group’s ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/typeIdentifier",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " attribute.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/final-cut-pro-media-group-type-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Final Cut Pro Media Group Type Identifiers",
      "type": "topic",
      "url": "/documentation/medialibrary/final-cut-pro-media-group-type-identifiers"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/folders-media-group-type-identifiers": {
      "abstract": [
        {
          "text": "Identifiers for media group types in folder-based media sources. These constants are used to specify a media group’s ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/typeIdentifier",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " attribute.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/folders-media-group-type-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Folders Media Group Type Identifiers",
      "type": "topic",
      "url": "/documentation/medialibrary/folders-media-group-type-identifiers"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/garageband-media-group-type-identifiers": {
      "abstract": [
        {
          "text": "Identifiers for media group types in the GarageBand media source. These constants are used to specify a media group’s ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/typeIdentifier",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " attribute.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/garageband-media-group-type-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GarageBand Media Group Type Identifiers",
      "type": "topic",
      "url": "/documentation/medialibrary/garageband-media-group-type-identifiers"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/logic-media-group-type-identifiers": {
      "abstract": [
        {
          "text": "Identifiers for media group types in the Logic media source. These constants are used to specify a media group’s ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/typeIdentifier",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " attribute.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/logic-media-group-type-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Logic Media Group Type Identifiers",
      "type": "topic",
      "url": "/documentation/medialibrary/logic-media-group-type-identifiers"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/media-source-identifiers": {
      "abstract": [
        {
          "text": "Identifiers for media sources which correspond to apps used to manage groups of media objects. Used with ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/load-options-keys",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/media-source-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Media Source Identifiers",
      "type": "topic",
      "url": "/documentation/medialibrary/media-source-identifiers"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/medialibrary-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/medialibrary-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MediaLibrary Constants",
      "type": "topic",
      "url": "/documentation/medialibrary/medialibrary-constants"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/well-known-folder-identifiers": {
      "abstract": [
        {
          "text": "Identifiers for well-known media folders used to specify the value for ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadFoldersKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/well-known-folder-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Well-Known Folder Identifiers",
      "type": "topic",
      "url": "/documentation/medialibrary/well-known-folder-identifiers"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.medialibrary/documentation/MediaLibrary/aperture-media-group-type-identifiers",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/final-cut-pro-media-group-type-identifiers",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/folders-media-group-type-identifiers",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/garageband-media-group-type-identifiers",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/logic-media-group-type-identifiers",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppFoldersKey",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppleLoops",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadExcludeSourcesKey",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadFoldersKey",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadIncludeSourcesKey",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadMoviesFolder",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadSourceTypesKey",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceApertureIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceAppDefinedFoldersIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceCustomFoldersIdentifier"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoRootGroupTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoSmartAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoLibraryAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoFolderAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoEventAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoEventsFolderTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoLastViewedEventAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoLastImportAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoLastNMonthsAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoFlaggedAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoSubscribedAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoSlideShowAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoPhotoStreamAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoFacesAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoPlacesAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoPlacesCountryAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoPlacesProvinceAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoPlacesCityAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoPlacesPointOfInterestAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoFacebookAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoFacebookGroupTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoFlickrAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoFlickrGroupTypeIdentifier"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoRootGroupTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoSmartAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoLibraryAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoFolderAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoEventAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoEventsFolderTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoLastViewedEventAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoLastImportAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoLastNMonthsAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoFlaggedAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoSubscribedAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoSlideShowAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoPhotoStreamAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoFacesAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoPlacesAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoPlacesCountryAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoPlacesProvinceAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoPlacesCityAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoPlacesPointOfInterestAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoFacebookAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoFacebookGroupTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoFlickrAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoFlickrGroupTypeIdentifier"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.medialibrary/documentation/MediaLibrary/aperture-media-group-type-identifiers",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/final-cut-pro-media-group-type-identifiers",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/folders-media-group-type-identifiers",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/garageband-media-group-type-identifiers",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/logic-media-group-type-identifiers",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppFoldersKey",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppleLoops",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadExcludeSourcesKey",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadFoldersKey",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadIncludeSourcesKey",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadMoviesFolder",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadSourceTypesKey",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceApertureIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceAppDefinedFoldersIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceCustomFoldersIdentifier"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadAppleLoops/title",
          "value": "MLMediaLoadAppleLoops"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadAppleLoops/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaLoadAppleLoops"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoRootGroupTypeIdentifier/title",
          "value": "MLiPhotoRootGroupTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoRootGroupTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiPhotoRootGroupTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoLibraryAlbumTypeIdentifier/title",
          "value": "MLiPhotoLibraryAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoLibraryAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiPhotoLibraryAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadExcludeSourcesKey/title",
          "value": "MLMediaLoadExcludeSourcesKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadExcludeSourcesKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaLoadExcludeSourcesKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadAppFoldersKey/title",
          "value": "MLMediaLoadAppFoldersKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadAppFoldersKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaLoadAppFoldersKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoFolderAlbumTypeIdentifier/title",
          "value": "MLiPhotoFolderAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoFolderAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiPhotoFolderAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoPlacesPointOfInterestAlbumTypeIdentifier/title",
          "value": "MLiPhotoPlacesPointOfInterestAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoPlacesPointOfInterestAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiPhotoPlacesPointOfInterestAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoFacebookAlbumTypeIdentifier/title",
          "value": "MLiPhotoFacebookAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoFacebookAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiPhotoFacebookAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoLastImportAlbumTypeIdentifier/title",
          "value": "MLiPhotoLastImportAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoLastImportAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiPhotoLastImportAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoEventsFolderTypeIdentifier/title",
          "value": "MLiPhotoEventsFolderTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoEventsFolderTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiPhotoEventsFolderTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceAppDefinedFoldersIdentifier/title",
          "value": "MLMediaSourceAppDefinedFoldersIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceAppDefinedFoldersIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaSourceAppDefinedFoldersIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoSlideShowAlbumTypeIdentifier/title",
          "value": "MLiPhotoSlideShowAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoSlideShowAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiPhotoSlideShowAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoLastViewedEventAlbumTypeIdentifier/title",
          "value": "MLiPhotoLastViewedEventAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoLastViewedEventAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiPhotoLastViewedEventAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadIncludeSourcesKey/title",
          "value": "MLMediaLoadIncludeSourcesKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadIncludeSourcesKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaLoadIncludeSourcesKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoFacesAlbumTypeIdentifier/title",
          "value": "MLiPhotoFacesAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoFacesAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiPhotoFacesAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoPlacesCityAlbumTypeIdentifier/title",
          "value": "MLiPhotoPlacesCityAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoPlacesCityAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiPhotoPlacesCityAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoPlacesProvinceAlbumTypeIdentifier/title",
          "value": "MLiPhotoPlacesProvinceAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoPlacesProvinceAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiPhotoPlacesProvinceAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoFacebookGroupTypeIdentifier/title",
          "value": "MLiPhotoFacebookGroupTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoFacebookGroupTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiPhotoFacebookGroupTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadSourceTypesKey/title",
          "value": "MLMediaLoadSourceTypesKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadSourceTypesKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaLoadSourceTypesKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoLastNMonthsAlbumTypeIdentifier/title",
          "value": "MLiPhotoLastNMonthsAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoLastNMonthsAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiPhotoLastNMonthsAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoFlickrAlbumTypeIdentifier/title",
          "value": "MLiPhotoFlickrAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoFlickrAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiPhotoFlickrAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoSmartAlbumTypeIdentifier/title",
          "value": "MLiPhotoSmartAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoSmartAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiPhotoSmartAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceCustomFoldersIdentifier/title",
          "value": "MLMediaSourceCustomFoldersIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceCustomFoldersIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaSourceCustomFoldersIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoEventAlbumTypeIdentifier/title",
          "value": "MLiPhotoEventAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoEventAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiPhotoEventAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoPhotoStreamAlbumTypeIdentifier/title",
          "value": "MLiPhotoPhotoStreamAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoPhotoStreamAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiPhotoPhotoStreamAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaGroup~1typeIdentifier/title",
          "value": "typeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaGroup~1typeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "typeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoFlaggedAlbumTypeIdentifier/title",
          "value": "MLiPhotoFlaggedAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoFlaggedAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiPhotoFlaggedAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoPlacesCountryAlbumTypeIdentifier/title",
          "value": "MLiPhotoPlacesCountryAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoPlacesCountryAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiPhotoPlacesCountryAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoPlacesAlbumTypeIdentifier/title",
          "value": "MLiPhotoPlacesAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoPlacesAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiPhotoPlacesAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadFoldersKey/title",
          "value": "MLMediaLoadFoldersKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadFoldersKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaLoadFoldersKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceApertureIdentifier/title",
          "value": "MLMediaSourceApertureIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceApertureIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaSourceApertureIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoFlickrGroupTypeIdentifier/title",
          "value": "MLiPhotoFlickrGroupTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoFlickrGroupTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiPhotoFlickrGroupTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoAlbumTypeIdentifier/title",
          "value": "MLiPhotoAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiPhotoAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceType/title",
          "value": "MLMediaSourceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaSourceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaSourceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoSubscribedAlbumTypeIdentifier/title",
          "value": "MLiPhotoSubscribedAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoSubscribedAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiPhotoSubscribedAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadMoviesFolder/title",
          "value": "MLMediaLoadMoviesFolder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadMoviesFolder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaLoadMoviesFolder"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/medialibrary/iphoto-media-group-type-identifiers"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/medialibrary/iphoto-media-group-type-identifiers"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
