{
  "abstract": [
    {
      "text": "Identifiers for media group types in the iTunes media source. These constants are used to specify a media group’s ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/typeIdentifier",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " attribute.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.medialibrary/documentation/MediaLibrary",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/medialibrary-constants"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.medialibrary/documentation/MediaLibrary/itunes-media-group-type-identifiers"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Media Library"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "iTunes Media Group Type Identifiers"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary": {
      "abstract": [
        {
          "text": "Access read-only collections of the user’s multimedia content.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Library",
      "type": "topic",
      "url": "/documentation/medialibrary"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/typeIdentifier": {
      "abstract": [
        {
          "text": "An identifier for the media group’s type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "typeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/typeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "typeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "typeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediagroup/typeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppFoldersKey": {
      "abstract": [
        {
          "text": "Specifies one or more relative paths inside the caller’s app bundle in which to search for media files. The value for this key is an array of strings (relative paths inside the caller’s app bundle).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaLoadAppFoldersKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppFoldersKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaLoadAppFoldersKey"
        }
      ],
      "role": "symbol",
      "title": "MLMediaLoadAppFoldersKey",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmedialoadappfolderskey"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppleLoops": {
      "abstract": [
        {
          "text": "Identifies the folder containing audio loops from Apple.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaLoadAppleLoops"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppleLoops",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaLoadAppleLoops"
        }
      ],
      "role": "symbol",
      "title": "MLMediaLoadAppleLoops",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmedialoadappleloops"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadExcludeSourcesKey": {
      "abstract": [
        {
          "text": "Defines which media sources to exclude when loading. This option is processed after ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadIncludeSourcesKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ". The value for this key is an array of strings (media source identifiers). For a list of valid media source identifiers, see ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/media-source-identifiers",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaLoadExcludeSourcesKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadExcludeSourcesKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaLoadExcludeSourcesKey"
        }
      ],
      "role": "symbol",
      "title": "MLMediaLoadExcludeSourcesKey",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmedialoadexcludesourceskey"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadFoldersKey": {
      "abstract": [
        {
          "text": "Specifies the well-known folders that should be searched for media files. If this key is not present, none of the well-known folders will be provided. The value for this key is an array of strings (identifiers that correspond to well-known folder locations). For a list of well-known folder identifiers, see ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/well-known-folder-identifiers",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaLoadFoldersKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadFoldersKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaLoadFoldersKey"
        }
      ],
      "role": "symbol",
      "title": "MLMediaLoadFoldersKey",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmedialoadfolderskey"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadIncludeSourcesKey": {
      "abstract": [
        {
          "text": "Defines which media sources to include when loading. If not present, load all available media sources. This option is processed after ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadSourceTypesKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ". If ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadIncludeSourcesKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " is present but ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadSourceTypesKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " is not, then only those sources specified here will be loaded. This is useful for loading a single media source. When both keys are present, this is useful for adding one or more media sources that normally would not appear for the requested library type. The value for this key is an array of strings (media source identifiers). For a list of valid media source identifiers, see ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/media-source-identifiers",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaLoadIncludeSourcesKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadIncludeSourcesKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaLoadIncludeSourcesKey"
        }
      ],
      "role": "symbol",
      "title": "MLMediaLoadIncludeSourcesKey",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmedialoadincludesourceskey"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadMoviesFolder": {
      "abstract": [
        {
          "text": "Identifies the user’s Movies folder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaLoadMoviesFolder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadMoviesFolder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaLoadMoviesFolder"
        }
      ],
      "role": "symbol",
      "title": "MLMediaLoadMoviesFolder",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmedialoadmoviesfolder"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadSourceTypesKey": {
      "abstract": [
        {
          "text": "Defines which sources to load based on library type. If not present, this will load all sources. The value for this key is a media source type. For a list of valid media source types, see ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceType",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaLoadSourceTypesKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadSourceTypesKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaLoadSourceTypesKey"
        }
      ],
      "role": "symbol",
      "title": "MLMediaLoadSourceTypesKey",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmedialoadsourcetypeskey"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceApertureIdentifier": {
      "abstract": [
        {
          "text": "The media source providing content from Aperture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaSourceApertureIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceApertureIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaSourceApertureIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLMediaSourceApertureIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediasourceapertureidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceAppDefinedFoldersIdentifier": {
      "abstract": [
        {
          "text": "The media source for app-defined folders. This identifies a media source created from a relative path inside the caller’s app bundle. This source provides data when ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppFoldersKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " is provided in the options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaSourceAppDefinedFoldersIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceAppDefinedFoldersIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaSourceAppDefinedFoldersIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLMediaSourceAppDefinedFoldersIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediasourceappdefinedfoldersidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceCustomFoldersIdentifier": {
      "abstract": [
        {
          "text": "The media source for custom folders. Currently, the only custom folder is the folder containing audio loops from Apple. This source provides data when ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadFoldersKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " is provided with the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppleLoops",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaSourceCustomFoldersIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceCustomFoldersIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaSourceCustomFoldersIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLMediaSourceCustomFoldersIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediasourcecustomfoldersidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceType": {
      "abstract": [
        {
          "text": "Specifies the source type associated with a particular media source. Source type reflects the primary type of media within the source. These constants are used to specify values for ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadSourceTypesKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " in the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLibrary/init(options:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLibrary",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaSourceType"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaSourceType"
        }
      ],
      "role": "symbol",
      "title": "MLMediaSourceType",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediasourcetype"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesAudioBooksPlaylistTypeIdentifier": {
      "abstract": [
        {
          "text": "The media group that represents the Audio Books playlist in iTunes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiTunesAudioBooksPlaylistTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesAudioBooksPlaylistTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiTunesAudioBooksPlaylistTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiTunesAudioBooksPlaylistTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlitunesaudiobooksplaylisttypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesFolderPlaylistTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a folder in iTunes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiTunesFolderPlaylistTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesFolderPlaylistTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiTunesFolderPlaylistTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiTunesFolderPlaylistTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlitunesfolderplaylisttypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesGeniusPlaylistTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a genius playlist in iTunes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiTunesGeniusPlaylistTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesGeniusPlaylistTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiTunesGeniusPlaylistTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiTunesGeniusPlaylistTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlitunesgeniusplaylisttypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesMoviesPlaylistTypeIdentifier": {
      "abstract": [
        {
          "text": "The media group that represents the Movies playlist in iTunes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiTunesMoviesPlaylistTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesMoviesPlaylistTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiTunesMoviesPlaylistTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiTunesMoviesPlaylistTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlitunesmoviesplaylisttypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesMusicPlaylistTypeIdentifier": {
      "abstract": [
        {
          "text": "The media group that represents the Music playlist in iTunes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiTunesMusicPlaylistTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesMusicPlaylistTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiTunesMusicPlaylistTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiTunesMusicPlaylistTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlitunesmusicplaylisttypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesPlaylistTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a user-created playlist in iTunes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiTunesPlaylistTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesPlaylistTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiTunesPlaylistTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiTunesPlaylistTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlitunesplaylisttypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesPodcastPlaylistTypeIdentifier": {
      "abstract": [
        {
          "text": "The media group that represents the Podcast playlist in iTunes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiTunesPodcastPlaylistTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesPodcastPlaylistTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiTunesPodcastPlaylistTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiTunesPodcastPlaylistTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlitunespodcastplaylisttypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesPurchasedPlaylistTypeIdentifier": {
      "abstract": [
        {
          "text": "The media group that represents the Purchased playlist in iTunes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiTunesPurchasedPlaylistTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesPurchasedPlaylistTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiTunesPurchasedPlaylistTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiTunesPurchasedPlaylistTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlitunespurchasedplaylisttypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesRootGroupTypeIdentifier": {
      "abstract": [
        {
          "text": "The root media group for iTunes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiTunesRootGroupTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesRootGroupTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiTunesRootGroupTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiTunesRootGroupTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlitunesrootgrouptypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesSavedGeniusPlaylistTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a saved genius playlist in iTunes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiTunesSavedGeniusPlaylistTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesSavedGeniusPlaylistTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiTunesSavedGeniusPlaylistTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiTunesSavedGeniusPlaylistTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlitunessavedgeniusplaylisttypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesSmartPlaylistTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a smart playlist in iTunes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiTunesSmartPlaylistTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesSmartPlaylistTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiTunesSmartPlaylistTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiTunesSmartPlaylistTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlitunessmartplaylisttypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesTVShowsPlaylistTypeIdentifier": {
      "abstract": [
        {
          "text": "The media group that represents the TV Shows playlist in iTunes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiTunesTVShowsPlaylistTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesTVShowsPlaylistTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiTunesTVShowsPlaylistTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiTunesTVShowsPlaylistTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlitunestvshowsplaylisttypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesiTunesUPlaylistTypeIdentifier": {
      "abstract": [
        {
          "text": "The media group that represents the iTunes U playlist in iTunes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiTunesiTunesUPlaylistTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesiTunesUPlaylistTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiTunesiTunesUPlaylistTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiTunesiTunesUPlaylistTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlitunesitunesuplaylisttypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/aperture-media-group-type-identifiers": {
      "abstract": [
        {
          "text": "Identifiers for media group types in the Aperture media source. These constants are used to specify a media group’s ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/typeIdentifier",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " attribute.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/aperture-media-group-type-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Aperture Media Group Type Identifiers",
      "type": "topic",
      "url": "/documentation/medialibrary/aperture-media-group-type-identifiers"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/final-cut-pro-media-group-type-identifiers": {
      "abstract": [
        {
          "text": "Identifiers for media group types in the Final Cut Pro media source. These constants are used to specify a media group’s ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/typeIdentifier",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " attribute.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/final-cut-pro-media-group-type-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Final Cut Pro Media Group Type Identifiers",
      "type": "topic",
      "url": "/documentation/medialibrary/final-cut-pro-media-group-type-identifiers"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/folders-media-group-type-identifiers": {
      "abstract": [
        {
          "text": "Identifiers for media group types in folder-based media sources. These constants are used to specify a media group’s ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/typeIdentifier",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " attribute.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/folders-media-group-type-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Folders Media Group Type Identifiers",
      "type": "topic",
      "url": "/documentation/medialibrary/folders-media-group-type-identifiers"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/garageband-media-group-type-identifiers": {
      "abstract": [
        {
          "text": "Identifiers for media group types in the GarageBand media source. These constants are used to specify a media group’s ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/typeIdentifier",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " attribute.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/garageband-media-group-type-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GarageBand Media Group Type Identifiers",
      "type": "topic",
      "url": "/documentation/medialibrary/garageband-media-group-type-identifiers"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/logic-media-group-type-identifiers": {
      "abstract": [
        {
          "text": "Identifiers for media group types in the Logic media source. These constants are used to specify a media group’s ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/typeIdentifier",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " attribute.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/logic-media-group-type-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Logic Media Group Type Identifiers",
      "type": "topic",
      "url": "/documentation/medialibrary/logic-media-group-type-identifiers"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/media-source-identifiers": {
      "abstract": [
        {
          "text": "Identifiers for media sources which correspond to apps used to manage groups of media objects. Used with ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/load-options-keys",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/media-source-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Media Source Identifiers",
      "type": "topic",
      "url": "/documentation/medialibrary/media-source-identifiers"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/medialibrary-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/medialibrary-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MediaLibrary Constants",
      "type": "topic",
      "url": "/documentation/medialibrary/medialibrary-constants"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/well-known-folder-identifiers": {
      "abstract": [
        {
          "text": "Identifiers for well-known media folders used to specify the value for ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadFoldersKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/well-known-folder-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Well-Known Folder Identifiers",
      "type": "topic",
      "url": "/documentation/medialibrary/well-known-folder-identifiers"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.medialibrary/documentation/MediaLibrary/aperture-media-group-type-identifiers",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/final-cut-pro-media-group-type-identifiers",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/folders-media-group-type-identifiers",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/garageband-media-group-type-identifiers",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/logic-media-group-type-identifiers",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppFoldersKey",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppleLoops",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadExcludeSourcesKey",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadFoldersKey",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadIncludeSourcesKey",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadMoviesFolder",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadSourceTypesKey",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceApertureIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceAppDefinedFoldersIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceCustomFoldersIdentifier"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesRootGroupTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesPlaylistTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesSmartPlaylistTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesGeniusPlaylistTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesSavedGeniusPlaylistTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesFolderPlaylistTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesAudioBooksPlaylistTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesiTunesUPlaylistTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesMoviesPlaylistTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesMusicPlaylistTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesPodcastPlaylistTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesPurchasedPlaylistTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesTVShowsPlaylistTypeIdentifier"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesRootGroupTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesPlaylistTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesSmartPlaylistTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesGeniusPlaylistTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesSavedGeniusPlaylistTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesFolderPlaylistTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesAudioBooksPlaylistTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesiTunesUPlaylistTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesMoviesPlaylistTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesMusicPlaylistTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesPodcastPlaylistTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesPurchasedPlaylistTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesTVShowsPlaylistTypeIdentifier"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.medialibrary/documentation/MediaLibrary/aperture-media-group-type-identifiers",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/final-cut-pro-media-group-type-identifiers",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/folders-media-group-type-identifiers",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/garageband-media-group-type-identifiers",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/logic-media-group-type-identifiers",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppFoldersKey",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppleLoops",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadExcludeSourcesKey",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadFoldersKey",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadIncludeSourcesKey",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadMoviesFolder",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadSourceTypesKey",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceApertureIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceAppDefinedFoldersIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceCustomFoldersIdentifier"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadExcludeSourcesKey/title",
          "value": "MLMediaLoadExcludeSourcesKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadExcludeSourcesKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaLoadExcludeSourcesKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadMoviesFolder/title",
          "value": "MLMediaLoadMoviesFolder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadMoviesFolder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaLoadMoviesFolder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiTunesGeniusPlaylistTypeIdentifier/title",
          "value": "MLiTunesGeniusPlaylistTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiTunesGeniusPlaylistTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiTunesGeniusPlaylistTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiTunesAudioBooksPlaylistTypeIdentifier/title",
          "value": "MLiTunesAudioBooksPlaylistTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiTunesAudioBooksPlaylistTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiTunesAudioBooksPlaylistTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiTunesPodcastPlaylistTypeIdentifier/title",
          "value": "MLiTunesPodcastPlaylistTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiTunesPodcastPlaylistTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiTunesPodcastPlaylistTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaGroup~1typeIdentifier/title",
          "value": "typeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaGroup~1typeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "typeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiTunesPurchasedPlaylistTypeIdentifier/title",
          "value": "MLiTunesPurchasedPlaylistTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiTunesPurchasedPlaylistTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiTunesPurchasedPlaylistTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiTunesRootGroupTypeIdentifier/title",
          "value": "MLiTunesRootGroupTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiTunesRootGroupTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiTunesRootGroupTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadIncludeSourcesKey/title",
          "value": "MLMediaLoadIncludeSourcesKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadIncludeSourcesKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaLoadIncludeSourcesKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceType/title",
          "value": "MLMediaSourceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaSourceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaSourceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceCustomFoldersIdentifier/title",
          "value": "MLMediaSourceCustomFoldersIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceCustomFoldersIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaSourceCustomFoldersIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceApertureIdentifier/title",
          "value": "MLMediaSourceApertureIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceApertureIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaSourceApertureIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiTunesMusicPlaylistTypeIdentifier/title",
          "value": "MLiTunesMusicPlaylistTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiTunesMusicPlaylistTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiTunesMusicPlaylistTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadAppFoldersKey/title",
          "value": "MLMediaLoadAppFoldersKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadAppFoldersKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaLoadAppFoldersKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadFoldersKey/title",
          "value": "MLMediaLoadFoldersKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadFoldersKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaLoadFoldersKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiTunesMoviesPlaylistTypeIdentifier/title",
          "value": "MLiTunesMoviesPlaylistTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiTunesMoviesPlaylistTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiTunesMoviesPlaylistTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiTunesFolderPlaylistTypeIdentifier/title",
          "value": "MLiTunesFolderPlaylistTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiTunesFolderPlaylistTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiTunesFolderPlaylistTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiTunesSmartPlaylistTypeIdentifier/title",
          "value": "MLiTunesSmartPlaylistTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiTunesSmartPlaylistTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiTunesSmartPlaylistTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiTunesPlaylistTypeIdentifier/title",
          "value": "MLiTunesPlaylistTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiTunesPlaylistTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiTunesPlaylistTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiTunesTVShowsPlaylistTypeIdentifier/title",
          "value": "MLiTunesTVShowsPlaylistTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiTunesTVShowsPlaylistTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiTunesTVShowsPlaylistTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiTunesiTunesUPlaylistTypeIdentifier/title",
          "value": "MLiTunesiTunesUPlaylistTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiTunesiTunesUPlaylistTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiTunesiTunesUPlaylistTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceAppDefinedFoldersIdentifier/title",
          "value": "MLMediaSourceAppDefinedFoldersIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceAppDefinedFoldersIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaSourceAppDefinedFoldersIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadSourceTypesKey/title",
          "value": "MLMediaLoadSourceTypesKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadSourceTypesKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaLoadSourceTypesKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiTunesSavedGeniusPlaylistTypeIdentifier/title",
          "value": "MLiTunesSavedGeniusPlaylistTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiTunesSavedGeniusPlaylistTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiTunesSavedGeniusPlaylistTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadAppleLoops/title",
          "value": "MLMediaLoadAppleLoops"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadAppleLoops/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaLoadAppleLoops"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/medialibrary/itunes-media-group-type-identifiers"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/medialibrary/itunes-media-group-type-identifiers"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
