{
  "abstract": [
    {
      "text": "Attribute keys for a media object. These constants are used to specify keys within a media object’s ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObject/attributes",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " dictionary.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.medialibrary/documentation/MediaLibrary",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/medialibrary-constants"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.medialibrary/documentation/MediaLibrary/media-object-attribute-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Media Library"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Media Object Attribute Keys"
  },
  "references": {
    "doc://com.apple.documentation/documentation/foundation/1391112-nssizefromstring": {
      "abstract": [
        {
          "text": "Returns an `NSSize` from a text-based representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "NSSizeFromString"
        },
        {
          "kind": "text",
          "text": "(String) -> NSSize"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/1391112-nssizefromstring",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSizeFromString(_:)",
      "type": "topic",
      "url": "/documentation/foundation/1391112-nssizefromstring"
    },
    "doc://com.apple.documentation/documentation/foundation/nsarray": {
      "abstract": [
        {
          "text": "An object representing a static ordered collection, for use instead of an  constant in cases that require reference semantics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSArray"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsarray",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSArray",
      "type": "topic",
      "url": "/documentation/foundation/nsarray"
    },
    "doc://com.apple.documentation/documentation/foundation/nsnumber": {
      "abstract": [
        {
          "text": "An object wrapper for primitive scalar numeric values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNumber",
      "type": "topic",
      "url": "/documentation/foundation/nsnumber"
    },
    "doc://com.apple.documentation/documentation/foundation/nssize": {
      "abstract": [
        {
          "text": "A two-dimensional size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSSize"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nssize",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSize",
      "type": "topic",
      "url": "/documentation/foundation/nssize"
    },
    "doc://com.apple.documentation/documentation/foundation/nsstring": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary": {
      "abstract": [
        {
          "text": "Access read-only collections of the user’s multimedia content.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Library",
      "type": "topic",
      "url": "/documentation/medialibrary"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/typeIdentifier": {
      "abstract": [
        {
          "text": "An identifier for the media group’s type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "typeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/typeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "typeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "typeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediagroup/typeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppFoldersKey": {
      "abstract": [
        {
          "text": "Specifies one or more relative paths inside the caller’s app bundle in which to search for media files. The value for this key is an array of strings (relative paths inside the caller’s app bundle).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaLoadAppFoldersKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppFoldersKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaLoadAppFoldersKey"
        }
      ],
      "role": "symbol",
      "title": "MLMediaLoadAppFoldersKey",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmedialoadappfolderskey"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppleLoops": {
      "abstract": [
        {
          "text": "Identifies the folder containing audio loops from Apple.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaLoadAppleLoops"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppleLoops",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaLoadAppleLoops"
        }
      ],
      "role": "symbol",
      "title": "MLMediaLoadAppleLoops",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmedialoadappleloops"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadExcludeSourcesKey": {
      "abstract": [
        {
          "text": "Defines which media sources to exclude when loading. This option is processed after ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadIncludeSourcesKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ". The value for this key is an array of strings (media source identifiers). For a list of valid media source identifiers, see ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/media-source-identifiers",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaLoadExcludeSourcesKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadExcludeSourcesKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaLoadExcludeSourcesKey"
        }
      ],
      "role": "symbol",
      "title": "MLMediaLoadExcludeSourcesKey",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmedialoadexcludesourceskey"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadFoldersKey": {
      "abstract": [
        {
          "text": "Specifies the well-known folders that should be searched for media files. If this key is not present, none of the well-known folders will be provided. The value for this key is an array of strings (identifiers that correspond to well-known folder locations). For a list of well-known folder identifiers, see ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/well-known-folder-identifiers",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaLoadFoldersKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadFoldersKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaLoadFoldersKey"
        }
      ],
      "role": "symbol",
      "title": "MLMediaLoadFoldersKey",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmedialoadfolderskey"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadIncludeSourcesKey": {
      "abstract": [
        {
          "text": "Defines which media sources to include when loading. If not present, load all available media sources. This option is processed after ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadSourceTypesKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ". If ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadIncludeSourcesKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " is present but ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadSourceTypesKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " is not, then only those sources specified here will be loaded. This is useful for loading a single media source. When both keys are present, this is useful for adding one or more media sources that normally would not appear for the requested library type. The value for this key is an array of strings (media source identifiers). For a list of valid media source identifiers, see ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/media-source-identifiers",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaLoadIncludeSourcesKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadIncludeSourcesKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaLoadIncludeSourcesKey"
        }
      ],
      "role": "symbol",
      "title": "MLMediaLoadIncludeSourcesKey",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmedialoadincludesourceskey"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadMoviesFolder": {
      "abstract": [
        {
          "text": "Identifies the user’s Movies folder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaLoadMoviesFolder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadMoviesFolder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaLoadMoviesFolder"
        }
      ],
      "role": "symbol",
      "title": "MLMediaLoadMoviesFolder",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmedialoadmoviesfolder"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadSourceTypesKey": {
      "abstract": [
        {
          "text": "Defines which sources to load based on library type. If not present, this will load all sources. The value for this key is a media source type. For a list of valid media source types, see ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceType",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaLoadSourceTypesKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadSourceTypesKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaLoadSourceTypesKey"
        }
      ],
      "role": "symbol",
      "title": "MLMediaLoadSourceTypesKey",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmedialoadsourcetypeskey"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObject/attributes": {
      "abstract": [
        {
          "text": "A dictionary of attributes describing the media object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attributes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObject/attributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attributes"
        }
      ],
      "role": "symbol",
      "title": "attributes",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediaobject/attributes"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectAlbumKey": {
      "abstract": [
        {
          "text": "Specifies the media object’s album. The value for this key is a string (",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaObjectAlbumKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectAlbumKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaObjectAlbumKey"
        }
      ],
      "role": "symbol",
      "title": "MLMediaObjectAlbumKey",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediaobjectalbumkey"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectArtistKey": {
      "abstract": [
        {
          "text": "Specifies the media object’s artist. The value for this key is a string (",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaObjectArtistKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectArtistKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaObjectArtistKey"
        }
      ],
      "role": "symbol",
      "title": "MLMediaObjectArtistKey",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediaobjectartistkey"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectBitRateKey": {
      "abstract": [
        {
          "text": "Specifies the media object’s bit rate, in kilobits per second. The value for this key is a number (",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaObjectBitRateKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectBitRateKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaObjectBitRateKey"
        }
      ],
      "role": "symbol",
      "title": "MLMediaObjectBitRateKey",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediaobjectbitratekey"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectChannelCountKey": {
      "abstract": [
        {
          "text": "Specifies the media object’s channel count. The value for this key is a number (",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaObjectChannelCountKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectChannelCountKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaObjectChannelCountKey"
        }
      ],
      "role": "symbol",
      "title": "MLMediaObjectChannelCountKey",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediaobjectchannelcountkey"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectCommentsKey": {
      "abstract": [
        {
          "text": "Specifies the contents of the comments field associated with the media object. The value for this key is a string (",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaObjectCommentsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectCommentsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaObjectCommentsKey"
        }
      ],
      "role": "symbol",
      "title": "MLMediaObjectCommentsKey",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediaobjectcommentskey"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectDurationKey": {
      "abstract": [
        {
          "text": "Specifies the media object’s duration, in seconds. The value for this key is a number (",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaObjectDurationKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectDurationKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaObjectDurationKey"
        }
      ],
      "role": "symbol",
      "title": "MLMediaObjectDurationKey",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediaobjectdurationkey"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectGenreKey": {
      "abstract": [
        {
          "text": "Specifies the media object’s genre. The value for this key is a string (",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaObjectGenreKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectGenreKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaObjectGenreKey"
        }
      ],
      "role": "symbol",
      "title": "MLMediaObjectGenreKey",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediaobjectgenrekey"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectKeywordsKey": {
      "abstract": [
        {
          "text": "Specifies the keywords associated with the media object. The value for this key is an array (",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsarray",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ") of strings (",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaObjectKeywordsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectKeywordsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaObjectKeywordsKey"
        }
      ],
      "role": "symbol",
      "title": "MLMediaObjectKeywordsKey",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediaobjectkeywordskey"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectKindKey": {
      "abstract": [
        {
          "text": "Used by iTunes only. Specifies the media object’s file format (shown in the “Kind” column in iTunes). The value for this key is a string (",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaObjectKindKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectKindKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaObjectKindKey"
        }
      ],
      "role": "symbol",
      "title": "MLMediaObjectKindKey",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediaobjectkindkey"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectProtectedKey": {
      "abstract": [
        {
          "text": "Specifies whether the media object is protected by DRM (Digital Rights Management). The value for this key is a number (",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": "), 0 or 1, that represents a Boolean value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaObjectProtectedKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectProtectedKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaObjectProtectedKey"
        }
      ],
      "role": "symbol",
      "title": "MLMediaObjectProtectedKey",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediaobjectprotectedkey"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectResolutionStringKey": {
      "abstract": [
        {
          "text": "Specifies the media object’s resolution. The value for this key is a string (",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ") intended to be converted to a size (",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nssize",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ") using the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/1391112-nssizefromstring",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaObjectResolutionStringKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectResolutionStringKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaObjectResolutionStringKey"
        }
      ],
      "role": "symbol",
      "title": "MLMediaObjectResolutionStringKey",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediaobjectresolutionstringkey"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectSampleRateKey": {
      "abstract": [
        {
          "text": "Specifies the media object’s sample rate, in samples per second (Hz). The value for this key is a number (",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaObjectSampleRateKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectSampleRateKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaObjectSampleRateKey"
        }
      ],
      "role": "symbol",
      "title": "MLMediaObjectSampleRateKey",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediaobjectsampleratekey"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectTrackNumberKey": {
      "abstract": [
        {
          "text": "Specifies the media object’s track number. The value for this key is a number (",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaObjectTrackNumberKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectTrackNumberKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaObjectTrackNumberKey"
        }
      ],
      "role": "symbol",
      "title": "MLMediaObjectTrackNumberKey",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediaobjecttracknumberkey"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceApertureIdentifier": {
      "abstract": [
        {
          "text": "The media source providing content from Aperture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaSourceApertureIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceApertureIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaSourceApertureIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLMediaSourceApertureIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediasourceapertureidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceAppDefinedFoldersIdentifier": {
      "abstract": [
        {
          "text": "The media source for app-defined folders. This identifies a media source created from a relative path inside the caller’s app bundle. This source provides data when ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppFoldersKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " is provided in the options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaSourceAppDefinedFoldersIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceAppDefinedFoldersIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaSourceAppDefinedFoldersIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLMediaSourceAppDefinedFoldersIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediasourceappdefinedfoldersidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceCustomFoldersIdentifier": {
      "abstract": [
        {
          "text": "The media source for custom folders. Currently, the only custom folder is the folder containing audio loops from Apple. This source provides data when ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadFoldersKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " is provided with the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppleLoops",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaSourceCustomFoldersIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceCustomFoldersIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaSourceCustomFoldersIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLMediaSourceCustomFoldersIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediasourcecustomfoldersidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceType": {
      "abstract": [
        {
          "text": "Specifies the source type associated with a particular media source. Source type reflects the primary type of media within the source. These constants are used to specify values for ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadSourceTypesKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " in the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLibrary/init(options:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLibrary",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaSourceType"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaSourceType"
        }
      ],
      "role": "symbol",
      "title": "MLMediaSourceType",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediasourcetype"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/aperture-media-group-type-identifiers": {
      "abstract": [
        {
          "text": "Identifiers for media group types in the Aperture media source. These constants are used to specify a media group’s ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/typeIdentifier",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " attribute.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/aperture-media-group-type-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Aperture Media Group Type Identifiers",
      "type": "topic",
      "url": "/documentation/medialibrary/aperture-media-group-type-identifiers"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/final-cut-pro-media-group-type-identifiers": {
      "abstract": [
        {
          "text": "Identifiers for media group types in the Final Cut Pro media source. These constants are used to specify a media group’s ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/typeIdentifier",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " attribute.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/final-cut-pro-media-group-type-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Final Cut Pro Media Group Type Identifiers",
      "type": "topic",
      "url": "/documentation/medialibrary/final-cut-pro-media-group-type-identifiers"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/folders-media-group-type-identifiers": {
      "abstract": [
        {
          "text": "Identifiers for media group types in folder-based media sources. These constants are used to specify a media group’s ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/typeIdentifier",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " attribute.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/folders-media-group-type-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Folders Media Group Type Identifiers",
      "type": "topic",
      "url": "/documentation/medialibrary/folders-media-group-type-identifiers"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/garageband-media-group-type-identifiers": {
      "abstract": [
        {
          "text": "Identifiers for media group types in the GarageBand media source. These constants are used to specify a media group’s ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/typeIdentifier",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " attribute.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/garageband-media-group-type-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GarageBand Media Group Type Identifiers",
      "type": "topic",
      "url": "/documentation/medialibrary/garageband-media-group-type-identifiers"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/logic-media-group-type-identifiers": {
      "abstract": [
        {
          "text": "Identifiers for media group types in the Logic media source. These constants are used to specify a media group’s ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/typeIdentifier",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " attribute.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/logic-media-group-type-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Logic Media Group Type Identifiers",
      "type": "topic",
      "url": "/documentation/medialibrary/logic-media-group-type-identifiers"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/media-source-identifiers": {
      "abstract": [
        {
          "text": "Identifiers for media sources which correspond to apps used to manage groups of media objects. Used with ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/load-options-keys",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/media-source-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Media Source Identifiers",
      "type": "topic",
      "url": "/documentation/medialibrary/media-source-identifiers"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/medialibrary-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/medialibrary-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MediaLibrary Constants",
      "type": "topic",
      "url": "/documentation/medialibrary/medialibrary-constants"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/well-known-folder-identifiers": {
      "abstract": [
        {
          "text": "Identifiers for well-known media folders used to specify the value for ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadFoldersKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/well-known-folder-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Well-Known Folder Identifiers",
      "type": "topic",
      "url": "/documentation/medialibrary/well-known-folder-identifiers"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.medialibrary/documentation/MediaLibrary/aperture-media-group-type-identifiers",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/final-cut-pro-media-group-type-identifiers",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/folders-media-group-type-identifiers",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/garageband-media-group-type-identifiers",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/logic-media-group-type-identifiers",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppFoldersKey",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppleLoops",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadExcludeSourcesKey",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadFoldersKey",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadIncludeSourcesKey",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadMoviesFolder",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadSourceTypesKey",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceApertureIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceAppDefinedFoldersIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceCustomFoldersIdentifier"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectDurationKey",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectArtistKey",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectAlbumKey",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectGenreKey",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectKindKey",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectTrackNumberKey",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectBitRateKey",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectSampleRateKey",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectChannelCountKey",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectResolutionStringKey",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectCommentsKey",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectKeywordsKey",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectProtectedKey"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectDurationKey",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectArtistKey",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectAlbumKey",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectGenreKey",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectKindKey",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectTrackNumberKey",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectBitRateKey",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectSampleRateKey",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectChannelCountKey",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectResolutionStringKey",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectCommentsKey",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectKeywordsKey",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectProtectedKey"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.medialibrary/documentation/MediaLibrary/aperture-media-group-type-identifiers",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/final-cut-pro-media-group-type-identifiers",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/folders-media-group-type-identifiers",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/garageband-media-group-type-identifiers",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/logic-media-group-type-identifiers",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppFoldersKey",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppleLoops",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadExcludeSourcesKey",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadFoldersKey",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadIncludeSourcesKey",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadMoviesFolder",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadSourceTypesKey",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceApertureIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceAppDefinedFoldersIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceCustomFoldersIdentifier"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObjectResolutionStringKey/title",
          "value": "MLMediaObjectResolutionStringKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObjectResolutionStringKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaObjectResolutionStringKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObjectKeywordsKey/title",
          "value": "MLMediaObjectKeywordsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObjectKeywordsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaObjectKeywordsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObjectGenreKey/title",
          "value": "MLMediaObjectGenreKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObjectGenreKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaObjectGenreKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceAppDefinedFoldersIdentifier/title",
          "value": "MLMediaSourceAppDefinedFoldersIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceAppDefinedFoldersIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaSourceAppDefinedFoldersIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObjectBitRateKey/title",
          "value": "MLMediaObjectBitRateKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObjectBitRateKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaObjectBitRateKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObjectProtectedKey/title",
          "value": "MLMediaObjectProtectedKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObjectProtectedKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaObjectProtectedKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaGroup~1typeIdentifier/title",
          "value": "typeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaGroup~1typeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "typeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObjectKindKey/title",
          "value": "MLMediaObjectKindKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObjectKindKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaObjectKindKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObjectArtistKey/title",
          "value": "MLMediaObjectArtistKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObjectArtistKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaObjectArtistKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceApertureIdentifier/title",
          "value": "MLMediaSourceApertureIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceApertureIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaSourceApertureIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsarray/abstract",
          "value": [
            {
              "text": "A static ordered collection of objects.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceType/title",
          "value": "MLMediaSourceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaSourceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaSourceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadMoviesFolder/title",
          "value": "MLMediaLoadMoviesFolder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadMoviesFolder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaLoadMoviesFolder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObjectCommentsKey/title",
          "value": "MLMediaObjectCommentsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObjectCommentsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaObjectCommentsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadExcludeSourcesKey/title",
          "value": "MLMediaLoadExcludeSourcesKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadExcludeSourcesKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaLoadExcludeSourcesKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadAppleLoops/title",
          "value": "MLMediaLoadAppleLoops"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadAppleLoops/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaLoadAppleLoops"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObject~1attributes/title",
          "value": "attributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObject~1attributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "attributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObjectDurationKey/title",
          "value": "MLMediaObjectDurationKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObjectDurationKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaObjectDurationKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~11391112-nssizefromstring/title",
          "value": "NSSizeFromString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObjectChannelCountKey/title",
          "value": "MLMediaObjectChannelCountKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObjectChannelCountKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaObjectChannelCountKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadIncludeSourcesKey/title",
          "value": "MLMediaLoadIncludeSourcesKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadIncludeSourcesKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaLoadIncludeSourcesKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObjectAlbumKey/title",
          "value": "MLMediaObjectAlbumKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObjectAlbumKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaObjectAlbumKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadSourceTypesKey/title",
          "value": "MLMediaLoadSourceTypesKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadSourceTypesKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaLoadSourceTypesKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadFoldersKey/title",
          "value": "MLMediaLoadFoldersKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadFoldersKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaLoadFoldersKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsstring/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadAppFoldersKey/title",
          "value": "MLMediaLoadAppFoldersKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadAppFoldersKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaLoadAppFoldersKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObjectTrackNumberKey/title",
          "value": "MLMediaObjectTrackNumberKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObjectTrackNumberKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaObjectTrackNumberKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObjectSampleRateKey/title",
          "value": "MLMediaObjectSampleRateKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObjectSampleRateKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaObjectSampleRateKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceCustomFoldersIdentifier/title",
          "value": "MLMediaSourceCustomFoldersIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceCustomFoldersIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaSourceCustomFoldersIdentifier"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/medialibrary/media-object-attribute-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/medialibrary/media-object-attribute-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
