{
  "abstract": [
    {
      "text": "Identifiers for media sources which correspond to apps used to manage groups of media objects. Used with ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/load-options-keys",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": ".",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.medialibrary/documentation/MediaLibrary",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLibrary"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.medialibrary/documentation/MediaLibrary/media-source-identifiers"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Media Library"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Media Source Identifiers"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary": {
      "abstract": [
        {
          "text": "Access read-only collections of the user’s multimedia content.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Library",
      "type": "topic",
      "url": "/documentation/medialibrary"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLibrary": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "MLMediaLibrary",
          "type": "codeVoice"
        },
        {
          "text": " class provides an interface for accessing a collection of media objects from various sources. It serves as the initial access point of the Media Library framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaLibrary"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLibrary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaLibrary"
        }
      ],
      "role": "symbol",
      "title": "MLMediaLibrary",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmedialibrary"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLibrary/init(options:)": {
      "abstract": [
        {
          "text": "Initializes the media library based on the specified load options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLibrary/init(options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithOptions:"
        }
      ],
      "role": "symbol",
      "title": "init(options:)",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmedialibrary/init(options:)"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadFoldersKey": {
      "abstract": [
        {
          "text": "Specifies the well-known folders that should be searched for media files. If this key is not present, none of the well-known folders will be provided. The value for this key is an array of strings (identifiers that correspond to well-known folder locations). For a list of well-known folder identifiers, see ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/well-known-folder-identifiers",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaLoadFoldersKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadFoldersKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaLoadFoldersKey"
        }
      ],
      "role": "symbol",
      "title": "MLMediaLoadFoldersKey",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmedialoadfolderskey"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceApertureIdentifier": {
      "abstract": [
        {
          "text": "The media source providing content from Aperture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaSourceApertureIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceApertureIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaSourceApertureIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLMediaSourceApertureIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediasourceapertureidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceFinalCutIdentifier": {
      "abstract": [
        {
          "text": "The media source providing content from Final Cut Pro.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaSourceFinalCutIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceFinalCutIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaSourceFinalCutIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLMediaSourceFinalCutIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediasourcefinalcutidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceGarageBandIdentifier": {
      "abstract": [
        {
          "text": "The media source providing content from GarageBand.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaSourceGarageBandIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceGarageBandIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaSourceGarageBandIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLMediaSourceGarageBandIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediasourcegaragebandidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceLogicIdentifier": {
      "abstract": [
        {
          "text": "The media source providing content from Logic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaSourceLogicIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceLogicIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaSourceLogicIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLMediaSourceLogicIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediasourcelogicidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourcePhotoBoothIdentifier": {
      "abstract": [
        {
          "text": "The media source providing content from Photo Booth.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaSourcePhotoBoothIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourcePhotoBoothIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaSourcePhotoBoothIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLMediaSourcePhotoBoothIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediasourcephotoboothidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceiMovieIdentifier": {
      "abstract": [
        {
          "text": "The media source providing content from iMovie.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaSourceiMovieIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceiMovieIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaSourceiMovieIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLMediaSourceiMovieIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediasourceimovieidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceiPhotoIdentifier": {
      "abstract": [
        {
          "text": "The media source providing content from iPhoto.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaSourceiPhotoIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceiPhotoIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaSourceiPhotoIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLMediaSourceiPhotoIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediasourceiphotoidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceiTunesIdentifier": {
      "abstract": [
        {
          "text": "The media source providing content from iTunes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaSourceiTunesIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceiTunesIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaSourceiTunesIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLMediaSourceiTunesIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediasourceitunesidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/load-options-keys": {
      "abstract": [
        {
          "text": "Keys used to specify the ",
          "type": "text"
        },
        {
          "code": "options",
          "type": "codeVoice"
        },
        {
          "text": " dictionary argument to ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLibrary/init(options:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/load-options-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Load Options Keys",
      "type": "topic",
      "url": "/documentation/medialibrary/load-options-keys"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/non-app-specific-media-source-identifiers": {
      "abstract": [
        {
          "text": "Identifiers for media sources which do not correspond to apps. Used with ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/load-options-keys",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/non-app-specific-media-source-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Non-App-Specific Media Source Identifiers",
      "type": "topic",
      "url": "/documentation/medialibrary/non-app-specific-media-source-identifiers"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/well-known-folder-identifiers": {
      "abstract": [
        {
          "text": "Identifiers for well-known media folders used to specify the value for ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadFoldersKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/well-known-folder-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Well-Known Folder Identifiers",
      "type": "topic",
      "url": "/documentation/medialibrary/well-known-folder-identifiers"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.medialibrary/documentation/MediaLibrary/load-options-keys",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/non-app-specific-media-source-identifiers",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/well-known-folder-identifiers"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceiPhotoIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceiTunesIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceApertureIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceiMovieIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceFinalCutIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceGarageBandIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceLogicIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourcePhotoBoothIdentifier"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceiPhotoIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceiTunesIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceApertureIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceiMovieIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceFinalCutIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceGarageBandIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceLogicIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourcePhotoBoothIdentifier"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.medialibrary/documentation/MediaLibrary/load-options-keys",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/non-app-specific-media-source-identifiers",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/well-known-folder-identifiers"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceiTunesIdentifier/title",
          "value": "MLMediaSourceiTunesIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceiTunesIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaSourceiTunesIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourcePhotoBoothIdentifier/title",
          "value": "MLMediaSourcePhotoBoothIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourcePhotoBoothIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaSourcePhotoBoothIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceApertureIdentifier/title",
          "value": "MLMediaSourceApertureIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceApertureIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaSourceApertureIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLibrary~1init(options:)/title",
          "value": "initWithOptions:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLibrary~1init(options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithOptions:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceLogicIdentifier/title",
          "value": "MLMediaSourceLogicIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceLogicIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaSourceLogicIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceGarageBandIdentifier/title",
          "value": "MLMediaSourceGarageBandIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceGarageBandIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaSourceGarageBandIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLibrary/title",
          "value": "MLMediaLibrary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLibrary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaLibrary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLibrary/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaLibrary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceFinalCutIdentifier/title",
          "value": "MLMediaSourceFinalCutIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceFinalCutIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaSourceFinalCutIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceiMovieIdentifier/title",
          "value": "MLMediaSourceiMovieIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceiMovieIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaSourceiMovieIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadFoldersKey/title",
          "value": "MLMediaLoadFoldersKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadFoldersKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaLoadFoldersKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceiPhotoIdentifier/title",
          "value": "MLMediaSourceiPhotoIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceiPhotoIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaSourceiPhotoIdentifier"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/medialibrary/media-source-identifiers"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/medialibrary/media-source-identifiers"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
