{
  "abstract": [
    {
      "text": "A media group that represents a SmugMug user account in Aperture. A SmugMug user account contains one or more SmugMug albums.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.medialibrary/documentation/MediaLibrary"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureSmugMugGroupTypeIdentifier"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@MLApertureSmugMugGroupTypeIdentifier",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MLApertureSmugMugGroupTypeIdentifier"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "Media Library"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MLApertureSmugMugGroupTypeIdentifier"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.15",
        "introducedAt": "10.9",
        "message": "MediaLibrary.framework will be removed in a future OS version. Use Photos.framework or iTunesLibrary.framework instead.",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "MLApertureSmugMugGroupTypeIdentifier"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MLApertureSmugMugGroupTypeIdentifier"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary": {
      "abstract": [
        {
          "text": "Access read-only collections of the user’s multimedia content.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Library",
      "type": "topic",
      "url": "/documentation/medialibrary"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureAllPhotosTypeIdentifier": {
      "abstract": [
        {
          "text": "The media group that represents all photos in Aperture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLApertureAllPhotosTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureAllPhotosTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLApertureAllPhotosTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLApertureAllPhotosTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlapertureallphotostypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureAllProjectsTypeIdentifier": {
      "abstract": [
        {
          "text": "The media group that represents all projects in Aperture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLApertureAllProjectsTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureAllProjectsTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLApertureAllProjectsTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLApertureAllProjectsTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlapertureallprojectstypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureFlaggedTypeIdentifier": {
      "abstract": [
        {
          "text": "The media group that represents the album of flagged media in Aperture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLApertureFlaggedTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureFlaggedTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLApertureFlaggedTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLApertureFlaggedTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlapertureflaggedtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureFolderAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a folder in Aperture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLApertureFolderAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureFolderAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLApertureFolderAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLApertureFolderAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlaperturefolderalbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureLastImportAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "The media group that represents the last import album in Aperture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLApertureLastImportAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureLastImportAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLApertureLastImportAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLApertureLastImportAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlaperturelastimportalbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureLastNMonthsAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "The media group that represents the recent content album in Aperture, known as the Last ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "N",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " Months album. The value for ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "N",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " is usually 12 (settable in Aperture > Preferences > General).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLApertureLastNMonthsAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureLastNMonthsAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLApertureLastNMonthsAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLApertureLastNMonthsAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlaperturelastnmonthsalbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureLastViewedEventAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "The media group that represents the last viewed event in Aperture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLApertureLastViewedEventAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureLastViewedEventAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLApertureLastViewedEventAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLApertureLastViewedEventAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlaperturelastviewedeventalbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureLightTableTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a light table in Aperture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLApertureLightTableTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureLightTableTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLApertureLightTableTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLApertureLightTableTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlaperturelighttabletypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLAperturePhotoStreamAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a photo stream in Aperture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLAperturePhotoStreamAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLAperturePhotoStreamAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLAperturePhotoStreamAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLAperturePhotoStreamAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlaperturephotostreamalbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureProjectAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a project in Aperture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLApertureProjectAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureProjectAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLApertureProjectAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLApertureProjectAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlapertureprojectalbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureProjectFolderAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a folder within a project in Aperture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLApertureProjectFolderAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureProjectFolderAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLApertureProjectFolderAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLApertureProjectFolderAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlapertureprojectfolderalbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureRootGroupTypeIdentifier": {
      "abstract": [
        {
          "text": "The root media group for Aperture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLApertureRootGroupTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureRootGroupTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLApertureRootGroupTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLApertureRootGroupTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlaperturerootgrouptypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureSlideShowTypeIdentifier": {
      "abstract": [
        {
          "text": "The media group that represents a slideshow in Aperture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLApertureSlideShowTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureSlideShowTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLApertureSlideShowTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLApertureSlideShowTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlapertureslideshowtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureSmugMugGroupTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a SmugMug user account in Aperture. A SmugMug user account contains one or more SmugMug albums.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLApertureSmugMugGroupTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureSmugMugGroupTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLApertureSmugMugGroupTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLApertureSmugMugGroupTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlaperturesmugmuggrouptypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureUserAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a user-created album in Aperture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLApertureUserAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureUserAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLApertureUserAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLApertureUserAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlapertureuseralbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureUserSmartAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a user-created smart album in Aperture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLApertureUserSmartAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureUserSmartAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLApertureUserSmartAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLApertureUserSmartAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlapertureusersmartalbumtypeidentifier"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureRootGroupTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureUserAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureUserSmartAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureProjectAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureFolderAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureProjectFolderAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureAllProjectsTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureAllPhotosTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureLastViewedEventAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureLastImportAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureLastNMonthsAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureFlaggedTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureLightTableTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureSlideShowTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLAperturePhotoStreamAlbumTypeIdentifier"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.15",
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MLApertureSmugMugGroupTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLApertureSmugMugGroupTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.medialibrary/documentation/MediaLibrary"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureRootGroupTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureUserAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureUserSmartAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureProjectAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureFolderAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureProjectFolderAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureAllProjectsTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureAllPhotosTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureLastViewedEventAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureLastImportAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureLastNMonthsAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureFlaggedTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureLightTableTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLApertureSlideShowTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLAperturePhotoStreamAlbumTypeIdentifier"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MLApertureSmugMugGroupTypeIdentifier"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureSlideShowTypeIdentifier/title",
          "value": "MLApertureSlideShowTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureSlideShowTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLApertureSlideShowTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureRootGroupTypeIdentifier/title",
          "value": "MLApertureRootGroupTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureRootGroupTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLApertureRootGroupTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureProjectAlbumTypeIdentifier/title",
          "value": "MLApertureProjectAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureProjectAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLApertureProjectAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureAllPhotosTypeIdentifier/title",
          "value": "MLApertureAllPhotosTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureAllPhotosTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLApertureAllPhotosTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureUserAlbumTypeIdentifier/title",
          "value": "MLApertureUserAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureUserAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLApertureUserAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureLastNMonthsAlbumTypeIdentifier/title",
          "value": "MLApertureLastNMonthsAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureLastNMonthsAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLApertureLastNMonthsAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLAperturePhotoStreamAlbumTypeIdentifier/title",
          "value": "MLAperturePhotoStreamAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLAperturePhotoStreamAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLAperturePhotoStreamAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureFolderAlbumTypeIdentifier/title",
          "value": "MLApertureFolderAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureFolderAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLApertureFolderAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureLastViewedEventAlbumTypeIdentifier/title",
          "value": "MLApertureLastViewedEventAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureLastViewedEventAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLApertureLastViewedEventAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureSmugMugGroupTypeIdentifier/title",
          "value": "MLApertureSmugMugGroupTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureSmugMugGroupTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLApertureSmugMugGroupTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureProjectFolderAlbumTypeIdentifier/title",
          "value": "MLApertureProjectFolderAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureProjectFolderAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLApertureProjectFolderAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureAllProjectsTypeIdentifier/title",
          "value": "MLApertureAllProjectsTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureAllProjectsTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLApertureAllProjectsTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureLightTableTypeIdentifier/title",
          "value": "MLApertureLightTableTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureLightTableTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLApertureLightTableTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureFlaggedTypeIdentifier/title",
          "value": "MLApertureFlaggedTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureFlaggedTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLApertureFlaggedTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureUserSmartAlbumTypeIdentifier/title",
          "value": "MLApertureUserSmartAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureUserSmartAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLApertureUserSmartAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureLastImportAlbumTypeIdentifier/title",
          "value": "MLApertureLastImportAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLApertureLastImportAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLApertureLastImportAlbumTypeIdentifier"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/medialibrary/mlaperturesmugmuggrouptypeidentifier"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/medialibrary/mlaperturesmugmuggrouptypeidentifier"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
