{
  "abstract": [
    {
      "text": "A media group that represents a photo stream in iPhoto.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.medialibrary/documentation/MediaLibrary"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoPhotoStreamAlbumTypeIdentifier"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@MLiPhotoPhotoStreamAlbumTypeIdentifier",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MLiPhotoPhotoStreamAlbumTypeIdentifier"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "Media Library"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MLiPhotoPhotoStreamAlbumTypeIdentifier"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.15",
        "introducedAt": "10.9",
        "message": "MediaLibrary.framework will be removed in a future OS version. Use Photos.framework or iTunesLibrary.framework instead.",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "MLiPhotoPhotoStreamAlbumTypeIdentifier"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MLiPhotoPhotoStreamAlbumTypeIdentifier"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary": {
      "abstract": [
        {
          "text": "Access read-only collections of the user’s multimedia content.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Library",
      "type": "topic",
      "url": "/documentation/medialibrary"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents an album in iPhoto.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiPhotoAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiPhotoAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiPhotoAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mliphotoalbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoEventAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents an event in iPhoto.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiPhotoEventAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoEventAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiPhotoEventAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiPhotoEventAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mliphotoeventalbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoEventsFolderTypeIdentifier": {
      "abstract": [
        {
          "text": "The media group that represents the Events album in iPhoto.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiPhotoEventsFolderTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoEventsFolderTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiPhotoEventsFolderTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiPhotoEventsFolderTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mliphotoeventsfoldertypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoFacesAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a Faces album in iPhoto. Individual Faces albums are nested in the main Faces album.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiPhotoFacesAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoFacesAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiPhotoFacesAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiPhotoFacesAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mliphotofacesalbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoFlaggedAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "The media group that represents the album of flagged media in iPhoto.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiPhotoFlaggedAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoFlaggedAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiPhotoFlaggedAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiPhotoFlaggedAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mliphotoflaggedalbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoFolderAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a folder in iPhoto.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiPhotoFolderAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoFolderAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiPhotoFolderAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiPhotoFolderAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mliphotofolderalbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoLastImportAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "The media group that represents the Last Import album in iPhoto.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiPhotoLastImportAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoLastImportAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiPhotoLastImportAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiPhotoLastImportAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mliphotolastimportalbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoLastNMonthsAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "The media group that represents the recent content album in iPhoto, known as the Last ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "N",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " Months album. The value for ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "N",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " is usually 12 (settable in iPhoto > Preferences > General).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiPhotoLastNMonthsAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoLastNMonthsAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiPhotoLastNMonthsAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiPhotoLastNMonthsAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mliphotolastnmonthsalbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoLastViewedEventAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "The media group that represents the last viewed event in iPhoto.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiPhotoLastViewedEventAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoLastViewedEventAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiPhotoLastViewedEventAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiPhotoLastViewedEventAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mliphotolastviewedeventalbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoLibraryAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "The media group that represents the Photos album in iPhoto.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiPhotoLibraryAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoLibraryAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiPhotoLibraryAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiPhotoLibraryAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mliphotolibraryalbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoPhotoStreamAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a photo stream in iPhoto.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiPhotoPhotoStreamAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoPhotoStreamAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiPhotoPhotoStreamAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiPhotoPhotoStreamAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mliphotophotostreamalbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoPlacesAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "The media group that represents the Places album in iPhoto.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiPhotoPlacesAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoPlacesAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiPhotoPlacesAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiPhotoPlacesAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mliphotoplacesalbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoRootGroupTypeIdentifier": {
      "abstract": [
        {
          "text": "The root media group for iPhoto.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiPhotoRootGroupTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoRootGroupTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiPhotoRootGroupTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiPhotoRootGroupTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mliphotorootgrouptypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoSlideShowAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a slideshow album in iPhoto.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiPhotoSlideShowAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoSlideShowAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiPhotoSlideShowAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiPhotoSlideShowAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mliphotoslideshowalbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoSmartAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a smart album in iPhoto.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiPhotoSmartAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoSmartAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiPhotoSmartAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiPhotoSmartAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mliphotosmartalbumtypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoSubscribedAlbumTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a subscribed album in iPhoto.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiPhotoSubscribedAlbumTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoSubscribedAlbumTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiPhotoSubscribedAlbumTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiPhotoSubscribedAlbumTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mliphotosubscribedalbumtypeidentifier"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoRootGroupTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoSmartAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoLibraryAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoFolderAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoEventAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoEventsFolderTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoLastViewedEventAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoLastImportAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoLastNMonthsAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoFlaggedAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoSubscribedAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoSlideShowAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoFacesAlbumTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoPlacesAlbumTypeIdentifier"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.15",
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MLiPhotoPhotoStreamAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiPhotoPhotoStreamAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.medialibrary/documentation/MediaLibrary"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoRootGroupTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoSmartAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoLibraryAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoFolderAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoEventAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoEventsFolderTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoLastViewedEventAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoLastImportAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoLastNMonthsAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoFlaggedAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoSubscribedAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoSlideShowAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoFacesAlbumTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiPhotoPlacesAlbumTypeIdentifier"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MLiPhotoPhotoStreamAlbumTypeIdentifier"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoSubscribedAlbumTypeIdentifier/title",
          "value": "MLiPhotoSubscribedAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoSubscribedAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiPhotoSubscribedAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoLastImportAlbumTypeIdentifier/title",
          "value": "MLiPhotoLastImportAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoLastImportAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiPhotoLastImportAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoLastViewedEventAlbumTypeIdentifier/title",
          "value": "MLiPhotoLastViewedEventAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoLastViewedEventAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiPhotoLastViewedEventAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoLastNMonthsAlbumTypeIdentifier/title",
          "value": "MLiPhotoLastNMonthsAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoLastNMonthsAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiPhotoLastNMonthsAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoPlacesAlbumTypeIdentifier/title",
          "value": "MLiPhotoPlacesAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoPlacesAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiPhotoPlacesAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoEventsFolderTypeIdentifier/title",
          "value": "MLiPhotoEventsFolderTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoEventsFolderTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiPhotoEventsFolderTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoEventAlbumTypeIdentifier/title",
          "value": "MLiPhotoEventAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoEventAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiPhotoEventAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoFolderAlbumTypeIdentifier/title",
          "value": "MLiPhotoFolderAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoFolderAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiPhotoFolderAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoSlideShowAlbumTypeIdentifier/title",
          "value": "MLiPhotoSlideShowAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoSlideShowAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiPhotoSlideShowAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoLibraryAlbumTypeIdentifier/title",
          "value": "MLiPhotoLibraryAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoLibraryAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiPhotoLibraryAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoAlbumTypeIdentifier/title",
          "value": "MLiPhotoAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiPhotoAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoRootGroupTypeIdentifier/title",
          "value": "MLiPhotoRootGroupTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoRootGroupTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiPhotoRootGroupTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoFlaggedAlbumTypeIdentifier/title",
          "value": "MLiPhotoFlaggedAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoFlaggedAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiPhotoFlaggedAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoFacesAlbumTypeIdentifier/title",
          "value": "MLiPhotoFacesAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoFacesAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiPhotoFacesAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoSmartAlbumTypeIdentifier/title",
          "value": "MLiPhotoSmartAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoSmartAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiPhotoSmartAlbumTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoPhotoStreamAlbumTypeIdentifier/title",
          "value": "MLiPhotoPhotoStreamAlbumTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiPhotoPhotoStreamAlbumTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiPhotoPhotoStreamAlbumTypeIdentifier"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/medialibrary/mliphotophotostreamalbumtypeidentifier"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/medialibrary/mliphotophotostreamalbumtypeidentifier"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
