{
  "abstract": [
    {
      "text": "The media group that represents the Purchased playlist in iTunes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.medialibrary/documentation/MediaLibrary"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesPurchasedPlaylistTypeIdentifier"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@MLiTunesPurchasedPlaylistTypeIdentifier",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MLiTunesPurchasedPlaylistTypeIdentifier"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "Media Library"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MLiTunesPurchasedPlaylistTypeIdentifier"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.15",
        "introducedAt": "10.9",
        "message": "MediaLibrary.framework will be removed in a future OS version. Use Photos.framework or iTunesLibrary.framework instead.",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "MLiTunesPurchasedPlaylistTypeIdentifier"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MLiTunesPurchasedPlaylistTypeIdentifier"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary": {
      "abstract": [
        {
          "text": "Access read-only collections of the user’s multimedia content.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Library",
      "type": "topic",
      "url": "/documentation/medialibrary"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesAudioBooksPlaylistTypeIdentifier": {
      "abstract": [
        {
          "text": "The media group that represents the Audio Books playlist in iTunes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiTunesAudioBooksPlaylistTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesAudioBooksPlaylistTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiTunesAudioBooksPlaylistTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiTunesAudioBooksPlaylistTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlitunesaudiobooksplaylisttypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesFolderPlaylistTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a folder in iTunes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiTunesFolderPlaylistTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesFolderPlaylistTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiTunesFolderPlaylistTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiTunesFolderPlaylistTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlitunesfolderplaylisttypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesGeniusPlaylistTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a genius playlist in iTunes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiTunesGeniusPlaylistTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesGeniusPlaylistTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiTunesGeniusPlaylistTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiTunesGeniusPlaylistTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlitunesgeniusplaylisttypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesMoviesPlaylistTypeIdentifier": {
      "abstract": [
        {
          "text": "The media group that represents the Movies playlist in iTunes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiTunesMoviesPlaylistTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesMoviesPlaylistTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiTunesMoviesPlaylistTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiTunesMoviesPlaylistTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlitunesmoviesplaylisttypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesMusicPlaylistTypeIdentifier": {
      "abstract": [
        {
          "text": "The media group that represents the Music playlist in iTunes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiTunesMusicPlaylistTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesMusicPlaylistTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiTunesMusicPlaylistTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiTunesMusicPlaylistTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlitunesmusicplaylisttypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesPlaylistTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a user-created playlist in iTunes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiTunesPlaylistTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesPlaylistTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiTunesPlaylistTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiTunesPlaylistTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlitunesplaylisttypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesPodcastPlaylistTypeIdentifier": {
      "abstract": [
        {
          "text": "The media group that represents the Podcast playlist in iTunes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiTunesPodcastPlaylistTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesPodcastPlaylistTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiTunesPodcastPlaylistTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiTunesPodcastPlaylistTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlitunespodcastplaylisttypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesPurchasedPlaylistTypeIdentifier": {
      "abstract": [
        {
          "text": "The media group that represents the Purchased playlist in iTunes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiTunesPurchasedPlaylistTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesPurchasedPlaylistTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiTunesPurchasedPlaylistTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiTunesPurchasedPlaylistTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlitunespurchasedplaylisttypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesRootGroupTypeIdentifier": {
      "abstract": [
        {
          "text": "The root media group for iTunes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiTunesRootGroupTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesRootGroupTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiTunesRootGroupTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiTunesRootGroupTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlitunesrootgrouptypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesSavedGeniusPlaylistTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a saved genius playlist in iTunes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiTunesSavedGeniusPlaylistTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesSavedGeniusPlaylistTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiTunesSavedGeniusPlaylistTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiTunesSavedGeniusPlaylistTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlitunessavedgeniusplaylisttypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesSmartPlaylistTypeIdentifier": {
      "abstract": [
        {
          "text": "A media group that represents a smart playlist in iTunes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiTunesSmartPlaylistTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesSmartPlaylistTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiTunesSmartPlaylistTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiTunesSmartPlaylistTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlitunessmartplaylisttypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesTVShowsPlaylistTypeIdentifier": {
      "abstract": [
        {
          "text": "The media group that represents the TV Shows playlist in iTunes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiTunesTVShowsPlaylistTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesTVShowsPlaylistTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiTunesTVShowsPlaylistTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiTunesTVShowsPlaylistTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlitunestvshowsplaylisttypeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesiTunesUPlaylistTypeIdentifier": {
      "abstract": [
        {
          "text": "The media group that represents the iTunes U playlist in iTunes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLiTunesiTunesUPlaylistTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesiTunesUPlaylistTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLiTunesiTunesUPlaylistTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLiTunesiTunesUPlaylistTypeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlitunesitunesuplaylisttypeidentifier"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesRootGroupTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesPlaylistTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesSmartPlaylistTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesGeniusPlaylistTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesSavedGeniusPlaylistTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesFolderPlaylistTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesAudioBooksPlaylistTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesiTunesUPlaylistTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesMoviesPlaylistTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesMusicPlaylistTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesPodcastPlaylistTypeIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesTVShowsPlaylistTypeIdentifier"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.15",
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MLiTunesPurchasedPlaylistTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiTunesPurchasedPlaylistTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.medialibrary/documentation/MediaLibrary"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesRootGroupTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesPlaylistTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesSmartPlaylistTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesGeniusPlaylistTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesSavedGeniusPlaylistTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesFolderPlaylistTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesAudioBooksPlaylistTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesiTunesUPlaylistTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesMoviesPlaylistTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesMusicPlaylistTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesPodcastPlaylistTypeIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLiTunesTVShowsPlaylistTypeIdentifier"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MLiTunesPurchasedPlaylistTypeIdentifier"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiTunesGeniusPlaylistTypeIdentifier/title",
          "value": "MLiTunesGeniusPlaylistTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiTunesGeniusPlaylistTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiTunesGeniusPlaylistTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiTunesAudioBooksPlaylistTypeIdentifier/title",
          "value": "MLiTunesAudioBooksPlaylistTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiTunesAudioBooksPlaylistTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiTunesAudioBooksPlaylistTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiTunesFolderPlaylistTypeIdentifier/title",
          "value": "MLiTunesFolderPlaylistTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiTunesFolderPlaylistTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiTunesFolderPlaylistTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiTunesPlaylistTypeIdentifier/title",
          "value": "MLiTunesPlaylistTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiTunesPlaylistTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiTunesPlaylistTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiTunesSavedGeniusPlaylistTypeIdentifier/title",
          "value": "MLiTunesSavedGeniusPlaylistTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiTunesSavedGeniusPlaylistTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiTunesSavedGeniusPlaylistTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiTunesMusicPlaylistTypeIdentifier/title",
          "value": "MLiTunesMusicPlaylistTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiTunesMusicPlaylistTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiTunesMusicPlaylistTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiTunesPodcastPlaylistTypeIdentifier/title",
          "value": "MLiTunesPodcastPlaylistTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiTunesPodcastPlaylistTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiTunesPodcastPlaylistTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiTunesSmartPlaylistTypeIdentifier/title",
          "value": "MLiTunesSmartPlaylistTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiTunesSmartPlaylistTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiTunesSmartPlaylistTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiTunesiTunesUPlaylistTypeIdentifier/title",
          "value": "MLiTunesiTunesUPlaylistTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiTunesiTunesUPlaylistTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiTunesiTunesUPlaylistTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiTunesRootGroupTypeIdentifier/title",
          "value": "MLiTunesRootGroupTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiTunesRootGroupTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiTunesRootGroupTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiTunesTVShowsPlaylistTypeIdentifier/title",
          "value": "MLiTunesTVShowsPlaylistTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiTunesTVShowsPlaylistTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiTunesTVShowsPlaylistTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiTunesPurchasedPlaylistTypeIdentifier/title",
          "value": "MLiTunesPurchasedPlaylistTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiTunesPurchasedPlaylistTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiTunesPurchasedPlaylistTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiTunesMoviesPlaylistTypeIdentifier/title",
          "value": "MLiTunesMoviesPlaylistTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLiTunesMoviesPlaylistTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLiTunesMoviesPlaylistTypeIdentifier"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/medialibrary/mlitunespurchasedplaylisttypeidentifier"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/medialibrary/mlitunespurchasedplaylisttypeidentifier"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
