{
  "abstract": [
    {
      "text": "Specifies the media object’s resolution. The value for this key is a string (",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": ") intended to be converted to a size (",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.documentation/documentation/foundation/nssize",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": ") using the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.documentation/documentation/foundation/1391112-nssizefromstring",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " method.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.medialibrary/documentation/MediaLibrary"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectResolutionStringKey"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@MLMediaObjectResolutionStringKey",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MLMediaObjectResolutionStringKey"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "Media Library"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MLMediaObjectResolutionStringKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.15",
        "introducedAt": "10.9",
        "message": "MediaLibrary.framework will be removed in a future OS version. Use Photos.framework or iTunesLibrary.framework instead.",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "MLMediaObjectResolutionStringKey"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MLMediaObjectResolutionStringKey"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/foundation/1391112-nssizefromstring": {
      "abstract": [
        {
          "text": "Returns an `NSSize` from a text-based representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "NSSizeFromString"
        },
        {
          "kind": "text",
          "text": "(String) -> NSSize"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/1391112-nssizefromstring",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSizeFromString(_:)",
      "type": "topic",
      "url": "/documentation/foundation/1391112-nssizefromstring"
    },
    "doc://com.apple.documentation/documentation/foundation/nsarray": {
      "abstract": [
        {
          "text": "An object representing a static ordered collection, for use instead of an  constant in cases that require reference semantics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSArray"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsarray",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSArray",
      "type": "topic",
      "url": "/documentation/foundation/nsarray"
    },
    "doc://com.apple.documentation/documentation/foundation/nsnumber": {
      "abstract": [
        {
          "text": "An object wrapper for primitive scalar numeric values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNumber",
      "type": "topic",
      "url": "/documentation/foundation/nsnumber"
    },
    "doc://com.apple.documentation/documentation/foundation/nssize": {
      "abstract": [
        {
          "text": "A two-dimensional size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSSize"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nssize",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSize",
      "type": "topic",
      "url": "/documentation/foundation/nssize"
    },
    "doc://com.apple.documentation/documentation/foundation/nsstring": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary": {
      "abstract": [
        {
          "text": "Access read-only collections of the user’s multimedia content.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Library",
      "type": "topic",
      "url": "/documentation/medialibrary"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectAlbumKey": {
      "abstract": [
        {
          "text": "Specifies the media object’s album. The value for this key is a string (",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaObjectAlbumKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectAlbumKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaObjectAlbumKey"
        }
      ],
      "role": "symbol",
      "title": "MLMediaObjectAlbumKey",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediaobjectalbumkey"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectArtistKey": {
      "abstract": [
        {
          "text": "Specifies the media object’s artist. The value for this key is a string (",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaObjectArtistKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectArtistKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaObjectArtistKey"
        }
      ],
      "role": "symbol",
      "title": "MLMediaObjectArtistKey",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediaobjectartistkey"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectBitRateKey": {
      "abstract": [
        {
          "text": "Specifies the media object’s bit rate, in kilobits per second. The value for this key is a number (",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaObjectBitRateKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectBitRateKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaObjectBitRateKey"
        }
      ],
      "role": "symbol",
      "title": "MLMediaObjectBitRateKey",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediaobjectbitratekey"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectChannelCountKey": {
      "abstract": [
        {
          "text": "Specifies the media object’s channel count. The value for this key is a number (",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaObjectChannelCountKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectChannelCountKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaObjectChannelCountKey"
        }
      ],
      "role": "symbol",
      "title": "MLMediaObjectChannelCountKey",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediaobjectchannelcountkey"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectCommentsKey": {
      "abstract": [
        {
          "text": "Specifies the contents of the comments field associated with the media object. The value for this key is a string (",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaObjectCommentsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectCommentsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaObjectCommentsKey"
        }
      ],
      "role": "symbol",
      "title": "MLMediaObjectCommentsKey",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediaobjectcommentskey"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectDurationKey": {
      "abstract": [
        {
          "text": "Specifies the media object’s duration, in seconds. The value for this key is a number (",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaObjectDurationKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectDurationKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaObjectDurationKey"
        }
      ],
      "role": "symbol",
      "title": "MLMediaObjectDurationKey",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediaobjectdurationkey"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectGenreKey": {
      "abstract": [
        {
          "text": "Specifies the media object’s genre. The value for this key is a string (",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaObjectGenreKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectGenreKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaObjectGenreKey"
        }
      ],
      "role": "symbol",
      "title": "MLMediaObjectGenreKey",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediaobjectgenrekey"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectKeywordsKey": {
      "abstract": [
        {
          "text": "Specifies the keywords associated with the media object. The value for this key is an array (",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsarray",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ") of strings (",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaObjectKeywordsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectKeywordsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaObjectKeywordsKey"
        }
      ],
      "role": "symbol",
      "title": "MLMediaObjectKeywordsKey",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediaobjectkeywordskey"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectKindKey": {
      "abstract": [
        {
          "text": "Used by iTunes only. Specifies the media object’s file format (shown in the “Kind” column in iTunes). The value for this key is a string (",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaObjectKindKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectKindKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaObjectKindKey"
        }
      ],
      "role": "symbol",
      "title": "MLMediaObjectKindKey",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediaobjectkindkey"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectProtectedKey": {
      "abstract": [
        {
          "text": "Specifies whether the media object is protected by DRM (Digital Rights Management). The value for this key is a number (",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": "), 0 or 1, that represents a Boolean value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaObjectProtectedKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectProtectedKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaObjectProtectedKey"
        }
      ],
      "role": "symbol",
      "title": "MLMediaObjectProtectedKey",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediaobjectprotectedkey"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectResolutionStringKey": {
      "abstract": [
        {
          "text": "Specifies the media object’s resolution. The value for this key is a string (",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ") intended to be converted to a size (",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nssize",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ") using the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/1391112-nssizefromstring",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaObjectResolutionStringKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectResolutionStringKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaObjectResolutionStringKey"
        }
      ],
      "role": "symbol",
      "title": "MLMediaObjectResolutionStringKey",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediaobjectresolutionstringkey"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectSampleRateKey": {
      "abstract": [
        {
          "text": "Specifies the media object’s sample rate, in samples per second (Hz). The value for this key is a number (",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaObjectSampleRateKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectSampleRateKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaObjectSampleRateKey"
        }
      ],
      "role": "symbol",
      "title": "MLMediaObjectSampleRateKey",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediaobjectsampleratekey"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectTrackNumberKey": {
      "abstract": [
        {
          "text": "Specifies the media object’s track number. The value for this key is a number (",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaObjectTrackNumberKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectTrackNumberKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaObjectTrackNumberKey"
        }
      ],
      "role": "symbol",
      "title": "MLMediaObjectTrackNumberKey",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediaobjecttracknumberkey"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectDurationKey",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectArtistKey",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectAlbumKey",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectGenreKey",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectKindKey",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectTrackNumberKey",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectBitRateKey",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectSampleRateKey",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectChannelCountKey",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectCommentsKey",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectKeywordsKey",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectProtectedKey"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.15",
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MLMediaObjectResolutionStringKey"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaObjectResolutionStringKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.medialibrary/documentation/MediaLibrary"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectDurationKey",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectArtistKey",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectAlbumKey",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectGenreKey",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectKindKey",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectTrackNumberKey",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectBitRateKey",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectSampleRateKey",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectChannelCountKey",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectCommentsKey",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectKeywordsKey",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObjectProtectedKey"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MLMediaObjectResolutionStringKey"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObjectGenreKey/title",
          "value": "MLMediaObjectGenreKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObjectGenreKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaObjectGenreKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsstring/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObjectChannelCountKey/title",
          "value": "MLMediaObjectChannelCountKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObjectChannelCountKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaObjectChannelCountKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObjectArtistKey/title",
          "value": "MLMediaObjectArtistKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObjectArtistKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaObjectArtistKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObjectCommentsKey/title",
          "value": "MLMediaObjectCommentsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObjectCommentsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaObjectCommentsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObjectResolutionStringKey/title",
          "value": "MLMediaObjectResolutionStringKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObjectResolutionStringKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaObjectResolutionStringKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObjectDurationKey/title",
          "value": "MLMediaObjectDurationKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObjectDurationKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaObjectDurationKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObjectKindKey/title",
          "value": "MLMediaObjectKindKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObjectKindKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaObjectKindKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObjectBitRateKey/title",
          "value": "MLMediaObjectBitRateKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObjectBitRateKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaObjectBitRateKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObjectTrackNumberKey/title",
          "value": "MLMediaObjectTrackNumberKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObjectTrackNumberKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaObjectTrackNumberKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObjectKeywordsKey/title",
          "value": "MLMediaObjectKeywordsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObjectKeywordsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaObjectKeywordsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsarray/abstract",
          "value": [
            {
              "text": "A static ordered collection of objects.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObjectSampleRateKey/title",
          "value": "MLMediaObjectSampleRateKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObjectSampleRateKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaObjectSampleRateKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObjectProtectedKey/title",
          "value": "MLMediaObjectProtectedKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObjectProtectedKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaObjectProtectedKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObjectAlbumKey/title",
          "value": "MLMediaObjectAlbumKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObjectAlbumKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaObjectAlbumKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~11391112-nssizefromstring/title",
          "value": "NSSizeFromString"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/medialibrary/mlmediaobjectresolutionstringkey"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/medialibrary/mlmediaobjectresolutionstringkey"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
