{
  "abstract": [
    {
      "text": "Specifies the source type associated with a particular media source. Source type reflects the primary type of media within the source. These constants are used to specify values for ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadSourceTypesKey",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " in the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLibrary/init(options:)",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " method of ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLibrary",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": ".",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.medialibrary/documentation/MediaLibrary"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MLMediaSourceType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MLMediaSourceType"
      }
    ],
    "modules": [
      {
        "name": "Media Library"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MLMediaSourceType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.15",
        "introducedAt": "10.9",
        "message": "MediaLibrary.framework will be removed in a future OS version. Use Photos.framework or iTunesLibrary.framework instead.",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "MLMediaSourceType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MLMediaSourceType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary": {
      "abstract": [
        {
          "text": "Access read-only collections of the user’s multimedia content.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Library",
      "type": "topic",
      "url": "/documentation/medialibrary"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/typeIdentifier": {
      "abstract": [
        {
          "text": "An identifier for the media group’s type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "typeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/typeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "typeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "typeIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediagroup/typeidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLibrary": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "MLMediaLibrary",
          "type": "codeVoice"
        },
        {
          "text": " class provides an interface for accessing a collection of media objects from various sources. It serves as the initial access point of the Media Library framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaLibrary"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLibrary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaLibrary"
        }
      ],
      "role": "symbol",
      "title": "MLMediaLibrary",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmedialibrary"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLibrary/init(options:)": {
      "abstract": [
        {
          "text": "Initializes the media library based on the specified load options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLibrary/init(options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithOptions:"
        }
      ],
      "role": "symbol",
      "title": "init(options:)",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmedialibrary/init(options:)"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppFoldersKey": {
      "abstract": [
        {
          "text": "Specifies one or more relative paths inside the caller’s app bundle in which to search for media files. The value for this key is an array of strings (relative paths inside the caller’s app bundle).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaLoadAppFoldersKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppFoldersKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaLoadAppFoldersKey"
        }
      ],
      "role": "symbol",
      "title": "MLMediaLoadAppFoldersKey",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmedialoadappfolderskey"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppleLoops": {
      "abstract": [
        {
          "text": "Identifies the folder containing audio loops from Apple.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaLoadAppleLoops"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppleLoops",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaLoadAppleLoops"
        }
      ],
      "role": "symbol",
      "title": "MLMediaLoadAppleLoops",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmedialoadappleloops"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadExcludeSourcesKey": {
      "abstract": [
        {
          "text": "Defines which media sources to exclude when loading. This option is processed after ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadIncludeSourcesKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ". The value for this key is an array of strings (media source identifiers). For a list of valid media source identifiers, see ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/media-source-identifiers",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaLoadExcludeSourcesKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadExcludeSourcesKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaLoadExcludeSourcesKey"
        }
      ],
      "role": "symbol",
      "title": "MLMediaLoadExcludeSourcesKey",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmedialoadexcludesourceskey"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadFoldersKey": {
      "abstract": [
        {
          "text": "Specifies the well-known folders that should be searched for media files. If this key is not present, none of the well-known folders will be provided. The value for this key is an array of strings (identifiers that correspond to well-known folder locations). For a list of well-known folder identifiers, see ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/well-known-folder-identifiers",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaLoadFoldersKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadFoldersKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaLoadFoldersKey"
        }
      ],
      "role": "symbol",
      "title": "MLMediaLoadFoldersKey",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmedialoadfolderskey"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadIncludeSourcesKey": {
      "abstract": [
        {
          "text": "Defines which media sources to include when loading. If not present, load all available media sources. This option is processed after ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadSourceTypesKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ". If ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadIncludeSourcesKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " is present but ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadSourceTypesKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " is not, then only those sources specified here will be loaded. This is useful for loading a single media source. When both keys are present, this is useful for adding one or more media sources that normally would not appear for the requested library type. The value for this key is an array of strings (media source identifiers). For a list of valid media source identifiers, see ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/media-source-identifiers",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaLoadIncludeSourcesKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadIncludeSourcesKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaLoadIncludeSourcesKey"
        }
      ],
      "role": "symbol",
      "title": "MLMediaLoadIncludeSourcesKey",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmedialoadincludesourceskey"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadMoviesFolder": {
      "abstract": [
        {
          "text": "Identifies the user’s Movies folder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaLoadMoviesFolder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadMoviesFolder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaLoadMoviesFolder"
        }
      ],
      "role": "symbol",
      "title": "MLMediaLoadMoviesFolder",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmedialoadmoviesfolder"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadSourceTypesKey": {
      "abstract": [
        {
          "text": "Defines which sources to load based on library type. If not present, this will load all sources. The value for this key is a media source type. For a list of valid media source types, see ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceType",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaLoadSourceTypesKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadSourceTypesKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaLoadSourceTypesKey"
        }
      ],
      "role": "symbol",
      "title": "MLMediaLoadSourceTypesKey",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmedialoadsourcetypeskey"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceApertureIdentifier": {
      "abstract": [
        {
          "text": "The media source providing content from Aperture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaSourceApertureIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceApertureIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaSourceApertureIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLMediaSourceApertureIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediasourceapertureidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceAppDefinedFoldersIdentifier": {
      "abstract": [
        {
          "text": "The media source for app-defined folders. This identifies a media source created from a relative path inside the caller’s app bundle. This source provides data when ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppFoldersKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " is provided in the options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaSourceAppDefinedFoldersIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceAppDefinedFoldersIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaSourceAppDefinedFoldersIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLMediaSourceAppDefinedFoldersIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediasourceappdefinedfoldersidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceCustomFoldersIdentifier": {
      "abstract": [
        {
          "text": "The media source for custom folders. Currently, the only custom folder is the folder containing audio loops from Apple. This source provides data when ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadFoldersKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " is provided with the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppleLoops",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaSourceCustomFoldersIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceCustomFoldersIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaSourceCustomFoldersIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MLMediaSourceCustomFoldersIdentifier",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediasourcecustomfoldersidentifier"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceType": {
      "abstract": [
        {
          "text": "Specifies the source type associated with a particular media source. Source type reflects the primary type of media within the source. These constants are used to specify values for ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadSourceTypesKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " in the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLibrary/init(options:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLibrary",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaSourceType"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaSourceType"
        }
      ],
      "role": "symbol",
      "title": "MLMediaSourceType",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediasourcetype"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceType/audio": {
      "abstract": [
        {
          "text": "Audio source type. Includes iTunes, GarageBand, and Logic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audio"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLMediaSourceType",
          "text": "MLMediaSourceType"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceType/audio",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaSourceTypeAudio"
        }
      ],
      "role": "symbol",
      "title": "audio",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediasourcetype/audio"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceType/image": {
      "abstract": [
        {
          "text": "Image source type. Includes iPhoto, Aperture, and Photo Booth.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "image"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLMediaSourceType",
          "text": "MLMediaSourceType"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceType/image",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaSourceTypeImage"
        }
      ],
      "role": "symbol",
      "title": "image",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediasourcetype/image"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediasourcetype/init(rawvalue:)"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceType/movie": {
      "abstract": [
        {
          "text": "Movie source type. Includes iMovie and Final Cut Pro.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "movie"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLMediaSourceType",
          "text": "MLMediaSourceType"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceType/movie",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaSourceTypeMovie"
        }
      ],
      "role": "symbol",
      "title": "movie",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediasourcetype/movie"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/aperture-media-group-type-identifiers": {
      "abstract": [
        {
          "text": "Identifiers for media group types in the Aperture media source. These constants are used to specify a media group’s ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/typeIdentifier",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " attribute.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/aperture-media-group-type-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Aperture Media Group Type Identifiers",
      "type": "topic",
      "url": "/documentation/medialibrary/aperture-media-group-type-identifiers"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/final-cut-pro-media-group-type-identifiers": {
      "abstract": [
        {
          "text": "Identifiers for media group types in the Final Cut Pro media source. These constants are used to specify a media group’s ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/typeIdentifier",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " attribute.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/final-cut-pro-media-group-type-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Final Cut Pro Media Group Type Identifiers",
      "type": "topic",
      "url": "/documentation/medialibrary/final-cut-pro-media-group-type-identifiers"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/folders-media-group-type-identifiers": {
      "abstract": [
        {
          "text": "Identifiers for media group types in folder-based media sources. These constants are used to specify a media group’s ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/typeIdentifier",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " attribute.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/folders-media-group-type-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Folders Media Group Type Identifiers",
      "type": "topic",
      "url": "/documentation/medialibrary/folders-media-group-type-identifiers"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/garageband-media-group-type-identifiers": {
      "abstract": [
        {
          "text": "Identifiers for media group types in the GarageBand media source. These constants are used to specify a media group’s ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/typeIdentifier",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " attribute.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/garageband-media-group-type-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GarageBand Media Group Type Identifiers",
      "type": "topic",
      "url": "/documentation/medialibrary/garageband-media-group-type-identifiers"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/logic-media-group-type-identifiers": {
      "abstract": [
        {
          "text": "Identifiers for media group types in the Logic media source. These constants are used to specify a media group’s ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/typeIdentifier",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " attribute.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/logic-media-group-type-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Logic Media Group Type Identifiers",
      "type": "topic",
      "url": "/documentation/medialibrary/logic-media-group-type-identifiers"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/media-source-identifiers": {
      "abstract": [
        {
          "text": "Identifiers for media sources which correspond to apps used to manage groups of media objects. Used with ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/load-options-keys",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/media-source-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Media Source Identifiers",
      "type": "topic",
      "url": "/documentation/medialibrary/media-source-identifiers"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/well-known-folder-identifiers": {
      "abstract": [
        {
          "text": "Identifiers for well-known media folders used to specify the value for ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadFoldersKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/well-known-folder-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Well-Known Folder Identifiers",
      "type": "topic",
      "url": "/documentation/medialibrary/well-known-folder-identifiers"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.medialibrary/documentation/MediaLibrary/aperture-media-group-type-identifiers",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/final-cut-pro-media-group-type-identifiers",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/folders-media-group-type-identifiers",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/garageband-media-group-type-identifiers",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/logic-media-group-type-identifiers",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppFoldersKey",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppleLoops",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadExcludeSourcesKey",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadFoldersKey",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadIncludeSourcesKey",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadMoviesFolder",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadSourceTypesKey",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceApertureIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceAppDefinedFoldersIdentifier",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceCustomFoldersIdentifier"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceType/audio",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceType/image",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceType/movie"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.15",
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MLMediaSourceType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaSourceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaSourceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.medialibrary/documentation/MediaLibrary"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceType/audio",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceType/image",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceType/movie"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.medialibrary/documentation/MediaLibrary/aperture-media-group-type-identifiers",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/final-cut-pro-media-group-type-identifiers",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/folders-media-group-type-identifiers",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/garageband-media-group-type-identifiers",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/logic-media-group-type-identifiers",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppFoldersKey",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadAppleLoops",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadExcludeSourcesKey",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadFoldersKey",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadIncludeSourcesKey",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadMoviesFolder",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadSourceTypesKey",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceApertureIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceAppDefinedFoldersIdentifier",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceCustomFoldersIdentifier"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MLMediaSourceType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceAppDefinedFoldersIdentifier/title",
          "value": "MLMediaSourceAppDefinedFoldersIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceAppDefinedFoldersIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaSourceAppDefinedFoldersIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadIncludeSourcesKey/title",
          "value": "MLMediaLoadIncludeSourcesKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadIncludeSourcesKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaLoadIncludeSourcesKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadAppFoldersKey/title",
          "value": "MLMediaLoadAppFoldersKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadAppFoldersKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaLoadAppFoldersKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadFoldersKey/title",
          "value": "MLMediaLoadFoldersKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadFoldersKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaLoadFoldersKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaGroup~1typeIdentifier/title",
          "value": "typeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaGroup~1typeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "typeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceType~1audio/title",
          "value": "MLMediaSourceTypeAudio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceType~1audio/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaSourceTypeAudio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLibrary/title",
          "value": "MLMediaLibrary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLibrary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaLibrary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLibrary/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaLibrary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceType/title",
          "value": "MLMediaSourceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaSourceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaSourceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadAppleLoops/title",
          "value": "MLMediaLoadAppleLoops"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadAppleLoops/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaLoadAppleLoops"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceCustomFoldersIdentifier/title",
          "value": "MLMediaSourceCustomFoldersIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceCustomFoldersIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaSourceCustomFoldersIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadMoviesFolder/title",
          "value": "MLMediaLoadMoviesFolder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadMoviesFolder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaLoadMoviesFolder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceType~1image/title",
          "value": "MLMediaSourceTypeImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceType~1image/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaSourceTypeImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceType~1movie/title",
          "value": "MLMediaSourceTypeMovie"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceType~1movie/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaSourceTypeMovie"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadExcludeSourcesKey/title",
          "value": "MLMediaLoadExcludeSourcesKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadExcludeSourcesKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaLoadExcludeSourcesKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceApertureIdentifier/title",
          "value": "MLMediaSourceApertureIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceApertureIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaSourceApertureIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadSourceTypesKey/title",
          "value": "MLMediaLoadSourceTypesKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadSourceTypesKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaLoadSourceTypesKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLibrary~1init(options:)/title",
          "value": "initWithOptions:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLibrary~1init(options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithOptions:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/medialibrary/mlmediasourcetype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/medialibrary/mlmediasourcetype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
