{
  "abstract": [
    {
      "text": "Constants that indicate errors in the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " domain.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit",
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension",
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern",
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/Error"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/Error/Code"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@WKWebExtensionMatchPatternError",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "platforms": [
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "2.4",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "WKWebExtension.MatchPattern.Error.Code"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Code"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension": {
      "abstract": [
        {
          "text": "An object that encapsulates a web extension’s resources that the manifest file defines.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKWebExtension"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebExtension"
        }
      ],
      "role": "symbol",
      "title": "WKWebExtension",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern": {
      "abstract": [
        {
          "text": "An object that represents a way to specify groups of URLs.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MatchPattern"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MatchPattern"
        }
      ],
      "role": "symbol",
      "title": "WKWebExtension.MatchPattern",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/matchpattern"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/Error": {
      "abstract": [
        {
          "text": "Constants that indicate errors in the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " domain.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/Error",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Error"
        }
      ],
      "role": "symbol",
      "title": "WKWebExtension.MatchPattern.Error",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/matchpattern/error"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/Error/Code": {
      "abstract": [
        {
          "text": "Constants that indicate errors in the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " domain.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/Error/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "WKWebExtension.MatchPattern.Error.Code",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/matchpattern/error/code"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/Error/Code/init(rawValue:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/Error/Code/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/matchpattern/error/code/init(rawvalue:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/Error/Code/invalidHost": {
      "abstract": [
        {
          "text": "Indicates that the host component was invalid.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidHost"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/Error/Code/invalidHost",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebExtensionMatchPatternErrorInvalidHost"
        }
      ],
      "role": "symbol",
      "title": "WKWebExtension.MatchPattern.Error.Code.invalidHost",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/matchpattern/error/code/invalidhost"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/Error/Code/invalidPath": {
      "abstract": [
        {
          "text": "Indicates that the path component was invalid.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidPath"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/Error/Code/invalidPath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebExtensionMatchPatternErrorInvalidPath"
        }
      ],
      "role": "symbol",
      "title": "WKWebExtension.MatchPattern.Error.Code.invalidPath",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/matchpattern/error/code/invalidpath"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/Error/Code/invalidScheme": {
      "abstract": [
        {
          "text": "Indicates that the scheme component was invalid.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidScheme"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/Error/Code/invalidScheme",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebExtensionMatchPatternErrorInvalidScheme"
        }
      ],
      "role": "symbol",
      "title": "WKWebExtension.MatchPattern.Error.Code.invalidScheme",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/matchpattern/error/code/invalidscheme"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/Error/Code/unknown": {
      "abstract": [
        {
          "text": "Indicates that an unknown error occurred.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/Error/Code/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebExtensionMatchPatternErrorUnknown"
        }
      ],
      "role": "symbol",
      "title": "WKWebExtension.MatchPattern.Error.Code.unknown",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/matchpattern/error/code/unknown"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/errorDomain": {
      "abstract": [
        {
          "text": "A string that identifies the error domain.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/errorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebExtensionMatchPatternErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "errorDomain",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/matchpattern/errordomain"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/Error",
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/errorDomain"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/Error/Code/invalidHost",
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/Error/Code/invalidPath",
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/Error/Code/invalidScheme",
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/Error/Code/unknown"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/Error/Code/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "2.4",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "WKWebExtensionMatchPatternError"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionMatchPatternError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionMatchPatternError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.webkit/documentation/WebKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/Error/Code/invalidHost",
                "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/Error/Code/invalidPath",
                "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/Error/Code/invalidScheme",
                "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/Error/Code/unknown"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/MatchPattern/errorDomain"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "WKWebExtensionMatchPatternError"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern~1Error~1Code~1invalidScheme/title",
          "value": "WKWebExtensionMatchPatternErrorInvalidScheme"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern~1Error~1Code~1invalidScheme/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionMatchPatternErrorInvalidScheme"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern/title",
          "value": "WKWebExtensionMatchPattern"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionMatchPattern"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionMatchPattern"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern~1Error~1Code/title",
          "value": "WKWebExtensionMatchPatternError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern~1Error~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionMatchPatternError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern~1Error~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionMatchPatternError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern~1Error~1Code~1invalidPath/title",
          "value": "WKWebExtensionMatchPatternErrorInvalidPath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern~1Error~1Code~1invalidPath/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionMatchPatternErrorInvalidPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern~1Error~1Code~1unknown/title",
          "value": "WKWebExtensionMatchPatternErrorUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern~1Error~1Code~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionMatchPatternErrorUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern~1errorDomain/title",
          "value": "WKWebExtensionMatchPatternErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern~1errorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionMatchPatternErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern~1Error~1Code~1invalidHost/title",
          "value": "WKWebExtensionMatchPatternErrorInvalidHost"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1MatchPattern~1Error~1Code~1invalidHost/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionMatchPatternErrorInvalidHost"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension/title",
          "value": "WKWebExtension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtension"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/wkwebextension/matchpattern/error/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/webkit/wkwebextension/matchpattern/error/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
