{
  "abstract": [
    {
      "text": "A type alias for a double-precision 4 x 4 matrix.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/double4x4"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:4simd9double4x4a",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "double4x4"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "double4x4"
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "double4x4"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "double4x4"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4x4",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@simd_double4x4",
              "text": "simd_double4x4"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/double4x4": {
      "abstract": [
        {
          "text": "A type alias for a double-precision 4 x 4 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "double4x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/double4x4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "double4x4"
        }
      ],
      "role": "symbol",
      "title": "double4x4",
      "type": "topic",
      "url": "/documentation/simd/double4x4"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_double4x4": {
      "abstract": [
        {
          "text": "A type alias for a double-precision 4 x 4 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matrix_double4x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_double4x4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "matrix_double4x4"
        }
      ],
      "role": "symbol",
      "title": "matrix_double4x4",
      "type": "topic",
      "url": "/documentation/simd/matrix_double4x4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double4x4": {
      "abstract": [
        {
          "text": "A matrix of four columns and four rows that contains double-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_double4x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4x4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_double4x4"
        }
      ],
      "role": "symbol",
      "title": "simd_double4x4",
      "type": "topic",
      "url": "/documentation/simd/simd_double4x4"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Type-Aliases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/matrix_double4x4"
      ],
      "title": "Type Aliases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1matrix_double4x4/title",
          "value": "matrix_double4x4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1matrix_double4x4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "matrix_double4x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1matrix_double4x4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "matrix_double4x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4x4/title",
          "value": "simd_double4x4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4x4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double4x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4x4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double4x4"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/double4x4"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
