{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/exp(_:)-9nl1f"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:4simd3expySo0A6_quatdaADF",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "exp"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@simd_quatd",
        "text": "simd_quatd"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@simd_quatd",
        "text": "simd_quatd"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "exp(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "exp"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "q"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_quatd",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@simd_quatd",
              "text": "simd_quatd"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_quatd",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@simd_quatd",
              "text": "simd_quatd"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/exp(_:)-9nl1f": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exp"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_quatd",
          "text": "simd_quatd"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_quatd",
          "text": "simd_quatd"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/exp(_:)-9nl1f",
      "kind": "symbol",
      "role": "symbol",
      "title": "exp(_:)",
      "type": "topic",
      "url": "/documentation/simd/exp(_:)-9nl1f"
    },
    "doc://com.apple.accelerate/documentation/simd/log(_:)-77xdo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "log"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_quatd",
          "text": "simd_quatd"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_quatd",
          "text": "simd_quatd"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/log(_:)-77xdo",
      "kind": "symbol",
      "role": "symbol",
      "title": "log(_:)",
      "type": "topic",
      "url": "/documentation/simd/log(_:)-77xdo"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_add(_:_:)-6ohmq": {
      "abstract": [
        {
          "text": "Returns the sum of two quaternions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_add"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_quatd",
          "text": "simd_quatd"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_quatd",
          "text": "simd_quatd"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_quatd",
          "text": "simd_quatd"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_add(_:_:)-6ohmq",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_add"
        }
      ],
      "role": "symbol",
      "title": "simd_add(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_add(_:_:)-6ohmq"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_mul(_:_:)-531pe": {
      "abstract": [
        {
          "text": "Returns the product of two quaternions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_mul"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_quatd",
          "text": "simd_quatd"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_quatd",
          "text": "simd_quatd"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_quatd",
          "text": "simd_quatd"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_mul(_:_:)-531pe",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_mul"
        }
      ],
      "role": "symbol",
      "title": "simd_mul(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_mul(_:_:)-531pe"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_mul(_:_:)-8aedk": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_mul"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_quatd",
          "text": "simd_quatd"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_quatd",
          "text": "simd_quatd"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_mul(_:_:)-8aedk",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_mul"
        }
      ],
      "role": "symbol",
      "title": "simd_mul(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_mul(_:_:)-8aedk"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_mul(_:_:)-8uidm": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_mul"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_quatd",
          "text": "simd_quatd"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_quatd",
          "text": "simd_quatd"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_mul(_:_:)-8uidm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_mul"
        }
      ],
      "role": "symbol",
      "title": "simd_mul(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_mul(_:_:)-8uidm"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_quatd": {
      "abstract": [
        {
          "text": "A double-precision quaternion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_quatd"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_quatd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_quatd"
        }
      ],
      "role": "symbol",
      "title": "simd_quatd",
      "type": "topic",
      "url": "/documentation/simd/simd_quatd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_sub(_:_:)-87caf": {
      "abstract": [
        {
          "text": "Returns the difference between two quaternions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_sub"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_quatd",
          "text": "simd_quatd"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_quatd",
          "text": "simd_quatd"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_quatd",
          "text": "simd_quatd"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_sub(_:_:)-87caf",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_sub"
        }
      ],
      "role": "symbol",
      "title": "simd_sub(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_sub(_:_:)-87caf"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Applying-arithmetic-operations-to-quaternions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_add(_:_:)-6ohmq",
        "doc://com.apple.accelerate/documentation/simd/simd_mul(_:_:)-531pe",
        "doc://com.apple.accelerate/documentation/simd/simd_mul(_:_:)-8aedk",
        "doc://com.apple.accelerate/documentation/simd/simd_mul(_:_:)-8uidm",
        "doc://com.apple.accelerate/documentation/simd/simd_sub(_:_:)-87caf",
        "doc://com.apple.accelerate/documentation/simd/log(_:)-77xdo"
      ],
      "title": "Applying arithmetic operations to quaternions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_sub(_:_:)-87caf/title",
          "value": "simd_sub"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_sub(_:_:)-87caf/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_sub"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_mul(_:_:)-531pe/title",
          "value": "simd_mul"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_mul(_:_:)-531pe/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_mul"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_mul(_:_:)-8uidm/title",
          "value": "simd_mul"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_mul(_:_:)-8uidm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_mul"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_quatd/title",
          "value": "simd_quatd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_quatd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_quatd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_quatd/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_quatd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_mul(_:_:)-8aedk/title",
          "value": "simd_mul"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_mul(_:_:)-8aedk/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_mul"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_add(_:_:)-6ohmq/title",
          "value": "simd_add"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_add(_:_:)-6ohmq/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_add"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/exp(_:)-9nl1f"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
