{
  "abstract": [
    {
      "text": "Returns ",
      "type": "text"
    },
    {
      "inlineContent": [
        {
          "text": "e",
          "type": "text"
        }
      ],
      "type": "emphasis"
    },
    {
      "text": " raised to the power of each element in a vector.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/exp(_:)-9nxip"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:4simd3expys5SIMD2VySdGAEF",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "exp"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_double2",
        "text": "simd_double2"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_double2",
        "text": "simd_double2"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "exp(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "exp"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "x"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_double2",
              "text": "simd_double2"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_double2",
              "text": "simd_double2"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/exp(_:)-9nxip": {
      "abstract": [
        {
          "text": "Returns ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "e",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " raised to the power of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exp"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double2",
          "text": "simd_double2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double2",
          "text": "simd_double2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/exp(_:)-9nxip",
      "kind": "symbol",
      "role": "symbol",
      "title": "exp(_:)",
      "type": "topic",
      "url": "/documentation/simd/exp(_:)-9nxip"
    },
    "doc://com.apple.accelerate/documentation/simd/exp10(_:)-4tdos": {
      "abstract": [
        {
          "text": "Returns 10 raised to the power of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exp10"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double2",
          "text": "simd_double2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double2",
          "text": "simd_double2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/exp10(_:)-4tdos",
      "kind": "symbol",
      "role": "symbol",
      "title": "exp10(_:)",
      "type": "topic",
      "url": "/documentation/simd/exp10(_:)-4tdos"
    },
    "doc://com.apple.accelerate/documentation/simd/exp2(_:)-4y2ne": {
      "abstract": [
        {
          "text": "Returns 2 raised to the power of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exp2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double2",
          "text": "simd_double2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double2",
          "text": "simd_double2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/exp2(_:)-4y2ne",
      "kind": "symbol",
      "role": "symbol",
      "title": "exp2(_:)",
      "type": "topic",
      "url": "/documentation/simd/exp2(_:)-4y2ne"
    },
    "doc://com.apple.accelerate/documentation/simd/expm1(_:)-9aitr": {
      "abstract": [
        {
          "text": "Returns ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "eˣ-1",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " for each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "expm1"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double2",
          "text": "simd_double2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double2",
          "text": "simd_double2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/expm1(_:)-9aitr",
      "kind": "symbol",
      "role": "symbol",
      "title": "expm1(_:)",
      "type": "topic",
      "url": "/documentation/simd/expm1(_:)-9aitr"
    },
    "doc://com.apple.accelerate/documentation/simd/log(_:)-2ieba": {
      "abstract": [
        {
          "text": "Returns the natural logarithm of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "log"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double2",
          "text": "simd_double2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double2",
          "text": "simd_double2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/log(_:)-2ieba",
      "kind": "symbol",
      "role": "symbol",
      "title": "log(_:)",
      "type": "topic",
      "url": "/documentation/simd/log(_:)-2ieba"
    },
    "doc://com.apple.accelerate/documentation/simd/log10(_:)-337zw": {
      "abstract": [
        {
          "text": "Returns the base 10 logarithm of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "log10"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double2",
          "text": "simd_double2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double2",
          "text": "simd_double2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/log10(_:)-337zw",
      "kind": "symbol",
      "role": "symbol",
      "title": "log10(_:)",
      "type": "topic",
      "url": "/documentation/simd/log10(_:)-337zw"
    },
    "doc://com.apple.accelerate/documentation/simd/log1p(_:)-40mka": {
      "abstract": [
        {
          "text": "Returns ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "log(1+x)",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "log1p"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double2",
          "text": "simd_double2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double2",
          "text": "simd_double2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/log1p(_:)-40mka",
      "kind": "symbol",
      "role": "symbol",
      "title": "log1p(_:)",
      "type": "topic",
      "url": "/documentation/simd/log1p(_:)-40mka"
    },
    "doc://com.apple.accelerate/documentation/simd/log2(_:)-779eu": {
      "abstract": [
        {
          "text": "Returns the base 2 logarithm of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "log2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double2",
          "text": "simd_double2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double2",
          "text": "simd_double2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/log2(_:)-779eu",
      "kind": "symbol",
      "role": "symbol",
      "title": "log2(_:)",
      "type": "topic",
      "url": "/documentation/simd/log2(_:)-779eu"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double2": {
      "abstract": [
        {
          "text": "A vector of two 64-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_double2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_double2"
        }
      ],
      "role": "symbol",
      "title": "simd_double2",
      "type": "topic",
      "url": "/documentation/simd/simd_double2"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Exponential-and-Logarithmic-Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/exp2(_:)-4y2ne",
        "doc://com.apple.accelerate/documentation/simd/exp10(_:)-4tdos",
        "doc://com.apple.accelerate/documentation/simd/expm1(_:)-9aitr",
        "doc://com.apple.accelerate/documentation/simd/log(_:)-2ieba",
        "doc://com.apple.accelerate/documentation/simd/log2(_:)-779eu",
        "doc://com.apple.accelerate/documentation/simd/log10(_:)-337zw",
        "doc://com.apple.accelerate/documentation/simd/log1p(_:)-40mka"
      ],
      "title": "Exponential and Logarithmic Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double2/title",
          "value": "simd_double2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double2"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/exp(_:)-9nxip"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
