{
  "abstract": [
    {
      "text": "Returns the multiply-add result for corresponding elements in three vectors.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/fma(_:_:_:)-49crk"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:4simd3fmays5SIMD8VySfGAE_A2EtF",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "fma"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_float8",
        "text": "simd_float8"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_float8",
        "text": "simd_float8"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_float8",
        "text": "simd_float8"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_float8",
        "text": "simd_float8"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "fma(_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "fma"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "x"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float8",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_float8",
              "text": "simd_float8"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "y"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float8",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_float8",
              "text": "simd_float8"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "z"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float8",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_float8",
              "text": "simd_float8"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float8",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_float8",
              "text": "simd_float8"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The ",
                  "type": "text"
                },
                {
                  "inlineContent": [
                    {
                      "text": "x",
                      "type": "text"
                    }
                  ],
                  "type": "emphasis"
                },
                {
                  "text": " in ",
                  "type": "text"
                },
                {
                  "code": "x*y + z",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "x"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The ",
                  "type": "text"
                },
                {
                  "inlineContent": [
                    {
                      "text": "y",
                      "type": "text"
                    }
                  ],
                  "type": "emphasis"
                },
                {
                  "text": " in ",
                  "type": "text"
                },
                {
                  "code": "x*y + z",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "y"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The ",
                  "type": "text"
                },
                {
                  "inlineContent": [
                    {
                      "text": "z",
                      "type": "text"
                    }
                  ],
                  "type": "emphasis"
                },
                {
                  "text": " in ",
                  "type": "text"
                },
                {
                  "code": "x*y + z",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "z"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The result of ",
              "type": "text"
            },
            {
              "code": "x*y + z",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/cbrt(_:)-3f2k2": {
      "abstract": [
        {
          "text": "Returns the cube root of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cbrt"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float8",
          "text": "simd_float8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float8",
          "text": "simd_float8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/cbrt(_:)-3f2k2",
      "kind": "symbol",
      "role": "symbol",
      "title": "cbrt(_:)",
      "type": "topic",
      "url": "/documentation/simd/cbrt(_:)-3f2k2"
    },
    "doc://com.apple.accelerate/documentation/simd/erf(_:)-5vzab": {
      "abstract": [
        {
          "text": "Returns the error function for each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "erf"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float8",
          "text": "simd_float8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float8",
          "text": "simd_float8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/erf(_:)-5vzab",
      "kind": "symbol",
      "role": "symbol",
      "title": "erf(_:)",
      "type": "topic",
      "url": "/documentation/simd/erf(_:)-5vzab"
    },
    "doc://com.apple.accelerate/documentation/simd/erfc(_:)-1csse": {
      "abstract": [
        {
          "text": "Returns the complementary error function for each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "erfc"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float8",
          "text": "simd_float8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float8",
          "text": "simd_float8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/erfc(_:)-1csse",
      "kind": "symbol",
      "role": "symbol",
      "title": "erfc(_:)",
      "type": "topic",
      "url": "/documentation/simd/erfc(_:)-1csse"
    },
    "doc://com.apple.accelerate/documentation/simd/fma(_:_:_:)-49crk": {
      "abstract": [
        {
          "text": "Returns the multiply-add result for corresponding elements in three vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fma"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float8",
          "text": "simd_float8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float8",
          "text": "simd_float8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float8",
          "text": "simd_float8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float8",
          "text": "simd_float8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/fma(_:_:_:)-49crk",
      "kind": "symbol",
      "role": "symbol",
      "title": "fma(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/fma(_:_:_:)-49crk"
    },
    "doc://com.apple.accelerate/documentation/simd/fmod(_:_:)-8fmuq": {
      "abstract": [
        {
          "text": "Returns the modulus after dividing each element in a vector by the corresponding element in a second vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fmod"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float8",
          "text": "simd_float8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float8",
          "text": "simd_float8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float8",
          "text": "simd_float8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/fmod(_:_:)-8fmuq",
      "kind": "symbol",
      "role": "symbol",
      "title": "fmod(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/fmod(_:_:)-8fmuq"
    },
    "doc://com.apple.accelerate/documentation/simd/hypot(_:_:)-47t8e": {
      "abstract": [
        {
          "text": "Returns the hypotenuse of a right-angled triangle with the sides that are adjacent to the right angle that two vectors define.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hypot"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float8",
          "text": "simd_float8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float8",
          "text": "simd_float8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float8",
          "text": "simd_float8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/hypot(_:_:)-47t8e",
      "kind": "symbol",
      "role": "symbol",
      "title": "hypot(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/hypot(_:_:)-47t8e"
    },
    "doc://com.apple.accelerate/documentation/simd/lgamma(_:)-9g2rk": {
      "abstract": [
        {
          "text": "Returns the natural logarithm of the absolute value of the gamma function of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lgamma"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float8",
          "text": "simd_float8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float8",
          "text": "simd_float8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/lgamma(_:)-9g2rk",
      "kind": "symbol",
      "role": "symbol",
      "title": "lgamma(_:)",
      "type": "topic",
      "url": "/documentation/simd/lgamma(_:)-9g2rk"
    },
    "doc://com.apple.accelerate/documentation/simd/nextafter(_:_:)-sc7d": {
      "abstract": [
        {
          "text": "Returns the next representable value of each element in a vector in the direction of the corresponding element in a second vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nextafter"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float8",
          "text": "simd_float8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float8",
          "text": "simd_float8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float8",
          "text": "simd_float8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/nextafter(_:_:)-sc7d",
      "kind": "symbol",
      "role": "symbol",
      "title": "nextafter(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/nextafter(_:_:)-sc7d"
    },
    "doc://com.apple.accelerate/documentation/simd/pow(_:_:)-nk2t": {
      "abstract": [
        {
          "text": "Returns each element in a vector raised to the power of the corresponding element in a second vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pow"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float8",
          "text": "simd_float8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float8",
          "text": "simd_float8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float8",
          "text": "simd_float8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/pow(_:_:)-nk2t",
      "kind": "symbol",
      "role": "symbol",
      "title": "pow(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/pow(_:_:)-nk2t"
    },
    "doc://com.apple.accelerate/documentation/simd/remainder(_:_:)-7l2wd": {
      "abstract": [
        {
          "text": "Returns the remainder after dividing each element in an array by the corresponding element in a second array of double-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remainder"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float8",
          "text": "simd_float8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float8",
          "text": "simd_float8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float8",
          "text": "simd_float8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/remainder(_:_:)-7l2wd",
      "kind": "symbol",
      "role": "symbol",
      "title": "remainder(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/remainder(_:_:)-7l2wd"
    },
    "doc://com.apple.accelerate/documentation/simd/round(_:)-1ffcx": {
      "abstract": [
        {
          "text": "Returns each element in a vector rounded to the nearest integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "round"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float8",
          "text": "simd_float8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float8",
          "text": "simd_float8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/round(_:)-1ffcx",
      "kind": "symbol",
      "role": "symbol",
      "title": "round(_:)",
      "type": "topic",
      "url": "/documentation/simd/round(_:)-1ffcx"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float8": {
      "abstract": [
        {
          "text": "A vector of eight 32-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_float8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_float8"
        }
      ],
      "role": "symbol",
      "title": "simd_float8",
      "type": "topic",
      "url": "/documentation/simd/simd_float8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_muladd(_:_:_:)-3v5t5": {
      "abstract": [
        {
          "text": "Returns the multiply-add result for corresponding elements in three vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_muladd"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float8",
          "text": "simd_float8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float8",
          "text": "simd_float8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float8",
          "text": "simd_float8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float8",
          "text": "simd_float8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_muladd(_:_:_:)-3v5t5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_muladd"
        }
      ],
      "role": "symbol",
      "title": "simd_muladd(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_muladd(_:_:_:)-3v5t5"
    },
    "doc://com.apple.accelerate/documentation/simd/tgamma(_:)-6tafl": {
      "abstract": [
        {
          "text": "Returns the gamma function for each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tgamma"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float8",
          "text": "simd_float8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float8",
          "text": "simd_float8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/tgamma(_:)-6tafl",
      "kind": "symbol",
      "role": "symbol",
      "title": "tgamma(_:)",
      "type": "topic",
      "url": "/documentation/simd/tgamma(_:)-6tafl"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Math-Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/cbrt(_:)-3f2k2",
        "doc://com.apple.accelerate/documentation/simd/erf(_:)-5vzab",
        "doc://com.apple.accelerate/documentation/simd/erfc(_:)-1csse",
        "doc://com.apple.accelerate/documentation/simd/fmod(_:_:)-8fmuq",
        "doc://com.apple.accelerate/documentation/simd/hypot(_:_:)-47t8e",
        "doc://com.apple.accelerate/documentation/simd/lgamma(_:)-9g2rk",
        "doc://com.apple.accelerate/documentation/simd/nextafter(_:_:)-sc7d",
        "doc://com.apple.accelerate/documentation/simd/pow(_:_:)-nk2t",
        "doc://com.apple.accelerate/documentation/simd/remainder(_:_:)-7l2wd",
        "doc://com.apple.accelerate/documentation/simd/round(_:)-1ffcx",
        "doc://com.apple.accelerate/documentation/simd/simd_muladd(_:_:_:)-3v5t5",
        "doc://com.apple.accelerate/documentation/simd/tgamma(_:)-6tafl"
      ],
      "title": "Math Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float8/title",
          "value": "simd_float8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_muladd(_:_:_:)-3v5t5/title",
          "value": "simd_muladd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_muladd(_:_:_:)-3v5t5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_muladd"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/fma(_:_:_:)-49crk"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
