{
  "abstract": [
    {
      "text": "Returns true for each element that is normal in a vector.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/isnormal(_:)-86aj9"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:4simd8isnormalys6SIMD16Vys5Int32VGADySfGF",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "isnormal"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_float16",
        "text": "simd_float16"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_int16",
        "text": "simd_int16"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "isnormal(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "isnormal"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "x"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float16",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_float16",
              "text": "simd_float16"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int16",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_int16",
              "text": "simd_int16"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/isfinite(_:)-8bt9t": {
      "abstract": [
        {
          "text": "Returns true for each element that is finite in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isfinite"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float16",
          "text": "simd_float16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int16",
          "text": "simd_int16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/isfinite(_:)-8bt9t",
      "kind": "symbol",
      "role": "symbol",
      "title": "isfinite(_:)",
      "type": "topic",
      "url": "/documentation/simd/isfinite(_:)-8bt9t"
    },
    "doc://com.apple.accelerate/documentation/simd/isinf(_:)-77t4f": {
      "abstract": [
        {
          "text": "Returns true for each element that is infinite in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isinf"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float16",
          "text": "simd_float16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int16",
          "text": "simd_int16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/isinf(_:)-77t4f",
      "kind": "symbol",
      "role": "symbol",
      "title": "isinf(_:)",
      "type": "topic",
      "url": "/documentation/simd/isinf(_:)-77t4f"
    },
    "doc://com.apple.accelerate/documentation/simd/isnan(_:)-3ek5k": {
      "abstract": [
        {
          "text": "Returns true for each element that is not a number (NaN) in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isnan"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float16",
          "text": "simd_float16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int16",
          "text": "simd_int16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/isnan(_:)-3ek5k",
      "kind": "symbol",
      "role": "symbol",
      "title": "isnan(_:)",
      "type": "topic",
      "url": "/documentation/simd/isnan(_:)-3ek5k"
    },
    "doc://com.apple.accelerate/documentation/simd/isnormal(_:)-86aj9": {
      "abstract": [
        {
          "text": "Returns true for each element that is normal in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isnormal"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float16",
          "text": "simd_float16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int16",
          "text": "simd_int16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/isnormal(_:)-86aj9",
      "kind": "symbol",
      "role": "symbol",
      "title": "isnormal(_:)",
      "type": "topic",
      "url": "/documentation/simd/isnormal(_:)-86aj9"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float16": {
      "abstract": [
        {
          "text": "A vector of sixteen 32-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_float16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_float16"
        }
      ],
      "role": "symbol",
      "title": "simd_float16",
      "type": "topic",
      "url": "/documentation/simd/simd_float16"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int16": {
      "abstract": [
        {
          "text": "A vector of sixteen 32-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_int16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_int16"
        }
      ],
      "role": "symbol",
      "title": "simd_int16",
      "type": "topic",
      "url": "/documentation/simd/simd_int16"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Classification-Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/isfinite(_:)-8bt9t",
        "doc://com.apple.accelerate/documentation/simd/isinf(_:)-77t4f",
        "doc://com.apple.accelerate/documentation/simd/isnan(_:)-3ek5k"
      ],
      "title": "Classification Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float16/title",
          "value": "simd_float16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float16/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int16/title",
          "value": "simd_int16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_int16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int16/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_int16"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/isnormal(_:)-86aj9"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
