{
  "abstract": [
    {
      "text": "Returns the product of a 2 x 2 matrix and a 4 x 2 matrix.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/matrix_multiply-7erm8"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@matrix_multiply#$@SA@simd_double2x2#$@SA@simd_double4x2#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "matrix_multiply"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "matrix_multiply"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "matrix_multiply"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4x2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@simd_double4x2",
              "text": "simd_double4x2"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "matrix_multiply"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double2x2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@simd_double2x2",
              "text": "simd_double2x2"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4x2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@simd_double4x2",
              "text": "simd_double4x2"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__y"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_multiply-2dc11": {
      "abstract": [
        {
          "text": "Returns the product of a 3 x 2 matrix and a 4 x 3 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "matrix_multiply"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_multiply-2dc11",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_multiply",
      "type": "topic",
      "url": "/documentation/simd/matrix_multiply-2dc11"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_multiply-4um5g": {
      "abstract": [
        {
          "text": "Returns the product of a 4 x 2 matrix and a 4 x 4 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "matrix_multiply"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_multiply-4um5g",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_multiply",
      "type": "topic",
      "url": "/documentation/simd/matrix_multiply-4um5g"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_multiply-7erm8": {
      "abstract": [
        {
          "text": "Returns the product of a 2 x 2 matrix and a 4 x 2 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "matrix_multiply"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_multiply-7erm8",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_multiply",
      "type": "topic",
      "url": "/documentation/simd/matrix_multiply-7erm8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double2x2": {
      "abstract": [
        {
          "text": "A matrix of two columns and two rows that contains double-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_double2x2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double2x2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_double2x2"
        }
      ],
      "role": "symbol",
      "title": "simd_double2x2",
      "type": "topic",
      "url": "/documentation/simd/simd_double2x2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double4x2": {
      "abstract": [
        {
          "text": "A matrix of four columns and two rows that contains double-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_double4x2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4x2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_double4x2"
        }
      ],
      "role": "symbol",
      "title": "simd_double4x2",
      "type": "topic",
      "url": "/documentation/simd/simd_double4x2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_mul-193a1": {
      "abstract": [
        {
          "text": "Returns the product of a 2 x 2 matrix and a 4 x 2 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_mul"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_mul-193a1",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_mul",
      "type": "topic",
      "url": "/documentation/simd/simd_mul-193a1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_mul-2ijzp": {
      "abstract": [
        {
          "text": "Returns the product of a 3 x 2 matrix and a 4 x 3 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_mul"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_mul-2ijzp",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_mul",
      "type": "topic",
      "url": "/documentation/simd/simd_mul-2ijzp"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_mul-jjeg": {
      "abstract": [
        {
          "text": "Returns the product of a 4 x 2 matrix and a 4 x 4 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_mul"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_mul-jjeg",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_mul",
      "type": "topic",
      "url": "/documentation/simd/simd_mul-jjeg"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Matrix-Matrix-Multiplication-Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_mul-193a1",
        "doc://com.apple.accelerate/documentation/simd/simd_mul-2ijzp",
        "doc://com.apple.accelerate/documentation/simd/matrix_multiply-2dc11",
        "doc://com.apple.accelerate/documentation/simd/simd_mul-jjeg",
        "doc://com.apple.accelerate/documentation/simd/matrix_multiply-4um5g"
      ],
      "title": "Matrix-Matrix Multiplication Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double2x2/title",
          "value": "simd_double2x2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double2x2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double2x2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double2x2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double2x2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4x2/title",
          "value": "simd_double4x2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4x2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double4x2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4x2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double4x2"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/matrix_multiply-7erm8"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
