{
  "abstract": [
    {
      "text": "Returns the product of a 4 x 3 matrix and a four-element vector.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/matrix_multiply-2zrla"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@matrix_multiply#$@SA@simd_float4x3#]4f#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "matrix_multiply"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "matrix_multiply"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "matrix_multiply"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float3",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_float3",
              "text": "simd_float3"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "matrix_multiply"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float4x3",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@simd_float4x3",
              "text": "simd_float4x3"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float4",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_float4",
              "text": "simd_float4"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__y"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_multiply-2zrla": {
      "abstract": [
        {
          "text": "Returns the product of a 4 x 3 matrix and a four-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "matrix_multiply"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_multiply-2zrla",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_multiply",
      "type": "topic",
      "url": "/documentation/simd/matrix_multiply-2zrla"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_multiply-9ikfl": {
      "abstract": [
        {
          "text": "Returns the product of a three-element vector and a 4 x 3 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "matrix_multiply"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_multiply-9ikfl",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_multiply",
      "type": "topic",
      "url": "/documentation/simd/matrix_multiply-9ikfl"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float3": {
      "abstract": [
        {
          "text": "A vector of three 32-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_float3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_float3"
        }
      ],
      "role": "symbol",
      "title": "simd_float3",
      "type": "topic",
      "url": "/documentation/simd/simd_float3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float4": {
      "abstract": [
        {
          "text": "A vector of four 32-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_float4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_float4"
        }
      ],
      "role": "symbol",
      "title": "simd_float4",
      "type": "topic",
      "url": "/documentation/simd/simd_float4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float4x3": {
      "abstract": [
        {
          "text": "A matrix of four columns and three rows that contains single-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_float4x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float4x3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_float4x3"
        }
      ],
      "role": "symbol",
      "title": "simd_float4x3",
      "type": "topic",
      "url": "/documentation/simd/simd_float4x3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_mul-2jbub": {
      "abstract": [
        {
          "text": "Returns the product of a 4 x 3 matrix and a four-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_mul"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_mul-2jbub",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_mul",
      "type": "topic",
      "url": "/documentation/simd/simd_mul-2jbub"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_mul-9e8z9": {
      "abstract": [
        {
          "text": "Returns the product of a three-element vector and a 4 x 3 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_mul"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_mul-9e8z9",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_mul",
      "type": "topic",
      "url": "/documentation/simd/simd_mul-9e8z9"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Matrix-Vector-Multiplication-Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_mul-9e8z9",
        "doc://com.apple.accelerate/documentation/simd/matrix_multiply-9ikfl",
        "doc://com.apple.accelerate/documentation/simd/simd_mul-2jbub"
      ],
      "title": "Matrix-Vector Multiplication Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float3/title",
          "value": "simd_float3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float4/title",
          "value": "simd_float4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float4x3/title",
          "value": "simd_float4x3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float4x3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float4x3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float4x3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float4x3"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/matrix_multiply-2zrla"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
