{
  "abstract": [
    {
      "text": "Returns the reciprocal square root of each element in a vector.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/rsqrt(_:)-3g5ej"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:4simd5rsqrtys5SIMD4VySfGAEF",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "rsqrt"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5SIMD4V",
        "text": "SIMD4"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sf",
        "text": "Float"
      },
      {
        "kind": "text",
        "text": ">) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5SIMD4V",
        "text": "SIMD4"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sf",
        "text": "Float"
      },
      {
        "kind": "text",
        "text": ">"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "rsqrt(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "rsqrt"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "x"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5SIMD4V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5SIMD4V",
              "text": "SIMD4"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sf",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sf",
              "text": "Float"
            },
            {
              "kind": "text",
              "text": ">) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5SIMD4V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5SIMD4V",
              "text": "SIMD4"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sf",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sf",
              "text": "Float"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/recip(_:)-3idnw": {
      "abstract": [
        {
          "text": "Returns the reciprocal of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recip"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD4V",
          "text": "SIMD4"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD4V",
          "text": "SIMD4"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/recip(_:)-3idnw",
      "kind": "symbol",
      "role": "symbol",
      "title": "recip(_:)",
      "type": "topic",
      "url": "/documentation/simd/recip(_:)-3idnw"
    },
    "doc://com.apple.accelerate/documentation/simd/rsqrt(_:)-3g5ej": {
      "abstract": [
        {
          "text": "Returns the reciprocal square root of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rsqrt"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD4V",
          "text": "SIMD4"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD4V",
          "text": "SIMD4"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/rsqrt(_:)-3g5ej",
      "kind": "symbol",
      "role": "symbol",
      "title": "rsqrt(_:)",
      "type": "topic",
      "url": "/documentation/simd/rsqrt(_:)-3g5ej"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_fast_recip(_:)-6nf": {
      "abstract": [
        {
          "text": "Returns the fast reciprocal of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_fast_recip"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float4",
          "text": "simd_float4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float4",
          "text": "simd_float4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_fast_recip(_:)-6nf",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_fast_recip"
        }
      ],
      "role": "symbol",
      "title": "simd_fast_recip(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_fast_recip(_:)-6nf"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_fast_rsqrt(_:)-8p7fk": {
      "abstract": [
        {
          "text": "Returns the fast reciprocal square root of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_fast_rsqrt"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float4",
          "text": "simd_float4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float4",
          "text": "simd_float4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_fast_rsqrt(_:)-8p7fk",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_fast_rsqrt"
        }
      ],
      "role": "symbol",
      "title": "simd_fast_rsqrt(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_fast_rsqrt(_:)-8p7fk"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_precise_recip(_:)-6ptoq": {
      "abstract": [
        {
          "text": "Returns the precise reciprocal of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_precise_recip"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float4",
          "text": "simd_float4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float4",
          "text": "simd_float4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_precise_recip(_:)-6ptoq",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_precise_recip"
        }
      ],
      "role": "symbol",
      "title": "simd_precise_recip(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_precise_recip(_:)-6ptoq"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_precise_rsqrt(_:)-136xw": {
      "abstract": [
        {
          "text": "Returns the precise reciprocal square root of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_precise_rsqrt"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float4",
          "text": "simd_float4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float4",
          "text": "simd_float4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_precise_rsqrt(_:)-136xw",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_precise_rsqrt"
        }
      ],
      "role": "symbol",
      "title": "simd_precise_rsqrt(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_precise_rsqrt(_:)-136xw"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_recip(_:)-820ma": {
      "abstract": [
        {
          "text": "Returns the reciprocal of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_recip"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float4",
          "text": "simd_float4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float4",
          "text": "simd_float4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_recip(_:)-820ma",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_recip"
        }
      ],
      "role": "symbol",
      "title": "simd_recip(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_recip(_:)-820ma"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_rsqrt(_:)-i4we": {
      "abstract": [
        {
          "text": "Returns the reciprocal square root of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_rsqrt"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float4",
          "text": "simd_float4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float4",
          "text": "simd_float4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_rsqrt(_:)-i4we",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_rsqrt"
        }
      ],
      "role": "symbol",
      "title": "simd_rsqrt(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_rsqrt(_:)-i4we"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Sf": {
      "abstract": [
        {
          "text": "A single-precision, floating-point value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sf",
      "kind": "symbol",
      "role": "symbol",
      "title": "Float",
      "type": "topic",
      "url": "/documentation/Swift/Float"
    },
    "doc://com.externally.resolved.symbol/s:s5SIMD4V": {
      "abstract": [
        {
          "text": "A vector of four scalar values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SIMD4"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SIMDScalarP",
          "text": "SIMDScalar"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5SIMD4V",
      "kind": "symbol",
      "role": "symbol",
      "title": "SIMD4",
      "type": "topic",
      "url": "/documentation/Swift/SIMD4"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reciprocal-and-Reciprocal-Square-Root-Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_recip(_:)-820ma",
        "doc://com.apple.accelerate/documentation/simd/recip(_:)-3idnw",
        "doc://com.apple.accelerate/documentation/simd/simd_rsqrt(_:)-i4we",
        "doc://com.apple.accelerate/documentation/simd/simd_precise_recip(_:)-6ptoq",
        "doc://com.apple.accelerate/documentation/simd/simd_precise_rsqrt(_:)-136xw",
        "doc://com.apple.accelerate/documentation/simd/simd_fast_recip(_:)-6nf",
        "doc://com.apple.accelerate/documentation/simd/simd_fast_rsqrt(_:)-8p7fk"
      ],
      "title": "Reciprocal and Reciprocal Square Root Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_recip(_:)-820ma/title",
          "value": "simd_recip"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_recip(_:)-820ma/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_recip"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_precise_recip(_:)-6ptoq/title",
          "value": "simd_precise_recip"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_precise_recip(_:)-6ptoq/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_precise_recip"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_precise_rsqrt(_:)-136xw/title",
          "value": "simd_precise_rsqrt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_precise_rsqrt(_:)-136xw/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_precise_rsqrt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_fast_recip(_:)-6nf/title",
          "value": "simd_fast_recip"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_fast_recip(_:)-6nf/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_fast_recip"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_rsqrt(_:)-i4we/title",
          "value": "simd_rsqrt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_rsqrt(_:)-i4we/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_rsqrt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_fast_rsqrt(_:)-8p7fk/title",
          "value": "simd_fast_rsqrt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_fast_rsqrt(_:)-8p7fk/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_fast_rsqrt"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/rsqrt(_:)-3g5ej"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
