{
  "abstract": [
    {
      "text": "Returns a new vector from the specified vector of 32-bit, signed-integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_float-182oo"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_float#]3I#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_float"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_float"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_float"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float3",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_float3",
              "text": "simd_float3"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_float"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int3",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_int3",
              "text": "simd_int3"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float-17lu0": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float-17lu0",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_float",
      "type": "topic",
      "url": "/documentation/simd/simd_float-17lu0"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float-17pac": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float-17pac",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_float",
      "type": "topic",
      "url": "/documentation/simd/simd_float-17pac"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float-17pws": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float-17pws",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_float",
      "type": "topic",
      "url": "/documentation/simd/simd_float-17pws"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float-17qqw": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float-17qqw",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_float",
      "type": "topic",
      "url": "/documentation/simd/simd_float-17qqw"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float-17rro": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float-17rro",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_float",
      "type": "topic",
      "url": "/documentation/simd/simd_float-17rro"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float-17sm0": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float-17sm0",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_float",
      "type": "topic",
      "url": "/documentation/simd/simd_float-17sm0"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float-17vt4": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float-17vt4",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_float",
      "type": "topic",
      "url": "/documentation/simd/simd_float-17vt4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float-180o8": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float-180o8",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_float",
      "type": "topic",
      "url": "/documentation/simd/simd_float-180o8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float-181qs": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float-181qs",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_float",
      "type": "topic",
      "url": "/documentation/simd/simd_float-181qs"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float-182oo": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float-182oo",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_float",
      "type": "topic",
      "url": "/documentation/simd/simd_float-182oo"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float3": {
      "abstract": [
        {
          "text": "A vector of three 32-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_float3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_float3"
        }
      ],
      "role": "symbol",
      "title": "simd_float3",
      "type": "topic",
      "url": "/documentation/simd/simd_float3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int3": {
      "abstract": [
        {
          "text": "A vector of three 32-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_int3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_int3"
        }
      ],
      "role": "symbol",
      "title": "simd_int3",
      "type": "topic",
      "url": "/documentation/simd/simd_int3"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Create-Three-Element-Vectors-From-Vectors-of-Other-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_float-180o8",
        "doc://com.apple.accelerate/documentation/simd/simd_float-17qqw",
        "doc://com.apple.accelerate/documentation/simd/simd_float-17vt4",
        "doc://com.apple.accelerate/documentation/simd/simd_float-17lu0",
        "doc://com.apple.accelerate/documentation/simd/simd_float-17sm0",
        "doc://com.apple.accelerate/documentation/simd/simd_float-181qs",
        "doc://com.apple.accelerate/documentation/simd/simd_float-17rro",
        "doc://com.apple.accelerate/documentation/simd/simd_float-17pws",
        "doc://com.apple.accelerate/documentation/simd/simd_float-17pac"
      ],
      "title": "Functions to Create Three-Element Vectors From Vectors of Other Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float3/title",
          "value": "simd_float3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int3/title",
          "value": "simd_int3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_int3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_int3"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_float-182oo"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
