{
  "abstract": [
    {
      "text": "A vector of three 64-bit unsigned integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_ulong3"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@simd_ulong3",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simd_ulong3"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_ulong3"
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "simd_ulong3"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_ulong3"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5SIMD3V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5SIMD3V",
              "text": "SIMD3"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong1",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_ulong1",
              "text": "simd_ulong1"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1adyq": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_all"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong3",
          "text": "simd_ulong3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_bool",
          "text": "simd_bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1adyq",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_all"
        }
      ],
      "role": "symbol",
      "title": "simd_all(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_all(_:)-1adyq"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-69ij0": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_any"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong3",
          "text": "simd_ulong3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_bool",
          "text": "simd_bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-69ij0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_any"
        }
      ],
      "role": "symbol",
      "title": "simd_any(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_any(_:)-69ij0"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-600bp": {
      "abstract": [
        {
          "text": "Returns a vector that contains elements from either the first or second parameter, based on the corresponding element in the third parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_bitselect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong3",
          "text": "simd_ulong3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong3",
          "text": "simd_ulong3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long3",
          "text": "simd_long3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong3",
          "text": "simd_ulong3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-600bp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_bitselect"
        }
      ],
      "role": "symbol",
      "title": "simd_bitselect(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_bitselect(_:_:_:)-600bp"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-5ce6": {
      "abstract": [
        {
          "text": "Returns each element in a vector clamped to a specified range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_clamp"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong3",
          "text": "simd_ulong3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong3",
          "text": "simd_ulong3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong3",
          "text": "simd_ulong3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong3",
          "text": "simd_ulong3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-5ce6",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_clamp"
        }
      ],
      "role": "symbol",
      "title": "simd_clamp(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_clamp(_:_:_:)-5ce6"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-2p336": {
      "abstract": [
        {
          "text": "Returns true if every element in a vector is exactly equal to the corresponding element in a second vector, and otherwise returns false.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_equal"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong3",
          "text": "simd_ulong3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong3",
          "text": "simd_ulong3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_bool",
          "text": "simd_bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-2p336",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_equal"
        }
      ],
      "role": "symbol",
      "title": "simd_equal(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_equal(_:_:)-2p336"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3(_:)-3eb9a": {
      "abstract": [
        {
          "text": "Returns a new vector with the first element set to a scalar value, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ulong3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong1",
          "text": "simd_ulong1"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong3",
          "text": "simd_ulong3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3(_:)-3eb9a",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ulong3"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ulong3(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ulong3(_:)-3eb9a"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3(_:)-4pyq9": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified eight-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ulong3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong8",
          "text": "simd_ulong8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong3",
          "text": "simd_ulong3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3(_:)-4pyq9",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ulong3"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ulong3(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ulong3(_:)-4pyq9"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3(_:)-57xdw": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ulong3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong3",
          "text": "simd_ulong3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong3",
          "text": "simd_ulong3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3(_:)-57xdw",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ulong3"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ulong3(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ulong3(_:)-57xdw"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3(_:)-5autj": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ulong3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong2",
          "text": "simd_ulong2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong3",
          "text": "simd_ulong3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3(_:)-5autj",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ulong3"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ulong3(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ulong3(_:)-5autj"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3(_:)-5w7y5": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified four-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ulong3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong4",
          "text": "simd_ulong4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong3",
          "text": "simd_ulong3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3(_:)-5w7y5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ulong3"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ulong3(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ulong3(_:)-5w7y5"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3(_:_:)-3orcm": {
      "abstract": [
        {
          "text": "Returns a new vector from a vector and a scalar value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ulong3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong2",
          "text": "simd_ulong2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong1",
          "text": "simd_ulong1"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong3",
          "text": "simd_ulong3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3(_:_:)-3orcm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ulong3"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ulong3(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ulong3(_:_:)-3orcm"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3(_:_:)-3zpz6": {
      "abstract": [
        {
          "text": "Returns a new vector from a scalar value and a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ulong3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong1",
          "text": "simd_ulong1"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong2",
          "text": "simd_ulong2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong3",
          "text": "simd_ulong3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3(_:_:)-3zpz6",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ulong3"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ulong3(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ulong3(_:_:)-3zpz6"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified scalar values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ulong3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong1",
          "text": "simd_ulong1"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong1",
          "text": "simd_ulong1"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong1",
          "text": "simd_ulong1"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong3",
          "text": "simd_ulong3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ulong3"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ulong3(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ulong3(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3_undef(_:)-5oqlt": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ulong3_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong2",
          "text": "simd_ulong2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong3",
          "text": "simd_ulong3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3_undef(_:)-5oqlt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ulong3_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ulong3_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ulong3_undef(_:)-5oqlt"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3_undef(_:)-7s0qh": {
      "abstract": [
        {
          "text": "Returns a new vector with the first element set to a scalar value, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ulong3_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong1",
          "text": "simd_ulong1"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong3",
          "text": "simd_ulong3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3_undef(_:)-7s0qh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ulong3_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ulong3_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ulong3_undef(_:)-7s0qh"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-765ec": {
      "abstract": [
        {
          "text": "Returns the maximum value of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_max"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong3",
          "text": "simd_ulong3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong3",
          "text": "simd_ulong3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong3",
          "text": "simd_ulong3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-765ec",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_max"
        }
      ],
      "role": "symbol",
      "title": "simd_max(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_max(_:_:)-765ec"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-914t0": {
      "abstract": [
        {
          "text": "Returns the minimum value of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_min"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong3",
          "text": "simd_ulong3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong3",
          "text": "simd_ulong3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong3",
          "text": "simd_ulong3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-914t0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_min"
        }
      ],
      "role": "symbol",
      "title": "simd_min(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_min(_:_:)-914t0"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-2v51x": {
      "abstract": [
        {
          "text": "Returns the sum of all elements in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_add"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong3",
          "text": "simd_ulong3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong1",
          "text": "simd_ulong1"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-2v51x",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_add"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_add(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_add(_:)-2v51x"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-4h1hr": {
      "abstract": [
        {
          "text": "Returns the maximum value in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_max"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong3",
          "text": "simd_ulong3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong1",
          "text": "simd_ulong1"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-4h1hr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_max"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_max(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_max(_:)-4h1hr"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-4697f": {
      "abstract": [
        {
          "text": "Returns the miniumum value in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_min"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong3",
          "text": "simd_ulong3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong1",
          "text": "simd_ulong1"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-4697f",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_min"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_min(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_min(_:)-4697f"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong-1malp": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong-1malp",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong-1malp"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong-1mdc7": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong-1mdc7",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong-1mdc7"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong-1me03": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong-1me03",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong-1me03"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong-1mfil": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong-1mfil",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong-1mfil"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong-1mfw7": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong-1mfw7",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong-1mfw7"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong-1mhet": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong-1mhet",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong-1mhet"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong-1mkj1": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong-1mkj1",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong-1mkj1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong-1mphp": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong-1mphp",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong-1mphp"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong-1mptj": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong-1mptj",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong-1mptj"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong-1mrfp": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong-1mrfp",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong-1mrfp"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong1": {
      "abstract": [
        {
          "text": "A vector of one 64-bit unsigned integer element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ulong1"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ulong1"
        }
      ],
      "role": "symbol",
      "title": "simd_ulong1",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong2": {
      "abstract": [
        {
          "text": "A vector of two 64-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ulong2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ulong2"
        }
      ],
      "role": "symbol",
      "title": "simd_ulong2",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong3": {
      "abstract": [
        {
          "text": "A vector of three 64-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ulong3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ulong3"
        }
      ],
      "role": "symbol",
      "title": "simd_ulong3",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong4": {
      "abstract": [
        {
          "text": "A vector of four 64-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ulong4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ulong4"
        }
      ],
      "role": "symbol",
      "title": "simd_ulong4",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong8": {
      "abstract": [
        {
          "text": "A vector of eight 64-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ulong8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ulong8"
        }
      ],
      "role": "symbol",
      "title": "simd_ulong8",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1ozs7": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1ozs7",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong_sat-1ozs7"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1p0xd": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1p0xd",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong_sat-1p0xd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1p1l7": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1p1l7",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong_sat-1p1l7"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1p4p3": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1p4p3",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong_sat-1p4p3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1p9pj": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1p9pj",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong_sat-1p9pj"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1panl": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1panl",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong_sat-1panl"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1pbrf": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1pbrf",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong_sat-1pbrf"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1pdb5": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1pdb5",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong_sat-1pdb5"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1pdyx": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1pdyx",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong_sat-1pdyx"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1pevb": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1pevb",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong_sat-1pevb"
    },
    "doc://com.apple.accelerate/documentation/simd/vector3-11y95": {
      "abstract": [
        {
          "text": "Returns a new vector from a vector and a scalar value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector3-11y95",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector3",
      "type": "topic",
      "url": "/documentation/simd/vector3-11y95"
    },
    "doc://com.apple.accelerate/documentation/simd/vector3-6utbv": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified scalar values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector3-6utbv",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector3",
      "type": "topic",
      "url": "/documentation/simd/vector3-6utbv"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_ulong3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vector_ulong3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_ulong3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vector_ulong3"
        }
      ],
      "role": "symbol",
      "title": "vector_ulong3",
      "type": "topic",
      "url": "/documentation/simd/vector_ulong3"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s5SIMD3V": {
      "abstract": [
        {
          "text": "A vector of three scalar values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SIMD3"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SIMDScalarP",
          "text": "SIMDScalar"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5SIMD3V",
      "kind": "symbol",
      "role": "symbol",
      "title": "SIMD3",
      "type": "topic",
      "url": "/documentation/Swift/SIMD3"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Vector-Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_ulong1",
        "doc://com.apple.accelerate/documentation/simd/simd_ulong2",
        "doc://com.apple.accelerate/documentation/simd/simd_ulong4",
        "doc://com.apple.accelerate/documentation/simd/simd_ulong8"
      ],
      "title": "Vector Data Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Functions-to-Create-Three-Element-Vectors-From-Other-Vectors",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3(_:)-5autj",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3(_:)-57xdw",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3(_:)-5w7y5",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3(_:)-4pyq9",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3_undef(_:)-5oqlt"
      ],
      "title": "Functions to Create Three-Element Vectors From Other Vectors"
    },
    {
      "anchor": "Functions-to-Create-Three-Element-Vectors-From-Scalar-Values",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3(_:)-3eb9a",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3(_:_:_:)",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3_undef(_:)-7s0qh"
      ],
      "title": "Functions to Create Three-Element Vectors From Scalar Values"
    },
    {
      "anchor": "Functions-to-Create-Three-Element-Vectors-From-Combinations-of-Vectors-and-Scalar-Values",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3(_:_:)-3zpz6",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3(_:_:)-3orcm"
      ],
      "title": "Functions to Create Three-Element Vectors From Combinations of Vectors and Scalar Values"
    },
    {
      "anchor": "Common-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-5ce6",
        "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-2p336"
      ],
      "title": "Common Functions"
    },
    {
      "anchor": "Reduce-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-4697f",
        "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-4h1hr",
        "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-2v51x"
      ],
      "title": "Reduce Functions"
    },
    {
      "anchor": "Extrema-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-914t0",
        "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-765ec"
      ],
      "title": "Extrema Functions"
    },
    {
      "anchor": "Logic-and-Bitwise-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-69ij0",
        "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1adyq",
        "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-600bp"
      ],
      "title": "Logic and Bitwise Functions"
    },
    {
      "anchor": "Alternative-Type-Alias",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/vector_ulong3"
      ],
      "title": "Alternative Type Alias"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "simd_ulong3"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/simd"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Functions-to-Create-Three-Element-Vectors-From-Other-Vectors",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3(_:)-5autj",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3(_:)-57xdw",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3(_:)-5w7y5",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3(_:)-4pyq9",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3_undef(_:)-5oqlt"
              ],
              "title": "Functions to Create Three-Element Vectors From Other Vectors"
            },
            {
              "anchor": "Functions-to-Create-Three-Element-Vectors-From-Scalar-Values",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3(_:)-3eb9a",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3(_:_:_:)",
                "doc://com.apple.accelerate/documentation/simd/vector3-6utbv",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3_undef(_:)-7s0qh"
              ],
              "title": "Functions to Create Three-Element Vectors From Scalar Values"
            },
            {
              "anchor": "Functions-to-Create-Three-Element-Vectors-From-Combinations-of-Vectors-and-Scalar-Values",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3(_:_:)-3zpz6",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3(_:_:)-3orcm",
                "doc://com.apple.accelerate/documentation/simd/vector3-11y95"
              ],
              "title": "Functions to Create Three-Element Vectors From Combinations of Vectors and Scalar Values"
            },
            {
              "anchor": "Functions-to-Create-Three-Element-Vectors-From-Vectors-of-Other-Types",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_ulong-1mphp",
                "doc://com.apple.accelerate/documentation/simd/simd_ulong-1mfil",
                "doc://com.apple.accelerate/documentation/simd/simd_ulong-1mkj1",
                "doc://com.apple.accelerate/documentation/simd/simd_ulong-1malp",
                "doc://com.apple.accelerate/documentation/simd/simd_ulong-1mrfp",
                "doc://com.apple.accelerate/documentation/simd/simd_ulong-1mhet",
                "doc://com.apple.accelerate/documentation/simd/simd_ulong-1mptj",
                "doc://com.apple.accelerate/documentation/simd/simd_ulong-1mfw7",
                "doc://com.apple.accelerate/documentation/simd/simd_ulong-1me03",
                "doc://com.apple.accelerate/documentation/simd/simd_ulong-1mdc7"
              ],
              "title": "Functions to Create Three-Element Vectors From Vectors of Other Types"
            },
            {
              "anchor": "Functions-to-Perform-Saturating-Conversion-From-Vectors-of-Other-Types",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1p4p3",
                "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1pevb",
                "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1ozs7",
                "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1p9pj",
                "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1p1l7",
                "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1pbrf",
                "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1p0xd",
                "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1panl",
                "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1pdyx",
                "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1pdb5"
              ],
              "title": "Functions to Perform Saturating Conversion From Vectors of Other Types"
            },
            {
              "anchor": "Common-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-5ce6",
                "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-2p336"
              ],
              "title": "Common Functions"
            },
            {
              "anchor": "Reduce-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-4697f",
                "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-4h1hr",
                "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-2v51x"
              ],
              "title": "Reduce Functions"
            },
            {
              "anchor": "Extrema-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-914t0",
                "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-765ec"
              ],
              "title": "Extrema Functions"
            },
            {
              "anchor": "Logic-and-Bitwise-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-69ij0",
                "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1adyq",
                "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-600bp"
              ],
              "title": "Logic and Bitwise Functions"
            },
            {
              "anchor": "Alternative-Type-Alias",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/vector_ulong3"
              ],
              "title": "Alternative Type Alias"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Vector-Data-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_ulong1",
                "doc://com.apple.accelerate/documentation/simd/simd_ulong2",
                "doc://com.apple.accelerate/documentation/simd/simd_ulong4",
                "doc://com.apple.accelerate/documentation/simd/simd_ulong8"
              ],
              "title": "Vector Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:]3l",
                    "text": "unsigned long __attribute__((ext_vector_type(3)))"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "simd_ulong3"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_max(_:_:)-765ec/title",
          "value": "simd_max"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_max(_:_:)-765ec/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_max"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong3(_:)-5autj/title",
          "value": "simd_make_ulong3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong3(_:)-5autj/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ulong3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_min(_:_:)-914t0/title",
          "value": "simd_min"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_min(_:_:)-914t0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_min"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_add(_:)-2v51x/title",
          "value": "simd_reduce_add"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_add(_:)-2v51x/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_add"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong3(_:_:)-3zpz6/title",
          "value": "simd_make_ulong3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong3(_:_:)-3zpz6/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ulong3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_equal(_:_:)-2p336/title",
          "value": "simd_equal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_equal(_:_:)-2p336/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_equal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_any(_:)-69ij0/title",
          "value": "simd_any"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_any(_:)-69ij0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_any"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong3(_:)-3eb9a/title",
          "value": "simd_make_ulong3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong3(_:)-3eb9a/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ulong3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong2/title",
          "value": "simd_ulong2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong3(_:_:_:)/title",
          "value": "simd_make_ulong3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong3(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ulong3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong3(_:)-5w7y5/title",
          "value": "simd_make_ulong3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong3(_:)-5w7y5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ulong3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1vector_ulong3/title",
          "value": "vector_ulong3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1vector_ulong3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vector_ulong3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1vector_ulong3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vector_ulong3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_min(_:)-4697f/title",
          "value": "simd_reduce_min"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_min(_:)-4697f/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_min"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_max(_:)-4h1hr/title",
          "value": "simd_reduce_max"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_max(_:)-4h1hr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_max"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong3/title",
          "value": "simd_ulong3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong3(_:_:)-3orcm/title",
          "value": "simd_make_ulong3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong3(_:_:)-3orcm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ulong3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_all(_:)-1adyq/title",
          "value": "simd_all"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_all(_:)-1adyq/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_all"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong3_undef(_:)-7s0qh/title",
          "value": "simd_make_ulong3_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong3_undef(_:)-7s0qh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ulong3_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_clamp(_:_:_:)-5ce6/title",
          "value": "simd_clamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_clamp(_:_:_:)-5ce6/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_clamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong8/title",
          "value": "simd_ulong8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong3(_:)-57xdw/title",
          "value": "simd_make_ulong3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong3(_:)-57xdw/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ulong3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong3(_:)-4pyq9/title",
          "value": "simd_make_ulong3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong3(_:)-4pyq9/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ulong3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_bitselect(_:_:_:)-600bp/title",
          "value": "simd_bitselect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_bitselect(_:_:_:)-600bp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_bitselect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong1/title",
          "value": "simd_ulong1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong1/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong3_undef(_:)-5oqlt/title",
          "value": "simd_make_ulong3_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong3_undef(_:)-5oqlt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ulong3_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong4/title",
          "value": "simd_ulong4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong4"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_ulong3"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/simd/simd_ulong3"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
