{
  "abstract": [
    {
      "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-2ladq"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_uchar_sat#]16I#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_uchar_sat"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_uchar_sat"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_uchar_sat"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar16",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_uchar16",
              "text": "simd_uchar16"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_uchar_sat"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int16",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_int16",
              "text": "simd_int16"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int16": {
      "abstract": [
        {
          "text": "A vector of sixteen 32-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_int16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_int16"
        }
      ],
      "role": "symbol",
      "title": "simd_int16",
      "type": "topic",
      "url": "/documentation/simd/simd_int16"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar16": {
      "abstract": [
        {
          "text": "A vector of sixteen 8-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uchar16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uchar16"
        }
      ],
      "role": "symbol",
      "title": "simd_uchar16",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar16"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-2l8ia": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-2l8ia",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar_sat-2l8ia"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-2ladq": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-2ladq",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar_sat-2ladq"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-2ldea": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-2ldea",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar_sat-2ldea"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-2lhga": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-2lhga",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar_sat-2lhga"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-2lihe": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-2lihe",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar_sat-2lihe"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-2lkcu": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-2lkcu",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar_sat-2lkcu"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-2lnde": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-2lnde",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar_sat-2lnde"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Perform-Saturating-Conversion-From-Vectors-of-Other-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-2l8ia",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-2lihe",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-2ldea",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-2lnde",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-2lkcu",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-2lhga"
      ],
      "title": "Functions to Perform Saturating Conversion From Vectors of Other Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar16/title",
          "value": "simd_uchar16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar16/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int16/title",
          "value": "simd_int16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_int16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int16/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_int16"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_uchar_sat-2ladq"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
