{
  "abstract": [
    {
      "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_long-93h2w"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_long#]8d#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_long"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_long"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_long"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long8",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_long8",
              "text": "simd_long8"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_long"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double8",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_double8",
              "text": "simd_double8"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double8": {
      "abstract": [
        {
          "text": "A vector of eight 64-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_double8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_double8"
        }
      ],
      "role": "symbol",
      "title": "simd_double8",
      "type": "topic",
      "url": "/documentation/simd/simd_double8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long-93gss": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long-93gss",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long",
      "type": "topic",
      "url": "/documentation/simd/simd_long-93gss"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long-93h2w": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long-93h2w",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long",
      "type": "topic",
      "url": "/documentation/simd/simd_long-93h2w"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long-93hmw": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long-93hmw",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long",
      "type": "topic",
      "url": "/documentation/simd/simd_long-93hmw"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long-93iok": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long-93iok",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long",
      "type": "topic",
      "url": "/documentation/simd/simd_long-93iok"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long-93jiw": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long-93jiw",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long",
      "type": "topic",
      "url": "/documentation/simd/simd_long-93jiw"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long-93lpo": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long-93lpo",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long",
      "type": "topic",
      "url": "/documentation/simd/simd_long-93lpo"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long-93qrw": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long-93qrw",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long",
      "type": "topic",
      "url": "/documentation/simd/simd_long-93qrw"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long-93sno": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long-93sno",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long",
      "type": "topic",
      "url": "/documentation/simd/simd_long-93sno"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long-93ti0": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long-93ti0",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long",
      "type": "topic",
      "url": "/documentation/simd/simd_long-93ti0"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long-93vu4": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long-93vu4",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long",
      "type": "topic",
      "url": "/documentation/simd/simd_long-93vu4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long8": {
      "abstract": [
        {
          "text": "A vector of eight 64-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_long8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_long8"
        }
      ],
      "role": "symbol",
      "title": "simd_long8",
      "type": "topic",
      "url": "/documentation/simd/simd_long8"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Create-Eight-Element-Vectors-From-Vectors-of-Other-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_long-93qrw",
        "doc://com.apple.accelerate/documentation/simd/simd_long-93gss",
        "doc://com.apple.accelerate/documentation/simd/simd_long-93vu4",
        "doc://com.apple.accelerate/documentation/simd/simd_long-93lpo",
        "doc://com.apple.accelerate/documentation/simd/simd_long-93sno",
        "doc://com.apple.accelerate/documentation/simd/simd_long-93iok",
        "doc://com.apple.accelerate/documentation/simd/simd_long-93ti0",
        "doc://com.apple.accelerate/documentation/simd/simd_long-93jiw",
        "doc://com.apple.accelerate/documentation/simd/simd_long-93hmw"
      ],
      "title": "Functions to Create Eight-Element Vectors From Vectors of Other Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double8/title",
          "value": "simd_double8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long8/title",
          "value": "simd_long8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_long8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_long8"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_long-93h2w"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
