{
  "abstract": [
    {
      "text": "Returns a new vector from the specified two-element vector, and other elements undefined.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_make_half8_undef(_:)-3on10"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_make_half8_undef#]2h#",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simd_make_half8_undef"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_half2",
        "text": "simd_half2"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_half8",
        "text": "simd_half8"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_make_half8_undef"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_make_half8_undef(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_make_half8_undef"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "other"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_half2",
              "text": "simd_half2"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half8",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_half8",
              "text": "simd_half8"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half2": {
      "abstract": [
        {
          "text": "A vector of two 16-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_half2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_half2"
        }
      ],
      "role": "symbol",
      "title": "simd_half2",
      "type": "topic",
      "url": "/documentation/simd/simd_half2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half8": {
      "abstract": [
        {
          "text": "A vector of eight 16-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_half8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_half8"
        }
      ],
      "role": "symbol",
      "title": "simd_half8",
      "type": "topic",
      "url": "/documentation/simd/simd_half8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_half8(_:)-4xf3n": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified 16-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_half8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half16",
          "text": "simd_half16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half8",
          "text": "simd_half8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_half8(_:)-4xf3n",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_half8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_half8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_half8(_:)-4xf3n"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_half8(_:)-94pmz": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified 32-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_half8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half32",
          "text": "simd_half32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half8",
          "text": "simd_half8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_half8(_:)-94pmz",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_half8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_half8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_half8(_:)-94pmz"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_half8(_:)-97ut4": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_half8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half2",
          "text": "simd_half2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half8",
          "text": "simd_half8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_half8(_:)-97ut4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_half8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_half8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_half8(_:)-97ut4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_half8(_:)-9anaf": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified three-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_half8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half3",
          "text": "simd_half3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half8",
          "text": "simd_half8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_half8(_:)-9anaf",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_half8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_half8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_half8(_:)-9anaf"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_half8(_:)-9e4ki": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified four-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_half8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half4",
          "text": "simd_half4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half8",
          "text": "simd_half8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_half8(_:)-9e4ki",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_half8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_half8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_half8(_:)-9e4ki"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_half8(_:)-9slsm": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_half8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half8",
          "text": "simd_half8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half8",
          "text": "simd_half8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_half8(_:)-9slsm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_half8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_half8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_half8(_:)-9slsm"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_half8(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_half8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half4",
          "text": "simd_half4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half4",
          "text": "simd_half4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half8",
          "text": "simd_half8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_half8(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_half8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_half8(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_half8(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_half8_undef(_:)-337am": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified four-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_half8_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half4",
          "text": "simd_half4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half8",
          "text": "simd_half8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_half8_undef(_:)-337am",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_half8_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_half8_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_half8_undef(_:)-337am"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_half8_undef(_:)-3l5sn": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified three-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_half8_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half3",
          "text": "simd_half3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half8",
          "text": "simd_half8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_half8_undef(_:)-3l5sn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_half8_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_half8_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_half8_undef(_:)-3l5sn"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_half8_undef(_:)-3on10": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_half8_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half2",
          "text": "simd_half2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half8",
          "text": "simd_half8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_half8_undef(_:)-3on10",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_half8_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_half8_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_half8_undef(_:)-3on10"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-create-eight-element-vectors-from-other-vectors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_half8(_:)-97ut4",
        "doc://com.apple.accelerate/documentation/simd/simd_make_half8(_:)-9anaf",
        "doc://com.apple.accelerate/documentation/simd/simd_make_half8(_:)-9e4ki",
        "doc://com.apple.accelerate/documentation/simd/simd_make_half8(_:)-9slsm",
        "doc://com.apple.accelerate/documentation/simd/simd_make_half8(_:)-4xf3n",
        "doc://com.apple.accelerate/documentation/simd/simd_make_half8(_:)-94pmz",
        "doc://com.apple.accelerate/documentation/simd/simd_make_half8_undef(_:)-3l5sn",
        "doc://com.apple.accelerate/documentation/simd/simd_make_half8_undef(_:)-337am",
        "doc://com.apple.accelerate/documentation/simd/simd_make_half8(_:_:)"
      ],
      "title": "Functions to create eight-element vectors from other vectors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "simd_make_half8_undef"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_half8_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/simd"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Functions-to-create-eight-element-vectors-from-other-vectors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_half8(_:)-97ut4",
                "doc://com.apple.accelerate/documentation/simd/simd_make_half8(_:)-9anaf",
                "doc://com.apple.accelerate/documentation/simd/simd_make_half8(_:)-9e4ki",
                "doc://com.apple.accelerate/documentation/simd/simd_make_half8(_:)-9slsm",
                "doc://com.apple.accelerate/documentation/simd/simd_make_half8(_:)-4xf3n",
                "doc://com.apple.accelerate/documentation/simd/simd_make_half8(_:)-94pmz",
                "doc://com.apple.accelerate/documentation/simd/simd_make_half8_undef(_:)-3l5sn",
                "doc://com.apple.accelerate/documentation/simd/simd_make_half8_undef(_:)-337am",
                "doc://com.apple.accelerate/documentation/simd/simd_make_half8(_:_:)"
              ],
              "title": "Functions to create eight-element vectors from other vectors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "static"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half8",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_half8",
                    "text": "simd_half8"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "simd_make_half8_undef"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half2",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_half2",
                    "text": "simd_half2"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "other"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half8(_:)-9slsm/title",
          "value": "simd_make_half8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half8(_:)-9slsm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_half8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half8/title",
          "value": "simd_half8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half8_undef(_:)-337am/title",
          "value": "simd_make_half8_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half8_undef(_:)-337am/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_half8_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half8(_:)-97ut4/title",
          "value": "simd_make_half8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half8(_:)-97ut4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_half8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half8(_:)-9anaf/title",
          "value": "simd_make_half8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half8(_:)-9anaf/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_half8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half8(_:_:)/title",
          "value": "simd_make_half8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half8(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_half8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half8(_:)-94pmz/title",
          "value": "simd_make_half8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half8(_:)-94pmz/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_half8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half8_undef(_:)-3l5sn/title",
          "value": "simd_make_half8_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half8_undef(_:)-3l5sn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_half8_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half8_undef(_:)-3on10/title",
          "value": "simd_make_half8_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half8_undef(_:)-3on10/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_half8_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half8(_:)-4xf3n/title",
          "value": "simd_make_half8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half8(_:)-4xf3n/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_half8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half8(_:)-9e4ki/title",
          "value": "simd_make_half8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half8(_:)-9e4ki/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_half8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half2/title",
          "value": "simd_half2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half2"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_make_half8_undef(_:)-3on10"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/simd/simd_make_half8_undef(_:)-3on10"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
