{
  "abstract": [
    {
      "text": "Returns a new vector by truncating the specified three-element vector.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:)-6gmv7"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_make_short2#]3S#",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simd_make_short2"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_short3",
        "text": "simd_short3"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_short2",
        "text": "simd_short2"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_make_short2"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_make_short2(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_make_short2"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "other"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short3",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_short3",
              "text": "simd_short3"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_short2",
              "text": "simd_short2"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:)-58qns": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified sixteen-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short16",
          "text": "simd_short16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short2",
          "text": "simd_short2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:)-58qns",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short2"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short2(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short2(_:)-58qns"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:)-5z7ps": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified four-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short4",
          "text": "simd_short4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short2",
          "text": "simd_short2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:)-5z7ps",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short2"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short2(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short2(_:)-5z7ps"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:)-6bz90": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified thirty two-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short32",
          "text": "simd_short32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short2",
          "text": "simd_short2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:)-6bz90",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short2"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short2(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short2(_:)-6bz90"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:)-6gmv7": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified three-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short3",
          "text": "simd_short3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short2",
          "text": "simd_short2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:)-6gmv7",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short2"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short2(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short2(_:)-6gmv7"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:)-6juuy": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short2",
          "text": "simd_short2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short2",
          "text": "simd_short2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:)-6juuy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short2"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short2(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short2(_:)-6juuy"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:)-74zg4": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified eight-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short2",
          "text": "simd_short2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:)-74zg4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short2"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short2(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short2(_:)-74zg4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short2": {
      "abstract": [
        {
          "text": "A vector of two 16-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_short2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_short2"
        }
      ],
      "role": "symbol",
      "title": "simd_short2",
      "type": "topic",
      "url": "/documentation/simd/simd_short2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short3": {
      "abstract": [
        {
          "text": "A vector of three 16-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_short3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_short3"
        }
      ],
      "role": "symbol",
      "title": "simd_short3",
      "type": "topic",
      "url": "/documentation/simd/simd_short3"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Create-Two-Element-Vectors-From-Other-Vectors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:)-6juuy",
        "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:)-5z7ps",
        "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:)-74zg4",
        "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:)-58qns",
        "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:)-6bz90"
      ],
      "title": "Functions to Create Two-Element Vectors From Other Vectors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "simd_make_short2"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/simd"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Functions-to-Create-Two-Element-Vectors-From-Other-Vectors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:)-6juuy",
                "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:)-5z7ps",
                "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:)-74zg4",
                "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:)-58qns",
                "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:)-6bz90"
              ],
              "title": "Functions to Create Two-Element Vectors From Other Vectors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "static"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short2",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_short2",
                    "text": "simd_short2"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "simd_make_short2"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short3",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_short3",
                    "text": "simd_short3"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "other"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short2(_:)-6gmv7/title",
          "value": "simd_make_short2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short2(_:)-6gmv7/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short2/title",
          "value": "simd_short2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short2(_:)-74zg4/title",
          "value": "simd_make_short2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short2(_:)-74zg4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short2(_:)-58qns/title",
          "value": "simd_make_short2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short2(_:)-58qns/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short3/title",
          "value": "simd_short3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short2(_:)-6juuy/title",
          "value": "simd_make_short2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short2(_:)-6juuy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short2(_:)-5z7ps/title",
          "value": "simd_make_short2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short2(_:)-5z7ps/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short2(_:)-6bz90/title",
          "value": "simd_make_short2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short2(_:)-6bz90/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short2"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_make_short2(_:)-6gmv7"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/simd/simd_make_short2(_:)-6gmv7"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
