{
  "abstract": [
    {
      "text": "Returns a new vector by truncating the specified sixty four-element vector.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-3p7i8"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_make_uchar3#]64c#",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simd_make_uchar3"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_uchar64",
        "text": "simd_uchar64"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_uchar3",
        "text": "simd_uchar3"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_make_uchar3"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_make_uchar3(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_make_uchar3"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "other"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar64",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_uchar64",
              "text": "simd_uchar64"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar3",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_uchar3",
              "text": "simd_uchar3"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-38lno": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified thirty two-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar3",
          "text": "simd_uchar3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-38lno",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar3"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar3(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar3(_:)-38lno"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-3p7i8": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified sixty four-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar64",
          "text": "simd_uchar64"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar3",
          "text": "simd_uchar3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-3p7i8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar3"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar3(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar3(_:)-3p7i8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-3sucp": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified eight-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar8",
          "text": "simd_uchar8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar3",
          "text": "simd_uchar3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-3sucp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar3"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar3(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar3(_:)-3sucp"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-45nsd": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified four-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar4",
          "text": "simd_uchar4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar3",
          "text": "simd_uchar3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-45nsd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar3"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar3(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar3(_:)-45nsd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-4nmxq": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar3",
          "text": "simd_uchar3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar3",
          "text": "simd_uchar3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-4nmxq",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar3"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar3(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar3(_:)-4nmxq"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-4qkxz": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar2",
          "text": "simd_uchar2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar3",
          "text": "simd_uchar3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-4qkxz",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar3"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar3(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar3(_:)-4qkxz"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-90ge7": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified sixteen-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar16",
          "text": "simd_uchar16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar3",
          "text": "simd_uchar3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-90ge7",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar3"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar3(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar3(_:)-90ge7"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3_undef(_:)-99t25": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar3_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar2",
          "text": "simd_uchar2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar3",
          "text": "simd_uchar3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3_undef(_:)-99t25",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar3_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar3_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar3_undef(_:)-99t25"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar3": {
      "abstract": [
        {
          "text": "A vector of three 8-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uchar3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uchar3"
        }
      ],
      "role": "symbol",
      "title": "simd_uchar3",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar64": {
      "abstract": [
        {
          "text": "A vector of sixty-four 8-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uchar64"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar64",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uchar64"
        }
      ],
      "role": "symbol",
      "title": "simd_uchar64",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar64"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Create-Three-Element-Vectors-From-Other-Vectors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-4qkxz",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-4nmxq",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-45nsd",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-3sucp",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-90ge7",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-38lno",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3_undef(_:)-99t25"
      ],
      "title": "Functions to Create Three-Element Vectors From Other Vectors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "simd_make_uchar3"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/simd"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Functions-to-Create-Three-Element-Vectors-From-Other-Vectors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-4qkxz",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-4nmxq",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-45nsd",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-3sucp",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-90ge7",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-38lno",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3_undef(_:)-99t25"
              ],
              "title": "Functions to Create Three-Element Vectors From Other Vectors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "static"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar3",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_uchar3",
                    "text": "simd_uchar3"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "simd_make_uchar3"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar64",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_uchar64",
                    "text": "simd_uchar64"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "other"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar3(_:)-3p7i8/title",
          "value": "simd_make_uchar3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar3(_:)-3p7i8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar3(_:)-38lno/title",
          "value": "simd_make_uchar3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar3(_:)-38lno/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar3_undef(_:)-99t25/title",
          "value": "simd_make_uchar3_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar3_undef(_:)-99t25/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar3_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar3(_:)-3sucp/title",
          "value": "simd_make_uchar3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar3(_:)-3sucp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar3(_:)-4nmxq/title",
          "value": "simd_make_uchar3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar3(_:)-4nmxq/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar3/title",
          "value": "simd_uchar3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar3(_:)-4qkxz/title",
          "value": "simd_make_uchar3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar3(_:)-4qkxz/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar64/title",
          "value": "simd_uchar64"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar64/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar64/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar3(_:)-45nsd/title",
          "value": "simd_make_uchar3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar3(_:)-45nsd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar3(_:)-90ge7/title",
          "value": "simd_make_uchar3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar3(_:)-90ge7/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar3"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_make_uchar3(_:)-3p7i8"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/simd/simd_make_uchar3(_:)-3p7i8"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
