{
  "abstract": [
    {
      "text": "A vector of two 16-bit unsigned integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_ushort2"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@simd_ushort2",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simd_ushort2"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_ushort2"
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "simd_ushort2"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_ushort2"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5SIMD2V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5SIMD2V",
              "text": "SIMD2"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt16V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt16V",
              "text": "UInt16"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1dffj": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_all"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort2",
          "text": "simd_ushort2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_bool",
          "text": "simd_bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1dffj",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_all"
        }
      ],
      "role": "symbol",
      "title": "simd_all(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_all(_:)-1dffj"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-649i9": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_any"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort2",
          "text": "simd_ushort2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_bool",
          "text": "simd_bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-649i9",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_any"
        }
      ],
      "role": "symbol",
      "title": "simd_any(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_any(_:)-649i9"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-9p6cd": {
      "abstract": [
        {
          "text": "Returns a vector that contains elements from either the first or second parameter, based on the corresponding element in the third parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_bitselect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort2",
          "text": "simd_ushort2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort2",
          "text": "simd_ushort2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short2",
          "text": "simd_short2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort2",
          "text": "simd_ushort2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-9p6cd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_bitselect"
        }
      ],
      "role": "symbol",
      "title": "simd_bitselect(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_bitselect(_:_:_:)-9p6cd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-3o9ad": {
      "abstract": [
        {
          "text": "Returns each element in a vector clamped to a specified range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_clamp"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort2",
          "text": "simd_ushort2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort2",
          "text": "simd_ushort2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort2",
          "text": "simd_ushort2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort2",
          "text": "simd_ushort2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-3o9ad",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_clamp"
        }
      ],
      "role": "symbol",
      "title": "simd_clamp(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_clamp(_:_:_:)-3o9ad"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-ktbu": {
      "abstract": [
        {
          "text": "Returns true if every element in a vector is exactly equal to the corresponding element in a second vector, and otherwise returns false.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_equal"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort2",
          "text": "simd_ushort2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort2",
          "text": "simd_ushort2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_bool",
          "text": "simd_bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-ktbu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_equal"
        }
      ],
      "role": "symbol",
      "title": "simd_equal(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_equal(_:_:)-ktbu"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort2(_:)-1sfxh": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified four-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort4",
          "text": "simd_ushort4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort2",
          "text": "simd_ushort2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort2(_:)-1sfxh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort2"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort2(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort2(_:)-1sfxh"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort2(_:)-2dkjj": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort2",
          "text": "simd_ushort2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort2",
          "text": "simd_ushort2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort2(_:)-2dkjj",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort2"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort2(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort2(_:)-2dkjj"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort2(_:)-2gsja": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified three-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort3",
          "text": "simd_ushort3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort2",
          "text": "simd_ushort2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort2(_:)-2gsja",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort2"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort2(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort2(_:)-2gsja"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort2(_:)-2yrlt": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified eight-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort8",
          "text": "simd_ushort8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort2",
          "text": "simd_ushort2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort2(_:)-2yrlt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort2"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort2(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort2(_:)-2yrlt"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort2(_:)-4i2ym": {
      "abstract": [
        {
          "text": "Returns a new vector with the first element set to a scalar value, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort2",
          "text": "simd_ushort2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort2(_:)-4i2ym",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort2"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort2(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort2(_:)-4i2ym"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort2(_:)-72vh1": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified sixteen-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort16",
          "text": "simd_ushort16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort2",
          "text": "simd_ushort2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort2(_:)-72vh1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort2"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort2(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort2(_:)-72vh1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort2(_:)-8zwg1": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified thirty two-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort32",
          "text": "simd_ushort32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort2",
          "text": "simd_ushort2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort2(_:)-8zwg1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort2"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort2(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort2(_:)-8zwg1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort2(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified scalar values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort2",
          "text": "simd_ushort2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort2(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort2"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort2(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort2(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort2_undef(_:)": {
      "abstract": [
        {
          "text": "Returns a new vector with the first element set to a scalar value, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort2_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort2",
          "text": "simd_ushort2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort2_undef(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort2_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort2_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort2_undef(_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-27z7q": {
      "abstract": [
        {
          "text": "Returns the maximum value of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_max"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort2",
          "text": "simd_ushort2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort2",
          "text": "simd_ushort2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort2",
          "text": "simd_ushort2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-27z7q",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_max"
        }
      ],
      "role": "symbol",
      "title": "simd_max(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_max(_:_:)-27z7q"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-717c8": {
      "abstract": [
        {
          "text": "Returns the minimum value of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_min"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort2",
          "text": "simd_ushort2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort2",
          "text": "simd_ushort2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort2",
          "text": "simd_ushort2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-717c8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_min"
        }
      ],
      "role": "symbol",
      "title": "simd_min(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_min(_:_:)-717c8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-2pw16": {
      "abstract": [
        {
          "text": "Returns the sum of all elements in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_add"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort2",
          "text": "simd_ushort2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-2pw16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_add"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_add(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_add(_:)-2pw16"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-4kcqg": {
      "abstract": [
        {
          "text": "Returns the maximum value in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_max"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort2",
          "text": "simd_ushort2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-4kcqg",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_max"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_max(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_max(_:)-4kcqg"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-49m28": {
      "abstract": [
        {
          "text": "Returns the miniumum value in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_min"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort2",
          "text": "simd_ushort2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-49m28",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_min"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_min(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_min(_:)-49m28"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort-3j49f": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort-3j49f",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort-3j49f"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort-3j95f": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort-3j95f",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort-3j95f"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort-3ja7h": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort-3ja7h",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort-3ja7h"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort-3jb1r": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort-3jb1r",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort-3jb1r"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort-3je8j": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort-3je8j",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort-3je8j"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort-3jhkd": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort-3jhkd",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort-3jhkd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort-3ji9x": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort-3ji9x",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort-3ji9x"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort-3jj4j": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort-3jj4j",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort-3jj4j"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort-3jk19": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort-3jk19",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort-3jk19"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort-3jl2n": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort-3jl2n",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort-3jl2n"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort1": {
      "abstract": [
        {
          "text": "A vector of one 16-bit unsigned integer element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ushort1"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ushort1"
        }
      ],
      "role": "symbol",
      "title": "simd_ushort1",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort16": {
      "abstract": [
        {
          "text": "A vector of sixteen 16-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ushort16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ushort16"
        }
      ],
      "role": "symbol",
      "title": "simd_ushort16",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort16"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort2": {
      "abstract": [
        {
          "text": "A vector of two 16-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ushort2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ushort2"
        }
      ],
      "role": "symbol",
      "title": "simd_ushort2",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort3": {
      "abstract": [
        {
          "text": "A vector of three 16-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ushort3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ushort3"
        }
      ],
      "role": "symbol",
      "title": "simd_ushort3",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort32": {
      "abstract": [
        {
          "text": "A vector of thirty-two 16-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ushort32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ushort32"
        }
      ],
      "role": "symbol",
      "title": "simd_ushort32",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort32"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort4": {
      "abstract": [
        {
          "text": "A vector of four 16-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ushort4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ushort4"
        }
      ],
      "role": "symbol",
      "title": "simd_ushort4",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort8": {
      "abstract": [
        {
          "text": "A vector of eight 16-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ushort8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ushort8"
        }
      ],
      "role": "symbol",
      "title": "simd_ushort8",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7h07e": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7h07e",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-7h07e"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7h23i": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7h23i",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-7h23i"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7h2xq": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7h2xq",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-7h2xq"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7h54a": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7h54a",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-7h54a"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7ha6i": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7ha6i",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-7ha6i"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7haim": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7haim",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-7haim"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7hb0i": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7hb0i",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-7hb0i"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7hc2m": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7hc2m",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-7hc2m"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7hcwu": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7hcwu",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-7hcwu"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7hf1m": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7hf1m",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-7hf1m"
    },
    "doc://com.apple.accelerate/documentation/simd/vector2-39jw3": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified scalar values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector2-39jw3",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector2",
      "type": "topic",
      "url": "/documentation/simd/vector2-39jw3"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_ushort2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vector_ushort2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_ushort2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vector_ushort2"
        }
      ],
      "role": "symbol",
      "title": "vector_ushort2",
      "type": "topic",
      "url": "/documentation/simd/vector_ushort2"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s5SIMD2V": {
      "abstract": [
        {
          "text": "A vector of two scalar values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SIMD2"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SIMDScalarP",
          "text": "SIMDScalar"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5SIMD2V",
      "kind": "symbol",
      "role": "symbol",
      "title": "SIMD2",
      "type": "topic",
      "url": "/documentation/Swift/SIMD2"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt16V": {
      "abstract": [
        {
          "text": "A 16-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt16"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt16V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt16",
      "type": "topic",
      "url": "/documentation/Swift/UInt16"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Vector-Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_ushort1",
        "doc://com.apple.accelerate/documentation/simd/simd_ushort3",
        "doc://com.apple.accelerate/documentation/simd/simd_ushort4",
        "doc://com.apple.accelerate/documentation/simd/simd_ushort8",
        "doc://com.apple.accelerate/documentation/simd/simd_ushort16",
        "doc://com.apple.accelerate/documentation/simd/simd_ushort32"
      ],
      "title": "Vector Data Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Functions-to-Create-Two-Element-Vectors-From-Other-Vectors",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_ushort2(_:)-2dkjj",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ushort2(_:)-2gsja",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ushort2(_:)-1sfxh",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ushort2(_:)-2yrlt",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ushort2(_:)-72vh1",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ushort2(_:)-8zwg1"
      ],
      "title": "Functions to Create Two-Element Vectors From Other Vectors"
    },
    {
      "anchor": "Functions-to-Create-Two-Element-Vectors-From-Scalar-Values",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_ushort2(_:)-4i2ym",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ushort2(_:_:)",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ushort2_undef(_:)"
      ],
      "title": "Functions to Create Two-Element Vectors From Scalar Values"
    },
    {
      "anchor": "Common-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-3o9ad",
        "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-ktbu"
      ],
      "title": "Common Functions"
    },
    {
      "anchor": "Reduce-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-49m28",
        "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-4kcqg",
        "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-2pw16"
      ],
      "title": "Reduce Functions"
    },
    {
      "anchor": "Extrema-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-717c8",
        "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-27z7q"
      ],
      "title": "Extrema Functions"
    },
    {
      "anchor": "Logic-and-Bitwise-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-649i9",
        "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1dffj",
        "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-9p6cd"
      ],
      "title": "Logic and Bitwise Functions"
    },
    {
      "anchor": "Alternative-Type-Alias",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/vector_ushort2"
      ],
      "title": "Alternative Type Alias"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "simd_ushort2"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/simd"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Functions-to-Create-Two-Element-Vectors-From-Other-Vectors",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_ushort2(_:)-2dkjj",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ushort2(_:)-2gsja",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ushort2(_:)-1sfxh",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ushort2(_:)-2yrlt",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ushort2(_:)-72vh1",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ushort2(_:)-8zwg1"
              ],
              "title": "Functions to Create Two-Element Vectors From Other Vectors"
            },
            {
              "anchor": "Functions-to-Create-Two-Element-Vectors-From-Scalar-Values",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_ushort2(_:)-4i2ym",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ushort2(_:_:)",
                "doc://com.apple.accelerate/documentation/simd/vector2-39jw3",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ushort2_undef(_:)"
              ],
              "title": "Functions to Create Two-Element Vectors From Scalar Values"
            },
            {
              "anchor": "Functions-to-Create-Two-Element-Vectors-From-Vectors-of-Other-Types",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_ushort-3j95f",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort-3jj4j",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort-3j49f",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort-3je8j",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort-3jb1r",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort-3jl2n",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort-3ja7h",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort-3jk19",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort-3ji9x",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort-3jhkd"
              ],
              "title": "Functions to Create Two-Element Vectors From Vectors of Other Types"
            },
            {
              "anchor": "Functions-to-Perform-Saturating-Conversion-From-Vectors-of-Other-Types",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7h07e",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7ha6i",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7h54a",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7hf1m",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7h23i",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7hc2m",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7h2xq",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7hcwu",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7hb0i",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7haim"
              ],
              "title": "Functions to Perform Saturating Conversion From Vectors of Other Types"
            },
            {
              "anchor": "Common-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-3o9ad",
                "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-ktbu"
              ],
              "title": "Common Functions"
            },
            {
              "anchor": "Reduce-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-49m28",
                "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-4kcqg",
                "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-2pw16"
              ],
              "title": "Reduce Functions"
            },
            {
              "anchor": "Extrema-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-717c8",
                "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-27z7q"
              ],
              "title": "Extrema Functions"
            },
            {
              "anchor": "Logic-and-Bitwise-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-649i9",
                "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1dffj",
                "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-9p6cd"
              ],
              "title": "Logic and Bitwise Functions"
            },
            {
              "anchor": "Alternative-Type-Alias",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/vector_ushort2"
              ],
              "title": "Alternative Type Alias"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Vector-Data-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_ushort1",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort3",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort4",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort8",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort16",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort32"
              ],
              "title": "Vector Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:]2s",
                    "text": "unsigned short __attribute__((ext_vector_type(2)))"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "simd_ushort2"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort2(_:)-2gsja/title",
          "value": "simd_make_ushort2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort2(_:)-2gsja/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort1/title",
          "value": "simd_ushort1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort1/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort2(_:)-8zwg1/title",
          "value": "simd_make_ushort2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort2(_:)-8zwg1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort3/title",
          "value": "simd_ushort3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_min(_:_:)-717c8/title",
          "value": "simd_min"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_min(_:_:)-717c8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_min"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_equal(_:_:)-ktbu/title",
          "value": "simd_equal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_equal(_:_:)-ktbu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_equal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort32/title",
          "value": "simd_ushort32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort32/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_bitselect(_:_:_:)-9p6cd/title",
          "value": "simd_bitselect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_bitselect(_:_:_:)-9p6cd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_bitselect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_max(_:)-4kcqg/title",
          "value": "simd_reduce_max"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_max(_:)-4kcqg/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_max"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_any(_:)-649i9/title",
          "value": "simd_any"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_any(_:)-649i9/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_any"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort2/title",
          "value": "simd_ushort2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_clamp(_:_:_:)-3o9ad/title",
          "value": "simd_clamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_clamp(_:_:_:)-3o9ad/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_clamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_all(_:)-1dffj/title",
          "value": "simd_all"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_all(_:)-1dffj/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_all"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort2_undef(_:)/title",
          "value": "simd_make_ushort2_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort2_undef(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort2_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort4/title",
          "value": "simd_ushort4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_min(_:)-49m28/title",
          "value": "simd_reduce_min"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_min(_:)-49m28/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_min"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort2(_:)-2dkjj/title",
          "value": "simd_make_ushort2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort2(_:)-2dkjj/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort8/title",
          "value": "simd_ushort8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_max(_:_:)-27z7q/title",
          "value": "simd_max"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_max(_:_:)-27z7q/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_max"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1vector_ushort2/title",
          "value": "vector_ushort2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1vector_ushort2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vector_ushort2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1vector_ushort2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vector_ushort2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort16/title",
          "value": "simd_ushort16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort16/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort2(_:)-72vh1/title",
          "value": "simd_make_ushort2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort2(_:)-72vh1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort2(_:)-1sfxh/title",
          "value": "simd_make_ushort2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort2(_:)-1sfxh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort2(_:)-2yrlt/title",
          "value": "simd_make_ushort2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort2(_:)-2yrlt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_add(_:)-2pw16/title",
          "value": "simd_reduce_add"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_add(_:)-2pw16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_add"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort2(_:_:)/title",
          "value": "simd_make_ushort2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort2(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort2(_:)-4i2ym/title",
          "value": "simd_make_ushort2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort2(_:)-4i2ym/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort2"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_ushort2"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/simd/simd_ushort2"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
