{
  "abstract": [
    {
      "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7hcwu"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_ushort_sat#]2l#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_ushort_sat"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_ushort_sat"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_ushort_sat"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_ushort2",
              "text": "simd_ushort2"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_ushort_sat"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_ulong2",
              "text": "simd_ulong2"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong2": {
      "abstract": [
        {
          "text": "A vector of two 64-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ulong2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ulong2"
        }
      ],
      "role": "symbol",
      "title": "simd_ulong2",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort2": {
      "abstract": [
        {
          "text": "A vector of two 16-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ushort2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ushort2"
        }
      ],
      "role": "symbol",
      "title": "simd_ushort2",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7h07e": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7h07e",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-7h07e"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7h23i": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7h23i",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-7h23i"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7h2xq": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7h2xq",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-7h2xq"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7h54a": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7h54a",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-7h54a"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7ha6i": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7ha6i",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-7ha6i"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7haim": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7haim",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-7haim"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7hb0i": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7hb0i",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-7hb0i"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7hc2m": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7hc2m",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-7hc2m"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7hcwu": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7hcwu",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-7hcwu"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7hf1m": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7hf1m",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-7hf1m"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Perform-Saturating-Conversion-From-Vectors-of-Other-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7h07e",
        "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7ha6i",
        "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7h54a",
        "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7hf1m",
        "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7h23i",
        "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7hc2m",
        "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7h2xq",
        "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7hb0i",
        "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7haim"
      ],
      "title": "Functions to Perform Saturating Conversion From Vectors of Other Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort2/title",
          "value": "simd_ushort2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong2/title",
          "value": "simd_ulong2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong2"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_ushort_sat-7hcwu"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
