{
  "abstract": [
    {
      "text": "A vector of eight 8-bit signed integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_char8"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@simd_char8",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simd_char8"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_char8"
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "simd_char8"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_char8"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5SIMD8V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5SIMD8V",
              "text": "SIMD8"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5CChara",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5CChara",
              "text": "CChar"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_abs(_:)-7oowg": {
      "abstract": [
        {
          "text": "Returns the absolute value of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_abs"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char8",
          "text": "simd_char8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char8",
          "text": "simd_char8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_abs(_:)-7oowg",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_abs"
        }
      ],
      "role": "symbol",
      "title": "simd_abs(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_abs(_:)-7oowg"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1yyw9": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_all"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char8",
          "text": "simd_char8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_bool",
          "text": "simd_bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1yyw9",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_all"
        }
      ],
      "role": "symbol",
      "title": "simd_all(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_all(_:)-1yyw9"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-6plnr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_any"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char8",
          "text": "simd_char8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_bool",
          "text": "simd_bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-6plnr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_any"
        }
      ],
      "role": "symbol",
      "title": "simd_any(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_any(_:)-6plnr"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-5bgc3": {
      "abstract": [
        {
          "text": "Returns a vector that contains elements from either the first or second parameter, based on the corresponding element in the third parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_bitselect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char8",
          "text": "simd_char8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char8",
          "text": "simd_char8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char8",
          "text": "simd_char8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char8",
          "text": "simd_char8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-5bgc3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_bitselect"
        }
      ],
      "role": "symbol",
      "title": "simd_bitselect(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_bitselect(_:_:_:)-5bgc3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char-7apve": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char-7apve",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char",
      "type": "topic",
      "url": "/documentation/simd/simd_char-7apve"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char-7aqw2": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char-7aqw2",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char",
      "type": "topic",
      "url": "/documentation/simd/simd_char-7aqw2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char-7arha": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char-7arha",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char",
      "type": "topic",
      "url": "/documentation/simd/simd_char-7arha"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char-7at2e": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char-7at2e",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char",
      "type": "topic",
      "url": "/documentation/simd/simd_char-7at2e"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char-7au4e": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char-7au4e",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char",
      "type": "topic",
      "url": "/documentation/simd/simd_char-7au4e"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char-7aure": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char-7aure",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char",
      "type": "topic",
      "url": "/documentation/simd/simd_char-7aure"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char-7azp6": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char-7azp6",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char",
      "type": "topic",
      "url": "/documentation/simd/simd_char-7azp6"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char-7b2w6": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char-7b2w6",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char",
      "type": "topic",
      "url": "/documentation/simd/simd_char-7b2w6"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char-7b3y6": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char-7b3y6",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char",
      "type": "topic",
      "url": "/documentation/simd/simd_char-7b3y6"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char-7b4ze": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char-7b4ze",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char",
      "type": "topic",
      "url": "/documentation/simd/simd_char-7b4ze"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char1": {
      "abstract": [
        {
          "text": "A vector of one 8-bit signed integer element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_char1"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_char1"
        }
      ],
      "role": "symbol",
      "title": "simd_char1",
      "type": "topic",
      "url": "/documentation/simd/simd_char1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char16": {
      "abstract": [
        {
          "text": "A vector of sixteen 8-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_char16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_char16"
        }
      ],
      "role": "symbol",
      "title": "simd_char16",
      "type": "topic",
      "url": "/documentation/simd/simd_char16"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char2": {
      "abstract": [
        {
          "text": "A vector of two 8-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_char2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_char2"
        }
      ],
      "role": "symbol",
      "title": "simd_char2",
      "type": "topic",
      "url": "/documentation/simd/simd_char2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char3": {
      "abstract": [
        {
          "text": "A vector of three 8-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_char3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_char3"
        }
      ],
      "role": "symbol",
      "title": "simd_char3",
      "type": "topic",
      "url": "/documentation/simd/simd_char3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char32": {
      "abstract": [
        {
          "text": "A vector of thirty-two 8-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_char32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_char32"
        }
      ],
      "role": "symbol",
      "title": "simd_char32",
      "type": "topic",
      "url": "/documentation/simd/simd_char32"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char4": {
      "abstract": [
        {
          "text": "A vector of four 8-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_char4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_char4"
        }
      ],
      "role": "symbol",
      "title": "simd_char4",
      "type": "topic",
      "url": "/documentation/simd/simd_char4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char64": {
      "abstract": [
        {
          "text": "A vector of sixty-four 8-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_char64"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char64",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_char64"
        }
      ],
      "role": "symbol",
      "title": "simd_char64",
      "type": "topic",
      "url": "/documentation/simd/simd_char64"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char8": {
      "abstract": [
        {
          "text": "A vector of eight 8-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_char8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_char8"
        }
      ],
      "role": "symbol",
      "title": "simd_char8",
      "type": "topic",
      "url": "/documentation/simd/simd_char8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1jyvr": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1jyvr",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_char_sat-1jyvr"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1k125": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1k125",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_char_sat-1k125"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1k1zv": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1k1zv",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_char_sat-1k1zv"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1k3vb": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1k3vb",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_char_sat-1k3vb"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1k8uv": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1k8uv",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_char_sat-1k8uv"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1kb19": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1kb19",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_char_sat-1kb19"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1kbyz": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1kbyz",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_char_sat-1kbyz"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1kcv9": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1kcv9",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_char_sat-1kcv9"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1kdj1": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1kdj1",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_char_sat-1kdj1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1kdqv": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1kdqv",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_char_sat-1kdqv"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-6t9ze": {
      "abstract": [
        {
          "text": "Returns each element in a vector clamped to a specified range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_clamp"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char8",
          "text": "simd_char8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char8",
          "text": "simd_char8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char8",
          "text": "simd_char8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char8",
          "text": "simd_char8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-6t9ze",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_clamp"
        }
      ],
      "role": "symbol",
      "title": "simd_clamp(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_clamp(_:_:_:)-6t9ze"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-7xed4": {
      "abstract": [
        {
          "text": "Returns true if every element in a vector is exactly equal to the corresponding element in a second vector, and otherwise returns false.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_equal"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char8",
          "text": "simd_char8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char8",
          "text": "simd_char8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_bool",
          "text": "simd_bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-7xed4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_equal"
        }
      ],
      "role": "symbol",
      "title": "simd_equal(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_equal(_:_:)-7xed4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_char8(_:)-2wraz": {
      "abstract": [
        {
          "text": "Returns a new vector with the first element set to a scalar value, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_char8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char8",
          "text": "simd_char8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_char8(_:)-2wraz",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_char8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_char8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_char8(_:)-2wraz"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_char8(_:)-39q4x": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified three-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_char8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char3",
          "text": "simd_char3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char8",
          "text": "simd_char8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_char8(_:)-39q4x",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_char8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_char8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_char8(_:)-39q4x"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_char8(_:)-3e9h4": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_char8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char2",
          "text": "simd_char2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char8",
          "text": "simd_char8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_char8(_:)-3e9h4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_char8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_char8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_char8(_:)-3e9h4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_char8(_:)-3y2oy": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified four-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_char8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char4",
          "text": "simd_char4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char8",
          "text": "simd_char8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_char8(_:)-3y2oy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_char8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_char8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_char8(_:)-3y2oy"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_char8(_:)-497r7": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified sixteen-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_char8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char16",
          "text": "simd_char16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char8",
          "text": "simd_char8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_char8(_:)-497r7",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_char8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_char8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_char8(_:)-497r7"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_char8(_:)-4c00u": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_char8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char8",
          "text": "simd_char8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char8",
          "text": "simd_char8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_char8(_:)-4c00u",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_char8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_char8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_char8(_:)-4c00u"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_char8(_:)-4m1k5": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified sixty four-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_char8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char64",
          "text": "simd_char64"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char8",
          "text": "simd_char8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_char8(_:)-4m1k5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_char8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_char8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_char8(_:)-4m1k5"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_char8(_:)-tbln": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified thrity two-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_char8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char32",
          "text": "simd_char32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char8",
          "text": "simd_char8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_char8(_:)-tbln",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_char8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_char8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_char8(_:)-tbln"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_char8(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_char8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char4",
          "text": "simd_char4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char4",
          "text": "simd_char4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char8",
          "text": "simd_char8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_char8(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_char8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_char8(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_char8(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_char8_undef(_:)-4zw8k": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_char8_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char2",
          "text": "simd_char2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char8",
          "text": "simd_char8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_char8_undef(_:)-4zw8k",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_char8_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_char8_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_char8_undef(_:)-4zw8k"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_char8_undef(_:)-53bml": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified three-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_char8_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char3",
          "text": "simd_char3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char8",
          "text": "simd_char8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_char8_undef(_:)-53bml",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_char8_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_char8_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_char8_undef(_:)-53bml"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_char8_undef(_:)-5kqwe": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified four-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_char8_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char4",
          "text": "simd_char4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char8",
          "text": "simd_char8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_char8_undef(_:)-5kqwe",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_char8_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_char8_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_char8_undef(_:)-5kqwe"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_char8_undef(_:)-830qy": {
      "abstract": [
        {
          "text": "Returns a new vector with the first element set to a scalar value, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_char8_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char8",
          "text": "simd_char8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_char8_undef(_:)-830qy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_char8_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_char8_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_char8_undef(_:)-830qy"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-1zyht": {
      "abstract": [
        {
          "text": "Returns the maximum value of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_max"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char8",
          "text": "simd_char8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char8",
          "text": "simd_char8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char8",
          "text": "simd_char8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-1zyht",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_max"
        }
      ],
      "role": "symbol",
      "title": "simd_max(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_max(_:_:)-1zyht"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-66w6r": {
      "abstract": [
        {
          "text": "Returns the minimum value of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_min"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char8",
          "text": "simd_char8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char8",
          "text": "simd_char8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char8",
          "text": "simd_char8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-66w6r",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_min"
        }
      ],
      "role": "symbol",
      "title": "simd_min(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_min(_:_:)-66w6r"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-3b8ak": {
      "abstract": [
        {
          "text": "Returns the sum of all elements in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_add"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char8",
          "text": "simd_char8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-3b8ak",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_add"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_add(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_add(_:)-3b8ak"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-55mb2": {
      "abstract": [
        {
          "text": "Returns the maximum value in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_max"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char8",
          "text": "simd_char8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-55mb2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_max"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_max(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_max(_:)-55mb2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-3omfa": {
      "abstract": [
        {
          "text": "Returns the miniumum value in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_min"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char8",
          "text": "simd_char8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-3omfa",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_min"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_min(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_min(_:)-3omfa"
    },
    "doc://com.apple.accelerate/documentation/simd/vector8-73z2d": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector8-73z2d",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector8",
      "type": "topic",
      "url": "/documentation/simd/vector8-73z2d"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_char8": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vector_char8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_char8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vector_char8"
        }
      ],
      "role": "symbol",
      "title": "vector_char8",
      "type": "topic",
      "url": "/documentation/simd/vector_char8"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s5CChara": {
      "abstract": [
        {
          "text": "The C char type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Int8V",
          "text": "Int8"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5CChara",
      "kind": "symbol",
      "role": "symbol",
      "title": "CChar",
      "type": "topic",
      "url": "/documentation/Swift/CChar"
    },
    "doc://com.externally.resolved.symbol/s:s5SIMD8V": {
      "abstract": [
        {
          "text": "A vector of eight scalar values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SIMD8"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SIMDScalarP",
          "text": "SIMDScalar"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5SIMD8V",
      "kind": "symbol",
      "role": "symbol",
      "title": "SIMD8",
      "type": "topic",
      "url": "/documentation/Swift/SIMD8"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Vector-Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_char1",
        "doc://com.apple.accelerate/documentation/simd/simd_char2",
        "doc://com.apple.accelerate/documentation/simd/simd_char3",
        "doc://com.apple.accelerate/documentation/simd/simd_char4",
        "doc://com.apple.accelerate/documentation/simd/simd_char16",
        "doc://com.apple.accelerate/documentation/simd/simd_char32",
        "doc://com.apple.accelerate/documentation/simd/simd_char64"
      ],
      "title": "Vector Data Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Functions-to-Create-Eight-Element-Vectors-From-Other-Vectors",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_char8(_:)-3e9h4",
        "doc://com.apple.accelerate/documentation/simd/simd_make_char8(_:)-39q4x",
        "doc://com.apple.accelerate/documentation/simd/simd_make_char8(_:)-3y2oy",
        "doc://com.apple.accelerate/documentation/simd/simd_make_char8(_:)-4c00u",
        "doc://com.apple.accelerate/documentation/simd/simd_make_char8(_:)-497r7",
        "doc://com.apple.accelerate/documentation/simd/simd_make_char8(_:)-tbln",
        "doc://com.apple.accelerate/documentation/simd/simd_make_char8(_:)-4m1k5",
        "doc://com.apple.accelerate/documentation/simd/simd_make_char8(_:_:)",
        "doc://com.apple.accelerate/documentation/simd/simd_make_char8_undef(_:)-4zw8k",
        "doc://com.apple.accelerate/documentation/simd/simd_make_char8_undef(_:)-53bml",
        "doc://com.apple.accelerate/documentation/simd/simd_make_char8_undef(_:)-5kqwe"
      ],
      "title": "Functions to Create Eight-Element Vectors From Other Vectors"
    },
    {
      "anchor": "Functions-to-Create-Eight-Element-Vectors-From-Scalar-Values",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_char8(_:)-2wraz",
        "doc://com.apple.accelerate/documentation/simd/simd_make_char8_undef(_:)-830qy"
      ],
      "title": "Functions to Create Eight-Element Vectors From Scalar Values"
    },
    {
      "anchor": "Common-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_abs(_:)-7oowg",
        "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-6t9ze",
        "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-7xed4"
      ],
      "title": "Common Functions"
    },
    {
      "anchor": "Reduce-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-3omfa",
        "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-55mb2",
        "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-3b8ak"
      ],
      "title": "Reduce Functions"
    },
    {
      "anchor": "Extrema-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-66w6r",
        "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-1zyht"
      ],
      "title": "Extrema Functions"
    },
    {
      "anchor": "Logic-and-Bitwise-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-6plnr",
        "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1yyw9",
        "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-5bgc3"
      ],
      "title": "Logic and Bitwise Functions"
    },
    {
      "anchor": "Alternative-Type-Alias",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/vector_char8"
      ],
      "title": "Alternative Type Alias"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "simd_char8"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/simd"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Functions-to-Create-Eight-Element-Vectors-From-Other-Vectors",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_char8(_:)-3e9h4",
                "doc://com.apple.accelerate/documentation/simd/simd_make_char8(_:)-39q4x",
                "doc://com.apple.accelerate/documentation/simd/simd_make_char8(_:)-3y2oy",
                "doc://com.apple.accelerate/documentation/simd/simd_make_char8(_:)-4c00u",
                "doc://com.apple.accelerate/documentation/simd/simd_make_char8(_:)-497r7",
                "doc://com.apple.accelerate/documentation/simd/simd_make_char8(_:)-tbln",
                "doc://com.apple.accelerate/documentation/simd/simd_make_char8(_:)-4m1k5",
                "doc://com.apple.accelerate/documentation/simd/simd_make_char8(_:_:)",
                "doc://com.apple.accelerate/documentation/simd/vector8-73z2d",
                "doc://com.apple.accelerate/documentation/simd/simd_make_char8_undef(_:)-4zw8k",
                "doc://com.apple.accelerate/documentation/simd/simd_make_char8_undef(_:)-53bml",
                "doc://com.apple.accelerate/documentation/simd/simd_make_char8_undef(_:)-5kqwe"
              ],
              "title": "Functions to Create Eight-Element Vectors From Other Vectors"
            },
            {
              "anchor": "Functions-to-Create-Eight-Element-Vectors-From-Scalar-Values",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_char8(_:)-2wraz",
                "doc://com.apple.accelerate/documentation/simd/simd_make_char8_undef(_:)-830qy"
              ],
              "title": "Functions to Create Eight-Element Vectors From Scalar Values"
            },
            {
              "anchor": "Functions-to-Create-Eight-Element-Vectors-From-Vectors-of-Other-Types",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_char-7azp6",
                "doc://com.apple.accelerate/documentation/simd/simd_char-7apve",
                "doc://com.apple.accelerate/documentation/simd/simd_char-7b4ze",
                "doc://com.apple.accelerate/documentation/simd/simd_char-7aure",
                "doc://com.apple.accelerate/documentation/simd/simd_char-7b2w6",
                "doc://com.apple.accelerate/documentation/simd/simd_char-7at2e",
                "doc://com.apple.accelerate/documentation/simd/simd_char-7b3y6",
                "doc://com.apple.accelerate/documentation/simd/simd_char-7au4e",
                "doc://com.apple.accelerate/documentation/simd/simd_char-7aqw2",
                "doc://com.apple.accelerate/documentation/simd/simd_char-7arha"
              ],
              "title": "Functions to Create Eight-Element Vectors From Vectors of Other Types"
            },
            {
              "anchor": "Functions-to-Perform-Saturating-Conversion-From-Vectors-of-Other-Types",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1k3vb",
                "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1kdqv",
                "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1jyvr",
                "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1k8uv",
                "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1k1zv",
                "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1kbyz",
                "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1k125",
                "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1kb19",
                "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1kcv9",
                "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1kdj1"
              ],
              "title": "Functions to Perform Saturating Conversion From Vectors of Other Types"
            },
            {
              "anchor": "Common-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_abs(_:)-7oowg",
                "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-6t9ze",
                "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-7xed4"
              ],
              "title": "Common Functions"
            },
            {
              "anchor": "Reduce-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-3omfa",
                "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-55mb2",
                "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-3b8ak"
              ],
              "title": "Reduce Functions"
            },
            {
              "anchor": "Extrema-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-66w6r",
                "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-1zyht"
              ],
              "title": "Extrema Functions"
            },
            {
              "anchor": "Logic-and-Bitwise-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-6plnr",
                "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1yyw9",
                "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-5bgc3"
              ],
              "title": "Logic and Bitwise Functions"
            },
            {
              "anchor": "Alternative-Type-Alias",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/vector_char8"
              ],
              "title": "Alternative Type Alias"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Vector-Data-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_char1",
                "doc://com.apple.accelerate/documentation/simd/simd_char2",
                "doc://com.apple.accelerate/documentation/simd/simd_char3",
                "doc://com.apple.accelerate/documentation/simd/simd_char4",
                "doc://com.apple.accelerate/documentation/simd/simd_char16",
                "doc://com.apple.accelerate/documentation/simd/simd_char32",
                "doc://com.apple.accelerate/documentation/simd/simd_char64"
              ],
              "title": "Vector Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:]8C",
                    "text": "char __attribute__((ext_vector_type(8)))"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "simd_char8"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char8(_:)-39q4x/title",
          "value": "simd_make_char8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char8(_:)-39q4x/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_char8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char3/title",
          "value": "simd_char3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_min(_:_:)-66w6r/title",
          "value": "simd_min"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_min(_:_:)-66w6r/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_min"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1vector_char8/title",
          "value": "vector_char8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1vector_char8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vector_char8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1vector_char8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vector_char8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char16/title",
          "value": "simd_char16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char16/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_max(_:_:)-1zyht/title",
          "value": "simd_max"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_max(_:_:)-1zyht/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_max"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_min(_:)-3omfa/title",
          "value": "simd_reduce_min"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_min(_:)-3omfa/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_min"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char8_undef(_:)-4zw8k/title",
          "value": "simd_make_char8_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char8_undef(_:)-4zw8k/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_char8_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char8(_:)-tbln/title",
          "value": "simd_make_char8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char8(_:)-tbln/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_char8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_equal(_:_:)-7xed4/title",
          "value": "simd_equal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_equal(_:_:)-7xed4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_equal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char8(_:)-3y2oy/title",
          "value": "simd_make_char8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char8(_:)-3y2oy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_char8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char1/title",
          "value": "simd_char1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char1/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_abs(_:)-7oowg/title",
          "value": "simd_abs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_abs(_:)-7oowg/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_abs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char8(_:)-497r7/title",
          "value": "simd_make_char8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char8(_:)-497r7/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_char8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char8(_:_:)/title",
          "value": "simd_make_char8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char8(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_char8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_add(_:)-3b8ak/title",
          "value": "simd_reduce_add"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_add(_:)-3b8ak/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_add"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_clamp(_:_:_:)-6t9ze/title",
          "value": "simd_clamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_clamp(_:_:_:)-6t9ze/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_clamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_bitselect(_:_:_:)-5bgc3/title",
          "value": "simd_bitselect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_bitselect(_:_:_:)-5bgc3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_bitselect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char8(_:)-3e9h4/title",
          "value": "simd_make_char8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char8(_:)-3e9h4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_char8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char8(_:)-2wraz/title",
          "value": "simd_make_char8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char8(_:)-2wraz/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_char8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char8(_:)-4m1k5/title",
          "value": "simd_make_char8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char8(_:)-4m1k5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_char8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_all(_:)-1yyw9/title",
          "value": "simd_all"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_all(_:)-1yyw9/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_all"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char8/title",
          "value": "simd_char8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char4/title",
          "value": "simd_char4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char8_undef(_:)-5kqwe/title",
          "value": "simd_make_char8_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char8_undef(_:)-5kqwe/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_char8_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char64/title",
          "value": "simd_char64"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char64/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char64/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char8_undef(_:)-830qy/title",
          "value": "simd_make_char8_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char8_undef(_:)-830qy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_char8_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_max(_:)-55mb2/title",
          "value": "simd_reduce_max"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_max(_:)-55mb2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_max"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_any(_:)-6plnr/title",
          "value": "simd_any"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_any(_:)-6plnr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_any"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char32/title",
          "value": "simd_char32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char32/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char2/title",
          "value": "simd_char2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char8(_:)-4c00u/title",
          "value": "simd_make_char8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char8(_:)-4c00u/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_char8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char8_undef(_:)-53bml/title",
          "value": "simd_make_char8_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char8_undef(_:)-53bml/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_char8_undef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_char8"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/simd/simd_char8"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
