{
  "abstract": [
    {
      "text": "A vector of one 16-bit floating-point element.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_half1"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@simd_half1",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simd_half1"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_half1"
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "simd_half1"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_half1"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s7Float16V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s7Float16V",
              "text": "Float16"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-c4d6": {
      "abstract": [
        {
          "text": "Returns each element in a vector clamped to a specified range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_clamp"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float16V",
          "text": "Float16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float16V",
          "text": "Float16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float16V",
          "text": "Float16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float16V",
          "text": "Float16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-c4d6",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_clamp"
        }
      ],
      "role": "symbol",
      "title": "simd_clamp(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_clamp(_:_:_:)-c4d6"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_fast_recip(_:)-1ibu": {
      "abstract": [
        {
          "text": "Returns the fast reciprocal of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_fast_recip"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float16V",
          "text": "Float16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float16V",
          "text": "Float16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_fast_recip(_:)-1ibu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_fast_recip"
        }
      ],
      "role": "symbol",
      "title": "simd_fast_recip(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_fast_recip(_:)-1ibu"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_fast_rsqrt(_:)-43sls": {
      "abstract": [
        {
          "text": "Returns the fast reciprocal square root of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_fast_rsqrt"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float16V",
          "text": "Float16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float16V",
          "text": "Float16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_fast_rsqrt(_:)-43sls",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_fast_rsqrt"
        }
      ],
      "role": "symbol",
      "title": "simd_fast_rsqrt(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_fast_rsqrt(_:)-43sls"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_fract(_:)-1wwew": {
      "abstract": [
        {
          "text": "Returns the fractional part of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_fract"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float16V",
          "text": "Float16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float16V",
          "text": "Float16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_fract(_:)-1wwew",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_fract"
        }
      ],
      "role": "symbol",
      "title": "simd_fract(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_fract(_:)-1wwew"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half1": {
      "abstract": [
        {
          "text": "A vector of one 16-bit floating-point element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_half1"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_half1"
        }
      ],
      "role": "symbol",
      "title": "simd_half1",
      "type": "topic",
      "url": "/documentation/simd/simd_half1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half16": {
      "abstract": [
        {
          "text": "A vector of sixteen 16-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_half16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_half16"
        }
      ],
      "role": "symbol",
      "title": "simd_half16",
      "type": "topic",
      "url": "/documentation/simd/simd_half16"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half2": {
      "abstract": [
        {
          "text": "A vector of two 16-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_half2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_half2"
        }
      ],
      "role": "symbol",
      "title": "simd_half2",
      "type": "topic",
      "url": "/documentation/simd/simd_half2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half3": {
      "abstract": [
        {
          "text": "A vector of three 16-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_half3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_half3"
        }
      ],
      "role": "symbol",
      "title": "simd_half3",
      "type": "topic",
      "url": "/documentation/simd/simd_half3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half32": {
      "abstract": [
        {
          "text": "A vector of thirty-two 16-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_half32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_half32"
        }
      ],
      "role": "symbol",
      "title": "simd_half32",
      "type": "topic",
      "url": "/documentation/simd/simd_half32"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half4": {
      "abstract": [
        {
          "text": "A vector of four 16-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_half4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_half4"
        }
      ],
      "role": "symbol",
      "title": "simd_half4",
      "type": "topic",
      "url": "/documentation/simd/simd_half4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half8": {
      "abstract": [
        {
          "text": "A vector of eight 16-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_half8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_half8"
        }
      ],
      "role": "symbol",
      "title": "simd_half8",
      "type": "topic",
      "url": "/documentation/simd/simd_half8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-3f8z7": {
      "abstract": [
        {
          "text": "Returns the maximum value of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_max"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float16V",
          "text": "Float16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float16V",
          "text": "Float16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float16V",
          "text": "Float16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-3f8z7",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_max"
        }
      ],
      "role": "symbol",
      "title": "simd_max(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_max(_:_:)-3f8z7"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-57wqc": {
      "abstract": [
        {
          "text": "Returns the minimum value of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_min"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float16V",
          "text": "Float16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float16V",
          "text": "Float16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float16V",
          "text": "Float16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-57wqc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_min"
        }
      ],
      "role": "symbol",
      "title": "simd_min(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_min(_:_:)-57wqc"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_mix(_:_:_:)-3mcrj": {
      "abstract": [
        {
          "text": "Returns an element-wise linearly interpolated value between two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_mix"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float16V",
          "text": "Float16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float16V",
          "text": "Float16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float16V",
          "text": "Float16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float16V",
          "text": "Float16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_mix(_:_:_:)-3mcrj",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_mix"
        }
      ],
      "role": "symbol",
      "title": "simd_mix(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_mix(_:_:_:)-3mcrj"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_muladd(_:_:_:)-41x8n": {
      "abstract": [
        {
          "text": "Returns the multiply-add result for corresponding elements in three vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_muladd"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float16V",
          "text": "Float16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float16V",
          "text": "Float16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float16V",
          "text": "Float16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float16V",
          "text": "Float16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_muladd(_:_:_:)-41x8n",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_muladd"
        }
      ],
      "role": "symbol",
      "title": "simd_muladd(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_muladd(_:_:_:)-41x8n"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_precise_recip(_:)-6q9sp": {
      "abstract": [
        {
          "text": "Returns the precise reciprocal of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_precise_recip"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float16V",
          "text": "Float16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float16V",
          "text": "Float16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_precise_recip(_:)-6q9sp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_precise_recip"
        }
      ],
      "role": "symbol",
      "title": "simd_precise_recip(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_precise_recip(_:)-6q9sp"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_precise_rsqrt(_:)-5fjxk": {
      "abstract": [
        {
          "text": "Returns the precise reciprocal square root of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_precise_rsqrt"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float16V",
          "text": "Float16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float16V",
          "text": "Float16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_precise_rsqrt(_:)-5fjxk",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_precise_rsqrt"
        }
      ],
      "role": "symbol",
      "title": "simd_precise_rsqrt(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_precise_rsqrt(_:)-5fjxk"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_recip(_:)-7yi5r": {
      "abstract": [
        {
          "text": "Returns the reciprocal of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_recip"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float16V",
          "text": "Float16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float16V",
          "text": "Float16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_recip(_:)-7yi5r",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_recip"
        }
      ],
      "role": "symbol",
      "title": "simd_recip(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_recip(_:)-7yi5r"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_rsqrt(_:)-4yfi0": {
      "abstract": [
        {
          "text": "Returns the reciprocal square root of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_rsqrt"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float16V",
          "text": "Float16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float16V",
          "text": "Float16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_rsqrt(_:)-4yfi0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_rsqrt"
        }
      ],
      "role": "symbol",
      "title": "simd_rsqrt(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_rsqrt(_:)-4yfi0"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_sign(_:)-9365i": {
      "abstract": [
        {
          "text": "Returns the sign of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_sign"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float16V",
          "text": "Float16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float16V",
          "text": "Float16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_sign(_:)-9365i",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_sign"
        }
      ],
      "role": "symbol",
      "title": "simd_sign(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_sign(_:)-9365i"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_smoothstep(_:_:_:)-6zp30": {
      "abstract": [
        {
          "text": "Returns an element-wise smoothly interpolated value between two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_smoothstep"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float16V",
          "text": "Float16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float16V",
          "text": "Float16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float16V",
          "text": "Float16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float16V",
          "text": "Float16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_smoothstep(_:_:_:)-6zp30",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_smoothstep"
        }
      ],
      "role": "symbol",
      "title": "simd_smoothstep(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_smoothstep(_:_:_:)-6zp30"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_step(_:_:)-u24h": {
      "abstract": [
        {
          "text": "Returns zero for each element in a vector less than a specified edge, and otherwise returns one.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_step"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float16V",
          "text": "Float16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float16V",
          "text": "Float16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float16V",
          "text": "Float16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_step(_:_:)-u24h",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_step"
        }
      ],
      "role": "symbol",
      "title": "simd_step(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_step(_:_:)-u24h"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s7Float16V": {
      "abstract": [
        {
          "text": "A half-precision (16b), floating-point value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Float16"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7Float16V",
      "kind": "symbol",
      "role": "symbol",
      "title": "Float16",
      "type": "topic",
      "url": "/documentation/Swift/Float16"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Vector-data-types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_half2",
        "doc://com.apple.accelerate/documentation/simd/simd_half3",
        "doc://com.apple.accelerate/documentation/simd/simd_half4",
        "doc://com.apple.accelerate/documentation/simd/simd_half8",
        "doc://com.apple.accelerate/documentation/simd/simd_half16",
        "doc://com.apple.accelerate/documentation/simd/simd_half32"
      ],
      "title": "Vector data types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Common-functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-c4d6",
        "doc://com.apple.accelerate/documentation/simd/simd_fract(_:)-1wwew",
        "doc://com.apple.accelerate/documentation/simd/simd_sign(_:)-9365i",
        "doc://com.apple.accelerate/documentation/simd/simd_step(_:_:)-u24h"
      ],
      "title": "Common functions"
    },
    {
      "anchor": "Interpolation-functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_mix(_:_:_:)-3mcrj",
        "doc://com.apple.accelerate/documentation/simd/simd_smoothstep(_:_:_:)-6zp30"
      ],
      "title": "Interpolation functions"
    },
    {
      "anchor": "Extrema-functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-3f8z7",
        "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-57wqc"
      ],
      "title": "Extrema functions"
    },
    {
      "anchor": "Reciprocal-and-reciprocal-square-root-functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_recip(_:)-7yi5r",
        "doc://com.apple.accelerate/documentation/simd/simd_rsqrt(_:)-4yfi0",
        "doc://com.apple.accelerate/documentation/simd/simd_precise_recip(_:)-6q9sp",
        "doc://com.apple.accelerate/documentation/simd/simd_precise_rsqrt(_:)-5fjxk",
        "doc://com.apple.accelerate/documentation/simd/simd_fast_recip(_:)-1ibu",
        "doc://com.apple.accelerate/documentation/simd/simd_fast_rsqrt(_:)-43sls"
      ],
      "title": "Reciprocal and reciprocal square root functions"
    },
    {
      "anchor": "Math-functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_muladd(_:_:_:)-41x8n"
      ],
      "title": "Math functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "simd_half1"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/simd"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Common-functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-c4d6",
                "doc://com.apple.accelerate/documentation/simd/simd_fract(_:)-1wwew",
                "doc://com.apple.accelerate/documentation/simd/simd_sign(_:)-9365i",
                "doc://com.apple.accelerate/documentation/simd/simd_step(_:_:)-u24h"
              ],
              "title": "Common functions"
            },
            {
              "anchor": "Interpolation-functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_mix(_:_:_:)-3mcrj",
                "doc://com.apple.accelerate/documentation/simd/simd_smoothstep(_:_:_:)-6zp30"
              ],
              "title": "Interpolation functions"
            },
            {
              "anchor": "Extrema-functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-3f8z7",
                "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-57wqc"
              ],
              "title": "Extrema functions"
            },
            {
              "anchor": "Reciprocal-and-reciprocal-square-root-functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_recip(_:)-7yi5r",
                "doc://com.apple.accelerate/documentation/simd/simd_rsqrt(_:)-4yfi0",
                "doc://com.apple.accelerate/documentation/simd/simd_precise_recip(_:)-6q9sp",
                "doc://com.apple.accelerate/documentation/simd/simd_precise_rsqrt(_:)-5fjxk",
                "doc://com.apple.accelerate/documentation/simd/simd_fast_recip(_:)-1ibu",
                "doc://com.apple.accelerate/documentation/simd/simd_fast_rsqrt(_:)-43sls"
              ],
              "title": "Reciprocal and reciprocal square root functions"
            },
            {
              "anchor": "Math-functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_muladd(_:_:_:)-41x8n"
              ],
              "title": "Math functions"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Vector-data-types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_half2",
                "doc://com.apple.accelerate/documentation/simd/simd_half3",
                "doc://com.apple.accelerate/documentation/simd/simd_half4",
                "doc://com.apple.accelerate/documentation/simd/simd_half8",
                "doc://com.apple.accelerate/documentation/simd/simd_half16",
                "doc://com.apple.accelerate/documentation/simd/simd_half32"
              ],
              "title": "Vector data types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:h",
                    "text": "_Float16"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "simd_half1"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_min(_:_:)-57wqc/title",
          "value": "simd_min"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_min(_:_:)-57wqc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_min"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_fast_recip(_:)-1ibu/title",
          "value": "simd_fast_recip"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_fast_recip(_:)-1ibu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_fast_recip"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_fast_rsqrt(_:)-43sls/title",
          "value": "simd_fast_rsqrt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_fast_rsqrt(_:)-43sls/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_fast_rsqrt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_muladd(_:_:_:)-41x8n/title",
          "value": "simd_muladd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_muladd(_:_:_:)-41x8n/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_muladd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_mix(_:_:_:)-3mcrj/title",
          "value": "simd_mix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_mix(_:_:_:)-3mcrj/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_mix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_precise_rsqrt(_:)-5fjxk/title",
          "value": "simd_precise_rsqrt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_precise_rsqrt(_:)-5fjxk/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_precise_rsqrt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_recip(_:)-7yi5r/title",
          "value": "simd_recip"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_recip(_:)-7yi5r/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_recip"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_clamp(_:_:_:)-c4d6/title",
          "value": "simd_clamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_clamp(_:_:_:)-c4d6/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_clamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half2/title",
          "value": "simd_half2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_step(_:_:)-u24h/title",
          "value": "simd_step"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_step(_:_:)-u24h/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_step"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half16/title",
          "value": "simd_half16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half16/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half8/title",
          "value": "simd_half8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_fract(_:)-1wwew/title",
          "value": "simd_fract"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_fract(_:)-1wwew/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_fract"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half32/title",
          "value": "simd_half32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half32/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_rsqrt(_:)-4yfi0/title",
          "value": "simd_rsqrt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_rsqrt(_:)-4yfi0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_rsqrt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_sign(_:)-9365i/title",
          "value": "simd_sign"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_sign(_:)-9365i/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_sign"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half3/title",
          "value": "simd_half3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_max(_:_:)-3f8z7/title",
          "value": "simd_max"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_max(_:_:)-3f8z7/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_max"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half4/title",
          "value": "simd_half4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_precise_recip(_:)-6q9sp/title",
          "value": "simd_precise_recip"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_precise_recip(_:)-6q9sp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_precise_recip"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half1/title",
          "value": "simd_half1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half1/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_smoothstep(_:_:_:)-6zp30/title",
          "value": "simd_smoothstep"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_smoothstep(_:_:_:)-6zp30/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_smoothstep"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_half1"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/simd/simd_half1"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
