{
  "abstract": [
    {
      "text": "A vector of thirty-two 8-bit unsigned integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_uchar32"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@simd_uchar32",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simd_uchar32"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_uchar32"
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "simd_uchar32"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_uchar32"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6SIMD32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6SIMD32V",
              "text": "SIMD32"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5UInt8V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5UInt8V",
              "text": "UInt8"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1khgz": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_all"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_bool",
          "text": "simd_bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1khgz",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_all"
        }
      ],
      "role": "symbol",
      "title": "simd_all(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_all(_:)-1khgz"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-3apcl": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_any"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_bool",
          "text": "simd_bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-3apcl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_any"
        }
      ],
      "role": "symbol",
      "title": "simd_any(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_any(_:)-3apcl"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-49vzj": {
      "abstract": [
        {
          "text": "Returns a vector that contains elements from either the first or second parameter, based on the corresponding element in the third parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_bitselect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char32",
          "text": "simd_char32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-49vzj",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_bitselect"
        }
      ],
      "role": "symbol",
      "title": "simd_bitselect(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_bitselect(_:_:_:)-49vzj"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-3bfcx": {
      "abstract": [
        {
          "text": "Returns each element in a vector clamped to a specified range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_clamp"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-3bfcx",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_clamp"
        }
      ],
      "role": "symbol",
      "title": "simd_clamp(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_clamp(_:_:_:)-3bfcx"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-qmif": {
      "abstract": [
        {
          "text": "Returns true if every element in a vector is exactly equal to the corresponding element in a second vector, and otherwise returns false.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_equal"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_bool",
          "text": "simd_bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-qmif",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_equal"
        }
      ],
      "role": "symbol",
      "title": "simd_equal(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_equal(_:_:)-qmif"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-3c53d": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar32"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-3c53d",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar32"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar32(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar32(_:)-3c53d"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-3tap7": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified sixty four-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar32"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar64",
          "text": "simd_uchar64"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-3tap7",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar32"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar32(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar32(_:)-3tap7"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-8z2lu": {
      "abstract": [
        {
          "text": "Returns a new vector with the first element set to a scalar value, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar32"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-8z2lu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar32"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar32(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar32(_:)-8z2lu"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-94jec": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified sixteen-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar32"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar16",
          "text": "simd_uchar16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-94jec",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar32"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar32(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar32(_:)-94jec"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-cvfv": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified four-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar32"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar4",
          "text": "simd_uchar4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-cvfv",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar32"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar32(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar32(_:)-cvfv"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-lv3": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified eight-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar32"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar8",
          "text": "simd_uchar8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-lv3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar32"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar32(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar32(_:)-lv3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-uuk8": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified three-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar32"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar3",
          "text": "simd_uchar3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-uuk8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar32"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar32(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar32(_:)-uuk8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-ycg1": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar32"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar2",
          "text": "simd_uchar2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-ycg1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar32"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar32(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar32(_:)-ycg1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar32"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar16",
          "text": "simd_uchar16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar16",
          "text": "simd_uchar16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar32"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar32(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar32(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32_undef(_:)-6klno": {
      "abstract": [
        {
          "text": "Returns a new vector with the first element set to a scalar value, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar32_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32_undef(_:)-6klno",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar32_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar32_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar32_undef(_:)-6klno"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32_undef(_:)-78b83": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified eight-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar32_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar8",
          "text": "simd_uchar8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32_undef(_:)-78b83",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar32_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar32_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar32_undef(_:)-78b83"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32_undef(_:)-86jc5": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar32_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar2",
          "text": "simd_uchar2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32_undef(_:)-86jc5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar32_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar32_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar32_undef(_:)-86jc5"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32_undef(_:)-89hb0": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified three-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar32_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar3",
          "text": "simd_uchar3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32_undef(_:)-89hb0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar32_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar32_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar32_undef(_:)-89hb0"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32_undef(_:)-8emxj": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified four-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar32_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar4",
          "text": "simd_uchar4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32_undef(_:)-8emxj",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar32_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar32_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar32_undef(_:)-8emxj"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32_undef(_:)-9vswr": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified sixteen-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar32_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar16",
          "text": "simd_uchar16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32_undef(_:)-9vswr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar32_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar32_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar32_undef(_:)-9vswr"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-xuo": {
      "abstract": [
        {
          "text": "Returns the maximum value of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_max"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-xuo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_max"
        }
      ],
      "role": "symbol",
      "title": "simd_max(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_max(_:_:)-xuo"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-4b2i2": {
      "abstract": [
        {
          "text": "Returns the minimum value of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_min"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-4b2i2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_min"
        }
      ],
      "role": "symbol",
      "title": "simd_min(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_min(_:_:)-4b2i2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-1updz": {
      "abstract": [
        {
          "text": "Returns the sum of all elements in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_add"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-1updz",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_add"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_add(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_add(_:)-1updz"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-9iwy0": {
      "abstract": [
        {
          "text": "Returns the maximum value in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_max"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-9iwy0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_max"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_max(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_max(_:)-9iwy0"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-2b45c": {
      "abstract": [
        {
          "text": "Returns the miniumum value in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_min"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-2b45c",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_min"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_min(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_min(_:)-2b45c"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar-5t6ew": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar-5t6ew",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar-5t6ew"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar-5tbi0": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar-5tbi0",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar-5tbi0"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar-5tgfs": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar-5tgfs",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar-5tgfs"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar-5tlbs": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar-5tlbs",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar-5tlbs"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar1": {
      "abstract": [
        {
          "text": "A vector of one 8-bit unsigned integer element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uchar1"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uchar1"
        }
      ],
      "role": "symbol",
      "title": "simd_uchar1",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar16": {
      "abstract": [
        {
          "text": "A vector of sixteen 8-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uchar16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uchar16"
        }
      ],
      "role": "symbol",
      "title": "simd_uchar16",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar16"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar2": {
      "abstract": [
        {
          "text": "A vector of two 8-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uchar2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uchar2"
        }
      ],
      "role": "symbol",
      "title": "simd_uchar2",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar3": {
      "abstract": [
        {
          "text": "A vector of three 8-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uchar3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uchar3"
        }
      ],
      "role": "symbol",
      "title": "simd_uchar3",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar32": {
      "abstract": [
        {
          "text": "A vector of thirty-two 8-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uchar32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uchar32"
        }
      ],
      "role": "symbol",
      "title": "simd_uchar32",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar32"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar4": {
      "abstract": [
        {
          "text": "A vector of four 8-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uchar4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uchar4"
        }
      ],
      "role": "symbol",
      "title": "simd_uchar4",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar64": {
      "abstract": [
        {
          "text": "A vector of sixty-four 8-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uchar64"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar64",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uchar64"
        }
      ],
      "role": "symbol",
      "title": "simd_uchar64",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar64"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar8": {
      "abstract": [
        {
          "text": "A vector of eight 8-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uchar8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uchar8"
        }
      ],
      "role": "symbol",
      "title": "simd_uchar8",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-32lax": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-32lax",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar_sat-32lax"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-32qhl": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-32qhl",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar_sat-32qhl"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-32vh5": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-32vh5",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar_sat-32vh5"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-330d5": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-330d5",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar_sat-330d5"
    },
    "doc://com.apple.accelerate/documentation/simd/vector32-68jyf": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector32-68jyf",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector32",
      "type": "topic",
      "url": "/documentation/simd/vector32-68jyf"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_uchar32": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vector_uchar32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_uchar32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vector_uchar32"
        }
      ],
      "role": "symbol",
      "title": "vector_uchar32",
      "type": "topic",
      "url": "/documentation/simd/vector_uchar32"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s5UInt8V": {
      "abstract": [
        {
          "text": "An 8-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5UInt8V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt8",
      "type": "topic",
      "url": "/documentation/Swift/UInt8"
    },
    "doc://com.externally.resolved.symbol/s:s6SIMD32V": {
      "abstract": [
        {
          "text": "A vector of 32 scalar values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SIMD32"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SIMDScalarP",
          "text": "SIMDScalar"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6SIMD32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "SIMD32",
      "type": "topic",
      "url": "/documentation/Swift/SIMD32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Vector-Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_uchar1",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar2",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar3",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar4",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar8",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar16",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar64"
      ],
      "title": "Vector Data Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Functions-to-Create-Thirty-Two-Element-Vectors-From-Other-Vectors",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-ycg1",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-uuk8",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-cvfv",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-lv3",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-94jec",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-3c53d",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-3tap7",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:_:)",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32_undef(_:)-86jc5",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32_undef(_:)-89hb0",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32_undef(_:)-8emxj",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32_undef(_:)-78b83",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32_undef(_:)-9vswr"
      ],
      "title": "Functions to Create Thirty Two-Element Vectors From Other Vectors"
    },
    {
      "anchor": "Functions-to-Create-Thirty-Two-Element-Vectors-From-Scalar-Values",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-8z2lu",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32_undef(_:)-6klno"
      ],
      "title": "Functions to Create Thirty Two-Element Vectors From Scalar Values"
    },
    {
      "anchor": "Common-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-3bfcx",
        "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-qmif"
      ],
      "title": "Common Functions"
    },
    {
      "anchor": "Reduce-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-2b45c",
        "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-9iwy0",
        "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-1updz"
      ],
      "title": "Reduce Functions"
    },
    {
      "anchor": "Extrema-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-4b2i2",
        "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-xuo"
      ],
      "title": "Extrema Functions"
    },
    {
      "anchor": "Logic-and-Bitwise-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-3apcl",
        "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1khgz",
        "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-49vzj"
      ],
      "title": "Logic and Bitwise Functions"
    },
    {
      "anchor": "Alternative-Type-Alias",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/vector_uchar32"
      ],
      "title": "Alternative Type Alias"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "simd_uchar32"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/simd"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Functions-to-Create-Thirty-Two-Element-Vectors-From-Other-Vectors",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-ycg1",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-uuk8",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-cvfv",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-lv3",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-94jec",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-3c53d",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-3tap7",
                "doc://com.apple.accelerate/documentation/simd/vector32-68jyf",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:_:)",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32_undef(_:)-86jc5",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32_undef(_:)-89hb0",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32_undef(_:)-8emxj",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32_undef(_:)-78b83",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32_undef(_:)-9vswr"
              ],
              "title": "Functions to Create Thirty Two-Element Vectors From Other Vectors"
            },
            {
              "anchor": "Functions-to-Create-Thirty-Two-Element-Vectors-From-Scalar-Values",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-8z2lu",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32_undef(_:)-6klno"
              ],
              "title": "Functions to Create Thirty Two-Element Vectors From Scalar Values"
            },
            {
              "anchor": "Functions-to-Create-Thirty-Two-Element-Vectors-From-Vectors-of-Other-Types",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_uchar-5tgfs",
                "doc://com.apple.accelerate/documentation/simd/simd_uchar-5t6ew",
                "doc://com.apple.accelerate/documentation/simd/simd_uchar-5tlbs",
                "doc://com.apple.accelerate/documentation/simd/simd_uchar-5tbi0"
              ],
              "title": "Functions to Create Thirty Two-Element Vectors From Vectors of Other Types"
            },
            {
              "anchor": "Functions-to-Perform-Saturating-Conversion-From-Vectors-of-Other-Types",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-330d5",
                "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-32qhl",
                "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-32vh5",
                "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-32lax"
              ],
              "title": "Functions to Perform Saturating Conversion From Vectors of Other Types"
            },
            {
              "anchor": "Common-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-3bfcx",
                "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-qmif"
              ],
              "title": "Common Functions"
            },
            {
              "anchor": "Reduce-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-2b45c",
                "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-9iwy0",
                "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-1updz"
              ],
              "title": "Reduce Functions"
            },
            {
              "anchor": "Extrema-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-4b2i2",
                "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-xuo"
              ],
              "title": "Extrema Functions"
            },
            {
              "anchor": "Logic-and-Bitwise-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-3apcl",
                "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1khgz",
                "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-49vzj"
              ],
              "title": "Logic and Bitwise Functions"
            },
            {
              "anchor": "Alternative-Type-Alias",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/vector_uchar32"
              ],
              "title": "Alternative Type Alias"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Vector-Data-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_uchar1",
                "doc://com.apple.accelerate/documentation/simd/simd_uchar2",
                "doc://com.apple.accelerate/documentation/simd/simd_uchar3",
                "doc://com.apple.accelerate/documentation/simd/simd_uchar4",
                "doc://com.apple.accelerate/documentation/simd/simd_uchar8",
                "doc://com.apple.accelerate/documentation/simd/simd_uchar16",
                "doc://com.apple.accelerate/documentation/simd/simd_uchar64"
              ],
              "title": "Vector Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:]32c",
                    "text": "unsigned char __attribute__((ext_vector_type(32)))"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "simd_uchar32"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_all(_:)-1khgz/title",
          "value": "simd_all"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_all(_:)-1khgz/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_all"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar16/title",
          "value": "simd_uchar16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar16/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_max(_:_:)-xuo/title",
          "value": "simd_max"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_max(_:_:)-xuo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_max"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32_undef(_:)-9vswr/title",
          "value": "simd_make_uchar32_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32_undef(_:)-9vswr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar32_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32_undef(_:)-8emxj/title",
          "value": "simd_make_uchar32_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32_undef(_:)-8emxj/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar32_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32(_:)-uuk8/title",
          "value": "simd_make_uchar32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32(_:)-uuk8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar32/title",
          "value": "simd_uchar32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar32/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32_undef(_:)-6klno/title",
          "value": "simd_make_uchar32_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32_undef(_:)-6klno/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar32_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar4/title",
          "value": "simd_uchar4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_any(_:)-3apcl/title",
          "value": "simd_any"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_any(_:)-3apcl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_any"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_bitselect(_:_:_:)-49vzj/title",
          "value": "simd_bitselect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_bitselect(_:_:_:)-49vzj/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_bitselect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar3/title",
          "value": "simd_uchar3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_min(_:)-2b45c/title",
          "value": "simd_reduce_min"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_min(_:)-2b45c/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_min"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar64/title",
          "value": "simd_uchar64"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar64/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar64/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar8/title",
          "value": "simd_uchar8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar1/title",
          "value": "simd_uchar1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar1/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1vector_uchar32/title",
          "value": "vector_uchar32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1vector_uchar32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vector_uchar32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1vector_uchar32/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vector_uchar32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_equal(_:_:)-qmif/title",
          "value": "simd_equal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_equal(_:_:)-qmif/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_equal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32(_:_:)/title",
          "value": "simd_make_uchar32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32_undef(_:)-86jc5/title",
          "value": "simd_make_uchar32_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32_undef(_:)-86jc5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar32_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32(_:)-lv3/title",
          "value": "simd_make_uchar32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32(_:)-lv3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32(_:)-3c53d/title",
          "value": "simd_make_uchar32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32(_:)-3c53d/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32_undef(_:)-89hb0/title",
          "value": "simd_make_uchar32_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32_undef(_:)-89hb0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar32_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32(_:)-3tap7/title",
          "value": "simd_make_uchar32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32(_:)-3tap7/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_clamp(_:_:_:)-3bfcx/title",
          "value": "simd_clamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_clamp(_:_:_:)-3bfcx/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_clamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_add(_:)-1updz/title",
          "value": "simd_reduce_add"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_add(_:)-1updz/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_add"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32(_:)-ycg1/title",
          "value": "simd_make_uchar32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32(_:)-ycg1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_min(_:_:)-4b2i2/title",
          "value": "simd_min"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_min(_:_:)-4b2i2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_min"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32_undef(_:)-78b83/title",
          "value": "simd_make_uchar32_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32_undef(_:)-78b83/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar32_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_max(_:)-9iwy0/title",
          "value": "simd_reduce_max"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_max(_:)-9iwy0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_max"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32(_:)-94jec/title",
          "value": "simd_make_uchar32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32(_:)-94jec/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32(_:)-cvfv/title",
          "value": "simd_make_uchar32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32(_:)-cvfv/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32(_:)-8z2lu/title",
          "value": "simd_make_uchar32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32(_:)-8z2lu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar2/title",
          "value": "simd_uchar2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar2"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_uchar32"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/simd/simd_uchar32"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
