{
  "abstract": [
    {
      "text": "A vector of eight 64-bit signed integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_long8"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@simd_long8",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simd_long8"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_long8"
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "simd_long8"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_long8"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5SIMD8V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5SIMD8V",
              "text": "SIMD8"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long1",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_long1",
              "text": "simd_long1"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_abs(_:)-7osxw": {
      "abstract": [
        {
          "text": "Returns the absolute value of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_abs"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long8",
          "text": "simd_long8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long8",
          "text": "simd_long8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_abs(_:)-7osxw",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_abs"
        }
      ],
      "role": "symbol",
      "title": "simd_abs(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_abs(_:)-7osxw"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1yys7": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_all"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long8",
          "text": "simd_long8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_bool",
          "text": "simd_bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1yys7",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_all"
        }
      ],
      "role": "symbol",
      "title": "simd_all(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_all(_:)-1yys7"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-6pjhd": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_any"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long8",
          "text": "simd_long8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_bool",
          "text": "simd_bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-6pjhd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_any"
        }
      ],
      "role": "symbol",
      "title": "simd_any(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_any(_:)-6pjhd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-5k6g": {
      "abstract": [
        {
          "text": "Returns a vector that contains elements from either the first or second parameter, based on the corresponding element in the third parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_bitselect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long8",
          "text": "simd_long8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long8",
          "text": "simd_long8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long8",
          "text": "simd_long8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long8",
          "text": "simd_long8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-5k6g",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_bitselect"
        }
      ],
      "role": "symbol",
      "title": "simd_bitselect(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_bitselect(_:_:_:)-5k6g"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-7h5og": {
      "abstract": [
        {
          "text": "Returns the absolute value of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_clamp"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long8",
          "text": "simd_long8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long8",
          "text": "simd_long8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long8",
          "text": "simd_long8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long8",
          "text": "simd_long8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-7h5og",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_clamp"
        }
      ],
      "role": "symbol",
      "title": "simd_clamp(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_clamp(_:_:_:)-7h5og"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-1fygf": {
      "abstract": [
        {
          "text": "Returns true if every element in a vector is exactly equal to the corresponding element in a second vector, and otherwise returns false.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_equal"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long8",
          "text": "simd_long8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long8",
          "text": "simd_long8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_bool",
          "text": "simd_bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-1fygf",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_equal"
        }
      ],
      "role": "symbol",
      "title": "simd_equal(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_equal(_:_:)-1fygf"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long-93gss": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long-93gss",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long",
      "type": "topic",
      "url": "/documentation/simd/simd_long-93gss"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long-93h2w": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long-93h2w",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long",
      "type": "topic",
      "url": "/documentation/simd/simd_long-93h2w"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long-93hmw": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long-93hmw",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long",
      "type": "topic",
      "url": "/documentation/simd/simd_long-93hmw"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long-93iok": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long-93iok",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long",
      "type": "topic",
      "url": "/documentation/simd/simd_long-93iok"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long-93jiw": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long-93jiw",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long",
      "type": "topic",
      "url": "/documentation/simd/simd_long-93jiw"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long-93lpo": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long-93lpo",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long",
      "type": "topic",
      "url": "/documentation/simd/simd_long-93lpo"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long-93qrw": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long-93qrw",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long",
      "type": "topic",
      "url": "/documentation/simd/simd_long-93qrw"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long-93sno": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long-93sno",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long",
      "type": "topic",
      "url": "/documentation/simd/simd_long-93sno"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long-93ti0": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long-93ti0",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long",
      "type": "topic",
      "url": "/documentation/simd/simd_long-93ti0"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long-93vu4": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long-93vu4",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long",
      "type": "topic",
      "url": "/documentation/simd/simd_long-93vu4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long1": {
      "abstract": [
        {
          "text": "A vector of one 64-bit signed integer element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_long1"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_long1"
        }
      ],
      "role": "symbol",
      "title": "simd_long1",
      "type": "topic",
      "url": "/documentation/simd/simd_long1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long2": {
      "abstract": [
        {
          "text": "A vector of two 64-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_long2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_long2"
        }
      ],
      "role": "symbol",
      "title": "simd_long2",
      "type": "topic",
      "url": "/documentation/simd/simd_long2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long3": {
      "abstract": [
        {
          "text": "A vector of three 64-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_long3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_long3"
        }
      ],
      "role": "symbol",
      "title": "simd_long3",
      "type": "topic",
      "url": "/documentation/simd/simd_long3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long4": {
      "abstract": [
        {
          "text": "A vector of four 64-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_long4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_long4"
        }
      ],
      "role": "symbol",
      "title": "simd_long4",
      "type": "topic",
      "url": "/documentation/simd/simd_long4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long8": {
      "abstract": [
        {
          "text": "A vector of eight 64-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_long8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_long8"
        }
      ],
      "role": "symbol",
      "title": "simd_long8",
      "type": "topic",
      "url": "/documentation/simd/simd_long8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long_rte-90anl": {
      "abstract": [
        {
          "text": "Returns a new eight-element vector by rounding halves to the nearest even value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long_rte"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long_rte-90anl",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long_rte",
      "type": "topic",
      "url": "/documentation/simd/simd_long_rte-90anl"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long_sat-6rux6": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long_sat-6rux6",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_long_sat-6rux6"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long_sat-6rvv6": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long_sat-6rvv6",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_long_sat-6rvv6"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long_sat-6rxje": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long_sat-6rxje",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_long_sat-6rxje"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long_sat-6ry46": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long_sat-6ry46",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_long_sat-6ry46"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long_sat-6rz5a": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long_sat-6rz5a",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_long_sat-6rz5a"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long_sat-6s426": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long_sat-6s426",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_long_sat-6s426"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long_sat-6s53e": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long_sat-6s53e",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_long_sat-6s53e"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long_sat-6s5qq": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long_sat-6s5qq",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_long_sat-6s5qq"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long_sat-6s8z2": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long_sat-6s8z2",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_long_sat-6s8z2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long_sat-6sdu6": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long_sat-6sdu6",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_long_sat-6sdu6"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_long8(_:)-2kqft": {
      "abstract": [
        {
          "text": "Returns a new vector with the first element set to a scalar value, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_long8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long1",
          "text": "simd_long1"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long8",
          "text": "simd_long8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_long8(_:)-2kqft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_long8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_long8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_long8(_:)-2kqft"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_long8(_:)-6saal": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_long8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long8",
          "text": "simd_long8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long8",
          "text": "simd_long8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_long8(_:)-6saal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_long8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_long8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_long8(_:)-6saal"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_long8(_:)-7netg": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified three-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_long8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long3",
          "text": "simd_long3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long8",
          "text": "simd_long8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_long8(_:)-7netg",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_long8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_long8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_long8(_:)-7netg"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_long8(_:)-7pzt7": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_long8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long2",
          "text": "simd_long2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long8",
          "text": "simd_long8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_long8(_:)-7pzt7",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_long8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_long8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_long8(_:)-7pzt7"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_long8(_:)-7wvxt": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified four-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_long8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long4",
          "text": "simd_long4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long8",
          "text": "simd_long8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_long8(_:)-7wvxt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_long8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_long8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_long8(_:)-7wvxt"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_long8(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_long8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long4",
          "text": "simd_long4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long4",
          "text": "simd_long4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long8",
          "text": "simd_long8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_long8(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_long8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_long8(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_long8(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_long8_undef(_:)-59t0j": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified four-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_long8_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long4",
          "text": "simd_long4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long8",
          "text": "simd_long8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_long8_undef(_:)-59t0j",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_long8_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_long8_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_long8_undef(_:)-59t0j"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_long8_undef(_:)-5uowh": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_long8_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long2",
          "text": "simd_long2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long8",
          "text": "simd_long8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_long8_undef(_:)-5uowh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_long8_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_long8_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_long8_undef(_:)-5uowh"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_long8_undef(_:)-5y3qm": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified three-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_long8_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long3",
          "text": "simd_long3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long8",
          "text": "simd_long8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_long8_undef(_:)-5y3qm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_long8_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_long8_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_long8_undef(_:)-5y3qm"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_long8_undef(_:)-9h1v1": {
      "abstract": [
        {
          "text": "Returns a new vector with the first element set to a scalar value, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_long8_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long1",
          "text": "simd_long1"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long8",
          "text": "simd_long8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_long8_undef(_:)-9h1v1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_long8_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_long8_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_long8_undef(_:)-9h1v1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-4cbvp": {
      "abstract": [
        {
          "text": "Returns the maximum value of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_max"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long8",
          "text": "simd_long8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long8",
          "text": "simd_long8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long8",
          "text": "simd_long8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-4cbvp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_max"
        }
      ],
      "role": "symbol",
      "title": "simd_max(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_max(_:_:)-4cbvp"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-1z34d": {
      "abstract": [
        {
          "text": "Returns the minimum value of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_min"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long8",
          "text": "simd_long8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long8",
          "text": "simd_long8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long8",
          "text": "simd_long8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-1z34d",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_min"
        }
      ],
      "role": "symbol",
      "title": "simd_min(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_min(_:_:)-1z34d"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-3b63s": {
      "abstract": [
        {
          "text": "Returns the sum of all elements in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_add"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long8",
          "text": "simd_long8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long1",
          "text": "simd_long1"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-3b63s",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_add"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_add(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_add(_:)-3b63s"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-55m7m": {
      "abstract": [
        {
          "text": "Returns the maximum value in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_max"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long8",
          "text": "simd_long8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long1",
          "text": "simd_long1"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-55m7m",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_max"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_max(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_max(_:)-55m7m"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-3okve": {
      "abstract": [
        {
          "text": "Returns the miniumum value in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_min"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long8",
          "text": "simd_long8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long1",
          "text": "simd_long1"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-3okve",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_min"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_min(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_min(_:)-3okve"
    },
    "doc://com.apple.accelerate/documentation/simd/vector8-6qxy0": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector8-6qxy0",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector8",
      "type": "topic",
      "url": "/documentation/simd/vector8-6qxy0"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_long8": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vector_long8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_long8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vector_long8"
        }
      ],
      "role": "symbol",
      "title": "vector_long8",
      "type": "topic",
      "url": "/documentation/simd/vector_long8"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s5SIMD8V": {
      "abstract": [
        {
          "text": "A vector of eight scalar values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SIMD8"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SIMDScalarP",
          "text": "SIMDScalar"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5SIMD8V",
      "kind": "symbol",
      "role": "symbol",
      "title": "SIMD8",
      "type": "topic",
      "url": "/documentation/Swift/SIMD8"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Vector-Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_long1",
        "doc://com.apple.accelerate/documentation/simd/simd_long2",
        "doc://com.apple.accelerate/documentation/simd/simd_long3",
        "doc://com.apple.accelerate/documentation/simd/simd_long4"
      ],
      "title": "Vector Data Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Functions-to-Create-Eight-Element-Vectors-From-Other-Vectors",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_long8(_:)-7pzt7",
        "doc://com.apple.accelerate/documentation/simd/simd_make_long8(_:)-7netg",
        "doc://com.apple.accelerate/documentation/simd/simd_make_long8(_:)-7wvxt",
        "doc://com.apple.accelerate/documentation/simd/simd_make_long8(_:)-6saal",
        "doc://com.apple.accelerate/documentation/simd/simd_make_long8(_:_:)",
        "doc://com.apple.accelerate/documentation/simd/simd_make_long8_undef(_:)-5uowh",
        "doc://com.apple.accelerate/documentation/simd/simd_make_long8_undef(_:)-5y3qm",
        "doc://com.apple.accelerate/documentation/simd/simd_make_long8_undef(_:)-59t0j"
      ],
      "title": "Functions to Create Eight-Element Vectors From Other Vectors"
    },
    {
      "anchor": "Functions-to-Create-Eight-Element-Vectors-From-Scalar-Values",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_long8(_:)-2kqft",
        "doc://com.apple.accelerate/documentation/simd/simd_make_long8_undef(_:)-9h1v1"
      ],
      "title": "Functions to Create Eight-Element Vectors From Scalar Values"
    },
    {
      "anchor": "Common-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_abs(_:)-7osxw",
        "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-7h5og",
        "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-1fygf"
      ],
      "title": "Common Functions"
    },
    {
      "anchor": "Reduce-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-3okve",
        "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-55m7m",
        "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-3b63s"
      ],
      "title": "Reduce Functions"
    },
    {
      "anchor": "Extrema-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-1z34d",
        "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-4cbvp"
      ],
      "title": "Extrema Functions"
    },
    {
      "anchor": "Logic-and-Bitwise-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-6pjhd",
        "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1yys7",
        "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-5k6g"
      ],
      "title": "Logic and Bitwise Functions"
    },
    {
      "anchor": "Alternative-Type-Alias",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/vector_long8"
      ],
      "title": "Alternative Type Alias"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "simd_long8"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_long8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_long8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/simd"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Functions-to-Create-Eight-Element-Vectors-From-Other-Vectors",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_long8(_:)-7pzt7",
                "doc://com.apple.accelerate/documentation/simd/simd_make_long8(_:)-7netg",
                "doc://com.apple.accelerate/documentation/simd/simd_make_long8(_:)-7wvxt",
                "doc://com.apple.accelerate/documentation/simd/simd_make_long8(_:)-6saal",
                "doc://com.apple.accelerate/documentation/simd/simd_make_long8(_:_:)",
                "doc://com.apple.accelerate/documentation/simd/vector8-6qxy0",
                "doc://com.apple.accelerate/documentation/simd/simd_make_long8_undef(_:)-5uowh",
                "doc://com.apple.accelerate/documentation/simd/simd_make_long8_undef(_:)-5y3qm",
                "doc://com.apple.accelerate/documentation/simd/simd_make_long8_undef(_:)-59t0j"
              ],
              "title": "Functions to Create Eight-Element Vectors From Other Vectors"
            },
            {
              "anchor": "Conversion-to-Signed-64-Bit-Round-Half-to-Even-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_long_rte-90anl"
              ],
              "title": "Conversion to Signed 64-Bit (Round Half to Even) Functions"
            },
            {
              "anchor": "Functions-to-Create-Eight-Element-Vectors-From-Scalar-Values",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_long8(_:)-2kqft",
                "doc://com.apple.accelerate/documentation/simd/simd_make_long8_undef(_:)-9h1v1"
              ],
              "title": "Functions to Create Eight-Element Vectors From Scalar Values"
            },
            {
              "anchor": "Functions-to-Create-Eight-Element-Vectors-From-Vectors-of-Other-Types",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_long-93qrw",
                "doc://com.apple.accelerate/documentation/simd/simd_long-93gss",
                "doc://com.apple.accelerate/documentation/simd/simd_long-93vu4",
                "doc://com.apple.accelerate/documentation/simd/simd_long-93lpo",
                "doc://com.apple.accelerate/documentation/simd/simd_long-93sno",
                "doc://com.apple.accelerate/documentation/simd/simd_long-93iok",
                "doc://com.apple.accelerate/documentation/simd/simd_long-93ti0",
                "doc://com.apple.accelerate/documentation/simd/simd_long-93jiw",
                "doc://com.apple.accelerate/documentation/simd/simd_long-93hmw",
                "doc://com.apple.accelerate/documentation/simd/simd_long-93h2w"
              ],
              "title": "Functions to Create Eight-Element Vectors From Vectors of Other Types"
            },
            {
              "anchor": "Functions-to-Perform-Saturating-Conversion-From-Vectors-of-Other-Types",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_long_sat-6s8z2",
                "doc://com.apple.accelerate/documentation/simd/simd_long_sat-6rz5a",
                "doc://com.apple.accelerate/documentation/simd/simd_long_sat-6sdu6",
                "doc://com.apple.accelerate/documentation/simd/simd_long_sat-6s426",
                "doc://com.apple.accelerate/documentation/simd/simd_long_sat-6s5qq",
                "doc://com.apple.accelerate/documentation/simd/simd_long_sat-6rvv6",
                "doc://com.apple.accelerate/documentation/simd/simd_long_sat-6s53e",
                "doc://com.apple.accelerate/documentation/simd/simd_long_sat-6rux6",
                "doc://com.apple.accelerate/documentation/simd/simd_long_sat-6ry46",
                "doc://com.apple.accelerate/documentation/simd/simd_long_sat-6rxje"
              ],
              "title": "Functions to Perform Saturating Conversion From Vectors of Other Types"
            },
            {
              "anchor": "Common-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_abs(_:)-7osxw",
                "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-7h5og",
                "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-1fygf"
              ],
              "title": "Common Functions"
            },
            {
              "anchor": "Reduce-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-3okve",
                "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-55m7m",
                "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-3b63s"
              ],
              "title": "Reduce Functions"
            },
            {
              "anchor": "Extrema-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-1z34d",
                "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-4cbvp"
              ],
              "title": "Extrema Functions"
            },
            {
              "anchor": "Logic-and-Bitwise-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-6pjhd",
                "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1yys7",
                "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-5k6g"
              ],
              "title": "Logic and Bitwise Functions"
            },
            {
              "anchor": "Alternative-Type-Alias",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/vector_long8"
              ],
              "title": "Alternative Type Alias"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Vector-Data-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_long1",
                "doc://com.apple.accelerate/documentation/simd/simd_long2",
                "doc://com.apple.accelerate/documentation/simd/simd_long3",
                "doc://com.apple.accelerate/documentation/simd/simd_long4"
              ],
              "title": "Vector Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:]8L",
                    "text": "long __attribute__((ext_vector_type(8)))"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "simd_long8"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_abs(_:)-7osxw/title",
          "value": "simd_abs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_abs(_:)-7osxw/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_abs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_max(_:_:)-4cbvp/title",
          "value": "simd_max"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_max(_:_:)-4cbvp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_max"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_add(_:)-3b63s/title",
          "value": "simd_reduce_add"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_add(_:)-3b63s/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_add"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_equal(_:_:)-1fygf/title",
          "value": "simd_equal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_equal(_:_:)-1fygf/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_equal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_long8(_:)-7pzt7/title",
          "value": "simd_make_long8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_long8(_:)-7pzt7/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_long8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_long8(_:)-7wvxt/title",
          "value": "simd_make_long8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_long8(_:)-7wvxt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_long8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long3/title",
          "value": "simd_long3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_long3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_long3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_bitselect(_:_:_:)-5k6g/title",
          "value": "simd_bitselect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_bitselect(_:_:_:)-5k6g/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_bitselect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_long8_undef(_:)-5uowh/title",
          "value": "simd_make_long8_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_long8_undef(_:)-5uowh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_long8_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_long8_undef(_:)-5y3qm/title",
          "value": "simd_make_long8_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_long8_undef(_:)-5y3qm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_long8_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_long8_undef(_:)-59t0j/title",
          "value": "simd_make_long8_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_long8_undef(_:)-59t0j/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_long8_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_max(_:)-55m7m/title",
          "value": "simd_reduce_max"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_max(_:)-55m7m/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_max"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_long8(_:_:)/title",
          "value": "simd_make_long8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_long8(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_long8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1vector_long8/title",
          "value": "vector_long8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1vector_long8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vector_long8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1vector_long8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vector_long8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_long8(_:)-6saal/title",
          "value": "simd_make_long8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_long8(_:)-6saal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_long8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_long8(_:)-2kqft/title",
          "value": "simd_make_long8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_long8(_:)-2kqft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_long8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_long8(_:)-7netg/title",
          "value": "simd_make_long8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_long8(_:)-7netg/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_long8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long8/title",
          "value": "simd_long8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_long8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_long8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_clamp(_:_:_:)-7h5og/title",
          "value": "simd_clamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_clamp(_:_:_:)-7h5og/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_clamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_min(_:_:)-1z34d/title",
          "value": "simd_min"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_min(_:_:)-1z34d/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_min"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_min(_:)-3okve/title",
          "value": "simd_reduce_min"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_min(_:)-3okve/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_min"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_all(_:)-1yys7/title",
          "value": "simd_all"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_all(_:)-1yys7/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_all"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long1/title",
          "value": "simd_long1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_long1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long1/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_long1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_any(_:)-6pjhd/title",
          "value": "simd_any"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_any(_:)-6pjhd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_any"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long2/title",
          "value": "simd_long2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_long2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_long2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_long8_undef(_:)-9h1v1/title",
          "value": "simd_make_long8_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_long8_undef(_:)-9h1v1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_long8_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long4/title",
          "value": "simd_long4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_long4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_long4"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_long8"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/simd/simd_long8"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
