{
  "abstract": [
    {
      "text": "Returns a new vector from the specified vector of 32-bit, signed-integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_double-631ha"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_double#]8I#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_double"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_double"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_double"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double8",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_double8",
              "text": "simd_double8"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_double"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int8",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_int8",
              "text": "simd_int8"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double-62zne": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double-62zne",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_double",
      "type": "topic",
      "url": "/documentation/simd/simd_double-62zne"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double-631ha": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double-631ha",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_double",
      "type": "topic",
      "url": "/documentation/simd/simd_double-631ha"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double-63332": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double-63332",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_double",
      "type": "topic",
      "url": "/documentation/simd/simd_double-63332"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double-634oq": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double-634oq",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_double",
      "type": "topic",
      "url": "/documentation/simd/simd_double-634oq"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double-639kq": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double-639kq",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_double",
      "type": "topic",
      "url": "/documentation/simd/simd_double-639kq"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double-63agu": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double-63agu",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_double",
      "type": "topic",
      "url": "/documentation/simd/simd_double-63agu"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double-63b6q": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double-63b6q",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_double",
      "type": "topic",
      "url": "/documentation/simd/simd_double-63b6q"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double-63bi6": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double-63bi6",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_double",
      "type": "topic",
      "url": "/documentation/simd/simd_double-63bi6"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double-63d26": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double-63d26",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_double",
      "type": "topic",
      "url": "/documentation/simd/simd_double-63d26"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double-63eii": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double-63eii",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_double",
      "type": "topic",
      "url": "/documentation/simd/simd_double-63eii"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double8": {
      "abstract": [
        {
          "text": "A vector of eight 64-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_double8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_double8"
        }
      ],
      "role": "symbol",
      "title": "simd_double8",
      "type": "topic",
      "url": "/documentation/simd/simd_double8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int8": {
      "abstract": [
        {
          "text": "A vector of eight 32-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_int8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_int8"
        }
      ],
      "role": "symbol",
      "title": "simd_int8",
      "type": "topic",
      "url": "/documentation/simd/simd_int8"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Create-Eight-Element-Vectors-From-Vectors-of-Other-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_double-62zne",
        "doc://com.apple.accelerate/documentation/simd/simd_double-639kq",
        "doc://com.apple.accelerate/documentation/simd/simd_double-634oq",
        "doc://com.apple.accelerate/documentation/simd/simd_double-63eii",
        "doc://com.apple.accelerate/documentation/simd/simd_double-63bi6",
        "doc://com.apple.accelerate/documentation/simd/simd_double-63332",
        "doc://com.apple.accelerate/documentation/simd/simd_double-63d26",
        "doc://com.apple.accelerate/documentation/simd/simd_double-63b6q",
        "doc://com.apple.accelerate/documentation/simd/simd_double-63agu"
      ],
      "title": "Functions to Create Eight-Element Vectors From Vectors of Other Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int8/title",
          "value": "simd_int8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_int8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_int8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double8/title",
          "value": "simd_double8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double8"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_double-631ha"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
