{
  "abstract": [
    {
      "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3mfdp"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_short_sat#]2L#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_short_sat"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_short_sat"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_short_sat"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_short2",
              "text": "simd_short2"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_short_sat"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_long2",
              "text": "simd_long2"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long2": {
      "abstract": [
        {
          "text": "A vector of two 64-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_long2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_long2"
        }
      ],
      "role": "symbol",
      "title": "simd_long2",
      "type": "topic",
      "url": "/documentation/simd/simd_long2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short2": {
      "abstract": [
        {
          "text": "A vector of two 16-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_short2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_short2"
        }
      ],
      "role": "symbol",
      "title": "simd_short2",
      "type": "topic",
      "url": "/documentation/simd/simd_short2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3m83r": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3m83r",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_short_sat-3m83r"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3md2f": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3md2f",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_short_sat-3md2f"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3mfdp": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3mfdp",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_short_sat-3mfdp"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3mg4b": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3mg4b",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_short_sat-3mg4b"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3mi6f": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3mi6f",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_short_sat-3mi6f"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3mm1h": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3mm1h",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_short_sat-3mm1h"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3mmpp": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3mmpp",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_short_sat-3mmpp"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3mn6v": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3mn6v",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_short_sat-3mn6v"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3mpct": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3mpct",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_short_sat-3mpct"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3mqaj": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3mqaj",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_short_sat-3mqaj"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Perform-Saturating-Conversion-From-Vectors-of-Other-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3md2f",
        "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3mn6v",
        "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3m83r",
        "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3mi6f",
        "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3mg4b",
        "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3mqaj",
        "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3mpct",
        "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3mm1h",
        "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3mmpp"
      ],
      "title": "Functions to Perform Saturating Conversion From Vectors of Other Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long2/title",
          "value": "simd_long2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_long2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_long2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short2/title",
          "value": "simd_short2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short2"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_short_sat-3mfdp"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
