{
  "abstract": [
    {
      "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_char-7pnki"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_char#]4l#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_char"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_char"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_char"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char4",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_char4",
              "text": "simd_char4"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_char"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong4",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_ulong4",
              "text": "simd_ulong4"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char-7pnki": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char-7pnki",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char",
      "type": "topic",
      "url": "/documentation/simd/simd_char-7pnki"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char-7pp6i": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char-7pp6i",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char",
      "type": "topic",
      "url": "/documentation/simd/simd_char-7pp6i"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char-7pp9i": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char-7pp9i",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char",
      "type": "topic",
      "url": "/documentation/simd/simd_char-7pp9i"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char-7pptu": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char-7pptu",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char",
      "type": "topic",
      "url": "/documentation/simd/simd_char-7pptu"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char-7pqwm": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char-7pqwm",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char",
      "type": "topic",
      "url": "/documentation/simd/simd_char-7pqwm"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char-7pvsm": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char-7pvsm",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char",
      "type": "topic",
      "url": "/documentation/simd/simd_char-7pvsm"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char-7pxci": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char-7pxci",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char",
      "type": "topic",
      "url": "/documentation/simd/simd_char-7pxci"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char-7pz0a": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char-7pz0a",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char",
      "type": "topic",
      "url": "/documentation/simd/simd_char-7pz0a"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char-7q0xi": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char-7q0xi",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char",
      "type": "topic",
      "url": "/documentation/simd/simd_char-7q0xi"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char-7q5x2": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char-7q5x2",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char",
      "type": "topic",
      "url": "/documentation/simd/simd_char-7q5x2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char4": {
      "abstract": [
        {
          "text": "A vector of four 8-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_char4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_char4"
        }
      ],
      "role": "symbol",
      "title": "simd_char4",
      "type": "topic",
      "url": "/documentation/simd/simd_char4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong4": {
      "abstract": [
        {
          "text": "A vector of four 64-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ulong4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ulong4"
        }
      ],
      "role": "symbol",
      "title": "simd_ulong4",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong4"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Create-Four-Element-Vectors-From-Vectors-of-Other-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_char-7q0xi",
        "doc://com.apple.accelerate/documentation/simd/simd_char-7pqwm",
        "doc://com.apple.accelerate/documentation/simd/simd_char-7q5x2",
        "doc://com.apple.accelerate/documentation/simd/simd_char-7pvsm",
        "doc://com.apple.accelerate/documentation/simd/simd_char-7pz0a",
        "doc://com.apple.accelerate/documentation/simd/simd_char-7pp6i",
        "doc://com.apple.accelerate/documentation/simd/simd_char-7pxci",
        "doc://com.apple.accelerate/documentation/simd/simd_char-7pp9i",
        "doc://com.apple.accelerate/documentation/simd/simd_char-7pptu"
      ],
      "title": "Functions to Create Four-Element Vectors From Vectors of Other Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char4/title",
          "value": "simd_char4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong4/title",
          "value": "simd_ulong4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong4"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_char-7pnki"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
