{
  "abstract": [
    {
      "text": "Returns a new vector from a scalar value and a vector.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_make_long3(_:_:)-3zz23"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_make_long3#L#]2L#",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simd_make_long3"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_long1",
        "text": "simd_long1"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_long2",
        "text": "simd_long2"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_long3",
        "text": "simd_long3"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_make_long3"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_make_long3(_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_make_long3"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "x"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long1",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_long1",
              "text": "simd_long1"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "yz"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_long2",
              "text": "simd_long2"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long3",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_long3",
              "text": "simd_long3"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long1": {
      "abstract": [
        {
          "text": "A vector of one 64-bit signed integer element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_long1"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_long1"
        }
      ],
      "role": "symbol",
      "title": "simd_long1",
      "type": "topic",
      "url": "/documentation/simd/simd_long1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long2": {
      "abstract": [
        {
          "text": "A vector of two 64-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_long2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_long2"
        }
      ],
      "role": "symbol",
      "title": "simd_long2",
      "type": "topic",
      "url": "/documentation/simd/simd_long2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long3": {
      "abstract": [
        {
          "text": "A vector of three 64-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_long3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_long3"
        }
      ],
      "role": "symbol",
      "title": "simd_long3",
      "type": "topic",
      "url": "/documentation/simd/simd_long3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_long3(_:_:)-36pz0": {
      "abstract": [
        {
          "text": "Returns a new vector from a vector and a scalar value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_long3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long2",
          "text": "simd_long2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long1",
          "text": "simd_long1"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long3",
          "text": "simd_long3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_long3(_:_:)-36pz0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_long3"
        }
      ],
      "role": "symbol",
      "title": "simd_make_long3(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_long3(_:_:)-36pz0"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_long3(_:_:)-3zz23": {
      "abstract": [
        {
          "text": "Returns a new vector from a scalar value and a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_long3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long1",
          "text": "simd_long1"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long2",
          "text": "simd_long2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long3",
          "text": "simd_long3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_long3(_:_:)-3zz23",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_long3"
        }
      ],
      "role": "symbol",
      "title": "simd_make_long3(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_long3(_:_:)-3zz23"
    },
    "doc://com.apple.accelerate/documentation/simd/vector3-6gwfj": {
      "abstract": [
        {
          "text": "Returns a new vector from a vector and a scalar value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector3-6gwfj",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector3",
      "type": "topic",
      "url": "/documentation/simd/vector3-6gwfj"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Create-Three-Element-Vectors-From-Combinations-of-Vectors-and-Scalar-Values",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_long3(_:_:)-36pz0"
      ],
      "title": "Functions to Create Three-Element Vectors From Combinations of Vectors and Scalar Values"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "simd_make_long3"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_long3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/simd"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Functions-to-Create-Three-Element-Vectors-From-Combinations-of-Vectors-and-Scalar-Values",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_long3(_:_:)-36pz0",
                "doc://com.apple.accelerate/documentation/simd/vector3-6gwfj"
              ],
              "title": "Functions to Create Three-Element Vectors From Combinations of Vectors and Scalar Values"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "static"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long3",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_long3",
                    "text": "simd_long3"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "simd_make_long3"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long1",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_long1",
                    "text": "simd_long1"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "x"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long2",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_long2",
                    "text": "simd_long2"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "yz"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long3/title",
          "value": "simd_long3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_long3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_long3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_long3(_:_:)-36pz0/title",
          "value": "simd_make_long3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_long3(_:_:)-36pz0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_long3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long2/title",
          "value": "simd_long2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_long2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_long2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_long3(_:_:)-3zz23/title",
          "value": "simd_make_long3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_long3(_:_:)-3zz23/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_long3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long1/title",
          "value": "simd_long1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_long1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long1/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_long1"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_make_long3(_:_:)-3zz23"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/simd/simd_make_long3(_:_:)-3zz23"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
