{
  "abstract": [
    {
      "text": "Returns the multiply-add result for corresponding elements in three vectors.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_muladd(_:_:_:)-6kpyx"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_muladd#]4d#S0_#S0_#",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simd_muladd"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_double4",
        "text": "simd_double4"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_double4",
        "text": "simd_double4"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_double4",
        "text": "simd_double4"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_double4",
        "text": "simd_double4"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_muladd"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_muladd(_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_muladd"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "x"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_double4",
              "text": "simd_double4"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "y"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_double4",
              "text": "simd_double4"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "z"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_double4",
              "text": "simd_double4"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_double4",
              "text": "simd_double4"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The ",
                  "type": "text"
                },
                {
                  "inlineContent": [
                    {
                      "text": "x",
                      "type": "text"
                    }
                  ],
                  "type": "emphasis"
                },
                {
                  "text": " in ",
                  "type": "text"
                },
                {
                  "code": "x*y + z",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "x"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The ",
                  "type": "text"
                },
                {
                  "inlineContent": [
                    {
                      "text": "y",
                      "type": "text"
                    }
                  ],
                  "type": "emphasis"
                },
                {
                  "text": " in ",
                  "type": "text"
                },
                {
                  "code": "x*y + z",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "y"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The ",
                  "type": "text"
                },
                {
                  "inlineContent": [
                    {
                      "text": "z",
                      "type": "text"
                    }
                  ],
                  "type": "emphasis"
                },
                {
                  "text": " in ",
                  "type": "text"
                },
                {
                  "code": "x*y + z",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "z"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The result of ",
              "type": "text"
            },
            {
              "code": "x*y + z",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/cbrt": {
      "abstract": [
        {
          "text": "Returns the cube root of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "cbrt"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/cbrt",
      "kind": "symbol",
      "role": "symbol",
      "title": "cbrt",
      "type": "topic",
      "url": "/documentation/simd/cbrt"
    },
    "doc://com.apple.accelerate/documentation/simd/cbrt(_:)-7pm3s": {
      "abstract": [
        {
          "text": "Returns the cube root of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cbrt"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/cbrt(_:)-7pm3s",
      "kind": "symbol",
      "role": "symbol",
      "title": "cbrt(_:)",
      "type": "topic",
      "url": "/documentation/simd/cbrt(_:)-7pm3s"
    },
    "doc://com.apple.accelerate/documentation/simd/ceil(_:)-9s503": {
      "abstract": [
        {
          "text": "Returns the ceiling of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ceil"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD4V",
          "text": "SIMD4"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD4V",
          "text": "SIMD4"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/ceil(_:)-9s503",
      "kind": "symbol",
      "role": "symbol",
      "title": "ceil(_:)",
      "type": "topic",
      "url": "/documentation/simd/ceil(_:)-9s503"
    },
    "doc://com.apple.accelerate/documentation/simd/copysign": {
      "abstract": [
        {
          "text": "Returns each element of a vector, with the sign of the corresponding element in a second vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "copysign"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/copysign",
      "kind": "symbol",
      "role": "symbol",
      "title": "copysign",
      "type": "topic",
      "url": "/documentation/simd/copysign"
    },
    "doc://com.apple.accelerate/documentation/simd/erf": {
      "abstract": [
        {
          "text": "Returns the error function for each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "erf"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/erf",
      "kind": "symbol",
      "role": "symbol",
      "title": "erf",
      "type": "topic",
      "url": "/documentation/simd/erf"
    },
    "doc://com.apple.accelerate/documentation/simd/erf(_:)-1yjjk": {
      "abstract": [
        {
          "text": "Returns the error function for each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "erf"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/erf(_:)-1yjjk",
      "kind": "symbol",
      "role": "symbol",
      "title": "erf(_:)",
      "type": "topic",
      "url": "/documentation/simd/erf(_:)-1yjjk"
    },
    "doc://com.apple.accelerate/documentation/simd/erfc": {
      "abstract": [
        {
          "text": "Returns the complementary error function for each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "erfc"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/erfc",
      "kind": "symbol",
      "role": "symbol",
      "title": "erfc",
      "type": "topic",
      "url": "/documentation/simd/erfc"
    },
    "doc://com.apple.accelerate/documentation/simd/erfc(_:)-6rgzx": {
      "abstract": [
        {
          "text": "Returns the complementary error function for each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "erfc"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/erfc(_:)-6rgzx",
      "kind": "symbol",
      "role": "symbol",
      "title": "erfc(_:)",
      "type": "topic",
      "url": "/documentation/simd/erfc(_:)-6rgzx"
    },
    "doc://com.apple.accelerate/documentation/simd/fabs": {
      "abstract": [
        {
          "text": "Returns the absolute value of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "fabs"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/fabs",
      "kind": "symbol",
      "role": "symbol",
      "title": "fabs",
      "type": "topic",
      "url": "/documentation/simd/fabs"
    },
    "doc://com.apple.accelerate/documentation/simd/fdim": {
      "abstract": [
        {
          "text": "Returns the positive difference between corresponding elements in two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "fdim"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/fdim",
      "kind": "symbol",
      "role": "symbol",
      "title": "fdim",
      "type": "topic",
      "url": "/documentation/simd/fdim"
    },
    "doc://com.apple.accelerate/documentation/simd/floor(_:)-3956i": {
      "abstract": [
        {
          "text": "Returns the floor of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "floor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD4V",
          "text": "SIMD4"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD4V",
          "text": "SIMD4"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/floor(_:)-3956i",
      "kind": "symbol",
      "role": "symbol",
      "title": "floor(_:)",
      "type": "topic",
      "url": "/documentation/simd/floor(_:)-3956i"
    },
    "doc://com.apple.accelerate/documentation/simd/fma": {
      "abstract": [
        {
          "text": "Returns the multiply-add result for corresponding elements in three vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "fma"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/fma",
      "kind": "symbol",
      "role": "symbol",
      "title": "fma",
      "type": "topic",
      "url": "/documentation/simd/fma"
    },
    "doc://com.apple.accelerate/documentation/simd/fma(_:_:_:)-6mqpv": {
      "abstract": [
        {
          "text": "Returns the multiply-add result for corresponding elements in three vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fma"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/fma(_:_:_:)-6mqpv",
      "kind": "symbol",
      "role": "symbol",
      "title": "fma(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/fma(_:_:_:)-6mqpv"
    },
    "doc://com.apple.accelerate/documentation/simd/fmod": {
      "abstract": [
        {
          "text": "Returns the modulus after dividing each element in a vector by the corresponding element in a second vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "fmod"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/fmod",
      "kind": "symbol",
      "role": "symbol",
      "title": "fmod",
      "type": "topic",
      "url": "/documentation/simd/fmod"
    },
    "doc://com.apple.accelerate/documentation/simd/fmod(_:_:)-92tjw": {
      "abstract": [
        {
          "text": "Returns the modulus after dividing each element in a vector by the corresponding element in a second vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fmod"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/fmod(_:_:)-92tjw",
      "kind": "symbol",
      "role": "symbol",
      "title": "fmod(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/fmod(_:_:)-92tjw"
    },
    "doc://com.apple.accelerate/documentation/simd/hypot": {
      "abstract": [
        {
          "text": "Returns the hypotenuse of a right-angled triangle with the sides that are adjacent to the right angle that two vectors define.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "hypot"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/hypot",
      "kind": "symbol",
      "role": "symbol",
      "title": "hypot",
      "type": "topic",
      "url": "/documentation/simd/hypot"
    },
    "doc://com.apple.accelerate/documentation/simd/hypot(_:_:)-2exik": {
      "abstract": [
        {
          "text": "Returns the hypotenuse of a right-angled triangle with the sides that are adjacent to the right angle that two vectors define.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hypot"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/hypot(_:_:)-2exik",
      "kind": "symbol",
      "role": "symbol",
      "title": "hypot(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/hypot(_:_:)-2exik"
    },
    "doc://com.apple.accelerate/documentation/simd/lgamma(_:)-2frmv": {
      "abstract": [
        {
          "text": "Returns the natural logarithm of the absolute value of the gamma function of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lgamma"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/lgamma(_:)-2frmv",
      "kind": "symbol",
      "role": "symbol",
      "title": "lgamma(_:)",
      "type": "topic",
      "url": "/documentation/simd/lgamma(_:)-2frmv"
    },
    "doc://com.apple.accelerate/documentation/simd/nextafter": {
      "abstract": [
        {
          "text": "Returns the next representable value of each element in a vector in the direction of the corresponding element in a second vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "nextafter"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/nextafter",
      "kind": "symbol",
      "role": "symbol",
      "title": "nextafter",
      "type": "topic",
      "url": "/documentation/simd/nextafter"
    },
    "doc://com.apple.accelerate/documentation/simd/nextafter(_:_:)-oxq7": {
      "abstract": [
        {
          "text": "Returns the next representable value of each element in a vector in the direction of the corresponding element in a second vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nextafter"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/nextafter(_:_:)-oxq7",
      "kind": "symbol",
      "role": "symbol",
      "title": "nextafter(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/nextafter(_:_:)-oxq7"
    },
    "doc://com.apple.accelerate/documentation/simd/pow": {
      "abstract": [
        {
          "text": "Returns each element in a vector raised to the power of the corresponding element in a second vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "pow"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/pow",
      "kind": "symbol",
      "role": "symbol",
      "title": "pow",
      "type": "topic",
      "url": "/documentation/simd/pow"
    },
    "doc://com.apple.accelerate/documentation/simd/pow(_:_:)-3jh7o": {
      "abstract": [
        {
          "text": "Returns each element in a vector raised to the power of the corresponding element in a second vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pow"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/pow(_:_:)-3jh7o",
      "kind": "symbol",
      "role": "symbol",
      "title": "pow(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/pow(_:_:)-3jh7o"
    },
    "doc://com.apple.accelerate/documentation/simd/remainder": {
      "abstract": [
        {
          "text": "Returns the remainder after dividing each element in an array by the corresponding element in a second array of double-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "remainder"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/remainder",
      "kind": "symbol",
      "role": "symbol",
      "title": "remainder",
      "type": "topic",
      "url": "/documentation/simd/remainder"
    },
    "doc://com.apple.accelerate/documentation/simd/remainder(_:_:)-jw8b": {
      "abstract": [
        {
          "text": "Returns the remainder after dividing each element in an array by the corresponding element in a second array of double-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remainder"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/remainder(_:_:)-jw8b",
      "kind": "symbol",
      "role": "symbol",
      "title": "remainder(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/remainder(_:_:)-jw8b"
    },
    "doc://com.apple.accelerate/documentation/simd/rint": {
      "abstract": [
        {
          "text": "Returns each element in a vector rounded to the nearest integer in the specified direction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "rint"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/rint",
      "kind": "symbol",
      "role": "symbol",
      "title": "rint",
      "type": "topic",
      "url": "/documentation/simd/rint"
    },
    "doc://com.apple.accelerate/documentation/simd/round": {
      "abstract": [
        {
          "text": "Returns each element in a vector rounded to the nearest integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "round"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/round",
      "kind": "symbol",
      "role": "symbol",
      "title": "round",
      "type": "topic",
      "url": "/documentation/simd/round"
    },
    "doc://com.apple.accelerate/documentation/simd/round(_:)-5ytc6": {
      "abstract": [
        {
          "text": "Returns each element in a vector rounded to the nearest integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "round"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/round(_:)-5ytc6",
      "kind": "symbol",
      "role": "symbol",
      "title": "round(_:)",
      "type": "topic",
      "url": "/documentation/simd/round(_:)-5ytc6"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double4": {
      "abstract": [
        {
          "text": "A vector of four 64-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_double4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_double4"
        }
      ],
      "role": "symbol",
      "title": "simd_double4",
      "type": "topic",
      "url": "/documentation/simd/simd_double4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_muladd(_:_:_:)-6kpyx": {
      "abstract": [
        {
          "text": "Returns the multiply-add result for corresponding elements in three vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_muladd"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_muladd(_:_:_:)-6kpyx",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_muladd"
        }
      ],
      "role": "symbol",
      "title": "simd_muladd(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_muladd(_:_:_:)-6kpyx"
    },
    "doc://com.apple.accelerate/documentation/simd/sqrt": {
      "abstract": [
        {
          "text": "Returns the square root of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "sqrt"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/sqrt",
      "kind": "symbol",
      "role": "symbol",
      "title": "sqrt",
      "type": "topic",
      "url": "/documentation/simd/sqrt"
    },
    "doc://com.apple.accelerate/documentation/simd/tgamma(_:)-2o8vo": {
      "abstract": [
        {
          "text": "Returns the gamma function for each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tgamma"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/tgamma(_:)-2o8vo",
      "kind": "symbol",
      "role": "symbol",
      "title": "tgamma(_:)",
      "type": "topic",
      "url": "/documentation/simd/tgamma(_:)-2o8vo"
    },
    "doc://com.apple.accelerate/documentation/simd/trunc(_:)-9n2h5": {
      "abstract": [
        {
          "text": "Returns each element in a vector rounded toward zero to the nearest integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trunc"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD4V",
          "text": "SIMD4"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD4V",
          "text": "SIMD4"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/trunc(_:)-9n2h5",
      "kind": "symbol",
      "role": "symbol",
      "title": "trunc(_:)",
      "type": "topic",
      "url": "/documentation/simd/trunc(_:)-9n2h5"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Math-Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/cbrt(_:)-7pm3s",
        "doc://com.apple.accelerate/documentation/simd/ceil(_:)-9s503",
        "doc://com.apple.accelerate/documentation/simd/erf(_:)-1yjjk",
        "doc://com.apple.accelerate/documentation/simd/erfc(_:)-6rgzx",
        "doc://com.apple.accelerate/documentation/simd/floor(_:)-3956i",
        "doc://com.apple.accelerate/documentation/simd/fma(_:_:_:)-6mqpv",
        "doc://com.apple.accelerate/documentation/simd/fmod(_:_:)-92tjw",
        "doc://com.apple.accelerate/documentation/simd/hypot(_:_:)-2exik",
        "doc://com.apple.accelerate/documentation/simd/lgamma(_:)-2frmv",
        "doc://com.apple.accelerate/documentation/simd/nextafter(_:_:)-oxq7",
        "doc://com.apple.accelerate/documentation/simd/pow(_:_:)-3jh7o",
        "doc://com.apple.accelerate/documentation/simd/remainder(_:_:)-jw8b",
        "doc://com.apple.accelerate/documentation/simd/round(_:)-5ytc6",
        "doc://com.apple.accelerate/documentation/simd/tgamma(_:)-2o8vo",
        "doc://com.apple.accelerate/documentation/simd/trunc(_:)-9n2h5"
      ],
      "title": "Math Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "simd_muladd"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_muladd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/simd"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Math-Functions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/cbrt",
                "doc://com.apple.accelerate/documentation/simd/copysign",
                "doc://com.apple.accelerate/documentation/simd/erf",
                "doc://com.apple.accelerate/documentation/simd/erfc",
                "doc://com.apple.accelerate/documentation/simd/fabs",
                "doc://com.apple.accelerate/documentation/simd/fdim",
                "doc://com.apple.accelerate/documentation/simd/fma",
                "doc://com.apple.accelerate/documentation/simd/fmod",
                "doc://com.apple.accelerate/documentation/simd/hypot",
                "doc://com.apple.accelerate/documentation/simd/nextafter",
                "doc://com.apple.accelerate/documentation/simd/pow",
                "doc://com.apple.accelerate/documentation/simd/remainder",
                "doc://com.apple.accelerate/documentation/simd/rint",
                "doc://com.apple.accelerate/documentation/simd/round",
                "doc://com.apple.accelerate/documentation/simd/sqrt"
              ],
              "title": "Math Functions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "static"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_double4",
                    "text": "simd_double4"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "simd_muladd"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_double4",
                    "text": "simd_double4"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "x"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_double4",
                    "text": "simd_double4"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "y"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_double4",
                    "text": "simd_double4"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "z"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The ",
                        "type": "text"
                      },
                      {
                        "inlineContent": [
                          {
                            "text": "x",
                            "type": "text"
                          }
                        ],
                        "type": "emphasis"
                      },
                      {
                        "text": " in ",
                        "type": "text"
                      },
                      {
                        "code": "x*y + z",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "x"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The ",
                        "type": "text"
                      },
                      {
                        "inlineContent": [
                          {
                            "text": "y",
                            "type": "text"
                          }
                        ],
                        "type": "emphasis"
                      },
                      {
                        "text": " in ",
                        "type": "text"
                      },
                      {
                        "code": "x*y + z",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "y"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The ",
                        "type": "text"
                      },
                      {
                        "inlineContent": [
                          {
                            "text": "z",
                            "type": "text"
                          }
                        ],
                        "type": "emphasis"
                      },
                      {
                        "text": " in ",
                        "type": "text"
                      },
                      {
                        "code": "x*y + z",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "z"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "The result of ",
                    "type": "text"
                  },
                  {
                    "code": "x*y + z",
                    "type": "codeVoice"
                  },
                  {
                    "text": ".",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4/title",
          "value": "simd_double4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_muladd(_:_:_:)-6kpyx/title",
          "value": "simd_muladd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_muladd(_:_:_:)-6kpyx/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_muladd"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_muladd(_:_:_:)-6kpyx"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/simd/simd_muladd(_:_:_:)-6kpyx"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
