{
  "abstract": [
    {
      "text": "A vector of eight 32-bit signed integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_int8"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@simd_int8",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simd_int8"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_int8"
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "simd_int8"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_int8"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5SIMD8V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5SIMD8V",
              "text": "SIMD8"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5Int32V",
              "text": "Int32"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_abs(_:)-7os48": {
      "abstract": [
        {
          "text": "Returns the absolute value of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_abs"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int8",
          "text": "simd_int8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int8",
          "text": "simd_int8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_abs(_:)-7os48",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_abs"
        }
      ],
      "role": "symbol",
      "title": "simd_abs(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_abs(_:)-7os48"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1yx6x": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_all"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int8",
          "text": "simd_int8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_bool",
          "text": "simd_bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1yx6x",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_all"
        }
      ],
      "role": "symbol",
      "title": "simd_all(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_all(_:)-1yx6x"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-6pigr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_any"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int8",
          "text": "simd_int8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_bool",
          "text": "simd_bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-6pigr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_any"
        }
      ],
      "role": "symbol",
      "title": "simd_any(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_any(_:)-6pigr"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-361vz": {
      "abstract": [
        {
          "text": "Returns a vector that contains elements from either the first or second parameter, based on the corresponding element in the third parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_bitselect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int8",
          "text": "simd_int8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int8",
          "text": "simd_int8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int8",
          "text": "simd_int8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int8",
          "text": "simd_int8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-361vz",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_bitselect"
        }
      ],
      "role": "symbol",
      "title": "simd_bitselect(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_bitselect(_:_:_:)-361vz"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-4jo2y": {
      "abstract": [
        {
          "text": "Returns each element in a vector clamped to a specified range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_clamp"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int8",
          "text": "simd_int8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int8",
          "text": "simd_int8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int8",
          "text": "simd_int8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int8",
          "text": "simd_int8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-4jo2y",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_clamp"
        }
      ],
      "role": "symbol",
      "title": "simd_clamp(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_clamp(_:_:_:)-4jo2y"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-ojy5": {
      "abstract": [
        {
          "text": "Returns true if every element in a vector is exactly equal to the corresponding element in a second vector, and otherwise returns false.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_equal"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int8",
          "text": "simd_int8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int8",
          "text": "simd_int8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_bool",
          "text": "simd_bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-ojy5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_equal"
        }
      ],
      "role": "symbol",
      "title": "simd_equal(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_equal(_:_:)-ojy5"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int-neij": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int-neij",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int",
      "type": "topic",
      "url": "/documentation/simd/simd_int-neij"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int-nfj5": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int-nfj5",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int",
      "type": "topic",
      "url": "/documentation/simd/simd_int-nfj5"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int-ngyj": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int-ngyj",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int",
      "type": "topic",
      "url": "/documentation/simd/simd_int-ngyj"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int-nhpj": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int-nhpj",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int",
      "type": "topic",
      "url": "/documentation/simd/simd_int-nhpj"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int-nik1": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int-nik1",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int",
      "type": "topic",
      "url": "/documentation/simd/simd_int-nik1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int-nnht": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int-nnht",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int",
      "type": "topic",
      "url": "/documentation/simd/simd_int-nnht"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int-nojf": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int-nojf",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int",
      "type": "topic",
      "url": "/documentation/simd/simd_int-nojf"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int-npcx": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int-npcx",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int",
      "type": "topic",
      "url": "/documentation/simd/simd_int-npcx"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int-nskx": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int-nskx",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int",
      "type": "topic",
      "url": "/documentation/simd/simd_int-nskx"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int-nxm9": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int-nxm9",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int",
      "type": "topic",
      "url": "/documentation/simd/simd_int-nxm9"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int1": {
      "abstract": [
        {
          "text": "A vector of one 32-bit signed integer element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_int1"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_int1"
        }
      ],
      "role": "symbol",
      "title": "simd_int1",
      "type": "topic",
      "url": "/documentation/simd/simd_int1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int16": {
      "abstract": [
        {
          "text": "A vector of sixteen 32-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_int16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_int16"
        }
      ],
      "role": "symbol",
      "title": "simd_int16",
      "type": "topic",
      "url": "/documentation/simd/simd_int16"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int2": {
      "abstract": [
        {
          "text": "A vector of two 32-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_int2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_int2"
        }
      ],
      "role": "symbol",
      "title": "simd_int2",
      "type": "topic",
      "url": "/documentation/simd/simd_int2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int3": {
      "abstract": [
        {
          "text": "A vector of three 32-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_int3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_int3"
        }
      ],
      "role": "symbol",
      "title": "simd_int3",
      "type": "topic",
      "url": "/documentation/simd/simd_int3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int4": {
      "abstract": [
        {
          "text": "A vector of four 32-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_int4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_int4"
        }
      ],
      "role": "symbol",
      "title": "simd_int4",
      "type": "topic",
      "url": "/documentation/simd/simd_int4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int8": {
      "abstract": [
        {
          "text": "A vector of eight 32-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_int8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_int8"
        }
      ],
      "role": "symbol",
      "title": "simd_int8",
      "type": "topic",
      "url": "/documentation/simd/simd_int8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int_rte-7ziwq": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified eight-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int_rte"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int_rte-7ziwq",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int_rte",
      "type": "topic",
      "url": "/documentation/simd/simd_int_rte-7ziwq"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7dovl": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7dovl",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_int_sat-7dovl"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7dttd": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7dttd",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_int_sat-7dttd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7dubn": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7dubn",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_int_sat-7dubn"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7dvvt": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7dvvt",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_int_sat-7dvvt"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7dysx": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7dysx",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_int_sat-7dysx"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7e1v7": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7e1v7",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_int_sat-7e1v7"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7e2fr": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7e2fr",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_int_sat-7e2fr"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7e41d": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7e41d",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_int_sat-7e41d"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7e43n": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7e43n",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_int_sat-7e43n"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7e5pl": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7e5pl",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_int_sat-7e5pl"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_int8(_:)-3lu01": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified sixteen-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_int8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int16",
          "text": "simd_int16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int8",
          "text": "simd_int8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_int8(_:)-3lu01",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_int8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_int8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_int8(_:)-3lu01"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_int8(_:)-9s1jp": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_int8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int2",
          "text": "simd_int2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int8",
          "text": "simd_int8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_int8(_:)-9s1jp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_int8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_int8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_int8(_:)-9s1jp"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_int8(_:)-9srg8": {
      "abstract": [
        {
          "text": "Returns a new vector with the first element set to a scalar value, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_int8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int8",
          "text": "simd_int8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_int8(_:)-9srg8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_int8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_int8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_int8(_:)-9srg8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_int8(_:)-9vi30": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified three-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_int8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int3",
          "text": "simd_int3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int8",
          "text": "simd_int8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_int8(_:)-9vi30",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_int8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_int8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_int8(_:)-9vi30"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_int8(_:)-efr4": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified four-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_int8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int4",
          "text": "simd_int4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int8",
          "text": "simd_int8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_int8(_:)-efr4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_int8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_int8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_int8(_:)-efr4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_int8(_:)-r4ak": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_int8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int8",
          "text": "simd_int8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int8",
          "text": "simd_int8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_int8(_:)-r4ak",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_int8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_int8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_int8(_:)-r4ak"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_int8(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_int8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int4",
          "text": "simd_int4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int4",
          "text": "simd_int4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int8",
          "text": "simd_int8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_int8(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_int8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_int8(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_int8(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_int8_undef(_:)-2ce80": {
      "abstract": [
        {
          "text": "Returns a new vector with the first element set to a scalar value, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_int8_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int8",
          "text": "simd_int8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_int8_undef(_:)-2ce80",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_int8_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_int8_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_int8_undef(_:)-2ce80"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_int8_undef(_:)-5324d": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified three-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_int8_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int3",
          "text": "simd_int3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int8",
          "text": "simd_int8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_int8_undef(_:)-5324d",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_int8_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_int8_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_int8_undef(_:)-5324d"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_int8_undef(_:)-57mj8": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_int8_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int2",
          "text": "simd_int2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int8",
          "text": "simd_int8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_int8_undef(_:)-57mj8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_int8_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_int8_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_int8_undef(_:)-57mj8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_int8_undef(_:)-5rem2": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified four-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_int8_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int4",
          "text": "simd_int4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int8",
          "text": "simd_int8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_int8_undef(_:)-5rem2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_int8_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_int8_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_int8_undef(_:)-5rem2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-5sjen": {
      "abstract": [
        {
          "text": "Returns the maximum value of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_max"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int8",
          "text": "simd_int8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int8",
          "text": "simd_int8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int8",
          "text": "simd_int8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-5sjen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_max"
        }
      ],
      "role": "symbol",
      "title": "simd_max(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_max(_:_:)-5sjen"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-2fywl": {
      "abstract": [
        {
          "text": "Returns the minimum value of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_min"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int8",
          "text": "simd_int8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int8",
          "text": "simd_int8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int8",
          "text": "simd_int8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-2fywl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_min"
        }
      ],
      "role": "symbol",
      "title": "simd_min(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_min(_:_:)-2fywl"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-3b56c": {
      "abstract": [
        {
          "text": "Returns the sum of all elements in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_add"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int8",
          "text": "simd_int8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-3b56c",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_add"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_add(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_add(_:)-3b56c"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-55kne": {
      "abstract": [
        {
          "text": "Returns the maximum value in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_max"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int8",
          "text": "simd_int8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-55kne",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_max"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_max(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_max(_:)-55kne"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-3ojci": {
      "abstract": [
        {
          "text": "Returns the miniumum value in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_min"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int8",
          "text": "simd_int8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-3ojci",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_min"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_min(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_min(_:)-3ojci"
    },
    "doc://com.apple.accelerate/documentation/simd/vector8-5snjo": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector8-5snjo",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector8",
      "type": "topic",
      "url": "/documentation/simd/vector8-5snjo"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_int8": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vector_int8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_int8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vector_int8"
        }
      ],
      "role": "symbol",
      "title": "vector_int8",
      "type": "topic",
      "url": "/documentation/simd/vector_int8"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s5Int32V": {
      "abstract": [
        {
          "text": "A 32-bit signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int32",
      "type": "topic",
      "url": "/documentation/Swift/Int32"
    },
    "doc://com.externally.resolved.symbol/s:s5SIMD8V": {
      "abstract": [
        {
          "text": "A vector of eight scalar values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SIMD8"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SIMDScalarP",
          "text": "SIMDScalar"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5SIMD8V",
      "kind": "symbol",
      "role": "symbol",
      "title": "SIMD8",
      "type": "topic",
      "url": "/documentation/Swift/SIMD8"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Vector-Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_int1",
        "doc://com.apple.accelerate/documentation/simd/simd_int2",
        "doc://com.apple.accelerate/documentation/simd/simd_int3",
        "doc://com.apple.accelerate/documentation/simd/simd_int4",
        "doc://com.apple.accelerate/documentation/simd/simd_int16"
      ],
      "title": "Vector Data Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Functions-to-Create-Eight-Element-Vectors-From-Other-Vectors",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_int8(_:)-9s1jp",
        "doc://com.apple.accelerate/documentation/simd/simd_make_int8(_:)-9vi30",
        "doc://com.apple.accelerate/documentation/simd/simd_make_int8(_:)-efr4",
        "doc://com.apple.accelerate/documentation/simd/simd_make_int8(_:)-r4ak",
        "doc://com.apple.accelerate/documentation/simd/simd_make_int8(_:)-3lu01",
        "doc://com.apple.accelerate/documentation/simd/simd_make_int8(_:_:)",
        "doc://com.apple.accelerate/documentation/simd/simd_make_int8_undef(_:)-57mj8",
        "doc://com.apple.accelerate/documentation/simd/simd_make_int8_undef(_:)-5324d",
        "doc://com.apple.accelerate/documentation/simd/simd_make_int8_undef(_:)-5rem2"
      ],
      "title": "Functions to Create Eight-Element Vectors From Other Vectors"
    },
    {
      "anchor": "Functions-to-Create-Eight-Element-Vectors-From-Scalar-Values",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_int8(_:)-9srg8",
        "doc://com.apple.accelerate/documentation/simd/simd_make_int8_undef(_:)-2ce80"
      ],
      "title": "Functions to Create Eight-Element Vectors From Scalar Values"
    },
    {
      "anchor": "Common-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_abs(_:)-7os48",
        "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-4jo2y",
        "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-ojy5"
      ],
      "title": "Common Functions"
    },
    {
      "anchor": "Reduce-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-3ojci",
        "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-55kne",
        "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-3b56c"
      ],
      "title": "Reduce Functions"
    },
    {
      "anchor": "Extrema-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-2fywl",
        "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-5sjen"
      ],
      "title": "Extrema Functions"
    },
    {
      "anchor": "Logic-and-Bitwise-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-6pigr",
        "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1yx6x",
        "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-361vz"
      ],
      "title": "Logic and Bitwise Functions"
    },
    {
      "anchor": "Alternative-Type-Alias",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/vector_int8"
      ],
      "title": "Alternative Type Alias"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "simd_int8"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_int8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_int8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/simd"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Functions-to-Create-Eight-Element-Vectors-From-Other-Vectors",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_int8(_:)-9s1jp",
                "doc://com.apple.accelerate/documentation/simd/simd_make_int8(_:)-9vi30",
                "doc://com.apple.accelerate/documentation/simd/simd_make_int8(_:)-efr4",
                "doc://com.apple.accelerate/documentation/simd/simd_make_int8(_:)-r4ak",
                "doc://com.apple.accelerate/documentation/simd/simd_make_int8(_:)-3lu01",
                "doc://com.apple.accelerate/documentation/simd/simd_make_int8(_:_:)",
                "doc://com.apple.accelerate/documentation/simd/vector8-5snjo",
                "doc://com.apple.accelerate/documentation/simd/simd_make_int8_undef(_:)-57mj8",
                "doc://com.apple.accelerate/documentation/simd/simd_make_int8_undef(_:)-5324d",
                "doc://com.apple.accelerate/documentation/simd/simd_make_int8_undef(_:)-5rem2"
              ],
              "title": "Functions to Create Eight-Element Vectors From Other Vectors"
            },
            {
              "anchor": "Functions-to-Create-Eight-Element-Vectors-From-Scalar-Values",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_int8(_:)-9srg8",
                "doc://com.apple.accelerate/documentation/simd/simd_make_int8_undef(_:)-2ce80"
              ],
              "title": "Functions to Create Eight-Element Vectors From Scalar Values"
            },
            {
              "anchor": "Functions-to-Create-Eight-Element-Vectors-From-Vectors-of-Other-Types",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_int-nskx",
                "doc://com.apple.accelerate/documentation/simd/simd_int-nik1",
                "doc://com.apple.accelerate/documentation/simd/simd_int-nxm9",
                "doc://com.apple.accelerate/documentation/simd/simd_int-nnht",
                "doc://com.apple.accelerate/documentation/simd/simd_int-npcx",
                "doc://com.apple.accelerate/documentation/simd/simd_int-nfj5",
                "doc://com.apple.accelerate/documentation/simd/simd_int-nojf",
                "doc://com.apple.accelerate/documentation/simd/simd_int-neij",
                "doc://com.apple.accelerate/documentation/simd/simd_int-nhpj",
                "doc://com.apple.accelerate/documentation/simd/simd_int-ngyj"
              ],
              "title": "Functions to Create Eight-Element Vectors From Vectors of Other Types"
            },
            {
              "anchor": "Functions-to-Perform-Saturating-Conversion-From-Vectors-of-Other-Types",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7dttd",
                "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7e41d",
                "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7dovl",
                "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7dysx",
                "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7dvvt",
                "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7e5pl",
                "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7dubn",
                "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7e43n",
                "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7e2fr",
                "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7e1v7"
              ],
              "title": "Functions to Perform Saturating Conversion From Vectors of Other Types"
            },
            {
              "anchor": "Functions-to-Perform-Round-Half-to-Even-Conversion-From-Single-Precision-Vectors",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_int_rte-7ziwq"
              ],
              "title": "Functions to Perform Round-Half-to-Even Conversion From Single-Precision Vectors"
            },
            {
              "anchor": "Common-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_abs(_:)-7os48",
                "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-4jo2y",
                "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-ojy5"
              ],
              "title": "Common Functions"
            },
            {
              "anchor": "Reduce-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-3ojci",
                "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-55kne",
                "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-3b56c"
              ],
              "title": "Reduce Functions"
            },
            {
              "anchor": "Extrema-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-2fywl",
                "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-5sjen"
              ],
              "title": "Extrema Functions"
            },
            {
              "anchor": "Logic-and-Bitwise-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-6pigr",
                "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1yx6x",
                "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-361vz"
              ],
              "title": "Logic and Bitwise Functions"
            },
            {
              "anchor": "Alternative-Type-Alias",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/vector_int8"
              ],
              "title": "Alternative Type Alias"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Vector-Data-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_int1",
                "doc://com.apple.accelerate/documentation/simd/simd_int2",
                "doc://com.apple.accelerate/documentation/simd/simd_int3",
                "doc://com.apple.accelerate/documentation/simd/simd_int4",
                "doc://com.apple.accelerate/documentation/simd/simd_int16"
              ],
              "title": "Vector Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:]8I",
                    "text": "int __attribute__((ext_vector_type(8)))"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "simd_int8"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_bitselect(_:_:_:)-361vz/title",
          "value": "simd_bitselect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_bitselect(_:_:_:)-361vz/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_bitselect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int8(_:)-3lu01/title",
          "value": "simd_make_int8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int8(_:)-3lu01/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_int8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int3/title",
          "value": "simd_int3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_int3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_int3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_any(_:)-6pigr/title",
          "value": "simd_any"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_any(_:)-6pigr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_any"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_add(_:)-3b56c/title",
          "value": "simd_reduce_add"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_add(_:)-3b56c/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_add"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int8_undef(_:)-2ce80/title",
          "value": "simd_make_int8_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int8_undef(_:)-2ce80/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_int8_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_abs(_:)-7os48/title",
          "value": "simd_abs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_abs(_:)-7os48/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_abs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_max(_:)-55kne/title",
          "value": "simd_reduce_max"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_max(_:)-55kne/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_max"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_equal(_:_:)-ojy5/title",
          "value": "simd_equal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_equal(_:_:)-ojy5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_equal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_max(_:_:)-5sjen/title",
          "value": "simd_max"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_max(_:_:)-5sjen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_max"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int8_undef(_:)-5rem2/title",
          "value": "simd_make_int8_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int8_undef(_:)-5rem2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_int8_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_clamp(_:_:_:)-4jo2y/title",
          "value": "simd_clamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_clamp(_:_:_:)-4jo2y/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_clamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int8(_:)-9s1jp/title",
          "value": "simd_make_int8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int8(_:)-9s1jp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_int8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int8/title",
          "value": "simd_int8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_int8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_int8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int8_undef(_:)-57mj8/title",
          "value": "simd_make_int8_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int8_undef(_:)-57mj8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_int8_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int8(_:)-efr4/title",
          "value": "simd_make_int8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int8(_:)-efr4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_int8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1vector_int8/title",
          "value": "vector_int8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1vector_int8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vector_int8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1vector_int8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vector_int8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int8(_:)-9srg8/title",
          "value": "simd_make_int8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int8(_:)-9srg8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_int8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int16/title",
          "value": "simd_int16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_int16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int16/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_int16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int8(_:)-r4ak/title",
          "value": "simd_make_int8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int8(_:)-r4ak/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_int8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_min(_:_:)-2fywl/title",
          "value": "simd_min"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_min(_:_:)-2fywl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_min"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int8_undef(_:)-5324d/title",
          "value": "simd_make_int8_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int8_undef(_:)-5324d/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_int8_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int8(_:)-9vi30/title",
          "value": "simd_make_int8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int8(_:)-9vi30/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_int8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_min(_:)-3ojci/title",
          "value": "simd_reduce_min"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_min(_:)-3ojci/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_min"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int8(_:_:)/title",
          "value": "simd_make_int8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int8(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_int8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_all(_:)-1yx6x/title",
          "value": "simd_all"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_all(_:)-1yx6x/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_all"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int4/title",
          "value": "simd_int4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_int4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_int4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int1/title",
          "value": "simd_int1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_int1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int1/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_int1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int2/title",
          "value": "simd_int2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_int2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_int2"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_int8"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/simd/simd_int8"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
