{
  "abstract": [
    {
      "text": "Returns a new vector from the specified sixteen-element vector, and other elements undefined.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32_undef(_:)-9vswr"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_make_uchar32_undef#]16c#",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simd_make_uchar32_undef"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_uchar16",
        "text": "simd_uchar16"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_uchar32",
        "text": "simd_uchar32"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_make_uchar32_undef"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_make_uchar32_undef(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_make_uchar32_undef"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "other"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar16",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_uchar16",
              "text": "simd_uchar16"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar32",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_uchar32",
              "text": "simd_uchar32"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-3c53d": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar32"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-3c53d",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar32"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar32(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar32(_:)-3c53d"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-3tap7": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified sixty four-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar32"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar64",
          "text": "simd_uchar64"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-3tap7",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar32"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar32(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar32(_:)-3tap7"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-94jec": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified sixteen-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar32"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar16",
          "text": "simd_uchar16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-94jec",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar32"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar32(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar32(_:)-94jec"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-cvfv": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified four-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar32"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar4",
          "text": "simd_uchar4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-cvfv",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar32"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar32(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar32(_:)-cvfv"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-lv3": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified eight-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar32"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar8",
          "text": "simd_uchar8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-lv3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar32"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar32(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar32(_:)-lv3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-uuk8": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified three-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar32"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar3",
          "text": "simd_uchar3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-uuk8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar32"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar32(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar32(_:)-uuk8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-ycg1": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar32"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar2",
          "text": "simd_uchar2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-ycg1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar32"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar32(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar32(_:)-ycg1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar32"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar16",
          "text": "simd_uchar16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar16",
          "text": "simd_uchar16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar32"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar32(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar32(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32_undef(_:)-78b83": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified eight-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar32_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar8",
          "text": "simd_uchar8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32_undef(_:)-78b83",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar32_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar32_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar32_undef(_:)-78b83"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32_undef(_:)-86jc5": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar32_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar2",
          "text": "simd_uchar2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32_undef(_:)-86jc5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar32_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar32_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar32_undef(_:)-86jc5"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32_undef(_:)-89hb0": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified three-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar32_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar3",
          "text": "simd_uchar3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32_undef(_:)-89hb0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar32_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar32_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar32_undef(_:)-89hb0"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32_undef(_:)-8emxj": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified four-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar32_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar4",
          "text": "simd_uchar4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32_undef(_:)-8emxj",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar32_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar32_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar32_undef(_:)-8emxj"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32_undef(_:)-9vswr": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified sixteen-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar32_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar16",
          "text": "simd_uchar16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32_undef(_:)-9vswr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar32_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar32_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar32_undef(_:)-9vswr"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar16": {
      "abstract": [
        {
          "text": "A vector of sixteen 8-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uchar16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uchar16"
        }
      ],
      "role": "symbol",
      "title": "simd_uchar16",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar16"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar32": {
      "abstract": [
        {
          "text": "A vector of thirty-two 8-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uchar32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uchar32"
        }
      ],
      "role": "symbol",
      "title": "simd_uchar32",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar32"
    },
    "doc://com.apple.accelerate/documentation/simd/vector32-68jyf": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector32-68jyf",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector32",
      "type": "topic",
      "url": "/documentation/simd/vector32-68jyf"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Create-Thirty-Two-Element-Vectors-From-Other-Vectors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-ycg1",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-uuk8",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-cvfv",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-lv3",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-94jec",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-3c53d",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-3tap7",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:_:)",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32_undef(_:)-86jc5",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32_undef(_:)-89hb0",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32_undef(_:)-8emxj",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32_undef(_:)-78b83"
      ],
      "title": "Functions to Create Thirty Two-Element Vectors From Other Vectors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "simd_make_uchar32_undef"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar32_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/simd"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Functions-to-Create-Thirty-Two-Element-Vectors-From-Other-Vectors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-ycg1",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-uuk8",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-cvfv",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-lv3",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-94jec",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-3c53d",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:)-3tap7",
                "doc://com.apple.accelerate/documentation/simd/vector32-68jyf",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32(_:_:)",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32_undef(_:)-86jc5",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32_undef(_:)-89hb0",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32_undef(_:)-8emxj",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar32_undef(_:)-78b83"
              ],
              "title": "Functions to Create Thirty Two-Element Vectors From Other Vectors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "static"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar32",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_uchar32",
                    "text": "simd_uchar32"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "simd_make_uchar32_undef"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar16",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_uchar16",
                    "text": "simd_uchar16"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "other"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32_undef(_:)-89hb0/title",
          "value": "simd_make_uchar32_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32_undef(_:)-89hb0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar32_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32_undef(_:)-8emxj/title",
          "value": "simd_make_uchar32_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32_undef(_:)-8emxj/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar32_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32_undef(_:)-86jc5/title",
          "value": "simd_make_uchar32_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32_undef(_:)-86jc5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar32_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32(_:)-3c53d/title",
          "value": "simd_make_uchar32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32(_:)-3c53d/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32(_:)-ycg1/title",
          "value": "simd_make_uchar32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32(_:)-ycg1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32(_:)-cvfv/title",
          "value": "simd_make_uchar32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32(_:)-cvfv/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32(_:)-uuk8/title",
          "value": "simd_make_uchar32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32(_:)-uuk8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32(_:_:)/title",
          "value": "simd_make_uchar32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32(_:)-3tap7/title",
          "value": "simd_make_uchar32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32(_:)-3tap7/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32(_:)-94jec/title",
          "value": "simd_make_uchar32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32(_:)-94jec/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32(_:)-lv3/title",
          "value": "simd_make_uchar32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32(_:)-lv3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar32/title",
          "value": "simd_uchar32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar32/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar16/title",
          "value": "simd_uchar16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar16/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32_undef(_:)-78b83/title",
          "value": "simd_make_uchar32_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32_undef(_:)-78b83/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar32_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32_undef(_:)-9vswr/title",
          "value": "simd_make_uchar32_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar32_undef(_:)-9vswr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar32_undef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_make_uchar32_undef(_:)-9vswr"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/simd/simd_make_uchar32_undef(_:)-9vswr"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
