{
  "abstract": [
    {
      "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_char-7arha"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_char#]8d#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_char"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_char"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_char"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char8",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_char8",
              "text": "simd_char8"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_char"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double8",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_double8",
              "text": "simd_double8"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char-7apve": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char-7apve",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char",
      "type": "topic",
      "url": "/documentation/simd/simd_char-7apve"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char-7aqw2": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char-7aqw2",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char",
      "type": "topic",
      "url": "/documentation/simd/simd_char-7aqw2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char-7arha": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char-7arha",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char",
      "type": "topic",
      "url": "/documentation/simd/simd_char-7arha"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char-7at2e": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char-7at2e",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char",
      "type": "topic",
      "url": "/documentation/simd/simd_char-7at2e"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char-7au4e": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char-7au4e",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char",
      "type": "topic",
      "url": "/documentation/simd/simd_char-7au4e"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char-7aure": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char-7aure",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char",
      "type": "topic",
      "url": "/documentation/simd/simd_char-7aure"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char-7azp6": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char-7azp6",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char",
      "type": "topic",
      "url": "/documentation/simd/simd_char-7azp6"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char-7b2w6": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char-7b2w6",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char",
      "type": "topic",
      "url": "/documentation/simd/simd_char-7b2w6"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char-7b3y6": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char-7b3y6",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char",
      "type": "topic",
      "url": "/documentation/simd/simd_char-7b3y6"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char-7b4ze": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char-7b4ze",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char",
      "type": "topic",
      "url": "/documentation/simd/simd_char-7b4ze"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char8": {
      "abstract": [
        {
          "text": "A vector of eight 8-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_char8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_char8"
        }
      ],
      "role": "symbol",
      "title": "simd_char8",
      "type": "topic",
      "url": "/documentation/simd/simd_char8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double8": {
      "abstract": [
        {
          "text": "A vector of eight 64-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_double8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_double8"
        }
      ],
      "role": "symbol",
      "title": "simd_double8",
      "type": "topic",
      "url": "/documentation/simd/simd_double8"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Create-Eight-Element-Vectors-From-Vectors-of-Other-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_char-7azp6",
        "doc://com.apple.accelerate/documentation/simd/simd_char-7apve",
        "doc://com.apple.accelerate/documentation/simd/simd_char-7b4ze",
        "doc://com.apple.accelerate/documentation/simd/simd_char-7aure",
        "doc://com.apple.accelerate/documentation/simd/simd_char-7b2w6",
        "doc://com.apple.accelerate/documentation/simd/simd_char-7at2e",
        "doc://com.apple.accelerate/documentation/simd/simd_char-7b3y6",
        "doc://com.apple.accelerate/documentation/simd/simd_char-7au4e",
        "doc://com.apple.accelerate/documentation/simd/simd_char-7aqw2"
      ],
      "title": "Functions to Create Eight-Element Vectors From Vectors of Other Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char8/title",
          "value": "simd_char8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double8/title",
          "value": "simd_double8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double8"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_char-7arha"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
