{
  "abstract": [
    {
      "text": "Returns the square of the distance between two vectors.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_distance_squared-6xb9g"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_distance_squared#]32h#S0_#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_distance_squared"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_distance_squared"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_distance_squared"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:h",
              "text": "_Float16"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_distance_squared"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half32",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_half32",
              "text": "simd_half32"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half32",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_half32",
              "text": "simd_half32"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__y"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_distance-5389o": {
      "abstract": [
        {
          "text": "Returns the distance between two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_distance"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_distance-5389o",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_distance",
      "type": "topic",
      "url": "/documentation/simd/simd_distance-5389o"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_distance_squared-6xb9g": {
      "abstract": [
        {
          "text": "Returns the square of the distance between two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_distance_squared"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_distance_squared-6xb9g",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_distance_squared",
      "type": "topic",
      "url": "/documentation/simd/simd_distance_squared-6xb9g"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_fast_distance-5ufke": {
      "abstract": [
        {
          "text": "Returns the fast distance between two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_fast_distance"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_fast_distance-5ufke",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_fast_distance",
      "type": "topic",
      "url": "/documentation/simd/simd_fast_distance-5ufke"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_fast_length-4jwws": {
      "abstract": [
        {
          "text": "Returns the fast length of a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_fast_length"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_fast_length-4jwws",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_fast_length",
      "type": "topic",
      "url": "/documentation/simd/simd_fast_length-4jwws"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half32": {
      "abstract": [
        {
          "text": "A vector of thirty-two 16-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_half32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_half32"
        }
      ],
      "role": "symbol",
      "title": "simd_half32",
      "type": "topic",
      "url": "/documentation/simd/simd_half32"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_length-zvvu": {
      "abstract": [
        {
          "text": "Returns the length of a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_length"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_length-zvvu",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_length",
      "type": "topic",
      "url": "/documentation/simd/simd_length-zvvu"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_length_squared-9h8sy": {
      "abstract": [
        {
          "text": "Returns the square of the length of a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_length_squared"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_length_squared-9h8sy",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_length_squared",
      "type": "topic",
      "url": "/documentation/simd/simd_length_squared-9h8sy"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_precise_distance-3ed89": {
      "abstract": [
        {
          "text": "Returns the precise distance between two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_precise_distance"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_precise_distance-3ed89",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_precise_distance",
      "type": "topic",
      "url": "/documentation/simd/simd_precise_distance-3ed89"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_precise_length-916dp": {
      "abstract": [
        {
          "text": "Returns the precise length of a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_precise_length"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_precise_length-916dp",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_precise_length",
      "type": "topic",
      "url": "/documentation/simd/simd_precise_length-916dp"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Length-and-distance-functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_length-zvvu",
        "doc://com.apple.accelerate/documentation/simd/simd_fast_length-4jwws",
        "doc://com.apple.accelerate/documentation/simd/simd_precise_length-916dp",
        "doc://com.apple.accelerate/documentation/simd/simd_length_squared-9h8sy",
        "doc://com.apple.accelerate/documentation/simd/simd_distance-5389o",
        "doc://com.apple.accelerate/documentation/simd/simd_fast_distance-5ufke",
        "doc://com.apple.accelerate/documentation/simd/simd_precise_distance-3ed89"
      ],
      "title": "Length and distance functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half32/title",
          "value": "simd_half32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half32/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half32"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_distance_squared-6xb9g"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
