{
  "abstract": [
    {
      "text": "Returns the precise projected vector.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_precise_project-7t3qn"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_precise_project#]2d#S0_#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_precise_project"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_precise_project"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_precise_project"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_double2",
              "text": "simd_double2"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_precise_project"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_double2",
              "text": "simd_double2"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_double2",
              "text": "simd_double2"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__y"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_cross-1dixl": {
      "abstract": [
        {
          "text": "Returns the cross product of two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_cross"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_cross-1dixl",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_cross",
      "type": "topic",
      "url": "/documentation/simd/simd_cross-1dixl"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_dot-3r1vl": {
      "abstract": [
        {
          "text": "Returns the dot product of two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_dot"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_dot-3r1vl",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_dot",
      "type": "topic",
      "url": "/documentation/simd/simd_dot-3r1vl"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double2": {
      "abstract": [
        {
          "text": "A vector of two 64-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_double2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_double2"
        }
      ],
      "role": "symbol",
      "title": "simd_double2",
      "type": "topic",
      "url": "/documentation/simd/simd_double2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_fast_normalize-9wy6m": {
      "abstract": [
        {
          "text": "Returns the fast normalized vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_fast_normalize"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_fast_normalize-9wy6m",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_fast_normalize",
      "type": "topic",
      "url": "/documentation/simd/simd_fast_normalize-9wy6m"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_fast_project-6c68k": {
      "abstract": [
        {
          "text": "Returns the fast projected vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_fast_project"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_fast_project-6c68k",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_fast_project",
      "type": "topic",
      "url": "/documentation/simd/simd_fast_project-6c68k"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_incircle-8iogb": {
      "abstract": [
        {
          "text": "Tests if a double-precision point lies inside, on, or outside a circle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_incircle"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_incircle-8iogb",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_incircle",
      "type": "topic",
      "url": "/documentation/simd/simd_incircle-8iogb"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_normalize-9fo1c": {
      "abstract": [
        {
          "text": "Returns a vector pointing in the same direction of the supplied vector, with a length of 1.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_normalize"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_normalize-9fo1c",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_normalize",
      "type": "topic",
      "url": "/documentation/simd/simd_normalize-9fo1c"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_orient-9b2wf": {
      "abstract": [
        {
          "text": "Tests the orientation of the three supplied vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_orient"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_orient-9b2wf",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_orient",
      "type": "topic",
      "url": "/documentation/simd/simd_orient-9b2wf"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_orient-9fgki": {
      "abstract": [
        {
          "text": "Tests the orientation of the two supplied vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_orient"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_orient-9fgki",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_orient",
      "type": "topic",
      "url": "/documentation/simd/simd_orient-9fgki"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_precise_normalize-54dru": {
      "abstract": [
        {
          "text": "Returns the precise normalized vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_precise_normalize"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_precise_normalize-54dru",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_precise_normalize",
      "type": "topic",
      "url": "/documentation/simd/simd_precise_normalize-54dru"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_precise_project-7t3qn": {
      "abstract": [
        {
          "text": "Returns the precise projected vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_precise_project"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_precise_project-7t3qn",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_precise_project",
      "type": "topic",
      "url": "/documentation/simd/simd_precise_project-7t3qn"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_project-1mg5p": {
      "abstract": [
        {
          "text": "Returns the first vector projected onto the second vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_project"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_project-1mg5p",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_project",
      "type": "topic",
      "url": "/documentation/simd/simd_project-1mg5p"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reflect-7c8f9": {
      "abstract": [
        {
          "text": "Returns the reflection direction of an incident vector and a unit normal vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_reflect"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reflect-7c8f9",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_reflect",
      "type": "topic",
      "url": "/documentation/simd/simd_reflect-7c8f9"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_refract-4ani9": {
      "abstract": [
        {
          "text": "Returns the refraction direction of an incident vector, a unit normal vector, and an index of refraction eta.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_refract"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_refract-4ani9",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_refract",
      "type": "topic",
      "url": "/documentation/simd/simd_refract-4ani9"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Geometry-Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_cross-1dixl",
        "doc://com.apple.accelerate/documentation/simd/simd_dot-3r1vl",
        "doc://com.apple.accelerate/documentation/simd/simd_incircle-8iogb",
        "doc://com.apple.accelerate/documentation/simd/simd_normalize-9fo1c",
        "doc://com.apple.accelerate/documentation/simd/simd_fast_normalize-9wy6m",
        "doc://com.apple.accelerate/documentation/simd/simd_precise_normalize-54dru",
        "doc://com.apple.accelerate/documentation/simd/simd_orient-9fgki",
        "doc://com.apple.accelerate/documentation/simd/simd_orient-9b2wf",
        "doc://com.apple.accelerate/documentation/simd/simd_project-1mg5p",
        "doc://com.apple.accelerate/documentation/simd/simd_fast_project-6c68k",
        "doc://com.apple.accelerate/documentation/simd/simd_reflect-7c8f9",
        "doc://com.apple.accelerate/documentation/simd/simd_refract-4ani9"
      ],
      "title": "Geometry Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double2/title",
          "value": "simd_double2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double2"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_precise_project-7t3qn"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
