{
  "abstract": [
    {
      "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1lwse"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_ulong_sat#]2c#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_ulong_sat"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_ulong_sat"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_ulong_sat"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_ulong2",
              "text": "simd_ulong2"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_ulong_sat"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_uchar2",
              "text": "simd_uchar2"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar2": {
      "abstract": [
        {
          "text": "A vector of two 8-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uchar2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uchar2"
        }
      ],
      "role": "symbol",
      "title": "simd_uchar2",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong2": {
      "abstract": [
        {
          "text": "A vector of two 64-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ulong2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ulong2"
        }
      ],
      "role": "symbol",
      "title": "simd_ulong2",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1ll2i": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1ll2i",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong_sat-1ll2i"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1llwi": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1llwi",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong_sat-1llwi"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1lmym": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1lmym",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong_sat-1lmym"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1lrzy": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1lrzy",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong_sat-1lrzy"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1lv3e": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1lv3e",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong_sat-1lv3e"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1lvtu": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1lvtu",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong_sat-1lvtu"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1lwse": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1lwse",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong_sat-1lwse"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1lxxa": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1lxxa",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong_sat-1lxxa"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1lyhe": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1lyhe",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong_sat-1lyhe"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1m1q6": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1m1q6",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong_sat-1m1q6"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Perform-Saturating-Conversion-From-Vectors-of-Other-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1lmym",
        "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1lrzy",
        "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1m1q6",
        "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1ll2i",
        "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1lv3e",
        "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1llwi",
        "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1lvtu",
        "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1lxxa",
        "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1lyhe"
      ],
      "title": "Functions to Perform Saturating Conversion From Vectors of Other Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong2/title",
          "value": "simd_ulong2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar2/title",
          "value": "simd_uchar2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar2"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_ulong_sat-1lwse"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
