{
  "abstract": [
    {
      "text": "Returns a new vector from the specified three-element vector, and other elements undefined.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_make_float4_undef(_:)-3f7tu"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_make_float4_undef#]3f#",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simd_make_float4_undef"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_float3",
        "text": "simd_float3"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_float4",
        "text": "simd_float4"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_make_float4_undef"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_make_float4_undef(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_make_float4_undef"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "other"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float3",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_float3",
              "text": "simd_float3"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float4",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_float4",
              "text": "simd_float4"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float3": {
      "abstract": [
        {
          "text": "A vector of three 32-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_float3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_float3"
        }
      ],
      "role": "symbol",
      "title": "simd_float3",
      "type": "topic",
      "url": "/documentation/simd/simd_float3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float4": {
      "abstract": [
        {
          "text": "A vector of four 32-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_float4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_float4"
        }
      ],
      "role": "symbol",
      "title": "simd_float4",
      "type": "topic",
      "url": "/documentation/simd/simd_float4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_float4(_:)-5sesp": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified 16-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_float4"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float16",
          "text": "simd_float16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float4",
          "text": "simd_float4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_float4(_:)-5sesp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_float4"
        }
      ],
      "role": "symbol",
      "title": "simd_make_float4(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_float4(_:)-5sesp"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_float4(_:)-9xll2": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified eight-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_float4"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float8",
          "text": "simd_float8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float4",
          "text": "simd_float4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_float4(_:)-9xll2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_float4"
        }
      ],
      "role": "symbol",
      "title": "simd_make_float4(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_float4(_:)-9xll2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_float4(_:)-cjxn": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_float4"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float4",
          "text": "simd_float4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float4",
          "text": "simd_float4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_float4(_:)-cjxn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_float4"
        }
      ],
      "role": "symbol",
      "title": "simd_make_float4(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_float4(_:)-cjxn"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_float4(_:)-fyse": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified three-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_float4"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float3",
          "text": "simd_float3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float4",
          "text": "simd_float4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_float4(_:)-fyse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_float4"
        }
      ],
      "role": "symbol",
      "title": "simd_make_float4(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_float4(_:)-fyse"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_float4(_:)-iuxp": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_float4"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float2",
          "text": "simd_float2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float4",
          "text": "simd_float4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_float4(_:)-iuxp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_float4"
        }
      ],
      "role": "symbol",
      "title": "simd_make_float4(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_float4(_:)-iuxp"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_float4(_:_:)-51w3j": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_float4"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float2",
          "text": "simd_float2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float2",
          "text": "simd_float2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float4",
          "text": "simd_float4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_float4(_:_:)-51w3j",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_float4"
        }
      ],
      "role": "symbol",
      "title": "simd_make_float4(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_float4(_:_:)-51w3j"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_float4_undef(_:)-3brs5": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_float4_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float2",
          "text": "simd_float2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float4",
          "text": "simd_float4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_float4_undef(_:)-3brs5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_float4_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_float4_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_float4_undef(_:)-3brs5"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_float4_undef(_:)-3f7tu": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified three-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_float4_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float3",
          "text": "simd_float3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float4",
          "text": "simd_float4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_float4_undef(_:)-3f7tu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_float4_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_float4_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_float4_undef(_:)-3f7tu"
    },
    "doc://com.apple.accelerate/documentation/simd/vector4-1op5j": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector4-1op5j",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector4",
      "type": "topic",
      "url": "/documentation/simd/vector4-1op5j"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Create-Four-Element-Vectors-From-Other-Vectors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_float4(_:)-iuxp",
        "doc://com.apple.accelerate/documentation/simd/simd_make_float4(_:)-fyse",
        "doc://com.apple.accelerate/documentation/simd/simd_make_float4(_:)-cjxn",
        "doc://com.apple.accelerate/documentation/simd/simd_make_float4(_:)-9xll2",
        "doc://com.apple.accelerate/documentation/simd/simd_make_float4(_:)-5sesp",
        "doc://com.apple.accelerate/documentation/simd/simd_make_float4(_:_:)-51w3j",
        "doc://com.apple.accelerate/documentation/simd/simd_make_float4_undef(_:)-3brs5"
      ],
      "title": "Functions to Create Four-Element Vectors From Other Vectors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "simd_make_float4_undef"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_float4_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/simd"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Functions-to-Create-Four-Element-Vectors-From-Other-Vectors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_float4(_:)-iuxp",
                "doc://com.apple.accelerate/documentation/simd/simd_make_float4(_:)-fyse",
                "doc://com.apple.accelerate/documentation/simd/simd_make_float4(_:)-cjxn",
                "doc://com.apple.accelerate/documentation/simd/simd_make_float4(_:)-9xll2",
                "doc://com.apple.accelerate/documentation/simd/simd_make_float4(_:)-5sesp",
                "doc://com.apple.accelerate/documentation/simd/simd_make_float4(_:_:)-51w3j",
                "doc://com.apple.accelerate/documentation/simd/vector4-1op5j",
                "doc://com.apple.accelerate/documentation/simd/simd_make_float4_undef(_:)-3brs5"
              ],
              "title": "Functions to Create Four-Element Vectors From Other Vectors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "static"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float4",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_float4",
                    "text": "simd_float4"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "simd_make_float4_undef"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float3",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_float3",
                    "text": "simd_float3"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "other"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_float4_undef(_:)-3f7tu/title",
          "value": "simd_make_float4_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_float4_undef(_:)-3f7tu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_float4_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float4/title",
          "value": "simd_float4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_float4(_:)-cjxn/title",
          "value": "simd_make_float4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_float4(_:)-cjxn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_float4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_float4(_:)-fyse/title",
          "value": "simd_make_float4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_float4(_:)-fyse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_float4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float3/title",
          "value": "simd_float3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_float4(_:)-iuxp/title",
          "value": "simd_make_float4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_float4(_:)-iuxp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_float4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_float4(_:)-5sesp/title",
          "value": "simd_make_float4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_float4(_:)-5sesp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_float4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_float4(_:_:)-51w3j/title",
          "value": "simd_make_float4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_float4(_:_:)-51w3j/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_float4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_float4(_:)-9xll2/title",
          "value": "simd_make_float4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_float4(_:)-9xll2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_float4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_float4_undef(_:)-3brs5/title",
          "value": "simd_make_float4_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_float4_undef(_:)-3brs5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_float4_undef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_make_float4_undef(_:)-3f7tu"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/simd/simd_make_float4_undef(_:)-3f7tu"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
