{
  "abstract": [
    {
      "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5ry5g"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_long_sat#]2l#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_long_sat"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_long_sat"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_long_sat"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_long2",
              "text": "simd_long2"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_long_sat"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_ulong2",
              "text": "simd_ulong2"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long2": {
      "abstract": [
        {
          "text": "A vector of two 64-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_long2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_long2"
        }
      ],
      "role": "symbol",
      "title": "simd_long2",
      "type": "topic",
      "url": "/documentation/simd/simd_long2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5ry5g": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5ry5g",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_long_sat-5ry5g"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5ryts": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5ryts",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_long_sat-5ryts"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5rzv0": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5rzv0",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_long_sat-5rzv0"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5s0fo": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5s0fo",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_long_sat-5s0fo"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5s0w0": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5s0w0",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_long_sat-5s0w0"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5s5sw": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5s5sw",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_long_sat-5s5sw"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5s7z8": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5s7z8",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_long_sat-5s7z8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5s900": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5s900",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_long_sat-5s900"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5sao0": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5sao0",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_long_sat-5sao0"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5sfmo": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5sfmo",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_long_sat-5sfmo"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong2": {
      "abstract": [
        {
          "text": "A vector of two 64-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ulong2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ulong2"
        }
      ],
      "role": "symbol",
      "title": "simd_ulong2",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong2"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Perform-Saturating-Conversion-From-Vectors-of-Other-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5sao0",
        "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5s0w0",
        "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5sfmo",
        "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5s5sw",
        "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5s900",
        "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5ryts",
        "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5s7z8",
        "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5rzv0",
        "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5s0fo"
      ],
      "title": "Functions to Perform Saturating Conversion From Vectors of Other Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long2/title",
          "value": "simd_long2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_long2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_long2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong2/title",
          "value": "simd_ulong2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong2"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_long_sat-5ry5g"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
