{
  "abstract": [
    {
      "text": "A matrix of two columns and three rows that contains double-precision values.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_double2x3"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@SA@simd_double2x3",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simd_double2x3"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_double2x3"
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "simd_double2x3"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_double2x3"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/double2x3": {
      "abstract": [
        {
          "text": "A type alias for a double-precision 2 x 3 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "double2x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/double2x3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "double2x3"
        }
      ],
      "role": "symbol",
      "title": "double2x3",
      "type": "topic",
      "url": "/documentation/simd/double2x3"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_double2x3": {
      "abstract": [
        {
          "text": "A type alias for a double-precision 2 x 3 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matrix_double2x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_double2x3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "matrix_double2x3"
        }
      ],
      "role": "symbol",
      "title": "matrix_double2x3",
      "type": "topic",
      "url": "/documentation/simd/matrix_double2x3"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_equal(_:_:)-52vds": {
      "abstract": [
        {
          "text": "Returns true if every element in a matrix is exactly equal to the corresponding element in a second matrix, and otherwise returns false.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matrix_equal"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double2x3",
          "text": "simd_double2x3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double2x3",
          "text": "simd_double2x3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_equal(_:_:)-52vds",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_equal(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/matrix_equal(_:_:)-52vds"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_from_columns(_:_:)-61w2n": {
      "abstract": [
        {
          "text": "Returns a new matrix with the specified columns.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matrix_from_columns"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD3V",
          "text": "SIMD3"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD3V",
          "text": "SIMD3"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double2x3",
          "text": "simd_double2x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_from_columns(_:_:)-61w2n",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_from_columns(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/matrix_from_columns(_:_:)-61w2n"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_from_rows(_:_:_:)-2ar1l": {
      "abstract": [
        {
          "text": "Returns a new matrix with the specified rows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matrix_from_rows"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD2V",
          "text": "SIMD2"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD2V",
          "text": "SIMD2"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD2V",
          "text": "SIMD2"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double2x3",
          "text": "simd_double2x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_from_rows(_:_:_:)-2ar1l",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_from_rows(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/matrix_from_rows(_:_:_:)-2ar1l"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_multiply-1lfzx": {
      "abstract": [
        {
          "text": "Returns the product of a 3 x 3 matrix and a 2 x 3 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "matrix_multiply"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_multiply-1lfzx",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_multiply",
      "type": "topic",
      "url": "/documentation/simd/matrix_multiply-1lfzx"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_multiply-2of7c": {
      "abstract": [
        {
          "text": "Returns the product of a 2 x 3 matrix and a two-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "matrix_multiply"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_multiply-2of7c",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_multiply",
      "type": "topic",
      "url": "/documentation/simd/matrix_multiply-2of7c"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_multiply-2uqmb": {
      "abstract": [
        {
          "text": "Returns the product of a 4 x 3 matrix and a 2 x 4 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "matrix_multiply"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_multiply-2uqmb",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_multiply",
      "type": "topic",
      "url": "/documentation/simd/matrix_multiply-2uqmb"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_multiply-545xs": {
      "abstract": [
        {
          "text": "Returns the product of a three-element vector and a 2 x 3 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "matrix_multiply"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_multiply-545xs",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_multiply",
      "type": "topic",
      "url": "/documentation/simd/matrix_multiply-545xs"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_multiply-5myx3": {
      "abstract": [
        {
          "text": "Returns the product of a 2 x 3 matrix and a 2 x 2 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "matrix_multiply"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_multiply-5myx3",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_multiply",
      "type": "topic",
      "url": "/documentation/simd/matrix_multiply-5myx3"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_scale-1fidi": {
      "abstract": [
        {
          "text": "Returns the product of a scalar value and a matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "matrix_scale"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_scale-1fidi",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_scale",
      "type": "topic",
      "url": "/documentation/simd/matrix_scale-1fidi"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_transpose(_:)-97k0o": {
      "abstract": [
        {
          "text": "Returns the transpose of a matrix.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matrix_transpose"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double3x2",
          "text": "simd_double3x2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:4simd9double2x3a",
          "text": "double2x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_transpose(_:)-97k0o",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_transpose(_:)",
      "type": "topic",
      "url": "/documentation/simd/matrix_transpose(_:)-97k0o"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_add-1zc96": {
      "abstract": [
        {
          "text": "Returns the sum of two matrices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_add"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_add-1zc96",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_add",
      "type": "topic",
      "url": "/documentation/simd/simd_add-1zc96"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_almost_equal_elements-crvf": {
      "abstract": [
        {
          "text": "Returns true if every element in a matrix is within a specified tolerance to the corresponding element in a second matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_almost_equal_elements"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_almost_equal_elements-crvf",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_almost_equal_elements",
      "type": "topic",
      "url": "/documentation/simd/simd_almost_equal_elements-crvf"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_almost_equal_elements_relative-2gmox": {
      "abstract": [
        {
          "text": "Returns true if every element in a matrix is within a specified double-precision relative tolerance to the corresponding element in a second matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_almost_equal_elements_relative"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_almost_equal_elements_relative-2gmox",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_almost_equal_elements_relative",
      "type": "topic",
      "url": "/documentation/simd/simd_almost_equal_elements_relative-2gmox"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double2x2": {
      "abstract": [
        {
          "text": "A matrix of two columns and two rows that contains double-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_double2x2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double2x2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_double2x2"
        }
      ],
      "role": "symbol",
      "title": "simd_double2x2",
      "type": "topic",
      "url": "/documentation/simd/simd_double2x2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double2x3": {
      "abstract": [
        {
          "text": "A matrix of two columns and three rows that contains double-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_double2x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double2x3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_double2x3"
        }
      ],
      "role": "symbol",
      "title": "simd_double2x3",
      "type": "topic",
      "url": "/documentation/simd/simd_double2x3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double2x3/*(_:_:)-26bpe": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "*"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double2x3",
          "text": "simd_double2x3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD2V",
          "text": "SIMD2"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD3V",
          "text": "SIMD3"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double2x3/*(_:_:)-26bpe",
      "kind": "symbol",
      "role": "symbol",
      "title": "*(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double2x3/*(_:_:)-26bpe"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double2x3/*(_:_:)-2qo9o": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "*"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double2x3",
          "text": "simd_double2x3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:4simd9double3x2a",
          "text": "double3x2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:4simd9double3x3a",
          "text": "double3x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double2x3/*(_:_:)-2qo9o",
      "kind": "symbol",
      "role": "symbol",
      "title": "*(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double2x3/*(_:_:)-2qo9o"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double2x3/*(_:_:)-3li3r": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "*"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double2x3",
          "text": "simd_double2x3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double2x3",
          "text": "simd_double2x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double2x3/*(_:_:)-3li3r",
      "kind": "symbol",
      "role": "symbol",
      "title": "*(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double2x3/*(_:_:)-3li3r"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double2x3/*(_:_:)-4bwlw": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "*"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double2x3",
          "text": "simd_double2x3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:4simd9double2x2a",
          "text": "double2x2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:4simd9double2x3a",
          "text": "double2x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double2x3/*(_:_:)-4bwlw",
      "kind": "symbol",
      "role": "symbol",
      "title": "*(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double2x3/*(_:_:)-4bwlw"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double2x3/*(_:_:)-559m0": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "*"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double2x3",
          "text": "simd_double2x3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double2x3",
          "text": "simd_double2x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double2x3/*(_:_:)-559m0",
      "kind": "symbol",
      "role": "symbol",
      "title": "*(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double2x3/*(_:_:)-559m0"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double2x3/*(_:_:)-8rxeu": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "*"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD3V",
          "text": "SIMD3"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double2x3",
          "text": "simd_double2x3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD2V",
          "text": "SIMD2"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double2x3/*(_:_:)-8rxeu",
      "kind": "symbol",
      "role": "symbol",
      "title": "*(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double2x3/*(_:_:)-8rxeu"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double2x3/*(_:_:)-919bm": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "*"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double2x3",
          "text": "simd_double2x3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:4simd9double4x2a",
          "text": "double4x2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:4simd9double4x3a",
          "text": "double4x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double2x3/*(_:_:)-919bm",
      "kind": "symbol",
      "role": "symbol",
      "title": "*(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double2x3/*(_:_:)-919bm"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double2x3/*=(_:_:)-3lbnh": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "*="
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "inout"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double2x3",
          "text": "simd_double2x3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:4simd9double2x2a",
          "text": "double2x2"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double2x3/*=(_:_:)-3lbnh",
      "kind": "symbol",
      "role": "symbol",
      "title": "*=(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double2x3/*=(_:_:)-3lbnh"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double2x3/*=(_:_:)-9b91z": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "*="
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "inout"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double2x3",
          "text": "simd_double2x3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double2x3/*=(_:_:)-9b91z",
      "kind": "symbol",
      "role": "symbol",
      "title": "*=(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double2x3/*=(_:_:)-9b91z"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double2x3/+(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "+"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double2x3",
          "text": "simd_double2x3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double2x3",
          "text": "simd_double2x3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double2x3",
          "text": "simd_double2x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double2x3/+(_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "+(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double2x3/+(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double2x3/+=(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "+="
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "inout"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double2x3",
          "text": "simd_double2x3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double2x3",
          "text": "simd_double2x3"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double2x3/+=(_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "+=(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double2x3/+=(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double2x3/-(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "-"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double2x3",
          "text": "simd_double2x3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double2x3",
          "text": "simd_double2x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double2x3/-(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "-(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double2x3/-(_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double2x3/-(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "-"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double2x3",
          "text": "simd_double2x3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double2x3",
          "text": "simd_double2x3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double2x3",
          "text": "simd_double2x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double2x3/-(_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "-(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double2x3/-(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double2x3/-=(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "-="
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "inout"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double2x3",
          "text": "simd_double2x3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double2x3",
          "text": "simd_double2x3"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double2x3/-=(_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "-=(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double2x3/-=(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double2x3/cmatrix": {
      "abstract": [
        {
          "text": "Returns the matrix as the corresponding C matrix type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cmatrix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double2x3",
          "text": "simd_double2x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double2x3/cmatrix",
      "kind": "symbol",
      "role": "symbol",
      "title": "cmatrix",
      "type": "topic",
      "url": "/documentation/simd/simd_double2x3/cmatrix"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double2x3/columns": {
      "abstract": [
        {
          "text": "The columns of the matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "columns"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double3",
          "text": "simd_double3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double3",
          "text": "simd_double3"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double2x3/columns",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "columns"
        }
      ],
      "role": "symbol",
      "title": "columns",
      "type": "topic",
      "url": "/documentation/simd/simd_double2x3/columns"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double2x3/init()": {
      "abstract": [
        {
          "text": "Creates a new matrix with uninitialized memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double2x3/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/simd/simd_double2x3/init()"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double2x3/init(_:)-6n7k": {
      "abstract": [
        {
          "text": "Creates a new matrix from an array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD3V",
          "text": "SIMD3"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">])"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double2x3/init(_:)-6n7k",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double2x3/init(_:)-6n7k"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double2x3/init(_:)-6xclm": {
      "abstract": [
        {
          "text": "Creates a new matrix with the specified scalar value on the main diagonal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double2x3/init(_:)-6xclm",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double2x3/init(_:)-6xclm"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double2x3/init(_:)-98rcw": {
      "abstract": [
        {
          "text": "Creates a new matrix with the specified matrix.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double2x3",
          "text": "simd_double2x3"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double2x3/init(_:)-98rcw",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double2x3/init(_:)-98rcw"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double2x3/init(_:_:)": {
      "abstract": [
        {
          "text": "Creates a new matrix with the specified vectors as columns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD3V",
          "text": "SIMD3"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD3V",
          "text": "SIMD3"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double2x3/init(_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double2x3/init(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double2x3/init(columns:)": {
      "abstract": [
        {
          "text": "Creates a new matrix with the specified columns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "columns"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double3",
          "text": "simd_double3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double3",
          "text": "simd_double3"
        },
        {
          "kind": "text",
          "text": "))"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double2x3/init(columns:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(columns:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double2x3/init(columns:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double2x3/init(diagonal:)": {
      "abstract": [
        {
          "text": "Creates a new matrix with the specified vector on the main diagonal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "diagonal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD2V",
          "text": "SIMD2"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double2x3/init(diagonal:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(diagonal:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double2x3/init(diagonal:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double2x3/init(rows:)": {
      "abstract": [
        {
          "text": "Creates a new matrix with the specified rows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rows"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD2V",
          "text": "SIMD2"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">])"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double2x3/init(rows:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rows:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double2x3/init(rows:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double2x3/subscript(_:)": {
      "abstract": [
        {
          "text": "Accesses the column at the specified position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD3V",
          "text": "SIMD3"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double2x3/subscript(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscript(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double2x3/subscript(_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double2x3/subscript(_:_:)": {
      "abstract": [
        {
          "text": "Accesses the element at the specified position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double2x3/subscript(_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscript(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double2x3/subscript(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double2x3/transpose": {
      "abstract": [
        {
          "text": "The transpose of the matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transpose"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:4simd9double3x2a",
          "text": "double3x2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double2x3/transpose",
      "kind": "symbol",
      "role": "symbol",
      "title": "transpose",
      "type": "topic",
      "url": "/documentation/simd/simd_double2x3/transpose"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double2x4": {
      "abstract": [
        {
          "text": "A matrix of two columns and four rows that contains double-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_double2x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double2x4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_double2x4"
        }
      ],
      "role": "symbol",
      "title": "simd_double2x4",
      "type": "topic",
      "url": "/documentation/simd/simd_double2x4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double3x2": {
      "abstract": [
        {
          "text": "A matrix of three columns and two rows that contains double-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_double3x2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double3x2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_double3x2"
        }
      ],
      "role": "symbol",
      "title": "simd_double3x2",
      "type": "topic",
      "url": "/documentation/simd/simd_double3x2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double3x3": {
      "abstract": [
        {
          "text": "A matrix of three columns and three rows that contains double-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_double3x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double3x3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_double3x3"
        }
      ],
      "role": "symbol",
      "title": "simd_double3x3",
      "type": "topic",
      "url": "/documentation/simd/simd_double3x3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double3x4": {
      "abstract": [
        {
          "text": "A matrix of three columns and four rows that contains double-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_double3x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double3x4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_double3x4"
        }
      ],
      "role": "symbol",
      "title": "simd_double3x4",
      "type": "topic",
      "url": "/documentation/simd/simd_double3x4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double4x2": {
      "abstract": [
        {
          "text": "A matrix of four columns and two rows that contains double-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_double4x2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4x2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_double4x2"
        }
      ],
      "role": "symbol",
      "title": "simd_double4x2",
      "type": "topic",
      "url": "/documentation/simd/simd_double4x2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double4x3": {
      "abstract": [
        {
          "text": "A matrix of four columns and three rows that contains double-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_double4x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4x3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_double4x3"
        }
      ],
      "role": "symbol",
      "title": "simd_double4x3",
      "type": "topic",
      "url": "/documentation/simd/simd_double4x3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double4x4": {
      "abstract": [
        {
          "text": "A matrix of four columns and four rows that contains double-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_double4x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4x4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_double4x4"
        }
      ],
      "role": "symbol",
      "title": "simd_double4x4",
      "type": "topic",
      "url": "/documentation/simd/simd_double4x4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_equal-9ko75": {
      "abstract": [
        {
          "text": "Returns true if every element in a matrix is exactly equal to the corresponding element in a second matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_equal"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_equal-9ko75",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_equal",
      "type": "topic",
      "url": "/documentation/simd/simd_equal-9ko75"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_linear_combination-9taxv": {
      "abstract": [
        {
          "text": "Returns the linear combination of two scalar values and two matrices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_linear_combination"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_linear_combination-9taxv",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_linear_combination",
      "type": "topic",
      "url": "/documentation/simd/simd_linear_combination-9taxv"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_matrix(_:_:)-86soe": {
      "abstract": [
        {
          "text": "Returns a new matrix with the specified columns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_matrix"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double3",
          "text": "simd_double3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double3",
          "text": "simd_double3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double2x3",
          "text": "simd_double2x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_matrix(_:_:)-86soe",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_matrix"
        }
      ],
      "role": "symbol",
      "title": "simd_matrix(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_matrix(_:_:)-86soe"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_matrix_from_rows(_:_:_:)-96jbn": {
      "abstract": [
        {
          "text": "Returns a new matrix with the specified rows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_matrix_from_rows"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double2",
          "text": "simd_double2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double2",
          "text": "simd_double2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double2",
          "text": "simd_double2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double2x3",
          "text": "simd_double2x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_matrix_from_rows(_:_:_:)-96jbn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_matrix_from_rows"
        }
      ],
      "role": "symbol",
      "title": "simd_matrix_from_rows(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_matrix_from_rows(_:_:_:)-96jbn"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_mul-194di": {
      "abstract": [
        {
          "text": "Returns the product of a 2 x 3 matrix and a 2 x 2 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_mul"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_mul-194di",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_mul",
      "type": "topic",
      "url": "/documentation/simd/simd_mul-194di"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_mul-4r4ek": {
      "abstract": [
        {
          "text": "Returns the product of a 2 x 3 matrix and a two-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_mul"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_mul-4r4ek",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_mul",
      "type": "topic",
      "url": "/documentation/simd/simd_mul-4r4ek"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_mul-4s2hh": {
      "abstract": [
        {
          "text": "Returns the product of a three-element vector and a 2 x 3 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_mul"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_mul-4s2hh",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_mul",
      "type": "topic",
      "url": "/documentation/simd/simd_mul-4s2hh"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_mul-4ymsr": {
      "abstract": [
        {
          "text": "Returns the product of a 3 x 3 matrix and a 2 x 3 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_mul"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_mul-4ymsr",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_mul",
      "type": "topic",
      "url": "/documentation/simd/simd_mul-4ymsr"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_mul-7g1h8": {
      "abstract": [
        {
          "text": "Returns the product of a scalar value and a 2 x 3 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_mul"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_mul-7g1h8",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_mul",
      "type": "topic",
      "url": "/documentation/simd/simd_mul-7g1h8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_mul-7yr3s": {
      "abstract": [
        {
          "text": "Returns the product of a 4 x 3 matrix and a 2 x 4 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_mul"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_mul-7yr3s",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_mul",
      "type": "topic",
      "url": "/documentation/simd/simd_mul-7yr3s"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_sub-6k8aw": {
      "abstract": [
        {
          "text": "Returns the difference of two matrices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_sub"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_sub-6k8aw",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_sub",
      "type": "topic",
      "url": "/documentation/simd/simd_sub-6k8aw"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_transpose-84813": {
      "abstract": [
        {
          "text": "Returns the transpose of a matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_transpose"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_transpose-84813",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_transpose",
      "type": "topic",
      "url": "/documentation/simd/simd_transpose-84813"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s8CopyableP": {
      "abstract": [
        {
          "text": "A type whose values can be implicitly or explicitly copied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8CopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Copyable",
      "type": "topic",
      "url": "/documentation/Swift/Copyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:s8CopyableP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Matrix-structures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_double2x2",
        "doc://com.apple.accelerate/documentation/simd/simd_double2x4",
        "doc://com.apple.accelerate/documentation/simd/simd_double3x2",
        "doc://com.apple.accelerate/documentation/simd/simd_double3x3",
        "doc://com.apple.accelerate/documentation/simd/simd_double3x4",
        "doc://com.apple.accelerate/documentation/simd/simd_double4x2",
        "doc://com.apple.accelerate/documentation/simd/simd_double4x3",
        "doc://com.apple.accelerate/documentation/simd/simd_double4x4"
      ],
      "title": "Matrix structures"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_double2x3/init()",
        "doc://com.apple.accelerate/documentation/simd/simd_double2x3/init(_:)-6xclm",
        "doc://com.apple.accelerate/documentation/simd/simd_double2x3/init(diagonal:)",
        "doc://com.apple.accelerate/documentation/simd/simd_double2x3/init(_:)-6n7k",
        "doc://com.apple.accelerate/documentation/simd/simd_double2x3/init(_:_:)",
        "doc://com.apple.accelerate/documentation/simd/simd_double2x3/init(columns:)",
        "doc://com.apple.accelerate/documentation/simd/simd_double2x3/init(rows:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Matrix-Properties",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_double2x3/transpose",
        "doc://com.apple.accelerate/documentation/simd/simd_double2x3/columns"
      ],
      "title": "Matrix Properties"
    },
    {
      "anchor": "Matrix-Creation-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_matrix(_:_:)-86soe",
        "doc://com.apple.accelerate/documentation/simd/simd_matrix_from_rows(_:_:_:)-96jbn",
        "doc://com.apple.accelerate/documentation/simd/matrix_from_rows(_:_:_:)-2ar1l"
      ],
      "title": "Matrix Creation Functions"
    },
    {
      "anchor": "Element-Access",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_double2x3/subscript(_:)",
        "doc://com.apple.accelerate/documentation/simd/simd_double2x3/subscript(_:_:)"
      ],
      "title": "Element Access"
    },
    {
      "anchor": "Type-Aliases",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/double2x3",
        "doc://com.apple.accelerate/documentation/simd/matrix_double2x3"
      ],
      "title": "Type Aliases"
    },
    {
      "anchor": "Deprecated-Symbols",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/matrix_equal(_:_:)-52vds",
        "doc://com.apple.accelerate/documentation/simd/matrix_from_columns(_:_:)-61w2n",
        "doc://com.apple.accelerate/documentation/simd/matrix_transpose(_:)-97k0o",
        "doc://com.apple.accelerate/documentation/simd/simd_double2x3/init(_:)-98rcw",
        "doc://com.apple.accelerate/documentation/simd/simd_double2x3/cmatrix"
      ],
      "title": "Deprecated Symbols"
    },
    {
      "anchor": "Operators",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_double2x3/*(_:_:)-26bpe",
        "doc://com.apple.accelerate/documentation/simd/simd_double2x3/*(_:_:)-2qo9o",
        "doc://com.apple.accelerate/documentation/simd/simd_double2x3/*(_:_:)-3li3r",
        "doc://com.apple.accelerate/documentation/simd/simd_double2x3/*(_:_:)-4bwlw",
        "doc://com.apple.accelerate/documentation/simd/simd_double2x3/*(_:_:)-559m0",
        "doc://com.apple.accelerate/documentation/simd/simd_double2x3/*(_:_:)-8rxeu",
        "doc://com.apple.accelerate/documentation/simd/simd_double2x3/*(_:_:)-919bm",
        "doc://com.apple.accelerate/documentation/simd/simd_double2x3/*=(_:_:)-3lbnh",
        "doc://com.apple.accelerate/documentation/simd/simd_double2x3/*=(_:_:)-9b91z",
        "doc://com.apple.accelerate/documentation/simd/simd_double2x3/+(_:_:)",
        "doc://com.apple.accelerate/documentation/simd/simd_double2x3/+=(_:_:)",
        "doc://com.apple.accelerate/documentation/simd/simd_double2x3/-(_:)",
        "doc://com.apple.accelerate/documentation/simd/simd_double2x3/-(_:_:)",
        "doc://com.apple.accelerate/documentation/simd/simd_double2x3/-=(_:_:)"
      ],
      "title": "Operators"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "simd_double2x3"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double2x3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double2x3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/simd"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Matrix-Properties",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_double2x3/columns"
              ],
              "title": "Matrix Properties"
            },
            {
              "anchor": "Matrix-Creation-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_matrix(_:_:)-86soe",
                "doc://com.apple.accelerate/documentation/simd/simd_matrix_from_rows(_:_:_:)-96jbn"
              ],
              "title": "Matrix Creation Functions"
            },
            {
              "anchor": "Math-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_add-1zc96",
                "doc://com.apple.accelerate/documentation/simd/simd_sub-6k8aw",
                "doc://com.apple.accelerate/documentation/simd/matrix_scale-1fidi"
              ],
              "title": "Math Functions"
            },
            {
              "anchor": "Matrix-Scalar-Multiplication-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_mul-7g1h8"
              ],
              "title": "Matrix-Scalar Multiplication Functions"
            },
            {
              "anchor": "Matrix-Vector-Multiplication-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_mul-4s2hh",
                "doc://com.apple.accelerate/documentation/simd/matrix_multiply-545xs",
                "doc://com.apple.accelerate/documentation/simd/simd_mul-4r4ek",
                "doc://com.apple.accelerate/documentation/simd/matrix_multiply-2of7c"
              ],
              "title": "Matrix-Vector Multiplication Functions"
            },
            {
              "anchor": "Matrix-Matrix-Multiplication-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_mul-194di",
                "doc://com.apple.accelerate/documentation/simd/matrix_multiply-5myx3",
                "doc://com.apple.accelerate/documentation/simd/simd_mul-4ymsr",
                "doc://com.apple.accelerate/documentation/simd/matrix_multiply-1lfzx",
                "doc://com.apple.accelerate/documentation/simd/simd_mul-7yr3s",
                "doc://com.apple.accelerate/documentation/simd/matrix_multiply-2uqmb"
              ],
              "title": "Matrix-Matrix Multiplication Functions"
            },
            {
              "anchor": "Equality-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_equal-9ko75",
                "doc://com.apple.accelerate/documentation/simd/simd_almost_equal_elements-crvf",
                "doc://com.apple.accelerate/documentation/simd/simd_almost_equal_elements_relative-2gmox"
              ],
              "title": "Equality Functions"
            },
            {
              "anchor": "Linear-Combination-Function",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_linear_combination-9taxv"
              ],
              "title": "Linear Combination Function"
            },
            {
              "anchor": "Transpose-Function",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_transpose-84813"
              ],
              "title": "Transpose Function"
            },
            {
              "anchor": "Type-Aliases",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/matrix_double2x3"
              ],
              "title": "Type Aliases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Matrix-structures",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_double2x2",
                "doc://com.apple.accelerate/documentation/simd/simd_double2x4",
                "doc://com.apple.accelerate/documentation/simd/simd_double3x2",
                "doc://com.apple.accelerate/documentation/simd/simd_double3x3",
                "doc://com.apple.accelerate/documentation/simd/simd_double3x4",
                "doc://com.apple.accelerate/documentation/simd/simd_double4x2",
                "doc://com.apple.accelerate/documentation/simd/simd_double4x3",
                "doc://com.apple.accelerate/documentation/simd/simd_double4x4"
              ],
              "title": "Matrix structures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "simd_double2x3"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double3x3/title",
          "value": "simd_double3x3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double3x3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double3x3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double3x3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double3x3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double3x4/title",
          "value": "simd_double3x4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double3x4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double3x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double3x4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double3x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4x3/title",
          "value": "simd_double4x3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4x3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double4x3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4x3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double4x3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_matrix_from_rows(_:_:_:)-96jbn/title",
          "value": "simd_matrix_from_rows"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_matrix_from_rows(_:_:_:)-96jbn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_matrix_from_rows"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double2x3/title",
          "value": "simd_double2x3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double2x3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double2x3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double2x3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double2x3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_matrix(_:_:)-86soe/title",
          "value": "simd_matrix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_matrix(_:_:)-86soe/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_matrix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4x2/title",
          "value": "simd_double4x2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4x2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double4x2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4x2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double4x2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double2x3~1columns/title",
          "value": "columns"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double2x3~1columns/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "columns"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double2x4/title",
          "value": "simd_double2x4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double2x4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double2x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double2x4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double2x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double2x2/title",
          "value": "simd_double2x2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double2x2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double2x2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double2x2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double2x2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4x4/title",
          "value": "simd_double4x4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4x4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double4x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4x4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double4x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1matrix_double2x3/title",
          "value": "matrix_double2x3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1matrix_double2x3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "matrix_double2x3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1matrix_double2x3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "matrix_double2x3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double3x2/title",
          "value": "simd_double3x2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double3x2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double3x2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double3x2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double3x2"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_double2x3"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/simd/simd_double2x3"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
