{
  "abstract": [
    {
      "text": "Returns the fast length of a vector.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_fast_length-5utao"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_fast_length#]8f#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_fast_length"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_fast_length"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_fast_length"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:f",
              "text": "float"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_fast_length"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float8",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_float8",
              "text": "simd_float8"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_distance-8i534": {
      "abstract": [
        {
          "text": "Returns the distance between two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_distance"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_distance-8i534",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_distance",
      "type": "topic",
      "url": "/documentation/simd/simd_distance-8i534"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_distance_squared-7gp4v": {
      "abstract": [
        {
          "text": "Returns the square of the distance between two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_distance_squared"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_distance_squared-7gp4v",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_distance_squared",
      "type": "topic",
      "url": "/documentation/simd/simd_distance_squared-7gp4v"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_fast_distance-1ml9e": {
      "abstract": [
        {
          "text": "Returns the fast distance between two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_fast_distance"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_fast_distance-1ml9e",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_fast_distance",
      "type": "topic",
      "url": "/documentation/simd/simd_fast_distance-1ml9e"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_fast_length-5utao": {
      "abstract": [
        {
          "text": "Returns the fast length of a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_fast_length"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_fast_length-5utao",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_fast_length",
      "type": "topic",
      "url": "/documentation/simd/simd_fast_length-5utao"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float8": {
      "abstract": [
        {
          "text": "A vector of eight 32-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_float8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_float8"
        }
      ],
      "role": "symbol",
      "title": "simd_float8",
      "type": "topic",
      "url": "/documentation/simd/simd_float8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_length-32wmj": {
      "abstract": [
        {
          "text": "Returns the length of a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_length"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_length-32wmj",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_length",
      "type": "topic",
      "url": "/documentation/simd/simd_length-32wmj"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_length_squared-3xa1d": {
      "abstract": [
        {
          "text": "Returns the square of the length of a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_length_squared"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_length_squared-3xa1d",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_length_squared",
      "type": "topic",
      "url": "/documentation/simd/simd_length_squared-3xa1d"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_precise_distance-9w7rx": {
      "abstract": [
        {
          "text": "Returns the precise distance between two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_precise_distance"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_precise_distance-9w7rx",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_precise_distance",
      "type": "topic",
      "url": "/documentation/simd/simd_precise_distance-9w7rx"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_precise_length-67kmm": {
      "abstract": [
        {
          "text": "Returns the precise length of a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_precise_length"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_precise_length-67kmm",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_precise_length",
      "type": "topic",
      "url": "/documentation/simd/simd_precise_length-67kmm"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Length-and-Distance-Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_length-32wmj",
        "doc://com.apple.accelerate/documentation/simd/simd_precise_length-67kmm",
        "doc://com.apple.accelerate/documentation/simd/simd_length_squared-3xa1d",
        "doc://com.apple.accelerate/documentation/simd/simd_distance-8i534",
        "doc://com.apple.accelerate/documentation/simd/simd_fast_distance-1ml9e",
        "doc://com.apple.accelerate/documentation/simd/simd_precise_distance-9w7rx",
        "doc://com.apple.accelerate/documentation/simd/simd_distance_squared-7gp4v"
      ],
      "title": "Length and Distance Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float8/title",
          "value": "simd_float8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float8"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_fast_length-5utao"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
