{
  "abstract": [
    {
      "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_ulong-1iz4u"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_ulong#]4f#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_ulong"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_ulong"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_ulong"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong4",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_ulong4",
              "text": "simd_ulong4"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_ulong"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float4",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_float4",
              "text": "simd_float4"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float4": {
      "abstract": [
        {
          "text": "A vector of four 32-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_float4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_float4"
        }
      ],
      "role": "symbol",
      "title": "simd_float4",
      "type": "topic",
      "url": "/documentation/simd/simd_float4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong-1ixkm": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong-1ixkm",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong-1ixkm"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong-1iykq": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong-1iykq",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong-1iykq"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong-1iz4u": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong-1iz4u",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong-1iz4u"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong-1izlu": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong-1izlu",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong-1izlu"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong-1j0ve": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong-1j0ve",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong-1j0ve"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong-1j2ly": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong-1j2ly",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong-1j2ly"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong-1j7li": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong-1j7li",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong-1j7li"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong-1j9du": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong-1j9du",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong-1j9du"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong-1jazu": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong-1jazu",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong-1jazu"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong-1jcja": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong-1jcja",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong-1jcja"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong4": {
      "abstract": [
        {
          "text": "A vector of four 64-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ulong4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ulong4"
        }
      ],
      "role": "symbol",
      "title": "simd_ulong4",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong4"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Create-Four-Element-Vectors-From-Vectors-of-Other-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_ulong-1j7li",
        "doc://com.apple.accelerate/documentation/simd/simd_ulong-1ixkm",
        "doc://com.apple.accelerate/documentation/simd/simd_ulong-1jcja",
        "doc://com.apple.accelerate/documentation/simd/simd_ulong-1j2ly",
        "doc://com.apple.accelerate/documentation/simd/simd_ulong-1j9du",
        "doc://com.apple.accelerate/documentation/simd/simd_ulong-1izlu",
        "doc://com.apple.accelerate/documentation/simd/simd_ulong-1jazu",
        "doc://com.apple.accelerate/documentation/simd/simd_ulong-1j0ve",
        "doc://com.apple.accelerate/documentation/simd/simd_ulong-1iykq"
      ],
      "title": "Functions to Create Four-Element Vectors From Vectors of Other Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong4/title",
          "value": "simd_ulong4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float4/title",
          "value": "simd_float4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float4"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_ulong-1iz4u"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
