{
  "abstract": [
    {
      "text": "A matrix of two columns and four rows that contains single-precision values.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_float2x4"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@SA@simd_float2x4",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simd_float2x4"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_float2x4"
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "simd_float2x4"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_float2x4"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/float2x4": {
      "abstract": [
        {
          "text": "A type alias for a single-precision 2 x 4 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "float2x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/float2x4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "float2x4"
        }
      ],
      "role": "symbol",
      "title": "float2x4",
      "type": "topic",
      "url": "/documentation/simd/float2x4"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_equal(_:_:)-34fuu": {
      "abstract": [
        {
          "text": "Returns true if every element in a matrix is exactly equal to the corresponding element in a second matrix, and otherwise returns false.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matrix_equal"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float2x4",
          "text": "simd_float2x4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float2x4",
          "text": "simd_float2x4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_equal(_:_:)-34fuu",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_equal(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/matrix_equal(_:_:)-34fuu"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_float2x4": {
      "abstract": [
        {
          "text": "A type alias for a single-precision 2 x 4 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matrix_float2x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_float2x4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "matrix_float2x4"
        }
      ],
      "role": "symbol",
      "title": "matrix_float2x4",
      "type": "topic",
      "url": "/documentation/simd/matrix_float2x4"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_from_columns(_:_:)-6tvfl": {
      "abstract": [
        {
          "text": "Returns a new matrix with the specified columns.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matrix_from_columns"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD4V",
          "text": "SIMD4"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD4V",
          "text": "SIMD4"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float2x4",
          "text": "simd_float2x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_from_columns(_:_:)-6tvfl",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_from_columns(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/matrix_from_columns(_:_:)-6tvfl"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_from_rows(_:_:_:_:)-51dz4": {
      "abstract": [
        {
          "text": "Returns a new matrix with the specified rows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matrix_from_rows"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD2V",
          "text": "SIMD2"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD2V",
          "text": "SIMD2"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD2V",
          "text": "SIMD2"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD2V",
          "text": "SIMD2"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float2x4",
          "text": "simd_float2x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_from_rows(_:_:_:_:)-51dz4",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_from_rows(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/matrix_from_rows(_:_:_:_:)-51dz4"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_multiply-20lvz": {
      "abstract": [
        {
          "text": "Returns the product of a 4 x 4 matrix and a 2 x 4 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "matrix_multiply"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_multiply-20lvz",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_multiply",
      "type": "topic",
      "url": "/documentation/simd/matrix_multiply-20lvz"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_multiply-55lia": {
      "abstract": [
        {
          "text": "Returns the product of a 2 x 4 matrix and a two-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "matrix_multiply"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_multiply-55lia",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_multiply",
      "type": "topic",
      "url": "/documentation/simd/matrix_multiply-55lia"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_multiply-5mq06": {
      "abstract": [
        {
          "text": "Returns the product of a 3 x 4 matrix and a 2 x 3 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "matrix_multiply"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_multiply-5mq06",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_multiply",
      "type": "topic",
      "url": "/documentation/simd/matrix_multiply-5mq06"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_multiply-6pu5f": {
      "abstract": [
        {
          "text": "Returns the product of a 2 x 4 matrix and a 2 x 1 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "matrix_multiply"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_multiply-6pu5f",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_multiply",
      "type": "topic",
      "url": "/documentation/simd/matrix_multiply-6pu5f"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_multiply-pq7f": {
      "abstract": [
        {
          "text": "Returns the product of a four-element vector and a 2 x 4 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "matrix_multiply"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_multiply-pq7f",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_multiply",
      "type": "topic",
      "url": "/documentation/simd/matrix_multiply-pq7f"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_scale-1imr2": {
      "abstract": [
        {
          "text": "Returns the product of a scalar value and a matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "matrix_scale"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_scale-1imr2",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_scale",
      "type": "topic",
      "url": "/documentation/simd/matrix_scale-1imr2"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_transpose(_:)-5ymlr": {
      "abstract": [
        {
          "text": "Returns the transpose of a matrix.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matrix_transpose"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float4x2",
          "text": "simd_float4x2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:4simd8float2x4a",
          "text": "float2x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_transpose(_:)-5ymlr",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_transpose(_:)",
      "type": "topic",
      "url": "/documentation/simd/matrix_transpose(_:)-5ymlr"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_add-8r5kq": {
      "abstract": [
        {
          "text": "Returns the sum of two matrices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_add"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_add-8r5kq",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_add",
      "type": "topic",
      "url": "/documentation/simd/simd_add-8r5kq"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_almost_equal_elements-9t9wk": {
      "abstract": [
        {
          "text": "Returns true if every element in a matrix is within a specified tolerance to the corresponding element in a second matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_almost_equal_elements"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_almost_equal_elements-9t9wk",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_almost_equal_elements",
      "type": "topic",
      "url": "/documentation/simd/simd_almost_equal_elements-9t9wk"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_almost_equal_elements_relative-8geix": {
      "abstract": [
        {
          "text": "Returns true if every element in a matrix is within a specified single-precision relative tolerance to the corresponding element in a second matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_almost_equal_elements_relative"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_almost_equal_elements_relative-8geix",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_almost_equal_elements_relative",
      "type": "topic",
      "url": "/documentation/simd/simd_almost_equal_elements_relative-8geix"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_equal-6e7pf": {
      "abstract": [
        {
          "text": "Returns true if every element in a matrix is exactly equal to the corresponding element in a second matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_equal"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_equal-6e7pf",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_equal",
      "type": "topic",
      "url": "/documentation/simd/simd_equal-6e7pf"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float2x2": {
      "abstract": [
        {
          "text": "A matrix of two columns and two rows that contains single-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_float2x2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float2x2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_float2x2"
        }
      ],
      "role": "symbol",
      "title": "simd_float2x2",
      "type": "topic",
      "url": "/documentation/simd/simd_float2x2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float2x3": {
      "abstract": [
        {
          "text": "A matrix of two columns and three rows that contains single-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_float2x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float2x3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_float2x3"
        }
      ],
      "role": "symbol",
      "title": "simd_float2x3",
      "type": "topic",
      "url": "/documentation/simd/simd_float2x3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float2x4": {
      "abstract": [
        {
          "text": "A matrix of two columns and four rows that contains single-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_float2x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float2x4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_float2x4"
        }
      ],
      "role": "symbol",
      "title": "simd_float2x4",
      "type": "topic",
      "url": "/documentation/simd/simd_float2x4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float2x4/*(_:_:)-10gif": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "*"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD4V",
          "text": "SIMD4"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float2x4",
          "text": "simd_float2x4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD2V",
          "text": "SIMD2"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float2x4/*(_:_:)-10gif",
      "kind": "symbol",
      "role": "symbol",
      "title": "*(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_float2x4/*(_:_:)-10gif"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float2x4/*(_:_:)-239o8": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "*"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float2x4",
          "text": "simd_float2x4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:4simd8float2x2a",
          "text": "float2x2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:4simd8float2x4a",
          "text": "float2x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float2x4/*(_:_:)-239o8",
      "kind": "symbol",
      "role": "symbol",
      "title": "*(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_float2x4/*(_:_:)-239o8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float2x4/*(_:_:)-35xo4": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "*"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float2x4",
          "text": "simd_float2x4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:4simd8float4x2a",
          "text": "float4x2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:4simd8float4x4a",
          "text": "float4x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float2x4/*(_:_:)-35xo4",
      "kind": "symbol",
      "role": "symbol",
      "title": "*(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_float2x4/*(_:_:)-35xo4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float2x4/*(_:_:)-3x5jg": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "*"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float2x4",
          "text": "simd_float2x4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float2x4",
          "text": "simd_float2x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float2x4/*(_:_:)-3x5jg",
      "kind": "symbol",
      "role": "symbol",
      "title": "*(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_float2x4/*(_:_:)-3x5jg"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float2x4/*(_:_:)-4clgl": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "*"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float2x4",
          "text": "simd_float2x4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD2V",
          "text": "SIMD2"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD4V",
          "text": "SIMD4"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float2x4/*(_:_:)-4clgl",
      "kind": "symbol",
      "role": "symbol",
      "title": "*(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_float2x4/*(_:_:)-4clgl"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float2x4/*(_:_:)-7gnvu": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "*"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float2x4",
          "text": "simd_float2x4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float2x4",
          "text": "simd_float2x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float2x4/*(_:_:)-7gnvu",
      "kind": "symbol",
      "role": "symbol",
      "title": "*(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_float2x4/*(_:_:)-7gnvu"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float2x4/*(_:_:)-7ypgr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "*"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float2x4",
          "text": "simd_float2x4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:4simd8float3x2a",
          "text": "float3x2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:4simd8float3x4a",
          "text": "float3x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float2x4/*(_:_:)-7ypgr",
      "kind": "symbol",
      "role": "symbol",
      "title": "*(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_float2x4/*(_:_:)-7ypgr"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float2x4/*=(_:_:)-6u2a": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "*="
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "inout"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float2x4",
          "text": "simd_float2x4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:4simd8float2x2a",
          "text": "float2x2"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float2x4/*=(_:_:)-6u2a",
      "kind": "symbol",
      "role": "symbol",
      "title": "*=(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_float2x4/*=(_:_:)-6u2a"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float2x4/*=(_:_:)-jfkv": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "*="
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "inout"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float2x4",
          "text": "simd_float2x4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float2x4/*=(_:_:)-jfkv",
      "kind": "symbol",
      "role": "symbol",
      "title": "*=(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_float2x4/*=(_:_:)-jfkv"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float2x4/+(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "+"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float2x4",
          "text": "simd_float2x4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float2x4",
          "text": "simd_float2x4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float2x4",
          "text": "simd_float2x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float2x4/+(_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "+(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_float2x4/+(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float2x4/+=(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "+="
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "inout"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float2x4",
          "text": "simd_float2x4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float2x4",
          "text": "simd_float2x4"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float2x4/+=(_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "+=(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_float2x4/+=(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float2x4/-(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "-"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float2x4",
          "text": "simd_float2x4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float2x4",
          "text": "simd_float2x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float2x4/-(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "-(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_float2x4/-(_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float2x4/-(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "-"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float2x4",
          "text": "simd_float2x4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float2x4",
          "text": "simd_float2x4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float2x4",
          "text": "simd_float2x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float2x4/-(_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "-(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_float2x4/-(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float2x4/-=(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "-="
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "inout"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float2x4",
          "text": "simd_float2x4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float2x4",
          "text": "simd_float2x4"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float2x4/-=(_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "-=(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_float2x4/-=(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float2x4/cmatrix": {
      "abstract": [
        {
          "text": "Returns the matrix as the corresponding C matrix type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cmatrix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float2x4",
          "text": "simd_float2x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float2x4/cmatrix",
      "kind": "symbol",
      "role": "symbol",
      "title": "cmatrix",
      "type": "topic",
      "url": "/documentation/simd/simd_float2x4/cmatrix"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float2x4/columns": {
      "abstract": [
        {
          "text": "The columns of the matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "columns"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float4",
          "text": "simd_float4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float4",
          "text": "simd_float4"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float2x4/columns",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "columns"
        }
      ],
      "role": "symbol",
      "title": "columns",
      "type": "topic",
      "url": "/documentation/simd/simd_float2x4/columns"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float2x4/init()": {
      "abstract": [
        {
          "text": "Creates a new matrix with uninitialized memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float2x4/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/simd/simd_float2x4/init()"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float2x4/init(_:)-3teag": {
      "abstract": [
        {
          "text": "Creates a new matrix with the specified matrix.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float2x4",
          "text": "simd_float2x4"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float2x4/init(_:)-3teag",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_float2x4/init(_:)-3teag"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float2x4/init(_:)-hvkr": {
      "abstract": [
        {
          "text": "Creates a new matrix from an array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD4V",
          "text": "SIMD4"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">])"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float2x4/init(_:)-hvkr",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_float2x4/init(_:)-hvkr"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float2x4/init(_:)-smdg": {
      "abstract": [
        {
          "text": "Creates a new matrix with the specified scalar value on the main diagonal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float2x4/init(_:)-smdg",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_float2x4/init(_:)-smdg"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float2x4/init(_:_:)": {
      "abstract": [
        {
          "text": "Creates a new matrix with the specified vectors as columns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD4V",
          "text": "SIMD4"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD4V",
          "text": "SIMD4"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float2x4/init(_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_float2x4/init(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float2x4/init(columns:)": {
      "abstract": [
        {
          "text": "Creates a new matrix with the specified columns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "columns"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float4",
          "text": "simd_float4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float4",
          "text": "simd_float4"
        },
        {
          "kind": "text",
          "text": "))"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float2x4/init(columns:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(columns:)",
      "type": "topic",
      "url": "/documentation/simd/simd_float2x4/init(columns:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float2x4/init(diagonal:)": {
      "abstract": [
        {
          "text": "Creates a new matrix with the specified vector on the main diagonal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "diagonal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD2V",
          "text": "SIMD2"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float2x4/init(diagonal:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(diagonal:)",
      "type": "topic",
      "url": "/documentation/simd/simd_float2x4/init(diagonal:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float2x4/init(rows:)": {
      "abstract": [
        {
          "text": "Creates a new matrix with the specified rows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rows"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD2V",
          "text": "SIMD2"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">])"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float2x4/init(rows:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rows:)",
      "type": "topic",
      "url": "/documentation/simd/simd_float2x4/init(rows:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float2x4/subscript(_:)": {
      "abstract": [
        {
          "text": "Accesses the column at the specified position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD4V",
          "text": "SIMD4"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float2x4/subscript(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscript(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_float2x4/subscript(_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float2x4/subscript(_:_:)": {
      "abstract": [
        {
          "text": "Accesses the element at the specified position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float2x4/subscript(_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscript(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_float2x4/subscript(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float2x4/transpose": {
      "abstract": [
        {
          "text": "The transpose of the matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transpose"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:4simd8float4x2a",
          "text": "float4x2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float2x4/transpose",
      "kind": "symbol",
      "role": "symbol",
      "title": "transpose",
      "type": "topic",
      "url": "/documentation/simd/simd_float2x4/transpose"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float3x2": {
      "abstract": [
        {
          "text": "A matrix of three columns and two rows that contains single-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_float3x2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float3x2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_float3x2"
        }
      ],
      "role": "symbol",
      "title": "simd_float3x2",
      "type": "topic",
      "url": "/documentation/simd/simd_float3x2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float3x3": {
      "abstract": [
        {
          "text": "A matrix of three columns and three rows that contains single-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_float3x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float3x3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_float3x3"
        }
      ],
      "role": "symbol",
      "title": "simd_float3x3",
      "type": "topic",
      "url": "/documentation/simd/simd_float3x3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float3x4": {
      "abstract": [
        {
          "text": "A matrix of three columns and four rows that contains single-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_float3x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float3x4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_float3x4"
        }
      ],
      "role": "symbol",
      "title": "simd_float3x4",
      "type": "topic",
      "url": "/documentation/simd/simd_float3x4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float4x2": {
      "abstract": [
        {
          "text": "A matrix of four columns and two rows that contains single-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_float4x2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float4x2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_float4x2"
        }
      ],
      "role": "symbol",
      "title": "simd_float4x2",
      "type": "topic",
      "url": "/documentation/simd/simd_float4x2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float4x3": {
      "abstract": [
        {
          "text": "A matrix of four columns and three rows that contains single-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_float4x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float4x3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_float4x3"
        }
      ],
      "role": "symbol",
      "title": "simd_float4x3",
      "type": "topic",
      "url": "/documentation/simd/simd_float4x3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float4x4": {
      "abstract": [
        {
          "text": "A matrix of four columns and four rows that contains single-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_float4x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float4x4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_float4x4"
        }
      ],
      "role": "symbol",
      "title": "simd_float4x4",
      "type": "topic",
      "url": "/documentation/simd/simd_float4x4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_linear_combination-5m3zf": {
      "abstract": [
        {
          "text": "Returns the linear combination of two scalar values and two matrices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_linear_combination"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_linear_combination-5m3zf",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_linear_combination",
      "type": "topic",
      "url": "/documentation/simd/simd_linear_combination-5m3zf"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_matrix(_:_:)-7ayva": {
      "abstract": [
        {
          "text": "Returns a new matrix with the specified columns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_matrix"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float4",
          "text": "simd_float4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float4",
          "text": "simd_float4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float2x4",
          "text": "simd_float2x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_matrix(_:_:)-7ayva",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_matrix"
        }
      ],
      "role": "symbol",
      "title": "simd_matrix(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_matrix(_:_:)-7ayva"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_matrix_from_rows(_:_:_:_:)-7s7pv": {
      "abstract": [
        {
          "text": "Returns a new matrix with the specified rows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_matrix_from_rows"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float2",
          "text": "simd_float2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float2",
          "text": "simd_float2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float2",
          "text": "simd_float2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float2",
          "text": "simd_float2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float2x4",
          "text": "simd_float2x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_matrix_from_rows(_:_:_:_:)-7s7pv",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_matrix_from_rows"
        }
      ],
      "role": "symbol",
      "title": "simd_matrix_from_rows(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_matrix_from_rows(_:_:_:_:)-7s7pv"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_mul-31xd0": {
      "abstract": [
        {
          "text": "Returns the product of a 4 x 4 matrix and a 2 x 4 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_mul"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_mul-31xd0",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_mul",
      "type": "topic",
      "url": "/documentation/simd/simd_mul-31xd0"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_mul-5fjl0": {
      "abstract": [
        {
          "text": "Returns the product of a four-element vector and a 2 x 4 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_mul"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_mul-5fjl0",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_mul",
      "type": "topic",
      "url": "/documentation/simd/simd_mul-5fjl0"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_mul-65z85": {
      "abstract": [
        {
          "text": "Returns the product of a 2 x 4 matrix and a 2 x 1 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_mul"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_mul-65z85",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_mul",
      "type": "topic",
      "url": "/documentation/simd/simd_mul-65z85"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_mul-6xn9": {
      "abstract": [
        {
          "text": "Returns the product of a scalar value and a 2 x 4 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_mul"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_mul-6xn9",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_mul",
      "type": "topic",
      "url": "/documentation/simd/simd_mul-6xn9"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_mul-9rkxm": {
      "abstract": [
        {
          "text": "Returns the product of a 3 x 4 matrix and a 2 x 3 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_mul"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_mul-9rkxm",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_mul",
      "type": "topic",
      "url": "/documentation/simd/simd_mul-9rkxm"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_mul-9tdcy": {
      "abstract": [
        {
          "text": "Returns the product of a 2 x 4 matrix and a two-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_mul"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_mul-9tdcy",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_mul",
      "type": "topic",
      "url": "/documentation/simd/simd_mul-9tdcy"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_sub-6idm9": {
      "abstract": [
        {
          "text": "Returns the difference of two matrices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_sub"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_sub-6idm9",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_sub",
      "type": "topic",
      "url": "/documentation/simd/simd_sub-6idm9"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_transpose-53s98": {
      "abstract": [
        {
          "text": "Returns the transpose of a matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_transpose"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_transpose-53s98",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_transpose",
      "type": "topic",
      "url": "/documentation/simd/simd_transpose-53s98"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s8CopyableP": {
      "abstract": [
        {
          "text": "A type whose values can be implicitly or explicitly copied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8CopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Copyable",
      "type": "topic",
      "url": "/documentation/Swift/Copyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:s8CopyableP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Matrix-structures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_float2x2",
        "doc://com.apple.accelerate/documentation/simd/simd_float2x3",
        "doc://com.apple.accelerate/documentation/simd/simd_float3x2",
        "doc://com.apple.accelerate/documentation/simd/simd_float3x3",
        "doc://com.apple.accelerate/documentation/simd/simd_float3x4",
        "doc://com.apple.accelerate/documentation/simd/simd_float4x2",
        "doc://com.apple.accelerate/documentation/simd/simd_float4x3",
        "doc://com.apple.accelerate/documentation/simd/simd_float4x4"
      ],
      "title": "Matrix structures"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_float2x4/init()",
        "doc://com.apple.accelerate/documentation/simd/simd_float2x4/init(_:)-smdg",
        "doc://com.apple.accelerate/documentation/simd/simd_float2x4/init(diagonal:)",
        "doc://com.apple.accelerate/documentation/simd/simd_float2x4/init(_:)-hvkr",
        "doc://com.apple.accelerate/documentation/simd/simd_float2x4/init(_:_:)",
        "doc://com.apple.accelerate/documentation/simd/simd_float2x4/init(columns:)",
        "doc://com.apple.accelerate/documentation/simd/simd_float2x4/init(rows:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Matrix-Properties",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_float2x4/transpose",
        "doc://com.apple.accelerate/documentation/simd/simd_float2x4/columns"
      ],
      "title": "Matrix Properties"
    },
    {
      "anchor": "Matrix-Creation-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_matrix(_:_:)-7ayva",
        "doc://com.apple.accelerate/documentation/simd/simd_matrix_from_rows(_:_:_:_:)-7s7pv",
        "doc://com.apple.accelerate/documentation/simd/matrix_from_rows(_:_:_:_:)-51dz4"
      ],
      "title": "Matrix Creation Functions"
    },
    {
      "anchor": "Element-Access",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_float2x4/subscript(_:)",
        "doc://com.apple.accelerate/documentation/simd/simd_float2x4/subscript(_:_:)"
      ],
      "title": "Element Access"
    },
    {
      "anchor": "Type-Aliases",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/float2x4",
        "doc://com.apple.accelerate/documentation/simd/matrix_float2x4"
      ],
      "title": "Type Aliases"
    },
    {
      "anchor": "Deprecated-Symbols",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/matrix_from_columns(_:_:)-6tvfl",
        "doc://com.apple.accelerate/documentation/simd/matrix_equal(_:_:)-34fuu",
        "doc://com.apple.accelerate/documentation/simd/matrix_transpose(_:)-5ymlr",
        "doc://com.apple.accelerate/documentation/simd/simd_float2x4/init(_:)-3teag",
        "doc://com.apple.accelerate/documentation/simd/simd_float2x4/cmatrix"
      ],
      "title": "Deprecated Symbols"
    },
    {
      "anchor": "Operators",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_float2x4/*(_:_:)-10gif",
        "doc://com.apple.accelerate/documentation/simd/simd_float2x4/*(_:_:)-239o8",
        "doc://com.apple.accelerate/documentation/simd/simd_float2x4/*(_:_:)-35xo4",
        "doc://com.apple.accelerate/documentation/simd/simd_float2x4/*(_:_:)-3x5jg",
        "doc://com.apple.accelerate/documentation/simd/simd_float2x4/*(_:_:)-4clgl",
        "doc://com.apple.accelerate/documentation/simd/simd_float2x4/*(_:_:)-7gnvu",
        "doc://com.apple.accelerate/documentation/simd/simd_float2x4/*(_:_:)-7ypgr",
        "doc://com.apple.accelerate/documentation/simd/simd_float2x4/*=(_:_:)-6u2a",
        "doc://com.apple.accelerate/documentation/simd/simd_float2x4/*=(_:_:)-jfkv",
        "doc://com.apple.accelerate/documentation/simd/simd_float2x4/+(_:_:)",
        "doc://com.apple.accelerate/documentation/simd/simd_float2x4/+=(_:_:)",
        "doc://com.apple.accelerate/documentation/simd/simd_float2x4/-(_:)",
        "doc://com.apple.accelerate/documentation/simd/simd_float2x4/-(_:_:)",
        "doc://com.apple.accelerate/documentation/simd/simd_float2x4/-=(_:_:)"
      ],
      "title": "Operators"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "simd_float2x4"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float2x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float2x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/simd"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Matrix-Properties",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_float2x4/columns"
              ],
              "title": "Matrix Properties"
            },
            {
              "anchor": "Matrix-Creation-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_matrix(_:_:)-7ayva",
                "doc://com.apple.accelerate/documentation/simd/simd_matrix_from_rows(_:_:_:_:)-7s7pv"
              ],
              "title": "Matrix Creation Functions"
            },
            {
              "anchor": "Math-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_add-8r5kq",
                "doc://com.apple.accelerate/documentation/simd/simd_sub-6idm9",
                "doc://com.apple.accelerate/documentation/simd/matrix_scale-1imr2"
              ],
              "title": "Math Functions"
            },
            {
              "anchor": "Matrix-Scalar-Multiplication-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_mul-6xn9"
              ],
              "title": "Matrix-Scalar Multiplication Functions"
            },
            {
              "anchor": "Matrix-Vector-Multiplication-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_mul-5fjl0",
                "doc://com.apple.accelerate/documentation/simd/matrix_multiply-pq7f",
                "doc://com.apple.accelerate/documentation/simd/simd_mul-9tdcy",
                "doc://com.apple.accelerate/documentation/simd/matrix_multiply-55lia"
              ],
              "title": "Matrix-Vector Multiplication Functions"
            },
            {
              "anchor": "Matrix-Matrix-Multiplication-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_mul-65z85",
                "doc://com.apple.accelerate/documentation/simd/matrix_multiply-6pu5f",
                "doc://com.apple.accelerate/documentation/simd/simd_mul-9rkxm",
                "doc://com.apple.accelerate/documentation/simd/matrix_multiply-5mq06",
                "doc://com.apple.accelerate/documentation/simd/simd_mul-31xd0",
                "doc://com.apple.accelerate/documentation/simd/matrix_multiply-20lvz"
              ],
              "title": "Matrix-Matrix Multiplication Functions"
            },
            {
              "anchor": "Equality-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_equal-6e7pf",
                "doc://com.apple.accelerate/documentation/simd/simd_almost_equal_elements-9t9wk",
                "doc://com.apple.accelerate/documentation/simd/simd_almost_equal_elements_relative-8geix"
              ],
              "title": "Equality Functions"
            },
            {
              "anchor": "Linear-Combination-Function",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_linear_combination-5m3zf"
              ],
              "title": "Linear Combination Function"
            },
            {
              "anchor": "Transpose-Function",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_transpose-53s98"
              ],
              "title": "Transpose Function"
            },
            {
              "anchor": "Type-Aliases",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/matrix_float2x4"
              ],
              "title": "Type Aliases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Matrix-structures",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_float2x2",
                "doc://com.apple.accelerate/documentation/simd/simd_float2x3",
                "doc://com.apple.accelerate/documentation/simd/simd_float3x2",
                "doc://com.apple.accelerate/documentation/simd/simd_float3x3",
                "doc://com.apple.accelerate/documentation/simd/simd_float3x4",
                "doc://com.apple.accelerate/documentation/simd/simd_float4x2",
                "doc://com.apple.accelerate/documentation/simd/simd_float4x3",
                "doc://com.apple.accelerate/documentation/simd/simd_float4x4"
              ],
              "title": "Matrix structures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "simd_float2x4"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float3x2/title",
          "value": "simd_float3x2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float3x2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float3x2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float3x2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float3x2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float2x2/title",
          "value": "simd_float2x2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float2x2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float2x2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float2x2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float2x2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float4x2/title",
          "value": "simd_float4x2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float4x2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float4x2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float4x2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float4x2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float2x3/title",
          "value": "simd_float2x3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float2x3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float2x3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float2x3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float2x3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_matrix_from_rows(_:_:_:_:)-7s7pv/title",
          "value": "simd_matrix_from_rows"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_matrix_from_rows(_:_:_:_:)-7s7pv/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_matrix_from_rows"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float3x4/title",
          "value": "simd_float3x4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float3x4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float3x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float3x4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float3x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1matrix_float2x4/title",
          "value": "matrix_float2x4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1matrix_float2x4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "matrix_float2x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1matrix_float2x4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "matrix_float2x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float2x4/title",
          "value": "simd_float2x4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float2x4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float2x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float2x4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float2x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_matrix(_:_:)-7ayva/title",
          "value": "simd_matrix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_matrix(_:_:)-7ayva/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_matrix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float4x4/title",
          "value": "simd_float4x4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float4x4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float4x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float4x4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float4x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float2x4~1columns/title",
          "value": "columns"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float2x4~1columns/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "columns"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float3x3/title",
          "value": "simd_float3x3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float3x3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float3x3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float3x3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float3x3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float4x3/title",
          "value": "simd_float4x3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float4x3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float4x3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float4x3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float4x3"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_float2x4"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/simd/simd_float2x4"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
