{
  "abstract": [
    {
      "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kk9d"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_ushort_sat#]3L#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_ushort_sat"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_ushort_sat"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_ushort_sat"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort3",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_ushort3",
              "text": "simd_ushort3"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_ushort_sat"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long3",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_long3",
              "text": "simd_long3"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long3": {
      "abstract": [
        {
          "text": "A vector of three 64-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_long3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_long3"
        }
      ],
      "role": "symbol",
      "title": "simd_long3",
      "type": "topic",
      "url": "/documentation/simd/simd_long3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort3": {
      "abstract": [
        {
          "text": "A vector of three 16-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ushort3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ushort3"
        }
      ],
      "role": "symbol",
      "title": "simd_ushort3",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kapv": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kapv",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-7kapv"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kfoj": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kfoj",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-7kfoj"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kipj": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kipj",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-7kipj"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kk9d": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kk9d",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-7kk9d"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kkoz": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kkoz",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-7kkoz"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kpib": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kpib",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-7kpib"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kr89": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kr89",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-7kr89"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kroh": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kroh",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-7kroh"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kstz": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kstz",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-7kstz"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kuc1": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kuc1",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-7kuc1"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Perform-Saturating-Conversion-From-Vectors-of-Other-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kfoj",
        "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kpib",
        "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kapv",
        "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kkoz",
        "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kipj",
        "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kstz",
        "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kuc1",
        "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kr89",
        "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kroh"
      ],
      "title": "Functions to Perform Saturating Conversion From Vectors of Other Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort3/title",
          "value": "simd_ushort3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long3/title",
          "value": "simd_long3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_long3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_long3"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_ushort_sat-7kk9d"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
