{
  "abstract": [
    {
      "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_long-4ay3"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_long#]2c#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_long"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_long"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_long"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_long2",
              "text": "simd_long2"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_long"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_uchar2",
              "text": "simd_uchar2"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long-3w3v": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long-3w3v",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long",
      "type": "topic",
      "url": "/documentation/simd/simd_long-3w3v"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long-3xox": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long-3xox",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long",
      "type": "topic",
      "url": "/documentation/simd/simd_long-3xox"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long-3z5r": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long-3z5r",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long",
      "type": "topic",
      "url": "/documentation/simd/simd_long-3z5r"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long-410r": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long-410r",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long",
      "type": "topic",
      "url": "/documentation/simd/simd_long-410r"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long-462z": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long-462z",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long",
      "type": "topic",
      "url": "/documentation/simd/simd_long-462z"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long-47o1": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long-47o1",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long",
      "type": "topic",
      "url": "/documentation/simd/simd_long-47o1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long-49a7": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long-49a7",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long",
      "type": "topic",
      "url": "/documentation/simd/simd_long-49a7"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long-49c1": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long-49c1",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long",
      "type": "topic",
      "url": "/documentation/simd/simd_long-49c1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long-4a75": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long-4a75",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long",
      "type": "topic",
      "url": "/documentation/simd/simd_long-4a75"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long-4ay3": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long-4ay3",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long",
      "type": "topic",
      "url": "/documentation/simd/simd_long-4ay3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long2": {
      "abstract": [
        {
          "text": "A vector of two 64-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_long2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_long2"
        }
      ],
      "role": "symbol",
      "title": "simd_long2",
      "type": "topic",
      "url": "/documentation/simd/simd_long2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar2": {
      "abstract": [
        {
          "text": "A vector of two 8-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uchar2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uchar2"
        }
      ],
      "role": "symbol",
      "title": "simd_uchar2",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar2"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Create-Two-Element-Vectors-From-Vectors-of-Other-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_long-410r",
        "doc://com.apple.accelerate/documentation/simd/simd_long-3w3v",
        "doc://com.apple.accelerate/documentation/simd/simd_long-462z",
        "doc://com.apple.accelerate/documentation/simd/simd_long-3z5r",
        "doc://com.apple.accelerate/documentation/simd/simd_long-49a7",
        "doc://com.apple.accelerate/documentation/simd/simd_long-3xox",
        "doc://com.apple.accelerate/documentation/simd/simd_long-47o1",
        "doc://com.apple.accelerate/documentation/simd/simd_long-49c1",
        "doc://com.apple.accelerate/documentation/simd/simd_long-4a75"
      ],
      "title": "Functions to Create Two-Element Vectors From Vectors of Other Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long2/title",
          "value": "simd_long2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_long2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_long2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar2/title",
          "value": "simd_uchar2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar2"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_long-4ay3"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
