{
  "abstract": [
    {
      "text": "Returns a new vector from the specified two-element vector, and other elements set to zero.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:)-1e906"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_make_ushort8#]2s#",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simd_make_ushort8"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_ushort2",
        "text": "simd_ushort2"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_ushort8",
        "text": "simd_ushort8"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_make_ushort8"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_make_ushort8(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_make_ushort8"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "other"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_ushort2",
              "text": "simd_ushort2"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort8",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_ushort8",
              "text": "simd_ushort8"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:)-17t38": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified four-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort4",
          "text": "simd_ushort4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort8",
          "text": "simd_ushort8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:)-17t38",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort8(_:)-17t38"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:)-1e906": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort2",
          "text": "simd_ushort2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort8",
          "text": "simd_ushort8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:)-1e906",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort8(_:)-1e906"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:)-1henz": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified three-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort3",
          "text": "simd_ushort3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort8",
          "text": "simd_ushort8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:)-1henz",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort8(_:)-1henz"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:)-2e4yw": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort8",
          "text": "simd_ushort8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort8",
          "text": "simd_ushort8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:)-2e4yw",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort8(_:)-2e4yw"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:)-4t9gk": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified thrity two-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort32",
          "text": "simd_ushort32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort8",
          "text": "simd_ushort8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:)-4t9gk",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort8(_:)-4t9gk"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:)-5yzvk": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified sixteen-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort16",
          "text": "simd_ushort16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort8",
          "text": "simd_ushort8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:)-5yzvk",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort8(_:)-5yzvk"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort4",
          "text": "simd_ushort4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort4",
          "text": "simd_ushort4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort8",
          "text": "simd_ushort8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort8(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort8(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8_undef(_:)-416aa": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified four-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort8_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort4",
          "text": "simd_ushort4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort8",
          "text": "simd_ushort8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8_undef(_:)-416aa",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort8_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort8_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort8_undef(_:)-416aa"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8_undef(_:)-46lw9": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified three-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort8_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort3",
          "text": "simd_ushort3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort8",
          "text": "simd_ushort8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8_undef(_:)-46lw9",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort8_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort8_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort8_undef(_:)-46lw9"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8_undef(_:)-49rg0": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort8_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort2",
          "text": "simd_ushort2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort8",
          "text": "simd_ushort8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8_undef(_:)-49rg0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort8_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort8_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort8_undef(_:)-49rg0"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort2": {
      "abstract": [
        {
          "text": "A vector of two 16-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ushort2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ushort2"
        }
      ],
      "role": "symbol",
      "title": "simd_ushort2",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort8": {
      "abstract": [
        {
          "text": "A vector of eight 16-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ushort8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ushort8"
        }
      ],
      "role": "symbol",
      "title": "simd_ushort8",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort8"
    },
    "doc://com.apple.accelerate/documentation/simd/vector8-411sw": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector8-411sw",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector8",
      "type": "topic",
      "url": "/documentation/simd/vector8-411sw"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Create-Eight-Element-Vectors-From-Other-Vectors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:)-1henz",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:)-17t38",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:)-2e4yw",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:)-5yzvk",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:)-4t9gk",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:_:)",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8_undef(_:)-49rg0",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8_undef(_:)-46lw9",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8_undef(_:)-416aa"
      ],
      "title": "Functions to Create Eight-Element Vectors From Other Vectors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "simd_make_ushort8"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/simd"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Functions-to-Create-Eight-Element-Vectors-From-Other-Vectors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:)-1henz",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:)-17t38",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:)-2e4yw",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:)-5yzvk",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:)-4t9gk",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:_:)",
                "doc://com.apple.accelerate/documentation/simd/vector8-411sw",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8_undef(_:)-49rg0",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8_undef(_:)-46lw9",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8_undef(_:)-416aa"
              ],
              "title": "Functions to Create Eight-Element Vectors From Other Vectors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "static"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort8",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_ushort8",
                    "text": "simd_ushort8"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "simd_make_ushort8"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort2",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_ushort2",
                    "text": "simd_ushort2"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "other"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort8_undef(_:)-49rg0/title",
          "value": "simd_make_ushort8_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort8_undef(_:)-49rg0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort8_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort8(_:)-2e4yw/title",
          "value": "simd_make_ushort8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort8(_:)-2e4yw/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort8_undef(_:)-46lw9/title",
          "value": "simd_make_ushort8_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort8_undef(_:)-46lw9/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort8_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort8(_:)-5yzvk/title",
          "value": "simd_make_ushort8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort8(_:)-5yzvk/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort8(_:)-4t9gk/title",
          "value": "simd_make_ushort8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort8(_:)-4t9gk/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort8(_:)-17t38/title",
          "value": "simd_make_ushort8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort8(_:)-17t38/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort8(_:)-1e906/title",
          "value": "simd_make_ushort8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort8(_:)-1e906/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort8_undef(_:)-416aa/title",
          "value": "simd_make_ushort8_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort8_undef(_:)-416aa/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort8_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort8/title",
          "value": "simd_ushort8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort8(_:_:)/title",
          "value": "simd_make_ushort8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort8(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort8(_:)-1henz/title",
          "value": "simd_make_ushort8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort8(_:)-1henz/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort2/title",
          "value": "simd_ushort2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort2"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_make_ushort8(_:)-1e906"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/simd/simd_make_ushort8(_:)-1e906"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
