{
  "abstract": [
    {
      "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_short-6zn74"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_short#]8i#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_short"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_short"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_short"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short8",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_short8",
              "text": "simd_short8"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_short"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint8",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_uint8",
              "text": "simd_uint8"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short-6zn74": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short-6zn74",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short",
      "type": "topic",
      "url": "/documentation/simd/simd_short-6zn74"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short-6zo8c": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short-6zo8c",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short",
      "type": "topic",
      "url": "/documentation/simd/simd_short-6zo8c"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short-6zqew": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short-6zqew",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short",
      "type": "topic",
      "url": "/documentation/simd/simd_short-6zqew"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short-6zqvg": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short-6zqvg",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short",
      "type": "topic",
      "url": "/documentation/simd/simd_short-6zqvg"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short-6zrfo": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short-6zrfo",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short",
      "type": "topic",
      "url": "/documentation/simd/simd_short-6zrfo"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short-6zvaw": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short-6zvaw",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short",
      "type": "topic",
      "url": "/documentation/simd/simd_short-6zvaw"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short-6zxf4": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short-6zxf4",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short",
      "type": "topic",
      "url": "/documentation/simd/simd_short-6zxf4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short-6zy24": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short-6zy24",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short",
      "type": "topic",
      "url": "/documentation/simd/simd_short-6zy24"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short-7008o": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short-7008o",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short",
      "type": "topic",
      "url": "/documentation/simd/simd_short-7008o"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short-705iw": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short-705iw",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short",
      "type": "topic",
      "url": "/documentation/simd/simd_short-705iw"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short8": {
      "abstract": [
        {
          "text": "A vector of eight 16-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_short8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_short8"
        }
      ],
      "role": "symbol",
      "title": "simd_short8",
      "type": "topic",
      "url": "/documentation/simd/simd_short8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint8": {
      "abstract": [
        {
          "text": "A vector of eight 32-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uint8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uint8"
        }
      ],
      "role": "symbol",
      "title": "simd_uint8",
      "type": "topic",
      "url": "/documentation/simd/simd_uint8"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Create-Eight-Element-Vectors-From-Vectors-of-Other-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_short-7008o",
        "doc://com.apple.accelerate/documentation/simd/simd_short-6zqew",
        "doc://com.apple.accelerate/documentation/simd/simd_short-705iw",
        "doc://com.apple.accelerate/documentation/simd/simd_short-6zvaw",
        "doc://com.apple.accelerate/documentation/simd/simd_short-6zxf4",
        "doc://com.apple.accelerate/documentation/simd/simd_short-6zy24",
        "doc://com.apple.accelerate/documentation/simd/simd_short-6zo8c",
        "doc://com.apple.accelerate/documentation/simd/simd_short-6zrfo",
        "doc://com.apple.accelerate/documentation/simd/simd_short-6zqvg"
      ],
      "title": "Functions to Create Eight-Element Vectors From Vectors of Other Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint8/title",
          "value": "simd_uint8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uint8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uint8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short8/title",
          "value": "simd_short8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short8"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_short-6zn74"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
