{
  "abstract": [
    {
      "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-ncn5"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_uint_sat#]3C#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_uint_sat"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_uint_sat"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_uint_sat"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint3",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_uint3",
              "text": "simd_uint3"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_uint_sat"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char3",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_char3",
              "text": "simd_char3"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char3": {
      "abstract": [
        {
          "text": "A vector of three 8-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_char3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_char3"
        }
      ],
      "role": "symbol",
      "title": "simd_char3",
      "type": "topic",
      "url": "/documentation/simd/simd_char3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint3": {
      "abstract": [
        {
          "text": "A vector of three 32-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uint3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uint3"
        }
      ],
      "role": "symbol",
      "title": "simd_uint3",
      "type": "topic",
      "url": "/documentation/simd/simd_uint3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-n2o1": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uint_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-n2o1",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uint_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uint_sat-n2o1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-n3iz": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uint_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-n3iz",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uint_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uint_sat-n3iz"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-n44n": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uint_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-n44n",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uint_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uint_sat-n44n"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-n5op": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uint_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-n5op",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uint_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uint_sat-n5op"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-n6qf": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uint_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-n6qf",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uint_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uint_sat-n6qf"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-n7q9": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uint_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-n7q9",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uint_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uint_sat-n7q9"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-ncn5": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uint_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-ncn5",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uint_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uint_sat-ncn5"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-nfrd": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uint_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-nfrd",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uint_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uint_sat-nfrd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-ngif": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uint_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-ngif",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uint_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uint_sat-ngif"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-nhgh": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uint_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-nhgh",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uint_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uint_sat-nhgh"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Perform-Saturating-Conversion-From-Vectors-of-Other-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-n2o1",
        "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-nhgh",
        "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-n7q9",
        "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-nfrd",
        "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-n5op",
        "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-ngif",
        "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-n6qf",
        "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-n3iz",
        "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-n44n"
      ],
      "title": "Functions to Perform Saturating Conversion From Vectors of Other Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char3/title",
          "value": "simd_char3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint3/title",
          "value": "simd_uint3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uint3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uint3"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_uint_sat-ncn5"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
