{
  "abstract": [
    {
      "text": "Returns the reciprocal square root of each element in a vector.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_rsqrt(_:)-okw0"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_rsqrt#]2f#",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simd_rsqrt"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_float2",
        "text": "simd_float2"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_float2",
        "text": "simd_float2"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_rsqrt"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_rsqrt(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_rsqrt"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "x"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_float2",
              "text": "simd_float2"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_float2",
              "text": "simd_float2"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/recip(_:)-2opi": {
      "abstract": [
        {
          "text": "Returns the reciprocal of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recip"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD2V",
          "text": "SIMD2"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD2V",
          "text": "SIMD2"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/recip(_:)-2opi",
      "kind": "symbol",
      "role": "symbol",
      "title": "recip(_:)",
      "type": "topic",
      "url": "/documentation/simd/recip(_:)-2opi"
    },
    "doc://com.apple.accelerate/documentation/simd/rsqrt(_:)-1er1q": {
      "abstract": [
        {
          "text": "Returns the reciprocal square root of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rsqrt"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD2V",
          "text": "SIMD2"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD2V",
          "text": "SIMD2"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/rsqrt(_:)-1er1q",
      "kind": "symbol",
      "role": "symbol",
      "title": "rsqrt(_:)",
      "type": "topic",
      "url": "/documentation/simd/rsqrt(_:)-1er1q"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_fast_recip(_:)-ll5x": {
      "abstract": [
        {
          "text": "Returns the fast reciprocal of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_fast_recip"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float2",
          "text": "simd_float2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float2",
          "text": "simd_float2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_fast_recip(_:)-ll5x",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_fast_recip"
        }
      ],
      "role": "symbol",
      "title": "simd_fast_recip(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_fast_recip(_:)-ll5x"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_fast_rsqrt(_:)-84cs6": {
      "abstract": [
        {
          "text": "Returns the fast reciprocal square root of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_fast_rsqrt"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float2",
          "text": "simd_float2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float2",
          "text": "simd_float2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_fast_rsqrt(_:)-84cs6",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_fast_rsqrt"
        }
      ],
      "role": "symbol",
      "title": "simd_fast_rsqrt(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_fast_rsqrt(_:)-84cs6"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float2": {
      "abstract": [
        {
          "text": "A vector of two 32-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_float2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_float2"
        }
      ],
      "role": "symbol",
      "title": "simd_float2",
      "type": "topic",
      "url": "/documentation/simd/simd_float2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_precise_recip(_:)-66mt8": {
      "abstract": [
        {
          "text": "Returns the precise reciprocal of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_precise_recip"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float2",
          "text": "simd_float2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float2",
          "text": "simd_float2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_precise_recip(_:)-66mt8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_precise_recip"
        }
      ],
      "role": "symbol",
      "title": "simd_precise_recip(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_precise_recip(_:)-66mt8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_precise_rsqrt(_:)-wqzu": {
      "abstract": [
        {
          "text": "Returns the precise reciprocal square root of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_precise_rsqrt"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float2",
          "text": "simd_float2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float2",
          "text": "simd_float2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_precise_rsqrt(_:)-wqzu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_precise_rsqrt"
        }
      ],
      "role": "symbol",
      "title": "simd_precise_rsqrt(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_precise_rsqrt(_:)-wqzu"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_recip(_:)-8nf6c": {
      "abstract": [
        {
          "text": "Returns the reciprocal of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_recip"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float2",
          "text": "simd_float2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float2",
          "text": "simd_float2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_recip(_:)-8nf6c",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_recip"
        }
      ],
      "role": "symbol",
      "title": "simd_recip(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_recip(_:)-8nf6c"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_rsqrt(_:)-okw0": {
      "abstract": [
        {
          "text": "Returns the reciprocal square root of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_rsqrt"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float2",
          "text": "simd_float2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float2",
          "text": "simd_float2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_rsqrt(_:)-okw0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_rsqrt"
        }
      ],
      "role": "symbol",
      "title": "simd_rsqrt(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_rsqrt(_:)-okw0"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reciprocal-and-Reciprocal-Square-Root-Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_recip(_:)-8nf6c",
        "doc://com.apple.accelerate/documentation/simd/recip(_:)-2opi",
        "doc://com.apple.accelerate/documentation/simd/rsqrt(_:)-1er1q",
        "doc://com.apple.accelerate/documentation/simd/simd_precise_recip(_:)-66mt8",
        "doc://com.apple.accelerate/documentation/simd/simd_precise_rsqrt(_:)-wqzu",
        "doc://com.apple.accelerate/documentation/simd/simd_fast_recip(_:)-ll5x",
        "doc://com.apple.accelerate/documentation/simd/simd_fast_rsqrt(_:)-84cs6"
      ],
      "title": "Reciprocal and Reciprocal Square Root Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "simd_rsqrt"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_rsqrt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/simd"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reciprocal-and-Reciprocal-Square-Root-Functions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_recip(_:)-8nf6c",
                "doc://com.apple.accelerate/documentation/simd/simd_precise_recip(_:)-66mt8",
                "doc://com.apple.accelerate/documentation/simd/simd_precise_rsqrt(_:)-wqzu",
                "doc://com.apple.accelerate/documentation/simd/simd_fast_recip(_:)-ll5x",
                "doc://com.apple.accelerate/documentation/simd/simd_fast_rsqrt(_:)-84cs6"
              ],
              "title": "Reciprocal and Reciprocal Square Root Functions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "static"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float2",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_float2",
                    "text": "simd_float2"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "simd_rsqrt"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float2",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_float2",
                    "text": "simd_float2"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "x"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_fast_rsqrt(_:)-84cs6/title",
          "value": "simd_fast_rsqrt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_fast_rsqrt(_:)-84cs6/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_fast_rsqrt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_recip(_:)-8nf6c/title",
          "value": "simd_recip"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_recip(_:)-8nf6c/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_recip"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_precise_recip(_:)-66mt8/title",
          "value": "simd_precise_recip"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_precise_recip(_:)-66mt8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_precise_recip"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float2/title",
          "value": "simd_float2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_precise_rsqrt(_:)-wqzu/title",
          "value": "simd_precise_rsqrt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_precise_rsqrt(_:)-wqzu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_precise_rsqrt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_rsqrt(_:)-okw0/title",
          "value": "simd_rsqrt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_rsqrt(_:)-okw0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_rsqrt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_fast_recip(_:)-ll5x/title",
          "value": "simd_fast_recip"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_fast_recip(_:)-ll5x/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_fast_recip"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_rsqrt(_:)-okw0"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/simd/simd_rsqrt(_:)-okw0"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
