{
  "abstract": [
    {
      "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_uchar-91b82"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_uchar#]2s#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_uchar"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_uchar"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_uchar"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_uchar2",
              "text": "simd_uchar2"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_uchar"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_ushort2",
              "text": "simd_ushort2"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar-911ci": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar-911ci",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar-911ci"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar-912hq": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar-912hq",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar-912hq"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar-9134u": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar-9134u",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar-9134u"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar-916c2": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar-916c2",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar-916c2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar-91b82": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar-91b82",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar-91b82"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar-91c9q": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar-91c9q",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar-91c9q"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar-91db2": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar-91db2",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar-91db2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar-91eym": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar-91eym",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar-91eym"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar-91fhm": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar-91fhm",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar-91fhm"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar-91gia": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar-91gia",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar-91gia"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar2": {
      "abstract": [
        {
          "text": "A vector of two 8-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uchar2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uchar2"
        }
      ],
      "role": "symbol",
      "title": "simd_uchar2",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort2": {
      "abstract": [
        {
          "text": "A vector of two 16-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ushort2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ushort2"
        }
      ],
      "role": "symbol",
      "title": "simd_ushort2",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort2"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Create-Two-Element-Vectors-From-Vectors-of-Other-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_uchar-916c2",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar-91gia",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar-911ci",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar-9134u",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar-91db2",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar-912hq",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar-91c9q",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar-91fhm",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar-91eym"
      ],
      "title": "Functions to Create Two-Element Vectors From Vectors of Other Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort2/title",
          "value": "simd_ushort2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar2/title",
          "value": "simd_uchar2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar2"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_uchar-91b82"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
