{
  "abstract": [
    {
      "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6weo6"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_int_sat#]3C#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_int_sat"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_int_sat"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_int_sat"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int3",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_int3",
              "text": "simd_int3"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_int_sat"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char3",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_char3",
              "text": "simd_char3"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char3": {
      "abstract": [
        {
          "text": "A vector of three 8-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_char3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_char3"
        }
      ],
      "role": "symbol",
      "title": "simd_char3",
      "type": "topic",
      "url": "/documentation/simd/simd_char3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int3": {
      "abstract": [
        {
          "text": "A vector of three 32-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_int3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_int3"
        }
      ],
      "role": "symbol",
      "title": "simd_int3",
      "type": "topic",
      "url": "/documentation/simd/simd_int3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6vzom": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6vzom",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_int_sat-6vzom"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6w3aa": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6w3aa",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_int_sat-6w3aa"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6w3v2": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6w3v2",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_int_sat-6w3v2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6w4w6": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6w4w6",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_int_sat-6w4w6"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6w5ki": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6w5ki",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_int_sat-6w5ki"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6w6m2": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6w6m2",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_int_sat-6w6m2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6w9t2": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6w9t2",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_int_sat-6w9t2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6weo6": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6weo6",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_int_sat-6weo6"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6wfsi": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6wfsi",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_int_sat-6wfsi"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6wgfu": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6wgfu",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_int_sat-6wgfu"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Perform-Saturating-Conversion-From-Vectors-of-Other-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6w4w6",
        "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6w9t2",
        "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6vzom",
        "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6wgfu",
        "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6w6m2",
        "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6wfsi",
        "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6w5ki",
        "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6w3v2",
        "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6w3aa"
      ],
      "title": "Functions to Perform Saturating Conversion From Vectors of Other Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int3/title",
          "value": "simd_int3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_int3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_int3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char3/title",
          "value": "simd_char3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char3"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_int_sat-6weo6"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
