{
  "abstract": [
    {
      "text": "Returns the dot product of two vectors.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_dot-z7ab"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_dot#]16f#S0_#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_dot"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_dot"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_dot"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:f",
              "text": "float"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_dot"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float16",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_float16",
              "text": "simd_float16"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float16",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_float16",
              "text": "simd_float16"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__y"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_dot-z7ab": {
      "abstract": [
        {
          "text": "Returns the dot product of two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_dot"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_dot-z7ab",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_dot",
      "type": "topic",
      "url": "/documentation/simd/simd_dot-z7ab"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_fast_normalize-fjva": {
      "abstract": [
        {
          "text": "Returns the fast normalized vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_fast_normalize"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_fast_normalize-fjva",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_fast_normalize",
      "type": "topic",
      "url": "/documentation/simd/simd_fast_normalize-fjva"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_fast_project-4kt3u": {
      "abstract": [
        {
          "text": "Returns the fast projected vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_fast_project"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_fast_project-4kt3u",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_fast_project",
      "type": "topic",
      "url": "/documentation/simd/simd_fast_project-4kt3u"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float16": {
      "abstract": [
        {
          "text": "A vector of sixteen 32-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_float16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_float16"
        }
      ],
      "role": "symbol",
      "title": "simd_float16",
      "type": "topic",
      "url": "/documentation/simd/simd_float16"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_normalize-3r4t9": {
      "abstract": [
        {
          "text": "Returns a vector pointing in the same direction of the supplied vector, with a length of 1.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_normalize"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_normalize-3r4t9",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_normalize",
      "type": "topic",
      "url": "/documentation/simd/simd_normalize-3r4t9"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_precise_normalize-53f8a": {
      "abstract": [
        {
          "text": "Returns the precise normalized vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_precise_normalize"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_precise_normalize-53f8a",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_precise_normalize",
      "type": "topic",
      "url": "/documentation/simd/simd_precise_normalize-53f8a"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_precise_project-39090": {
      "abstract": [
        {
          "text": "Returns the precise projected vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_precise_project"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_precise_project-39090",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_precise_project",
      "type": "topic",
      "url": "/documentation/simd/simd_precise_project-39090"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_project-4ofki": {
      "abstract": [
        {
          "text": "Returns the first vector projected onto the second vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_project"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_project-4ofki",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_project",
      "type": "topic",
      "url": "/documentation/simd/simd_project-4ofki"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Geometry-Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_project-4ofki",
        "doc://com.apple.accelerate/documentation/simd/simd_fast_project-4kt3u",
        "doc://com.apple.accelerate/documentation/simd/simd_precise_project-39090",
        "doc://com.apple.accelerate/documentation/simd/simd_normalize-3r4t9",
        "doc://com.apple.accelerate/documentation/simd/simd_fast_normalize-fjva",
        "doc://com.apple.accelerate/documentation/simd/simd_precise_normalize-53f8a"
      ],
      "title": "Geometry Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float16/title",
          "value": "simd_float16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float16/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float16"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_dot-z7ab"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
