{
  "abstract": [
    {
      "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3g9id"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_short_sat#]4c#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_short_sat"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_short_sat"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_short_sat"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short4",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_short4",
              "text": "simd_short4"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_short_sat"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar4",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_uchar4",
              "text": "simd_uchar4"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short4": {
      "abstract": [
        {
          "text": "A vector of four 16-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_short4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_short4"
        }
      ],
      "role": "symbol",
      "title": "simd_short4",
      "type": "topic",
      "url": "/documentation/simd/simd_short4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3g4p1": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3g4p1",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_short_sat-3g4p1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3g9id": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3g9id",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_short_sat-3g9id"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3ganz": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3ganz",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_short_sat-3ganz"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3gb7n": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3gb7n",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_short_sat-3gb7n"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3gblp": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3gblp",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_short_sat-3gblp"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3gcwv": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3gcwv",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_short_sat-3gcwv"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3geh1": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3geh1",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_short_sat-3geh1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3gjfp": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3gjfp",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_short_sat-3gjfp"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3glj1": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3glj1",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_short_sat-3glj1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3gn33": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3gn33",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_short_sat-3gn33"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar4": {
      "abstract": [
        {
          "text": "A vector of four 8-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uchar4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uchar4"
        }
      ],
      "role": "symbol",
      "title": "simd_uchar4",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar4"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Perform-Saturating-Conversion-From-Vectors-of-Other-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3gjfp",
        "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3geh1",
        "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3g4p1",
        "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3glj1",
        "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3gblp",
        "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3gn33",
        "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3gcwv",
        "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3gb7n",
        "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3ganz"
      ],
      "title": "Functions to Perform Saturating Conversion From Vectors of Other Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar4/title",
          "value": "simd_uchar4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short4/title",
          "value": "simd_short4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short4"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_short_sat-3g9id"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
