{
  "abstract": [
    {
      "text": "Returns a new vector from the specified vector of 32-bit, unsigned-integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_half-2ukun"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_half#]2i#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_half"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_half"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_half"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_half2",
              "text": "simd_half2"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_half"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_uint2",
              "text": "simd_uint2"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half-2u7u3": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_half"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half-2u7u3",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_half",
      "type": "topic",
      "url": "/documentation/simd/simd_half-2u7u3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half-2ub2n": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_half"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half-2ub2n",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_half",
      "type": "topic",
      "url": "/documentation/simd/simd_half-2ub2n"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half-2uco9": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_half"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half-2uco9",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_half",
      "type": "topic",
      "url": "/documentation/simd/simd_half-2uco9"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half-2ucqz": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_half"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half-2ucqz",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_half",
      "type": "topic",
      "url": "/documentation/simd/simd_half-2ucqz"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half-2uhrf": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_half"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half-2uhrf",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_half",
      "type": "topic",
      "url": "/documentation/simd/simd_half-2uhrf"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half-2ujap": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_half"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half-2ujap",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_half",
      "type": "topic",
      "url": "/documentation/simd/simd_half-2ujap"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half-2ujxl": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_half"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half-2ujxl",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_half",
      "type": "topic",
      "url": "/documentation/simd/simd_half-2ujxl"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half-2ukun": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_half"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half-2ukun",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_half",
      "type": "topic",
      "url": "/documentation/simd/simd_half-2ukun"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half-2ulcx": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_half"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half-2ulcx",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_half",
      "type": "topic",
      "url": "/documentation/simd/simd_half-2ulcx"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half-2umll": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_half"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half-2umll",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_half",
      "type": "topic",
      "url": "/documentation/simd/simd_half-2umll"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half-2umx7": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_half"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half-2umx7",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_half",
      "type": "topic",
      "url": "/documentation/simd/simd_half-2umx7"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half2": {
      "abstract": [
        {
          "text": "A vector of two 16-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_half2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_half2"
        }
      ],
      "role": "symbol",
      "title": "simd_half2",
      "type": "topic",
      "url": "/documentation/simd/simd_half2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint2": {
      "abstract": [
        {
          "text": "A vector of two 32-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uint2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uint2"
        }
      ],
      "role": "symbol",
      "title": "simd_uint2",
      "type": "topic",
      "url": "/documentation/simd/simd_uint2"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-create-two-element-vectors-from-vectors-of-other-types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_half-2u7u3",
        "doc://com.apple.accelerate/documentation/simd/simd_half-2uhrf",
        "doc://com.apple.accelerate/documentation/simd/simd_half-2ucqz",
        "doc://com.apple.accelerate/documentation/simd/simd_half-2umx7",
        "doc://com.apple.accelerate/documentation/simd/simd_half-2ub2n",
        "doc://com.apple.accelerate/documentation/simd/simd_half-2uco9",
        "doc://com.apple.accelerate/documentation/simd/simd_half-2umll",
        "doc://com.apple.accelerate/documentation/simd/simd_half-2ulcx",
        "doc://com.apple.accelerate/documentation/simd/simd_half-2ujap",
        "doc://com.apple.accelerate/documentation/simd/simd_half-2ujxl"
      ],
      "title": "Functions to create two-element vectors from vectors of other types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half2/title",
          "value": "simd_half2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint2/title",
          "value": "simd_uint2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uint2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uint2"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_half-2ukun"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
