{
  "abstract": [
    {
      "text": "Returns a new matrix with the specified rows.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_matrix_from_rows(_:_:_:_:)-31gpp"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_matrix_from_rows#]4h#S0_#S0_#S0_#",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simd_matrix_from_rows"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_half4",
        "text": "simd_half4"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_half4",
        "text": "simd_half4"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_half4",
        "text": "simd_half4"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_half4",
        "text": "simd_half4"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@simd_half4x4",
        "text": "simd_half4x4"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_matrix_from_rows"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_matrix_from_rows(_:_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_matrix_from_rows"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "row0"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half4",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_half4",
              "text": "simd_half4"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "row1"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half4",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_half4",
              "text": "simd_half4"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "row2"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half4",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_half4",
              "text": "simd_half4"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "row3"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half4",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_half4",
              "text": "simd_half4"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half4x4",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@simd_half4x4",
              "text": "simd_half4x4"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_diagonal_matrix-2l1as": {
      "abstract": [
        {
          "text": "Returns a new matrix with the specified vector on the main diagonal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_diagonal_matrix"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_diagonal_matrix-2l1as",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_diagonal_matrix",
      "type": "topic",
      "url": "/documentation/simd/simd_diagonal_matrix-2l1as"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half4": {
      "abstract": [
        {
          "text": "A vector of four 16-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_half4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_half4"
        }
      ],
      "role": "symbol",
      "title": "simd_half4",
      "type": "topic",
      "url": "/documentation/simd/simd_half4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half4x4": {
      "abstract": [
        {
          "text": "A matrix of four columns and four rows that contains half-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_half4x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half4x4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_half4x4"
        }
      ],
      "role": "symbol",
      "title": "simd_half4x4",
      "type": "topic",
      "url": "/documentation/simd/simd_half4x4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_matrix(_:_:_:_:)-7ltt0": {
      "abstract": [
        {
          "text": "Returns a new matrix with the specified columns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_matrix"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half4",
          "text": "simd_half4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half4",
          "text": "simd_half4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half4",
          "text": "simd_half4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half4",
          "text": "simd_half4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_half4x4",
          "text": "simd_half4x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_matrix(_:_:_:_:)-7ltt0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_matrix"
        }
      ],
      "role": "symbol",
      "title": "simd_matrix(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_matrix(_:_:_:_:)-7ltt0"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_matrix_from_rows(_:_:_:_:)-31gpp": {
      "abstract": [
        {
          "text": "Returns a new matrix with the specified rows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_matrix_from_rows"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half4",
          "text": "simd_half4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half4",
          "text": "simd_half4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half4",
          "text": "simd_half4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half4",
          "text": "simd_half4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_half4x4",
          "text": "simd_half4x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_matrix_from_rows(_:_:_:_:)-31gpp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_matrix_from_rows"
        }
      ],
      "role": "symbol",
      "title": "simd_matrix_from_rows(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_matrix_from_rows(_:_:_:_:)-31gpp"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Matrix-creation-functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_matrix(_:_:_:_:)-7ltt0"
      ],
      "title": "Matrix creation functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "simd_matrix_from_rows"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_matrix_from_rows"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/simd"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Matrix-creation-functions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_matrix(_:_:_:_:)-7ltt0",
                "doc://com.apple.accelerate/documentation/simd/simd_diagonal_matrix-2l1as"
              ],
              "title": "Matrix creation functions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "static"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half4x4",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@SA@simd_half4x4",
                    "text": "simd_half4x4"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "simd_matrix_from_rows"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half4",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_half4",
                    "text": "simd_half4"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "row0"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half4",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_half4",
                    "text": "simd_half4"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "row1"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half4",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_half4",
                    "text": "simd_half4"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "row2"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half4",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_half4",
                    "text": "simd_half4"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "row3"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_matrix(_:_:_:_:)-7ltt0/title",
          "value": "simd_matrix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_matrix(_:_:_:_:)-7ltt0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_matrix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half4/title",
          "value": "simd_half4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half4x4/title",
          "value": "simd_half4x4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half4x4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half4x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half4x4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half4x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_matrix_from_rows(_:_:_:_:)-31gpp/title",
          "value": "simd_matrix_from_rows"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_matrix_from_rows(_:_:_:_:)-31gpp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_matrix_from_rows"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_matrix_from_rows(_:_:_:_:)-31gpp"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/simd/simd_matrix_from_rows(_:_:_:_:)-31gpp"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
