{
  "abstract": [
    {
      "text": "Returns the product of a 4 x 2 matrix and a four-element vector.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_mul-8l982"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_mul#$@SA@simd_float4x2#]4f#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_mul"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_mul"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_mul"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_float2",
              "text": "simd_float2"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_mul"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float4x2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@simd_float4x2",
              "text": "simd_float4x2"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float4",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_float4",
              "text": "simd_float4"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__y"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_multiply-3vw6i": {
      "abstract": [
        {
          "text": "Returns the product of a 4 x 2 matrix and a four-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "matrix_multiply"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_multiply-3vw6i",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_multiply",
      "type": "topic",
      "url": "/documentation/simd/matrix_multiply-3vw6i"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_multiply-52sa": {
      "abstract": [
        {
          "text": "Returns the product of a two-element vector and a 4 x 2 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "matrix_multiply"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_multiply-52sa",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_multiply",
      "type": "topic",
      "url": "/documentation/simd/matrix_multiply-52sa"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float2": {
      "abstract": [
        {
          "text": "A vector of two 32-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_float2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_float2"
        }
      ],
      "role": "symbol",
      "title": "simd_float2",
      "type": "topic",
      "url": "/documentation/simd/simd_float2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float4": {
      "abstract": [
        {
          "text": "A vector of four 32-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_float4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_float4"
        }
      ],
      "role": "symbol",
      "title": "simd_float4",
      "type": "topic",
      "url": "/documentation/simd/simd_float4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float4x2": {
      "abstract": [
        {
          "text": "A matrix of four columns and two rows that contains single-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_float4x2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float4x2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_float4x2"
        }
      ],
      "role": "symbol",
      "title": "simd_float4x2",
      "type": "topic",
      "url": "/documentation/simd/simd_float4x2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_mul-8l982": {
      "abstract": [
        {
          "text": "Returns the product of a 4 x 2 matrix and a four-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_mul"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_mul-8l982",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_mul",
      "type": "topic",
      "url": "/documentation/simd/simd_mul-8l982"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_mul-9yzel": {
      "abstract": [
        {
          "text": "Returns the product of a two-element vector and a 4 x 2 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_mul"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_mul-9yzel",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_mul",
      "type": "topic",
      "url": "/documentation/simd/simd_mul-9yzel"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Matrix-Vector-Multiplication-Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_mul-9yzel",
        "doc://com.apple.accelerate/documentation/simd/matrix_multiply-52sa",
        "doc://com.apple.accelerate/documentation/simd/matrix_multiply-3vw6i"
      ],
      "title": "Matrix-Vector Multiplication Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float4/title",
          "value": "simd_float4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float2/title",
          "value": "simd_float2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float4x2/title",
          "value": "simd_float4x2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float4x2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float4x2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float4x2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float4x2"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_mul-8l982"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
