{
  "abstract": [
    {
      "text": "Returns the refraction direction of an incident vector, a unit normal vector, and an index of refraction eta.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_refract-7dskm"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_refract#]4d#S0_#d#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_refract"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_refract"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_refract"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_double4",
              "text": "simd_double4"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_refract"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_double4",
              "text": "simd_double4"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_double4",
              "text": "simd_double4"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__n"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:d",
              "text": "double"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__eta"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_dot-85nay": {
      "abstract": [
        {
          "text": "Returns the dot product of two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_dot"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_dot-85nay",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_dot",
      "type": "topic",
      "url": "/documentation/simd/simd_dot-85nay"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double4": {
      "abstract": [
        {
          "text": "A vector of four 64-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_double4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_double4"
        }
      ],
      "role": "symbol",
      "title": "simd_double4",
      "type": "topic",
      "url": "/documentation/simd/simd_double4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_fast_normalize-3rv7": {
      "abstract": [
        {
          "text": "Returns the fast normalized vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_fast_normalize"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_fast_normalize-3rv7",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_fast_normalize",
      "type": "topic",
      "url": "/documentation/simd/simd_fast_normalize-3rv7"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_fast_project-6urv1": {
      "abstract": [
        {
          "text": "Returns the fast projected vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_fast_project"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_fast_project-6urv1",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_fast_project",
      "type": "topic",
      "url": "/documentation/simd/simd_fast_project-6urv1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_normalize-9o7wa": {
      "abstract": [
        {
          "text": "Returns a vector pointing in the same direction of the supplied vector, with a length of 1.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_normalize"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_normalize-9o7wa",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_normalize",
      "type": "topic",
      "url": "/documentation/simd/simd_normalize-9o7wa"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_precise_normalize-4vtps": {
      "abstract": [
        {
          "text": "Returns the precise normalized vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_precise_normalize"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_precise_normalize-4vtps",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_precise_normalize",
      "type": "topic",
      "url": "/documentation/simd/simd_precise_normalize-4vtps"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_precise_project-1f1gc": {
      "abstract": [
        {
          "text": "Returns the precise projected vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_precise_project"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_precise_project-1f1gc",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_precise_project",
      "type": "topic",
      "url": "/documentation/simd/simd_precise_project-1f1gc"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_project-6cfku": {
      "abstract": [
        {
          "text": "Returns the first vector projected onto the second vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_project"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_project-6cfku",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_project",
      "type": "topic",
      "url": "/documentation/simd/simd_project-6cfku"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reflect-91ah5": {
      "abstract": [
        {
          "text": "Returns the reflection direction of an incident vector and a unit normal vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_reflect"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reflect-91ah5",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_reflect",
      "type": "topic",
      "url": "/documentation/simd/simd_reflect-91ah5"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_refract-7dskm": {
      "abstract": [
        {
          "text": "Returns the refraction direction of an incident vector, a unit normal vector, and an index of refraction eta.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_refract"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_refract-7dskm",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_refract",
      "type": "topic",
      "url": "/documentation/simd/simd_refract-7dskm"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Geometry-Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_dot-85nay",
        "doc://com.apple.accelerate/documentation/simd/simd_normalize-9o7wa",
        "doc://com.apple.accelerate/documentation/simd/simd_fast_normalize-3rv7",
        "doc://com.apple.accelerate/documentation/simd/simd_precise_normalize-4vtps",
        "doc://com.apple.accelerate/documentation/simd/simd_project-6cfku",
        "doc://com.apple.accelerate/documentation/simd/simd_fast_project-6urv1",
        "doc://com.apple.accelerate/documentation/simd/simd_precise_project-1f1gc",
        "doc://com.apple.accelerate/documentation/simd/simd_reflect-91ah5"
      ],
      "title": "Geometry Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4/title",
          "value": "simd_double4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double4"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_refract-7dskm"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
