{
  "abstract": [
    {
      "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_int-ngyj"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_int#]8d#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_int"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_int"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_int"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int8",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_int8",
              "text": "simd_int8"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_int"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double8",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_double8",
              "text": "simd_double8"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double8": {
      "abstract": [
        {
          "text": "A vector of eight 64-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_double8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_double8"
        }
      ],
      "role": "symbol",
      "title": "simd_double8",
      "type": "topic",
      "url": "/documentation/simd/simd_double8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int-neij": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int-neij",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int",
      "type": "topic",
      "url": "/documentation/simd/simd_int-neij"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int-nfj5": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int-nfj5",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int",
      "type": "topic",
      "url": "/documentation/simd/simd_int-nfj5"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int-ngyj": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int-ngyj",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int",
      "type": "topic",
      "url": "/documentation/simd/simd_int-ngyj"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int-nhpj": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int-nhpj",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int",
      "type": "topic",
      "url": "/documentation/simd/simd_int-nhpj"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int-nik1": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int-nik1",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int",
      "type": "topic",
      "url": "/documentation/simd/simd_int-nik1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int-nnht": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int-nnht",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int",
      "type": "topic",
      "url": "/documentation/simd/simd_int-nnht"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int-nojf": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int-nojf",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int",
      "type": "topic",
      "url": "/documentation/simd/simd_int-nojf"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int-npcx": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int-npcx",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int",
      "type": "topic",
      "url": "/documentation/simd/simd_int-npcx"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int-nskx": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int-nskx",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int",
      "type": "topic",
      "url": "/documentation/simd/simd_int-nskx"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int-nxm9": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int-nxm9",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int",
      "type": "topic",
      "url": "/documentation/simd/simd_int-nxm9"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int8": {
      "abstract": [
        {
          "text": "A vector of eight 32-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_int8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_int8"
        }
      ],
      "role": "symbol",
      "title": "simd_int8",
      "type": "topic",
      "url": "/documentation/simd/simd_int8"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Create-Eight-Element-Vectors-From-Vectors-of-Other-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_int-nskx",
        "doc://com.apple.accelerate/documentation/simd/simd_int-nik1",
        "doc://com.apple.accelerate/documentation/simd/simd_int-nxm9",
        "doc://com.apple.accelerate/documentation/simd/simd_int-nnht",
        "doc://com.apple.accelerate/documentation/simd/simd_int-npcx",
        "doc://com.apple.accelerate/documentation/simd/simd_int-nfj5",
        "doc://com.apple.accelerate/documentation/simd/simd_int-nojf",
        "doc://com.apple.accelerate/documentation/simd/simd_int-neij",
        "doc://com.apple.accelerate/documentation/simd/simd_int-nhpj"
      ],
      "title": "Functions to Create Eight-Element Vectors From Vectors of Other Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double8/title",
          "value": "simd_double8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int8/title",
          "value": "simd_int8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_int8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_int8"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_int-ngyj"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
