{
  "abstract": [
    {
      "text": "A vector of eight 16-bit unsigned integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_ushort8"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@simd_ushort8",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simd_ushort8"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_ushort8"
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "simd_ushort8"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_ushort8"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5SIMD8V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5SIMD8V",
              "text": "SIMD8"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt16V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt16V",
              "text": "UInt16"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1yk7d": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_all"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort8",
          "text": "simd_ushort8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_bool",
          "text": "simd_bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1yk7d",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_all"
        }
      ],
      "role": "symbol",
      "title": "simd_all(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_all(_:)-1yk7d"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-6pgp3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_any"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort8",
          "text": "simd_ushort8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_bool",
          "text": "simd_bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-6pgp3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_any"
        }
      ],
      "role": "symbol",
      "title": "simd_any(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_any(_:)-6pgp3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-4yay5": {
      "abstract": [
        {
          "text": "Returns a vector that contains elements from either the first or second parameter, based on the corresponding element in the third parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_bitselect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort8",
          "text": "simd_ushort8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort8",
          "text": "simd_ushort8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort8",
          "text": "simd_ushort8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-4yay5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_bitselect"
        }
      ],
      "role": "symbol",
      "title": "simd_bitselect(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_bitselect(_:_:_:)-4yay5"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-81cik": {
      "abstract": [
        {
          "text": "Returns each element in a vector clamped to a specified range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_clamp"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort8",
          "text": "simd_ushort8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort8",
          "text": "simd_ushort8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort8",
          "text": "simd_ushort8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort8",
          "text": "simd_ushort8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-81cik",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_clamp"
        }
      ],
      "role": "symbol",
      "title": "simd_clamp(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_clamp(_:_:_:)-81cik"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-3fkex": {
      "abstract": [
        {
          "text": "Returns true if every element in a vector is exactly equal to the corresponding element in a second vector, and otherwise returns false.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_equal"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort8",
          "text": "simd_ushort8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort8",
          "text": "simd_ushort8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_bool",
          "text": "simd_bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-3fkex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_equal"
        }
      ],
      "role": "symbol",
      "title": "simd_equal(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_equal(_:_:)-3fkex"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:)-17t38": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified four-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort4",
          "text": "simd_ushort4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort8",
          "text": "simd_ushort8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:)-17t38",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort8(_:)-17t38"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:)-1e906": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort2",
          "text": "simd_ushort2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort8",
          "text": "simd_ushort8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:)-1e906",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort8(_:)-1e906"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:)-1henz": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified three-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort3",
          "text": "simd_ushort3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort8",
          "text": "simd_ushort8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:)-1henz",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort8(_:)-1henz"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:)-2e4yw": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort8",
          "text": "simd_ushort8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort8",
          "text": "simd_ushort8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:)-2e4yw",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort8(_:)-2e4yw"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:)-4t9gk": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified thrity two-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort32",
          "text": "simd_ushort32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort8",
          "text": "simd_ushort8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:)-4t9gk",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort8(_:)-4t9gk"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:)-5yzvk": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified sixteen-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort16",
          "text": "simd_ushort16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort8",
          "text": "simd_ushort8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:)-5yzvk",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort8(_:)-5yzvk"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:)-66ltd": {
      "abstract": [
        {
          "text": "Returns a new vector with the first element set to a scalar value, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort8",
          "text": "simd_ushort8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:)-66ltd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort8(_:)-66ltd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort4",
          "text": "simd_ushort4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort4",
          "text": "simd_ushort4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort8",
          "text": "simd_ushort8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort8(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort8(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8_undef(_:)-416aa": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified four-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort8_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort4",
          "text": "simd_ushort4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort8",
          "text": "simd_ushort8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8_undef(_:)-416aa",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort8_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort8_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort8_undef(_:)-416aa"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8_undef(_:)-46lw9": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified three-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort8_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort3",
          "text": "simd_ushort3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort8",
          "text": "simd_ushort8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8_undef(_:)-46lw9",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort8_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort8_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort8_undef(_:)-46lw9"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8_undef(_:)-49rg0": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort8_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort2",
          "text": "simd_ushort2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort8",
          "text": "simd_ushort8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8_undef(_:)-49rg0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort8_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort8_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort8_undef(_:)-49rg0"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8_undef(_:)-wluw": {
      "abstract": [
        {
          "text": "Returns a new vector with the first element set to a scalar value, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort8_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort8",
          "text": "simd_ushort8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8_undef(_:)-wluw",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort8_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort8_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort8_undef(_:)-wluw"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-30jsw": {
      "abstract": [
        {
          "text": "Returns the maximum value of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_max"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort8",
          "text": "simd_ushort8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort8",
          "text": "simd_ushort8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort8",
          "text": "simd_ushort8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-30jsw",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_max"
        }
      ],
      "role": "symbol",
      "title": "simd_max(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_max(_:_:)-30jsw"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-2600d": {
      "abstract": [
        {
          "text": "Returns the minimum value of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_min"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort8",
          "text": "simd_ushort8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort8",
          "text": "simd_ushort8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort8",
          "text": "simd_ushort8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-2600d",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_min"
        }
      ],
      "role": "symbol",
      "title": "simd_min(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_min(_:_:)-2600d"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-3b3cs": {
      "abstract": [
        {
          "text": "Returns the sum of all elements in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_add"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort8",
          "text": "simd_ushort8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-3b3cs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_add"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_add(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_add(_:)-3b3cs"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-55hce": {
      "abstract": [
        {
          "text": "Returns the maximum value in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_max"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort8",
          "text": "simd_ushort8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-55hce",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_max"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_max(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_max(_:)-55hce"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-3oh9i": {
      "abstract": [
        {
          "text": "Returns the miniumum value in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_min"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort8",
          "text": "simd_ushort8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-3oh9i",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_min"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_min(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_min(_:)-3oh9i"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort-443vh": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort-443vh",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort-443vh"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort-44617": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort-44617",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort-44617"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort-446z9": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort-446z9",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort-446z9"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort-448v1": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort-448v1",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort-448v1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort-44cwv": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort-44cwv",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort-44cwv"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort-44dgr": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort-44dgr",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort-44dgr"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort-44dr1": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort-44dr1",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort-44dr1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort-44fwr": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort-44fwr",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort-44fwr"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort-44gyd": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort-44gyd",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort-44gyd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort-44iu5": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort-44iu5",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort-44iu5"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort1": {
      "abstract": [
        {
          "text": "A vector of one 16-bit unsigned integer element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ushort1"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ushort1"
        }
      ],
      "role": "symbol",
      "title": "simd_ushort1",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort16": {
      "abstract": [
        {
          "text": "A vector of sixteen 16-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ushort16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ushort16"
        }
      ],
      "role": "symbol",
      "title": "simd_ushort16",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort16"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort2": {
      "abstract": [
        {
          "text": "A vector of two 16-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ushort2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ushort2"
        }
      ],
      "role": "symbol",
      "title": "simd_ushort2",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort3": {
      "abstract": [
        {
          "text": "A vector of three 16-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ushort3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ushort3"
        }
      ],
      "role": "symbol",
      "title": "simd_ushort3",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort32": {
      "abstract": [
        {
          "text": "A vector of thirty-two 16-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ushort32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ushort32"
        }
      ],
      "role": "symbol",
      "title": "simd_ushort32",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort32"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort4": {
      "abstract": [
        {
          "text": "A vector of four 16-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ushort4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ushort4"
        }
      ],
      "role": "symbol",
      "title": "simd_ushort4",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort8": {
      "abstract": [
        {
          "text": "A vector of eight 16-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ushort8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ushort8"
        }
      ],
      "role": "symbol",
      "title": "simd_ushort8",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-8fd8s": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-8fd8s",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-8fd8s"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-8feug": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-8feug",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-8feug"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-8fgdw": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-8fgdw",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-8fgdw"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-8fgi0": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-8fgi0",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-8fgi0"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-8fh48": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-8fh48",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-8fh48"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-8fi24": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-8fi24",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-8fi24"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-8fn0s": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-8fn0s",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-8fn0s"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-8foko": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-8foko",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-8foko"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-8fq7o": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-8fq7o",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-8fq7o"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-8fsa4": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-8fsa4",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-8fsa4"
    },
    "doc://com.apple.accelerate/documentation/simd/vector8-411sw": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector8-411sw",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector8",
      "type": "topic",
      "url": "/documentation/simd/vector8-411sw"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_ushort8": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vector_ushort8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_ushort8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vector_ushort8"
        }
      ],
      "role": "symbol",
      "title": "vector_ushort8",
      "type": "topic",
      "url": "/documentation/simd/vector_ushort8"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s5SIMD8V": {
      "abstract": [
        {
          "text": "A vector of eight scalar values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SIMD8"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SIMDScalarP",
          "text": "SIMDScalar"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5SIMD8V",
      "kind": "symbol",
      "role": "symbol",
      "title": "SIMD8",
      "type": "topic",
      "url": "/documentation/Swift/SIMD8"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt16V": {
      "abstract": [
        {
          "text": "A 16-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt16"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt16V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt16",
      "type": "topic",
      "url": "/documentation/Swift/UInt16"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Vector-Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_ushort1",
        "doc://com.apple.accelerate/documentation/simd/simd_ushort2",
        "doc://com.apple.accelerate/documentation/simd/simd_ushort3",
        "doc://com.apple.accelerate/documentation/simd/simd_ushort4",
        "doc://com.apple.accelerate/documentation/simd/simd_ushort16",
        "doc://com.apple.accelerate/documentation/simd/simd_ushort32"
      ],
      "title": "Vector Data Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Functions-to-Create-Eight-Element-Vectors-From-Other-Vectors",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:)-1e906",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:)-1henz",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:)-17t38",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:)-2e4yw",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:)-5yzvk",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:)-4t9gk",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:_:)",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8_undef(_:)-49rg0",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8_undef(_:)-46lw9",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8_undef(_:)-416aa"
      ],
      "title": "Functions to Create Eight-Element Vectors From Other Vectors"
    },
    {
      "anchor": "Functions-to-Create-Eight-Element-Vectors-From-Scalar-Values",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:)-66ltd",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8_undef(_:)-wluw"
      ],
      "title": "Functions to Create Eight-Element Vectors From Scalar Values"
    },
    {
      "anchor": "Common-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-81cik",
        "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-3fkex"
      ],
      "title": "Common Functions"
    },
    {
      "anchor": "Reduce-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-3oh9i",
        "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-55hce",
        "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-3b3cs"
      ],
      "title": "Reduce Functions"
    },
    {
      "anchor": "Extrema-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-2600d",
        "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-30jsw"
      ],
      "title": "Extrema Functions"
    },
    {
      "anchor": "Logic-and-Bitwise-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-6pgp3",
        "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1yk7d",
        "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-4yay5"
      ],
      "title": "Logic and Bitwise Functions"
    },
    {
      "anchor": "Alternative-Type-Alias",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/vector_ushort8"
      ],
      "title": "Alternative Type Alias"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "simd_ushort8"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/simd"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Functions-to-Create-Eight-Element-Vectors-From-Other-Vectors",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:)-1e906",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:)-1henz",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:)-17t38",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:)-2e4yw",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:)-5yzvk",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:)-4t9gk",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:_:)",
                "doc://com.apple.accelerate/documentation/simd/vector8-411sw",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8_undef(_:)-49rg0",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8_undef(_:)-46lw9",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8_undef(_:)-416aa"
              ],
              "title": "Functions to Create Eight-Element Vectors From Other Vectors"
            },
            {
              "anchor": "Functions-to-Create-Eight-Element-Vectors-From-Scalar-Values",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8(_:)-66ltd",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ushort8_undef(_:)-wluw"
              ],
              "title": "Functions to Create Eight-Element Vectors From Scalar Values"
            },
            {
              "anchor": "Functions-to-Create-Eight-Element-Vectors-From-Vectors-of-Other-Types",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_ushort-443vh",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort-44dr1",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort-448v1",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort-44iu5",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort-446z9",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort-44gyd",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort-44617",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort-44fwr",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort-44cwv",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort-44dgr"
              ],
              "title": "Functions to Create Eight-Element Vectors From Vectors of Other Types"
            },
            {
              "anchor": "Functions-to-Perform-Saturating-Conversion-From-Vectors-of-Other-Types",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-8fsa4",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-8fi24",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-8fn0s",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-8fd8s",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-8fq7o",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-8fgdw",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-8foko",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-8feug",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-8fgi0",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-8fh48"
              ],
              "title": "Functions to Perform Saturating Conversion From Vectors of Other Types"
            },
            {
              "anchor": "Common-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-81cik",
                "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-3fkex"
              ],
              "title": "Common Functions"
            },
            {
              "anchor": "Reduce-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-3oh9i",
                "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-55hce",
                "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-3b3cs"
              ],
              "title": "Reduce Functions"
            },
            {
              "anchor": "Extrema-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-2600d",
                "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-30jsw"
              ],
              "title": "Extrema Functions"
            },
            {
              "anchor": "Logic-and-Bitwise-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-6pgp3",
                "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1yk7d",
                "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-4yay5"
              ],
              "title": "Logic and Bitwise Functions"
            },
            {
              "anchor": "Alternative-Type-Alias",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/vector_ushort8"
              ],
              "title": "Alternative Type Alias"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Vector-Data-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_ushort1",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort2",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort3",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort4",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort16",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort32"
              ],
              "title": "Vector Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:]8s",
                    "text": "unsigned short __attribute__((ext_vector_type(8)))"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "simd_ushort8"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_any(_:)-6pgp3/title",
          "value": "simd_any"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_any(_:)-6pgp3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_any"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort8(_:)-1henz/title",
          "value": "simd_make_ushort8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort8(_:)-1henz/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1vector_ushort8/title",
          "value": "vector_ushort8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1vector_ushort8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vector_ushort8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1vector_ushort8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vector_ushort8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_max(_:)-55hce/title",
          "value": "simd_reduce_max"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_max(_:)-55hce/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_max"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort8(_:)-1e906/title",
          "value": "simd_make_ushort8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort8(_:)-1e906/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort8(_:)-2e4yw/title",
          "value": "simd_make_ushort8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort8(_:)-2e4yw/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_bitselect(_:_:_:)-4yay5/title",
          "value": "simd_bitselect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_bitselect(_:_:_:)-4yay5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_bitselect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort8_undef(_:)-416aa/title",
          "value": "simd_make_ushort8_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort8_undef(_:)-416aa/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort8_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort4/title",
          "value": "simd_ushort4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort8_undef(_:)-46lw9/title",
          "value": "simd_make_ushort8_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort8_undef(_:)-46lw9/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort8_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort8(_:)-5yzvk/title",
          "value": "simd_make_ushort8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort8(_:)-5yzvk/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_equal(_:_:)-3fkex/title",
          "value": "simd_equal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_equal(_:_:)-3fkex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_equal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort8(_:_:)/title",
          "value": "simd_make_ushort8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort8(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_max(_:_:)-30jsw/title",
          "value": "simd_max"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_max(_:_:)-30jsw/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_max"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort8(_:)-17t38/title",
          "value": "simd_make_ushort8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort8(_:)-17t38/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort8_undef(_:)-wluw/title",
          "value": "simd_make_ushort8_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort8_undef(_:)-wluw/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort8_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_add(_:)-3b3cs/title",
          "value": "simd_reduce_add"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_add(_:)-3b3cs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_add"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort32/title",
          "value": "simd_ushort32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort32/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort8(_:)-66ltd/title",
          "value": "simd_make_ushort8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort8(_:)-66ltd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort8/title",
          "value": "simd_ushort8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort8(_:)-4t9gk/title",
          "value": "simd_make_ushort8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort8(_:)-4t9gk/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort3/title",
          "value": "simd_ushort3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_all(_:)-1yk7d/title",
          "value": "simd_all"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_all(_:)-1yk7d/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_all"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_min(_:)-3oh9i/title",
          "value": "simd_reduce_min"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_min(_:)-3oh9i/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_min"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_min(_:_:)-2600d/title",
          "value": "simd_min"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_min(_:_:)-2600d/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_min"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort2/title",
          "value": "simd_ushort2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort8_undef(_:)-49rg0/title",
          "value": "simd_make_ushort8_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort8_undef(_:)-49rg0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort8_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_clamp(_:_:_:)-81cik/title",
          "value": "simd_clamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_clamp(_:_:_:)-81cik/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_clamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort1/title",
          "value": "simd_ushort1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort1/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort16/title",
          "value": "simd_ushort16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort16/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort16"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_ushort8"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/simd/simd_ushort8"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
