{
  "abstract": [
    {
      "text": "A vector of eight 16-bit signed integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_short8"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@simd_short8",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simd_short8"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_short8"
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "simd_short8"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_short8"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5SIMD8V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5SIMD8V",
              "text": "SIMD8"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5Int16V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5Int16V",
              "text": "Int16"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_abs(_:)-7otzk": {
      "abstract": [
        {
          "text": "Returns the absolute value of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_abs"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_abs(_:)-7otzk",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_abs"
        }
      ],
      "role": "symbol",
      "title": "simd_abs(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_abs(_:)-7otzk"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1ytzd": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_all"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_bool",
          "text": "simd_bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1ytzd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_all"
        }
      ],
      "role": "symbol",
      "title": "simd_all(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_all(_:)-1ytzd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-6pqh3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_any"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_bool",
          "text": "simd_bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-6pqh3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_any"
        }
      ],
      "role": "symbol",
      "title": "simd_any(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_any(_:)-6pqh3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-1vm6y": {
      "abstract": [
        {
          "text": "Returns a vector that contains elements from either the first or second parameter, based on the corresponding element in the third parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_bitselect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-1vm6y",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_bitselect"
        }
      ],
      "role": "symbol",
      "title": "simd_bitselect(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_bitselect(_:_:_:)-1vm6y"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-3cc2g": {
      "abstract": [
        {
          "text": "Returns each element in a vector clamped to a specified range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_clamp"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-3cc2g",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_clamp"
        }
      ],
      "role": "symbol",
      "title": "simd_clamp(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_clamp(_:_:_:)-3cc2g"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-4n1gi": {
      "abstract": [
        {
          "text": "Returns true if every element in a vector is exactly equal to the corresponding element in a second vector, and otherwise returns false.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_equal"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_bool",
          "text": "simd_bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-4n1gi",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_equal"
        }
      ],
      "role": "symbol",
      "title": "simd_equal(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_equal(_:_:)-4n1gi"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:)-1jz7f": {
      "abstract": [
        {
          "text": "Returns a new vector with the first element set to a scalar value, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int16V",
          "text": "Int16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:)-1jz7f",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short8(_:)-1jz7f"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:)-22n5y": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified sixteen-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short16",
          "text": "simd_short16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:)-22n5y",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short8(_:)-22n5y"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:)-5gjta": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:)-5gjta",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short8(_:)-5gjta"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:)-5wv29": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified three-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short3",
          "text": "simd_short3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:)-5wv29",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short8(_:)-5wv29"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:)-600rc": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short2",
          "text": "simd_short2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:)-600rc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short8(_:)-600rc"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:)-6l7oy": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified four-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short4",
          "text": "simd_short4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:)-6l7oy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short8(_:)-6l7oy"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:)-8mc9h": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified thrity two-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short32",
          "text": "simd_short32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:)-8mc9h",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short8(_:)-8mc9h"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short4",
          "text": "simd_short4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short4",
          "text": "simd_short4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short8(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short8(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short8_undef(_:)-54hbi": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short8_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short2",
          "text": "simd_short2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short8_undef(_:)-54hbi",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short8_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short8_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short8_undef(_:)-54hbi"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short8_undef(_:)-57mlz": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified three-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short8_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short3",
          "text": "simd_short3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short8_undef(_:)-57mlz",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short8_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short8_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short8_undef(_:)-57mlz"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short8_undef(_:)-5ny5g": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified four-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short8_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short4",
          "text": "simd_short4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short8_undef(_:)-5ny5g",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short8_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short8_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short8_undef(_:)-5ny5g"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short8_undef(_:)-7945n": {
      "abstract": [
        {
          "text": "Returns a new vector with the first element set to a scalar value, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short8_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int16V",
          "text": "Int16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short8_undef(_:)-7945n",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short8_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short8_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short8_undef(_:)-7945n"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-1u1su": {
      "abstract": [
        {
          "text": "Returns the maximum value of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_max"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-1u1su",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_max"
        }
      ],
      "role": "symbol",
      "title": "simd_max(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_max(_:_:)-1u1su"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-40hpn": {
      "abstract": [
        {
          "text": "Returns the minimum value of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_min"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-40hpn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_min"
        }
      ],
      "role": "symbol",
      "title": "simd_min(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_min(_:_:)-40hpn"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-3bda4": {
      "abstract": [
        {
          "text": "Returns the sum of all elements in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_add"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int16V",
          "text": "Int16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-3bda4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_add"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_add(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_add(_:)-3bda4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-55r7y": {
      "abstract": [
        {
          "text": "Returns the maximum value in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_max"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int16V",
          "text": "Int16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-55r7y",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_max"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_max(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_max(_:)-55r7y"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-3ordy": {
      "abstract": [
        {
          "text": "Returns the miniumum value in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_min"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int16V",
          "text": "Int16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-3ordy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_min"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_min(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_min(_:)-3ordy"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short-6zn74": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short-6zn74",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short",
      "type": "topic",
      "url": "/documentation/simd/simd_short-6zn74"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short-6zo8c": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short-6zo8c",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short",
      "type": "topic",
      "url": "/documentation/simd/simd_short-6zo8c"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short-6zqew": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short-6zqew",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short",
      "type": "topic",
      "url": "/documentation/simd/simd_short-6zqew"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short-6zqvg": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short-6zqvg",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short",
      "type": "topic",
      "url": "/documentation/simd/simd_short-6zqvg"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short-6zrfo": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short-6zrfo",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short",
      "type": "topic",
      "url": "/documentation/simd/simd_short-6zrfo"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short-6zvaw": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short-6zvaw",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short",
      "type": "topic",
      "url": "/documentation/simd/simd_short-6zvaw"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short-6zxf4": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short-6zxf4",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short",
      "type": "topic",
      "url": "/documentation/simd/simd_short-6zxf4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short-6zy24": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short-6zy24",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short",
      "type": "topic",
      "url": "/documentation/simd/simd_short-6zy24"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short-7008o": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short-7008o",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short",
      "type": "topic",
      "url": "/documentation/simd/simd_short-7008o"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short-705iw": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short-705iw",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short",
      "type": "topic",
      "url": "/documentation/simd/simd_short-705iw"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short1": {
      "abstract": [
        {
          "text": "A vector of one 16-bit signed integer element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_short1"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_short1"
        }
      ],
      "role": "symbol",
      "title": "simd_short1",
      "type": "topic",
      "url": "/documentation/simd/simd_short1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short16": {
      "abstract": [
        {
          "text": "A vector of sixteen 16-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_short16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_short16"
        }
      ],
      "role": "symbol",
      "title": "simd_short16",
      "type": "topic",
      "url": "/documentation/simd/simd_short16"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short2": {
      "abstract": [
        {
          "text": "A vector of two 16-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_short2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_short2"
        }
      ],
      "role": "symbol",
      "title": "simd_short2",
      "type": "topic",
      "url": "/documentation/simd/simd_short2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short3": {
      "abstract": [
        {
          "text": "A vector of three 16-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_short3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_short3"
        }
      ],
      "role": "symbol",
      "title": "simd_short3",
      "type": "topic",
      "url": "/documentation/simd/simd_short3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short32": {
      "abstract": [
        {
          "text": "A vector of thirty-two 16-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_short32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_short32"
        }
      ],
      "role": "symbol",
      "title": "simd_short32",
      "type": "topic",
      "url": "/documentation/simd/simd_short32"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short4": {
      "abstract": [
        {
          "text": "A vector of four 16-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_short4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_short4"
        }
      ],
      "role": "symbol",
      "title": "simd_short4",
      "type": "topic",
      "url": "/documentation/simd/simd_short4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short8": {
      "abstract": [
        {
          "text": "A vector of eight 16-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_short8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_short8"
        }
      ],
      "role": "symbol",
      "title": "simd_short8",
      "type": "topic",
      "url": "/documentation/simd/simd_short8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3170j": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3170j",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_short_sat-3170j"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short_sat-317n3": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short_sat-317n3",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_short_sat-317n3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short_sat-318h5": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short_sat-318h5",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_short_sat-318h5"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short_sat-319ir": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short_sat-319ir",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_short_sat-319ir"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short_sat-31ad5": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short_sat-31ad5",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_short_sat-31ad5"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short_sat-31de1": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short_sat-31de1",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_short_sat-31de1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short_sat-31ieh": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short_sat-31ieh",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_short_sat-31ieh"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short_sat-31jcj": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short_sat-31jcj",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_short_sat-31jcj"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short_sat-31khl": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short_sat-31khl",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_short_sat-31khl"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short_sat-31nk9": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short_sat-31nk9",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_short_sat-31nk9"
    },
    "doc://com.apple.accelerate/documentation/simd/vector8-7jnqf": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector8-7jnqf",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector8",
      "type": "topic",
      "url": "/documentation/simd/vector8-7jnqf"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_short8": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vector_short8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_short8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vector_short8"
        }
      ],
      "role": "symbol",
      "title": "vector_short8",
      "type": "topic",
      "url": "/documentation/simd/vector_short8"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s5Int16V": {
      "abstract": [
        {
          "text": "A 16-bit signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int16"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5Int16V",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int16",
      "type": "topic",
      "url": "/documentation/Swift/Int16"
    },
    "doc://com.externally.resolved.symbol/s:s5SIMD8V": {
      "abstract": [
        {
          "text": "A vector of eight scalar values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SIMD8"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SIMDScalarP",
          "text": "SIMDScalar"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5SIMD8V",
      "kind": "symbol",
      "role": "symbol",
      "title": "SIMD8",
      "type": "topic",
      "url": "/documentation/Swift/SIMD8"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Vector-Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_short1",
        "doc://com.apple.accelerate/documentation/simd/simd_short2",
        "doc://com.apple.accelerate/documentation/simd/simd_short3",
        "doc://com.apple.accelerate/documentation/simd/simd_short4",
        "doc://com.apple.accelerate/documentation/simd/simd_short16",
        "doc://com.apple.accelerate/documentation/simd/simd_short32"
      ],
      "title": "Vector Data Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Functions-to-Create-Eight-Element-Vectors-From-Other-Vectors",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:)-600rc",
        "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:)-5wv29",
        "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:)-6l7oy",
        "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:)-5gjta",
        "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:)-22n5y",
        "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:)-8mc9h",
        "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:_:)",
        "doc://com.apple.accelerate/documentation/simd/simd_make_short8_undef(_:)-54hbi",
        "doc://com.apple.accelerate/documentation/simd/simd_make_short8_undef(_:)-57mlz",
        "doc://com.apple.accelerate/documentation/simd/simd_make_short8_undef(_:)-5ny5g"
      ],
      "title": "Functions to Create Eight-Element Vectors From Other Vectors"
    },
    {
      "anchor": "Functions-to-Create-Eight-Element-Vectors-From-Scalar-Values",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:)-1jz7f",
        "doc://com.apple.accelerate/documentation/simd/simd_make_short8_undef(_:)-7945n"
      ],
      "title": "Functions to Create Eight-Element Vectors From Scalar Values"
    },
    {
      "anchor": "Common-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_abs(_:)-7otzk",
        "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-3cc2g",
        "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-4n1gi"
      ],
      "title": "Common Functions"
    },
    {
      "anchor": "Reduce-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-3ordy",
        "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-55r7y",
        "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-3bda4"
      ],
      "title": "Reduce Functions"
    },
    {
      "anchor": "Extrema-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-40hpn",
        "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-1u1su"
      ],
      "title": "Extrema Functions"
    },
    {
      "anchor": "Logic-and-Bitwise-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-6pqh3",
        "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1ytzd",
        "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-1vm6y"
      ],
      "title": "Logic and Bitwise Functions"
    },
    {
      "anchor": "Alternative-Type-Alias",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/vector_short8"
      ],
      "title": "Alternative Type Alias"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "simd_short8"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/simd"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Functions-to-Create-Eight-Element-Vectors-From-Other-Vectors",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:)-600rc",
                "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:)-5wv29",
                "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:)-6l7oy",
                "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:)-5gjta",
                "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:)-22n5y",
                "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:)-8mc9h",
                "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:_:)",
                "doc://com.apple.accelerate/documentation/simd/vector8-7jnqf",
                "doc://com.apple.accelerate/documentation/simd/simd_make_short8_undef(_:)-54hbi",
                "doc://com.apple.accelerate/documentation/simd/simd_make_short8_undef(_:)-57mlz",
                "doc://com.apple.accelerate/documentation/simd/simd_make_short8_undef(_:)-5ny5g"
              ],
              "title": "Functions to Create Eight-Element Vectors From Other Vectors"
            },
            {
              "anchor": "Functions-to-Create-Eight-Element-Vectors-From-Scalar-Values",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:)-1jz7f",
                "doc://com.apple.accelerate/documentation/simd/simd_make_short8_undef(_:)-7945n"
              ],
              "title": "Functions to Create Eight-Element Vectors From Scalar Values"
            },
            {
              "anchor": "Functions-to-Create-Eight-Element-Vectors-From-Vectors-of-Other-Types",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_short-7008o",
                "doc://com.apple.accelerate/documentation/simd/simd_short-6zqew",
                "doc://com.apple.accelerate/documentation/simd/simd_short-705iw",
                "doc://com.apple.accelerate/documentation/simd/simd_short-6zvaw",
                "doc://com.apple.accelerate/documentation/simd/simd_short-6zxf4",
                "doc://com.apple.accelerate/documentation/simd/simd_short-6zn74",
                "doc://com.apple.accelerate/documentation/simd/simd_short-6zy24",
                "doc://com.apple.accelerate/documentation/simd/simd_short-6zo8c",
                "doc://com.apple.accelerate/documentation/simd/simd_short-6zrfo",
                "doc://com.apple.accelerate/documentation/simd/simd_short-6zqvg"
              ],
              "title": "Functions to Create Eight-Element Vectors From Vectors of Other Types"
            },
            {
              "anchor": "Functions-to-Perform-Saturating-Conversion-From-Vectors-of-Other-Types",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_short_sat-31ieh",
                "doc://com.apple.accelerate/documentation/simd/simd_short_sat-318h5",
                "doc://com.apple.accelerate/documentation/simd/simd_short_sat-31nk9",
                "doc://com.apple.accelerate/documentation/simd/simd_short_sat-31de1",
                "doc://com.apple.accelerate/documentation/simd/simd_short_sat-31khl",
                "doc://com.apple.accelerate/documentation/simd/simd_short_sat-31ad5",
                "doc://com.apple.accelerate/documentation/simd/simd_short_sat-31jcj",
                "doc://com.apple.accelerate/documentation/simd/simd_short_sat-319ir",
                "doc://com.apple.accelerate/documentation/simd/simd_short_sat-317n3",
                "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3170j"
              ],
              "title": "Functions to Perform Saturating Conversion From Vectors of Other Types"
            },
            {
              "anchor": "Common-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_abs(_:)-7otzk",
                "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-3cc2g",
                "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-4n1gi"
              ],
              "title": "Common Functions"
            },
            {
              "anchor": "Reduce-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-3ordy",
                "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-55r7y",
                "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-3bda4"
              ],
              "title": "Reduce Functions"
            },
            {
              "anchor": "Extrema-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-40hpn",
                "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-1u1su"
              ],
              "title": "Extrema Functions"
            },
            {
              "anchor": "Logic-and-Bitwise-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-6pqh3",
                "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1ytzd",
                "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-1vm6y"
              ],
              "title": "Logic and Bitwise Functions"
            },
            {
              "anchor": "Alternative-Type-Alias",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/vector_short8"
              ],
              "title": "Alternative Type Alias"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Vector-Data-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_short1",
                "doc://com.apple.accelerate/documentation/simd/simd_short2",
                "doc://com.apple.accelerate/documentation/simd/simd_short3",
                "doc://com.apple.accelerate/documentation/simd/simd_short4",
                "doc://com.apple.accelerate/documentation/simd/simd_short16",
                "doc://com.apple.accelerate/documentation/simd/simd_short32"
              ],
              "title": "Vector Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:]8S",
                    "text": "short __attribute__((ext_vector_type(8)))"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "simd_short8"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_any(_:)-6pqh3/title",
          "value": "simd_any"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_any(_:)-6pqh3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_any"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short8(_:)-5wv29/title",
          "value": "simd_make_short8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short8(_:)-5wv29/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short8(_:)-22n5y/title",
          "value": "simd_make_short8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short8(_:)-22n5y/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short3/title",
          "value": "simd_short3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_add(_:)-3bda4/title",
          "value": "simd_reduce_add"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_add(_:)-3bda4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_add"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_clamp(_:_:_:)-3cc2g/title",
          "value": "simd_clamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_clamp(_:_:_:)-3cc2g/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_clamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short32/title",
          "value": "simd_short32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short32/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short2/title",
          "value": "simd_short2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_abs(_:)-7otzk/title",
          "value": "simd_abs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_abs(_:)-7otzk/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_abs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short16/title",
          "value": "simd_short16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short16/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short8_undef(_:)-57mlz/title",
          "value": "simd_make_short8_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short8_undef(_:)-57mlz/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short8_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short8(_:)-8mc9h/title",
          "value": "simd_make_short8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short8(_:)-8mc9h/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short8_undef(_:)-7945n/title",
          "value": "simd_make_short8_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short8_undef(_:)-7945n/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short8_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short8(_:)-1jz7f/title",
          "value": "simd_make_short8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short8(_:)-1jz7f/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short8(_:)-5gjta/title",
          "value": "simd_make_short8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short8(_:)-5gjta/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_all(_:)-1ytzd/title",
          "value": "simd_all"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_all(_:)-1ytzd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_all"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1vector_short8/title",
          "value": "vector_short8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1vector_short8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vector_short8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1vector_short8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vector_short8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_bitselect(_:_:_:)-1vm6y/title",
          "value": "simd_bitselect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_bitselect(_:_:_:)-1vm6y/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_bitselect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short8(_:)-6l7oy/title",
          "value": "simd_make_short8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short8(_:)-6l7oy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short8_undef(_:)-54hbi/title",
          "value": "simd_make_short8_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short8_undef(_:)-54hbi/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short8_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short1/title",
          "value": "simd_short1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short1/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_equal(_:_:)-4n1gi/title",
          "value": "simd_equal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_equal(_:_:)-4n1gi/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_equal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short8/title",
          "value": "simd_short8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short8(_:)-600rc/title",
          "value": "simd_make_short8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short8(_:)-600rc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short8(_:_:)/title",
          "value": "simd_make_short8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short8(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_max(_:_:)-1u1su/title",
          "value": "simd_max"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_max(_:_:)-1u1su/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_max"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_min(_:_:)-40hpn/title",
          "value": "simd_min"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_min(_:_:)-40hpn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_min"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short4/title",
          "value": "simd_short4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short8_undef(_:)-5ny5g/title",
          "value": "simd_make_short8_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short8_undef(_:)-5ny5g/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short8_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_max(_:)-55r7y/title",
          "value": "simd_reduce_max"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_max(_:)-55r7y/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_max"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_min(_:)-3ordy/title",
          "value": "simd_reduce_min"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_min(_:)-3ordy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_min"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_short8"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/simd/simd_short8"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
