{
  "abstract": [
    {
      "text": "Returns a new vector from the specified eight-element vector, and other elements set to zero.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_make_uint16(_:)-9hiq"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_make_uint16#]8i#",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simd_make_uint16"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_uint8",
        "text": "simd_uint8"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_uint16",
        "text": "simd_uint16"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_make_uint16"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_make_uint16(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_make_uint16"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "other"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint8",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_uint8",
              "text": "simd_uint8"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint16",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_uint16",
              "text": "simd_uint16"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uint16(_:)-99aov": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uint16"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint2",
          "text": "simd_uint2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint16",
          "text": "simd_uint16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uint16(_:)-99aov",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uint16"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uint16(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uint16(_:)-99aov"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uint16(_:)-9efau": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified three-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uint16"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint3",
          "text": "simd_uint3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint16",
          "text": "simd_uint16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uint16(_:)-9efau",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uint16"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uint16(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uint16(_:)-9efau"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uint16(_:)-9hiq": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified eight-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uint16"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint8",
          "text": "simd_uint8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint16",
          "text": "simd_uint16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uint16(_:)-9hiq",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uint16"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uint16(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uint16(_:)-9hiq"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uint16(_:)-9s9mg": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uint16"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint16",
          "text": "simd_uint16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint16",
          "text": "simd_uint16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uint16(_:)-9s9mg",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uint16"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uint16(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uint16(_:)-9s9mg"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uint16(_:)-9u6t5": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified four-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uint16"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint4",
          "text": "simd_uint4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint16",
          "text": "simd_uint16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uint16(_:)-9u6t5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uint16"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uint16(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uint16(_:)-9u6t5"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uint16(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uint16"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint8",
          "text": "simd_uint8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint8",
          "text": "simd_uint8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint16",
          "text": "simd_uint16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uint16(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uint16"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uint16(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uint16(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uint16_undef(_:)-9slqx": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified three-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uint16_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint3",
          "text": "simd_uint3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint16",
          "text": "simd_uint16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uint16_undef(_:)-9slqx",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uint16_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uint16_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uint16_undef(_:)-9slqx"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uint16_undef(_:)-9w2go": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uint16_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint2",
          "text": "simd_uint2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint16",
          "text": "simd_uint16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uint16_undef(_:)-9w2go",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uint16_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uint16_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uint16_undef(_:)-9w2go"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uint16_undef(_:)-hcyl": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified four-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uint16_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint4",
          "text": "simd_uint4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint16",
          "text": "simd_uint16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uint16_undef(_:)-hcyl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uint16_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uint16_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uint16_undef(_:)-hcyl"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uint16_undef(_:)-we1l": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified eight-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uint16_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint8",
          "text": "simd_uint8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint16",
          "text": "simd_uint16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uint16_undef(_:)-we1l",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uint16_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uint16_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uint16_undef(_:)-we1l"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint16": {
      "abstract": [
        {
          "text": "A vector of sixteen 32-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uint16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uint16"
        }
      ],
      "role": "symbol",
      "title": "simd_uint16",
      "type": "topic",
      "url": "/documentation/simd/simd_uint16"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint8": {
      "abstract": [
        {
          "text": "A vector of eight 32-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uint8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uint8"
        }
      ],
      "role": "symbol",
      "title": "simd_uint8",
      "type": "topic",
      "url": "/documentation/simd/simd_uint8"
    },
    "doc://com.apple.accelerate/documentation/simd/vector16-8xs3z": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector16-8xs3z",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector16",
      "type": "topic",
      "url": "/documentation/simd/vector16-8xs3z"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Create-Sixteen-Element-Vectors-From-Other-Vectors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_uint16(_:)-99aov",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uint16(_:)-9efau",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uint16(_:)-9u6t5",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uint16(_:)-9s9mg",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uint16(_:_:)",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uint16_undef(_:)-9w2go",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uint16_undef(_:)-9slqx",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uint16_undef(_:)-hcyl",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uint16_undef(_:)-we1l"
      ],
      "title": "Functions to Create Sixteen-Element Vectors From Other Vectors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "simd_make_uint16"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uint16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/simd"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Functions-to-Create-Sixteen-Element-Vectors-From-Other-Vectors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_uint16(_:)-99aov",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uint16(_:)-9efau",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uint16(_:)-9u6t5",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uint16(_:)-9s9mg",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uint16(_:_:)",
                "doc://com.apple.accelerate/documentation/simd/vector16-8xs3z",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uint16_undef(_:)-9w2go",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uint16_undef(_:)-9slqx",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uint16_undef(_:)-hcyl",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uint16_undef(_:)-we1l"
              ],
              "title": "Functions to Create Sixteen-Element Vectors From Other Vectors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "static"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint16",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_uint16",
                    "text": "simd_uint16"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "simd_make_uint16"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint8",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_uint8",
                    "text": "simd_uint8"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "other"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uint16(_:)-9efau/title",
          "value": "simd_make_uint16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uint16(_:)-9efau/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uint16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint8/title",
          "value": "simd_uint8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uint8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uint8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint16/title",
          "value": "simd_uint16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uint16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint16/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uint16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uint16(_:)-9u6t5/title",
          "value": "simd_make_uint16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uint16(_:)-9u6t5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uint16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uint16(_:)-9hiq/title",
          "value": "simd_make_uint16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uint16(_:)-9hiq/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uint16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uint16_undef(_:)-9w2go/title",
          "value": "simd_make_uint16_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uint16_undef(_:)-9w2go/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uint16_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uint16(_:)-9s9mg/title",
          "value": "simd_make_uint16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uint16(_:)-9s9mg/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uint16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uint16_undef(_:)-9slqx/title",
          "value": "simd_make_uint16_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uint16_undef(_:)-9slqx/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uint16_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uint16(_:)-99aov/title",
          "value": "simd_make_uint16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uint16(_:)-99aov/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uint16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uint16_undef(_:)-we1l/title",
          "value": "simd_make_uint16_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uint16_undef(_:)-we1l/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uint16_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uint16(_:_:)/title",
          "value": "simd_make_uint16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uint16(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uint16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uint16_undef(_:)-hcyl/title",
          "value": "simd_make_uint16_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uint16_undef(_:)-hcyl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uint16_undef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_make_uint16(_:)-9hiq"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/simd/simd_make_uint16(_:)-9hiq"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
