{
  "abstract": [
    {
      "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-11tza"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_ushort_sat#]32C#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_ushort_sat"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_ushort_sat"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_ushort_sat"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort32",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_ushort32",
              "text": "simd_ushort32"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_ushort_sat"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char32",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_char32",
              "text": "simd_char32"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char32": {
      "abstract": [
        {
          "text": "A vector of thirty-two 8-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_char32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_char32"
        }
      ],
      "role": "symbol",
      "title": "simd_char32",
      "type": "topic",
      "url": "/documentation/simd/simd_char32"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort32": {
      "abstract": [
        {
          "text": "A vector of thirty-two 16-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ushort32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ushort32"
        }
      ],
      "role": "symbol",
      "title": "simd_ushort32",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort32"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-11fae": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-11fae",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-11fae"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-11k7a": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-11k7a",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-11k7a"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-11p46": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-11p46",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-11p46"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-11tza": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-11tza",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-11tza"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Perform-Saturating-Conversion-From-Vectors-of-Other-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-11k7a",
        "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-11p46",
        "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-11fae"
      ],
      "title": "Functions to Perform Saturating Conversion From Vectors of Other Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort32/title",
          "value": "simd_ushort32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort32/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char32/title",
          "value": "simd_char32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char32/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char32"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_ushort_sat-11tza"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
