{
  "abstract": [
    {
      "text": "A vector of sixty-four 8-bit unsigned integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_uchar64"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@simd_uchar64",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simd_uchar64"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_uchar64"
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "simd_uchar64"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_uchar64"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6SIMD64V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6SIMD64V",
              "text": "SIMD64"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5UInt8V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5UInt8V",
              "text": "UInt8"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-2m0jp": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_all"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar64",
          "text": "simd_uchar64"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_bool",
          "text": "simd_bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-2m0jp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_all"
        }
      ],
      "role": "symbol",
      "title": "simd_all(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_all(_:)-2m0jp"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-jl1j": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_any"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar64",
          "text": "simd_uchar64"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_bool",
          "text": "simd_bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-jl1j",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_any"
        }
      ],
      "role": "symbol",
      "title": "simd_any(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_any(_:)-jl1j"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-2bway": {
      "abstract": [
        {
          "text": "Returns a vector that contains elements from either the first or second parameter, based on the corresponding element in the third parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_bitselect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar64",
          "text": "simd_uchar64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar64",
          "text": "simd_uchar64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char64",
          "text": "simd_char64"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar64",
          "text": "simd_uchar64"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-2bway",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_bitselect"
        }
      ],
      "role": "symbol",
      "title": "simd_bitselect(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_bitselect(_:_:_:)-2bway"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-52h9h": {
      "abstract": [
        {
          "text": "Returns each element in a vector clamped to a specified range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_clamp"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar64",
          "text": "simd_uchar64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar64",
          "text": "simd_uchar64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar64",
          "text": "simd_uchar64"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar64",
          "text": "simd_uchar64"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-52h9h",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_clamp"
        }
      ],
      "role": "symbol",
      "title": "simd_clamp(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_clamp(_:_:_:)-52h9h"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-494kp": {
      "abstract": [
        {
          "text": "Returns true if every element in a vector is exactly equal to the corresponding element in a second vector, and otherwise returns false.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_equal"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar64",
          "text": "simd_uchar64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar64",
          "text": "simd_uchar64"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_bool",
          "text": "simd_bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-494kp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_equal"
        }
      ],
      "role": "symbol",
      "title": "simd_equal(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_equal(_:_:)-494kp"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64(_:)-1g5oc": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar64"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar64",
          "text": "simd_uchar64"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar64",
          "text": "simd_uchar64"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64(_:)-1g5oc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar64"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar64(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar64(_:)-1g5oc"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64(_:)-3wfeh": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified sixteen-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar64"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar16",
          "text": "simd_uchar16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar64",
          "text": "simd_uchar64"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64(_:)-3wfeh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar64"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar64(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar64(_:)-3wfeh"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64(_:)-51eby": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified four-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar64"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar4",
          "text": "simd_uchar4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar64",
          "text": "simd_uchar64"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64(_:)-51eby",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar64"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar64(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar64(_:)-51eby"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64(_:)-56lh8": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified thirty two-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar64"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar64",
          "text": "simd_uchar64"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64(_:)-56lh8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar64"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar64(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar64(_:)-56lh8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64(_:)-57u64": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar64"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar2",
          "text": "simd_uchar2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar64",
          "text": "simd_uchar64"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64(_:)-57u64",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar64"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar64(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar64(_:)-57u64"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64(_:)-5apn9": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified three-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar64"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar3",
          "text": "simd_uchar3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar64",
          "text": "simd_uchar64"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64(_:)-5apn9",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar64"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar64(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar64(_:)-5apn9"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64(_:)-65i5u": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified eight-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar64"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar8",
          "text": "simd_uchar8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar64",
          "text": "simd_uchar64"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64(_:)-65i5u",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar64"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar64(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar64(_:)-65i5u"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64(_:)-9d1w7": {
      "abstract": [
        {
          "text": "Returns a new vector with the first element set to a scalar value, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar64"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar64",
          "text": "simd_uchar64"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64(_:)-9d1w7",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar64"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar64(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar64(_:)-9d1w7"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar64"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar64",
          "text": "simd_uchar64"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar64"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar64(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar64(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64_undef(_:)-6vlwv": {
      "abstract": [
        {
          "text": "Returns a new vector with the first element set to a scalar value, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar64_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar64",
          "text": "simd_uchar64"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64_undef(_:)-6vlwv",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar64_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar64_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar64_undef(_:)-6vlwv"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64_undef(_:)-8fhu3": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified four-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar64_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar4",
          "text": "simd_uchar4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar64",
          "text": "simd_uchar64"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64_undef(_:)-8fhu3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar64_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar64_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar64_undef(_:)-8fhu3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64_undef(_:)-8ig34": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified three-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar64_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar3",
          "text": "simd_uchar3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar64",
          "text": "simd_uchar64"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64_undef(_:)-8ig34",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar64_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar64_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar64_undef(_:)-8ig34"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64_undef(_:)-8lvix": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar64_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar2",
          "text": "simd_uchar2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar64",
          "text": "simd_uchar64"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64_undef(_:)-8lvix",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar64_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar64_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar64_undef(_:)-8lvix"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64_undef(_:)-9jm47": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified eight-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar64_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar8",
          "text": "simd_uchar8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar64",
          "text": "simd_uchar64"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64_undef(_:)-9jm47",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar64_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar64_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar64_undef(_:)-9jm47"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64_undef(_:)-9ldf2": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified thirty two-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar64_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar64",
          "text": "simd_uchar64"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64_undef(_:)-9ldf2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar64_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar64_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar64_undef(_:)-9ldf2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64_undef(_:)-p0tj": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified sixteen-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar64_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar16",
          "text": "simd_uchar16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar64",
          "text": "simd_uchar64"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64_undef(_:)-p0tj",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar64_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar64_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar64_undef(_:)-p0tj"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-5la8o": {
      "abstract": [
        {
          "text": "Returns the maximum value of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_max"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar64",
          "text": "simd_uchar64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar64",
          "text": "simd_uchar64"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar64",
          "text": "simd_uchar64"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-5la8o",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_max"
        }
      ],
      "role": "symbol",
      "title": "simd_max(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_max(_:_:)-5la8o"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-ep1f": {
      "abstract": [
        {
          "text": "Returns the minimum value of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_min"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar64",
          "text": "simd_uchar64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar64",
          "text": "simd_uchar64"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar64",
          "text": "simd_uchar64"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-ep1f",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_min"
        }
      ],
      "role": "symbol",
      "title": "simd_min(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_min(_:_:)-ep1f"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-936l4": {
      "abstract": [
        {
          "text": "Returns the sum of all elements in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_add"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar64",
          "text": "simd_uchar64"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-936l4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_add"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_add(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_add(_:)-936l4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-micz": {
      "abstract": [
        {
          "text": "Returns the maximum value in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_max"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar64",
          "text": "simd_uchar64"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-micz",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_max"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_max(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_max(_:)-micz"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-jpn5": {
      "abstract": [
        {
          "text": "Returns the miniumum value in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_min"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar64",
          "text": "simd_uchar64"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-jpn5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_min"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_min(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_min(_:)-jpn5"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar1": {
      "abstract": [
        {
          "text": "A vector of one 8-bit unsigned integer element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uchar1"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uchar1"
        }
      ],
      "role": "symbol",
      "title": "simd_uchar1",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar16": {
      "abstract": [
        {
          "text": "A vector of sixteen 8-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uchar16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uchar16"
        }
      ],
      "role": "symbol",
      "title": "simd_uchar16",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar16"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar2": {
      "abstract": [
        {
          "text": "A vector of two 8-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uchar2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uchar2"
        }
      ],
      "role": "symbol",
      "title": "simd_uchar2",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar3": {
      "abstract": [
        {
          "text": "A vector of three 8-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uchar3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uchar3"
        }
      ],
      "role": "symbol",
      "title": "simd_uchar3",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar32": {
      "abstract": [
        {
          "text": "A vector of thirty-two 8-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uchar32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uchar32"
        }
      ],
      "role": "symbol",
      "title": "simd_uchar32",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar32"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar4": {
      "abstract": [
        {
          "text": "A vector of four 8-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uchar4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uchar4"
        }
      ],
      "role": "symbol",
      "title": "simd_uchar4",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar64": {
      "abstract": [
        {
          "text": "A vector of sixty-four 8-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uchar64"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar64",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uchar64"
        }
      ],
      "role": "symbol",
      "title": "simd_uchar64",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar64"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar8": {
      "abstract": [
        {
          "text": "A vector of eight 8-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uchar8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uchar8"
        }
      ],
      "role": "symbol",
      "title": "simd_uchar8",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar8"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s5UInt8V": {
      "abstract": [
        {
          "text": "An 8-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5UInt8V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt8",
      "type": "topic",
      "url": "/documentation/Swift/UInt8"
    },
    "doc://com.externally.resolved.symbol/s:s6SIMD64V": {
      "abstract": [
        {
          "text": "A vector of 64 scalar values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SIMD64"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SIMDScalarP",
          "text": "SIMDScalar"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6SIMD64V",
      "kind": "symbol",
      "role": "symbol",
      "title": "SIMD64",
      "type": "topic",
      "url": "/documentation/Swift/SIMD64"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Vector-Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_uchar1",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar2",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar3",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar4",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar8",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar16",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar32"
      ],
      "title": "Vector Data Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Functions-to-Create-Sixty-Four-Element-Vectors-From-Other-Vectors",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64(_:)-57u64",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64(_:)-5apn9",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64(_:)-51eby",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64(_:)-65i5u",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64(_:)-3wfeh",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64(_:)-56lh8",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64(_:)-1g5oc",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64(_:_:)",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64_undef(_:)-8lvix",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64_undef(_:)-8ig34",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64_undef(_:)-8fhu3",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64_undef(_:)-9jm47",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64_undef(_:)-p0tj",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64_undef(_:)-9ldf2"
      ],
      "title": "Functions to Create Sixty Four-Element Vectors From Other Vectors"
    },
    {
      "anchor": "Functions-to-Create-Sixty-Four-Element-Vectors-From-Scalar-Values",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64(_:)-9d1w7",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64_undef(_:)-6vlwv"
      ],
      "title": "Functions to Create Sixty Four-Element Vectors From Scalar Values"
    },
    {
      "anchor": "Reduce-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-jpn5",
        "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-micz",
        "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-936l4"
      ],
      "title": "Reduce Functions"
    },
    {
      "anchor": "Extrema-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-ep1f",
        "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-5la8o"
      ],
      "title": "Extrema Functions"
    },
    {
      "anchor": "Common-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-52h9h",
        "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-494kp"
      ],
      "title": "Common Functions"
    },
    {
      "anchor": "Logic-and-Bitwise-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-jl1j",
        "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-2m0jp",
        "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-2bway"
      ],
      "title": "Logic and Bitwise Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "simd_uchar64"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/simd"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Functions-to-Create-Sixty-Four-Element-Vectors-From-Other-Vectors",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64(_:)-57u64",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64(_:)-5apn9",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64(_:)-51eby",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64(_:)-65i5u",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64(_:)-3wfeh",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64(_:)-56lh8",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64(_:)-1g5oc",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64(_:_:)",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64_undef(_:)-8lvix",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64_undef(_:)-8ig34",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64_undef(_:)-8fhu3",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64_undef(_:)-9jm47",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64_undef(_:)-p0tj",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64_undef(_:)-9ldf2"
              ],
              "title": "Functions to Create Sixty Four-Element Vectors From Other Vectors"
            },
            {
              "anchor": "Functions-to-Create-Sixty-Four-Element-Vectors-From-Scalar-Values",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64(_:)-9d1w7",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar64_undef(_:)-6vlwv"
              ],
              "title": "Functions to Create Sixty Four-Element Vectors From Scalar Values"
            },
            {
              "anchor": "Reduce-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-jpn5",
                "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-micz",
                "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-936l4"
              ],
              "title": "Reduce Functions"
            },
            {
              "anchor": "Extrema-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-ep1f",
                "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-5la8o"
              ],
              "title": "Extrema Functions"
            },
            {
              "anchor": "Common-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-52h9h",
                "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-494kp"
              ],
              "title": "Common Functions"
            },
            {
              "anchor": "Logic-and-Bitwise-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-jl1j",
                "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-2m0jp",
                "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-2bway"
              ],
              "title": "Logic and Bitwise Functions"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Vector-Data-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_uchar1",
                "doc://com.apple.accelerate/documentation/simd/simd_uchar2",
                "doc://com.apple.accelerate/documentation/simd/simd_uchar3",
                "doc://com.apple.accelerate/documentation/simd/simd_uchar4",
                "doc://com.apple.accelerate/documentation/simd/simd_uchar8",
                "doc://com.apple.accelerate/documentation/simd/simd_uchar16",
                "doc://com.apple.accelerate/documentation/simd/simd_uchar32"
              ],
              "title": "Vector Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:]64c",
                    "text": "unsigned char __attribute__((ext_vector_type(64)))"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "simd_uchar64"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar2/title",
          "value": "simd_uchar2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar4/title",
          "value": "simd_uchar4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar64_undef(_:)-8fhu3/title",
          "value": "simd_make_uchar64_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar64_undef(_:)-8fhu3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar64_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar64_undef(_:)-p0tj/title",
          "value": "simd_make_uchar64_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar64_undef(_:)-p0tj/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar64_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar64(_:)-65i5u/title",
          "value": "simd_make_uchar64"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar64(_:)-65i5u/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar64/title",
          "value": "simd_uchar64"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar64/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar64/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar64(_:)-3wfeh/title",
          "value": "simd_make_uchar64"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar64(_:)-3wfeh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar3/title",
          "value": "simd_uchar3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar8/title",
          "value": "simd_uchar8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar64_undef(_:)-9jm47/title",
          "value": "simd_make_uchar64_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar64_undef(_:)-9jm47/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar64_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_max(_:_:)-5la8o/title",
          "value": "simd_max"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_max(_:_:)-5la8o/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_max"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar64(_:)-57u64/title",
          "value": "simd_make_uchar64"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar64(_:)-57u64/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_all(_:)-2m0jp/title",
          "value": "simd_all"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_all(_:)-2m0jp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_all"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar64(_:)-9d1w7/title",
          "value": "simd_make_uchar64"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar64(_:)-9d1w7/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar64(_:)-56lh8/title",
          "value": "simd_make_uchar64"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar64(_:)-56lh8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar1/title",
          "value": "simd_uchar1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar1/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_equal(_:_:)-494kp/title",
          "value": "simd_equal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_equal(_:_:)-494kp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_equal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_any(_:)-jl1j/title",
          "value": "simd_any"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_any(_:)-jl1j/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_any"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_min(_:_:)-ep1f/title",
          "value": "simd_min"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_min(_:_:)-ep1f/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_min"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_max(_:)-micz/title",
          "value": "simd_reduce_max"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_max(_:)-micz/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_max"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_clamp(_:_:_:)-52h9h/title",
          "value": "simd_clamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_clamp(_:_:_:)-52h9h/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_clamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_add(_:)-936l4/title",
          "value": "simd_reduce_add"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_add(_:)-936l4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_add"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar64_undef(_:)-8lvix/title",
          "value": "simd_make_uchar64_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar64_undef(_:)-8lvix/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar64_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_bitselect(_:_:_:)-2bway/title",
          "value": "simd_bitselect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_bitselect(_:_:_:)-2bway/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_bitselect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar64(_:)-1g5oc/title",
          "value": "simd_make_uchar64"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar64(_:)-1g5oc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar64_undef(_:)-9ldf2/title",
          "value": "simd_make_uchar64_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar64_undef(_:)-9ldf2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar64_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar64_undef(_:)-8ig34/title",
          "value": "simd_make_uchar64_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar64_undef(_:)-8ig34/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar64_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar64(_:)-5apn9/title",
          "value": "simd_make_uchar64"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar64(_:)-5apn9/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_min(_:)-jpn5/title",
          "value": "simd_reduce_min"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_min(_:)-jpn5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_min"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar16/title",
          "value": "simd_uchar16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar16/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar64_undef(_:)-6vlwv/title",
          "value": "simd_make_uchar64_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar64_undef(_:)-6vlwv/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar64_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar32/title",
          "value": "simd_uchar32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar32/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar64(_:_:)/title",
          "value": "simd_make_uchar64"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar64(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar64(_:)-51eby/title",
          "value": "simd_make_uchar64"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar64(_:)-51eby/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar64"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_uchar64"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/simd/simd_uchar64"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
