{
  "abstract": [
    {
      "text": "Returns a new vector from the specified eight-element vector, and other elements undefined.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_make_half16_undef(_:)-1lcb5"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_make_half16_undef#]8h#",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simd_make_half16_undef"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_half8",
        "text": "simd_half8"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_half16",
        "text": "simd_half16"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_make_half16_undef"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_make_half16_undef(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_make_half16_undef"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "other"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half8",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_half8",
              "text": "simd_half8"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half16",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_half16",
              "text": "simd_half16"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half16": {
      "abstract": [
        {
          "text": "A vector of sixteen 16-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_half16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_half16"
        }
      ],
      "role": "symbol",
      "title": "simd_half16",
      "type": "topic",
      "url": "/documentation/simd/simd_half16"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half8": {
      "abstract": [
        {
          "text": "A vector of eight 16-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_half8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_half8"
        }
      ],
      "role": "symbol",
      "title": "simd_half8",
      "type": "topic",
      "url": "/documentation/simd/simd_half8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_half16(_:)-18zo3": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified 32-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_half16"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half32",
          "text": "simd_half32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half16",
          "text": "simd_half16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_half16(_:)-18zo3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_half16"
        }
      ],
      "role": "symbol",
      "title": "simd_make_half16(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_half16(_:)-18zo3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_half16(_:)-2eeq3": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_half16"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half16",
          "text": "simd_half16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half16",
          "text": "simd_half16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_half16(_:)-2eeq3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_half16"
        }
      ],
      "role": "symbol",
      "title": "simd_make_half16(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_half16(_:)-2eeq3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_half16(_:)-7czq5": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified four-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_half16"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half4",
          "text": "simd_half4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half16",
          "text": "simd_half16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_half16(_:)-7czq5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_half16"
        }
      ],
      "role": "symbol",
      "title": "simd_make_half16(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_half16(_:)-7czq5"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_half16(_:)-7fwvg": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified three-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_half16"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half3",
          "text": "simd_half3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half16",
          "text": "simd_half16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_half16(_:)-7fwvg",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_half16"
        }
      ],
      "role": "symbol",
      "title": "simd_make_half16(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_half16(_:)-7fwvg"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_half16(_:)-7jegv": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_half16"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half2",
          "text": "simd_half2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half16",
          "text": "simd_half16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_half16(_:)-7jegv",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_half16"
        }
      ],
      "role": "symbol",
      "title": "simd_make_half16(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_half16(_:)-7jegv"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_half16(_:)-8jb49": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified eight-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_half16"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half8",
          "text": "simd_half8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half16",
          "text": "simd_half16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_half16(_:)-8jb49",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_half16"
        }
      ],
      "role": "symbol",
      "title": "simd_make_half16(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_half16(_:)-8jb49"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_half16(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_half16"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half8",
          "text": "simd_half8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half8",
          "text": "simd_half8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half16",
          "text": "simd_half16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_half16(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_half16"
        }
      ],
      "role": "symbol",
      "title": "simd_make_half16(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_half16(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_half16_undef(_:)-1lcb5": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified eight-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_half16_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half8",
          "text": "simd_half8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half16",
          "text": "simd_half16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_half16_undef(_:)-1lcb5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_half16_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_half16_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_half16_undef(_:)-1lcb5"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_half16_undef(_:)-hd79": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified four-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_half16_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half4",
          "text": "simd_half4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half16",
          "text": "simd_half16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_half16_undef(_:)-hd79",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_half16_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_half16_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_half16_undef(_:)-hd79"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_half16_undef(_:)-nn1z": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_half16_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half2",
          "text": "simd_half2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half16",
          "text": "simd_half16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_half16_undef(_:)-nn1z",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_half16_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_half16_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_half16_undef(_:)-nn1z"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_half16_undef(_:)-qkco": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified three-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_half16_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half3",
          "text": "simd_half3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half16",
          "text": "simd_half16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_half16_undef(_:)-qkco",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_half16_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_half16_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_half16_undef(_:)-qkco"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-create-16-element-vectors-from-other-vectors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_half16(_:)-7jegv",
        "doc://com.apple.accelerate/documentation/simd/simd_make_half16(_:)-7fwvg",
        "doc://com.apple.accelerate/documentation/simd/simd_make_half16(_:)-7czq5",
        "doc://com.apple.accelerate/documentation/simd/simd_make_half16(_:)-8jb49",
        "doc://com.apple.accelerate/documentation/simd/simd_make_half16(_:)-2eeq3",
        "doc://com.apple.accelerate/documentation/simd/simd_make_half16(_:)-18zo3",
        "doc://com.apple.accelerate/documentation/simd/simd_make_half16_undef(_:)-nn1z",
        "doc://com.apple.accelerate/documentation/simd/simd_make_half16_undef(_:)-qkco",
        "doc://com.apple.accelerate/documentation/simd/simd_make_half16_undef(_:)-hd79",
        "doc://com.apple.accelerate/documentation/simd/simd_make_half16(_:_:)"
      ],
      "title": "Functions to create 16-element vectors from other vectors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "simd_make_half16_undef"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_half16_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/simd"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Functions-to-create-16-element-vectors-from-other-vectors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_half16(_:)-7jegv",
                "doc://com.apple.accelerate/documentation/simd/simd_make_half16(_:)-7fwvg",
                "doc://com.apple.accelerate/documentation/simd/simd_make_half16(_:)-7czq5",
                "doc://com.apple.accelerate/documentation/simd/simd_make_half16(_:)-8jb49",
                "doc://com.apple.accelerate/documentation/simd/simd_make_half16(_:)-2eeq3",
                "doc://com.apple.accelerate/documentation/simd/simd_make_half16(_:)-18zo3",
                "doc://com.apple.accelerate/documentation/simd/simd_make_half16_undef(_:)-nn1z",
                "doc://com.apple.accelerate/documentation/simd/simd_make_half16_undef(_:)-qkco",
                "doc://com.apple.accelerate/documentation/simd/simd_make_half16_undef(_:)-hd79",
                "doc://com.apple.accelerate/documentation/simd/simd_make_half16(_:_:)"
              ],
              "title": "Functions to create 16-element vectors from other vectors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "static"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half16",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_half16",
                    "text": "simd_half16"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "simd_make_half16_undef"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half8",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_half8",
                    "text": "simd_half8"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "other"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half16(_:)-7jegv/title",
          "value": "simd_make_half16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half16(_:)-7jegv/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_half16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half8/title",
          "value": "simd_half8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half16(_:_:)/title",
          "value": "simd_make_half16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half16(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_half16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half16/title",
          "value": "simd_half16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half16/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half16(_:)-8jb49/title",
          "value": "simd_make_half16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half16(_:)-8jb49/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_half16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half16_undef(_:)-1lcb5/title",
          "value": "simd_make_half16_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half16_undef(_:)-1lcb5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_half16_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half16_undef(_:)-hd79/title",
          "value": "simd_make_half16_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half16_undef(_:)-hd79/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_half16_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half16(_:)-2eeq3/title",
          "value": "simd_make_half16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half16(_:)-2eeq3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_half16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half16(_:)-18zo3/title",
          "value": "simd_make_half16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half16(_:)-18zo3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_half16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half16_undef(_:)-qkco/title",
          "value": "simd_make_half16_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half16_undef(_:)-qkco/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_half16_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half16(_:)-7czq5/title",
          "value": "simd_make_half16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half16(_:)-7czq5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_half16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half16(_:)-7fwvg/title",
          "value": "simd_make_half16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half16(_:)-7fwvg/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_half16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half16_undef(_:)-nn1z/title",
          "value": "simd_make_half16_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half16_undef(_:)-nn1z/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_half16_undef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_make_half16_undef(_:)-1lcb5"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/simd/simd_make_half16_undef(_:)-1lcb5"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
