{
  "abstract": [
    {
      "text": "A vector of one 16-bit unsigned integer element.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_ushort1"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@simd_ushort1",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simd_ushort1"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_ushort1"
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "simd_ushort1"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_ushort1"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt16V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt16V",
              "text": "UInt16"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort1": {
      "abstract": [
        {
          "text": "A vector of one 16-bit unsigned integer element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ushort1"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ushort1"
        }
      ],
      "role": "symbol",
      "title": "simd_ushort1",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort16": {
      "abstract": [
        {
          "text": "A vector of sixteen 16-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ushort16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ushort16"
        }
      ],
      "role": "symbol",
      "title": "simd_ushort16",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort16"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort2": {
      "abstract": [
        {
          "text": "A vector of two 16-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ushort2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ushort2"
        }
      ],
      "role": "symbol",
      "title": "simd_ushort2",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort3": {
      "abstract": [
        {
          "text": "A vector of three 16-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ushort3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ushort3"
        }
      ],
      "role": "symbol",
      "title": "simd_ushort3",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort32": {
      "abstract": [
        {
          "text": "A vector of thirty-two 16-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ushort32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ushort32"
        }
      ],
      "role": "symbol",
      "title": "simd_ushort32",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort32"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort4": {
      "abstract": [
        {
          "text": "A vector of four 16-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ushort4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ushort4"
        }
      ],
      "role": "symbol",
      "title": "simd_ushort4",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort8": {
      "abstract": [
        {
          "text": "A vector of eight 16-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ushort8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ushort8"
        }
      ],
      "role": "symbol",
      "title": "simd_ushort8",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort8"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt16V": {
      "abstract": [
        {
          "text": "A 16-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt16"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt16V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt16",
      "type": "topic",
      "url": "/documentation/Swift/UInt16"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Vector-Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_ushort2",
        "doc://com.apple.accelerate/documentation/simd/simd_ushort3",
        "doc://com.apple.accelerate/documentation/simd/simd_ushort4",
        "doc://com.apple.accelerate/documentation/simd/simd_ushort8",
        "doc://com.apple.accelerate/documentation/simd/simd_ushort16",
        "doc://com.apple.accelerate/documentation/simd/simd_ushort32"
      ],
      "title": "Vector Data Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "simd_ushort1"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/simd"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Vector-Data-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_ushort2",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort3",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort4",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort8",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort16",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort32"
              ],
              "title": "Vector Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:s",
                    "text": "unsigned short"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "simd_ushort1"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort4/title",
          "value": "simd_ushort4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort1/title",
          "value": "simd_ushort1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort1/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort2/title",
          "value": "simd_ushort2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort16/title",
          "value": "simd_ushort16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort16/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort32/title",
          "value": "simd_ushort32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort32/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort3/title",
          "value": "simd_ushort3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort8/title",
          "value": "simd_ushort8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort8"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_ushort1"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/simd/simd_ushort1"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
