{
  "abstract": [
    {
      "text": "Tests if a single-precision point lies inside, on, or outside a sphere.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_insphere-5jw77"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_insphere#]3f#S0_#S0_#S0_#S0_#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_insphere"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_insphere"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_insphere"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:f",
              "text": "float"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_insphere"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float3",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_float3",
              "text": "simd_float3"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float3",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_float3",
              "text": "simd_float3"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__a"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float3",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_float3",
              "text": "simd_float3"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__b"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float3",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_float3",
              "text": "simd_float3"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__c"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float3",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_float3",
              "text": "simd_float3"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__d"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The point that the function tests.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "__x"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The first point that determines the sphere.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "__a"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The second point that determines the sphere.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "__b"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The third point that determines the sphere.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "__c"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The fourth point that determines the sphere.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "__d"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A value that indicates whether the point lies inside, on, or outside the specified sphere.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If the points ",
              "type": "text"
            },
            {
              "code": "a",
              "type": "codeVoice"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "code": "b",
              "type": "codeVoice"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "code": "c",
              "type": "codeVoice"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "code": "d",
              "type": "codeVoice"
            },
            {
              "text": " describe a positively-oriented sphere (that is, the sphere’s normals point away from its center), the function returns:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "A positive value if ",
                      "type": "text"
                    },
                    {
                      "code": "x",
                      "type": "codeVoice"
                    },
                    {
                      "text": " is inside the sphere",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Zero if ",
                      "type": "text"
                    },
                    {
                      "code": "x",
                      "type": "codeVoice"
                    },
                    {
                      "text": " is on the sphere",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "A negative value if ",
                      "type": "text"
                    },
                    {
                      "code": "x",
                      "type": "codeVoice"
                    },
                    {
                      "text": " is outside the sphere",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The function flips sign of the return value if the sphere is negatively-oriented (that is, the sphere’s normals point towards its center).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_cross-4jxj0": {
      "abstract": [
        {
          "text": "Returns the cross product of two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_cross"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_cross-4jxj0",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_cross",
      "type": "topic",
      "url": "/documentation/simd/simd_cross-4jxj0"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_dot-3ndxt": {
      "abstract": [
        {
          "text": "Returns the dot product of two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_dot"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_dot-3ndxt",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_dot",
      "type": "topic",
      "url": "/documentation/simd/simd_dot-3ndxt"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_fast_normalize-dj6": {
      "abstract": [
        {
          "text": "Returns the fast normalized vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_fast_normalize"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_fast_normalize-dj6",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_fast_normalize",
      "type": "topic",
      "url": "/documentation/simd/simd_fast_normalize-dj6"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_fast_project-7du9p": {
      "abstract": [
        {
          "text": "Returns the fast projected vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_fast_project"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_fast_project-7du9p",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_fast_project",
      "type": "topic",
      "url": "/documentation/simd/simd_fast_project-7du9p"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float3": {
      "abstract": [
        {
          "text": "A vector of three 32-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_float3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_float3"
        }
      ],
      "role": "symbol",
      "title": "simd_float3",
      "type": "topic",
      "url": "/documentation/simd/simd_float3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_insphere-5jw77": {
      "abstract": [
        {
          "text": "Tests if a single-precision point lies inside, on, or outside a sphere.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_insphere"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_insphere-5jw77",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_insphere",
      "type": "topic",
      "url": "/documentation/simd/simd_insphere-5jw77"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_normalize-9c3mv": {
      "abstract": [
        {
          "text": "Returns a vector pointing in the same direction of the supplied vector, with a length of 1.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_normalize"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_normalize-9c3mv",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_normalize",
      "type": "topic",
      "url": "/documentation/simd/simd_normalize-9c3mv"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_orient-6ae1u": {
      "abstract": [
        {
          "text": "Tests the orientation of the three supplied vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_orient"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_orient-6ae1u",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_orient",
      "type": "topic",
      "url": "/documentation/simd/simd_orient-6ae1u"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_orient-kj8u": {
      "abstract": [
        {
          "text": "Tests the orientation of the four supplied vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_orient"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_orient-kj8u",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_orient",
      "type": "topic",
      "url": "/documentation/simd/simd_orient-kj8u"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_precise_normalize-4z9ah": {
      "abstract": [
        {
          "text": "Returns the precise normalized vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_precise_normalize"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_precise_normalize-4z9ah",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_precise_normalize",
      "type": "topic",
      "url": "/documentation/simd/simd_precise_normalize-4z9ah"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_precise_project-3sxbh": {
      "abstract": [
        {
          "text": "Returns the precise projected vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_precise_project"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_precise_project-3sxbh",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_precise_project",
      "type": "topic",
      "url": "/documentation/simd/simd_precise_project-3sxbh"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_project-6qmce": {
      "abstract": [
        {
          "text": "Returns the first vector projected onto the second vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_project"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_project-6qmce",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_project",
      "type": "topic",
      "url": "/documentation/simd/simd_project-6qmce"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reflect-4bvhy": {
      "abstract": [
        {
          "text": "Returns the reflection direction of an incident vector and a unit normal vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_reflect"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reflect-4bvhy",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_reflect",
      "type": "topic",
      "url": "/documentation/simd/simd_reflect-4bvhy"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_refract-2fvfh": {
      "abstract": [
        {
          "text": "Returns the refraction direction of an incident vector, a unit normal vector, and an index of refraction eta.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_refract"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_refract-2fvfh",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_refract",
      "type": "topic",
      "url": "/documentation/simd/simd_refract-2fvfh"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Geometry-Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_cross-4jxj0",
        "doc://com.apple.accelerate/documentation/simd/simd_dot-3ndxt",
        "doc://com.apple.accelerate/documentation/simd/simd_normalize-9c3mv",
        "doc://com.apple.accelerate/documentation/simd/simd_fast_normalize-dj6",
        "doc://com.apple.accelerate/documentation/simd/simd_precise_normalize-4z9ah",
        "doc://com.apple.accelerate/documentation/simd/simd_orient-6ae1u",
        "doc://com.apple.accelerate/documentation/simd/simd_orient-kj8u",
        "doc://com.apple.accelerate/documentation/simd/simd_project-6qmce",
        "doc://com.apple.accelerate/documentation/simd/simd_fast_project-7du9p",
        "doc://com.apple.accelerate/documentation/simd/simd_precise_project-3sxbh",
        "doc://com.apple.accelerate/documentation/simd/simd_reflect-4bvhy",
        "doc://com.apple.accelerate/documentation/simd/simd_refract-2fvfh"
      ],
      "title": "Geometry Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float3/title",
          "value": "simd_float3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float3"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_insphere-5jw77"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
