{
  "abstract": [
    {
      "text": "A matrix of four columns and three rows that contains double-precision values.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_double4x3"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@SA@simd_double4x3",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simd_double4x3"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_double4x3"
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "simd_double4x3"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_double4x3"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/double4x3": {
      "abstract": [
        {
          "text": "A type alias for a double-precision 4 x 3 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "double4x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/double4x3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "double4x3"
        }
      ],
      "role": "symbol",
      "title": "double4x3",
      "type": "topic",
      "url": "/documentation/simd/double4x3"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_double4x3": {
      "abstract": [
        {
          "text": "A type alias for a double-precision 4 x 3 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matrix_double4x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_double4x3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "matrix_double4x3"
        }
      ],
      "role": "symbol",
      "title": "matrix_double4x3",
      "type": "topic",
      "url": "/documentation/simd/matrix_double4x3"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_equal(_:_:)-1x3ox": {
      "abstract": [
        {
          "text": "Returns true if every element in a matrix is exactly equal to the corresponding element in a second matrix, and otherwise returns false.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matrix_equal"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double4x3",
          "text": "simd_double4x3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double4x3",
          "text": "simd_double4x3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_equal(_:_:)-1x3ox",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_equal(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/matrix_equal(_:_:)-1x3ox"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_from_columns(_:_:_:_:)-7g6mu": {
      "abstract": [
        {
          "text": "Returns a new matrix with the specified columns.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matrix_from_columns"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD3V",
          "text": "SIMD3"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD3V",
          "text": "SIMD3"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD3V",
          "text": "SIMD3"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD3V",
          "text": "SIMD3"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double4x3",
          "text": "simd_double4x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_from_columns(_:_:_:_:)-7g6mu",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_from_columns(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/matrix_from_columns(_:_:_:_:)-7g6mu"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_from_rows(_:_:_:)-19j6n": {
      "abstract": [
        {
          "text": "Returns a new matrix with the specified rows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matrix_from_rows"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD4V",
          "text": "SIMD4"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD4V",
          "text": "SIMD4"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD4V",
          "text": "SIMD4"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double4x3",
          "text": "simd_double4x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_from_rows(_:_:_:)-19j6n",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_from_rows(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/matrix_from_rows(_:_:_:)-19j6n"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_multiply-1q0om": {
      "abstract": [
        {
          "text": "Returns the product of a three-element vector and a 4 x 3 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "matrix_multiply"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_multiply-1q0om",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_multiply",
      "type": "topic",
      "url": "/documentation/simd/matrix_multiply-1q0om"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_multiply-2txdr": {
      "abstract": [
        {
          "text": "Returns the product of a 2 x 3 matrix and a 4 x 2 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "matrix_multiply"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_multiply-2txdr",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_multiply",
      "type": "topic",
      "url": "/documentation/simd/matrix_multiply-2txdr"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_multiply-4obd4": {
      "abstract": [
        {
          "text": "Returns the product of a 4 x 3 matrix and a four-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "matrix_multiply"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_multiply-4obd4",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_multiply",
      "type": "topic",
      "url": "/documentation/simd/matrix_multiply-4obd4"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_multiply-8s05c": {
      "abstract": [
        {
          "text": "Returns the product of a 3 x 3 matrix and a 4 x 3 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "matrix_multiply"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_multiply-8s05c",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_multiply",
      "type": "topic",
      "url": "/documentation/simd/matrix_multiply-8s05c"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_multiply-9g2os": {
      "abstract": [
        {
          "text": "Returns the product of a 4 x 3 matrix and a 4 x 4 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "matrix_multiply"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_multiply-9g2os",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_multiply",
      "type": "topic",
      "url": "/documentation/simd/matrix_multiply-9g2os"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_scale-4to0w": {
      "abstract": [
        {
          "text": "Returns the product of a scalar value and a matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "matrix_scale"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_scale-4to0w",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_scale",
      "type": "topic",
      "url": "/documentation/simd/matrix_scale-4to0w"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_transpose(_:)-23ibz": {
      "abstract": [
        {
          "text": "Returns the transpose of a matrix.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matrix_transpose"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double3x4",
          "text": "simd_double3x4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:4simd9double4x3a",
          "text": "double4x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_transpose(_:)-23ibz",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_transpose(_:)",
      "type": "topic",
      "url": "/documentation/simd/matrix_transpose(_:)-23ibz"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_add-5827c": {
      "abstract": [
        {
          "text": "Returns the sum of two matrices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_add"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_add-5827c",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_add",
      "type": "topic",
      "url": "/documentation/simd/simd_add-5827c"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_almost_equal_elements-1d74k": {
      "abstract": [
        {
          "text": "Returns true if every element in a matrix is within a specified tolerance to the corresponding element in a second matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_almost_equal_elements"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_almost_equal_elements-1d74k",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_almost_equal_elements",
      "type": "topic",
      "url": "/documentation/simd/simd_almost_equal_elements-1d74k"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_almost_equal_elements_relative-39069": {
      "abstract": [
        {
          "text": "Returns true if every element in a matrix is within a specified double-precision relative tolerance to the corresponding element in a second matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_almost_equal_elements_relative"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_almost_equal_elements_relative-39069",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_almost_equal_elements_relative",
      "type": "topic",
      "url": "/documentation/simd/simd_almost_equal_elements_relative-39069"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double2x2": {
      "abstract": [
        {
          "text": "A matrix of two columns and two rows that contains double-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_double2x2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double2x2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_double2x2"
        }
      ],
      "role": "symbol",
      "title": "simd_double2x2",
      "type": "topic",
      "url": "/documentation/simd/simd_double2x2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double2x3": {
      "abstract": [
        {
          "text": "A matrix of two columns and three rows that contains double-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_double2x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double2x3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_double2x3"
        }
      ],
      "role": "symbol",
      "title": "simd_double2x3",
      "type": "topic",
      "url": "/documentation/simd/simd_double2x3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double2x4": {
      "abstract": [
        {
          "text": "A matrix of two columns and four rows that contains double-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_double2x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double2x4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_double2x4"
        }
      ],
      "role": "symbol",
      "title": "simd_double2x4",
      "type": "topic",
      "url": "/documentation/simd/simd_double2x4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double3x2": {
      "abstract": [
        {
          "text": "A matrix of three columns and two rows that contains double-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_double3x2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double3x2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_double3x2"
        }
      ],
      "role": "symbol",
      "title": "simd_double3x2",
      "type": "topic",
      "url": "/documentation/simd/simd_double3x2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double3x3": {
      "abstract": [
        {
          "text": "A matrix of three columns and three rows that contains double-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_double3x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double3x3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_double3x3"
        }
      ],
      "role": "symbol",
      "title": "simd_double3x3",
      "type": "topic",
      "url": "/documentation/simd/simd_double3x3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double3x4": {
      "abstract": [
        {
          "text": "A matrix of three columns and four rows that contains double-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_double3x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double3x4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_double3x4"
        }
      ],
      "role": "symbol",
      "title": "simd_double3x4",
      "type": "topic",
      "url": "/documentation/simd/simd_double3x4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double4x2": {
      "abstract": [
        {
          "text": "A matrix of four columns and two rows that contains double-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_double4x2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4x2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_double4x2"
        }
      ],
      "role": "symbol",
      "title": "simd_double4x2",
      "type": "topic",
      "url": "/documentation/simd/simd_double4x2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double4x3": {
      "abstract": [
        {
          "text": "A matrix of four columns and three rows that contains double-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_double4x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4x3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_double4x3"
        }
      ],
      "role": "symbol",
      "title": "simd_double4x3",
      "type": "topic",
      "url": "/documentation/simd/simd_double4x3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double4x3/*(_:_:)-13lud": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "*"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double4x3",
          "text": "simd_double4x3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double4x3",
          "text": "simd_double4x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4x3/*(_:_:)-13lud",
      "kind": "symbol",
      "role": "symbol",
      "title": "*(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double4x3/*(_:_:)-13lud"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double4x3/*(_:_:)-3vmls": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "*"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double4x3",
          "text": "simd_double4x3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:4simd9double4x4a",
          "text": "double4x4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:4simd9double4x3a",
          "text": "double4x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4x3/*(_:_:)-3vmls",
      "kind": "symbol",
      "role": "symbol",
      "title": "*(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double4x3/*(_:_:)-3vmls"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double4x3/*(_:_:)-4q5li": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "*"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double4x3",
          "text": "simd_double4x3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double4x3",
          "text": "simd_double4x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4x3/*(_:_:)-4q5li",
      "kind": "symbol",
      "role": "symbol",
      "title": "*(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double4x3/*(_:_:)-4q5li"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double4x3/*(_:_:)-61nnq": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "*"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double4x3",
          "text": "simd_double4x3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:4simd9double3x4a",
          "text": "double3x4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:4simd9double3x3a",
          "text": "double3x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4x3/*(_:_:)-61nnq",
      "kind": "symbol",
      "role": "symbol",
      "title": "*(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double4x3/*(_:_:)-61nnq"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double4x3/*(_:_:)-6sw55": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "*"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double4x3",
          "text": "simd_double4x3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD4V",
          "text": "SIMD4"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD3V",
          "text": "SIMD3"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4x3/*(_:_:)-6sw55",
      "kind": "symbol",
      "role": "symbol",
      "title": "*(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double4x3/*(_:_:)-6sw55"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double4x3/*(_:_:)-7362q": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "*"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD3V",
          "text": "SIMD3"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double4x3",
          "text": "simd_double4x3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD4V",
          "text": "SIMD4"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4x3/*(_:_:)-7362q",
      "kind": "symbol",
      "role": "symbol",
      "title": "*(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double4x3/*(_:_:)-7362q"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double4x3/*(_:_:)-8ugfy": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "*"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double4x3",
          "text": "simd_double4x3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:4simd9double2x4a",
          "text": "double2x4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:4simd9double2x3a",
          "text": "double2x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4x3/*(_:_:)-8ugfy",
      "kind": "symbol",
      "role": "symbol",
      "title": "*(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double4x3/*(_:_:)-8ugfy"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double4x3/*=(_:_:)-2x6ni": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "*="
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "inout"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double4x3",
          "text": "simd_double4x3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:4simd9double4x4a",
          "text": "double4x4"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4x3/*=(_:_:)-2x6ni",
      "kind": "symbol",
      "role": "symbol",
      "title": "*=(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double4x3/*=(_:_:)-2x6ni"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double4x3/*=(_:_:)-4o6cd": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "*="
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "inout"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double4x3",
          "text": "simd_double4x3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4x3/*=(_:_:)-4o6cd",
      "kind": "symbol",
      "role": "symbol",
      "title": "*=(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double4x3/*=(_:_:)-4o6cd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double4x3/+(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "+"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double4x3",
          "text": "simd_double4x3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double4x3",
          "text": "simd_double4x3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double4x3",
          "text": "simd_double4x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4x3/+(_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "+(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double4x3/+(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double4x3/+=(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "+="
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "inout"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double4x3",
          "text": "simd_double4x3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double4x3",
          "text": "simd_double4x3"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4x3/+=(_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "+=(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double4x3/+=(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double4x3/-(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "-"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double4x3",
          "text": "simd_double4x3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double4x3",
          "text": "simd_double4x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4x3/-(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "-(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double4x3/-(_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double4x3/-(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "-"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double4x3",
          "text": "simd_double4x3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double4x3",
          "text": "simd_double4x3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double4x3",
          "text": "simd_double4x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4x3/-(_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "-(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double4x3/-(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double4x3/-=(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "-="
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "inout"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double4x3",
          "text": "simd_double4x3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double4x3",
          "text": "simd_double4x3"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4x3/-=(_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "-=(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double4x3/-=(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double4x3/cmatrix": {
      "abstract": [
        {
          "text": "Returns the matrix as the corresponding C matrix type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cmatrix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double4x3",
          "text": "simd_double4x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4x3/cmatrix",
      "kind": "symbol",
      "role": "symbol",
      "title": "cmatrix",
      "type": "topic",
      "url": "/documentation/simd/simd_double4x3/cmatrix"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double4x3/columns": {
      "abstract": [
        {
          "text": "The columns of the matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "columns"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double3",
          "text": "simd_double3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double3",
          "text": "simd_double3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double3",
          "text": "simd_double3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double3",
          "text": "simd_double3"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4x3/columns",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "columns"
        }
      ],
      "role": "symbol",
      "title": "columns",
      "type": "topic",
      "url": "/documentation/simd/simd_double4x3/columns"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double4x3/init()": {
      "abstract": [
        {
          "text": "Creates a new matrix with uninitialized memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4x3/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/simd/simd_double4x3/init()"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double4x3/init(_:)-24exh": {
      "abstract": [
        {
          "text": "Creates a new matrix from an array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD3V",
          "text": "SIMD3"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">])"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4x3/init(_:)-24exh",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double4x3/init(_:)-24exh"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double4x3/init(_:)-30jps": {
      "abstract": [
        {
          "text": "Creates a new matrix with the specified matrix.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double4x3",
          "text": "simd_double4x3"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4x3/init(_:)-30jps",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double4x3/init(_:)-30jps"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double4x3/init(_:)-lh76": {
      "abstract": [
        {
          "text": "Creates a new matrix with the specified scalar value on the main diagonal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4x3/init(_:)-lh76",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double4x3/init(_:)-lh76"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double4x3/init(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a new matrix with the specified vectors as columns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD3V",
          "text": "SIMD3"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD3V",
          "text": "SIMD3"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD3V",
          "text": "SIMD3"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD3V",
          "text": "SIMD3"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4x3/init(_:_:_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double4x3/init(_:_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double4x3/init(columns:)": {
      "abstract": [
        {
          "text": "Creates a new matrix with the specified columns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "columns"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double3",
          "text": "simd_double3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double3",
          "text": "simd_double3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double3",
          "text": "simd_double3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double3",
          "text": "simd_double3"
        },
        {
          "kind": "text",
          "text": "))"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4x3/init(columns:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(columns:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double4x3/init(columns:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double4x3/init(diagonal:)": {
      "abstract": [
        {
          "text": "Creates a new matrix with the specified vector on the main diagonal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "diagonal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD3V",
          "text": "SIMD3"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4x3/init(diagonal:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(diagonal:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double4x3/init(diagonal:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double4x3/init(rows:)": {
      "abstract": [
        {
          "text": "Creates a new matrix with the specified rows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rows"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD4V",
          "text": "SIMD4"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">])"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4x3/init(rows:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rows:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double4x3/init(rows:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double4x3/subscript(_:)": {
      "abstract": [
        {
          "text": "Accesses the column at the specified position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD3V",
          "text": "SIMD3"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4x3/subscript(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscript(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double4x3/subscript(_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double4x3/subscript(_:_:)": {
      "abstract": [
        {
          "text": "Accesses the element at the specified position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4x3/subscript(_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscript(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double4x3/subscript(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double4x3/transpose": {
      "abstract": [
        {
          "text": "The transpose of the matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transpose"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:4simd9double3x4a",
          "text": "double3x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4x3/transpose",
      "kind": "symbol",
      "role": "symbol",
      "title": "transpose",
      "type": "topic",
      "url": "/documentation/simd/simd_double4x3/transpose"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double4x4": {
      "abstract": [
        {
          "text": "A matrix of four columns and four rows that contains double-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_double4x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4x4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_double4x4"
        }
      ],
      "role": "symbol",
      "title": "simd_double4x4",
      "type": "topic",
      "url": "/documentation/simd/simd_double4x4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_equal-9yy3z": {
      "abstract": [
        {
          "text": "Returns true if every element in a matrix is exactly equal to the corresponding element in a second matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_equal"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_equal-9yy3z",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_equal",
      "type": "topic",
      "url": "/documentation/simd/simd_equal-9yy3z"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_linear_combination-7zah2": {
      "abstract": [
        {
          "text": "Returns the linear combination of two scalar values and two matrices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_linear_combination"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_linear_combination-7zah2",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_linear_combination",
      "type": "topic",
      "url": "/documentation/simd/simd_linear_combination-7zah2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_matrix(_:_:_:_:)-4swfv": {
      "abstract": [
        {
          "text": "Returns a new matrix with the specified columns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_matrix"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double3",
          "text": "simd_double3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double3",
          "text": "simd_double3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double3",
          "text": "simd_double3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double3",
          "text": "simd_double3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double4x3",
          "text": "simd_double4x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_matrix(_:_:_:_:)-4swfv",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_matrix"
        }
      ],
      "role": "symbol",
      "title": "simd_matrix(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_matrix(_:_:_:_:)-4swfv"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_matrix_from_rows(_:_:_:)-6525o": {
      "abstract": [
        {
          "text": "Returns a new matrix with the specified rows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_matrix_from_rows"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double4x3",
          "text": "simd_double4x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_matrix_from_rows(_:_:_:)-6525o",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_matrix_from_rows"
        }
      ],
      "role": "symbol",
      "title": "simd_matrix_from_rows(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_matrix_from_rows(_:_:_:)-6525o"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_mul-1ly1": {
      "abstract": [
        {
          "text": "Returns the product of a 3 x 3 matrix and a 4 x 3 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_mul"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_mul-1ly1",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_mul",
      "type": "topic",
      "url": "/documentation/simd/simd_mul-1ly1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_mul-24gts": {
      "abstract": [
        {
          "text": "Returns the product of a 4 x 3 matrix and a four-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_mul"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_mul-24gts",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_mul",
      "type": "topic",
      "url": "/documentation/simd/simd_mul-24gts"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_mul-2ykj4": {
      "abstract": [
        {
          "text": "Returns the product of a three-element vector and a 4 x 3 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_mul"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_mul-2ykj4",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_mul",
      "type": "topic",
      "url": "/documentation/simd/simd_mul-2ykj4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_mul-33ps1": {
      "abstract": [
        {
          "text": "Returns the product of a 2 x 3 matrix and a 4 x 2 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_mul"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_mul-33ps1",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_mul",
      "type": "topic",
      "url": "/documentation/simd/simd_mul-33ps1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_mul-9tjlv": {
      "abstract": [
        {
          "text": "Returns the product of a scalar value and a 4 x 3 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_mul"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_mul-9tjlv",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_mul",
      "type": "topic",
      "url": "/documentation/simd/simd_mul-9tjlv"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_mul-cmf2": {
      "abstract": [
        {
          "text": "Returns the product of a 4 x 3 matrix and a 4 x 4 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_mul"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_mul-cmf2",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_mul",
      "type": "topic",
      "url": "/documentation/simd/simd_mul-cmf2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_sub-7r2k2": {
      "abstract": [
        {
          "text": "Returns the difference of two matrices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_sub"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_sub-7r2k2",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_sub",
      "type": "topic",
      "url": "/documentation/simd/simd_sub-7r2k2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_transpose-xo7a": {
      "abstract": [
        {
          "text": "Returns the transpose of a matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_transpose"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_transpose-xo7a",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_transpose",
      "type": "topic",
      "url": "/documentation/simd/simd_transpose-xo7a"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s8CopyableP": {
      "abstract": [
        {
          "text": "A type whose values can be implicitly or explicitly copied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8CopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Copyable",
      "type": "topic",
      "url": "/documentation/Swift/Copyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:s8CopyableP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Matrix-structures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_double2x2",
        "doc://com.apple.accelerate/documentation/simd/simd_double2x3",
        "doc://com.apple.accelerate/documentation/simd/simd_double2x4",
        "doc://com.apple.accelerate/documentation/simd/simd_double3x2",
        "doc://com.apple.accelerate/documentation/simd/simd_double3x3",
        "doc://com.apple.accelerate/documentation/simd/simd_double3x4",
        "doc://com.apple.accelerate/documentation/simd/simd_double4x2",
        "doc://com.apple.accelerate/documentation/simd/simd_double4x4"
      ],
      "title": "Matrix structures"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_double4x3/init()",
        "doc://com.apple.accelerate/documentation/simd/simd_double4x3/init(_:)-lh76",
        "doc://com.apple.accelerate/documentation/simd/simd_double4x3/init(diagonal:)",
        "doc://com.apple.accelerate/documentation/simd/simd_double4x3/init(_:)-24exh",
        "doc://com.apple.accelerate/documentation/simd/simd_double4x3/init(_:_:_:_:)",
        "doc://com.apple.accelerate/documentation/simd/simd_double4x3/init(columns:)",
        "doc://com.apple.accelerate/documentation/simd/simd_double4x3/init(rows:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Matrix-Properties",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_double4x3/transpose",
        "doc://com.apple.accelerate/documentation/simd/simd_double4x3/columns"
      ],
      "title": "Matrix Properties"
    },
    {
      "anchor": "Matrix-Creation-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_matrix(_:_:_:_:)-4swfv",
        "doc://com.apple.accelerate/documentation/simd/simd_matrix_from_rows(_:_:_:)-6525o",
        "doc://com.apple.accelerate/documentation/simd/matrix_from_rows(_:_:_:)-19j6n"
      ],
      "title": "Matrix Creation Functions"
    },
    {
      "anchor": "Element-Access",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_double4x3/subscript(_:)",
        "doc://com.apple.accelerate/documentation/simd/simd_double4x3/subscript(_:_:)"
      ],
      "title": "Element Access"
    },
    {
      "anchor": "Type-Aliases",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/double4x3",
        "doc://com.apple.accelerate/documentation/simd/matrix_double4x3"
      ],
      "title": "Type Aliases"
    },
    {
      "anchor": "Deprecated-Symbols",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/matrix_from_columns(_:_:_:_:)-7g6mu",
        "doc://com.apple.accelerate/documentation/simd/matrix_equal(_:_:)-1x3ox",
        "doc://com.apple.accelerate/documentation/simd/matrix_transpose(_:)-23ibz",
        "doc://com.apple.accelerate/documentation/simd/simd_double4x3/init(_:)-30jps",
        "doc://com.apple.accelerate/documentation/simd/simd_double4x3/cmatrix"
      ],
      "title": "Deprecated Symbols"
    },
    {
      "anchor": "Operators",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_double4x3/*(_:_:)-13lud",
        "doc://com.apple.accelerate/documentation/simd/simd_double4x3/*(_:_:)-3vmls",
        "doc://com.apple.accelerate/documentation/simd/simd_double4x3/*(_:_:)-4q5li",
        "doc://com.apple.accelerate/documentation/simd/simd_double4x3/*(_:_:)-61nnq",
        "doc://com.apple.accelerate/documentation/simd/simd_double4x3/*(_:_:)-6sw55",
        "doc://com.apple.accelerate/documentation/simd/simd_double4x3/*(_:_:)-7362q",
        "doc://com.apple.accelerate/documentation/simd/simd_double4x3/*(_:_:)-8ugfy",
        "doc://com.apple.accelerate/documentation/simd/simd_double4x3/*=(_:_:)-2x6ni",
        "doc://com.apple.accelerate/documentation/simd/simd_double4x3/*=(_:_:)-4o6cd",
        "doc://com.apple.accelerate/documentation/simd/simd_double4x3/+(_:_:)",
        "doc://com.apple.accelerate/documentation/simd/simd_double4x3/+=(_:_:)",
        "doc://com.apple.accelerate/documentation/simd/simd_double4x3/-(_:)",
        "doc://com.apple.accelerate/documentation/simd/simd_double4x3/-(_:_:)",
        "doc://com.apple.accelerate/documentation/simd/simd_double4x3/-=(_:_:)"
      ],
      "title": "Operators"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "simd_double4x3"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double4x3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double4x3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/simd"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Matrix-Properties",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_double4x3/columns"
              ],
              "title": "Matrix Properties"
            },
            {
              "anchor": "Matrix-Creation-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_matrix(_:_:_:_:)-4swfv",
                "doc://com.apple.accelerate/documentation/simd/simd_matrix_from_rows(_:_:_:)-6525o"
              ],
              "title": "Matrix Creation Functions"
            },
            {
              "anchor": "Math-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_add-5827c",
                "doc://com.apple.accelerate/documentation/simd/simd_sub-7r2k2",
                "doc://com.apple.accelerate/documentation/simd/matrix_scale-4to0w"
              ],
              "title": "Math Functions"
            },
            {
              "anchor": "Matrix-Scalar-Multiplication-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_mul-9tjlv"
              ],
              "title": "Matrix-Scalar Multiplication Functions"
            },
            {
              "anchor": "Matrix-Vector-Multiplication-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_mul-2ykj4",
                "doc://com.apple.accelerate/documentation/simd/matrix_multiply-1q0om",
                "doc://com.apple.accelerate/documentation/simd/simd_mul-24gts",
                "doc://com.apple.accelerate/documentation/simd/matrix_multiply-4obd4"
              ],
              "title": "Matrix-Vector Multiplication Functions"
            },
            {
              "anchor": "Matrix-Matrix-Multiplication-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_mul-33ps1",
                "doc://com.apple.accelerate/documentation/simd/matrix_multiply-2txdr",
                "doc://com.apple.accelerate/documentation/simd/simd_mul-1ly1",
                "doc://com.apple.accelerate/documentation/simd/matrix_multiply-8s05c",
                "doc://com.apple.accelerate/documentation/simd/simd_mul-cmf2",
                "doc://com.apple.accelerate/documentation/simd/matrix_multiply-9g2os"
              ],
              "title": "Matrix-Matrix Multiplication Functions"
            },
            {
              "anchor": "Equality-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_equal-9yy3z",
                "doc://com.apple.accelerate/documentation/simd/simd_almost_equal_elements-1d74k",
                "doc://com.apple.accelerate/documentation/simd/simd_almost_equal_elements_relative-39069"
              ],
              "title": "Equality Functions"
            },
            {
              "anchor": "Linear-Combination-Function",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_linear_combination-7zah2"
              ],
              "title": "Linear Combination Function"
            },
            {
              "anchor": "Transpose-Function",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_transpose-xo7a"
              ],
              "title": "Transpose Function"
            },
            {
              "anchor": "Type-Aliases",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/matrix_double4x3"
              ],
              "title": "Type Aliases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Matrix-structures",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_double2x2",
                "doc://com.apple.accelerate/documentation/simd/simd_double2x3",
                "doc://com.apple.accelerate/documentation/simd/simd_double2x4",
                "doc://com.apple.accelerate/documentation/simd/simd_double3x2",
                "doc://com.apple.accelerate/documentation/simd/simd_double3x3",
                "doc://com.apple.accelerate/documentation/simd/simd_double3x4",
                "doc://com.apple.accelerate/documentation/simd/simd_double4x2",
                "doc://com.apple.accelerate/documentation/simd/simd_double4x4"
              ],
              "title": "Matrix structures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "simd_double4x3"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4x3/title",
          "value": "simd_double4x3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4x3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double4x3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4x3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double4x3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4x2/title",
          "value": "simd_double4x2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4x2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double4x2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4x2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double4x2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1matrix_double4x3/title",
          "value": "matrix_double4x3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1matrix_double4x3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "matrix_double4x3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1matrix_double4x3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "matrix_double4x3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double2x3/title",
          "value": "simd_double2x3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double2x3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double2x3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double2x3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double2x3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_matrix_from_rows(_:_:_:)-6525o/title",
          "value": "simd_matrix_from_rows"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_matrix_from_rows(_:_:_:)-6525o/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_matrix_from_rows"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_matrix(_:_:_:_:)-4swfv/title",
          "value": "simd_matrix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_matrix(_:_:_:_:)-4swfv/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_matrix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double2x4/title",
          "value": "simd_double2x4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double2x4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double2x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double2x4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double2x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4x4/title",
          "value": "simd_double4x4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4x4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double4x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4x4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double4x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double3x4/title",
          "value": "simd_double3x4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double3x4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double3x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double3x4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double3x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double2x2/title",
          "value": "simd_double2x2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double2x2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double2x2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double2x2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double2x2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double3x3/title",
          "value": "simd_double3x3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double3x3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double3x3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double3x3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double3x3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double3x2/title",
          "value": "simd_double3x2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double3x2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double3x2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double3x2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double3x2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4x3~1columns/title",
          "value": "columns"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4x3~1columns/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "columns"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_double4x3"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/simd/simd_double4x3"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
