{
  "abstract": [
    {
      "text": "Returns a new vector from the specified two-element vector, and other elements undefined.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_make_half32_undef(_:)-3w7jb"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_make_half32_undef#]2h#",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simd_make_half32_undef"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_half2",
        "text": "simd_half2"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_half32",
        "text": "simd_half32"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_make_half32_undef"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_make_half32_undef(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_make_half32_undef"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "other"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_half2",
              "text": "simd_half2"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half32",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_half32",
              "text": "simd_half32"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half2": {
      "abstract": [
        {
          "text": "A vector of two 16-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_half2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_half2"
        }
      ],
      "role": "symbol",
      "title": "simd_half2",
      "type": "topic",
      "url": "/documentation/simd/simd_half2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half32": {
      "abstract": [
        {
          "text": "A vector of thirty-two 16-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_half32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_half32"
        }
      ],
      "role": "symbol",
      "title": "simd_half32",
      "type": "topic",
      "url": "/documentation/simd/simd_half32"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_half32(_:)-6xe53": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified 16-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_half32"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half16",
          "text": "simd_half16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half32",
          "text": "simd_half32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_half32(_:)-6xe53",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_half32"
        }
      ],
      "role": "symbol",
      "title": "simd_make_half32(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_half32(_:)-6xe53"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_half32(_:)-80qof": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_half32"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half32",
          "text": "simd_half32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half32",
          "text": "simd_half32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_half32(_:)-80qof",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_half32"
        }
      ],
      "role": "symbol",
      "title": "simd_make_half32(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_half32(_:)-80qof"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_half32(_:)-82w1c": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified four-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_half32"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half4",
          "text": "simd_half4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half32",
          "text": "simd_half32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_half32(_:)-82w1c",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_half32"
        }
      ],
      "role": "symbol",
      "title": "simd_make_half32(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_half32(_:)-82w1c"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_half32(_:)-8kum5": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified three-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_half32"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half3",
          "text": "simd_half3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half32",
          "text": "simd_half32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_half32(_:)-8kum5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_half32"
        }
      ],
      "role": "symbol",
      "title": "simd_make_half32(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_half32(_:)-8kum5"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_half32(_:)-8obpe": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_half32"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half2",
          "text": "simd_half2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half32",
          "text": "simd_half32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_half32(_:)-8obpe",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_half32"
        }
      ],
      "role": "symbol",
      "title": "simd_make_half32(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_half32(_:)-8obpe"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_half32(_:)-997h0": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified eight-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_half32"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half8",
          "text": "simd_half8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half32",
          "text": "simd_half32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_half32(_:)-997h0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_half32"
        }
      ],
      "role": "symbol",
      "title": "simd_make_half32(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_half32(_:)-997h0"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_half32(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_half32"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half16",
          "text": "simd_half16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half16",
          "text": "simd_half16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half32",
          "text": "simd_half32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_half32(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_half32"
        }
      ],
      "role": "symbol",
      "title": "simd_make_half32(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_half32(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_half32_undef(_:)-3w7jb": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_half32_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half2",
          "text": "simd_half2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half32",
          "text": "simd_half32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_half32_undef(_:)-3w7jb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_half32_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_half32_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_half32_undef(_:)-3w7jb"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_half32_undef(_:)-3yzwk": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified three-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_half32_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half3",
          "text": "simd_half3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half32",
          "text": "simd_half32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_half32_undef(_:)-3yzwk",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_half32_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_half32_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_half32_undef(_:)-3yzwk"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_half32_undef(_:)-42h8l": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified four-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_half32_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half4",
          "text": "simd_half4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half32",
          "text": "simd_half32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_half32_undef(_:)-42h8l",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_half32_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_half32_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_half32_undef(_:)-42h8l"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_half32_undef(_:)-4gyi9": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified eight-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_half32_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half8",
          "text": "simd_half8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half32",
          "text": "simd_half32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_half32_undef(_:)-4gyi9",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_half32_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_half32_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_half32_undef(_:)-4gyi9"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_half32_undef(_:)-9hc0w": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified 16-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_half32_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half16",
          "text": "simd_half16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half32",
          "text": "simd_half32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_half32_undef(_:)-9hc0w",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_half32_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_half32_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_half32_undef(_:)-9hc0w"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-create-32-element-vectors-from-other-vectors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_half32(_:)-8obpe",
        "doc://com.apple.accelerate/documentation/simd/simd_make_half32(_:)-8kum5",
        "doc://com.apple.accelerate/documentation/simd/simd_make_half32(_:)-82w1c",
        "doc://com.apple.accelerate/documentation/simd/simd_make_half32(_:)-997h0",
        "doc://com.apple.accelerate/documentation/simd/simd_make_half32(_:)-6xe53",
        "doc://com.apple.accelerate/documentation/simd/simd_make_half32(_:)-80qof",
        "doc://com.apple.accelerate/documentation/simd/simd_make_half32_undef(_:)-3yzwk",
        "doc://com.apple.accelerate/documentation/simd/simd_make_half32_undef(_:)-42h8l",
        "doc://com.apple.accelerate/documentation/simd/simd_make_half32_undef(_:)-4gyi9",
        "doc://com.apple.accelerate/documentation/simd/simd_make_half32_undef(_:)-9hc0w",
        "doc://com.apple.accelerate/documentation/simd/simd_make_half32(_:_:)"
      ],
      "title": "Functions to create 32-element vectors from other vectors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "simd_make_half32_undef"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_half32_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/simd"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Functions-to-create-32-element-vectors-from-other-vectors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_half32(_:)-8obpe",
                "doc://com.apple.accelerate/documentation/simd/simd_make_half32(_:)-8kum5",
                "doc://com.apple.accelerate/documentation/simd/simd_make_half32(_:)-82w1c",
                "doc://com.apple.accelerate/documentation/simd/simd_make_half32(_:)-997h0",
                "doc://com.apple.accelerate/documentation/simd/simd_make_half32(_:)-6xe53",
                "doc://com.apple.accelerate/documentation/simd/simd_make_half32(_:)-80qof",
                "doc://com.apple.accelerate/documentation/simd/simd_make_half32_undef(_:)-3yzwk",
                "doc://com.apple.accelerate/documentation/simd/simd_make_half32_undef(_:)-42h8l",
                "doc://com.apple.accelerate/documentation/simd/simd_make_half32_undef(_:)-4gyi9",
                "doc://com.apple.accelerate/documentation/simd/simd_make_half32_undef(_:)-9hc0w",
                "doc://com.apple.accelerate/documentation/simd/simd_make_half32(_:_:)"
              ],
              "title": "Functions to create 32-element vectors from other vectors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "static"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half32",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_half32",
                    "text": "simd_half32"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "simd_make_half32_undef"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half2",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_half2",
                    "text": "simd_half2"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "other"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half32(_:)-6xe53/title",
          "value": "simd_make_half32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half32(_:)-6xe53/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_half32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half32_undef(_:)-4gyi9/title",
          "value": "simd_make_half32_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half32_undef(_:)-4gyi9/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_half32_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half32(_:)-8obpe/title",
          "value": "simd_make_half32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half32(_:)-8obpe/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_half32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half32(_:)-8kum5/title",
          "value": "simd_make_half32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half32(_:)-8kum5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_half32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half32_undef(_:)-3yzwk/title",
          "value": "simd_make_half32_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half32_undef(_:)-3yzwk/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_half32_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half32_undef(_:)-3w7jb/title",
          "value": "simd_make_half32_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half32_undef(_:)-3w7jb/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_half32_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half32(_:_:)/title",
          "value": "simd_make_half32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half32(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_half32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half32(_:)-82w1c/title",
          "value": "simd_make_half32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half32(_:)-82w1c/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_half32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half32_undef(_:)-9hc0w/title",
          "value": "simd_make_half32_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half32_undef(_:)-9hc0w/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_half32_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half32(_:)-997h0/title",
          "value": "simd_make_half32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half32(_:)-997h0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_half32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half2/title",
          "value": "simd_half2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half32(_:)-80qof/title",
          "value": "simd_make_half32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half32(_:)-80qof/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_half32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half32/title",
          "value": "simd_half32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half32/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half32_undef(_:)-42h8l/title",
          "value": "simd_make_half32_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half32_undef(_:)-42h8l/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_half32_undef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_make_half32_undef(_:)-3w7jb"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/simd/simd_make_half32_undef(_:)-3w7jb"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
