{
  "abstract": [
    {
      "text": "Returns true if every element in a matrix is within a specified single-precision relative tolerance to the corresponding element in a second matrix.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_almost_equal_elements_relative-30vug"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_almost_equal_elements_relative#$@SA@simd_half2x3#S0_#h#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_almost_equal_elements_relative"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_almost_equal_elements_relative"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_almost_equal_elements_relative"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_bool",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_bool",
              "text": "simd_bool"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_almost_equal_elements_relative"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half2x3",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@simd_half2x3",
              "text": "simd_half2x3"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half2x3",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@simd_half2x3",
              "text": "simd_half2x3"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__y"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:h",
              "text": "_Float16"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__tol"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_almost_equal_elements-5ca3v": {
      "abstract": [
        {
          "text": "Returns true if every element in a matrix is within a specified tolerance to the corresponding element in a second matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_almost_equal_elements"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_almost_equal_elements-5ca3v",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_almost_equal_elements",
      "type": "topic",
      "url": "/documentation/simd/simd_almost_equal_elements-5ca3v"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_almost_equal_elements_relative-30vug": {
      "abstract": [
        {
          "text": "Returns true if every element in a matrix is within a specified single-precision relative tolerance to the corresponding element in a second matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_almost_equal_elements_relative"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_almost_equal_elements_relative-30vug",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_almost_equal_elements_relative",
      "type": "topic",
      "url": "/documentation/simd/simd_almost_equal_elements_relative-30vug"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_bool": {
      "abstract": [
        {
          "text": "A Boolean scalar value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_bool",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_bool"
        }
      ],
      "role": "symbol",
      "title": "simd_bool",
      "type": "topic",
      "url": "/documentation/simd/simd_bool"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_equal-1qead": {
      "abstract": [
        {
          "text": "Returns true if every element in a matrix is exactly equal to the corresponding element in a second matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_equal"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_equal-1qead",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_equal",
      "type": "topic",
      "url": "/documentation/simd/simd_equal-1qead"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half2x3": {
      "abstract": [
        {
          "text": "A matrix of two columns and three rows that contains half-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_half2x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half2x3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_half2x3"
        }
      ],
      "role": "symbol",
      "title": "simd_half2x3",
      "type": "topic",
      "url": "/documentation/simd/simd_half2x3"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Equality-functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_equal-1qead",
        "doc://com.apple.accelerate/documentation/simd/simd_almost_equal_elements-5ca3v"
      ],
      "title": "Equality functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_bool/title",
          "value": "simd_bool"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_bool/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_bool"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_bool/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_bool"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half2x3/title",
          "value": "simd_half2x3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half2x3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half2x3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half2x3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half2x3"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_almost_equal_elements_relative-30vug"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
