{
  "abstract": [
    {
      "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_short-6hhh3"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_short#]3C#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_short"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_short"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_short"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short3",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_short3",
              "text": "simd_short3"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_short"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char3",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_char3",
              "text": "simd_char3"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char3": {
      "abstract": [
        {
          "text": "A vector of three 8-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_char3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_char3"
        }
      ],
      "role": "symbol",
      "title": "simd_char3",
      "type": "topic",
      "url": "/documentation/simd/simd_char3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short-6he6b": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short-6he6b",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short",
      "type": "topic",
      "url": "/documentation/simd/simd_short-6he6b"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short-6hfx5": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short-6hfx5",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short",
      "type": "topic",
      "url": "/documentation/simd/simd_short-6hfx5"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short-6hhh3": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short-6hhh3",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short",
      "type": "topic",
      "url": "/documentation/simd/simd_short-6hhh3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short-6hmgn": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short-6hmgn",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short",
      "type": "topic",
      "url": "/documentation/simd/simd_short-6hmgn"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short-6ho1v": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short-6ho1v",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short",
      "type": "topic",
      "url": "/documentation/simd/simd_short-6ho1v"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short-6hpp5": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short-6hpp5",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short",
      "type": "topic",
      "url": "/documentation/simd/simd_short-6hpp5"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short-6hrav": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short-6hrav",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short",
      "type": "topic",
      "url": "/documentation/simd/simd_short-6hrav"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short-6hsc9": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short-6hsc9",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short",
      "type": "topic",
      "url": "/documentation/simd/simd_short-6hsc9"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short-6hswh": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short-6hswh",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short",
      "type": "topic",
      "url": "/documentation/simd/simd_short-6hswh"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short-6hw6v": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short-6hw6v",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short",
      "type": "topic",
      "url": "/documentation/simd/simd_short-6hw6v"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short3": {
      "abstract": [
        {
          "text": "A vector of three 16-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_short3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_short3"
        }
      ],
      "role": "symbol",
      "title": "simd_short3",
      "type": "topic",
      "url": "/documentation/simd/simd_short3"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Create-Three-Element-Vectors-From-Vectors-of-Other-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_short-6hrav",
        "doc://com.apple.accelerate/documentation/simd/simd_short-6hmgn",
        "doc://com.apple.accelerate/documentation/simd/simd_short-6hw6v",
        "doc://com.apple.accelerate/documentation/simd/simd_short-6he6b",
        "doc://com.apple.accelerate/documentation/simd/simd_short-6ho1v",
        "doc://com.apple.accelerate/documentation/simd/simd_short-6hfx5",
        "doc://com.apple.accelerate/documentation/simd/simd_short-6hpp5",
        "doc://com.apple.accelerate/documentation/simd/simd_short-6hswh",
        "doc://com.apple.accelerate/documentation/simd/simd_short-6hsc9"
      ],
      "title": "Functions to Create Three-Element Vectors From Vectors of Other Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char3/title",
          "value": "simd_char3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short3/title",
          "value": "simd_short3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short3"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_short-6hhh3"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
