{
  "abstract": [
    {
      "text": "A vector of two 32-bit signed integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_int2"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@simd_int2",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simd_int2"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_int2"
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "simd_int2"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_int2"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5SIMD2V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5SIMD2V",
              "text": "SIMD2"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5Int32V",
              "text": "Int32"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/abs(_:)-770jg": {
      "abstract": [
        {
          "text": "Returns the absolute value of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "abs"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD2V",
          "text": "SIMD2"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD2V",
          "text": "SIMD2"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/abs(_:)-770jg",
      "kind": "symbol",
      "role": "symbol",
      "title": "abs(_:)",
      "type": "topic",
      "url": "/documentation/simd/abs(_:)-770jg"
    },
    "doc://com.apple.accelerate/documentation/simd/clamp(_:min:max:)-11cyt": {
      "abstract": [
        {
          "text": "Returns each element in a vector clamped to a specified scalar range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clamp"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD2V",
          "text": "SIMD2"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "min"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "max"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD2V",
          "text": "SIMD2"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/clamp(_:min:max:)-11cyt",
      "kind": "symbol",
      "role": "symbol",
      "title": "clamp(_:min:max:)",
      "type": "topic",
      "url": "/documentation/simd/clamp(_:min:max:)-11cyt"
    },
    "doc://com.apple.accelerate/documentation/simd/clamp(_:min:max:)-y596": {
      "abstract": [
        {
          "text": "Returns each element in a vector clamped to a specified range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clamp"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD2V",
          "text": "SIMD2"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "min"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD2V",
          "text": "SIMD2"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "max"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD2V",
          "text": "SIMD2"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD2V",
          "text": "SIMD2"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/clamp(_:min:max:)-y596",
      "kind": "symbol",
      "role": "symbol",
      "title": "clamp(_:min:max:)",
      "type": "topic",
      "url": "/documentation/simd/clamp(_:min:max:)-y596"
    },
    "doc://com.apple.accelerate/documentation/simd/int2": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "int2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/int2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "int2"
        }
      ],
      "role": "symbol",
      "title": "int2",
      "type": "topic",
      "url": "/documentation/simd/int2"
    },
    "doc://com.apple.accelerate/documentation/simd/max(_:_:)-9uijf": {
      "abstract": [
        {
          "text": "Returns the maximum value of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "max"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD2V",
          "text": "SIMD2"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD2V",
          "text": "SIMD2"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/max(_:_:)-9uijf",
      "kind": "symbol",
      "role": "symbol",
      "title": "max(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/max(_:_:)-9uijf"
    },
    "doc://com.apple.accelerate/documentation/simd/max(_:_:)-9xpv0": {
      "abstract": [
        {
          "text": "Returns the maximum value of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "max"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD2V",
          "text": "SIMD2"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD2V",
          "text": "SIMD2"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD2V",
          "text": "SIMD2"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/max(_:_:)-9xpv0",
      "kind": "symbol",
      "role": "symbol",
      "title": "max(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/max(_:_:)-9xpv0"
    },
    "doc://com.apple.accelerate/documentation/simd/min(_:_:)-goji": {
      "abstract": [
        {
          "text": "Returns the minimum value of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "min"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD2V",
          "text": "SIMD2"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD2V",
          "text": "SIMD2"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/min(_:_:)-goji",
      "kind": "symbol",
      "role": "symbol",
      "title": "min(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/min(_:_:)-goji"
    },
    "doc://com.apple.accelerate/documentation/simd/min(_:_:)-jyi5": {
      "abstract": [
        {
          "text": "Returns the minimum value of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "min"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD2V",
          "text": "SIMD2"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD2V",
          "text": "SIMD2"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD2V",
          "text": "SIMD2"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/min(_:_:)-jyi5",
      "kind": "symbol",
      "role": "symbol",
      "title": "min(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/min(_:_:)-jyi5"
    },
    "doc://com.apple.accelerate/documentation/simd/reduce_add(_:)-4edwc": {
      "abstract": [
        {
          "text": "Returns the sum of all elements in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reduce_add"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD2V",
          "text": "SIMD2"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/reduce_add(_:)-4edwc",
      "kind": "symbol",
      "role": "symbol",
      "title": "reduce_add(_:)",
      "type": "topic",
      "url": "/documentation/simd/reduce_add(_:)-4edwc"
    },
    "doc://com.apple.accelerate/documentation/simd/reduce_max(_:)-6qw44": {
      "abstract": [
        {
          "text": "Returns the maximum value in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reduce_max"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD2V",
          "text": "SIMD2"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/reduce_max(_:)-6qw44",
      "kind": "symbol",
      "role": "symbol",
      "title": "reduce_max(_:)",
      "type": "topic",
      "url": "/documentation/simd/reduce_max(_:)-6qw44"
    },
    "doc://com.apple.accelerate/documentation/simd/reduce_min(_:)-34ha7": {
      "abstract": [
        {
          "text": "Returns the minimum value in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reduce_min"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD2V",
          "text": "SIMD2"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/reduce_min(_:)-34ha7",
      "kind": "symbol",
      "role": "symbol",
      "title": "reduce_min(_:)",
      "type": "topic",
      "url": "/documentation/simd/reduce_min(_:)-34ha7"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_abs(_:)-88kbu": {
      "abstract": [
        {
          "text": "Returns the absolute value of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_abs"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int2",
          "text": "simd_int2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int2",
          "text": "simd_int2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_abs(_:)-88kbu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_abs"
        }
      ],
      "role": "symbol",
      "title": "simd_abs(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_abs(_:)-88kbu"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1cxjv": {
      "abstract": [
        {
          "text": "Returns true if the high-order bit of every element is set; false otherwise.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_all"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int2",
          "text": "simd_int2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_bool",
          "text": "simd_bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1cxjv",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_all"
        }
      ],
      "role": "symbol",
      "title": "simd_all(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_all(_:)-1cxjv"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-64rh5": {
      "abstract": [
        {
          "text": "Returns true if the high-order bit of any element is set; false otherwise.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_any"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int2",
          "text": "simd_int2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_bool",
          "text": "simd_bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-64rh5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_any"
        }
      ],
      "role": "symbol",
      "title": "simd_any(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_any(_:)-64rh5"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-6p66c": {
      "abstract": [
        {
          "text": "Returns a vector that contains elements from either the first or second parameter, based on the corresponding element in the third parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_bitselect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int2",
          "text": "simd_int2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int2",
          "text": "simd_int2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int2",
          "text": "simd_int2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int2",
          "text": "simd_int2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-6p66c",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_bitselect"
        }
      ],
      "role": "symbol",
      "title": "simd_bitselect(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_bitselect(_:_:_:)-6p66c"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-9n2rx": {
      "abstract": [
        {
          "text": "Returns each element in a vector clamped to a specified range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_clamp"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int2",
          "text": "simd_int2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int2",
          "text": "simd_int2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int2",
          "text": "simd_int2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int2",
          "text": "simd_int2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-9n2rx",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_clamp"
        }
      ],
      "role": "symbol",
      "title": "simd_clamp(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_clamp(_:_:_:)-9n2rx"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-8sg1t": {
      "abstract": [
        {
          "text": "Returns true if every element in a vector is exactly equal to the corresponding element in a second vector, and otherwise returns false.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_equal"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int2",
          "text": "simd_int2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int2",
          "text": "simd_int2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_bool",
          "text": "simd_bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-8sg1t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_equal"
        }
      ],
      "role": "symbol",
      "title": "simd_equal(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_equal(_:_:)-8sg1t"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int-9n2z8": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int-9n2z8",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int",
      "type": "topic",
      "url": "/documentation/simd/simd_int-9n2z8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int-9n3sw": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int-9n3sw",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int",
      "type": "topic",
      "url": "/documentation/simd/simd_int-9n3sw"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int-9n4v0": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int-9n4v0",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int",
      "type": "topic",
      "url": "/documentation/simd/simd_int-9n4v0"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int-9n5es": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int-9n5es",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int",
      "type": "topic",
      "url": "/documentation/simd/simd_int-9n5es"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int-9n5ow": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int-9n5ow",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int",
      "type": "topic",
      "url": "/documentation/simd/simd_int-9n5ow"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int-9nas0": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int-9nas0",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int",
      "type": "topic",
      "url": "/documentation/simd/simd_int-9nas0"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int-9ncyc": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int-9ncyc",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int",
      "type": "topic",
      "url": "/documentation/simd/simd_int-9ncyc"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int-9nds0": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int-9nds0",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int",
      "type": "topic",
      "url": "/documentation/simd/simd_int-9nds0"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int-9nfo0": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int-9nfo0",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int",
      "type": "topic",
      "url": "/documentation/simd/simd_int-9nfo0"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int-9nkr4": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int-9nkr4",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int",
      "type": "topic",
      "url": "/documentation/simd/simd_int-9nkr4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int1": {
      "abstract": [
        {
          "text": "A vector of one 32-bit signed integer element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_int1"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_int1"
        }
      ],
      "role": "symbol",
      "title": "simd_int1",
      "type": "topic",
      "url": "/documentation/simd/simd_int1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int16": {
      "abstract": [
        {
          "text": "A vector of sixteen 32-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_int16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_int16"
        }
      ],
      "role": "symbol",
      "title": "simd_int16",
      "type": "topic",
      "url": "/documentation/simd/simd_int16"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int2": {
      "abstract": [
        {
          "text": "A vector of two 32-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_int2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_int2"
        }
      ],
      "role": "symbol",
      "title": "simd_int2",
      "type": "topic",
      "url": "/documentation/simd/simd_int2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int3": {
      "abstract": [
        {
          "text": "A vector of three 32-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_int3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_int3"
        }
      ],
      "role": "symbol",
      "title": "simd_int3",
      "type": "topic",
      "url": "/documentation/simd/simd_int3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int4": {
      "abstract": [
        {
          "text": "A vector of four 32-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_int4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_int4"
        }
      ],
      "role": "symbol",
      "title": "simd_int4",
      "type": "topic",
      "url": "/documentation/simd/simd_int4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int8": {
      "abstract": [
        {
          "text": "A vector of eight 32-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_int8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_int8"
        }
      ],
      "role": "symbol",
      "title": "simd_int8",
      "type": "topic",
      "url": "/documentation/simd/simd_int8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int_rte-8zh34": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int_rte"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int_rte-8zh34",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int_rte",
      "type": "topic",
      "url": "/documentation/simd/simd_int_rte-8zh34"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6smr3": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6smr3",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_int_sat-6smr3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6snv1": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6snv1",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_int_sat-6snv1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6sohh": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6sohh",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_int_sat-6sohh"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6sq1n": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6sq1n",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_int_sat-6sq1n"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6sqyt": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6sqyt",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_int_sat-6sqyt"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6srpr": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6srpr",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_int_sat-6srpr"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6swof": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6swof",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_int_sat-6swof"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6sztn": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6sztn",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_int_sat-6sztn"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6t0ud": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6t0ud",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_int_sat-6t0ud"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6t1vz": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6t1vz",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_int_sat-6t1vz"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_int2(_:)-1j0r7": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_int2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int2",
          "text": "simd_int2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int2",
          "text": "simd_int2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_int2(_:)-1j0r7",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_int2"
        }
      ],
      "role": "symbol",
      "title": "simd_make_int2(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_int2(_:)-1j0r7"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_int2(_:)-1mclu": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified three-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_int2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int3",
          "text": "simd_int3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int2",
          "text": "simd_int2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_int2(_:)-1mclu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_int2"
        }
      ],
      "role": "symbol",
      "title": "simd_make_int2(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_int2(_:)-1mclu"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_int2(_:)-1qyb9": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified four-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_int2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int4",
          "text": "simd_int4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int2",
          "text": "simd_int2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_int2(_:)-1qyb9",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_int2"
        }
      ],
      "role": "symbol",
      "title": "simd_make_int2(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_int2(_:)-1qyb9"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_int2(_:)-23rr5": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified eight-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_int2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int8",
          "text": "simd_int8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int2",
          "text": "simd_int2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_int2(_:)-23rr5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_int2"
        }
      ],
      "role": "symbol",
      "title": "simd_make_int2(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_int2(_:)-23rr5"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_int2(_:)-3zby": {
      "abstract": [
        {
          "text": "Returns a new vector with the first element set to a scalar value, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_int2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int2",
          "text": "simd_int2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_int2(_:)-3zby",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_int2"
        }
      ],
      "role": "symbol",
      "title": "simd_make_int2(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_int2(_:)-3zby"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_int2(_:)-4okip": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified sixteen-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_int2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int16",
          "text": "simd_int16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int2",
          "text": "simd_int2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_int2(_:)-4okip",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_int2"
        }
      ],
      "role": "symbol",
      "title": "simd_make_int2(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_int2(_:)-4okip"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_int2(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified scalar values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_int2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int2",
          "text": "simd_int2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_int2(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_int2"
        }
      ],
      "role": "symbol",
      "title": "simd_make_int2(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_int2(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_int2_undef(_:)": {
      "abstract": [
        {
          "text": "Returns a new vector with the first element set to a scalar value, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_int2_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int2",
          "text": "simd_int2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_int2_undef(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_int2_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_int2_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_int2_undef(_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-2xs4j": {
      "abstract": [
        {
          "text": "Returns the maximum value of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_max"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int2",
          "text": "simd_int2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int2",
          "text": "simd_int2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int2",
          "text": "simd_int2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-2xs4j",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_max"
        }
      ],
      "role": "symbol",
      "title": "simd_max(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_max(_:_:)-2xs4j"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-3focz": {
      "abstract": [
        {
          "text": "Returns the minimum value of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_min"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int2",
          "text": "simd_int2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int2",
          "text": "simd_int2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int2",
          "text": "simd_int2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-3focz",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_min"
        }
      ],
      "role": "symbol",
      "title": "simd_min(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_min(_:_:)-3focz"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-2qeam": {
      "abstract": [
        {
          "text": "Returns the sum of all elements in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_add"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int2",
          "text": "simd_int2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-2qeam",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_add"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_add(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_add(_:)-2qeam"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-4kojc": {
      "abstract": [
        {
          "text": "Returns the maximum value in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_max"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int2",
          "text": "simd_int2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-4kojc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_max"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_max(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_max(_:)-4kojc"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-49f1c": {
      "abstract": [
        {
          "text": "Returns the minimum value in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_min"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int2",
          "text": "simd_int2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-49f1c",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_min"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_min(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_min(_:)-49f1c"
    },
    "doc://com.apple.accelerate/documentation/simd/vector2-9gvdx": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified scalar values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector2-9gvdx",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector2",
      "type": "topic",
      "url": "/documentation/simd/vector2-9gvdx"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_int2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vector_int2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_int2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vector_int2"
        }
      ],
      "role": "symbol",
      "title": "vector_int2",
      "type": "topic",
      "url": "/documentation/simd/vector_int2"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s5Int32V": {
      "abstract": [
        {
          "text": "A 32-bit signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int32",
      "type": "topic",
      "url": "/documentation/Swift/Int32"
    },
    "doc://com.externally.resolved.symbol/s:s5SIMD2V": {
      "abstract": [
        {
          "text": "A vector of two scalar values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SIMD2"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SIMDScalarP",
          "text": "SIMDScalar"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5SIMD2V",
      "kind": "symbol",
      "role": "symbol",
      "title": "SIMD2",
      "type": "topic",
      "url": "/documentation/Swift/SIMD2"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Vector-Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_int1",
        "doc://com.apple.accelerate/documentation/simd/simd_int3",
        "doc://com.apple.accelerate/documentation/simd/simd_int4",
        "doc://com.apple.accelerate/documentation/simd/simd_int8",
        "doc://com.apple.accelerate/documentation/simd/simd_int16"
      ],
      "title": "Vector Data Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Functions-to-Create-Two-Element-Vectors-From-Other-Vectors",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_int2(_:)-1j0r7",
        "doc://com.apple.accelerate/documentation/simd/simd_make_int2(_:)-1mclu",
        "doc://com.apple.accelerate/documentation/simd/simd_make_int2(_:)-1qyb9",
        "doc://com.apple.accelerate/documentation/simd/simd_make_int2(_:)-23rr5",
        "doc://com.apple.accelerate/documentation/simd/simd_make_int2(_:)-4okip"
      ],
      "title": "Functions to Create Two-Element Vectors From Other Vectors"
    },
    {
      "anchor": "Functions-to-Create-Two-Element-Vectors-From-Scalar-Values",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_int2(_:)-3zby",
        "doc://com.apple.accelerate/documentation/simd/simd_make_int2(_:_:)",
        "doc://com.apple.accelerate/documentation/simd/simd_make_int2_undef(_:)"
      ],
      "title": "Functions to Create Two-Element Vectors From Scalar Values"
    },
    {
      "anchor": "Common-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_abs(_:)-88kbu",
        "doc://com.apple.accelerate/documentation/simd/abs(_:)-770jg",
        "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-9n2rx",
        "doc://com.apple.accelerate/documentation/simd/clamp(_:min:max:)-y596",
        "doc://com.apple.accelerate/documentation/simd/clamp(_:min:max:)-11cyt",
        "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-8sg1t"
      ],
      "title": "Common Functions"
    },
    {
      "anchor": "Reduce-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-49f1c",
        "doc://com.apple.accelerate/documentation/simd/reduce_min(_:)-34ha7",
        "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-4kojc",
        "doc://com.apple.accelerate/documentation/simd/reduce_max(_:)-6qw44",
        "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-2qeam",
        "doc://com.apple.accelerate/documentation/simd/reduce_add(_:)-4edwc"
      ],
      "title": "Reduce Functions"
    },
    {
      "anchor": "Extrema-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-2xs4j",
        "doc://com.apple.accelerate/documentation/simd/max(_:_:)-9xpv0",
        "doc://com.apple.accelerate/documentation/simd/max(_:_:)-9uijf",
        "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-3focz",
        "doc://com.apple.accelerate/documentation/simd/min(_:_:)-jyi5",
        "doc://com.apple.accelerate/documentation/simd/min(_:_:)-goji"
      ],
      "title": "Extrema Functions"
    },
    {
      "anchor": "Logic-and-Bitwise-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-64rh5",
        "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1cxjv",
        "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-6p66c"
      ],
      "title": "Logic and Bitwise Functions"
    },
    {
      "anchor": "Alternative-Type-Alias",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/int2",
        "doc://com.apple.accelerate/documentation/simd/vector_int2"
      ],
      "title": "Alternative Type Alias"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "simd_int2"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_int2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_int2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/simd"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Functions-to-Create-Two-Element-Vectors-From-Other-Vectors",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_int2(_:)-1j0r7",
                "doc://com.apple.accelerate/documentation/simd/simd_make_int2(_:)-1mclu",
                "doc://com.apple.accelerate/documentation/simd/simd_make_int2(_:)-1qyb9",
                "doc://com.apple.accelerate/documentation/simd/simd_make_int2(_:)-23rr5",
                "doc://com.apple.accelerate/documentation/simd/simd_make_int2(_:)-4okip"
              ],
              "title": "Functions to Create Two-Element Vectors From Other Vectors"
            },
            {
              "anchor": "Functions-to-Create-Two-Element-Vectors-From-Scalar-Values",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_int2(_:)-3zby",
                "doc://com.apple.accelerate/documentation/simd/simd_make_int2(_:_:)",
                "doc://com.apple.accelerate/documentation/simd/vector2-9gvdx",
                "doc://com.apple.accelerate/documentation/simd/simd_make_int2_undef(_:)"
              ],
              "title": "Functions to Create Two-Element Vectors From Scalar Values"
            },
            {
              "anchor": "Functions-to-Create-Two-Element-Vectors-From-Vectors-of-Other-Types",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_int-9nfo0",
                "doc://com.apple.accelerate/documentation/simd/simd_int-9n5ow",
                "doc://com.apple.accelerate/documentation/simd/simd_int-9nkr4",
                "doc://com.apple.accelerate/documentation/simd/simd_int-9nas0",
                "doc://com.apple.accelerate/documentation/simd/simd_int-9nds0",
                "doc://com.apple.accelerate/documentation/simd/simd_int-9n3sw",
                "doc://com.apple.accelerate/documentation/simd/simd_int-9ncyc",
                "doc://com.apple.accelerate/documentation/simd/simd_int-9n2z8",
                "doc://com.apple.accelerate/documentation/simd/simd_int-9n4v0",
                "doc://com.apple.accelerate/documentation/simd/simd_int-9n5es"
              ],
              "title": "Functions to Create Two-Element Vectors From Vectors of Other Types"
            },
            {
              "anchor": "Functions-to-Perform-Saturating-Conversion-From-Vectors-of-Other-Types",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6swof",
                "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6smr3",
                "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6t1vz",
                "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6srpr",
                "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6sztn",
                "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6sq1n",
                "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6t0ud",
                "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6sqyt",
                "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6snv1",
                "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6sohh"
              ],
              "title": "Functions to Perform Saturating Conversion From Vectors of Other Types"
            },
            {
              "anchor": "Functions-to-Perform-Round-Half-to-Even-Conversion-From-Single-Precision-Vectors",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_int_rte-8zh34"
              ],
              "title": "Functions to Perform Round-Half-to-Even Conversion From Single-Precision Vectors"
            },
            {
              "anchor": "Common-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_abs(_:)-88kbu",
                "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-9n2rx",
                "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-8sg1t"
              ],
              "title": "Common Functions"
            },
            {
              "anchor": "Reduce-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-49f1c",
                "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-4kojc",
                "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-2qeam"
              ],
              "title": "Reduce Functions"
            },
            {
              "anchor": "Extrema-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-2xs4j",
                "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-3focz"
              ],
              "title": "Extrema Functions"
            },
            {
              "anchor": "Logic-and-Bitwise-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-64rh5",
                "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1cxjv",
                "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-6p66c"
              ],
              "title": "Logic and Bitwise Functions"
            },
            {
              "anchor": "Alternative-Type-Alias",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/vector_int2"
              ],
              "title": "Alternative Type Alias"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Vector-Data-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_int1",
                "doc://com.apple.accelerate/documentation/simd/simd_int3",
                "doc://com.apple.accelerate/documentation/simd/simd_int4",
                "doc://com.apple.accelerate/documentation/simd/simd_int8",
                "doc://com.apple.accelerate/documentation/simd/simd_int16"
              ],
              "title": "Vector Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:]2I",
                    "text": "int __attribute__((ext_vector_type(2)))"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "simd_int2"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int2(_:)-1mclu/title",
          "value": "simd_make_int2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int2(_:)-1mclu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_int2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int2(_:)-4okip/title",
          "value": "simd_make_int2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int2(_:)-4okip/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_int2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_all(_:)-1cxjv/title",
          "value": "simd_all"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_all(_:)-1cxjv/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_all"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_max(_:_:)-2xs4j/title",
          "value": "simd_max"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_max(_:_:)-2xs4j/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_max"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int2(_:_:)/title",
          "value": "simd_make_int2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int2(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_int2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int3/title",
          "value": "simd_int3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_int3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_int3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int2(_:)-1j0r7/title",
          "value": "simd_make_int2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int2(_:)-1j0r7/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_int2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int2(_:)-1qyb9/title",
          "value": "simd_make_int2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int2(_:)-1qyb9/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_int2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_abs(_:)-88kbu/title",
          "value": "simd_abs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_abs(_:)-88kbu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_abs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_bitselect(_:_:_:)-6p66c/title",
          "value": "simd_bitselect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_bitselect(_:_:_:)-6p66c/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_bitselect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_equal(_:_:)-8sg1t/title",
          "value": "simd_equal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_equal(_:_:)-8sg1t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_equal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_min(_:_:)-3focz/title",
          "value": "simd_min"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_min(_:_:)-3focz/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_min"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_min(_:)-49f1c/title",
          "value": "simd_reduce_min"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_min(_:)-49f1c/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_min"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int2(_:)-3zby/title",
          "value": "simd_make_int2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int2(_:)-3zby/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_int2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int2_undef(_:)/title",
          "value": "simd_make_int2_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int2_undef(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_int2_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int16/title",
          "value": "simd_int16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_int16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int16/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_int16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int2(_:)-23rr5/title",
          "value": "simd_make_int2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int2(_:)-23rr5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_int2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_add(_:)-2qeam/title",
          "value": "simd_reduce_add"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_add(_:)-2qeam/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_add"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int4/title",
          "value": "simd_int4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_int4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_int4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_any(_:)-64rh5/title",
          "value": "simd_any"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_any(_:)-64rh5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_any"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1vector_int2/title",
          "value": "vector_int2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1vector_int2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vector_int2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1vector_int2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vector_int2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_clamp(_:_:_:)-9n2rx/title",
          "value": "simd_clamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_clamp(_:_:_:)-9n2rx/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_clamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_max(_:)-4kojc/title",
          "value": "simd_reduce_max"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_max(_:)-4kojc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_max"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int2/title",
          "value": "simd_int2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_int2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_int2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int1/title",
          "value": "simd_int1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_int1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int1/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_int1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int8/title",
          "value": "simd_int8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_int8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_int8"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_int2"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/simd/simd_int2"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
