{
  "abstract": [
    {
      "text": "Returns the sum of all elements in a vector.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-2q2jq"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_reduce_add#]2l#",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simd_reduce_add"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_ulong2",
        "text": "simd_ulong2"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_ulong1",
        "text": "simd_ulong1"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_reduce_add"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_reduce_add(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_reduce_add"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "x"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_ulong2",
              "text": "simd_ulong2"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong1",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_ulong1",
              "text": "simd_ulong1"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-2q2jq": {
      "abstract": [
        {
          "text": "Returns the sum of all elements in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_add"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong2",
          "text": "simd_ulong2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong1",
          "text": "simd_ulong1"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-2q2jq",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_add"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_add(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_add(_:)-2q2jq"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-4kgd8": {
      "abstract": [
        {
          "text": "Returns the maximum value in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_max"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong2",
          "text": "simd_ulong2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong1",
          "text": "simd_ulong1"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-4kgd8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_max"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_max(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_max(_:)-4kgd8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-49qq4": {
      "abstract": [
        {
          "text": "Returns the miniumum value in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_min"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong2",
          "text": "simd_ulong2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong1",
          "text": "simd_ulong1"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-49qq4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_min"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_min(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_min(_:)-49qq4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong1": {
      "abstract": [
        {
          "text": "A vector of one 64-bit unsigned integer element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ulong1"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ulong1"
        }
      ],
      "role": "symbol",
      "title": "simd_ulong1",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong2": {
      "abstract": [
        {
          "text": "A vector of two 64-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ulong2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ulong2"
        }
      ],
      "role": "symbol",
      "title": "simd_ulong2",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong2"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reduce-Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-49qq4",
        "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-4kgd8"
      ],
      "title": "Reduce Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "simd_reduce_add"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_add"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/simd"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reduce-Functions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-49qq4",
                "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-4kgd8"
              ],
              "title": "Reduce Functions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "static"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong1",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_ulong1",
                    "text": "simd_ulong1"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "simd_reduce_add"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong2",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_ulong2",
                    "text": "simd_ulong2"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "x"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_add(_:)-2q2jq/title",
          "value": "simd_reduce_add"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_add(_:)-2q2jq/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_add"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_min(_:)-49qq4/title",
          "value": "simd_reduce_min"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_min(_:)-49qq4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_min"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_max(_:)-4kgd8/title",
          "value": "simd_reduce_max"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_max(_:)-4kgd8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_max"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong2/title",
          "value": "simd_ulong2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong1/title",
          "value": "simd_ulong1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong1/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong1"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_reduce_add(_:)-2q2jq"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/simd/simd_reduce_add(_:)-2q2jq"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
