{
  "abstract": [
    {
      "text": "Returns a new vector from the specified vector.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_make_int8(_:)-r4ak"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_make_int8#]8I#",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simd_make_int8"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_int8",
        "text": "simd_int8"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_int8",
        "text": "simd_int8"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_make_int8"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_make_int8(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_make_int8"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "other"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int8",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_int8",
              "text": "simd_int8"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int8",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_int8",
              "text": "simd_int8"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int8": {
      "abstract": [
        {
          "text": "A vector of eight 32-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_int8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_int8"
        }
      ],
      "role": "symbol",
      "title": "simd_int8",
      "type": "topic",
      "url": "/documentation/simd/simd_int8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_int8(_:)-3lu01": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified sixteen-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_int8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int16",
          "text": "simd_int16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int8",
          "text": "simd_int8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_int8(_:)-3lu01",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_int8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_int8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_int8(_:)-3lu01"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_int8(_:)-9s1jp": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_int8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int2",
          "text": "simd_int2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int8",
          "text": "simd_int8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_int8(_:)-9s1jp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_int8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_int8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_int8(_:)-9s1jp"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_int8(_:)-9vi30": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified three-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_int8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int3",
          "text": "simd_int3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int8",
          "text": "simd_int8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_int8(_:)-9vi30",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_int8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_int8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_int8(_:)-9vi30"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_int8(_:)-efr4": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified four-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_int8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int4",
          "text": "simd_int4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int8",
          "text": "simd_int8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_int8(_:)-efr4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_int8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_int8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_int8(_:)-efr4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_int8(_:)-r4ak": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_int8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int8",
          "text": "simd_int8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int8",
          "text": "simd_int8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_int8(_:)-r4ak",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_int8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_int8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_int8(_:)-r4ak"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_int8(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_int8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int4",
          "text": "simd_int4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int4",
          "text": "simd_int4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int8",
          "text": "simd_int8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_int8(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_int8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_int8(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_int8(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_int8_undef(_:)-5324d": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified three-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_int8_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int3",
          "text": "simd_int3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int8",
          "text": "simd_int8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_int8_undef(_:)-5324d",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_int8_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_int8_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_int8_undef(_:)-5324d"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_int8_undef(_:)-57mj8": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_int8_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int2",
          "text": "simd_int2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int8",
          "text": "simd_int8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_int8_undef(_:)-57mj8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_int8_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_int8_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_int8_undef(_:)-57mj8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_int8_undef(_:)-5rem2": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified four-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_int8_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int4",
          "text": "simd_int4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int8",
          "text": "simd_int8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_int8_undef(_:)-5rem2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_int8_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_int8_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_int8_undef(_:)-5rem2"
    },
    "doc://com.apple.accelerate/documentation/simd/vector8-5snjo": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector8-5snjo",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector8",
      "type": "topic",
      "url": "/documentation/simd/vector8-5snjo"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Create-Eight-Element-Vectors-From-Other-Vectors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_int8(_:)-9s1jp",
        "doc://com.apple.accelerate/documentation/simd/simd_make_int8(_:)-9vi30",
        "doc://com.apple.accelerate/documentation/simd/simd_make_int8(_:)-efr4",
        "doc://com.apple.accelerate/documentation/simd/simd_make_int8(_:)-3lu01",
        "doc://com.apple.accelerate/documentation/simd/simd_make_int8(_:_:)",
        "doc://com.apple.accelerate/documentation/simd/simd_make_int8_undef(_:)-57mj8",
        "doc://com.apple.accelerate/documentation/simd/simd_make_int8_undef(_:)-5324d",
        "doc://com.apple.accelerate/documentation/simd/simd_make_int8_undef(_:)-5rem2"
      ],
      "title": "Functions to Create Eight-Element Vectors From Other Vectors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "simd_make_int8"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_int8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/simd"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Functions-to-Create-Eight-Element-Vectors-From-Other-Vectors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_int8(_:)-9s1jp",
                "doc://com.apple.accelerate/documentation/simd/simd_make_int8(_:)-9vi30",
                "doc://com.apple.accelerate/documentation/simd/simd_make_int8(_:)-efr4",
                "doc://com.apple.accelerate/documentation/simd/simd_make_int8(_:)-3lu01",
                "doc://com.apple.accelerate/documentation/simd/simd_make_int8(_:_:)",
                "doc://com.apple.accelerate/documentation/simd/vector8-5snjo",
                "doc://com.apple.accelerate/documentation/simd/simd_make_int8_undef(_:)-57mj8",
                "doc://com.apple.accelerate/documentation/simd/simd_make_int8_undef(_:)-5324d",
                "doc://com.apple.accelerate/documentation/simd/simd_make_int8_undef(_:)-5rem2"
              ],
              "title": "Functions to Create Eight-Element Vectors From Other Vectors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "static"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int8",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_int8",
                    "text": "simd_int8"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "simd_make_int8"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int8",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_int8",
                    "text": "simd_int8"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "other"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int8(_:)-9vi30/title",
          "value": "simd_make_int8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int8(_:)-9vi30/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_int8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int8(_:)-r4ak/title",
          "value": "simd_make_int8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int8(_:)-r4ak/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_int8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int8_undef(_:)-5324d/title",
          "value": "simd_make_int8_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int8_undef(_:)-5324d/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_int8_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int8_undef(_:)-5rem2/title",
          "value": "simd_make_int8_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int8_undef(_:)-5rem2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_int8_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int8(_:)-3lu01/title",
          "value": "simd_make_int8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int8(_:)-3lu01/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_int8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int8(_:)-efr4/title",
          "value": "simd_make_int8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int8(_:)-efr4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_int8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int8/title",
          "value": "simd_int8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_int8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_int8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int8_undef(_:)-57mj8/title",
          "value": "simd_make_int8_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int8_undef(_:)-57mj8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_int8_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int8(_:)-9s1jp/title",
          "value": "simd_make_int8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int8(_:)-9s1jp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_int8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int8(_:_:)/title",
          "value": "simd_make_int8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_int8(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_int8"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_make_int8(_:)-r4ak"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/simd/simd_make_int8(_:)-r4ak"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
