{
  "abstract": [
    {
      "text": "Returns a new vector from the specified vector of 8-bit, unsigned-integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_double-5osau"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_double#]4c#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_double"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_double"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_double"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_double4",
              "text": "simd_double4"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_double"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar4",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_uchar4",
              "text": "simd_uchar4"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double-5onhi": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double-5onhi",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_double",
      "type": "topic",
      "url": "/documentation/simd/simd_double-5onhi"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double-5oqzm": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double-5oqzm",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_double",
      "type": "topic",
      "url": "/documentation/simd/simd_double-5oqzm"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double-5orke": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double-5orke",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_double",
      "type": "topic",
      "url": "/documentation/simd/simd_double-5orke"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double-5osau": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double-5osau",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_double",
      "type": "topic",
      "url": "/documentation/simd/simd_double-5osau"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double-5ot9u": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double-5ot9u",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_double",
      "type": "topic",
      "url": "/documentation/simd/simd_double-5ot9u"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double-5ouey": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double-5ouey",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_double",
      "type": "topic",
      "url": "/documentation/simd/simd_double-5ouey"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double-5oxie": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double-5oxie",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_double",
      "type": "topic",
      "url": "/documentation/simd/simd_double-5oxie"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double-5p2h2": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double-5p2h2",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_double",
      "type": "topic",
      "url": "/documentation/simd/simd_double-5p2h2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double-5p376": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double-5p376",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_double",
      "type": "topic",
      "url": "/documentation/simd/simd_double-5p376"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double-5p456": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double-5p456",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_double",
      "type": "topic",
      "url": "/documentation/simd/simd_double-5p456"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double4": {
      "abstract": [
        {
          "text": "A vector of four 64-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_double4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_double4"
        }
      ],
      "role": "symbol",
      "title": "simd_double4",
      "type": "topic",
      "url": "/documentation/simd/simd_double4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar4": {
      "abstract": [
        {
          "text": "A vector of four 8-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uchar4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uchar4"
        }
      ],
      "role": "symbol",
      "title": "simd_uchar4",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar4"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Create-Four-Element-Vectors-From-Vectors-of-Other-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_double-5p2h2",
        "doc://com.apple.accelerate/documentation/simd/simd_double-5oxie",
        "doc://com.apple.accelerate/documentation/simd/simd_double-5onhi",
        "doc://com.apple.accelerate/documentation/simd/simd_double-5p456",
        "doc://com.apple.accelerate/documentation/simd/simd_double-5ouey",
        "doc://com.apple.accelerate/documentation/simd/simd_double-5p376",
        "doc://com.apple.accelerate/documentation/simd/simd_double-5ot9u",
        "doc://com.apple.accelerate/documentation/simd/simd_double-5orke",
        "doc://com.apple.accelerate/documentation/simd/simd_double-5oqzm"
      ],
      "title": "Functions to Create Four-Element Vectors From Vectors of Other Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar4/title",
          "value": "simd_uchar4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4/title",
          "value": "simd_double4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double4"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_double-5osau"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
