{
  "abstract": [
    {
      "text": "Returns a new matrix with the specified vector on the main diagonal.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_diagonal_matrix-2kzr8"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_diagonal_matrix#]4d#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_diagonal_matrix"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_diagonal_matrix"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_diagonal_matrix"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4x4",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@simd_double4x4",
              "text": "simd_double4x4"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_diagonal_matrix"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_double4",
              "text": "simd_double4"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_diagonal_matrix-2kzr8": {
      "abstract": [
        {
          "text": "Returns a new matrix with the specified vector on the main diagonal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_diagonal_matrix"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_diagonal_matrix-2kzr8",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_diagonal_matrix",
      "type": "topic",
      "url": "/documentation/simd/simd_diagonal_matrix-2kzr8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double4": {
      "abstract": [
        {
          "text": "A vector of four 64-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_double4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_double4"
        }
      ],
      "role": "symbol",
      "title": "simd_double4",
      "type": "topic",
      "url": "/documentation/simd/simd_double4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double4x4": {
      "abstract": [
        {
          "text": "A matrix of four columns and four rows that contains double-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_double4x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4x4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_double4x4"
        }
      ],
      "role": "symbol",
      "title": "simd_double4x4",
      "type": "topic",
      "url": "/documentation/simd/simd_double4x4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_matrix(_:_:_:_:)-28at0": {
      "abstract": [
        {
          "text": "Returns a new matrix with the specified columns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_matrix"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double4x4",
          "text": "simd_double4x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_matrix(_:_:_:_:)-28at0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_matrix"
        }
      ],
      "role": "symbol",
      "title": "simd_matrix(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_matrix(_:_:_:_:)-28at0"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_matrix4x4(_:)-20mdz": {
      "abstract": [
        {
          "text": "Returns a new matrix with the specified quarternion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_matrix4x4"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_quatd",
          "text": "simd_quatd"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double4x4",
          "text": "simd_double4x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_matrix4x4(_:)-20mdz",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_matrix4x4"
        }
      ],
      "role": "symbol",
      "title": "simd_matrix4x4(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_matrix4x4(_:)-20mdz"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_matrix_from_rows(_:_:_:_:)-898tw": {
      "abstract": [
        {
          "text": "Returns a new matrix with the specified rows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_matrix_from_rows"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double4x4",
          "text": "simd_double4x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_matrix_from_rows(_:_:_:_:)-898tw",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_matrix_from_rows"
        }
      ],
      "role": "symbol",
      "title": "simd_matrix_from_rows(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_matrix_from_rows(_:_:_:_:)-898tw"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Matrix-Creation-Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_matrix(_:_:_:_:)-28at0",
        "doc://com.apple.accelerate/documentation/simd/simd_matrix_from_rows(_:_:_:_:)-898tw",
        "doc://com.apple.accelerate/documentation/simd/simd_matrix4x4(_:)-20mdz"
      ],
      "title": "Matrix Creation Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_matrix4x4(_:)-20mdz/title",
          "value": "simd_matrix4x4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_matrix4x4(_:)-20mdz/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_matrix4x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_matrix_from_rows(_:_:_:_:)-898tw/title",
          "value": "simd_matrix_from_rows"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_matrix_from_rows(_:_:_:_:)-898tw/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_matrix_from_rows"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4x4/title",
          "value": "simd_double4x4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4x4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double4x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4x4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double4x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_matrix(_:_:_:_:)-28at0/title",
          "value": "simd_matrix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_matrix(_:_:_:_:)-28at0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_matrix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4/title",
          "value": "simd_double4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double4"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_diagonal_matrix-2kzr8"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
