{
  "abstract": [
    {
      "text": "A vector of three 16-bit unsigned integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_ushort3"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@simd_ushort3",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simd_ushort3"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_ushort3"
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "simd_ushort3"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_ushort3"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5SIMD3V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5SIMD3V",
              "text": "SIMD3"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt16V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt16V",
              "text": "UInt16"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1a7fa": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_all"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort3",
          "text": "simd_ushort3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_bool",
          "text": "simd_bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1a7fa",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_all"
        }
      ],
      "role": "symbol",
      "title": "simd_all(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_all(_:)-1a7fa"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-69p6w": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_any"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort3",
          "text": "simd_ushort3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_bool",
          "text": "simd_bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-69p6w",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_any"
        }
      ],
      "role": "symbol",
      "title": "simd_any(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_any(_:)-69p6w"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-7yglw": {
      "abstract": [
        {
          "text": "Returns a vector that contains elements from either the first or second parameter, based on the corresponding element in the third parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_bitselect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort3",
          "text": "simd_ushort3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort3",
          "text": "simd_ushort3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short3",
          "text": "simd_short3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort3",
          "text": "simd_ushort3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-7yglw",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_bitselect"
        }
      ],
      "role": "symbol",
      "title": "simd_bitselect(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_bitselect(_:_:_:)-7yglw"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-4akg3": {
      "abstract": [
        {
          "text": "Returns each element in a vector clamped to a specified range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_clamp"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort3",
          "text": "simd_ushort3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort3",
          "text": "simd_ushort3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort3",
          "text": "simd_ushort3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort3",
          "text": "simd_ushort3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-4akg3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_clamp"
        }
      ],
      "role": "symbol",
      "title": "simd_clamp(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_clamp(_:_:_:)-4akg3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-9b270": {
      "abstract": [
        {
          "text": "Returns true if every element in a vector is exactly equal to the corresponding element in a second vector, and otherwise returns false.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_equal"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort3",
          "text": "simd_ushort3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort3",
          "text": "simd_ushort3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_bool",
          "text": "simd_bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-9b270",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_equal"
        }
      ],
      "role": "symbol",
      "title": "simd_equal(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_equal(_:_:)-9b270"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort3(_:)-11fhu": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified thirty two-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort32",
          "text": "simd_ushort32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort3",
          "text": "simd_ushort3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort3(_:)-11fhu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort3"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort3(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort3(_:)-11fhu"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort3(_:)-58w42": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified sixteen-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort16",
          "text": "simd_ushort16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort3",
          "text": "simd_ushort3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort3(_:)-58w42",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort3"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort3(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort3(_:)-58w42"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort3(_:)-7fbo6": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified eight-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort8",
          "text": "simd_ushort8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort3",
          "text": "simd_ushort3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort3(_:)-7fbo6",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort3"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort3(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort3(_:)-7fbo6"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort3(_:)-7u2h6": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified four-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort4",
          "text": "simd_ushort4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort3",
          "text": "simd_ushort3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort3(_:)-7u2h6",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort3"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort3(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort3(_:)-7u2h6"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort3(_:)-7xag1": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort3",
          "text": "simd_ushort3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort3",
          "text": "simd_ushort3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort3(_:)-7xag1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort3"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort3(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort3(_:)-7xag1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort3(_:)-80g2g": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort2",
          "text": "simd_ushort2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort3",
          "text": "simd_ushort3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort3(_:)-80g2g",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort3"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort3(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort3(_:)-80g2g"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort3(_:)-93msa": {
      "abstract": [
        {
          "text": "Returns a new vector with the first element set to a scalar value, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort3",
          "text": "simd_ushort3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort3(_:)-93msa",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort3"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort3(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort3(_:)-93msa"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort3(_:_:)-3ap3r": {
      "abstract": [
        {
          "text": "Returns a new vector from a vector and a scalar value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort2",
          "text": "simd_ushort2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort3",
          "text": "simd_ushort3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort3(_:_:)-3ap3r",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort3"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort3(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort3(_:_:)-3ap3r"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort3(_:_:)-9h935": {
      "abstract": [
        {
          "text": "Returns a new vector from a scalar value and a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort2",
          "text": "simd_ushort2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort3",
          "text": "simd_ushort3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort3(_:_:)-9h935",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort3"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort3(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort3(_:_:)-9h935"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort3(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified scalar values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort3",
          "text": "simd_ushort3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort3(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort3"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort3(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort3(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort3_undef(_:)-6cyga": {
      "abstract": [
        {
          "text": "Returns a new vector with the first element set to a scalar value, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort3_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort3",
          "text": "simd_ushort3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort3_undef(_:)-6cyga",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort3_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort3_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort3_undef(_:)-6cyga"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort3_undef(_:)-6m2i9": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort3_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort2",
          "text": "simd_ushort2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort3",
          "text": "simd_ushort3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort3_undef(_:)-6m2i9",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort3_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort3_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort3_undef(_:)-6m2i9"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-4fcp5": {
      "abstract": [
        {
          "text": "Returns the maximum value of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_max"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort3",
          "text": "simd_ushort3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort3",
          "text": "simd_ushort3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort3",
          "text": "simd_ushort3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-4fcp5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_max"
        }
      ],
      "role": "symbol",
      "title": "simd_max(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_max(_:_:)-4fcp5"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-4jk8l": {
      "abstract": [
        {
          "text": "Returns the minimum value of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_min"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort3",
          "text": "simd_ushort3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort3",
          "text": "simd_ushort3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort3",
          "text": "simd_ushort3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-4jk8l",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_min"
        }
      ],
      "role": "symbol",
      "title": "simd_min(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_min(_:_:)-4jk8l"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-2vbub": {
      "abstract": [
        {
          "text": "Returns the sum of all elements in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_add"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort3",
          "text": "simd_ushort3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-2vbub",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_add"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_add(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_add(_:)-2vbub"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-4h4s1": {
      "abstract": [
        {
          "text": "Returns the maximum value in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_max"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort3",
          "text": "simd_ushort3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-4h4s1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_max"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_max(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_max(_:)-4h4s1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-46gdl": {
      "abstract": [
        {
          "text": "Returns the miniumum value in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_min"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort3",
          "text": "simd_ushort3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-46gdl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_min"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_min(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_min(_:)-46gdl"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort-3fra2": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort-3fra2",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort-3fra2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort-3fudi": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort-3fudi",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort-3fudi"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort-3fvby": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort-3fvby",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort-3fvby"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort-3fw9m": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort-3fw9m",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort-3fw9m"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort-3g196": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort-3g196",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort-3g196"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort-3g22q": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort-3g22q",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort-3g22q"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort-3g2v2": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort-3g2v2",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort-3g2v2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort-3g492": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort-3g492",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort-3g492"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort-3g5b2": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort-3g5b2",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort-3g5b2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort-3g656": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort-3g656",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort-3g656"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort1": {
      "abstract": [
        {
          "text": "A vector of one 16-bit unsigned integer element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ushort1"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ushort1"
        }
      ],
      "role": "symbol",
      "title": "simd_ushort1",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort16": {
      "abstract": [
        {
          "text": "A vector of sixteen 16-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ushort16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ushort16"
        }
      ],
      "role": "symbol",
      "title": "simd_ushort16",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort16"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort2": {
      "abstract": [
        {
          "text": "A vector of two 16-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ushort2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ushort2"
        }
      ],
      "role": "symbol",
      "title": "simd_ushort2",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort3": {
      "abstract": [
        {
          "text": "A vector of three 16-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ushort3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ushort3"
        }
      ],
      "role": "symbol",
      "title": "simd_ushort3",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort32": {
      "abstract": [
        {
          "text": "A vector of thirty-two 16-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ushort32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ushort32"
        }
      ],
      "role": "symbol",
      "title": "simd_ushort32",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort32"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort4": {
      "abstract": [
        {
          "text": "A vector of four 16-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ushort4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ushort4"
        }
      ],
      "role": "symbol",
      "title": "simd_ushort4",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort8": {
      "abstract": [
        {
          "text": "A vector of eight 16-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ushort8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ushort8"
        }
      ],
      "role": "symbol",
      "title": "simd_ushort8",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kapv": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kapv",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-7kapv"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kfoj": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kfoj",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-7kfoj"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kipj": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kipj",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-7kipj"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kk9d": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kk9d",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-7kk9d"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kkoz": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kkoz",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-7kkoz"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kpib": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kpib",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-7kpib"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kr89": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kr89",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-7kr89"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kroh": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kroh",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-7kroh"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kstz": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kstz",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-7kstz"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kuc1": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kuc1",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort_sat-7kuc1"
    },
    "doc://com.apple.accelerate/documentation/simd/vector3-5er36": {
      "abstract": [
        {
          "text": "Returns a new vector from a vector and a scalar value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector3-5er36",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector3",
      "type": "topic",
      "url": "/documentation/simd/vector3-5er36"
    },
    "doc://com.apple.accelerate/documentation/simd/vector3-6gujk": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified scalar values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector3-6gujk",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector3",
      "type": "topic",
      "url": "/documentation/simd/vector3-6gujk"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_ushort3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vector_ushort3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_ushort3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vector_ushort3"
        }
      ],
      "role": "symbol",
      "title": "vector_ushort3",
      "type": "topic",
      "url": "/documentation/simd/vector_ushort3"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s5SIMD3V": {
      "abstract": [
        {
          "text": "A vector of three scalar values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SIMD3"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SIMDScalarP",
          "text": "SIMDScalar"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5SIMD3V",
      "kind": "symbol",
      "role": "symbol",
      "title": "SIMD3",
      "type": "topic",
      "url": "/documentation/Swift/SIMD3"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt16V": {
      "abstract": [
        {
          "text": "A 16-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt16"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt16V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt16",
      "type": "topic",
      "url": "/documentation/Swift/UInt16"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Vector-Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_ushort1",
        "doc://com.apple.accelerate/documentation/simd/simd_ushort2",
        "doc://com.apple.accelerate/documentation/simd/simd_ushort4",
        "doc://com.apple.accelerate/documentation/simd/simd_ushort8",
        "doc://com.apple.accelerate/documentation/simd/simd_ushort16",
        "doc://com.apple.accelerate/documentation/simd/simd_ushort32"
      ],
      "title": "Vector Data Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Functions-to-Create-Three-Element-Vectors-From-Other-Vectors",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_ushort3(_:)-80g2g",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ushort3(_:)-7xag1",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ushort3(_:)-7u2h6",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ushort3(_:)-7fbo6",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ushort3(_:)-58w42",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ushort3(_:)-11fhu",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ushort3_undef(_:)-6m2i9"
      ],
      "title": "Functions to Create Three-Element Vectors From Other Vectors"
    },
    {
      "anchor": "Functions-to-Create-Three-Element-Vectors-From-Scalar-Values",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_ushort3(_:)-93msa",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ushort3(_:_:_:)",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ushort3_undef(_:)-6cyga"
      ],
      "title": "Functions to Create Three-Element Vectors From Scalar Values"
    },
    {
      "anchor": "Functions-to-Create-Three-Element-Vectors-From-Combinations-of-Vectors-and-Scalar-Values",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_ushort3(_:_:)-3ap3r",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ushort3(_:_:)-9h935"
      ],
      "title": "Functions to Create Three-Element Vectors From Combinations of Vectors and Scalar Values"
    },
    {
      "anchor": "Common-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-4akg3",
        "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-9b270"
      ],
      "title": "Common Functions"
    },
    {
      "anchor": "Reduce-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-46gdl",
        "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-4h4s1",
        "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-2vbub"
      ],
      "title": "Reduce Functions"
    },
    {
      "anchor": "Extrema-Function",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-4jk8l",
        "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-4fcp5"
      ],
      "title": "Extrema Function"
    },
    {
      "anchor": "Logic-and-Bitwise-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-69p6w",
        "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1a7fa",
        "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-7yglw"
      ],
      "title": "Logic and Bitwise Functions"
    },
    {
      "anchor": "Alternative-Type-Alias",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/vector_ushort3"
      ],
      "title": "Alternative Type Alias"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "simd_ushort3"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/simd"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Functions-to-Create-Three-Element-Vectors-From-Other-Vectors",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_ushort3(_:)-80g2g",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ushort3(_:)-7xag1",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ushort3(_:)-7u2h6",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ushort3(_:)-7fbo6",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ushort3(_:)-58w42",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ushort3(_:)-11fhu",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ushort3_undef(_:)-6m2i9"
              ],
              "title": "Functions to Create Three-Element Vectors From Other Vectors"
            },
            {
              "anchor": "Functions-to-Create-Three-Element-Vectors-From-Scalar-Values",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_ushort3(_:)-93msa",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ushort3(_:_:_:)",
                "doc://com.apple.accelerate/documentation/simd/vector3-6gujk",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ushort3_undef(_:)-6cyga"
              ],
              "title": "Functions to Create Three-Element Vectors From Scalar Values"
            },
            {
              "anchor": "Functions-to-Create-Three-Element-Vectors-From-Combinations-of-Vectors-and-Scalar-Values",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/vector3-5er36",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ushort3(_:_:)-3ap3r",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ushort3(_:_:)-9h935"
              ],
              "title": "Functions to Create Three-Element Vectors From Combinations of Vectors and Scalar Values"
            },
            {
              "anchor": "Functions-to-Create-Three-Element-Vectors-From-Vectors-of-Other-Types",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_ushort-3fra2",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort-3g196",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort-3fw9m",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort-3g656",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort-3fudi",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort-3g492",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort-3fvby",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort-3g5b2",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort-3g22q",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort-3g2v2"
              ],
              "title": "Functions to Create Three-Element Vectors From Vectors of Other Types"
            },
            {
              "anchor": "Functions-to-Perform-Saturating-Conversion-From-Vectors-of-Other-Types",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kfoj",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kpib",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kapv",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kkoz",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kipj",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kstz",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kk9d",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kuc1",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kr89",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort_sat-7kroh"
              ],
              "title": "Functions to Perform Saturating Conversion From Vectors of Other Types"
            },
            {
              "anchor": "Common-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-4akg3",
                "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-9b270"
              ],
              "title": "Common Functions"
            },
            {
              "anchor": "Reduce-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-46gdl",
                "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-4h4s1",
                "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-2vbub"
              ],
              "title": "Reduce Functions"
            },
            {
              "anchor": "Extrema-Function",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-4jk8l",
                "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-4fcp5"
              ],
              "title": "Extrema Function"
            },
            {
              "anchor": "Logic-and-Bitwise-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-69p6w",
                "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1a7fa",
                "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-7yglw"
              ],
              "title": "Logic and Bitwise Functions"
            },
            {
              "anchor": "Alternative-Type-Alias",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/vector_ushort3"
              ],
              "title": "Alternative Type Alias"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Vector-Data-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_ushort1",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort2",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort4",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort8",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort16",
                "doc://com.apple.accelerate/documentation/simd/simd_ushort32"
              ],
              "title": "Vector Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:]3s",
                    "text": "unsigned short __attribute__((ext_vector_type(3)))"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "simd_ushort3"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_any(_:)-69p6w/title",
          "value": "simd_any"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_any(_:)-69p6w/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_any"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_equal(_:_:)-9b270/title",
          "value": "simd_equal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_equal(_:_:)-9b270/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_equal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort3(_:)-80g2g/title",
          "value": "simd_make_ushort3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort3(_:)-80g2g/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort3(_:_:)-9h935/title",
          "value": "simd_make_ushort3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort3(_:_:)-9h935/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_add(_:)-2vbub/title",
          "value": "simd_reduce_add"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_add(_:)-2vbub/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_add"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_all(_:)-1a7fa/title",
          "value": "simd_all"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_all(_:)-1a7fa/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_all"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort2/title",
          "value": "simd_ushort2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort3_undef(_:)-6cyga/title",
          "value": "simd_make_ushort3_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort3_undef(_:)-6cyga/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort3_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort4/title",
          "value": "simd_ushort4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort3(_:)-7xag1/title",
          "value": "simd_make_ushort3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort3(_:)-7xag1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1vector_ushort3/title",
          "value": "vector_ushort3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1vector_ushort3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vector_ushort3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1vector_ushort3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vector_ushort3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_max(_:)-4h4s1/title",
          "value": "simd_reduce_max"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_max(_:)-4h4s1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_max"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_clamp(_:_:_:)-4akg3/title",
          "value": "simd_clamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_clamp(_:_:_:)-4akg3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_clamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_min(_:_:)-4jk8l/title",
          "value": "simd_min"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_min(_:_:)-4jk8l/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_min"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort3(_:)-11fhu/title",
          "value": "simd_make_ushort3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort3(_:)-11fhu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort3/title",
          "value": "simd_ushort3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_max(_:_:)-4fcp5/title",
          "value": "simd_max"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_max(_:_:)-4fcp5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_max"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort3(_:)-7fbo6/title",
          "value": "simd_make_ushort3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort3(_:)-7fbo6/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort3(_:)-58w42/title",
          "value": "simd_make_ushort3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort3(_:)-58w42/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort3(_:)-93msa/title",
          "value": "simd_make_ushort3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort3(_:)-93msa/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort32/title",
          "value": "simd_ushort32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort32/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_bitselect(_:_:_:)-7yglw/title",
          "value": "simd_bitselect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_bitselect(_:_:_:)-7yglw/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_bitselect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort3(_:_:)-3ap3r/title",
          "value": "simd_make_ushort3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort3(_:_:)-3ap3r/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_min(_:)-46gdl/title",
          "value": "simd_reduce_min"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_min(_:)-46gdl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_min"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort1/title",
          "value": "simd_ushort1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort1/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort16/title",
          "value": "simd_ushort16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort16/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort3_undef(_:)-6m2i9/title",
          "value": "simd_make_ushort3_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort3_undef(_:)-6m2i9/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort3_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort8/title",
          "value": "simd_ushort8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort3(_:_:_:)/title",
          "value": "simd_make_ushort3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort3(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort3(_:)-7u2h6/title",
          "value": "simd_make_ushort3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort3(_:)-7u2h6/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort3"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_ushort3"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/simd/simd_ushort3"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
