{
  "abstract": [
    {
      "text": "Returns the first vector projected onto the second vector.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_project-24ld6"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_project#]4h#S0_#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_project"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_project"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_project"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half4",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_half4",
              "text": "simd_half4"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_project"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half4",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_half4",
              "text": "simd_half4"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half4",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_half4",
              "text": "simd_half4"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__y"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_dot-87ssc": {
      "abstract": [
        {
          "text": "Returns the dot product of two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_dot"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_dot-87ssc",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_dot",
      "type": "topic",
      "url": "/documentation/simd/simd_dot-87ssc"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_fast_normalize-3vaz": {
      "abstract": [
        {
          "text": "Returns the fast normalized vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_fast_normalize"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_fast_normalize-3vaz",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_fast_normalize",
      "type": "topic",
      "url": "/documentation/simd/simd_fast_normalize-3vaz"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_fast_project-6ymj6": {
      "abstract": [
        {
          "text": "Returns the fast projected vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_fast_project"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_fast_project-6ymj6",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_fast_project",
      "type": "topic",
      "url": "/documentation/simd/simd_fast_project-6ymj6"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half4": {
      "abstract": [
        {
          "text": "A vector of four 16-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_half4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_half4"
        }
      ],
      "role": "symbol",
      "title": "simd_half4",
      "type": "topic",
      "url": "/documentation/simd/simd_half4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_normalize-9o6iq": {
      "abstract": [
        {
          "text": "Returns a vector pointing in the same direction of the supplied vector, with a length of 1.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_normalize"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_normalize-9o6iq",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_normalize",
      "type": "topic",
      "url": "/documentation/simd/simd_normalize-9o6iq"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_precise_normalize-4vqaw": {
      "abstract": [
        {
          "text": "Returns the precise normalized vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_precise_normalize"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_precise_normalize-4vqaw",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_precise_normalize",
      "type": "topic",
      "url": "/documentation/simd/simd_precise_normalize-4vqaw"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_precise_project-1cw2i": {
      "abstract": [
        {
          "text": "Returns the precise projected vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_precise_project"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_precise_project-1cw2i",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_precise_project",
      "type": "topic",
      "url": "/documentation/simd/simd_precise_project-1cw2i"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_project-24ld6": {
      "abstract": [
        {
          "text": "Returns the first vector projected onto the second vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_project"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_project-24ld6",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_project",
      "type": "topic",
      "url": "/documentation/simd/simd_project-24ld6"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reflect-9r760": {
      "abstract": [
        {
          "text": "Returns the reflection direction of an incident vector and a unit normal vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_reflect"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reflect-9r760",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_reflect",
      "type": "topic",
      "url": "/documentation/simd/simd_reflect-9r760"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_refract-6q75f": {
      "abstract": [
        {
          "text": "Returns the refraction direction of an incident vector, a unit normal vector, and an index of refraction eta.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_refract"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_refract-6q75f",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_refract",
      "type": "topic",
      "url": "/documentation/simd/simd_refract-6q75f"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Geometry-functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_dot-87ssc",
        "doc://com.apple.accelerate/documentation/simd/simd_normalize-9o6iq",
        "doc://com.apple.accelerate/documentation/simd/simd_fast_normalize-3vaz",
        "doc://com.apple.accelerate/documentation/simd/simd_precise_normalize-4vqaw",
        "doc://com.apple.accelerate/documentation/simd/simd_precise_project-1cw2i",
        "doc://com.apple.accelerate/documentation/simd/simd_fast_project-6ymj6",
        "doc://com.apple.accelerate/documentation/simd/simd_reflect-9r760",
        "doc://com.apple.accelerate/documentation/simd/simd_refract-6q75f"
      ],
      "title": "Geometry functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half4/title",
          "value": "simd_half4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half4"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_project-24ld6"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
