{
  "abstract": [
    {
      "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_ushort-44iu5"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_ushort#]8s#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_ushort"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_ushort"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_ushort"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort8",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_ushort8",
              "text": "simd_ushort8"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_ushort"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort8",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_ushort8",
              "text": "simd_ushort8"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort-443vh": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort-443vh",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort-443vh"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort-44617": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort-44617",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort-44617"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort-446z9": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort-446z9",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort-446z9"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort-448v1": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort-448v1",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort-448v1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort-44cwv": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort-44cwv",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort-44cwv"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort-44dgr": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort-44dgr",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort-44dgr"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort-44dr1": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort-44dr1",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort-44dr1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort-44fwr": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort-44fwr",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort-44fwr"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort-44gyd": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort-44gyd",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort-44gyd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort-44iu5": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort-44iu5",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort-44iu5"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort8": {
      "abstract": [
        {
          "text": "A vector of eight 16-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ushort8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ushort8"
        }
      ],
      "role": "symbol",
      "title": "simd_ushort8",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort8"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Create-Eight-Element-Vectors-From-Vectors-of-Other-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_ushort-443vh",
        "doc://com.apple.accelerate/documentation/simd/simd_ushort-44dr1",
        "doc://com.apple.accelerate/documentation/simd/simd_ushort-448v1",
        "doc://com.apple.accelerate/documentation/simd/simd_ushort-446z9",
        "doc://com.apple.accelerate/documentation/simd/simd_ushort-44gyd",
        "doc://com.apple.accelerate/documentation/simd/simd_ushort-44617",
        "doc://com.apple.accelerate/documentation/simd/simd_ushort-44fwr",
        "doc://com.apple.accelerate/documentation/simd/simd_ushort-44cwv",
        "doc://com.apple.accelerate/documentation/simd/simd_ushort-44dgr"
      ],
      "title": "Functions to Create Eight-Element Vectors From Vectors of Other Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort8/title",
          "value": "simd_ushort8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort8"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_ushort-44iu5"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
