{
  "abstract": [
    {
      "text": "Returns a new vector by truncating the specified thrity two-element vector.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:)-8mc9h"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_make_short8#]32S#",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simd_make_short8"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_short32",
        "text": "simd_short32"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_short8",
        "text": "simd_short8"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_make_short8"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_make_short8(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_make_short8"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "other"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short32",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_short32",
              "text": "simd_short32"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short8",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_short8",
              "text": "simd_short8"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:)-22n5y": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified sixteen-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short16",
          "text": "simd_short16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:)-22n5y",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short8(_:)-22n5y"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:)-5gjta": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:)-5gjta",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short8(_:)-5gjta"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:)-5wv29": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified three-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short3",
          "text": "simd_short3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:)-5wv29",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short8(_:)-5wv29"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:)-600rc": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short2",
          "text": "simd_short2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:)-600rc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short8(_:)-600rc"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:)-6l7oy": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified four-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short4",
          "text": "simd_short4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:)-6l7oy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short8(_:)-6l7oy"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:)-8mc9h": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified thrity two-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short32",
          "text": "simd_short32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:)-8mc9h",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short8(_:)-8mc9h"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short4",
          "text": "simd_short4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short4",
          "text": "simd_short4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short8(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short8(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short8_undef(_:)-54hbi": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short8_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short2",
          "text": "simd_short2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short8_undef(_:)-54hbi",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short8_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short8_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short8_undef(_:)-54hbi"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short8_undef(_:)-57mlz": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified three-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short8_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short3",
          "text": "simd_short3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short8_undef(_:)-57mlz",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short8_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short8_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short8_undef(_:)-57mlz"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short8_undef(_:)-5ny5g": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified four-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short8_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short4",
          "text": "simd_short4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short8_undef(_:)-5ny5g",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short8_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short8_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short8_undef(_:)-5ny5g"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short32": {
      "abstract": [
        {
          "text": "A vector of thirty-two 16-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_short32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_short32"
        }
      ],
      "role": "symbol",
      "title": "simd_short32",
      "type": "topic",
      "url": "/documentation/simd/simd_short32"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short8": {
      "abstract": [
        {
          "text": "A vector of eight 16-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_short8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_short8"
        }
      ],
      "role": "symbol",
      "title": "simd_short8",
      "type": "topic",
      "url": "/documentation/simd/simd_short8"
    },
    "doc://com.apple.accelerate/documentation/simd/vector8-7jnqf": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector8-7jnqf",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector8",
      "type": "topic",
      "url": "/documentation/simd/vector8-7jnqf"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Create-Eight-Element-Vectors-From-Other-Vectors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:)-600rc",
        "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:)-5wv29",
        "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:)-6l7oy",
        "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:)-5gjta",
        "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:)-22n5y",
        "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:_:)",
        "doc://com.apple.accelerate/documentation/simd/simd_make_short8_undef(_:)-54hbi",
        "doc://com.apple.accelerate/documentation/simd/simd_make_short8_undef(_:)-57mlz",
        "doc://com.apple.accelerate/documentation/simd/simd_make_short8_undef(_:)-5ny5g"
      ],
      "title": "Functions to Create Eight-Element Vectors From Other Vectors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "simd_make_short8"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/simd"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Functions-to-Create-Eight-Element-Vectors-From-Other-Vectors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:)-600rc",
                "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:)-5wv29",
                "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:)-6l7oy",
                "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:)-5gjta",
                "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:)-22n5y",
                "doc://com.apple.accelerate/documentation/simd/simd_make_short8(_:_:)",
                "doc://com.apple.accelerate/documentation/simd/vector8-7jnqf",
                "doc://com.apple.accelerate/documentation/simd/simd_make_short8_undef(_:)-54hbi",
                "doc://com.apple.accelerate/documentation/simd/simd_make_short8_undef(_:)-57mlz",
                "doc://com.apple.accelerate/documentation/simd/simd_make_short8_undef(_:)-5ny5g"
              ],
              "title": "Functions to Create Eight-Element Vectors From Other Vectors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "static"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short8",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_short8",
                    "text": "simd_short8"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "simd_make_short8"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short32",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_short32",
                    "text": "simd_short32"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "other"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short8(_:)-600rc/title",
          "value": "simd_make_short8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short8(_:)-600rc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short8/title",
          "value": "simd_short8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short8_undef(_:)-5ny5g/title",
          "value": "simd_make_short8_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short8_undef(_:)-5ny5g/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short8_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short8(_:)-5wv29/title",
          "value": "simd_make_short8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short8(_:)-5wv29/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short32/title",
          "value": "simd_short32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short32/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short8_undef(_:)-57mlz/title",
          "value": "simd_make_short8_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short8_undef(_:)-57mlz/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short8_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short8(_:)-22n5y/title",
          "value": "simd_make_short8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short8(_:)-22n5y/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short8_undef(_:)-54hbi/title",
          "value": "simd_make_short8_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short8_undef(_:)-54hbi/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short8_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short8(_:)-6l7oy/title",
          "value": "simd_make_short8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short8(_:)-6l7oy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short8(_:)-5gjta/title",
          "value": "simd_make_short8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short8(_:)-5gjta/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short8(_:_:)/title",
          "value": "simd_make_short8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short8(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short8(_:)-8mc9h/title",
          "value": "simd_make_short8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short8(_:)-8mc9h/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short8"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_make_short8(_:)-8mc9h"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/simd/simd_make_short8(_:)-8mc9h"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
