{
  "abstract": [
    {
      "text": "Returns the precise reciprocal of each element in a vector.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_precise_recip(_:)-74cqq"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_precise_recip#]8d#",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simd_precise_recip"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_double8",
        "text": "simd_double8"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_double8",
        "text": "simd_double8"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_precise_recip"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_precise_recip(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_precise_recip"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "x"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double8",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_double8",
              "text": "simd_double8"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double8",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_double8",
              "text": "simd_double8"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double8": {
      "abstract": [
        {
          "text": "A vector of eight 64-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_double8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_double8"
        }
      ],
      "role": "symbol",
      "title": "simd_double8",
      "type": "topic",
      "url": "/documentation/simd/simd_double8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_fast_recip(_:)-16f97": {
      "abstract": [
        {
          "text": "Returns the fast reciprocal of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_fast_recip"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double8",
          "text": "simd_double8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double8",
          "text": "simd_double8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_fast_recip(_:)-16f97",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_fast_recip"
        }
      ],
      "role": "symbol",
      "title": "simd_fast_recip(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_fast_recip(_:)-16f97"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_fast_rsqrt(_:)-922us": {
      "abstract": [
        {
          "text": "Returns the fast reciprocal square root of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_fast_rsqrt"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double8",
          "text": "simd_double8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double8",
          "text": "simd_double8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_fast_rsqrt(_:)-922us",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_fast_rsqrt"
        }
      ],
      "role": "symbol",
      "title": "simd_fast_rsqrt(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_fast_rsqrt(_:)-922us"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_precise_recip(_:)-74cqq": {
      "abstract": [
        {
          "text": "Returns the precise reciprocal of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_precise_recip"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double8",
          "text": "simd_double8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double8",
          "text": "simd_double8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_precise_recip(_:)-74cqq",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_precise_recip"
        }
      ],
      "role": "symbol",
      "title": "simd_precise_recip(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_precise_recip(_:)-74cqq"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_precise_rsqrt(_:)-1hq00": {
      "abstract": [
        {
          "text": "Returns the precise reciprocal square root of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_precise_rsqrt"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double8",
          "text": "simd_double8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double8",
          "text": "simd_double8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_precise_rsqrt(_:)-1hq00",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_precise_rsqrt"
        }
      ],
      "role": "symbol",
      "title": "simd_precise_rsqrt(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_precise_rsqrt(_:)-1hq00"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_recip(_:)-98afu": {
      "abstract": [
        {
          "text": "Returns the reciprocal of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_recip"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double8",
          "text": "simd_double8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double8",
          "text": "simd_double8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_recip(_:)-98afu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_recip"
        }
      ],
      "role": "symbol",
      "title": "simd_recip(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_recip(_:)-98afu"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_rsqrt(_:)-1ojpy": {
      "abstract": [
        {
          "text": "Returns the reciprocal square root of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_rsqrt"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double8",
          "text": "simd_double8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double8",
          "text": "simd_double8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_rsqrt(_:)-1ojpy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_rsqrt"
        }
      ],
      "role": "symbol",
      "title": "simd_rsqrt(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_rsqrt(_:)-1ojpy"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reciprocal-and-Reciprocal-Square-Root-Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_recip(_:)-98afu",
        "doc://com.apple.accelerate/documentation/simd/simd_fast_recip(_:)-16f97",
        "doc://com.apple.accelerate/documentation/simd/simd_rsqrt(_:)-1ojpy",
        "doc://com.apple.accelerate/documentation/simd/simd_fast_rsqrt(_:)-922us",
        "doc://com.apple.accelerate/documentation/simd/simd_precise_rsqrt(_:)-1hq00"
      ],
      "title": "Reciprocal and Reciprocal Square Root Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "simd_precise_recip"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_precise_recip"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/simd"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reciprocal-and-Reciprocal-Square-Root-Functions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_recip(_:)-98afu",
                "doc://com.apple.accelerate/documentation/simd/simd_fast_recip(_:)-16f97",
                "doc://com.apple.accelerate/documentation/simd/simd_rsqrt(_:)-1ojpy",
                "doc://com.apple.accelerate/documentation/simd/simd_fast_rsqrt(_:)-922us",
                "doc://com.apple.accelerate/documentation/simd/simd_precise_rsqrt(_:)-1hq00"
              ],
              "title": "Reciprocal and Reciprocal Square Root Functions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "static"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double8",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_double8",
                    "text": "simd_double8"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "simd_precise_recip"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double8",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_double8",
                    "text": "simd_double8"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "x"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_fast_rsqrt(_:)-922us/title",
          "value": "simd_fast_rsqrt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_fast_rsqrt(_:)-922us/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_fast_rsqrt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_precise_recip(_:)-74cqq/title",
          "value": "simd_precise_recip"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_precise_recip(_:)-74cqq/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_precise_recip"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_precise_rsqrt(_:)-1hq00/title",
          "value": "simd_precise_rsqrt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_precise_rsqrt(_:)-1hq00/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_precise_rsqrt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_recip(_:)-98afu/title",
          "value": "simd_recip"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_recip(_:)-98afu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_recip"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_rsqrt(_:)-1ojpy/title",
          "value": "simd_rsqrt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_rsqrt(_:)-1ojpy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_rsqrt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double8/title",
          "value": "simd_double8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_fast_recip(_:)-16f97/title",
          "value": "simd_fast_recip"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_fast_recip(_:)-16f97/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_fast_recip"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_precise_recip(_:)-74cqq"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/simd/simd_precise_recip(_:)-74cqq"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
