{
  "abstract": [
    {
      "text": "Returns a new vector from the specified vector of 8-bit, signed-integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_float-33quw"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_float#]16C#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_float"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_float"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_float"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float16",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_float16",
              "text": "simd_float16"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_float"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char16",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_char16",
              "text": "simd_char16"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char16": {
      "abstract": [
        {
          "text": "A vector of sixteen 8-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_char16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_char16"
        }
      ],
      "role": "symbol",
      "title": "simd_char16",
      "type": "topic",
      "url": "/documentation/simd/simd_char16"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float-33bqw": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float-33bqw",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_float",
      "type": "topic",
      "url": "/documentation/simd/simd_float-33bqw"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float-33eyg": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float-33eyg",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_float",
      "type": "topic",
      "url": "/documentation/simd/simd_float-33eyg"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float-33h14": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float-33h14",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_float",
      "type": "topic",
      "url": "/documentation/simd/simd_float-33h14"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float-33i8s": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float-33i8s",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_float",
      "type": "topic",
      "url": "/documentation/simd/simd_float-33i8s"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float-33lyw": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float-33lyw",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_float",
      "type": "topic",
      "url": "/documentation/simd/simd_float-33lyw"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float-33os8": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float-33os8",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_float",
      "type": "topic",
      "url": "/documentation/simd/simd_float-33os8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float-33quw": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float-33quw",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_float",
      "type": "topic",
      "url": "/documentation/simd/simd_float-33quw"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float16": {
      "abstract": [
        {
          "text": "A vector of sixteen 32-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_float16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_float16"
        }
      ],
      "role": "symbol",
      "title": "simd_float16",
      "type": "topic",
      "url": "/documentation/simd/simd_float16"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Create-16-Element-Vectors-From-Vectors-of-Other-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_float-33h14",
        "doc://com.apple.accelerate/documentation/simd/simd_float-33lyw",
        "doc://com.apple.accelerate/documentation/simd/simd_float-33bqw",
        "doc://com.apple.accelerate/documentation/simd/simd_float-33os8",
        "doc://com.apple.accelerate/documentation/simd/simd_float-33eyg",
        "doc://com.apple.accelerate/documentation/simd/simd_float-33i8s"
      ],
      "title": "Functions to Create 16-Element Vectors From Vectors of Other Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float16/title",
          "value": "simd_float16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float16/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char16/title",
          "value": "simd_char16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char16/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char16"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_float-33quw"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
