{
  "abstract": [
    {
      "text": "A vector of three 8-bit unsigned integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_uchar3"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@simd_uchar3",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simd_uchar3"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_uchar3"
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "simd_uchar3"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_uchar3"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5SIMD3V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5SIMD3V",
              "text": "SIMD3"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5UInt8V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5UInt8V",
              "text": "UInt8"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1aceu": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_all"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar3",
          "text": "simd_uchar3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_bool",
          "text": "simd_bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1aceu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_all"
        }
      ],
      "role": "symbol",
      "title": "simd_all(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_all(_:)-1aceu"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-69k4o": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_any"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar3",
          "text": "simd_uchar3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_bool",
          "text": "simd_bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-69k4o",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_any"
        }
      ],
      "role": "symbol",
      "title": "simd_any(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_any(_:)-69k4o"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-2syfj": {
      "abstract": [
        {
          "text": "Returns a vector that contains elements from either the first or second parameter, based on the corresponding element in the third parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_bitselect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar3",
          "text": "simd_uchar3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar3",
          "text": "simd_uchar3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char3",
          "text": "simd_char3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar3",
          "text": "simd_uchar3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-2syfj",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_bitselect"
        }
      ],
      "role": "symbol",
      "title": "simd_bitselect(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_bitselect(_:_:_:)-2syfj"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-6h8i3": {
      "abstract": [
        {
          "text": "Returns each element in a vector clamped to a specified range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_clamp"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar3",
          "text": "simd_uchar3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar3",
          "text": "simd_uchar3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar3",
          "text": "simd_uchar3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar3",
          "text": "simd_uchar3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-6h8i3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_clamp"
        }
      ],
      "role": "symbol",
      "title": "simd_clamp(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_clamp(_:_:_:)-6h8i3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-8iga0": {
      "abstract": [
        {
          "text": "Returns true if every element in a vector is exactly equal to the corresponding element in a second vector, and otherwise returns false.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_equal"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar3",
          "text": "simd_uchar3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar3",
          "text": "simd_uchar3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_bool",
          "text": "simd_bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-8iga0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_equal"
        }
      ],
      "role": "symbol",
      "title": "simd_equal(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_equal(_:_:)-8iga0"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-38lno": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified thirty two-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar32",
          "text": "simd_uchar32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar3",
          "text": "simd_uchar3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-38lno",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar3"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar3(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar3(_:)-38lno"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-3p7i8": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified sixty four-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar64",
          "text": "simd_uchar64"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar3",
          "text": "simd_uchar3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-3p7i8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar3"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar3(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar3(_:)-3p7i8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-3sucp": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified eight-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar8",
          "text": "simd_uchar8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar3",
          "text": "simd_uchar3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-3sucp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar3"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar3(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar3(_:)-3sucp"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-45nsd": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified four-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar4",
          "text": "simd_uchar4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar3",
          "text": "simd_uchar3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-45nsd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar3"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar3(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar3(_:)-45nsd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-4nmxq": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar3",
          "text": "simd_uchar3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar3",
          "text": "simd_uchar3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-4nmxq",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar3"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar3(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar3(_:)-4nmxq"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-4qkxz": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar2",
          "text": "simd_uchar2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar3",
          "text": "simd_uchar3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-4qkxz",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar3"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar3(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar3(_:)-4qkxz"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-90ge7": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified sixteen-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar16",
          "text": "simd_uchar16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar3",
          "text": "simd_uchar3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-90ge7",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar3"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar3(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar3(_:)-90ge7"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-bybh": {
      "abstract": [
        {
          "text": "Returns a new vector with the first element set to a scalar value, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar3",
          "text": "simd_uchar3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-bybh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar3"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar3(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar3(_:)-bybh"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:_:)-2m5x7": {
      "abstract": [
        {
          "text": "Returns a new vector from a scalar value and a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar2",
          "text": "simd_uchar2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar3",
          "text": "simd_uchar3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:_:)-2m5x7",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar3"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar3(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar3(_:_:)-2m5x7"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:_:)-5tgih": {
      "abstract": [
        {
          "text": "Returns a new vector from a vector and a scalar value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar2",
          "text": "simd_uchar2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar3",
          "text": "simd_uchar3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:_:)-5tgih",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar3"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar3(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar3(_:_:)-5tgih"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified scalar values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar3",
          "text": "simd_uchar3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar3"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar3(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar3(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3_undef(_:)-562ub": {
      "abstract": [
        {
          "text": "Returns a new vector with the first element set to a scalar value, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar3_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar3",
          "text": "simd_uchar3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3_undef(_:)-562ub",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar3_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar3_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar3_undef(_:)-562ub"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3_undef(_:)-99t25": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uchar3_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar2",
          "text": "simd_uchar2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar3",
          "text": "simd_uchar3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3_undef(_:)-99t25",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uchar3_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uchar3_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uchar3_undef(_:)-99t25"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-8ylny": {
      "abstract": [
        {
          "text": "Returns the maximum value of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_max"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar3",
          "text": "simd_uchar3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar3",
          "text": "simd_uchar3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar3",
          "text": "simd_uchar3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-8ylny",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_max"
        }
      ],
      "role": "symbol",
      "title": "simd_max(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_max(_:_:)-8ylny"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-8h62y": {
      "abstract": [
        {
          "text": "Returns the minimum value of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_min"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar3",
          "text": "simd_uchar3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar3",
          "text": "simd_uchar3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar3",
          "text": "simd_uchar3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-8h62y",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_min"
        }
      ],
      "role": "symbol",
      "title": "simd_min(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_min(_:_:)-8h62y"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-2v6nn": {
      "abstract": [
        {
          "text": "Returns the sum of all elements in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_add"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar3",
          "text": "simd_uchar3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-2v6nn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_add"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_add(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_add(_:)-2v6nn"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-4gzsh": {
      "abstract": [
        {
          "text": "Returns the maximum value in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_max"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar3",
          "text": "simd_uchar3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-4gzsh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_max"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_max(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_max(_:)-4gzsh"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-46bd5": {
      "abstract": [
        {
          "text": "Returns the miniumum value in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_min"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uchar3",
          "text": "simd_uchar3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-46bd5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_min"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_min(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_min(_:)-46bd5"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar-8xmh3": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar-8xmh3",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar-8xmh3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar-8xnn5": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar-8xnn5",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar-8xnn5"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar-8xokr": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar-8xokr",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar-8xokr"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar-8xtjf": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar-8xtjf",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar-8xtjf"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar-8xwnb": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar-8xwnb",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar-8xwnb"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar-8xxdd": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar-8xxdd",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar-8xxdd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar-8xyej": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar-8xyej",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar-8xyej"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar-8xzfl": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar-8xzfl",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar-8xzfl"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar-8y001": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar-8y001",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar-8y001"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar-8y3bf": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar-8y3bf",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar-8y3bf"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar1": {
      "abstract": [
        {
          "text": "A vector of one 8-bit unsigned integer element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uchar1"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uchar1"
        }
      ],
      "role": "symbol",
      "title": "simd_uchar1",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar16": {
      "abstract": [
        {
          "text": "A vector of sixteen 8-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uchar16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uchar16"
        }
      ],
      "role": "symbol",
      "title": "simd_uchar16",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar16"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar2": {
      "abstract": [
        {
          "text": "A vector of two 8-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uchar2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uchar2"
        }
      ],
      "role": "symbol",
      "title": "simd_uchar2",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar3": {
      "abstract": [
        {
          "text": "A vector of three 8-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uchar3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uchar3"
        }
      ],
      "role": "symbol",
      "title": "simd_uchar3",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar32": {
      "abstract": [
        {
          "text": "A vector of thirty-two 8-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uchar32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uchar32"
        }
      ],
      "role": "symbol",
      "title": "simd_uchar32",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar32"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar4": {
      "abstract": [
        {
          "text": "A vector of four 8-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uchar4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uchar4"
        }
      ],
      "role": "symbol",
      "title": "simd_uchar4",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar64": {
      "abstract": [
        {
          "text": "A vector of sixty-four 8-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uchar64"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar64",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uchar64"
        }
      ],
      "role": "symbol",
      "title": "simd_uchar64",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar64"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar8": {
      "abstract": [
        {
          "text": "A vector of eight 8-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uchar8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uchar8"
        }
      ],
      "role": "symbol",
      "title": "simd_uchar8",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1x225": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1x225",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar_sat-1x225"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1x3m3": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1x3m3",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar_sat-1x3m3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1x3x1": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1x3x1",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar_sat-1x3x1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1x905": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1x905",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar_sat-1x905"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1xc6l": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1xc6l",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar_sat-1xc6l"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1xdor": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1xdor",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar_sat-1xdor"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1xdsl": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1xdsl",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar_sat-1xdsl"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1xfdz": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1xfdz",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar_sat-1xfdz"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1xfyj": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1xfyj",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar_sat-1xfyj"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1xis5": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1xis5",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar_sat-1xis5"
    },
    "doc://com.apple.accelerate/documentation/simd/vector3-9kx6s": {
      "abstract": [
        {
          "text": "Returns a new vector from a vector and a scalar value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector3-9kx6s",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector3",
      "type": "topic",
      "url": "/documentation/simd/vector3-9kx6s"
    },
    "doc://com.apple.accelerate/documentation/simd/vector3-9qwfg": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified scalar values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector3-9qwfg",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector3",
      "type": "topic",
      "url": "/documentation/simd/vector3-9qwfg"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_uchar3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vector_uchar3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_uchar3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vector_uchar3"
        }
      ],
      "role": "symbol",
      "title": "vector_uchar3",
      "type": "topic",
      "url": "/documentation/simd/vector_uchar3"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s5SIMD3V": {
      "abstract": [
        {
          "text": "A vector of three scalar values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SIMD3"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SIMDScalarP",
          "text": "SIMDScalar"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5SIMD3V",
      "kind": "symbol",
      "role": "symbol",
      "title": "SIMD3",
      "type": "topic",
      "url": "/documentation/Swift/SIMD3"
    },
    "doc://com.externally.resolved.symbol/s:s5UInt8V": {
      "abstract": [
        {
          "text": "An 8-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5UInt8V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt8",
      "type": "topic",
      "url": "/documentation/Swift/UInt8"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Vector-Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_uchar1",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar2",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar4",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar8",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar16",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar32",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar64"
      ],
      "title": "Vector Data Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Functions-to-Create-Three-Element-Vectors-From-Other-Vectors",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-4qkxz",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-4nmxq",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-45nsd",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-3sucp",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-90ge7",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-38lno",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-3p7i8",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3_undef(_:)-99t25"
      ],
      "title": "Functions to Create Three-Element Vectors From Other Vectors"
    },
    {
      "anchor": "Functions-to-Create-Three-Element-Vectors-From-Scalar-Values",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-bybh",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:_:_:)",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3_undef(_:)-562ub"
      ],
      "title": "Functions to Create Three-Element Vectors From Scalar Values"
    },
    {
      "anchor": "Functions-to-Create-Three-Element-Vectors-From-Combinations-of-Vectors-and-Scalar-Values",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:_:)-5tgih",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:_:)-2m5x7"
      ],
      "title": "Functions to Create Three-Element Vectors From Combinations of Vectors and Scalar Values"
    },
    {
      "anchor": "Common-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-6h8i3",
        "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-8iga0"
      ],
      "title": "Common Functions"
    },
    {
      "anchor": "Reduce-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-46bd5",
        "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-4gzsh",
        "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-2v6nn"
      ],
      "title": "Reduce Functions"
    },
    {
      "anchor": "Extrema-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-8h62y",
        "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-8ylny"
      ],
      "title": "Extrema Functions"
    },
    {
      "anchor": "Logic-and-Bitwise-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-69k4o",
        "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1aceu",
        "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-2syfj"
      ],
      "title": "Logic and Bitwise Functions"
    },
    {
      "anchor": "Alternative-Type-Alias",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/vector_uchar3"
      ],
      "title": "Alternative Type Alias"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "simd_uchar3"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/simd"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Functions-to-Create-Three-Element-Vectors-From-Other-Vectors",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-4qkxz",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-4nmxq",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-45nsd",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-3sucp",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-90ge7",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-38lno",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-3p7i8",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3_undef(_:)-99t25"
              ],
              "title": "Functions to Create Three-Element Vectors From Other Vectors"
            },
            {
              "anchor": "Functions-to-Create-Three-Element-Vectors-From-Scalar-Values",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:)-bybh",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:_:_:)",
                "doc://com.apple.accelerate/documentation/simd/vector3-9qwfg",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3_undef(_:)-562ub"
              ],
              "title": "Functions to Create Three-Element Vectors From Scalar Values"
            },
            {
              "anchor": "Functions-to-Create-Three-Element-Vectors-From-Combinations-of-Vectors-and-Scalar-Values",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:_:)-5tgih",
                "doc://com.apple.accelerate/documentation/simd/vector3-9kx6s",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uchar3(_:_:)-2m5x7"
              ],
              "title": "Functions to Create Three-Element Vectors From Combinations of Vectors and Scalar Values"
            },
            {
              "anchor": "Functions-to-Create-Three-Element-Vectors-From-Vectors-of-Other-Types",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_uchar-8xokr",
                "doc://com.apple.accelerate/documentation/simd/simd_uchar-8xyej",
                "doc://com.apple.accelerate/documentation/simd/simd_uchar-8xtjf",
                "doc://com.apple.accelerate/documentation/simd/simd_uchar-8y3bf",
                "doc://com.apple.accelerate/documentation/simd/simd_uchar-8xmh3",
                "doc://com.apple.accelerate/documentation/simd/simd_uchar-8xwnb",
                "doc://com.apple.accelerate/documentation/simd/simd_uchar-8xnn5",
                "doc://com.apple.accelerate/documentation/simd/simd_uchar-8xxdd",
                "doc://com.apple.accelerate/documentation/simd/simd_uchar-8xzfl",
                "doc://com.apple.accelerate/documentation/simd/simd_uchar-8y001"
              ],
              "title": "Functions to Create Three-Element Vectors From Vectors of Other Types"
            },
            {
              "anchor": "Functions-to-Perform-Saturating-Conversion-From-Vectors-of-Other-Types",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1x3x1",
                "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1xdsl",
                "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1x905",
                "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1xis5",
                "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1x225",
                "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1xc6l",
                "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1x3m3",
                "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1xdor",
                "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1xfdz",
                "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1xfyj"
              ],
              "title": "Functions to Perform Saturating Conversion From Vectors of Other Types"
            },
            {
              "anchor": "Common-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-6h8i3",
                "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-8iga0"
              ],
              "title": "Common Functions"
            },
            {
              "anchor": "Reduce-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-46bd5",
                "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-4gzsh",
                "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-2v6nn"
              ],
              "title": "Reduce Functions"
            },
            {
              "anchor": "Extrema-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-8h62y",
                "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-8ylny"
              ],
              "title": "Extrema Functions"
            },
            {
              "anchor": "Logic-and-Bitwise-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-69k4o",
                "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1aceu",
                "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-2syfj"
              ],
              "title": "Logic and Bitwise Functions"
            },
            {
              "anchor": "Alternative-Type-Alias",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/vector_uchar3"
              ],
              "title": "Alternative Type Alias"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Vector-Data-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_uchar1",
                "doc://com.apple.accelerate/documentation/simd/simd_uchar2",
                "doc://com.apple.accelerate/documentation/simd/simd_uchar4",
                "doc://com.apple.accelerate/documentation/simd/simd_uchar8",
                "doc://com.apple.accelerate/documentation/simd/simd_uchar16",
                "doc://com.apple.accelerate/documentation/simd/simd_uchar32",
                "doc://com.apple.accelerate/documentation/simd/simd_uchar64"
              ],
              "title": "Vector Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:]3c",
                    "text": "unsigned char __attribute__((ext_vector_type(3)))"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "simd_uchar3"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar2/title",
          "value": "simd_uchar2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_max(_:_:)-8ylny/title",
          "value": "simd_max"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_max(_:_:)-8ylny/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_max"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_add(_:)-2v6nn/title",
          "value": "simd_reduce_add"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_add(_:)-2v6nn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_add"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_min(_:)-46bd5/title",
          "value": "simd_reduce_min"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_min(_:)-46bd5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_min"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_any(_:)-69k4o/title",
          "value": "simd_any"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_any(_:)-69k4o/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_any"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar3(_:)-38lno/title",
          "value": "simd_make_uchar3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar3(_:)-38lno/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar3(_:)-45nsd/title",
          "value": "simd_make_uchar3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar3(_:)-45nsd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar32/title",
          "value": "simd_uchar32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar32/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar3(_:_:_:)/title",
          "value": "simd_make_uchar3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar3(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar64/title",
          "value": "simd_uchar64"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar64/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar64/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar3(_:)-3sucp/title",
          "value": "simd_make_uchar3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar3(_:)-3sucp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar3(_:_:)-2m5x7/title",
          "value": "simd_make_uchar3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar3(_:_:)-2m5x7/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar3_undef(_:)-562ub/title",
          "value": "simd_make_uchar3_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar3_undef(_:)-562ub/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar3_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar16/title",
          "value": "simd_uchar16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar16/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_max(_:)-4gzsh/title",
          "value": "simd_reduce_max"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_max(_:)-4gzsh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_max"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar3(_:)-90ge7/title",
          "value": "simd_make_uchar3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar3(_:)-90ge7/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1vector_uchar3/title",
          "value": "vector_uchar3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1vector_uchar3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vector_uchar3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1vector_uchar3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vector_uchar3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar8/title",
          "value": "simd_uchar8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar3(_:)-bybh/title",
          "value": "simd_make_uchar3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar3(_:)-bybh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_bitselect(_:_:_:)-2syfj/title",
          "value": "simd_bitselect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_bitselect(_:_:_:)-2syfj/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_bitselect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar3(_:_:)-5tgih/title",
          "value": "simd_make_uchar3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar3(_:_:)-5tgih/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar1/title",
          "value": "simd_uchar1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar1/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar3(_:)-3p7i8/title",
          "value": "simd_make_uchar3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar3(_:)-3p7i8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_all(_:)-1aceu/title",
          "value": "simd_all"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_all(_:)-1aceu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_all"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar3(_:)-4qkxz/title",
          "value": "simd_make_uchar3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar3(_:)-4qkxz/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar3_undef(_:)-99t25/title",
          "value": "simd_make_uchar3_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar3_undef(_:)-99t25/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar3_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_min(_:_:)-8h62y/title",
          "value": "simd_min"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_min(_:_:)-8h62y/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_min"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_equal(_:_:)-8iga0/title",
          "value": "simd_equal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_equal(_:_:)-8iga0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_equal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar4/title",
          "value": "simd_uchar4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar3/title",
          "value": "simd_uchar3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar3(_:)-4nmxq/title",
          "value": "simd_make_uchar3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uchar3(_:)-4nmxq/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uchar3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_clamp(_:_:_:)-6h8i3/title",
          "value": "simd_clamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_clamp(_:_:_:)-6h8i3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_clamp"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_uchar3"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/simd/simd_uchar3"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
