{
  "abstract": [
    {
      "text": "Returns a new vector from the specified vectors.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8(_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_make_ulong8#]4l#S0_#",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simd_make_ulong8"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_ulong4",
        "text": "simd_ulong4"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_ulong4",
        "text": "simd_ulong4"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_ulong8",
        "text": "simd_ulong8"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_make_ulong8"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_make_ulong8(_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_make_ulong8"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "lo"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong4",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_ulong4",
              "text": "simd_ulong4"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "hi"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong4",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_ulong4",
              "text": "simd_ulong4"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong8",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_ulong8",
              "text": "simd_ulong8"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8(_:)-5w0n4": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ulong8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong2",
          "text": "simd_ulong2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong8",
          "text": "simd_ulong8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8(_:)-5w0n4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ulong8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ulong8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ulong8(_:)-5w0n4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8(_:)-5zhz7": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified three-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ulong8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong3",
          "text": "simd_ulong3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong8",
          "text": "simd_ulong8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8(_:)-5zhz7",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ulong8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ulong8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ulong8(_:)-5zhz7"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8(_:)-6hggi": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified four-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ulong8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong4",
          "text": "simd_ulong4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong8",
          "text": "simd_ulong8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8(_:)-6hggi",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ulong8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ulong8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ulong8(_:)-6hggi"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8(_:)-6wa2m": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ulong8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong8",
          "text": "simd_ulong8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong8",
          "text": "simd_ulong8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8(_:)-6wa2m",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ulong8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ulong8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ulong8(_:)-6wa2m"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ulong8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong4",
          "text": "simd_ulong4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong4",
          "text": "simd_ulong4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong8",
          "text": "simd_ulong8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ulong8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ulong8(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ulong8(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8_undef(_:)-9oge2": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified three-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ulong8_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong3",
          "text": "simd_ulong3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong8",
          "text": "simd_ulong8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8_undef(_:)-9oge2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ulong8_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ulong8_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ulong8_undef(_:)-9oge2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8_undef(_:)-9rdt9": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ulong8_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong2",
          "text": "simd_ulong2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong8",
          "text": "simd_ulong8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8_undef(_:)-9rdt9",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ulong8_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ulong8_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ulong8_undef(_:)-9rdt9"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8_undef(_:)-d5pk": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified four-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ulong8_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong4",
          "text": "simd_ulong4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong8",
          "text": "simd_ulong8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8_undef(_:)-d5pk",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ulong8_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ulong8_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ulong8_undef(_:)-d5pk"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong4": {
      "abstract": [
        {
          "text": "A vector of four 64-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ulong4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ulong4"
        }
      ],
      "role": "symbol",
      "title": "simd_ulong4",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong8": {
      "abstract": [
        {
          "text": "A vector of eight 64-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ulong8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ulong8"
        }
      ],
      "role": "symbol",
      "title": "simd_ulong8",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong8"
    },
    "doc://com.apple.accelerate/documentation/simd/vector8-5kkur": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector8-5kkur",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector8",
      "type": "topic",
      "url": "/documentation/simd/vector8-5kkur"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Create-Eight-Element-Vectors-From-Other-Vectors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8(_:)-5w0n4",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8(_:)-5zhz7",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8(_:)-6hggi",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8(_:)-6wa2m",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8_undef(_:)-9rdt9",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8_undef(_:)-9oge2",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8_undef(_:)-d5pk"
      ],
      "title": "Functions to Create Eight-Element Vectors From Other Vectors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "simd_make_ulong8"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ulong8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/simd"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Functions-to-Create-Eight-Element-Vectors-From-Other-Vectors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8(_:)-5w0n4",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8(_:)-5zhz7",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8(_:)-6hggi",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8(_:)-6wa2m",
                "doc://com.apple.accelerate/documentation/simd/vector8-5kkur",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8_undef(_:)-9rdt9",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8_undef(_:)-9oge2",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8_undef(_:)-d5pk"
              ],
              "title": "Functions to Create Eight-Element Vectors From Other Vectors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "static"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong8",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_ulong8",
                    "text": "simd_ulong8"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "simd_make_ulong8"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong4",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_ulong4",
                    "text": "simd_ulong4"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "lo"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong4",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_ulong4",
                    "text": "simd_ulong4"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "hi"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong8(_:)-5zhz7/title",
          "value": "simd_make_ulong8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong8(_:)-5zhz7/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ulong8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong8_undef(_:)-9oge2/title",
          "value": "simd_make_ulong8_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong8_undef(_:)-9oge2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ulong8_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong8(_:_:)/title",
          "value": "simd_make_ulong8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong8(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ulong8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong4/title",
          "value": "simd_ulong4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong8(_:)-6hggi/title",
          "value": "simd_make_ulong8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong8(_:)-6hggi/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ulong8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong8_undef(_:)-d5pk/title",
          "value": "simd_make_ulong8_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong8_undef(_:)-d5pk/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ulong8_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong8(_:)-5w0n4/title",
          "value": "simd_make_ulong8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong8(_:)-5w0n4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ulong8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong8/title",
          "value": "simd_ulong8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong8(_:)-6wa2m/title",
          "value": "simd_make_ulong8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong8(_:)-6wa2m/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ulong8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong8_undef(_:)-9rdt9/title",
          "value": "simd_make_ulong8_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong8_undef(_:)-9rdt9/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ulong8_undef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_make_ulong8(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/simd/simd_make_ulong8(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
