{
  "abstract": [
    {
      "text": "Returns the sum of two matrices.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_add-53ag9"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_add#$@SA@simd_double3x4#S0_#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_add"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_add"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_add"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double3x4",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@simd_double3x4",
              "text": "simd_double3x4"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_add"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double3x4",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@simd_double3x4",
              "text": "simd_double3x4"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double3x4",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@simd_double3x4",
              "text": "simd_double3x4"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__y"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_scale-5ie6g": {
      "abstract": [
        {
          "text": "Returns the product of a scalar value and a matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "matrix_scale"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_scale-5ie6g",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_scale",
      "type": "topic",
      "url": "/documentation/simd/matrix_scale-5ie6g"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_add-53ag9": {
      "abstract": [
        {
          "text": "Returns the sum of two matrices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_add"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_add-53ag9",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_add",
      "type": "topic",
      "url": "/documentation/simd/simd_add-53ag9"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double3x4": {
      "abstract": [
        {
          "text": "A matrix of three columns and four rows that contains double-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_double3x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double3x4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_double3x4"
        }
      ],
      "role": "symbol",
      "title": "simd_double3x4",
      "type": "topic",
      "url": "/documentation/simd/simd_double3x4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_sub-6yn8w": {
      "abstract": [
        {
          "text": "Returns the difference of two matrices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_sub"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_sub-6yn8w",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_sub",
      "type": "topic",
      "url": "/documentation/simd/simd_sub-6yn8w"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Math-Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_sub-6yn8w",
        "doc://com.apple.accelerate/documentation/simd/matrix_scale-5ie6g"
      ],
      "title": "Math Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double3x4/title",
          "value": "simd_double3x4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double3x4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double3x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double3x4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double3x4"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_add-53ag9"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
