{
  "abstract": [
    {
      "text": "Returns the precise distance between two vectors.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_precise_distance-5ci0y"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_precise_distance#]16f#S0_#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_precise_distance"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_precise_distance"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_precise_distance"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:f",
              "text": "float"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_precise_distance"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float16",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_float16",
              "text": "simd_float16"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float16",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_float16",
              "text": "simd_float16"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__y"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_distance-7xk9e": {
      "abstract": [
        {
          "text": "Returns the distance between two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_distance"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_distance-7xk9e",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_distance",
      "type": "topic",
      "url": "/documentation/simd/simd_distance-7xk9e"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_distance_squared-57ui2": {
      "abstract": [
        {
          "text": "Returns the square of the distance between two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_distance_squared"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_distance_squared-57ui2",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_distance_squared",
      "type": "topic",
      "url": "/documentation/simd/simd_distance_squared-57ui2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_fast_distance-56een": {
      "abstract": [
        {
          "text": "Returns the fast distance between two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_fast_distance"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_fast_distance-56een",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_fast_distance",
      "type": "topic",
      "url": "/documentation/simd/simd_fast_distance-56een"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_fast_length-3edeo": {
      "abstract": [
        {
          "text": "Returns the fast length of a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_fast_length"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_fast_length-3edeo",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_fast_length",
      "type": "topic",
      "url": "/documentation/simd/simd_fast_length-3edeo"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float16": {
      "abstract": [
        {
          "text": "A vector of sixteen 32-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_float16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_float16"
        }
      ],
      "role": "symbol",
      "title": "simd_float16",
      "type": "topic",
      "url": "/documentation/simd/simd_float16"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_length-575we": {
      "abstract": [
        {
          "text": "Returns the length of a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_length"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_length-575we",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_length",
      "type": "topic",
      "url": "/documentation/simd/simd_length-575we"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_length_squared-7moqe": {
      "abstract": [
        {
          "text": "Returns the square of the length of a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_length_squared"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_length_squared-7moqe",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_length_squared",
      "type": "topic",
      "url": "/documentation/simd/simd_length_squared-7moqe"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_precise_distance-5ci0y": {
      "abstract": [
        {
          "text": "Returns the precise distance between two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_precise_distance"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_precise_distance-5ci0y",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_precise_distance",
      "type": "topic",
      "url": "/documentation/simd/simd_precise_distance-5ci0y"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_precise_length-bswz": {
      "abstract": [
        {
          "text": "Returns the precise length of a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_precise_length"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_precise_length-bswz",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_precise_length",
      "type": "topic",
      "url": "/documentation/simd/simd_precise_length-bswz"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Length-and-Distance-Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_length-575we",
        "doc://com.apple.accelerate/documentation/simd/simd_fast_length-3edeo",
        "doc://com.apple.accelerate/documentation/simd/simd_precise_length-bswz",
        "doc://com.apple.accelerate/documentation/simd/simd_length_squared-7moqe",
        "doc://com.apple.accelerate/documentation/simd/simd_distance-7xk9e",
        "doc://com.apple.accelerate/documentation/simd/simd_fast_distance-56een",
        "doc://com.apple.accelerate/documentation/simd/simd_distance_squared-57ui2"
      ],
      "title": "Length and Distance Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float16/title",
          "value": "simd_float16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float16/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float16"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_precise_distance-5ci0y"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
