{
  "abstract": [
    {
      "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5lk6u"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_long_sat#]4i#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_long_sat"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_long_sat"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_long_sat"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long4",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_long4",
              "text": "simd_long4"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_long_sat"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint4",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_uint4",
              "text": "simd_uint4"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long4": {
      "abstract": [
        {
          "text": "A vector of four 64-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_long4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_long4"
        }
      ],
      "role": "symbol",
      "title": "simd_long4",
      "type": "topic",
      "url": "/documentation/simd/simd_long4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5la9i": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5la9i",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_long_sat-5la9i"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5lbza": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5lbza",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_long_sat-5lbza"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5ldhe": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5ldhe",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_long_sat-5ldhe"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5lihu": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5lihu",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_long_sat-5lihu"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5lk6u": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5lk6u",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_long_sat-5lk6u"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5llpi": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5llpi",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_long_sat-5llpi"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5ln9e": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5ln9e",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_long_sat-5ln9e"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5lody": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5lody",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_long_sat-5lody"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5loyi": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5loyi",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_long_sat-5loyi"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5ls82": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5ls82",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_long_sat-5ls82"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint4": {
      "abstract": [
        {
          "text": "A vector of four 32-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uint4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uint4"
        }
      ],
      "role": "symbol",
      "title": "simd_uint4",
      "type": "topic",
      "url": "/documentation/simd/simd_uint4"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Perform-Saturating-Conversion-From-Vectors-of-Other-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5ldhe",
        "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5ln9e",
        "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5lihu",
        "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5ls82",
        "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5la9i",
        "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5lbza",
        "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5llpi",
        "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5loyi",
        "doc://com.apple.accelerate/documentation/simd/simd_long_sat-5lody"
      ],
      "title": "Functions to Perform Saturating Conversion From Vectors of Other Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long4/title",
          "value": "simd_long4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_long4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_long4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint4/title",
          "value": "simd_uint4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uint4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uint4"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_long_sat-5lk6u"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
