{
  "abstract": [
    {
      "text": "Returns a new vector from the specified vector of 8-bit, unsigned-integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_float-148tt"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_float#]2c#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_float"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_float"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_float"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_float2",
              "text": "simd_float2"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_float"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_uchar2",
              "text": "simd_uchar2"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float-148tt": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float-148tt",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_float",
      "type": "topic",
      "url": "/documentation/simd/simd_float-148tt"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float-149uz": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float-149uz",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_float",
      "type": "topic",
      "url": "/documentation/simd/simd_float-149uz"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float-14afr": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float-14afr",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_float",
      "type": "topic",
      "url": "/documentation/simd/simd_float-14afr"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float-14c1l": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float-14c1l",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_float",
      "type": "topic",
      "url": "/documentation/simd/simd_float-14c1l"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float-14cvb": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float-14cvb",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_float",
      "type": "topic",
      "url": "/documentation/simd/simd_float-14cvb"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float-14dwx": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float-14dwx",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_float",
      "type": "topic",
      "url": "/documentation/simd/simd_float-14dwx"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float-14iup": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float-14iup",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_float",
      "type": "topic",
      "url": "/documentation/simd/simd_float-14iup"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float-14lvd": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float-14lvd",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_float",
      "type": "topic",
      "url": "/documentation/simd/simd_float-14lvd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float-14mw7": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float-14mw7",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_float",
      "type": "topic",
      "url": "/documentation/simd/simd_float-14mw7"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float-14nqp": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float-14nqp",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_float",
      "type": "topic",
      "url": "/documentation/simd/simd_float-14nqp"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float2": {
      "abstract": [
        {
          "text": "A vector of two 32-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_float2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_float2"
        }
      ],
      "role": "symbol",
      "title": "simd_float2",
      "type": "topic",
      "url": "/documentation/simd/simd_float2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar2": {
      "abstract": [
        {
          "text": "A vector of two 8-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uchar2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uchar2"
        }
      ],
      "role": "symbol",
      "title": "simd_uchar2",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar2"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Create-Two-Element-Vectors-From-Vectors-of-Other-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_float-14iup",
        "doc://com.apple.accelerate/documentation/simd/simd_float-14nqp",
        "doc://com.apple.accelerate/documentation/simd/simd_float-14dwx",
        "doc://com.apple.accelerate/documentation/simd/simd_float-14lvd",
        "doc://com.apple.accelerate/documentation/simd/simd_float-14c1l",
        "doc://com.apple.accelerate/documentation/simd/simd_float-14mw7",
        "doc://com.apple.accelerate/documentation/simd/simd_float-14cvb",
        "doc://com.apple.accelerate/documentation/simd/simd_float-149uz",
        "doc://com.apple.accelerate/documentation/simd/simd_float-14afr"
      ],
      "title": "Functions to Create Two-Element Vectors From Vectors of Other Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float2/title",
          "value": "simd_float2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar2/title",
          "value": "simd_uchar2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar2"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_float-148tt"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
