{
  "abstract": [
    {
      "text": "Returns a new vector from the specified three-element vector, and other elements undefined.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_make_char4_undef(_:)-73111"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_make_char4_undef#]3C#",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simd_make_char4_undef"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_char3",
        "text": "simd_char3"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_char4",
        "text": "simd_char4"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_make_char4_undef"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_make_char4_undef(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_make_char4_undef"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "other"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char3",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_char3",
              "text": "simd_char3"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char4",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_char4",
              "text": "simd_char4"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char3": {
      "abstract": [
        {
          "text": "A vector of three 8-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_char3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_char3"
        }
      ],
      "role": "symbol",
      "title": "simd_char3",
      "type": "topic",
      "url": "/documentation/simd/simd_char3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char4": {
      "abstract": [
        {
          "text": "A vector of four 8-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_char4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_char4"
        }
      ],
      "role": "symbol",
      "title": "simd_char4",
      "type": "topic",
      "url": "/documentation/simd/simd_char4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_char4(_:)-1mbtb": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified eight-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_char4"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char8",
          "text": "simd_char8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char4",
          "text": "simd_char4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_char4(_:)-1mbtb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_char4"
        }
      ],
      "role": "symbol",
      "title": "simd_make_char4(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_char4(_:)-1mbtb"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_char4(_:)-3tnz9": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified thirty two-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_char4"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char32",
          "text": "simd_char32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char4",
          "text": "simd_char4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_char4(_:)-3tnz9",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_char4"
        }
      ],
      "role": "symbol",
      "title": "simd_make_char4(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_char4(_:)-3tnz9"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_char4(_:)-4y0kh": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified sixteen-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_char4"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char16",
          "text": "simd_char16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char4",
          "text": "simd_char4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_char4(_:)-4y0kh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_char4"
        }
      ],
      "role": "symbol",
      "title": "simd_make_char4(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_char4(_:)-4y0kh"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_char4(_:)-69u9q": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified sixty four-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_char4"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char64",
          "text": "simd_char64"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char4",
          "text": "simd_char4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_char4(_:)-69u9q",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_char4"
        }
      ],
      "role": "symbol",
      "title": "simd_make_char4(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_char4(_:)-69u9q"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_char4(_:)-gjz7": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_char4"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char4",
          "text": "simd_char4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char4",
          "text": "simd_char4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_char4(_:)-gjz7",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_char4"
        }
      ],
      "role": "symbol",
      "title": "simd_make_char4(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_char4(_:)-gjz7"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_char4(_:)-k1u0": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified three-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_char4"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char3",
          "text": "simd_char3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char4",
          "text": "simd_char4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_char4(_:)-k1u0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_char4"
        }
      ],
      "role": "symbol",
      "title": "simd_make_char4(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_char4(_:)-k1u0"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_char4(_:)-mdlt": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_char4"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char2",
          "text": "simd_char2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char4",
          "text": "simd_char4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_char4(_:)-mdlt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_char4"
        }
      ],
      "role": "symbol",
      "title": "simd_make_char4(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_char4(_:)-mdlt"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_char4(_:_:)-3vf4l": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_char4"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char2",
          "text": "simd_char2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char2",
          "text": "simd_char2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char4",
          "text": "simd_char4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_char4(_:_:)-3vf4l",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_char4"
        }
      ],
      "role": "symbol",
      "title": "simd_make_char4(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_char4(_:_:)-3vf4l"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_char4_undef(_:)-6zlek": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_char4_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char2",
          "text": "simd_char2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char4",
          "text": "simd_char4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_char4_undef(_:)-6zlek",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_char4_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_char4_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_char4_undef(_:)-6zlek"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_char4_undef(_:)-73111": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified three-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_char4_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char3",
          "text": "simd_char3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char4",
          "text": "simd_char4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_char4_undef(_:)-73111",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_char4_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_char4_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_char4_undef(_:)-73111"
    },
    "doc://com.apple.accelerate/documentation/simd/vector4-695o8": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector4-695o8",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector4",
      "type": "topic",
      "url": "/documentation/simd/vector4-695o8"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Create-Four-Element-Vectors-From-Other-Vectors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_char4(_:)-mdlt",
        "doc://com.apple.accelerate/documentation/simd/simd_make_char4(_:)-k1u0",
        "doc://com.apple.accelerate/documentation/simd/simd_make_char4(_:)-gjz7",
        "doc://com.apple.accelerate/documentation/simd/simd_make_char4(_:)-1mbtb",
        "doc://com.apple.accelerate/documentation/simd/simd_make_char4(_:)-4y0kh",
        "doc://com.apple.accelerate/documentation/simd/simd_make_char4(_:)-3tnz9",
        "doc://com.apple.accelerate/documentation/simd/simd_make_char4(_:)-69u9q",
        "doc://com.apple.accelerate/documentation/simd/simd_make_char4(_:_:)-3vf4l",
        "doc://com.apple.accelerate/documentation/simd/simd_make_char4_undef(_:)-6zlek"
      ],
      "title": "Functions to Create Four-Element Vectors From Other Vectors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "simd_make_char4_undef"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_char4_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/simd"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Functions-to-Create-Four-Element-Vectors-From-Other-Vectors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_char4(_:)-mdlt",
                "doc://com.apple.accelerate/documentation/simd/simd_make_char4(_:)-k1u0",
                "doc://com.apple.accelerate/documentation/simd/simd_make_char4(_:)-gjz7",
                "doc://com.apple.accelerate/documentation/simd/simd_make_char4(_:)-1mbtb",
                "doc://com.apple.accelerate/documentation/simd/simd_make_char4(_:)-4y0kh",
                "doc://com.apple.accelerate/documentation/simd/simd_make_char4(_:)-3tnz9",
                "doc://com.apple.accelerate/documentation/simd/simd_make_char4(_:)-69u9q",
                "doc://com.apple.accelerate/documentation/simd/simd_make_char4(_:_:)-3vf4l",
                "doc://com.apple.accelerate/documentation/simd/vector4-695o8",
                "doc://com.apple.accelerate/documentation/simd/simd_make_char4_undef(_:)-6zlek"
              ],
              "title": "Functions to Create Four-Element Vectors From Other Vectors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "static"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char4",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_char4",
                    "text": "simd_char4"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "simd_make_char4_undef"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char3",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_char3",
                    "text": "simd_char3"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "other"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char4_undef(_:)-73111/title",
          "value": "simd_make_char4_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char4_undef(_:)-73111/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_char4_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char4(_:)-k1u0/title",
          "value": "simd_make_char4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char4(_:)-k1u0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_char4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char4(_:)-mdlt/title",
          "value": "simd_make_char4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char4(_:)-mdlt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_char4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char4(_:)-3tnz9/title",
          "value": "simd_make_char4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char4(_:)-3tnz9/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_char4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char4(_:)-4y0kh/title",
          "value": "simd_make_char4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char4(_:)-4y0kh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_char4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char4(_:)-gjz7/title",
          "value": "simd_make_char4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char4(_:)-gjz7/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_char4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char3/title",
          "value": "simd_char3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char4(_:)-1mbtb/title",
          "value": "simd_make_char4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char4(_:)-1mbtb/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_char4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char4(_:_:)-3vf4l/title",
          "value": "simd_make_char4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char4(_:_:)-3vf4l/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_char4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char4_undef(_:)-6zlek/title",
          "value": "simd_make_char4_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char4_undef(_:)-6zlek/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_char4_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char4/title",
          "value": "simd_char4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char4(_:)-69u9q/title",
          "value": "simd_make_char4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char4(_:)-69u9q/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_char4"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_make_char4_undef(_:)-73111"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/simd/simd_make_char4_undef(_:)-73111"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
