{
  "abstract": [
    {
      "text": "Returns a new vector from the specified vector of 64-bit, signed-integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_float-jr19"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_float#]4L#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_float"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_float"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_float"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float4",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_float4",
              "text": "simd_float4"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_float"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long4",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_long4",
              "text": "simd_long4"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float-j957": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float-j957",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_float",
      "type": "topic",
      "url": "/documentation/simd/simd_float-j957"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float-je97": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float-je97",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_float",
      "type": "topic",
      "url": "/documentation/simd/simd_float-je97"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float-jekd": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float-jekd",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_float",
      "type": "topic",
      "url": "/documentation/simd/simd_float-jekd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float-jf39": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float-jf39",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_float",
      "type": "topic",
      "url": "/documentation/simd/simd_float-jf39"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float-jg4f": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float-jg4f",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_float",
      "type": "topic",
      "url": "/documentation/simd/simd_float-jg4f"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float-jgyl": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float-jgyl",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_float",
      "type": "topic",
      "url": "/documentation/simd/simd_float-jgyl"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float-jj4b": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float-jj4b",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_float",
      "type": "topic",
      "url": "/documentation/simd/simd_float-jj4b"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float-joa3": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float-joa3",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_float",
      "type": "topic",
      "url": "/documentation/simd/simd_float-joa3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float-jq3j": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float-jq3j",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_float",
      "type": "topic",
      "url": "/documentation/simd/simd_float-jq3j"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float-jr19": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float-jr19",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_float",
      "type": "topic",
      "url": "/documentation/simd/simd_float-jr19"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float4": {
      "abstract": [
        {
          "text": "A vector of four 32-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_float4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_float4"
        }
      ],
      "role": "symbol",
      "title": "simd_float4",
      "type": "topic",
      "url": "/documentation/simd/simd_float4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long4": {
      "abstract": [
        {
          "text": "A vector of four 64-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_long4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_long4"
        }
      ],
      "role": "symbol",
      "title": "simd_long4",
      "type": "topic",
      "url": "/documentation/simd/simd_long4"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Create-Four-Element-Vectors-From-Vectors-of-Other-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_float-joa3",
        "doc://com.apple.accelerate/documentation/simd/simd_float-je97",
        "doc://com.apple.accelerate/documentation/simd/simd_float-jj4b",
        "doc://com.apple.accelerate/documentation/simd/simd_float-j957",
        "doc://com.apple.accelerate/documentation/simd/simd_float-jq3j",
        "doc://com.apple.accelerate/documentation/simd/simd_float-jg4f",
        "doc://com.apple.accelerate/documentation/simd/simd_float-jgyl",
        "doc://com.apple.accelerate/documentation/simd/simd_float-jf39",
        "doc://com.apple.accelerate/documentation/simd/simd_float-jekd"
      ],
      "title": "Functions to Create Four-Element Vectors From Vectors of Other Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float4/title",
          "value": "simd_float4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long4/title",
          "value": "simd_long4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_long4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_long4"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_float-jr19"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
