{
  "abstract": [
    {
      "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_long-a7cr"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_long#]4l#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_long"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_long"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_long"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long4",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_long4",
              "text": "simd_long4"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_long"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong4",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_ulong4",
              "text": "simd_ulong4"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long-9x5l": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long-9x5l",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long",
      "type": "topic",
      "url": "/documentation/simd/simd_long-9x5l"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long-9xiz": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long-9xiz",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long",
      "type": "topic",
      "url": "/documentation/simd/simd_long-9xiz"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long-9yxd": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long-9yxd",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long",
      "type": "topic",
      "url": "/documentation/simd/simd_long-9yxd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long-a255": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long-a255",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long",
      "type": "topic",
      "url": "/documentation/simd/simd_long-a255"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long-a4uz": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long-a4uz",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long",
      "type": "topic",
      "url": "/documentation/simd/simd_long-a4uz"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long-a5mn": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long-a5mn",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long",
      "type": "topic",
      "url": "/documentation/simd/simd_long-a5mn"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long-a715": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long-a715",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long",
      "type": "topic",
      "url": "/documentation/simd/simd_long-a715"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long-a7cr": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long-a7cr",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long",
      "type": "topic",
      "url": "/documentation/simd/simd_long-a7cr"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long-a8wh": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long-a8wh",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long",
      "type": "topic",
      "url": "/documentation/simd/simd_long-a8wh"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long-ac49": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long-ac49",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long",
      "type": "topic",
      "url": "/documentation/simd/simd_long-ac49"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long4": {
      "abstract": [
        {
          "text": "A vector of four 64-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_long4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_long4"
        }
      ],
      "role": "symbol",
      "title": "simd_long4",
      "type": "topic",
      "url": "/documentation/simd/simd_long4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong4": {
      "abstract": [
        {
          "text": "A vector of four 64-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ulong4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ulong4"
        }
      ],
      "role": "symbol",
      "title": "simd_ulong4",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong4"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Create-Four-Element-Vectors-From-Vectors-of-Other-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_long-9x5l",
        "doc://com.apple.accelerate/documentation/simd/simd_long-a715",
        "doc://com.apple.accelerate/documentation/simd/simd_long-a255",
        "doc://com.apple.accelerate/documentation/simd/simd_long-ac49",
        "doc://com.apple.accelerate/documentation/simd/simd_long-9yxd",
        "doc://com.apple.accelerate/documentation/simd/simd_long-a8wh",
        "doc://com.apple.accelerate/documentation/simd/simd_long-9xiz",
        "doc://com.apple.accelerate/documentation/simd/simd_long-a5mn",
        "doc://com.apple.accelerate/documentation/simd/simd_long-a4uz"
      ],
      "title": "Functions to Create Four-Element Vectors From Vectors of Other Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long4/title",
          "value": "simd_long4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_long4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_long4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong4/title",
          "value": "simd_ulong4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong4"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_long-a7cr"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
