{
  "abstract": [
    {
      "text": "A vector of eight 32-bit unsigned integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_uint8"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@simd_uint8",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simd_uint8"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_uint8"
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "simd_uint8"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_uint8"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5SIMD8V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5SIMD8V",
              "text": "SIMD8"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt32V",
              "text": "UInt32"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1ynbd": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_all"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint8",
          "text": "simd_uint8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_bool",
          "text": "simd_bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1ynbd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_all"
        }
      ],
      "role": "symbol",
      "title": "simd_all(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_all(_:)-1ynbd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-6p8mz": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_any"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint8",
          "text": "simd_uint8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_bool",
          "text": "simd_bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-6p8mz",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_any"
        }
      ],
      "role": "symbol",
      "title": "simd_any(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_any(_:)-6p8mz"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-803fj": {
      "abstract": [
        {
          "text": "Returns a vector that contains elements from either the first or second parameter, based on the corresponding element in the third parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_bitselect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint8",
          "text": "simd_uint8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint8",
          "text": "simd_uint8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_int8",
          "text": "simd_int8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint8",
          "text": "simd_uint8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-803fj",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_bitselect"
        }
      ],
      "role": "symbol",
      "title": "simd_bitselect(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_bitselect(_:_:_:)-803fj"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-9evfi": {
      "abstract": [
        {
          "text": "Returns each element in a vector clamped to a specified range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_clamp"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint8",
          "text": "simd_uint8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint8",
          "text": "simd_uint8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint8",
          "text": "simd_uint8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint8",
          "text": "simd_uint8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-9evfi",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_clamp"
        }
      ],
      "role": "symbol",
      "title": "simd_clamp(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_clamp(_:_:_:)-9evfi"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-1v1wn": {
      "abstract": [
        {
          "text": "Returns true if every element in a vector is exactly equal to the corresponding element in a second vector, and otherwise returns false.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_equal"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint8",
          "text": "simd_uint8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint8",
          "text": "simd_uint8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_bool",
          "text": "simd_bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-1v1wn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_equal"
        }
      ],
      "role": "symbol",
      "title": "simd_equal(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_equal(_:_:)-1v1wn"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uint8(_:)-2ovzr": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified four-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uint8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint4",
          "text": "simd_uint4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint8",
          "text": "simd_uint8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uint8(_:)-2ovzr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uint8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uint8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uint8(_:)-2ovzr"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uint8(_:)-2rtxs": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified three-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uint8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint3",
          "text": "simd_uint3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint8",
          "text": "simd_uint8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uint8(_:)-2rtxs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uint8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uint8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uint8(_:)-2rtxs"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uint8(_:)-2vaoh": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uint8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint2",
          "text": "simd_uint2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint8",
          "text": "simd_uint8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uint8(_:)-2vaoh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uint8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uint8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uint8(_:)-2vaoh"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uint8(_:)-3sztf": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uint8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint8",
          "text": "simd_uint8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint8",
          "text": "simd_uint8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uint8(_:)-3sztf",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uint8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uint8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uint8(_:)-3sztf"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uint8(_:)-64gkj": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified sixteen-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uint8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint16",
          "text": "simd_uint16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint8",
          "text": "simd_uint8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uint8(_:)-64gkj",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uint8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uint8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uint8(_:)-64gkj"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uint8(_:)-7jqj3": {
      "abstract": [
        {
          "text": "Returns a new vector with the first element set to a scalar value, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uint8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint8",
          "text": "simd_uint8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uint8(_:)-7jqj3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uint8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uint8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uint8(_:)-7jqj3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uint8(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uint8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint4",
          "text": "simd_uint4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint4",
          "text": "simd_uint4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint8",
          "text": "simd_uint8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uint8(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uint8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uint8(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uint8(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uint8_undef(_:)-6a8k": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified four-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uint8_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint4",
          "text": "simd_uint4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint8",
          "text": "simd_uint8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uint8_undef(_:)-6a8k",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uint8_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uint8_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uint8_undef(_:)-6a8k"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uint8_undef(_:)-8p5i8": {
      "abstract": [
        {
          "text": "Returns a new vector with the first element set to a scalar value, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uint8_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint8",
          "text": "simd_uint8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uint8_undef(_:)-8p5i8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uint8_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uint8_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uint8_undef(_:)-8p5i8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uint8_undef(_:)-ck1m": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uint8_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint2",
          "text": "simd_uint2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint8",
          "text": "simd_uint8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uint8_undef(_:)-ck1m",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uint8_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uint8_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uint8_undef(_:)-ck1m"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_uint8_undef(_:)-hojv": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified three-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_uint8_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint3",
          "text": "simd_uint3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint8",
          "text": "simd_uint8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_uint8_undef(_:)-hojv",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_uint8_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_uint8_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_uint8_undef(_:)-hojv"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-4l2k6": {
      "abstract": [
        {
          "text": "Returns the maximum value of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_max"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint8",
          "text": "simd_uint8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint8",
          "text": "simd_uint8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint8",
          "text": "simd_uint8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-4l2k6",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_max"
        }
      ],
      "role": "symbol",
      "title": "simd_max(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_max(_:_:)-4l2k6"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-873mx": {
      "abstract": [
        {
          "text": "Returns the minimum value of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_min"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint8",
          "text": "simd_uint8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint8",
          "text": "simd_uint8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint8",
          "text": "simd_uint8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-873mx",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_min"
        }
      ],
      "role": "symbol",
      "title": "simd_min(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_min(_:_:)-873mx"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-3av90": {
      "abstract": [
        {
          "text": "Returns the sum of all elements in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_add"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint8",
          "text": "simd_uint8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-3av90",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_add"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_add(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_add(_:)-3av90"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-55ah6": {
      "abstract": [
        {
          "text": "Returns the maximum value in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_max"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint8",
          "text": "simd_uint8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-55ah6",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_max"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_max(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_max(_:)-55ah6"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-3o9f6": {
      "abstract": [
        {
          "text": "Returns the miniumum value in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_min"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_uint8",
          "text": "simd_uint8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-3o9f6",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_min"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_min(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_min(_:)-3o9f6"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint-8ddf0": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uint"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint-8ddf0",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uint",
      "type": "topic",
      "url": "/documentation/simd/simd_uint-8ddf0"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint-8dgmc": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uint"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint-8dgmc",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uint",
      "type": "topic",
      "url": "/documentation/simd/simd_uint-8dgmc"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint-8dhgw": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uint"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint-8dhgw",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uint",
      "type": "topic",
      "url": "/documentation/simd/simd_uint-8dhgw"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint-8dih8": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uint"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint-8dih8",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uint",
      "type": "topic",
      "url": "/documentation/simd/simd_uint-8dih8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint-8dncc": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uint"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint-8dncc",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uint",
      "type": "topic",
      "url": "/documentation/simd/simd_uint-8dncc"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint-8dqg4": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uint"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint-8dqg4",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uint",
      "type": "topic",
      "url": "/documentation/simd/simd_uint-8dqg4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint-8drlc": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uint"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint-8drlc",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uint",
      "type": "topic",
      "url": "/documentation/simd/simd_uint-8drlc"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint-8ds98": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uint"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint-8ds98",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uint",
      "type": "topic",
      "url": "/documentation/simd/simd_uint-8ds98"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint-8dt6o": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uint"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint-8dt6o",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uint",
      "type": "topic",
      "url": "/documentation/simd/simd_uint-8dt6o"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint-8dtuo": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uint"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint-8dtuo",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uint",
      "type": "topic",
      "url": "/documentation/simd/simd_uint-8dtuo"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint1": {
      "abstract": [
        {
          "text": "A vector of one 32-bit unsigned integer element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uint1"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uint1"
        }
      ],
      "role": "symbol",
      "title": "simd_uint1",
      "type": "topic",
      "url": "/documentation/simd/simd_uint1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint16": {
      "abstract": [
        {
          "text": "A vector of sixteen 32-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uint16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uint16"
        }
      ],
      "role": "symbol",
      "title": "simd_uint16",
      "type": "topic",
      "url": "/documentation/simd/simd_uint16"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint2": {
      "abstract": [
        {
          "text": "A vector of two 32-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uint2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uint2"
        }
      ],
      "role": "symbol",
      "title": "simd_uint2",
      "type": "topic",
      "url": "/documentation/simd/simd_uint2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint3": {
      "abstract": [
        {
          "text": "A vector of three 32-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uint3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uint3"
        }
      ],
      "role": "symbol",
      "title": "simd_uint3",
      "type": "topic",
      "url": "/documentation/simd/simd_uint3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint4": {
      "abstract": [
        {
          "text": "A vector of four 32-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uint4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uint4"
        }
      ],
      "role": "symbol",
      "title": "simd_uint4",
      "type": "topic",
      "url": "/documentation/simd/simd_uint4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint8": {
      "abstract": [
        {
          "text": "A vector of eight 32-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uint8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uint8"
        }
      ],
      "role": "symbol",
      "title": "simd_uint8",
      "type": "topic",
      "url": "/documentation/simd/simd_uint8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bebq": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uint_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bebq",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uint_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uint_sat-1bebq"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bexu": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uint_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bexu",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uint_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uint_sat-1bexu"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bf6e": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uint_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bf6e",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uint_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uint_sat-1bf6e"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bhbm": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uint_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bhbm",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uint_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uint_sat-1bhbm"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bi96": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uint_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bi96",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uint_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uint_sat-1bi96"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bk2e": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uint_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bk2e",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uint_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uint_sat-1bk2e"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bp92": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uint_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bp92",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uint_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uint_sat-1bp92"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1brg2": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uint_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1brg2",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uint_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uint_sat-1brg2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bs6i": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uint_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bs6i",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uint_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uint_sat-1bs6i"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bu8m": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uint_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bu8m",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uint_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uint_sat-1bu8m"
    },
    "doc://com.apple.accelerate/documentation/simd/vector8-2a1px": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector8-2a1px",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector8",
      "type": "topic",
      "url": "/documentation/simd/vector8-2a1px"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_uint8": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vector_uint8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_uint8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vector_uint8"
        }
      ],
      "role": "symbol",
      "title": "vector_uint8",
      "type": "topic",
      "url": "/documentation/simd/vector_uint8"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s5SIMD8V": {
      "abstract": [
        {
          "text": "A vector of eight scalar values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SIMD8"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SIMDScalarP",
          "text": "SIMDScalar"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5SIMD8V",
      "kind": "symbol",
      "role": "symbol",
      "title": "SIMD8",
      "type": "topic",
      "url": "/documentation/Swift/SIMD8"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt32V": {
      "abstract": [
        {
          "text": "A 32-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt32",
      "type": "topic",
      "url": "/documentation/Swift/UInt32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Vector-Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_uint1",
        "doc://com.apple.accelerate/documentation/simd/simd_uint2",
        "doc://com.apple.accelerate/documentation/simd/simd_uint3",
        "doc://com.apple.accelerate/documentation/simd/simd_uint4",
        "doc://com.apple.accelerate/documentation/simd/simd_uint16"
      ],
      "title": "Vector Data Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Functions-to-Create-Eight-Element-Vectors-From-Other-Vectors",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_uint8(_:)-2vaoh",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uint8(_:)-2rtxs",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uint8(_:)-2ovzr",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uint8(_:)-3sztf",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uint8(_:)-64gkj",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uint8(_:_:)",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uint8_undef(_:)-ck1m",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uint8_undef(_:)-hojv",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uint8_undef(_:)-6a8k"
      ],
      "title": "Functions to Create Eight-Element Vectors From Other Vectors"
    },
    {
      "anchor": "Functions-to-Create-Eight-Element-Vectors-From-Scalar-Values",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_uint8(_:)-7jqj3",
        "doc://com.apple.accelerate/documentation/simd/simd_make_uint8_undef(_:)-8p5i8"
      ],
      "title": "Functions to Create Eight-Element Vectors From Scalar Values"
    },
    {
      "anchor": "Common-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-9evfi",
        "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-1v1wn"
      ],
      "title": "Common Functions"
    },
    {
      "anchor": "Reduce-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-3o9f6",
        "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-55ah6",
        "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-3av90"
      ],
      "title": "Reduce Functions"
    },
    {
      "anchor": "Extrema-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-873mx",
        "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-4l2k6"
      ],
      "title": "Extrema Functions"
    },
    {
      "anchor": "Logic-and-Bitwise-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-6p8mz",
        "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1ynbd",
        "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-803fj"
      ],
      "title": "Logic and Bitwise Functions"
    },
    {
      "anchor": "Alternative-Type-Alias",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/vector_uint8"
      ],
      "title": "Alternative Type Alias"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "simd_uint8"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uint8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uint8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/simd"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Functions-to-Create-Eight-Element-Vectors-From-Other-Vectors",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_uint8(_:)-2vaoh",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uint8(_:)-2rtxs",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uint8(_:)-2ovzr",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uint8(_:)-3sztf",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uint8(_:)-64gkj",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uint8(_:_:)",
                "doc://com.apple.accelerate/documentation/simd/vector8-2a1px",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uint8_undef(_:)-ck1m",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uint8_undef(_:)-hojv",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uint8_undef(_:)-6a8k"
              ],
              "title": "Functions to Create Eight-Element Vectors From Other Vectors"
            },
            {
              "anchor": "Functions-to-Create-Eight-Element-Vectors-From-Scalar-Values",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_uint8(_:)-7jqj3",
                "doc://com.apple.accelerate/documentation/simd/simd_make_uint8_undef(_:)-8p5i8"
              ],
              "title": "Functions to Create Eight-Element Vectors From Scalar Values"
            },
            {
              "anchor": "Functions-to-Create-Eight-Element-Vectors-From-Vectors-of-Other-Types",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_uint-8dih8",
                "doc://com.apple.accelerate/documentation/simd/simd_uint-8ds98",
                "doc://com.apple.accelerate/documentation/simd/simd_uint-8ddf0",
                "doc://com.apple.accelerate/documentation/simd/simd_uint-8dncc",
                "doc://com.apple.accelerate/documentation/simd/simd_uint-8dgmc",
                "doc://com.apple.accelerate/documentation/simd/simd_uint-8dqg4",
                "doc://com.apple.accelerate/documentation/simd/simd_uint-8dhgw",
                "doc://com.apple.accelerate/documentation/simd/simd_uint-8drlc",
                "doc://com.apple.accelerate/documentation/simd/simd_uint-8dt6o",
                "doc://com.apple.accelerate/documentation/simd/simd_uint-8dtuo"
              ],
              "title": "Functions to Create Eight-Element Vectors From Vectors of Other Types"
            },
            {
              "anchor": "Functions-to-Perform-Saturating-Conversion-From-Vectors-of-Other-Types",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bp92",
                "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bf6e",
                "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bu8m",
                "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bk2e",
                "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bs6i",
                "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bi96",
                "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1brg2",
                "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bhbm",
                "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bebq",
                "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bexu"
              ],
              "title": "Functions to Perform Saturating Conversion From Vectors of Other Types"
            },
            {
              "anchor": "Common-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-9evfi",
                "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-1v1wn"
              ],
              "title": "Common Functions"
            },
            {
              "anchor": "Reduce-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-3o9f6",
                "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-55ah6",
                "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-3av90"
              ],
              "title": "Reduce Functions"
            },
            {
              "anchor": "Extrema-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-873mx",
                "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-4l2k6"
              ],
              "title": "Extrema Functions"
            },
            {
              "anchor": "Logic-and-Bitwise-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-6p8mz",
                "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1ynbd",
                "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-803fj"
              ],
              "title": "Logic and Bitwise Functions"
            },
            {
              "anchor": "Alternative-Type-Alias",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/vector_uint8"
              ],
              "title": "Alternative Type Alias"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Vector-Data-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_uint1",
                "doc://com.apple.accelerate/documentation/simd/simd_uint2",
                "doc://com.apple.accelerate/documentation/simd/simd_uint3",
                "doc://com.apple.accelerate/documentation/simd/simd_uint4",
                "doc://com.apple.accelerate/documentation/simd/simd_uint16"
              ],
              "title": "Vector Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:]8i",
                    "text": "unsigned int __attribute__((ext_vector_type(8)))"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "simd_uint8"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_bitselect(_:_:_:)-803fj/title",
          "value": "simd_bitselect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_bitselect(_:_:_:)-803fj/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_bitselect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uint8(_:)-2vaoh/title",
          "value": "simd_make_uint8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uint8(_:)-2vaoh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uint8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uint8(_:)-2rtxs/title",
          "value": "simd_make_uint8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uint8(_:)-2rtxs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uint8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_clamp(_:_:_:)-9evfi/title",
          "value": "simd_clamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_clamp(_:_:_:)-9evfi/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_clamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uint8(_:)-3sztf/title",
          "value": "simd_make_uint8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uint8(_:)-3sztf/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uint8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uint8(_:_:)/title",
          "value": "simd_make_uint8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uint8(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uint8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint1/title",
          "value": "simd_uint1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uint1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint1/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uint1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_add(_:)-3av90/title",
          "value": "simd_reduce_add"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_add(_:)-3av90/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_add"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_any(_:)-6p8mz/title",
          "value": "simd_any"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_any(_:)-6p8mz/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_any"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint2/title",
          "value": "simd_uint2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uint2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uint2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_min(_:)-3o9f6/title",
          "value": "simd_reduce_min"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_min(_:)-3o9f6/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_min"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_equal(_:_:)-1v1wn/title",
          "value": "simd_equal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_equal(_:_:)-1v1wn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_equal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uint8_undef(_:)-hojv/title",
          "value": "simd_make_uint8_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uint8_undef(_:)-hojv/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uint8_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint3/title",
          "value": "simd_uint3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uint3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uint3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uint8_undef(_:)-ck1m/title",
          "value": "simd_make_uint8_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uint8_undef(_:)-ck1m/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uint8_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint8/title",
          "value": "simd_uint8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uint8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uint8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint4/title",
          "value": "simd_uint4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uint4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uint4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uint8(_:)-2ovzr/title",
          "value": "simd_make_uint8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uint8(_:)-2ovzr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uint8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uint8(_:)-7jqj3/title",
          "value": "simd_make_uint8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uint8(_:)-7jqj3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uint8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_max(_:_:)-4l2k6/title",
          "value": "simd_max"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_max(_:_:)-4l2k6/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_max"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uint8_undef(_:)-8p5i8/title",
          "value": "simd_make_uint8_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uint8_undef(_:)-8p5i8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uint8_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_min(_:_:)-873mx/title",
          "value": "simd_min"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_min(_:_:)-873mx/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_min"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1vector_uint8/title",
          "value": "vector_uint8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1vector_uint8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vector_uint8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1vector_uint8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vector_uint8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint16/title",
          "value": "simd_uint16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uint16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint16/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uint16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uint8_undef(_:)-6a8k/title",
          "value": "simd_make_uint8_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uint8_undef(_:)-6a8k/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uint8_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uint8(_:)-64gkj/title",
          "value": "simd_make_uint8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_uint8(_:)-64gkj/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_uint8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_max(_:)-55ah6/title",
          "value": "simd_reduce_max"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_max(_:)-55ah6/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_max"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_all(_:)-1ynbd/title",
          "value": "simd_all"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_all(_:)-1ynbd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_all"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_uint8"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/simd/simd_uint8"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
