{
  "abstract": [
    {
      "text": "A vector of eight 64-bit unsigned integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_ulong8"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@simd_ulong8",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simd_ulong8"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_ulong8"
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "simd_ulong8"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_ulong8"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5SIMD8V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5SIMD8V",
              "text": "SIMD8"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong1",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_ulong1",
              "text": "simd_ulong1"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1yolz": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_all"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong8",
          "text": "simd_ulong8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_bool",
          "text": "simd_bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1yolz",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_all"
        }
      ],
      "role": "symbol",
      "title": "simd_all(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_all(_:)-1yolz"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-6p9gh": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_any"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong8",
          "text": "simd_ulong8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_bool",
          "text": "simd_bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-6p9gh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_any"
        }
      ],
      "role": "symbol",
      "title": "simd_any(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_any(_:)-6p9gh"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-3xirg": {
      "abstract": [
        {
          "text": "Returns a vector that contains elements from either the first or second parameter, based on the corresponding element in the third parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_bitselect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong8",
          "text": "simd_ulong8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong8",
          "text": "simd_ulong8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long8",
          "text": "simd_long8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong8",
          "text": "simd_ulong8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-3xirg",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_bitselect"
        }
      ],
      "role": "symbol",
      "title": "simd_bitselect(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_bitselect(_:_:_:)-3xirg"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-6mt76": {
      "abstract": [
        {
          "text": "Returns each element in a vector clamped to a specified range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_clamp"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong8",
          "text": "simd_ulong8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong8",
          "text": "simd_ulong8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong8",
          "text": "simd_ulong8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong8",
          "text": "simd_ulong8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-6mt76",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_clamp"
        }
      ],
      "role": "symbol",
      "title": "simd_clamp(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_clamp(_:_:_:)-6mt76"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-4dws0": {
      "abstract": [
        {
          "text": "Returns true if every element in a matrix is exactly equal to the corresponding element in a second matrix, and otherwise returns false.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_equal"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong8",
          "text": "simd_ulong8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong8",
          "text": "simd_ulong8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_bool",
          "text": "simd_bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-4dws0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_equal"
        }
      ],
      "role": "symbol",
      "title": "simd_equal(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_equal(_:_:)-4dws0"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8(_:)-5w0n4": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ulong8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong2",
          "text": "simd_ulong2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong8",
          "text": "simd_ulong8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8(_:)-5w0n4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ulong8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ulong8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ulong8(_:)-5w0n4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8(_:)-5zhz7": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified three-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ulong8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong3",
          "text": "simd_ulong3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong8",
          "text": "simd_ulong8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8(_:)-5zhz7",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ulong8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ulong8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ulong8(_:)-5zhz7"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8(_:)-6hggi": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified four-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ulong8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong4",
          "text": "simd_ulong4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong8",
          "text": "simd_ulong8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8(_:)-6hggi",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ulong8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ulong8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ulong8(_:)-6hggi"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8(_:)-6wa2m": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ulong8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong8",
          "text": "simd_ulong8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong8",
          "text": "simd_ulong8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8(_:)-6wa2m",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ulong8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ulong8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ulong8(_:)-6wa2m"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8(_:)-w5ee": {
      "abstract": [
        {
          "text": "Returns a new vector with the first element set to a scalar value, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ulong8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong1",
          "text": "simd_ulong1"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong8",
          "text": "simd_ulong8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8(_:)-w5ee",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ulong8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ulong8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ulong8(_:)-w5ee"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ulong8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong4",
          "text": "simd_ulong4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong4",
          "text": "simd_ulong4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong8",
          "text": "simd_ulong8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ulong8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ulong8(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ulong8(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8_undef(_:)-73woc": {
      "abstract": [
        {
          "text": "Returns a new vector with the first element set to a scalar value, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ulong8_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong1",
          "text": "simd_ulong1"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong8",
          "text": "simd_ulong8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8_undef(_:)-73woc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ulong8_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ulong8_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ulong8_undef(_:)-73woc"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8_undef(_:)-9oge2": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified three-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ulong8_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong3",
          "text": "simd_ulong3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong8",
          "text": "simd_ulong8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8_undef(_:)-9oge2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ulong8_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ulong8_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ulong8_undef(_:)-9oge2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8_undef(_:)-9rdt9": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ulong8_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong2",
          "text": "simd_ulong2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong8",
          "text": "simd_ulong8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8_undef(_:)-9rdt9",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ulong8_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ulong8_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ulong8_undef(_:)-9rdt9"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8_undef(_:)-d5pk": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified four-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ulong8_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong4",
          "text": "simd_ulong4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong8",
          "text": "simd_ulong8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8_undef(_:)-d5pk",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ulong8_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ulong8_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ulong8_undef(_:)-d5pk"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-9mj3u": {
      "abstract": [
        {
          "text": "Returns the maximum value of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_max"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong8",
          "text": "simd_ulong8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong8",
          "text": "simd_ulong8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong8",
          "text": "simd_ulong8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-9mj3u",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_max"
        }
      ],
      "role": "symbol",
      "title": "simd_max(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_max(_:_:)-9mj3u"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-1ynv5": {
      "abstract": [
        {
          "text": "Returns the minimum value of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_min"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong8",
          "text": "simd_ulong8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong8",
          "text": "simd_ulong8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong8",
          "text": "simd_ulong8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-1ynv5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_min"
        }
      ],
      "role": "symbol",
      "title": "simd_min(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_min(_:_:)-1ynv5"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-3avzc": {
      "abstract": [
        {
          "text": "Returns the sum of all elements in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_add"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong8",
          "text": "simd_ulong8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong1",
          "text": "simd_ulong1"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-3avzc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_add"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_add(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_add(_:)-3avzc"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-55c36": {
      "abstract": [
        {
          "text": "Returns the maximum value in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_max"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong8",
          "text": "simd_ulong8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong1",
          "text": "simd_ulong1"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-55c36",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_max"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_max(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_max(_:)-55c36"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-3oaqy": {
      "abstract": [
        {
          "text": "Returns the miniumum value in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_min"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong8",
          "text": "simd_ulong8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong1",
          "text": "simd_ulong1"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-3oaqy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_min"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_min(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_min(_:)-3oaqy"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong-1692y": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong-1692y",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong-1692y"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong-16dyy": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong-16dyy",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong-16dyy"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong-16eyu": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong-16eyu",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong-16eyu"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong-16fzq": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong-16fzq",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong-16fzq"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong-16j3u": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong-16j3u",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong-16j3u"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong-16mhi": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong-16mhi",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong-16mhi"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong-16n5e": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong-16n5e",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong-16n5e"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong-16o3e": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong-16o3e",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong-16o3e"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong-16oxy": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong-16oxy",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong-16oxy"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong-16px2": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong-16px2",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong-16px2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong1": {
      "abstract": [
        {
          "text": "A vector of one 64-bit unsigned integer element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ulong1"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ulong1"
        }
      ],
      "role": "symbol",
      "title": "simd_ulong1",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong2": {
      "abstract": [
        {
          "text": "A vector of two 64-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ulong2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ulong2"
        }
      ],
      "role": "symbol",
      "title": "simd_ulong2",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong3": {
      "abstract": [
        {
          "text": "A vector of three 64-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ulong3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ulong3"
        }
      ],
      "role": "symbol",
      "title": "simd_ulong3",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong4": {
      "abstract": [
        {
          "text": "A vector of four 64-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ulong4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ulong4"
        }
      ],
      "role": "symbol",
      "title": "simd_ulong4",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong8": {
      "abstract": [
        {
          "text": "A vector of eight 64-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ulong8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ulong8"
        }
      ],
      "role": "symbol",
      "title": "simd_ulong8",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-nu30": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-nu30",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong_sat-nu30"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-nvpk": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-nvpk",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong_sat-nvpk"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-nyps": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-nyps",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong_sat-nyps"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-o3vk": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-o3vk",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong_sat-o3vk"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-o3yk": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-o3yk",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong_sat-o3yk"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-o5oo": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-o5oo",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong_sat-o5oo"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-o6mk": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-o6mk",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong_sat-o6mk"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-o7ac": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-o7ac",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong_sat-o7ac"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-o8sg": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-o8sg",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong_sat-o8sg"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-odsw": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-odsw",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong_sat-odsw"
    },
    "doc://com.apple.accelerate/documentation/simd/vector8-5kkur": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector8-5kkur",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector8",
      "type": "topic",
      "url": "/documentation/simd/vector8-5kkur"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_ulong8": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vector_ulong8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_ulong8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vector_ulong8"
        }
      ],
      "role": "symbol",
      "title": "vector_ulong8",
      "type": "topic",
      "url": "/documentation/simd/vector_ulong8"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s5SIMD8V": {
      "abstract": [
        {
          "text": "A vector of eight scalar values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SIMD8"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SIMDScalarP",
          "text": "SIMDScalar"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5SIMD8V",
      "kind": "symbol",
      "role": "symbol",
      "title": "SIMD8",
      "type": "topic",
      "url": "/documentation/Swift/SIMD8"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Vector-Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_ulong1",
        "doc://com.apple.accelerate/documentation/simd/simd_ulong2",
        "doc://com.apple.accelerate/documentation/simd/simd_ulong3",
        "doc://com.apple.accelerate/documentation/simd/simd_ulong4"
      ],
      "title": "Vector Data Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Functions-to-Create-Eight-Element-Vectors-From-Other-Vectors",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8(_:)-5w0n4",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8(_:)-5zhz7",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8(_:)-6hggi",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8(_:)-6wa2m",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8(_:_:)",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8_undef(_:)-9rdt9",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8_undef(_:)-9oge2",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8_undef(_:)-d5pk"
      ],
      "title": "Functions to Create Eight-Element Vectors From Other Vectors"
    },
    {
      "anchor": "Functions-to-Create-Eight-Element-Vectors-From-Scalar-Values",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8(_:)-w5ee",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8_undef(_:)-73woc"
      ],
      "title": "Functions to Create Eight-Element Vectors From Scalar Values"
    },
    {
      "anchor": "Common-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-6mt76",
        "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-4dws0"
      ],
      "title": "Common Functions"
    },
    {
      "anchor": "Reduce-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-3oaqy",
        "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-55c36",
        "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-3avzc"
      ],
      "title": "Reduce Functions"
    },
    {
      "anchor": "Extrema-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-1ynv5",
        "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-9mj3u"
      ],
      "title": "Extrema Functions"
    },
    {
      "anchor": "Logic-and-Bitwise-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-6p9gh",
        "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1yolz",
        "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-3xirg"
      ],
      "title": "Logic and Bitwise Functions"
    },
    {
      "anchor": "Alternative-Type-Alias",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/vector_ulong8"
      ],
      "title": "Alternative Type Alias"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "simd_ulong8"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/simd"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Functions-to-Create-Eight-Element-Vectors-From-Other-Vectors",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8(_:)-5w0n4",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8(_:)-5zhz7",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8(_:)-6hggi",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8(_:)-6wa2m",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8(_:_:)",
                "doc://com.apple.accelerate/documentation/simd/vector8-5kkur",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8_undef(_:)-9rdt9",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8_undef(_:)-9oge2",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8_undef(_:)-d5pk"
              ],
              "title": "Functions to Create Eight-Element Vectors From Other Vectors"
            },
            {
              "anchor": "Functions-to-Create-Eight-Element-Vectors-From-Scalar-Values",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8(_:)-w5ee",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ulong8_undef(_:)-73woc"
              ],
              "title": "Functions to Create Eight-Element Vectors From Scalar Values"
            },
            {
              "anchor": "Functions-to-Create-Eight-Element-Vectors-From-Vectors-of-Other-Types",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_ulong-16dyy",
                "doc://com.apple.accelerate/documentation/simd/simd_ulong-16o3e",
                "doc://com.apple.accelerate/documentation/simd/simd_ulong-1692y",
                "doc://com.apple.accelerate/documentation/simd/simd_ulong-16j3u",
                "doc://com.apple.accelerate/documentation/simd/simd_ulong-16fzq",
                "doc://com.apple.accelerate/documentation/simd/simd_ulong-16px2",
                "doc://com.apple.accelerate/documentation/simd/simd_ulong-16eyu",
                "doc://com.apple.accelerate/documentation/simd/simd_ulong-16oxy",
                "doc://com.apple.accelerate/documentation/simd/simd_ulong-16n5e",
                "doc://com.apple.accelerate/documentation/simd/simd_ulong-16mhi"
              ],
              "title": "Functions to Create Eight-Element Vectors From Vectors of Other Types"
            },
            {
              "anchor": "Functions-to-Perform-Saturating-Conversion-From-Vectors-of-Other-Types",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-nyps",
                "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-o8sg",
                "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-o3vk",
                "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-odsw",
                "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-nvpk",
                "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-o5oo",
                "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-nu30",
                "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-o3yk",
                "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-o7ac",
                "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-o6mk"
              ],
              "title": "Functions to Perform Saturating Conversion From Vectors of Other Types"
            },
            {
              "anchor": "Common-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-6mt76",
                "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-4dws0"
              ],
              "title": "Common Functions"
            },
            {
              "anchor": "Reduce-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-3oaqy",
                "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-55c36",
                "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-3avzc"
              ],
              "title": "Reduce Functions"
            },
            {
              "anchor": "Extrema-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-1ynv5",
                "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-9mj3u"
              ],
              "title": "Extrema Functions"
            },
            {
              "anchor": "Logic-and-Bitwise-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-6p9gh",
                "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1yolz",
                "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-3xirg"
              ],
              "title": "Logic and Bitwise Functions"
            },
            {
              "anchor": "Alternative-Type-Alias",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/vector_ulong8"
              ],
              "title": "Alternative Type Alias"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Vector-Data-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_ulong1",
                "doc://com.apple.accelerate/documentation/simd/simd_ulong2",
                "doc://com.apple.accelerate/documentation/simd/simd_ulong3",
                "doc://com.apple.accelerate/documentation/simd/simd_ulong4"
              ],
              "title": "Vector Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:]8l",
                    "text": "unsigned long __attribute__((ext_vector_type(8)))"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "simd_ulong8"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_equal(_:_:)-4dws0/title",
          "value": "simd_equal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_equal(_:_:)-4dws0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_equal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_min(_:)-3oaqy/title",
          "value": "simd_reduce_min"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_min(_:)-3oaqy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_min"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong8_undef(_:)-9oge2/title",
          "value": "simd_make_ulong8_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong8_undef(_:)-9oge2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ulong8_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_min(_:_:)-1ynv5/title",
          "value": "simd_min"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_min(_:_:)-1ynv5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_min"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong3/title",
          "value": "simd_ulong3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_max(_:)-55c36/title",
          "value": "simd_reduce_max"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_max(_:)-55c36/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_max"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong8(_:)-5w0n4/title",
          "value": "simd_make_ulong8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong8(_:)-5w0n4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ulong8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong8(_:)-6wa2m/title",
          "value": "simd_make_ulong8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong8(_:)-6wa2m/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ulong8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1vector_ulong8/title",
          "value": "vector_ulong8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1vector_ulong8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vector_ulong8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1vector_ulong8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vector_ulong8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_clamp(_:_:_:)-6mt76/title",
          "value": "simd_clamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_clamp(_:_:_:)-6mt76/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_clamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_add(_:)-3avzc/title",
          "value": "simd_reduce_add"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_add(_:)-3avzc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_add"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong4/title",
          "value": "simd_ulong4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong8(_:)-w5ee/title",
          "value": "simd_make_ulong8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong8(_:)-w5ee/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ulong8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_any(_:)-6p9gh/title",
          "value": "simd_any"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_any(_:)-6p9gh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_any"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong8_undef(_:)-d5pk/title",
          "value": "simd_make_ulong8_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong8_undef(_:)-d5pk/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ulong8_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong8(_:)-6hggi/title",
          "value": "simd_make_ulong8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong8(_:)-6hggi/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ulong8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong1/title",
          "value": "simd_ulong1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong1/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_all(_:)-1yolz/title",
          "value": "simd_all"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_all(_:)-1yolz/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_all"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong8(_:_:)/title",
          "value": "simd_make_ulong8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong8(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ulong8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_max(_:_:)-9mj3u/title",
          "value": "simd_max"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_max(_:_:)-9mj3u/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_max"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong2/title",
          "value": "simd_ulong2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong8_undef(_:)-9rdt9/title",
          "value": "simd_make_ulong8_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong8_undef(_:)-9rdt9/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ulong8_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong8/title",
          "value": "simd_ulong8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong8(_:)-5zhz7/title",
          "value": "simd_make_ulong8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong8(_:)-5zhz7/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ulong8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_bitselect(_:_:_:)-3xirg/title",
          "value": "simd_bitselect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_bitselect(_:_:_:)-3xirg/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_bitselect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong8_undef(_:)-73woc/title",
          "value": "simd_make_ulong8_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong8_undef(_:)-73woc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ulong8_undef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_ulong8"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/simd/simd_ulong8"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
