{
  "abstract": [
    {
      "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1p4p3"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_ulong_sat#]3C#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_ulong_sat"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_ulong_sat"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_ulong_sat"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong3",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_ulong3",
              "text": "simd_ulong3"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_ulong_sat"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char3",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_char3",
              "text": "simd_char3"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char3": {
      "abstract": [
        {
          "text": "A vector of three 8-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_char3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_char3"
        }
      ],
      "role": "symbol",
      "title": "simd_char3",
      "type": "topic",
      "url": "/documentation/simd/simd_char3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong3": {
      "abstract": [
        {
          "text": "A vector of three 64-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ulong3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ulong3"
        }
      ],
      "role": "symbol",
      "title": "simd_ulong3",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1ozs7": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1ozs7",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong_sat-1ozs7"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1p0xd": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1p0xd",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong_sat-1p0xd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1p1l7": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1p1l7",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong_sat-1p1l7"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1p4p3": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1p4p3",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong_sat-1p4p3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1p9pj": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1p9pj",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong_sat-1p9pj"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1panl": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1panl",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong_sat-1panl"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1pbrf": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1pbrf",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong_sat-1pbrf"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1pdb5": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1pdb5",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong_sat-1pdb5"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1pdyx": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1pdyx",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong_sat-1pdyx"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1pevb": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1pevb",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong_sat-1pevb"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Perform-Saturating-Conversion-From-Vectors-of-Other-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1pevb",
        "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1ozs7",
        "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1p9pj",
        "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1p1l7",
        "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1pbrf",
        "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1p0xd",
        "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1panl",
        "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1pdyx",
        "doc://com.apple.accelerate/documentation/simd/simd_ulong_sat-1pdb5"
      ],
      "title": "Functions to Perform Saturating Conversion From Vectors of Other Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char3/title",
          "value": "simd_char3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong3/title",
          "value": "simd_ulong3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong3"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_ulong_sat-1p4p3"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
