{
  "abstract": [
    {
      "text": "Returns the multiply-add result for corresponding elements in three vectors.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_muladd(_:_:_:)-8imv2"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_muladd#]16f#S0_#S0_#",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simd_muladd"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_float16",
        "text": "simd_float16"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_float16",
        "text": "simd_float16"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_float16",
        "text": "simd_float16"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_float16",
        "text": "simd_float16"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_muladd"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_muladd(_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_muladd"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "x"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float16",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_float16",
              "text": "simd_float16"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "y"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float16",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_float16",
              "text": "simd_float16"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "z"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float16",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_float16",
              "text": "simd_float16"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float16",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_float16",
              "text": "simd_float16"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The ",
                  "type": "text"
                },
                {
                  "inlineContent": [
                    {
                      "text": "x",
                      "type": "text"
                    }
                  ],
                  "type": "emphasis"
                },
                {
                  "text": " in ",
                  "type": "text"
                },
                {
                  "code": "x*y + z",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "x"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The ",
                  "type": "text"
                },
                {
                  "inlineContent": [
                    {
                      "text": "y",
                      "type": "text"
                    }
                  ],
                  "type": "emphasis"
                },
                {
                  "text": " in ",
                  "type": "text"
                },
                {
                  "code": "x*y + z",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "y"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The ",
                  "type": "text"
                },
                {
                  "inlineContent": [
                    {
                      "text": "z",
                      "type": "text"
                    }
                  ],
                  "type": "emphasis"
                },
                {
                  "text": " in ",
                  "type": "text"
                },
                {
                  "code": "x*y + z",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "z"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The result of ",
              "type": "text"
            },
            {
              "code": "x*y + z",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/cbrt(_:)-3cnri": {
      "abstract": [
        {
          "text": "Returns the cube root of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cbrt"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float16",
          "text": "simd_float16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float16",
          "text": "simd_float16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/cbrt(_:)-3cnri",
      "kind": "symbol",
      "role": "symbol",
      "title": "cbrt(_:)",
      "type": "topic",
      "url": "/documentation/simd/cbrt(_:)-3cnri"
    },
    "doc://com.apple.accelerate/documentation/simd/erf(_:)-7wkg3": {
      "abstract": [
        {
          "text": "Returns the error function for each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "erf"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float16",
          "text": "simd_float16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float16",
          "text": "simd_float16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/erf(_:)-7wkg3",
      "kind": "symbol",
      "role": "symbol",
      "title": "erf(_:)",
      "type": "topic",
      "url": "/documentation/simd/erf(_:)-7wkg3"
    },
    "doc://com.apple.accelerate/documentation/simd/erfc(_:)-20vsh": {
      "abstract": [
        {
          "text": "Returns the complementary error function for each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "erfc"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float16",
          "text": "simd_float16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float16",
          "text": "simd_float16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/erfc(_:)-20vsh",
      "kind": "symbol",
      "role": "symbol",
      "title": "erfc(_:)",
      "type": "topic",
      "url": "/documentation/simd/erfc(_:)-20vsh"
    },
    "doc://com.apple.accelerate/documentation/simd/fma(_:_:_:)-503dp": {
      "abstract": [
        {
          "text": "Returns the multiply-add result for corresponding elements in three vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fma"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float16",
          "text": "simd_float16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float16",
          "text": "simd_float16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float16",
          "text": "simd_float16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float16",
          "text": "simd_float16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/fma(_:_:_:)-503dp",
      "kind": "symbol",
      "role": "symbol",
      "title": "fma(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/fma(_:_:_:)-503dp"
    },
    "doc://com.apple.accelerate/documentation/simd/fmod(_:_:)-2bys0": {
      "abstract": [
        {
          "text": "Returns the modulus after dividing each element in a vector by the corresponding element in a second vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fmod"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float16",
          "text": "simd_float16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float16",
          "text": "simd_float16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float16",
          "text": "simd_float16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/fmod(_:_:)-2bys0",
      "kind": "symbol",
      "role": "symbol",
      "title": "fmod(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/fmod(_:_:)-2bys0"
    },
    "doc://com.apple.accelerate/documentation/simd/hypot(_:_:)-265pt": {
      "abstract": [
        {
          "text": "Returns the hypotenuse of a right-angled triangle with the sides that are adjacent to the right angle that two vectors define.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hypot"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float16",
          "text": "simd_float16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float16",
          "text": "simd_float16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float16",
          "text": "simd_float16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/hypot(_:_:)-265pt",
      "kind": "symbol",
      "role": "symbol",
      "title": "hypot(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/hypot(_:_:)-265pt"
    },
    "doc://com.apple.accelerate/documentation/simd/lgamma(_:)-1onkc": {
      "abstract": [
        {
          "text": "Returns the natural logarithm of the absolute value of the gamma function of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lgamma"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float16",
          "text": "simd_float16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float16",
          "text": "simd_float16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/lgamma(_:)-1onkc",
      "kind": "symbol",
      "role": "symbol",
      "title": "lgamma(_:)",
      "type": "topic",
      "url": "/documentation/simd/lgamma(_:)-1onkc"
    },
    "doc://com.apple.accelerate/documentation/simd/nextafter(_:_:)-9kvo8": {
      "abstract": [
        {
          "text": "Returns the next representable value of each element in a vector in the direction of the corresponding element in a second vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nextafter"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float16",
          "text": "simd_float16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float16",
          "text": "simd_float16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float16",
          "text": "simd_float16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/nextafter(_:_:)-9kvo8",
      "kind": "symbol",
      "role": "symbol",
      "title": "nextafter(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/nextafter(_:_:)-9kvo8"
    },
    "doc://com.apple.accelerate/documentation/simd/pow(_:_:)-7mpyc": {
      "abstract": [
        {
          "text": "Returns each element in a vector raised to the power of the corresponding element in a second vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pow"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float16",
          "text": "simd_float16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float16",
          "text": "simd_float16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float16",
          "text": "simd_float16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/pow(_:_:)-7mpyc",
      "kind": "symbol",
      "role": "symbol",
      "title": "pow(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/pow(_:_:)-7mpyc"
    },
    "doc://com.apple.accelerate/documentation/simd/remainder(_:_:)-5dxqm": {
      "abstract": [
        {
          "text": "Returns the remainder after dividing each element in an array by the corresponding element in a second array of double-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remainder"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float16",
          "text": "simd_float16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float16",
          "text": "simd_float16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float16",
          "text": "simd_float16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/remainder(_:_:)-5dxqm",
      "kind": "symbol",
      "role": "symbol",
      "title": "remainder(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/remainder(_:_:)-5dxqm"
    },
    "doc://com.apple.accelerate/documentation/simd/round(_:)-74w3c": {
      "abstract": [
        {
          "text": "Returns each element in a vector rounded to the nearest integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "round"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float16",
          "text": "simd_float16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float16",
          "text": "simd_float16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/round(_:)-74w3c",
      "kind": "symbol",
      "role": "symbol",
      "title": "round(_:)",
      "type": "topic",
      "url": "/documentation/simd/round(_:)-74w3c"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float16": {
      "abstract": [
        {
          "text": "A vector of sixteen 32-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_float16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_float16"
        }
      ],
      "role": "symbol",
      "title": "simd_float16",
      "type": "topic",
      "url": "/documentation/simd/simd_float16"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_muladd(_:_:_:)-8imv2": {
      "abstract": [
        {
          "text": "Returns the multiply-add result for corresponding elements in three vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_muladd"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float16",
          "text": "simd_float16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float16",
          "text": "simd_float16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float16",
          "text": "simd_float16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float16",
          "text": "simd_float16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_muladd(_:_:_:)-8imv2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_muladd"
        }
      ],
      "role": "symbol",
      "title": "simd_muladd(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_muladd(_:_:_:)-8imv2"
    },
    "doc://com.apple.accelerate/documentation/simd/tgamma(_:)-9r61k": {
      "abstract": [
        {
          "text": "Returns the gamma function for each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tgamma"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float16",
          "text": "simd_float16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float16",
          "text": "simd_float16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/tgamma(_:)-9r61k",
      "kind": "symbol",
      "role": "symbol",
      "title": "tgamma(_:)",
      "type": "topic",
      "url": "/documentation/simd/tgamma(_:)-9r61k"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Math-Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/cbrt(_:)-3cnri",
        "doc://com.apple.accelerate/documentation/simd/erf(_:)-7wkg3",
        "doc://com.apple.accelerate/documentation/simd/erfc(_:)-20vsh",
        "doc://com.apple.accelerate/documentation/simd/fma(_:_:_:)-503dp",
        "doc://com.apple.accelerate/documentation/simd/fmod(_:_:)-2bys0",
        "doc://com.apple.accelerate/documentation/simd/hypot(_:_:)-265pt",
        "doc://com.apple.accelerate/documentation/simd/lgamma(_:)-1onkc",
        "doc://com.apple.accelerate/documentation/simd/nextafter(_:_:)-9kvo8",
        "doc://com.apple.accelerate/documentation/simd/pow(_:_:)-7mpyc",
        "doc://com.apple.accelerate/documentation/simd/remainder(_:_:)-5dxqm",
        "doc://com.apple.accelerate/documentation/simd/round(_:)-74w3c",
        "doc://com.apple.accelerate/documentation/simd/tgamma(_:)-9r61k"
      ],
      "title": "Math Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "simd_muladd"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_muladd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/simd"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "static"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float16",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_float16",
                    "text": "simd_float16"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "simd_muladd"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float16",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_float16",
                    "text": "simd_float16"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "x"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float16",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_float16",
                    "text": "simd_float16"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "y"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float16",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_float16",
                    "text": "simd_float16"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "z"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The ",
                        "type": "text"
                      },
                      {
                        "inlineContent": [
                          {
                            "text": "x",
                            "type": "text"
                          }
                        ],
                        "type": "emphasis"
                      },
                      {
                        "text": " in ",
                        "type": "text"
                      },
                      {
                        "code": "x*y + z",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "x"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The ",
                        "type": "text"
                      },
                      {
                        "inlineContent": [
                          {
                            "text": "y",
                            "type": "text"
                          }
                        ],
                        "type": "emphasis"
                      },
                      {
                        "text": " in ",
                        "type": "text"
                      },
                      {
                        "code": "x*y + z",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "y"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The ",
                        "type": "text"
                      },
                      {
                        "inlineContent": [
                          {
                            "text": "z",
                            "type": "text"
                          }
                        ],
                        "type": "emphasis"
                      },
                      {
                        "text": " in ",
                        "type": "text"
                      },
                      {
                        "code": "x*y + z",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "z"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "The result of ",
                    "type": "text"
                  },
                  {
                    "code": "x*y + z",
                    "type": "codeVoice"
                  },
                  {
                    "text": ".",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float16/title",
          "value": "simd_float16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float16/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_muladd(_:_:_:)-8imv2/title",
          "value": "simd_muladd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_muladd(_:_:_:)-8imv2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_muladd"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_muladd(_:_:_:)-8imv2"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/simd/simd_muladd(_:_:_:)-8imv2"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
