{
  "abstract": [
    {
      "text": "Returns a new vector with the first element set to a scalar value, and other elements set to zero.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_make_ulong2(_:)-14omj"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_make_ulong2#l#",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simd_make_ulong2"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_ulong1",
        "text": "simd_ulong1"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_ulong2",
        "text": "simd_ulong2"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_make_ulong2"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_make_ulong2(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_make_ulong2"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "other"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong1",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_ulong1",
              "text": "simd_ulong1"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_ulong2",
              "text": "simd_ulong2"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ulong2(_:)-14omj": {
      "abstract": [
        {
          "text": "Returns a new vector with the first element set to a scalar value, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ulong2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong1",
          "text": "simd_ulong1"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong2",
          "text": "simd_ulong2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ulong2(_:)-14omj",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ulong2"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ulong2(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ulong2(_:)-14omj"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ulong2(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified scalar values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ulong2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong1",
          "text": "simd_ulong1"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong1",
          "text": "simd_ulong1"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong2",
          "text": "simd_ulong2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ulong2(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ulong2"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ulong2(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ulong2(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ulong2_undef(_:)": {
      "abstract": [
        {
          "text": "Returns a new vector with the first element set to a scalar value, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ulong2_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong1",
          "text": "simd_ulong1"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong2",
          "text": "simd_ulong2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ulong2_undef(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ulong2_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ulong2_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ulong2_undef(_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong1": {
      "abstract": [
        {
          "text": "A vector of one 64-bit unsigned integer element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ulong1"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ulong1"
        }
      ],
      "role": "symbol",
      "title": "simd_ulong1",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong2": {
      "abstract": [
        {
          "text": "A vector of two 64-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ulong2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ulong2"
        }
      ],
      "role": "symbol",
      "title": "simd_ulong2",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong2"
    },
    "doc://com.apple.accelerate/documentation/simd/vector2-6n9bx": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified scalar values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector2-6n9bx",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector2",
      "type": "topic",
      "url": "/documentation/simd/vector2-6n9bx"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Create-Two-Element-Vectors-From-Scalar-Values",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_ulong2(_:_:)",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ulong2_undef(_:)"
      ],
      "title": "Functions to Create Two-Element Vectors From Scalar Values"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "simd_make_ulong2"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ulong2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/simd"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Functions-to-Create-Two-Element-Vectors-From-Scalar-Values",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_ulong2(_:_:)",
                "doc://com.apple.accelerate/documentation/simd/vector2-6n9bx",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ulong2_undef(_:)"
              ],
              "title": "Functions to Create Two-Element Vectors From Scalar Values"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "static"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong2",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_ulong2",
                    "text": "simd_ulong2"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "simd_make_ulong2"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong1",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_ulong1",
                    "text": "simd_ulong1"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "other"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong2(_:_:)/title",
          "value": "simd_make_ulong2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong2(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ulong2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong2_undef(_:)/title",
          "value": "simd_make_ulong2_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong2_undef(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ulong2_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong2(_:)-14omj/title",
          "value": "simd_make_ulong2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong2(_:)-14omj/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ulong2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong2/title",
          "value": "simd_ulong2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong1/title",
          "value": "simd_ulong1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong1/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong1"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_make_ulong2(_:)-14omj"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/simd/simd_make_ulong2(_:)-14omj"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
