{
  "abstract": [
    {
      "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1xdsl"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_uchar_sat#]3c#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_uchar_sat"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_uchar_sat"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_uchar_sat"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar3",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_uchar3",
              "text": "simd_uchar3"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_uchar_sat"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar3",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_uchar3",
              "text": "simd_uchar3"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar3": {
      "abstract": [
        {
          "text": "A vector of three 8-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uchar3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uchar3"
        }
      ],
      "role": "symbol",
      "title": "simd_uchar3",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1x225": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1x225",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar_sat-1x225"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1x3m3": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1x3m3",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar_sat-1x3m3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1x3x1": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1x3x1",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar_sat-1x3x1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1x905": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1x905",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar_sat-1x905"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1xc6l": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1xc6l",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar_sat-1xc6l"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1xdor": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1xdor",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar_sat-1xdor"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1xdsl": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1xdsl",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar_sat-1xdsl"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1xfdz": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1xfdz",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar_sat-1xfdz"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1xfyj": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1xfyj",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar_sat-1xfyj"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1xis5": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1xis5",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar_sat-1xis5"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Perform-Saturating-Conversion-From-Vectors-of-Other-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1x3x1",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1x905",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1xis5",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1x225",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1xc6l",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1x3m3",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1xdor",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1xfdz",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1xfyj"
      ],
      "title": "Functions to Perform Saturating Conversion From Vectors of Other Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar3/title",
          "value": "simd_uchar3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar3"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_uchar_sat-1xdsl"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
