{
  "abstract": [
    {
      "text": "Returns a new vector from the specified vector of 8-bit, signed-integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_double-531gc"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_double#]2C#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_double"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_double"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_double"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_double2",
              "text": "simd_double2"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_double"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_char2",
              "text": "simd_char2"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char2": {
      "abstract": [
        {
          "text": "A vector of two 8-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_char2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_char2"
        }
      ],
      "role": "symbol",
      "title": "simd_char2",
      "type": "topic",
      "url": "/documentation/simd/simd_char2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double-531gc": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double-531gc",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_double",
      "type": "topic",
      "url": "/documentation/simd/simd_double-531gc"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double-534k4": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double-534k4",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_double",
      "type": "topic",
      "url": "/documentation/simd/simd_double-534k4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double-5365s": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double-5365s",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_double",
      "type": "topic",
      "url": "/documentation/simd/simd_double-5365s"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double-536fw": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double-536fw",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_double",
      "type": "topic",
      "url": "/documentation/simd/simd_double-536fw"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double-53bbw": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double-53bbw",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_double",
      "type": "topic",
      "url": "/documentation/simd/simd_double-53bbw"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double-53czc": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double-53czc",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_double",
      "type": "topic",
      "url": "/documentation/simd/simd_double-53czc"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double-53di8": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double-53di8",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_double",
      "type": "topic",
      "url": "/documentation/simd/simd_double-53di8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double-53ej8": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double-53ej8",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_double",
      "type": "topic",
      "url": "/documentation/simd/simd_double-53ej8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double-53fzk": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double-53fzk",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_double",
      "type": "topic",
      "url": "/documentation/simd/simd_double-53fzk"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double-53gf0": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double-53gf0",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_double",
      "type": "topic",
      "url": "/documentation/simd/simd_double-53gf0"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double2": {
      "abstract": [
        {
          "text": "A vector of two 64-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_double2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_double2"
        }
      ],
      "role": "symbol",
      "title": "simd_double2",
      "type": "topic",
      "url": "/documentation/simd/simd_double2"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Create-Three-Element-Vectors-From-Vectors-of-Other-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_double-53bbw",
        "doc://com.apple.accelerate/documentation/simd/simd_double-536fw",
        "doc://com.apple.accelerate/documentation/simd/simd_double-53gf0",
        "doc://com.apple.accelerate/documentation/simd/simd_double-534k4",
        "doc://com.apple.accelerate/documentation/simd/simd_double-53ej8",
        "doc://com.apple.accelerate/documentation/simd/simd_double-5365s",
        "doc://com.apple.accelerate/documentation/simd/simd_double-53fzk",
        "doc://com.apple.accelerate/documentation/simd/simd_double-53czc",
        "doc://com.apple.accelerate/documentation/simd/simd_double-53di8"
      ],
      "title": "Functions to Create Three-Element Vectors From Vectors of Other Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double2/title",
          "value": "simd_double2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char2/title",
          "value": "simd_char2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char2"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_double-531gc"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
