{
  "abstract": [
    {
      "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bu8m"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_uint_sat#]8S#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_uint_sat"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_uint_sat"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_uint_sat"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint8",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_uint8",
              "text": "simd_uint8"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_uint_sat"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short8",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_short8",
              "text": "simd_short8"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short8": {
      "abstract": [
        {
          "text": "A vector of eight 16-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_short8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_short8"
        }
      ],
      "role": "symbol",
      "title": "simd_short8",
      "type": "topic",
      "url": "/documentation/simd/simd_short8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint8": {
      "abstract": [
        {
          "text": "A vector of eight 32-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uint8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uint8"
        }
      ],
      "role": "symbol",
      "title": "simd_uint8",
      "type": "topic",
      "url": "/documentation/simd/simd_uint8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bebq": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uint_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bebq",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uint_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uint_sat-1bebq"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bexu": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uint_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bexu",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uint_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uint_sat-1bexu"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bf6e": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uint_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bf6e",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uint_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uint_sat-1bf6e"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bhbm": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uint_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bhbm",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uint_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uint_sat-1bhbm"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bi96": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uint_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bi96",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uint_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uint_sat-1bi96"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bk2e": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uint_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bk2e",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uint_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uint_sat-1bk2e"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bp92": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uint_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bp92",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uint_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uint_sat-1bp92"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1brg2": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uint_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1brg2",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uint_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uint_sat-1brg2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bs6i": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uint_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bs6i",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uint_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uint_sat-1bs6i"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bu8m": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uint_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bu8m",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uint_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uint_sat-1bu8m"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Perform-Saturating-Conversion-From-Vectors-of-Other-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bp92",
        "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bf6e",
        "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bk2e",
        "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bs6i",
        "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bi96",
        "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1brg2",
        "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bhbm",
        "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bebq",
        "doc://com.apple.accelerate/documentation/simd/simd_uint_sat-1bexu"
      ],
      "title": "Functions to Perform Saturating Conversion From Vectors of Other Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short8/title",
          "value": "simd_short8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint8/title",
          "value": "simd_uint8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uint8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uint8"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_uint_sat-1bu8m"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
