{
  "abstract": [
    {
      "text": "Returns a new vector by truncating the specified 16-element vector.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_make_half3(_:)-9063q"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_make_half3#]16h#",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simd_make_half3"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_half16",
        "text": "simd_half16"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_half3",
        "text": "simd_half3"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_make_half3"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_make_half3(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_make_half3"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "other"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half16",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_half16",
              "text": "simd_half16"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half3",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_half3",
              "text": "simd_half3"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half16": {
      "abstract": [
        {
          "text": "A vector of sixteen 16-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_half16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_half16"
        }
      ],
      "role": "symbol",
      "title": "simd_half16",
      "type": "topic",
      "url": "/documentation/simd/simd_half16"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half3": {
      "abstract": [
        {
          "text": "A vector of three 16-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_half3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_half3"
        }
      ],
      "role": "symbol",
      "title": "simd_half3",
      "type": "topic",
      "url": "/documentation/simd/simd_half3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_half3(_:)-4h0kc": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified four-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_half3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half4",
          "text": "simd_half4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half3",
          "text": "simd_half3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_half3(_:)-4h0kc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_half3"
        }
      ],
      "role": "symbol",
      "title": "simd_make_half3(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_half3(_:)-4h0kc"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_half3(_:)-4yz0x": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_half3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half3",
          "text": "simd_half3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half3",
          "text": "simd_half3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_half3(_:)-4yz0x",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_half3"
        }
      ],
      "role": "symbol",
      "title": "simd_make_half3(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_half3(_:)-4yz0x"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_half3(_:)-52gdy": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_half3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half2",
          "text": "simd_half2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half3",
          "text": "simd_half3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_half3(_:)-52gdy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_half3"
        }
      ],
      "role": "symbol",
      "title": "simd_make_half3(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_half3(_:)-52gdy"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_half3(_:)-5nca0": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified eight-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_half3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half8",
          "text": "simd_half8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half3",
          "text": "simd_half3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_half3(_:)-5nca0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_half3"
        }
      ],
      "role": "symbol",
      "title": "simd_make_half3(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_half3(_:)-5nca0"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_half3(_:)-64v1": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified 32-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_half3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half32",
          "text": "simd_half32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half3",
          "text": "simd_half3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_half3(_:)-64v1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_half3"
        }
      ],
      "role": "symbol",
      "title": "simd_make_half3(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_half3(_:)-64v1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_half3(_:)-9063q": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified 16-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_half3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half16",
          "text": "simd_half16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half3",
          "text": "simd_half3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_half3(_:)-9063q",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_half3"
        }
      ],
      "role": "symbol",
      "title": "simd_make_half3(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_half3(_:)-9063q"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_half3_undef(_:)-1frd1": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_half3_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half2",
          "text": "simd_half2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half3",
          "text": "simd_half3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_half3_undef(_:)-1frd1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_half3_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_half3_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_half3_undef(_:)-1frd1"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-create-three-element-vectors-from-other-vectors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_half3(_:)-52gdy",
        "doc://com.apple.accelerate/documentation/simd/simd_make_half3(_:)-4yz0x",
        "doc://com.apple.accelerate/documentation/simd/simd_make_half3(_:)-4h0kc",
        "doc://com.apple.accelerate/documentation/simd/simd_make_half3(_:)-5nca0",
        "doc://com.apple.accelerate/documentation/simd/simd_make_half3(_:)-64v1",
        "doc://com.apple.accelerate/documentation/simd/simd_make_half3_undef(_:)-1frd1"
      ],
      "title": "Functions to create three-element vectors from other vectors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "simd_make_half3"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_half3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/simd"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Functions-to-create-three-element-vectors-from-other-vectors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_half3(_:)-52gdy",
                "doc://com.apple.accelerate/documentation/simd/simd_make_half3(_:)-4yz0x",
                "doc://com.apple.accelerate/documentation/simd/simd_make_half3(_:)-4h0kc",
                "doc://com.apple.accelerate/documentation/simd/simd_make_half3(_:)-5nca0",
                "doc://com.apple.accelerate/documentation/simd/simd_make_half3(_:)-64v1",
                "doc://com.apple.accelerate/documentation/simd/simd_make_half3_undef(_:)-1frd1"
              ],
              "title": "Functions to create three-element vectors from other vectors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "static"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half3",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_half3",
                    "text": "simd_half3"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "simd_make_half3"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half16",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_half16",
                    "text": "simd_half16"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "other"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half3/title",
          "value": "simd_half3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half3(_:)-4h0kc/title",
          "value": "simd_make_half3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half3(_:)-4h0kc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_half3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half3(_:)-9063q/title",
          "value": "simd_make_half3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half3(_:)-9063q/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_half3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half3(_:)-64v1/title",
          "value": "simd_make_half3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half3(_:)-64v1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_half3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half3(_:)-4yz0x/title",
          "value": "simd_make_half3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half3(_:)-4yz0x/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_half3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half3(_:)-5nca0/title",
          "value": "simd_make_half3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half3(_:)-5nca0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_half3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half3_undef(_:)-1frd1/title",
          "value": "simd_make_half3_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half3_undef(_:)-1frd1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_half3_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half3(_:)-52gdy/title",
          "value": "simd_make_half3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_half3(_:)-52gdy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_half3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half16/title",
          "value": "simd_half16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half16/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half16"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_make_half3(_:)-9063q"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/simd/simd_make_half3(_:)-9063q"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
