{
  "abstract": [
    {
      "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7dvvt"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_int_sat#]8I#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_int_sat"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_int_sat"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_int_sat"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int8",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_int8",
              "text": "simd_int8"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_int_sat"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int8",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_int8",
              "text": "simd_int8"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int8": {
      "abstract": [
        {
          "text": "A vector of eight 32-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_int8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_int8"
        }
      ],
      "role": "symbol",
      "title": "simd_int8",
      "type": "topic",
      "url": "/documentation/simd/simd_int8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7dovl": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7dovl",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_int_sat-7dovl"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7dttd": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7dttd",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_int_sat-7dttd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7dubn": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7dubn",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_int_sat-7dubn"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7dvvt": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7dvvt",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_int_sat-7dvvt"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7dysx": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7dysx",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_int_sat-7dysx"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7e1v7": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7e1v7",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_int_sat-7e1v7"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7e2fr": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7e2fr",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_int_sat-7e2fr"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7e41d": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7e41d",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_int_sat-7e41d"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7e43n": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7e43n",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_int_sat-7e43n"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7e5pl": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7e5pl",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_int_sat-7e5pl"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Perform-Saturating-Conversion-From-Vectors-of-Other-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7dttd",
        "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7e41d",
        "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7dovl",
        "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7dysx",
        "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7e5pl",
        "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7dubn",
        "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7e43n",
        "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7e2fr",
        "doc://com.apple.accelerate/documentation/simd/simd_int_sat-7e1v7"
      ],
      "title": "Functions to Perform Saturating Conversion From Vectors of Other Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int8/title",
          "value": "simd_int8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_int8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_int8"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_int_sat-7dvvt"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
