{
  "abstract": [
    {
      "text": "Returns a new vector from the specified two-element vector, and other elements undefined.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_make_short16_undef(_:)-19u0l"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_make_short16_undef#]2S#",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simd_make_short16_undef"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_short2",
        "text": "simd_short2"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_short16",
        "text": "simd_short16"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_make_short16_undef"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_make_short16_undef(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_make_short16_undef"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "other"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_short2",
              "text": "simd_short2"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short16",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_short16",
              "text": "simd_short16"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short16(_:)-4ubc7": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified thirty two-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short16"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short32",
          "text": "simd_short32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short16",
          "text": "simd_short16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short16(_:)-4ubc7",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short16"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short16(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short16(_:)-4ubc7"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short16(_:)-5xtuv": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short16"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short16",
          "text": "simd_short16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short16",
          "text": "simd_short16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short16(_:)-5xtuv",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short16"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short16(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short16(_:)-5xtuv"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short16(_:)-82czr": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified four-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short16"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short4",
          "text": "simd_short4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short16",
          "text": "simd_short16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short16(_:)-82czr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short16"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short16(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short16(_:)-82czr"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short16(_:)-8892t": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short16"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short2",
          "text": "simd_short2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short16",
          "text": "simd_short16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short16(_:)-8892t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short16"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short16(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short16(_:)-8892t"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short16(_:)-8bejg": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified three-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short16"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short3",
          "text": "simd_short3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short16",
          "text": "simd_short16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short16(_:)-8bejg",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short16"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short16(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short16(_:)-8bejg"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short16(_:)-984rv": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified eight-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short16"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short16",
          "text": "simd_short16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short16(_:)-984rv",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short16"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short16(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short16(_:)-984rv"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short16(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short16"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short16",
          "text": "simd_short16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short16(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short16"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short16(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short16(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short16_undef(_:)-11st3": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified four-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short16_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short4",
          "text": "simd_short4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short16",
          "text": "simd_short16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short16_undef(_:)-11st3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short16_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short16_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short16_undef(_:)-11st3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short16_undef(_:)-150ws": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified three-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short16_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short3",
          "text": "simd_short3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short16",
          "text": "simd_short16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short16_undef(_:)-150ws",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short16_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short16_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short16_undef(_:)-150ws"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short16_undef(_:)-19u0l": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short16_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short2",
          "text": "simd_short2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short16",
          "text": "simd_short16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short16_undef(_:)-19u0l",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short16_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short16_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short16_undef(_:)-19u0l"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short16_undef(_:)-27knv": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified eight-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short16_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short16",
          "text": "simd_short16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short16_undef(_:)-27knv",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short16_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short16_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short16_undef(_:)-27knv"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short16": {
      "abstract": [
        {
          "text": "A vector of sixteen 16-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_short16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_short16"
        }
      ],
      "role": "symbol",
      "title": "simd_short16",
      "type": "topic",
      "url": "/documentation/simd/simd_short16"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short2": {
      "abstract": [
        {
          "text": "A vector of two 16-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_short2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_short2"
        }
      ],
      "role": "symbol",
      "title": "simd_short2",
      "type": "topic",
      "url": "/documentation/simd/simd_short2"
    },
    "doc://com.apple.accelerate/documentation/simd/vector16-97qyz": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector16-97qyz",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector16",
      "type": "topic",
      "url": "/documentation/simd/vector16-97qyz"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Create-Sixteen-Element-Vectors-From-Other-Vectors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_short16(_:)-8892t",
        "doc://com.apple.accelerate/documentation/simd/simd_make_short16(_:)-8bejg",
        "doc://com.apple.accelerate/documentation/simd/simd_make_short16(_:)-82czr",
        "doc://com.apple.accelerate/documentation/simd/simd_make_short16(_:)-984rv",
        "doc://com.apple.accelerate/documentation/simd/simd_make_short16(_:)-5xtuv",
        "doc://com.apple.accelerate/documentation/simd/simd_make_short16(_:)-4ubc7",
        "doc://com.apple.accelerate/documentation/simd/simd_make_short16(_:_:)",
        "doc://com.apple.accelerate/documentation/simd/simd_make_short16_undef(_:)-150ws",
        "doc://com.apple.accelerate/documentation/simd/simd_make_short16_undef(_:)-11st3",
        "doc://com.apple.accelerate/documentation/simd/simd_make_short16_undef(_:)-27knv"
      ],
      "title": "Functions to Create Sixteen-Element Vectors From Other Vectors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "simd_make_short16_undef"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short16_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/simd"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Functions-to-Create-Sixteen-Element-Vectors-From-Other-Vectors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_short16(_:)-8892t",
                "doc://com.apple.accelerate/documentation/simd/simd_make_short16(_:)-8bejg",
                "doc://com.apple.accelerate/documentation/simd/simd_make_short16(_:)-82czr",
                "doc://com.apple.accelerate/documentation/simd/simd_make_short16(_:)-984rv",
                "doc://com.apple.accelerate/documentation/simd/simd_make_short16(_:)-5xtuv",
                "doc://com.apple.accelerate/documentation/simd/simd_make_short16(_:)-4ubc7",
                "doc://com.apple.accelerate/documentation/simd/simd_make_short16(_:_:)",
                "doc://com.apple.accelerate/documentation/simd/vector16-97qyz",
                "doc://com.apple.accelerate/documentation/simd/simd_make_short16_undef(_:)-150ws",
                "doc://com.apple.accelerate/documentation/simd/simd_make_short16_undef(_:)-11st3",
                "doc://com.apple.accelerate/documentation/simd/simd_make_short16_undef(_:)-27knv"
              ],
              "title": "Functions to Create Sixteen-Element Vectors From Other Vectors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "static"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short16",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_short16",
                    "text": "simd_short16"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "simd_make_short16_undef"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short2",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_short2",
                    "text": "simd_short2"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "other"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short16_undef(_:)-27knv/title",
          "value": "simd_make_short16_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short16_undef(_:)-27knv/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short16_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short16_undef(_:)-150ws/title",
          "value": "simd_make_short16_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short16_undef(_:)-150ws/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short16_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short16_undef(_:)-19u0l/title",
          "value": "simd_make_short16_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short16_undef(_:)-19u0l/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short16_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short16(_:)-8bejg/title",
          "value": "simd_make_short16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short16(_:)-8bejg/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short16(_:)-8892t/title",
          "value": "simd_make_short16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short16(_:)-8892t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short16/title",
          "value": "simd_short16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short16/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short16(_:)-82czr/title",
          "value": "simd_make_short16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short16(_:)-82czr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short16(_:_:)/title",
          "value": "simd_make_short16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short16(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short16(_:)-4ubc7/title",
          "value": "simd_make_short16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short16(_:)-4ubc7/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short16_undef(_:)-11st3/title",
          "value": "simd_make_short16_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short16_undef(_:)-11st3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short16_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short16(_:)-984rv/title",
          "value": "simd_make_short16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short16(_:)-984rv/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short16(_:)-5xtuv/title",
          "value": "simd_make_short16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short16(_:)-5xtuv/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short2/title",
          "value": "simd_short2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short2"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_make_short16_undef(_:)-19u0l"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/simd/simd_make_short16_undef(_:)-19u0l"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
