{
  "abstract": [
    {
      "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_uchar-8xyej"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_uchar#]3c#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_uchar"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_uchar"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_uchar"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar3",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_uchar3",
              "text": "simd_uchar3"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_uchar"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar3",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_uchar3",
              "text": "simd_uchar3"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar-8xmh3": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar-8xmh3",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar-8xmh3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar-8xnn5": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar-8xnn5",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar-8xnn5"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar-8xokr": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar-8xokr",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar-8xokr"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar-8xtjf": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar-8xtjf",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar-8xtjf"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar-8xwnb": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar-8xwnb",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar-8xwnb"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar-8xxdd": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar-8xxdd",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar-8xxdd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar-8xyej": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar-8xyej",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar-8xyej"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar-8xzfl": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar-8xzfl",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar-8xzfl"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar-8y001": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar-8y001",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar-8y001"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar-8y3bf": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar-8y3bf",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar-8y3bf"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar3": {
      "abstract": [
        {
          "text": "A vector of three 8-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uchar3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uchar3"
        }
      ],
      "role": "symbol",
      "title": "simd_uchar3",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar3"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Create-Three-Element-Vectors-From-Vectors-of-Other-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_uchar-8xokr",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar-8xtjf",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar-8y3bf",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar-8xmh3",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar-8xwnb",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar-8xnn5",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar-8xxdd",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar-8xzfl",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar-8y001"
      ],
      "title": "Functions to Create Three-Element Vectors From Vectors of Other Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar3/title",
          "value": "simd_uchar3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar3"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_uchar-8xyej"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
