{
  "abstract": [
    {
      "text": "A vector of sixteen 8-bit signed integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_char16"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@simd_char16",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simd_char16"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_char16"
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "simd_char16"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_char16"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6SIMD16V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6SIMD16V",
              "text": "SIMD16"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5CChara",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5CChara",
              "text": "CChar"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_abs(_:)-475ng": {
      "abstract": [
        {
          "text": "Returns the absolute value of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_abs"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char16",
          "text": "simd_char16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char16",
          "text": "simd_char16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_abs(_:)-475ng",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_abs"
        }
      ],
      "role": "symbol",
      "title": "simd_abs(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_abs(_:)-475ng"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-iajg": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_all"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char16",
          "text": "simd_char16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_bool",
          "text": "simd_bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-iajg",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_all"
        }
      ],
      "role": "symbol",
      "title": "simd_all(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_all(_:)-iajg"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-92tuy": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_any"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char16",
          "text": "simd_char16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_bool",
          "text": "simd_bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-92tuy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_any"
        }
      ],
      "role": "symbol",
      "title": "simd_any(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_any(_:)-92tuy"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-5uq86": {
      "abstract": [
        {
          "text": "Returns a vector that contains elements from either the first or second parameter, based on the corresponding element in the third parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_bitselect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char16",
          "text": "simd_char16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char16",
          "text": "simd_char16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char16",
          "text": "simd_char16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char16",
          "text": "simd_char16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-5uq86",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_bitselect"
        }
      ],
      "role": "symbol",
      "title": "simd_bitselect(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_bitselect(_:_:_:)-5uq86"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char-98c7g": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char-98c7g",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char",
      "type": "topic",
      "url": "/documentation/simd/simd_char-98c7g"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char-98dt4": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char-98dt4",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char",
      "type": "topic",
      "url": "/documentation/simd/simd_char-98dt4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char-98dx0": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char-98dx0",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char",
      "type": "topic",
      "url": "/documentation/simd/simd_char-98dx0"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char-98h4c": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char-98h4c",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char",
      "type": "topic",
      "url": "/documentation/simd/simd_char-98h4c"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char-98lzg": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char-98lzg",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char",
      "type": "topic",
      "url": "/documentation/simd/simd_char-98lzg"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char-98nqs": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char-98nqs",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char",
      "type": "topic",
      "url": "/documentation/simd/simd_char-98nqs"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char-98qy4": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char-98qy4",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char",
      "type": "topic",
      "url": "/documentation/simd/simd_char-98qy4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char1": {
      "abstract": [
        {
          "text": "A vector of one 8-bit signed integer element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_char1"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_char1"
        }
      ],
      "role": "symbol",
      "title": "simd_char1",
      "type": "topic",
      "url": "/documentation/simd/simd_char1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char16": {
      "abstract": [
        {
          "text": "A vector of sixteen 8-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_char16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_char16"
        }
      ],
      "role": "symbol",
      "title": "simd_char16",
      "type": "topic",
      "url": "/documentation/simd/simd_char16"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char2": {
      "abstract": [
        {
          "text": "A vector of two 8-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_char2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_char2"
        }
      ],
      "role": "symbol",
      "title": "simd_char2",
      "type": "topic",
      "url": "/documentation/simd/simd_char2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char3": {
      "abstract": [
        {
          "text": "A vector of three 8-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_char3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_char3"
        }
      ],
      "role": "symbol",
      "title": "simd_char3",
      "type": "topic",
      "url": "/documentation/simd/simd_char3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char32": {
      "abstract": [
        {
          "text": "A vector of thirty-two 8-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_char32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_char32"
        }
      ],
      "role": "symbol",
      "title": "simd_char32",
      "type": "topic",
      "url": "/documentation/simd/simd_char32"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char4": {
      "abstract": [
        {
          "text": "A vector of four 8-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_char4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_char4"
        }
      ],
      "role": "symbol",
      "title": "simd_char4",
      "type": "topic",
      "url": "/documentation/simd/simd_char4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char64": {
      "abstract": [
        {
          "text": "A vector of sixty-four 8-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_char64"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char64",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_char64"
        }
      ],
      "role": "symbol",
      "title": "simd_char64",
      "type": "topic",
      "url": "/documentation/simd/simd_char64"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char8": {
      "abstract": [
        {
          "text": "A vector of eight 8-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_char8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_char8"
        }
      ],
      "role": "symbol",
      "title": "simd_char8",
      "type": "topic",
      "url": "/documentation/simd/simd_char8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char_sat-6mogs": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char_sat-6mogs",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_char_sat-6mogs"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char_sat-6mtcs": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char_sat-6mtcs",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_char_sat-6mtcs"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char_sat-6mwk4": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char_sat-6mwk4",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_char_sat-6mwk4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char_sat-6myfw": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char_sat-6myfw",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_char_sat-6myfw"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char_sat-6n1q0": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char_sat-6n1q0",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_char_sat-6n1q0"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char_sat-6n38c": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char_sat-6n38c",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_char_sat-6n38c"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char_sat-6n6j8": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char_sat-6n6j8",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_char_sat-6n6j8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-509lj": {
      "abstract": [
        {
          "text": "Returns each element in a vector clamped to a specified range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_clamp"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char16",
          "text": "simd_char16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char16",
          "text": "simd_char16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char16",
          "text": "simd_char16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char16",
          "text": "simd_char16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-509lj",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_clamp"
        }
      ],
      "role": "symbol",
      "title": "simd_clamp(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_clamp(_:_:_:)-509lj"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-19z1a": {
      "abstract": [
        {
          "text": "Returns true if every element in a vector is exactly equal to the corresponding element in a second vector, and otherwise returns false.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_equal"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char16",
          "text": "simd_char16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char16",
          "text": "simd_char16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_bool",
          "text": "simd_bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-19z1a",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_equal"
        }
      ],
      "role": "symbol",
      "title": "simd_equal(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_equal(_:_:)-19z1a"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_char16(_:)-2j94t": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified sixty four-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_char16"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char64",
          "text": "simd_char64"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char16",
          "text": "simd_char16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_char16(_:)-2j94t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_char16"
        }
      ],
      "role": "symbol",
      "title": "simd_make_char16(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_char16(_:)-2j94t"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_char16(_:)-4pte6": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified eight-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_char16"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char8",
          "text": "simd_char8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char16",
          "text": "simd_char16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_char16(_:)-4pte6",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_char16"
        }
      ],
      "role": "symbol",
      "title": "simd_make_char16(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_char16(_:)-4pte6"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_char16(_:)-516bc": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_char16"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char16",
          "text": "simd_char16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char16",
          "text": "simd_char16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_char16(_:)-516bc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_char16"
        }
      ],
      "role": "symbol",
      "title": "simd_make_char16(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_char16(_:)-516bc"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_char16(_:)-54urm": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified four-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_char16"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char4",
          "text": "simd_char4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char16",
          "text": "simd_char16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_char16(_:)-54urm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_char16"
        }
      ],
      "role": "symbol",
      "title": "simd_make_char16(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_char16(_:)-54urm"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_char16(_:)-5aqmo": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_char16"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char2",
          "text": "simd_char2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char16",
          "text": "simd_char16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_char16(_:)-5aqmo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_char16"
        }
      ],
      "role": "symbol",
      "title": "simd_make_char16(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_char16(_:)-5aqmo"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_char16(_:)-5e63t": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified three-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_char16"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char3",
          "text": "simd_char3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char16",
          "text": "simd_char16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_char16(_:)-5e63t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_char16"
        }
      ],
      "role": "symbol",
      "title": "simd_make_char16(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_char16(_:)-5e63t"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_char16(_:)-9skzf": {
      "abstract": [
        {
          "text": "Returns a new vector with the first element set to a scalar value, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_char16"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char16",
          "text": "simd_char16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_char16(_:)-9skzf",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_char16"
        }
      ],
      "role": "symbol",
      "title": "simd_make_char16(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_char16(_:)-9skzf"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_char16(_:)-tfq4": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified thirty two-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_char16"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char32",
          "text": "simd_char32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char16",
          "text": "simd_char16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_char16(_:)-tfq4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_char16"
        }
      ],
      "role": "symbol",
      "title": "simd_make_char16(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_char16(_:)-tfq4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_char16(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_char16"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char8",
          "text": "simd_char8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char8",
          "text": "simd_char8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char16",
          "text": "simd_char16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_char16(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_char16"
        }
      ],
      "role": "symbol",
      "title": "simd_make_char16(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_char16(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_char16_undef(_:)-4yci9": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified eight-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_char16_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char8",
          "text": "simd_char8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char16",
          "text": "simd_char16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_char16_undef(_:)-4yci9",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_char16_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_char16_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_char16_undef(_:)-4yci9"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_char16_undef(_:)-5ddf1": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified four-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_char16_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char4",
          "text": "simd_char4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char16",
          "text": "simd_char16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_char16_undef(_:)-5ddf1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_char16_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_char16_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_char16_undef(_:)-5ddf1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_char16_undef(_:)-5gvk6": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified three-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_char16_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char3",
          "text": "simd_char3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char16",
          "text": "simd_char16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_char16_undef(_:)-5gvk6",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_char16_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_char16_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_char16_undef(_:)-5gvk6"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_char16_undef(_:)-5kb1b": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_char16_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char2",
          "text": "simd_char2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char16",
          "text": "simd_char16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_char16_undef(_:)-5kb1b",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_char16_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_char16_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_char16_undef(_:)-5kb1b"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_char16_undef(_:)-9uhre": {
      "abstract": [
        {
          "text": "Returns a new vector with the first element set to a scalar value, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_char16_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char16",
          "text": "simd_char16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_char16_undef(_:)-9uhre",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_char16_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_char16_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_char16_undef(_:)-9uhre"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-2pboz": {
      "abstract": [
        {
          "text": "Returns the maximum value of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_max"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char16",
          "text": "simd_char16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char16",
          "text": "simd_char16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char16",
          "text": "simd_char16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-2pboz",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_max"
        }
      ],
      "role": "symbol",
      "title": "simd_max(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_max(_:_:)-2pboz"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-3t06b": {
      "abstract": [
        {
          "text": "Returns the minimum value of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_min"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char16",
          "text": "simd_char16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char16",
          "text": "simd_char16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char16",
          "text": "simd_char16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-3t06b",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_min"
        }
      ],
      "role": "symbol",
      "title": "simd_min(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_min(_:_:)-3t06b"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-7mtzs": {
      "abstract": [
        {
          "text": "Returns the sum of all elements in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_add"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char16",
          "text": "simd_char16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-7mtzs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_add"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_add(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_add(_:)-7mtzs"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-8idj9": {
      "abstract": [
        {
          "text": "Returns the maximum value in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_max"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char16",
          "text": "simd_char16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-8idj9",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_max"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_max(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_max(_:)-8idj9"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-3crdj": {
      "abstract": [
        {
          "text": "Returns the miniumum value in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_min"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char16",
          "text": "simd_char16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-3crdj",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_min"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_min(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_min(_:)-3crdj"
    },
    "doc://com.apple.accelerate/documentation/simd/vector16-gwvj": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector16-gwvj",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector16",
      "type": "topic",
      "url": "/documentation/simd/vector16-gwvj"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_char16": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vector_char16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_char16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vector_char16"
        }
      ],
      "role": "symbol",
      "title": "vector_char16",
      "type": "topic",
      "url": "/documentation/simd/vector_char16"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s5CChara": {
      "abstract": [
        {
          "text": "The C char type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Int8V",
          "text": "Int8"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5CChara",
      "kind": "symbol",
      "role": "symbol",
      "title": "CChar",
      "type": "topic",
      "url": "/documentation/Swift/CChar"
    },
    "doc://com.externally.resolved.symbol/s:s6SIMD16V": {
      "abstract": [
        {
          "text": "A vector of 16 scalar values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SIMD16"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SIMDScalarP",
          "text": "SIMDScalar"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6SIMD16V",
      "kind": "symbol",
      "role": "symbol",
      "title": "SIMD16",
      "type": "topic",
      "url": "/documentation/Swift/SIMD16"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Vector-Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_char1",
        "doc://com.apple.accelerate/documentation/simd/simd_char2",
        "doc://com.apple.accelerate/documentation/simd/simd_char3",
        "doc://com.apple.accelerate/documentation/simd/simd_char4",
        "doc://com.apple.accelerate/documentation/simd/simd_char8",
        "doc://com.apple.accelerate/documentation/simd/simd_char32",
        "doc://com.apple.accelerate/documentation/simd/simd_char64"
      ],
      "title": "Vector Data Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Functions-to-Create-Sixteen-Element-Vectors-From-Other-Vectors",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_char16(_:)-5aqmo",
        "doc://com.apple.accelerate/documentation/simd/simd_make_char16(_:)-5e63t",
        "doc://com.apple.accelerate/documentation/simd/simd_make_char16(_:)-54urm",
        "doc://com.apple.accelerate/documentation/simd/simd_make_char16(_:)-4pte6",
        "doc://com.apple.accelerate/documentation/simd/simd_make_char16(_:)-516bc",
        "doc://com.apple.accelerate/documentation/simd/simd_make_char16(_:)-tfq4",
        "doc://com.apple.accelerate/documentation/simd/simd_make_char16(_:)-2j94t",
        "doc://com.apple.accelerate/documentation/simd/simd_make_char16(_:_:)",
        "doc://com.apple.accelerate/documentation/simd/simd_make_char16_undef(_:)-5kb1b",
        "doc://com.apple.accelerate/documentation/simd/simd_make_char16_undef(_:)-5gvk6",
        "doc://com.apple.accelerate/documentation/simd/simd_make_char16_undef(_:)-5ddf1",
        "doc://com.apple.accelerate/documentation/simd/simd_make_char16_undef(_:)-4yci9"
      ],
      "title": "Functions to Create Sixteen-Element Vectors From Other Vectors"
    },
    {
      "anchor": "Functions-to-Create-Sixteen-Element-Vectors-From-Scalar-Values",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_char16(_:)-9skzf",
        "doc://com.apple.accelerate/documentation/simd/simd_make_char16_undef(_:)-9uhre"
      ],
      "title": "Functions to Create Sixteen-Element Vectors From Scalar Values"
    },
    {
      "anchor": "Common-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_abs(_:)-475ng",
        "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-509lj",
        "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-19z1a"
      ],
      "title": "Common Functions"
    },
    {
      "anchor": "Reduce-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-3crdj",
        "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-8idj9",
        "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-7mtzs"
      ],
      "title": "Reduce Functions"
    },
    {
      "anchor": "Extrema-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-3t06b",
        "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-2pboz"
      ],
      "title": "Extrema Functions"
    },
    {
      "anchor": "Logic-and-Bitwise-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-92tuy",
        "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-iajg",
        "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-5uq86"
      ],
      "title": "Logic and Bitwise Functions"
    },
    {
      "anchor": "Alternative-Type-Alias",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/vector_char16"
      ],
      "title": "Alternative Type Alias"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "simd_char16"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/simd"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Functions-to-Create-Sixteen-Element-Vectors-From-Other-Vectors",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_char16(_:)-5aqmo",
                "doc://com.apple.accelerate/documentation/simd/simd_make_char16(_:)-5e63t",
                "doc://com.apple.accelerate/documentation/simd/simd_make_char16(_:)-54urm",
                "doc://com.apple.accelerate/documentation/simd/simd_make_char16(_:)-4pte6",
                "doc://com.apple.accelerate/documentation/simd/simd_make_char16(_:)-516bc",
                "doc://com.apple.accelerate/documentation/simd/simd_make_char16(_:)-tfq4",
                "doc://com.apple.accelerate/documentation/simd/simd_make_char16(_:)-2j94t",
                "doc://com.apple.accelerate/documentation/simd/simd_make_char16(_:_:)",
                "doc://com.apple.accelerate/documentation/simd/vector16-gwvj",
                "doc://com.apple.accelerate/documentation/simd/simd_make_char16_undef(_:)-5kb1b",
                "doc://com.apple.accelerate/documentation/simd/simd_make_char16_undef(_:)-5gvk6",
                "doc://com.apple.accelerate/documentation/simd/simd_make_char16_undef(_:)-5ddf1",
                "doc://com.apple.accelerate/documentation/simd/simd_make_char16_undef(_:)-4yci9"
              ],
              "title": "Functions to Create Sixteen-Element Vectors From Other Vectors"
            },
            {
              "anchor": "Functions-to-Create-Sixteen-Element-Vectors-From-Scalar-Values",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_char16(_:)-9skzf",
                "doc://com.apple.accelerate/documentation/simd/simd_make_char16_undef(_:)-9uhre"
              ],
              "title": "Functions to Create Sixteen-Element Vectors From Scalar Values"
            },
            {
              "anchor": "Functions-to-Create-Sixteen-Element-Vectors-From-Vectors-of-Other-Types",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_char-98lzg",
                "doc://com.apple.accelerate/documentation/simd/simd_char-98c7g",
                "doc://com.apple.accelerate/documentation/simd/simd_char-98qy4",
                "doc://com.apple.accelerate/documentation/simd/simd_char-98h4c",
                "doc://com.apple.accelerate/documentation/simd/simd_char-98nqs",
                "doc://com.apple.accelerate/documentation/simd/simd_char-98dx0",
                "doc://com.apple.accelerate/documentation/simd/simd_char-98dt4"
              ],
              "title": "Functions to Create Sixteen-Element Vectors From Vectors of Other Types"
            },
            {
              "anchor": "Functions-to-Perform-Saturating-Conversion-From-Vectors-of-Other-Types",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_char_sat-6mtcs",
                "doc://com.apple.accelerate/documentation/simd/simd_char_sat-6n38c",
                "doc://com.apple.accelerate/documentation/simd/simd_char_sat-6mogs",
                "doc://com.apple.accelerate/documentation/simd/simd_char_sat-6myfw",
                "doc://com.apple.accelerate/documentation/simd/simd_char_sat-6mwk4",
                "doc://com.apple.accelerate/documentation/simd/simd_char_sat-6n6j8",
                "doc://com.apple.accelerate/documentation/simd/simd_char_sat-6n1q0"
              ],
              "title": "Functions to Perform Saturating Conversion From Vectors of Other Types"
            },
            {
              "anchor": "Common-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_abs(_:)-475ng",
                "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-509lj",
                "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-19z1a"
              ],
              "title": "Common Functions"
            },
            {
              "anchor": "Reduce-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-3crdj",
                "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-8idj9",
                "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-7mtzs"
              ],
              "title": "Reduce Functions"
            },
            {
              "anchor": "Extrema-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-3t06b",
                "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-2pboz"
              ],
              "title": "Extrema Functions"
            },
            {
              "anchor": "Logic-and-Bitwise-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-92tuy",
                "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-iajg",
                "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-5uq86"
              ],
              "title": "Logic and Bitwise Functions"
            },
            {
              "anchor": "Alternative-Type-Alias",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/vector_char16"
              ],
              "title": "Alternative Type Alias"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Vector-Data-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_char1",
                "doc://com.apple.accelerate/documentation/simd/simd_char2",
                "doc://com.apple.accelerate/documentation/simd/simd_char3",
                "doc://com.apple.accelerate/documentation/simd/simd_char4",
                "doc://com.apple.accelerate/documentation/simd/simd_char8",
                "doc://com.apple.accelerate/documentation/simd/simd_char32",
                "doc://com.apple.accelerate/documentation/simd/simd_char64"
              ],
              "title": "Vector Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:]16C",
                    "text": "char __attribute__((ext_vector_type(16)))"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "simd_char16"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_all(_:)-iajg/title",
          "value": "simd_all"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_all(_:)-iajg/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_all"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char16(_:)-5e63t/title",
          "value": "simd_make_char16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char16(_:)-5e63t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_char16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char16_undef(_:)-9uhre/title",
          "value": "simd_make_char16_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char16_undef(_:)-9uhre/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_char16_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char16_undef(_:)-4yci9/title",
          "value": "simd_make_char16_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char16_undef(_:)-4yci9/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_char16_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char16(_:)-4pte6/title",
          "value": "simd_make_char16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char16(_:)-4pte6/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_char16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_clamp(_:_:_:)-509lj/title",
          "value": "simd_clamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_clamp(_:_:_:)-509lj/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_clamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_min(_:_:)-3t06b/title",
          "value": "simd_min"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_min(_:_:)-3t06b/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_min"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char8/title",
          "value": "simd_char8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char1/title",
          "value": "simd_char1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char1/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_abs(_:)-475ng/title",
          "value": "simd_abs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_abs(_:)-475ng/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_abs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_equal(_:_:)-19z1a/title",
          "value": "simd_equal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_equal(_:_:)-19z1a/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_equal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char16(_:)-5aqmo/title",
          "value": "simd_make_char16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char16(_:)-5aqmo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_char16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char2/title",
          "value": "simd_char2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_min(_:)-3crdj/title",
          "value": "simd_reduce_min"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_min(_:)-3crdj/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_min"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char16(_:)-tfq4/title",
          "value": "simd_make_char16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char16(_:)-tfq4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_char16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char16_undef(_:)-5ddf1/title",
          "value": "simd_make_char16_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char16_undef(_:)-5ddf1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_char16_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char16(_:_:)/title",
          "value": "simd_make_char16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char16(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_char16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char64/title",
          "value": "simd_char64"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char64/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char64/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char16/title",
          "value": "simd_char16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char16/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char16(_:)-54urm/title",
          "value": "simd_make_char16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char16(_:)-54urm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_char16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char4/title",
          "value": "simd_char4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char16(_:)-516bc/title",
          "value": "simd_make_char16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char16(_:)-516bc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_char16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_bitselect(_:_:_:)-5uq86/title",
          "value": "simd_bitselect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_bitselect(_:_:_:)-5uq86/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_bitselect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1vector_char16/title",
          "value": "vector_char16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1vector_char16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vector_char16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1vector_char16/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vector_char16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char16_undef(_:)-5gvk6/title",
          "value": "simd_make_char16_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char16_undef(_:)-5gvk6/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_char16_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_any(_:)-92tuy/title",
          "value": "simd_any"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_any(_:)-92tuy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_any"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char3/title",
          "value": "simd_char3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char16_undef(_:)-5kb1b/title",
          "value": "simd_make_char16_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char16_undef(_:)-5kb1b/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_char16_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_add(_:)-7mtzs/title",
          "value": "simd_reduce_add"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_add(_:)-7mtzs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_add"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char16(_:)-2j94t/title",
          "value": "simd_make_char16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char16(_:)-2j94t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_char16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_max(_:)-8idj9/title",
          "value": "simd_reduce_max"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_max(_:)-8idj9/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_max"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char32/title",
          "value": "simd_char32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char32/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char16(_:)-9skzf/title",
          "value": "simd_make_char16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char16(_:)-9skzf/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_char16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_max(_:_:)-2pboz/title",
          "value": "simd_max"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_max(_:_:)-2pboz/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_max"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_char16"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/simd/simd_char16"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
