{
  "abstract": [
    {
      "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_uint-7grch"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_uint#]3f#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_uint"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_uint"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_uint"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint3",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_uint3",
              "text": "simd_uint3"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_uint"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float3",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_float3",
              "text": "simd_float3"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float3": {
      "abstract": [
        {
          "text": "A vector of three 32-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_float3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_float3"
        }
      ],
      "role": "symbol",
      "title": "simd_float3",
      "type": "topic",
      "url": "/documentation/simd/simd_float3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint-7gpgp": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uint"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint-7gpgp",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uint",
      "type": "topic",
      "url": "/documentation/simd/simd_uint-7gpgp"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint-7gqav": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uint"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint-7gqav",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uint",
      "type": "topic",
      "url": "/documentation/simd/simd_uint-7gqav"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint-7grch": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uint"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint-7grch",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uint",
      "type": "topic",
      "url": "/documentation/simd/simd_uint-7grch"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint-7grux": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uint"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint-7grux",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uint",
      "type": "topic",
      "url": "/documentation/simd/simd_uint-7grux"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint-7gs6z": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uint"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint-7gs6z",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uint",
      "type": "topic",
      "url": "/documentation/simd/simd_uint-7gs6z"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint-7gxbv": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uint"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint-7gxbv",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uint",
      "type": "topic",
      "url": "/documentation/simd/simd_uint-7gxbv"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint-7gzhl": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uint"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint-7gzhl",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uint",
      "type": "topic",
      "url": "/documentation/simd/simd_uint-7gzhl"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint-7h087": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uint"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint-7h087",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uint",
      "type": "topic",
      "url": "/documentation/simd/simd_uint-7h087"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint-7h2bf": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uint"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint-7h2bf",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uint",
      "type": "topic",
      "url": "/documentation/simd/simd_uint-7h2bf"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint-7h797": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uint"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint-7h797",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uint",
      "type": "topic",
      "url": "/documentation/simd/simd_uint-7h797"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint3": {
      "abstract": [
        {
          "text": "A vector of three 32-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uint3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uint3"
        }
      ],
      "role": "symbol",
      "title": "simd_uint3",
      "type": "topic",
      "url": "/documentation/simd/simd_uint3"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Create-Three-Element-Vectors-From-Vectors-of-Other-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_uint-7h2bf",
        "doc://com.apple.accelerate/documentation/simd/simd_uint-7gs6z",
        "doc://com.apple.accelerate/documentation/simd/simd_uint-7h797",
        "doc://com.apple.accelerate/documentation/simd/simd_uint-7gxbv",
        "doc://com.apple.accelerate/documentation/simd/simd_uint-7h087",
        "doc://com.apple.accelerate/documentation/simd/simd_uint-7gqav",
        "doc://com.apple.accelerate/documentation/simd/simd_uint-7gzhl",
        "doc://com.apple.accelerate/documentation/simd/simd_uint-7gpgp",
        "doc://com.apple.accelerate/documentation/simd/simd_uint-7grux"
      ],
      "title": "Functions to Create Three-Element Vectors From Vectors of Other Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float3/title",
          "value": "simd_float3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint3/title",
          "value": "simd_uint3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uint3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uint3"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_uint-7grch"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
