{
  "abstract": [
    {
      "text": "Returns a new vector from the specified vector.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3(_:)-57xdw"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_make_ulong3#]3l#",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simd_make_ulong3"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_ulong3",
        "text": "simd_ulong3"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_ulong3",
        "text": "simd_ulong3"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_make_ulong3"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_make_ulong3(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_make_ulong3"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "other"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong3",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_ulong3",
              "text": "simd_ulong3"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong3",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_ulong3",
              "text": "simd_ulong3"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3(_:)-4pyq9": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified eight-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ulong3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong8",
          "text": "simd_ulong8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong3",
          "text": "simd_ulong3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3(_:)-4pyq9",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ulong3"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ulong3(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ulong3(_:)-4pyq9"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3(_:)-57xdw": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ulong3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong3",
          "text": "simd_ulong3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong3",
          "text": "simd_ulong3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3(_:)-57xdw",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ulong3"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ulong3(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ulong3(_:)-57xdw"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3(_:)-5autj": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ulong3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong2",
          "text": "simd_ulong2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong3",
          "text": "simd_ulong3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3(_:)-5autj",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ulong3"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ulong3(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ulong3(_:)-5autj"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3(_:)-5w7y5": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified four-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ulong3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong4",
          "text": "simd_ulong4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong3",
          "text": "simd_ulong3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3(_:)-5w7y5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ulong3"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ulong3(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ulong3(_:)-5w7y5"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3_undef(_:)-5oqlt": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ulong3_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong2",
          "text": "simd_ulong2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong3",
          "text": "simd_ulong3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3_undef(_:)-5oqlt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ulong3_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ulong3_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ulong3_undef(_:)-5oqlt"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong3": {
      "abstract": [
        {
          "text": "A vector of three 64-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ulong3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ulong3"
        }
      ],
      "role": "symbol",
      "title": "simd_ulong3",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong3"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Create-Three-Element-Vectors-From-Other-Vectors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3(_:)-5autj",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3(_:)-5w7y5",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3(_:)-4pyq9",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3_undef(_:)-5oqlt"
      ],
      "title": "Functions to Create Three-Element Vectors From Other Vectors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "simd_make_ulong3"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ulong3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/simd"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Functions-to-Create-Three-Element-Vectors-From-Other-Vectors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3(_:)-5autj",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3(_:)-5w7y5",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3(_:)-4pyq9",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3_undef(_:)-5oqlt"
              ],
              "title": "Functions to Create Three-Element Vectors From Other Vectors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "static"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong3",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_ulong3",
                    "text": "simd_ulong3"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "simd_make_ulong3"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong3",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_ulong3",
                    "text": "simd_ulong3"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "other"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong3_undef(_:)-5oqlt/title",
          "value": "simd_make_ulong3_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong3_undef(_:)-5oqlt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ulong3_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong3(_:)-5w7y5/title",
          "value": "simd_make_ulong3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong3(_:)-5w7y5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ulong3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong3(_:)-5autj/title",
          "value": "simd_make_ulong3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong3(_:)-5autj/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ulong3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong3(_:)-57xdw/title",
          "value": "simd_make_ulong3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong3(_:)-57xdw/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ulong3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong3/title",
          "value": "simd_ulong3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong3(_:)-4pyq9/title",
          "value": "simd_make_ulong3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong3(_:)-4pyq9/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ulong3"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_make_ulong3(_:)-57xdw"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/simd/simd_make_ulong3(_:)-57xdw"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
