{
  "abstract": [
    {
      "text": "Returns the fast reciprocal square root of each element in a vector.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_fast_rsqrt(_:)-84ema"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_fast_rsqrt#]2h#",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simd_fast_rsqrt"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_half2",
        "text": "simd_half2"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_half2",
        "text": "simd_half2"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_fast_rsqrt"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_fast_rsqrt(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_fast_rsqrt"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "x"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_half2",
              "text": "simd_half2"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_half2",
              "text": "simd_half2"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_fast_recip(_:)-ln7x": {
      "abstract": [
        {
          "text": "Returns the fast reciprocal of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_fast_recip"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half2",
          "text": "simd_half2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half2",
          "text": "simd_half2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_fast_recip(_:)-ln7x",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_fast_recip"
        }
      ],
      "role": "symbol",
      "title": "simd_fast_recip(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_fast_recip(_:)-ln7x"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_fast_rsqrt(_:)-84ema": {
      "abstract": [
        {
          "text": "Returns the fast reciprocal square root of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_fast_rsqrt"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half2",
          "text": "simd_half2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half2",
          "text": "simd_half2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_fast_rsqrt(_:)-84ema",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_fast_rsqrt"
        }
      ],
      "role": "symbol",
      "title": "simd_fast_rsqrt(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_fast_rsqrt(_:)-84ema"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half2": {
      "abstract": [
        {
          "text": "A vector of two 16-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_half2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_half2"
        }
      ],
      "role": "symbol",
      "title": "simd_half2",
      "type": "topic",
      "url": "/documentation/simd/simd_half2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_precise_recip(_:)-66ohg": {
      "abstract": [
        {
          "text": "Returns the precise reciprocal of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_precise_recip"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half2",
          "text": "simd_half2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half2",
          "text": "simd_half2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_precise_recip(_:)-66ohg",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_precise_recip"
        }
      ],
      "role": "symbol",
      "title": "simd_precise_recip(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_precise_recip(_:)-66ohg"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_precise_rsqrt(_:)-wvby": {
      "abstract": [
        {
          "text": "Returns the precise reciprocal square root of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_precise_rsqrt"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half2",
          "text": "simd_half2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half2",
          "text": "simd_half2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_precise_rsqrt(_:)-wvby",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_precise_rsqrt"
        }
      ],
      "role": "symbol",
      "title": "simd_precise_rsqrt(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_precise_rsqrt(_:)-wvby"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_recip(_:)-8ni98": {
      "abstract": [
        {
          "text": "Returns the reciprocal of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_recip"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half2",
          "text": "simd_half2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half2",
          "text": "simd_half2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_recip(_:)-8ni98",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_recip"
        }
      ],
      "role": "symbol",
      "title": "simd_recip(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_recip(_:)-8ni98"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_rsqrt(_:)-oj14": {
      "abstract": [
        {
          "text": "Returns the reciprocal square root of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_rsqrt"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half2",
          "text": "simd_half2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half2",
          "text": "simd_half2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_rsqrt(_:)-oj14",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_rsqrt"
        }
      ],
      "role": "symbol",
      "title": "simd_rsqrt(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_rsqrt(_:)-oj14"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reciprocal-and-reciprocal-square-root-functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_recip(_:)-8ni98",
        "doc://com.apple.accelerate/documentation/simd/simd_rsqrt(_:)-oj14",
        "doc://com.apple.accelerate/documentation/simd/simd_precise_recip(_:)-66ohg",
        "doc://com.apple.accelerate/documentation/simd/simd_precise_rsqrt(_:)-wvby",
        "doc://com.apple.accelerate/documentation/simd/simd_fast_recip(_:)-ln7x"
      ],
      "title": "Reciprocal and reciprocal square root functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "simd_fast_rsqrt"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_fast_rsqrt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/simd"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reciprocal-and-reciprocal-square-root-functions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_recip(_:)-8ni98",
                "doc://com.apple.accelerate/documentation/simd/simd_rsqrt(_:)-oj14",
                "doc://com.apple.accelerate/documentation/simd/simd_precise_recip(_:)-66ohg",
                "doc://com.apple.accelerate/documentation/simd/simd_precise_rsqrt(_:)-wvby",
                "doc://com.apple.accelerate/documentation/simd/simd_fast_recip(_:)-ln7x"
              ],
              "title": "Reciprocal and reciprocal square root functions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "static"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half2",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_half2",
                    "text": "simd_half2"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "simd_fast_rsqrt"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half2",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_half2",
                    "text": "simd_half2"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "x"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_rsqrt(_:)-oj14/title",
          "value": "simd_rsqrt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_rsqrt(_:)-oj14/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_rsqrt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half2/title",
          "value": "simd_half2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_fast_recip(_:)-ln7x/title",
          "value": "simd_fast_recip"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_fast_recip(_:)-ln7x/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_fast_recip"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_recip(_:)-8ni98/title",
          "value": "simd_recip"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_recip(_:)-8ni98/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_recip"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_precise_rsqrt(_:)-wvby/title",
          "value": "simd_precise_rsqrt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_precise_rsqrt(_:)-wvby/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_precise_rsqrt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_precise_recip(_:)-66ohg/title",
          "value": "simd_precise_recip"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_precise_recip(_:)-66ohg/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_precise_recip"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_fast_rsqrt(_:)-84ema/title",
          "value": "simd_fast_rsqrt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_fast_rsqrt(_:)-84ema/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_fast_rsqrt"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_fast_rsqrt(_:)-84ema"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/simd/simd_fast_rsqrt(_:)-84ema"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
