{
  "abstract": [
    {
      "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_int-9gib6"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_int#]4C#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_int"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_int"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_int"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int4",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_int4",
              "text": "simd_int4"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_int"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char4",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_char4",
              "text": "simd_char4"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char4": {
      "abstract": [
        {
          "text": "A vector of four 8-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_char4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_char4"
        }
      ],
      "role": "symbol",
      "title": "simd_char4",
      "type": "topic",
      "url": "/documentation/simd/simd_char4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int-9gf7q": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int-9gf7q",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int",
      "type": "topic",
      "url": "/documentation/simd/simd_int-9gf7q"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int-9ggra": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int-9ggra",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int",
      "type": "topic",
      "url": "/documentation/simd/simd_int-9ggra"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int-9gib6": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int-9gib6",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int",
      "type": "topic",
      "url": "/documentation/simd/simd_int-9gib6"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int-9gnaq": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int-9gnaq",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int",
      "type": "topic",
      "url": "/documentation/simd/simd_int-9gnaq"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int-9gp3a": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int-9gp3a",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int",
      "type": "topic",
      "url": "/documentation/simd/simd_int-9gp3a"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int-9gqqe": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int-9gqqe",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int",
      "type": "topic",
      "url": "/documentation/simd/simd_int-9gqqe"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int-9gsc2": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int-9gsc2",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int",
      "type": "topic",
      "url": "/documentation/simd/simd_int-9gsc2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int-9gt5y": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int-9gt5y",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int",
      "type": "topic",
      "url": "/documentation/simd/simd_int-9gt5y"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int-9gtqi": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int-9gtqi",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int",
      "type": "topic",
      "url": "/documentation/simd/simd_int-9gtqi"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int-9gx82": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int-9gx82",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int",
      "type": "topic",
      "url": "/documentation/simd/simd_int-9gx82"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int4": {
      "abstract": [
        {
          "text": "A vector of four 32-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_int4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_int4"
        }
      ],
      "role": "symbol",
      "title": "simd_int4",
      "type": "topic",
      "url": "/documentation/simd/simd_int4"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Create-Four-Element-Vectors-From-Vectors-of-Other-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_int-9gsc2",
        "doc://com.apple.accelerate/documentation/simd/simd_int-9gnaq",
        "doc://com.apple.accelerate/documentation/simd/simd_int-9gx82",
        "doc://com.apple.accelerate/documentation/simd/simd_int-9gf7q",
        "doc://com.apple.accelerate/documentation/simd/simd_int-9gp3a",
        "doc://com.apple.accelerate/documentation/simd/simd_int-9ggra",
        "doc://com.apple.accelerate/documentation/simd/simd_int-9gqqe",
        "doc://com.apple.accelerate/documentation/simd/simd_int-9gtqi",
        "doc://com.apple.accelerate/documentation/simd/simd_int-9gt5y"
      ],
      "title": "Functions to Create Four-Element Vectors From Vectors of Other Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char4/title",
          "value": "simd_char4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int4/title",
          "value": "simd_int4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_int4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_int4"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_int-9gib6"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
