{
  "abstract": [
    {
      "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-18wbe"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_uchar_sat#]8S#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_uchar_sat"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_uchar_sat"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_uchar_sat"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar8",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_uchar8",
              "text": "simd_uchar8"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_uchar_sat"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short8",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_short8",
              "text": "simd_short8"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short8": {
      "abstract": [
        {
          "text": "A vector of eight 16-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_short8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_short8"
        }
      ],
      "role": "symbol",
      "title": "simd_short8",
      "type": "topic",
      "url": "/documentation/simd/simd_short8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar8": {
      "abstract": [
        {
          "text": "A vector of eight 8-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uchar8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uchar8"
        }
      ],
      "role": "symbol",
      "title": "simd_uchar8",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-18rfe": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-18rfe",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar_sat-18rfe"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-18svq": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-18svq",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar_sat-18svq"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-18ufi": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-18ufi",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar_sat-18ufi"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-18wbe": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-18wbe",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar_sat-18wbe"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-18zuq": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-18zuq",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar_sat-18zuq"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-190iu": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-190iu",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar_sat-190iu"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1917e": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1917e",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar_sat-1917e"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-192t2": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-192t2",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar_sat-192t2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-194b2": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-194b2",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar_sat-194b2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-196e2": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_uchar_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-196e2",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_uchar_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar_sat-196e2"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Perform-Saturating-Conversion-From-Vectors-of-Other-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-18rfe",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-1917e",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-196e2",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-18ufi",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-194b2",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-18svq",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-192t2",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-18zuq",
        "doc://com.apple.accelerate/documentation/simd/simd_uchar_sat-190iu"
      ],
      "title": "Functions to Perform Saturating Conversion From Vectors of Other Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar8/title",
          "value": "simd_uchar8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short8/title",
          "value": "simd_short8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short8"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_uchar_sat-18wbe"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
