{
  "abstract": [
    {
      "text": "Returns a new vector from the specified four-element vector, and other elements undefined.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort16_undef(_:)-bxgi"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_make_ushort16_undef#]4s#",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simd_make_ushort16_undef"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_ushort4",
        "text": "simd_ushort4"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_ushort16",
        "text": "simd_ushort16"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_make_ushort16_undef"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_make_ushort16_undef(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_make_ushort16_undef"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "other"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort4",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_ushort4",
              "text": "simd_ushort4"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort16",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_ushort16",
              "text": "simd_ushort16"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort16(_:)-43b0g": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort16"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort16",
          "text": "simd_ushort16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort16",
          "text": "simd_ushort16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort16(_:)-43b0g",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort16"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort16(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort16(_:)-43b0g"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort16(_:)-4h3f4": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified eight-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort16"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort8",
          "text": "simd_ushort8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort16",
          "text": "simd_ushort16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort16(_:)-4h3f4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort16"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort16(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort16(_:)-4h3f4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort16(_:)-4vumc": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified four-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort16"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort4",
          "text": "simd_ushort4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort16",
          "text": "simd_ushort16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort16(_:)-4vumc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort16"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort16(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort16(_:)-4vumc"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort16(_:)-5dtrr": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified three-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort16"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort3",
          "text": "simd_ushort3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort16",
          "text": "simd_ushort16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort16(_:)-5dtrr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort16"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort16(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort16(_:)-5dtrr"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort16(_:)-5h1oe": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort16"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort2",
          "text": "simd_ushort2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort16",
          "text": "simd_ushort16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort16(_:)-5h1oe",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort16"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort16(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort16(_:)-5h1oe"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort16(_:)-5wstb": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified thirty two-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort16"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort32",
          "text": "simd_ushort32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort16",
          "text": "simd_ushort16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort16(_:)-5wstb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort16"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort16(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort16(_:)-5wstb"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort16(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort16"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort8",
          "text": "simd_ushort8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort8",
          "text": "simd_ushort8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort16",
          "text": "simd_ushort16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort16(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort16"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort16(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort16(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort16_undef(_:)-3jyo": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort16_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort2",
          "text": "simd_ushort2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort16",
          "text": "simd_ushort16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort16_undef(_:)-3jyo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort16_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort16_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort16_undef(_:)-3jyo"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort16_undef(_:)-8phl": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified three-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort16_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort3",
          "text": "simd_ushort3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort16",
          "text": "simd_ushort16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort16_undef(_:)-8phl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort16_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort16_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort16_undef(_:)-8phl"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort16_undef(_:)-957cx": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified eight-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort16_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort8",
          "text": "simd_ushort8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort16",
          "text": "simd_ushort16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort16_undef(_:)-957cx",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort16_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort16_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort16_undef(_:)-957cx"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ushort16_undef(_:)-bxgi": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified four-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ushort16_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort4",
          "text": "simd_ushort4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ushort16",
          "text": "simd_ushort16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ushort16_undef(_:)-bxgi",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ushort16_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ushort16_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ushort16_undef(_:)-bxgi"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort16": {
      "abstract": [
        {
          "text": "A vector of sixteen 16-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ushort16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ushort16"
        }
      ],
      "role": "symbol",
      "title": "simd_ushort16",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort16"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort4": {
      "abstract": [
        {
          "text": "A vector of four 16-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ushort4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ushort4"
        }
      ],
      "role": "symbol",
      "title": "simd_ushort4",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort4"
    },
    "doc://com.apple.accelerate/documentation/simd/vector16-4zacu": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector16-4zacu",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector16",
      "type": "topic",
      "url": "/documentation/simd/vector16-4zacu"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Create-Sixteen-Element-Vectors-From-Other-Vectors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_ushort16(_:)-5h1oe",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ushort16(_:)-5dtrr",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ushort16(_:)-4vumc",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ushort16(_:)-4h3f4",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ushort16(_:)-43b0g",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ushort16(_:)-5wstb",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ushort16(_:_:)",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ushort16_undef(_:)-3jyo",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ushort16_undef(_:)-8phl",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ushort16_undef(_:)-957cx"
      ],
      "title": "Functions to Create Sixteen-Element Vectors From Other Vectors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "simd_make_ushort16_undef"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort16_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/simd"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Functions-to-Create-Sixteen-Element-Vectors-From-Other-Vectors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_ushort16(_:)-5h1oe",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ushort16(_:)-5dtrr",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ushort16(_:)-4vumc",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ushort16(_:)-4h3f4",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ushort16(_:)-43b0g",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ushort16(_:)-5wstb",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ushort16(_:_:)",
                "doc://com.apple.accelerate/documentation/simd/vector16-4zacu",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ushort16_undef(_:)-3jyo",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ushort16_undef(_:)-8phl",
                "doc://com.apple.accelerate/documentation/simd/simd_make_ushort16_undef(_:)-957cx"
              ],
              "title": "Functions to Create Sixteen-Element Vectors From Other Vectors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "static"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort16",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_ushort16",
                    "text": "simd_ushort16"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "simd_make_ushort16_undef"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort4",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_ushort4",
                    "text": "simd_ushort4"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "other"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort16_undef(_:)-8phl/title",
          "value": "simd_make_ushort16_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort16_undef(_:)-8phl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort16_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort16_undef(_:)-957cx/title",
          "value": "simd_make_ushort16_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort16_undef(_:)-957cx/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort16_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort16(_:_:)/title",
          "value": "simd_make_ushort16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort16(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort16(_:)-4vumc/title",
          "value": "simd_make_ushort16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort16(_:)-4vumc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort16(_:)-4h3f4/title",
          "value": "simd_make_ushort16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort16(_:)-4h3f4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort16/title",
          "value": "simd_ushort16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort16/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort16(_:)-43b0g/title",
          "value": "simd_make_ushort16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort16(_:)-43b0g/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort16(_:)-5wstb/title",
          "value": "simd_make_ushort16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort16(_:)-5wstb/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort16(_:)-5h1oe/title",
          "value": "simd_make_ushort16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort16(_:)-5h1oe/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort16_undef(_:)-bxgi/title",
          "value": "simd_make_ushort16_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort16_undef(_:)-bxgi/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort16_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort16(_:)-5dtrr/title",
          "value": "simd_make_ushort16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort16(_:)-5dtrr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort16_undef(_:)-3jyo/title",
          "value": "simd_make_ushort16_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ushort16_undef(_:)-3jyo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ushort16_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort4/title",
          "value": "simd_ushort4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort4"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_make_ushort16_undef(_:)-bxgi"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/simd/simd_make_ushort16_undef(_:)-bxgi"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
