{
  "abstract": [
    {
      "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1kdj1"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_char_sat#]8d#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_char_sat"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_char_sat"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_char_sat"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char8",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_char8",
              "text": "simd_char8"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_char_sat"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double8",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_double8",
              "text": "simd_double8"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char8": {
      "abstract": [
        {
          "text": "A vector of eight 8-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_char8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_char8"
        }
      ],
      "role": "symbol",
      "title": "simd_char8",
      "type": "topic",
      "url": "/documentation/simd/simd_char8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1jyvr": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1jyvr",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_char_sat-1jyvr"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1k125": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1k125",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_char_sat-1k125"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1k1zv": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1k1zv",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_char_sat-1k1zv"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1k3vb": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1k3vb",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_char_sat-1k3vb"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1k8uv": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1k8uv",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_char_sat-1k8uv"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1kb19": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1kb19",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_char_sat-1kb19"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1kbyz": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1kbyz",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_char_sat-1kbyz"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1kcv9": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1kcv9",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_char_sat-1kcv9"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1kdj1": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1kdj1",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_char_sat-1kdj1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1kdqv": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1kdqv",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_char_sat-1kdqv"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double8": {
      "abstract": [
        {
          "text": "A vector of eight 64-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_double8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_double8"
        }
      ],
      "role": "symbol",
      "title": "simd_double8",
      "type": "topic",
      "url": "/documentation/simd/simd_double8"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Perform-Saturating-Conversion-From-Vectors-of-Other-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1k3vb",
        "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1kdqv",
        "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1jyvr",
        "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1k8uv",
        "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1k1zv",
        "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1kbyz",
        "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1k125",
        "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1kb19",
        "doc://com.apple.accelerate/documentation/simd/simd_char_sat-1kcv9"
      ],
      "title": "Functions to Perform Saturating Conversion From Vectors of Other Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double8/title",
          "value": "simd_double8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char8/title",
          "value": "simd_char8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char8"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_char_sat-1kdj1"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
