{
  "abstract": [
    {
      "text": "A vector of thirty-two 8-bit signed integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_char32"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@simd_char32",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simd_char32"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_char32"
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "simd_char32"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_char32"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6SIMD32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6SIMD32V",
              "text": "SIMD32"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5CChara",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5CChara",
              "text": "CChar"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_abs(_:)-2ca9r": {
      "abstract": [
        {
          "text": "Returns the absolute value of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_abs"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char32",
          "text": "simd_char32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char32",
          "text": "simd_char32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_abs(_:)-2ca9r",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_abs"
        }
      ],
      "role": "symbol",
      "title": "simd_abs(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_abs(_:)-2ca9r"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1k7jn": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_all"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char32",
          "text": "simd_char32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_bool",
          "text": "simd_bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1k7jn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_all"
        }
      ],
      "role": "symbol",
      "title": "simd_all(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_all(_:)-1k7jn"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-3az4l": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_any"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char32",
          "text": "simd_char32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_bool",
          "text": "simd_bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-3az4l",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_any"
        }
      ],
      "role": "symbol",
      "title": "simd_any(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_any(_:)-3az4l"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-2da13": {
      "abstract": [
        {
          "text": "Returns a vector that contains elements from either the first or second parameter, based on the corresponding element in the third parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_bitselect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char32",
          "text": "simd_char32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char32",
          "text": "simd_char32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char32",
          "text": "simd_char32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char32",
          "text": "simd_char32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-2da13",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_bitselect"
        }
      ],
      "role": "symbol",
      "title": "simd_bitselect(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_bitselect(_:_:_:)-2da13"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char-50vc0": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char-50vc0",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char",
      "type": "topic",
      "url": "/documentation/simd/simd_char-50vc0"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char-51074": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char-51074",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char",
      "type": "topic",
      "url": "/documentation/simd/simd_char-51074"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char-5159c": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char-5159c",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char",
      "type": "topic",
      "url": "/documentation/simd/simd_char-5159c"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char-51a68": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char-51a68",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char",
      "type": "topic",
      "url": "/documentation/simd/simd_char-51a68"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char1": {
      "abstract": [
        {
          "text": "A vector of one 8-bit signed integer element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_char1"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_char1"
        }
      ],
      "role": "symbol",
      "title": "simd_char1",
      "type": "topic",
      "url": "/documentation/simd/simd_char1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char16": {
      "abstract": [
        {
          "text": "A vector of sixteen 8-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_char16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_char16"
        }
      ],
      "role": "symbol",
      "title": "simd_char16",
      "type": "topic",
      "url": "/documentation/simd/simd_char16"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char2": {
      "abstract": [
        {
          "text": "A vector of two 8-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_char2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_char2"
        }
      ],
      "role": "symbol",
      "title": "simd_char2",
      "type": "topic",
      "url": "/documentation/simd/simd_char2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char3": {
      "abstract": [
        {
          "text": "A vector of three 8-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_char3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_char3"
        }
      ],
      "role": "symbol",
      "title": "simd_char3",
      "type": "topic",
      "url": "/documentation/simd/simd_char3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char32": {
      "abstract": [
        {
          "text": "A vector of thirty-two 8-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_char32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_char32"
        }
      ],
      "role": "symbol",
      "title": "simd_char32",
      "type": "topic",
      "url": "/documentation/simd/simd_char32"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char4": {
      "abstract": [
        {
          "text": "A vector of four 8-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_char4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_char4"
        }
      ],
      "role": "symbol",
      "title": "simd_char4",
      "type": "topic",
      "url": "/documentation/simd/simd_char4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char64": {
      "abstract": [
        {
          "text": "A vector of sixty-four 8-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_char64"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char64",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_char64"
        }
      ],
      "role": "symbol",
      "title": "simd_char64",
      "type": "topic",
      "url": "/documentation/simd/simd_char64"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char8": {
      "abstract": [
        {
          "text": "A vector of eight 8-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_char8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_char8"
        }
      ],
      "role": "symbol",
      "title": "simd_char8",
      "type": "topic",
      "url": "/documentation/simd/simd_char8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char_sat-uov5": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char_sat-uov5",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_char_sat-uov5"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char_sat-utq9": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char_sat-utq9",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_char_sat-utq9"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char_sat-uyox": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char_sat-uyox",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_char_sat-uyox"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char_sat-v3lt": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char_sat-v3lt",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_char_sat-v3lt"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-2eiom": {
      "abstract": [
        {
          "text": "Returns each element in a vector clamped to a specified range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_clamp"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char32",
          "text": "simd_char32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char32",
          "text": "simd_char32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char32",
          "text": "simd_char32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char32",
          "text": "simd_char32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-2eiom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_clamp"
        }
      ],
      "role": "symbol",
      "title": "simd_clamp(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_clamp(_:_:_:)-2eiom"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-2iweh": {
      "abstract": [
        {
          "text": "Returns true if every element in a vector is exactly equal to the corresponding element in a second vector, and otherwise returns false.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_equal"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char32",
          "text": "simd_char32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char32",
          "text": "simd_char32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_bool",
          "text": "simd_bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-2iweh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_equal"
        }
      ],
      "role": "symbol",
      "title": "simd_equal(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_equal(_:_:)-2iweh"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_char32(_:)-20u7n": {
      "abstract": [
        {
          "text": "Returns a new vector with the first element set to a scalar value, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_char32"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char32",
          "text": "simd_char32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_char32(_:)-20u7n",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_char32"
        }
      ],
      "role": "symbol",
      "title": "simd_make_char32(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_char32(_:)-20u7n"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_char32(_:)-2ag5j": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified eight-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_char32"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char8",
          "text": "simd_char8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char32",
          "text": "simd_char32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_char32(_:)-2ag5j",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_char32"
        }
      ],
      "role": "symbol",
      "title": "simd_make_char32(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_char32(_:)-2ag5j"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_char32(_:)-2n9wz": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified four-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_char32"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char4",
          "text": "simd_char4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char32",
          "text": "simd_char32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_char32(_:)-2n9wz",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_char32"
        }
      ],
      "role": "symbol",
      "title": "simd_make_char32(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_char32(_:)-2n9wz"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_char32(_:)-384hl": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_char32"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char2",
          "text": "simd_char2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char32",
          "text": "simd_char32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_char32(_:)-384hl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_char32"
        }
      ],
      "role": "symbol",
      "title": "simd_make_char32(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_char32(_:)-384hl"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_char32(_:)-3bm80": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified three-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_char32"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char3",
          "text": "simd_char3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char32",
          "text": "simd_char32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_char32(_:)-3bm80",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_char32"
        }
      ],
      "role": "symbol",
      "title": "simd_make_char32(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_char32(_:)-3bm80"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_char32(_:)-3g5k3": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified sixteen-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_char32"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char16",
          "text": "simd_char16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char32",
          "text": "simd_char32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_char32(_:)-3g5k3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_char32"
        }
      ],
      "role": "symbol",
      "title": "simd_make_char32(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_char32(_:)-3g5k3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_char32(_:)-6kn8l": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified sixty four-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_char32"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char64",
          "text": "simd_char64"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char32",
          "text": "simd_char32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_char32(_:)-6kn8l",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_char32"
        }
      ],
      "role": "symbol",
      "title": "simd_make_char32(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_char32(_:)-6kn8l"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_char32(_:)-8fqzf": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_char32"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char32",
          "text": "simd_char32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char32",
          "text": "simd_char32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_char32(_:)-8fqzf",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_char32"
        }
      ],
      "role": "symbol",
      "title": "simd_make_char32(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_char32(_:)-8fqzf"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_char32(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_char32"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char16",
          "text": "simd_char16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char16",
          "text": "simd_char16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char32",
          "text": "simd_char32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_char32(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_char32"
        }
      ],
      "role": "symbol",
      "title": "simd_make_char32(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_char32(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_char32_undef(_:)-3vq4m": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified sixteen-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_char32_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char16",
          "text": "simd_char16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char32",
          "text": "simd_char32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_char32_undef(_:)-3vq4m",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_char32_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_char32_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_char32_undef(_:)-3vq4m"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_char32_undef(_:)-6t8l5": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified eight-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_char32_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char8",
          "text": "simd_char8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char32",
          "text": "simd_char32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_char32_undef(_:)-6t8l5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_char32_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_char32_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_char32_undef(_:)-6t8l5"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_char32_undef(_:)-7poo6": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified three-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_char32_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char3",
          "text": "simd_char3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char32",
          "text": "simd_char32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_char32_undef(_:)-7poo6",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_char32_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_char32_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_char32_undef(_:)-7poo6"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_char32_undef(_:)-7t6qn": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_char32_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char2",
          "text": "simd_char2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char32",
          "text": "simd_char32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_char32_undef(_:)-7t6qn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_char32_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_char32_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_char32_undef(_:)-7t6qn"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_char32_undef(_:)-7z0ct": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified four-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_char32_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char4",
          "text": "simd_char4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char32",
          "text": "simd_char32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_char32_undef(_:)-7z0ct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_char32_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_char32_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_char32_undef(_:)-7z0ct"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_char32_undef(_:)-9nqa9": {
      "abstract": [
        {
          "text": "Returns a new vector with the first element set to a scalar value, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_char32_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char32",
          "text": "simd_char32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_char32_undef(_:)-9nqa9",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_char32_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_char32_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_char32_undef(_:)-9nqa9"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-9ec8n": {
      "abstract": [
        {
          "text": "Returns the maximum value of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_max"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char32",
          "text": "simd_char32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char32",
          "text": "simd_char32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char32",
          "text": "simd_char32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-9ec8n",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_max"
        }
      ],
      "role": "symbol",
      "title": "simd_max(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_max(_:_:)-9ec8n"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-2isjs": {
      "abstract": [
        {
          "text": "Returns the minimum value of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_min"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char32",
          "text": "simd_char32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char32",
          "text": "simd_char32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char32",
          "text": "simd_char32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-2isjs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_min"
        }
      ],
      "role": "symbol",
      "title": "simd_min(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_min(_:_:)-2isjs"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-1uzk7": {
      "abstract": [
        {
          "text": "Returns the sum of all elements in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_add"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char32",
          "text": "simd_char32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-1uzk7",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_add"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_add(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_add(_:)-1uzk7"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-9j748": {
      "abstract": [
        {
          "text": "Returns the maximum value in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_max"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char32",
          "text": "simd_char32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-9j748",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_max"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_max(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_max(_:)-9j748"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-2au68": {
      "abstract": [
        {
          "text": "Returns the miniumum value in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_min"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_char32",
          "text": "simd_char32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-2au68",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_min"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_min(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_min(_:)-2au68"
    },
    "doc://com.apple.accelerate/documentation/simd/vector32-6853f": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector32-6853f",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector32",
      "type": "topic",
      "url": "/documentation/simd/vector32-6853f"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_char32": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vector_char32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_char32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vector_char32"
        }
      ],
      "role": "symbol",
      "title": "vector_char32",
      "type": "topic",
      "url": "/documentation/simd/vector_char32"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s5CChara": {
      "abstract": [
        {
          "text": "The C char type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Int8V",
          "text": "Int8"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5CChara",
      "kind": "symbol",
      "role": "symbol",
      "title": "CChar",
      "type": "topic",
      "url": "/documentation/Swift/CChar"
    },
    "doc://com.externally.resolved.symbol/s:s6SIMD32V": {
      "abstract": [
        {
          "text": "A vector of 32 scalar values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SIMD32"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SIMDScalarP",
          "text": "SIMDScalar"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6SIMD32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "SIMD32",
      "type": "topic",
      "url": "/documentation/Swift/SIMD32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Vector-Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_char1",
        "doc://com.apple.accelerate/documentation/simd/simd_char2",
        "doc://com.apple.accelerate/documentation/simd/simd_char3",
        "doc://com.apple.accelerate/documentation/simd/simd_char4",
        "doc://com.apple.accelerate/documentation/simd/simd_char8",
        "doc://com.apple.accelerate/documentation/simd/simd_char16",
        "doc://com.apple.accelerate/documentation/simd/simd_char64"
      ],
      "title": "Vector Data Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Functions-to-Create-Thirty-Two-Element-Vectors-From-Other-Vectors",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_char32(_:)-384hl",
        "doc://com.apple.accelerate/documentation/simd/simd_make_char32(_:)-3bm80",
        "doc://com.apple.accelerate/documentation/simd/simd_make_char32(_:)-2n9wz",
        "doc://com.apple.accelerate/documentation/simd/simd_make_char32(_:)-2ag5j",
        "doc://com.apple.accelerate/documentation/simd/simd_make_char32(_:)-3g5k3",
        "doc://com.apple.accelerate/documentation/simd/simd_make_char32(_:)-8fqzf",
        "doc://com.apple.accelerate/documentation/simd/simd_make_char32(_:)-6kn8l",
        "doc://com.apple.accelerate/documentation/simd/simd_make_char32(_:_:)",
        "doc://com.apple.accelerate/documentation/simd/simd_make_char32_undef(_:)-7t6qn",
        "doc://com.apple.accelerate/documentation/simd/simd_make_char32_undef(_:)-7poo6",
        "doc://com.apple.accelerate/documentation/simd/simd_make_char32_undef(_:)-7z0ct",
        "doc://com.apple.accelerate/documentation/simd/simd_make_char32_undef(_:)-6t8l5",
        "doc://com.apple.accelerate/documentation/simd/simd_make_char32_undef(_:)-3vq4m"
      ],
      "title": "Functions to Create Thirty Two-Element Vectors From Other Vectors"
    },
    {
      "anchor": "Functions-to-Create-Thirty-Two-Element-Vectors-From-Scalar-Values",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_char32(_:)-20u7n",
        "doc://com.apple.accelerate/documentation/simd/simd_make_char32_undef(_:)-9nqa9"
      ],
      "title": "Functions to Create Thirty Two-Element Vectors From Scalar Values"
    },
    {
      "anchor": "Common-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_abs(_:)-2ca9r",
        "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-2eiom",
        "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-2iweh"
      ],
      "title": "Common Functions"
    },
    {
      "anchor": "Reduce-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-2au68",
        "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-9j748",
        "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-1uzk7"
      ],
      "title": "Reduce Functions"
    },
    {
      "anchor": "Extrema-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-2isjs",
        "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-9ec8n"
      ],
      "title": "Extrema Functions"
    },
    {
      "anchor": "Logic-and-Bitwise-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-3az4l",
        "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1k7jn",
        "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-2da13"
      ],
      "title": "Logic and Bitwise Functions"
    },
    {
      "anchor": "Alternative-Type-Alias",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/vector_char32"
      ],
      "title": "Alternative Type Alias"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "simd_char32"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/simd"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Functions-to-Create-Thirty-Two-Element-Vectors-From-Other-Vectors",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_char32(_:)-384hl",
                "doc://com.apple.accelerate/documentation/simd/simd_make_char32(_:)-3bm80",
                "doc://com.apple.accelerate/documentation/simd/simd_make_char32(_:)-2n9wz",
                "doc://com.apple.accelerate/documentation/simd/simd_make_char32(_:)-2ag5j",
                "doc://com.apple.accelerate/documentation/simd/simd_make_char32(_:)-3g5k3",
                "doc://com.apple.accelerate/documentation/simd/simd_make_char32(_:)-8fqzf",
                "doc://com.apple.accelerate/documentation/simd/simd_make_char32(_:)-6kn8l",
                "doc://com.apple.accelerate/documentation/simd/simd_make_char32(_:_:)",
                "doc://com.apple.accelerate/documentation/simd/vector32-6853f",
                "doc://com.apple.accelerate/documentation/simd/simd_make_char32_undef(_:)-7t6qn",
                "doc://com.apple.accelerate/documentation/simd/simd_make_char32_undef(_:)-7poo6",
                "doc://com.apple.accelerate/documentation/simd/simd_make_char32_undef(_:)-7z0ct",
                "doc://com.apple.accelerate/documentation/simd/simd_make_char32_undef(_:)-6t8l5",
                "doc://com.apple.accelerate/documentation/simd/simd_make_char32_undef(_:)-3vq4m"
              ],
              "title": "Functions to Create Thirty Two-Element Vectors From Other Vectors"
            },
            {
              "anchor": "Functions-to-Create-Thirty-Two-Element-Vectors-From-Scalar-Values",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_char32(_:)-20u7n",
                "doc://com.apple.accelerate/documentation/simd/simd_make_char32_undef(_:)-9nqa9"
              ],
              "title": "Functions to Create Thirty Two-Element Vectors From Scalar Values"
            },
            {
              "anchor": "Functions-to-Create-Thirty-Two-Element-Vectors-From-Vectors-of-Other-Types",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_char-50vc0",
                "doc://com.apple.accelerate/documentation/simd/simd_char-5159c",
                "doc://com.apple.accelerate/documentation/simd/simd_char-51074",
                "doc://com.apple.accelerate/documentation/simd/simd_char-51a68"
              ],
              "title": "Functions to Create Thirty Two-Element Vectors From Vectors of Other Types"
            },
            {
              "anchor": "Functions-to-Perform-Saturating-Conversion-From-Vectors-of-Other-Types",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_char_sat-uyox",
                "doc://com.apple.accelerate/documentation/simd/simd_char_sat-uov5",
                "doc://com.apple.accelerate/documentation/simd/simd_char_sat-v3lt",
                "doc://com.apple.accelerate/documentation/simd/simd_char_sat-utq9"
              ],
              "title": "Functions to Perform Saturating Conversion From Vectors of Other Types"
            },
            {
              "anchor": "Common-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_abs(_:)-2ca9r",
                "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-2eiom",
                "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-2iweh"
              ],
              "title": "Common Functions"
            },
            {
              "anchor": "Reduce-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-2au68",
                "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-9j748",
                "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-1uzk7"
              ],
              "title": "Reduce Functions"
            },
            {
              "anchor": "Extrema-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-2isjs",
                "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-9ec8n"
              ],
              "title": "Extrema Functions"
            },
            {
              "anchor": "Logic-and-Bitwise-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-3az4l",
                "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1k7jn",
                "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-2da13"
              ],
              "title": "Logic and Bitwise Functions"
            },
            {
              "anchor": "Alternative-Type-Alias",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/vector_char32"
              ],
              "title": "Alternative Type Alias"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Vector-Data-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_char1",
                "doc://com.apple.accelerate/documentation/simd/simd_char2",
                "doc://com.apple.accelerate/documentation/simd/simd_char3",
                "doc://com.apple.accelerate/documentation/simd/simd_char4",
                "doc://com.apple.accelerate/documentation/simd/simd_char8",
                "doc://com.apple.accelerate/documentation/simd/simd_char16",
                "doc://com.apple.accelerate/documentation/simd/simd_char64"
              ],
              "title": "Vector Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:]32C",
                    "text": "char __attribute__((ext_vector_type(32)))"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "simd_char32"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char32_undef(_:)-6t8l5/title",
          "value": "simd_make_char32_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char32_undef(_:)-6t8l5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_char32_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_max(_:)-9j748/title",
          "value": "simd_reduce_max"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_max(_:)-9j748/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_max"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char1/title",
          "value": "simd_char1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char1/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char32_undef(_:)-7z0ct/title",
          "value": "simd_make_char32_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char32_undef(_:)-7z0ct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_char32_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_min(_:_:)-2isjs/title",
          "value": "simd_min"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_min(_:_:)-2isjs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_min"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char32_undef(_:)-3vq4m/title",
          "value": "simd_make_char32_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char32_undef(_:)-3vq4m/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_char32_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char32(_:)-3bm80/title",
          "value": "simd_make_char32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char32(_:)-3bm80/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_char32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char32(_:)-2n9wz/title",
          "value": "simd_make_char32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char32(_:)-2n9wz/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_char32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1vector_char32/title",
          "value": "vector_char32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1vector_char32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vector_char32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1vector_char32/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vector_char32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_max(_:_:)-9ec8n/title",
          "value": "simd_max"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_max(_:_:)-9ec8n/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_max"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_all(_:)-1k7jn/title",
          "value": "simd_all"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_all(_:)-1k7jn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_all"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char32(_:)-2ag5j/title",
          "value": "simd_make_char32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char32(_:)-2ag5j/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_char32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char64/title",
          "value": "simd_char64"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char64/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char64/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char4/title",
          "value": "simd_char4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char32(_:)-6kn8l/title",
          "value": "simd_make_char32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char32(_:)-6kn8l/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_char32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char32_undef(_:)-7t6qn/title",
          "value": "simd_make_char32_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char32_undef(_:)-7t6qn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_char32_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_min(_:)-2au68/title",
          "value": "simd_reduce_min"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_min(_:)-2au68/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_min"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_equal(_:_:)-2iweh/title",
          "value": "simd_equal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_equal(_:_:)-2iweh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_equal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_add(_:)-1uzk7/title",
          "value": "simd_reduce_add"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_add(_:)-1uzk7/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_add"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char32_undef(_:)-9nqa9/title",
          "value": "simd_make_char32_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char32_undef(_:)-9nqa9/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_char32_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_any(_:)-3az4l/title",
          "value": "simd_any"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_any(_:)-3az4l/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_any"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char32/title",
          "value": "simd_char32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char32/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char16/title",
          "value": "simd_char16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char16/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char32(_:_:)/title",
          "value": "simd_make_char32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char32(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_char32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char8/title",
          "value": "simd_char8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char32(_:)-20u7n/title",
          "value": "simd_make_char32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char32(_:)-20u7n/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_char32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char32(_:)-3g5k3/title",
          "value": "simd_make_char32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char32(_:)-3g5k3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_char32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_clamp(_:_:_:)-2eiom/title",
          "value": "simd_clamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_clamp(_:_:_:)-2eiom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_clamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char32(_:)-384hl/title",
          "value": "simd_make_char32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char32(_:)-384hl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_char32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char2/title",
          "value": "simd_char2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_bitselect(_:_:_:)-2da13/title",
          "value": "simd_bitselect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_bitselect(_:_:_:)-2da13/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_bitselect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char32(_:)-8fqzf/title",
          "value": "simd_make_char32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char32(_:)-8fqzf/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_char32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char32_undef(_:)-7poo6/title",
          "value": "simd_make_char32_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_char32_undef(_:)-7poo6/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_char32_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_abs(_:)-2ca9r/title",
          "value": "simd_abs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_abs(_:)-2ca9r/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_abs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char3/title",
          "value": "simd_char3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char3"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_char32"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/simd/simd_char32"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
