{
  "abstract": [
    {
      "text": "Returns a new vector by truncating the specified four-element vector.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_make_float2(_:)-32usp"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_make_float2#]4f#",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simd_make_float2"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_float4",
        "text": "simd_float4"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_float2",
        "text": "simd_float2"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_make_float2"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_make_float2(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_make_float2"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "other"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float4",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_float4",
              "text": "simd_float4"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_float2",
              "text": "simd_float2"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float2": {
      "abstract": [
        {
          "text": "A vector of two 32-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_float2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_float2"
        }
      ],
      "role": "symbol",
      "title": "simd_float2",
      "type": "topic",
      "url": "/documentation/simd/simd_float2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float4": {
      "abstract": [
        {
          "text": "A vector of four 32-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_float4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_float4"
        }
      ],
      "role": "symbol",
      "title": "simd_float4",
      "type": "topic",
      "url": "/documentation/simd/simd_float4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_float2(_:)-32usp": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified four-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_float2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float4",
          "text": "simd_float4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float2",
          "text": "simd_float2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_float2(_:)-32usp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_float2"
        }
      ],
      "role": "symbol",
      "title": "simd_make_float2(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_float2(_:)-32usp"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_float2(_:)-3kta4": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified three-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_float2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float3",
          "text": "simd_float3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float2",
          "text": "simd_float2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_float2(_:)-3kta4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_float2"
        }
      ],
      "role": "symbol",
      "title": "simd_make_float2(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_float2(_:)-3kta4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_float2(_:)-3nphb": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_float2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float2",
          "text": "simd_float2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float2",
          "text": "simd_float2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_float2(_:)-3nphb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_float2"
        }
      ],
      "role": "symbol",
      "title": "simd_make_float2(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_float2(_:)-3nphb"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_float2(_:)-493yd": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified eight-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_float2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float8",
          "text": "simd_float8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float2",
          "text": "simd_float2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_float2(_:)-493yd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_float2"
        }
      ],
      "role": "symbol",
      "title": "simd_make_float2(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_float2(_:)-493yd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_float2(_:)-4e6k3": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified 16-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_float2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float16",
          "text": "simd_float16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float2",
          "text": "simd_float2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_float2(_:)-4e6k3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_float2"
        }
      ],
      "role": "symbol",
      "title": "simd_make_float2(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_float2(_:)-4e6k3"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Create-Two-Element-Vectors-From-Other-Vectors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_float2(_:)-3nphb",
        "doc://com.apple.accelerate/documentation/simd/simd_make_float2(_:)-3kta4",
        "doc://com.apple.accelerate/documentation/simd/simd_make_float2(_:)-493yd",
        "doc://com.apple.accelerate/documentation/simd/simd_make_float2(_:)-4e6k3"
      ],
      "title": "Functions to Create Two-Element Vectors From Other Vectors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "simd_make_float2"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_float2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/simd"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Functions-to-Create-Two-Element-Vectors-From-Other-Vectors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_float2(_:)-3nphb",
                "doc://com.apple.accelerate/documentation/simd/simd_make_float2(_:)-3kta4",
                "doc://com.apple.accelerate/documentation/simd/simd_make_float2(_:)-493yd",
                "doc://com.apple.accelerate/documentation/simd/simd_make_float2(_:)-4e6k3"
              ],
              "title": "Functions to Create Two-Element Vectors From Other Vectors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "static"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float2",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_float2",
                    "text": "simd_float2"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "simd_make_float2"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float4",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_float4",
                    "text": "simd_float4"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "other"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_float2(_:)-3nphb/title",
          "value": "simd_make_float2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_float2(_:)-3nphb/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_float2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_float2(_:)-4e6k3/title",
          "value": "simd_make_float2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_float2(_:)-4e6k3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_float2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_float2(_:)-493yd/title",
          "value": "simd_make_float2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_float2(_:)-493yd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_float2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float2/title",
          "value": "simd_float2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float4/title",
          "value": "simd_float4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_float2(_:)-3kta4/title",
          "value": "simd_make_float2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_float2(_:)-3kta4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_float2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_float2(_:)-32usp/title",
          "value": "simd_make_float2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_float2(_:)-32usp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_float2"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_make_float2(_:)-32usp"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/simd/simd_make_float2(_:)-32usp"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
