{
  "abstract": [
    {
      "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_ulong-16eyu"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_ulong#]8L#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_ulong"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_ulong"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_ulong"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong8",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_ulong8",
              "text": "simd_ulong8"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_ulong"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long8",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_long8",
              "text": "simd_long8"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long8": {
      "abstract": [
        {
          "text": "A vector of eight 64-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_long8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_long8"
        }
      ],
      "role": "symbol",
      "title": "simd_long8",
      "type": "topic",
      "url": "/documentation/simd/simd_long8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong-1692y": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong-1692y",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong-1692y"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong-16dyy": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong-16dyy",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong-16dyy"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong-16eyu": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong-16eyu",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong-16eyu"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong-16fzq": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong-16fzq",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong-16fzq"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong-16j3u": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong-16j3u",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong-16j3u"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong-16mhi": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong-16mhi",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong-16mhi"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong-16n5e": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong-16n5e",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong-16n5e"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong-16o3e": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong-16o3e",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong-16o3e"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong-16oxy": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong-16oxy",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong-16oxy"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong-16px2": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong-16px2",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong-16px2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong8": {
      "abstract": [
        {
          "text": "A vector of eight 64-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ulong8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ulong8"
        }
      ],
      "role": "symbol",
      "title": "simd_ulong8",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong8"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Create-Eight-Element-Vectors-From-Vectors-of-Other-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_ulong-16dyy",
        "doc://com.apple.accelerate/documentation/simd/simd_ulong-16o3e",
        "doc://com.apple.accelerate/documentation/simd/simd_ulong-1692y",
        "doc://com.apple.accelerate/documentation/simd/simd_ulong-16j3u",
        "doc://com.apple.accelerate/documentation/simd/simd_ulong-16fzq",
        "doc://com.apple.accelerate/documentation/simd/simd_ulong-16px2",
        "doc://com.apple.accelerate/documentation/simd/simd_ulong-16oxy",
        "doc://com.apple.accelerate/documentation/simd/simd_ulong-16n5e",
        "doc://com.apple.accelerate/documentation/simd/simd_ulong-16mhi"
      ],
      "title": "Functions to Create Eight-Element Vectors From Vectors of Other Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long8/title",
          "value": "simd_long8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_long8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_long8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong8/title",
          "value": "simd_ulong8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong8"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_ulong-16eyu"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
