{
  "abstract": [
    {
      "text": "Returns the precise length of a vector.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_precise_length-7az1z"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_precise_length#]3f#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_precise_length"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_precise_length"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_precise_length"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:f",
              "text": "float"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_precise_length"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float3",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_float3",
              "text": "simd_float3"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_distance-52a41": {
      "abstract": [
        {
          "text": "Returns the distance between two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_distance"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_distance-52a41",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_distance",
      "type": "topic",
      "url": "/documentation/simd/simd_distance-52a41"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_distance_squared-320dw": {
      "abstract": [
        {
          "text": "Returns the square of the distance between two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_distance_squared"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_distance_squared-320dw",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_distance_squared",
      "type": "topic",
      "url": "/documentation/simd/simd_distance_squared-320dw"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_fast_distance-8n00l": {
      "abstract": [
        {
          "text": "Returns the fast distance between two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_fast_distance"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_fast_distance-8n00l",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_fast_distance",
      "type": "topic",
      "url": "/documentation/simd/simd_fast_distance-8n00l"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_fast_length-56ii9": {
      "abstract": [
        {
          "text": "Returns the fast length of a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_fast_length"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_fast_length-56ii9",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_fast_length",
      "type": "topic",
      "url": "/documentation/simd/simd_fast_length-56ii9"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float3": {
      "abstract": [
        {
          "text": "A vector of three 32-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_float3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_float3"
        }
      ],
      "role": "symbol",
      "title": "simd_float3",
      "type": "topic",
      "url": "/documentation/simd/simd_float3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_length-3r7cm": {
      "abstract": [
        {
          "text": "Returns the length of a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_length"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_length-3r7cm",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_length",
      "type": "topic",
      "url": "/documentation/simd/simd_length-3r7cm"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_length_squared-3hj9o": {
      "abstract": [
        {
          "text": "Returns the square of the length of a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_length_squared"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_length_squared-3hj9o",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_length_squared",
      "type": "topic",
      "url": "/documentation/simd/simd_length_squared-3hj9o"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_precise_distance-2kvj2": {
      "abstract": [
        {
          "text": "Returns the precise distance between two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_precise_distance"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_precise_distance-2kvj2",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_precise_distance",
      "type": "topic",
      "url": "/documentation/simd/simd_precise_distance-2kvj2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_precise_length-7az1z": {
      "abstract": [
        {
          "text": "Returns the precise length of a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_precise_length"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_precise_length-7az1z",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_precise_length",
      "type": "topic",
      "url": "/documentation/simd/simd_precise_length-7az1z"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Length-and-Distance-Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_length-3r7cm",
        "doc://com.apple.accelerate/documentation/simd/simd_fast_length-56ii9",
        "doc://com.apple.accelerate/documentation/simd/simd_length_squared-3hj9o",
        "doc://com.apple.accelerate/documentation/simd/simd_distance-52a41",
        "doc://com.apple.accelerate/documentation/simd/simd_fast_distance-8n00l",
        "doc://com.apple.accelerate/documentation/simd/simd_precise_distance-2kvj2",
        "doc://com.apple.accelerate/documentation/simd/simd_distance_squared-320dw"
      ],
      "title": "Length and Distance Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float3/title",
          "value": "simd_float3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float3"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_precise_length-7az1z"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
