{
  "abstract": [
    {
      "text": "Returns the precise length of a vector.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_precise_length-77xwk"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_precise_length#]2f#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_precise_length"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_precise_length"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_precise_length"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:f",
              "text": "float"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_precise_length"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_float2",
              "text": "simd_float2"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_distance-598wa": {
      "abstract": [
        {
          "text": "Returns the distance between two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_distance"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_distance-598wa",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_distance",
      "type": "topic",
      "url": "/documentation/simd/simd_distance-598wa"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_distance_squared-7zevh": {
      "abstract": [
        {
          "text": "Returns the square of the distance between two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_distance_squared"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_distance_squared-7zevh",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_distance_squared",
      "type": "topic",
      "url": "/documentation/simd/simd_distance_squared-7zevh"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_fast_distance-2jlix": {
      "abstract": [
        {
          "text": "Returns the fast distance between two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_fast_distance"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_fast_distance-2jlix",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_fast_distance",
      "type": "topic",
      "url": "/documentation/simd/simd_fast_distance-2jlix"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_fast_length-59ep6": {
      "abstract": [
        {
          "text": "Returns the fast length of a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_fast_length"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_fast_length-59ep6",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_fast_length",
      "type": "topic",
      "url": "/documentation/simd/simd_fast_length-59ep6"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float2": {
      "abstract": [
        {
          "text": "A vector of two 32-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_float2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_float2"
        }
      ],
      "role": "symbol",
      "title": "simd_float2",
      "type": "topic",
      "url": "/documentation/simd/simd_float2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_length-3ob5d": {
      "abstract": [
        {
          "text": "Returns the length of a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_length"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_length-3ob5d",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_length",
      "type": "topic",
      "url": "/documentation/simd/simd_length-3ob5d"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_length_squared-3e32j": {
      "abstract": [
        {
          "text": "Returns the square of the length of a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_length_squared"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_length_squared-3e32j",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_length_squared",
      "type": "topic",
      "url": "/documentation/simd/simd_length_squared-3e32j"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_precise_distance-8hrn8": {
      "abstract": [
        {
          "text": "Returns the precise distance between two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_precise_distance"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_precise_distance-8hrn8",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_precise_distance",
      "type": "topic",
      "url": "/documentation/simd/simd_precise_distance-8hrn8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_precise_length-77xwk": {
      "abstract": [
        {
          "text": "Returns the precise length of a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_precise_length"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_precise_length-77xwk",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_precise_length",
      "type": "topic",
      "url": "/documentation/simd/simd_precise_length-77xwk"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Length-and-Distance-Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_length-3ob5d",
        "doc://com.apple.accelerate/documentation/simd/simd_fast_length-59ep6",
        "doc://com.apple.accelerate/documentation/simd/simd_length_squared-3e32j",
        "doc://com.apple.accelerate/documentation/simd/simd_distance-598wa",
        "doc://com.apple.accelerate/documentation/simd/simd_fast_distance-2jlix",
        "doc://com.apple.accelerate/documentation/simd/simd_precise_distance-8hrn8",
        "doc://com.apple.accelerate/documentation/simd/simd_distance_squared-7zevh"
      ],
      "title": "Length and Distance Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float2/title",
          "value": "simd_float2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float2"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_precise_length-77xwk"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
