{
  "abstract": [
    {
      "text": "A matrix of four columns and two rows that contains half-precision values.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_half4x2"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@SA@simd_half4x2",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simd_half4x2"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_half4x2"
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "simd_half4x2"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_half4x2"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_multiply-338dm": {
      "abstract": [
        {
          "text": "Returns the product of a vector and a matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "matrix_multiply"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_multiply-338dm",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_multiply",
      "type": "topic",
      "url": "/documentation/simd/matrix_multiply-338dm"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_multiply-5z5lq": {
      "abstract": [
        {
          "text": "Returns the product of a 2 x 2 matrix and a 4 x 2 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "matrix_multiply"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_multiply-5z5lq",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_multiply",
      "type": "topic",
      "url": "/documentation/simd/matrix_multiply-5z5lq"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_scale-ltxk": {
      "abstract": [
        {
          "text": "Returns the product of a scalar value and a matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "matrix_scale"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_scale-ltxk",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_scale",
      "type": "topic",
      "url": "/documentation/simd/matrix_scale-ltxk"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_add-1gp5l": {
      "abstract": [
        {
          "text": "Returns the sum of two matrices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_add"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_add-1gp5l",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_add",
      "type": "topic",
      "url": "/documentation/simd/simd_add-1gp5l"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_almost_equal_elements-9xbkd": {
      "abstract": [
        {
          "text": "Returns true if every element in a matrix is within a specified tolerance to the corresponding element in a second matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_almost_equal_elements"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_almost_equal_elements-9xbkd",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_almost_equal_elements",
      "type": "topic",
      "url": "/documentation/simd/simd_almost_equal_elements-9xbkd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_almost_equal_elements_relative-7hff8": {
      "abstract": [
        {
          "text": "Returns true if every element in a matrix is within a specified single-precision relative tolerance to the corresponding element in a second matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_almost_equal_elements_relative"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_almost_equal_elements_relative-7hff8",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_almost_equal_elements_relative",
      "type": "topic",
      "url": "/documentation/simd/simd_almost_equal_elements_relative-7hff8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_equal-1u248": {
      "abstract": [
        {
          "text": "Returns true if every element in a matrix is exactly equal to the corresponding element in a second matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_equal"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_equal-1u248",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_equal",
      "type": "topic",
      "url": "/documentation/simd/simd_equal-1u248"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half2x2": {
      "abstract": [
        {
          "text": "A matrix of two columns and two rows that contains half-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_half2x2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half2x2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_half2x2"
        }
      ],
      "role": "symbol",
      "title": "simd_half2x2",
      "type": "topic",
      "url": "/documentation/simd/simd_half2x2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half2x3": {
      "abstract": [
        {
          "text": "A matrix of two columns and three rows that contains half-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_half2x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half2x3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_half2x3"
        }
      ],
      "role": "symbol",
      "title": "simd_half2x3",
      "type": "topic",
      "url": "/documentation/simd/simd_half2x3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half2x4": {
      "abstract": [
        {
          "text": "A matrix of two columns and four rows that contains half-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_half2x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half2x4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_half2x4"
        }
      ],
      "role": "symbol",
      "title": "simd_half2x4",
      "type": "topic",
      "url": "/documentation/simd/simd_half2x4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half3x2": {
      "abstract": [
        {
          "text": "A matrix of three columns and two rows that contains half-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_half3x2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half3x2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_half3x2"
        }
      ],
      "role": "symbol",
      "title": "simd_half3x2",
      "type": "topic",
      "url": "/documentation/simd/simd_half3x2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half3x3": {
      "abstract": [
        {
          "text": "A matrix of three columns and three rows that contains half-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_half3x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half3x3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_half3x3"
        }
      ],
      "role": "symbol",
      "title": "simd_half3x3",
      "type": "topic",
      "url": "/documentation/simd/simd_half3x3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half3x4": {
      "abstract": [
        {
          "text": "A matrix of three columns and four rows that contains half-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_half3x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half3x4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_half3x4"
        }
      ],
      "role": "symbol",
      "title": "simd_half3x4",
      "type": "topic",
      "url": "/documentation/simd/simd_half3x4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half4x2": {
      "abstract": [
        {
          "text": "A matrix of four columns and two rows that contains half-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_half4x2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half4x2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_half4x2"
        }
      ],
      "role": "symbol",
      "title": "simd_half4x2",
      "type": "topic",
      "url": "/documentation/simd/simd_half4x2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half4x2/columns": {
      "abstract": [
        {
          "text": "The columns of the matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "columns"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half2",
          "text": "simd_half2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half2",
          "text": "simd_half2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half2",
          "text": "simd_half2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half2",
          "text": "simd_half2"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half4x2/columns",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "columns"
        }
      ],
      "role": "symbol",
      "title": "columns",
      "type": "topic",
      "url": "/documentation/simd/simd_half4x2/columns"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half4x2/init()": {
      "abstract": [
        {
          "text": "Creates a new matrix with uninitialized memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half4x2/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/simd/simd_half4x2/init()"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half4x2/init(columns:)": {
      "abstract": [
        {
          "text": "Creates a new matrix with the specified columns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "columns"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half2",
          "text": "simd_half2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half2",
          "text": "simd_half2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half2",
          "text": "simd_half2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half2",
          "text": "simd_half2"
        },
        {
          "kind": "text",
          "text": "))"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half4x2/init(columns:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(columns:)",
      "type": "topic",
      "url": "/documentation/simd/simd_half4x2/init(columns:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half4x3": {
      "abstract": [
        {
          "text": "A matrix of four columns and three rows that contains half-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_half4x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half4x3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_half4x3"
        }
      ],
      "role": "symbol",
      "title": "simd_half4x3",
      "type": "topic",
      "url": "/documentation/simd/simd_half4x3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half4x4": {
      "abstract": [
        {
          "text": "A matrix of four columns and four rows that contains half-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_half4x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half4x4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_half4x4"
        }
      ],
      "role": "symbol",
      "title": "simd_half4x4",
      "type": "topic",
      "url": "/documentation/simd/simd_half4x4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_linear_combination-6h9ag": {
      "abstract": [
        {
          "text": "Returns the linear combination of two scalar values and two matrices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_linear_combination"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_linear_combination-6h9ag",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_linear_combination",
      "type": "topic",
      "url": "/documentation/simd/simd_linear_combination-6h9ag"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_matrix(_:_:_:_:)-9nj2": {
      "abstract": [
        {
          "text": "Returns a new matrix with the specified columns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_matrix"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half2",
          "text": "simd_half2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half2",
          "text": "simd_half2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half2",
          "text": "simd_half2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half2",
          "text": "simd_half2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_half4x2",
          "text": "simd_half4x2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_matrix(_:_:_:_:)-9nj2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_matrix"
        }
      ],
      "role": "symbol",
      "title": "simd_matrix(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_matrix(_:_:_:_:)-9nj2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_matrix_from_rows(_:_:)-74k": {
      "abstract": [
        {
          "text": "Returns a new matrix with the specified rows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_matrix_from_rows"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half4",
          "text": "simd_half4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_half4",
          "text": "simd_half4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_half4x2",
          "text": "simd_half4x2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_matrix_from_rows(_:_:)-74k",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_matrix_from_rows"
        }
      ],
      "role": "symbol",
      "title": "simd_matrix_from_rows(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_matrix_from_rows(_:_:)-74k"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_sub-8pp6m": {
      "abstract": [
        {
          "text": "Returns the difference of two matrices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_sub"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_sub-8pp6m",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_sub",
      "type": "topic",
      "url": "/documentation/simd/simd_sub-8pp6m"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_transpose-4uji2": {
      "abstract": [
        {
          "text": "Returns the transpose of a matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_transpose"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_transpose-4uji2",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_transpose",
      "type": "topic",
      "url": "/documentation/simd/simd_transpose-4uji2"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Matrix-structures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_half2x2",
        "doc://com.apple.accelerate/documentation/simd/simd_half2x3",
        "doc://com.apple.accelerate/documentation/simd/simd_half2x4",
        "doc://com.apple.accelerate/documentation/simd/simd_half3x2",
        "doc://com.apple.accelerate/documentation/simd/simd_half3x3",
        "doc://com.apple.accelerate/documentation/simd/simd_half3x4",
        "doc://com.apple.accelerate/documentation/simd/simd_half4x3",
        "doc://com.apple.accelerate/documentation/simd/simd_half4x4"
      ],
      "title": "Matrix structures"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_half4x2/init()",
        "doc://com.apple.accelerate/documentation/simd/simd_half4x2/init(columns:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Matrix-properties",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_half4x2/columns"
      ],
      "title": "Matrix properties"
    },
    {
      "anchor": "Matrix-creation-functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_matrix(_:_:_:_:)-9nj2",
        "doc://com.apple.accelerate/documentation/simd/simd_matrix_from_rows(_:_:)-74k"
      ],
      "title": "Matrix creation functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "simd_half4x2"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half4x2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half4x2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/simd"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Matrix-properties",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_half4x2/columns"
              ],
              "title": "Matrix properties"
            },
            {
              "anchor": "Matrix-creation-functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_matrix(_:_:_:_:)-9nj2",
                "doc://com.apple.accelerate/documentation/simd/simd_matrix_from_rows(_:_:)-74k"
              ],
              "title": "Matrix creation functions"
            },
            {
              "anchor": "Math-functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_add-1gp5l",
                "doc://com.apple.accelerate/documentation/simd/simd_sub-8pp6m"
              ],
              "title": "Math functions"
            },
            {
              "anchor": "Matrix-scalar-multiplication-functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/matrix_scale-ltxk"
              ],
              "title": "Matrix-scalar multiplication functions"
            },
            {
              "anchor": "Matrix-vector-multiplication-functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/matrix_multiply-338dm"
              ],
              "title": "Matrix-vector multiplication functions"
            },
            {
              "anchor": "Matrix-matrix-multiplication-functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/matrix_multiply-5z5lq"
              ],
              "title": "Matrix-matrix multiplication functions"
            },
            {
              "anchor": "Equality-functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_equal-1u248",
                "doc://com.apple.accelerate/documentation/simd/simd_almost_equal_elements-9xbkd",
                "doc://com.apple.accelerate/documentation/simd/simd_almost_equal_elements_relative-7hff8"
              ],
              "title": "Equality functions"
            },
            {
              "anchor": "Linear-combination-function",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_linear_combination-6h9ag"
              ],
              "title": "Linear combination function"
            },
            {
              "anchor": "Transpose-function",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_transpose-4uji2"
              ],
              "title": "Transpose function"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Matrix-structures",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_half2x2",
                "doc://com.apple.accelerate/documentation/simd/simd_half2x3",
                "doc://com.apple.accelerate/documentation/simd/simd_half2x4",
                "doc://com.apple.accelerate/documentation/simd/simd_half3x2",
                "doc://com.apple.accelerate/documentation/simd/simd_half3x3",
                "doc://com.apple.accelerate/documentation/simd/simd_half3x4",
                "doc://com.apple.accelerate/documentation/simd/simd_half4x3",
                "doc://com.apple.accelerate/documentation/simd/simd_half4x4"
              ],
              "title": "Matrix structures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "simd_half4x2"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half3x3/title",
          "value": "simd_half3x3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half3x3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half3x3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half3x3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half3x3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half4x3/title",
          "value": "simd_half4x3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half4x3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half4x3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half4x3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half4x3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half2x4/title",
          "value": "simd_half2x4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half2x4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half2x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half2x4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half2x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half3x2/title",
          "value": "simd_half3x2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half3x2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half3x2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half3x2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half3x2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half3x4/title",
          "value": "simd_half3x4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half3x4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half3x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half3x4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half3x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half2x2/title",
          "value": "simd_half2x2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half2x2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half2x2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half2x2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half2x2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half4x2/title",
          "value": "simd_half4x2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half4x2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half4x2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half4x2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half4x2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_matrix_from_rows(_:_:)-74k/title",
          "value": "simd_matrix_from_rows"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_matrix_from_rows(_:_:)-74k/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_matrix_from_rows"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half4x2~1columns/title",
          "value": "columns"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half4x2~1columns/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "columns"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_matrix(_:_:_:_:)-9nj2/title",
          "value": "simd_matrix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_matrix(_:_:_:_:)-9nj2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_matrix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half2x3/title",
          "value": "simd_half2x3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half2x3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half2x3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half2x3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half2x3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half4x4/title",
          "value": "simd_half4x4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half4x4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half4x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half4x4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half4x4"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_half4x2"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/simd/simd_half4x2"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
