{
  "abstract": [
    {
      "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_long-7kye"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_long#]3I#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_long"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_long"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_long"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long3",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_long3",
              "text": "simd_long3"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_long"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int3",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_int3",
              "text": "simd_int3"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int3": {
      "abstract": [
        {
          "text": "A vector of three 32-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_int3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_int3"
        }
      ],
      "role": "symbol",
      "title": "simd_int3",
      "type": "topic",
      "url": "/documentation/simd/simd_int3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long-740y": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long-740y",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long",
      "type": "topic",
      "url": "/documentation/simd/simd_long-740y"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long-7936": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long-7936",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long",
      "type": "topic",
      "url": "/documentation/simd/simd_long-7936"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long-79xy": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long-79xy",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long",
      "type": "topic",
      "url": "/documentation/simd/simd_long-79xy"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long-7aju": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long-7aju",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long",
      "type": "topic",
      "url": "/documentation/simd/simd_long-7aju"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long-7aza": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long-7aza",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long",
      "type": "topic",
      "url": "/documentation/simd/simd_long-7aza"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long-7ccm": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long-7ccm",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long",
      "type": "topic",
      "url": "/documentation/simd/simd_long-7ccm"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long-7dya": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long-7dya",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long",
      "type": "topic",
      "url": "/documentation/simd/simd_long-7dya"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long-7iv6": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long-7iv6",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long",
      "type": "topic",
      "url": "/documentation/simd/simd_long-7iv6"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long-7kye": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long-7kye",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long",
      "type": "topic",
      "url": "/documentation/simd/simd_long-7kye"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long-7miu": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_long"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long-7miu",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_long",
      "type": "topic",
      "url": "/documentation/simd/simd_long-7miu"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long3": {
      "abstract": [
        {
          "text": "A vector of three 64-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_long3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_long3"
        }
      ],
      "role": "symbol",
      "title": "simd_long3",
      "type": "topic",
      "url": "/documentation/simd/simd_long3"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Create-Three-Element-Vectors-From-Vectors-of-Other-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_long-7iv6",
        "doc://com.apple.accelerate/documentation/simd/simd_long-7936",
        "doc://com.apple.accelerate/documentation/simd/simd_long-7dya",
        "doc://com.apple.accelerate/documentation/simd/simd_long-740y",
        "doc://com.apple.accelerate/documentation/simd/simd_long-7aza",
        "doc://com.apple.accelerate/documentation/simd/simd_long-7miu",
        "doc://com.apple.accelerate/documentation/simd/simd_long-7ccm",
        "doc://com.apple.accelerate/documentation/simd/simd_long-7aju",
        "doc://com.apple.accelerate/documentation/simd/simd_long-79xy"
      ],
      "title": "Functions to Create Three-Element Vectors From Vectors of Other Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int3/title",
          "value": "simd_int3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_int3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_int3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long3/title",
          "value": "simd_long3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_long3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_long3"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_long-7kye"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
