{
  "abstract": [
    {
      "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_ulong-1rkuo"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_ulong#]2l#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_ulong"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_ulong"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_ulong"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_ulong2",
              "text": "simd_ulong2"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_ulong"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_ulong2",
              "text": "simd_ulong2"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong-1r8xg": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong-1r8xg",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong-1r8xg"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong-1rb2o": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong-1rb2o",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong-1rb2o"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong-1rbpo": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong-1rbpo",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong-1rbpo"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong-1rdv8": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong-1rdv8",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong-1rdv8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong-1rhpk": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong-1rhpk",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong-1rhpk"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong-1ri80": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong-1ri80",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong-1ri80"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong-1rir8": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong-1rir8",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong-1rir8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong-1rkuo": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong-1rkuo",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong-1rkuo"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong-1rlsc": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong-1rlsc",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong-1rlsc"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong-1rnp0": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ulong"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong-1rnp0",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ulong",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong-1rnp0"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong2": {
      "abstract": [
        {
          "text": "A vector of two 64-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ulong2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ulong2"
        }
      ],
      "role": "symbol",
      "title": "simd_ulong2",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong2"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Create-Two-Element-Vectors-From-Vectors-of-Other-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_ulong-1r8xg",
        "doc://com.apple.accelerate/documentation/simd/simd_ulong-1rir8",
        "doc://com.apple.accelerate/documentation/simd/simd_ulong-1rdv8",
        "doc://com.apple.accelerate/documentation/simd/simd_ulong-1rnp0",
        "doc://com.apple.accelerate/documentation/simd/simd_ulong-1rbpo",
        "doc://com.apple.accelerate/documentation/simd/simd_ulong-1rlsc",
        "doc://com.apple.accelerate/documentation/simd/simd_ulong-1rb2o",
        "doc://com.apple.accelerate/documentation/simd/simd_ulong-1rhpk",
        "doc://com.apple.accelerate/documentation/simd/simd_ulong-1ri80"
      ],
      "title": "Functions to Create Two-Element Vectors From Vectors of Other Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong2/title",
          "value": "simd_ulong2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong2"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_ulong-1rkuo"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
