{
  "abstract": [
    {
      "text": "A vector of two 16-bit signed integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_short2"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@simd_short2",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simd_short2"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_short2"
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "simd_short2"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_short2"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5SIMD2V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5SIMD2V",
              "text": "SIMD2"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5Int16V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5Int16V",
              "text": "Int16"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_abs(_:)-88dfi": {
      "abstract": [
        {
          "text": "Returns the absolute value of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_abs"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short2",
          "text": "simd_short2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short2",
          "text": "simd_short2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_abs(_:)-88dfi",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_abs"
        }
      ],
      "role": "symbol",
      "title": "simd_abs(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_abs(_:)-88dfi"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1d5nj": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_all"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short2",
          "text": "simd_short2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_bool",
          "text": "simd_bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1d5nj",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_all"
        }
      ],
      "role": "symbol",
      "title": "simd_all(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_all(_:)-1d5nj"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-64jj5": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_any"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short2",
          "text": "simd_short2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_bool",
          "text": "simd_bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-64jj5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_any"
        }
      ],
      "role": "symbol",
      "title": "simd_any(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_any(_:)-64jj5"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-625jo": {
      "abstract": [
        {
          "text": "Returns a vector that contains elements from either the first or second parameter, based on the corresponding element in the third parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_bitselect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short2",
          "text": "simd_short2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short2",
          "text": "simd_short2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short2",
          "text": "simd_short2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short2",
          "text": "simd_short2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-625jo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_bitselect"
        }
      ],
      "role": "symbol",
      "title": "simd_bitselect(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_bitselect(_:_:_:)-625jo"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-5qqhe": {
      "abstract": [
        {
          "text": "Returns each element in a vector clamped to a specified range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_clamp"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short2",
          "text": "simd_short2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short2",
          "text": "simd_short2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short2",
          "text": "simd_short2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short2",
          "text": "simd_short2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-5qqhe",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_clamp"
        }
      ],
      "role": "symbol",
      "title": "simd_clamp(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_clamp(_:_:_:)-5qqhe"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-6gad6": {
      "abstract": [
        {
          "text": "Returns true if every element in a vector is exactly equal to the corresponding element in a second vector, and otherwise returns false.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_equal"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short2",
          "text": "simd_short2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short2",
          "text": "simd_short2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_bool",
          "text": "simd_bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-6gad6",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_equal"
        }
      ],
      "role": "symbol",
      "title": "simd_equal(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_equal(_:_:)-6gad6"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:)-222xa": {
      "abstract": [
        {
          "text": "Returns a new vector with the first element set to a scalar value, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int16V",
          "text": "Int16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short2",
          "text": "simd_short2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:)-222xa",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short2"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short2(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short2(_:)-222xa"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:)-58qns": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified sixteen-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short16",
          "text": "simd_short16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short2",
          "text": "simd_short2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:)-58qns",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short2"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short2(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short2(_:)-58qns"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:)-5z7ps": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified four-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short4",
          "text": "simd_short4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short2",
          "text": "simd_short2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:)-5z7ps",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short2"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short2(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short2(_:)-5z7ps"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:)-6bz90": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified thirty two-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short32",
          "text": "simd_short32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short2",
          "text": "simd_short2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:)-6bz90",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short2"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short2(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short2(_:)-6bz90"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:)-6gmv7": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified three-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short3",
          "text": "simd_short3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short2",
          "text": "simd_short2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:)-6gmv7",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short2"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short2(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short2(_:)-6gmv7"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:)-6juuy": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short2",
          "text": "simd_short2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short2",
          "text": "simd_short2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:)-6juuy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short2"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short2(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short2(_:)-6juuy"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:)-74zg4": {
      "abstract": [
        {
          "text": "Returns a new vector by truncating the specified eight-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short2",
          "text": "simd_short2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:)-74zg4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short2"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short2(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short2(_:)-74zg4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified scalar values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int16V",
          "text": "Int16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int16V",
          "text": "Int16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short2",
          "text": "simd_short2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short2"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short2(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short2(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short2_undef(_:)": {
      "abstract": [
        {
          "text": "Returns a new vector with the first element set to a scalar value, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short2_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int16V",
          "text": "Int16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short2",
          "text": "simd_short2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short2_undef(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short2_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short2_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short2_undef(_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-6w9rg": {
      "abstract": [
        {
          "text": "Returns the maximum value of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_max"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short2",
          "text": "simd_short2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short2",
          "text": "simd_short2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short2",
          "text": "simd_short2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-6w9rg",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_max"
        }
      ],
      "role": "symbol",
      "title": "simd_max(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_max(_:_:)-6w9rg"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-13ip4": {
      "abstract": [
        {
          "text": "Returns the minimum value of each element in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_min"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short2",
          "text": "simd_short2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short2",
          "text": "simd_short2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short2",
          "text": "simd_short2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-13ip4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_min"
        }
      ],
      "role": "symbol",
      "title": "simd_min(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_min(_:_:)-13ip4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-2q65m": {
      "abstract": [
        {
          "text": "Returns the sum of all elements in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_add"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short2",
          "text": "simd_short2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int16V",
          "text": "Int16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-2q65m",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_add"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_add(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_add(_:)-2q65m"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-4kmuw": {
      "abstract": [
        {
          "text": "Returns the maximum value in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_max"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short2",
          "text": "simd_short2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int16V",
          "text": "Int16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-4kmuw",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_max"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_max(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_max(_:)-4kmuw"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-49c4w": {
      "abstract": [
        {
          "text": "Returns the miniumum value in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_reduce_min"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short2",
          "text": "simd_short2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int16V",
          "text": "Int16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-49c4w",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_reduce_min"
        }
      ],
      "role": "symbol",
      "title": "simd_reduce_min(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_reduce_min(_:)-49c4w"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short-6eoa6": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short-6eoa6",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short",
      "type": "topic",
      "url": "/documentation/simd/simd_short-6eoa6"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short-6erke": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short-6erke",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short",
      "type": "topic",
      "url": "/documentation/simd/simd_short-6erke"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short-6esiy": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short-6esiy",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short",
      "type": "topic",
      "url": "/documentation/simd/simd_short-6esiy"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short-6et5a": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short-6et5a",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short",
      "type": "topic",
      "url": "/documentation/simd/simd_short-6et5a"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short-6eusq": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short-6eusq",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short",
      "type": "topic",
      "url": "/documentation/simd/simd_short-6eusq"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short-6ewci": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short-6ewci",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short",
      "type": "topic",
      "url": "/documentation/simd/simd_short-6ewci"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short-6ey3y": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short-6ey3y",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short",
      "type": "topic",
      "url": "/documentation/simd/simd_short-6ey3y"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short-6f37y": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short-6f37y",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short",
      "type": "topic",
      "url": "/documentation/simd/simd_short-6f37y"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short-6f4tm": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short-6f4tm",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short",
      "type": "topic",
      "url": "/documentation/simd/simd_short-6f4tm"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short-6f6bm": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short-6f6bm",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short",
      "type": "topic",
      "url": "/documentation/simd/simd_short-6f6bm"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short1": {
      "abstract": [
        {
          "text": "A vector of one 16-bit signed integer element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_short1"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_short1"
        }
      ],
      "role": "symbol",
      "title": "simd_short1",
      "type": "topic",
      "url": "/documentation/simd/simd_short1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short16": {
      "abstract": [
        {
          "text": "A vector of sixteen 16-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_short16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_short16"
        }
      ],
      "role": "symbol",
      "title": "simd_short16",
      "type": "topic",
      "url": "/documentation/simd/simd_short16"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short2": {
      "abstract": [
        {
          "text": "A vector of two 16-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_short2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_short2"
        }
      ],
      "role": "symbol",
      "title": "simd_short2",
      "type": "topic",
      "url": "/documentation/simd/simd_short2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short3": {
      "abstract": [
        {
          "text": "A vector of three 16-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_short3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_short3"
        }
      ],
      "role": "symbol",
      "title": "simd_short3",
      "type": "topic",
      "url": "/documentation/simd/simd_short3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short32": {
      "abstract": [
        {
          "text": "A vector of thirty-two 16-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_short32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_short32"
        }
      ],
      "role": "symbol",
      "title": "simd_short32",
      "type": "topic",
      "url": "/documentation/simd/simd_short32"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short4": {
      "abstract": [
        {
          "text": "A vector of four 16-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_short4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_short4"
        }
      ],
      "role": "symbol",
      "title": "simd_short4",
      "type": "topic",
      "url": "/documentation/simd/simd_short4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short8": {
      "abstract": [
        {
          "text": "A vector of eight 16-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_short8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_short8"
        }
      ],
      "role": "symbol",
      "title": "simd_short8",
      "type": "topic",
      "url": "/documentation/simd/simd_short8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3m83r": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3m83r",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_short_sat-3m83r"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3md2f": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3md2f",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_short_sat-3md2f"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3mfdp": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3mfdp",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_short_sat-3mfdp"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3mg4b": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3mg4b",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_short_sat-3mg4b"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3mi6f": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3mi6f",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_short_sat-3mi6f"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3mm1h": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3mm1h",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_short_sat-3mm1h"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3mmpp": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3mmpp",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_short_sat-3mmpp"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3mn6v": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3mn6v",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_short_sat-3mn6v"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3mpct": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3mpct",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_short_sat-3mpct"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3mqaj": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_short_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3mqaj",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_short_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_short_sat-3mqaj"
    },
    "doc://com.apple.accelerate/documentation/simd/vector2-5ek7j": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified scalar values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector2-5ek7j",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector2",
      "type": "topic",
      "url": "/documentation/simd/vector2-5ek7j"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_short2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vector_short2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_short2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vector_short2"
        }
      ],
      "role": "symbol",
      "title": "vector_short2",
      "type": "topic",
      "url": "/documentation/simd/vector_short2"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s5Int16V": {
      "abstract": [
        {
          "text": "A 16-bit signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int16"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5Int16V",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int16",
      "type": "topic",
      "url": "/documentation/Swift/Int16"
    },
    "doc://com.externally.resolved.symbol/s:s5SIMD2V": {
      "abstract": [
        {
          "text": "A vector of two scalar values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SIMD2"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SIMDScalarP",
          "text": "SIMDScalar"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5SIMD2V",
      "kind": "symbol",
      "role": "symbol",
      "title": "SIMD2",
      "type": "topic",
      "url": "/documentation/Swift/SIMD2"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Vector-Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_short1",
        "doc://com.apple.accelerate/documentation/simd/simd_short3",
        "doc://com.apple.accelerate/documentation/simd/simd_short4",
        "doc://com.apple.accelerate/documentation/simd/simd_short8",
        "doc://com.apple.accelerate/documentation/simd/simd_short16",
        "doc://com.apple.accelerate/documentation/simd/simd_short32"
      ],
      "title": "Vector Data Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Functions-to-Create-Two-Element-Vectors-From-Other-Vectors",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:)-6juuy",
        "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:)-6gmv7",
        "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:)-5z7ps",
        "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:)-74zg4",
        "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:)-58qns",
        "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:)-6bz90"
      ],
      "title": "Functions to Create Two-Element Vectors From Other Vectors"
    },
    {
      "anchor": "Functions-to-Create-Two-Element-Vectors-From-Scalar-Values",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:)-222xa",
        "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:_:)",
        "doc://com.apple.accelerate/documentation/simd/simd_make_short2_undef(_:)"
      ],
      "title": "Functions to Create Two-Element Vectors From Scalar Values"
    },
    {
      "anchor": "Common-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_abs(_:)-88dfi",
        "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-5qqhe",
        "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-6gad6"
      ],
      "title": "Common Functions"
    },
    {
      "anchor": "Reduce-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-49c4w",
        "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-4kmuw",
        "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-2q65m"
      ],
      "title": "Reduce Functions"
    },
    {
      "anchor": "Extrema-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-13ip4",
        "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-6w9rg"
      ],
      "title": "Extrema Functions"
    },
    {
      "anchor": "Logic-and-Bitwise-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-64jj5",
        "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1d5nj",
        "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-625jo"
      ],
      "title": "Logic and Bitwise Functions"
    },
    {
      "anchor": "Alternative-Type-Alias",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/vector_short2"
      ],
      "title": "Alternative Type Alias"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "simd_short2"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/simd"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Functions-to-Create-Two-Element-Vectors-From-Other-Vectors",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:)-6juuy",
                "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:)-6gmv7",
                "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:)-5z7ps",
                "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:)-74zg4",
                "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:)-58qns",
                "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:)-6bz90"
              ],
              "title": "Functions to Create Two-Element Vectors From Other Vectors"
            },
            {
              "anchor": "Functions-to-Create-Two-Element-Vectors-From-Scalar-Values",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:)-222xa",
                "doc://com.apple.accelerate/documentation/simd/simd_make_short2(_:_:)",
                "doc://com.apple.accelerate/documentation/simd/vector2-5ek7j",
                "doc://com.apple.accelerate/documentation/simd/simd_make_short2_undef(_:)"
              ],
              "title": "Functions to Create Two-Element Vectors From Scalar Values"
            },
            {
              "anchor": "Functions-to-Create-Two-Element-Vectors-From-Vectors-of-Other-Types",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_short-6f37y",
                "doc://com.apple.accelerate/documentation/simd/simd_short-6et5a",
                "doc://com.apple.accelerate/documentation/simd/simd_short-6ey3y",
                "doc://com.apple.accelerate/documentation/simd/simd_short-6eoa6",
                "doc://com.apple.accelerate/documentation/simd/simd_short-6f6bm",
                "doc://com.apple.accelerate/documentation/simd/simd_short-6ewci",
                "doc://com.apple.accelerate/documentation/simd/simd_short-6f4tm",
                "doc://com.apple.accelerate/documentation/simd/simd_short-6eusq",
                "doc://com.apple.accelerate/documentation/simd/simd_short-6erke",
                "doc://com.apple.accelerate/documentation/simd/simd_short-6esiy"
              ],
              "title": "Functions to Create Two-Element Vectors From Vectors of Other Types"
            },
            {
              "anchor": "Functions-to-Perform-Saturating-Conversion-From-Vectors-of-Other-Types",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3md2f",
                "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3mn6v",
                "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3m83r",
                "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3mi6f",
                "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3mg4b",
                "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3mqaj",
                "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3mfdp",
                "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3mpct",
                "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3mm1h",
                "doc://com.apple.accelerate/documentation/simd/simd_short_sat-3mmpp"
              ],
              "title": "Functions to Perform Saturating Conversion From Vectors of Other Types"
            },
            {
              "anchor": "Common-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_abs(_:)-88dfi",
                "doc://com.apple.accelerate/documentation/simd/simd_clamp(_:_:_:)-5qqhe",
                "doc://com.apple.accelerate/documentation/simd/simd_equal(_:_:)-6gad6"
              ],
              "title": "Common Functions"
            },
            {
              "anchor": "Reduce-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_reduce_min(_:)-49c4w",
                "doc://com.apple.accelerate/documentation/simd/simd_reduce_max(_:)-4kmuw",
                "doc://com.apple.accelerate/documentation/simd/simd_reduce_add(_:)-2q65m"
              ],
              "title": "Reduce Functions"
            },
            {
              "anchor": "Extrema-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_min(_:_:)-13ip4",
                "doc://com.apple.accelerate/documentation/simd/simd_max(_:_:)-6w9rg"
              ],
              "title": "Extrema Functions"
            },
            {
              "anchor": "Logic-and-Bitwise-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_any(_:)-64jj5",
                "doc://com.apple.accelerate/documentation/simd/simd_all(_:)-1d5nj",
                "doc://com.apple.accelerate/documentation/simd/simd_bitselect(_:_:_:)-625jo"
              ],
              "title": "Logic and Bitwise Functions"
            },
            {
              "anchor": "Alternative-Type-Alias",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/vector_short2"
              ],
              "title": "Alternative Type Alias"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Vector-Data-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_short1",
                "doc://com.apple.accelerate/documentation/simd/simd_short3",
                "doc://com.apple.accelerate/documentation/simd/simd_short4",
                "doc://com.apple.accelerate/documentation/simd/simd_short8",
                "doc://com.apple.accelerate/documentation/simd/simd_short16",
                "doc://com.apple.accelerate/documentation/simd/simd_short32"
              ],
              "title": "Vector Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:]2S",
                    "text": "short __attribute__((ext_vector_type(2)))"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "simd_short2"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_min(_:_:)-13ip4/title",
          "value": "simd_min"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_min(_:_:)-13ip4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_min"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_abs(_:)-88dfi/title",
          "value": "simd_abs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_abs(_:)-88dfi/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_abs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short2(_:)-6juuy/title",
          "value": "simd_make_short2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short2(_:)-6juuy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short2(_:)-58qns/title",
          "value": "simd_make_short2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short2(_:)-58qns/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short8/title",
          "value": "simd_short8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_any(_:)-64jj5/title",
          "value": "simd_any"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_any(_:)-64jj5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_any"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short1/title",
          "value": "simd_short1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short1/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short2(_:)-74zg4/title",
          "value": "simd_make_short2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short2(_:)-74zg4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short3/title",
          "value": "simd_short3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_bitselect(_:_:_:)-625jo/title",
          "value": "simd_bitselect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_bitselect(_:_:_:)-625jo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_bitselect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1vector_short2/title",
          "value": "vector_short2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1vector_short2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vector_short2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1vector_short2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vector_short2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short16/title",
          "value": "simd_short16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short16/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_add(_:)-2q65m/title",
          "value": "simd_reduce_add"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_add(_:)-2q65m/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_add"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short4/title",
          "value": "simd_short4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_clamp(_:_:_:)-5qqhe/title",
          "value": "simd_clamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_clamp(_:_:_:)-5qqhe/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_clamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short2/title",
          "value": "simd_short2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short2(_:)-6gmv7/title",
          "value": "simd_make_short2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short2(_:)-6gmv7/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short2(_:_:)/title",
          "value": "simd_make_short2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short2(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_equal(_:_:)-6gad6/title",
          "value": "simd_equal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_equal(_:_:)-6gad6/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_equal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_max(_:_:)-6w9rg/title",
          "value": "simd_max"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_max(_:_:)-6w9rg/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_max"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short2(_:)-222xa/title",
          "value": "simd_make_short2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short2(_:)-222xa/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short2_undef(_:)/title",
          "value": "simd_make_short2_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short2_undef(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short2_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short2(_:)-5z7ps/title",
          "value": "simd_make_short2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short2(_:)-5z7ps/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short32/title",
          "value": "simd_short32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short32/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short2(_:)-6bz90/title",
          "value": "simd_make_short2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short2(_:)-6bz90/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_all(_:)-1d5nj/title",
          "value": "simd_all"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_all(_:)-1d5nj/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_all"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_max(_:)-4kmuw/title",
          "value": "simd_reduce_max"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_max(_:)-4kmuw/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_max"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_min(_:)-49c4w/title",
          "value": "simd_reduce_min"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_reduce_min(_:)-49c4w/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_reduce_min"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_short2"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/simd/simd_short2"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
