{
  "abstract": [
    {
      "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_ushort-5bvzm"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_ushort#]32s#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_ushort"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_ushort"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_ushort"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort32",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_ushort32",
              "text": "simd_ushort32"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_ushort"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort32",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_ushort32",
              "text": "simd_ushort32"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort-5bm2a": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort-5bm2a",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort-5bm2a"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort-5br1u": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort-5br1u",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort-5br1u"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort-5bvzm": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort-5bvzm",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort-5bvzm"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort-5c12q": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_ushort"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort-5c12q",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_ushort",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort-5c12q"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ushort32": {
      "abstract": [
        {
          "text": "A vector of thirty-two 16-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ushort32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ushort32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ushort32"
        }
      ],
      "role": "symbol",
      "title": "simd_ushort32",
      "type": "topic",
      "url": "/documentation/simd/simd_ushort32"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Create-Thirty-Two-Element-Vectors-From-Vectors-of-Other-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_ushort-5br1u",
        "doc://com.apple.accelerate/documentation/simd/simd_ushort-5c12q",
        "doc://com.apple.accelerate/documentation/simd/simd_ushort-5bm2a"
      ],
      "title": "Functions to Create Thirty Two-Element Vectors From Vectors of Other Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort32/title",
          "value": "simd_ushort32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ushort32/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ushort32"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_ushort-5bvzm"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
