{
  "abstract": [
    {
      "text": "Returns a new vector from the specified vectors.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_make_long8(_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_make_long8#]4L#S0_#",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simd_make_long8"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_long4",
        "text": "simd_long4"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_long4",
        "text": "simd_long4"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_long8",
        "text": "simd_long8"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_make_long8"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_make_long8(_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_make_long8"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "lo"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long4",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_long4",
              "text": "simd_long4"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "hi"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long4",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_long4",
              "text": "simd_long4"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long8",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_long8",
              "text": "simd_long8"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long4": {
      "abstract": [
        {
          "text": "A vector of four 64-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_long4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_long4"
        }
      ],
      "role": "symbol",
      "title": "simd_long4",
      "type": "topic",
      "url": "/documentation/simd/simd_long4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long8": {
      "abstract": [
        {
          "text": "A vector of eight 64-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_long8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_long8"
        }
      ],
      "role": "symbol",
      "title": "simd_long8",
      "type": "topic",
      "url": "/documentation/simd/simd_long8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_long8(_:)-6saal": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_long8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long8",
          "text": "simd_long8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long8",
          "text": "simd_long8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_long8(_:)-6saal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_long8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_long8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_long8(_:)-6saal"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_long8(_:)-7netg": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified three-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_long8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long3",
          "text": "simd_long3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long8",
          "text": "simd_long8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_long8(_:)-7netg",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_long8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_long8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_long8(_:)-7netg"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_long8(_:)-7pzt7": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_long8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long2",
          "text": "simd_long2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long8",
          "text": "simd_long8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_long8(_:)-7pzt7",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_long8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_long8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_long8(_:)-7pzt7"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_long8(_:)-7wvxt": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified four-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_long8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long4",
          "text": "simd_long4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long8",
          "text": "simd_long8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_long8(_:)-7wvxt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_long8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_long8(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_long8(_:)-7wvxt"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_long8(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_long8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long4",
          "text": "simd_long4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long4",
          "text": "simd_long4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long8",
          "text": "simd_long8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_long8(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_long8"
        }
      ],
      "role": "symbol",
      "title": "simd_make_long8(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_long8(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_long8_undef(_:)-59t0j": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified four-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_long8_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long4",
          "text": "simd_long4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long8",
          "text": "simd_long8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_long8_undef(_:)-59t0j",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_long8_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_long8_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_long8_undef(_:)-59t0j"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_long8_undef(_:)-5uowh": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_long8_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long2",
          "text": "simd_long2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long8",
          "text": "simd_long8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_long8_undef(_:)-5uowh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_long8_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_long8_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_long8_undef(_:)-5uowh"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_long8_undef(_:)-5y3qm": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified three-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_long8_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long3",
          "text": "simd_long3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long8",
          "text": "simd_long8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_long8_undef(_:)-5y3qm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_long8_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_long8_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_long8_undef(_:)-5y3qm"
    },
    "doc://com.apple.accelerate/documentation/simd/vector8-6qxy0": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector8-6qxy0",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector8",
      "type": "topic",
      "url": "/documentation/simd/vector8-6qxy0"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Create-Eight-Element-Vectors-From-Other-Vectors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_long8(_:)-7pzt7",
        "doc://com.apple.accelerate/documentation/simd/simd_make_long8(_:)-7netg",
        "doc://com.apple.accelerate/documentation/simd/simd_make_long8(_:)-7wvxt",
        "doc://com.apple.accelerate/documentation/simd/simd_make_long8(_:)-6saal",
        "doc://com.apple.accelerate/documentation/simd/simd_make_long8_undef(_:)-5uowh",
        "doc://com.apple.accelerate/documentation/simd/simd_make_long8_undef(_:)-5y3qm",
        "doc://com.apple.accelerate/documentation/simd/simd_make_long8_undef(_:)-59t0j"
      ],
      "title": "Functions to Create Eight-Element Vectors From Other Vectors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "simd_make_long8"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_long8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/simd"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Functions-to-Create-Eight-Element-Vectors-From-Other-Vectors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_long8(_:)-7pzt7",
                "doc://com.apple.accelerate/documentation/simd/simd_make_long8(_:)-7netg",
                "doc://com.apple.accelerate/documentation/simd/simd_make_long8(_:)-7wvxt",
                "doc://com.apple.accelerate/documentation/simd/simd_make_long8(_:)-6saal",
                "doc://com.apple.accelerate/documentation/simd/vector8-6qxy0",
                "doc://com.apple.accelerate/documentation/simd/simd_make_long8_undef(_:)-5uowh",
                "doc://com.apple.accelerate/documentation/simd/simd_make_long8_undef(_:)-5y3qm",
                "doc://com.apple.accelerate/documentation/simd/simd_make_long8_undef(_:)-59t0j"
              ],
              "title": "Functions to Create Eight-Element Vectors From Other Vectors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "static"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long8",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_long8",
                    "text": "simd_long8"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "simd_make_long8"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long4",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_long4",
                    "text": "simd_long4"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "lo"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long4",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_long4",
                    "text": "simd_long4"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "hi"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_long8_undef(_:)-5y3qm/title",
          "value": "simd_make_long8_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_long8_undef(_:)-5y3qm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_long8_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_long8(_:)-6saal/title",
          "value": "simd_make_long8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_long8(_:)-6saal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_long8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long8/title",
          "value": "simd_long8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_long8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_long8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_long8_undef(_:)-59t0j/title",
          "value": "simd_make_long8_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_long8_undef(_:)-59t0j/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_long8_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long4/title",
          "value": "simd_long4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_long4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_long4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_long8_undef(_:)-5uowh/title",
          "value": "simd_make_long8_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_long8_undef(_:)-5uowh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_long8_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_long8(_:_:)/title",
          "value": "simd_make_long8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_long8(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_long8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_long8(_:)-7pzt7/title",
          "value": "simd_make_long8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_long8(_:)-7pzt7/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_long8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_long8(_:)-7netg/title",
          "value": "simd_make_long8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_long8(_:)-7netg/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_long8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_long8(_:)-7wvxt/title",
          "value": "simd_make_long8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_long8(_:)-7wvxt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_long8"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_make_long8(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/simd/simd_make_long8(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
