{
  "abstract": [
    {
      "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_int_sat-67sad"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_int_sat#]4c#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_int_sat"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_int_sat"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_int_sat"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int4",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_int4",
              "text": "simd_int4"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_int_sat"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar4",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_uchar4",
              "text": "simd_uchar4"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int4": {
      "abstract": [
        {
          "text": "A vector of four 32-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_int4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_int4"
        }
      ],
      "role": "symbol",
      "title": "simd_int4",
      "type": "topic",
      "url": "/documentation/simd/simd_int4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int_sat-67nat": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int_sat-67nat",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_int_sat-67nat"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int_sat-67sad": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int_sat-67sad",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_int_sat-67sad"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int_sat-67sbj": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int_sat-67sbj",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_int_sat-67sbj"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int_sat-67t8j": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int_sat-67t8j",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_int_sat-67t8j"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int_sat-67tx9": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int_sat-67tx9",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_int_sat-67tx9"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int_sat-67uyn": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int_sat-67uyn",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_int_sat-67uyn"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int_sat-67x4l": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int_sat-67x4l",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_int_sat-67x4l"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6820l": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6820l",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_int_sat-6820l"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int_sat-68459": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int_sat-68459",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_int_sat-68459"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_int_sat-684sf": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_int_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_int_sat-684sf",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_int_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_int_sat-684sf"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uchar4": {
      "abstract": [
        {
          "text": "A vector of four 8-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uchar4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uchar4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uchar4"
        }
      ],
      "role": "symbol",
      "title": "simd_uchar4",
      "type": "topic",
      "url": "/documentation/simd/simd_uchar4"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Perform-Saturating-Conversion-From-Vectors-of-Other-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_int_sat-6820l",
        "doc://com.apple.accelerate/documentation/simd/simd_int_sat-67x4l",
        "doc://com.apple.accelerate/documentation/simd/simd_int_sat-67nat",
        "doc://com.apple.accelerate/documentation/simd/simd_int_sat-68459",
        "doc://com.apple.accelerate/documentation/simd/simd_int_sat-67tx9",
        "doc://com.apple.accelerate/documentation/simd/simd_int_sat-684sf",
        "doc://com.apple.accelerate/documentation/simd/simd_int_sat-67uyn",
        "doc://com.apple.accelerate/documentation/simd/simd_int_sat-67t8j",
        "doc://com.apple.accelerate/documentation/simd/simd_int_sat-67sbj"
      ],
      "title": "Functions to Perform Saturating Conversion From Vectors of Other Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar4/title",
          "value": "simd_uchar4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uchar4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uchar4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int4/title",
          "value": "simd_int4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_int4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_int4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_int4"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_int_sat-67sad"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
