{
  "abstract": [
    {
      "text": "A matrix of three columns and four rows that contains double-precision values.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_double3x4"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@SA@simd_double3x4",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simd_double3x4"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_double3x4"
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "simd_double3x4"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_double3x4"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/double3x4": {
      "abstract": [
        {
          "text": "A type alias for a double-precision 3 x 4 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "double3x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/double3x4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "double3x4"
        }
      ],
      "role": "symbol",
      "title": "double3x4",
      "type": "topic",
      "url": "/documentation/simd/double3x4"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_double3x4": {
      "abstract": [
        {
          "text": "A type alias for a double-precision 3 x 4 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matrix_double3x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_double3x4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "matrix_double3x4"
        }
      ],
      "role": "symbol",
      "title": "matrix_double3x4",
      "type": "topic",
      "url": "/documentation/simd/matrix_double3x4"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_equal(_:_:)-4qog1": {
      "abstract": [
        {
          "text": "Returns true if every element in a matrix is exactly equal to the corresponding element in a second matrix, and otherwise returns false.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matrix_equal"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double3x4",
          "text": "simd_double3x4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double3x4",
          "text": "simd_double3x4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_equal(_:_:)-4qog1",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_equal(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/matrix_equal(_:_:)-4qog1"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_from_columns(_:_:_:)-4no1k": {
      "abstract": [
        {
          "text": "Returns a new matrix with the specified columns.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matrix_from_columns"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD4V",
          "text": "SIMD4"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD4V",
          "text": "SIMD4"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD4V",
          "text": "SIMD4"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double3x4",
          "text": "simd_double3x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_from_columns(_:_:_:)-4no1k",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_from_columns(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/matrix_from_columns(_:_:_:)-4no1k"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_from_rows(_:_:_:_:)-69xld": {
      "abstract": [
        {
          "text": "Returns a new matrix with the specified rows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matrix_from_rows"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD3V",
          "text": "SIMD3"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD3V",
          "text": "SIMD3"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD3V",
          "text": "SIMD3"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD3V",
          "text": "SIMD3"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double3x4",
          "text": "simd_double3x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_from_rows(_:_:_:_:)-69xld",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_from_rows(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/matrix_from_rows(_:_:_:_:)-69xld"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_multiply-5wjn1": {
      "abstract": [
        {
          "text": "Returns the product of a 2 x 4 matrix and a 3 x 2 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "matrix_multiply"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_multiply-5wjn1",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_multiply",
      "type": "topic",
      "url": "/documentation/simd/matrix_multiply-5wjn1"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_multiply-6ga2h": {
      "abstract": [
        {
          "text": "Returns the product of a 3 x 4 matrix and a 3 x 3 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "matrix_multiply"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_multiply-6ga2h",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_multiply",
      "type": "topic",
      "url": "/documentation/simd/matrix_multiply-6ga2h"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_multiply-8rk6t": {
      "abstract": [
        {
          "text": "Returns the product of a four-element vector and a 3 x 4 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "matrix_multiply"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_multiply-8rk6t",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_multiply",
      "type": "topic",
      "url": "/documentation/simd/matrix_multiply-8rk6t"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_multiply-8xc78": {
      "abstract": [
        {
          "text": "Returns the product of a 4 x 4 matrix and a 3 x 4 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "matrix_multiply"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_multiply-8xc78",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_multiply",
      "type": "topic",
      "url": "/documentation/simd/matrix_multiply-8xc78"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_multiply-f05e": {
      "abstract": [
        {
          "text": "Returns the product of a 3 x 4 matrix and a three-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "matrix_multiply"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_multiply-f05e",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_multiply",
      "type": "topic",
      "url": "/documentation/simd/matrix_multiply-f05e"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_scale-5ie6g": {
      "abstract": [
        {
          "text": "Returns the product of a scalar value and a matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "matrix_scale"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_scale-5ie6g",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_scale",
      "type": "topic",
      "url": "/documentation/simd/matrix_scale-5ie6g"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_transpose(_:)-8am0o": {
      "abstract": [
        {
          "text": "Returns the transpose of a matrix.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matrix_transpose"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double4x3",
          "text": "simd_double4x3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:4simd9double3x4a",
          "text": "double3x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_transpose(_:)-8am0o",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_transpose(_:)",
      "type": "topic",
      "url": "/documentation/simd/matrix_transpose(_:)-8am0o"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_add-53ag9": {
      "abstract": [
        {
          "text": "Returns the sum of two matrices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_add"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_add-53ag9",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_add",
      "type": "topic",
      "url": "/documentation/simd/simd_add-53ag9"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_almost_equal_elements-h72t": {
      "abstract": [
        {
          "text": "Returns true if every element in a matrix is within a specified tolerance to the corresponding element in a second matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_almost_equal_elements"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_almost_equal_elements-h72t",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_almost_equal_elements",
      "type": "topic",
      "url": "/documentation/simd/simd_almost_equal_elements-h72t"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_almost_equal_elements_relative-9q7od": {
      "abstract": [
        {
          "text": "Returns true if every element in a matrix is within a specified double-precision relative tolerance to the corresponding element in a second matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_almost_equal_elements_relative"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_almost_equal_elements_relative-9q7od",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_almost_equal_elements_relative",
      "type": "topic",
      "url": "/documentation/simd/simd_almost_equal_elements_relative-9q7od"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double2x2": {
      "abstract": [
        {
          "text": "A matrix of two columns and two rows that contains double-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_double2x2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double2x2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_double2x2"
        }
      ],
      "role": "symbol",
      "title": "simd_double2x2",
      "type": "topic",
      "url": "/documentation/simd/simd_double2x2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double2x3": {
      "abstract": [
        {
          "text": "A matrix of two columns and three rows that contains double-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_double2x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double2x3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_double2x3"
        }
      ],
      "role": "symbol",
      "title": "simd_double2x3",
      "type": "topic",
      "url": "/documentation/simd/simd_double2x3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double2x4": {
      "abstract": [
        {
          "text": "A matrix of two columns and four rows that contains double-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_double2x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double2x4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_double2x4"
        }
      ],
      "role": "symbol",
      "title": "simd_double2x4",
      "type": "topic",
      "url": "/documentation/simd/simd_double2x4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double3x2": {
      "abstract": [
        {
          "text": "A matrix of three columns and two rows that contains double-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_double3x2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double3x2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_double3x2"
        }
      ],
      "role": "symbol",
      "title": "simd_double3x2",
      "type": "topic",
      "url": "/documentation/simd/simd_double3x2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double3x3": {
      "abstract": [
        {
          "text": "A matrix of three columns and three rows that contains double-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_double3x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double3x3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_double3x3"
        }
      ],
      "role": "symbol",
      "title": "simd_double3x3",
      "type": "topic",
      "url": "/documentation/simd/simd_double3x3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double3x4": {
      "abstract": [
        {
          "text": "A matrix of three columns and four rows that contains double-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_double3x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double3x4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_double3x4"
        }
      ],
      "role": "symbol",
      "title": "simd_double3x4",
      "type": "topic",
      "url": "/documentation/simd/simd_double3x4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double3x4/*(_:_:)-15q5b": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "*"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double3x4",
          "text": "simd_double3x4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:4simd9double2x3a",
          "text": "double2x3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:4simd9double2x4a",
          "text": "double2x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double3x4/*(_:_:)-15q5b",
      "kind": "symbol",
      "role": "symbol",
      "title": "*(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double3x4/*(_:_:)-15q5b"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double3x4/*(_:_:)-2qxoj": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "*"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double3x4",
          "text": "simd_double3x4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double3x4",
          "text": "simd_double3x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double3x4/*(_:_:)-2qxoj",
      "kind": "symbol",
      "role": "symbol",
      "title": "*(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double3x4/*(_:_:)-2qxoj"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double3x4/*(_:_:)-3xyct": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "*"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD4V",
          "text": "SIMD4"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double3x4",
          "text": "simd_double3x4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD3V",
          "text": "SIMD3"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double3x4/*(_:_:)-3xyct",
      "kind": "symbol",
      "role": "symbol",
      "title": "*(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double3x4/*(_:_:)-3xyct"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double3x4/*(_:_:)-4g9jd": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "*"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double3x4",
          "text": "simd_double3x4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD3V",
          "text": "SIMD3"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD4V",
          "text": "SIMD4"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double3x4/*(_:_:)-4g9jd",
      "kind": "symbol",
      "role": "symbol",
      "title": "*(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double3x4/*(_:_:)-4g9jd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double3x4/*(_:_:)-4qzww": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "*"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double3x4",
          "text": "simd_double3x4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double3x4",
          "text": "simd_double3x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double3x4/*(_:_:)-4qzww",
      "kind": "symbol",
      "role": "symbol",
      "title": "*(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double3x4/*(_:_:)-4qzww"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double3x4/*(_:_:)-6qa2j": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "*"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double3x4",
          "text": "simd_double3x4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:4simd9double3x3a",
          "text": "double3x3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:4simd9double3x4a",
          "text": "double3x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double3x4/*(_:_:)-6qa2j",
      "kind": "symbol",
      "role": "symbol",
      "title": "*(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double3x4/*(_:_:)-6qa2j"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double3x4/*(_:_:)-962p4": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "*"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double3x4",
          "text": "simd_double3x4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:4simd9double4x3a",
          "text": "double4x3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:4simd9double4x4a",
          "text": "double4x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double3x4/*(_:_:)-962p4",
      "kind": "symbol",
      "role": "symbol",
      "title": "*(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double3x4/*(_:_:)-962p4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double3x4/*=(_:_:)-62fjm": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "*="
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "inout"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double3x4",
          "text": "simd_double3x4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double3x4/*=(_:_:)-62fjm",
      "kind": "symbol",
      "role": "symbol",
      "title": "*=(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double3x4/*=(_:_:)-62fjm"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double3x4/*=(_:_:)-sjb5": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "*="
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "inout"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double3x4",
          "text": "simd_double3x4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:4simd9double3x3a",
          "text": "double3x3"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double3x4/*=(_:_:)-sjb5",
      "kind": "symbol",
      "role": "symbol",
      "title": "*=(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double3x4/*=(_:_:)-sjb5"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double3x4/+(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "+"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double3x4",
          "text": "simd_double3x4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double3x4",
          "text": "simd_double3x4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double3x4",
          "text": "simd_double3x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double3x4/+(_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "+(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double3x4/+(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double3x4/+=(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "+="
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "inout"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double3x4",
          "text": "simd_double3x4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double3x4",
          "text": "simd_double3x4"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double3x4/+=(_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "+=(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double3x4/+=(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double3x4/-(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "-"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double3x4",
          "text": "simd_double3x4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double3x4",
          "text": "simd_double3x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double3x4/-(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "-(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double3x4/-(_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double3x4/-(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "-"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double3x4",
          "text": "simd_double3x4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double3x4",
          "text": "simd_double3x4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double3x4",
          "text": "simd_double3x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double3x4/-(_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "-(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double3x4/-(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double3x4/-=(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "-="
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "inout"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double3x4",
          "text": "simd_double3x4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double3x4",
          "text": "simd_double3x4"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double3x4/-=(_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "-=(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double3x4/-=(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double3x4/cmatrix": {
      "abstract": [
        {
          "text": "Returns the matrix as the corresponding C matrix type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cmatrix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double3x4",
          "text": "simd_double3x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double3x4/cmatrix",
      "kind": "symbol",
      "role": "symbol",
      "title": "cmatrix",
      "type": "topic",
      "url": "/documentation/simd/simd_double3x4/cmatrix"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double3x4/columns": {
      "abstract": [
        {
          "text": "The columns of the matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "columns"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double3x4/columns",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "columns"
        }
      ],
      "role": "symbol",
      "title": "columns",
      "type": "topic",
      "url": "/documentation/simd/simd_double3x4/columns"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double3x4/init()": {
      "abstract": [
        {
          "text": "Creates a new matrix with uninitialized memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double3x4/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/simd/simd_double3x4/init()"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double3x4/init(_:)-11lc1": {
      "abstract": [
        {
          "text": "Creates a new matrix with the specified scalar value on the main diagonal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double3x4/init(_:)-11lc1",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double3x4/init(_:)-11lc1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double3x4/init(_:)-2qvpe": {
      "abstract": [
        {
          "text": "Creates a new matrix with the specified matrix.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double3x4",
          "text": "simd_double3x4"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double3x4/init(_:)-2qvpe",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double3x4/init(_:)-2qvpe"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double3x4/init(_:)-74wu4": {
      "abstract": [
        {
          "text": "Creates a new matrix from an array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD4V",
          "text": "SIMD4"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">])"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double3x4/init(_:)-74wu4",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double3x4/init(_:)-74wu4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double3x4/init(_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a new matrix with the specified vectors as columns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD4V",
          "text": "SIMD4"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD4V",
          "text": "SIMD4"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD4V",
          "text": "SIMD4"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double3x4/init(_:_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double3x4/init(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double3x4/init(columns:)": {
      "abstract": [
        {
          "text": "Creates a new matrix with the specified columns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "columns"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        },
        {
          "kind": "text",
          "text": "))"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double3x4/init(columns:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(columns:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double3x4/init(columns:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double3x4/init(diagonal:)": {
      "abstract": [
        {
          "text": "Creates a new matrix with the specified vector on the main diagonal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "diagonal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD3V",
          "text": "SIMD3"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double3x4/init(diagonal:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(diagonal:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double3x4/init(diagonal:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double3x4/init(rows:)": {
      "abstract": [
        {
          "text": "Creates a new matrix with the specified rows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rows"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD3V",
          "text": "SIMD3"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">])"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double3x4/init(rows:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rows:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double3x4/init(rows:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double3x4/subscript(_:)": {
      "abstract": [
        {
          "text": "Accesses the column at the specified position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD4V",
          "text": "SIMD4"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double3x4/subscript(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscript(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double3x4/subscript(_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double3x4/subscript(_:_:)": {
      "abstract": [
        {
          "text": "Accesses the element at the specified position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double3x4/subscript(_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscript(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double3x4/subscript(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double3x4/transpose": {
      "abstract": [
        {
          "text": "The transpose of the matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transpose"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:4simd9double4x3a",
          "text": "double4x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double3x4/transpose",
      "kind": "symbol",
      "role": "symbol",
      "title": "transpose",
      "type": "topic",
      "url": "/documentation/simd/simd_double3x4/transpose"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double4x2": {
      "abstract": [
        {
          "text": "A matrix of four columns and two rows that contains double-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_double4x2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4x2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_double4x2"
        }
      ],
      "role": "symbol",
      "title": "simd_double4x2",
      "type": "topic",
      "url": "/documentation/simd/simd_double4x2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double4x3": {
      "abstract": [
        {
          "text": "A matrix of four columns and three rows that contains double-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_double4x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4x3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_double4x3"
        }
      ],
      "role": "symbol",
      "title": "simd_double4x3",
      "type": "topic",
      "url": "/documentation/simd/simd_double4x3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double4x4": {
      "abstract": [
        {
          "text": "A matrix of four columns and four rows that contains double-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_double4x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4x4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_double4x4"
        }
      ],
      "role": "symbol",
      "title": "simd_double4x4",
      "type": "topic",
      "url": "/documentation/simd/simd_double4x4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_equal-4m10u": {
      "abstract": [
        {
          "text": "Returns true if every element in a matrix is exactly equal to the corresponding element in a second matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_equal"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_equal-4m10u",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_equal",
      "type": "topic",
      "url": "/documentation/simd/simd_equal-4m10u"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_linear_combination-2oumb": {
      "abstract": [
        {
          "text": "Returns the linear combination of two scalar values and two matrices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_linear_combination"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_linear_combination-2oumb",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_linear_combination",
      "type": "topic",
      "url": "/documentation/simd/simd_linear_combination-2oumb"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_matrix(_:_:_:)-4o4n5": {
      "abstract": [
        {
          "text": "Returns a new matrix with the specified columns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_matrix"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double3x4",
          "text": "simd_double3x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_matrix(_:_:_:)-4o4n5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_matrix"
        }
      ],
      "role": "symbol",
      "title": "simd_matrix(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_matrix(_:_:_:)-4o4n5"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_matrix_from_rows(_:_:_:_:)-7j052": {
      "abstract": [
        {
          "text": "Returns a new matrix with the specified rows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_matrix_from_rows"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double3",
          "text": "simd_double3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double3",
          "text": "simd_double3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double3",
          "text": "simd_double3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double3",
          "text": "simd_double3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double3x4",
          "text": "simd_double3x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_matrix_from_rows(_:_:_:_:)-7j052",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_matrix_from_rows"
        }
      ],
      "role": "symbol",
      "title": "simd_matrix_from_rows(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_matrix_from_rows(_:_:_:_:)-7j052"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_mul-3kj8k": {
      "abstract": [
        {
          "text": "Returns the product of a 3 x 4 matrix and a three-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_mul"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_mul-3kj8k",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_mul",
      "type": "topic",
      "url": "/documentation/simd/simd_mul-3kj8k"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_mul-5zv": {
      "abstract": [
        {
          "text": "Returns the product of a four-element vector and a 3 x 4 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_mul"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_mul-5zv",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_mul",
      "type": "topic",
      "url": "/documentation/simd/simd_mul-5zv"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_mul-6r1po": {
      "abstract": [
        {
          "text": "Returns the product of a scalar value and a 3 x 4 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_mul"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_mul-6r1po",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_mul",
      "type": "topic",
      "url": "/documentation/simd/simd_mul-6r1po"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_mul-9jaek": {
      "abstract": [
        {
          "text": "Returns the product of a 2 x 4 matrix and a 3 x 2 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_mul"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_mul-9jaek",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_mul",
      "type": "topic",
      "url": "/documentation/simd/simd_mul-9jaek"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_mul-hhfz": {
      "abstract": [
        {
          "text": "Returns the product of a 4 x 4 matrix and a 3 x 4 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_mul"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_mul-hhfz",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_mul",
      "type": "topic",
      "url": "/documentation/simd/simd_mul-hhfz"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_mul-tzji": {
      "abstract": [
        {
          "text": "Returns the product of a 3 x 4 matrix and a 3 x 3 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_mul"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_mul-tzji",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_mul",
      "type": "topic",
      "url": "/documentation/simd/simd_mul-tzji"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_sub-6yn8w": {
      "abstract": [
        {
          "text": "Returns the difference of two matrices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_sub"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_sub-6yn8w",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_sub",
      "type": "topic",
      "url": "/documentation/simd/simd_sub-6yn8w"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_transpose-26pwk": {
      "abstract": [
        {
          "text": "Returns the transpose of a matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_transpose"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_transpose-26pwk",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_transpose",
      "type": "topic",
      "url": "/documentation/simd/simd_transpose-26pwk"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s8CopyableP": {
      "abstract": [
        {
          "text": "A type whose values can be implicitly or explicitly copied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8CopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Copyable",
      "type": "topic",
      "url": "/documentation/Swift/Copyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:s8CopyableP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Matrix-structures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_double2x2",
        "doc://com.apple.accelerate/documentation/simd/simd_double2x3",
        "doc://com.apple.accelerate/documentation/simd/simd_double2x4",
        "doc://com.apple.accelerate/documentation/simd/simd_double3x2",
        "doc://com.apple.accelerate/documentation/simd/simd_double3x3",
        "doc://com.apple.accelerate/documentation/simd/simd_double4x2",
        "doc://com.apple.accelerate/documentation/simd/simd_double4x3",
        "doc://com.apple.accelerate/documentation/simd/simd_double4x4"
      ],
      "title": "Matrix structures"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_double3x4/init()",
        "doc://com.apple.accelerate/documentation/simd/simd_double3x4/init(_:)-11lc1",
        "doc://com.apple.accelerate/documentation/simd/simd_double3x4/init(diagonal:)",
        "doc://com.apple.accelerate/documentation/simd/simd_double3x4/init(_:)-74wu4",
        "doc://com.apple.accelerate/documentation/simd/simd_double3x4/init(_:_:_:)",
        "doc://com.apple.accelerate/documentation/simd/simd_double3x4/init(columns:)",
        "doc://com.apple.accelerate/documentation/simd/simd_double3x4/init(rows:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Matrix-Properties",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_double3x4/transpose",
        "doc://com.apple.accelerate/documentation/simd/simd_double3x4/columns"
      ],
      "title": "Matrix Properties"
    },
    {
      "anchor": "Matrix-Creation-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_matrix(_:_:_:)-4o4n5",
        "doc://com.apple.accelerate/documentation/simd/simd_matrix_from_rows(_:_:_:_:)-7j052",
        "doc://com.apple.accelerate/documentation/simd/matrix_from_rows(_:_:_:_:)-69xld"
      ],
      "title": "Matrix Creation Functions"
    },
    {
      "anchor": "Element-Access",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_double3x4/subscript(_:)",
        "doc://com.apple.accelerate/documentation/simd/simd_double3x4/subscript(_:_:)"
      ],
      "title": "Element Access"
    },
    {
      "anchor": "Type-Aliases",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/double3x4",
        "doc://com.apple.accelerate/documentation/simd/matrix_double3x4"
      ],
      "title": "Type Aliases"
    },
    {
      "anchor": "Deprecated-Symbols",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/matrix_equal(_:_:)-4qog1",
        "doc://com.apple.accelerate/documentation/simd/matrix_from_columns(_:_:_:)-4no1k",
        "doc://com.apple.accelerate/documentation/simd/matrix_transpose(_:)-8am0o",
        "doc://com.apple.accelerate/documentation/simd/simd_double3x4/init(_:)-2qvpe",
        "doc://com.apple.accelerate/documentation/simd/simd_double3x4/cmatrix"
      ],
      "title": "Deprecated Symbols"
    },
    {
      "anchor": "Operators",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_double3x4/*(_:_:)-15q5b",
        "doc://com.apple.accelerate/documentation/simd/simd_double3x4/*(_:_:)-2qxoj",
        "doc://com.apple.accelerate/documentation/simd/simd_double3x4/*(_:_:)-3xyct",
        "doc://com.apple.accelerate/documentation/simd/simd_double3x4/*(_:_:)-4g9jd",
        "doc://com.apple.accelerate/documentation/simd/simd_double3x4/*(_:_:)-4qzww",
        "doc://com.apple.accelerate/documentation/simd/simd_double3x4/*(_:_:)-6qa2j",
        "doc://com.apple.accelerate/documentation/simd/simd_double3x4/*(_:_:)-962p4",
        "doc://com.apple.accelerate/documentation/simd/simd_double3x4/*=(_:_:)-62fjm",
        "doc://com.apple.accelerate/documentation/simd/simd_double3x4/*=(_:_:)-sjb5",
        "doc://com.apple.accelerate/documentation/simd/simd_double3x4/+(_:_:)",
        "doc://com.apple.accelerate/documentation/simd/simd_double3x4/+=(_:_:)",
        "doc://com.apple.accelerate/documentation/simd/simd_double3x4/-(_:)",
        "doc://com.apple.accelerate/documentation/simd/simd_double3x4/-(_:_:)",
        "doc://com.apple.accelerate/documentation/simd/simd_double3x4/-=(_:_:)"
      ],
      "title": "Operators"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "simd_double3x4"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double3x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double3x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/simd"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Matrix-Properties",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_double3x4/columns"
              ],
              "title": "Matrix Properties"
            },
            {
              "anchor": "Matrix-Creation-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_matrix(_:_:_:)-4o4n5",
                "doc://com.apple.accelerate/documentation/simd/simd_matrix_from_rows(_:_:_:_:)-7j052"
              ],
              "title": "Matrix Creation Functions"
            },
            {
              "anchor": "Equality-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_equal-4m10u",
                "doc://com.apple.accelerate/documentation/simd/simd_almost_equal_elements-h72t",
                "doc://com.apple.accelerate/documentation/simd/simd_almost_equal_elements_relative-9q7od"
              ],
              "title": "Equality Functions"
            },
            {
              "anchor": "Math-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_add-53ag9",
                "doc://com.apple.accelerate/documentation/simd/simd_sub-6yn8w",
                "doc://com.apple.accelerate/documentation/simd/matrix_scale-5ie6g"
              ],
              "title": "Math Functions"
            },
            {
              "anchor": "Matrix-Scalar-Multiplication-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_mul-6r1po"
              ],
              "title": "Matrix-Scalar Multiplication Functions"
            },
            {
              "anchor": "Matrix-Vector-Multiplication-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_mul-5zv",
                "doc://com.apple.accelerate/documentation/simd/matrix_multiply-8rk6t",
                "doc://com.apple.accelerate/documentation/simd/simd_mul-3kj8k",
                "doc://com.apple.accelerate/documentation/simd/matrix_multiply-f05e"
              ],
              "title": "Matrix-Vector Multiplication Functions"
            },
            {
              "anchor": "Matrix-Matrix-Multiplication-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_mul-9jaek",
                "doc://com.apple.accelerate/documentation/simd/matrix_multiply-5wjn1",
                "doc://com.apple.accelerate/documentation/simd/simd_mul-tzji",
                "doc://com.apple.accelerate/documentation/simd/matrix_multiply-6ga2h",
                "doc://com.apple.accelerate/documentation/simd/simd_mul-hhfz",
                "doc://com.apple.accelerate/documentation/simd/matrix_multiply-8xc78"
              ],
              "title": "Matrix-Matrix Multiplication Functions"
            },
            {
              "anchor": "Linear-Combination-Function",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_linear_combination-2oumb"
              ],
              "title": "Linear Combination Function"
            },
            {
              "anchor": "Transpose-Function",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_transpose-26pwk"
              ],
              "title": "Transpose Function"
            },
            {
              "anchor": "Type-Aliases",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/matrix_double3x4"
              ],
              "title": "Type Aliases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Matrix-structures",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_double2x2",
                "doc://com.apple.accelerate/documentation/simd/simd_double2x3",
                "doc://com.apple.accelerate/documentation/simd/simd_double2x4",
                "doc://com.apple.accelerate/documentation/simd/simd_double3x2",
                "doc://com.apple.accelerate/documentation/simd/simd_double3x3",
                "doc://com.apple.accelerate/documentation/simd/simd_double4x2",
                "doc://com.apple.accelerate/documentation/simd/simd_double4x3",
                "doc://com.apple.accelerate/documentation/simd/simd_double4x4"
              ],
              "title": "Matrix structures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "simd_double3x4"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_matrix_from_rows(_:_:_:_:)-7j052/title",
          "value": "simd_matrix_from_rows"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_matrix_from_rows(_:_:_:_:)-7j052/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_matrix_from_rows"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double2x2/title",
          "value": "simd_double2x2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double2x2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double2x2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double2x2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double2x2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double3x3/title",
          "value": "simd_double3x3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double3x3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double3x3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double3x3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double3x3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4x3/title",
          "value": "simd_double4x3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4x3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double4x3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4x3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double4x3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4x2/title",
          "value": "simd_double4x2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4x2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double4x2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4x2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double4x2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_matrix(_:_:_:)-4o4n5/title",
          "value": "simd_matrix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_matrix(_:_:_:)-4o4n5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_matrix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double3x2/title",
          "value": "simd_double3x2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double3x2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double3x2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double3x2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double3x2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double3x4/title",
          "value": "simd_double3x4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double3x4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double3x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double3x4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double3x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double2x4/title",
          "value": "simd_double2x4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double2x4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double2x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double2x4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double2x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4x4/title",
          "value": "simd_double4x4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4x4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double4x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4x4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double4x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double2x3/title",
          "value": "simd_double2x3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double2x3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double2x3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double2x3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double2x3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1matrix_double3x4/title",
          "value": "matrix_double3x4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1matrix_double3x4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "matrix_double3x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1matrix_double3x4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "matrix_double3x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double3x4~1columns/title",
          "value": "columns"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double3x4~1columns/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "columns"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_double3x4"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/simd/simd_double3x4"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
