{
  "abstract": [
    {
      "text": "Returns a new vector from the specified vector of 64-bit, unsigned-integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_double-50irj"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_double#]3l#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_double"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_double"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_double"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double3",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_double3",
              "text": "simd_double3"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_double"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong3",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_ulong3",
              "text": "simd_ulong3"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double-50at1": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double-50at1",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_double",
      "type": "topic",
      "url": "/documentation/simd/simd_double-50at1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double-50fw5": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double-50fw5",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_double",
      "type": "topic",
      "url": "/documentation/simd/simd_double-50fw5"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double-50g0v": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double-50g0v",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_double",
      "type": "topic",
      "url": "/documentation/simd/simd_double-50g0v"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double-50gn7": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double-50gn7",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_double",
      "type": "topic",
      "url": "/documentation/simd/simd_double-50gn7"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double-50hml": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double-50hml",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_double",
      "type": "topic",
      "url": "/documentation/simd/simd_double-50hml"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double-50irj": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double-50irj",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_double",
      "type": "topic",
      "url": "/documentation/simd/simd_double-50irj"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double-50kxh": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double-50kxh",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_double",
      "type": "topic",
      "url": "/documentation/simd/simd_double-50kxh"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double-50ppx": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double-50ppx",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_double",
      "type": "topic",
      "url": "/documentation/simd/simd_double-50ppx"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double-50rjx": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double-50rjx",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_double",
      "type": "topic",
      "url": "/documentation/simd/simd_double-50rjx"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double-50shr": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed-integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double-50shr",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_double",
      "type": "topic",
      "url": "/documentation/simd/simd_double-50shr"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double3": {
      "abstract": [
        {
          "text": "A vector of three 64-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_double3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_double3"
        }
      ],
      "role": "symbol",
      "title": "simd_double3",
      "type": "topic",
      "url": "/documentation/simd/simd_double3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong3": {
      "abstract": [
        {
          "text": "A vector of three 64-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ulong3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ulong3"
        }
      ],
      "role": "symbol",
      "title": "simd_ulong3",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong3"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Create-Three-Element-Vectors-From-Vectors-of-Other-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_double-50ppx",
        "doc://com.apple.accelerate/documentation/simd/simd_double-50fw5",
        "doc://com.apple.accelerate/documentation/simd/simd_double-50kxh",
        "doc://com.apple.accelerate/documentation/simd/simd_double-50at1",
        "doc://com.apple.accelerate/documentation/simd/simd_double-50rjx",
        "doc://com.apple.accelerate/documentation/simd/simd_double-50hml",
        "doc://com.apple.accelerate/documentation/simd/simd_double-50shr",
        "doc://com.apple.accelerate/documentation/simd/simd_double-50gn7",
        "doc://com.apple.accelerate/documentation/simd/simd_double-50g0v"
      ],
      "title": "Functions to Create Three-Element Vectors From Vectors of Other Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong3/title",
          "value": "simd_ulong3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double3/title",
          "value": "simd_double3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double3"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_double-50irj"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
