{
  "abstract": [
    {
      "text": "Returns true if every element in a matrix is exactly equal to the corresponding element in a second matrix.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_equal-49bi6"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_equal#$@SA@simd_double3x2#S0_#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_equal"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_equal"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_equal"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_bool",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_bool",
              "text": "simd_bool"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_equal"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double3x2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@simd_double3x2",
              "text": "simd_double3x2"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double3x2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@simd_double3x2",
              "text": "simd_double3x2"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__y"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_almost_equal_elements-19451": {
      "abstract": [
        {
          "text": "Returns true if every element in a matrix is within a specified tolerance to the corresponding element in a second matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_almost_equal_elements"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_almost_equal_elements-19451",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_almost_equal_elements",
      "type": "topic",
      "url": "/documentation/simd/simd_almost_equal_elements-19451"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_almost_equal_elements_relative-7rdht": {
      "abstract": [
        {
          "text": "Returns true if every element in a matrix is within a specified double-precision relative tolerance to the corresponding element in a second matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_almost_equal_elements_relative"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_almost_equal_elements_relative-7rdht",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_almost_equal_elements_relative",
      "type": "topic",
      "url": "/documentation/simd/simd_almost_equal_elements_relative-7rdht"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_bool": {
      "abstract": [
        {
          "text": "A Boolean scalar value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_bool",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_bool"
        }
      ],
      "role": "symbol",
      "title": "simd_bool",
      "type": "topic",
      "url": "/documentation/simd/simd_bool"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double3x2": {
      "abstract": [
        {
          "text": "A matrix of three columns and two rows that contains double-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_double3x2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double3x2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_double3x2"
        }
      ],
      "role": "symbol",
      "title": "simd_double3x2",
      "type": "topic",
      "url": "/documentation/simd/simd_double3x2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_equal-49bi6": {
      "abstract": [
        {
          "text": "Returns true if every element in a matrix is exactly equal to the corresponding element in a second matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_equal"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_equal-49bi6",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_equal",
      "type": "topic",
      "url": "/documentation/simd/simd_equal-49bi6"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Equality-Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_almost_equal_elements-19451",
        "doc://com.apple.accelerate/documentation/simd/simd_almost_equal_elements_relative-7rdht"
      ],
      "title": "Equality Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double3x2/title",
          "value": "simd_double3x2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double3x2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double3x2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double3x2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double3x2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_bool/title",
          "value": "simd_bool"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_bool/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_bool"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_bool/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_bool"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_equal-49bi6"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
