{
  "abstract": [
    {
      "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_char_sat-2gp4g"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_char_sat#]3S#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "simd_char_sat"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_char_sat"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_char_sat"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char3",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_char3",
              "text": "simd_char3"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_char_sat"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short3",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_short3",
              "text": "simd_short3"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char3": {
      "abstract": [
        {
          "text": "A vector of three 8-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_char3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_char3"
        }
      ],
      "role": "symbol",
      "title": "simd_char3",
      "type": "topic",
      "url": "/documentation/simd/simd_char3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char_sat-2giaw": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char_sat-2giaw",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_char_sat-2giaw"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char_sat-2gjc4": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char_sat-2gjc4",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_char_sat-2gjc4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char_sat-2gjzk": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char_sat-2gjzk",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_char_sat-2gjzk"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char_sat-2gp4g": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char_sat-2gp4g",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_char_sat-2gp4g"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char_sat-2gs88": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char_sat-2gs88",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_char_sat-2gs88"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char_sat-2gt5w": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char_sat-2gt5w",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_char_sat-2gt5w"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char_sat-2gu40": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 8-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char_sat-2gu40",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_char_sat-2gu40"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char_sat-2gv24": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 32-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char_sat-2gv24",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_char_sat-2gv24"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char_sat-2gvmc": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 64-bit, floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char_sat-2gvmc",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_char_sat-2gvmc"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char_sat-2gz1s": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector of 16-bit, unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_char_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char_sat-2gz1s",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_char_sat",
      "type": "topic",
      "url": "/documentation/simd/simd_char_sat-2gz1s"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short3": {
      "abstract": [
        {
          "text": "A vector of three 16-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_short3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_short3"
        }
      ],
      "role": "symbol",
      "title": "simd_short3",
      "type": "topic",
      "url": "/documentation/simd/simd_short3"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Perform-Saturating-Conversion-From-Vectors-of-Other-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_char_sat-2gjzk",
        "doc://com.apple.accelerate/documentation/simd/simd_char_sat-2gu40",
        "doc://com.apple.accelerate/documentation/simd/simd_char_sat-2gz1s",
        "doc://com.apple.accelerate/documentation/simd/simd_char_sat-2giaw",
        "doc://com.apple.accelerate/documentation/simd/simd_char_sat-2gs88",
        "doc://com.apple.accelerate/documentation/simd/simd_char_sat-2gjc4",
        "doc://com.apple.accelerate/documentation/simd/simd_char_sat-2gt5w",
        "doc://com.apple.accelerate/documentation/simd/simd_char_sat-2gv24",
        "doc://com.apple.accelerate/documentation/simd/simd_char_sat-2gvmc"
      ],
      "title": "Functions to Perform Saturating Conversion From Vectors of Other Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short3/title",
          "value": "simd_short3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char3/title",
          "value": "simd_char3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char3"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_char_sat-2gp4g"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
