{
  "abstract": [
    {
      "text": "Returns a new vector from the specified two-element vector, and other elements undefined.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_make_short32_undef(_:)-lops"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@simd_make_short32_undef#]2S#",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "simd_make_short32_undef"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_short2",
        "text": "simd_short2"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@simd_short32",
        "text": "simd_short32"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "simd_make_short32_undef"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "simd_make_short32_undef(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "simd_make_short32_undef"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "other"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_short2",
              "text": "simd_short2"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short32",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_short32",
              "text": "simd_short32"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short32(_:)-1eywv": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified eight-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short32"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short32",
          "text": "simd_short32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short32(_:)-1eywv",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short32"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short32(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short32(_:)-1eywv"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short32(_:)-94o20": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short32"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short32",
          "text": "simd_short32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short32",
          "text": "simd_short32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short32(_:)-94o20",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short32"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short32(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short32(_:)-94o20"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short32(_:)-9757": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified four-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short32"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short4",
          "text": "simd_short4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short32",
          "text": "simd_short32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short32(_:)-9757",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short32"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short32(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short32(_:)-9757"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short32(_:)-9m5sz": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified sixteen-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short32"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short16",
          "text": "simd_short16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short32",
          "text": "simd_short32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short32(_:)-9m5sz",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short32"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short32(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short32(_:)-9m5sz"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short32(_:)-ubpt": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short32"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short2",
          "text": "simd_short2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short32",
          "text": "simd_short32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short32(_:)-ubpt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short32"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short32(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short32(_:)-ubpt"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short32(_:)-xjmw": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified three-element vector, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short32"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short3",
          "text": "simd_short3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short32",
          "text": "simd_short32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short32(_:)-xjmw",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short32"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short32(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short32(_:)-xjmw"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short32(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short32"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short16",
          "text": "simd_short16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short16",
          "text": "simd_short16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short32",
          "text": "simd_short32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short32(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short32"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short32(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short32(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short32_undef(_:)-169di": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified eight-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short32_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short8",
          "text": "simd_short8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short32",
          "text": "simd_short32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short32_undef(_:)-169di",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short32_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short32_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short32_undef(_:)-169di"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short32_undef(_:)-435zw": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified sixteen-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short32_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short16",
          "text": "simd_short16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short32",
          "text": "simd_short32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short32_undef(_:)-435zw",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short32_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short32_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short32_undef(_:)-435zw"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short32_undef(_:)-hws9": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified three-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short32_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short3",
          "text": "simd_short3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short32",
          "text": "simd_short32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short32_undef(_:)-hws9",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short32_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short32_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short32_undef(_:)-hws9"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short32_undef(_:)-lops": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified two-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short32_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short2",
          "text": "simd_short2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short32",
          "text": "simd_short32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short32_undef(_:)-lops",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short32_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short32_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short32_undef(_:)-lops"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short32_undef(_:)-ri8y": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified four-element vector, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short32_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short4",
          "text": "simd_short4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short32",
          "text": "simd_short32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short32_undef(_:)-ri8y",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short32_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short32_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short32_undef(_:)-ri8y"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short2": {
      "abstract": [
        {
          "text": "A vector of two 16-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_short2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_short2"
        }
      ],
      "role": "symbol",
      "title": "simd_short2",
      "type": "topic",
      "url": "/documentation/simd/simd_short2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short32": {
      "abstract": [
        {
          "text": "A vector of thirty-two 16-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_short32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_short32"
        }
      ],
      "role": "symbol",
      "title": "simd_short32",
      "type": "topic",
      "url": "/documentation/simd/simd_short32"
    },
    "doc://com.apple.accelerate/documentation/simd/vector32-62nb2": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector32-62nb2",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector32",
      "type": "topic",
      "url": "/documentation/simd/vector32-62nb2"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Create-Thirty-Two-Element-Vectors-From-Other-Vectors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_short32(_:)-ubpt",
        "doc://com.apple.accelerate/documentation/simd/simd_make_short32(_:)-xjmw",
        "doc://com.apple.accelerate/documentation/simd/simd_make_short32(_:)-9757",
        "doc://com.apple.accelerate/documentation/simd/simd_make_short32(_:)-1eywv",
        "doc://com.apple.accelerate/documentation/simd/simd_make_short32(_:)-9m5sz",
        "doc://com.apple.accelerate/documentation/simd/simd_make_short32(_:)-94o20",
        "doc://com.apple.accelerate/documentation/simd/simd_make_short32(_:_:)",
        "doc://com.apple.accelerate/documentation/simd/simd_make_short32_undef(_:)-hws9",
        "doc://com.apple.accelerate/documentation/simd/simd_make_short32_undef(_:)-ri8y",
        "doc://com.apple.accelerate/documentation/simd/simd_make_short32_undef(_:)-169di",
        "doc://com.apple.accelerate/documentation/simd/simd_make_short32_undef(_:)-435zw"
      ],
      "title": "Functions to Create Thirty Two-Element Vectors From Other Vectors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "simd_make_short32_undef"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short32_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/simd"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Functions-to-Create-Thirty-Two-Element-Vectors-From-Other-Vectors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/simd/simd_make_short32(_:)-ubpt",
                "doc://com.apple.accelerate/documentation/simd/simd_make_short32(_:)-xjmw",
                "doc://com.apple.accelerate/documentation/simd/simd_make_short32(_:)-9757",
                "doc://com.apple.accelerate/documentation/simd/simd_make_short32(_:)-1eywv",
                "doc://com.apple.accelerate/documentation/simd/simd_make_short32(_:)-9m5sz",
                "doc://com.apple.accelerate/documentation/simd/simd_make_short32(_:)-94o20",
                "doc://com.apple.accelerate/documentation/simd/simd_make_short32(_:_:)",
                "doc://com.apple.accelerate/documentation/simd/vector32-62nb2",
                "doc://com.apple.accelerate/documentation/simd/simd_make_short32_undef(_:)-hws9",
                "doc://com.apple.accelerate/documentation/simd/simd_make_short32_undef(_:)-ri8y",
                "doc://com.apple.accelerate/documentation/simd/simd_make_short32_undef(_:)-169di",
                "doc://com.apple.accelerate/documentation/simd/simd_make_short32_undef(_:)-435zw"
              ],
              "title": "Functions to Create Thirty Two-Element Vectors From Other Vectors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "static"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short32",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_short32",
                    "text": "simd_short32"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "simd_make_short32_undef"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short2",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@simd_short2",
                    "text": "simd_short2"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "other"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short32(_:_:)/title",
          "value": "simd_make_short32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short32(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short32_undef(_:)-ri8y/title",
          "value": "simd_make_short32_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short32_undef(_:)-ri8y/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short32_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short2/title",
          "value": "simd_short2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short32_undef(_:)-169di/title",
          "value": "simd_make_short32_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short32_undef(_:)-169di/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short32_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short32(_:)-9757/title",
          "value": "simd_make_short32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short32(_:)-9757/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short32/title",
          "value": "simd_short32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short32/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short32(_:)-9m5sz/title",
          "value": "simd_make_short32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short32(_:)-9m5sz/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short32(_:)-ubpt/title",
          "value": "simd_make_short32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short32(_:)-ubpt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short32_undef(_:)-435zw/title",
          "value": "simd_make_short32_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short32_undef(_:)-435zw/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short32_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short32_undef(_:)-lops/title",
          "value": "simd_make_short32_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short32_undef(_:)-lops/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short32_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short32(_:)-1eywv/title",
          "value": "simd_make_short32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short32(_:)-1eywv/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short32(_:)-xjmw/title",
          "value": "simd_make_short32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short32(_:)-xjmw/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short32_undef(_:)-hws9/title",
          "value": "simd_make_short32_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short32_undef(_:)-hws9/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short32_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short32(_:)-94o20/title",
          "value": "simd_make_short32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short32(_:)-94o20/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short32"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_make_short32_undef(_:)-lops"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/simd/simd_make_short32_undef(_:)-lops"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
