{
  "abstract": [
    {
      "text": "Returns a new vector from a vector and a scalar value.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/vector3-3833i"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@vector3#]2S#S#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "vector3"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "vector3"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "vector3"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short3",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_short3",
              "text": "simd_short3"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "vector3"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_short2",
              "text": "simd_short2"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__xy"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:S",
              "text": "short"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__z"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short3(_:_:)-7dmp4": {
      "abstract": [
        {
          "text": "Returns a new vector from a vector and a scalar value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short2",
          "text": "simd_short2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int16V",
          "text": "Int16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short3",
          "text": "simd_short3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short3(_:_:)-7dmp4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short3"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short3(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short3(_:_:)-7dmp4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_short3(_:_:)-9bk9v": {
      "abstract": [
        {
          "text": "Returns a new vector from a scalar value and a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_short3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int16V",
          "text": "Int16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short2",
          "text": "simd_short2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_short3",
          "text": "simd_short3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_short3(_:_:)-9bk9v",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_short3"
        }
      ],
      "role": "symbol",
      "title": "simd_make_short3(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_short3(_:_:)-9bk9v"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short2": {
      "abstract": [
        {
          "text": "A vector of two 16-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_short2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_short2"
        }
      ],
      "role": "symbol",
      "title": "simd_short2",
      "type": "topic",
      "url": "/documentation/simd/simd_short2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short3": {
      "abstract": [
        {
          "text": "A vector of three 16-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_short3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_short3"
        }
      ],
      "role": "symbol",
      "title": "simd_short3",
      "type": "topic",
      "url": "/documentation/simd/simd_short3"
    },
    "doc://com.apple.accelerate/documentation/simd/vector3-3833i": {
      "abstract": [
        {
          "text": "Returns a new vector from a vector and a scalar value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector3-3833i",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector3",
      "type": "topic",
      "url": "/documentation/simd/vector3-3833i"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Create-Three-Element-Vectors-From-Combinations-of-Vectors-and-Scalar-Values",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_short3(_:_:)-7dmp4",
        "doc://com.apple.accelerate/documentation/simd/simd_make_short3(_:_:)-9bk9v"
      ],
      "title": "Functions to Create Three-Element Vectors From Combinations of Vectors and Scalar Values"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short3(_:_:)-7dmp4/title",
          "value": "simd_make_short3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short3(_:_:)-7dmp4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short3(_:_:)-9bk9v/title",
          "value": "simd_make_short3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_short3(_:_:)-9bk9v/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_short3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short2/title",
          "value": "simd_short2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short3/title",
          "value": "simd_short3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short3"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/vector3-3833i"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
