{
  "abstract": [
    {
      "text": "Returns a new vector from a vector and a scalar value.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/vector3-11y95"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@vector3#]2l#l#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "vector3"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "vector3"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "vector3"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong3",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_ulong3",
              "text": "simd_ulong3"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "vector3"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_ulong2",
              "text": "simd_ulong2"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__xy"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong1",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_ulong1",
              "text": "simd_ulong1"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__z"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3(_:_:)-3orcm": {
      "abstract": [
        {
          "text": "Returns a new vector from a vector and a scalar value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ulong3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong2",
          "text": "simd_ulong2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong1",
          "text": "simd_ulong1"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong3",
          "text": "simd_ulong3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3(_:_:)-3orcm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ulong3"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ulong3(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ulong3(_:_:)-3orcm"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3(_:_:)-3zpz6": {
      "abstract": [
        {
          "text": "Returns a new vector from a scalar value and a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_ulong3"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong1",
          "text": "simd_ulong1"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong2",
          "text": "simd_ulong2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_ulong3",
          "text": "simd_ulong3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3(_:_:)-3zpz6",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_ulong3"
        }
      ],
      "role": "symbol",
      "title": "simd_make_ulong3(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_ulong3(_:_:)-3zpz6"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong1": {
      "abstract": [
        {
          "text": "A vector of one 64-bit unsigned integer element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ulong1"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ulong1"
        }
      ],
      "role": "symbol",
      "title": "simd_ulong1",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong2": {
      "abstract": [
        {
          "text": "A vector of two 64-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ulong2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ulong2"
        }
      ],
      "role": "symbol",
      "title": "simd_ulong2",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong3": {
      "abstract": [
        {
          "text": "A vector of three 64-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ulong3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ulong3"
        }
      ],
      "role": "symbol",
      "title": "simd_ulong3",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong3"
    },
    "doc://com.apple.accelerate/documentation/simd/vector3-11y95": {
      "abstract": [
        {
          "text": "Returns a new vector from a vector and a scalar value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector3-11y95",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector3",
      "type": "topic",
      "url": "/documentation/simd/vector3-11y95"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Create-Three-Element-Vectors-From-Combinations-of-Vectors-and-Scalar-Values",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3(_:_:)-3zpz6",
        "doc://com.apple.accelerate/documentation/simd/simd_make_ulong3(_:_:)-3orcm"
      ],
      "title": "Functions to Create Three-Element Vectors From Combinations of Vectors and Scalar Values"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong3(_:_:)-3orcm/title",
          "value": "simd_make_ulong3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong3(_:_:)-3orcm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ulong3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong1/title",
          "value": "simd_ulong1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong1/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong3/title",
          "value": "simd_ulong3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong3(_:_:)-3zpz6/title",
          "value": "simd_make_ulong3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_ulong3(_:_:)-3zpz6/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_ulong3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong2/title",
          "value": "simd_ulong2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong2"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/vector3-11y95"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
