{
  "abstract": [
    {
      "text": "Returns a new vector from the specified scalar values.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/simd/vector2-8txip"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@vector2#L#L#",
    "fragments": [
      {
        "kind": "identifier",
        "text": "vector2"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "vector2"
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "vector2"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_long2",
              "text": "simd_long2"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "vector2"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long1",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_long1",
              "text": "simd_long1"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__x"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long1",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_long1",
              "text": "simd_long1"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__y"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long1": {
      "abstract": [
        {
          "text": "A vector of one 64-bit signed integer element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_long1"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_long1"
        }
      ],
      "role": "symbol",
      "title": "simd_long1",
      "type": "topic",
      "url": "/documentation/simd/simd_long1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_long2": {
      "abstract": [
        {
          "text": "A vector of two 64-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_long2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_long2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_long2"
        }
      ],
      "role": "symbol",
      "title": "simd_long2",
      "type": "topic",
      "url": "/documentation/simd/simd_long2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_long2(_:)-698vu": {
      "abstract": [
        {
          "text": "Returns a new vector with the first element set to a scalar value, and other elements set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_long2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long1",
          "text": "simd_long1"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long2",
          "text": "simd_long2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_long2(_:)-698vu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_long2"
        }
      ],
      "role": "symbol",
      "title": "simd_make_long2(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_long2(_:)-698vu"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_long2(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified scalar values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_long2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long1",
          "text": "simd_long1"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long1",
          "text": "simd_long1"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long2",
          "text": "simd_long2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_long2(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_long2"
        }
      ],
      "role": "symbol",
      "title": "simd_make_long2(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_long2(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_make_long2_undef(_:)": {
      "abstract": [
        {
          "text": "Returns a new vector with the first element set to a scalar value, and other elements undefined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_make_long2_undef"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long1",
          "text": "simd_long1"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_long2",
          "text": "simd_long2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_make_long2_undef(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_make_long2_undef"
        }
      ],
      "role": "symbol",
      "title": "simd_make_long2_undef(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_make_long2_undef(_:)"
    },
    "doc://com.apple.accelerate/documentation/simd/vector2-8txip": {
      "abstract": [
        {
          "text": "Returns a new vector from the specified scalar values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector2-8txip",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector2",
      "type": "topic",
      "url": "/documentation/simd/vector2-8txip"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions-to-Create-Two-Element-Vectors-From-Scalar-Values",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_make_long2(_:)-698vu",
        "doc://com.apple.accelerate/documentation/simd/simd_make_long2(_:_:)",
        "doc://com.apple.accelerate/documentation/simd/simd_make_long2_undef(_:)"
      ],
      "title": "Functions to Create Two-Element Vectors From Scalar Values"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long1/title",
          "value": "simd_long1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_long1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long1/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_long1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_long2(_:_:)/title",
          "value": "simd_make_long2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_long2(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_long2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_long2(_:)-698vu/title",
          "value": "simd_make_long2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_long2(_:)-698vu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_long2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_long2_undef(_:)/title",
          "value": "simd_make_long2_undef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_make_long2_undef(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_make_long2_undef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long2/title",
          "value": "simd_long2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_long2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_long2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_long2"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/vector2-8txip"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
