{
  "abstract": [
    {
      "text": "Add additional accessibility information to the view.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.AppIntents/documentation/AppIntents",
        "doc://com.apple.AppIntents/documentation/AppIntents/ShortcutsLink"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.AppIntents/documentation/AppIntents/ShortcutsLink/accessibilityCustomContent(_:_:importance:)-5fyx4"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "SwiftUI",
    "externalID": "s:7SwiftUI4ViewPAAE26accessibilityCustomContent__10importanceAA08ModifiedF0VyxAA31AccessibilityAttachmentModifierVGAA18LocalizedStringKeyV_qd__So08AXCustomF10ImportanceVtSyRd__lF::SYNTHESIZED::s:19_AppIntents_SwiftUI13ShortcutsLinkV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "accessibilityCustomContent"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "genericParameter",
        "text": "V"
      },
      {
        "kind": "text",
        "text": ">("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:7SwiftUI18LocalizedStringKeyV",
        "text": "LocalizedStringKey"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "text": "V"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "importance"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)AXCustomContent",
        "text": "AXCustomContent"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@AXCustomContentImportance",
        "text": "Importance"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:7SwiftUI15ModifiedContentV",
        "text": "ModifiedContent"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "text": "Self"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:7SwiftUI31AccessibilityAttachmentModifierV",
        "text": "AccessibilityAttachmentModifier"
      },
      {
        "kind": "text",
        "text": ">"
      }
    ],
    "modules": [
      {
        "name": "AppIntents",
        "relatedModules": [
          "SwiftUI"
        ]
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "accessibilityCustomContent(_:_:importance:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "nonisolated"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "accessibilityCustomContent"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "kind": "genericParameter",
              "text": "V"
            },
            {
              "kind": "text",
              "text": ">("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "labelKey"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:7SwiftUI18LocalizedStringKeyV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:7SwiftUI18LocalizedStringKeyV",
              "text": "LocalizedStringKey"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "value"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "text": "V"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "importance"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)AXCustomContent",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AXCustomContent",
              "text": "AXCustomContent"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@E@AXCustomContentImportance",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@AXCustomContentImportance",
              "text": "Importance"
            },
            {
              "kind": "text",
              "text": " = .default) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:7SwiftUI15ModifiedContentV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:7SwiftUI15ModifiedContentV",
              "text": "ModifiedContent"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "kind": "typeIdentifier",
              "text": "Self"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:7SwiftUI31AccessibilityAttachmentModifierV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:7SwiftUI31AccessibilityAttachmentModifierV",
              "text": "AccessibilityAttachmentModifier"
            },
            {
              "kind": "text",
              "text": "> "
            },
            {
              "kind": "keyword",
              "text": "where"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "text": "V"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sy",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sy",
              "text": "StringProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Localized text describing to the user what",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "is contained in this additional information entry. For example:",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "“orientation”.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "labelKey"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Text value for the additional accessibility",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "information. For example: “landscape.”",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "value"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Importance of the accessibility information.",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "High-importance information gets read out immediately, while",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "default-importance information must be explicitly asked for by the",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "user.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "importance"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this method to add information you want accessibility users to be",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "able to access about this element, beyond the basics of label, value,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "and hint. For example, ",
              "type": "text"
            },
            {
              "code": "accessibilityCustomContent",
              "type": "codeVoice"
            },
            {
              "text": " can be used to add",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "information about the orientation of a photograph, or the number of",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "people found in the picture.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Repeated calls of ",
                  "type": "text"
                },
                {
                  "code": "accessibilityCustomContent",
                  "type": "codeVoice"
                },
                {
                  "text": " with different",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "labels will create new entries of additional information. Calling",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "code": "accessibilityAdditionalContent",
                  "type": "codeVoice"
                },
                {
                  "text": " repeatedly with the same label will",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "instead replace the previous value and importance.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.AppIntents/documentation/AppIntents": {
      "abstract": [
        {
          "text": "Make your app’s content and actions discoverable with system experiences like Spotlight, widgets, and enhanced action capabilities of Siri, powered by Apple Intelligence.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.AppIntents/documentation/AppIntents",
      "kind": "symbol",
      "role": "collection",
      "title": "App Intents",
      "type": "topic",
      "url": "/documentation/appintents"
    },
    "doc://com.apple.AppIntents/documentation/AppIntents/ShortcutsLink": {
      "abstract": [
        {
          "text": "A button that brings users to the current app’s App Shortcuts page in the Shortcuts app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ShortcutsLink"
        }
      ],
      "identifier": "doc://com.apple.AppIntents/documentation/AppIntents/ShortcutsLink",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ShortcutsLink"
        }
      ],
      "role": "symbol",
      "title": "ShortcutsLink",
      "type": "topic",
      "url": "/documentation/appintents/shortcutslink"
    },
    "doc://com.apple.AppIntents/documentation/AppIntents/ShortcutsLink/accessibilityCustomContent(_:_:importance:)-5fyx4": {
      "abstract": [
        {
          "text": "Add additional accessibility information to the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityCustomContent"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "V"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI18LocalizedStringKeyV",
          "text": "LocalizedStringKey"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "V"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "importance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AXCustomContent",
          "text": "AXCustomContent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AXCustomContentImportance",
          "text": "Importance"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI15ModifiedContentV",
          "text": "ModifiedContent"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI31AccessibilityAttachmentModifierV",
          "text": "AccessibilityAttachmentModifier"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.AppIntents/documentation/AppIntents/ShortcutsLink/accessibilityCustomContent(_:_:importance:)-5fyx4",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityCustomContent(_:_:importance:)",
      "type": "topic",
      "url": "/documentation/appintents/shortcutslink/accessibilitycustomcontent(_:_:importance:)-5fyx4"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@E@AXCustomContentImportance": {
      "abstract": [
        {
          "text": "Objects that control the timing of content output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Importance"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@E@AXCustomContentImportance",
      "kind": "symbol",
      "role": "symbol",
      "title": "AXCustomContent.Importance",
      "type": "topic",
      "url": "/documentation/Accessibility/AXCustomContent/Importance-swift.enum"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)AXCustomContent": {
      "abstract": [
        {
          "text": "Objects that define custom content and the timing of its output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXCustomContent"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)AXCustomContent",
      "kind": "symbol",
      "role": "symbol",
      "title": "AXCustomContent",
      "type": "topic",
      "url": "/documentation/Accessibility/AXCustomContent"
    },
    "doc://com.externally.resolved.symbol/s:7SwiftUI15ModifiedContentV": {
      "abstract": [
        {
          "text": "A value with a modifier applied to it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ModifiedContent"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "Modifier"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:7SwiftUI15ModifiedContentV",
      "kind": "symbol",
      "role": "symbol",
      "title": "ModifiedContent",
      "type": "topic",
      "url": "/documentation/SwiftUI/ModifiedContent"
    },
    "doc://com.externally.resolved.symbol/s:7SwiftUI18LocalizedStringKeyV": {
      "abstract": [
        {
          "text": "The key used to look up an entry in a strings file or strings dictionary file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LocalizedStringKey"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:7SwiftUI18LocalizedStringKeyV",
      "kind": "symbol",
      "role": "symbol",
      "title": "LocalizedStringKey",
      "type": "topic",
      "url": "/documentation/SwiftUI/LocalizedStringKey"
    },
    "doc://com.externally.resolved.symbol/s:7SwiftUI31AccessibilityAttachmentModifierV": {
      "abstract": [
        {
          "text": "A view modifier that adds accessibility properties to the view",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AccessibilityAttachmentModifier"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:7SwiftUI31AccessibilityAttachmentModifierV",
      "kind": "symbol",
      "role": "symbol",
      "title": "AccessibilityAttachmentModifier",
      "type": "topic",
      "url": "/documentation/SwiftUI/AccessibilityAttachmentModifier"
    },
    "doc://com.externally.resolved.symbol/s:Sy": {
      "abstract": [
        {
          "text": "A type that can represent a string as a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "StringProtocol"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SK",
          "text": "BidirectionalCollection"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SL",
          "text": "Comparable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s32ExpressibleByStringInterpolationP",
          "text": "ExpressibleByStringInterpolation"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SH",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25LosslessStringConvertibleP",
          "text": "LosslessStringConvertible"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s16TextOutputStreamP",
          "text": "TextOutputStream"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s20TextOutputStreamableP",
          "text": "TextOutputStreamable"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:ST7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": " == "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SJ",
          "text": "Character"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sl5IndexQa",
          "text": "Index"
        },
        {
          "kind": "text",
          "text": " == "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS5IndexV",
          "text": "Index"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s32ExpressibleByStringInterpolationP0cD0Qa",
          "text": "StringInterpolation"
        },
        {
          "kind": "text",
          "text": " == "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s26DefaultStringInterpolationV",
          "text": "DefaultStringInterpolation"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sl11SubSequenceQa",
          "text": "SubSequence"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sy",
          "text": "StringProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sy",
      "kind": "symbol",
      "role": "symbol",
      "title": "StringProtocol",
      "type": "topic",
      "url": "/documentation/Swift/StringProtocol"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@E@AXCustomContentImportance/title",
          "value": "AXCustomContentImportance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@E@AXCustomContentImportance/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AXCustomContentImportance"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSUInteger",
              "text": "NSUInteger"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)AXCustomContent/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AXCustomContent"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appintents/shortcutslink/accessibilitycustomcontent(_:_:importance:)-5fyx4"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
