{
  "abstract": [
    {
      "text": "The session used all of its allocated time.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.watchkit/documentation/WatchKit",
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason/expired"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@WKExtendedRuntimeSessionInvalidationReason@WKExtendedRuntimeSessionInvalidationReasonExpired",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "expired"
      }
    ],
    "modules": [
      {
        "name": "WatchKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "WKExtendedRuntimeSessionInvalidationReasonExpired"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "WKExtendedRuntimeSessionInvalidationReason.expired"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "expired"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Sessions can only run for a limited amount of time. Each session type has a different time limit. For more information, see the session’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSession/expirationDate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.watchkit/documentation/WatchKit": {
      "abstract": [
        {
          "text": "Build watchOS apps that use features the app delegate monitors or controls, such as background tasks and extended runtime sessions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WatchKit",
      "type": "topic",
      "url": "/documentation/watchkit"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSession/expirationDate": {
      "abstract": [
        {
          "text": "The time and date when the session expires.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "expirationDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSession/expirationDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "expirationDate"
        }
      ],
      "role": "symbol",
      "title": "expirationDate",
      "type": "topic",
      "url": "/documentation/watchkit/wkextendedruntimesession/expirationdate"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason": {
      "abstract": [
        {
          "text": "The reasons why a session can become invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKExtendedRuntimeSessionInvalidationReason"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKExtendedRuntimeSessionInvalidationReason"
        }
      ],
      "role": "symbol",
      "title": "WKExtendedRuntimeSessionInvalidationReason",
      "type": "topic",
      "url": "/documentation/watchkit/wkextendedruntimesessioninvalidationreason"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason/error": {
      "abstract": [
        {
          "text": "An error prevented the session from running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "error"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason/error",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKExtendedRuntimeSessionInvalidationReasonError"
        }
      ],
      "role": "symbol",
      "title": "WKExtendedRuntimeSessionInvalidationReason.error",
      "type": "topic",
      "url": "/documentation/watchkit/wkextendedruntimesessioninvalidationreason/error"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason/expired": {
      "abstract": [
        {
          "text": "The session used all of its allocated time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "expired"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason/expired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKExtendedRuntimeSessionInvalidationReasonExpired"
        }
      ],
      "role": "symbol",
      "title": "WKExtendedRuntimeSessionInvalidationReason.expired",
      "type": "topic",
      "url": "/documentation/watchkit/wkextendedruntimesessioninvalidationreason/expired"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason/none": {
      "abstract": [
        {
          "text": "The session ended normally.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKExtendedRuntimeSessionInvalidationReasonNone"
        }
      ],
      "role": "symbol",
      "title": "WKExtendedRuntimeSessionInvalidationReason.none",
      "type": "topic",
      "url": "/documentation/watchkit/wkextendedruntimesessioninvalidationreason/none"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason/resignedFrontmost": {
      "abstract": [
        {
          "text": "The app lost its frontmost status.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resignedFrontmost"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason/resignedFrontmost",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKExtendedRuntimeSessionInvalidationReasonResignedFrontmost"
        }
      ],
      "role": "symbol",
      "title": "WKExtendedRuntimeSessionInvalidationReason.resignedFrontmost",
      "type": "topic",
      "url": "/documentation/watchkit/wkextendedruntimesessioninvalidationreason/resignedfrontmost"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason/sessionInProgress": {
      "abstract": [
        {
          "text": "This app already has a running session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sessionInProgress"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason/sessionInProgress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKExtendedRuntimeSessionInvalidationReasonSessionInProgress"
        }
      ],
      "role": "symbol",
      "title": "WKExtendedRuntimeSessionInvalidationReason.sessionInProgress",
      "type": "topic",
      "url": "/documentation/watchkit/wkextendedruntimesessioninvalidationreason/sessioninprogress"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason/suppressedBySystem": {
      "abstract": [
        {
          "text": "The system is in a state that doesn’t allow sessions of this type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "suppressedBySystem"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason/suppressedBySystem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKExtendedRuntimeSessionInvalidationReasonSuppressedBySystem"
        }
      ],
      "role": "symbol",
      "title": "WKExtendedRuntimeSessionInvalidationReason.suppressedBySystem",
      "type": "topic",
      "url": "/documentation/watchkit/wkextendedruntimesessioninvalidationreason/suppressedbysystem"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Invalidation-Reasons",
      "generated": true,
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason/error",
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason/none",
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason/sessionInProgress",
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason/resignedFrontmost",
        "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason/suppressedBySystem"
      ],
      "title": "Invalidation Reasons"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "WKExtendedRuntimeSessionInvalidationReasonExpired"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtendedRuntimeSessionInvalidationReasonExpired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.watchkit/documentation/WatchKit",
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Invalidation-Reasons",
              "generated": true,
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason/error",
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason/none",
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason/sessionInProgress",
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason/resignedFrontmost",
                "doc://com.apple.watchkit/documentation/WatchKit/WKExtendedRuntimeSessionInvalidationReason/suppressedBySystem"
              ],
              "title": "Invalidation Reasons"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "WKExtendedRuntimeSessionInvalidationReasonExpired"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionInvalidationReason~1resignedFrontmost/title",
          "value": "WKExtendedRuntimeSessionInvalidationReasonResignedFrontmost"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionInvalidationReason~1resignedFrontmost/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtendedRuntimeSessionInvalidationReasonResignedFrontmost"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionInvalidationReason~1suppressedBySystem/title",
          "value": "WKExtendedRuntimeSessionInvalidationReasonSuppressedBySystem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionInvalidationReason~1suppressedBySystem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtendedRuntimeSessionInvalidationReasonSuppressedBySystem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionInvalidationReason/title",
          "value": "WKExtendedRuntimeSessionInvalidationReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionInvalidationReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtendedRuntimeSessionInvalidationReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionInvalidationReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtendedRuntimeSessionInvalidationReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionInvalidationReason~1none/title",
          "value": "WKExtendedRuntimeSessionInvalidationReasonNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionInvalidationReason~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtendedRuntimeSessionInvalidationReasonNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionInvalidationReason~1error/title",
          "value": "WKExtendedRuntimeSessionInvalidationReasonError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionInvalidationReason~1error/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtendedRuntimeSessionInvalidationReasonError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionInvalidationReason~1expired/title",
          "value": "WKExtendedRuntimeSessionInvalidationReasonExpired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionInvalidationReason~1expired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtendedRuntimeSessionInvalidationReasonExpired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSession~1expirationDate/title",
          "value": "expirationDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSession~1expirationDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "expirationDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionInvalidationReason~1sessionInProgress/title",
          "value": "WKExtendedRuntimeSessionInvalidationReasonSessionInProgress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKExtendedRuntimeSessionInvalidationReason~1sessionInProgress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKExtendedRuntimeSessionInvalidationReasonSessionInProgress"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/watchkit/wkextendedruntimesessioninvalidationreason/expired"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/watchkit/wkextendedruntimesessioninvalidationreason/expired"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
