{
  "abstract": [
    {
      "text": "Signifies a creation event.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYou",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightPersistenceEventTrigger"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightPersistenceEventTrigger/created"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SWHighlightPersistenceEventTrigger@SWHighlightPersistenceEventTriggerCreated",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "created"
      }
    ],
    "modules": [
      {
        "name": "Shared With You"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SWHighlightPersistenceEventTriggerCreated"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "SWHighlightPersistenceEventTrigger.created"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "created"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou": {
      "abstract": [
        {
          "text": "Surface shared content and collaborate in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou",
      "kind": "symbol",
      "role": "collection",
      "title": "Shared With You",
      "type": "topic",
      "url": "/documentation/sharedwithyou"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightPersistenceEventTrigger": {
      "abstract": [
        {
          "text": "Signifies the type of persistence event trigger.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SWHighlightPersistenceEventTrigger"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightPersistenceEventTrigger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SWHighlightPersistenceEventTrigger"
        }
      ],
      "role": "symbol",
      "title": "SWHighlightPersistenceEventTrigger",
      "type": "topic",
      "url": "/documentation/sharedwithyou/swhighlightpersistenceeventtrigger"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightPersistenceEventTrigger/created": {
      "abstract": [
        {
          "text": "Signifies a creation event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "created"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightPersistenceEventTrigger/created",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SWHighlightPersistenceEventTriggerCreated"
        }
      ],
      "role": "symbol",
      "title": "SWHighlightPersistenceEventTrigger.created",
      "type": "topic",
      "url": "/documentation/sharedwithyou/swhighlightpersistenceeventtrigger/created"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightPersistenceEventTrigger/deleted": {
      "abstract": [
        {
          "text": "Signifies a deletion event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deleted"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightPersistenceEventTrigger/deleted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SWHighlightPersistenceEventTriggerDeleted"
        }
      ],
      "role": "symbol",
      "title": "SWHighlightPersistenceEventTrigger.deleted",
      "type": "topic",
      "url": "/documentation/sharedwithyou/swhighlightpersistenceeventtrigger/deleted"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightPersistenceEventTrigger/moved": {
      "abstract": [
        {
          "text": "Signifies a move event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "moved"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightPersistenceEventTrigger/moved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SWHighlightPersistenceEventTriggerMoved"
        }
      ],
      "role": "symbol",
      "title": "SWHighlightPersistenceEventTrigger.moved",
      "type": "topic",
      "url": "/documentation/sharedwithyou/swhighlightpersistenceeventtrigger/moved"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightPersistenceEventTrigger/renamed": {
      "abstract": [
        {
          "text": "Signifies a rename event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "renamed"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightPersistenceEventTrigger/renamed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SWHighlightPersistenceEventTriggerRenamed"
        }
      ],
      "role": "symbol",
      "title": "SWHighlightPersistenceEventTrigger.renamed",
      "type": "topic",
      "url": "/documentation/sharedwithyou/swhighlightpersistenceeventtrigger/renamed"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Persistence-actions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightPersistenceEventTrigger/deleted",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightPersistenceEventTrigger/renamed",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightPersistenceEventTrigger/moved"
      ],
      "title": "Persistence actions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SWHighlightPersistenceEventTriggerCreated"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWHighlightPersistenceEventTriggerCreated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sharedwithyou/documentation/SharedWithYou",
                "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightPersistenceEventTrigger"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Persistence-actions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightPersistenceEventTrigger/deleted",
                "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightPersistenceEventTrigger/renamed",
                "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightPersistenceEventTrigger/moved"
              ],
              "title": "Persistence actions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "SWHighlightPersistenceEventTriggerCreated"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWHighlightPersistenceEventTrigger~1created/title",
          "value": "SWHighlightPersistenceEventTriggerCreated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWHighlightPersistenceEventTrigger~1created/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWHighlightPersistenceEventTriggerCreated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWHighlightPersistenceEventTrigger~1renamed/title",
          "value": "SWHighlightPersistenceEventTriggerRenamed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWHighlightPersistenceEventTrigger~1renamed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWHighlightPersistenceEventTriggerRenamed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWHighlightPersistenceEventTrigger/title",
          "value": "SWHighlightPersistenceEventTrigger"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWHighlightPersistenceEventTrigger/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWHighlightPersistenceEventTrigger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWHighlightPersistenceEventTrigger/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SWHighlightPersistenceEventTrigger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWHighlightPersistenceEventTrigger~1deleted/title",
          "value": "SWHighlightPersistenceEventTriggerDeleted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWHighlightPersistenceEventTrigger~1deleted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWHighlightPersistenceEventTriggerDeleted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWHighlightPersistenceEventTrigger~1moved/title",
          "value": "SWHighlightPersistenceEventTriggerMoved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWHighlightPersistenceEventTrigger~1moved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWHighlightPersistenceEventTriggerMoved"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/sharedwithyou/swhighlightpersistenceeventtrigger/created"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/sharedwithyou/swhighlightpersistenceeventtrigger/created"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
