{
  "abstract": [
    {
      "text": "Offset for the condition, in the range from -10,000 through 10,000.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION/lOffset"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@FFCONDITION@FI@lOffset",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "lOffset"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@LONG",
        "text": "LONG"
      }
    ],
    "modules": [
      {
        "name": "Force Feedback"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "lOffset"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "lOffset"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "lOffset"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/LONG",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@LONG",
              "text": "LONG"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback": {
      "abstract": [
        {
          "text": "Control force feedback devices attached to the system. Develop plug-ins that enable communication with force feedback hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback",
      "kind": "symbol",
      "role": "collection",
      "title": "Force Feedback",
      "type": "topic",
      "url": "/documentation/forcefeedback"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION": {
      "abstract": [
        {
          "text": "A structure containing type-specific information for certain effects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFCONDITION"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFCONDITION"
        }
      ],
      "role": "symbol",
      "title": "FFCONDITION",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcondition"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION/dwNegativeSaturation": {
      "abstract": [
        {
          "text": "Maximum force output on the negative side of the offset, in the range from 0 through 10,000.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dwNegativeSaturation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DWORD",
          "text": "DWORD"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION/dwNegativeSaturation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dwNegativeSaturation"
        }
      ],
      "role": "symbol",
      "title": "dwNegativeSaturation",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcondition/dwnegativesaturation"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION/dwPositiveSaturation": {
      "abstract": [
        {
          "text": "Maximum force output on the positive side of the offset, in the range from 0 through 10,000.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dwPositiveSaturation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DWORD",
          "text": "DWORD"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION/dwPositiveSaturation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dwPositiveSaturation"
        }
      ],
      "role": "symbol",
      "title": "dwPositiveSaturation",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcondition/dwpositivesaturation"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION/lDeadBand": {
      "abstract": [
        {
          "text": "Region around ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "lOffset",
              "type": "text"
            }
          ],
          "type": "strong"
        },
        {
          "text": " in which the condition is not active, in the range from 0 through 10,000. In other words, the condition is not active between ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "lOffset",
              "type": "text"
            }
          ],
          "type": "strong"
        },
        {
          "text": " minus ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "lDeadBand",
              "type": "text"
            }
          ],
          "type": "strong"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "lOffset",
              "type": "text"
            }
          ],
          "type": "strong"
        },
        {
          "text": " plus ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "lDeadBand",
              "type": "text"
            }
          ],
          "type": "strong"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lDeadBand"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@LONG",
          "text": "LONG"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION/lDeadBand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lDeadBand"
        }
      ],
      "role": "symbol",
      "title": "lDeadBand",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcondition/ldeadband"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION/lNegativeCoefficient": {
      "abstract": [
        {
          "text": "Coefficient constant on the negative side of the offset, in the range from -10,000 through 10,000.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lNegativeCoefficient"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@LONG",
          "text": "LONG"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION/lNegativeCoefficient",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lNegativeCoefficient"
        }
      ],
      "role": "symbol",
      "title": "lNegativeCoefficient",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcondition/lnegativecoefficient"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION/lOffset": {
      "abstract": [
        {
          "text": "Offset for the condition, in the range from -10,000 through 10,000.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@LONG",
          "text": "LONG"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION/lOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lOffset"
        }
      ],
      "role": "symbol",
      "title": "lOffset",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcondition/loffset"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION/lPositiveCoefficient": {
      "abstract": [
        {
          "text": "Coefficient constant on the positive side of the offset, in the range from -10,000 through 10,000.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lPositiveCoefficient"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@LONG",
          "text": "LONG"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION/lPositiveCoefficient",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lPositiveCoefficient"
        }
      ],
      "role": "symbol",
      "title": "lPositiveCoefficient",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffcondition/lpositivecoefficient"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/LONG": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LONG"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/LONG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LONG"
        }
      ],
      "role": "symbol",
      "title": "LONG",
      "type": "topic",
      "url": "/documentation/forcefeedback/long"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION/dwNegativeSaturation",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION/dwPositiveSaturation",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION/lDeadBand",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION/lNegativeCoefficient",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION/lPositiveCoefficient"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.2",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "lOffset"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION/dwNegativeSaturation",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION/dwPositiveSaturation",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION/lDeadBand",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION/lNegativeCoefficient",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFCONDITION/lPositiveCoefficient"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/LONG",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@LONG",
                    "text": "LONG"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "lOffset"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCONDITION~1lDeadBand/title",
          "value": "lDeadBand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCONDITION~1lDeadBand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lDeadBand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1LONG/title",
          "value": "LONG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1LONG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LONG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1LONG/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LONG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCONDITION/title",
          "value": "FFCONDITION"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCONDITION/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCONDITION"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCONDITION/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFCONDITION"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCONDITION~1lOffset/title",
          "value": "lOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCONDITION~1lOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCONDITION~1lPositiveCoefficient/title",
          "value": "lPositiveCoefficient"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCONDITION~1lPositiveCoefficient/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lPositiveCoefficient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCONDITION~1lNegativeCoefficient/title",
          "value": "lNegativeCoefficient"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCONDITION~1lNegativeCoefficient/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lNegativeCoefficient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCONDITION~1dwPositiveSaturation/title",
          "value": "dwPositiveSaturation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCONDITION~1dwPositiveSaturation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dwPositiveSaturation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCONDITION~1dwNegativeSaturation/title",
          "value": "dwNegativeSaturation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFCONDITION~1dwNegativeSaturation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dwNegativeSaturation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/forcefeedback/ffcondition/loffset"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/forcefeedback/ffcondition/loffset"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
