{
  "abstract": [
    {
      "text": "The RTF data (",
      "type": "text"
    },
    {
      "code": "NSData",
      "type": "codeVoice"
    },
    {
      "text": ") describing the specified range of characters (",
      "type": "text"
    },
    {
      "code": "NSValue",
      "type": "codeVoice"
    },
    {
      "text": " containing an ",
      "type": "text"
    },
    {
      "code": "NSRange",
      "type": "codeVoice"
    },
    {
      "text": " value).",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/rtfForRange"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@NSAccessibilityRTFForRangeParameterizedAttribute",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "rtfForRange"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@NSAccessibility",
        "text": "NSAccessibility"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSAccessibilityParameterizedAttributeName",
        "text": "ParameterizedAttribute"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSAccessibilityRTFForRangeParameterizedAttribute"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "rtfForRange"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "rtfForRange"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@NSAccessibility",
              "text": "NSAccessibility"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSAccessibilityParameterizedAttributeName",
              "text": "ParameterizedAttribute"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct": {
      "abstract": [
        {
          "text": "A namespace for accessibility symbols for AppKit apps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibility"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibility"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibility",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute": {
      "abstract": [
        {
          "text": "Values that describe parameterized attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ParameterizedAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ParameterizedAttribute"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibility.ParameterizedAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/parameterizedattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/attributedStringForRange": {
      "abstract": [
        {
          "text": "Does not use attributes from Appkit/AttributedString.h (",
          "type": "text"
        },
        {
          "code": "NSAttributedString",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attributedStringForRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityParameterizedAttributeName",
          "text": "ParameterizedAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/attributedStringForRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityAttributedStringForRangeParameterizedAttribute"
        }
      ],
      "role": "symbol",
      "title": "attributedStringForRange",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/parameterizedattribute/attributedstringforrange"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/boundsForRange": {
      "abstract": [
        {
          "text": "The rectangle (",
          "type": "text"
        },
        {
          "code": "NSValue",
          "type": "codeVoice"
        },
        {
          "text": " containing an ",
          "type": "text"
        },
        {
          "code": "NSRect",
          "type": "codeVoice"
        },
        {
          "text": " value) enclosing the specified range of characters (",
          "type": "text"
        },
        {
          "code": "NSValue",
          "type": "codeVoice"
        },
        {
          "text": " containing an ",
          "type": "text"
        },
        {
          "code": "NSRange",
          "type": "codeVoice"
        },
        {
          "text": " value). If the range crosses a line boundary, the returned rectangle will fully enclose all the lines of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "boundsForRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityParameterizedAttributeName",
          "text": "ParameterizedAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/boundsForRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityBoundsForRangeParameterizedAttribute"
        }
      ],
      "role": "symbol",
      "title": "boundsForRange",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/parameterizedattribute/boundsforrange"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/cellForColumnAndRow": {
      "abstract": [
        {
          "text": "The cell at the specified row and column.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cellForColumnAndRow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityParameterizedAttributeName",
          "text": "ParameterizedAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/cellForColumnAndRow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityCellForColumnAndRowParameterizedAttribute"
        }
      ],
      "role": "symbol",
      "title": "cellForColumnAndRow",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/parameterizedattribute/cellforcolumnandrow"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/layoutPointForScreenPoint": {
      "abstract": [
        {
          "text": "The point in the layout area (",
          "type": "text"
        },
        {
          "code": "NSValue",
          "type": "codeVoice"
        },
        {
          "text": ") corresponding to the specified point on the screen (",
          "type": "text"
        },
        {
          "code": "NSValue",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layoutPointForScreenPoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityParameterizedAttributeName",
          "text": "ParameterizedAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/layoutPointForScreenPoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityLayoutPointForScreenPointParameterizedAttribute"
        }
      ],
      "role": "symbol",
      "title": "layoutPointForScreenPoint",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/parameterizedattribute/layoutpointforscreenpoint"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/layoutSizeForScreenSize": {
      "abstract": [
        {
          "text": "The size of the layout area in points (",
          "type": "text"
        },
        {
          "code": "NSValue",
          "type": "codeVoice"
        },
        {
          "text": ") corresponding to the specified screen size (",
          "type": "text"
        },
        {
          "code": "NSValue",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layoutSizeForScreenSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityParameterizedAttributeName",
          "text": "ParameterizedAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/layoutSizeForScreenSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityLayoutSizeForScreenSizeParameterizedAttribute"
        }
      ],
      "role": "symbol",
      "title": "layoutSizeForScreenSize",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/parameterizedattribute/layoutsizeforscreensize"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/lineForIndex": {
      "abstract": [
        {
          "text": "The line number (",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": ") of the specified character (",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lineForIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityParameterizedAttributeName",
          "text": "ParameterizedAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/lineForIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityLineForIndexParameterizedAttribute"
        }
      ],
      "role": "symbol",
      "title": "lineForIndex",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/parameterizedattribute/lineforindex"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/rangeForIndex": {
      "abstract": [
        {
          "text": "The full range of characters (",
          "type": "text"
        },
        {
          "code": "NSValue",
          "type": "codeVoice"
        },
        {
          "text": " containing an ",
          "type": "text"
        },
        {
          "code": "NSRange",
          "type": "codeVoice"
        },
        {
          "text": " value), including the specified character, which compose a single glyph (",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rangeForIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityParameterizedAttributeName",
          "text": "ParameterizedAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/rangeForIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityRangeForIndexParameterizedAttribute"
        }
      ],
      "role": "symbol",
      "title": "rangeForIndex",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/parameterizedattribute/rangeforindex"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/rangeForLine": {
      "abstract": [
        {
          "text": "The range of characters (",
          "type": "text"
        },
        {
          "code": "NSValue",
          "type": "codeVoice"
        },
        {
          "text": " containing an ",
          "type": "text"
        },
        {
          "code": "NSRange",
          "type": "codeVoice"
        },
        {
          "text": " value) corresponding to the specified line number (",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rangeForLine"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityParameterizedAttributeName",
          "text": "ParameterizedAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/rangeForLine",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityRangeForLineParameterizedAttribute"
        }
      ],
      "role": "symbol",
      "title": "rangeForLine",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/parameterizedattribute/rangeforline"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/rangeForPosition": {
      "abstract": [
        {
          "text": "The range of characters (",
          "type": "text"
        },
        {
          "code": "NSValue",
          "type": "codeVoice"
        },
        {
          "text": " containing an ",
          "type": "text"
        },
        {
          "code": "NSRange",
          "type": "codeVoice"
        },
        {
          "text": " value) composing the glyph at the specified point (",
          "type": "text"
        },
        {
          "code": "NSValue",
          "type": "codeVoice"
        },
        {
          "text": " containing an ",
          "type": "text"
        },
        {
          "code": "NSPoint",
          "type": "codeVoice"
        },
        {
          "text": " value).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rangeForPosition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityParameterizedAttributeName",
          "text": "ParameterizedAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/rangeForPosition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityRangeForPositionParameterizedAttribute"
        }
      ],
      "role": "symbol",
      "title": "rangeForPosition",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/parameterizedattribute/rangeforposition"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/rtfForRange": {
      "abstract": [
        {
          "text": "The RTF data (",
          "type": "text"
        },
        {
          "code": "NSData",
          "type": "codeVoice"
        },
        {
          "text": ") describing the specified range of characters (",
          "type": "text"
        },
        {
          "code": "NSValue",
          "type": "codeVoice"
        },
        {
          "text": " containing an ",
          "type": "text"
        },
        {
          "code": "NSRange",
          "type": "codeVoice"
        },
        {
          "text": " value).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rtfForRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityParameterizedAttributeName",
          "text": "ParameterizedAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/rtfForRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityRTFForRangeParameterizedAttribute"
        }
      ],
      "role": "symbol",
      "title": "rtfForRange",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/parameterizedattribute/rtfforrange"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/screenPointForLayoutPoint": {
      "abstract": [
        {
          "text": "The screen point (",
          "type": "text"
        },
        {
          "code": "NSValue",
          "type": "codeVoice"
        },
        {
          "text": ") corresponding to the specified point in the layout area (",
          "type": "text"
        },
        {
          "code": "NSValue",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "screenPointForLayoutPoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityParameterizedAttributeName",
          "text": "ParameterizedAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/screenPointForLayoutPoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityScreenPointForLayoutPointParameterizedAttribute"
        }
      ],
      "role": "symbol",
      "title": "screenPointForLayoutPoint",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/parameterizedattribute/screenpointforlayoutpoint"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/screenSizeForLayoutSize": {
      "abstract": [
        {
          "text": "The size of the screen in points (",
          "type": "text"
        },
        {
          "code": "NSValue",
          "type": "codeVoice"
        },
        {
          "text": ") corresponding to the specified size of the layout area (",
          "type": "text"
        },
        {
          "code": "NSValue",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "screenSizeForLayoutSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityParameterizedAttributeName",
          "text": "ParameterizedAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/screenSizeForLayoutSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityScreenSizeForLayoutSizeParameterizedAttribute"
        }
      ],
      "role": "symbol",
      "title": "screenSizeForLayoutSize",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/parameterizedattribute/screensizeforlayoutsize"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/stringForRange": {
      "abstract": [
        {
          "text": "The substring (",
          "type": "text"
        },
        {
          "code": "NSString",
          "type": "codeVoice"
        },
        {
          "text": ") specified by the range (",
          "type": "text"
        },
        {
          "code": "NSValue",
          "type": "codeVoice"
        },
        {
          "text": " containing an ",
          "type": "text"
        },
        {
          "code": "NSRange",
          "type": "codeVoice"
        },
        {
          "text": " value).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stringForRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityParameterizedAttributeName",
          "text": "ParameterizedAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/stringForRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityStringForRangeParameterizedAttribute"
        }
      ],
      "role": "symbol",
      "title": "stringForRange",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/parameterizedattribute/stringforrange"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/styleRangeForIndex": {
      "abstract": [
        {
          "text": "The full range of characters (",
          "type": "text"
        },
        {
          "code": "NSValue",
          "type": "codeVoice"
        },
        {
          "text": " containing an ",
          "type": "text"
        },
        {
          "code": "NSRange",
          "type": "codeVoice"
        },
        {
          "text": " value), including the specified character (",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": "), which have the same style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "styleRangeForIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityParameterizedAttributeName",
          "text": "ParameterizedAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/styleRangeForIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityStyleRangeForIndexParameterizedAttribute"
        }
      ],
      "role": "symbol",
      "title": "styleRangeForIndex",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/parameterizedattribute/stylerangeforindex"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Attribute-Names",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/attributedStringForRange",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/boundsForRange",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/cellForColumnAndRow",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/layoutPointForScreenPoint",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/layoutSizeForScreenSize",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/lineForIndex",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/rangeForIndex",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/rangeForLine",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/rangeForPosition",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/screenPointForLayoutPoint",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/screenSizeForLayoutSize",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/stringForRange",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/styleRangeForIndex"
      ],
      "title": "Attribute Names"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSAccessibilityRTFForRangeParameterizedAttribute"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityRTFForRangeParameterizedAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Attribute-Names",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/attributedStringForRange",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/boundsForRange",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/cellForColumnAndRow",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/layoutPointForScreenPoint",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/layoutSizeForScreenSize",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/lineForIndex",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/rangeForIndex",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/rangeForLine",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/rangeForPosition",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/screenPointForLayoutPoint",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/screenSizeForLayoutSize",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/stringForRange",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute/styleRangeForIndex"
              ],
              "title": "Attribute Names"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSAccessibilityParameterizedAttributeName",
                    "text": "NSAccessibilityParameterizedAttributeName"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSAccessibilityRTFForRangeParameterizedAttribute"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1ParameterizedAttribute~1screenPointForLayoutPoint/title",
          "value": "NSAccessibilityScreenPointForLayoutPointParameterizedAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1ParameterizedAttribute~1screenPointForLayoutPoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityScreenPointForLayoutPointParameterizedAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1ParameterizedAttribute~1attributedStringForRange/title",
          "value": "NSAccessibilityAttributedStringForRangeParameterizedAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1ParameterizedAttribute~1attributedStringForRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityAttributedStringForRangeParameterizedAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1ParameterizedAttribute~1boundsForRange/title",
          "value": "NSAccessibilityBoundsForRangeParameterizedAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1ParameterizedAttribute~1boundsForRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityBoundsForRangeParameterizedAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1ParameterizedAttribute/title",
          "value": "NSAccessibilityParameterizedAttributeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1ParameterizedAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityParameterizedAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1ParameterizedAttribute/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityParameterizedAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1ParameterizedAttribute~1rangeForLine/title",
          "value": "NSAccessibilityRangeForLineParameterizedAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1ParameterizedAttribute~1rangeForLine/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityRangeForLineParameterizedAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1ParameterizedAttribute~1rtfForRange/title",
          "value": "NSAccessibilityRTFForRangeParameterizedAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1ParameterizedAttribute~1rtfForRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityRTFForRangeParameterizedAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1ParameterizedAttribute~1screenSizeForLayoutSize/title",
          "value": "NSAccessibilityScreenSizeForLayoutSizeParameterizedAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1ParameterizedAttribute~1screenSizeForLayoutSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityScreenSizeForLayoutSizeParameterizedAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1ParameterizedAttribute~1rangeForIndex/title",
          "value": "NSAccessibilityRangeForIndexParameterizedAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1ParameterizedAttribute~1rangeForIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityRangeForIndexParameterizedAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1ParameterizedAttribute~1lineForIndex/title",
          "value": "NSAccessibilityLineForIndexParameterizedAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1ParameterizedAttribute~1lineForIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityLineForIndexParameterizedAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1ParameterizedAttribute~1styleRangeForIndex/title",
          "value": "NSAccessibilityStyleRangeForIndexParameterizedAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1ParameterizedAttribute~1styleRangeForIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityStyleRangeForIndexParameterizedAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1ParameterizedAttribute~1stringForRange/title",
          "value": "NSAccessibilityStringForRangeParameterizedAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1ParameterizedAttribute~1stringForRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityStringForRangeParameterizedAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1ParameterizedAttribute~1layoutPointForScreenPoint/title",
          "value": "NSAccessibilityLayoutPointForScreenPointParameterizedAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1ParameterizedAttribute~1layoutPointForScreenPoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityLayoutPointForScreenPointParameterizedAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1ParameterizedAttribute~1cellForColumnAndRow/title",
          "value": "NSAccessibilityCellForColumnAndRowParameterizedAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1ParameterizedAttribute~1cellForColumnAndRow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityCellForColumnAndRowParameterizedAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1ParameterizedAttribute~1rangeForPosition/title",
          "value": "NSAccessibilityRangeForPositionParameterizedAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1ParameterizedAttribute~1rangeForPosition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityRangeForPositionParameterizedAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1ParameterizedAttribute~1layoutSizeForScreenSize/title",
          "value": "NSAccessibilityLayoutSizeForScreenSizeParameterizedAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1ParameterizedAttribute~1layoutSizeForScreenSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityLayoutSizeForScreenSizeParameterizedAttribute"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsaccessibility-swift.struct/parameterizedattribute/rtfforrange"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsaccessibility-swift.struct/parameterizedattribute/rtfforrange"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
