{
  "abstract": [
    {
      "text": "Constants that define aperture modes to use when generating images.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/ApertureMode-swift.struct"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AVFoundation",
    "externalID": "c:@T@AVAssetImageGeneratorApertureMode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ApertureMode"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ApertureMode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "AVAssetImageGenerator.ApertureMode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ApertureMode"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator": {
      "abstract": [
        {
          "text": "An object that generates images from a video asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetImageGenerator"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetImageGenerator"
        }
      ],
      "role": "symbol",
      "title": "AVAssetImageGenerator",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetimagegenerator"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/ApertureMode-swift.struct": {
      "abstract": [
        {
          "text": "Constants that define aperture modes to use when generating images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ApertureMode"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/ApertureMode-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ApertureMode"
        }
      ],
      "role": "symbol",
      "title": "AVAssetImageGenerator.ApertureMode",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetimagegenerator/aperturemode-swift.struct"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/ApertureMode-swift.struct/cleanAperture": {
      "abstract": [
        {
          "text": "A mode that applies both pixel aspect ratio and clean aperture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cleanAperture"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAssetImageGenerator",
          "text": "AVAssetImageGenerator"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAssetImageGeneratorApertureMode",
          "text": "ApertureMode"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/ApertureMode-swift.struct/cleanAperture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetImageGeneratorApertureModeCleanAperture"
        }
      ],
      "role": "symbol",
      "title": "cleanAperture",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetimagegenerator/aperturemode-swift.struct/cleanaperture"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/ApertureMode-swift.struct/encodedPixels": {
      "abstract": [
        {
          "text": "A mode that applies neither pixel aspect ratio nor clean aperture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "encodedPixels"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAssetImageGenerator",
          "text": "AVAssetImageGenerator"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAssetImageGeneratorApertureMode",
          "text": "ApertureMode"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/ApertureMode-swift.struct/encodedPixels",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetImageGeneratorApertureModeEncodedPixels"
        }
      ],
      "role": "symbol",
      "title": "encodedPixels",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetimagegenerator/aperturemode-swift.struct/encodedpixels"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/ApertureMode-swift.struct/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates an aperture mode with a string value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/ApertureMode-swift.struct/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetimagegenerator/aperturemode-swift.struct/init(rawvalue:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/ApertureMode-swift.struct/productionAperture": {
      "abstract": [
        {
          "text": "A mode that applies only pixel aspect ratio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "productionAperture"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAssetImageGenerator",
          "text": "AVAssetImageGenerator"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAssetImageGeneratorApertureMode",
          "text": "ApertureMode"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/ApertureMode-swift.struct/productionAperture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetImageGeneratorApertureModeProductionAperture"
        }
      ],
      "role": "symbol",
      "title": "productionAperture",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetimagegenerator/aperturemode-swift.struct/productionaperture"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/DynamicRangePolicy-swift.struct": {
      "abstract": [
        {
          "text": "A type that specifies the dynamic range policy to apply when generating images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DynamicRangePolicy"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/DynamicRangePolicy-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DynamicRangePolicy"
        }
      ],
      "role": "symbol",
      "title": "AVAssetImageGenerator.DynamicRangePolicy",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetimagegenerator/dynamicrangepolicy-swift.struct"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/apertureMode-swift.property": {
      "abstract": [
        {
          "text": "Specifies the aperture mode for the generated image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "apertureMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAssetImageGenerator",
          "text": "AVAssetImageGenerator"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAssetImageGeneratorApertureMode",
          "text": "ApertureMode"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/apertureMode-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "apertureMode"
        }
      ],
      "role": "symbol",
      "title": "apertureMode",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetimagegenerator/aperturemode-swift.property"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/appliesPreferredTrackTransform": {
      "abstract": [
        {
          "text": "A Boolean value that specifies whether to apply the track matrix or matrices when generating an image from the asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appliesPreferredTrackTransform"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/appliesPreferredTrackTransform",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "appliesPreferredTrackTransform"
        }
      ],
      "role": "symbol",
      "title": "appliesPreferredTrackTransform",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetimagegenerator/appliespreferredtracktransform"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/dynamicRangePolicy-swift.property": {
      "abstract": [
        {
          "text": "The dynamic range policy to use when generating images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dynamicRangePolicy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAssetImageGenerator",
          "text": "AVAssetImageGenerator"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAssetImageGeneratorDynamicRangePolicy",
          "text": "DynamicRangePolicy"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/dynamicRangePolicy-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dynamicRangePolicy"
        }
      ],
      "role": "symbol",
      "title": "dynamicRangePolicy",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetimagegenerator/dynamicrangepolicy-swift.property"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/maximumSize": {
      "abstract": [
        {
          "text": "The maximum size of images to generate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/maximumSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maximumSize"
        }
      ],
      "role": "symbol",
      "title": "maximumSize",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetimagegenerator/maximumsize"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/requestedTimeToleranceAfter": {
      "abstract": [
        {
          "text": "A maximum length of time after the requested time to allow image generation to occur.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestedTimeToleranceAfter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/requestedTimeToleranceAfter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestedTimeToleranceAfter"
        }
      ],
      "role": "symbol",
      "title": "requestedTimeToleranceAfter",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetimagegenerator/requestedtimetoleranceafter"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/requestedTimeToleranceBefore": {
      "abstract": [
        {
          "text": "A maximum length of time before the requested time to allow image generation to occur.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestedTimeToleranceBefore"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/requestedTimeToleranceBefore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestedTimeToleranceBefore"
        }
      ],
      "role": "symbol",
      "title": "requestedTimeToleranceBefore",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetimagegenerator/requestedtimetolerancebefore"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-Image-Generation",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/maximumSize",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/requestedTimeToleranceBefore",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/requestedTimeToleranceAfter",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/dynamicRangePolicy-swift.property",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/DynamicRangePolicy-swift.struct",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/appliesPreferredTrackTransform",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/apertureMode-swift.property"
      ],
      "title": "Configuring Image Generation"
    }
  ],
  "topicSections": [
    {
      "anchor": "Aperture-Modes",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/ApertureMode-swift.struct/cleanAperture",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/ApertureMode-swift.struct/encodedPixels",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/ApertureMode-swift.struct/productionAperture"
      ],
      "title": "Aperture Modes"
    },
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/ApertureMode-swift.struct/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVAssetImageGeneratorApertureMode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetImageGeneratorApertureMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetImageGeneratorApertureMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Aperture-Modes",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/ApertureMode-swift.struct/cleanAperture",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/ApertureMode-swift.struct/encodedPixels",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/ApertureMode-swift.struct/productionAperture"
              ],
              "title": "Aperture Modes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-Image-Generation",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/maximumSize",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/requestedTimeToleranceBefore",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/requestedTimeToleranceAfter",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/dynamicRangePolicy-swift.property",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/DynamicRangePolicy-swift.struct",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/appliesPreferredTrackTransform",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/apertureMode-swift.property"
              ],
              "title": "Configuring Image Generation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVAssetImageGeneratorApertureMode"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1ApertureMode-swift.struct/title",
          "value": "AVAssetImageGeneratorApertureMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1ApertureMode-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetImageGeneratorApertureMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1ApertureMode-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetImageGeneratorApertureMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1DynamicRangePolicy-swift.struct/title",
          "value": "AVAssetImageGeneratorDynamicRangePolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1DynamicRangePolicy-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetImageGeneratorDynamicRangePolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1DynamicRangePolicy-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetImageGeneratorDynamicRangePolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1apertureMode-swift.property/title",
          "value": "apertureMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1apertureMode-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "apertureMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1appliesPreferredTrackTransform/title",
          "value": "appliesPreferredTrackTransform"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1appliesPreferredTrackTransform/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "appliesPreferredTrackTransform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1ApertureMode-swift.struct~1productionAperture/title",
          "value": "AVAssetImageGeneratorApertureModeProductionAperture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1ApertureMode-swift.struct~1productionAperture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetImageGeneratorApertureModeProductionAperture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1ApertureMode-swift.struct~1cleanAperture/title",
          "value": "AVAssetImageGeneratorApertureModeCleanAperture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1ApertureMode-swift.struct~1cleanAperture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetImageGeneratorApertureModeCleanAperture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1maximumSize/title",
          "value": "maximumSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1maximumSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maximumSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1requestedTimeToleranceBefore/title",
          "value": "requestedTimeToleranceBefore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1requestedTimeToleranceBefore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "requestedTimeToleranceBefore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1requestedTimeToleranceAfter/title",
          "value": "requestedTimeToleranceAfter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1requestedTimeToleranceAfter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "requestedTimeToleranceAfter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1dynamicRangePolicy-swift.property/title",
          "value": "dynamicRangePolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1dynamicRangePolicy-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dynamicRangePolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1ApertureMode-swift.struct~1encodedPixels/title",
          "value": "AVAssetImageGeneratorApertureModeEncodedPixels"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1ApertureMode-swift.struct~1encodedPixels/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetImageGeneratorApertureModeEncodedPixels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator/title",
          "value": "AVAssetImageGenerator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetImageGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetImageGenerator"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avassetimagegenerator/aperturemode-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avassetimagegenerator/aperturemode-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
