{"identifier":{"url":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/appliesPreferredTrackTransform","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator"]]},"abstract":[{"type":"text","text":"A Boolean value that specifies whether to apply the track matrix or matrices when generating an image from the asset."}],"metadata":{"modules":[{"name":"AVFoundation"}],"navigatorTitle":[{"kind":"identifier","text":"appliesPreferredTrackTransform"}],"roleHeading":"Instance Property","externalID":"c:objc(cs)AVAssetImageGenerator(py)appliesPreferredTrackTransform","role":"symbol","title":"appliesPreferredTrackTransform","platforms":[{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"4.0","name":"iOS"},{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"4.0","name":"iPadOS"},{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"13.1","name":"Mac Catalyst"},{"introducedAt":"10.7","name":"macOS","unavailable":false,"beta":false,"deprecated":false},{"introducedAt":"9.0","name":"tvOS","unavailable":false,"beta":false,"deprecated":false},{"introducedAt":"1.0","name":"visionOS","unavailable":false,"beta":false,"deprecated":false}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"appliesPreferredTrackTransform"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"appliesPreferredTrackTransform","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","identifier":"doc://com.externally.resolved.symbol/s:Sb","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"]}],"kind":"declarations"},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"Discussion"},{"inlineContent":[{"type":"text","text":"The default value is "},{"identifier":"doc://com.apple.documentation/documentation/swift/false","isActive":true,"type":"reference"},{"type":"text","text":". This class only supports rotation by 90, 180, or 270 degrees."}],"type":"paragraph"},{"inlineContent":[{"text":"The image generator ignores this property if you set a value for the ","type":"text"},{"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/videoComposition","isActive":true,"type":"reference"},{"text":" property.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["/documentation/avfoundation/avassetimagegenerator/appliespreferredtracktransform"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/avfoundation/avassetimagegenerator/appliespreferredtracktransform"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"seeAlsoSections":[{"generated":true,"anchor":"Configuring-Image-Generation","title":"Configuring Image Generation","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/maximumSize","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/requestedTimeToleranceBefore","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/requestedTimeToleranceAfter","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/dynamicRangePolicy-swift.property","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/DynamicRangePolicy-swift.struct","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/apertureMode-swift.property","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/ApertureMode-swift.struct"]}],"references":{"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVAssetImageGenerator","kind":"identifier"}],"navigatorTitle":[{"text":"AVAssetImageGenerator","kind":"identifier"}],"abstract":[{"type":"text","text":"An object that generates images from a video asset."}],"type":"topic","title":"AVAssetImageGenerator","url":"/documentation/avfoundation/avassetimagegenerator","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"type":"topic","title":"Technologies","url":"/documentation/technologies","kind":"technologies"},"doc://com.apple.avfoundation/documentation/AVFoundation":{"role":"collection","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation","abstract":[{"type":"text","text":"Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions."}],"type":"topic","title":"AVFoundation","url":"/documentation/avfoundation","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/ApertureMode-swift.struct":{"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/ApertureMode-swift.struct","navigatorTitle":[{"kind":"identifier","text":"ApertureMode"}],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApertureMode"}],"role":"symbol","kind":"symbol","url":"/documentation/avfoundation/avassetimagegenerator/aperturemode-swift.struct","abstract":[{"text":"Constants that define aperture modes to use when generating images.","type":"text"}],"title":"AVAssetImageGenerator.ApertureMode"},"doc://com.externally.resolved.symbol/s:Sb":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:Sb","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Bool","kind":"identifier"}],"abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"type":"topic","title":"Bool","url":"/documentation/Swift/Bool","kind":"symbol"},"doc://com.apple.documentation/documentation/swift/false":{"type":"topic","kind":"symbol","url":"/documentation/swift/false","identifier":"doc://com.apple.documentation/documentation/swift/false","abstract":[{"type":"text","text":"A false value."}],"role":"symbol","title":"false"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/videoComposition":{"role":"symbol","kind":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/videoComposition","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoComposition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVVideoComposition","preciseIdentifier":"c:objc(cs)AVVideoComposition"},{"kind":"text","text":"?"}],"title":"videoComposition","url":"/documentation/avfoundation/avassetimagegenerator/videocomposition","abstract":[{"type":"text","text":"A video composition to use when extracting images from assets with multiple video tracks."}],"navigatorTitle":[{"kind":"identifier","text":"videoComposition"}],"type":"topic"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/appliesPreferredTrackTransform":{"title":"appliesPreferredTrackTransform","kind":"symbol","abstract":[{"type":"text","text":"A Boolean value that specifies whether to apply the track matrix or matrices when generating an image from the asset."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"appliesPreferredTrackTransform"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"appliesPreferredTrackTransform"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/appliesPreferredTrackTransform","url":"/documentation/avfoundation/avassetimagegenerator/appliespreferredtracktransform"},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","title":"BOOL","url":"/documentation/objectivec/bool","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Type to represent a Boolean value."}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/maximumSize":{"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/maximumSize","navigatorTitle":[{"text":"maximumSize","kind":"identifier"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maximumSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"}],"role":"symbol","kind":"symbol","url":"/documentation/avfoundation/avassetimagegenerator/maximumsize","abstract":[{"text":"The maximum size of images to generate.","type":"text"}],"title":"maximumSize"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/DynamicRangePolicy-swift.struct":{"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/DynamicRangePolicy-swift.struct","navigatorTitle":[{"text":"DynamicRangePolicy","kind":"identifier"}],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DynamicRangePolicy","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"/documentation/avfoundation/avassetimagegenerator/dynamicrangepolicy-swift.struct","abstract":[{"text":"A type that specifies the dynamic range policy to apply when generating images.","type":"text"}],"title":"AVAssetImageGenerator.DynamicRangePolicy"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/dynamicRangePolicy-swift.property":{"role":"symbol","kind":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/dynamicRangePolicy-swift.property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dynamicRangePolicy"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AVAssetImageGenerator","kind":"typeIdentifier","text":"AVAssetImageGenerator"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@T@AVAssetImageGeneratorDynamicRangePolicy","kind":"typeIdentifier","text":"DynamicRangePolicy"}],"title":"dynamicRangePolicy","url":"/documentation/avfoundation/avassetimagegenerator/dynamicrangepolicy-swift.property","abstract":[{"type":"text","text":"The dynamic range policy to use when generating images."}],"navigatorTitle":[{"kind":"identifier","text":"dynamicRangePolicy"}],"type":"topic"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/apertureMode-swift.property":{"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/apertureMode-swift.property","navigatorTitle":[{"kind":"identifier","text":"apertureMode"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"apertureMode"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AVAssetImageGenerator","kind":"typeIdentifier","text":"AVAssetImageGenerator"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@T@AVAssetImageGeneratorApertureMode","kind":"typeIdentifier","text":"ApertureMode"},{"kind":"text","text":"?"}],"role":"symbol","kind":"symbol","url":"/documentation/avfoundation/avassetimagegenerator/aperturemode-swift.property","abstract":[{"text":"Specifies the aperture mode for the generated image.","type":"text"}],"title":"apertureMode"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/requestedTimeToleranceBefore":{"title":"requestedTimeToleranceBefore","kind":"symbol","abstract":[{"type":"text","text":"A maximum length of time before the requested time to allow image generation to occur."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"requestedTimeToleranceBefore"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestedTimeToleranceBefore"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CMTime","preciseIdentifier":"c:@SA@CMTime"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/requestedTimeToleranceBefore","url":"/documentation/avfoundation/avassetimagegenerator/requestedtimetolerancebefore"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/requestedTimeToleranceAfter":{"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/requestedTimeToleranceAfter","navigatorTitle":[{"kind":"identifier","text":"requestedTimeToleranceAfter"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requestedTimeToleranceAfter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@SA@CMTime","text":"CMTime"}],"role":"symbol","kind":"symbol","url":"/documentation/avfoundation/avassetimagegenerator/requestedtimetoleranceafter","abstract":[{"text":"A maximum length of time after the requested time to allow image generation to occur.","type":"text"}],"title":"requestedTimeToleranceAfter"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"unavailable":false,"beta":false,"introducedAt":"4.0","name":"iOS","deprecated":false},{"introducedAt":"4.0","name":"iPadOS","unavailable":false,"beta":false,"deprecated":false},{"introducedAt":"13.1","name":"Mac Catalyst","unavailable":false,"beta":false,"deprecated":false},{"introducedAt":"10.7","name":"macOS","unavailable":false,"beta":false,"deprecated":false},{"introducedAt":"9.0","name":"tvOS","unavailable":false,"beta":false,"deprecated":false},{"name":"visionOS","introducedAt":"1.0","beta":false,"unavailable":false,"deprecated":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Property","path":"/metadata/roleHeading","op":"replace"},{"value":"appliesPreferredTrackTransform","path":"/metadata/title","op":"replace"},{"value":"property","path":"/metadata/symbolKind","op":"replace"},{"value":[{"text":"appliesPreferredTrackTransform","kind":"identifier"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"generated":true,"anchor":"Configuring-Image-Generation","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/maximumSize","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/requestedTimeToleranceBefore","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/requestedTimeToleranceAfter","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/dynamicRangePolicy-swift.property","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/DynamicRangePolicy-swift.struct","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/apertureMode-swift.property","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/ApertureMode-swift.struct"],"title":"Configuring Image Generation"}],"path":"/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"appliesPreferredTrackTransform","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"/primaryContentSections/0","op":"replace"},{"op":"replace","value":"AVAssetImageGenerator","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator/title"},{"op":"replace","value":[{"text":"AVAssetImageGenerator","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AVAssetImageGenerator"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator/navigatorTitle"},{"op":"replace","value":"AVAssetImageGeneratorApertureMode","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1ApertureMode-swift.struct/title"},{"op":"replace","value":[{"text":"AVAssetImageGeneratorApertureMode","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1ApertureMode-swift.struct/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AVAssetImageGeneratorApertureMode"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1ApertureMode-swift.struct/navigatorTitle"},{"op":"replace","value":"videoComposition","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1videoComposition/title"},{"op":"replace","value":[{"text":"videoComposition","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1videoComposition/fragments"},{"op":"replace","value":"appliesPreferredTrackTransform","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1appliesPreferredTrackTransform/title"},{"op":"replace","value":[{"text":"appliesPreferredTrackTransform","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1appliesPreferredTrackTransform/fragments"},{"op":"replace","value":"maximumSize","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1maximumSize/title"},{"op":"replace","value":[{"kind":"identifier","text":"maximumSize"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1maximumSize/fragments"},{"op":"replace","value":"AVAssetImageGeneratorDynamicRangePolicy","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1DynamicRangePolicy-swift.struct/title"},{"op":"replace","value":[{"kind":"identifier","text":"AVAssetImageGeneratorDynamicRangePolicy"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1DynamicRangePolicy-swift.struct/fragments"},{"op":"replace","value":[{"text":"AVAssetImageGeneratorDynamicRangePolicy","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1DynamicRangePolicy-swift.struct/navigatorTitle"},{"op":"replace","value":"dynamicRangePolicy","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1dynamicRangePolicy-swift.property/title"},{"op":"replace","value":[{"text":"dynamicRangePolicy","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1dynamicRangePolicy-swift.property/fragments"},{"op":"replace","value":"apertureMode","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1apertureMode-swift.property/title"},{"op":"replace","value":[{"text":"apertureMode","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1apertureMode-swift.property/fragments"},{"op":"replace","value":"requestedTimeToleranceBefore","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1requestedTimeToleranceBefore/title"},{"op":"replace","value":[{"kind":"identifier","text":"requestedTimeToleranceBefore"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1requestedTimeToleranceBefore/fragments"},{"op":"replace","value":"requestedTimeToleranceAfter","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1requestedTimeToleranceAfter/title"},{"op":"replace","value":[{"kind":"identifier","text":"requestedTimeToleranceAfter"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1requestedTimeToleranceAfter/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}