{"abstract":[{"text":"The dynamic range policy to use when generating images.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["/documentation/avfoundation/avassetimagegenerator/dynamicrangepolicy-swift.property"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/avfoundation/avassetimagegenerator/dynamicrangepolicy-swift.property"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","seeAlsoSections":[{"anchor":"Configuring-Image-Generation","generated":true,"title":"Configuring Image Generation","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/maximumSize","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/requestedTimeToleranceBefore","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/requestedTimeToleranceAfter","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/DynamicRangePolicy-swift.struct","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/appliesPreferredTrackTransform","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/apertureMode-swift.property","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/ApertureMode-swift.struct"]}],"metadata":{"roleHeading":"Instance Property","navigatorTitle":[{"text":"dynamicRangePolicy","kind":"identifier"}],"platforms":[{"name":"iOS","unavailable":false,"beta":false,"introducedAt":"18.0","deprecated":false},{"name":"iPadOS","unavailable":false,"beta":false,"introducedAt":"18.0","deprecated":false},{"name":"Mac Catalyst","unavailable":false,"beta":false,"introducedAt":"18.0","deprecated":false},{"name":"macOS","unavailable":false,"beta":false,"introducedAt":"15.0","deprecated":false},{"name":"tvOS","unavailable":false,"beta":false,"introducedAt":"18.0","deprecated":false},{"name":"visionOS","unavailable":false,"beta":false,"introducedAt":"2.0","deprecated":false}],"symbolKind":"property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dynamicRangePolicy","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AVAssetImageGenerator","preciseIdentifier":"c:objc(cs)AVAssetImageGenerator","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"DynamicRangePolicy","preciseIdentifier":"c:@T@AVAssetImageGeneratorDynamicRangePolicy","kind":"typeIdentifier"}],"externalID":"c:objc(cs)AVAssetImageGenerator(py)dynamicRangePolicy","modules":[{"name":"AVFoundation"}],"title":"dynamicRangePolicy"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator"]]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/dynamicRangePolicy-swift.property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"dynamicRangePolicy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVAssetImageGenerator","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator","preciseIdentifier":"c:objc(cs)AVAssetImageGenerator"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"DynamicRangePolicy","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/DynamicRangePolicy-swift.struct","preciseIdentifier":"c:@T@AVAssetImageGeneratorDynamicRangePolicy"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"]}]},{"kind":"content","content":[{"type":"heading","anchor":"Discussion","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"This property defaults to ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/DynamicRangePolicy-swift.struct/forceSDR","type":"reference"},{"text":".","type":"text"}]}]}],"references":{"doc://com.apple.documentation/documentation/technologies":{"role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"type":"topic","title":"Technologies","url":"/documentation/technologies","kind":"technologies"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/requestedTimeToleranceBefore":{"title":"requestedTimeToleranceBefore","kind":"symbol","abstract":[{"type":"text","text":"A maximum length of time before the requested time to allow image generation to occur."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"requestedTimeToleranceBefore"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestedTimeToleranceBefore"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CMTime","preciseIdentifier":"c:@SA@CMTime"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/requestedTimeToleranceBefore","url":"/documentation/avfoundation/avassetimagegenerator/requestedtimetolerancebefore"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/DynamicRangePolicy-swift.struct/forceSDR":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"forceSDR","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AVAssetImageGenerator","preciseIdentifier":"c:objc(cs)AVAssetImageGenerator","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"DynamicRangePolicy","preciseIdentifier":"c:@T@AVAssetImageGeneratorDynamicRangePolicy","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/DynamicRangePolicy-swift.struct/forceSDR","title":"forceSDR","type":"topic","url":"/documentation/avfoundation/avassetimagegenerator/dynamicrangepolicy-swift.struct/forcesdr","abstract":[{"type":"text","text":"A policy that forces conversion to standard dynamic range."}],"role":"symbol","navigatorTitle":[{"text":"AVAssetImageGeneratorDynamicRangePolicyForceSDR","kind":"identifier"}]},"doc://com.apple.avfoundation/documentation/AVFoundation":{"role":"collection","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation","abstract":[{"type":"text","text":"Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions."}],"type":"topic","title":"AVFoundation","url":"/documentation/avfoundation","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/maximumSize":{"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/maximumSize","navigatorTitle":[{"text":"maximumSize","kind":"identifier"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maximumSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"}],"role":"symbol","kind":"symbol","url":"/documentation/avfoundation/avassetimagegenerator/maximumsize","abstract":[{"text":"The maximum size of images to generate.","type":"text"}],"title":"maximumSize"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/dynamicRangePolicy-swift.property":{"role":"symbol","kind":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/dynamicRangePolicy-swift.property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dynamicRangePolicy"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AVAssetImageGenerator","kind":"typeIdentifier","text":"AVAssetImageGenerator"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@T@AVAssetImageGeneratorDynamicRangePolicy","kind":"typeIdentifier","text":"DynamicRangePolicy"}],"title":"dynamicRangePolicy","url":"/documentation/avfoundation/avassetimagegenerator/dynamicrangepolicy-swift.property","abstract":[{"type":"text","text":"The dynamic range policy to use when generating images."}],"navigatorTitle":[{"kind":"identifier","text":"dynamicRangePolicy"}],"type":"topic"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/appliesPreferredTrackTransform":{"title":"appliesPreferredTrackTransform","kind":"symbol","abstract":[{"type":"text","text":"A Boolean value that specifies whether to apply the track matrix or matrices when generating an image from the asset."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"appliesPreferredTrackTransform"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"appliesPreferredTrackTransform"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/appliesPreferredTrackTransform","url":"/documentation/avfoundation/avassetimagegenerator/appliespreferredtracktransform"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/requestedTimeToleranceAfter":{"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/requestedTimeToleranceAfter","navigatorTitle":[{"kind":"identifier","text":"requestedTimeToleranceAfter"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requestedTimeToleranceAfter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@SA@CMTime","text":"CMTime"}],"role":"symbol","kind":"symbol","url":"/documentation/avfoundation/avassetimagegenerator/requestedtimetoleranceafter","abstract":[{"text":"A maximum length of time after the requested time to allow image generation to occur.","type":"text"}],"title":"requestedTimeToleranceAfter"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/apertureMode-swift.property":{"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/apertureMode-swift.property","navigatorTitle":[{"kind":"identifier","text":"apertureMode"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"apertureMode"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AVAssetImageGenerator","kind":"typeIdentifier","text":"AVAssetImageGenerator"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@T@AVAssetImageGeneratorApertureMode","kind":"typeIdentifier","text":"ApertureMode"},{"kind":"text","text":"?"}],"role":"symbol","kind":"symbol","url":"/documentation/avfoundation/avassetimagegenerator/aperturemode-swift.property","abstract":[{"text":"Specifies the aperture mode for the generated image.","type":"text"}],"title":"apertureMode"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/ApertureMode-swift.struct":{"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/ApertureMode-swift.struct","navigatorTitle":[{"kind":"identifier","text":"ApertureMode"}],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApertureMode"}],"role":"symbol","kind":"symbol","url":"/documentation/avfoundation/avassetimagegenerator/aperturemode-swift.struct","abstract":[{"text":"Constants that define aperture modes to use when generating images.","type":"text"}],"title":"AVAssetImageGenerator.ApertureMode"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVAssetImageGenerator","kind":"identifier"}],"navigatorTitle":[{"text":"AVAssetImageGenerator","kind":"identifier"}],"abstract":[{"type":"text","text":"An object that generates images from a video asset."}],"type":"topic","title":"AVAssetImageGenerator","url":"/documentation/avfoundation/avassetimagegenerator","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/DynamicRangePolicy-swift.struct":{"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/DynamicRangePolicy-swift.struct","navigatorTitle":[{"text":"DynamicRangePolicy","kind":"identifier"}],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DynamicRangePolicy","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"/documentation/avfoundation/avassetimagegenerator/dynamicrangepolicy-swift.struct","abstract":[{"text":"A type that specifies the dynamic range policy to apply when generating images.","type":"text"}],"title":"AVAssetImageGenerator.DynamicRangePolicy"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"unavailable":false,"name":"iOS","deprecated":false,"introducedAt":"18.0","beta":false},{"unavailable":false,"name":"iPadOS","deprecated":false,"introducedAt":"18.0","beta":false},{"unavailable":false,"name":"Mac Catalyst","deprecated":false,"introducedAt":"18.0","beta":false},{"unavailable":false,"name":"macOS","deprecated":false,"introducedAt":"15.0","beta":false},{"unavailable":false,"name":"tvOS","deprecated":false,"introducedAt":"18.0","beta":false},{"unavailable":false,"name":"visionOS","deprecated":false,"introducedAt":"2.0","beta":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Property","op":"replace","path":"/metadata/roleHeading"},{"value":"dynamicRangePolicy","op":"replace","path":"/metadata/title"},{"value":"property","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"dynamicRangePolicy","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/maximumSize","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/requestedTimeToleranceBefore","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/requestedTimeToleranceAfter","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/DynamicRangePolicy-swift.struct","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/appliesPreferredTrackTransform","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/apertureMode-swift.property","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/ApertureMode-swift.struct"],"title":"Configuring Image Generation","anchor":"Configuring-Image-Generation","generated":true}],"op":"replace","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"AVAssetImageGeneratorDynamicRangePolicy","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator/DynamicRangePolicy-swift.struct","preciseIdentifier":"c:@T@AVAssetImageGeneratorDynamicRangePolicy"},{"kind":"text","text":" "},{"kind":"identifier","text":"dynamicRangePolicy"},{"kind":"text","text":";"}]}]},"op":"replace","path":"/primaryContentSections/0"},{"value":"requestedTimeToleranceBefore","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1requestedTimeToleranceBefore/title","op":"replace"},{"value":[{"text":"requestedTimeToleranceBefore","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1requestedTimeToleranceBefore/fragments","op":"replace"},{"value":"AVAssetImageGeneratorDynamicRangePolicyForceSDR","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1DynamicRangePolicy-swift.struct~1forceSDR/title","op":"replace"},{"value":[{"kind":"identifier","text":"AVAssetImageGeneratorDynamicRangePolicyForceSDR"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1DynamicRangePolicy-swift.struct~1forceSDR/fragments","op":"replace"},{"value":"maximumSize","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1maximumSize/title","op":"replace"},{"value":[{"text":"maximumSize","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1maximumSize/fragments","op":"replace"},{"value":"dynamicRangePolicy","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1dynamicRangePolicy-swift.property/title","op":"replace"},{"value":[{"kind":"identifier","text":"dynamicRangePolicy"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1dynamicRangePolicy-swift.property/fragments","op":"replace"},{"value":"appliesPreferredTrackTransform","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1appliesPreferredTrackTransform/title","op":"replace"},{"value":[{"text":"appliesPreferredTrackTransform","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1appliesPreferredTrackTransform/fragments","op":"replace"},{"value":"requestedTimeToleranceAfter","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1requestedTimeToleranceAfter/title","op":"replace"},{"value":[{"text":"requestedTimeToleranceAfter","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1requestedTimeToleranceAfter/fragments","op":"replace"},{"value":"apertureMode","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1apertureMode-swift.property/title","op":"replace"},{"value":[{"text":"apertureMode","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1apertureMode-swift.property/fragments","op":"replace"},{"value":"AVAssetImageGeneratorApertureMode","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1ApertureMode-swift.struct/title","op":"replace"},{"value":[{"kind":"identifier","text":"AVAssetImageGeneratorApertureMode"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1ApertureMode-swift.struct/fragments","op":"replace"},{"value":[{"text":"AVAssetImageGeneratorApertureMode","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1ApertureMode-swift.struct/navigatorTitle","op":"replace"},{"value":"AVAssetImageGenerator","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator/title","op":"replace"},{"value":[{"text":"AVAssetImageGenerator","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AVAssetImageGenerator"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator/navigatorTitle","op":"replace"},{"value":"AVAssetImageGeneratorDynamicRangePolicy","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1DynamicRangePolicy-swift.struct/title","op":"replace"},{"value":[{"kind":"identifier","text":"AVAssetImageGeneratorDynamicRangePolicy"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1DynamicRangePolicy-swift.struct/fragments","op":"replace"},{"value":[{"text":"AVAssetImageGeneratorDynamicRangePolicy","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator~1DynamicRangePolicy-swift.struct/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}