{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@ICReturnConnectionErrorCode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "ImageCaptureCore"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "ICReturnConnectionError.Code"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Code"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore": {
      "abstract": [
        {
          "text": "Browse for media devices and control them programmatically from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
      "kind": "symbol",
      "role": "collection",
      "title": "ImageCaptureCore",
      "type": "topic",
      "url": "/documentation/imagecapturecore"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError": {
      "abstract": [
        {
          "text": "A connection error returned from ImageCaptureCore.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICReturnConnectionError"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnConnectionError"
        }
      ],
      "role": "symbol",
      "title": "ICReturnConnectionError",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnconnectionerror"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "ICReturnConnectionError.Code",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnconnectionerror/code"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/closedSessionSuddenly": {
      "abstract": [
        {
          "text": "Device closed session without request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "closedSessionSuddenly"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/closedSessionSuddenly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnConnectionClosedSessionSuddenly"
        }
      ],
      "role": "symbol",
      "title": "ICReturnConnectionError.Code.closedSessionSuddenly",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnconnectionerror/code/closedsessionsuddenly"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/driverExited": {
      "abstract": [
        {
          "text": "Device driver exited without request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "driverExited"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/driverExited",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnConnectionDriverExited"
        }
      ],
      "role": "symbol",
      "title": "ICReturnConnectionError.Code.driverExited",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnconnectionerror/code/driverexited"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/ejectFailed": {
      "abstract": [
        {
          "text": "Device reports eject has failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ejectFailed"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/ejectFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnConnectionEjectFailed"
        }
      ],
      "role": "symbol",
      "title": "ICReturnConnectionError.Code.ejectFailed",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnconnectionerror/code/ejectfailed"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/ejectedSuddenly": {
      "abstract": [
        {
          "text": "Device ejected without request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ejectedSuddenly"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/ejectedSuddenly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnConnectionEjectedSuddenly"
        }
      ],
      "role": "symbol",
      "title": "ICReturnConnectionError.Code.ejectedSuddenly",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnconnectionerror/code/ejectedsuddenly"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/failedToOpen": {
      "abstract": [
        {
          "text": "Failed to open a connection to the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failedToOpen"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/failedToOpen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnConnectionFailedToOpen"
        }
      ],
      "role": "symbol",
      "title": "ICReturnConnectionError.Code.failedToOpen",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnconnectionerror/code/failedtoopen"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/failedToOpenDevice": {
      "abstract": [
        {
          "text": "Failed to open the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failedToOpenDevice"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/failedToOpenDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnConnectionFailedToOpenDevice"
        }
      ],
      "role": "symbol",
      "title": "ICReturnConnectionError.Code.failedToOpenDevice",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnconnectionerror/code/failedtoopendevice"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnconnectionerror/code/init(rawvalue:)"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/notAuthorizedToOpenDevice": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notAuthorizedToOpenDevice"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/notAuthorizedToOpenDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnConnectionNotAuthorizedToOpenDevice"
        }
      ],
      "role": "symbol",
      "title": "ICReturnConnectionError.Code.notAuthorizedToOpenDevice",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnconnectionerror/code/notauthorizedtoopendevice"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/sessionAlreadyOpen": {
      "abstract": [
        {
          "text": "Device reports session is already open.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sessionAlreadyOpen"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/sessionAlreadyOpen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnConnectionSessionAlreadyOpen"
        }
      ],
      "role": "symbol",
      "title": "ICReturnConnectionError.Code.sessionAlreadyOpen",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnconnectionerror/code/sessionalreadyopen"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/closedSessionSuddenly": {
      "abstract": [
        {
          "text": "Device closed session without request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "closedSessionSuddenly"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC27ICReturnConnectionErrorCodeLeV",
          "text": "ICReturnConnectionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ICReturnConnectionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/closedSessionSuddenly",
      "kind": "symbol",
      "role": "symbol",
      "title": "closedSessionSuddenly",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnconnectionerror/closedsessionsuddenly"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/driverExited": {
      "abstract": [
        {
          "text": "Device driver exited without request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "driverExited"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC27ICReturnConnectionErrorCodeLeV",
          "text": "ICReturnConnectionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ICReturnConnectionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/driverExited",
      "kind": "symbol",
      "role": "symbol",
      "title": "driverExited",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnconnectionerror/driverexited"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/ejectFailed": {
      "abstract": [
        {
          "text": "Device reports eject has failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ejectFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC27ICReturnConnectionErrorCodeLeV",
          "text": "ICReturnConnectionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ICReturnConnectionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/ejectFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "ejectFailed",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnconnectionerror/ejectfailed"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/ejectedSuddenly": {
      "abstract": [
        {
          "text": "Device ejected without request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ejectedSuddenly"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC27ICReturnConnectionErrorCodeLeV",
          "text": "ICReturnConnectionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ICReturnConnectionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/ejectedSuddenly",
      "kind": "symbol",
      "role": "symbol",
      "title": "ejectedSuddenly",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnconnectionerror/ejectedsuddenly"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/failedToOpen": {
      "abstract": [
        {
          "text": "Failed to open a connection to the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failedToOpen"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC27ICReturnConnectionErrorCodeLeV",
          "text": "ICReturnConnectionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ICReturnConnectionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/failedToOpen",
      "kind": "symbol",
      "role": "symbol",
      "title": "failedToOpen",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnconnectionerror/failedtoopen"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/failedToOpenDevice": {
      "abstract": [
        {
          "text": "Failed to open the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failedToOpenDevice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC27ICReturnConnectionErrorCodeLeV",
          "text": "ICReturnConnectionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ICReturnConnectionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/failedToOpenDevice",
      "kind": "symbol",
      "role": "symbol",
      "title": "failedToOpenDevice",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnconnectionerror/failedtoopendevice"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/sessionAlreadyOpen": {
      "abstract": [
        {
          "text": "Device reports session is already open.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sessionAlreadyOpen"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC27ICReturnConnectionErrorCodeLeV",
          "text": "ICReturnConnectionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ICReturnConnectionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/sessionAlreadyOpen",
      "kind": "symbol",
      "role": "symbol",
      "title": "sessionAlreadyOpen",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnconnectionerror/sessionalreadyopen"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/closedSessionSuddenly",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/driverExited",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/ejectFailed",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/ejectedSuddenly",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/failedToOpen",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/failedToOpenDevice",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/sessionAlreadyOpen"
      ],
      "title": "Error Codes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Error-Cases",
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/closedSessionSuddenly",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/driverExited",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/ejectedSuddenly",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/ejectFailed",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/failedToOpen",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/failedToOpenDevice",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/sessionAlreadyOpen",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/closedSessionSuddenly",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/driverExited",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/ejectedSuddenly",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/ejectFailed",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/failedToOpen",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/failedToOpenDevice",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/sessionAlreadyOpen"
      ],
      "title": "Error Cases"
    },
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/notAuthorizedToOpenDevice"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ICReturnConnectionErrorCode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnConnectionErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnConnectionErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Error-Cases",
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/closedSessionSuddenly",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/driverExited",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/ejectedSuddenly",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/ejectFailed",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/failedToOpen",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/failedToOpenDevice",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/sessionAlreadyOpen",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/closedSessionSuddenly",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/driverExited",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/ejectedSuddenly",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/ejectFailed",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/failedToOpen",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/failedToOpenDevice",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/sessionAlreadyOpen"
              ],
              "title": "Error Cases"
            },
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/notAuthorizedToOpenDevice"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ICReturnConnectionErrorCode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnConnectionError~1Code~1ejectFailed/title",
          "value": "ICReturnConnectionEjectFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnConnectionError~1Code~1ejectFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnConnectionEjectFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnConnectionError~1Code~1sessionAlreadyOpen/title",
          "value": "ICReturnConnectionSessionAlreadyOpen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnConnectionError~1Code~1sessionAlreadyOpen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnConnectionSessionAlreadyOpen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnConnectionError~1Code~1driverExited/title",
          "value": "ICReturnConnectionDriverExited"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnConnectionError~1Code~1driverExited/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnConnectionDriverExited"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnConnectionError~1Code~1ejectedSuddenly/title",
          "value": "ICReturnConnectionEjectedSuddenly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnConnectionError~1Code~1ejectedSuddenly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnConnectionEjectedSuddenly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnConnectionError~1Code~1notAuthorizedToOpenDevice/title",
          "value": "ICReturnConnectionNotAuthorizedToOpenDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnConnectionError~1Code~1notAuthorizedToOpenDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnConnectionNotAuthorizedToOpenDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnConnectionError~1Code~1failedToOpen/title",
          "value": "ICReturnConnectionFailedToOpen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnConnectionError~1Code~1failedToOpen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnConnectionFailedToOpen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnConnectionError~1Code/title",
          "value": "ICReturnConnectionErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnConnectionError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnConnectionErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnConnectionError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnConnectionErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnConnectionError~1Code~1closedSessionSuddenly/title",
          "value": "ICReturnConnectionClosedSessionSuddenly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnConnectionError~1Code~1closedSessionSuddenly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnConnectionClosedSessionSuddenly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnConnectionError~1Code~1failedToOpenDevice/title",
          "value": "ICReturnConnectionFailedToOpenDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnConnectionError~1Code~1failedToOpenDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnConnectionFailedToOpenDevice"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imagecapturecore/icreturnconnectionerror/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imagecapturecore/icreturnconnectionerror/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
