{
  "abstract": [
    {
      "text": "Device reports session is already open.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/sessionAlreadyOpen"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC27ICReturnConnectionErrorCodeLeV18sessionAlreadyOpenSoAAVvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "sessionAlreadyOpen"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SC27ICReturnConnectionErrorCodeLeV",
        "text": "ICReturnConnectionError"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@ICReturnConnectionErrorCode",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "ImageCaptureCore"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "sessionAlreadyOpen"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "sessionAlreadyOpen"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SC27ICReturnConnectionErrorCodeLeV",
              "text": "ICReturnConnectionError"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@ICReturnConnectionErrorCode",
              "text": "Code"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore": {
      "abstract": [
        {
          "text": "Browse for media devices and control them programmatically from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
      "kind": "symbol",
      "role": "collection",
      "title": "ImageCaptureCore",
      "type": "topic",
      "url": "/documentation/imagecapturecore"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError": {
      "abstract": [
        {
          "text": "A connection error returned from ImageCaptureCore.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICReturnConnectionError"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnConnectionError"
        }
      ],
      "role": "symbol",
      "title": "ICReturnConnectionError",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnconnectionerror"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "ICReturnConnectionError.Code",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnconnectionerror/code"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/closedSessionSuddenly": {
      "abstract": [
        {
          "text": "Device closed session without request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "closedSessionSuddenly"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC27ICReturnConnectionErrorCodeLeV",
          "text": "ICReturnConnectionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ICReturnConnectionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/closedSessionSuddenly",
      "kind": "symbol",
      "role": "symbol",
      "title": "closedSessionSuddenly",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnconnectionerror/closedsessionsuddenly"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/driverExited": {
      "abstract": [
        {
          "text": "Device driver exited without request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "driverExited"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC27ICReturnConnectionErrorCodeLeV",
          "text": "ICReturnConnectionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ICReturnConnectionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/driverExited",
      "kind": "symbol",
      "role": "symbol",
      "title": "driverExited",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnconnectionerror/driverexited"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/ejectFailed": {
      "abstract": [
        {
          "text": "Device reports eject has failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ejectFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC27ICReturnConnectionErrorCodeLeV",
          "text": "ICReturnConnectionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ICReturnConnectionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/ejectFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "ejectFailed",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnconnectionerror/ejectfailed"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/ejectedSuddenly": {
      "abstract": [
        {
          "text": "Device ejected without request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ejectedSuddenly"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC27ICReturnConnectionErrorCodeLeV",
          "text": "ICReturnConnectionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ICReturnConnectionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/ejectedSuddenly",
      "kind": "symbol",
      "role": "symbol",
      "title": "ejectedSuddenly",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnconnectionerror/ejectedsuddenly"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/failedToOpen": {
      "abstract": [
        {
          "text": "Failed to open a connection to the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failedToOpen"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC27ICReturnConnectionErrorCodeLeV",
          "text": "ICReturnConnectionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ICReturnConnectionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/failedToOpen",
      "kind": "symbol",
      "role": "symbol",
      "title": "failedToOpen",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnconnectionerror/failedtoopen"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/failedToOpenDevice": {
      "abstract": [
        {
          "text": "Failed to open the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failedToOpenDevice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC27ICReturnConnectionErrorCodeLeV",
          "text": "ICReturnConnectionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ICReturnConnectionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/failedToOpenDevice",
      "kind": "symbol",
      "role": "symbol",
      "title": "failedToOpenDevice",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnconnectionerror/failedtoopendevice"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/sessionAlreadyOpen": {
      "abstract": [
        {
          "text": "Device reports session is already open.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sessionAlreadyOpen"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC27ICReturnConnectionErrorCodeLeV",
          "text": "ICReturnConnectionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ICReturnConnectionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/sessionAlreadyOpen",
      "kind": "symbol",
      "role": "symbol",
      "title": "sessionAlreadyOpen",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnconnectionerror/sessionalreadyopen"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/closedSessionSuddenly",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/driverExited",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/ejectFailed",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/ejectedSuddenly",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/failedToOpen",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/failedToOpenDevice",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code"
      ],
      "title": "Error Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnConnectionError~1Code/title",
          "value": "ICReturnConnectionErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnConnectionError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnConnectionErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnConnectionError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnConnectionErrorCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imagecapturecore/icreturnconnectionerror/sessionalreadyopen"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
