{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.vmnet/documentation/vmnet",
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_TOO_MANY_PACKETS"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@vmnet_return_t@VMNET_TOO_MANY_PACKETS",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "VMNET_TOO_MANY_PACKETS"
      }
    ],
    "modules": [
      {
        "name": "vmnet"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VMNET_TOO_MANY_PACKETS"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "vmnet_return_t.VMNET_TOO_MANY_PACKETS"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "VMNET_TOO_MANY_PACKETS"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Indicates failure due to the number of packets exceeding the system limit.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.vmnet/documentation/vmnet": {
      "abstract": [
        {
          "text": "Connect with network interfaces to read and write packets on guest operating systems.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet",
      "kind": "symbol",
      "role": "collection",
      "title": "vmnet",
      "type": "topic",
      "url": "/documentation/vmnet"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t": {
      "abstract": [
        {
          "text": "Values returned by functions in the vmnet Framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vmnet_return_t"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vmnet_return_t"
        }
      ],
      "role": "symbol",
      "title": "vmnet_return_t",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_return_t"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_BUFFER_EXHAUSTED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VMNET_BUFFER_EXHAUSTED"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_BUFFER_EXHAUSTED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VMNET_BUFFER_EXHAUSTED"
        }
      ],
      "role": "symbol",
      "title": "vmnet_return_t.VMNET_BUFFER_EXHAUSTED",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_return_t/vmnet_buffer_exhausted"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_FAILURE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VMNET_FAILURE"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_FAILURE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VMNET_FAILURE"
        }
      ],
      "role": "symbol",
      "title": "vmnet_return_t.VMNET_FAILURE",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_return_t/vmnet_failure"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_INVALID_ACCESS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VMNET_INVALID_ACCESS"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_INVALID_ACCESS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VMNET_INVALID_ACCESS"
        }
      ],
      "role": "symbol",
      "title": "vmnet_return_t.VMNET_INVALID_ACCESS",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_return_t/vmnet_invalid_access"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_INVALID_ARGUMENT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VMNET_INVALID_ARGUMENT"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_INVALID_ARGUMENT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VMNET_INVALID_ARGUMENT"
        }
      ],
      "role": "symbol",
      "title": "vmnet_return_t.VMNET_INVALID_ARGUMENT",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_return_t/vmnet_invalid_argument"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_MEM_FAILURE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VMNET_MEM_FAILURE"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_MEM_FAILURE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VMNET_MEM_FAILURE"
        }
      ],
      "role": "symbol",
      "title": "vmnet_return_t.VMNET_MEM_FAILURE",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_return_t/vmnet_mem_failure"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_PACKET_TOO_BIG": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VMNET_PACKET_TOO_BIG"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_PACKET_TOO_BIG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VMNET_PACKET_TOO_BIG"
        }
      ],
      "role": "symbol",
      "title": "vmnet_return_t.VMNET_PACKET_TOO_BIG",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_return_t/vmnet_packet_too_big"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_SETUP_INCOMPLETE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VMNET_SETUP_INCOMPLETE"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_SETUP_INCOMPLETE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VMNET_SETUP_INCOMPLETE"
        }
      ],
      "role": "symbol",
      "title": "vmnet_return_t.VMNET_SETUP_INCOMPLETE",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_return_t/vmnet_setup_incomplete"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_SUCCESS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VMNET_SUCCESS"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_SUCCESS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VMNET_SUCCESS"
        }
      ],
      "role": "symbol",
      "title": "vmnet_return_t.VMNET_SUCCESS",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_return_t/vmnet_success"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_TOO_MANY_PACKETS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VMNET_TOO_MANY_PACKETS"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_TOO_MANY_PACKETS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VMNET_TOO_MANY_PACKETS"
        }
      ],
      "role": "symbol",
      "title": "vmnet_return_t.VMNET_TOO_MANY_PACKETS",
      "type": "topic",
      "url": "/documentation/vmnet/vmnet_return_t/vmnet_too_many_packets"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_SUCCESS",
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_FAILURE",
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_MEM_FAILURE",
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_INVALID_ARGUMENT",
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_SETUP_INCOMPLETE",
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_INVALID_ACCESS",
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_PACKET_TOO_BIG",
        "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_BUFFER_EXHAUSTED"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VMNET_TOO_MANY_PACKETS"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VMNET_TOO_MANY_PACKETS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.vmnet/documentation/vmnet",
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_SUCCESS",
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_FAILURE",
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_MEM_FAILURE",
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_INVALID_ARGUMENT",
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_SETUP_INCOMPLETE",
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_INVALID_ACCESS",
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_PACKET_TOO_BIG",
                "doc://com.apple.vmnet/documentation/vmnet/vmnet_return_t/VMNET_BUFFER_EXHAUSTED"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "VMNET_TOO_MANY_PACKETS"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_return_t~1VMNET_INVALID_ARGUMENT/title",
          "value": "VMNET_INVALID_ARGUMENT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_return_t~1VMNET_INVALID_ARGUMENT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VMNET_INVALID_ARGUMENT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_return_t~1VMNET_SETUP_INCOMPLETE/title",
          "value": "VMNET_SETUP_INCOMPLETE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_return_t~1VMNET_SETUP_INCOMPLETE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VMNET_SETUP_INCOMPLETE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_return_t~1VMNET_SUCCESS/title",
          "value": "VMNET_SUCCESS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_return_t~1VMNET_SUCCESS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VMNET_SUCCESS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_return_t~1VMNET_MEM_FAILURE/title",
          "value": "VMNET_MEM_FAILURE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_return_t~1VMNET_MEM_FAILURE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VMNET_MEM_FAILURE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_return_t~1VMNET_FAILURE/title",
          "value": "VMNET_FAILURE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_return_t~1VMNET_FAILURE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VMNET_FAILURE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_return_t~1VMNET_TOO_MANY_PACKETS/title",
          "value": "VMNET_TOO_MANY_PACKETS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_return_t~1VMNET_TOO_MANY_PACKETS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VMNET_TOO_MANY_PACKETS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_return_t~1VMNET_BUFFER_EXHAUSTED/title",
          "value": "VMNET_BUFFER_EXHAUSTED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_return_t~1VMNET_BUFFER_EXHAUSTED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VMNET_BUFFER_EXHAUSTED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_return_t~1VMNET_INVALID_ACCESS/title",
          "value": "VMNET_INVALID_ACCESS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_return_t~1VMNET_INVALID_ACCESS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VMNET_INVALID_ACCESS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_return_t~1VMNET_PACKET_TOO_BIG/title",
          "value": "VMNET_PACKET_TOO_BIG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_return_t~1VMNET_PACKET_TOO_BIG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VMNET_PACKET_TOO_BIG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_return_t/title",
          "value": "vmnet_return_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_return_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_return_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmnet_return_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vmnet_return_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/vmnet/vmnet_return_t/vmnet_too_many_packets"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/vmnet/vmnet_return_t/vmnet_too_many_packets"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
