{
  "abstract": [
    {
      "text": "A linear animation curve causes an animation to occur evenly over its duration.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIView",
        "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/curveLinear"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIViewAnimationOptions@UIViewAnimationOptionCurveLinear",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "curveLinear"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UIView",
        "text": "UIView"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@UIViewAnimationOptions",
        "text": "AnimationOptions"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIViewAnimationOptionCurveLinear"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "curveLinear"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "curveLinear"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIView",
              "text": "UIView"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@UIViewAnimationOptions",
              "text": "AnimationOptions"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView": {
      "abstract": [
        {
          "text": "An object that manages the content for a rectangular area on the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIView"
        }
      ],
      "role": "symbol",
      "title": "UIView",
      "type": "topic",
      "url": "/documentation/uikit/uiview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions": {
      "abstract": [
        {
          "text": "Options for animating views using block objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AnimationOptions"
        }
      ],
      "role": "symbol",
      "title": "UIView.AnimationOptions",
      "type": "topic",
      "url": "/documentation/uikit/uiview/animationoptions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/allowAnimatedContent": {
      "abstract": [
        {
          "text": "Animate the views by changing the property values dynamically and redrawing the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowAnimatedContent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewAnimationOptions",
          "text": "AnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/allowAnimatedContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewAnimationOptionAllowAnimatedContent"
        }
      ],
      "role": "symbol",
      "title": "allowAnimatedContent",
      "type": "topic",
      "url": "/documentation/uikit/uiview/animationoptions/allowanimatedcontent"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/allowUserInteraction": {
      "abstract": [
        {
          "text": "Allow the user to interact with views while they are being animated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowUserInteraction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewAnimationOptions",
          "text": "AnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/allowUserInteraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewAnimationOptionAllowUserInteraction"
        }
      ],
      "role": "symbol",
      "title": "allowUserInteraction",
      "type": "topic",
      "url": "/documentation/uikit/uiview/animationoptions/allowuserinteraction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/autoreverse": {
      "abstract": [
        {
          "text": "Run the animation backwards and forwards (must be combined with the repeat option).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "autoreverse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewAnimationOptions",
          "text": "AnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/autoreverse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewAnimationOptionAutoreverse"
        }
      ],
      "role": "symbol",
      "title": "autoreverse",
      "type": "topic",
      "url": "/documentation/uikit/uiview/animationoptions/autoreverse"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/beginFromCurrentState": {
      "abstract": [
        {
          "text": "Start the animation from the current setting associated with an already in-flight animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beginFromCurrentState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewAnimationOptions",
          "text": "AnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/beginFromCurrentState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewAnimationOptionBeginFromCurrentState"
        }
      ],
      "role": "symbol",
      "title": "beginFromCurrentState",
      "type": "topic",
      "url": "/documentation/uikit/uiview/animationoptions/beginfromcurrentstate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/curveEaseIn": {
      "abstract": [
        {
          "text": "An ease-in curve causes the animation to begin slowly, and then speed up as it progresses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "curveEaseIn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewAnimationOptions",
          "text": "AnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/curveEaseIn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewAnimationOptionCurveEaseIn"
        }
      ],
      "role": "symbol",
      "title": "curveEaseIn",
      "type": "topic",
      "url": "/documentation/uikit/uiview/animationoptions/curveeasein"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/curveEaseInOut": {
      "abstract": [
        {
          "text": "Specify an ease-in ease-out curve, which causes the animation to begin slowly, accelerate through the middle of its duration, and then slow again before completing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "curveEaseInOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewAnimationOptions",
          "text": "AnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/curveEaseInOut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewAnimationOptionCurveEaseInOut"
        }
      ],
      "role": "symbol",
      "title": "curveEaseInOut",
      "type": "topic",
      "url": "/documentation/uikit/uiview/animationoptions/curveeaseinout"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/curveEaseOut": {
      "abstract": [
        {
          "text": "An ease-out curve causes the animation to begin quickly, and then slow as it completes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "curveEaseOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewAnimationOptions",
          "text": "AnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/curveEaseOut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewAnimationOptionCurveEaseOut"
        }
      ],
      "role": "symbol",
      "title": "curveEaseOut",
      "type": "topic",
      "url": "/documentation/uikit/uiview/animationoptions/curveeaseout"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/curveLinear": {
      "abstract": [
        {
          "text": "A linear animation curve causes an animation to occur evenly over its duration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "curveLinear"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewAnimationOptions",
          "text": "AnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/curveLinear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewAnimationOptionCurveLinear"
        }
      ],
      "role": "symbol",
      "title": "curveLinear",
      "type": "topic",
      "url": "/documentation/uikit/uiview/animationoptions/curvelinear"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/layoutSubviews": {
      "abstract": [
        {
          "text": "Lay out subviews at commit time so that they are animated along with their parent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layoutSubviews"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewAnimationOptions",
          "text": "AnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/layoutSubviews",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewAnimationOptionLayoutSubviews"
        }
      ],
      "role": "symbol",
      "title": "layoutSubviews",
      "type": "topic",
      "url": "/documentation/uikit/uiview/animationoptions/layoutsubviews"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/overrideInheritedCurve": {
      "abstract": [
        {
          "text": "Force the animation to use the original curve value specified when the animation was submitted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "overrideInheritedCurve"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewAnimationOptions",
          "text": "AnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/overrideInheritedCurve",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewAnimationOptionOverrideInheritedCurve"
        }
      ],
      "role": "symbol",
      "title": "overrideInheritedCurve",
      "type": "topic",
      "url": "/documentation/uikit/uiview/animationoptions/overrideinheritedcurve"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/overrideInheritedDuration": {
      "abstract": [
        {
          "text": "Force the animation to use the original duration value specified when the animation was submitted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "overrideInheritedDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewAnimationOptions",
          "text": "AnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/overrideInheritedDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewAnimationOptionOverrideInheritedDuration"
        }
      ],
      "role": "symbol",
      "title": "overrideInheritedDuration",
      "type": "topic",
      "url": "/documentation/uikit/uiview/animationoptions/overrideinheritedduration"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/overrideInheritedOptions": {
      "abstract": [
        {
          "text": "The option to not inherit the animation type or any options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "overrideInheritedOptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewAnimationOptions",
          "text": "AnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/overrideInheritedOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewAnimationOptionOverrideInheritedOptions"
        }
      ],
      "role": "symbol",
      "title": "overrideInheritedOptions",
      "type": "topic",
      "url": "/documentation/uikit/uiview/animationoptions/overrideinheritedoptions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/repeat": {
      "abstract": [
        {
          "text": "Repeat the animation indefinitely.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`repeat`"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewAnimationOptions",
          "text": "AnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/repeat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewAnimationOptionRepeat"
        }
      ],
      "role": "symbol",
      "title": "repeat",
      "type": "topic",
      "url": "/documentation/uikit/uiview/animationoptions/repeat"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/showHideTransitionViews": {
      "abstract": [
        {
          "text": "Hide or show views during a view transition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showHideTransitionViews"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewAnimationOptions",
          "text": "AnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/showHideTransitionViews",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewAnimationOptionShowHideTransitionViews"
        }
      ],
      "role": "symbol",
      "title": "showHideTransitionViews",
      "type": "topic",
      "url": "/documentation/uikit/uiview/animationoptions/showhidetransitionviews"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/transitionFlipFromLeft": {
      "abstract": [
        {
          "text": "A transition that flips a view around its vertical axis from left to right (the left side of the view moves toward the front and right side toward the back).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transitionFlipFromLeft"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewAnimationOptions",
          "text": "AnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/transitionFlipFromLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewAnimationOptionTransitionFlipFromLeft"
        }
      ],
      "role": "symbol",
      "title": "transitionFlipFromLeft",
      "type": "topic",
      "url": "/documentation/uikit/uiview/animationoptions/transitionflipfromleft"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/transitionFlipFromRight": {
      "abstract": [
        {
          "text": "A transition that flips a view around its vertical axis from right to left (the right side of the view moves toward the front and left side toward the back).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transitionFlipFromRight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewAnimationOptions",
          "text": "AnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/transitionFlipFromRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewAnimationOptionTransitionFlipFromRight"
        }
      ],
      "role": "symbol",
      "title": "transitionFlipFromRight",
      "type": "topic",
      "url": "/documentation/uikit/uiview/animationoptions/transitionflipfromright"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewAnimationOptions/UIViewAnimationOptionTransitionNone": {
      "abstract": [
        {
          "text": "No transition is specified.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIViewAnimationOptionTransitionNone"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewAnimationOptions/UIViewAnimationOptionTransitionNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIViewAnimationOptionTransitionNone",
      "type": "topic",
      "url": "/documentation/uikit/uiviewanimationoptions/uiviewanimationoptiontransitionnone"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/layoutSubviews",
        "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/allowUserInteraction",
        "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/beginFromCurrentState",
        "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/repeat",
        "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/autoreverse",
        "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/overrideInheritedDuration",
        "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/overrideInheritedCurve",
        "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/allowAnimatedContent",
        "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/showHideTransitionViews",
        "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/overrideInheritedOptions",
        "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/curveEaseInOut",
        "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/curveEaseIn",
        "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/curveEaseOut",
        "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/transitionFlipFromLeft",
        "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/transitionFlipFromRight"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIViewAnimationOptionCurveLinear"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationOptionCurveLinear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/layoutSubviews",
                "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/allowUserInteraction",
                "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/beginFromCurrentState",
                "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/repeat",
                "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/autoreverse",
                "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/overrideInheritedDuration",
                "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/overrideInheritedCurve",
                "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/allowAnimatedContent",
                "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/showHideTransitionViews",
                "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/overrideInheritedOptions",
                "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/curveEaseInOut",
                "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/curveEaseIn",
                "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/curveEaseOut",
                "doc://com.apple.uikit/documentation/UIKit/UIViewAnimationOptions/UIViewAnimationOptionTransitionNone",
                "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/transitionFlipFromLeft"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UIViewAnimationOptionCurveLinear"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1curveEaseOut/title",
          "value": "UIViewAnimationOptionCurveEaseOut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1curveEaseOut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationOptionCurveEaseOut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1layoutSubviews/title",
          "value": "UIViewAnimationOptionLayoutSubviews"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1layoutSubviews/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationOptionLayoutSubviews"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1autoreverse/title",
          "value": "UIViewAnimationOptionAutoreverse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1autoreverse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationOptionAutoreverse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1overrideInheritedOptions/title",
          "value": "UIViewAnimationOptionOverrideInheritedOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1overrideInheritedOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationOptionOverrideInheritedOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1overrideInheritedCurve/title",
          "value": "UIViewAnimationOptionOverrideInheritedCurve"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1overrideInheritedCurve/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationOptionOverrideInheritedCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1curveEaseIn/title",
          "value": "UIViewAnimationOptionCurveEaseIn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1curveEaseIn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationOptionCurveEaseIn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1showHideTransitionViews/title",
          "value": "UIViewAnimationOptionShowHideTransitionViews"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1showHideTransitionViews/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationOptionShowHideTransitionViews"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/title",
          "value": "UIView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1allowUserInteraction/title",
          "value": "UIViewAnimationOptionAllowUserInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1allowUserInteraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationOptionAllowUserInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1curveEaseInOut/title",
          "value": "UIViewAnimationOptionCurveEaseInOut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1curveEaseInOut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationOptionCurveEaseInOut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1beginFromCurrentState/title",
          "value": "UIViewAnimationOptionBeginFromCurrentState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1beginFromCurrentState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationOptionBeginFromCurrentState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions/title",
          "value": "UIViewAnimationOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1curveLinear/title",
          "value": "UIViewAnimationOptionCurveLinear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1curveLinear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationOptionCurveLinear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1overrideInheritedDuration/title",
          "value": "UIViewAnimationOptionOverrideInheritedDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1overrideInheritedDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationOptionOverrideInheritedDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1allowAnimatedContent/title",
          "value": "UIViewAnimationOptionAllowAnimatedContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1allowAnimatedContent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationOptionAllowAnimatedContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1repeat/title",
          "value": "UIViewAnimationOptionRepeat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1repeat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationOptionRepeat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1transitionFlipFromRight/title",
          "value": "UIViewAnimationOptionTransitionFlipFromRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1transitionFlipFromRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationOptionTransitionFlipFromRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1transitionFlipFromLeft/title",
          "value": "UIViewAnimationOptionTransitionFlipFromLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1transitionFlipFromLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationOptionTransitionFlipFromLeft"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiview/animationoptions/curvelinear"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiview/animationoptions/curvelinear"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
