{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.spritekit/documentation/SpriteKit",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKUniform"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.spritekit/documentation/SpriteKit/SKUniform/uniformWithName:vectorFloat3:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SKUniform(cm)uniformWithName:vectorFloat3:",
    "fragments": [
      {
        "kind": "text",
        "text": "+ "
      },
      {
        "kind": "identifier",
        "text": "uniformWithName:vectorFloat3:"
      }
    ],
    "modules": [
      {
        "name": "SpriteKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "uniformWithName:vectorFloat3:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "uniformWithName:vectorFloat3:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "+ ("
            },
            {
              "kind": "keyword",
              "text": "instancetype"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "uniformWithName:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "name"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "vectorFloat3:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/vector_float3",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@vector_float3",
              "text": "vector_float3"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "value"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit": {
      "abstract": [
        {
          "text": "Add high-performance 2D content with smooth animations to your app, or create a game with a high-level set of 2D game-based tools.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SpriteKit",
      "type": "topic",
      "url": "/documentation/spritekit"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKUniform": {
      "abstract": [
        {
          "text": "A container for uniform shader data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKUniform"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKUniform",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKUniform"
        }
      ],
      "role": "symbol",
      "title": "SKUniform",
      "type": "topic",
      "url": "/documentation/spritekit/skuniform"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKUniform/uniformWithName:matrixFloat2x2:": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "uniformWithName:matrixFloat2x2:"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKUniform/uniformWithName:matrixFloat2x2:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "uniformWithName:matrixFloat2x2:"
        }
      ],
      "role": "symbol",
      "title": "uniformWithName:matrixFloat2x2:",
      "type": "topic",
      "url": "/documentation/spritekit/skuniform/uniformwithname:matrixfloat2x2:"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKUniform/uniformWithName:matrixFloat3x3:": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "uniformWithName:matrixFloat3x3:"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKUniform/uniformWithName:matrixFloat3x3:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "uniformWithName:matrixFloat3x3:"
        }
      ],
      "role": "symbol",
      "title": "uniformWithName:matrixFloat3x3:",
      "type": "topic",
      "url": "/documentation/spritekit/skuniform/uniformwithname:matrixfloat3x3:"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKUniform/uniformWithName:matrixFloat4x4:": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "uniformWithName:matrixFloat4x4:"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKUniform/uniformWithName:matrixFloat4x4:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "uniformWithName:matrixFloat4x4:"
        }
      ],
      "role": "symbol",
      "title": "uniformWithName:matrixFloat4x4:",
      "type": "topic",
      "url": "/documentation/spritekit/skuniform/uniformwithname:matrixfloat4x4:"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKUniform/uniformWithName:vectorFloat2:": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "uniformWithName:vectorFloat2:"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKUniform/uniformWithName:vectorFloat2:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "uniformWithName:vectorFloat2:"
        }
      ],
      "role": "symbol",
      "title": "uniformWithName:vectorFloat2:",
      "type": "topic",
      "url": "/documentation/spritekit/skuniform/uniformwithname:vectorfloat2:"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKUniform/uniformWithName:vectorFloat3:": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "uniformWithName:vectorFloat3:"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKUniform/uniformWithName:vectorFloat3:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "uniformWithName:vectorFloat3:"
        }
      ],
      "role": "symbol",
      "title": "uniformWithName:vectorFloat3:",
      "type": "topic",
      "url": "/documentation/spritekit/skuniform/uniformwithname:vectorfloat3:"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKUniform/uniformWithName:vectorFloat4:": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "uniformWithName:vectorFloat4:"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKUniform/uniformWithName:vectorFloat4:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "uniformWithName:vectorFloat4:"
        }
      ],
      "role": "symbol",
      "title": "uniformWithName:vectorFloat4:",
      "type": "topic",
      "url": "/documentation/spritekit/skuniform/uniformwithname:vectorfloat4:"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/vector_float3": {
      "abstract": [
        {
          "text": "A floating point vector type used to perform physics calculations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_float3"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/vector_float3",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_float3",
      "type": "topic",
      "url": "/documentation/spritekit/vector_float3"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Type-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/SKUniform/uniformWithName:matrixFloat2x2:",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKUniform/uniformWithName:matrixFloat3x3:",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKUniform/uniformWithName:matrixFloat4x4:",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKUniform/uniformWithName:vectorFloat2:",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKUniform/uniformWithName:vectorFloat4:"
      ],
      "title": "Type Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKUniform/title",
          "value": "SKUniform"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKUniform/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKUniform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKUniform/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKUniform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/spritekit/skuniform/uniformwithname:vectorfloat3:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
