{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCRecordingOutputDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)SCRecordingOutputDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SCRecordingOutputDelegate"
      }
    ],
    "modules": [
      {
        "name": "ScreenCaptureKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SCRecordingOutputDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.2",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "SCRecordingOutputDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SCRecordingOutputDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit": {
      "abstract": [
        {
          "text": "Filter and select screen content and stream it to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ScreenCaptureKit",
      "type": "topic",
      "url": "/documentation/screencapturekit"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCRecordingOutput/init(configuration:delegate:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "configuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCRecordingOutputConfiguration",
          "text": "SCRecordingOutputConfiguration"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)SCRecordingOutputDelegate",
          "text": "SCRecordingOutputDelegate"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCRecordingOutput/init(configuration:delegate:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithConfiguration:delegate:"
        }
      ],
      "role": "symbol",
      "title": "init(configuration:delegate:)",
      "type": "topic",
      "url": "/documentation/screencapturekit/screcordingoutput/init(configuration:delegate:)"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCRecordingOutputConfiguration": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCRecordingOutputConfiguration"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCRecordingOutputConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCRecordingOutputConfiguration"
        }
      ],
      "role": "symbol",
      "title": "SCRecordingOutputConfiguration",
      "type": "topic",
      "url": "/documentation/screencapturekit/screcordingoutputconfiguration"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCRecordingOutputDelegate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCRecordingOutputDelegate"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCRecordingOutputDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCRecordingOutputDelegate"
        }
      ],
      "role": "symbol",
      "title": "SCRecordingOutputDelegate",
      "type": "topic",
      "url": "/documentation/screencapturekit/screcordingoutputdelegate"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCRecordingOutputDelegate/recordingOutput(_:didFailWithError:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recordingOutput"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCRecordingOutput",
          "text": "SCRecordingOutput"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didFailWithError"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCRecordingOutputDelegate/recordingOutput(_:didFailWithError:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "recordingOutput:didFailWithError:"
        }
      ],
      "role": "symbol",
      "title": "recordingOutput(_:didFailWithError:)",
      "type": "topic",
      "url": "/documentation/screencapturekit/screcordingoutputdelegate/recordingoutput(_:didfailwitherror:)"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCRecordingOutputDelegate/recordingOutputDidFinishRecording(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recordingOutputDidFinishRecording"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCRecordingOutput",
          "text": "SCRecordingOutput"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCRecordingOutputDelegate/recordingOutputDidFinishRecording(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "recordingOutputDidFinishRecording:"
        }
      ],
      "role": "symbol",
      "title": "recordingOutputDidFinishRecording(_:)",
      "type": "topic",
      "url": "/documentation/screencapturekit/screcordingoutputdelegate/recordingoutputdidfinishrecording(_:)"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCRecordingOutputDelegate/recordingOutputDidStartRecording(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recordingOutputDidStartRecording"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCRecordingOutput",
          "text": "SCRecordingOutput"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCRecordingOutputDelegate/recordingOutputDidStartRecording(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "recordingOutputDidStartRecording:"
        }
      ],
      "role": "symbol",
      "title": "recordingOutputDidStartRecording(_:)",
      "type": "topic",
      "url": "/documentation/screencapturekit/screcordingoutputdelegate/recordingoutputdidstartrecording(_:)"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-recording-output",
      "generated": true,
      "identifiers": [
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCRecordingOutput/init(configuration:delegate:)",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCRecordingOutputConfiguration"
      ],
      "title": "Creating a recording output"
    }
  ],
  "topicSections": [
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCRecordingOutputDelegate/recordingOutput(_:didFailWithError:)",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCRecordingOutputDelegate/recordingOutputDidFinishRecording(_:)",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCRecordingOutputDelegate/recordingOutputDidStartRecording(_:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.2",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SCRecordingOutputDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCRecordingOutputDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCRecordingOutputDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCRecordingOutputDelegate/recordingOutput(_:didFailWithError:)",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCRecordingOutputDelegate/recordingOutputDidFinishRecording(_:)",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCRecordingOutputDelegate/recordingOutputDidStartRecording(_:)"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-a-recording-output",
              "generated": true,
              "identifiers": [
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCRecordingOutput/init(configuration:delegate:)",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCRecordingOutputConfiguration"
              ],
              "title": "Creating a recording output"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SCRecordingOutputDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCRecordingOutputDelegate~1recordingOutputDidFinishRecording(_:)/title",
          "value": "recordingOutputDidFinishRecording:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCRecordingOutputDelegate~1recordingOutputDidFinishRecording(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "recordingOutputDidFinishRecording:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCRecordingOutputDelegate~1recordingOutput(_:didFailWithError:)/title",
          "value": "recordingOutput:didFailWithError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCRecordingOutputDelegate~1recordingOutput(_:didFailWithError:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "recordingOutput:didFailWithError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCRecordingOutputConfiguration/title",
          "value": "SCRecordingOutputConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCRecordingOutputConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCRecordingOutputConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCRecordingOutputConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCRecordingOutputConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCRecordingOutput~1init(configuration:delegate:)/title",
          "value": "initWithConfiguration:delegate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCRecordingOutput~1init(configuration:delegate:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithConfiguration:delegate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCRecordingOutputDelegate~1recordingOutputDidStartRecording(_:)/title",
          "value": "recordingOutputDidStartRecording:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCRecordingOutputDelegate~1recordingOutputDidStartRecording(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "recordingOutputDidStartRecording:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCRecordingOutputDelegate/title",
          "value": "SCRecordingOutputDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCRecordingOutputDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCRecordingOutputDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCRecordingOutputDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCRecordingOutputDelegate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/screencapturekit/screcordingoutputdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/screencapturekit/screcordingoutputdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
