{
  "abstract": [
    {
      "text": "An instance that represents a stream of shareable content.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStream"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SCStream",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SCStream"
      }
    ],
    "modules": [
      {
        "name": "ScreenCaptureKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SCStream"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.2",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.3",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "SCStream"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SCStream"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use a stream to capture video of screen content like apps and windows. Create a content stream by passing it an instance of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentFilter",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamConfiguration",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. The stream uses the filter to determine which screen content to capture, and uses the configuration data to configure the output.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit": {
      "abstract": [
        {
          "text": "Filter and select screen content and stream it to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ScreenCaptureKit",
      "type": "topic",
      "url": "/documentation/screencapturekit"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentFilter": {
      "abstract": [
        {
          "text": "An instance that filters the content a stream captures.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCContentFilter"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCContentFilter"
        }
      ],
      "role": "symbol",
      "title": "SCContentFilter",
      "type": "topic",
      "url": "/documentation/screencapturekit/sccontentfilter"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCRecordingOutput": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCRecordingOutput"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCRecordingOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCRecordingOutput"
        }
      ],
      "role": "symbol",
      "title": "SCRecordingOutput",
      "type": "topic",
      "url": "/documentation/screencapturekit/screcordingoutput"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCScreenshotManager": {
      "abstract": [
        {
          "text": "An instance for the capture of single frames from a stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCScreenshotManager"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCScreenshotManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCScreenshotManager"
        }
      ],
      "role": "symbol",
      "title": "SCScreenshotManager",
      "type": "topic",
      "url": "/documentation/screencapturekit/scscreenshotmanager"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStream": {
      "abstract": [
        {
          "text": "An instance that represents a stream of shareable content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCStream"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStream",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStream"
        }
      ],
      "role": "symbol",
      "title": "SCStream",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstream"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStream/addRecordingOutput(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addRecordingOutput"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCRecordingOutput",
          "text": "SCRecordingOutput"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStream/addRecordingOutput(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addRecordingOutput:error:"
        }
      ],
      "role": "symbol",
      "title": "addRecordingOutput(_:)",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstream/addrecordingoutput(_:)"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStream/addStreamOutput(_:type:sampleHandlerQueue:)": {
      "abstract": [
        {
          "text": "Adds a destination that receives the stream output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addStreamOutput"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)SCStreamOutput",
          "text": "SCStreamOutput"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCStreamOutputType",
          "text": "SCStreamOutputType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "sampleHandlerQueue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": "?) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStream/addStreamOutput(_:type:sampleHandlerQueue:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addStreamOutput:type:sampleHandlerQueue:error:"
        }
      ],
      "role": "symbol",
      "title": "addStreamOutput(_:type:sampleHandlerQueue:)",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstream/addstreamoutput(_:type:samplehandlerqueue:)"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStream/init(filter:configuration:delegate:)": {
      "abstract": [
        {
          "text": "Creates a stream with a content filter and configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "filter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCContentFilter",
          "text": "SCContentFilter"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "configuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCStreamConfiguration",
          "text": "SCStreamConfiguration"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)SCStreamDelegate",
          "text": "SCStreamDelegate"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStream/init(filter:configuration:delegate:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithFilter:configuration:delegate:"
        }
      ],
      "role": "symbol",
      "title": "init(filter:configuration:delegate:)",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstream/init(filter:configuration:delegate:)"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStream/removeRecordingOutput(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeRecordingOutput"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCRecordingOutput",
          "text": "SCRecordingOutput"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStream/removeRecordingOutput(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeRecordingOutput:error:"
        }
      ],
      "role": "symbol",
      "title": "removeRecordingOutput(_:)",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstream/removerecordingoutput(_:)"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStream/removeStreamOutput(_:type:)": {
      "abstract": [
        {
          "text": "Removes a destination from receiving stream output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeStreamOutput"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)SCStreamOutput",
          "text": "SCStreamOutput"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCStreamOutputType",
          "text": "SCStreamOutputType"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStream/removeStreamOutput(_:type:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeStreamOutput:type:error:"
        }
      ],
      "role": "symbol",
      "title": "removeStreamOutput(_:type:)",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstream/removestreamoutput(_:type:)"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStream/startCapture(completionHandler:)": {
      "abstract": [
        {
          "text": "Starts the stream with a callback to indicate whether it successfully starts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startCapture"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStream/startCapture(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startCaptureWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "startCapture(completionHandler:)",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstream/startcapture(completionhandler:)"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStream/stopCapture(completionHandler:)": {
      "abstract": [
        {
          "text": "Stops the stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stopCapture"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStream/stopCapture(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stopCaptureWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "stopCapture(completionHandler:)",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstream/stopcapture(completionhandler:)"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStream/synchronizationClock": {
      "abstract": [
        {
          "text": "A clock to use for output synchronization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "synchronizationClock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMClockRef",
          "text": "CMClock"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStream/synchronizationClock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "synchronizationClock"
        }
      ],
      "role": "symbol",
      "title": "synchronizationClock",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstream/synchronizationclock"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStream/updateConfiguration(_:completionHandler:)": {
      "abstract": [
        {
          "text": "Updates the stream with a new configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateConfiguration"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCStreamConfiguration",
          "text": "SCStreamConfiguration"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStream/updateConfiguration(_:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updateConfiguration:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "updateConfiguration(_:completionHandler:)",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstream/updateconfiguration(_:completionhandler:)"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStream/updateContentFilter(_:completionHandler:)": {
      "abstract": [
        {
          "text": "Updates the stream by applying a new content filter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateContentFilter"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCContentFilter",
          "text": "SCContentFilter"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStream/updateContentFilter(_:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updateContentFilter:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "updateContentFilter(_:completionHandler:)",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstream/updatecontentfilter(_:completionhandler:)"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamConfiguration": {
      "abstract": [
        {
          "text": "An instance that provides the output configuration for a stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCStreamConfiguration"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStreamConfiguration"
        }
      ],
      "role": "symbol",
      "title": "SCStreamConfiguration",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamconfiguration"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamDelegate": {
      "abstract": [
        {
          "text": "A delegate protocol your app implements to respond to stream events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCStreamDelegate"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStreamDelegate"
        }
      ],
      "role": "symbol",
      "title": "SCStreamDelegate",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamdelegate"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Content-capture",
      "generated": true,
      "identifiers": [
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamConfiguration",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentFilter",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamDelegate",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCScreenshotManager"
      ],
      "title": "Content capture"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-stream",
      "identifiers": [
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStream/init(filter:configuration:delegate:)"
      ],
      "title": "Creating a stream"
    },
    {
      "anchor": "Updating-stream-configuration",
      "identifiers": [
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStream/updateConfiguration(_:completionHandler:)",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStream/updateContentFilter(_:completionHandler:)"
      ],
      "title": "Updating stream configuration"
    },
    {
      "anchor": "Adding-and-removing-stream-output",
      "identifiers": [
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStream/addStreamOutput(_:type:sampleHandlerQueue:)",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStream/removeStreamOutput(_:type:)"
      ],
      "title": "Adding and removing stream output"
    },
    {
      "anchor": "Adding-and-removing-recording-output",
      "identifiers": [
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStream/addRecordingOutput(_:)",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStream/removeRecordingOutput(_:)",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCRecordingOutput"
      ],
      "title": "Adding and removing recording output"
    },
    {
      "anchor": "Starting-and-stopping-a-stream",
      "identifiers": [
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStream/startCapture(completionHandler:)",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStream/stopCapture(completionHandler:)"
      ],
      "title": "Starting and stopping a stream"
    },
    {
      "anchor": "Stream-synchronization",
      "identifiers": [
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStream/synchronizationClock"
      ],
      "title": "Stream synchronization"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.2",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.3",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SCStream"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStream"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStream"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-stream",
              "identifiers": [
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStream/init(filter:configuration:delegate:)"
              ],
              "title": "Creating a stream"
            },
            {
              "anchor": "Updating-stream-configuration",
              "identifiers": [
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStream/updateConfiguration(_:completionHandler:)",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStream/updateContentFilter(_:completionHandler:)"
              ],
              "title": "Updating stream configuration"
            },
            {
              "anchor": "Adding-and-removing-stream-output",
              "identifiers": [
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStream/addStreamOutput(_:type:sampleHandlerQueue:)",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStream/removeStreamOutput(_:type:)"
              ],
              "title": "Adding and removing stream output"
            },
            {
              "anchor": "Adding-and-removing-recording-output",
              "identifiers": [
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStream/addRecordingOutput(_:)",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStream/removeRecordingOutput(_:)",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCRecordingOutput"
              ],
              "title": "Adding and removing recording output"
            },
            {
              "anchor": "Starting-and-stopping-a-stream",
              "identifiers": [
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStream/startCapture(completionHandler:)",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStream/stopCapture(completionHandler:)"
              ],
              "title": "Starting and stopping a stream"
            },
            {
              "anchor": "Stream-synchronization",
              "identifiers": [
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStream/synchronizationClock"
              ],
              "title": "Stream synchronization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Content-capture",
              "generated": true,
              "identifiers": [
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamConfiguration",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentFilter",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamDelegate",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCScreenshotManager"
              ],
              "title": "Content capture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SCStream"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCRecordingOutput/title",
          "value": "SCRecordingOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCRecordingOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCRecordingOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCRecordingOutput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCRecordingOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStream~1removeStreamOutput(_:type:)/title",
          "value": "removeStreamOutput:type:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStream~1removeStreamOutput(_:type:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeStreamOutput:type:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStream~1updateContentFilter(_:completionHandler:)/title",
          "value": "updateContentFilter:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStream~1updateContentFilter(_:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "updateContentFilter:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStream~1startCapture(completionHandler:)/title",
          "value": "startCaptureWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStream~1startCapture(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startCaptureWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStream~1removeRecordingOutput(_:)/title",
          "value": "removeRecordingOutput:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStream~1removeRecordingOutput(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeRecordingOutput:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStream~1init(filter:configuration:delegate:)/title",
          "value": "initWithFilter:configuration:delegate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStream~1init(filter:configuration:delegate:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithFilter:configuration:delegate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStream~1synchronizationClock/title",
          "value": "synchronizationClock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStream~1synchronizationClock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "synchronizationClock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStream~1addRecordingOutput(_:)/title",
          "value": "addRecordingOutput:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStream~1addRecordingOutput(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addRecordingOutput:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStream~1stopCapture(completionHandler:)/title",
          "value": "stopCaptureWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStream~1stopCapture(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "stopCaptureWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStream~1updateConfiguration(_:completionHandler:)/title",
          "value": "updateConfiguration:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStream~1updateConfiguration(_:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "updateConfiguration:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamDelegate/title",
          "value": "SCStreamDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCScreenshotManager/title",
          "value": "SCScreenshotManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCScreenshotManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCScreenshotManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCScreenshotManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCScreenshotManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStream/title",
          "value": "SCStream"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStream/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStream"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStream/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStream"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCContentFilter/title",
          "value": "SCContentFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCContentFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCContentFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCContentFilter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCContentFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamConfiguration/title",
          "value": "SCStreamConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStream~1addStreamOutput(_:type:sampleHandlerQueue:)/title",
          "value": "addStreamOutput:type:sampleHandlerQueue:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStream~1addStreamOutput(_:type:sampleHandlerQueue:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addStreamOutput:type:sampleHandlerQueue:error:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/screencapturekit/scstream"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/screencapturekit/scstream"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
