{
  "abstract": [
    {
      "text": "The context for the current request.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.identitylookup/documentation/IdentityLookupUI",
        "doc://com.apple.identitylookup/documentation/IdentityLookupUI/ILClassificationUIExtensionViewController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.identitylookup/documentation/IdentityLookupUI/ILClassificationUIExtensionViewController/extensionContext"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ILClassificationUIExtensionViewController(py)extensionContext",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "extensionContext"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)ILClassificationUIExtensionContext",
        "text": "ILClassificationUIExtensionContext"
      }
    ],
    "modules": [
      {
        "name": "IdentityLookupUI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "extensionContext"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "extensionContext"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "extensionContext"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookupUI/ILClassificationUIExtensionContext",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)ILClassificationUIExtensionContext",
              "text": "ILClassificationUIExtensionContext"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookupUI": {
      "abstract": [],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookupUI",
      "kind": "symbol",
      "role": "collection",
      "title": "IdentityLookupUI",
      "type": "topic",
      "url": "/documentation/identitylookupui"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookupUI/ILClassificationUIExtensionContext": {
      "abstract": [
        {
          "text": "An object that manages the state of the current request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ILClassificationUIExtensionContext"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookupUI/ILClassificationUIExtensionContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ILClassificationUIExtensionContext"
        }
      ],
      "role": "symbol",
      "title": "ILClassificationUIExtensionContext",
      "type": "topic",
      "url": "/documentation/identitylookupui/ilclassificationuiextensioncontext"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookupUI/ILClassificationUIExtensionViewController": {
      "abstract": [
        {
          "text": "The superclass for an Unwanted Communication Reporting extension’s principal view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ILClassificationUIExtensionViewController"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookupUI/ILClassificationUIExtensionViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ILClassificationUIExtensionViewController"
        }
      ],
      "role": "symbol",
      "title": "ILClassificationUIExtensionViewController",
      "type": "topic",
      "url": "/documentation/identitylookupui/ilclassificationuiextensionviewcontroller"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookupUI/ILClassificationUIExtensionViewController/extensionContext": {
      "abstract": [
        {
          "text": "The context for the current request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extensionContext"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ILClassificationUIExtensionContext",
          "text": "ILClassificationUIExtensionContext"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookupUI/ILClassificationUIExtensionViewController/extensionContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "extensionContext"
        }
      ],
      "role": "symbol",
      "title": "extensionContext",
      "type": "topic",
      "url": "/documentation/identitylookupui/ilclassificationuiextensionviewcontroller/extensioncontext"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-the-Request",
      "generated": true,
      "identifiers": [
        "doc://com.apple.identitylookup/documentation/IdentityLookupUI/ILClassificationUIExtensionContext"
      ],
      "title": "Managing the Request"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "extensionContext"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "extensionContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.identitylookup/documentation/IdentityLookupUI",
                "doc://com.apple.identitylookup/documentation/IdentityLookupUI/ILClassificationUIExtensionViewController"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-the-Request",
              "generated": true,
              "identifiers": [
                "doc://com.apple.identitylookup/documentation/IdentityLookupUI/ILClassificationUIExtensionContext"
              ],
              "title": "Managing the Request"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookupUI/ILClassificationUIExtensionContext",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)ILClassificationUIExtensionContext",
                    "text": "ILClassificationUIExtensionContext"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "extensionContext"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookupUI~1ILClassificationUIExtensionContext/title",
          "value": "ILClassificationUIExtensionContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookupUI~1ILClassificationUIExtensionContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ILClassificationUIExtensionContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookupUI~1ILClassificationUIExtensionContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ILClassificationUIExtensionContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookupUI~1ILClassificationUIExtensionViewController~1extensionContext/title",
          "value": "extensionContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookupUI~1ILClassificationUIExtensionViewController~1extensionContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "extensionContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookupUI~1ILClassificationUIExtensionViewController/title",
          "value": "ILClassificationUIExtensionViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookupUI~1ILClassificationUIExtensionViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ILClassificationUIExtensionViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookupUI~1ILClassificationUIExtensionViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ILClassificationUIExtensionViewController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/identitylookupui/ilclassificationuiextensionviewcontroller/extensioncontext"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/identitylookupui/ilclassificationuiextensionviewcontroller/extensioncontext"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
