{
  "abstract": [
    {
      "text": "The value that represents no selected enumeration options.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutFragment/EnumerationOptions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutFragmentEnumerationOptions/NSTextLayoutFragmentEnumerationOptionsNone"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSTextLayoutFragmentEnumerationOptions@NSTextLayoutFragmentEnumerationOptionsNone",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSTextLayoutFragmentEnumerationOptionsNone"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSTextLayoutFragmentEnumerationOptionsNone"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "symbolKind": "case",
    "title": "NSTextLayoutFragmentEnumerationOptionsNone"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "NSTextLayoutFragmentEnumerationOptionsNone"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutFragment/EnumerationOptions": {
      "abstract": [
        {
          "text": "Values that describe options for enumerating text layout fragments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EnumerationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutFragment/EnumerationOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EnumerationOptions"
        }
      ],
      "role": "symbol",
      "title": "NSTextLayoutFragment.EnumerationOptions",
      "type": "topic",
      "url": "/documentation/uikit/nstextlayoutfragment/enumerationoptions"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutFragment/EnumerationOptions/ensuresExtraLineFragment": {
      "abstract": [
        {
          "text": "Synthesize the extra line fragment when necessary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ensuresExtraLineFragment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextLayoutFragment",
          "text": "NSTextLayoutFragment"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTextLayoutFragmentEnumerationOptions",
          "text": "EnumerationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutFragment/EnumerationOptions/ensuresExtraLineFragment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextLayoutFragmentEnumerationOptionsEnsuresExtraLineFragment"
        }
      ],
      "role": "symbol",
      "title": "ensuresExtraLineFragment",
      "type": "topic",
      "url": "/documentation/uikit/nstextlayoutfragment/enumerationoptions/ensuresextralinefragment"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutFragment/EnumerationOptions/ensuresLayout": {
      "abstract": [
        {
          "text": "When enumerating, tell the layout fragments to layout their contents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ensuresLayout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextLayoutFragment",
          "text": "NSTextLayoutFragment"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTextLayoutFragmentEnumerationOptions",
          "text": "EnumerationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutFragment/EnumerationOptions/ensuresLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextLayoutFragmentEnumerationOptionsEnsuresLayout"
        }
      ],
      "role": "symbol",
      "title": "ensuresLayout",
      "type": "topic",
      "url": "/documentation/uikit/nstextlayoutfragment/enumerationoptions/ensureslayout"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutFragment/EnumerationOptions/estimatesSize": {
      "abstract": [
        {
          "text": "When enumerating, tell the layout fragments to estimate their size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "estimatesSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextLayoutFragment",
          "text": "NSTextLayoutFragment"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTextLayoutFragmentEnumerationOptions",
          "text": "EnumerationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutFragment/EnumerationOptions/estimatesSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextLayoutFragmentEnumerationOptionsEstimatesSize"
        }
      ],
      "role": "symbol",
      "title": "estimatesSize",
      "type": "topic",
      "url": "/documentation/uikit/nstextlayoutfragment/enumerationoptions/estimatessize"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutFragment/EnumerationOptions/reverse": {
      "abstract": [
        {
          "text": "Causes the enumeration to start from the last element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reverse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextLayoutFragment",
          "text": "NSTextLayoutFragment"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTextLayoutFragmentEnumerationOptions",
          "text": "EnumerationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutFragment/EnumerationOptions/reverse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextLayoutFragmentEnumerationOptionsReverse"
        }
      ],
      "role": "symbol",
      "title": "reverse",
      "type": "topic",
      "url": "/documentation/uikit/nstextlayoutfragment/enumerationoptions/reverse"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutFragmentEnumerationOptions/NSTextLayoutFragmentEnumerationOptionsNone": {
      "abstract": [
        {
          "text": "The value that represents no selected enumeration options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextLayoutFragmentEnumerationOptionsNone"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutFragmentEnumerationOptions/NSTextLayoutFragmentEnumerationOptionsNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextLayoutFragmentEnumerationOptionsNone",
      "type": "topic",
      "url": "/documentation/uikit/nstextlayoutfragmentenumerationoptions/nstextlayoutfragmentenumerationoptionsnone"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Layout-fragment-characteristics",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutFragment/EnumerationOptions/ensuresExtraLineFragment",
        "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutFragment/EnumerationOptions/ensuresLayout",
        "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutFragment/EnumerationOptions/estimatesSize",
        "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutFragment/EnumerationOptions/reverse"
      ],
      "title": "Layout fragment characteristics"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutFragment~1EnumerationOptions~1reverse/title",
          "value": "NSTextLayoutFragmentEnumerationOptionsReverse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutFragment~1EnumerationOptions~1reverse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLayoutFragmentEnumerationOptionsReverse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutFragment~1EnumerationOptions~1ensuresExtraLineFragment/title",
          "value": "NSTextLayoutFragmentEnumerationOptionsEnsuresExtraLineFragment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutFragment~1EnumerationOptions~1ensuresExtraLineFragment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLayoutFragmentEnumerationOptionsEnsuresExtraLineFragment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutFragment~1EnumerationOptions~1estimatesSize/title",
          "value": "NSTextLayoutFragmentEnumerationOptionsEstimatesSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutFragment~1EnumerationOptions~1estimatesSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLayoutFragmentEnumerationOptionsEstimatesSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutFragment~1EnumerationOptions/title",
          "value": "NSTextLayoutFragmentEnumerationOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutFragment~1EnumerationOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLayoutFragmentEnumerationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutFragment~1EnumerationOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLayoutFragmentEnumerationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutFragment~1EnumerationOptions~1ensuresLayout/title",
          "value": "NSTextLayoutFragmentEnumerationOptionsEnsuresLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutFragment~1EnumerationOptions~1ensuresLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLayoutFragmentEnumerationOptionsEnsuresLayout"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/nstextlayoutfragmentenumerationoptions/nstextlayoutfragmentenumerationoptionsnone"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
