{
  "abstract": [
    {
      "text": "A constant indicating a point of interest during a workout session.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEventType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEventType/marker"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@HKWorkoutEventType@HKWorkoutEventTypeMarker",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "marker"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HKWorkoutEventTypeMarker"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "HKWorkoutEventType.marker"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "marker"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use markers to indicate arbitrary points during a workout (for example, when the user reaches the top of a hill during a run).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEventType": {
      "abstract": [
        {
          "text": "Constants that represent events occurring during a workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutEventType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEventType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutEventType"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutEventType",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkouteventtype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEventType/lap": {
      "abstract": [
        {
          "text": "A constant indicating a lap.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lap"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEventType/lap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutEventTypeLap"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutEventType.lap",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkouteventtype/lap"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEventType/marker": {
      "abstract": [
        {
          "text": "A constant indicating a point of interest during a workout session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "marker"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEventType/marker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutEventTypeMarker"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutEventType.marker",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkouteventtype/marker"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEventType/motionPaused": {
      "abstract": [
        {
          "text": "A constant indicating that the system has automatically paused a workout session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "motionPaused"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEventType/motionPaused",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutEventTypeMotionPaused"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutEventType.motionPaused",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkouteventtype/motionpaused"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEventType/motionResumed": {
      "abstract": [
        {
          "text": "A constant indicating that the system has automatically resumed a workout session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "motionResumed"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEventType/motionResumed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutEventTypeMotionResumed"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutEventType.motionResumed",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkouteventtype/motionresumed"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEventType/pause": {
      "abstract": [
        {
          "text": "A constant indicating that the workout has paused.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pause"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEventType/pause",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutEventTypePause"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutEventType.pause",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkouteventtype/pause"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEventType/pauseOrResumeRequest": {
      "abstract": [
        {
          "text": "A constant indicating that the user has requested a pause or resume.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pauseOrResumeRequest"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEventType/pauseOrResumeRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutEventTypePauseOrResumeRequest"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutEventType.pauseOrResumeRequest",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkouteventtype/pauseorresumerequest"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEventType/resume": {
      "abstract": [
        {
          "text": "A constant indicating that the workout has resumed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resume"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEventType/resume",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutEventTypeResume"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutEventType.resume",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkouteventtype/resume"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEventType/segment": {
      "abstract": [
        {
          "text": "A constant indicating a period of time of interest during a workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "segment"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEventType/segment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutEventTypeSegment"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutEventType.segment",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkouteventtype/segment"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Events",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEventType/pause",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEventType/resume",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEventType/motionPaused",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEventType/motionResumed",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEventType/pauseOrResumeRequest",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEventType/lap",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEventType/segment"
      ],
      "title": "Events"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HKWorkoutEventTypeMarker"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutEventTypeMarker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEventType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Events",
              "generated": true,
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEventType/pause",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEventType/resume",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEventType/motionPaused",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEventType/motionResumed",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEventType/pauseOrResumeRequest",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEventType/lap",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEventType/segment"
              ],
              "title": "Events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "HKWorkoutEventTypeMarker"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEventType~1motionResumed/title",
          "value": "HKWorkoutEventTypeMotionResumed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEventType~1motionResumed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutEventTypeMotionResumed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEventType~1marker/title",
          "value": "HKWorkoutEventTypeMarker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEventType~1marker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutEventTypeMarker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEventType~1motionPaused/title",
          "value": "HKWorkoutEventTypeMotionPaused"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEventType~1motionPaused/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutEventTypeMotionPaused"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEventType~1lap/title",
          "value": "HKWorkoutEventTypeLap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEventType~1lap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutEventTypeLap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEventType/title",
          "value": "HKWorkoutEventType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEventType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEventType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEventType~1pause/title",
          "value": "HKWorkoutEventTypePause"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEventType~1pause/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutEventTypePause"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEventType~1pauseOrResumeRequest/title",
          "value": "HKWorkoutEventTypePauseOrResumeRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEventType~1pauseOrResumeRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutEventTypePauseOrResumeRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEventType~1resume/title",
          "value": "HKWorkoutEventTypeResume"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEventType~1resume/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutEventTypeResume"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEventType~1segment/title",
          "value": "HKWorkoutEventTypeSegment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEventType~1segment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutEventTypeSegment"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkworkouteventtype/marker"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkworkouteventtype/marker"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
