{
  "abstract": [
    {
      "text": "Creates a static function with the specified values.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStaticFunction"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStaticFunction/init(name:callAsFunction:attributes:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So16JSStaticFunctiona4name06callAsB010attributesABSPys4Int8VGSg_s13OpaquePointerVSgAL_A2LSiSPyALGSgSpyALGSgtXCSgs6UInt32Vtcfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "name"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SP",
        "text": "UnsafePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5CChara",
        "text": "CChar"
      },
      {
        "kind": "text",
        "text": ">!, "
      },
      {
        "kind": "externalParam",
        "text": "callAsFunction"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@JSObjectCallAsFunctionCallback",
        "text": "JSObjectCallAsFunctionCallback"
      },
      {
        "kind": "text",
        "text": "!, "
      },
      {
        "kind": "externalParam",
        "text": "attributes"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@JSPropertyAttributes",
        "text": "JSPropertyAttributes"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "JavaScriptCore"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(name:callAsFunction:attributes:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "name"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SP",
              "text": "UnsafePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5CChara",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5CChara",
              "text": "CChar"
            },
            {
              "kind": "text",
              "text": ">!, "
            },
            {
              "kind": "externalParam",
              "text": "callAsFunction"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectCallAsFunctionCallback",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@JSObjectCallAsFunctionCallback",
              "text": "JSObjectCallAsFunctionCallback"
            },
            {
              "kind": "text",
              "text": "!, "
            },
            {
              "kind": "externalParam",
              "text": "attributes"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyAttributes",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@JSPropertyAttributes",
              "text": "JSPropertyAttributes"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore": {
      "abstract": [
        {
          "text": "Evaluate JavaScript programs from within an app, and support JavaScript scripting of your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore",
      "kind": "symbol",
      "role": "collection",
      "title": "JavaScriptCore",
      "type": "topic",
      "url": "/documentation/javascriptcore"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectCallAsFunctionCallback": {
      "abstract": [
        {
          "text": "The callback type for calling an object as a function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSObjectCallAsFunctionCallback"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectCallAsFunctionCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSObjectCallAsFunctionCallback"
        }
      ],
      "role": "symbol",
      "title": "JSObjectCallAsFunctionCallback",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsobjectcallasfunctioncallback"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyAttributes": {
      "abstract": [
        {
          "text": "A set of JavaScript property attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSPropertyAttributes"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSPropertyAttributes"
        }
      ],
      "role": "symbol",
      "title": "JSPropertyAttributes",
      "type": "topic",
      "url": "/documentation/javascriptcore/jspropertyattributes"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStaticFunction": {
      "abstract": [
        {
          "text": "A statically declared function property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSStaticFunction"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStaticFunction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSStaticFunction"
        }
      ],
      "role": "symbol",
      "title": "JSStaticFunction",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsstaticfunction"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStaticFunction/init()": {
      "abstract": [
        {
          "text": "Creates a static function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStaticFunction/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsstaticfunction/init()"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStaticFunction/init(name:callAsFunction:attributes:)": {
      "abstract": [
        {
          "text": "Creates a static function with the specified values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "externalParam",
          "text": "callAsFunction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSObjectCallAsFunctionCallback",
          "text": "JSObjectCallAsFunctionCallback"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "attributes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSPropertyAttributes",
          "text": "JSPropertyAttributes"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStaticFunction/init(name:callAsFunction:attributes:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(name:callAsFunction:attributes:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsstaticfunction/init(name:callasfunction:attributes:)"
    },
    "doc://com.externally.resolved.symbol/s:SP": {
      "abstract": [
        {
          "text": "A pointer for accessing data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SP",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafePointer"
    },
    "doc://com.externally.resolved.symbol/s:s5CChara": {
      "abstract": [
        {
          "text": "The C ‘char’ type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Int8V",
          "text": "Int8"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5CChara",
      "kind": "symbol",
      "role": "symbol",
      "title": "CChar",
      "type": "topic",
      "url": "/documentation/Swift/CChar"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-Static-Function",
      "generated": true,
      "identifiers": [
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStaticFunction/init()"
      ],
      "title": "Creating a Static Function"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectCallAsFunctionCallback/title",
          "value": "JSObjectCallAsFunctionCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectCallAsFunctionCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSObjectCallAsFunctionCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectCallAsFunctionCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSObjectCallAsFunctionCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSStaticFunction/title",
          "value": "JSStaticFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSStaticFunction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSStaticFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSStaticFunction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSStaticFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyAttributes/title",
          "value": "JSPropertyAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSPropertyAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyAttributes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSPropertyAttributes"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/javascriptcore/jsstaticfunction/init(name:callasfunction:attributes:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
