{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uilayoutsupport/bottomanchor"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uilayoutsupport/bottomanchor"]}],"seeAlsoSections":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UILayoutSupport/heightAnchor","doc://com.apple.uikit/documentation/UIKit/UILayoutSupport/topAnchor"],"title":"Creating constraints using layout anchors","generated":true,"anchor":"Creating-constraints-using-layout-anchors"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomAnchor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSLayoutYAxisAnchor","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutYAxisAnchor","text":"NSLayoutYAxisAnchor"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"},{"content":[{"level":2,"anchor":"Discussion","type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use this anchor to create constraints with the guide’s bottom edge. You can only combine this anchor with other "},{"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutYAxisAnchor","isActive":true},{"type":"text","text":" anchors. For more information, see "},{"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutAnchor","isActive":true},{"type":"text","text":"."}]}],"kind":"content"}],"metadata":{"roleHeading":"Instance Property","title":"bottomAnchor","platforms":[{"beta":false,"deprecated":false,"unavailable":false,"name":"iOS","introducedAt":"9.0"},{"beta":false,"deprecated":false,"unavailable":false,"name":"iPadOS","introducedAt":"9.0"},{"beta":false,"deprecated":false,"unavailable":false,"name":"Mac Catalyst","introducedAt":"13.1"},{"beta":false,"deprecated":false,"unavailable":false,"name":"tvOS","introducedAt":"9.0"},{"beta":false,"deprecated":false,"unavailable":false,"name":"visionOS","introducedAt":"1.0"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"bottomAnchor"}],"externalID":"c:objc(pl)UILayoutSupport(py)bottomAnchor","symbolKind":"property","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bottomAnchor","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSLayoutYAxisAnchor","text":"NSLayoutYAxisAnchor"}],"modules":[{"name":"UIKit"}]},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UILayoutSupport"]]},"abstract":[{"text":"A layout anchor representing the guide’s bottom edge.","type":"text"}],"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UILayoutSupport/bottomAnchor","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UILayoutSupport":{"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UILayoutSupport","title":"UILayoutSupport","navigatorTitle":[{"text":"UILayoutSupport","kind":"identifier"}],"type":"topic","url":"/documentation/uikit/uilayoutsupport","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UILayoutSupport","kind":"identifier"}],"abstract":[{"text":"A set of methods that provide layout support and access to layout anchors.","type":"text"}],"kind":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/NSLayoutYAxisAnchor":{"url":"/documentation/uikit/nslayoutyaxisanchor","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSLayoutYAxisAnchor","kind":"identifier"}],"title":"NSLayoutYAxisAnchor","navigatorTitle":[{"text":"NSLayoutYAxisAnchor","kind":"identifier"}],"role":"symbol","abstract":[{"text":"A factory class for creating vertical layout constraint objects using a fluent API.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutYAxisAnchor","kind":"symbol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UILayoutSupport/bottomAnchor":{"role":"symbol","kind":"symbol","title":"bottomAnchor","url":"/documentation/uikit/uilayoutsupport/bottomanchor","identifier":"doc://com.apple.uikit/documentation/UIKit/UILayoutSupport/bottomAnchor","required":true,"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bottomAnchor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSLayoutYAxisAnchor","preciseIdentifier":"c:objc(cs)NSLayoutYAxisAnchor","kind":"typeIdentifier"}],"abstract":[{"text":"A layout anchor representing the guide’s bottom edge.","type":"text"}],"navigatorTitle":[{"text":"bottomAnchor","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/NSLayoutAnchor":{"kind":"symbol","role":"symbol","title":"NSLayoutAnchor","abstract":[{"text":"A factory class for creating layout constraint objects using a fluent API.","type":"text"}],"type":"topic","url":"/documentation/uikit/nslayoutanchor","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSLayoutAnchor","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutAnchor","navigatorTitle":[{"text":"NSLayoutAnchor","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UILayoutSupport/topAnchor":{"role":"symbol","kind":"symbol","title":"topAnchor","url":"/documentation/uikit/uilayoutsupport/topanchor","identifier":"doc://com.apple.uikit/documentation/UIKit/UILayoutSupport/topAnchor","required":true,"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"topAnchor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSLayoutYAxisAnchor","kind":"typeIdentifier","text":"NSLayoutYAxisAnchor"}],"abstract":[{"text":"A layout anchor representing the guide’s top edge.","type":"text"}],"navigatorTitle":[{"text":"topAnchor","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UILayoutSupport/heightAnchor":{"role":"symbol","kind":"symbol","title":"heightAnchor","url":"/documentation/uikit/uilayoutsupport/heightanchor","identifier":"doc://com.apple.uikit/documentation/UIKit/UILayoutSupport/heightAnchor","required":true,"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"heightAnchor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSLayoutDimension","preciseIdentifier":"c:objc(cs)NSLayoutDimension","kind":"typeIdentifier"}],"abstract":[{"text":"A layout anchor representing the guide’s height.","type":"text"}],"navigatorTitle":[{"text":"heightAnchor","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"beta":false,"deprecated":false,"unavailable":false,"name":"iOS","introducedAt":"9.0"},{"beta":false,"deprecated":false,"unavailable":false,"name":"iPadOS","introducedAt":"9.0"},{"beta":false,"deprecated":false,"unavailable":false,"name":"Mac Catalyst","introducedAt":"13.1"},{"name":"tvOS","beta":false,"unavailable":false,"deprecated":false,"introducedAt":"9.0"},{"name":"visionOS","beta":false,"unavailable":false,"deprecated":false,"introducedAt":"1.0"}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Property"},{"op":"replace","path":"/metadata/title","value":"bottomAnchor"},{"op":"replace","path":"/metadata/symbolKind","value":"property"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"identifier","text":"bottomAnchor"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UILayoutSupport"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"generated":true,"title":"Creating constraints using layout anchors","identifiers":["doc://com.apple.uikit/documentation/UIKit/UILayoutSupport/heightAnchor","doc://com.apple.uikit/documentation/UIKit/UILayoutSupport/topAnchor"],"anchor":"Creating-constraints-using-layout-anchors"}]},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSLayoutYAxisAnchor","preciseIdentifier":"c:objc(cs)NSLayoutYAxisAnchor","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutYAxisAnchor"},{"text":" * ","kind":"text"},{"text":"bottomAnchor","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}]}},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILayoutSupport/title","op":"replace","value":"UILayoutSupport"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILayoutSupport/fragments","op":"replace","value":[{"text":"UILayoutSupport","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILayoutSupport/navigatorTitle","op":"replace","value":[{"text":"UILayoutSupport","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutYAxisAnchor/title","op":"replace","value":"NSLayoutYAxisAnchor"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutYAxisAnchor/fragments","op":"replace","value":[{"text":"NSLayoutYAxisAnchor","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutYAxisAnchor/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NSLayoutYAxisAnchor"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILayoutSupport~1bottomAnchor/title","op":"replace","value":"bottomAnchor"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILayoutSupport~1bottomAnchor/fragments","op":"replace","value":[{"text":"bottomAnchor","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutAnchor/title","op":"replace","value":"NSLayoutAnchor"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutAnchor/fragments","op":"replace","value":[{"text":"NSLayoutAnchor","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutAnchor/navigatorTitle","op":"replace","value":[{"text":"NSLayoutAnchor","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILayoutSupport~1topAnchor/title","op":"replace","value":"topAnchor"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILayoutSupport~1topAnchor/fragments","op":"replace","value":[{"text":"topAnchor","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILayoutSupport~1heightAnchor/title","op":"replace","value":"heightAnchor"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILayoutSupport~1heightAnchor/fragments","op":"replace","value":[{"text":"heightAnchor","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}