{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText",
        "doc://com.apple.coretext/documentation/CoreText/KernVersion0SubtableHeader"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/KernVersion0SubtableHeader/init(version:length:stInfo:fsHeader:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So26KernVersion0SubtableHeaderV7version6length6stInfo02fsD0ABs6UInt16V_A2HSo0a14FormatSpecificD0Vtcfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "version"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s6UInt16V",
        "text": "UInt16"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "length"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s6UInt16V",
        "text": "UInt16"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "stInfo"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@KernSubtableInfo",
        "text": "KernSubtableInfo"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "fsHeader"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@U@KernFormatSpecificHeader",
        "text": "KernFormatSpecificHeader"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(version:length:stInfo:fsHeader:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "version"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt16V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt16V",
              "text": "UInt16"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "length"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt16V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt16V",
              "text": "UInt16"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "stInfo"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coretext/documentation/CoreText/KernSubtableInfo",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@KernSubtableInfo",
              "text": "KernSubtableInfo"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "fsHeader"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coretext/documentation/CoreText/KernFormatSpecificHeader",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@U@KernFormatSpecificHeader",
              "text": "KernFormatSpecificHeader"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/KernFormatSpecificHeader": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "KernFormatSpecificHeader"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/KernFormatSpecificHeader",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "KernFormatSpecificHeader"
        }
      ],
      "role": "symbol",
      "title": "KernFormatSpecificHeader",
      "type": "topic",
      "url": "/documentation/coretext/kernformatspecificheader"
    },
    "doc://com.apple.coretext/documentation/CoreText/KernSubtableInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "KernSubtableInfo"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/KernSubtableInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "KernSubtableInfo"
        }
      ],
      "role": "symbol",
      "title": "KernSubtableInfo",
      "type": "topic",
      "url": "/documentation/coretext/kernsubtableinfo"
    },
    "doc://com.apple.coretext/documentation/CoreText/KernVersion0SubtableHeader": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "KernVersion0SubtableHeader"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/KernVersion0SubtableHeader",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "KernVersion0SubtableHeader"
        }
      ],
      "role": "symbol",
      "title": "KernVersion0SubtableHeader",
      "type": "topic",
      "url": "/documentation/coretext/kernversion0subtableheader"
    },
    "doc://com.apple.coretext/documentation/CoreText/KernVersion0SubtableHeader/init(version:length:stInfo:fsHeader:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "version"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "length"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "stInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@KernSubtableInfo",
          "text": "KernSubtableInfo"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "fsHeader"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@KernFormatSpecificHeader",
          "text": "KernFormatSpecificHeader"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/KernVersion0SubtableHeader/init(version:length:stInfo:fsHeader:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(version:length:stInfo:fsHeader:)",
      "type": "topic",
      "url": "/documentation/coretext/kernversion0subtableheader/init(version:length:stinfo:fsheader:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt16V": {
      "abstract": [
        {
          "text": "A 16-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt16"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt16V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt16",
      "type": "topic",
      "url": "/documentation/Swift/UInt16"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1KernSubtableInfo/title",
          "value": "KernSubtableInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1KernSubtableInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "KernSubtableInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1KernSubtableInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "KernSubtableInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1KernFormatSpecificHeader/title",
          "value": "KernFormatSpecificHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1KernFormatSpecificHeader/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "KernFormatSpecificHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1KernFormatSpecificHeader/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "KernFormatSpecificHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1KernVersion0SubtableHeader/title",
          "value": "KernVersion0SubtableHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1KernVersion0SubtableHeader/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "KernVersion0SubtableHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1KernVersion0SubtableHeader/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "KernVersion0SubtableHeader"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/kernversion0subtableheader/init(version:length:stinfo:fsheader:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
