{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security",
        "doc://com.apple.security/documentation/Security/cssm_memory_funcs-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/cssm_memory_funcs-swift.struct/init(malloc_func:free_func:realloc_func:calloc_func:AllocRef:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So17cssm_memory_funcsV11malloc_func05free_E008realloc_E007calloc_E08AllocRefABSvSgSi_AHtXCSg_yAH_AHtXCSgA2H_SiAHtXCSgAHs6UInt32V_SiAHtXCSgAHtcfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "malloc_func"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CSSM_MALLOC",
        "text": "CSSM_MALLOC"
      },
      {
        "kind": "text",
        "text": "!, "
      },
      {
        "kind": "externalParam",
        "text": "free_func"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CSSM_FREE",
        "text": "CSSM_FREE"
      },
      {
        "kind": "text",
        "text": "!, "
      },
      {
        "kind": "externalParam",
        "text": "realloc_func"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CSSM_REALLOC",
        "text": "CSSM_REALLOC"
      },
      {
        "kind": "text",
        "text": "!, "
      },
      {
        "kind": "externalParam",
        "text": "calloc_func"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CSSM_CALLOC",
        "text": "CSSM_CALLOC"
      },
      {
        "kind": "text",
        "text": "!, "
      },
      {
        "kind": "externalParam",
        "text": "AllocRef"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sv",
        "text": "UnsafeMutableRawPointer"
      },
      {
        "kind": "text",
        "text": "!)"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(malloc_func:free_func:realloc_func:calloc_func:AllocRef:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "malloc_func"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/CSSM_MALLOC",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CSSM_MALLOC",
              "text": "CSSM_MALLOC"
            },
            {
              "kind": "text",
              "text": "!, "
            },
            {
              "kind": "externalParam",
              "text": "free_func"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/CSSM_FREE",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CSSM_FREE",
              "text": "CSSM_FREE"
            },
            {
              "kind": "text",
              "text": "!, "
            },
            {
              "kind": "externalParam",
              "text": "realloc_func"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/CSSM_REALLOC",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CSSM_REALLOC",
              "text": "CSSM_REALLOC"
            },
            {
              "kind": "text",
              "text": "!, "
            },
            {
              "kind": "externalParam",
              "text": "calloc_func"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/CSSM_CALLOC",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CSSM_CALLOC",
              "text": "CSSM_CALLOC"
            },
            {
              "kind": "text",
              "text": "!, "
            },
            {
              "kind": "externalParam",
              "text": "AllocRef"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sv",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sv",
              "text": "UnsafeMutableRawPointer"
            },
            {
              "kind": "text",
              "text": "!)"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/CSSM_CALLOC": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_CALLOC"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_CALLOC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_CALLOC"
        }
      ],
      "role": "symbol",
      "title": "CSSM_CALLOC",
      "type": "topic",
      "url": "/documentation/security/cssm_calloc"
    },
    "doc://com.apple.security/documentation/Security/CSSM_FREE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_FREE"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_FREE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_FREE"
        }
      ],
      "role": "symbol",
      "title": "CSSM_FREE",
      "type": "topic",
      "url": "/documentation/security/cssm_free"
    },
    "doc://com.apple.security/documentation/Security/CSSM_MALLOC": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_MALLOC"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_MALLOC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_MALLOC"
        }
      ],
      "role": "symbol",
      "title": "CSSM_MALLOC",
      "type": "topic",
      "url": "/documentation/security/cssm_malloc"
    },
    "doc://com.apple.security/documentation/Security/CSSM_REALLOC": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_REALLOC"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_REALLOC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_REALLOC"
        }
      ],
      "role": "symbol",
      "title": "CSSM_REALLOC",
      "type": "topic",
      "url": "/documentation/security/cssm_realloc"
    },
    "doc://com.apple.security/documentation/Security/cssm_memory_funcs-swift.struct": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cssm_memory_funcs"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/cssm_memory_funcs-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cssm_memory_funcs"
        }
      ],
      "role": "symbol",
      "title": "cssm_memory_funcs",
      "type": "topic",
      "url": "/documentation/security/cssm_memory_funcs-swift.struct"
    },
    "doc://com.apple.security/documentation/Security/cssm_memory_funcs-swift.struct/init(malloc_func:free_func:realloc_func:calloc_func:AllocRef:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "malloc_func"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CSSM_MALLOC",
          "text": "CSSM_MALLOC"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "free_func"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CSSM_FREE",
          "text": "CSSM_FREE"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "realloc_func"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CSSM_REALLOC",
          "text": "CSSM_REALLOC"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "calloc_func"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CSSM_CALLOC",
          "text": "CSSM_CALLOC"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "AllocRef"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/cssm_memory_funcs-swift.struct/init(malloc_func:free_func:realloc_func:calloc_func:AllocRef:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(malloc_func:free_func:realloc_func:calloc_func:AllocRef:)",
      "type": "topic",
      "url": "/documentation/security/cssm_memory_funcs-swift.struct/init(malloc_func:free_func:realloc_func:calloc_func:allocref:)"
    },
    "doc://com.externally.resolved.symbol/s:Sv": {
      "abstract": [
        {
          "text": "A raw pointer for accessing and manipulating untyped data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutableRawPointer"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sv",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutableRawPointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutableRawPointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_CALLOC/title",
          "value": "CSSM_CALLOC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_CALLOC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_CALLOC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_CALLOC/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_CALLOC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_REALLOC/title",
          "value": "CSSM_REALLOC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_REALLOC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_REALLOC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_REALLOC/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_REALLOC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_memory_funcs-swift.struct/title",
          "value": "cssm_memory_funcs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_memory_funcs-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cssm_memory_funcs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_memory_funcs-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "cssm_memory_funcs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_MALLOC/title",
          "value": "CSSM_MALLOC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_MALLOC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_MALLOC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_MALLOC/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_MALLOC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_FREE/title",
          "value": "CSSM_FREE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_FREE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_FREE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_FREE/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_FREE"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/cssm_memory_funcs-swift.struct/init(malloc_func:free_func:realloc_func:calloc_func:allocref:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
