{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["/documentation/authenticationservices/asauthorizationproviderextensionregistrationhandler/supporteddeviceencryptionalgorithms"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/authenticationservices/asauthorizationproviderextensionregistrationhandler/supporteddeviceencryptionalgorithms"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"property","externalID":"c:objc(pl)ASAuthorizationProviderExtensionRegistrationHandler(py)supportedDeviceEncryptionAlgorithms","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"supportedDeviceEncryptionAlgorithms","kind":"identifier"},{"text":": [","kind":"text"},{"text":"ASAuthorizationProviderExtensionEncryptionAlgorithm","kind":"typeIdentifier","preciseIdentifier":"c:@T@ASAuthorizationProviderExtensionEncryptionAlgorithm"},{"text":"]","kind":"text"}],"platforms":[{"beta":false,"introducedAt":"15.0","name":"macOS","deprecated":false,"unavailable":false}],"role":"symbol","title":"supportedDeviceEncryptionAlgorithms","modules":[{"name":"Authentication Services"}],"navigatorTitle":[{"text":"supportedDeviceEncryptionAlgorithms","kind":"identifier"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"supportedDeviceEncryptionAlgorithms"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ASAuthorizationProviderExtensionEncryptionAlgorithm","preciseIdentifier":"c:@T@ASAuthorizationProviderExtensionEncryptionAlgorithm","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionEncryptionAlgorithm"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["macOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionRegistrationHandler/supportedDeviceEncryptionAlgorithms"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.authenticationservices/documentation/AuthenticationServices","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionRegistrationHandler"]]},"sections":[],"references":{"doc://com.apple.authenticationservices/documentation/AuthenticationServices":{"identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices","abstract":[{"text":"Make it easy for users to log into apps and services.","type":"text"}],"role":"collection","type":"topic","title":"Authentication Services","url":"/documentation/authenticationservices","kind":"symbol"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionRegistrationHandler":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ASAuthorizationProviderExtensionRegistrationHandler","kind":"identifier"}],"abstract":[{"type":"text","text":"An interface through which a single sign-on (SSO) authentication provider extension registers users and devices for platform SSO."}],"title":"ASAuthorizationProviderExtensionRegistrationHandler","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionRegistrationHandler","navigatorTitle":[{"text":"ASAuthorizationProviderExtensionRegistrationHandler","kind":"identifier"}],"type":"topic","kind":"symbol","url":"/documentation/authenticationservices/asauthorizationproviderextensionregistrationhandler","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"url":"/documentation/technologies","role":"overview","kind":"technologies","type":"topic","title":"Technologies","abstract":[{"text":"","type":"text"}],"identifier":"doc://com.apple.documentation/documentation/technologies"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionRegistrationHandler/supportedDeviceEncryptionAlgorithms":{"navigatorTitle":[{"text":"supportedDeviceEncryptionAlgorithms","kind":"identifier"}],"type":"topic","abstract":[],"url":"/documentation/authenticationservices/asauthorizationproviderextensionregistrationhandler/supporteddeviceencryptionalgorithms","role":"symbol","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionRegistrationHandler/supportedDeviceEncryptionAlgorithms","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"supportedDeviceEncryptionAlgorithms","kind":"identifier"},{"text":": [","kind":"text"},{"text":"ASAuthorizationProviderExtensionEncryptionAlgorithm","kind":"typeIdentifier","preciseIdentifier":"c:@T@ASAuthorizationProviderExtensionEncryptionAlgorithm"},{"text":"]","kind":"text"}],"kind":"symbol","title":"supportedDeviceEncryptionAlgorithms"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionEncryptionAlgorithm":{"url":"/documentation/authenticationservices/asauthorizationproviderextensionencryptionalgorithm","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ASAuthorizationProviderExtensionEncryptionAlgorithm","kind":"identifier"}],"navigatorTitle":[{"text":"ASAuthorizationProviderExtensionEncryptionAlgorithm","kind":"identifier"}],"abstract":[],"identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionEncryptionAlgorithm","kind":"symbol","type":"topic","title":"ASAuthorizationProviderExtensionEncryptionAlgorithm"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"beta":false,"deprecated":false,"name":"macOS","unavailable":false,"introducedAt":"15.0"}],"op":"replace"},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Property"},{"path":"/metadata/title","op":"replace","value":"supportedDeviceEncryptionAlgorithms"},{"path":"/metadata/symbolKind","op":"replace","value":"property"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"identifier","text":"supportedDeviceEncryptionAlgorithms"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.authenticationservices/documentation/AuthenticationServices","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionRegistrationHandler"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"add","path":"/seeAlsoSections","value":null},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<NSNumber *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"supportedDeviceEncryptionAlgorithms","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationProviderExtensionRegistrationHandler/title","op":"replace","value":"ASAuthorizationProviderExtensionRegistrationHandler"},{"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationProviderExtensionRegistrationHandler/fragments","op":"replace","value":[{"text":"ASAuthorizationProviderExtensionRegistrationHandler","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationProviderExtensionRegistrationHandler/navigatorTitle","op":"replace","value":[{"text":"ASAuthorizationProviderExtensionRegistrationHandler","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationProviderExtensionRegistrationHandler~1supportedDeviceEncryptionAlgorithms/title","op":"replace","value":"supportedDeviceEncryptionAlgorithms"},{"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationProviderExtensionRegistrationHandler~1supportedDeviceEncryptionAlgorithms/fragments","op":"replace","value":[{"text":"supportedDeviceEncryptionAlgorithms","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationProviderExtensionEncryptionAlgorithm/title","op":"replace","value":"ASAuthorizationProviderExtensionEncryptionAlgorithm"},{"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationProviderExtensionEncryptionAlgorithm/fragments","op":"replace","value":[{"kind":"identifier","text":"ASAuthorizationProviderExtensionEncryptionAlgorithm"}]},{"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationProviderExtensionEncryptionAlgorithm/navigatorTitle","op":"replace","value":[{"text":"ASAuthorizationProviderExtensionEncryptionAlgorithm","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}