{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"supportedUserSecureEnclaveKeySigningAlgorithms"},{"kind":"text","text":": ["},{"identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionSigningAlgorithm","kind":"typeIdentifier","text":"ASAuthorizationProviderExtensionSigningAlgorithm","preciseIdentifier":"c:@T@ASAuthorizationProviderExtensionSigningAlgorithm"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/authenticationservices/asauthorizationproviderextensionregistrationhandler/supportedusersecureenclavekeysigningalgorithms"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/authenticationservices/asauthorizationproviderextensionregistrationhandler/supportedusersecureenclavekeysigningalgorithms"]}],"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.authenticationservices/documentation/AuthenticationServices","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionRegistrationHandler"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionRegistrationHandler/supportedUserSecureEnclaveKeySigningAlgorithms"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"supportedUserSecureEnclaveKeySigningAlgorithms"}],"symbolKind":"property","modules":[{"name":"Authentication Services"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"supportedUserSecureEnclaveKeySigningAlgorithms"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ASAuthorizationProviderExtensionSigningAlgorithm","preciseIdentifier":"c:@T@ASAuthorizationProviderExtensionSigningAlgorithm"},{"kind":"text","text":"]"}],"title":"supportedUserSecureEnclaveKeySigningAlgorithms","platforms":[{"unavailable":false,"deprecated":false,"beta":false,"introducedAt":"15.0","name":"macOS"}],"externalID":"c:objc(pl)ASAuthorizationProviderExtensionRegistrationHandler(py)supportedUserSecureEnclaveKeySigningAlgorithms","role":"symbol"},"references":{"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionSigningAlgorithm":{"type":"topic","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionSigningAlgorithm","navigatorTitle":[{"text":"ASAuthorizationProviderExtensionSigningAlgorithm","kind":"identifier"}],"abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ASAuthorizationProviderExtensionSigningAlgorithm","kind":"identifier"}],"url":"/documentation/authenticationservices/asauthorizationproviderextensionsigningalgorithm","kind":"symbol","role":"symbol","title":"ASAuthorizationProviderExtensionSigningAlgorithm"},"doc://com.apple.documentation/documentation/technologies":{"url":"/documentation/technologies","role":"overview","kind":"technologies","type":"topic","title":"Technologies","abstract":[{"text":"","type":"text"}],"identifier":"doc://com.apple.documentation/documentation/technologies"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionRegistrationHandler":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ASAuthorizationProviderExtensionRegistrationHandler","kind":"identifier"}],"abstract":[{"type":"text","text":"An interface through which a single sign-on (SSO) authentication provider extension registers users and devices for platform SSO."}],"title":"ASAuthorizationProviderExtensionRegistrationHandler","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionRegistrationHandler","navigatorTitle":[{"text":"ASAuthorizationProviderExtensionRegistrationHandler","kind":"identifier"}],"type":"topic","kind":"symbol","url":"/documentation/authenticationservices/asauthorizationproviderextensionregistrationhandler","role":"symbol"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices":{"identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices","abstract":[{"text":"Make it easy for users to log into apps and services.","type":"text"}],"role":"collection","type":"topic","title":"Authentication Services","url":"/documentation/authenticationservices","kind":"symbol"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionRegistrationHandler/supportedUserSecureEnclaveKeySigningAlgorithms":{"navigatorTitle":[{"text":"supportedUserSecureEnclaveKeySigningAlgorithms","kind":"identifier"}],"type":"topic","abstract":[],"url":"/documentation/authenticationservices/asauthorizationproviderextensionregistrationhandler/supportedusersecureenclavekeysigningalgorithms","role":"symbol","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionRegistrationHandler/supportedUserSecureEnclaveKeySigningAlgorithms","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"supportedUserSecureEnclaveKeySigningAlgorithms","kind":"identifier"},{"text":": [","kind":"text"},{"text":"ASAuthorizationProviderExtensionSigningAlgorithm","kind":"typeIdentifier","preciseIdentifier":"c:@T@ASAuthorizationProviderExtensionSigningAlgorithm"},{"text":"]","kind":"text"}],"kind":"symbol","title":"supportedUserSecureEnclaveKeySigningAlgorithms"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"unavailable":false,"deprecated":false,"beta":false,"introducedAt":"15.0","name":"macOS"}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Property"},{"value":"supportedUserSecureEnclaveKeySigningAlgorithms","path":"/metadata/title","op":"replace"},{"value":"property","path":"/metadata/symbolKind","op":"replace"},{"value":[{"text":"supportedUserSecureEnclaveKeySigningAlgorithms","kind":"identifier"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.authenticationservices/documentation/AuthenticationServices","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionRegistrationHandler"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":null,"path":"/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["macOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<NSNumber *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"supportedUserSecureEnclaveKeySigningAlgorithms","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"/primaryContentSections/0","op":"replace"},{"value":"ASAuthorizationProviderExtensionSigningAlgorithm","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationProviderExtensionSigningAlgorithm/title","op":"replace"},{"value":[{"kind":"identifier","text":"ASAuthorizationProviderExtensionSigningAlgorithm"}],"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationProviderExtensionSigningAlgorithm/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"ASAuthorizationProviderExtensionSigningAlgorithm"}],"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationProviderExtensionSigningAlgorithm/navigatorTitle","op":"replace"},{"value":"ASAuthorizationProviderExtensionRegistrationHandler","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationProviderExtensionRegistrationHandler/title","op":"replace"},{"value":[{"kind":"identifier","text":"ASAuthorizationProviderExtensionRegistrationHandler"}],"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationProviderExtensionRegistrationHandler/fragments","op":"replace"},{"value":[{"text":"ASAuthorizationProviderExtensionRegistrationHandler","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationProviderExtensionRegistrationHandler/navigatorTitle","op":"replace"},{"value":"supportedUserSecureEnclaveKeySigningAlgorithms","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationProviderExtensionRegistrationHandler~1supportedUserSecureEnclaveKeySigningAlgorithms/title","op":"replace"},{"value":[{"text":"supportedUserSecureEnclaveKeySigningAlgorithms","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationProviderExtensionRegistrationHandler~1supportedUserSecureEnclaveKeySigningAlgorithms/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}