{
  "abstract": [
    {
      "text": "Error codes that the exposure notification framework issues.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@ENErrorCode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "Exposure Notification"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.5",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.5",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.5",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "ENError.Code"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Code"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "This enumeration is available in iOS 12.5, and in iOS 13.5 and later.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification": {
      "abstract": [
        {
          "text": "Implement a COVID-19 exposure notification system that protects user privacy.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification",
      "kind": "symbol",
      "role": "collection",
      "title": "Exposure Notification",
      "type": "topic",
      "url": "/documentation/exposurenotification"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError": {
      "abstract": [
        {
          "text": "Errors that the exposure notification framework issues.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENError"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENError"
        }
      ],
      "role": "symbol",
      "title": "ENError",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code": {
      "abstract": [
        {
          "text": "Error codes that the exposure notification framework issues.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "ENError.Code",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/code"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/apiMisuse": {
      "abstract": [
        {
          "text": "The API use is incorrect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "apiMisuse"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/apiMisuse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENErrorCodeAPIMisuse"
        }
      ],
      "role": "symbol",
      "title": "ENError.Code.apiMisuse",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/code/apimisuse"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/badFormat": {
      "abstract": [
        {
          "text": "A file is formated incorrectly.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "badFormat"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/badFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENErrorCodeBadFormat"
        }
      ],
      "role": "symbol",
      "title": "ENError.Code.badFormat",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/code/badformat"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/badParameter": {
      "abstract": [
        {
          "text": "The parameter is missing or incorrect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "badParameter"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/badParameter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENErrorCodeBadParameter"
        }
      ],
      "role": "symbol",
      "title": "ENError.Code.badParameter",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/code/badparameter"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/bluetoothOff": {
      "abstract": [
        {
          "text": "Bluetooth is turned off.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bluetoothOff"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/bluetoothOff",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENErrorCodeBluetoothOff"
        }
      ],
      "role": "symbol",
      "title": "ENError.Code.bluetoothOff",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/code/bluetoothoff"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/dataInaccessible": {
      "abstract": [
        {
          "text": "The user must unlock the device before it can access data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataInaccessible"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/dataInaccessible",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENErrorCodeDataInaccessible"
        }
      ],
      "role": "symbol",
      "title": "ENError.Code.dataInaccessible",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/code/datainaccessible"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/code/init(rawvalue:)"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/insufficientMemory": {
      "abstract": [
        {
          "text": "The memory is insufficient to perform the operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insufficientMemory"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/insufficientMemory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENErrorCodeInsufficientMemory"
        }
      ],
      "role": "symbol",
      "title": "ENError.Code.insufficientMemory",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/code/insufficientmemory"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/insufficientStorage": {
      "abstract": [
        {
          "text": "The storage is insufficient to enable notifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insufficientStorage"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/insufficientStorage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENErrorCodeInsufficientStorage"
        }
      ],
      "role": "symbol",
      "title": "ENError.Code.insufficientStorage",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/code/insufficientstorage"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/internal": {
      "abstract": [
        {
          "text": "A bug in the internal notification framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`internal`"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/internal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENErrorCodeInternal"
        }
      ],
      "role": "symbol",
      "title": "ENError.Code.internal",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/code/internal"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/invalidated": {
      "abstract": [
        {
          "text": "A call to invalidate before the operation completes normally.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidated"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/invalidated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENErrorCodeInvalidated"
        }
      ],
      "role": "symbol",
      "title": "ENError.Code.invalidated",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/code/invalidated"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/notAuthorized": {
      "abstract": [
        {
          "text": "The user has denied access to the notification framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notAuthorized"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/notAuthorized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENErrorCodeNotAuthorized"
        }
      ],
      "role": "symbol",
      "title": "ENError.Code.notAuthorized",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/code/notauthorized"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/notEnabled": {
      "abstract": [
        {
          "text": "Notification is not enabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notEnabled"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/notEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENErrorCodeNotEnabled"
        }
      ],
      "role": "symbol",
      "title": "ENError.Code.notEnabled",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/code/notenabled"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/notEntitled": {
      "abstract": [
        {
          "text": "Process of calling is not entitled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notEntitled"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/notEntitled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENErrorCodeNotEntitled"
        }
      ],
      "role": "symbol",
      "title": "ENError.Code.notEntitled",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/code/notentitled"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/rateLimited": {
      "abstract": [
        {
          "text": "API calls are too frequent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rateLimited"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/rateLimited",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENErrorCodeRateLimited"
        }
      ],
      "role": "symbol",
      "title": "ENError.Code.rateLimited",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/code/ratelimited"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/restricted": {
      "abstract": [
        {
          "text": "Exposure notification is disabled due to system policies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "restricted"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/restricted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENErrorCodeRestricted"
        }
      ],
      "role": "symbol",
      "title": "ENError.Code.restricted",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/code/restricted"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/travelStatusNotAvailable": {
      "abstract": [
        {
          "text": "The system can’t determine whether the user is traveling.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "travelStatusNotAvailable"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/travelStatusNotAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENErrorCodeTravelStatusNotAvailable"
        }
      ],
      "role": "symbol",
      "title": "ENError.Code.travelStatusNotAvailable",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/code/travelstatusnotavailable"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/unknown": {
      "abstract": [
        {
          "text": "Failure has an unknown cause.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENErrorCodeUnknown"
        }
      ],
      "role": "symbol",
      "title": "ENError.Code.unknown",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/code/unknown"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/unsupported": {
      "abstract": [
        {
          "text": "Operation is not supported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupported"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/unsupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENErrorCodeUnsupported"
        }
      ],
      "role": "symbol",
      "title": "ENError.Code.unsupported",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/code/unsupported"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENErrorDomain": {
      "abstract": [
        {
          "text": "The domain for an error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "ENErrorDomain",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerrordomain"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENErrorHandler": {
      "abstract": [
        {
          "text": "The handler for error conditions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENErrorHandler"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENErrorHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENErrorHandler"
        }
      ],
      "role": "symbol",
      "title": "ENErrorHandler",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerrorhandler"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENErrorDomain",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENErrorHandler"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Error-Codes",
      "identifiers": [
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/apiMisuse",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/badFormat",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/badParameter",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/restricted",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/bluetoothOff",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/insufficientMemory",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/insufficientStorage",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/internal",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/invalidated",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/notAuthorized",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/notEnabled",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/notEntitled",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/rateLimited",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/unknown",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/unsupported",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/dataInaccessible",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/travelStatusNotAvailable"
      ],
      "title": "Error Codes"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.5",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.5",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.5",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ENErrorCode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Error-Codes",
              "identifiers": [
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/apiMisuse",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/badFormat",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/badParameter",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/restricted",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/bluetoothOff",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/insufficientMemory",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/insufficientStorage",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/internal",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/invalidated",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/notAuthorized",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/notEnabled",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/notEntitled",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/rateLimited",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/unknown",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/unsupported",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/dataInaccessible",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code/travelStatusNotAvailable"
              ],
              "title": "Error Codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENErrorDomain",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENErrorHandler"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ENErrorCode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1restricted/title",
          "value": "ENErrorCodeRestricted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1restricted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENErrorCodeRestricted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1insufficientMemory/title",
          "value": "ENErrorCodeInsufficientMemory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1insufficientMemory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENErrorCodeInsufficientMemory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1unknown/title",
          "value": "ENErrorCodeUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENErrorCodeUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1notAuthorized/title",
          "value": "ENErrorCodeNotAuthorized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1notAuthorized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENErrorCodeNotAuthorized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1badParameter/title",
          "value": "ENErrorCodeBadParameter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1badParameter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENErrorCodeBadParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1notEnabled/title",
          "value": "ENErrorCodeNotEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1notEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENErrorCodeNotEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1travelStatusNotAvailable/title",
          "value": "ENErrorCodeTravelStatusNotAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1travelStatusNotAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENErrorCodeTravelStatusNotAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENErrorHandler/title",
          "value": "ENErrorHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENErrorHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENErrorHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENErrorHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENErrorHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code/title",
          "value": "ENErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENErrorDomain/title",
          "value": "ENErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1unsupported/title",
          "value": "ENErrorCodeUnsupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1unsupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENErrorCodeUnsupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1badFormat/title",
          "value": "ENErrorCodeBadFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1badFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENErrorCodeBadFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1insufficientStorage/title",
          "value": "ENErrorCodeInsufficientStorage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1insufficientStorage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENErrorCodeInsufficientStorage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1dataInaccessible/title",
          "value": "ENErrorCodeDataInaccessible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1dataInaccessible/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENErrorCodeDataInaccessible"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1apiMisuse/title",
          "value": "ENErrorCodeAPIMisuse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1apiMisuse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENErrorCodeAPIMisuse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1notEntitled/title",
          "value": "ENErrorCodeNotEntitled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1notEntitled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENErrorCodeNotEntitled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1invalidated/title",
          "value": "ENErrorCodeInvalidated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1invalidated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENErrorCodeInvalidated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1bluetoothOff/title",
          "value": "ENErrorCodeBluetoothOff"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1bluetoothOff/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENErrorCodeBluetoothOff"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1rateLimited/title",
          "value": "ENErrorCodeRateLimited"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1rateLimited/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENErrorCodeRateLimited"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1internal/title",
          "value": "ENErrorCodeInternal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code~1internal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENErrorCodeInternal"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/exposurenotification/enerror/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/exposurenotification/enerror/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
