{
  "abstract": [
    {
      "text": "Operation is not supported.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/unsupported"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC11ENErrorCodeLeV11unsupportedSoAAVvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "unsupported"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SC11ENErrorCodeLeV",
        "text": "ENError"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@ENErrorCode",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "Exposure Notification"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.5",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.5",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.5",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "unsupported"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "unsupported"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SC11ENErrorCodeLeV",
              "text": "ENError"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@ENErrorCode",
              "text": "Code"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification": {
      "abstract": [
        {
          "text": "Implement a COVID-19 exposure notification system that protects user privacy.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification",
      "kind": "symbol",
      "role": "collection",
      "title": "Exposure Notification",
      "type": "topic",
      "url": "/documentation/exposurenotification"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError": {
      "abstract": [
        {
          "text": "Errors that the exposure notification framework issues.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENError"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENError"
        }
      ],
      "role": "symbol",
      "title": "ENError",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code": {
      "abstract": [
        {
          "text": "Error codes that the exposure notification framework issues.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "ENError.Code",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/code"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/apiMisuse": {
      "abstract": [
        {
          "text": "The API use is incorrect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "apiMisuse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11ENErrorCodeLeV",
          "text": "ENError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ENErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/apiMisuse",
      "kind": "symbol",
      "role": "symbol",
      "title": "apiMisuse",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/apimisuse"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/badFormat": {
      "abstract": [
        {
          "text": "A file is formated incorrectly.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "badFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11ENErrorCodeLeV",
          "text": "ENError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ENErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/badFormat",
      "kind": "symbol",
      "role": "symbol",
      "title": "badFormat",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/badformat"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/badParameter": {
      "abstract": [
        {
          "text": "The parameter is missing or incorrect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "badParameter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11ENErrorCodeLeV",
          "text": "ENError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ENErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/badParameter",
      "kind": "symbol",
      "role": "symbol",
      "title": "badParameter",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/badparameter"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/bluetoothOff": {
      "abstract": [
        {
          "text": "Bluetooth is turned off.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bluetoothOff"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11ENErrorCodeLeV",
          "text": "ENError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ENErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/bluetoothOff",
      "kind": "symbol",
      "role": "symbol",
      "title": "bluetoothOff",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/bluetoothoff"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/dataInaccessible": {
      "abstract": [
        {
          "text": "The user must unlock the device before it can access data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataInaccessible"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11ENErrorCodeLeV",
          "text": "ENError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ENErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/dataInaccessible",
      "kind": "symbol",
      "role": "symbol",
      "title": "dataInaccessible",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/datainaccessible"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/insufficientMemory": {
      "abstract": [
        {
          "text": "The memory is insufficient to perform the operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insufficientMemory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11ENErrorCodeLeV",
          "text": "ENError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ENErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/insufficientMemory",
      "kind": "symbol",
      "role": "symbol",
      "title": "insufficientMemory",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/insufficientmemory"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/insufficientStorage": {
      "abstract": [
        {
          "text": "The storage is insufficient to enable notifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insufficientStorage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11ENErrorCodeLeV",
          "text": "ENError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ENErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/insufficientStorage",
      "kind": "symbol",
      "role": "symbol",
      "title": "insufficientStorage",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/insufficientstorage"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/internal": {
      "abstract": [
        {
          "text": "A bug in the internal notification framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`internal`"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11ENErrorCodeLeV",
          "text": "ENError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ENErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/internal",
      "kind": "symbol",
      "role": "symbol",
      "title": "internal",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/internal"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/invalidated": {
      "abstract": [
        {
          "text": "A call to invalidate before the operation completes normally.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11ENErrorCodeLeV",
          "text": "ENError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ENErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/invalidated",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidated",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/invalidated"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/notAuthorized": {
      "abstract": [
        {
          "text": "The user has denied access to the notification framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notAuthorized"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11ENErrorCodeLeV",
          "text": "ENError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ENErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/notAuthorized",
      "kind": "symbol",
      "role": "symbol",
      "title": "notAuthorized",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/notauthorized"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/notEnabled": {
      "abstract": [
        {
          "text": "Notification is not enabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11ENErrorCodeLeV",
          "text": "ENError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ENErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/notEnabled",
      "kind": "symbol",
      "role": "symbol",
      "title": "notEnabled",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/notenabled"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/notEntitled": {
      "abstract": [
        {
          "text": "Process of calling is not entitled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notEntitled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11ENErrorCodeLeV",
          "text": "ENError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ENErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/notEntitled",
      "kind": "symbol",
      "role": "symbol",
      "title": "notEntitled",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/notentitled"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/rateLimited": {
      "abstract": [
        {
          "text": "API calls are too frequent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rateLimited"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11ENErrorCodeLeV",
          "text": "ENError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ENErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/rateLimited",
      "kind": "symbol",
      "role": "symbol",
      "title": "rateLimited",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/ratelimited"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/restricted": {
      "abstract": [
        {
          "text": "Exposure notification is disabled due to system policies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "restricted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11ENErrorCodeLeV",
          "text": "ENError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ENErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/restricted",
      "kind": "symbol",
      "role": "symbol",
      "title": "restricted",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/restricted"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/unknown": {
      "abstract": [
        {
          "text": "Failure has an unknown cause.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11ENErrorCodeLeV",
          "text": "ENError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ENErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/unknown",
      "kind": "symbol",
      "role": "symbol",
      "title": "unknown",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/unknown"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/unsupported": {
      "abstract": [
        {
          "text": "Operation is not supported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11ENErrorCodeLeV",
          "text": "ENError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ENErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/unsupported",
      "kind": "symbol",
      "role": "symbol",
      "title": "unsupported",
      "type": "topic",
      "url": "/documentation/exposurenotification/enerror/unsupported"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/apiMisuse",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/badFormat",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/badParameter",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/bluetoothOff",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/insufficientMemory",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/insufficientStorage",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/internal",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/invalidated",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/notAuthorized",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/notEnabled",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/notEntitled",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/rateLimited",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/restricted",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/unknown",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENError/dataInaccessible"
      ],
      "title": "Error Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code/title",
          "value": "ENErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENErrorCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/exposurenotification/enerror/unsupported"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
