{"seeAlsoSections":[{"anchor":"Constants","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth/sixtyfourBitRGB","doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth/twentyfourBitRGB"],"title":"Constants"}],"sections":[],"metadata":{"navigatorTitle":[{"text":"NSWindowDepthOnehundredtwentyeightBitRGB","kind":"identifier"}],"externalID":"c:@E@NSWindowDepth@NSWindowDepthOnehundredtwentyeightBitRGB","roleHeading":"Case","platforms":[{"unavailable":false,"introducedAt":"10.6","deprecated":false,"name":"macOS","beta":false}],"modules":[{"name":"AppKit"}],"symbolKind":"case","title":"NSWindow.Depth.onehundredtwentyeightBitRGB","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onehundredtwentyeightBitRGB","kind":"identifier"}],"role":"symbol"},"abstract":[{"text":"One hundred and twenty eight bit RGB depth limit.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onehundredtwentyeightBitRGB","kind":"identifier"}],"platforms":["macOS"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSWindow","doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth"]]},"variants":[{"paths":["/documentation/appkit/nswindow/depth/onehundredtwentyeightbitrgb"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nswindow/depth/onehundredtwentyeightbitrgb"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth/onehundredtwentyeightBitRGB","interfaceLanguage":"swift"},"references":{"doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth/sixtyfourBitRGB":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sixtyfourBitRGB","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth/sixtyfourBitRGB","navigatorTitle":[{"text":"NSWindowDepthSixtyfourBitRGB","kind":"identifier"}],"title":"NSWindow.Depth.sixtyfourBitRGB","url":"/documentation/appkit/nswindow/depth/sixtyfourbitrgb","abstract":[{"text":"Sixty four bit RGB depth limit.","type":"text"}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth","abstract":[{"text":"A type that represents the depth, or amount of memory, for a single pixel in a window or screen.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"Depth","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Depth","kind":"identifier"}],"title":"NSWindow.Depth","kind":"symbol","url":"/documentation/appkit/nswindow/depth","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth/onehundredtwentyeightBitRGB":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"onehundredtwentyeightBitRGB","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth/onehundredtwentyeightBitRGB","navigatorTitle":[{"text":"NSWindowDepthOnehundredtwentyeightBitRGB","kind":"identifier"}],"title":"NSWindow.Depth.onehundredtwentyeightBitRGB","url":"/documentation/appkit/nswindow/depth/onehundredtwentyeightbitrgb","abstract":[{"text":"One hundred and twenty eight bit RGB depth limit.","type":"text"}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSWindow"}],"url":"/documentation/appkit/nswindow","title":"NSWindow","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSWindow"}],"abstract":[{"type":"text","text":"A window that an app displays on the screen."}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth/twentyfourBitRGB":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"twentyfourBitRGB","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth/twentyfourBitRGB","navigatorTitle":[{"text":"NSWindowDepthTwentyfourBitRGB","kind":"identifier"}],"title":"NSWindow.Depth.twentyfourBitRGB","url":"/documentation/appkit/nswindow/depth/twentyfourbitrgb","abstract":[{"type":"text","text":"Twenty four bit RGB depth limit."}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"deprecated":false,"beta":false,"introducedAt":"10.6","unavailable":false,"name":"macOS"}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"/metadata/title","value":"NSWindowDepthOnehundredtwentyeightBitRGB","op":"replace"},{"path":"/metadata/symbolKind","value":"case","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"NSWindowDepthOnehundredtwentyeightBitRGB","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"generated":true,"title":"Constants","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth/sixtyfourBitRGB","doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth/twentyfourBitRGB"],"anchor":"Constants"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"text":"NSWindowDepthOnehundredtwentyeightBitRGB","kind":"identifier"}],"languages":["occ"],"platforms":["Mac Catalyst","macOS"]}],"kind":"declarations"},"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1Depth~1sixtyfourBitRGB/title","value":"NSWindowDepthSixtyfourBitRGB","op":"replace"},{"value":[{"kind":"identifier","text":"NSWindowDepthSixtyfourBitRGB"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1Depth~1sixtyfourBitRGB/fragments","op":"replace"},{"value":"NSWindowDepth","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1Depth/title","op":"replace"},{"value":[{"text":"NSWindowDepth","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1Depth/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"NSWindowDepth"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1Depth/navigatorTitle","op":"replace"},{"value":"NSWindowDepthOnehundredtwentyeightBitRGB","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1Depth~1onehundredtwentyeightBitRGB/title","op":"replace"},{"value":[{"kind":"identifier","text":"NSWindowDepthOnehundredtwentyeightBitRGB"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1Depth~1onehundredtwentyeightBitRGB/fragments","op":"replace"},{"value":"NSWindow","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/title","op":"replace"},{"value":[{"kind":"identifier","text":"NSWindow"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"NSWindow"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/navigatorTitle","op":"replace"},{"value":"NSWindowDepthTwentyfourBitRGB","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1Depth~1twentyfourBitRGB/title","op":"replace"},{"value":[{"text":"NSWindowDepthTwentyfourBitRGB","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1Depth~1twentyfourBitRGB/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}