{"metadata":{"role":"symbol","platforms":[{"beta":false,"deprecated":false,"unavailable":false,"name":"macOS","introducedAt":"10.8"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"instantiateWithOwner:topLevelObjects:"}],"externalID":"c:objc(cs)NSNib(im)instantiateWithOwner:topLevelObjects:","modules":[{"name":"AppKit"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"instantiate","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withOwner"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"topLevelObjects"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SA","kind":"typeIdentifier","text":"AutoreleasingUnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSArray","text":"NSArray"},{"kind":"text","text":"?>?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"instantiate(withOwner:topLevelObjects:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"instantiate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withOwner","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"owner"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"topLevelObjects"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:SA","preciseIdentifier":"s:SA","text":"AutoreleasingUnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSArray","preciseIdentifier":"c:objc(cs)NSArray","text":"NSArray"},{"kind":"text","text":"?>?) -> "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:Sb","preciseIdentifier":"s:Sb","text":"Bool"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The object to set as the Nib’s owner (File’s Owner)."}],"type":"paragraph"}],"name":"owner"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"On return, an array containing the top-level objects of the nib."}]}],"name":"topLevelObjects"}]},{"kind":"content","content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"inlineContent":[{"type":"text","text":""},{"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/true","isActive":true},{"type":"text","text":" if the nib is instantiated; otherwise "},{"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/false","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}]},{"kind":"content","content":[{"level":2,"anchor":"Discussion","text":"Discussion","type":"heading"},{"inlineContent":[{"text":"Unlike legacy methods, the objects adhere to standard Cocoa memory management rules; it is necessary to keep a strong reference to the objects or the array to prevent the nib contents from being deallocated.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"Outlets to top level objects should be strong references to demonstrate ownership and prevent deallocation.","type":"text"}],"type":"paragraph"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSNib"]]},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSNib/instantiate(withOwner:topLevelObjects:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsnib/instantiate(withowner:toplevelobjects:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsnib/instantiate(withowner:toplevelobjects:)"]}],"abstract":[{"text":"Instantiates objects in the nib file with the specified owner.","type":"text"}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSNib/instantiateNibWithOwner:topLevelObjects:":{"fragments":[{"text":"- ","kind":"text"},{"text":"instantiateNibWithOwner:topLevelObjects:","kind":"identifier"}],"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSNib/instantiateNibWithOwner:topLevelObjects:","url":"/documentation/appkit/nsnib/instantiatenibwithowner:toplevelobjects:","title":"instantiateNibWithOwner:topLevelObjects:","kind":"symbol","navigatorTitle":[{"text":"instantiateNibWithOwner:topLevelObjects:","kind":"identifier"}],"type":"topic","abstract":[{"text":"Unarchives and instantiates the in-memory contents of the receiver’s nib file, creating a distinct object tree and set of top level objects.","type":"text"}],"deprecated":true},"doc://com.externally.resolved.symbol/s:SA":{"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SA","url":"/documentation/Swift/AutoreleasingUnsafeMutablePointer","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutoreleasingUnsafeMutablePointer","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Pointee","kind":"genericParameter"},{"text":">","kind":"text"}],"type":"topic","title":"AutoreleasingUnsafeMutablePointer","role":"symbol","abstract":[{"type":"text","text":"A mutable pointer addressing an Objective-C reference that doesn’t own its target."}]},"doc://com.apple.appkit/documentation/AppKit/NSNib/instantiateNibWithExternalNameTable:":{"fragments":[{"text":"- ","kind":"text"},{"text":"instantiateNibWithExternalNameTable:","kind":"identifier"}],"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSNib/instantiateNibWithExternalNameTable:","url":"/documentation/appkit/nsnib/instantiatenibwithexternalnametable:","title":"instantiateNibWithExternalNameTable:","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"instantiateNibWithExternalNameTable:"}],"type":"topic","abstract":[{"text":"Unarchives and instantiates the in-memory contents of the receiver’s nib file, creating a distinct object tree and top level objects.","type":"text"}],"deprecated":true},"doc://com.apple.documentation/documentation/swift/true":{"title":"true","type":"topic","identifier":"doc://com.apple.documentation/documentation/swift/true","role":"symbol","abstract":[{"type":"text","text":"A true value."}],"kind":"symbol","url":"/documentation/swift/true"},"doc://com.apple.appkit/documentation/AppKit/NSNib":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NSNib"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"An object wrapper, or container, for an Interface Builder nib file."}],"url":"/documentation/appkit/nsnib","navigatorTitle":[{"text":"NSNib","kind":"identifier"}],"title":"NSNib","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSNib"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.externally.resolved.symbol/c:objc(cs)NSArray":{"title":"NSArray","url":"/documentation/foundation/nsarray","fragments":[{"text":"class ","kind":"text"},{"text":"NSArray","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSArray","role":"symbol","type":"topic","abstract":[{"type":"text","text":"An object representing a static ordered collection, for use instead of an  constant in cases that require reference semantics."}]},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSNib/instantiate(withOwner:topLevelObjects:)":{"url":"/documentation/appkit/nsnib/instantiate(withowner:toplevelobjects:)","kind":"symbol","navigatorTitle":[{"text":"instantiateWithOwner:topLevelObjects:","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSNib/instantiate(withOwner:topLevelObjects:)","title":"instantiate(withOwner:topLevelObjects:)","abstract":[{"text":"Instantiates objects in the nib file with the specified owner.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"instantiate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withOwner","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?, ","kind":"text"},{"text":"topLevelObjects","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SA","text":"AutoreleasingUnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSArray","text":"NSArray","kind":"typeIdentifier"},{"text":"?>?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol"},"doc://com.externally.resolved.symbol/s:Sb":{"title":"Bool","type":"topic","identifier":"doc://com.externally.resolved.symbol/s:Sb","role":"symbol","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Bool","kind":"identifier"}],"abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"kind":"symbol","url":"/documentation/Swift/Bool"},"doc://com.apple.documentation/documentation/swift/false":{"title":"false","type":"topic","identifier":"doc://com.apple.documentation/documentation/swift/false","role":"symbol","abstract":[{"text":"A false value.","type":"text"}],"kind":"symbol","url":"/documentation/swift/false"},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"title":"BOOL","kind":"symbol","abstract":[{"type":"text","text":"Type to represent a Boolean value."}],"type":"topic","role":"symbol","url":"/documentation/objectivec/bool","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"beta":false,"introducedAt":"10.8","name":"macOS","deprecated":false,"unavailable":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Method","path":"/metadata/roleHeading"},{"value":"instantiateWithOwner:topLevelObjects:","path":"/metadata/title","op":"replace"},{"value":"method","path":"/metadata/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"instantiateWithOwner:topLevelObjects:","kind":"identifier"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSNib"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"anchor":"Instantiating-a-Nib","title":"Instantiating a Nib","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSNib/instantiateNibWithOwner:topLevelObjects:","doc://com.apple.appkit/documentation/AppKit/NSNib/instantiateNibWithExternalNameTable:"],"generated":true}],"path":"/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"instantiateWithOwner:"},{"kind":"text","text":"("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"internalParam","text":"owner"},{"kind":"text","text":" "},{"kind":"identifier","text":"topLevelObjects:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSArray","preciseIdentifier":"c:objc(cs)NSArray","text":"NSArray"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"topLevelObjects"},{"kind":"text","text":";"}],"platforms":["Mac Catalyst","macOS"]}],"kind":"declarations"},"path":"/primaryContentSections/0","op":"replace"},{"op":"replace","path":"/primaryContentSections/1","value":{"kind":"parameters","parameters":[{"name":"owner","content":[{"type":"paragraph","inlineContent":[{"text":"The object to set as the Nib’s owner (File’s Owner).","type":"text"}]}]},{"name":"topLevelObjects","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"On return, an array containing the top-level objects of the nib."}]}]}]}},{"value":{"kind":"content","content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"inlineContent":[{"type":"text","text":""},{"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/true","isActive":true},{"type":"text","text":" if the nib is instantiated; otherwise "},{"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/false","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}]},"path":"/primaryContentSections/2","op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSNib/title","value":"NSNib"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSNib/fragments","value":[{"text":"NSNib","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSNib/navigatorTitle","value":[{"text":"NSNib","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSArray/abstract","value":[{"text":"A static ordered collection of objects.","type":"text"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSNib~1instantiate(withOwner:topLevelObjects:)/title","value":"instantiateWithOwner:topLevelObjects:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSNib~1instantiate(withOwner:topLevelObjects:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"instantiateWithOwner:topLevelObjects:"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}