{
  "abstract": [
    {
      "text": "Position the element in the center of its containing element.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Please use SwiftUI or UIKit",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.tvmlkit/documentation/TVMLKit",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/center"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@TVElementPosition@TVElementPositionCenter",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "center"
      }
    ],
    "modules": [
      {
        "name": "TVMLKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "TVElementPositionCenter"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "9.0",
        "message": "Please use SwiftUI or UIKit",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "TVElementPosition.center"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "center"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit": {
      "abstract": [
        {
          "text": "Create client-server apps by incorporating JavaScript and TVML files in your binary app.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit",
      "kind": "symbol",
      "role": "collection",
      "title": "TVMLKit",
      "type": "topic",
      "url": "/documentation/tvmlkit"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition": {
      "abstract": [
        {
          "text": "Location of an element relative to the screen or its containing element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVElementPosition"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVElementPosition"
        }
      ],
      "role": "symbol",
      "title": "TVElementPosition",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvelementposition"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/bottom": {
      "abstract": [
        {
          "text": "Position the element at the bottom of the containing element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottom"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/bottom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVElementPositionBottom"
        }
      ],
      "role": "symbol",
      "title": "TVElementPosition.bottom",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvelementposition/bottom"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/bottomLeft": {
      "abstract": [
        {
          "text": "Position the element in the bottom-left of the containing element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottomLeft"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/bottomLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVElementPositionBottomLeft"
        }
      ],
      "role": "symbol",
      "title": "TVElementPosition.bottomLeft",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvelementposition/bottomleft"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/bottomRight": {
      "abstract": [
        {
          "text": "Position the element in the bottom-right of the containing element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottomRight"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/bottomRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVElementPositionBottomRight"
        }
      ],
      "role": "symbol",
      "title": "TVElementPosition.bottomRight",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvelementposition/bottomright"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/center": {
      "abstract": [
        {
          "text": "Position the element in the center of its containing element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "center"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/center",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVElementPositionCenter"
        }
      ],
      "role": "symbol",
      "title": "TVElementPosition.center",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvelementposition/center"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/footer": {
      "abstract": [
        {
          "text": "Position the element in the footer area of the containing element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "footer"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/footer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVElementPositionFooter"
        }
      ],
      "role": "symbol",
      "title": "TVElementPosition.footer",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvelementposition/footer"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/header": {
      "abstract": [
        {
          "text": "Position the element in the header area of the containing element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "header"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/header",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVElementPositionHeader"
        }
      ],
      "role": "symbol",
      "title": "TVElementPosition.header",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvelementposition/header"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/leading": {
      "abstract": [
        {
          "text": "Position the element in the leading edge of the containing element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leading"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/leading",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVElementPositionLeading"
        }
      ],
      "role": "symbol",
      "title": "TVElementPosition.leading",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvelementposition/leading"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/left": {
      "abstract": [
        {
          "text": "Position the element along the left side of the containing element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "left"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/left",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVElementPositionLeft"
        }
      ],
      "role": "symbol",
      "title": "TVElementPosition.left",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvelementposition/left"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/right": {
      "abstract": [
        {
          "text": "Position the element along the right side of the containing element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "right"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/right",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVElementPositionRight"
        }
      ],
      "role": "symbol",
      "title": "TVElementPosition.right",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvelementposition/right"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/top": {
      "abstract": [
        {
          "text": "Position the element at the top of the containing element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "top"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/top",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVElementPositionTop"
        }
      ],
      "role": "symbol",
      "title": "TVElementPosition.top",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvelementposition/top"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/topLeading": {
      "abstract": [
        {
          "text": "Position the element in the top-leading edge of the containing element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "topLeading"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/topLeading",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVElementPositionTopLeading"
        }
      ],
      "role": "symbol",
      "title": "TVElementPosition.topLeading",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvelementposition/topleading"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/topLeft": {
      "abstract": [
        {
          "text": "Position the element in the top-left of the containing element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "topLeft"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/topLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVElementPositionTopLeft"
        }
      ],
      "role": "symbol",
      "title": "TVElementPosition.topLeft",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvelementposition/topleft"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/topRight": {
      "abstract": [
        {
          "text": "Position the element in the top-right of the containing element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "topRight"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/topRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVElementPositionTopRight"
        }
      ],
      "role": "symbol",
      "title": "TVElementPosition.topRight",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvelementposition/topright"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/topTrailing": {
      "abstract": [
        {
          "text": "Position the element in the top-trailing edge of the containing element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "topTrailing"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/topTrailing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVElementPositionTopTrailing"
        }
      ],
      "role": "symbol",
      "title": "TVElementPosition.topTrailing",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvelementposition/toptrailing"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/trailing": {
      "abstract": [
        {
          "text": "Position the element in the trailing edge of the containing element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trailing"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/trailing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVElementPositionTrailing"
        }
      ],
      "role": "symbol",
      "title": "TVElementPosition.trailing",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvelementposition/trailing"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/undefined": {
      "abstract": [
        {
          "text": "The position has not been defined.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "undefined"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/undefined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVElementPositionUndefined"
        }
      ],
      "role": "symbol",
      "title": "TVElementPosition.undefined",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvelementposition/undefined"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/undefined",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/top",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/bottom",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/left",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/right",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/topLeft",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/topRight",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/bottomLeft",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/bottomRight",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/header",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/footer",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/leading",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/trailing",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/topLeading",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/topTrailing"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "TVElementPositionCenter"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementPositionCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.tvmlkit/documentation/TVMLKit",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/undefined",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/top",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/bottom",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/left",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/right",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/topLeft",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/topRight",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/bottomLeft",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/bottomRight",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/header",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/footer",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/leading",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/trailing",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/topLeading",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/topTrailing"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "TVElementPositionCenter"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Please use SwiftUI or UIKit",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1header/title",
          "value": "TVElementPositionHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1header/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementPositionHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1topLeft/title",
          "value": "TVElementPositionTopLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1topLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementPositionTopLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1topTrailing/title",
          "value": "TVElementPositionTopTrailing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1topTrailing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementPositionTopTrailing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1leading/title",
          "value": "TVElementPositionLeading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1leading/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementPositionLeading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1bottom/title",
          "value": "TVElementPositionBottom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1bottom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementPositionBottom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1undefined/title",
          "value": "TVElementPositionUndefined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1undefined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementPositionUndefined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1bottomLeft/title",
          "value": "TVElementPositionBottomLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1bottomLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementPositionBottomLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1top/title",
          "value": "TVElementPositionTop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1top/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementPositionTop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1center/title",
          "value": "TVElementPositionCenter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1center/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementPositionCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition/title",
          "value": "TVElementPosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1topLeading/title",
          "value": "TVElementPositionTopLeading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1topLeading/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementPositionTopLeading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1right/title",
          "value": "TVElementPositionRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1right/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementPositionRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1topRight/title",
          "value": "TVElementPositionTopRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1topRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementPositionTopRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1left/title",
          "value": "TVElementPositionLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1left/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementPositionLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1footer/title",
          "value": "TVElementPositionFooter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1footer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementPositionFooter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1bottomRight/title",
          "value": "TVElementPositionBottomRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1bottomRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementPositionBottomRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1trailing/title",
          "value": "TVElementPositionTrailing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1trailing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementPositionTrailing"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/tvmlkit/tvelementposition/center"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/tvmlkit/tvelementposition/center"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
