{"metadata":{"title":"type","required":true,"role":"symbol","externalID":"c:objc(pl)MDLMeshBuffer(py)type","modules":[{"name":"Model I/O"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@MDLMeshBufferType","text":"MDLMeshBufferType","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"type","kind":"identifier"}],"platforms":[{"name":"iOS","beta":false,"unavailable":false,"deprecated":false,"introducedAt":"9.0"},{"name":"iPadOS","beta":false,"unavailable":false,"deprecated":false,"introducedAt":"9.0"},{"name":"Mac Catalyst","beta":false,"unavailable":false,"deprecated":false,"introducedAt":"13.1"},{"unavailable":false,"introducedAt":"10.11","deprecated":false,"name":"macOS","beta":false},{"unavailable":false,"introducedAt":"9.0","deprecated":false,"name":"tvOS","beta":false},{"unavailable":false,"introducedAt":"1.0","deprecated":false,"name":"visionOS","beta":false}],"roleHeading":"Instance Property"},"seeAlsoSections":[{"identifiers":["doc://com.apple.modelio/documentation/ModelIO/MDLMeshBuffer/allocator","doc://com.apple.modelio/documentation/ModelIO/MDLMeshBuffer/zone"],"anchor":"Inspecting-a-Buffer","title":"Inspecting a Buffer","generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/modelio/mdlmeshbuffer/type"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/modelio/mdlmeshbuffer/type"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.modelio/documentation/ModelIO","doc://com.apple.modelio/documentation/ModelIO/MDLMeshBuffer"]]},"sections":[],"kind":"symbol","abstract":[{"text":"The type of data contained in a buffer.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MDLMeshBufferType","preciseIdentifier":"c:@E@MDLMeshBufferType","kind":"typeIdentifier","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferType"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"]}]},{"content":[{"text":"Discussion","level":2,"anchor":"Discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"A buffer can contain per-vertex data for one or more vertex attributes of a ","type":"text"},{"identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMesh","type":"reference","isActive":true},{"text":" object (","type":"text"},{"identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferType/vertex","type":"reference","isActive":true},{"text":"), or index data for a ","type":"text"},{"identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLSubmesh","type":"reference","isActive":true},{"text":" object (","type":"text"},{"identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferType/index","type":"reference","isActive":true},{"text":").","type":"text"}]}],"kind":"content"}],"identifier":{"url":"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBuffer/type","interfaceLanguage":"swift"},"references":{"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBuffer/allocator":{"url":"/documentation/modelio/mdlmeshbuffer/allocator","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBuffer/allocator","role":"symbol","abstract":[{"text":"The allocator object that created the buffer.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allocator","kind":"identifier"},{"text":": any ","kind":"text"},{"text":"MDLMeshBufferAllocator","preciseIdentifier":"c:objc(pl)MDLMeshBufferAllocator","kind":"typeIdentifier"}],"title":"allocator","required":true,"type":"topic","kind":"symbol","navigatorTitle":[{"text":"allocator","kind":"identifier"}]},"doc://com.apple.modelio/documentation/ModelIO":{"identifier":"doc://com.apple.modelio/documentation/ModelIO","title":"Model I/O","role":"collection","kind":"symbol","abstract":[{"text":"Import, export, and manipulate 3D models using a common infrastructure that integrates MetalKit, GLKit, and SceneKit.","type":"text"}],"type":"topic","url":"/documentation/modelio"},"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferType/index":{"type":"topic","navigatorTitle":[{"text":"MDLMeshBufferTypeIndex","kind":"identifier"}],"title":"MDLMeshBufferType.index","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"index","kind":"identifier"}],"identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferType/index","url":"/documentation/modelio/mdlmeshbuffertype/index","kind":"symbol","role":"symbol","abstract":[{"text":"The buffer contains index data for a ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLSubmesh"},{"type":"text","text":" object."}]},"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferType":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MDLMeshBufferType"}],"url":"/documentation/modelio/mdlmeshbuffertype","abstract":[{"type":"text","text":"Options for the content of a mesh buffer, used by the "},{"type":"reference","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBuffer/type","isActive":true},{"type":"text","text":" property and by "},{"type":"reference","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferAllocator","isActive":true},{"type":"text","text":" methods for creating buffers."}],"title":"MDLMeshBufferType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MDLMeshBufferType"}],"role":"symbol","kind":"symbol","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferType"},"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBuffer/zone":{"url":"/documentation/modelio/mdlmeshbuffer/zone","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBuffer/zone","role":"symbol","abstract":[{"type":"text","text":"The memory pool from which the buffer was created."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"zone","kind":"identifier"},{"text":": any ","kind":"text"},{"text":"MDLMeshBufferZone","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MDLMeshBufferZone"}],"title":"zone","required":true,"type":"topic","kind":"symbol","navigatorTitle":[{"text":"zone","kind":"identifier"}]},"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferType/vertex":{"url":"/documentation/modelio/mdlmeshbuffertype/vertex","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferType/vertex","navigatorTitle":[{"text":"MDLMeshBufferTypeVertex","kind":"identifier"}],"type":"topic","abstract":[{"text":"The buffer contains per-vertex data for one or more vertex attributes of a ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMesh"},{"type":"text","text":" object."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"vertex","kind":"identifier"}],"role":"symbol","title":"MDLMeshBufferType.vertex","kind":"symbol"},"doc://com.apple.modelio/documentation/ModelIO/MDLMesh":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MDLMesh","kind":"identifier"}],"type":"topic","abstract":[{"text":"A container for vertex buffer data to be used in rendering a 3D object.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"MDLMesh","kind":"identifier"}],"title":"MDLMesh","url":"/documentation/modelio/mdlmesh","kind":"symbol","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMesh"},"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferAllocator":{"abstract":[{"text":"The general interface for managing allocation of data buffers to be used in loading, processing, and rendering meshes.","type":"text"}],"navigatorTitle":[{"text":"MDLMeshBufferAllocator","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferAllocator","url":"/documentation/modelio/mdlmeshbufferallocator","title":"MDLMeshBufferAllocator","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MDLMeshBufferAllocator","kind":"identifier"}],"type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","url":"/documentation/technologies","kind":"technologies","role":"overview","abstract":[{"text":"","type":"text"}],"type":"topic"},"doc://com.apple.modelio/documentation/ModelIO/MDLSubmesh":{"abstract":[{"text":"A container for index buffer data and material information to be used in rendering all or part of a 3D object.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MDLSubmesh"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MDLSubmesh"}],"kind":"symbol","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLSubmesh","title":"MDLSubmesh","url":"/documentation/modelio/mdlsubmesh"},"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBuffer":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MDLMeshBuffer","kind":"identifier"}],"kind":"symbol","title":"MDLMeshBuffer","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBuffer","url":"/documentation/modelio/mdlmeshbuffer","abstract":[{"type":"text","text":"The general interface for managing storage of vertex and index data used in loading, processing, and rendering meshes."}],"role":"symbol","navigatorTitle":[{"text":"MDLMeshBuffer","kind":"identifier"}],"type":"topic"},"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBuffer/type":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MDLMeshBufferType","preciseIdentifier":"c:@E@MDLMeshBufferType"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"type"}],"type":"topic","url":"/documentation/modelio/mdlmeshbuffer/type","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBuffer/type","title":"type","abstract":[{"type":"text","text":"The type of data contained in a buffer."}],"required":true}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"introducedAt":"9.0","unavailable":false,"name":"iOS","beta":false,"deprecated":false},{"introducedAt":"9.0","unavailable":false,"name":"iPadOS","beta":false,"deprecated":false},{"introducedAt":"13.1","unavailable":false,"name":"Mac Catalyst","beta":false,"deprecated":false},{"introducedAt":"10.11","unavailable":false,"name":"macOS","beta":false,"deprecated":false},{"introducedAt":"9.0","unavailable":false,"name":"tvOS","beta":false,"deprecated":false},{"introducedAt":"1.0","unavailable":false,"name":"visionOS","beta":false,"deprecated":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Property","op":"replace"},{"value":"type","path":"/metadata/title","op":"replace"},{"value":"property","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"type"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.modelio/documentation/ModelIO","doc://com.apple.modelio/documentation/ModelIO/MDLMeshBuffer"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"identifiers":["doc://com.apple.modelio/documentation/ModelIO/MDLMeshBuffer/allocator","doc://com.apple.modelio/documentation/ModelIO/MDLMeshBuffer/zone"],"generated":true,"title":"Inspecting a Buffer","anchor":"Inspecting-a-Buffer"}],"path":"/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"MDLMeshBufferType","kind":"typeIdentifier","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferType","preciseIdentifier":"c:@E@MDLMeshBufferType"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"/primaryContentSections/0","op":"replace"},{"value":"allocator","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBuffer~1allocator/title","op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBuffer~1allocator/fragments","value":[{"text":"allocator","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferType~1index/title","value":"MDLMeshBufferTypeIndex"},{"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferType~1index/fragments","value":[{"text":"MDLMeshBufferTypeIndex","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferType/title","value":"MDLMeshBufferType"},{"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferType/fragments","value":[{"kind":"identifier","text":"MDLMeshBufferType"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferType/navigatorTitle","value":[{"kind":"identifier","text":"MDLMeshBufferType"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBuffer~1zone/title","value":"zone"},{"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBuffer~1zone/fragments","value":[{"kind":"identifier","text":"zone"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferType~1vertex/title","value":"MDLMeshBufferTypeVertex"},{"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferType~1vertex/fragments","value":[{"kind":"identifier","text":"MDLMeshBufferTypeVertex"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh/title","value":"MDLMesh"},{"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh/fragments","value":[{"kind":"identifier","text":"MDLMesh"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh/navigatorTitle","value":[{"text":"MDLMesh","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferAllocator/title","value":"MDLMeshBufferAllocator"},{"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferAllocator/fragments","value":[{"kind":"identifier","text":"MDLMeshBufferAllocator"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferAllocator/navigatorTitle","value":[{"text":"MDLMeshBufferAllocator","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSubmesh/title","value":"MDLSubmesh"},{"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSubmesh/fragments","value":[{"text":"MDLSubmesh","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSubmesh/navigatorTitle","value":[{"kind":"identifier","text":"MDLSubmesh"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBuffer/title","value":"MDLMeshBuffer"},{"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBuffer/fragments","value":[{"kind":"identifier","text":"MDLMeshBuffer"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBuffer/navigatorTitle","value":[{"kind":"identifier","text":"MDLMeshBuffer"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBuffer~1type/title","value":"type"},{"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBuffer~1type/fragments","value":[{"kind":"identifier","text":"type"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}