{
  "abstract": [
    {
      "text": "An error encountered when performing an FSKit operation.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://FSKit/documentation/FSKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://FSKit/documentation/FSKit/FSError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC11FSErrorCodeLeV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "FSError"
      }
    ],
    "modules": [
      {
        "name": "FSKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "FSError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "FSError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "FSError"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://FSKit/documentation/FSKit": {
      "abstract": [
        {
          "text": "Implement a file system that runs in user space.",
          "type": "text"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit",
      "kind": "symbol",
      "role": "collection",
      "title": "FSKit",
      "type": "topic",
      "url": "/documentation/fskit"
    },
    "doc://FSKit/documentation/FSKit/FSError": {
      "abstract": [
        {
          "text": "An error encountered when performing an FSKit operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FSError"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSError"
        }
      ],
      "role": "symbol",
      "title": "FSError",
      "type": "topic",
      "url": "/documentation/fskit/fserror"
    },
    "doc://FSKit/documentation/FSKit/FSError/Code": {
      "abstract": [
        {
          "text": "A code that indicates a specific FSKit error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "FSError.Code",
      "type": "topic",
      "url": "/documentation/fskit/fserror/code"
    },
    "doc://FSKit/documentation/FSKit/FSError/CustomNSError-Implementations": {
      "abstract": [],
      "identifier": "doc://FSKit/documentation/FSKit/FSError/CustomNSError-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CustomNSError Implementations",
      "type": "topic",
      "url": "/documentation/fskit/fserror/customnserror-implementations"
    },
    "doc://FSKit/documentation/FSKit/FSError/Equatable-Implementations": {
      "abstract": [],
      "identifier": "doc://FSKit/documentation/FSKit/FSError/Equatable-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Equatable Implementations",
      "type": "topic",
      "url": "/documentation/fskit/fserror/equatable-implementations"
    },
    "doc://FSKit/documentation/FSKit/FSError/Error-Implementations": {
      "abstract": [],
      "identifier": "doc://FSKit/documentation/FSKit/FSError/Error-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Error Implementations",
      "type": "topic",
      "url": "/documentation/fskit/fserror/error-implementations"
    },
    "doc://FSKit/documentation/FSKit/FSError/Hashable-Implementations": {
      "abstract": [],
      "identifier": "doc://FSKit/documentation/FSKit/FSError/Hashable-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Hashable Implementations",
      "type": "topic",
      "url": "/documentation/fskit/fserror/hashable-implementations"
    },
    "doc://FSKit/documentation/FSKit/FSError/errorDomain": {
      "abstract": [
        {
          "text": "The domain of the error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSError/errorDomain",
      "kind": "symbol",
      "role": "symbol",
      "title": "errorDomain",
      "type": "topic",
      "url": "/documentation/fskit/fserror/errordomain"
    },
    "doc://FSKit/documentation/FSKit/FSError/invalidDirectoryCookie": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidDirectoryCookie"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11FSErrorCodeLeV",
          "text": "FSError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@FSErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSError/invalidDirectoryCookie",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidDirectoryCookie",
      "type": "topic",
      "url": "/documentation/fskit/fserror/invaliddirectorycookie"
    },
    "doc://FSKit/documentation/FSKit/FSError/moduleLoadFailed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "moduleLoadFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11FSErrorCodeLeV",
          "text": "FSError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@FSErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSError/moduleLoadFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "moduleLoadFailed",
      "type": "topic",
      "url": "/documentation/fskit/fserror/moduleloadfailed"
    },
    "doc://FSKit/documentation/FSKit/FSError/resourceDamaged": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resourceDamaged"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11FSErrorCodeLeV",
          "text": "FSError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@FSErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSError/resourceDamaged",
      "kind": "symbol",
      "role": "symbol",
      "title": "resourceDamaged",
      "type": "topic",
      "url": "/documentation/fskit/fserror/resourcedamaged"
    },
    "doc://FSKit/documentation/FSKit/FSError/resourceUnrecognized": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resourceUnrecognized"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11FSErrorCodeLeV",
          "text": "FSError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@FSErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSError/resourceUnrecognized",
      "kind": "symbol",
      "role": "symbol",
      "title": "resourceUnrecognized",
      "type": "topic",
      "url": "/documentation/fskit/fserror/resourceunrecognized"
    },
    "doc://FSKit/documentation/FSKit/FSError/resourceUnusable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resourceUnusable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11FSErrorCodeLeV",
          "text": "FSError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@FSErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSError/resourceUnusable",
      "kind": "symbol",
      "role": "symbol",
      "title": "resourceUnusable",
      "type": "topic",
      "url": "/documentation/fskit/fserror/resourceunusable"
    },
    "doc://FSKit/documentation/FSKit/FSError/statusOperationInProgress": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusOperationInProgress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11FSErrorCodeLeV",
          "text": "FSError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@FSErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSError/statusOperationInProgress",
      "kind": "symbol",
      "role": "symbol",
      "title": "statusOperationInProgress",
      "type": "topic",
      "url": "/documentation/fskit/fserror/statusoperationinprogress"
    },
    "doc://FSKit/documentation/FSKit/FSError/statusOperationPaused": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusOperationPaused"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11FSErrorCodeLeV",
          "text": "FSError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@FSErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSError/statusOperationPaused",
      "kind": "symbol",
      "role": "symbol",
      "title": "statusOperationPaused",
      "type": "topic",
      "url": "/documentation/fskit/fserror/statusoperationpaused"
    },
    "doc://FSKit/documentation/FSKit/FSKitErrorDomain": {
      "abstract": [
        {
          "text": "An error domain for FSKit errors.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FSKitErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSKitErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSKitErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "FSKitErrorDomain",
      "type": "topic",
      "url": "/documentation/fskit/fskiterrordomain"
    },
    "doc://FSKit/documentation/FSKit/fs_errorForCocoaError(_:)": {
      "abstract": [
        {
          "text": "Creates an error object for the given Cocoa error code.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fs_errorForCocoaError"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ") -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/fs_errorForCocoaError(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fs_errorForCocoaError"
        }
      ],
      "role": "symbol",
      "title": "fs_errorForCocoaError(_:)",
      "type": "topic",
      "url": "/documentation/fskit/fs_errorforcocoaerror(_:)"
    },
    "doc://FSKit/documentation/FSKit/fs_errorForMachError(_:)": {
      "abstract": [
        {
          "text": "Creates an error object for the given Mach error code.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fs_errorForMachError"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ") -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/fs_errorForMachError(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fs_errorForMachError"
        }
      ],
      "role": "symbol",
      "title": "fs_errorForMachError(_:)",
      "type": "topic",
      "url": "/documentation/fskit/fs_errorformacherror(_:)"
    },
    "doc://FSKit/documentation/FSKit/fs_errorForPOSIXError(_:)": {
      "abstract": [
        {
          "text": "Creates an error object for the given POSIX error code.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fs_errorForPOSIXError"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ") -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/fs_errorForPOSIXError(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fs_errorForPOSIXError"
        }
      ],
      "role": "symbol",
      "title": "fs_errorForPOSIXError(_:)",
      "type": "topic",
      "url": "/documentation/fskit/fs_errorforposixerror(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP": {
      "abstract": [
        {
          "text": "A specialized error that provides a domain, error code, and user-info dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "CustomNSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomNSError",
      "type": "topic",
      "url": "/documentation/foundation/customnserror"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s5ErrorP",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors-and-logging",
      "generated": true,
      "identifiers": [
        "doc://FSKit/documentation/FSKit/fs_errorForCocoaError(_:)",
        "doc://FSKit/documentation/FSKit/fs_errorForMachError(_:)",
        "doc://FSKit/documentation/FSKit/fs_errorForPOSIXError(_:)",
        "doc://FSKit/documentation/FSKit/FSError/Code",
        "doc://FSKit/documentation/FSKit/FSKitErrorDomain"
      ],
      "title": "Errors and logging"
    }
  ],
  "topicSections": [
    {
      "anchor": "Identifying-errors",
      "identifiers": [
        "doc://FSKit/documentation/FSKit/FSError/invalidDirectoryCookie",
        "doc://FSKit/documentation/FSKit/FSError/moduleLoadFailed",
        "doc://FSKit/documentation/FSKit/FSError/resourceDamaged",
        "doc://FSKit/documentation/FSKit/FSError/resourceUnrecognized",
        "doc://FSKit/documentation/FSKit/FSError/resourceUnusable",
        "doc://FSKit/documentation/FSKit/FSError/statusOperationInProgress",
        "doc://FSKit/documentation/FSKit/FSError/statusOperationPaused"
      ],
      "title": "Identifying errors"
    },
    {
      "anchor": "Identifying-the-error-domain",
      "identifiers": [
        "doc://FSKit/documentation/FSKit/FSError/errorDomain"
      ],
      "title": "Identifying the error domain"
    },
    {
      "anchor": "Default-Implementations",
      "generated": true,
      "identifiers": [
        "doc://FSKit/documentation/FSKit/FSError/CustomNSError-Implementations",
        "doc://FSKit/documentation/FSKit/FSError/Equatable-Implementations",
        "doc://FSKit/documentation/FSKit/FSError/Error-Implementations",
        "doc://FSKit/documentation/FSKit/FSError/Hashable-Implementations"
      ],
      "title": "Default Implementations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSKitErrorDomain/title",
          "value": "FSKitErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSKitErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSKitErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1fs_errorForCocoaError(_:)/title",
          "value": "fs_errorForCocoaError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1fs_errorForCocoaError(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fs_errorForCocoaError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSError~1Code/title",
          "value": "FSErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1fs_errorForMachError(_:)/title",
          "value": "fs_errorForMachError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1fs_errorForMachError(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fs_errorForMachError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1fs_errorForPOSIXError(_:)/title",
          "value": "fs_errorForPOSIXError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1fs_errorForPOSIXError(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fs_errorForPOSIXError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/fskit/fserror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
