{
  "abstract": [
    {
      "text": "The name of a file, expressed as a data buffer.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://FSKit/documentation/FSKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://FSKit/documentation/FSKit/FSFileName"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)FSFileName",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "FSFileName"
      }
    ],
    "modules": [
      {
        "name": "FSKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "FSFileName"
      }
    ],
    "platforms": [
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "FSFileName"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "FSFileName"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "code": "FSFileName",
              "type": "codeVoice"
            },
            {
              "text": " is the class that carries filenames from the kernel to ",
              "type": "text"
            },
            {
              "code": "FSModule",
              "type": "codeVoice"
            },
            {
              "text": " instances, and carries names back to the kernel as part of directory enumeration.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "A filename is usually a valid UTF-8 sequence, but can be an arbitrary byte sequence that doesn’t conform to that format.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "As a result, the ",
              "type": "text"
            },
            {
              "identifier": "doc://FSKit/documentation/FSKit/FSFileName/data",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property always contains a value, but the ",
              "type": "text"
            },
            {
              "identifier": "doc://FSKit/documentation/FSKit/FSFileName/string",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property may be empty.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "An ",
              "type": "text"
            },
            {
              "code": "FSModule",
              "type": "codeVoice"
            },
            {
              "text": " can receive an ",
              "type": "text"
            },
            {
              "code": "FSFileName",
              "type": "codeVoice"
            },
            {
              "text": " that isn’t valid UTF-8 in two cases:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "A program passes erroneous data to a system call. The ",
                      "type": "text"
                    },
                    {
                      "code": "FSModule",
                      "type": "codeVoice"
                    },
                    {
                      "text": " treats this situation as an error.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "An ",
                      "type": "text"
                    },
                    {
                      "code": "FSModule",
                      "type": "codeVoice"
                    },
                    {
                      "text": " lacks the character encoding used for a file name.",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "This situation occurs because some file system formats consider a filename to be an arbitrary “bag of bytes,” and leave character encoding up to the operating system.",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "Without encoding information, the ",
                      "type": "text"
                    },
                    {
                      "code": "FSModule",
                      "type": "codeVoice"
                    },
                    {
                      "text": " can only pass back the names it finds on disk.",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "In this case, the behavior of upper layers such as ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/foundation/nsfilemanager",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " is unspecified.",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "However, the ",
                      "type": "text"
                    },
                    {
                      "code": "FSModule",
                      "type": "codeVoice"
                    },
                    {
                      "text": " must support looking up such names and using them as the source name of rename operations.",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "The ",
                      "type": "text"
                    },
                    {
                      "code": "FSModule",
                      "type": "codeVoice"
                    },
                    {
                      "text": " must also be able to support filenames that are derivatives of filenames returned from directory enumeration.",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "Derivative filenames include Apple Double filenames (",
                      "type": "text"
                    },
                    {
                      "code": "\"._Name\"",
                      "type": "codeVoice"
                    },
                    {
                      "text": "), and editor backup filenames.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Don’t subclass this class.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://FSKit/documentation/FSKit": {
      "abstract": [
        {
          "text": "Implement a file system that runs in user space.",
          "type": "text"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit",
      "kind": "symbol",
      "role": "collection",
      "title": "FSKit",
      "type": "topic",
      "url": "/documentation/fskit"
    },
    "doc://FSKit/documentation/FSKit/FSFileName": {
      "abstract": [
        {
          "text": "The name of a file, expressed as a data buffer.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FSFileName"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSFileName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSFileName"
        }
      ],
      "role": "symbol",
      "title": "FSFileName",
      "type": "topic",
      "url": "/documentation/fskit/fsfilename"
    },
    "doc://FSKit/documentation/FSKit/FSFileName/data": {
      "abstract": [
        {
          "text": "The byte sequence of the filename, as a data object.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "data"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSFileName/data",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "data"
        }
      ],
      "role": "symbol",
      "title": "data",
      "type": "topic",
      "url": "/documentation/fskit/fsfilename/data"
    },
    "doc://FSKit/documentation/FSKit/FSFileName/debugDescription": {
      "abstract": [
        {
          "text": "The filename, represented as a potentially lossy conversion to a string.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "debugDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSFileName/debugDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "debugDescription"
        }
      ],
      "role": "symbol",
      "title": "debugDescription",
      "type": "topic",
      "url": "/documentation/fskit/fsfilename/debugdescription"
    },
    "doc://FSKit/documentation/FSKit/FSFileName/init(bytes:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "bytes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SR",
          "text": "UnsafeBufferPointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSFileName/init(bytes:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(bytes:)",
      "type": "topic",
      "url": "/documentation/fskit/fsfilename/init(bytes:)"
    },
    "doc://FSKit/documentation/FSKit/FSFileName/init(cString:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "cString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SR",
          "text": "UnsafeBufferPointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSFileName/init(cString:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(cString:)",
      "type": "topic",
      "url": "/documentation/fskit/fsfilename/init(cstring:)"
    },
    "doc://FSKit/documentation/FSKit/FSFileName/init(data:)": {
      "abstract": [
        {
          "text": "Creates a filename by copying a character sequence data object.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "data"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSFileName/init(data:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithData:"
        }
      ],
      "role": "symbol",
      "title": "init(data:)",
      "type": "topic",
      "url": "/documentation/fskit/fsfilename/init(data:)"
    },
    "doc://FSKit/documentation/FSKit/FSFileName/init(string:)": {
      "abstract": [
        {
          "text": "Creates a filename by copying a character sequence from a string instance.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "string"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSFileName/init(string:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithString:"
        }
      ],
      "role": "symbol",
      "title": "init(string:)",
      "type": "topic",
      "url": "/documentation/fskit/fsfilename/init(string:)"
    },
    "doc://FSKit/documentation/FSKit/FSFileName/initWithBytes:length:": {
      "abstract": [
        {
          "text": "Initializes a file name by copying a character sequence from a byte array.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithBytes:length:"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSFileName/initWithBytes:length:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithBytes:length:"
        }
      ],
      "role": "symbol",
      "title": "initWithBytes:length:",
      "type": "topic",
      "url": "/documentation/fskit/fsfilename/initwithbytes:length:"
    },
    "doc://FSKit/documentation/FSKit/FSFileName/initWithCString:": {
      "abstract": [
        {
          "text": "Initializes a filename from a null-terminated character sequence.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithCString:"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSFileName/initWithCString:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithCString:"
        }
      ],
      "role": "symbol",
      "title": "initWithCString:",
      "type": "topic",
      "url": "/documentation/fskit/fsfilename/initwithcstring:"
    },
    "doc://FSKit/documentation/FSKit/FSFileName/nameWithBytes:length:": {
      "abstract": [
        {
          "text": "Creates a filename by copying a character sequence from a byte array.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "nameWithBytes:length:"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSFileName/nameWithBytes:length:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nameWithBytes:length:"
        }
      ],
      "role": "symbol",
      "title": "nameWithBytes:length:",
      "type": "topic",
      "url": "/documentation/fskit/fsfilename/namewithbytes:length:"
    },
    "doc://FSKit/documentation/FSKit/FSFileName/nameWithCString:": {
      "abstract": [
        {
          "text": "Creates a filename from a null-terminated character sequence.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "nameWithCString:"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSFileName/nameWithCString:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nameWithCString:"
        }
      ],
      "role": "symbol",
      "title": "nameWithCString:",
      "type": "topic",
      "url": "/documentation/fskit/fsfilename/namewithcstring:"
    },
    "doc://FSKit/documentation/FSKit/FSFileName/nameWithData:": {
      "abstract": [
        {
          "text": "Creates a filename by copying a character sequence data object.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "nameWithData:"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSFileName/nameWithData:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nameWithData:"
        }
      ],
      "role": "symbol",
      "title": "nameWithData:",
      "type": "topic",
      "url": "/documentation/fskit/fsfilename/namewithdata:"
    },
    "doc://FSKit/documentation/FSKit/FSFileName/nameWithString:": {
      "abstract": [
        {
          "text": "Creates a filename by copying a character sequence from a string instance.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "nameWithString:"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSFileName/nameWithString:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nameWithString:"
        }
      ],
      "role": "symbol",
      "title": "nameWithString:",
      "type": "topic",
      "url": "/documentation/fskit/fsfilename/namewithstring:"
    },
    "doc://FSKit/documentation/FSKit/FSFileName/string": {
      "abstract": [
        {
          "text": "The filename, represented as a Unicode string.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "string"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSFileName/string",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "string"
        }
      ],
      "role": "symbol",
      "title": "string",
      "type": "topic",
      "url": "/documentation/fskit/fsfilename/string"
    },
    "doc://FSKit/documentation/FSKit/FSFileSystem": {
      "abstract": [
        {
          "text": "An abstract base class for implementing a full-featured file system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "FSFileSystem"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSFileSystem",
      "kind": "symbol",
      "role": "symbol",
      "title": "FSFileSystem",
      "type": "topic",
      "url": "/documentation/fskit/fsfilesystem"
    },
    "doc://FSKit/documentation/FSKit/FSFileSystemBase": {
      "abstract": [
        {
          "text": "A protocol containing functionality supplied by FSKit to file system implementations.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FSFileSystemBase"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSFileSystemBase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSFileSystemBase"
        }
      ],
      "role": "symbol",
      "title": "FSFileSystemBase",
      "type": "topic",
      "url": "/documentation/fskit/fsfilesystembase"
    },
    "doc://FSKit/documentation/FSKit/FSUnaryFileSystem": {
      "abstract": [
        {
          "text": "An abstract base class for implementing a minimal file system.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FSUnaryFileSystem"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSUnaryFileSystem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSUnaryFileSystem"
        }
      ],
      "role": "symbol",
      "title": "FSUnaryFileSystem",
      "type": "topic",
      "url": "/documentation/fskit/fsunaryfilesystem"
    },
    "doc://com.apple.documentation/documentation/foundation/nsfilemanager": {
      "abstract": [
        {
          "text": "A convenient interface to the contents of the file system, and the primary means of interacting with it.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsfilemanager",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSFileManager",
      "type": "topic",
      "url": "/documentation/foundation/nsfilemanager"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "File-systems",
      "generated": true,
      "identifiers": [
        "doc://FSKit/documentation/FSKit/FSUnaryFileSystem",
        "doc://FSKit/documentation/FSKit/FSFileSystemBase"
      ],
      "title": "File systems"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-filename",
      "identifiers": [
        "doc://FSKit/documentation/FSKit/FSFileName/init(bytes:)",
        "doc://FSKit/documentation/FSKit/FSFileName/init(cString:)",
        "doc://FSKit/documentation/FSKit/FSFileName/init(data:)",
        "doc://FSKit/documentation/FSKit/FSFileName/init(string:)"
      ],
      "title": "Creating a filename"
    },
    {
      "anchor": "Accessing-filename-properties",
      "identifiers": [
        "doc://FSKit/documentation/FSKit/FSFileName/data",
        "doc://FSKit/documentation/FSKit/FSFileName/string",
        "doc://FSKit/documentation/FSKit/FSFileName/debugDescription"
      ],
      "title": "Accessing filename properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "FSFileName"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSFileName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSFileName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://FSKit/documentation/FSKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-filename",
              "identifiers": [
                "doc://FSKit/documentation/FSKit/FSFileName/initWithBytes:length:",
                "doc://FSKit/documentation/FSKit/FSFileName/nameWithBytes:length:",
                "doc://FSKit/documentation/FSKit/FSFileName/initWithCString:",
                "doc://FSKit/documentation/FSKit/FSFileName/nameWithCString:",
                "doc://FSKit/documentation/FSKit/FSFileName/init(data:)",
                "doc://FSKit/documentation/FSKit/FSFileName/nameWithData:",
                "doc://FSKit/documentation/FSKit/FSFileName/init(string:)",
                "doc://FSKit/documentation/FSKit/FSFileName/nameWithString:"
              ],
              "title": "Creating a filename"
            },
            {
              "anchor": "Accessing-filename-properties",
              "identifiers": [
                "doc://FSKit/documentation/FSKit/FSFileName/data",
                "doc://FSKit/documentation/FSKit/FSFileName/string",
                "doc://FSKit/documentation/FSKit/FSFileName/debugDescription"
              ],
              "title": "Accessing filename properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "File-systems",
              "generated": true,
              "identifiers": [
                "doc://FSKit/documentation/FSKit/FSFileSystem",
                "doc://FSKit/documentation/FSKit/FSUnaryFileSystem",
                "doc://FSKit/documentation/FSKit/FSFileSystemBase"
              ],
              "title": "File systems"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "FSFileName"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSFileName~1init(data:)/title",
          "value": "initWithData:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSFileName~1init(data:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithData:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSFileSystemBase/title",
          "value": "FSFileSystemBase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSFileSystemBase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSFileSystemBase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSFileSystemBase/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSFileSystemBase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSFileName~1data/title",
          "value": "data"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSFileName~1data/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSFileName~1init(string:)/title",
          "value": "initWithString:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSFileName~1init(string:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithString:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSFileName/title",
          "value": "FSFileName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSFileName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSFileName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSFileName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSFileName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSFileName~1debugDescription/title",
          "value": "debugDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSFileName~1debugDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "debugDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSUnaryFileSystem/title",
          "value": "FSUnaryFileSystem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSUnaryFileSystem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSUnaryFileSystem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSUnaryFileSystem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSUnaryFileSystem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSFileName~1string/title",
          "value": "string"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSFileName~1string/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "string"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    },
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsfilemanager/title",
          "value": "FileManager"
        },
        {
          "op": "add",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsfilemanager/fragments",
          "value": [
            {
              "kind": "text",
              "text": "class "
            },
            {
              "kind": "identifier",
              "text": "FileManager"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/fskit/fsfilename"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/fskit/fsfilename"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
