{
  "diffAvailability": {
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://FSKit/documentation/FSKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://FSKit/documentation/FSKit/FSProbeResult"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)FSProbeResult",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "FSProbeResult"
      }
    ],
    "modules": [
      {
        "name": "FSKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "FSProbeResult"
      }
    ],
    "platforms": [
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "FSProbeResult"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "FSProbeResult"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://FSKit/documentation/FSKit": {
      "abstract": [
        {
          "text": "Implement a file system that runs in user space.",
          "type": "text"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit",
      "kind": "symbol",
      "role": "collection",
      "title": "FSKit",
      "type": "topic",
      "url": "/documentation/fskit"
    },
    "doc://FSKit/documentation/FSKit/FSBlockmapFlags": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FSBlockmapFlags"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSBlockmapFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSBlockmapFlags"
        }
      ],
      "role": "symbol",
      "title": "FSBlockmapFlags",
      "type": "topic",
      "url": "/documentation/fskit/fsblockmapflags"
    },
    "doc://FSKit/documentation/FSKit/FSCompleteIOFlags": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FSCompleteIOFlags"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSCompleteIOFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSCompleteIOFlags"
        }
      ],
      "role": "symbol",
      "title": "FSCompleteIOFlags",
      "type": "topic",
      "url": "/documentation/fskit/fscompleteioflags"
    },
    "doc://FSKit/documentation/FSKit/FSDeactivateOptions": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FSDeactivateOptions"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSDeactivateOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSDeactivateOptions"
        }
      ],
      "role": "symbol",
      "title": "FSDeactivateOptions",
      "type": "topic",
      "url": "/documentation/fskit/fsdeactivateoptions"
    },
    "doc://FSKit/documentation/FSKit/FSDirectoryCookie": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FSDirectoryCookie"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSDirectoryCookie",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSDirectoryCookie"
        }
      ],
      "role": "symbol",
      "title": "FSDirectoryCookie",
      "type": "topic",
      "url": "/documentation/fskit/fsdirectorycookie"
    },
    "doc://FSKit/documentation/FSKit/FSDirectoryCookie/initial": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "initial"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FSDirectoryCookie",
          "text": "FSDirectoryCookie"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSDirectoryCookie/initial",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSDirectoryCookieInitial"
        }
      ],
      "role": "symbol",
      "title": "initial",
      "type": "topic",
      "url": "/documentation/fskit/fsdirectorycookie/initial"
    },
    "doc://FSKit/documentation/FSKit/FSDirectoryEntryPacker": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FSDirectoryEntryPacker"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSDirectoryEntryPacker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSDirectoryEntryPacker"
        }
      ],
      "role": "symbol",
      "title": "FSDirectoryEntryPacker",
      "type": "topic",
      "url": "/documentation/fskit/fsdirectoryentrypacker"
    },
    "doc://FSKit/documentation/FSKit/FSDirectoryVerifier": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FSDirectoryVerifier"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSDirectoryVerifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSDirectoryVerifier"
        }
      ],
      "role": "symbol",
      "title": "FSDirectoryVerifier",
      "type": "topic",
      "url": "/documentation/fskit/fsdirectoryverifier"
    },
    "doc://FSKit/documentation/FSKit/FSDirectoryVerifier/initial": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "initial"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FSDirectoryVerifier",
          "text": "FSDirectoryVerifier"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSDirectoryVerifier/initial",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSDirectoryVerifierInitial"
        }
      ],
      "role": "symbol",
      "title": "initial",
      "type": "topic",
      "url": "/documentation/fskit/fsdirectoryverifier/initial"
    },
    "doc://FSKit/documentation/FSKit/FSEntityIdentifier": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FSEntityIdentifier"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSEntityIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSEntityIdentifier"
        }
      ],
      "role": "symbol",
      "title": "FSEntityIdentifier",
      "type": "topic",
      "url": "/documentation/fskit/fsentityidentifier"
    },
    "doc://FSKit/documentation/FSKit/FSExtentPacker": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FSExtentPacker"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSExtentPacker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSExtentPacker"
        }
      ],
      "role": "symbol",
      "title": "FSExtentPacker",
      "type": "topic",
      "url": "/documentation/fskit/fsextentpacker"
    },
    "doc://FSKit/documentation/FSKit/FSExtentType": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FSExtentType"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSExtentType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSExtentType"
        }
      ],
      "role": "symbol",
      "title": "FSExtentType",
      "type": "topic",
      "url": "/documentation/fskit/fsextenttype"
    },
    "doc://FSKit/documentation/FSKit/FSMatchResult": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FSMatchResult"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSMatchResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSMatchResult"
        }
      ],
      "role": "symbol",
      "title": "FSMatchResult",
      "type": "topic",
      "url": "/documentation/fskit/fsmatchresult"
    },
    "doc://FSKit/documentation/FSKit/FSProbeResult": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FSProbeResult"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSProbeResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSProbeResult"
        }
      ],
      "role": "symbol",
      "title": "FSProbeResult",
      "type": "topic",
      "url": "/documentation/fskit/fsproberesult"
    },
    "doc://FSKit/documentation/FSKit/FSProbeResult/containerID": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "containerID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSContainerIdentifier",
          "text": "FSContainerIdentifier"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSProbeResult/containerID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "containerID"
        }
      ],
      "role": "symbol",
      "title": "containerID",
      "type": "topic",
      "url": "/documentation/fskit/fsproberesult/containerid"
    },
    "doc://FSKit/documentation/FSKit/FSProbeResult/name": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSProbeResult/name",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "name"
        }
      ],
      "role": "symbol",
      "title": "name",
      "type": "topic",
      "url": "/documentation/fskit/fsproberesult/name"
    },
    "doc://FSKit/documentation/FSKit/FSProbeResult/notRecognized": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notRecognized"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSProbeResult",
          "text": "FSProbeResult"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSProbeResult/notRecognized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "notRecognizedProbeResult"
        }
      ],
      "role": "symbol",
      "title": "notRecognized",
      "type": "topic",
      "url": "/documentation/fskit/fsproberesult/notrecognized"
    },
    "doc://FSKit/documentation/FSKit/FSProbeResult/recognized(name:containerID:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recognized"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "containerID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSContainerIdentifier",
          "text": "FSContainerIdentifier"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSProbeResult/recognized(name:containerID:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "recognizedProbeResultWithName:containerID:"
        }
      ],
      "role": "symbol",
      "title": "recognized(name:containerID:)",
      "type": "topic",
      "url": "/documentation/fskit/fsproberesult/recognized(name:containerid:)"
    },
    "doc://FSKit/documentation/FSKit/FSProbeResult/result": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "result"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@FSMatchResult",
          "text": "FSMatchResult"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSProbeResult/result",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "result"
        }
      ],
      "role": "symbol",
      "title": "result",
      "type": "topic",
      "url": "/documentation/fskit/fsproberesult/result"
    },
    "doc://FSKit/documentation/FSKit/FSProbeResult/usable(name:containerID:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "usable"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "containerID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSContainerIdentifier",
          "text": "FSContainerIdentifier"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSProbeResult/usable(name:containerID:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "usableProbeResultWithName:containerID:"
        }
      ],
      "role": "symbol",
      "title": "usable(name:containerID:)",
      "type": "topic",
      "url": "/documentation/fskit/fsproberesult/usable(name:containerid:)"
    },
    "doc://FSKit/documentation/FSKit/FSProbeResult/usableButLimited": {
      "abstract": [
        {
          "text": "This probe result indicates that the file system format is known and is usable with limited capabilities, however the name and/or containerID were unavailable due to limitations on the probed resource.",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "This result must never be returned as the result from probing a reslurce which is not limited.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "usableButLimited"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSProbeResult",
          "text": "FSProbeResult"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSProbeResult/usableButLimited",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "usableButLimitedProbeResult"
        }
      ],
      "role": "symbol",
      "title": "usableButLimited",
      "type": "topic",
      "url": "/documentation/fskit/fsproberesult/usablebutlimited"
    },
    "doc://FSKit/documentation/FSKit/FSProbeResult/usableButLimited(name:containerID:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "usableButLimited"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "containerID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSContainerIdentifier",
          "text": "FSContainerIdentifier"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSProbeResult/usableButLimited(name:containerID:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "usableButLimitedProbeResultWithName:containerID:"
        }
      ],
      "role": "symbol",
      "title": "usableButLimited(name:containerID:)",
      "type": "topic",
      "url": "/documentation/fskit/fsproberesult/usablebutlimited(name:containerid:)"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/AccessMask": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AccessMask"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/AccessMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AccessMask"
        }
      ],
      "role": "symbol",
      "title": "FSVolume.AccessMask",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/accessmask"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Supporting-types",
      "generated": true,
      "identifiers": [
        "doc://FSKit/documentation/FSKit/FSVolume/AccessMask",
        "doc://FSKit/documentation/FSKit/FSBlockmapFlags",
        "doc://FSKit/documentation/FSKit/FSCompleteIOFlags",
        "doc://FSKit/documentation/FSKit/FSDeactivateOptions",
        "doc://FSKit/documentation/FSKit/FSDirectoryCookie",
        "doc://FSKit/documentation/FSKit/FSDirectoryCookie",
        "doc://FSKit/documentation/FSKit/FSDirectoryCookie/initial",
        "doc://FSKit/documentation/FSKit/FSDirectoryEntryPacker",
        "doc://FSKit/documentation/FSKit/FSDirectoryVerifier",
        "doc://FSKit/documentation/FSKit/FSDirectoryVerifier",
        "doc://FSKit/documentation/FSKit/FSDirectoryVerifier/initial",
        "doc://FSKit/documentation/FSKit/FSEntityIdentifier",
        "doc://FSKit/documentation/FSKit/FSExtentPacker",
        "doc://FSKit/documentation/FSKit/FSExtentType",
        "doc://FSKit/documentation/FSKit/FSMatchResult"
      ],
      "title": "Supporting types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://FSKit/documentation/FSKit/FSProbeResult/containerID",
        "doc://FSKit/documentation/FSKit/FSProbeResult/name",
        "doc://FSKit/documentation/FSKit/FSProbeResult/result"
      ],
      "title": "Instance Properties"
    },
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://FSKit/documentation/FSKit/FSProbeResult/notRecognized",
        "doc://FSKit/documentation/FSKit/FSProbeResult/usableButLimited"
      ],
      "title": "Type Properties"
    },
    {
      "anchor": "Type-Methods",
      "generated": true,
      "identifiers": [
        "doc://FSKit/documentation/FSKit/FSProbeResult/recognized(name:containerID:)",
        "doc://FSKit/documentation/FSKit/FSProbeResult/usable(name:containerID:)",
        "doc://FSKit/documentation/FSKit/FSProbeResult/usableButLimited(name:containerID:)"
      ],
      "title": "Type Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "FSProbeResult"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSProbeResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSProbeResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://FSKit/documentation/FSKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://FSKit/documentation/FSKit/FSProbeResult/containerID",
                "doc://FSKit/documentation/FSKit/FSProbeResult/name",
                "doc://FSKit/documentation/FSKit/FSProbeResult/result"
              ],
              "title": "Instance Properties"
            },
            {
              "anchor": "Type-Properties",
              "generated": true,
              "identifiers": [
                "doc://FSKit/documentation/FSKit/FSProbeResult/notRecognized",
                "doc://FSKit/documentation/FSKit/FSProbeResult/usableButLimited"
              ],
              "title": "Type Properties"
            },
            {
              "anchor": "Type-Methods",
              "generated": true,
              "identifiers": [
                "doc://FSKit/documentation/FSKit/FSProbeResult/recognized(name:containerID:)",
                "doc://FSKit/documentation/FSKit/FSProbeResult/usable(name:containerID:)",
                "doc://FSKit/documentation/FSKit/FSProbeResult/usableButLimited(name:containerID:)"
              ],
              "title": "Type Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Supporting-types",
              "generated": true,
              "identifiers": [
                "doc://FSKit/documentation/FSKit/FSVolume/AccessMask",
                "doc://FSKit/documentation/FSKit/FSBlockmapFlags",
                "doc://FSKit/documentation/FSKit/FSCompleteIOFlags",
                "doc://FSKit/documentation/FSKit/FSDeactivateOptions",
                "doc://FSKit/documentation/FSKit/FSDirectoryCookie",
                "doc://FSKit/documentation/FSKit/FSDirectoryCookie",
                "doc://FSKit/documentation/FSKit/FSDirectoryCookie/initial",
                "doc://FSKit/documentation/FSKit/FSDirectoryEntryPacker",
                "doc://FSKit/documentation/FSKit/FSDirectoryVerifier",
                "doc://FSKit/documentation/FSKit/FSDirectoryVerifier",
                "doc://FSKit/documentation/FSKit/FSDirectoryVerifier/initial",
                "doc://FSKit/documentation/FSKit/FSEntityIdentifier",
                "doc://FSKit/documentation/FSKit/FSExtentPacker",
                "doc://FSKit/documentation/FSKit/FSExtentType",
                "doc://FSKit/documentation/FSKit/FSMatchResult"
              ],
              "title": "Supporting types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "FSProbeResult"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSDirectoryCookie/title",
          "value": "FSDirectoryCookie"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSDirectoryCookie/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSDirectoryCookie"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSDirectoryCookie/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSDirectoryCookie"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSBlockmapFlags/title",
          "value": "FSBlockmapFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSBlockmapFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSBlockmapFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSBlockmapFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSBlockmapFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSDirectoryEntryPacker/title",
          "value": "FSDirectoryEntryPacker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSDirectoryEntryPacker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSDirectoryEntryPacker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSDirectoryEntryPacker/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSDirectoryEntryPacker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSExtentType/title",
          "value": "FSExtentType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSExtentType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSExtentType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSExtentType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSExtentType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSDeactivateOptions/title",
          "value": "FSDeactivateOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSDeactivateOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSDeactivateOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSDeactivateOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSDeactivateOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSProbeResult~1name/title",
          "value": "name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSProbeResult~1name/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSMatchResult/title",
          "value": "FSMatchResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSMatchResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSMatchResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSMatchResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSMatchResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSDirectoryCookie~1initial/title",
          "value": "FSDirectoryCookieInitial"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSDirectoryCookie~1initial/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSDirectoryCookieInitial"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSExtentPacker/title",
          "value": "FSExtentPacker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSExtentPacker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSExtentPacker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSExtentPacker/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSExtentPacker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSDirectoryVerifier/title",
          "value": "FSDirectoryVerifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSDirectoryVerifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSDirectoryVerifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSDirectoryVerifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSDirectoryVerifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSProbeResult~1containerID/title",
          "value": "containerID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSProbeResult~1containerID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "containerID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSProbeResult~1notRecognized/title",
          "value": "notRecognizedProbeResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSProbeResult~1notRecognized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "notRecognizedProbeResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSProbeResult~1usableButLimited(name:containerID:)/title",
          "value": "usableButLimitedProbeResultWithName:containerID:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSProbeResult~1usableButLimited(name:containerID:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "usableButLimitedProbeResultWithName:containerID:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSCompleteIOFlags/title",
          "value": "FSCompleteIOFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSCompleteIOFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSCompleteIOFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSCompleteIOFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSCompleteIOFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSProbeResult~1recognized(name:containerID:)/title",
          "value": "recognizedProbeResultWithName:containerID:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSProbeResult~1recognized(name:containerID:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "recognizedProbeResultWithName:containerID:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSDirectoryVerifier~1initial/title",
          "value": "FSDirectoryVerifierInitial"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSDirectoryVerifier~1initial/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSDirectoryVerifierInitial"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSProbeResult~1usableButLimited/title",
          "value": "usableButLimitedProbeResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSProbeResult~1usableButLimited/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "usableButLimitedProbeResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1AccessMask/title",
          "value": "FSAccessMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1AccessMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSAccessMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1AccessMask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSAccessMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSProbeResult~1usable(name:containerID:)/title",
          "value": "usableProbeResultWithName:containerID:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSProbeResult~1usable(name:containerID:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "usableProbeResultWithName:containerID:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSProbeResult~1result/title",
          "value": "result"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSProbeResult~1result/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "result"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSProbeResult/title",
          "value": "FSProbeResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSProbeResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSProbeResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSProbeResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSProbeResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSEntityIdentifier/title",
          "value": "FSEntityIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSEntityIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSEntityIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSEntityIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSEntityIdentifier"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/fskit/fsproberesult"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/fskit/fsproberesult"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
