{
  "abstract": [
    {
      "text": "Operations performed by a unary file system.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://FSKit/documentation/FSKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://FSKit/documentation/FSKit/FSUnaryFileSystemOperations"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)FSUnaryFileSystemOperations",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "FSUnaryFileSystemOperations"
      }
    ],
    "modules": [
      {
        "name": "FSKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "FSUnaryFileSystemOperations"
      }
    ],
    "platforms": [
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "FSUnaryFileSystemOperations"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "FSUnaryFileSystemOperations"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Make sure your subclass of ",
              "type": "text"
            },
            {
              "identifier": "doc://FSKit/documentation/FSKit/FSUnaryFileSystem",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " conforms to this protocol.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://FSKit/documentation/FSKit": {
      "abstract": [
        {
          "text": "Implement a file system that runs in user space.",
          "type": "text"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit",
      "kind": "symbol",
      "role": "collection",
      "title": "FSKit",
      "type": "topic",
      "url": "/documentation/fskit"
    },
    "doc://FSKit/documentation/FSKit/FSUnaryFileSystem": {
      "abstract": [
        {
          "text": "An abstract base class for implementing a minimal file system.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FSUnaryFileSystem"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSUnaryFileSystem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSUnaryFileSystem"
        }
      ],
      "role": "symbol",
      "title": "FSUnaryFileSystem",
      "type": "topic",
      "url": "/documentation/fskit/fsunaryfilesystem"
    },
    "doc://FSKit/documentation/FSKit/FSUnaryFileSystemOperations": {
      "abstract": [
        {
          "text": "Operations performed by a unary file system.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FSUnaryFileSystemOperations"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSUnaryFileSystemOperations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSUnaryFileSystemOperations"
        }
      ],
      "role": "symbol",
      "title": "FSUnaryFileSystemOperations",
      "type": "topic",
      "url": "/documentation/fskit/fsunaryfilesystemoperations"
    },
    "doc://FSKit/documentation/FSKit/FSUnaryFileSystemOperations/didFinishLoading()": {
      "abstract": [
        {
          "text": "Notifies you that the system finished loading your file system extension.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didFinishLoading"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSUnaryFileSystemOperations/didFinishLoading()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "didFinishLoading"
        }
      ],
      "role": "symbol",
      "title": "didFinishLoading()",
      "type": "topic",
      "url": "/documentation/fskit/fsunaryfilesystemoperations/didfinishloading()"
    },
    "doc://FSKit/documentation/FSKit/FSUnaryFileSystemOperations/loadResource(resource:options:replyHandler:)": {
      "abstract": [
        {
          "text": "Requests that the file system load a resource and present it as a volume.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loadResource"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "resource"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSResource",
          "text": "FSResource"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSTaskOptions",
          "text": "FSTaskOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "replyHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSVolume",
          "text": "FSVolume"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSUnaryFileSystemOperations/loadResource(resource:options:replyHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loadResource:options:replyHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "loadResource(resource:options:replyHandler:)",
      "type": "topic",
      "url": "/documentation/fskit/fsunaryfilesystemoperations/loadresource(resource:options:replyhandler:)"
    },
    "doc://FSKit/documentation/FSKit/FSUnaryFileSystemOperations/probeResource(resource:replyHandler:)": {
      "abstract": [
        {
          "text": "Requests that the file system probe the specified resource.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "probeResource"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "resource"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSResource",
          "text": "FSResource"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "replyHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSProbeResult",
          "text": "FSProbeResult"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSUnaryFileSystemOperations/probeResource(resource:replyHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "probeResource:replyHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "probeResource(resource:replyHandler:)",
      "type": "topic",
      "url": "/documentation/fskit/fsunaryfilesystemoperations/proberesource(resource:replyhandler:)"
    },
    "doc://FSKit/documentation/FSKit/FSUnaryFileSystemOperations/unloadResource(resource:options:replyHandler:)": {
      "abstract": [
        {
          "text": "Requests that the file system unload the specified resource.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unloadResource"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "resource"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSResource",
          "text": "FSResource"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSTaskOptions",
          "text": "FSTaskOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "replyHandler"
        },
        {
          "kind": "text",
          "text": ": ((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSUnaryFileSystemOperations/unloadResource(resource:options:replyHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "unloadResource:options:replyHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "unloadResource(resource:options:replyHandler:)",
      "type": "topic",
      "url": "/documentation/fskit/fsunaryfilesystemoperations/unloadresource(resource:options:replyhandler:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://FSKit/documentation/FSKit/FSUnaryFileSystemOperations/didFinishLoading()",
        "doc://FSKit/documentation/FSKit/FSUnaryFileSystemOperations/loadResource(resource:options:replyHandler:)",
        "doc://FSKit/documentation/FSKit/FSUnaryFileSystemOperations/probeResource(resource:replyHandler:)",
        "doc://FSKit/documentation/FSKit/FSUnaryFileSystemOperations/unloadResource(resource:options:replyHandler:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "FSUnaryFileSystemOperations"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSUnaryFileSystemOperations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSUnaryFileSystemOperations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://FSKit/documentation/FSKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://FSKit/documentation/FSKit/FSUnaryFileSystemOperations/didFinishLoading()",
                "doc://FSKit/documentation/FSKit/FSUnaryFileSystemOperations/loadResource(resource:options:replyHandler:)",
                "doc://FSKit/documentation/FSKit/FSUnaryFileSystemOperations/probeResource(resource:replyHandler:)",
                "doc://FSKit/documentation/FSKit/FSUnaryFileSystemOperations/unloadResource(resource:options:replyHandler:)"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "FSUnaryFileSystemOperations"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSUnaryFileSystemOperations~1didFinishLoading()/title",
          "value": "didFinishLoading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSUnaryFileSystemOperations~1didFinishLoading()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "didFinishLoading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSUnaryFileSystem/title",
          "value": "FSUnaryFileSystem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSUnaryFileSystem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSUnaryFileSystem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSUnaryFileSystem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSUnaryFileSystem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSUnaryFileSystemOperations~1probeResource(resource:replyHandler:)/title",
          "value": "probeResource:replyHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSUnaryFileSystemOperations~1probeResource(resource:replyHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "probeResource:replyHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSUnaryFileSystemOperations~1loadResource(resource:options:replyHandler:)/title",
          "value": "loadResource:options:replyHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSUnaryFileSystemOperations~1loadResource(resource:options:replyHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "loadResource:options:replyHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSUnaryFileSystemOperations/title",
          "value": "FSUnaryFileSystemOperations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSUnaryFileSystemOperations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSUnaryFileSystemOperations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSUnaryFileSystemOperations/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSUnaryFileSystemOperations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSUnaryFileSystemOperations~1unloadResource(resource:options:replyHandler:)/title",
          "value": "unloadResource:options:replyHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSUnaryFileSystemOperations~1unloadResource(resource:options:replyHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "unloadResource:options:replyHandler:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/fskit/fsunaryfilesystemoperations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/fskit/fsunaryfilesystemoperations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
