{
  "abstract": [
    {
      "text": "The minimum gradient value before the optimizer rescales the gradient, if you enabled gradient clipping.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mlcompute/documentation/MLCompute",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizerDescriptor"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizerDescriptor/gradientClipMin"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MLCOptimizerDescriptor(py)gradientClipMin",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "gradientClipMin"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sf",
        "text": "Float"
      }
    ],
    "modules": [
      {
        "name": "ML Compute"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "gradientClipMin"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.3",
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "gradientClipMin"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "gradientClipMin"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sf",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sf",
              "text": "Float"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute": {
      "abstract": [
        {
          "text": "Accelerate training and validation of neural networks across the CPU and one or more GPUs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute",
      "kind": "symbol",
      "role": "collection",
      "title": "ML Compute",
      "type": "topic",
      "url": "/documentation/mlcompute"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCGradientClippingType": {
      "abstract": [
        {
          "text": "A clipping type the system applies to a gradient.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCGradientClippingType"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCGradientClippingType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCGradientClippingType"
        }
      ],
      "role": "symbol",
      "title": "MLCGradientClippingType",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcgradientclippingtype"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizerDescriptor": {
      "abstract": [
        {
          "text": "A configuration object you use to create an optimizer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCOptimizerDescriptor"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizerDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCOptimizerDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MLCOptimizerDescriptor",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcoptimizerdescriptor"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizerDescriptor/appliesGradientClipping": {
      "abstract": [
        {
          "text": "A Boolean that indicates whether you apply gradient clipping.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appliesGradientClipping"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizerDescriptor/appliesGradientClipping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "appliesGradientClipping"
        }
      ],
      "role": "symbol",
      "title": "appliesGradientClipping",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcoptimizerdescriptor/appliesgradientclipping"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizerDescriptor/customGlobalNorm": {
      "abstract": [
        {
          "text": "A custom norm the system uses in place of the global norm.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "customGlobalNorm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizerDescriptor/customGlobalNorm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "customGlobalNorm"
        }
      ],
      "role": "symbol",
      "title": "customGlobalNorm",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcoptimizerdescriptor/customglobalnorm"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizerDescriptor/gradientClipMax": {
      "abstract": [
        {
          "text": "The maximum gradient value before the optimizer rescales the gradient, if you enabled gradient clipping.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gradientClipMax"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizerDescriptor/gradientClipMax",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gradientClipMax"
        }
      ],
      "role": "symbol",
      "title": "gradientClipMax",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcoptimizerdescriptor/gradientclipmax"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizerDescriptor/gradientClipMin": {
      "abstract": [
        {
          "text": "The minimum gradient value before the optimizer rescales the gradient, if you enabled gradient clipping.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gradientClipMin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizerDescriptor/gradientClipMin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gradientClipMin"
        }
      ],
      "role": "symbol",
      "title": "gradientClipMin",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcoptimizerdescriptor/gradientclipmin"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizerDescriptor/gradientClippingType": {
      "abstract": [
        {
          "text": "The type of clipping the system applies to the gradient.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gradientClippingType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCGradientClippingType",
          "text": "MLCGradientClippingType"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizerDescriptor/gradientClippingType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gradientClippingType"
        }
      ],
      "role": "symbol",
      "title": "gradientClippingType",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcoptimizerdescriptor/gradientclippingtype"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizerDescriptor/gradientRescale": {
      "abstract": [
        {
          "text": "The rescale value the optimizer applies to gradients during updates.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gradientRescale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizerDescriptor/gradientRescale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gradientRescale"
        }
      ],
      "role": "symbol",
      "title": "gradientRescale",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcoptimizerdescriptor/gradientrescale"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizerDescriptor/learningRate": {
      "abstract": [
        {
          "text": "The learning rate.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "learningRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizerDescriptor/learningRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "learningRate"
        }
      ],
      "role": "symbol",
      "title": "learningRate",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcoptimizerdescriptor/learningrate"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizerDescriptor/maximumClippingNorm": {
      "abstract": [
        {
          "text": "The maximum clipping value.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumClippingNorm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizerDescriptor/maximumClippingNorm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maximumClippingNorm"
        }
      ],
      "role": "symbol",
      "title": "maximumClippingNorm",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcoptimizerdescriptor/maximumclippingnorm"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizerDescriptor/regularizationScale": {
      "abstract": [
        {
          "text": "The regularization scale.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "regularizationScale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizerDescriptor/regularizationScale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "regularizationScale"
        }
      ],
      "role": "symbol",
      "title": "regularizationScale",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcoptimizerdescriptor/regularizationscale"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizerDescriptor/regularizationType": {
      "abstract": [
        {
          "text": "The regularization type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "regularizationType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCRegularizationType",
          "text": "MLCRegularizationType"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizerDescriptor/regularizationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "regularizationType"
        }
      ],
      "role": "symbol",
      "title": "regularizationType",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcoptimizerdescriptor/regularizationtype"
    },
    "doc://com.externally.resolved.symbol/s:Sf": {
      "abstract": [
        {
          "text": "A single-precision, floating-point value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sf",
      "kind": "symbol",
      "role": "symbol",
      "title": "Float",
      "type": "topic",
      "url": "/documentation/Swift/Float"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-an-Optimizer-Descriptor",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizerDescriptor/learningRate",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizerDescriptor/gradientRescale",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizerDescriptor/appliesGradientClipping",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizerDescriptor/gradientClipMax",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizerDescriptor/regularizationScale",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizerDescriptor/regularizationType",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizerDescriptor/gradientClippingType",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCGradientClippingType",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizerDescriptor/maximumClippingNorm",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizerDescriptor/customGlobalNorm"
      ],
      "title": "Inspecting an Optimizer Descriptor"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.3",
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "gradientClipMin"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gradientClipMin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mlcompute/documentation/MLCompute",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizerDescriptor"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Inspecting-an-Optimizer-Descriptor",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizerDescriptor/learningRate",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizerDescriptor/gradientRescale",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizerDescriptor/appliesGradientClipping",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizerDescriptor/gradientClipMax",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizerDescriptor/regularizationScale",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizerDescriptor/regularizationType",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizerDescriptor/gradientClippingType",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCGradientClippingType",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizerDescriptor/maximumClippingNorm",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizerDescriptor/customGlobalNorm"
              ],
              "title": "Inspecting an Optimizer Descriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:f",
                    "text": "float"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "gradientClipMin"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizerDescriptor~1gradientClipMax/title",
          "value": "gradientClipMax"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizerDescriptor~1gradientClipMax/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gradientClipMax"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizerDescriptor~1gradientRescale/title",
          "value": "gradientRescale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizerDescriptor~1gradientRescale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gradientRescale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizerDescriptor~1appliesGradientClipping/title",
          "value": "appliesGradientClipping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizerDescriptor~1appliesGradientClipping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "appliesGradientClipping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizerDescriptor~1regularizationScale/title",
          "value": "regularizationScale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizerDescriptor~1regularizationScale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "regularizationScale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizerDescriptor~1gradientClippingType/title",
          "value": "gradientClippingType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizerDescriptor~1gradientClippingType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gradientClippingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizerDescriptor~1customGlobalNorm/title",
          "value": "customGlobalNorm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizerDescriptor~1customGlobalNorm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "customGlobalNorm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizerDescriptor~1regularizationType/title",
          "value": "regularizationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizerDescriptor~1regularizationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "regularizationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizerDescriptor~1learningRate/title",
          "value": "learningRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizerDescriptor~1learningRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "learningRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCGradientClippingType/title",
          "value": "MLCGradientClippingType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCGradientClippingType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCGradientClippingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCGradientClippingType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCGradientClippingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizerDescriptor~1gradientClipMin/title",
          "value": "gradientClipMin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizerDescriptor~1gradientClipMin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gradientClipMin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizerDescriptor~1maximumClippingNorm/title",
          "value": "maximumClippingNorm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizerDescriptor~1maximumClippingNorm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maximumClippingNorm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizerDescriptor/title",
          "value": "MLCOptimizerDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizerDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCOptimizerDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizerDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCOptimizerDescriptor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mlcompute/mlcoptimizerdescriptor/gradientclipmin"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mlcompute/mlcoptimizerdescriptor/gradientclipmin"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
