{
  "abstract": [
    {
      "text": "Creates a new lodging reservation with the provided information.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INLodgingReservation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.sirikit/documentation/Intents/INLodgingReservation/initWithItemReference:reservationNumber:bookingTime:reservationStatus:reservationHolderName:actions:lodgingBusinessLocation:reservationDuration:numberOfAdults:numberOfChildren:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)INLodgingReservation(im)initWithItemReference:reservationNumber:bookingTime:reservationStatus:reservationHolderName:actions:lodgingBusinessLocation:reservationDuration:numberOfAdults:numberOfChildren:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "initWithItemReference:reservationNumber:bookingTime:reservationStatus:reservationHolderName:actions:lodgingBusinessLocation:reservationDuration:numberOfAdults:numberOfChildren:"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "initWithItemReference:reservationNumber:bookingTime:reservationStatus:reservationHolderName:actions:lodgingBusinessLocation:reservationDuration:numberOfAdults:numberOfChildren:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "initWithItemReference:reservationNumber:bookingTime:reservationStatus:reservationHolderName:actions:lodgingBusinessLocation:reservationDuration:numberOfAdults:numberOfChildren:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "keyword",
              "text": "instancetype"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "initWithItemReference:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INSpeakableString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)INSpeakableString",
              "text": "INSpeakableString"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "itemReference"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "reservationNumber:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "reservationNumber"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "bookingTime:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSDate",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSDate",
              "text": "NSDate"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "bookingTime"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "reservationStatus:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INReservationStatus",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@INReservationStatus",
              "text": "INReservationStatus"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "reservationStatus"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "reservationHolderName:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "reservationHolderName"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "actions:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSArray",
              "text": "NSArray<INReservationAction *>"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "actions"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "lodgingBusinessLocation:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)CLPlacemark",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CLPlacemark",
              "text": "CLPlacemark"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "lodgingBusinessLocation"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "reservationDuration:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INDateComponentsRange",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)INDateComponentsRange",
              "text": "INDateComponentsRange"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "reservationDuration"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "numberOfAdults:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSNumber",
              "text": "NSNumber"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "numberOfAdults"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "numberOfChildren:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSNumber",
              "text": "NSNumber"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "numberOfChildren"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A unique value for the reservation item.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "itemReference"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The reservation or booking number provided by the app.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "reservationNumber"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The date and time the user made the reservation.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "bookingTime"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The current status of the reservation.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "reservationStatus"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The name of the person the reservation is under.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "reservationHolderName"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The available actions for the reservation. For example, checking in for the reservation from your phone.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "actions"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The name and location of the lodging establishment.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "lodgingBusinessLocation"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The date and time range that indicates the start and end times for the reservation.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "reservationDuration"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The number of adults staying in the lodging.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "numberOfAdults"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The number of children staying in the lodging.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "numberOfChildren"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A new ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INLodgingReservation",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object or ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " if unable to create one.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INDateComponentsRange": {
      "abstract": [
        {
          "text": "A span of time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INDateComponentsRange"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INDateComponentsRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INDateComponentsRange"
        }
      ],
      "role": "symbol",
      "title": "INDateComponentsRange",
      "type": "topic",
      "url": "/documentation/intents/indatecomponentsrange"
    },
    "doc://com.apple.sirikit/documentation/Intents/INLodgingReservation": {
      "abstract": [
        {
          "text": "The information that describes a lodging reservation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INLodgingReservation"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INLodgingReservation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INLodgingReservation"
        }
      ],
      "role": "symbol",
      "title": "INLodgingReservation",
      "type": "topic",
      "url": "/documentation/intents/inlodgingreservation"
    },
    "doc://com.apple.sirikit/documentation/Intents/INLodgingReservation/initWithItemReference:reservationNumber:bookingTime:reservationStatus:reservationHolderName:actions:URL:lodgingBusinessLocation:reservationDuration:numberOfAdults:numberOfChildren:": {
      "abstract": [
        {
          "text": "Creates a lodging reservation with the specified contents and attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithItemReference:reservationNumber:bookingTime:reservationStatus:reservationHolderName:actions:URL:lodgingBusinessLocation:reservationDuration:numberOfAdults:numberOfChildren:"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INLodgingReservation/initWithItemReference:reservationNumber:bookingTime:reservationStatus:reservationHolderName:actions:URL:lodgingBusinessLocation:reservationDuration:numberOfAdults:numberOfChildren:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithItemReference:reservationNumber:bookingTime:reservationStatus:reservationHolderName:actions:URL:lodgingBusinessLocation:reservationDuration:numberOfAdults:numberOfChildren:"
        }
      ],
      "role": "symbol",
      "title": "initWithItemReference:reservationNumber:bookingTime:reservationStatus:reservationHolderName:actions:URL:lodgingBusinessLocation:reservationDuration:numberOfAdults:numberOfChildren:",
      "type": "topic",
      "url": "/documentation/intents/inlodgingreservation/initwithitemreference:reservationnumber:bookingtime:reservationstatus:reservationholdername:actions:url:lodgingbusinesslocation:reservationduration:numberofadults:numberofchildren:"
    },
    "doc://com.apple.sirikit/documentation/Intents/INLodgingReservation/initWithItemReference:reservationNumber:bookingTime:reservationStatus:reservationHolderName:actions:lodgingBusinessLocation:reservationDuration:numberOfAdults:numberOfChildren:": {
      "abstract": [
        {
          "text": "Creates a new lodging reservation with the provided information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithItemReference:reservationNumber:bookingTime:reservationStatus:reservationHolderName:actions:lodgingBusinessLocation:reservationDuration:numberOfAdults:numberOfChildren:"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INLodgingReservation/initWithItemReference:reservationNumber:bookingTime:reservationStatus:reservationHolderName:actions:lodgingBusinessLocation:reservationDuration:numberOfAdults:numberOfChildren:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithItemReference:reservationNumber:bookingTime:reservationStatus:reservationHolderName:actions:lodgingBusinessLocation:reservationDuration:numberOfAdults:numberOfChildren:"
        }
      ],
      "role": "symbol",
      "title": "initWithItemReference:reservationNumber:bookingTime:reservationStatus:reservationHolderName:actions:lodgingBusinessLocation:reservationDuration:numberOfAdults:numberOfChildren:",
      "type": "topic",
      "url": "/documentation/intents/inlodgingreservation/initwithitemreference:reservationnumber:bookingtime:reservationstatus:reservationholdername:actions:lodgingbusinesslocation:reservationduration:numberofadults:numberofchildren:"
    },
    "doc://com.apple.sirikit/documentation/Intents/INReservationStatus": {
      "abstract": [
        {
          "text": "Constants that describe the current status of the reservation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INReservationStatus"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INReservationStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INReservationStatus"
        }
      ],
      "role": "symbol",
      "title": "INReservationStatus",
      "type": "topic",
      "url": "/documentation/intents/inreservationstatus"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSpeakableString": {
      "abstract": [
        {
          "text": "A custom phrase to be resolved by an Intents extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSpeakableString"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSpeakableString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSpeakableString"
        }
      ],
      "role": "symbol",
      "title": "INSpeakableString",
      "type": "topic",
      "url": "/documentation/intents/inspeakablestring"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)CLPlacemark": {
      "abstract": [
        {
          "text": "A user-friendly description of a geographic coordinate, often containing the name of the place, its address, and other relevant information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLPlacemark"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)CLPlacemark",
      "kind": "symbol",
      "role": "symbol",
      "title": "CLPlacemark",
      "type": "topic",
      "url": "/documentation/CoreLocation/CLPlacemark"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSDate": {
      "abstract": [
        {
          "text": "A representation of a specific point in time, for use when you need reference semantics or other Foundation-specific behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSDate"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSDate",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSDate",
      "type": "topic",
      "url": "/documentation/foundation/nsdate"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber": {
      "abstract": [
        {
          "text": "An object wrapper for primitive scalar numeric values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNumber",
      "type": "topic",
      "url": "/documentation/foundation/nsnumber"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-Lodging-Reservation",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INLodgingReservation/initWithItemReference:reservationNumber:bookingTime:reservationStatus:reservationHolderName:actions:URL:lodgingBusinessLocation:reservationDuration:numberOfAdults:numberOfChildren:"
      ],
      "title": "Creating a Lodging Reservation"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INLodgingReservation/title",
          "value": "INLodgingReservation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INLodgingReservation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INLodgingReservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INLodgingReservation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INLodgingReservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDateComponentsRange/title",
          "value": "INDateComponentsRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDateComponentsRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INDateComponentsRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDateComponentsRange/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INDateComponentsRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSDate/abstract",
          "value": [
            {
              "text": "A representation of a specific point in time, independent of any calendar or time zone.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)CLPlacemark/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CLPlacemark"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INReservationStatus/title",
          "value": "INReservationStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INReservationStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INReservationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INReservationStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INReservationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSpeakableString/title",
          "value": "INSpeakableString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSpeakableString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSpeakableString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSpeakableString/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSpeakableString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inlodgingreservation/initwithitemreference:reservationnumber:bookingtime:reservationstatus:reservationholdername:actions:lodgingbusinesslocation:reservationduration:numberofadults:numberofchildren:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
