{
  "abstract": [
    {
      "text": "The number of adults staying at the lodging location.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INLodgingReservation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INLodgingReservation/numberOfAdults-6fsnq"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "Intents",
    "externalID": "s:So20INLodgingReservationC7IntentsE14numberOfAdultsSiSgvp",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "numberOfAdults"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "numberOfAdults"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@nonobjc"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "final"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "numberOfAdults"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INLodgingReservation": {
      "abstract": [
        {
          "text": "The information that describes a lodging reservation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INLodgingReservation"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INLodgingReservation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INLodgingReservation"
        }
      ],
      "role": "symbol",
      "title": "INLodgingReservation",
      "type": "topic",
      "url": "/documentation/intents/inlodgingreservation"
    },
    "doc://com.apple.sirikit/documentation/Intents/INLodgingReservation/lodgingBusinessLocation": {
      "abstract": [
        {
          "text": "The name and location of the lodging establishment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lodgingBusinessLocation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLPlacemark",
          "text": "CLPlacemark"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INLodgingReservation/lodgingBusinessLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lodgingBusinessLocation"
        }
      ],
      "role": "symbol",
      "title": "lodgingBusinessLocation",
      "type": "topic",
      "url": "/documentation/intents/inlodgingreservation/lodgingbusinesslocation"
    },
    "doc://com.apple.sirikit/documentation/Intents/INLodgingReservation/numberOfAdults-6fsnq": {
      "abstract": [
        {
          "text": "The number of adults staying at the lodging location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numberOfAdults"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INLodgingReservation/numberOfAdults-6fsnq",
      "kind": "symbol",
      "role": "symbol",
      "title": "numberOfAdults",
      "type": "topic",
      "url": "/documentation/intents/inlodgingreservation/numberofadults-6fsnq"
    },
    "doc://com.apple.sirikit/documentation/Intents/INLodgingReservation/numberOfChildren-1dm3g": {
      "abstract": [
        {
          "text": "The number of children staying at the lodging location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numberOfChildren"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INLodgingReservation/numberOfChildren-1dm3g",
      "kind": "symbol",
      "role": "symbol",
      "title": "numberOfChildren",
      "type": "topic",
      "url": "/documentation/intents/inlodgingreservation/numberofchildren-1dm3g"
    },
    "doc://com.apple.sirikit/documentation/Intents/INLodgingReservation/reservationDuration": {
      "abstract": [
        {
          "text": "The date and time range that indicates the beginning and end of the reservation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reservationDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INDateComponentsRange",
          "text": "INDateComponentsRange"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INLodgingReservation/reservationDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reservationDuration"
        }
      ],
      "role": "symbol",
      "title": "reservationDuration",
      "type": "topic",
      "url": "/documentation/intents/inlodgingreservation/reservationduration"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-Lodging-Reservation-Information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INLodgingReservation/lodgingBusinessLocation",
        "doc://com.apple.sirikit/documentation/Intents/INLodgingReservation/reservationDuration",
        "doc://com.apple.sirikit/documentation/Intents/INLodgingReservation/numberOfChildren-1dm3g"
      ],
      "title": "Getting the Lodging Reservation Information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INLodgingReservation~1lodgingBusinessLocation/title",
          "value": "lodgingBusinessLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INLodgingReservation~1lodgingBusinessLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lodgingBusinessLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INLodgingReservation~1reservationDuration/title",
          "value": "reservationDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INLodgingReservation~1reservationDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reservationDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INLodgingReservation/title",
          "value": "INLodgingReservation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INLodgingReservation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INLodgingReservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INLodgingReservation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INLodgingReservation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inlodgingreservation/numberofadults-6fsnq"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
