{
  "abstract": [
    {
      "text": "The system interrupts the audio session due to a disconnection of an audio route.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfaudio/documentation/AVFAudio",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/InterruptionReason"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/InterruptionReason/routeDisconnected"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AVAudioSessionInterruptionReason@AVAudioSessionInterruptionReasonRouteDisconnected",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "routeDisconnected"
      }
    ],
    "modules": [
      {
        "name": "AVFAudio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVAudioSessionInterruptionReasonRouteDisconnected"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "AVAudioSession.InterruptionReason.routeDisconnected"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "routeDisconnected"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfaudio/documentation/AVFAudio": {
      "abstract": [
        {
          "text": "Play, record, and process audio; configure your app’s system audio behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFAudio",
      "type": "topic",
      "url": "/documentation/avfaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession": {
      "abstract": [
        {
          "text": "An object that communicates to the system how you intend to use audio in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioSession"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSession"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/InterruptionReason": {
      "abstract": [
        {
          "text": "Constants that define the reasons for an audio session interruption.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "InterruptionReason"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/InterruptionReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "InterruptionReason"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.InterruptionReason",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/interruptionreason"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/InterruptionReason/appWasSuspended": {
      "abstract": [
        {
          "text": "The system suspends the app and interrupts the audio session.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appWasSuspended"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/InterruptionReason/appWasSuspended",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionInterruptionReasonAppWasSuspended"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.InterruptionReason.appWasSuspended",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/interruptionreason/appwassuspended"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/InterruptionReason/builtInMicMuted": {
      "abstract": [
        {
          "text": "The system interrupts the audio session when the device mutes the built-in microphone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "builtInMicMuted"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/InterruptionReason/builtInMicMuted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionInterruptionReasonBuiltInMicMuted"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.InterruptionReason.builtInMicMuted",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/interruptionreason/builtinmicmuted"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/InterruptionReason/default": {
      "abstract": [
        {
          "text": "The system interrupts this audio session when it activates another.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/InterruptionReason/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionInterruptionReasonDefault"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.InterruptionReason.default",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/interruptionreason/default"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/InterruptionReason/routeDisconnected": {
      "abstract": [
        {
          "text": "The system interrupts the audio session due to a disconnection of an audio route.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "routeDisconnected"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/InterruptionReason/routeDisconnected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionInterruptionReasonRouteDisconnected"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.InterruptionReason.routeDisconnected",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/interruptionreason/routedisconnected"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/InterruptionReason/sceneWasBackgrounded": {
      "abstract": [
        {
          "text": "The system backgrounds the scene and interrupts the audio session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sceneWasBackgrounded"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/InterruptionReason/sceneWasBackgrounded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionInterruptionReasonSceneWasBackgrounded"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.InterruptionReason.sceneWasBackgrounded",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/interruptionreason/scenewasbackgrounded"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Interruption-Reasons",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/InterruptionReason/default",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/InterruptionReason/builtInMicMuted",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/InterruptionReason/appWasSuspended",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/InterruptionReason/sceneWasBackgrounded"
      ],
      "title": "Interruption Reasons"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVAudioSessionInterruptionReasonRouteDisconnected"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionInterruptionReasonRouteDisconnected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfaudio/documentation/AVFAudio",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/InterruptionReason"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Interruption-Reasons",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/InterruptionReason/default",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/InterruptionReason/builtInMicMuted",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/InterruptionReason/appWasSuspended",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/InterruptionReason/sceneWasBackgrounded"
              ],
              "title": "Interruption Reasons"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "AVAudioSessionInterruptionReasonRouteDisconnected"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1InterruptionReason~1default/title",
          "value": "AVAudioSessionInterruptionReasonDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1InterruptionReason~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionInterruptionReasonDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1InterruptionReason~1routeDisconnected/title",
          "value": "AVAudioSessionInterruptionReasonRouteDisconnected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1InterruptionReason~1routeDisconnected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionInterruptionReasonRouteDisconnected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1InterruptionReason/title",
          "value": "AVAudioSessionInterruptionReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1InterruptionReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionInterruptionReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1InterruptionReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionInterruptionReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1InterruptionReason~1builtInMicMuted/title",
          "value": "AVAudioSessionInterruptionReasonBuiltInMicMuted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1InterruptionReason~1builtInMicMuted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionInterruptionReasonBuiltInMicMuted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/title",
          "value": "AVAudioSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1InterruptionReason~1appWasSuspended/title",
          "value": "AVAudioSessionInterruptionReasonAppWasSuspended"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1InterruptionReason~1appWasSuspended/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionInterruptionReasonAppWasSuspended"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1InterruptionReason~1sceneWasBackgrounded/title",
          "value": "AVAudioSessionInterruptionReasonSceneWasBackgrounded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1InterruptionReason~1sceneWasBackgrounded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionInterruptionReasonSceneWasBackgrounded"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfaudio/avaudiosession/interruptionreason/routedisconnected"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfaudio/avaudiosession/interruptionreason/routedisconnected"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
