{
  "abstract": [
    {
      "text": "The function can only read its argument data.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLBindingAccess"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.metal/documentation/Metal/MTLBindingAccess/MTLArgumentAccessReadOnly"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLBindingAccess@MTLArgumentAccessReadOnly",
    "fragments": [
      {
        "kind": "identifier",
        "text": "MTLArgumentAccessReadOnly"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLArgumentAccessReadOnly"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.0",
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.0",
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.0",
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.0",
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "symbolKind": "case",
    "title": "MTLArgumentAccessReadOnly"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "MTLArgumentAccessReadOnly"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBindingAccess": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLBindingAccess"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBindingAccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBindingAccess"
        }
      ],
      "role": "symbol",
      "title": "MTLBindingAccess",
      "type": "topic",
      "url": "/documentation/metal/mtlbindingaccess"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBindingAccess/MTLArgumentAccessReadOnly": {
      "abstract": [
        {
          "text": "The function can only read its argument data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MTLArgumentAccessReadOnly"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBindingAccess/MTLArgumentAccessReadOnly",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTLArgumentAccessReadOnly",
      "type": "topic",
      "url": "/documentation/metal/mtlbindingaccess/mtlargumentaccessreadonly"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBindingAccess/MTLArgumentAccessReadWrite": {
      "abstract": [
        {
          "text": "The function can either read or write its argument data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MTLArgumentAccessReadWrite"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBindingAccess/MTLArgumentAccessReadWrite",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTLArgumentAccessReadWrite",
      "type": "topic",
      "url": "/documentation/metal/mtlbindingaccess/mtlargumentaccessreadwrite"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBindingAccess/MTLArgumentAccessWriteOnly": {
      "abstract": [
        {
          "text": "The function can only write its argument data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MTLArgumentAccessWriteOnly"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBindingAccess/MTLArgumentAccessWriteOnly",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTLArgumentAccessWriteOnly",
      "type": "topic",
      "url": "/documentation/metal/mtlbindingaccess/mtlargumentaccesswriteonly"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Specifying-Access-Options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLBindingAccess/MTLArgumentAccessWriteOnly",
        "doc://com.apple.metal/documentation/Metal/MTLBindingAccess/MTLArgumentAccessReadWrite"
      ],
      "title": "Specifying Access Options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBindingAccess/title",
          "value": "MTLBindingAccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBindingAccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBindingAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBindingAccess/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBindingAccess"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlbindingaccess/mtlargumentaccessreadonly"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
