{
  "abstract": [
    {
      "text": "Constants that indicate whether the output is ready to receive capture requests.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/CaptureReadiness-swift.enum"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AVFoundation",
    "externalID": "c:@E@AVCapturePhotoOutputCaptureReadiness",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CaptureReadiness"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CaptureReadiness"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "AVCapturePhotoOutput.CaptureReadiness"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CaptureReadiness"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput": {
      "abstract": [
        {
          "text": "A capture output for still image, Live Photos, and other photography workflows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCapturePhotoOutput"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCapturePhotoOutput"
        }
      ],
      "role": "symbol",
      "title": "AVCapturePhotoOutput",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotooutput"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/CaptureReadiness-swift.enum": {
      "abstract": [
        {
          "text": "Constants that indicate whether the output is ready to receive capture requests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CaptureReadiness"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/CaptureReadiness-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CaptureReadiness"
        }
      ],
      "role": "symbol",
      "title": "AVCapturePhotoOutput.CaptureReadiness",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotooutput/capturereadiness-swift.enum"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/CaptureReadiness-swift.enum/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/CaptureReadiness-swift.enum/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotooutput/capturereadiness-swift.enum/init(rawvalue:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/CaptureReadiness-swift.enum/notReadyMomentarily": {
      "abstract": [
        {
          "text": "Indicates that the output isn’t ready to receive requests, but may be ready shortly.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notReadyMomentarily"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/CaptureReadiness-swift.enum/notReadyMomentarily",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCapturePhotoOutputCaptureReadinessNotReadyMomentarily"
        }
      ],
      "role": "symbol",
      "title": "AVCapturePhotoOutput.CaptureReadiness.notReadyMomentarily",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotooutput/capturereadiness-swift.enum/notreadymomentarily"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/CaptureReadiness-swift.enum/notReadyWaitingForCapture": {
      "abstract": [
        {
          "text": "Indicates that the output isn’t ready to receive requests for a longer duration because it’s busy capturing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notReadyWaitingForCapture"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/CaptureReadiness-swift.enum/notReadyWaitingForCapture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCapturePhotoOutputCaptureReadinessNotReadyWaitingForCapture"
        }
      ],
      "role": "symbol",
      "title": "AVCapturePhotoOutput.CaptureReadiness.notReadyWaitingForCapture",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotooutput/capturereadiness-swift.enum/notreadywaitingforcapture"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/CaptureReadiness-swift.enum/notReadyWaitingForProcessing": {
      "abstract": [
        {
          "text": "Indicates that the output isn’t ready to receive requests for a longer duration because it’s busy processing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notReadyWaitingForProcessing"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/CaptureReadiness-swift.enum/notReadyWaitingForProcessing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCapturePhotoOutputCaptureReadinessNotReadyWaitingForProcessing"
        }
      ],
      "role": "symbol",
      "title": "AVCapturePhotoOutput.CaptureReadiness.notReadyWaitingForProcessing",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotooutput/capturereadiness-swift.enum/notreadywaitingforprocessing"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/CaptureReadiness-swift.enum/ready": {
      "abstract": [
        {
          "text": "Indicates that the output is ready to receive new requests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ready"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/CaptureReadiness-swift.enum/ready",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCapturePhotoOutputCaptureReadinessReady"
        }
      ],
      "role": "symbol",
      "title": "AVCapturePhotoOutput.CaptureReadiness.ready",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotooutput/capturereadiness-swift.enum/ready"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/CaptureReadiness-swift.enum/sessionNotRunning": {
      "abstract": [
        {
          "text": "Indicates that the session isn’t running and the output isn’t ready to receive requests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sessionNotRunning"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/CaptureReadiness-swift.enum/sessionNotRunning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCapturePhotoOutputCaptureReadinessSessionNotRunning"
        }
      ],
      "role": "symbol",
      "title": "AVCapturePhotoOutput.CaptureReadiness.sessionNotRunning",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotooutput/capturereadiness-swift.enum/sessionnotrunning"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/captureReadiness-swift.property": {
      "abstract": [
        {
          "text": "A value that specifies whether the photo output is ready to respond to new capture requests in a timely manner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "captureReadiness"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCapturePhotoOutput",
          "text": "AVCapturePhotoOutput"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVCapturePhotoOutputCaptureReadiness",
          "text": "CaptureReadiness"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/captureReadiness-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "captureReadiness"
        }
      ],
      "role": "symbol",
      "title": "captureReadiness",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotooutput/capturereadiness-swift.property"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/isAutoDeferredPhotoDeliveryEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates the enabled state of automatic deferred photo delivery.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAutoDeferredPhotoDeliveryEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/isAutoDeferredPhotoDeliveryEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "autoDeferredPhotoDeliveryEnabled"
        }
      ],
      "role": "symbol",
      "title": "isAutoDeferredPhotoDeliveryEnabled",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotooutput/isautodeferredphotodeliveryenabled"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/isAutoDeferredPhotoDeliverySupported": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the photo output supports deferred photo delivery.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAutoDeferredPhotoDeliverySupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/isAutoDeferredPhotoDeliverySupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "autoDeferredPhotoDeliverySupported"
        }
      ],
      "role": "symbol",
      "title": "isAutoDeferredPhotoDeliverySupported",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotooutput/isautodeferredphotodeliverysupported"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/isFastCapturePrioritizationEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the output enables fast capture prioritization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isFastCapturePrioritizationEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/isFastCapturePrioritizationEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fastCapturePrioritizationEnabled"
        }
      ],
      "role": "symbol",
      "title": "isFastCapturePrioritizationEnabled",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotooutput/isfastcaptureprioritizationenabled"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/isFastCapturePrioritizationSupported": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the photo output supports fast capture prioritization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isFastCapturePrioritizationSupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/isFastCapturePrioritizationSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fastCapturePrioritizationSupported"
        }
      ],
      "role": "symbol",
      "title": "isFastCapturePrioritizationSupported",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotooutput/isfastcaptureprioritizationsupported"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/isResponsiveCaptureEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the photo output configuration enables responsive capture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isResponsiveCaptureEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/isResponsiveCaptureEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "responsiveCaptureEnabled"
        }
      ],
      "role": "symbol",
      "title": "isResponsiveCaptureEnabled",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotooutput/isresponsivecaptureenabled"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/isResponsiveCaptureSupported": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the photo output supports responsive capture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isResponsiveCaptureSupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/isResponsiveCaptureSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "responsiveCaptureSupported"
        }
      ],
      "role": "symbol",
      "title": "isResponsiveCaptureSupported",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotooutput/isresponsivecapturesupported"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/isZeroShutterLagEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the photo output configuration enables zero shutter lag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isZeroShutterLagEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/isZeroShutterLagEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "zeroShutterLagEnabled"
        }
      ],
      "role": "symbol",
      "title": "isZeroShutterLagEnabled",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotooutput/iszeroshutterlagenabled"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/isZeroShutterLagSupported": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the photo output supports zero shutter lag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isZeroShutterLagSupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/isZeroShutterLagSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "zeroShutterLagSupported"
        }
      ],
      "role": "symbol",
      "title": "isZeroShutterLagSupported",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotooutput/iszeroshutterlagsupported"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-Responsive-Capture",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/captureReadiness-swift.property",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/isAutoDeferredPhotoDeliveryEnabled",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/isAutoDeferredPhotoDeliverySupported",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/isFastCapturePrioritizationSupported",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/isFastCapturePrioritizationEnabled",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/isResponsiveCaptureSupported",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/isResponsiveCaptureEnabled",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/isZeroShutterLagSupported",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/isZeroShutterLagEnabled"
      ],
      "title": "Managing Responsive Capture"
    }
  ],
  "topicSections": [
    {
      "anchor": "Readiness-states",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/CaptureReadiness-swift.enum/sessionNotRunning",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/CaptureReadiness-swift.enum/notReadyMomentarily",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/CaptureReadiness-swift.enum/notReadyWaitingForCapture",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/CaptureReadiness-swift.enum/notReadyWaitingForProcessing",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/CaptureReadiness-swift.enum/ready"
      ],
      "title": "Readiness states"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/CaptureReadiness-swift.enum/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVCapturePhotoOutputCaptureReadiness"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCapturePhotoOutputCaptureReadiness"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCapturePhotoOutputCaptureReadiness"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Readiness-states",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/CaptureReadiness-swift.enum/sessionNotRunning",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/CaptureReadiness-swift.enum/notReadyMomentarily",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/CaptureReadiness-swift.enum/notReadyWaitingForCapture",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/CaptureReadiness-swift.enum/notReadyWaitingForProcessing",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/CaptureReadiness-swift.enum/ready"
              ],
              "title": "Readiness states"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-Responsive-Capture",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/captureReadiness-swift.property",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/isAutoDeferredPhotoDeliveryEnabled",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/isAutoDeferredPhotoDeliverySupported",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/isFastCapturePrioritizationSupported",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/isFastCapturePrioritizationEnabled",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/isResponsiveCaptureSupported",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/isResponsiveCaptureEnabled",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/isZeroShutterLagSupported",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/isZeroShutterLagEnabled"
              ],
              "title": "Managing Responsive Capture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVCapturePhotoOutputCaptureReadiness"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1CaptureReadiness-swift.enum~1ready/title",
          "value": "AVCapturePhotoOutputCaptureReadinessReady"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1CaptureReadiness-swift.enum~1ready/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCapturePhotoOutputCaptureReadinessReady"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1isZeroShutterLagEnabled/title",
          "value": "zeroShutterLagEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1isZeroShutterLagEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "zeroShutterLagEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1captureReadiness-swift.property/title",
          "value": "captureReadiness"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1captureReadiness-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "captureReadiness"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1isAutoDeferredPhotoDeliveryEnabled/title",
          "value": "autoDeferredPhotoDeliveryEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1isAutoDeferredPhotoDeliveryEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "autoDeferredPhotoDeliveryEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1isFastCapturePrioritizationSupported/title",
          "value": "fastCapturePrioritizationSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1isFastCapturePrioritizationSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fastCapturePrioritizationSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1isResponsiveCaptureSupported/title",
          "value": "responsiveCaptureSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1isResponsiveCaptureSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "responsiveCaptureSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1isAutoDeferredPhotoDeliverySupported/title",
          "value": "autoDeferredPhotoDeliverySupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1isAutoDeferredPhotoDeliverySupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "autoDeferredPhotoDeliverySupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1CaptureReadiness-swift.enum~1notReadyWaitingForCapture/title",
          "value": "AVCapturePhotoOutputCaptureReadinessNotReadyWaitingForCapture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1CaptureReadiness-swift.enum~1notReadyWaitingForCapture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCapturePhotoOutputCaptureReadinessNotReadyWaitingForCapture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1isZeroShutterLagSupported/title",
          "value": "zeroShutterLagSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1isZeroShutterLagSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "zeroShutterLagSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput/title",
          "value": "AVCapturePhotoOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCapturePhotoOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCapturePhotoOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1CaptureReadiness-swift.enum~1notReadyWaitingForProcessing/title",
          "value": "AVCapturePhotoOutputCaptureReadinessNotReadyWaitingForProcessing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1CaptureReadiness-swift.enum~1notReadyWaitingForProcessing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCapturePhotoOutputCaptureReadinessNotReadyWaitingForProcessing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1CaptureReadiness-swift.enum/title",
          "value": "AVCapturePhotoOutputCaptureReadiness"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1CaptureReadiness-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCapturePhotoOutputCaptureReadiness"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1CaptureReadiness-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCapturePhotoOutputCaptureReadiness"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1CaptureReadiness-swift.enum~1sessionNotRunning/title",
          "value": "AVCapturePhotoOutputCaptureReadinessSessionNotRunning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1CaptureReadiness-swift.enum~1sessionNotRunning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCapturePhotoOutputCaptureReadinessSessionNotRunning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1CaptureReadiness-swift.enum~1notReadyMomentarily/title",
          "value": "AVCapturePhotoOutputCaptureReadinessNotReadyMomentarily"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1CaptureReadiness-swift.enum~1notReadyMomentarily/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCapturePhotoOutputCaptureReadinessNotReadyMomentarily"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1isFastCapturePrioritizationEnabled/title",
          "value": "fastCapturePrioritizationEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1isFastCapturePrioritizationEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fastCapturePrioritizationEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1isResponsiveCaptureEnabled/title",
          "value": "responsiveCaptureEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1isResponsiveCaptureEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "responsiveCaptureEnabled"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avcapturephotooutput/capturereadiness-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avcapturephotooutput/capturereadiness-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
