{
  "abstract": [
    {
      "text": "The version of PencilKit necessary to use the ink type.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pencilkit/documentation/PencilKit",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKInkingTool-swift.struct",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKInkingTool-swift.struct/InkType-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pencilkit/documentation/PencilKit/PKInkingTool-swift.struct/InkType-swift.enum/requiredContentVersion"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:9PencilKit12PKInkingToolV7InkTypeO22requiredContentVersionSo09PKContentI0Vvp",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "requiredContentVersion"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@PKContentVersion",
        "text": "PKContentVersion"
      }
    ],
    "modules": [
      {
        "name": "PencilKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "requiredContentVersion"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "requiredContentVersion"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKContentVersion",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@PKContentVersion",
              "text": "PKContentVersion"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit": {
      "abstract": [
        {
          "text": "Capture touch and Apple Pencil input as a drawing, and display that content from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PencilKit",
      "type": "topic",
      "url": "/documentation/pencilkit"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKContentVersion": {
      "abstract": [
        {
          "text": "Constants that represent versions of PencilKit for backward compatibility.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKContentVersion"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKContentVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKContentVersion"
        }
      ],
      "role": "symbol",
      "title": "PKContentVersion",
      "type": "topic",
      "url": "/documentation/pencilkit/pkcontentversion"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKInkingTool-swift.struct": {
      "abstract": [
        {
          "text": "A structure that defines the drawing characteristics (width, color, pen style) to use when drawing lines on a canvas view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKInkingTool"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKInkingTool-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKInkingTool"
        }
      ],
      "role": "symbol",
      "title": "PKInkingTool",
      "type": "topic",
      "url": "/documentation/pencilkit/pkinkingtool-swift.struct"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKInkingTool-swift.struct/InkType-swift.enum": {
      "abstract": [
        {
          "text": "The type that defines the shape of stroked lines.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "InkType"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKInkingTool-swift.struct/InkType-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "InkType"
        }
      ],
      "role": "symbol",
      "title": "PKInkingTool.InkType",
      "type": "topic",
      "url": "/documentation/pencilkit/pkinkingtool-swift.struct/inktype-swift.enum"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKInkingTool-swift.struct/InkType-swift.enum/requiredContentVersion": {
      "abstract": [
        {
          "text": "The version of PencilKit necessary to use the ink type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requiredContentVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKContentVersion",
          "text": "PKContentVersion"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKInkingTool-swift.struct/InkType-swift.enum/requiredContentVersion",
      "kind": "symbol",
      "role": "symbol",
      "title": "requiredContentVersion",
      "type": "topic",
      "url": "/documentation/pencilkit/pkinkingtool-swift.struct/inktype-swift.enum/requiredcontentversion"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKContentVersion/title",
          "value": "PKContentVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKContentVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKContentVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKContentVersion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKContentVersion"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pencilkit/pkinkingtool-swift.struct/inktype-swift.enum/requiredcontentversion"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
