{
  "abstract": [
    {
      "text": "An element that represents the user’s home address.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/address"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PKIdentityElement(cpy)addressElement",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "address"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)PKIdentityElement",
        "text": "PKIdentityElement"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "addressElement"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "address"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "address"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)PKIdentityElement",
              "text": "PKIdentityElement"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement": {
      "abstract": [
        {
          "text": "An object that represents the elements an app requests from identity documents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKIdentityElement"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKIdentityElement"
        }
      ],
      "role": "symbol",
      "title": "PKIdentityElement",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityelement"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/address": {
      "abstract": [
        {
          "text": "An element that represents the user’s home address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "address"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKIdentityElement",
          "text": "PKIdentityElement"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/address",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addressElement"
        }
      ],
      "role": "symbol",
      "title": "address",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityelement/address"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/dateOfBirth": {
      "abstract": [
        {
          "text": "An element that represents the user’s date of birth.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dateOfBirth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKIdentityElement",
          "text": "PKIdentityElement"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/dateOfBirth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dateOfBirthElement"
        }
      ],
      "role": "symbol",
      "title": "dateOfBirth",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityelement/dateofbirth"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/documentExpirationDate": {
      "abstract": [
        {
          "text": "An element that represents the expiration date of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentExpirationDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKIdentityElement",
          "text": "PKIdentityElement"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/documentExpirationDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentExpirationDateElement"
        }
      ],
      "role": "symbol",
      "title": "documentExpirationDate",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityelement/documentexpirationdate"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/documentIssueDate": {
      "abstract": [
        {
          "text": "An element that represents the issue date of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentIssueDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKIdentityElement",
          "text": "PKIdentityElement"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/documentIssueDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentIssueDateElement"
        }
      ],
      "role": "symbol",
      "title": "documentIssueDate",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityelement/documentissuedate"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/documentNumber": {
      "abstract": [
        {
          "text": "An element that represents the document’s number, as the issuing authority defines.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKIdentityElement",
          "text": "PKIdentityElement"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/documentNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentNumberElement"
        }
      ],
      "role": "symbol",
      "title": "documentNumber",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityelement/documentnumber"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/drivingPrivileges": {
      "abstract": [
        {
          "text": "An element that represents the user’s driving privileges.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "drivingPrivileges"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKIdentityElement",
          "text": "PKIdentityElement"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/drivingPrivileges",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "drivingPrivilegesElement"
        }
      ],
      "role": "symbol",
      "title": "drivingPrivileges",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityelement/drivingprivileges"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/familyName": {
      "abstract": [
        {
          "text": "An element that represents the user’s family name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "familyName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKIdentityElement",
          "text": "PKIdentityElement"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/familyName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "familyNameElement"
        }
      ],
      "role": "symbol",
      "title": "familyName",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityelement/familyname"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/givenName": {
      "abstract": [
        {
          "text": "An element that represents the user’s given name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "givenName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKIdentityElement",
          "text": "PKIdentityElement"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/givenName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "givenNameElement"
        }
      ],
      "role": "symbol",
      "title": "givenName",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityelement/givenname"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/issuingAuthority": {
      "abstract": [
        {
          "text": "An element that represents the user’s issuing authority.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "issuingAuthority"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKIdentityElement",
          "text": "PKIdentityElement"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/issuingAuthority",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "issuingAuthorityElement"
        }
      ],
      "role": "symbol",
      "title": "issuingAuthority",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityelement/issuingauthority"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/portrait": {
      "abstract": [
        {
          "text": "An element that represents the user’s photo.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "portrait"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKIdentityElement",
          "text": "PKIdentityElement"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/portrait",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "portraitElement"
        }
      ],
      "role": "symbol",
      "title": "portrait",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityelement/portrait"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-identity-elements",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/dateOfBirth",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/documentIssueDate",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/documentExpirationDate",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/documentNumber",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/drivingPrivileges",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/familyName",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/givenName",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/issuingAuthority",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/portrait"
      ],
      "title": "Getting identity elements"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "addressElement"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "addressElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit",
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-identity-elements",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/dateOfBirth",
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/documentIssueDate",
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/documentExpirationDate",
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/documentNumber",
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/drivingPrivileges",
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/familyName",
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/givenName",
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/issuingAuthority",
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement/portrait"
              ],
              "title": "Getting identity elements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "class"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityElement",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)PKIdentityElement",
                    "text": "PKIdentityElement"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "addressElement"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement~1portrait/title",
          "value": "portraitElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement~1portrait/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "portraitElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement~1documentIssueDate/title",
          "value": "documentIssueDateElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement~1documentIssueDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "documentIssueDateElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement~1givenName/title",
          "value": "givenNameElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement~1givenName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "givenNameElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement~1address/title",
          "value": "addressElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement~1address/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "addressElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement/title",
          "value": "PKIdentityElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement~1documentNumber/title",
          "value": "documentNumberElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement~1documentNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "documentNumberElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement~1dateOfBirth/title",
          "value": "dateOfBirthElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement~1dateOfBirth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dateOfBirthElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement~1drivingPrivileges/title",
          "value": "drivingPrivilegesElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement~1drivingPrivileges/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "drivingPrivilegesElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement~1familyName/title",
          "value": "familyNameElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement~1familyName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "familyNameElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement~1issuingAuthority/title",
          "value": "issuingAuthorityElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement~1issuingAuthority/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "issuingAuthorityElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement~1documentExpirationDate/title",
          "value": "documentExpirationDateElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityElement~1documentExpirationDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "documentExpirationDateElement"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkidentityelement/address"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pkidentityelement/address"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
