{
  "abstract": [
    {
      "text": "A button that allows for a configurable number of stepped pressure levels and provides tactile feedback as the user reaches each step.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSButton",
        "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/multiLevelAccelerator"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSButtonType@NSButtonTypeMultiLevelAccelerator",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "multiLevelAccelerator"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSButtonTypeMultiLevelAccelerator"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10.3",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSButton.ButtonType.multiLevelAccelerator"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "multiLevelAccelerator"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/maxAcceleratorLevel",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to configure the number of pressure levels. For other types of buttons, this property value defaults to ",
              "type": "text"
            },
            {
              "code": "1",
              "type": "codeVoice"
            },
            {
              "text": ". For multilevel accelerator buttons, this property value defaults to ",
              "type": "text"
            },
            {
              "code": "2",
              "type": "codeVoice"
            },
            {
              "text": ", and you can set it to a value between ",
              "type": "text"
            },
            {
              "code": "1",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "5",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Like a normal accelerator button, the button sends an action when the user first clicks it. If ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSControl/isContinuous",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", while the user clicks the button, it then sends actions at repeating intervals that are based on pressure. If ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSControl/isContinuous",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/false",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", the button sends actions as the user presses harder and reaches different levels of pressure. The button sends a final action when the user releases the button.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The value of a multilevel accelerator button is distinct from its state. The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSControl/integerValue",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " of a multilevel button is ",
              "type": "text"
            },
            {
              "code": "0",
              "type": "codeVoice"
            },
            {
              "text": " when the user doesn’t click it or ",
              "type": "text"
            },
            {
              "code": "1",
              "type": "codeVoice"
            },
            {
              "text": " through ",
              "type": "text"
            },
            {
              "code": "5",
              "type": "codeVoice"
            },
            {
              "text": " when the user clicks it, depending on the level of pressure. If you set the value of a multilevel accelerator button explicitly, the button doesn’t send an action until pressure reaches the level you specify.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "On a system that doesn’t support pressure sensitivity, a multilevel accelerator button’s value is always ",
              "type": "text"
            },
            {
              "code": "1",
              "type": "codeVoice"
            },
            {
              "text": " when the user clicks it.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This option corresponds to the Multi Level Accelerator type in Interface Builder’s Attributes inspector.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton": {
      "abstract": [
        {
          "text": "A control that defines an area on the screen that a user clicks to trigger an action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSButton"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSButton"
        }
      ],
      "role": "symbol",
      "title": "NSButton",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType": {
      "abstract": [
        {
          "text": "Button types that you can specify using ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButtonCell/setButtonType(_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ButtonType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ButtonType"
        }
      ],
      "role": "symbol",
      "title": "NSButton.ButtonType",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/buttontype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/accelerator": {
      "abstract": [
        {
          "text": "A button that sends repeating actions as pressure changes occur.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accelerator"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/accelerator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSButtonTypeAccelerator"
        }
      ],
      "role": "symbol",
      "title": "NSButton.ButtonType.accelerator",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/buttontype/accelerator"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/momentaryChange": {
      "abstract": [
        {
          "text": "A button that displays its alternate content when clicked and returns to its normal content when the user releases it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "momentaryChange"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/momentaryChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSButtonTypeMomentaryChange"
        }
      ],
      "role": "symbol",
      "title": "NSButton.ButtonType.momentaryChange",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/buttontype/momentarychange"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/momentaryLight": {
      "abstract": [
        {
          "text": "A button that displays a highlight when the user clicks it and returns to its normal state when the user releases it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "momentaryLight"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/momentaryLight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSButtonTypeMomentaryLight"
        }
      ],
      "role": "symbol",
      "title": "NSButton.ButtonType.momentaryLight",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/buttontype/momentarylight"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/momentaryPushIn": {
      "abstract": [
        {
          "text": "A button that illuminates when the user clicks it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "momentaryPushIn"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/momentaryPushIn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSButtonTypeMomentaryPushIn"
        }
      ],
      "role": "symbol",
      "title": "NSButton.ButtonType.momentaryPushIn",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/buttontype/momentarypushin"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/multiLevelAccelerator": {
      "abstract": [
        {
          "text": "A button that allows for a configurable number of stepped pressure levels and provides tactile feedback as the user reaches each step.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "multiLevelAccelerator"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/multiLevelAccelerator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSButtonTypeMultiLevelAccelerator"
        }
      ],
      "role": "symbol",
      "title": "NSButton.ButtonType.multiLevelAccelerator",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/buttontype/multilevelaccelerator"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/onOff": {
      "abstract": [
        {
          "text": "A button that switches between a normal and emphasized bezel on each click.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "onOff"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/onOff",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSButtonTypeOnOff"
        }
      ],
      "role": "symbol",
      "title": "NSButton.ButtonType.onOff",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/buttontype/onoff"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/pushOnPushOff": {
      "abstract": [
        {
          "text": "A button that switches between on and off states with each click.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pushOnPushOff"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/pushOnPushOff",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSButtonTypePushOnPushOff"
        }
      ],
      "role": "symbol",
      "title": "NSButton.ButtonType.pushOnPushOff",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/buttontype/pushonpushoff"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/radio": {
      "abstract": [
        {
          "text": "A button that displays a single selected value from group of possible choices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "radio"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/radio",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSButtonTypeRadio"
        }
      ],
      "role": "symbol",
      "title": "NSButton.ButtonType.radio",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/buttontype/radio"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/switch": {
      "abstract": [
        {
          "text": "A standard checkbox button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`switch`"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/switch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSButtonTypeSwitch"
        }
      ],
      "role": "symbol",
      "title": "NSButton.ButtonType.switch",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/buttontype/switch"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/toggle": {
      "abstract": [
        {
          "text": "A button that switches between its normal and alternate content on each click.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "toggle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/toggle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSButtonTypeToggle"
        }
      ],
      "role": "symbol",
      "title": "NSButton.ButtonType.toggle",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/buttontype/toggle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/maxAcceleratorLevel": {
      "abstract": [
        {
          "text": "An integer value indicating the maximum pressure level for a button of type ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMultiLevelAcceleratorButton",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maxAcceleratorLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/maxAcceleratorLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maxAcceleratorLevel"
        }
      ],
      "role": "symbol",
      "title": "maxAcceleratorLevel",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/maxacceleratorlevel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButtonCell/setButtonType(_:)": {
      "abstract": [
        {
          "text": "Sets how the button highlights while pressed and how it shows its state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setButtonType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSButton",
          "text": "NSButton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSButtonType",
          "text": "ButtonType"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButtonCell/setButtonType(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setButtonType:"
        }
      ],
      "role": "symbol",
      "title": "setButtonType(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsbuttoncell/setbuttontype(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSControl/integerValue": {
      "abstract": [
        {
          "text": "The value of the receiver’s cell as an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/objectivec/nsinteger",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "integerValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSControl/integerValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "integerValue"
        }
      ],
      "role": "symbol",
      "title": "integerValue",
      "type": "topic",
      "url": "/documentation/appkit/nscontrol/integervalue"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSControl/isContinuous": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the receiver’s cell sends its action message continuously to its target during mouse tracking.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isContinuous"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSControl/isContinuous",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "continuous"
        }
      ],
      "role": "symbol",
      "title": "isContinuous",
      "type": "topic",
      "url": "/documentation/appkit/nscontrol/iscontinuous"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMultiLevelAcceleratorButton": {
      "abstract": [
        {
          "text": "A multilevel accelerator button is a variation of a normal accelerator button that allows for a configurable number of stepped pressure levels. As each one is reached, the user receives light tactile feedback and an action is sent.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSMultiLevelAcceleratorButton"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMultiLevelAcceleratorButton",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMultiLevelAcceleratorButton",
      "type": "topic",
      "url": "/documentation/appkit/nsmultilevelacceleratorbutton"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsinteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsinteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-Button-Behavior",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/momentaryPushIn",
        "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/momentaryLight",
        "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/momentaryChange",
        "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/pushOnPushOff",
        "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/onOff",
        "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/toggle",
        "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/switch",
        "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/radio",
        "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/accelerator"
      ],
      "title": "Configuring Button Behavior"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10.3",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSButtonTypeMultiLevelAccelerator"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButtonTypeMultiLevelAccelerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-Button-Behavior",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/momentaryPushIn",
                "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/momentaryLight",
                "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/momentaryChange",
                "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/pushOnPushOff",
                "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/onOff",
                "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/toggle",
                "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/switch",
                "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/radio",
                "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/accelerator"
              ],
              "title": "Configuring Button Behavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSButtonTypeMultiLevelAccelerator"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1isContinuous/title",
          "value": "continuous"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1isContinuous/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "continuous"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType~1multiLevelAccelerator/title",
          "value": "NSButtonTypeMultiLevelAccelerator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType~1multiLevelAccelerator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButtonTypeMultiLevelAccelerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType/title",
          "value": "NSButtonType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButtonType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButtonType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButtonCell~1setButtonType(_:)/title",
          "value": "setButtonType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButtonCell~1setButtonType(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setButtonType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType~1accelerator/title",
          "value": "NSButtonTypeAccelerator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType~1accelerator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButtonTypeAccelerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType~1switch/title",
          "value": "NSButtonTypeSwitch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType~1switch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButtonTypeSwitch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType~1radio/title",
          "value": "NSButtonTypeRadio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType~1radio/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButtonTypeRadio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType~1toggle/title",
          "value": "NSButtonTypeToggle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType~1toggle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButtonTypeToggle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType~1momentaryLight/title",
          "value": "NSButtonTypeMomentaryLight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType~1momentaryLight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButtonTypeMomentaryLight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType~1pushOnPushOff/title",
          "value": "NSButtonTypePushOnPushOff"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType~1pushOnPushOff/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButtonTypePushOnPushOff"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1integerValue/title",
          "value": "integerValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1integerValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "integerValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType~1momentaryPushIn/title",
          "value": "NSButtonTypeMomentaryPushIn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType~1momentaryPushIn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButtonTypeMomentaryPushIn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType~1momentaryChange/title",
          "value": "NSButtonTypeMomentaryChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType~1momentaryChange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButtonTypeMomentaryChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType~1onOff/title",
          "value": "NSButtonTypeOnOff"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType~1onOff/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButtonTypeOnOff"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1maxAcceleratorLevel/title",
          "value": "maxAcceleratorLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1maxAcceleratorLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maxAcceleratorLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton/title",
          "value": "NSButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButton"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsbutton/buttontype/multilevelaccelerator"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsbutton/buttontype/multilevelaccelerator"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
