{
  "abstract": [
    {
      "text": "A state that indicates that the scene is running in the foreground and is currently receiving events.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIScene",
        "doc://com.apple.uikit/documentation/UIKit/UIScene/ActivationState-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIScene/ActivationState-swift.enum/foregroundActive"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UISceneActivationState@UISceneActivationStateForegroundActive",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "foregroundActive"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UISceneActivationStateForegroundActive"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UIScene.ActivationState.foregroundActive"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "foregroundActive"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The interface for an active scene is onscreen and visible to the user.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScene": {
      "abstract": [
        {
          "text": "An object that represents one instance of your app’s user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIScene"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScene",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIScene"
        }
      ],
      "role": "symbol",
      "title": "UIScene",
      "type": "topic",
      "url": "/documentation/uikit/uiscene"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScene/ActivationState-swift.enum": {
      "abstract": [
        {
          "text": "Constants that indicate the foreground or background execution state of your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ActivationState"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScene/ActivationState-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ActivationState"
        }
      ],
      "role": "symbol",
      "title": "UIScene.ActivationState",
      "type": "topic",
      "url": "/documentation/uikit/uiscene/activationstate-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScene/ActivationState-swift.enum/background": {
      "abstract": [
        {
          "text": "A state that indicates that the scene is running in the background and is not onscreen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "background"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScene/ActivationState-swift.enum/background",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISceneActivationStateBackground"
        }
      ],
      "role": "symbol",
      "title": "UIScene.ActivationState.background",
      "type": "topic",
      "url": "/documentation/uikit/uiscene/activationstate-swift.enum/background"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScene/ActivationState-swift.enum/foregroundActive": {
      "abstract": [
        {
          "text": "A state that indicates that the scene is running in the foreground and is currently receiving events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "foregroundActive"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScene/ActivationState-swift.enum/foregroundActive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISceneActivationStateForegroundActive"
        }
      ],
      "role": "symbol",
      "title": "UIScene.ActivationState.foregroundActive",
      "type": "topic",
      "url": "/documentation/uikit/uiscene/activationstate-swift.enum/foregroundactive"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScene/ActivationState-swift.enum/foregroundInactive": {
      "abstract": [
        {
          "text": "A state that indicates that the scene is running in the foreground but is not receiving events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "foregroundInactive"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScene/ActivationState-swift.enum/foregroundInactive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISceneActivationStateForegroundInactive"
        }
      ],
      "role": "symbol",
      "title": "UIScene.ActivationState.foregroundInactive",
      "type": "topic",
      "url": "/documentation/uikit/uiscene/activationstate-swift.enum/foregroundinactive"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScene/ActivationState-swift.enum/unattached": {
      "abstract": [
        {
          "text": "A state that indicates that the scene is not currently connected to your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unattached"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScene/ActivationState-swift.enum/unattached",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISceneActivationStateUnattached"
        }
      ],
      "role": "symbol",
      "title": "UIScene.ActivationState.unattached",
      "type": "topic",
      "url": "/documentation/uikit/uiscene/activationstate-swift.enum/unattached"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Scene-States",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIScene/ActivationState-swift.enum/unattached",
        "doc://com.apple.uikit/documentation/UIKit/UIScene/ActivationState-swift.enum/foregroundInactive",
        "doc://com.apple.uikit/documentation/UIKit/UIScene/ActivationState-swift.enum/background"
      ],
      "title": "Scene States"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UISceneActivationStateForegroundActive"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISceneActivationStateForegroundActive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIScene/ActivationState-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Scene-States",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIScene/ActivationState-swift.enum/unattached",
                "doc://com.apple.uikit/documentation/UIKit/UIScene/ActivationState-swift.enum/foregroundInactive",
                "doc://com.apple.uikit/documentation/UIKit/UIScene/ActivationState-swift.enum/background"
              ],
              "title": "Scene States"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UISceneActivationStateForegroundActive"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScene~1ActivationState-swift.enum~1foregroundActive/title",
          "value": "UISceneActivationStateForegroundActive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScene~1ActivationState-swift.enum~1foregroundActive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISceneActivationStateForegroundActive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScene~1ActivationState-swift.enum/title",
          "value": "UISceneActivationState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScene~1ActivationState-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISceneActivationState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScene~1ActivationState-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISceneActivationState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScene~1ActivationState-swift.enum~1background/title",
          "value": "UISceneActivationStateBackground"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScene~1ActivationState-swift.enum~1background/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISceneActivationStateBackground"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScene/title",
          "value": "UIScene"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScene/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScene"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScene/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScene"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScene~1ActivationState-swift.enum~1unattached/title",
          "value": "UISceneActivationStateUnattached"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScene~1ActivationState-swift.enum~1unattached/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISceneActivationStateUnattached"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScene~1ActivationState-swift.enum~1foregroundInactive/title",
          "value": "UISceneActivationStateForegroundInactive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScene~1ActivationState-swift.enum~1foregroundInactive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISceneActivationStateForegroundInactive"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiscene/activationstate-swift.enum/foregroundactive"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiscene/activationstate-swift.enum/foregroundactive"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
