{
  "abstract": [
    {
      "text": "An option to request a layout that supports foveated rendering.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.compositorservices/documentation/CompositorServices",
        "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer",
        "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Capabilities",
        "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Capabilities/SupportedLayoutsOptions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Capabilities/SupportedLayoutsOptions/foveationEnabled"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So27CP_OBJECT_cp_layer_rendererC18CompositorServicesE12CapabilitiesV23SupportedLayoutsOptionsV16foveationEnabledAGvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "foveationEnabled"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CP_OBJECT_cp_layer_renderer",
        "text": "LayerRenderer"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:So27CP_OBJECT_cp_layer_rendererC18CompositorServicesE12CapabilitiesV",
        "text": "Capabilities"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:So27CP_OBJECT_cp_layer_rendererC18CompositorServicesE12CapabilitiesV23SupportedLayoutsOptionsV",
        "text": "SupportedLayoutsOptions"
      }
    ],
    "modules": [
      {
        "name": "Compositor Services"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "foveationEnabled"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "foveationEnabled"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CP_OBJECT_cp_layer_renderer",
              "text": "LayerRenderer"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Capabilities",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:So27CP_OBJECT_cp_layer_rendererC18CompositorServicesE12CapabilitiesV",
              "text": "Capabilities"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Capabilities/SupportedLayoutsOptions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:So27CP_OBJECT_cp_layer_rendererC18CompositorServicesE12CapabilitiesV23SupportedLayoutsOptionsV",
              "text": "SupportedLayoutsOptions"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.compositorservices/documentation/CompositorServices": {
      "abstract": [
        {
          "text": "Take control of the drawing environment and render your own content using Metal.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices",
      "kind": "symbol",
      "role": "collection",
      "title": "Compositor Services",
      "type": "topic",
      "url": "/documentation/compositorservices"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer": {
      "abstract": [
        {
          "text": "A type that provides the Metal types and timing information you need to draw your content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LayerRenderer"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LayerRenderer"
        }
      ],
      "role": "symbol",
      "title": "LayerRenderer",
      "type": "topic",
      "url": "/documentation/compositorservices/layerrenderer"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Capabilities": {
      "abstract": [
        {
          "text": "The color formats, depth formats, and features that you can use to configure your rendering engine.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Capabilities"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Capabilities",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Capabilities"
        }
      ],
      "role": "symbol",
      "title": "LayerRenderer.Capabilities",
      "type": "topic",
      "url": "/documentation/compositorservices/layerrenderer/capabilities"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Capabilities/SupportedLayoutsOptions": {
      "abstract": [
        {
          "text": "Options you can use to filter the supported layouts for a layer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SupportedLayoutsOptions"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Capabilities/SupportedLayoutsOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SupportedLayoutsOptions"
        }
      ],
      "role": "symbol",
      "title": "LayerRenderer.Capabilities.SupportedLayoutsOptions",
      "type": "topic",
      "url": "/documentation/compositorservices/layerrenderer/capabilities/supportedlayoutsoptions"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Capabilities/SupportedLayoutsOptions/foveationEnabled": {
      "abstract": [
        {
          "text": "An option to request a layout that supports foveated rendering.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "foveationEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CP_OBJECT_cp_layer_renderer",
          "text": "LayerRenderer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So27CP_OBJECT_cp_layer_rendererC18CompositorServicesE12CapabilitiesV",
          "text": "Capabilities"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So27CP_OBJECT_cp_layer_rendererC18CompositorServicesE12CapabilitiesV23SupportedLayoutsOptionsV",
          "text": "SupportedLayoutsOptions"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/LayerRenderer/Capabilities/SupportedLayoutsOptions/foveationEnabled",
      "kind": "symbol",
      "role": "symbol",
      "title": "foveationEnabled",
      "type": "topic",
      "url": "/documentation/compositorservices/layerrenderer/capabilities/supportedlayoutsoptions/foveationenabled"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerRenderer/title",
          "value": "CP_OBJECT_cp_layer_renderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerRenderer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CP_OBJECT_cp_layer_renderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1LayerRenderer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CP_OBJECT_cp_layer_renderer"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/compositorservices/layerrenderer/capabilities/supportedlayoutsoptions/foveationenabled"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
