{
  "abstract": [
    {
      "text": "The option to compute intermediate frames using the cubic scheme while ignoring the timing properties of the animation.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIView",
        "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/calculationModeCubicPaced"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIViewKeyframeAnimationOptions@UIViewKeyframeAnimationOptionCalculationModeCubicPaced",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "calculationModeCubicPaced"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UIView",
        "text": "UIView"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@UIViewKeyframeAnimationOptions",
        "text": "KeyframeAnimationOptions"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIViewKeyframeAnimationOptionCalculationModeCubicPaced"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "calculationModeCubicPaced"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "calculationModeCubicPaced"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIView",
              "text": "UIView"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@UIViewKeyframeAnimationOptions",
              "text": "KeyframeAnimationOptions"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Instead, timing parameters are calculated implicitly to give the animation a constant velocity.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView": {
      "abstract": [
        {
          "text": "An object that manages the content for a rectangular area on the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIView"
        }
      ],
      "role": "symbol",
      "title": "UIView",
      "type": "topic",
      "url": "/documentation/uikit/uiview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions": {
      "abstract": [
        {
          "text": "Options for configuring keyframe-based animations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "KeyframeAnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "KeyframeAnimationOptions"
        }
      ],
      "role": "symbol",
      "title": "UIView.KeyframeAnimationOptions",
      "type": "topic",
      "url": "/documentation/uikit/uiview/keyframeanimationoptions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/allowUserInteraction": {
      "abstract": [
        {
          "text": "The option that allows a person to interact with views while they’re being animated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowUserInteraction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewKeyframeAnimationOptions",
          "text": "KeyframeAnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/allowUserInteraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewKeyframeAnimationOptionAllowUserInteraction"
        }
      ],
      "role": "symbol",
      "title": "allowUserInteraction",
      "type": "topic",
      "url": "/documentation/uikit/uiview/keyframeanimationoptions/allowuserinteraction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/autoreverse": {
      "abstract": [
        {
          "text": "The option to run an animation backwards and forwards.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "autoreverse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewKeyframeAnimationOptions",
          "text": "KeyframeAnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/autoreverse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewKeyframeAnimationOptionAutoreverse"
        }
      ],
      "role": "symbol",
      "title": "autoreverse",
      "type": "topic",
      "url": "/documentation/uikit/uiview/keyframeanimationoptions/autoreverse"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/beginFromCurrentState": {
      "abstract": [
        {
          "text": "The option to start an animation from the current setting associated with an already in-flight animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beginFromCurrentState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewKeyframeAnimationOptions",
          "text": "KeyframeAnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/beginFromCurrentState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewKeyframeAnimationOptionBeginFromCurrentState"
        }
      ],
      "role": "symbol",
      "title": "beginFromCurrentState",
      "type": "topic",
      "url": "/documentation/uikit/uiview/keyframeanimationoptions/beginfromcurrentstate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/calculationModeCubic": {
      "abstract": [
        {
          "text": "The option to compute intermediate frames using a default Catmull-Rom spline that passes through the keyframe values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "calculationModeCubic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewKeyframeAnimationOptions",
          "text": "KeyframeAnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/calculationModeCubic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewKeyframeAnimationOptionCalculationModeCubic"
        }
      ],
      "role": "symbol",
      "title": "calculationModeCubic",
      "type": "topic",
      "url": "/documentation/uikit/uiview/keyframeanimationoptions/calculationmodecubic"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/calculationModeCubicPaced": {
      "abstract": [
        {
          "text": "The option to compute intermediate frames using the cubic scheme while ignoring the timing properties of the animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "calculationModeCubicPaced"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewKeyframeAnimationOptions",
          "text": "KeyframeAnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/calculationModeCubicPaced",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewKeyframeAnimationOptionCalculationModeCubicPaced"
        }
      ],
      "role": "symbol",
      "title": "calculationModeCubicPaced",
      "type": "topic",
      "url": "/documentation/uikit/uiview/keyframeanimationoptions/calculationmodecubicpaced"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/calculationModeDiscrete": {
      "abstract": [
        {
          "text": "The option to not interpolate between keyframe values, but rather to jump directly to each new keyframe value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "calculationModeDiscrete"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewKeyframeAnimationOptions",
          "text": "KeyframeAnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/calculationModeDiscrete",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewKeyframeAnimationOptionCalculationModeDiscrete"
        }
      ],
      "role": "symbol",
      "title": "calculationModeDiscrete",
      "type": "topic",
      "url": "/documentation/uikit/uiview/keyframeanimationoptions/calculationmodediscrete"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/calculationModeLinear": {
      "abstract": [
        {
          "text": "The option to use a simple linear calculation when interpolating between keyframe values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "calculationModeLinear"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewKeyframeAnimationOptions",
          "text": "KeyframeAnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/calculationModeLinear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewKeyframeAnimationOptionCalculationModeLinear"
        }
      ],
      "role": "symbol",
      "title": "calculationModeLinear",
      "type": "topic",
      "url": "/documentation/uikit/uiview/keyframeanimationoptions/calculationmodelinear"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/calculationModePaced": {
      "abstract": [
        {
          "text": "The option to compute intermediate keyframe values using a simple pacing algorithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "calculationModePaced"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewKeyframeAnimationOptions",
          "text": "KeyframeAnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/calculationModePaced",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewKeyframeAnimationOptionCalculationModePaced"
        }
      ],
      "role": "symbol",
      "title": "calculationModePaced",
      "type": "topic",
      "url": "/documentation/uikit/uiview/keyframeanimationoptions/calculationmodepaced"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/layoutSubviews": {
      "abstract": [
        {
          "text": "The option to lay out subviews at commit time so that they’re animated along with their parent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layoutSubviews"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewKeyframeAnimationOptions",
          "text": "KeyframeAnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/layoutSubviews",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewKeyframeAnimationOptionLayoutSubviews"
        }
      ],
      "role": "symbol",
      "title": "layoutSubviews",
      "type": "topic",
      "url": "/documentation/uikit/uiview/keyframeanimationoptions/layoutsubviews"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/overrideInheritedDuration": {
      "abstract": [
        {
          "text": "The option to force an animation to use the original duration value specified when the animation was submitted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "overrideInheritedDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewKeyframeAnimationOptions",
          "text": "KeyframeAnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/overrideInheritedDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewKeyframeAnimationOptionOverrideInheritedDuration"
        }
      ],
      "role": "symbol",
      "title": "overrideInheritedDuration",
      "type": "topic",
      "url": "/documentation/uikit/uiview/keyframeanimationoptions/overrideinheritedduration"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/overrideInheritedOptions": {
      "abstract": [
        {
          "text": "The option to not inherit the animation type or any options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "overrideInheritedOptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewKeyframeAnimationOptions",
          "text": "KeyframeAnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/overrideInheritedOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewKeyframeAnimationOptionOverrideInheritedOptions"
        }
      ],
      "role": "symbol",
      "title": "overrideInheritedOptions",
      "type": "topic",
      "url": "/documentation/uikit/uiview/keyframeanimationoptions/overrideinheritedoptions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/repeat": {
      "abstract": [
        {
          "text": "The option to repeat an animation indefinitely.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`repeat`"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewKeyframeAnimationOptions",
          "text": "KeyframeAnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/repeat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewKeyframeAnimationOptionRepeat"
        }
      ],
      "role": "symbol",
      "title": "repeat",
      "type": "topic",
      "url": "/documentation/uikit/uiview/keyframeanimationoptions/repeat"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/layoutSubviews",
        "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/allowUserInteraction",
        "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/beginFromCurrentState",
        "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/repeat",
        "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/autoreverse",
        "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/overrideInheritedDuration",
        "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/overrideInheritedOptions",
        "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/calculationModeLinear",
        "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/calculationModeDiscrete",
        "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/calculationModePaced",
        "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/calculationModeCubic"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIViewKeyframeAnimationOptionCalculationModeCubicPaced"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewKeyframeAnimationOptionCalculationModeCubicPaced"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/layoutSubviews",
                "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/allowUserInteraction",
                "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/beginFromCurrentState",
                "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/repeat",
                "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/autoreverse",
                "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/overrideInheritedDuration",
                "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/overrideInheritedOptions",
                "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/calculationModeLinear",
                "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/calculationModeDiscrete",
                "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/calculationModePaced",
                "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/calculationModeCubic"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UIViewKeyframeAnimationOptionCalculationModeCubicPaced"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/title",
          "value": "UIView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions~1autoreverse/title",
          "value": "UIViewKeyframeAnimationOptionAutoreverse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions~1autoreverse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewKeyframeAnimationOptionAutoreverse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions~1overrideInheritedDuration/title",
          "value": "UIViewKeyframeAnimationOptionOverrideInheritedDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions~1overrideInheritedDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewKeyframeAnimationOptionOverrideInheritedDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions~1layoutSubviews/title",
          "value": "UIViewKeyframeAnimationOptionLayoutSubviews"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions~1layoutSubviews/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewKeyframeAnimationOptionLayoutSubviews"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions~1calculationModeCubic/title",
          "value": "UIViewKeyframeAnimationOptionCalculationModeCubic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions~1calculationModeCubic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewKeyframeAnimationOptionCalculationModeCubic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions~1allowUserInteraction/title",
          "value": "UIViewKeyframeAnimationOptionAllowUserInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions~1allowUserInteraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewKeyframeAnimationOptionAllowUserInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions~1calculationModeDiscrete/title",
          "value": "UIViewKeyframeAnimationOptionCalculationModeDiscrete"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions~1calculationModeDiscrete/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewKeyframeAnimationOptionCalculationModeDiscrete"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions/title",
          "value": "UIViewKeyframeAnimationOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewKeyframeAnimationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewKeyframeAnimationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions~1overrideInheritedOptions/title",
          "value": "UIViewKeyframeAnimationOptionOverrideInheritedOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions~1overrideInheritedOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewKeyframeAnimationOptionOverrideInheritedOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions~1calculationModeLinear/title",
          "value": "UIViewKeyframeAnimationOptionCalculationModeLinear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions~1calculationModeLinear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewKeyframeAnimationOptionCalculationModeLinear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions~1calculationModeCubicPaced/title",
          "value": "UIViewKeyframeAnimationOptionCalculationModeCubicPaced"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions~1calculationModeCubicPaced/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewKeyframeAnimationOptionCalculationModeCubicPaced"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions~1repeat/title",
          "value": "UIViewKeyframeAnimationOptionRepeat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions~1repeat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewKeyframeAnimationOptionRepeat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions~1calculationModePaced/title",
          "value": "UIViewKeyframeAnimationOptionCalculationModePaced"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions~1calculationModePaced/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewKeyframeAnimationOptionCalculationModePaced"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions~1beginFromCurrentState/title",
          "value": "UIViewKeyframeAnimationOptionBeginFromCurrentState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions~1beginFromCurrentState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewKeyframeAnimationOptionBeginFromCurrentState"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiview/keyframeanimationoptions/calculationmodecubicpaced"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiview/keyframeanimationoptions/calculationmodecubicpaced"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
