{
  "abstract": [
    {
      "text": "A transmission request that indicates a user pressed a button on a hands-free device.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pushtotalk/documentation/PushToTalk",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelTransmitRequestSource"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelTransmitRequestSource/handsfreeButton"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PTChannelTransmitRequestSource@PTChannelTransmitRequestSourceHandsfreeButton",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "handsfreeButton"
      }
    ],
    "modules": [
      {
        "name": "Push to Talk"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PTChannelTransmitRequestSourceHandsfreeButton"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "PTChannelTransmitRequestSource.handsfreeButton"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "handsfreeButton"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk": {
      "abstract": [
        {
          "text": "Display the system user interface for your app’s Push to Talk services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk",
      "kind": "symbol",
      "role": "collection",
      "title": "Push to Talk",
      "type": "topic",
      "url": "/documentation/pushtotalk"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelTransmitRequestSource": {
      "abstract": [
        {
          "text": "Identifies the type that indicates the transmission request source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PTChannelTransmitRequestSource"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelTransmitRequestSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTChannelTransmitRequestSource"
        }
      ],
      "role": "symbol",
      "title": "PTChannelTransmitRequestSource",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptchanneltransmitrequestsource"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelTransmitRequestSource/developerRequest": {
      "abstract": [
        {
          "text": "A transmission request that indicates the app calls the begin transmission method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "developerRequest"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelTransmitRequestSource/developerRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTChannelTransmitRequestSourceDeveloperRequest"
        }
      ],
      "role": "symbol",
      "title": "PTChannelTransmitRequestSource.developerRequest",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptchanneltransmitrequestsource/developerrequest"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelTransmitRequestSource/handsfreeButton": {
      "abstract": [
        {
          "text": "A transmission request that indicates a user pressed a button on a hands-free device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handsfreeButton"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelTransmitRequestSource/handsfreeButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTChannelTransmitRequestSourceHandsfreeButton"
        }
      ],
      "role": "symbol",
      "title": "PTChannelTransmitRequestSource.handsfreeButton",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptchanneltransmitrequestsource/handsfreebutton"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelTransmitRequestSource/unknown": {
      "abstract": [
        {
          "text": "A transmission request that indicates an unknown reason.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelTransmitRequestSource/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTChannelTransmitRequestSourceUnknown"
        }
      ],
      "role": "symbol",
      "title": "PTChannelTransmitRequestSource.unknown",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptchanneltransmitrequestsource/unknown"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelTransmitRequestSource/userRequest": {
      "abstract": [
        {
          "text": "A transmission request that indicates the user pressed the transmit button in the system user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userRequest"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelTransmitRequestSource/userRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTChannelTransmitRequestSourceUserRequest"
        }
      ],
      "role": "symbol",
      "title": "PTChannelTransmitRequestSource.userRequest",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptchanneltransmitrequestsource/userrequest"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Transmission-sources",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelTransmitRequestSource/userRequest",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelTransmitRequestSource/developerRequest",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelTransmitRequestSource/unknown"
      ],
      "title": "Transmission sources"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PTChannelTransmitRequestSourceHandsfreeButton"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelTransmitRequestSourceHandsfreeButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.pushtotalk/documentation/PushToTalk",
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelTransmitRequestSource"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Transmission-sources",
              "generated": true,
              "identifiers": [
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelTransmitRequestSource/userRequest",
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelTransmitRequestSource/developerRequest",
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelTransmitRequestSource/unknown"
              ],
              "title": "Transmission sources"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "PTChannelTransmitRequestSourceHandsfreeButton"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelTransmitRequestSource~1handsfreeButton/title",
          "value": "PTChannelTransmitRequestSourceHandsfreeButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelTransmitRequestSource~1handsfreeButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelTransmitRequestSourceHandsfreeButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelTransmitRequestSource~1developerRequest/title",
          "value": "PTChannelTransmitRequestSourceDeveloperRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelTransmitRequestSource~1developerRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelTransmitRequestSourceDeveloperRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelTransmitRequestSource~1unknown/title",
          "value": "PTChannelTransmitRequestSourceUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelTransmitRequestSource~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelTransmitRequestSourceUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelTransmitRequestSource~1userRequest/title",
          "value": "PTChannelTransmitRequestSourceUserRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelTransmitRequestSource~1userRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelTransmitRequestSourceUserRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelTransmitRequestSource/title",
          "value": "PTChannelTransmitRequestSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelTransmitRequestSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelTransmitRequestSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelTransmitRequestSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelTransmitRequestSource"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pushtotalk/ptchanneltransmitrequestsource/handsfreebutton"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/pushtotalk/ptchanneltransmitrequestsource/handsfreebutton"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
