{
  "abstract": [
    {
      "text": "Configure devices that connect a mouse and keyboard to the guest system.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.virtualization/documentation/Virtualization"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.virtualization/documentation/Virtualization/keyboards-and-pointing-devices"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Virtualization"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Keyboards and pointing devices"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Configure a keyboard and a pointing device to allow people to interact with macOS or Linux VMs.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.virtualization/documentation/Virtualization": {
      "abstract": [
        {
          "text": "Create virtual machines and run macOS and Linux-based operating systems.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization",
      "kind": "symbol",
      "role": "collection",
      "title": "Virtualization",
      "type": "topic",
      "url": "/documentation/virtualization"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZKeyboardConfiguration": {
      "abstract": [
        {
          "text": "The base class for a configuring a keyboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZKeyboardConfiguration"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZKeyboardConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZKeyboardConfiguration"
        }
      ],
      "role": "symbol",
      "title": "VZKeyboardConfiguration",
      "type": "topic",
      "url": "/documentation/virtualization/vzkeyboardconfiguration"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZMacKeyboardConfiguration": {
      "abstract": [
        {
          "text": "A device that defines the configuration for a Mac keyboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZMacKeyboardConfiguration"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMacKeyboardConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZMacKeyboardConfiguration"
        }
      ],
      "role": "symbol",
      "title": "VZMacKeyboardConfiguration",
      "type": "topic",
      "url": "/documentation/virtualization/vzmackeyboardconfiguration"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZMacTrackpadConfiguration": {
      "abstract": [
        {
          "text": "The class that represents the configuration for a Mac trackpad.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZMacTrackpadConfiguration"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMacTrackpadConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZMacTrackpadConfiguration"
        }
      ],
      "role": "symbol",
      "title": "VZMacTrackpadConfiguration",
      "type": "topic",
      "url": "/documentation/virtualization/vzmactrackpadconfiguration"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZPointingDeviceConfiguration": {
      "abstract": [
        {
          "text": "The base class for a pointing device configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZPointingDeviceConfiguration"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZPointingDeviceConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZPointingDeviceConfiguration"
        }
      ],
      "role": "symbol",
      "title": "VZPointingDeviceConfiguration",
      "type": "topic",
      "url": "/documentation/virtualization/vzpointingdeviceconfiguration"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZUSBKeyboardConfiguration": {
      "abstract": [
        {
          "text": "A device that defines the configuration for a USB keyboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZUSBKeyboardConfiguration"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZUSBKeyboardConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZUSBKeyboardConfiguration"
        }
      ],
      "role": "symbol",
      "title": "VZUSBKeyboardConfiguration",
      "type": "topic",
      "url": "/documentation/virtualization/vzusbkeyboardconfiguration"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZUSBScreenCoordinatePointingDeviceConfiguration": {
      "abstract": [
        {
          "text": "An object that defines the configuration for a USB pointing device that reports absolute coordinates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZUSBScreenCoordinatePointingDeviceConfiguration"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZUSBScreenCoordinatePointingDeviceConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZUSBScreenCoordinatePointingDeviceConfiguration"
        }
      ],
      "role": "symbol",
      "title": "VZUSBScreenCoordinatePointingDeviceConfiguration",
      "type": "topic",
      "url": "/documentation/virtualization/vzusbscreencoordinatepointingdeviceconfiguration"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/audio": {
      "abstract": [
        {
          "text": "Configure audio devices that enable the guest operating system to perform audio playback and capture through the host’s audio devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/audio",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio",
      "type": "topic",
      "url": "/documentation/virtualization/audio"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/clipboard-sharing": {
      "abstract": [
        {
          "text": "Share the pasteboard between the host and guest system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/clipboard-sharing",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Clipboard sharing",
      "type": "topic",
      "url": "/documentation/virtualization/clipboard-sharing"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/consoles": {
      "abstract": [
        {
          "text": "Configure a device that manages multiport console communication with the guest system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/consoles",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Consoles",
      "type": "topic",
      "url": "/documentation/virtualization/consoles"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/graphics": {
      "abstract": [
        {
          "text": "Configure a device for a guest to display its UI.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/graphics",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Graphics",
      "type": "topic",
      "url": "/documentation/virtualization/graphics"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/memory": {
      "abstract": [
        {
          "text": "Configure a memory balloon device to change the allocated memory for the guest system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/memory",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Memory",
      "type": "topic",
      "url": "/documentation/virtualization/memory"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/network": {
      "abstract": [
        {
          "text": "Configure the devices that connect the guest system to the network.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/network",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/virtualization/network"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/randomization": {
      "abstract": [
        {
          "text": "Configure a device for the guest system to use to generate random numbers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/randomization",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Randomization",
      "type": "topic",
      "url": "/documentation/virtualization/randomization"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/serial-ports": {
      "abstract": [
        {
          "text": "Configure the serial devices that you use to communicate with the guest system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/serial-ports",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Serial ports",
      "type": "topic",
      "url": "/documentation/virtualization/serial-ports"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/shared-directories": {
      "abstract": [
        {
          "text": "Configure devices that share directories from the host into the guest system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/shared-directories",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Shared directories",
      "type": "topic",
      "url": "/documentation/virtualization/shared-directories"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/sockets": {
      "abstract": [
        {
          "text": "Configure a device that manages port-based communication with the guest system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/sockets",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sockets",
      "type": "topic",
      "url": "/documentation/virtualization/sockets"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/storage": {
      "abstract": [
        {
          "text": "Configure the block-storage devices that represent the disks of the guest system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/storage",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Storage",
      "type": "topic",
      "url": "/documentation/virtualization/storage"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/usb-devices": {
      "abstract": [],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/usb-devices",
      "kind": "article",
      "role": "collectionGroup",
      "title": "USB Devices",
      "type": "topic",
      "url": "/documentation/virtualization/usb-devices"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Devices",
      "generated": true,
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/audio",
        "doc://com.apple.virtualization/documentation/Virtualization/graphics",
        "doc://com.apple.virtualization/documentation/Virtualization/memory",
        "doc://com.apple.virtualization/documentation/Virtualization/network",
        "doc://com.apple.virtualization/documentation/Virtualization/randomization",
        "doc://com.apple.virtualization/documentation/Virtualization/serial-ports",
        "doc://com.apple.virtualization/documentation/Virtualization/shared-directories",
        "doc://com.apple.virtualization/documentation/Virtualization/sockets",
        "doc://com.apple.virtualization/documentation/Virtualization/storage",
        "doc://com.apple.virtualization/documentation/Virtualization/consoles",
        "doc://com.apple.virtualization/documentation/Virtualization/clipboard-sharing",
        "doc://com.apple.virtualization/documentation/Virtualization/usb-devices"
      ],
      "title": "Devices"
    }
  ],
  "topicSections": [
    {
      "anchor": "Keyboards",
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZKeyboardConfiguration",
        "doc://com.apple.virtualization/documentation/Virtualization/VZMacKeyboardConfiguration",
        "doc://com.apple.virtualization/documentation/Virtualization/VZUSBKeyboardConfiguration"
      ],
      "title": "Keyboards"
    },
    {
      "anchor": "Pointing-devices",
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZMacTrackpadConfiguration",
        "doc://com.apple.virtualization/documentation/Virtualization/VZUSBScreenCoordinatePointingDeviceConfiguration",
        "doc://com.apple.virtualization/documentation/Virtualization/VZPointingDeviceConfiguration"
      ],
      "title": "Pointing devices"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Keyboards",
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/VZKeyboardConfiguration",
                "doc://com.apple.virtualization/documentation/Virtualization/VZMacKeyboardConfiguration",
                "doc://com.apple.virtualization/documentation/Virtualization/VZUSBKeyboardConfiguration"
              ],
              "title": "Keyboards"
            },
            {
              "anchor": "Pointing-devices",
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/VZMacTrackpadConfiguration",
                "doc://com.apple.virtualization/documentation/Virtualization/VZUSBScreenCoordinatePointingDeviceConfiguration",
                "doc://com.apple.virtualization/documentation/Virtualization/VZPointingDeviceConfiguration"
              ],
              "title": "Pointing devices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Devices",
              "generated": true,
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/audio",
                "doc://com.apple.virtualization/documentation/Virtualization/graphics",
                "doc://com.apple.virtualization/documentation/Virtualization/memory",
                "doc://com.apple.virtualization/documentation/Virtualization/network",
                "doc://com.apple.virtualization/documentation/Virtualization/randomization",
                "doc://com.apple.virtualization/documentation/Virtualization/serial-ports",
                "doc://com.apple.virtualization/documentation/Virtualization/shared-directories",
                "doc://com.apple.virtualization/documentation/Virtualization/sockets",
                "doc://com.apple.virtualization/documentation/Virtualization/storage",
                "doc://com.apple.virtualization/documentation/Virtualization/consoles",
                "doc://com.apple.virtualization/documentation/Virtualization/clipboard-sharing",
                "doc://com.apple.virtualization/documentation/Virtualization/usb-devices"
              ],
              "title": "Devices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZUSBKeyboardConfiguration/title",
          "value": "VZUSBKeyboardConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZUSBKeyboardConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZUSBKeyboardConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZUSBKeyboardConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZUSBKeyboardConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacTrackpadConfiguration/title",
          "value": "VZMacTrackpadConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacTrackpadConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZMacTrackpadConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacTrackpadConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZMacTrackpadConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacKeyboardConfiguration/title",
          "value": "VZMacKeyboardConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacKeyboardConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZMacKeyboardConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacKeyboardConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZMacKeyboardConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZKeyboardConfiguration/title",
          "value": "VZKeyboardConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZKeyboardConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZKeyboardConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZKeyboardConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZKeyboardConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZUSBScreenCoordinatePointingDeviceConfiguration/title",
          "value": "VZUSBScreenCoordinatePointingDeviceConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZUSBScreenCoordinatePointingDeviceConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZUSBScreenCoordinatePointingDeviceConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZUSBScreenCoordinatePointingDeviceConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZUSBScreenCoordinatePointingDeviceConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZPointingDeviceConfiguration/title",
          "value": "VZPointingDeviceConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZPointingDeviceConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZPointingDeviceConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZPointingDeviceConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZPointingDeviceConfiguration"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/virtualization/keyboards-and-pointing-devices"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/virtualization/keyboards-and-pointing-devices"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
