{
  "abstract": [
    {
      "text": "Configure the devices that connect the guest system to the network.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.virtualization/documentation/Virtualization"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.virtualization/documentation/Virtualization/network"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Virtualization"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Network"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.virtualization/documentation/Virtualization": {
      "abstract": [
        {
          "text": "Create virtual machines and run macOS and Linux-based operating systems.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization",
      "kind": "symbol",
      "role": "collection",
      "title": "Virtualization",
      "type": "topic",
      "url": "/documentation/virtualization"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZBridgedNetworkDeviceAttachment": {
      "abstract": [
        {
          "text": "A network device that interacts directly with a physical network interface on the host computer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZBridgedNetworkDeviceAttachment"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZBridgedNetworkDeviceAttachment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZBridgedNetworkDeviceAttachment"
        }
      ],
      "role": "symbol",
      "title": "VZBridgedNetworkDeviceAttachment",
      "type": "topic",
      "url": "/documentation/virtualization/vzbridgednetworkdeviceattachment"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZBridgedNetworkInterface": {
      "abstract": [
        {
          "text": "An object that identifies the supported network interfaces of the host computer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZBridgedNetworkInterface"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZBridgedNetworkInterface",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZBridgedNetworkInterface"
        }
      ],
      "role": "symbol",
      "title": "VZBridgedNetworkInterface",
      "type": "topic",
      "url": "/documentation/virtualization/vzbridgednetworkinterface"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZFileHandleNetworkDeviceAttachment": {
      "abstract": [
        {
          "text": "A network device that transmits raw network packets and frames using a datagram socket.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZFileHandleNetworkDeviceAttachment"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZFileHandleNetworkDeviceAttachment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZFileHandleNetworkDeviceAttachment"
        }
      ],
      "role": "symbol",
      "title": "VZFileHandleNetworkDeviceAttachment",
      "type": "topic",
      "url": "/documentation/virtualization/vzfilehandlenetworkdeviceattachment"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZMACAddress": {
      "abstract": [
        {
          "text": "The media access control (MAC) address for a network interface in your virtual machine.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZMACAddress"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMACAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZMACAddress"
        }
      ],
      "role": "symbol",
      "title": "VZMACAddress",
      "type": "topic",
      "url": "/documentation/virtualization/vzmacaddress"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZNATNetworkDeviceAttachment": {
      "abstract": [
        {
          "text": "A device that routes network requests through the host computer and performs network address translation on the resulting packets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZNATNetworkDeviceAttachment"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZNATNetworkDeviceAttachment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZNATNetworkDeviceAttachment"
        }
      ],
      "role": "symbol",
      "title": "VZNATNetworkDeviceAttachment",
      "type": "topic",
      "url": "/documentation/virtualization/vznatnetworkdeviceattachment"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZNetworkDevice": {
      "abstract": [
        {
          "text": "A base class that represents a network device in a virtual machine.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZNetworkDevice"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZNetworkDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZNetworkDevice"
        }
      ],
      "role": "symbol",
      "title": "VZNetworkDevice",
      "type": "topic",
      "url": "/documentation/virtualization/vznetworkdevice"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZNetworkDeviceAttachment": {
      "abstract": [
        {
          "text": "The common behaviors for the network attachment points of your virtual machine.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZNetworkDeviceAttachment"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZNetworkDeviceAttachment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZNetworkDeviceAttachment"
        }
      ],
      "role": "symbol",
      "title": "VZNetworkDeviceAttachment",
      "type": "topic",
      "url": "/documentation/virtualization/vznetworkdeviceattachment"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZNetworkDeviceConfiguration": {
      "abstract": [
        {
          "text": "The common configuration traits for network devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZNetworkDeviceConfiguration"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZNetworkDeviceConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZNetworkDeviceConfiguration"
        }
      ],
      "role": "symbol",
      "title": "VZNetworkDeviceConfiguration",
      "type": "topic",
      "url": "/documentation/virtualization/vznetworkdeviceconfiguration"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioNetworkDeviceConfiguration": {
      "abstract": [
        {
          "text": "A configuration object that requests the creation of a network device for the guest system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZVirtioNetworkDeviceConfiguration"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioNetworkDeviceConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZVirtioNetworkDeviceConfiguration"
        }
      ],
      "role": "symbol",
      "title": "VZVirtioNetworkDeviceConfiguration",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtionetworkdeviceconfiguration"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/audio": {
      "abstract": [
        {
          "text": "Configure audio devices that enable the guest operating system to perform audio playback and capture through the host’s audio devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/audio",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio",
      "type": "topic",
      "url": "/documentation/virtualization/audio"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/clipboard-sharing": {
      "abstract": [
        {
          "text": "Share the pasteboard between the host and guest system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/clipboard-sharing",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Clipboard sharing",
      "type": "topic",
      "url": "/documentation/virtualization/clipboard-sharing"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/consoles": {
      "abstract": [
        {
          "text": "Configure a device that manages multiport console communication with the guest system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/consoles",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Consoles",
      "type": "topic",
      "url": "/documentation/virtualization/consoles"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/graphics": {
      "abstract": [
        {
          "text": "Configure a device for a guest to display its UI.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/graphics",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Graphics",
      "type": "topic",
      "url": "/documentation/virtualization/graphics"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/keyboards-and-pointing-devices": {
      "abstract": [
        {
          "text": "Configure devices that connect a mouse and keyboard to the guest system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/keyboards-and-pointing-devices",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Keyboards and pointing devices",
      "type": "topic",
      "url": "/documentation/virtualization/keyboards-and-pointing-devices"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/memory": {
      "abstract": [
        {
          "text": "Configure a memory balloon device to change the allocated memory for the guest system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/memory",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Memory",
      "type": "topic",
      "url": "/documentation/virtualization/memory"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/randomization": {
      "abstract": [
        {
          "text": "Configure a device for the guest system to use to generate random numbers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/randomization",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Randomization",
      "type": "topic",
      "url": "/documentation/virtualization/randomization"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/serial-ports": {
      "abstract": [
        {
          "text": "Configure the serial devices that you use to communicate with the guest system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/serial-ports",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Serial ports",
      "type": "topic",
      "url": "/documentation/virtualization/serial-ports"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/shared-directories": {
      "abstract": [
        {
          "text": "Configure devices that share directories from the host into the guest system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/shared-directories",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Shared directories",
      "type": "topic",
      "url": "/documentation/virtualization/shared-directories"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/sockets": {
      "abstract": [
        {
          "text": "Configure a device that manages port-based communication with the guest system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/sockets",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sockets",
      "type": "topic",
      "url": "/documentation/virtualization/sockets"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/storage": {
      "abstract": [
        {
          "text": "Configure the block-storage devices that represent the disks of the guest system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/storage",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Storage",
      "type": "topic",
      "url": "/documentation/virtualization/storage"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/usb-devices": {
      "abstract": [],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/usb-devices",
      "kind": "article",
      "role": "collectionGroup",
      "title": "USB Devices",
      "type": "topic",
      "url": "/documentation/virtualization/usb-devices"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Devices",
      "generated": true,
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/audio",
        "doc://com.apple.virtualization/documentation/Virtualization/graphics",
        "doc://com.apple.virtualization/documentation/Virtualization/keyboards-and-pointing-devices",
        "doc://com.apple.virtualization/documentation/Virtualization/memory",
        "doc://com.apple.virtualization/documentation/Virtualization/randomization",
        "doc://com.apple.virtualization/documentation/Virtualization/serial-ports",
        "doc://com.apple.virtualization/documentation/Virtualization/shared-directories",
        "doc://com.apple.virtualization/documentation/Virtualization/sockets",
        "doc://com.apple.virtualization/documentation/Virtualization/storage",
        "doc://com.apple.virtualization/documentation/Virtualization/consoles",
        "doc://com.apple.virtualization/documentation/Virtualization/clipboard-sharing",
        "doc://com.apple.virtualization/documentation/Virtualization/usb-devices"
      ],
      "title": "Devices"
    }
  ],
  "topicSections": [
    {
      "anchor": "Configurations",
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioNetworkDeviceConfiguration",
        "doc://com.apple.virtualization/documentation/Virtualization/VZNetworkDeviceConfiguration",
        "doc://com.apple.virtualization/documentation/Virtualization/VZMACAddress"
      ],
      "title": "Configurations"
    },
    {
      "anchor": "Attachment-points",
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZBridgedNetworkDeviceAttachment",
        "doc://com.apple.virtualization/documentation/Virtualization/VZFileHandleNetworkDeviceAttachment",
        "doc://com.apple.virtualization/documentation/Virtualization/VZNATNetworkDeviceAttachment",
        "doc://com.apple.virtualization/documentation/Virtualization/VZNetworkDeviceAttachment"
      ],
      "title": "Attachment points"
    },
    {
      "anchor": "Hardware-interfaces",
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZBridgedNetworkInterface"
      ],
      "title": "Hardware interfaces"
    },
    {
      "anchor": "Devices",
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZNetworkDevice"
      ],
      "title": "Devices"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Configurations",
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioNetworkDeviceConfiguration",
                "doc://com.apple.virtualization/documentation/Virtualization/VZNetworkDeviceConfiguration",
                "doc://com.apple.virtualization/documentation/Virtualization/VZMACAddress"
              ],
              "title": "Configurations"
            },
            {
              "anchor": "Attachment-points",
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/VZBridgedNetworkDeviceAttachment",
                "doc://com.apple.virtualization/documentation/Virtualization/VZFileHandleNetworkDeviceAttachment",
                "doc://com.apple.virtualization/documentation/Virtualization/VZNATNetworkDeviceAttachment",
                "doc://com.apple.virtualization/documentation/Virtualization/VZNetworkDeviceAttachment"
              ],
              "title": "Attachment points"
            },
            {
              "anchor": "Hardware-interfaces",
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/VZBridgedNetworkInterface"
              ],
              "title": "Hardware interfaces"
            },
            {
              "anchor": "Devices",
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/VZNetworkDevice"
              ],
              "title": "Devices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Devices",
              "generated": true,
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/audio",
                "doc://com.apple.virtualization/documentation/Virtualization/graphics",
                "doc://com.apple.virtualization/documentation/Virtualization/keyboards-and-pointing-devices",
                "doc://com.apple.virtualization/documentation/Virtualization/memory",
                "doc://com.apple.virtualization/documentation/Virtualization/randomization",
                "doc://com.apple.virtualization/documentation/Virtualization/serial-ports",
                "doc://com.apple.virtualization/documentation/Virtualization/shared-directories",
                "doc://com.apple.virtualization/documentation/Virtualization/sockets",
                "doc://com.apple.virtualization/documentation/Virtualization/storage",
                "doc://com.apple.virtualization/documentation/Virtualization/consoles",
                "doc://com.apple.virtualization/documentation/Virtualization/clipboard-sharing",
                "doc://com.apple.virtualization/documentation/Virtualization/usb-devices"
              ],
              "title": "Devices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZBridgedNetworkDeviceAttachment/title",
          "value": "VZBridgedNetworkDeviceAttachment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZBridgedNetworkDeviceAttachment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZBridgedNetworkDeviceAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZBridgedNetworkDeviceAttachment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZBridgedNetworkDeviceAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZNetworkDeviceConfiguration/title",
          "value": "VZNetworkDeviceConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZNetworkDeviceConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZNetworkDeviceConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZNetworkDeviceConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZNetworkDeviceConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZNetworkDevice/title",
          "value": "VZNetworkDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZNetworkDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZNetworkDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZNetworkDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZNetworkDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMACAddress/title",
          "value": "VZMACAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMACAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZMACAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMACAddress/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZMACAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZBridgedNetworkInterface/title",
          "value": "VZBridgedNetworkInterface"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZBridgedNetworkInterface/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZBridgedNetworkInterface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZBridgedNetworkInterface/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZBridgedNetworkInterface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZNetworkDeviceAttachment/title",
          "value": "VZNetworkDeviceAttachment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZNetworkDeviceAttachment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZNetworkDeviceAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZNetworkDeviceAttachment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZNetworkDeviceAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioNetworkDeviceConfiguration/title",
          "value": "VZVirtioNetworkDeviceConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioNetworkDeviceConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtioNetworkDeviceConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioNetworkDeviceConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtioNetworkDeviceConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZNATNetworkDeviceAttachment/title",
          "value": "VZNATNetworkDeviceAttachment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZNATNetworkDeviceAttachment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZNATNetworkDeviceAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZNATNetworkDeviceAttachment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZNATNetworkDeviceAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZFileHandleNetworkDeviceAttachment/title",
          "value": "VZFileHandleNetworkDeviceAttachment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZFileHandleNetworkDeviceAttachment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZFileHandleNetworkDeviceAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZFileHandleNetworkDeviceAttachment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZFileHandleNetworkDeviceAttachment"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/virtualization/network"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/virtualization/network"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
