{
  "abstract": [
    {
      "text": "Run x86_64 Linux binaries under ARM Linux on Apple silicon.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.virtualization/documentation/Virtualization"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.virtualization/documentation/Virtualization/running-intel-binaries-in-linux-vms-with-rosetta"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Virtualization"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Running Intel Binaries in Linux VMs with Rosetta"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In macOS 13 and later on Mac computers with Apple silicon chips, the Virtualization framework supports Rosetta in ARM Linux virtual machines (VMs). Rosetta is a translation process that allows users to run apps that contain x86_64 instructions on Apple silicon. In macOS, this allows apps built for Intel-based Mac computers to run seamlessly on Apple silicon; Rosetta allows the same capability for Intel Linux apps in ARM Linux VMs.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Rosetta doesn’t support the bootstrapping or installation of Intel Linux distributions on Mac computers with Apple silicon using the Virtualization framework. Intel Linux distributions can run using the Virtualization framework on Intel-based Mac computers without the need for this translation capability.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Test-for-Rosetta-Availability",
          "level": 3,
          "text": "Test for Rosetta Availability",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Before trying to install, run, or activate Rosetta, your app should check to ensure that the capability is available in the version of macOS running on the host computer. The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaDirectoryShare/availability",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class method returns a value from the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaAvailability",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " enumeration that describes whether the current host supports Rosetta or if the capability is already installed on the host Mac. The example below shows the process for checking for Rosetta availability:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "import Virtualization",
                    "",
                    "let rosettaAvailability = VZLinuxRosettaDirectoryShare.availability",
                    "",
                    "switch rosettaAvailability {",
                    "case notSupported:",
                    "    // Alert the user the capability isn't available; offer ",
                    "    // continuation options according to your app's requirements.",
                    "",
                    "case notInstalled:",
                    "    // Ask the user for permission to install Rosetta, and ",
                    "    // start the installation process if they grant permission.",
                    "",
                    "case installed:",
                    "    break // Ready to go.",
                    "}"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "import <Virtualization/Virtualization.h>",
                    "",
                    "VZLinuxRosettaAvailability rosettaAvailability = VZLinuxRosettaDirectoryShare.availability;",
                    "switch (rosettaAvailability) {",
                    "    case VZLinuxRosettaAvailabilityNotSupported:",
                    "        // Alert the user the capability isn't available; offer ",
                    "        // continuation options according to your app's requirements.",
                    "",
                    "    case VZLinuxRosettaAvailabilityNotInstalled:",
                    "        // Ask the user for permission to install Rosetta, and ",
                    "        // start the installation process if they grant permission.",
                    "",
                    "    case VZLinuxRosettaAvailabilityInstalled:",
                    "        break; // Ready to go.",
                    "}"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "anchor": "Install-Rosetta",
          "level": 3,
          "text": "Install Rosetta",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Installing Rosetta is a one-time process per computer that requires the user to grant permission for the system to install Rosetta. If Rosetta is already installed in macOS, the system activates it for use under the Virtualization framework; if Rosetta isn’t installed, the framework downloads the installer from the network and performs the installation. The installer interactively prompts the user for authorization, and your app should handle any of the possible error conditions that could occur during the authorization, download, and installation process. The example below shows how to start the installation:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "do {",
                    "    try await VZLinuxRosettaDirectoryShare.installRosetta()",
                    "    // Success: The system installs Rosetta on the host system.",
                    "} catch let error {",
                    "    switch error.code {",
                    "    case networkError:",
                    "        // A network error prevented the download from completing successfully.",
                    "    case outOfDiskSpace:",
                    "        // Not enough disk space on the system volume to complete the installation.",
                    "    case userCancelled:",
                    "        // The user cancelled the installation.",
                    "    case notSupported:",
                    "        // Rosetta isn't supported on the host Mac or macOS version.",
                    "",
                    "    default:",
                    "        break // A non installer-related error occurred.",
                    "    }",
                    "}"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "[VZLinuxRosettaDirectoryShare installRosettaWithCompletionHandler:^(NSError *error) {",
                    "    if (!error) {",
                    "        // Success: The system installs Rosetta on the host system.",
                    "    } else {",
                    "        // Handle error if error is not nil:",
                    "        switch error.code {",
                    "             case VSErrorNetworkError:",
                    "                 // A network error prevented the download from completing successfully.",
                    "             case VZErrorOutOfDiskSpace:",
                    "                 // Not enough disk space on the system volume to complete the installation.",
                    "             case VZErrorUserCancelled:",
                    "                 // The user cancelled the installation.",
                    "             case VZErrorNotSupported:",
                    "                // Rosetta isn't supported on the host Mac or macOS version.",
                    "            default:",
                    "               break; // A non installer-related error occurred.",
                    "        }",
                    "    }",
                    "}];"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "anchor": "Create-the-Rosetta-Directory-Share",
          "level": 3,
          "text": "Create the Rosetta Directory Share",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "After installing Rosetta, your app needs to configure a Rosetta directory share in the Linux guest. The shared directory must have a tag that uniquely identifies the share and that you validate using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioFileSystemDeviceConfiguration/validateTag(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to ensure it conforms to the length and format for file system tags:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "let tag = \"EXAMPLE_TAG\"  ",
                    "let configuration = VZVirtualMachineConfiguration()",
                    "do {",
                    "    try let validationError = VZVirtioFileSystemDeviceConfiguration.validateTag(tag)",
                    "    let rosettaDirectoryShare = try VZLinuxRosettaDirectoryShare()",
                    "    let fileSystemDevice = VZVirtioFileSystemDeviceConfiguration(tag: tag)",
                    "    fileSystemDevice.share = rosettaDirectoryShare",
                    "",
                    "    configuration.directorySharingDevices = [ fileSystemDevice ]",
                    "} catch VZError.invalidVirtualMachineConfiguration {",
                    "    // Rosetta is unavailable.",
                    "}"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "NSString *tag = @\"EXAMPLE_TAG\";",
                    "NSError *validationError = [[VZVirtioFileSystemDeviceConfiguration] validateTag: tag];",
                    "if (validationError) {",
                    "    AbortWithErrorMessage(\"Tag %@\", tag.localizedDescription); // tag failed to validate.",
                    "}",
                    "",
                    "VZVirtualMachineConfiguration *configuration = [[VZVirtualMachineConfiguration alloc] init];",
                    "VZVirtioFileSystemDeviceConfiguration *fileSystemDevice = [[VZVirtioFileSystemDeviceConfiguration alloc] initWithTag:tag];",
                    "",
                    "NSError *error = nil;",
                    "VZLinuxRosettaDirectoryShare *rosettaDirectoryShare = [[VZLinuxRosettaDirectoryShare alloc] initWithError:&error];",
                    "if (rosettaDirectoryShare) {",
                    "    fileSystemDevice.share = rosettaDirectoryShare;",
                    "    configuration.directorySharingDevices = @[ fileSystemDevice ];",
                    "} else {",
                    "    // Rosetta is unavailable.",
                    "}"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "anchor": "Mount-the-Shared-Directory-and-Register-Rosetta",
          "level": 3,
          "text": "Mount the Shared Directory and Register Rosetta",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In order to use Rosetta in the Linux guest, the user must mount the Rosetta share in the guest VM and install Rosetta as the application the system uses to run x86_64 binaries using the following process:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The remaining steps required to activate Rosetta in a Linux guest aren’t commands that your app can execute or that you can script from inside your application to a Linux VM; the user must perform them either interactively or as part of a script while logged in to the Linux guest. You must communicate these requirements to the user of your app.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Install the ",
                      "type": "text"
                    },
                    {
                      "code": "update-binfmts",
                      "type": "codeVoice"
                    },
                    {
                      "text": " command, if necessary. The command is part of the binfmt-support package in most Linux distributions; installation methods vary by distribution. Additionally, in order to run this command, the user must be able to use the ",
                      "type": "text"
                    },
                    {
                      "code": "sudo",
                      "type": "codeVoice"
                    },
                    {
                      "text": " command, which requires adding their username to the system’s ",
                      "type": "text"
                    },
                    {
                      "code": "/etc/sudoers",
                      "type": "codeVoice"
                    },
                    {
                      "text": " file.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Create a directory as a mount point.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Mount the VirtioFS file system tag to the mount point. This is the file system tag the app uses to identify the share and must be the same as the tag the user specifies on the command line demonstrated here.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Check if the mounted directory has the Rosetta runtime. You should see ",
                      "type": "text"
                    },
                    {
                      "code": "rosetta",
                      "type": "codeVoice"
                    },
                    {
                      "text": " in the mounted directory.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Register the Rosetta runtime binary as the handler for x86_64 ELF format executable files using the ",
                      "type": "text"
                    },
                    {
                      "code": "update-binfmts",
                      "type": "codeVoice"
                    },
                    {
                      "text": " command. The ",
                      "type": "text"
                    },
                    {
                      "code": "magic",
                      "type": "codeVoice"
                    },
                    {
                      "text": " parameter describes the first 20 bytes of the ELF header for x86_64 binaries. The Linux kernel performs a bitwise logical ",
                      "type": "text"
                    },
                    {
                      "code": "AND",
                      "type": "codeVoice"
                    },
                    {
                      "text": " with the first 20 bytes of a binary a user attempts to run with the ",
                      "type": "text"
                    },
                    {
                      "code": "mask",
                      "type": "codeVoice"
                    },
                    {
                      "text": " value. If it matches the ",
                      "type": "text"
                    },
                    {
                      "code": "magic",
                      "type": "codeVoice"
                    },
                    {
                      "text": " value, the kernel uses the registered handler as the interpreter for that binary. If the system can’t find a handler for the specified binary, it reports an error.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The example below lists the commands, with the exception of the ",
              "type": "text"
            },
            {
              "code": "update-binfmts",
              "type": "codeVoice"
            },
            {
              "text": " command installation, required to enable Rosetta in the Linux guest:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "When using Rosetta in macOS 13, set the ",
                  "type": "text"
                },
                {
                  "code": "preserve",
                  "type": "codeVoice"
                },
                {
                  "text": " option to ",
                  "type": "text"
                },
                {
                  "code": "no.",
                  "type": "codeVoice"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "code": [
            "% mkdir /tmp/mountpoint",
            "% sudo mount -t virtiofs EXAMPLE_TAG /tmp/mountpoint",
            "% ls /tmp/mountpoint rosetta",
            "% sudo /usr/sbin/update-binfmts --install rosetta /tmp/mountpoint/rosetta \\",
            "    --magic \"\\x7fELF\\x02\\x01\\x01\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x02\\x00\\x3e\\x00\" \\",
            "    --mask \"\\xff\\xff\\xff\\xff\\xff\\xfe\\xfe\\x00\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xfe\\xff\\xff\\xff\" \\",
            "    --credentials yes --preserve yes --fix-binary yes"
          ],
          "syntax": "bash",
          "type": "codeListing"
        },
        {
          "anchor": "Ensure-Shared-Libraries-are-Available-for-Dynamically-Linked-Apps",
          "level": 3,
          "text": "Ensure Shared Libraries are Available for Dynamically Linked Apps",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Rosetta can run statically linked x86_64 binaries without additional configuration. Binaries that are dynamically linked and that depend on shared libraries require the installation of the shared libraries, or library hierarchies, in the Linux guest in paths that are accessible to both the user and to Rosetta.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Configure-Rosettas-ahead-of-time-AOT-caching-options",
          "level": 3,
          "text": "Configure Rosetta’s ahead of time (AOT) caching options",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In macOS 14 and later, Rosetta supports options that allow you control the ahead of time (AOT) cache characteristics; this can improve the performance of some X86 workloads.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "There are two modes of operation for AOT caching: The first is communication using a Unix Domain Socket where the Virtualization framework shares a file that represents the socket between the Rosetta daemon and Rosetta runtime through a symlink or bind-mount. The second is communication through an abstract socket where the framework defines a shared name rather than a shared file. ",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You enable these options after you create the Rosetta directory share by setting one of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaDirectoryShare/CachingOptions-swift.enum",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaDirectoryShare/setCachingOptions(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". This example shows how to configure Rosetta’s caching options in a new virtual machine configuration using a Unix Domain Socket though a shared, named file:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "    let configuration = VZVirtualMachineConfiguration()",
                    "    do {",
                    "        let rosettaDirectoryShare = try VZLinuxRosettaDirectoryShare()",
                    "        try rosettaDirectoryShare.setCachingOptions(cachingOptions: .unixSocket(\"/valid/path/rosetta.sock\"))",
                    "",
                    "        let fileSystemDevice = VZVirtioFileSystemDeviceConfiguration(tag: \"example-tag\")",
                    "        fileSystemDevice.share = rosettaDirectoryShare",
                    "",
                    "        configuration.directorySharingDevices = [ fileSystemDevice ]",
                    "    } catch VZError.invalidVirtualMachineConfiguration {",
                    "        // Rosetta for Linux is unavailable or failed to initialize Rosetta caching options.",
                    "        // If Rosetta for Linux is unavailable, clients may install the resources or proceed without them.",
                    "        // If Rosetta caching options failed to initialize, clients may gracefully fail or proceed without caching.",
                    "    }"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "    VZVirtualMachineConfiguration *configuration = [[VZVirtualMachineConfiguration alloc] init];",
                    "    VZVirtioFileSystemDeviceConfiguration *fileSystemDevice = [[VZVirtioFileSystemDeviceConfiguration alloc] initWithTag:@\"example-tag\"];",
                    "",
                    "    NSError *error = nil;",
                    "    VZLinuxRosettaDirectoryShare *rosettaDirectoryShare = [[VZLinuxRosettaDirectoryShare alloc] initWithError:&error];",
                    "    if (rosettaDirectoryShare) {",
                    "        error = nil;",
                    "        VZLinuxRosettaUnixSocketCachingOptions *rosettaCachingOptions = [[VZLinuxRosettaUnixSocketCachingOptions alloc] initWithPath:@\"/valid/path/rosetta.sock\" error:&error];",
                    "        if (rosettaCachingOptions) {",
                    "            rosettaDirectoryShare.options = rosettaCachingOptions;",
                    "            fileSystemDevice.share = rosettaDirectoryShare;",
                    "            configuration.directorySharingDevices = @[ fileSystemDevice ];",
                    "        } else {",
                    "            // Failed to initialize Rosetta caching options. Clients may gracefully fail or proceed without caching.",
                    "        }",
                    "    } else {",
                    "        // Rosetta for Linux is unavailable. Clients may install the resources or proceed without them.",
                    "    }"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "inlineContent": [
            {
              "text": "The following example shows how to configure Rosetta’s caching options in a new virtual machine configuration using an abstract socket:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "    let configuration = VZVirtualMachineConfiguration()",
                    "    do {",
                    "        let rosettaDirectoryShare = try VZLinuxRosettaDirectoryShare()",
                    "        try rosettaDirectoryShare.setCachingOptions(.abstractSocket(\"abstractSocketName\"))",
                    "",
                    "        let fileSystemDevice = VZVirtioFileSystemDeviceConfiguration(tag: \"example-tag\")",
                    "        fileSystemDevice.share = rosettaDirectoryShare",
                    "",
                    "        configuration.directorySharingDevices = [ fileSystemDevice ]",
                    "    } catch VZError.invalidVirtualMachineConfiguration {",
                    "        // Rosetta for Linux is unavailable or failed to initialize Rosetta caching options.",
                    "        // If Rosetta for Linux is unavailable, clients may install the resources or proceed without them.",
                    "        // If Rosetta caching options failed to initialize, clients may gracefully fail or proceed without caching.",
                    "    }    "
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "    VZVirtualMachineConfiguration *configuration = [[VZVirtualMachineConfiguration alloc] init];",
                    "    VZVirtioFileSystemDeviceConfiguration *fileSystemDevice = [[VZVirtioFileSystemDeviceConfiguration alloc] initWithTag:@\"example-tag\"];",
                    "",
                    "    NSError *error = nil;",
                    "    VZLinuxRosettaDirectoryShare *rosettaDirectoryShare = [[VZLinuxRosettaDirectoryShare alloc] initWithError:&error];",
                    "    if (rosettaDirectoryShare) {",
                    "        VZLinuxRosettaAbstractSocketCachingOptions *options = [[VZLinuxRosettaAbstractSocketCachingOptions alloc] initWithName:@\"abstractSocketName\" error:&error];",
                    "        if (rosettaCachingOptions) {",
                    "            rosettaDirectoryShare.options = rosettaCachingOptions;",
                    "            fileSystemDevice.share = rosettaDirectoryShare;",
                    "            configuration.directorySharingDevices = @[ fileSystemDevice ];",
                    "        } else {",
                    "            // Failed to initialize Rosetta caching options. Clients may gracefully fail or proceed without caching.",
                    "        }",
                    "       } else {",
                    "        // Rosetta for Linux is unavailable. Clients may install the resources or proceed without them.",
                    "    }"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.virtualization/documentation/Virtualization": {
      "abstract": [
        {
          "text": "Create virtual machines and run macOS and Linux-based operating systems.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization",
      "kind": "symbol",
      "role": "collection",
      "title": "Virtualization",
      "type": "topic",
      "url": "/documentation/virtualization"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaAvailability": {
      "abstract": [
        {
          "text": "Constants that describe the availability and installation status of Rosetta.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZLinuxRosettaAvailability"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaAvailability",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZLinuxRosettaAvailability"
        }
      ],
      "role": "symbol",
      "title": "VZLinuxRosettaAvailability",
      "type": "topic",
      "url": "/documentation/virtualization/vzlinuxrosettaavailability"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaDirectoryShare/CachingOptions-swift.enum": {
      "abstract": [
        {
          "text": "Socket values you specify to configure Rosetta’s caching capabilities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CachingOptions"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaDirectoryShare/CachingOptions-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CachingOptions"
        }
      ],
      "role": "symbol",
      "title": "VZLinuxRosettaDirectoryShare.CachingOptions",
      "type": "topic",
      "url": "/documentation/virtualization/vzlinuxrosettadirectoryshare/cachingoptions-swift.enum"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaDirectoryShare/availability": {
      "abstract": [
        {
          "text": "A value that indicates the current state of Rosetta’s availability.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "availability"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VZLinuxRosettaAvailability",
          "text": "VZLinuxRosettaAvailability"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaDirectoryShare/availability",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "availability"
        }
      ],
      "role": "symbol",
      "title": "availability",
      "type": "topic",
      "url": "/documentation/virtualization/vzlinuxrosettadirectoryshare/availability"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaDirectoryShare/setCachingOptions(_:)": {
      "abstract": [
        {
          "text": "Sets the Rosetta caching options using the options you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setCachingOptions"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VZLinuxRosettaDirectoryShare",
          "text": "VZLinuxRosettaDirectoryShare"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So28VZLinuxRosettaDirectoryShareC14VirtualizationE14CachingOptionsO",
          "text": "CachingOptions"
        },
        {
          "kind": "text",
          "text": "?) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaDirectoryShare/setCachingOptions(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setCachingOptions(_:)",
      "type": "topic",
      "url": "/documentation/virtualization/vzlinuxrosettadirectoryshare/setcachingoptions(_:)"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioFileSystemDeviceConfiguration/validateTag(_:)": {
      "abstract": [
        {
          "text": "Checks to see whether a Virtio tag is valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "validateTag"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioFileSystemDeviceConfiguration/validateTag(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "validateTag:error:"
        }
      ],
      "role": "symbol",
      "title": "validateTag(_:)",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtiofilesystemdeviceconfiguration/validatetag(_:)"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/accelerating-the-performance-of-rosetta": {
      "abstract": [
        {
          "text": "Improve Rosetta performance by adding support for the total store ordering (TSO) memory model to your Linux kernel.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/accelerating-the-performance-of-rosetta",
      "kind": "article",
      "role": "article",
      "title": "Accelerating the performance of Rosetta",
      "type": "topic",
      "url": "/documentation/virtualization/accelerating-the-performance-of-rosetta"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/creating-and-running-a-linux-virtual-machine": {
      "abstract": [
        {
          "text": "Design and run custom Linux guests on Apple silicon or Intel-based Mac Computers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/creating-and-running-a-linux-virtual-machine",
      "kind": "article",
      "role": "article",
      "title": "Creating and Running a Linux Virtual Machine",
      "type": "topic",
      "url": "/documentation/virtualization/creating-and-running-a-linux-virtual-machine"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/installing-macos-on-a-virtual-machine": {
      "abstract": [
        {
          "text": "Download a macOS restore image and install it in a new VM.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/installing-macos-on-a-virtual-machine",
      "kind": "article",
      "role": "article",
      "title": "Installing macOS on a Virtual Machine",
      "type": "topic",
      "url": "/documentation/virtualization/installing-macos-on-a-virtual-machine"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/running-gui-linux-in-a-virtual-machine-on-a-mac": {
      "abstract": [
        {
          "text": "Install and run GUI Linux in a virtual machine using the Virtualization framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/running-gui-linux-in-a-virtual-machine-on-a-mac",
      "kind": "article",
      "role": "sampleCode",
      "title": "Running GUI Linux in a virtual machine on a Mac",
      "type": "topic",
      "url": "/documentation/virtualization/running-gui-linux-in-a-virtual-machine-on-a-mac"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/running-linux-in-a-virtual-machine": {
      "abstract": [
        {
          "text": "Run a Linux operating system on your Mac using the Virtualization framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/running-linux-in-a-virtual-machine",
      "kind": "article",
      "role": "sampleCode",
      "title": "Running Linux in a Virtual Machine",
      "type": "topic",
      "url": "/documentation/virtualization/running-linux-in-a-virtual-machine"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/running-macos-in-a-virtual-machine-on-apple-silicon": {
      "abstract": [
        {
          "text": "Install and run macOS in a virtual machine using the Virtualization framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/running-macos-in-a-virtual-machine-on-apple-silicon",
      "kind": "article",
      "role": "sampleCode",
      "title": "Running macOS in a virtual machine on Apple silicon",
      "type": "topic",
      "url": "/documentation/virtualization/running-macos-in-a-virtual-machine-on-apple-silicon"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/virtualize-linux-on-a-mac": {
      "abstract": [
        {
          "text": "Configure and run Linux guests on Apple silicon and Intel-based Mac computers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/virtualize-linux-on-a-mac",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Virtualize Linux on a Mac",
      "type": "topic",
      "url": "/documentation/virtualization/virtualize-linux-on-a-mac"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/virtualize-macos-on-a-mac": {
      "abstract": [
        {
          "text": "Configure and run macOS guests on Apple silicon.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/virtualize-macos-on-a-mac",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Virtualize macOS on a Mac",
      "type": "topic",
      "url": "/documentation/virtualization/virtualize-macos-on-a-mac"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Virtual-machine-setup",
      "generated": true,
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/running-macos-in-a-virtual-machine-on-apple-silicon",
        "doc://com.apple.virtualization/documentation/Virtualization/running-linux-in-a-virtual-machine",
        "doc://com.apple.virtualization/documentation/Virtualization/running-gui-linux-in-a-virtual-machine-on-a-mac",
        "doc://com.apple.virtualization/documentation/Virtualization/installing-macos-on-a-virtual-machine",
        "doc://com.apple.virtualization/documentation/Virtualization/creating-and-running-a-linux-virtual-machine",
        "doc://com.apple.virtualization/documentation/Virtualization/virtualize-macos-on-a-mac",
        "doc://com.apple.virtualization/documentation/Virtualization/virtualize-linux-on-a-mac",
        "doc://com.apple.virtualization/documentation/Virtualization/accelerating-the-performance-of-rosetta"
      ],
      "title": "Virtual machine setup"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Virtual-machine-setup",
              "generated": true,
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/running-macos-in-a-virtual-machine-on-apple-silicon",
                "doc://com.apple.virtualization/documentation/Virtualization/running-linux-in-a-virtual-machine",
                "doc://com.apple.virtualization/documentation/Virtualization/running-gui-linux-in-a-virtual-machine-on-a-mac",
                "doc://com.apple.virtualization/documentation/Virtualization/installing-macos-on-a-virtual-machine",
                "doc://com.apple.virtualization/documentation/Virtualization/creating-and-running-a-linux-virtual-machine",
                "doc://com.apple.virtualization/documentation/Virtualization/virtualize-macos-on-a-mac",
                "doc://com.apple.virtualization/documentation/Virtualization/virtualize-linux-on-a-mac",
                "doc://com.apple.virtualization/documentation/Virtualization/accelerating-the-performance-of-rosetta"
              ],
              "title": "Virtual machine setup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZLinuxRosettaAvailability/title",
          "value": "VZLinuxRosettaAvailability"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZLinuxRosettaAvailability/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZLinuxRosettaAvailability"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZLinuxRosettaAvailability/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZLinuxRosettaAvailability"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZLinuxRosettaDirectoryShare~1availability/title",
          "value": "availability"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZLinuxRosettaDirectoryShare~1availability/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "availability"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioFileSystemDeviceConfiguration~1validateTag(_:)/title",
          "value": "validateTag:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioFileSystemDeviceConfiguration~1validateTag(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "validateTag:error:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/virtualization/running-intel-binaries-in-linux-vms-with-rosetta"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/virtualization/running-intel-binaries-in-linux-vms-with-rosetta"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
