{
  "abstract": [
    {
      "text": "Configure the serial devices that you use to communicate with the guest system.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.virtualization/documentation/Virtualization"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.virtualization/documentation/Virtualization/serial-ports"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Virtualization"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Serial ports"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.virtualization/documentation/Virtualization": {
      "abstract": [
        {
          "text": "Create virtual machines and run macOS and Linux-based operating systems.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization",
      "kind": "symbol",
      "role": "collection",
      "title": "Virtualization",
      "type": "topic",
      "url": "/documentation/virtualization"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZFileHandleSerialPortAttachment": {
      "abstract": [
        {
          "text": "An attachment point that allows bidirectional communication using file handles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZFileHandleSerialPortAttachment"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZFileHandleSerialPortAttachment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZFileHandleSerialPortAttachment"
        }
      ],
      "role": "symbol",
      "title": "VZFileHandleSerialPortAttachment",
      "type": "topic",
      "url": "/documentation/virtualization/vzfilehandleserialportattachment"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZFileSerialPortAttachment": {
      "abstract": [
        {
          "text": "An attachment point that writes data from the guest system to a file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZFileSerialPortAttachment"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZFileSerialPortAttachment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZFileSerialPortAttachment"
        }
      ],
      "role": "symbol",
      "title": "VZFileSerialPortAttachment",
      "type": "topic",
      "url": "/documentation/virtualization/vzfileserialportattachment"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZSerialPortAttachment": {
      "abstract": [
        {
          "text": "The common behaviors for the serial attachment points of your virtual machine.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZSerialPortAttachment"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZSerialPortAttachment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZSerialPortAttachment"
        }
      ],
      "role": "symbol",
      "title": "VZSerialPortAttachment",
      "type": "topic",
      "url": "/documentation/virtualization/vzserialportattachment"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZSerialPortConfiguration": {
      "abstract": [
        {
          "text": "The common configuration traits for serial port requests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZSerialPortConfiguration"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZSerialPortConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZSerialPortConfiguration"
        }
      ],
      "role": "symbol",
      "title": "VZSerialPortConfiguration",
      "type": "topic",
      "url": "/documentation/virtualization/vzserialportconfiguration"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioConsoleDeviceSerialPortConfiguration": {
      "abstract": [
        {
          "text": "A configuration object that requests the creation of a console device to communicate with the guest system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZVirtioConsoleDeviceSerialPortConfiguration"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioConsoleDeviceSerialPortConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZVirtioConsoleDeviceSerialPortConfiguration"
        }
      ],
      "role": "symbol",
      "title": "VZVirtioConsoleDeviceSerialPortConfiguration",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtioconsoledeviceserialportconfiguration"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/audio": {
      "abstract": [
        {
          "text": "Configure audio devices that enable the guest operating system to perform audio playback and capture through the host’s audio devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/audio",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio",
      "type": "topic",
      "url": "/documentation/virtualization/audio"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/clipboard-sharing": {
      "abstract": [
        {
          "text": "Share the pasteboard between the host and guest system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/clipboard-sharing",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Clipboard sharing",
      "type": "topic",
      "url": "/documentation/virtualization/clipboard-sharing"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/consoles": {
      "abstract": [
        {
          "text": "Configure a device that manages multiport console communication with the guest system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/consoles",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Consoles",
      "type": "topic",
      "url": "/documentation/virtualization/consoles"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/graphics": {
      "abstract": [
        {
          "text": "Configure a device for a guest to display its UI.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/graphics",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Graphics",
      "type": "topic",
      "url": "/documentation/virtualization/graphics"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/keyboards-and-pointing-devices": {
      "abstract": [
        {
          "text": "Configure devices that connect a mouse and keyboard to the guest system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/keyboards-and-pointing-devices",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Keyboards and pointing devices",
      "type": "topic",
      "url": "/documentation/virtualization/keyboards-and-pointing-devices"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/memory": {
      "abstract": [
        {
          "text": "Configure a memory balloon device to change the allocated memory for the guest system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/memory",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Memory",
      "type": "topic",
      "url": "/documentation/virtualization/memory"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/network": {
      "abstract": [
        {
          "text": "Configure the devices that connect the guest system to the network.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/network",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/virtualization/network"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/randomization": {
      "abstract": [
        {
          "text": "Configure a device for the guest system to use to generate random numbers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/randomization",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Randomization",
      "type": "topic",
      "url": "/documentation/virtualization/randomization"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/shared-directories": {
      "abstract": [
        {
          "text": "Configure devices that share directories from the host into the guest system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/shared-directories",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Shared directories",
      "type": "topic",
      "url": "/documentation/virtualization/shared-directories"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/sockets": {
      "abstract": [
        {
          "text": "Configure a device that manages port-based communication with the guest system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/sockets",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sockets",
      "type": "topic",
      "url": "/documentation/virtualization/sockets"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/storage": {
      "abstract": [
        {
          "text": "Configure the block-storage devices that represent the disks of the guest system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/storage",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Storage",
      "type": "topic",
      "url": "/documentation/virtualization/storage"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/usb-devices": {
      "abstract": [],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/usb-devices",
      "kind": "article",
      "role": "collectionGroup",
      "title": "USB Devices",
      "type": "topic",
      "url": "/documentation/virtualization/usb-devices"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Devices",
      "generated": true,
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/audio",
        "doc://com.apple.virtualization/documentation/Virtualization/graphics",
        "doc://com.apple.virtualization/documentation/Virtualization/keyboards-and-pointing-devices",
        "doc://com.apple.virtualization/documentation/Virtualization/memory",
        "doc://com.apple.virtualization/documentation/Virtualization/network",
        "doc://com.apple.virtualization/documentation/Virtualization/randomization",
        "doc://com.apple.virtualization/documentation/Virtualization/shared-directories",
        "doc://com.apple.virtualization/documentation/Virtualization/sockets",
        "doc://com.apple.virtualization/documentation/Virtualization/storage",
        "doc://com.apple.virtualization/documentation/Virtualization/consoles",
        "doc://com.apple.virtualization/documentation/Virtualization/clipboard-sharing",
        "doc://com.apple.virtualization/documentation/Virtualization/usb-devices"
      ],
      "title": "Devices"
    }
  ],
  "topicSections": [
    {
      "anchor": "Configurations",
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioConsoleDeviceSerialPortConfiguration",
        "doc://com.apple.virtualization/documentation/Virtualization/VZSerialPortConfiguration"
      ],
      "title": "Configurations"
    },
    {
      "anchor": "Attachment-points",
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZFileHandleSerialPortAttachment",
        "doc://com.apple.virtualization/documentation/Virtualization/VZFileSerialPortAttachment",
        "doc://com.apple.virtualization/documentation/Virtualization/VZSerialPortAttachment"
      ],
      "title": "Attachment points"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Configurations",
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioConsoleDeviceSerialPortConfiguration",
                "doc://com.apple.virtualization/documentation/Virtualization/VZSerialPortConfiguration"
              ],
              "title": "Configurations"
            },
            {
              "anchor": "Attachment-points",
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/VZFileHandleSerialPortAttachment",
                "doc://com.apple.virtualization/documentation/Virtualization/VZFileSerialPortAttachment",
                "doc://com.apple.virtualization/documentation/Virtualization/VZSerialPortAttachment"
              ],
              "title": "Attachment points"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Devices",
              "generated": true,
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/audio",
                "doc://com.apple.virtualization/documentation/Virtualization/graphics",
                "doc://com.apple.virtualization/documentation/Virtualization/keyboards-and-pointing-devices",
                "doc://com.apple.virtualization/documentation/Virtualization/memory",
                "doc://com.apple.virtualization/documentation/Virtualization/network",
                "doc://com.apple.virtualization/documentation/Virtualization/randomization",
                "doc://com.apple.virtualization/documentation/Virtualization/shared-directories",
                "doc://com.apple.virtualization/documentation/Virtualization/sockets",
                "doc://com.apple.virtualization/documentation/Virtualization/storage",
                "doc://com.apple.virtualization/documentation/Virtualization/consoles",
                "doc://com.apple.virtualization/documentation/Virtualization/clipboard-sharing",
                "doc://com.apple.virtualization/documentation/Virtualization/usb-devices"
              ],
              "title": "Devices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZSerialPortConfiguration/title",
          "value": "VZSerialPortConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZSerialPortConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZSerialPortConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZSerialPortConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZSerialPortConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZFileSerialPortAttachment/title",
          "value": "VZFileSerialPortAttachment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZFileSerialPortAttachment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZFileSerialPortAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZFileSerialPortAttachment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZFileSerialPortAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZFileHandleSerialPortAttachment/title",
          "value": "VZFileHandleSerialPortAttachment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZFileHandleSerialPortAttachment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZFileHandleSerialPortAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZFileHandleSerialPortAttachment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZFileHandleSerialPortAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZSerialPortAttachment/title",
          "value": "VZSerialPortAttachment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZSerialPortAttachment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZSerialPortAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZSerialPortAttachment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZSerialPortAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioConsoleDeviceSerialPortConfiguration/title",
          "value": "VZVirtioConsoleDeviceSerialPortConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioConsoleDeviceSerialPortConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtioConsoleDeviceSerialPortConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioConsoleDeviceSerialPortConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtioConsoleDeviceSerialPortConfiguration"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/virtualization/serial-ports"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/virtualization/serial-ports"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
