{
  "abstract": [
    {
      "text": "Configure a device that manages port-based communication with the guest system.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.virtualization/documentation/Virtualization"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.virtualization/documentation/Virtualization/sockets"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Virtualization"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Sockets"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.virtualization/documentation/Virtualization": {
      "abstract": [
        {
          "text": "Create virtual machines and run macOS and Linux-based operating systems.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization",
      "kind": "symbol",
      "role": "collection",
      "title": "Virtualization",
      "type": "topic",
      "url": "/documentation/virtualization"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZSocketDevice": {
      "abstract": [
        {
          "text": "The common behavior of socket devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZSocketDevice"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZSocketDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZSocketDevice"
        }
      ],
      "role": "symbol",
      "title": "VZSocketDevice",
      "type": "topic",
      "url": "/documentation/virtualization/vzsocketdevice"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZSocketDeviceConfiguration": {
      "abstract": [
        {
          "text": "The common configuration traits for socket device requests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZSocketDeviceConfiguration"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZSocketDeviceConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZSocketDeviceConfiguration"
        }
      ],
      "role": "symbol",
      "title": "VZSocketDeviceConfiguration",
      "type": "topic",
      "url": "/documentation/virtualization/vzsocketdeviceconfiguration"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSocketConnection": {
      "abstract": [
        {
          "text": "A port-based connection between the guest operating system and the host computer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZVirtioSocketConnection"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSocketConnection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZVirtioSocketConnection"
        }
      ],
      "role": "symbol",
      "title": "VZVirtioSocketConnection",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtiosocketconnection"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSocketDevice": {
      "abstract": [
        {
          "text": "A device that manages port-based connections between the guest system and the host computer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZVirtioSocketDevice"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSocketDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZVirtioSocketDevice"
        }
      ],
      "role": "symbol",
      "title": "VZVirtioSocketDevice",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtiosocketdevice"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSocketDeviceConfiguration": {
      "abstract": [
        {
          "text": "A configuration object that requests the creation of a socket device to communicate with the guest system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZVirtioSocketDeviceConfiguration"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSocketDeviceConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZVirtioSocketDeviceConfiguration"
        }
      ],
      "role": "symbol",
      "title": "VZVirtioSocketDeviceConfiguration",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtiosocketdeviceconfiguration"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSocketListener": {
      "abstract": [
        {
          "text": "An object that listens for port-based connection requests from the guest operating system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZVirtioSocketListener"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSocketListener",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZVirtioSocketListener"
        }
      ],
      "role": "symbol",
      "title": "VZVirtioSocketListener",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtiosocketlistener"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/audio": {
      "abstract": [
        {
          "text": "Configure audio devices that enable the guest operating system to perform audio playback and capture through the host’s audio devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/audio",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio",
      "type": "topic",
      "url": "/documentation/virtualization/audio"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/clipboard-sharing": {
      "abstract": [
        {
          "text": "Share the pasteboard between the host and guest system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/clipboard-sharing",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Clipboard sharing",
      "type": "topic",
      "url": "/documentation/virtualization/clipboard-sharing"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/consoles": {
      "abstract": [
        {
          "text": "Configure a device that manages multiport console communication with the guest system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/consoles",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Consoles",
      "type": "topic",
      "url": "/documentation/virtualization/consoles"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/graphics": {
      "abstract": [
        {
          "text": "Configure a device for a guest to display its UI.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/graphics",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Graphics",
      "type": "topic",
      "url": "/documentation/virtualization/graphics"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/keyboards-and-pointing-devices": {
      "abstract": [
        {
          "text": "Configure devices that connect a mouse and keyboard to the guest system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/keyboards-and-pointing-devices",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Keyboards and pointing devices",
      "type": "topic",
      "url": "/documentation/virtualization/keyboards-and-pointing-devices"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/memory": {
      "abstract": [
        {
          "text": "Configure a memory balloon device to change the allocated memory for the guest system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/memory",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Memory",
      "type": "topic",
      "url": "/documentation/virtualization/memory"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/network": {
      "abstract": [
        {
          "text": "Configure the devices that connect the guest system to the network.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/network",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/virtualization/network"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/randomization": {
      "abstract": [
        {
          "text": "Configure a device for the guest system to use to generate random numbers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/randomization",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Randomization",
      "type": "topic",
      "url": "/documentation/virtualization/randomization"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/serial-ports": {
      "abstract": [
        {
          "text": "Configure the serial devices that you use to communicate with the guest system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/serial-ports",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Serial ports",
      "type": "topic",
      "url": "/documentation/virtualization/serial-ports"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/shared-directories": {
      "abstract": [
        {
          "text": "Configure devices that share directories from the host into the guest system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/shared-directories",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Shared directories",
      "type": "topic",
      "url": "/documentation/virtualization/shared-directories"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/storage": {
      "abstract": [
        {
          "text": "Configure the block-storage devices that represent the disks of the guest system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/storage",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Storage",
      "type": "topic",
      "url": "/documentation/virtualization/storage"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/usb-devices": {
      "abstract": [],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/usb-devices",
      "kind": "article",
      "role": "collectionGroup",
      "title": "USB Devices",
      "type": "topic",
      "url": "/documentation/virtualization/usb-devices"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Devices",
      "generated": true,
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/audio",
        "doc://com.apple.virtualization/documentation/Virtualization/graphics",
        "doc://com.apple.virtualization/documentation/Virtualization/keyboards-and-pointing-devices",
        "doc://com.apple.virtualization/documentation/Virtualization/memory",
        "doc://com.apple.virtualization/documentation/Virtualization/network",
        "doc://com.apple.virtualization/documentation/Virtualization/randomization",
        "doc://com.apple.virtualization/documentation/Virtualization/serial-ports",
        "doc://com.apple.virtualization/documentation/Virtualization/shared-directories",
        "doc://com.apple.virtualization/documentation/Virtualization/storage",
        "doc://com.apple.virtualization/documentation/Virtualization/consoles",
        "doc://com.apple.virtualization/documentation/Virtualization/clipboard-sharing",
        "doc://com.apple.virtualization/documentation/Virtualization/usb-devices"
      ],
      "title": "Devices"
    }
  ],
  "topicSections": [
    {
      "anchor": "Configurations",
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSocketDeviceConfiguration",
        "doc://com.apple.virtualization/documentation/Virtualization/VZSocketDeviceConfiguration"
      ],
      "title": "Configurations"
    },
    {
      "anchor": "Devices",
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSocketDevice",
        "doc://com.apple.virtualization/documentation/Virtualization/VZSocketDevice"
      ],
      "title": "Devices"
    },
    {
      "anchor": "Connection-management",
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSocketListener",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSocketConnection"
      ],
      "title": "Connection management"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Configurations",
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSocketDeviceConfiguration",
                "doc://com.apple.virtualization/documentation/Virtualization/VZSocketDeviceConfiguration"
              ],
              "title": "Configurations"
            },
            {
              "anchor": "Devices",
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSocketDevice",
                "doc://com.apple.virtualization/documentation/Virtualization/VZSocketDevice"
              ],
              "title": "Devices"
            },
            {
              "anchor": "Connection-management",
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSocketListener",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSocketConnection"
              ],
              "title": "Connection management"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Devices",
              "generated": true,
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/audio",
                "doc://com.apple.virtualization/documentation/Virtualization/graphics",
                "doc://com.apple.virtualization/documentation/Virtualization/keyboards-and-pointing-devices",
                "doc://com.apple.virtualization/documentation/Virtualization/memory",
                "doc://com.apple.virtualization/documentation/Virtualization/network",
                "doc://com.apple.virtualization/documentation/Virtualization/randomization",
                "doc://com.apple.virtualization/documentation/Virtualization/serial-ports",
                "doc://com.apple.virtualization/documentation/Virtualization/shared-directories",
                "doc://com.apple.virtualization/documentation/Virtualization/storage",
                "doc://com.apple.virtualization/documentation/Virtualization/consoles",
                "doc://com.apple.virtualization/documentation/Virtualization/clipboard-sharing",
                "doc://com.apple.virtualization/documentation/Virtualization/usb-devices"
              ],
              "title": "Devices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZSocketDeviceConfiguration/title",
          "value": "VZSocketDeviceConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZSocketDeviceConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZSocketDeviceConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZSocketDeviceConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZSocketDeviceConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSocketDevice/title",
          "value": "VZVirtioSocketDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSocketDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtioSocketDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSocketDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtioSocketDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSocketDeviceConfiguration/title",
          "value": "VZVirtioSocketDeviceConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSocketDeviceConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtioSocketDeviceConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSocketDeviceConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtioSocketDeviceConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSocketConnection/title",
          "value": "VZVirtioSocketConnection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSocketConnection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtioSocketConnection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSocketConnection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtioSocketConnection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSocketListener/title",
          "value": "VZVirtioSocketListener"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSocketListener/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtioSocketListener"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSocketListener/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtioSocketListener"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZSocketDevice/title",
          "value": "VZSocketDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZSocketDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZSocketDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZSocketDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZSocketDevice"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/virtualization/sockets"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/virtualization/sockets"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
