{
  "abstract": [
    {
      "text": "Control the caching modes, disk synchronization, and macOS auxiliary storage options of VMs.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.virtualization/documentation/Virtualization"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.virtualization/documentation/Virtualization/virtualization-enumerations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Virtualization"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Virtualization enumerations"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "These are values you use to control aspects of the operation of the virtual drives for guest VMs and the auxiliary storage of macOS guest VMs.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.virtualization/documentation/Virtualization": {
      "abstract": [
        {
          "text": "Create virtual machines and run macOS and Linux-based operating systems.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization",
      "kind": "symbol",
      "role": "collection",
      "title": "Virtualization",
      "type": "topic",
      "url": "/documentation/virtualization"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageCachingMode": {
      "abstract": [
        {
          "text": "An integer that describes the disk image caching mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZDiskImageCachingMode"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageCachingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZDiskImageCachingMode"
        }
      ],
      "role": "symbol",
      "title": "VZDiskImageCachingMode",
      "type": "topic",
      "url": "/documentation/virtualization/vzdiskimagecachingmode"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageSynchronizationMode": {
      "abstract": [
        {
          "text": "An integer that describes the disk image synchronization mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZDiskImageSynchronizationMode"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageSynchronizationMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZDiskImageSynchronizationMode"
        }
      ],
      "role": "symbol",
      "title": "VZDiskImageSynchronizationMode",
      "type": "topic",
      "url": "/documentation/virtualization/vzdiskimagesynchronizationmode"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZDiskSynchronizationMode": {
      "abstract": [
        {
          "text": "Values that describe the synchronization modes available to the guest OS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZDiskSynchronizationMode"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZDiskSynchronizationMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZDiskSynchronizationMode"
        }
      ],
      "role": "symbol",
      "title": "VZDiskSynchronizationMode",
      "type": "topic",
      "url": "/documentation/virtualization/vzdisksynchronizationmode"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code": {
      "abstract": [
        {
          "text": "Errors you might encounter when configuring or using a virtual machine.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "VZError.Code",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/code"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaAvailability": {
      "abstract": [
        {
          "text": "Constants that describe the availability and installation status of Rosetta.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZLinuxRosettaAvailability"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaAvailability",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZLinuxRosettaAvailability"
        }
      ],
      "role": "symbol",
      "title": "VZLinuxRosettaAvailability",
      "type": "topic",
      "url": "/documentation/virtualization/vzlinuxrosettaavailability"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZMacAuxiliaryStorage/InitializationOptions": {
      "abstract": [
        {
          "text": "Options you can set when creating new auxiliary storage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "InitializationOptions"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMacAuxiliaryStorage/InitializationOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "InitializationOptions"
        }
      ],
      "role": "symbol",
      "title": "VZMacAuxiliaryStorage.InitializationOptions",
      "type": "topic",
      "url": "/documentation/virtualization/vzmacauxiliarystorage/initializationoptions"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum": {
      "abstract": [
        {
          "text": "The execution states of the VM.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "State"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "State"
        }
      ],
      "role": "symbol",
      "title": "VZVirtualMachine.State",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachine/state-swift.enum"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Virtual-disk-image-caching-modes",
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageCachingMode"
      ],
      "title": "Virtual disk image caching modes"
    },
    {
      "anchor": "Virtual-disk-synchronization-modes",
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageSynchronizationMode",
        "doc://com.apple.virtualization/documentation/Virtualization/VZDiskSynchronizationMode"
      ],
      "title": "Virtual disk synchronization modes"
    },
    {
      "anchor": "Mac-specific-auxiliary-storage-options",
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZMacAuxiliaryStorage/InitializationOptions"
      ],
      "title": "Mac-specific auxiliary storage options"
    },
    {
      "anchor": "Rosetta-availability-states",
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaAvailability"
      ],
      "title": "Rosetta availability states"
    },
    {
      "anchor": "Virtualization-error-codes",
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code"
      ],
      "title": "Virtualization error codes"
    },
    {
      "anchor": "VM-states",
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum"
      ],
      "title": "VM states"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Virtual-disk-image-caching-modes",
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageCachingMode"
              ],
              "title": "Virtual disk image caching modes"
            },
            {
              "anchor": "Virtual-disk-synchronization-modes",
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageSynchronizationMode",
                "doc://com.apple.virtualization/documentation/Virtualization/VZDiskSynchronizationMode"
              ],
              "title": "Virtual disk synchronization modes"
            },
            {
              "anchor": "Mac-specific-auxiliary-storage-options",
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/VZMacAuxiliaryStorage/InitializationOptions"
              ],
              "title": "Mac-specific auxiliary storage options"
            },
            {
              "anchor": "Rosetta-availability-states",
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaAvailability"
              ],
              "title": "Rosetta availability states"
            },
            {
              "anchor": "Virtualization-error-codes",
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code"
              ],
              "title": "Virtualization error codes"
            },
            {
              "anchor": "VM-states",
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum"
              ],
              "title": "VM states"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacAuxiliaryStorage~1InitializationOptions/title",
          "value": "VZMacAuxiliaryStorageInitializationOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacAuxiliaryStorage~1InitializationOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZMacAuxiliaryStorageInitializationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacAuxiliaryStorage~1InitializationOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZMacAuxiliaryStorageInitializationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZDiskImageSynchronizationMode/title",
          "value": "VZDiskImageSynchronizationMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZDiskImageSynchronizationMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZDiskImageSynchronizationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZDiskImageSynchronizationMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZDiskImageSynchronizationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum/title",
          "value": "VZVirtualMachineState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtualMachineState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtualMachineState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZLinuxRosettaAvailability/title",
          "value": "VZLinuxRosettaAvailability"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZLinuxRosettaAvailability/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZLinuxRosettaAvailability"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZLinuxRosettaAvailability/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZLinuxRosettaAvailability"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZDiskImageCachingMode/title",
          "value": "VZDiskImageCachingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZDiskImageCachingMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZDiskImageCachingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZDiskImageCachingMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZDiskImageCachingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code/title",
          "value": "VZErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZDiskSynchronizationMode/title",
          "value": "VZDiskSynchronizationMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZDiskSynchronizationMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZDiskSynchronizationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZDiskSynchronizationMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZDiskSynchronizationMode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/virtualization/virtualization-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/virtualization/virtualization-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
