{
  "abstract": [
    {
      "text": "Configure and run Linux guests on Apple silicon and Intel-based Mac computers.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.virtualization/documentation/Virtualization"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.virtualization/documentation/Virtualization/virtualize-linux-on-a-mac"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Virtualization"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Virtualize Linux on a Mac"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to create a configuration that represents a specific Linux platform with the devices you want to use with your virtual machine (VM) — like ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSoundDeviceConfiguration",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZUSBKeyboardConfiguration",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You use this configuration to load a Linux kernel image from disk that — using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxBootLoader",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " — runs in a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " that you control.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more information about running a Linux guest, including how to download kernel and RAM disk images, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.virtualization/documentation/Virtualization/creating-and-running-a-linux-virtual-machine",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". For more information about running GUI Linux virtual machines, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.virtualization/documentation/Virtualization/running-gui-linux-in-a-virtual-machine-on-a-mac",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.virtualization/documentation/Virtualization": {
      "abstract": [
        {
          "text": "Create virtual machines and run macOS and Linux-based operating systems.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization",
      "kind": "symbol",
      "role": "collection",
      "title": "Virtualization",
      "type": "topic",
      "url": "/documentation/virtualization"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZBootLoader": {
      "abstract": [
        {
          "text": "The base class that defines the management of the initial process of the guest system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZBootLoader"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZBootLoader",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZBootLoader"
        }
      ],
      "role": "symbol",
      "title": "VZBootLoader",
      "type": "topic",
      "url": "/documentation/virtualization/vzbootloader"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZEFIBootLoader": {
      "abstract": [
        {
          "text": "The boot loader configuration the system uses to boot guest-operating systems that expect an Extensible Firmware Interface (EFI) ROM.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZEFIBootLoader"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZEFIBootLoader",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZEFIBootLoader"
        }
      ],
      "role": "symbol",
      "title": "VZEFIBootLoader",
      "type": "topic",
      "url": "/documentation/virtualization/vzefibootloader"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZEFIVariableStore": {
      "abstract": [
        {
          "text": "An object that represents the Extensible Firmware Interface (EFI) variable store that contains NVRAM variables the EFI exposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZEFIVariableStore"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZEFIVariableStore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZEFIVariableStore"
        }
      ],
      "role": "symbol",
      "title": "VZEFIVariableStore",
      "type": "topic",
      "url": "/documentation/virtualization/vzefivariablestore"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZGenericPlatformConfiguration": {
      "abstract": [
        {
          "text": "The platform configuration for a generic Intel or ARM virtual machine.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZGenericPlatformConfiguration"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZGenericPlatformConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZGenericPlatformConfiguration"
        }
      ],
      "role": "symbol",
      "title": "VZGenericPlatformConfiguration",
      "type": "topic",
      "url": "/documentation/virtualization/vzgenericplatformconfiguration"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxBootLoader": {
      "abstract": [
        {
          "text": "An object that loads and configures a Linux kernel as the guest system of your VM.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZLinuxBootLoader"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxBootLoader",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZLinuxBootLoader"
        }
      ],
      "role": "symbol",
      "title": "VZLinuxBootLoader",
      "type": "topic",
      "url": "/documentation/virtualization/vzlinuxbootloader"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZPlatformConfiguration": {
      "abstract": [
        {
          "text": "The base class for a platform configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZPlatformConfiguration"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZPlatformConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZPlatformConfiguration"
        }
      ],
      "role": "symbol",
      "title": "VZPlatformConfiguration",
      "type": "topic",
      "url": "/documentation/virtualization/vzplatformconfiguration"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZUSBKeyboardConfiguration": {
      "abstract": [
        {
          "text": "A device that defines the configuration for a USB keyboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZUSBKeyboardConfiguration"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZUSBKeyboardConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZUSBKeyboardConfiguration"
        }
      ],
      "role": "symbol",
      "title": "VZUSBKeyboardConfiguration",
      "type": "topic",
      "url": "/documentation/virtualization/vzusbkeyboardconfiguration"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSoundDeviceConfiguration": {
      "abstract": [
        {
          "text": "An object that defines a Virtio sound device configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZVirtioSoundDeviceConfiguration"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSoundDeviceConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZVirtioSoundDeviceConfiguration"
        }
      ],
      "role": "symbol",
      "title": "VZVirtioSoundDeviceConfiguration",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtiosounddeviceconfiguration"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine": {
      "abstract": [
        {
          "text": "An object that manages the overall state and configuration of your VM.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZVirtualMachine"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZVirtualMachine"
        }
      ],
      "role": "symbol",
      "title": "VZVirtualMachine",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachine"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration": {
      "abstract": [
        {
          "text": "The environment attributes and list of devices to use during the configuration of macOS or Linux VMs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZVirtualMachineConfiguration"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZVirtualMachineConfiguration"
        }
      ],
      "role": "symbol",
      "title": "VZVirtualMachineConfiguration",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachineconfiguration"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineStartOptions": {
      "abstract": [
        {
          "text": "The abstract class for VM start options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZVirtualMachineStartOptions"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineStartOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZVirtualMachineStartOptions"
        }
      ],
      "role": "symbol",
      "title": "VZVirtualMachineStartOptions",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachinestartoptions"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/accelerating-the-performance-of-rosetta": {
      "abstract": [
        {
          "text": "Improve Rosetta performance by adding support for the total store ordering (TSO) memory model to your Linux kernel.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/accelerating-the-performance-of-rosetta",
      "kind": "article",
      "role": "article",
      "title": "Accelerating the performance of Rosetta",
      "type": "topic",
      "url": "/documentation/virtualization/accelerating-the-performance-of-rosetta"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/creating-and-running-a-linux-virtual-machine": {
      "abstract": [
        {
          "text": "Design and run custom Linux guests on Apple silicon or Intel-based Mac Computers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/creating-and-running-a-linux-virtual-machine",
      "kind": "article",
      "role": "article",
      "title": "Creating and Running a Linux Virtual Machine",
      "type": "topic",
      "url": "/documentation/virtualization/creating-and-running-a-linux-virtual-machine"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/installing-macos-on-a-virtual-machine": {
      "abstract": [
        {
          "text": "Download a macOS restore image and install it in a new VM.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/installing-macos-on-a-virtual-machine",
      "kind": "article",
      "role": "article",
      "title": "Installing macOS on a Virtual Machine",
      "type": "topic",
      "url": "/documentation/virtualization/installing-macos-on-a-virtual-machine"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/running-gui-linux-in-a-virtual-machine-on-a-mac": {
      "abstract": [
        {
          "text": "Install and run GUI Linux in a virtual machine using the Virtualization framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/running-gui-linux-in-a-virtual-machine-on-a-mac",
      "kind": "article",
      "role": "sampleCode",
      "title": "Running GUI Linux in a virtual machine on a Mac",
      "type": "topic",
      "url": "/documentation/virtualization/running-gui-linux-in-a-virtual-machine-on-a-mac"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/running-intel-binaries-in-linux-vms-with-rosetta": {
      "abstract": [
        {
          "text": "Run x86_64 Linux binaries under ARM Linux on Apple silicon.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/running-intel-binaries-in-linux-vms-with-rosetta",
      "kind": "article",
      "role": "article",
      "title": "Running Intel Binaries in Linux VMs with Rosetta",
      "type": "topic",
      "url": "/documentation/virtualization/running-intel-binaries-in-linux-vms-with-rosetta"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/running-linux-in-a-virtual-machine": {
      "abstract": [
        {
          "text": "Run a Linux operating system on your Mac using the Virtualization framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/running-linux-in-a-virtual-machine",
      "kind": "article",
      "role": "sampleCode",
      "title": "Running Linux in a Virtual Machine",
      "type": "topic",
      "url": "/documentation/virtualization/running-linux-in-a-virtual-machine"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/running-macos-in-a-virtual-machine-on-apple-silicon": {
      "abstract": [
        {
          "text": "Install and run macOS in a virtual machine using the Virtualization framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/running-macos-in-a-virtual-machine-on-apple-silicon",
      "kind": "article",
      "role": "sampleCode",
      "title": "Running macOS in a virtual machine on Apple silicon",
      "type": "topic",
      "url": "/documentation/virtualization/running-macos-in-a-virtual-machine-on-apple-silicon"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/virtualize-macos-on-a-mac": {
      "abstract": [
        {
          "text": "Configure and run macOS guests on Apple silicon.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/virtualize-macos-on-a-mac",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Virtualize macOS on a Mac",
      "type": "topic",
      "url": "/documentation/virtualization/virtualize-macos-on-a-mac"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Virtual-machine-setup",
      "generated": true,
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/running-macos-in-a-virtual-machine-on-apple-silicon",
        "doc://com.apple.virtualization/documentation/Virtualization/running-linux-in-a-virtual-machine",
        "doc://com.apple.virtualization/documentation/Virtualization/running-gui-linux-in-a-virtual-machine-on-a-mac",
        "doc://com.apple.virtualization/documentation/Virtualization/installing-macos-on-a-virtual-machine",
        "doc://com.apple.virtualization/documentation/Virtualization/creating-and-running-a-linux-virtual-machine",
        "doc://com.apple.virtualization/documentation/Virtualization/virtualize-macos-on-a-mac",
        "doc://com.apple.virtualization/documentation/Virtualization/running-intel-binaries-in-linux-vms-with-rosetta",
        "doc://com.apple.virtualization/documentation/Virtualization/accelerating-the-performance-of-rosetta"
      ],
      "title": "Virtual machine setup"
    }
  ],
  "topicSections": [
    {
      "anchor": "Configurations",
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineStartOptions",
        "doc://com.apple.virtualization/documentation/Virtualization/VZGenericPlatformConfiguration",
        "doc://com.apple.virtualization/documentation/Virtualization/VZPlatformConfiguration"
      ],
      "title": "Configurations"
    },
    {
      "anchor": "Boot-loaders",
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZBootLoader",
        "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxBootLoader",
        "doc://com.apple.virtualization/documentation/Virtualization/VZEFIBootLoader",
        "doc://com.apple.virtualization/documentation/Virtualization/VZEFIVariableStore"
      ],
      "title": "Boot loaders"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Configurations",
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineStartOptions",
                "doc://com.apple.virtualization/documentation/Virtualization/VZGenericPlatformConfiguration",
                "doc://com.apple.virtualization/documentation/Virtualization/VZPlatformConfiguration"
              ],
              "title": "Configurations"
            },
            {
              "anchor": "Boot-loaders",
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/VZBootLoader",
                "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxBootLoader",
                "doc://com.apple.virtualization/documentation/Virtualization/VZEFIBootLoader",
                "doc://com.apple.virtualization/documentation/Virtualization/VZEFIVariableStore"
              ],
              "title": "Boot loaders"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Virtual-machine-setup",
              "generated": true,
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/running-macos-in-a-virtual-machine-on-apple-silicon",
                "doc://com.apple.virtualization/documentation/Virtualization/running-linux-in-a-virtual-machine",
                "doc://com.apple.virtualization/documentation/Virtualization/running-gui-linux-in-a-virtual-machine-on-a-mac",
                "doc://com.apple.virtualization/documentation/Virtualization/installing-macos-on-a-virtual-machine",
                "doc://com.apple.virtualization/documentation/Virtualization/creating-and-running-a-linux-virtual-machine",
                "doc://com.apple.virtualization/documentation/Virtualization/virtualize-macos-on-a-mac",
                "doc://com.apple.virtualization/documentation/Virtualization/running-intel-binaries-in-linux-vms-with-rosetta",
                "doc://com.apple.virtualization/documentation/Virtualization/accelerating-the-performance-of-rosetta"
              ],
              "title": "Virtual machine setup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZLinuxBootLoader/title",
          "value": "VZLinuxBootLoader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZLinuxBootLoader/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZLinuxBootLoader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZLinuxBootLoader/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZLinuxBootLoader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZEFIVariableStore/title",
          "value": "VZEFIVariableStore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZEFIVariableStore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZEFIVariableStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZEFIVariableStore/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZEFIVariableStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZGenericPlatformConfiguration/title",
          "value": "VZGenericPlatformConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZGenericPlatformConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZGenericPlatformConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZGenericPlatformConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZGenericPlatformConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSoundDeviceConfiguration/title",
          "value": "VZVirtioSoundDeviceConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSoundDeviceConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtioSoundDeviceConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSoundDeviceConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtioSoundDeviceConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine/title",
          "value": "VZVirtualMachine"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtualMachine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtualMachine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZUSBKeyboardConfiguration/title",
          "value": "VZUSBKeyboardConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZUSBKeyboardConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZUSBKeyboardConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZUSBKeyboardConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZUSBKeyboardConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration/title",
          "value": "VZVirtualMachineConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtualMachineConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtualMachineConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineStartOptions/title",
          "value": "VZVirtualMachineStartOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineStartOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtualMachineStartOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineStartOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtualMachineStartOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZBootLoader/title",
          "value": "VZBootLoader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZBootLoader/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZBootLoader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZBootLoader/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZBootLoader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZPlatformConfiguration/title",
          "value": "VZPlatformConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZPlatformConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZPlatformConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZPlatformConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZPlatformConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZEFIBootLoader/title",
          "value": "VZEFIBootLoader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZEFIBootLoader/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZEFIBootLoader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZEFIBootLoader/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZEFIBootLoader"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/virtualization/virtualize-linux-on-a-mac"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/virtualization/virtualize-linux-on-a-mac"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
