{
  "abstract": [
    {
      "text": "Configure and run macOS guests on Apple silicon.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.virtualization/documentation/Virtualization"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.virtualization/documentation/Virtualization/virtualize-macos-on-a-mac"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Virtualization"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Virtualize macOS on a Mac"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to create a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMacPlatformConfiguration",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " that represents a specific macOS platform configuration (",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMacHardwareModel",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", number of virtual CPUs, RAM, devices, and so on) that you want to run on your Apple silicon Mac.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The Virtualization framework provides everything you need to macOS on a VM using macOS installation images you download from Apple. Use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSRestoreImage/latestSupported",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSRestoreImage",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to obtain the URL for the installation media used to install the latest version of macOS. Alternatively, if you’ve already downloaded a macOS release, you can construct a ",
              "type": "text"
            },
            {
              "code": "VZMacOSRestoreImage",
              "type": "codeVoice"
            },
            {
              "text": " object using that file. The ",
              "type": "text"
            },
            {
              "code": "mostFeaturefulSupportedConfiguration",
              "type": "codeVoice"
            },
            {
              "text": " property of a ",
              "type": "text"
            },
            {
              "code": "VZMacOSRestoreImage",
              "type": "codeVoice"
            },
            {
              "text": " object specifies the requirements and recommendations that you use to configure a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineDelegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to complete this installation. After creating a ",
              "type": "text"
            },
            {
              "code": "VZVirtualMachine",
              "type": "codeVoice"
            },
            {
              "text": ", use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSInstaller",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to install macOS on that virtual machine. You then use this configuration to create a bootable image that, along with a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSBootLoader",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", runs in a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " that you can control.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more information on running macOS as a guest, see ",
              "type": "text"
            },
            {
              "code": "Creating and Running a macOS Virtual Machine",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.virtualization/documentation/Virtualization": {
      "abstract": [
        {
          "text": "Create virtual machines and run macOS and Linux-based operating systems.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization",
      "kind": "symbol",
      "role": "collection",
      "title": "Virtualization",
      "type": "topic",
      "url": "/documentation/virtualization"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZBootLoader": {
      "abstract": [
        {
          "text": "The base class that defines the management of the initial process of the guest system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZBootLoader"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZBootLoader",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZBootLoader"
        }
      ],
      "role": "symbol",
      "title": "VZBootLoader",
      "type": "topic",
      "url": "/documentation/virtualization/vzbootloader"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZMacAuxiliaryStorage": {
      "abstract": [
        {
          "text": "An object that contains information the boot loader needs for booting macOS as a guest operating system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZMacAuxiliaryStorage"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMacAuxiliaryStorage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZMacAuxiliaryStorage"
        }
      ],
      "role": "symbol",
      "title": "VZMacAuxiliaryStorage",
      "type": "topic",
      "url": "/documentation/virtualization/vzmacauxiliarystorage"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZMacHardwareModel": {
      "abstract": [
        {
          "text": "A specification for the hardware elements and configurations present in a particular Mac hardware model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZMacHardwareModel"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMacHardwareModel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZMacHardwareModel"
        }
      ],
      "role": "symbol",
      "title": "VZMacHardwareModel",
      "type": "topic",
      "url": "/documentation/virtualization/vzmachardwaremodel"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZMacMachineIdentifier": {
      "abstract": [
        {
          "text": "A unique identifier for a VM.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZMacMachineIdentifier"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMacMachineIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZMacMachineIdentifier"
        }
      ],
      "role": "symbol",
      "title": "VZMacMachineIdentifier",
      "type": "topic",
      "url": "/documentation/virtualization/vzmacmachineidentifier"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSBootLoader": {
      "abstract": [
        {
          "text": "An object that loads and configures a boot loader for running macOS on Apple silicon as a guest system of your VM.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZMacOSBootLoader"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSBootLoader",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZMacOSBootLoader"
        }
      ],
      "role": "symbol",
      "title": "VZMacOSBootLoader",
      "type": "topic",
      "url": "/documentation/virtualization/vzmacosbootloader"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSConfigurationRequirements": {
      "abstract": [
        {
          "text": "An object that describes the parameter constraints required by a specific configuration of macOS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZMacOSConfigurationRequirements"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSConfigurationRequirements",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZMacOSConfigurationRequirements"
        }
      ],
      "role": "symbol",
      "title": "VZMacOSConfigurationRequirements",
      "type": "topic",
      "url": "/documentation/virtualization/vzmacosconfigurationrequirements"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSInstaller": {
      "abstract": [
        {
          "text": "An object you use to install macOS on the specified virtual machine.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZMacOSInstaller"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSInstaller",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZMacOSInstaller"
        }
      ],
      "role": "symbol",
      "title": "VZMacOSInstaller",
      "type": "topic",
      "url": "/documentation/virtualization/vzmacosinstaller"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSRestoreImage": {
      "abstract": [
        {
          "text": "An object that describes a version of macOS to install on to a virtual machine.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZMacOSRestoreImage"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSRestoreImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZMacOSRestoreImage"
        }
      ],
      "role": "symbol",
      "title": "VZMacOSRestoreImage",
      "type": "topic",
      "url": "/documentation/virtualization/vzmacosrestoreimage"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSRestoreImage/latestSupported": {
      "abstract": [
        {
          "text": "Fetches the latest restore image supported by this host from the network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "latestSupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VZMacOSRestoreImage",
          "text": "VZMacOSRestoreImage"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSRestoreImage/latestSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fetchLatestSupportedWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "latestSupported",
      "type": "topic",
      "url": "/documentation/virtualization/vzmacosrestoreimage/latestsupported"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSVirtualMachineStartOptions": {
      "abstract": [
        {
          "text": "A class that describes start options for macOS VMs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZMacOSVirtualMachineStartOptions"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSVirtualMachineStartOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZMacOSVirtualMachineStartOptions"
        }
      ],
      "role": "symbol",
      "title": "VZMacOSVirtualMachineStartOptions",
      "type": "topic",
      "url": "/documentation/virtualization/vzmacosvirtualmachinestartoptions"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZMacPlatformConfiguration": {
      "abstract": [
        {
          "text": "The platform configuration for booting macOS on Apple silicon.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZMacPlatformConfiguration"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMacPlatformConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZMacPlatformConfiguration"
        }
      ],
      "role": "symbol",
      "title": "VZMacPlatformConfiguration",
      "type": "topic",
      "url": "/documentation/virtualization/vzmacplatformconfiguration"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZPlatformConfiguration": {
      "abstract": [
        {
          "text": "The base class for a platform configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZPlatformConfiguration"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZPlatformConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZPlatformConfiguration"
        }
      ],
      "role": "symbol",
      "title": "VZPlatformConfiguration",
      "type": "topic",
      "url": "/documentation/virtualization/vzplatformconfiguration"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine": {
      "abstract": [
        {
          "text": "An object that manages the overall state and configuration of your VM.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZVirtualMachine"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZVirtualMachine"
        }
      ],
      "role": "symbol",
      "title": "VZVirtualMachine",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachine"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration": {
      "abstract": [
        {
          "text": "The environment attributes and list of devices to use during the configuration of macOS or Linux VMs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZVirtualMachineConfiguration"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZVirtualMachineConfiguration"
        }
      ],
      "role": "symbol",
      "title": "VZVirtualMachineConfiguration",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachineconfiguration"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineDelegate": {
      "abstract": [
        {
          "text": "The methods you use to respond to changes in the state of the VM.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZVirtualMachineDelegate"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZVirtualMachineDelegate"
        }
      ],
      "role": "symbol",
      "title": "VZVirtualMachineDelegate",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachinedelegate"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/accelerating-the-performance-of-rosetta": {
      "abstract": [
        {
          "text": "Improve Rosetta performance by adding support for the total store ordering (TSO) memory model to your Linux kernel.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/accelerating-the-performance-of-rosetta",
      "kind": "article",
      "role": "article",
      "title": "Accelerating the performance of Rosetta",
      "type": "topic",
      "url": "/documentation/virtualization/accelerating-the-performance-of-rosetta"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/creating-and-running-a-linux-virtual-machine": {
      "abstract": [
        {
          "text": "Design and run custom Linux guests on Apple silicon or Intel-based Mac Computers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/creating-and-running-a-linux-virtual-machine",
      "kind": "article",
      "role": "article",
      "title": "Creating and Running a Linux Virtual Machine",
      "type": "topic",
      "url": "/documentation/virtualization/creating-and-running-a-linux-virtual-machine"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/installing-macos-on-a-virtual-machine": {
      "abstract": [
        {
          "text": "Download a macOS restore image and install it in a new VM.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/installing-macos-on-a-virtual-machine",
      "kind": "article",
      "role": "article",
      "title": "Installing macOS on a Virtual Machine",
      "type": "topic",
      "url": "/documentation/virtualization/installing-macos-on-a-virtual-machine"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/running-gui-linux-in-a-virtual-machine-on-a-mac": {
      "abstract": [
        {
          "text": "Install and run GUI Linux in a virtual machine using the Virtualization framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/running-gui-linux-in-a-virtual-machine-on-a-mac",
      "kind": "article",
      "role": "sampleCode",
      "title": "Running GUI Linux in a virtual machine on a Mac",
      "type": "topic",
      "url": "/documentation/virtualization/running-gui-linux-in-a-virtual-machine-on-a-mac"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/running-intel-binaries-in-linux-vms-with-rosetta": {
      "abstract": [
        {
          "text": "Run x86_64 Linux binaries under ARM Linux on Apple silicon.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/running-intel-binaries-in-linux-vms-with-rosetta",
      "kind": "article",
      "role": "article",
      "title": "Running Intel Binaries in Linux VMs with Rosetta",
      "type": "topic",
      "url": "/documentation/virtualization/running-intel-binaries-in-linux-vms-with-rosetta"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/running-linux-in-a-virtual-machine": {
      "abstract": [
        {
          "text": "Run a Linux operating system on your Mac using the Virtualization framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/running-linux-in-a-virtual-machine",
      "kind": "article",
      "role": "sampleCode",
      "title": "Running Linux in a Virtual Machine",
      "type": "topic",
      "url": "/documentation/virtualization/running-linux-in-a-virtual-machine"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/running-macos-in-a-virtual-machine-on-apple-silicon": {
      "abstract": [
        {
          "text": "Install and run macOS in a virtual machine using the Virtualization framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/running-macos-in-a-virtual-machine-on-apple-silicon",
      "kind": "article",
      "role": "sampleCode",
      "title": "Running macOS in a virtual machine on Apple silicon",
      "type": "topic",
      "url": "/documentation/virtualization/running-macos-in-a-virtual-machine-on-apple-silicon"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/virtualize-linux-on-a-mac": {
      "abstract": [
        {
          "text": "Configure and run Linux guests on Apple silicon and Intel-based Mac computers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/virtualize-linux-on-a-mac",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Virtualize Linux on a Mac",
      "type": "topic",
      "url": "/documentation/virtualization/virtualize-linux-on-a-mac"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Virtual-machine-setup",
      "generated": true,
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/running-macos-in-a-virtual-machine-on-apple-silicon",
        "doc://com.apple.virtualization/documentation/Virtualization/running-linux-in-a-virtual-machine",
        "doc://com.apple.virtualization/documentation/Virtualization/running-gui-linux-in-a-virtual-machine-on-a-mac",
        "doc://com.apple.virtualization/documentation/Virtualization/installing-macos-on-a-virtual-machine",
        "doc://com.apple.virtualization/documentation/Virtualization/creating-and-running-a-linux-virtual-machine",
        "doc://com.apple.virtualization/documentation/Virtualization/virtualize-linux-on-a-mac",
        "doc://com.apple.virtualization/documentation/Virtualization/running-intel-binaries-in-linux-vms-with-rosetta",
        "doc://com.apple.virtualization/documentation/Virtualization/accelerating-the-performance-of-rosetta"
      ],
      "title": "Virtual machine setup"
    }
  ],
  "topicSections": [
    {
      "abstract": [
        {
          "text": "Configure macOS guests with specific hardware capabilities and unique hardware identifiers.",
          "type": "text"
        }
      ],
      "anchor": "Platform-components",
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration",
        "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSVirtualMachineStartOptions",
        "doc://com.apple.virtualization/documentation/Virtualization/VZMacPlatformConfiguration",
        "doc://com.apple.virtualization/documentation/Virtualization/VZPlatformConfiguration",
        "doc://com.apple.virtualization/documentation/Virtualization/VZMacHardwareModel",
        "doc://com.apple.virtualization/documentation/Virtualization/VZMacMachineIdentifier",
        "doc://com.apple.virtualization/documentation/Virtualization/VZMacAuxiliaryStorage"
      ],
      "title": "Platform components"
    },
    {
      "abstract": [
        {
          "text": "Create macOS boot loaders for running macOS on Apple silicon.",
          "type": "text"
        }
      ],
      "anchor": "Boot-images",
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSBootLoader",
        "doc://com.apple.virtualization/documentation/Virtualization/VZBootLoader"
      ],
      "title": "Boot images"
    },
    {
      "abstract": [
        {
          "text": "Create macOS installation and restoration images.",
          "type": "text"
        }
      ],
      "anchor": "Installers",
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSInstaller",
        "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSRestoreImage",
        "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSConfigurationRequirements"
      ],
      "title": "Installers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "abstract": [
                {
                  "text": "Configure macOS guests with specific hardware capabilities and unique hardware identifiers.",
                  "type": "text"
                }
              ],
              "anchor": "Platform-components",
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration",
                "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSVirtualMachineStartOptions",
                "doc://com.apple.virtualization/documentation/Virtualization/VZMacPlatformConfiguration",
                "doc://com.apple.virtualization/documentation/Virtualization/VZPlatformConfiguration",
                "doc://com.apple.virtualization/documentation/Virtualization/VZMacHardwareModel",
                "doc://com.apple.virtualization/documentation/Virtualization/VZMacMachineIdentifier",
                "doc://com.apple.virtualization/documentation/Virtualization/VZMacAuxiliaryStorage"
              ],
              "title": "Platform components"
            },
            {
              "abstract": [
                {
                  "text": "Create macOS boot loaders for running macOS on Apple silicon.",
                  "type": "text"
                }
              ],
              "anchor": "Boot-images",
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSBootLoader",
                "doc://com.apple.virtualization/documentation/Virtualization/VZBootLoader"
              ],
              "title": "Boot images"
            },
            {
              "abstract": [
                {
                  "text": "Create macOS installation and restoration images.",
                  "type": "text"
                }
              ],
              "anchor": "Installers",
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSInstaller",
                "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSRestoreImage",
                "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSConfigurationRequirements"
              ],
              "title": "Installers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Virtual-machine-setup",
              "generated": true,
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/running-macos-in-a-virtual-machine-on-apple-silicon",
                "doc://com.apple.virtualization/documentation/Virtualization/running-linux-in-a-virtual-machine",
                "doc://com.apple.virtualization/documentation/Virtualization/running-gui-linux-in-a-virtual-machine-on-a-mac",
                "doc://com.apple.virtualization/documentation/Virtualization/installing-macos-on-a-virtual-machine",
                "doc://com.apple.virtualization/documentation/Virtualization/creating-and-running-a-linux-virtual-machine",
                "doc://com.apple.virtualization/documentation/Virtualization/virtualize-linux-on-a-mac",
                "doc://com.apple.virtualization/documentation/Virtualization/running-intel-binaries-in-linux-vms-with-rosetta",
                "doc://com.apple.virtualization/documentation/Virtualization/accelerating-the-performance-of-rosetta"
              ],
              "title": "Virtual machine setup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacOSRestoreImage/title",
          "value": "VZMacOSRestoreImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacOSRestoreImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZMacOSRestoreImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacOSRestoreImage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZMacOSRestoreImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration/title",
          "value": "VZVirtualMachineConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtualMachineConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtualMachineConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacOSConfigurationRequirements/title",
          "value": "VZMacOSConfigurationRequirements"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacOSConfigurationRequirements/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZMacOSConfigurationRequirements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacOSConfigurationRequirements/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZMacOSConfigurationRequirements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacOSBootLoader/title",
          "value": "VZMacOSBootLoader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacOSBootLoader/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZMacOSBootLoader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacOSBootLoader/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZMacOSBootLoader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZBootLoader/title",
          "value": "VZBootLoader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZBootLoader/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZBootLoader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZBootLoader/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZBootLoader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacMachineIdentifier/title",
          "value": "VZMacMachineIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacMachineIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZMacMachineIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacMachineIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZMacMachineIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacOSRestoreImage~1latestSupported/title",
          "value": "fetchLatestSupportedWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacOSRestoreImage~1latestSupported/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "fetchLatestSupportedWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZPlatformConfiguration/title",
          "value": "VZPlatformConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZPlatformConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZPlatformConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZPlatformConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZPlatformConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacPlatformConfiguration/title",
          "value": "VZMacPlatformConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacPlatformConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZMacPlatformConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacPlatformConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZMacPlatformConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacOSVirtualMachineStartOptions/title",
          "value": "VZMacOSVirtualMachineStartOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacOSVirtualMachineStartOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZMacOSVirtualMachineStartOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacOSVirtualMachineStartOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZMacOSVirtualMachineStartOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacOSInstaller/title",
          "value": "VZMacOSInstaller"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacOSInstaller/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZMacOSInstaller"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacOSInstaller/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZMacOSInstaller"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineDelegate/title",
          "value": "VZVirtualMachineDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtualMachineDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtualMachineDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacHardwareModel/title",
          "value": "VZMacHardwareModel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacHardwareModel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZMacHardwareModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacHardwareModel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZMacHardwareModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine/title",
          "value": "VZVirtualMachine"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtualMachine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtualMachine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacAuxiliaryStorage/title",
          "value": "VZMacAuxiliaryStorage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacAuxiliaryStorage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZMacAuxiliaryStorage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacAuxiliaryStorage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZMacAuxiliaryStorage"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/virtualization/virtualize-macos-on-a-mac"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/virtualization/virtualize-macos-on-a-mac"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
