{
  "abstract": [
    {
      "text": "An integer that describes the disk image caching mode.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.virtualization/documentation/Virtualization"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageCachingMode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@VZDiskImageCachingMode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "VZDiskImageCachingMode"
      }
    ],
    "modules": [
      {
        "name": "Virtualization"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VZDiskImageCachingMode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "VZDiskImageCachingMode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "VZDiskImageCachingMode"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.virtualization/documentation/Virtualization": {
      "abstract": [
        {
          "text": "Create virtual machines and run macOS and Linux-based operating systems.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization",
      "kind": "symbol",
      "role": "collection",
      "title": "Virtualization",
      "type": "topic",
      "url": "/documentation/virtualization"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageCachingMode": {
      "abstract": [
        {
          "text": "An integer that describes the disk image caching mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZDiskImageCachingMode"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageCachingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZDiskImageCachingMode"
        }
      ],
      "role": "symbol",
      "title": "VZDiskImageCachingMode",
      "type": "topic",
      "url": "/documentation/virtualization/vzdiskimagecachingmode"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageCachingMode/automatic": {
      "abstract": [
        {
          "text": "Allows the virtualization framework to automatically determine whether to enable data caching.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automatic"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageCachingMode/automatic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZDiskImageCachingModeAutomatic"
        }
      ],
      "role": "symbol",
      "title": "VZDiskImageCachingMode.automatic",
      "type": "topic",
      "url": "/documentation/virtualization/vzdiskimagecachingmode/automatic"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageCachingMode/cached": {
      "abstract": [
        {
          "text": "Enables data caching.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cached"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageCachingMode/cached",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZDiskImageCachingModeCached"
        }
      ],
      "role": "symbol",
      "title": "VZDiskImageCachingMode.cached",
      "type": "topic",
      "url": "/documentation/virtualization/vzdiskimagecachingmode/cached"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageCachingMode/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageCachingMode/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/virtualization/vzdiskimagecachingmode/init(rawvalue:)"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageCachingMode/uncached": {
      "abstract": [
        {
          "text": "Disables data caching.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uncached"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageCachingMode/uncached",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZDiskImageCachingModeUncached"
        }
      ],
      "role": "symbol",
      "title": "VZDiskImageCachingMode.uncached",
      "type": "topic",
      "url": "/documentation/virtualization/vzdiskimagecachingmode/uncached"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageSynchronizationMode": {
      "abstract": [
        {
          "text": "An integer that describes the disk image synchronization mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZDiskImageSynchronizationMode"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageSynchronizationMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZDiskImageSynchronizationMode"
        }
      ],
      "role": "symbol",
      "title": "VZDiskImageSynchronizationMode",
      "type": "topic",
      "url": "/documentation/virtualization/vzdiskimagesynchronizationmode"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZNVMExpressControllerDeviceConfiguration": {
      "abstract": [
        {
          "text": "The configuration object that represents an NVM Express Controller storage device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZNVMExpressControllerDeviceConfiguration"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZNVMExpressControllerDeviceConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZNVMExpressControllerDeviceConfiguration"
        }
      ],
      "role": "symbol",
      "title": "VZNVMExpressControllerDeviceConfiguration",
      "type": "topic",
      "url": "/documentation/virtualization/vznvmexpresscontrollerdeviceconfiguration"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZStorageDeviceConfiguration": {
      "abstract": [
        {
          "text": "The common configuration traits for storage device requests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZStorageDeviceConfiguration"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZStorageDeviceConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZStorageDeviceConfiguration"
        }
      ],
      "role": "symbol",
      "title": "VZStorageDeviceConfiguration",
      "type": "topic",
      "url": "/documentation/virtualization/vzstoragedeviceconfiguration"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZUSBMassStorageDeviceConfiguration": {
      "abstract": [
        {
          "text": "The configuration object that represents a USB Mass storage device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZUSBMassStorageDeviceConfiguration"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZUSBMassStorageDeviceConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZUSBMassStorageDeviceConfiguration"
        }
      ],
      "role": "symbol",
      "title": "VZUSBMassStorageDeviceConfiguration",
      "type": "topic",
      "url": "/documentation/virtualization/vzusbmassstoragedeviceconfiguration"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioBlockDeviceConfiguration": {
      "abstract": [
        {
          "text": "The configuration object that requests the creation of a virtual storage device in the guest system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZVirtioBlockDeviceConfiguration"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioBlockDeviceConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZVirtioBlockDeviceConfiguration"
        }
      ],
      "role": "symbol",
      "title": "VZVirtioBlockDeviceConfiguration",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtioblockdeviceconfiguration"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configurations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioBlockDeviceConfiguration",
        "doc://com.apple.virtualization/documentation/Virtualization/VZStorageDeviceConfiguration",
        "doc://com.apple.virtualization/documentation/Virtualization/VZUSBMassStorageDeviceConfiguration",
        "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageSynchronizationMode",
        "doc://com.apple.virtualization/documentation/Virtualization/VZNVMExpressControllerDeviceConfiguration"
      ],
      "title": "Configurations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Disk-image-caching-modes",
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageCachingMode/automatic",
        "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageCachingMode/cached",
        "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageCachingMode/uncached"
      ],
      "title": "Disk image caching modes"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageCachingMode/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VZDiskImageCachingMode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZDiskImageCachingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZDiskImageCachingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.virtualization/documentation/Virtualization"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Disk-image-caching-modes",
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageCachingMode/automatic",
                "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageCachingMode/cached",
                "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageCachingMode/uncached"
              ],
              "title": "Disk image caching modes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configurations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioBlockDeviceConfiguration",
                "doc://com.apple.virtualization/documentation/Virtualization/VZStorageDeviceConfiguration",
                "doc://com.apple.virtualization/documentation/Virtualization/VZUSBMassStorageDeviceConfiguration",
                "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageSynchronizationMode",
                "doc://com.apple.virtualization/documentation/Virtualization/VZNVMExpressControllerDeviceConfiguration"
              ],
              "title": "Configurations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "VZDiskImageCachingMode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZNVMExpressControllerDeviceConfiguration/title",
          "value": "VZNVMExpressControllerDeviceConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZNVMExpressControllerDeviceConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZNVMExpressControllerDeviceConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZNVMExpressControllerDeviceConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZNVMExpressControllerDeviceConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZDiskImageSynchronizationMode/title",
          "value": "VZDiskImageSynchronizationMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZDiskImageSynchronizationMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZDiskImageSynchronizationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZDiskImageSynchronizationMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZDiskImageSynchronizationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZDiskImageCachingMode/title",
          "value": "VZDiskImageCachingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZDiskImageCachingMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZDiskImageCachingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZDiskImageCachingMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZDiskImageCachingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZDiskImageCachingMode~1cached/title",
          "value": "VZDiskImageCachingModeCached"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZDiskImageCachingMode~1cached/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZDiskImageCachingModeCached"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZUSBMassStorageDeviceConfiguration/title",
          "value": "VZUSBMassStorageDeviceConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZUSBMassStorageDeviceConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZUSBMassStorageDeviceConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZUSBMassStorageDeviceConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZUSBMassStorageDeviceConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZStorageDeviceConfiguration/title",
          "value": "VZStorageDeviceConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZStorageDeviceConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZStorageDeviceConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZStorageDeviceConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZStorageDeviceConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZDiskImageCachingMode~1automatic/title",
          "value": "VZDiskImageCachingModeAutomatic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZDiskImageCachingMode~1automatic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZDiskImageCachingModeAutomatic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZDiskImageCachingMode~1uncached/title",
          "value": "VZDiskImageCachingModeUncached"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZDiskImageCachingMode~1uncached/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZDiskImageCachingModeUncached"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioBlockDeviceConfiguration/title",
          "value": "VZVirtioBlockDeviceConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioBlockDeviceConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtioBlockDeviceConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioBlockDeviceConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtioBlockDeviceConfiguration"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/virtualization/vzdiskimagecachingmode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/virtualization/vzdiskimagecachingmode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
