{
  "abstract": [
    {
      "text": "A device that stores content in a disk image.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.virtualization/documentation/Virtualization"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageStorageDeviceAttachment"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)VZDiskImageStorageDeviceAttachment",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "VZDiskImageStorageDeviceAttachment"
      }
    ],
    "modules": [
      {
        "name": "Virtualization"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VZDiskImageStorageDeviceAttachment"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "VZDiskImageStorageDeviceAttachment"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "VZDiskImageStorageDeviceAttachment"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageStorageDeviceAttachment",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object to manage the storage for a disk in the virtual machine. The guest operating system sees the storage as a disk. When the guest operating system writes files to disk, the virtual machine stores those files in the disk image you provide.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Create a RAW disk image in the file system of the host computer, and use that disk image to initialize your ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageStorageDeviceAttachment",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. Use the attachment object to configure the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioBlockDeviceConfiguration",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object that you add to your virtual machine’s configuration.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.virtualization/documentation/Virtualization": {
      "abstract": [
        {
          "text": "Create virtual machines and run macOS and Linux-based operating systems.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization",
      "kind": "symbol",
      "role": "collection",
      "title": "Virtualization",
      "type": "topic",
      "url": "/documentation/virtualization"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZDiskBlockDeviceStorageDeviceAttachment": {
      "abstract": [
        {
          "text": "A storage device attachment that uses a disk to store data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZDiskBlockDeviceStorageDeviceAttachment"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZDiskBlockDeviceStorageDeviceAttachment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZDiskBlockDeviceStorageDeviceAttachment"
        }
      ],
      "role": "symbol",
      "title": "VZDiskBlockDeviceStorageDeviceAttachment",
      "type": "topic",
      "url": "/documentation/virtualization/vzdiskblockdevicestoragedeviceattachment"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageStorageDeviceAttachment": {
      "abstract": [
        {
          "text": "A device that stores content in a disk image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZDiskImageStorageDeviceAttachment"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageStorageDeviceAttachment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZDiskImageStorageDeviceAttachment"
        }
      ],
      "role": "symbol",
      "title": "VZDiskImageStorageDeviceAttachment",
      "type": "topic",
      "url": "/documentation/virtualization/vzdiskimagestoragedeviceattachment"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageStorageDeviceAttachment/cachingMode": {
      "abstract": [
        {
          "text": "The current cacheing mode for the virtual disk image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cachingMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VZDiskImageCachingMode",
          "text": "VZDiskImageCachingMode"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageStorageDeviceAttachment/cachingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cachingMode"
        }
      ],
      "role": "symbol",
      "title": "cachingMode",
      "type": "topic",
      "url": "/documentation/virtualization/vzdiskimagestoragedeviceattachment/cachingmode"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageStorageDeviceAttachment/init(url:readOnly:)": {
      "abstract": [
        {
          "text": "Creates the attachment object from the specified disk image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "url"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "readOnly"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageStorageDeviceAttachment/init(url:readOnly:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithURL:readOnly:error:"
        }
      ],
      "role": "symbol",
      "title": "init(url:readOnly:)",
      "type": "topic",
      "url": "/documentation/virtualization/vzdiskimagestoragedeviceattachment/init(url:readonly:)"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageStorageDeviceAttachment/init(url:readOnly:cachingMode:synchronizationMode:)": {
      "abstract": [
        {
          "text": "Initialize the attachment from a local file URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "url"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "readOnly"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "cachingMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VZDiskImageCachingMode",
          "text": "VZDiskImageCachingMode"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "synchronizationMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VZDiskImageSynchronizationMode",
          "text": "VZDiskImageSynchronizationMode"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageStorageDeviceAttachment/init(url:readOnly:cachingMode:synchronizationMode:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithURL:readOnly:cachingMode:synchronizationMode:error:"
        }
      ],
      "role": "symbol",
      "title": "init(url:readOnly:cachingMode:synchronizationMode:)",
      "type": "topic",
      "url": "/documentation/virtualization/vzdiskimagestoragedeviceattachment/init(url:readonly:cachingmode:synchronizationmode:)"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageStorageDeviceAttachment/isReadOnly": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the underlying disk image is read-only.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isReadOnly"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageStorageDeviceAttachment/isReadOnly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readOnly"
        }
      ],
      "role": "symbol",
      "title": "isReadOnly",
      "type": "topic",
      "url": "/documentation/virtualization/vzdiskimagestoragedeviceattachment/isreadonly"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageStorageDeviceAttachment/synchronizationMode": {
      "abstract": [
        {
          "text": "The mode in which the disk image synchronizes data with the underlying storage device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "synchronizationMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VZDiskImageSynchronizationMode",
          "text": "VZDiskImageSynchronizationMode"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageStorageDeviceAttachment/synchronizationMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "synchronizationMode"
        }
      ],
      "role": "symbol",
      "title": "synchronizationMode",
      "type": "topic",
      "url": "/documentation/virtualization/vzdiskimagestoragedeviceattachment/synchronizationmode"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageStorageDeviceAttachment/url": {
      "abstract": [
        {
          "text": "The URL of the underlying disk image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "url"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageStorageDeviceAttachment/url",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "URL"
        }
      ],
      "role": "symbol",
      "title": "url",
      "type": "topic",
      "url": "/documentation/virtualization/vzdiskimagestoragedeviceattachment/url"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZNetworkBlockDeviceStorageDeviceAttachment": {
      "abstract": [
        {
          "text": "A storage device attachment backed by a Network Block Device (NBD) client.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZNetworkBlockDeviceStorageDeviceAttachment"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZNetworkBlockDeviceStorageDeviceAttachment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZNetworkBlockDeviceStorageDeviceAttachment"
        }
      ],
      "role": "symbol",
      "title": "VZNetworkBlockDeviceStorageDeviceAttachment",
      "type": "topic",
      "url": "/documentation/virtualization/vznetworkblockdevicestoragedeviceattachment"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZStorageDeviceAttachment": {
      "abstract": [
        {
          "text": "The common behaviors for storage devices in the guest system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZStorageDeviceAttachment"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZStorageDeviceAttachment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZStorageDeviceAttachment"
        }
      ],
      "role": "symbol",
      "title": "VZStorageDeviceAttachment",
      "type": "topic",
      "url": "/documentation/virtualization/vzstoragedeviceattachment"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioBlockDeviceConfiguration": {
      "abstract": [
        {
          "text": "The configuration object that requests the creation of a virtual storage device in the guest system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZVirtioBlockDeviceConfiguration"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioBlockDeviceConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZVirtioBlockDeviceConfiguration"
        }
      ],
      "role": "symbol",
      "title": "VZVirtioBlockDeviceConfiguration",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtioblockdeviceconfiguration"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZStorageDeviceAttachment"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Attachment-points",
      "generated": true,
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZDiskBlockDeviceStorageDeviceAttachment",
        "doc://com.apple.virtualization/documentation/Virtualization/VZNetworkBlockDeviceStorageDeviceAttachment",
        "doc://com.apple.virtualization/documentation/Virtualization/VZStorageDeviceAttachment"
      ],
      "title": "Attachment points"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-the-attachment-point",
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageStorageDeviceAttachment/init(url:readOnly:)",
        "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageStorageDeviceAttachment/init(url:readOnly:cachingMode:synchronizationMode:)"
      ],
      "title": "Creating the attachment point"
    },
    {
      "anchor": "Getting-the-disk-image-details",
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageStorageDeviceAttachment/url",
        "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageStorageDeviceAttachment/isReadOnly",
        "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageStorageDeviceAttachment/cachingMode",
        "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageStorageDeviceAttachment/synchronizationMode"
      ],
      "title": "Getting the disk image details"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VZDiskImageStorageDeviceAttachment"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZDiskImageStorageDeviceAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZDiskImageStorageDeviceAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.virtualization/documentation/Virtualization"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-the-attachment-point",
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageStorageDeviceAttachment/init(url:readOnly:)",
                "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageStorageDeviceAttachment/init(url:readOnly:cachingMode:synchronizationMode:)"
              ],
              "title": "Creating the attachment point"
            },
            {
              "anchor": "Getting-the-disk-image-details",
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageStorageDeviceAttachment/url",
                "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageStorageDeviceAttachment/isReadOnly",
                "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageStorageDeviceAttachment/cachingMode",
                "doc://com.apple.virtualization/documentation/Virtualization/VZDiskImageStorageDeviceAttachment/synchronizationMode"
              ],
              "title": "Getting the disk image details"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/VZStorageDeviceAttachment"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Attachment-points",
              "generated": true,
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/VZDiskBlockDeviceStorageDeviceAttachment",
                "doc://com.apple.virtualization/documentation/Virtualization/VZNetworkBlockDeviceStorageDeviceAttachment",
                "doc://com.apple.virtualization/documentation/Virtualization/VZStorageDeviceAttachment"
              ],
              "title": "Attachment points"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "VZDiskImageStorageDeviceAttachment"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZStorageDeviceAttachment",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)VZStorageDeviceAttachment",
                    "text": "VZStorageDeviceAttachment"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZStorageDeviceAttachment/title",
          "value": "VZStorageDeviceAttachment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZStorageDeviceAttachment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZStorageDeviceAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZStorageDeviceAttachment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZStorageDeviceAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZDiskImageStorageDeviceAttachment~1cachingMode/title",
          "value": "cachingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZDiskImageStorageDeviceAttachment~1cachingMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cachingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZDiskImageStorageDeviceAttachment/title",
          "value": "VZDiskImageStorageDeviceAttachment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZDiskImageStorageDeviceAttachment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZDiskImageStorageDeviceAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZDiskImageStorageDeviceAttachment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZDiskImageStorageDeviceAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZDiskImageStorageDeviceAttachment~1url/title",
          "value": "URL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZDiskImageStorageDeviceAttachment~1url/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "URL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioBlockDeviceConfiguration/title",
          "value": "VZVirtioBlockDeviceConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioBlockDeviceConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtioBlockDeviceConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioBlockDeviceConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtioBlockDeviceConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZDiskImageStorageDeviceAttachment~1synchronizationMode/title",
          "value": "synchronizationMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZDiskImageStorageDeviceAttachment~1synchronizationMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "synchronizationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZNetworkBlockDeviceStorageDeviceAttachment/title",
          "value": "VZNetworkBlockDeviceStorageDeviceAttachment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZNetworkBlockDeviceStorageDeviceAttachment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZNetworkBlockDeviceStorageDeviceAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZNetworkBlockDeviceStorageDeviceAttachment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZNetworkBlockDeviceStorageDeviceAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZDiskImageStorageDeviceAttachment~1init(url:readOnly:)/title",
          "value": "initWithURL:readOnly:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZDiskImageStorageDeviceAttachment~1init(url:readOnly:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithURL:readOnly:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZDiskImageStorageDeviceAttachment~1init(url:readOnly:cachingMode:synchronizationMode:)/title",
          "value": "initWithURL:readOnly:cachingMode:synchronizationMode:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZDiskImageStorageDeviceAttachment~1init(url:readOnly:cachingMode:synchronizationMode:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithURL:readOnly:cachingMode:synchronizationMode:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZDiskImageStorageDeviceAttachment~1isReadOnly/title",
          "value": "readOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZDiskImageStorageDeviceAttachment~1isReadOnly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "readOnly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZDiskBlockDeviceStorageDeviceAttachment/title",
          "value": "VZDiskBlockDeviceStorageDeviceAttachment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZDiskBlockDeviceStorageDeviceAttachment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZDiskBlockDeviceStorageDeviceAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZDiskBlockDeviceStorageDeviceAttachment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZDiskBlockDeviceStorageDeviceAttachment"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/virtualization/vzdiskimagestoragedeviceattachment"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/virtualization/vzdiskimagestoragedeviceattachment"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
