{"metadata":{"externalID":"c:objc(cs)VZGenericMachineIdentifier","roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"VZGenericMachineIdentifier"}],"platforms":[{"deprecated":false,"name":"macOS","introducedAt":"13.0","unavailable":false,"beta":false}],"role":"symbol","modules":[{"name":"Virtualization"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VZGenericMachineIdentifier"}],"title":"VZGenericMachineIdentifier","symbolKind":"class"},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VZGenericMachineIdentifier"}]}],"kind":"declarations"},{"content":[{"type":"heading","text":"Overview","level":2,"anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use the data representation in "},{"type":"reference","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZGenericMachineIdentifier/dataRepresentation","isActive":true},{"type":"text","text":" to save the VM’s identifier. To restore a previously saved identifier use "},{"type":"reference","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZGenericMachineIdentifier/init(dataRepresentation:)","isActive":true},{"type":"text","text":"."}]}],"kind":"content"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.virtualization/documentation/Virtualization"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/virtualization/vzgenericmachineidentifier"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/virtualization/vzgenericmachineidentifier"]}],"sections":[],"kind":"symbol","identifier":{"url":"doc://com.apple.virtualization/documentation/Virtualization/VZGenericMachineIdentifier","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc://com.externally.resolved.symbol/c:objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc://com.externally.resolved.symbol/s:s7CVarArgP","doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","doc://com.externally.resolved.symbol/c:objc(pl)NSObject"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"abstract":[{"text":"An object that represents a unique identifier for a virtual machine.","type":"text"}],"topicSections":[{"identifiers":["doc://com.apple.virtualization/documentation/Virtualization/VZGenericMachineIdentifier/init()","doc://com.apple.virtualization/documentation/Virtualization/VZGenericMachineIdentifier/init(dataRepresentation:)"],"anchor":"Creating-a-Machine-Identifier","title":"Creating a Machine Identifier"},{"identifiers":["doc://com.apple.virtualization/documentation/Virtualization/VZGenericMachineIdentifier/dataRepresentation"],"anchor":"Getting-Information-About-the-Machine-Identifier","title":"Getting Information About the Machine Identifier"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"identifiers":["doc://com.apple.virtualization/documentation/Virtualization/VZGenericPlatformConfiguration/machineIdentifier","doc://com.apple.virtualization/documentation/Virtualization/VZGenericPlatformConfiguration/isNestedVirtualizationEnabled","doc://com.apple.virtualization/documentation/Virtualization/VZGenericPlatformConfiguration/isNestedVirtualizationSupported"],"anchor":"Identifying-the-platform-configuration","generated":true,"title":"Identifying the platform configuration"}],"references":{"doc://com.externally.resolved.symbol/s:SQ":{"abstract":[{"type":"text","text":"A type that can be compared for value equality."}],"title":"Equatable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Equatable"}],"identifier":"doc://com.externally.resolved.symbol/s:SQ","kind":"symbol","url":"/documentation/Swift/Equatable","type":"topic","role":"symbol"},"doc://com.externally.resolved.symbol/c:objc(cs)NSObject":{"type":"topic","abstract":[{"text":"The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.","type":"text"}],"fragments":[{"text":"class ","kind":"text"},{"text":"NSObject","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSObject","title":"NSObject","url":"/documentation/objectivec/nsobject"},"doc://com.apple.virtualization/documentation/Virtualization/VZGenericPlatformConfiguration/isNestedVirtualizationSupported":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isNestedVirtualizationSupported","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"isNestedVirtualizationSupported","url":"/documentation/virtualization/vzgenericplatformconfiguration/isnestedvirtualizationsupported","role":"symbol","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZGenericPlatformConfiguration/isNestedVirtualizationSupported","abstract":[{"text":"A Boolean value that describes whether the platform configuration supports nested virtualization.","type":"text"}],"navigatorTitle":[{"text":"nestedVirtualizationSupported","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.apple.virtualization/documentation/Virtualization/VZGenericMachineIdentifier/dataRepresentation":{"navigatorTitle":[{"kind":"identifier","text":"dataRepresentation"}],"type":"topic","abstract":[{"type":"text","text":"An opaque data representation of the VM’s identifier."}],"role":"symbol","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZGenericMachineIdentifier/dataRepresentation","url":"/documentation/virtualization/vzgenericmachineidentifier/datarepresentation","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataRepresentation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"}],"title":"dataRepresentation"},"doc://com.apple.virtualization/documentation/Virtualization/VZGenericMachineIdentifier/init(dataRepresentation:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithDataRepresentation:"}],"type":"topic","abstract":[{"type":"text","text":"Creates a new unique identifier for a VM with the provided data."}],"role":"symbol","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZGenericMachineIdentifier/init(dataRepresentation:)","url":"/documentation/virtualization/vzgenericmachineidentifier/init(datarepresentation:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"dataRepresentation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":")"}],"title":"init(dataRepresentation:)"},"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP":{"type":"topic","abstract":[{"text":"A type with a customized textual representation.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomStringConvertible","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","title":"CustomStringConvertible","url":"/documentation/Swift/CustomStringConvertible"},"doc://com.externally.resolved.symbol/s:SH":{"type":"topic","abstract":[{"text":"A type that can be hashed into a `Hasher` to produce an integer hash value.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hashable","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SQ","text":"Equatable","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SH","title":"Hashable","url":"/documentation/Swift/Hashable"},"doc://com.apple.virtualization/documentation/Virtualization/VZGenericPlatformConfiguration/isNestedVirtualizationEnabled":{"abstract":[{"text":"A Boolean value that indicates whether nested virtualization is in an enabled state.","type":"text"}],"title":"isNestedVirtualizationEnabled","navigatorTitle":[{"text":"nestedVirtualizationEnabled","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isNestedVirtualizationEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZGenericPlatformConfiguration/isNestedVirtualizationEnabled","kind":"symbol","url":"/documentation/virtualization/vzgenericplatformconfiguration/isnestedvirtualizationenabled","type":"topic","role":"symbol"},"doc://com.apple.virtualization/documentation/Virtualization":{"type":"topic","abstract":[{"text":"Create virtual machines and run macOS and Linux-based operating systems.","type":"text"}],"role":"collection","kind":"symbol","identifier":"doc://com.apple.virtualization/documentation/Virtualization","title":"Virtualization","url":"/documentation/virtualization"},"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP":{"type":"topic","abstract":[{"text":"A type with a customized textual representation suitable for debugging purposes.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomDebugStringConvertible","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","title":"CustomDebugStringConvertible","url":"/documentation/Swift/CustomDebugStringConvertible"},"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying":{"title":"NSCopying","role":"symbol","kind":"symbol","abstract":[{"text":"A protocol that objects adopt to provide functional copies of themselves.","type":"text"}],"type":"topic","url":"/documentation/foundation/nscopying","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSCopying","kind":"identifier"}]},"doc://com.apple.virtualization/documentation/Virtualization/VZGenericPlatformConfiguration/machineIdentifier":{"type":"topic","abstract":[{"type":"text","text":"A value that represents a unique identifier for the virtual machine."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"machineIdentifier","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)VZGenericMachineIdentifier","text":"VZGenericMachineIdentifier","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZGenericPlatformConfiguration/machineIdentifier","title":"machineIdentifier","navigatorTitle":[{"text":"machineIdentifier","kind":"identifier"}],"url":"/documentation/virtualization/vzgenericplatformconfiguration/machineidentifier"},"doc://com.apple.virtualization/documentation/Virtualization/VZGenericMachineIdentifier/init()":{"navigatorTitle":[{"kind":"identifier","text":"init"}],"type":"topic","abstract":[{"type":"text","text":"Creates a new unique identifier for a VM."}],"role":"symbol","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZGenericMachineIdentifier/init()","url":"/documentation/virtualization/vzgenericmachineidentifier/init()","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"title":"init()"},"doc://com.apple.virtualization/documentation/Virtualization/VZGenericMachineIdentifier":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VZGenericMachineIdentifier","kind":"identifier"}],"navigatorTitle":[{"text":"VZGenericMachineIdentifier","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZGenericMachineIdentifier","abstract":[{"type":"text","text":"An object that represents a unique identifier for a virtual machine."}],"url":"/documentation/virtualization/vzgenericmachineidentifier","kind":"symbol","title":"VZGenericMachineIdentifier"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","role":"overview","kind":"technologies","abstract":[{"text":"","type":"text"}],"type":"topic","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies"},"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"title":"NSObjectProtocol","role":"symbol","kind":"symbol","abstract":[{"text":"The group of methods that are fundamental to all Objective-C objects.","type":"text"}],"type":"topic","url":"/documentation/objectivec/nsobjectprotocol","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSObjectProtocol","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:s7CVarArgP":{"abstract":[{"type":"text","text":"A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`."}],"title":"CVarArg","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CVarArg"}],"identifier":"doc://com.externally.resolved.symbol/s:s7CVarArgP","kind":"symbol","url":"/documentation/Swift/CVarArg","type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"unavailable":false,"beta":false,"introducedAt":"13.0","name":"macOS","deprecated":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Class","path":"/metadata/roleHeading"},{"op":"replace","value":"VZGenericMachineIdentifier","path":"/metadata/title"},{"op":"replace","value":"class","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"VZGenericMachineIdentifier"}],"path":"/metadata/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"VZGenericMachineIdentifier"}],"path":"/metadata/navigatorTitle"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.virtualization/documentation/Virtualization"]]},"path":"/hierarchy"},{"op":"replace","value":[{"title":"Creating a Machine Identifier","anchor":"Creating-a-Machine-Identifier","identifiers":["doc://com.apple.virtualization/documentation/Virtualization/VZGenericMachineIdentifier/init()","doc://com.apple.virtualization/documentation/Virtualization/VZGenericMachineIdentifier/init(dataRepresentation:)"]},{"title":"Getting Information About the Machine Identifier","anchor":"Getting-Information-About-the-Machine-Identifier","identifiers":["doc://com.apple.virtualization/documentation/Virtualization/VZGenericMachineIdentifier/dataRepresentation"]}],"path":"/topicSections"},{"op":"replace","value":[{"kind":"relationships","identifiers":["doc://com.externally.resolved.symbol/c:objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"],"type":"conformsTo","title":"Conforms To"}],"path":"/relationshipsSections"},{"op":"replace","value":[{"anchor":"Identifying-the-platform-configuration","title":"Identifying the platform configuration","identifiers":["doc://com.apple.virtualization/documentation/Virtualization/VZGenericPlatformConfiguration/machineIdentifier","doc://com.apple.virtualization/documentation/Virtualization/VZGenericPlatformConfiguration/isNestedVirtualizationEnabled","doc://com.apple.virtualization/documentation/Virtualization/VZGenericPlatformConfiguration/isNestedVirtualizationSupported"],"generated":true}],"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["macOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VZGenericMachineIdentifier","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSObject"}]}]},"path":"/primaryContentSections/0"},{"op":"replace","value":"nestedVirtualizationSupported","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZGenericPlatformConfiguration~1isNestedVirtualizationSupported/title"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZGenericPlatformConfiguration~1isNestedVirtualizationSupported/fragments","value":[{"text":"nestedVirtualizationSupported","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZGenericMachineIdentifier~1dataRepresentation/title","value":"dataRepresentation","op":"replace"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZGenericMachineIdentifier~1dataRepresentation/fragments","value":[{"kind":"identifier","text":"dataRepresentation"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZGenericMachineIdentifier~1init(dataRepresentation:)/title","value":"initWithDataRepresentation:","op":"replace"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZGenericMachineIdentifier~1init(dataRepresentation:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithDataRepresentation:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZGenericPlatformConfiguration~1isNestedVirtualizationEnabled/title","value":"nestedVirtualizationEnabled","op":"replace"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZGenericPlatformConfiguration~1isNestedVirtualizationEnabled/fragments","value":[{"kind":"identifier","text":"nestedVirtualizationEnabled"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZGenericPlatformConfiguration~1machineIdentifier/title","value":"machineIdentifier","op":"replace"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZGenericPlatformConfiguration~1machineIdentifier/fragments","value":[{"kind":"identifier","text":"machineIdentifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZGenericMachineIdentifier~1init()/title","value":"init","op":"replace"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZGenericMachineIdentifier~1init()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZGenericMachineIdentifier/title","value":"VZGenericMachineIdentifier","op":"replace"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZGenericMachineIdentifier/fragments","value":[{"kind":"identifier","text":"VZGenericMachineIdentifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZGenericMachineIdentifier/navigatorTitle","value":[{"text":"VZGenericMachineIdentifier","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title","value":"NSObject","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}