{
  "abstract": [
    {
      "text": "The media access control (MAC) address for a network interface in your virtual machine.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.virtualization/documentation/Virtualization"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.virtualization/documentation/Virtualization/VZMACAddress"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)VZMACAddress",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "VZMACAddress"
      }
    ],
    "modules": [
      {
        "name": "Virtualization"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VZMACAddress"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "VZMACAddress"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "VZMACAddress"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMACAddress",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object contains the hardware address of your network interface. Every network device has a unique 48-bit MAC address that the system uses to route network packets to that device.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Call the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMACAddress/randomLocallyAdministered()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method to get a local MAC address suitable for use with your network interfaces. Alternatively, you can create a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMACAddress",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object yourself from a string or ",
              "type": "text"
            },
            {
              "code": "ether_addr_t",
              "type": "codeVoice"
            },
            {
              "text": " structure.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.virtualization/documentation/Virtualization": {
      "abstract": [
        {
          "text": "Create virtual machines and run macOS and Linux-based operating systems.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization",
      "kind": "symbol",
      "role": "collection",
      "title": "Virtualization",
      "type": "topic",
      "url": "/documentation/virtualization"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZMACAddress": {
      "abstract": [
        {
          "text": "The media access control (MAC) address for a network interface in your virtual machine.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZMACAddress"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMACAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZMACAddress"
        }
      ],
      "role": "symbol",
      "title": "VZMACAddress",
      "type": "topic",
      "url": "/documentation/virtualization/vzmacaddress"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZMACAddress/ethernetAddress": {
      "abstract": [
        {
          "text": "The MAC address as an Ethernet data structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ethernetAddress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ether_addr_t",
          "text": "ether_addr_t"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMACAddress/ethernetAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ethernetAddress"
        }
      ],
      "role": "symbol",
      "title": "ethernetAddress",
      "type": "topic",
      "url": "/documentation/virtualization/vzmacaddress/ethernetaddress"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZMACAddress/init(ethernetAddress:)": {
      "abstract": [
        {
          "text": "Creates a MAC address from the specified 48-bit Ethernet address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "ethernetAddress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ether_addr_t",
          "text": "ether_addr_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMACAddress/init(ethernetAddress:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithEthernetAddress:"
        }
      ],
      "role": "symbol",
      "title": "init(ethernetAddress:)",
      "type": "topic",
      "url": "/documentation/virtualization/vzmacaddress/init(ethernetaddress:)"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZMACAddress/init(string:)": {
      "abstract": [
        {
          "text": "Creates a MAC address object from a specially formatted string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "string"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMACAddress/init(string:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithString:"
        }
      ],
      "role": "symbol",
      "title": "init(string:)",
      "type": "topic",
      "url": "/documentation/virtualization/vzmacaddress/init(string:)"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZMACAddress/isBroadcastAddress": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the address is a broadcast address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isBroadcastAddress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMACAddress/isBroadcastAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isBroadcastAddress"
        }
      ],
      "role": "symbol",
      "title": "isBroadcastAddress",
      "type": "topic",
      "url": "/documentation/virtualization/vzmacaddress/isbroadcastaddress"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZMACAddress/isLocallyAdministeredAddress": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the address is a locally administered address (LAA).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isLocallyAdministeredAddress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMACAddress/isLocallyAdministeredAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isLocallyAdministeredAddress"
        }
      ],
      "role": "symbol",
      "title": "isLocallyAdministeredAddress",
      "type": "topic",
      "url": "/documentation/virtualization/vzmacaddress/islocallyadministeredaddress"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZMACAddress/isMulticastAddress": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the address is a multicast address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isMulticastAddress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMACAddress/isMulticastAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isMulticastAddress"
        }
      ],
      "role": "symbol",
      "title": "isMulticastAddress",
      "type": "topic",
      "url": "/documentation/virtualization/vzmacaddress/ismulticastaddress"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZMACAddress/isUnicastAddress": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the address is a unicast address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isUnicastAddress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMACAddress/isUnicastAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isUnicastAddress"
        }
      ],
      "role": "symbol",
      "title": "isUnicastAddress",
      "type": "topic",
      "url": "/documentation/virtualization/vzmacaddress/isunicastaddress"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZMACAddress/isUniversallyAdministeredAddress": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the address is a universally adminstered address (UAA).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isUniversallyAdministeredAddress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMACAddress/isUniversallyAdministeredAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isUniversallyAdministeredAddress"
        }
      ],
      "role": "symbol",
      "title": "isUniversallyAdministeredAddress",
      "type": "topic",
      "url": "/documentation/virtualization/vzmacaddress/isuniversallyadministeredaddress"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZMACAddress/randomLocallyAdministered()": {
      "abstract": [
        {
          "text": "Returns a valid, random, locally administered, unicast MAC address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "randomLocallyAdministered"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMACAddress/randomLocallyAdministered()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "randomLocallyAdministeredAddress"
        }
      ],
      "role": "symbol",
      "title": "randomLocallyAdministered()",
      "type": "topic",
      "url": "/documentation/virtualization/vzmacaddress/randomlocallyadministered()"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZMACAddress/string": {
      "abstract": [
        {
          "text": "The MAC address as a formatted string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "string"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMACAddress/string",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "string"
        }
      ],
      "role": "symbol",
      "title": "string",
      "type": "topic",
      "url": "/documentation/virtualization/vzmacaddress/string"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZNetworkDeviceConfiguration": {
      "abstract": [
        {
          "text": "The common configuration traits for network devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZNetworkDeviceConfiguration"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZNetworkDeviceConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZNetworkDeviceConfiguration"
        }
      ],
      "role": "symbol",
      "title": "VZNetworkDeviceConfiguration",
      "type": "topic",
      "url": "/documentation/virtualization/vznetworkdeviceconfiguration"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioNetworkDeviceConfiguration": {
      "abstract": [
        {
          "text": "A configuration object that requests the creation of a network device for the guest system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZVirtioNetworkDeviceConfiguration"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioNetworkDeviceConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZVirtioNetworkDeviceConfiguration"
        }
      ],
      "role": "symbol",
      "title": "VZVirtioNetworkDeviceConfiguration",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtionetworkdeviceconfiguration"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configurations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioNetworkDeviceConfiguration",
        "doc://com.apple.virtualization/documentation/Virtualization/VZNetworkDeviceConfiguration"
      ],
      "title": "Configurations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-MAC-address",
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZMACAddress/randomLocallyAdministered()",
        "doc://com.apple.virtualization/documentation/Virtualization/VZMACAddress/init(string:)",
        "doc://com.apple.virtualization/documentation/Virtualization/VZMACAddress/init(ethernetAddress:)"
      ],
      "title": "Creating a MAC address"
    },
    {
      "anchor": "Getting-the-address",
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZMACAddress/string",
        "doc://com.apple.virtualization/documentation/Virtualization/VZMACAddress/ethernetAddress"
      ],
      "title": "Getting the address"
    },
    {
      "anchor": "Getting-address-attributes",
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZMACAddress/isBroadcastAddress",
        "doc://com.apple.virtualization/documentation/Virtualization/VZMACAddress/isMulticastAddress",
        "doc://com.apple.virtualization/documentation/Virtualization/VZMACAddress/isUnicastAddress",
        "doc://com.apple.virtualization/documentation/Virtualization/VZMACAddress/isLocallyAdministeredAddress",
        "doc://com.apple.virtualization/documentation/Virtualization/VZMACAddress/isUniversallyAdministeredAddress"
      ],
      "title": "Getting address attributes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VZMACAddress"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZMACAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZMACAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.virtualization/documentation/Virtualization"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-MAC-address",
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/VZMACAddress/randomLocallyAdministered()",
                "doc://com.apple.virtualization/documentation/Virtualization/VZMACAddress/init(string:)",
                "doc://com.apple.virtualization/documentation/Virtualization/VZMACAddress/init(ethernetAddress:)"
              ],
              "title": "Creating a MAC address"
            },
            {
              "anchor": "Getting-the-address",
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/VZMACAddress/string",
                "doc://com.apple.virtualization/documentation/Virtualization/VZMACAddress/ethernetAddress"
              ],
              "title": "Getting the address"
            },
            {
              "anchor": "Getting-address-attributes",
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/VZMACAddress/isBroadcastAddress",
                "doc://com.apple.virtualization/documentation/Virtualization/VZMACAddress/isMulticastAddress",
                "doc://com.apple.virtualization/documentation/Virtualization/VZMACAddress/isUnicastAddress",
                "doc://com.apple.virtualization/documentation/Virtualization/VZMACAddress/isLocallyAdministeredAddress",
                "doc://com.apple.virtualization/documentation/Virtualization/VZMACAddress/isUniversallyAdministeredAddress"
              ],
              "title": "Getting address attributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configurations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioNetworkDeviceConfiguration",
                "doc://com.apple.virtualization/documentation/Virtualization/VZNetworkDeviceConfiguration"
              ],
              "title": "Configurations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "VZMACAddress"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMACAddress~1isUniversallyAdministeredAddress/title",
          "value": "isUniversallyAdministeredAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMACAddress~1isUniversallyAdministeredAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "isUniversallyAdministeredAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMACAddress~1init(ethernetAddress:)/title",
          "value": "initWithEthernetAddress:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMACAddress~1init(ethernetAddress:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithEthernetAddress:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioNetworkDeviceConfiguration/title",
          "value": "VZVirtioNetworkDeviceConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioNetworkDeviceConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtioNetworkDeviceConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioNetworkDeviceConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtioNetworkDeviceConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMACAddress~1randomLocallyAdministered()/title",
          "value": "randomLocallyAdministeredAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMACAddress~1randomLocallyAdministered()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "randomLocallyAdministeredAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMACAddress~1isBroadcastAddress/title",
          "value": "isBroadcastAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMACAddress~1isBroadcastAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "isBroadcastAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMACAddress~1isMulticastAddress/title",
          "value": "isMulticastAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMACAddress~1isMulticastAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "isMulticastAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMACAddress/title",
          "value": "VZMACAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMACAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZMACAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMACAddress/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZMACAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZNetworkDeviceConfiguration/title",
          "value": "VZNetworkDeviceConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZNetworkDeviceConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZNetworkDeviceConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZNetworkDeviceConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZNetworkDeviceConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMACAddress~1ethernetAddress/title",
          "value": "ethernetAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMACAddress~1ethernetAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ethernetAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMACAddress~1string/title",
          "value": "string"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMACAddress~1string/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "string"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMACAddress~1init(string:)/title",
          "value": "initWithString:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMACAddress~1init(string:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithString:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMACAddress~1isUnicastAddress/title",
          "value": "isUnicastAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMACAddress~1isUnicastAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "isUnicastAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMACAddress~1isLocallyAdministeredAddress/title",
          "value": "isLocallyAdministeredAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMACAddress~1isLocallyAdministeredAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "isLocallyAdministeredAddress"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/virtualization/vzmacaddress"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/virtualization/vzmacaddress"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
