{"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc://com.externally.resolved.symbol/c:objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc://com.externally.resolved.symbol/s:s7CVarArgP","doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","doc://com.externally.resolved.symbol/c:objc(pl)NSObject"],"type":"conformsTo"}],"seeAlsoSections":[{"title":"Platform components","identifiers":["doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration","doc://com.apple.virtualization/documentation/Virtualization/VZMacOSVirtualMachineStartOptions","doc://com.apple.virtualization/documentation/Virtualization/VZMacPlatformConfiguration","doc://com.apple.virtualization/documentation/Virtualization/VZPlatformConfiguration","doc://com.apple.virtualization/documentation/Virtualization/VZMacHardwareModel","doc://com.apple.virtualization/documentation/Virtualization/VZMacAuxiliaryStorage"],"anchor":"Platform-components","generated":true}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.virtualization/documentation/Virtualization/VZMacMachineIdentifier"},"metadata":{"title":"VZMacMachineIdentifier","role":"symbol","roleHeading":"Class","platforms":[{"unavailable":false,"name":"macOS","deprecated":false,"introducedAt":"12.0","beta":false}],"symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VZMacMachineIdentifier"}],"modules":[{"name":"Virtualization"}],"navigatorTitle":[{"kind":"identifier","text":"VZMacMachineIdentifier"}],"externalID":"c:objc(cs)VZMacMachineIdentifier"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"type":"text","text":"A unique identifier for a VM."}],"topicSections":[{"title":"Creating a machine identifier","identifiers":["doc://com.apple.virtualization/documentation/Virtualization/VZMacMachineIdentifier/init(dataRepresentation:)","doc://com.apple.virtualization/documentation/Virtualization/VZMacMachineIdentifier/init()"],"anchor":"Creating-a-machine-identifier"},{"title":"Machine data representation","identifiers":["doc://com.apple.virtualization/documentation/Virtualization/VZMacMachineIdentifier/dataRepresentation"],"anchor":"Machine-data-representation"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.virtualization/documentation/Virtualization"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/virtualization/vzmacmachineidentifier"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/virtualization/vzmacmachineidentifier"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VZMacMachineIdentifier","kind":"identifier"}],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"anchor":"overview","text":"Overview","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"This value uniquely identifies a virtual Mac hardware instance. Two VMs running concurrently shouldn’t use the same identifier.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"When serializing the VM to disk, you can preserve the identifier in a binary representation by serializing the data in the "},{"code":"VZMacMachineIdentifier","type":"codeVoice"},{"type":"text","text":"."},{"type":"reference","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZMacHardwareModel/dataRepresentation","isActive":true},{"type":"text","text":" property. Conversely, you can recreate the identifier with "},{"type":"reference","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZMacMachineIdentifier/init(dataRepresentation:)","isActive":true},{"type":"text","text":" from the binary representation."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can compare the contents of two identifiers with "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.documentation/documentation/objectivec/nsobject/1393823-isequal"},{"type":"text","text":"."}]}]}],"references":{"doc://com.apple.virtualization/documentation/Virtualization/VZMacMachineIdentifier":{"identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZMacMachineIdentifier","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"A unique identifier for a VM."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VZMacMachineIdentifier"}],"title":"VZMacMachineIdentifier","url":"/documentation/virtualization/vzmacmachineidentifier","navigatorTitle":[{"kind":"identifier","text":"VZMacMachineIdentifier"}]},"doc://com.apple.virtualization/documentation/Virtualization/VZPlatformConfiguration":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VZPlatformConfiguration"}],"identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZPlatformConfiguration","abstract":[{"type":"text","text":"The base class for a platform configuration."}],"role":"symbol","title":"VZPlatformConfiguration","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"VZPlatformConfiguration"}],"url":"/documentation/virtualization/vzplatformconfiguration"},"doc://com.externally.resolved.symbol/s:SQ":{"abstract":[{"type":"text","text":"A type that can be compared for value equality."}],"title":"Equatable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Equatable"}],"identifier":"doc://com.externally.resolved.symbol/s:SQ","kind":"symbol","url":"/documentation/Swift/Equatable","type":"topic","role":"symbol"},"doc://com.apple.virtualization/documentation/Virtualization/VZMacAuxiliaryStorage":{"identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZMacAuxiliaryStorage","navigatorTitle":[{"kind":"identifier","text":"VZMacAuxiliaryStorage"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VZMacAuxiliaryStorage"}],"title":"VZMacAuxiliaryStorage","url":"/documentation/virtualization/vzmacauxiliarystorage","type":"topic","kind":"symbol","abstract":[{"text":"An object that contains information the boot loader needs for booting macOS as a guest operating system.","type":"text"}],"role":"symbol"},"doc://com.externally.resolved.symbol/c:objc(cs)NSObject":{"type":"topic","abstract":[{"text":"The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.","type":"text"}],"fragments":[{"text":"class ","kind":"text"},{"text":"NSObject","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSObject","title":"NSObject","url":"/documentation/objectivec/nsobject"},"doc://com.apple.virtualization/documentation/Virtualization":{"type":"topic","abstract":[{"text":"Create virtual machines and run macOS and Linux-based operating systems.","type":"text"}],"role":"collection","kind":"symbol","identifier":"doc://com.apple.virtualization/documentation/Virtualization","title":"Virtualization","url":"/documentation/virtualization"},"doc://com.apple.documentation/documentation/objectivec/nsobject/1393823-isequal":{"identifier":"doc://com.apple.documentation/documentation/objectivec/nsobject/1393823-isequal","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Returns a Boolean value that indicates whether the receiver is equal to another given object."}],"type":"topic","fragments":[{"kind":"text","text":"func "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"identifier","text":"to"},{"kind":"text","text":": Any?) -> Bool"}],"title":"isEqual(to:)","url":"/documentation/objectivec/nsobject/1393823-isequal"},"doc://com.apple.virtualization/documentation/Virtualization/VZMacPlatformConfiguration":{"title":"VZMacPlatformConfiguration","role":"symbol","navigatorTitle":[{"text":"VZMacPlatformConfiguration","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"The platform configuration for booting macOS on Apple silicon.","type":"text"}],"type":"topic","url":"/documentation/virtualization/vzmacplatformconfiguration","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZMacPlatformConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VZMacPlatformConfiguration","kind":"identifier"}]},"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying":{"title":"NSCopying","role":"symbol","kind":"symbol","abstract":[{"text":"A protocol that objects adopt to provide functional copies of themselves.","type":"text"}],"type":"topic","url":"/documentation/foundation/nscopying","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSCopying","kind":"identifier"}]},"doc://com.apple.virtualization/documentation/Virtualization/VZMacMachineIdentifier/dataRepresentation":{"identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZMacMachineIdentifier/dataRepresentation","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Returns the opaque data representation of the machine identifier."}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataRepresentation"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"}],"title":"dataRepresentation","url":"/documentation/virtualization/vzmacmachineidentifier/datarepresentation","navigatorTitle":[{"kind":"identifier","text":"dataRepresentation"}]},"doc://com.apple.virtualization/documentation/Virtualization/VZMacOSVirtualMachineStartOptions":{"identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZMacOSVirtualMachineStartOptions","title":"VZMacOSVirtualMachineStartOptions","kind":"symbol","role":"symbol","abstract":[{"text":"A class that describes start options for macOS VMs.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VZMacOSVirtualMachineStartOptions","kind":"identifier"}],"url":"/documentation/virtualization/vzmacosvirtualmachinestartoptions","navigatorTitle":[{"text":"VZMacOSVirtualMachineStartOptions","kind":"identifier"}],"type":"topic"},"doc://com.apple.virtualization/documentation/Virtualization/VZMacHardwareModel":{"url":"/documentation/virtualization/vzmachardwaremodel","title":"VZMacHardwareModel","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZMacHardwareModel","type":"topic","abstract":[{"text":"A specification for the hardware elements and configurations present in a particular Mac hardware model.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"VZMacHardwareModel","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VZMacHardwareModel","kind":"identifier"}],"role":"symbol"},"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP":{"type":"topic","abstract":[{"text":"A type with a customized textual representation.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomStringConvertible","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","title":"CustomStringConvertible","url":"/documentation/Swift/CustomStringConvertible"},"doc://com.externally.resolved.symbol/s:s7CVarArgP":{"abstract":[{"type":"text","text":"A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`."}],"title":"CVarArg","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CVarArg"}],"identifier":"doc://com.externally.resolved.symbol/s:s7CVarArgP","kind":"symbol","url":"/documentation/Swift/CVarArg","type":"topic","role":"symbol"},"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration":{"type":"topic","abstract":[{"type":"text","text":"The environment attributes and list of devices to use during the configuration of macOS or Linux VMs."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"VZVirtualMachineConfiguration","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration","title":"VZVirtualMachineConfiguration","navigatorTitle":[{"text":"VZVirtualMachineConfiguration","kind":"identifier"}],"url":"/documentation/virtualization/vzvirtualmachineconfiguration"},"doc://com.apple.virtualization/documentation/Virtualization/VZMacMachineIdentifier/init()":{"abstract":[{"type":"text","text":"Creates a new unique machine identifier."}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"type":"topic","kind":"symbol","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZMacMachineIdentifier/init()","title":"init()","url":"/documentation/virtualization/vzmacmachineidentifier/init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"role":"symbol"},"doc://com.apple.virtualization/documentation/Virtualization/VZMacHardwareModel/dataRepresentation":{"abstract":[{"type":"text","text":"Returns the opaque data representation of the hardware model."}],"navigatorTitle":[{"kind":"identifier","text":"dataRepresentation"}],"type":"topic","kind":"symbol","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZMacHardwareModel/dataRepresentation","title":"dataRepresentation","url":"/documentation/virtualization/vzmachardwaremodel/datarepresentation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataRepresentation"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"}],"role":"symbol"},"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"title":"NSObjectProtocol","role":"symbol","kind":"symbol","abstract":[{"text":"The group of methods that are fundamental to all Objective-C objects.","type":"text"}],"type":"topic","url":"/documentation/objectivec/nsobjectprotocol","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSObjectProtocol","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:SH":{"type":"topic","abstract":[{"text":"A type that can be hashed into a `Hasher` to produce an integer hash value.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hashable","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SQ","text":"Equatable","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SH","title":"Hashable","url":"/documentation/Swift/Hashable"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","role":"overview","kind":"technologies","abstract":[{"text":"","type":"text"}],"type":"topic","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies"},"doc://com.apple.virtualization/documentation/Virtualization/VZMacMachineIdentifier/init(dataRepresentation:)":{"url":"/documentation/virtualization/vzmacmachineidentifier/init(datarepresentation:)","navigatorTitle":[{"kind":"identifier","text":"initWithDataRepresentation:"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"dataRepresentation"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":")"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZMacMachineIdentifier/init(dataRepresentation:)","abstract":[{"type":"text","text":"Create a machine identifier described by the specified data representation."}],"title":"init(dataRepresentation:)"},"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP":{"type":"topic","abstract":[{"text":"A type with a customized textual representation suitable for debugging purposes.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomDebugStringConvertible","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","title":"CustomDebugStringConvertible","url":"/documentation/Swift/CustomDebugStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"name":"macOS","beta":false,"introducedAt":"12.0","deprecated":false,"unavailable":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Class","op":"replace"},{"path":"/metadata/title","value":"VZMacMachineIdentifier","op":"replace"},{"path":"/metadata/symbolKind","value":"class","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"VZMacMachineIdentifier","kind":"identifier"}],"op":"replace"},{"path":"/metadata/navigatorTitle","value":[{"kind":"identifier","text":"VZMacMachineIdentifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.virtualization/documentation/Virtualization"]]},"op":"replace"},{"path":"/topicSections","value":[{"identifiers":["doc://com.apple.virtualization/documentation/Virtualization/VZMacMachineIdentifier/init(dataRepresentation:)","doc://com.apple.virtualization/documentation/Virtualization/VZMacMachineIdentifier/init()"],"title":"Creating a machine identifier","anchor":"Creating-a-machine-identifier"},{"identifiers":["doc://com.apple.virtualization/documentation/Virtualization/VZMacMachineIdentifier/dataRepresentation"],"title":"Machine data representation","anchor":"Machine-data-representation"}],"op":"replace"},{"path":"/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc://com.externally.resolved.symbol/c:objc(cs)NSObject"]},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"]}],"op":"replace"},{"path":"/seeAlsoSections","value":[{"generated":true,"title":"Platform components","identifiers":["doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration","doc://com.apple.virtualization/documentation/Virtualization/VZMacOSVirtualMachineStartOptions","doc://com.apple.virtualization/documentation/Virtualization/VZMacPlatformConfiguration","doc://com.apple.virtualization/documentation/Virtualization/VZPlatformConfiguration","doc://com.apple.virtualization/documentation/Virtualization/VZMacHardwareModel","doc://com.apple.virtualization/documentation/Virtualization/VZMacAuxiliaryStorage"],"anchor":"Platform-components"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"VZMacMachineIdentifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSObject"}],"platforms":["macOS"]}]},"op":"replace"},{"value":"VZMacMachineIdentifier","op":"replace","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacMachineIdentifier/title"},{"value":[{"kind":"identifier","text":"VZMacMachineIdentifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacMachineIdentifier/fragments"},{"value":[{"kind":"identifier","text":"VZMacMachineIdentifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacMachineIdentifier/navigatorTitle"},{"value":"VZPlatformConfiguration","op":"replace","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZPlatformConfiguration/title"},{"value":[{"text":"VZPlatformConfiguration","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZPlatformConfiguration/fragments"},{"value":[{"kind":"identifier","text":"VZPlatformConfiguration"}],"op":"replace","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZPlatformConfiguration/navigatorTitle"},{"value":"VZMacAuxiliaryStorage","op":"replace","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacAuxiliaryStorage/title"},{"value":[{"kind":"identifier","text":"VZMacAuxiliaryStorage"}],"op":"replace","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacAuxiliaryStorage/fragments"},{"value":[{"text":"VZMacAuxiliaryStorage","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacAuxiliaryStorage/navigatorTitle"},{"op":"replace","value":"isEqualTo:","path":"/references/doc:~1~1com.apple.documentation~1documentation~1objectivec~1nsobject~11393823-isequal/title"},{"op":"replace","value":"VZMacPlatformConfiguration","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacPlatformConfiguration/title"},{"op":"replace","value":[{"text":"VZMacPlatformConfiguration","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacPlatformConfiguration/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"VZMacPlatformConfiguration"}],"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacPlatformConfiguration/navigatorTitle"},{"op":"replace","value":"dataRepresentation","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacMachineIdentifier~1dataRepresentation/title"},{"op":"replace","value":[{"kind":"identifier","text":"dataRepresentation"}],"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacMachineIdentifier~1dataRepresentation/fragments"},{"op":"replace","value":"VZMacOSVirtualMachineStartOptions","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacOSVirtualMachineStartOptions/title"},{"op":"replace","value":[{"text":"VZMacOSVirtualMachineStartOptions","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacOSVirtualMachineStartOptions/fragments"},{"op":"replace","value":[{"text":"VZMacOSVirtualMachineStartOptions","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacOSVirtualMachineStartOptions/navigatorTitle"},{"op":"replace","value":"VZMacHardwareModel","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacHardwareModel/title"},{"op":"replace","value":[{"text":"VZMacHardwareModel","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacHardwareModel/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"VZMacHardwareModel"}],"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacHardwareModel/navigatorTitle"},{"op":"replace","value":"VZVirtualMachineConfiguration","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration/title"},{"op":"replace","value":[{"text":"VZVirtualMachineConfiguration","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"VZVirtualMachineConfiguration"}],"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration/navigatorTitle"},{"op":"replace","value":"init","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacMachineIdentifier~1init()/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacMachineIdentifier~1init()/fragments"},{"op":"replace","value":"dataRepresentation","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacHardwareModel~1dataRepresentation/title"},{"op":"replace","value":[{"text":"dataRepresentation","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacHardwareModel~1dataRepresentation/fragments"},{"op":"replace","value":"NSObject","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title"},{"op":"replace","value":"initWithDataRepresentation:","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacMachineIdentifier~1init(dataRepresentation:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDataRepresentation:"}],"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacMachineIdentifier~1init(dataRepresentation:)/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}