{
  "abstract": [
    {
      "text": "An object that describes a version of macOS to install on to a virtual machine.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.virtualization/documentation/Virtualization"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSRestoreImage"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)VZMacOSRestoreImage",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "VZMacOSRestoreImage"
      }
    ],
    "modules": [
      {
        "name": "Virtualization"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VZMacOSRestoreImage"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "VZMacOSRestoreImage"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "VZMacOSRestoreImage"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.virtualization/documentation/Virtualization/installing-macos-on-a-virtual-machine",
        "doc://com.apple.virtualization/documentation/Virtualization/using-icloud-with-macos-virtual-machines"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To set up a new VM compatible with the restore image, use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSRestoreImage/mostFeaturefulSupportedConfiguration",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to obtain the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMacPlatformConfiguration/hardwareModel",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMacPlatformConfiguration",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Then, create a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSRestoreImage",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object by loading an installation media file. Initialize a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSInstaller",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object with this ",
              "type": "text"
            },
            {
              "code": "VZMacOSRestoreImage",
              "type": "codeVoice"
            },
            {
              "text": " object to install the operating system onto a VM.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Loading a restore image requires the app to have the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.virtualization",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " entitlement.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.virtualization": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether your app can use the Virtualization framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.security.virtualization",
      "kind": "symbol",
      "role": "symbol",
      "title": "com.apple.security.virtualization",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.security.virtualization"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.virtualization/documentation/Virtualization": {
      "abstract": [
        {
          "text": "Create virtual machines and run macOS and Linux-based operating systems.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization",
      "kind": "symbol",
      "role": "collection",
      "title": "Virtualization",
      "type": "topic",
      "url": "/documentation/virtualization"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZMacHardwareModel": {
      "abstract": [
        {
          "text": "A specification for the hardware elements and configurations present in a particular Mac hardware model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZMacHardwareModel"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMacHardwareModel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZMacHardwareModel"
        }
      ],
      "role": "symbol",
      "title": "VZMacHardwareModel",
      "type": "topic",
      "url": "/documentation/virtualization/vzmachardwaremodel"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSConfigurationRequirements": {
      "abstract": [
        {
          "text": "An object that describes the parameter constraints required by a specific configuration of macOS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZMacOSConfigurationRequirements"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSConfigurationRequirements",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZMacOSConfigurationRequirements"
        }
      ],
      "role": "symbol",
      "title": "VZMacOSConfigurationRequirements",
      "type": "topic",
      "url": "/documentation/virtualization/vzmacosconfigurationrequirements"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSInstaller": {
      "abstract": [
        {
          "text": "An object you use to install macOS on the specified virtual machine.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZMacOSInstaller"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSInstaller",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZMacOSInstaller"
        }
      ],
      "role": "symbol",
      "title": "VZMacOSInstaller",
      "type": "topic",
      "url": "/documentation/virtualization/vzmacosinstaller"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSRestoreImage": {
      "abstract": [
        {
          "text": "An object that describes a version of macOS to install on to a virtual machine.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZMacOSRestoreImage"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSRestoreImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZMacOSRestoreImage"
        }
      ],
      "role": "symbol",
      "title": "VZMacOSRestoreImage",
      "type": "topic",
      "url": "/documentation/virtualization/vzmacosrestoreimage"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSRestoreImage/buildVersion": {
      "abstract": [
        {
          "text": "The build version this restore image contains.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "buildVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSRestoreImage/buildVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "buildVersion"
        }
      ],
      "role": "symbol",
      "title": "buildVersion",
      "type": "topic",
      "url": "/documentation/virtualization/vzmacosrestoreimage/buildversion"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSRestoreImage/fetchLatestSupported(completionHandler:)": {
      "abstract": [
        {
          "text": "Fetches the latest restore image supported by this host from the network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fetchLatestSupported"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6ResultO",
          "text": "Result"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VZMacOSRestoreImage",
          "text": "VZMacOSRestoreImage"
        },
        {
          "kind": "text",
          "text": ", any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSRestoreImage/fetchLatestSupported(completionHandler:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "fetchLatestSupported(completionHandler:)",
      "type": "topic",
      "url": "/documentation/virtualization/vzmacosrestoreimage/fetchlatestsupported(completionhandler:)"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSRestoreImage/image(from:)": {
      "abstract": [
        {
          "text": "Load a restore image from a file on the local file system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "image"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VZMacOSRestoreImage",
          "text": "VZMacOSRestoreImage"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSRestoreImage/image(from:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loadFileURL:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "image(from:)",
      "type": "topic",
      "url": "/documentation/virtualization/vzmacosrestoreimage/image(from:)"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSRestoreImage/isSupported": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the current host supports this restore image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isSupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSRestoreImage/isSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supported"
        }
      ],
      "role": "symbol",
      "title": "isSupported",
      "type": "topic",
      "url": "/documentation/virtualization/vzmacosrestoreimage/issupported"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSRestoreImage/latestSupported": {
      "abstract": [
        {
          "text": "Fetches the latest restore image supported by this host from the network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "latestSupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VZMacOSRestoreImage",
          "text": "VZMacOSRestoreImage"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSRestoreImage/latestSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fetchLatestSupportedWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "latestSupported",
      "type": "topic",
      "url": "/documentation/virtualization/vzmacosrestoreimage/latestsupported"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSRestoreImage/load(from:completionHandler:)": {
      "abstract": [
        {
          "text": "Load a restore image from a file on the local file system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "load"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6ResultO",
          "text": "Result"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VZMacOSRestoreImage",
          "text": "VZMacOSRestoreImage"
        },
        {
          "kind": "text",
          "text": ", any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSRestoreImage/load(from:completionHandler:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "load(from:completionHandler:)",
      "type": "topic",
      "url": "/documentation/virtualization/vzmacosrestoreimage/load(from:completionhandler:)"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSRestoreImage/mostFeaturefulSupportedConfiguration": {
      "abstract": [
        {
          "text": "This object represents the most fully featured configuration that’s supported by both the current host and by this restore image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mostFeaturefulSupportedConfiguration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VZMacOSConfigurationRequirements",
          "text": "VZMacOSConfigurationRequirements"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSRestoreImage/mostFeaturefulSupportedConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mostFeaturefulSupportedConfiguration"
        }
      ],
      "role": "symbol",
      "title": "mostFeaturefulSupportedConfiguration",
      "type": "topic",
      "url": "/documentation/virtualization/vzmacosrestoreimage/mostfeaturefulsupportedconfiguration"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSRestoreImage/operatingSystemVersion": {
      "abstract": [
        {
          "text": "The operating system version this restore image contains.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "operatingSystemVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@NSOperatingSystemVersion",
          "text": "OperatingSystemVersion"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSRestoreImage/operatingSystemVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "operatingSystemVersion"
        }
      ],
      "role": "symbol",
      "title": "operatingSystemVersion",
      "type": "topic",
      "url": "/documentation/virtualization/vzmacosrestoreimage/operatingsystemversion"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSRestoreImage/url": {
      "abstract": [
        {
          "text": "The URL of this restore image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "url"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSRestoreImage/url",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "URL"
        }
      ],
      "role": "symbol",
      "title": "url",
      "type": "topic",
      "url": "/documentation/virtualization/vzmacosrestoreimage/url"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZMacPlatformConfiguration": {
      "abstract": [
        {
          "text": "The platform configuration for booting macOS on Apple silicon.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZMacPlatformConfiguration"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMacPlatformConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZMacPlatformConfiguration"
        }
      ],
      "role": "symbol",
      "title": "VZMacPlatformConfiguration",
      "type": "topic",
      "url": "/documentation/virtualization/vzmacplatformconfiguration"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZMacPlatformConfiguration/hardwareModel": {
      "abstract": [
        {
          "text": "The Mac hardware model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hardwareModel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VZMacHardwareModel",
          "text": "VZMacHardwareModel"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZMacPlatformConfiguration/hardwareModel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hardwareModel"
        }
      ],
      "role": "symbol",
      "title": "hardwareModel",
      "type": "topic",
      "url": "/documentation/virtualization/vzmacplatformconfiguration/hardwaremodel"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/installing-macos-on-a-virtual-machine": {
      "abstract": [
        {
          "text": "Download a macOS restore image and install it in a new VM.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/installing-macos-on-a-virtual-machine",
      "kind": "article",
      "role": "article",
      "title": "Installing macOS on a Virtual Machine",
      "type": "topic",
      "url": "/documentation/virtualization/installing-macos-on-a-virtual-machine"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/using-icloud-with-macos-virtual-machines": {
      "abstract": [
        {
          "text": "Access iCloud from macOS guest virtual machines.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/using-icloud-with-macos-virtual-machines",
      "kind": "article",
      "role": "article",
      "title": "Using iCloud with macOS virtual machines",
      "type": "topic",
      "url": "/documentation/virtualization/using-icloud-with-macos-virtual-machines"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZMacHardwareModel"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Installers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSInstaller",
        "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSConfigurationRequirements"
      ],
      "title": "Installers"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-Information-About-the-Restore-Image",
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSRestoreImage/buildVersion",
        "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSRestoreImage/isSupported",
        "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSRestoreImage/mostFeaturefulSupportedConfiguration",
        "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSRestoreImage/operatingSystemVersion",
        "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSRestoreImage/url"
      ],
      "title": "Getting Information About the Restore Image"
    },
    {
      "anchor": "Controlling-the-Restoration-Process",
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSRestoreImage/fetchLatestSupported(completionHandler:)",
        "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSRestoreImage/load(from:completionHandler:)",
        "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSRestoreImage/latestSupported",
        "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSRestoreImage/image(from:)"
      ],
      "title": "Controlling the Restoration Process"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VZMacOSRestoreImage"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZMacOSRestoreImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZMacOSRestoreImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.virtualization/documentation/Virtualization"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-Information-About-the-Restore-Image",
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSRestoreImage/buildVersion",
                "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSRestoreImage/isSupported",
                "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSRestoreImage/mostFeaturefulSupportedConfiguration",
                "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSRestoreImage/operatingSystemVersion",
                "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSRestoreImage/url"
              ],
              "title": "Getting Information About the Restore Image"
            },
            {
              "anchor": "Controlling-the-Restoration-Process",
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSRestoreImage/latestSupported",
                "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSRestoreImage/image(from:)"
              ],
              "title": "Controlling the Restoration Process"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/VZMacHardwareModel"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Installers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSInstaller",
                "doc://com.apple.virtualization/documentation/Virtualization/VZMacOSConfigurationRequirements"
              ],
              "title": "Installers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "VZMacOSRestoreImage"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacOSRestoreImage/title",
          "value": "VZMacOSRestoreImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacOSRestoreImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZMacOSRestoreImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacOSRestoreImage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZMacOSRestoreImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacOSRestoreImage~1isSupported/title",
          "value": "supported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacOSRestoreImage~1isSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacOSRestoreImage~1buildVersion/title",
          "value": "buildVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacOSRestoreImage~1buildVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "buildVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacOSRestoreImage~1latestSupported/title",
          "value": "fetchLatestSupportedWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacOSRestoreImage~1latestSupported/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "fetchLatestSupportedWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacOSRestoreImage~1image(from:)/title",
          "value": "loadFileURL:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacOSRestoreImage~1image(from:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "loadFileURL:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacPlatformConfiguration/title",
          "value": "VZMacPlatformConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacPlatformConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZMacPlatformConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacPlatformConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZMacPlatformConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacOSConfigurationRequirements/title",
          "value": "VZMacOSConfigurationRequirements"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacOSConfigurationRequirements/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZMacOSConfigurationRequirements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacOSConfigurationRequirements/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZMacOSConfigurationRequirements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacOSRestoreImage~1mostFeaturefulSupportedConfiguration/title",
          "value": "mostFeaturefulSupportedConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacOSRestoreImage~1mostFeaturefulSupportedConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mostFeaturefulSupportedConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacPlatformConfiguration~1hardwareModel/title",
          "value": "hardwareModel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacPlatformConfiguration~1hardwareModel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hardwareModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacOSRestoreImage~1url/title",
          "value": "URL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacOSRestoreImage~1url/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "URL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacOSRestoreImage~1operatingSystemVersion/title",
          "value": "operatingSystemVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacOSRestoreImage~1operatingSystemVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "operatingSystemVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacHardwareModel/title",
          "value": "VZMacHardwareModel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacHardwareModel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZMacHardwareModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacHardwareModel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZMacHardwareModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacOSInstaller/title",
          "value": "VZMacOSInstaller"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacOSInstaller/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZMacOSInstaller"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacOSInstaller/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZMacOSInstaller"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/virtualization/vzmacosrestoreimage"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/virtualization/vzmacosrestoreimage"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
