{
  "abstract": [
    {
      "text": "The protocol for configuring USB devices.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.virtualization/documentation/Virtualization"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.virtualization/documentation/Virtualization/VZUSBDeviceConfiguration"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)VZUSBDeviceConfiguration",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "VZUSBDeviceConfiguration"
      }
    ],
    "modules": [
      {
        "name": "Virtualization"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VZUSBDeviceConfiguration"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "VZUSBDeviceConfiguration"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "VZUSBDeviceConfiguration"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Classes that conform to this protocol represent hot-pluggable USB device configurations.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Don’t use the ",
                  "type": "text"
                },
                {
                  "code": "VZUSBDeviceConfiguration",
                  "type": "codeVoice"
                },
                {
                  "text": " protocol with objects outside the Virtualization framework. This protocol only describes capabilities of Virtualization framework objects.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.virtualization/documentation/Virtualization": {
      "abstract": [
        {
          "text": "Create virtual machines and run macOS and Linux-based operating systems.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization",
      "kind": "symbol",
      "role": "collection",
      "title": "Virtualization",
      "type": "topic",
      "url": "/documentation/virtualization"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZUSBDevice": {
      "abstract": [
        {
          "text": "A protocol that represents a USB device in a VM.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZUSBDevice"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZUSBDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZUSBDevice"
        }
      ],
      "role": "symbol",
      "title": "VZUSBDevice",
      "type": "topic",
      "url": "/documentation/virtualization/vzusbdevice"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZUSBDeviceConfiguration": {
      "abstract": [
        {
          "text": "The protocol for configuring USB devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZUSBDeviceConfiguration"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZUSBDeviceConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZUSBDeviceConfiguration"
        }
      ],
      "role": "symbol",
      "title": "VZUSBDeviceConfiguration",
      "type": "topic",
      "url": "/documentation/virtualization/vzusbdeviceconfiguration"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZUSBDeviceConfiguration/uuid": {
      "abstract": [
        {
          "text": "The device’s unique identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uuid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4UUIDV",
          "text": "UUID"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZUSBDeviceConfiguration/uuid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "uuid"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "uuid",
      "type": "topic",
      "url": "/documentation/virtualization/vzusbdeviceconfiguration/uuid"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZUSBMassStorageDeviceConfiguration": {
      "abstract": [
        {
          "text": "The configuration object that represents a USB Mass storage device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZUSBMassStorageDeviceConfiguration"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZUSBMassStorageDeviceConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZUSBMassStorageDeviceConfiguration"
        }
      ],
      "role": "symbol",
      "title": "VZUSBMassStorageDeviceConfiguration",
      "type": "topic",
      "url": "/documentation/virtualization/vzusbmassstoragedeviceconfiguration"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZUSBMassStorageDeviceConfiguration"
      ],
      "kind": "relationships",
      "title": "Conforming Types",
      "type": "conformingTypes"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Protocols",
      "generated": true,
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZUSBDevice"
      ],
      "title": "Protocols"
    }
  ],
  "topicSections": [
    {
      "anchor": "Properties",
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZUSBDeviceConfiguration/uuid"
      ],
      "title": "Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VZUSBDeviceConfiguration"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZUSBDeviceConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZUSBDeviceConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.virtualization/documentation/Virtualization"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Properties",
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/VZUSBDeviceConfiguration/uuid"
              ],
              "title": "Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/VZUSBMassStorageDeviceConfiguration"
              ],
              "kind": "relationships",
              "title": "Conforming Types",
              "type": "conformingTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Protocols",
              "generated": true,
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/VZUSBDevice"
              ],
              "title": "Protocols"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "VZUSBDeviceConfiguration"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZUSBDeviceConfiguration/title",
          "value": "VZUSBDeviceConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZUSBDeviceConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZUSBDeviceConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZUSBDeviceConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZUSBDeviceConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZUSBMassStorageDeviceConfiguration/title",
          "value": "VZUSBMassStorageDeviceConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZUSBMassStorageDeviceConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZUSBMassStorageDeviceConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZUSBMassStorageDeviceConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZUSBMassStorageDeviceConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZUSBDeviceConfiguration~1uuid/title",
          "value": "uuid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZUSBDeviceConfiguration~1uuid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "uuid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZUSBDevice/title",
          "value": "VZUSBDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZUSBDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZUSBDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZUSBDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZUSBDevice"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/virtualization/vzusbdeviceconfiguration"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/virtualization/vzusbdeviceconfiguration"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
