{"seeAlsoSections":[{"anchor":"Configurations","generated":true,"title":"Configurations","identifiers":["doc://com.apple.virtualization/documentation/Virtualization/VZSocketDeviceConfiguration"]}],"metadata":{"symbolKind":"class","platforms":[{"introducedAt":"11.0","name":"macOS","unavailable":false,"deprecated":false,"beta":false}],"modules":[{"name":"Virtualization"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VZVirtioSocketDeviceConfiguration","kind":"identifier"}],"externalID":"c:objc(cs)VZVirtioSocketDeviceConfiguration","roleHeading":"Class","navigatorTitle":[{"text":"VZVirtioSocketDeviceConfiguration","kind":"identifier"}],"role":"symbol","title":"VZVirtioSocketDeviceConfiguration"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.virtualization/documentation/Virtualization"]]},"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc://com.apple.virtualization/documentation/Virtualization/VZSocketDeviceConfiguration"]},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc://com.externally.resolved.symbol/s:s7CVarArgP","doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","doc://com.externally.resolved.symbol/c:objc(pl)NSObject"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/virtualization/vzvirtiosocketdeviceconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/virtualization/vzvirtiosocketdeviceconfiguration"]}],"topicSections":[{"anchor":"Creating-the-Configuration-Object","title":"Creating the Configuration Object","identifiers":["doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSocketDeviceConfiguration/init()"]}],"abstract":[{"text":"A configuration object that requests the creation of a socket device to communicate with the guest system.","type":"text"}],"identifier":{"url":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSocketDeviceConfiguration","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VZVirtioSocketDeviceConfiguration","kind":"identifier"}],"languages":["swift"],"platforms":["macOS"]}]},{"content":[{"anchor":"overview","type":"heading","level":2,"text":"Overview"},{"inlineContent":[{"text":"Use a ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSocketDeviceConfiguration"},{"text":" object to implement port-based communication between the guest operating system and the host computer. When you add this object to the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/socketDevices"},{"text":" property of your ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration"},{"text":", the virtual machine provides a corresponding ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSocketDevice"},{"text":" object to use to configure the ports. Add only one ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSocketDeviceConfiguration"},{"text":" to your virtual machine’s configuration.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","references":{"doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSocketDeviceConfiguration":{"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VZVirtioSocketDeviceConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"VZVirtioSocketDeviceConfiguration","kind":"identifier"}],"abstract":[{"text":"A configuration object that requests the creation of a socket device to communicate with the guest system.","type":"text"}],"role":"symbol","title":"VZVirtioSocketDeviceConfiguration","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSocketDeviceConfiguration","url":"/documentation/virtualization/vzvirtiosocketdeviceconfiguration"},"doc://com.apple.virtualization/documentation/Virtualization/VZSocketDeviceConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"VZSocketDeviceConfiguration"}],"title":"VZSocketDeviceConfiguration","type":"topic","url":"/documentation/virtualization/vzsocketdeviceconfiguration","kind":"symbol","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZSocketDeviceConfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VZSocketDeviceConfiguration"}],"abstract":[{"text":"The common configuration traits for socket device requests.","type":"text"}]},"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying":{"title":"NSCopying","role":"symbol","kind":"symbol","abstract":[{"text":"A protocol that objects adopt to provide functional copies of themselves.","type":"text"}],"type":"topic","url":"/documentation/foundation/nscopying","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSCopying","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:SH":{"type":"topic","abstract":[{"text":"A type that can be hashed into a `Hasher` to produce an integer hash value.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hashable","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SQ","text":"Equatable","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SH","title":"Hashable","url":"/documentation/Swift/Hashable"},"doc://com.externally.resolved.symbol/s:SQ":{"abstract":[{"type":"text","text":"A type that can be compared for value equality."}],"title":"Equatable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Equatable"}],"identifier":"doc://com.externally.resolved.symbol/s:SQ","kind":"symbol","url":"/documentation/Swift/Equatable","type":"topic","role":"symbol"},"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP":{"type":"topic","abstract":[{"text":"A type with a customized textual representation.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomStringConvertible","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","title":"CustomStringConvertible","url":"/documentation/Swift/CustomStringConvertible"},"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/socketDevices":{"type":"topic","abstract":[{"text":"The socket device that you use to implement port-based communication with the guest operating system.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"socketDevices"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)VZSocketDeviceConfiguration","text":"VZSocketDeviceConfiguration"},{"kind":"text","text":"]"}],"role":"symbol","kind":"symbol","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration/socketDevices","title":"socketDevices","navigatorTitle":[{"kind":"identifier","text":"socketDevices"}],"url":"/documentation/virtualization/vzvirtualmachineconfiguration/socketdevices"},"doc://com.apple.virtualization/documentation/Virtualization":{"type":"topic","abstract":[{"text":"Create virtual machines and run macOS and Linux-based operating systems.","type":"text"}],"role":"collection","kind":"symbol","identifier":"doc://com.apple.virtualization/documentation/Virtualization","title":"Virtualization","url":"/documentation/virtualization"},"doc://com.externally.resolved.symbol/s:s7CVarArgP":{"abstract":[{"type":"text","text":"A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`."}],"title":"CVarArg","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CVarArg"}],"identifier":"doc://com.externally.resolved.symbol/s:s7CVarArgP","kind":"symbol","url":"/documentation/Swift/CVarArg","type":"topic","role":"symbol"},"doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSocketDevice":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VZVirtioSocketDevice"}],"role":"symbol","type":"topic","url":"/documentation/virtualization/vzvirtiosocketdevice","navigatorTitle":[{"kind":"identifier","text":"VZVirtioSocketDevice"}],"title":"VZVirtioSocketDevice","kind":"symbol","abstract":[{"text":"A device that manages port-based connections between the guest system and the host computer.","type":"text"}],"identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSocketDevice"},"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"title":"NSObjectProtocol","role":"symbol","kind":"symbol","abstract":[{"text":"The group of methods that are fundamental to all Objective-C objects.","type":"text"}],"type":"topic","url":"/documentation/objectivec/nsobjectprotocol","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSObjectProtocol","kind":"identifier"}]},"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration":{"type":"topic","abstract":[{"type":"text","text":"The environment attributes and list of devices to use during the configuration of macOS or Linux VMs."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"VZVirtualMachineConfiguration","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachineConfiguration","title":"VZVirtualMachineConfiguration","navigatorTitle":[{"text":"VZVirtualMachineConfiguration","kind":"identifier"}],"url":"/documentation/virtualization/vzvirtualmachineconfiguration"},"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP":{"type":"topic","abstract":[{"text":"A type with a customized textual representation suitable for debugging purposes.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomDebugStringConvertible","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","title":"CustomDebugStringConvertible","url":"/documentation/Swift/CustomDebugStringConvertible"},"doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSocketDeviceConfiguration/init()":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"type":"topic","title":"init()","role":"symbol","abstract":[{"type":"text","text":"Creates a socket device configuration object."}],"identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSocketDeviceConfiguration/init()","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"/documentation/virtualization/vzvirtiosocketdeviceconfiguration/init()","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","role":"overview","kind":"technologies","abstract":[{"text":"","type":"text"}],"type":"topic","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"unavailable":false,"introducedAt":"11.0","deprecated":false,"name":"macOS","beta":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Class","op":"replace","path":"/metadata/roleHeading"},{"op":"replace","path":"/metadata/title","value":"VZVirtioSocketDeviceConfiguration"},{"op":"replace","path":"/metadata/symbolKind","value":"class"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"VZVirtioSocketDeviceConfiguration","kind":"identifier"}]},{"op":"replace","path":"/metadata/navigatorTitle","value":[{"kind":"identifier","text":"VZVirtioSocketDeviceConfiguration"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.virtualization/documentation/Virtualization"]]}},{"op":"replace","path":"/topicSections","value":[{"identifiers":["doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSocketDeviceConfiguration/init()"],"title":"Creating the Configuration Object","anchor":"Creating-the-Configuration-Object"}]},{"op":"replace","path":"/relationshipsSections","value":[{"identifiers":["doc://com.apple.virtualization/documentation/Virtualization/VZSocketDeviceConfiguration"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}]},{"op":"replace","path":"/seeAlsoSections","value":[{"generated":true,"anchor":"Configurations","title":"Configurations","identifiers":["doc://com.apple.virtualization/documentation/Virtualization/VZSocketDeviceConfiguration"]}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VZVirtioSocketDeviceConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"VZSocketDeviceConfiguration","preciseIdentifier":"c:objc(cs)VZSocketDeviceConfiguration","kind":"typeIdentifier","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZSocketDeviceConfiguration"}],"platforms":["macOS"]}],"kind":"declarations"}},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSocketDeviceConfiguration/title","op":"replace","value":"VZVirtioSocketDeviceConfiguration"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSocketDeviceConfiguration/fragments","op":"replace","value":[{"kind":"identifier","text":"VZVirtioSocketDeviceConfiguration"}]},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSocketDeviceConfiguration/navigatorTitle","op":"replace","value":[{"text":"VZVirtioSocketDeviceConfiguration","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZSocketDeviceConfiguration/title","op":"replace","value":"VZSocketDeviceConfiguration"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZSocketDeviceConfiguration/fragments","op":"replace","value":[{"text":"VZSocketDeviceConfiguration","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZSocketDeviceConfiguration/navigatorTitle","op":"replace","value":[{"text":"VZSocketDeviceConfiguration","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1socketDevices/title","op":"replace","value":"socketDevices"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1socketDevices/fragments","op":"replace","value":[{"text":"socketDevices","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSocketDevice/title","op":"replace","value":"VZVirtioSocketDevice"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSocketDevice/fragments","op":"replace","value":[{"kind":"identifier","text":"VZVirtioSocketDevice"}]},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSocketDevice/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"VZVirtioSocketDevice"}]},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title","op":"replace","value":"NSObject"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration/title","op":"replace","value":"VZVirtualMachineConfiguration"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration/fragments","op":"replace","value":[{"kind":"identifier","text":"VZVirtualMachineConfiguration"}]},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachineConfiguration/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"VZVirtualMachineConfiguration"}]},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSocketDeviceConfiguration~1init()/title","op":"replace","value":"init"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSocketDeviceConfiguration~1init()/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}