{
  "abstract": [
    {
      "text": "An object that defines a Virtio sound device output stream configuration.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.virtualization/documentation/Virtualization"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSoundDeviceOutputStreamConfiguration"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)VZVirtioSoundDeviceOutputStreamConfiguration",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "VZVirtioSoundDeviceOutputStreamConfiguration"
      }
    ],
    "modules": [
      {
        "name": "Virtualization"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VZVirtioSoundDeviceOutputStreamConfiguration"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "VZVirtioSoundDeviceOutputStreamConfiguration"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "VZVirtioSoundDeviceOutputStreamConfiguration"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.virtualization/documentation/Virtualization/creating-and-running-a-linux-virtual-machine"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A PCM stream of output audio data, such as to a speaker.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.virtualization/documentation/Virtualization": {
      "abstract": [
        {
          "text": "Create virtual machines and run macOS and Linux-based operating systems.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization",
      "kind": "symbol",
      "role": "collection",
      "title": "Virtualization",
      "type": "topic",
      "url": "/documentation/virtualization"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZAudioDeviceConfiguration": {
      "abstract": [
        {
          "text": "The base class for an audio device configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZAudioDeviceConfiguration"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZAudioDeviceConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZAudioDeviceConfiguration"
        }
      ],
      "role": "symbol",
      "title": "VZAudioDeviceConfiguration",
      "type": "topic",
      "url": "/documentation/virtualization/vzaudiodeviceconfiguration"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZAudioOutputStreamSink": {
      "abstract": [
        {
          "text": "The base class for an audio output stream sink.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZAudioOutputStreamSink"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZAudioOutputStreamSink",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZAudioOutputStreamSink"
        }
      ],
      "role": "symbol",
      "title": "VZAudioOutputStreamSink",
      "type": "topic",
      "url": "/documentation/virtualization/vzaudiooutputstreamsink"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZHostAudioOutputStreamSink": {
      "abstract": [
        {
          "text": "Host audio output stream sink plays audio to the host system’s default output device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZHostAudioOutputStreamSink"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZHostAudioOutputStreamSink",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZHostAudioOutputStreamSink"
        }
      ],
      "role": "symbol",
      "title": "VZHostAudioOutputStreamSink",
      "type": "topic",
      "url": "/documentation/virtualization/vzhostaudiooutputstreamsink"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSoundDeviceConfiguration": {
      "abstract": [
        {
          "text": "An object that defines a Virtio sound device configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZVirtioSoundDeviceConfiguration"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSoundDeviceConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZVirtioSoundDeviceConfiguration"
        }
      ],
      "role": "symbol",
      "title": "VZVirtioSoundDeviceConfiguration",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtiosounddeviceconfiguration"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSoundDeviceInputStreamConfiguration": {
      "abstract": [
        {
          "text": "A PCM stream of input audio data, such as from a microphone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZVirtioSoundDeviceInputStreamConfiguration"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSoundDeviceInputStreamConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZVirtioSoundDeviceInputStreamConfiguration"
        }
      ],
      "role": "symbol",
      "title": "VZVirtioSoundDeviceInputStreamConfiguration",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtiosounddeviceinputstreamconfiguration"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSoundDeviceOutputStreamConfiguration": {
      "abstract": [
        {
          "text": "An object that defines a Virtio sound device output stream configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZVirtioSoundDeviceOutputStreamConfiguration"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSoundDeviceOutputStreamConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZVirtioSoundDeviceOutputStreamConfiguration"
        }
      ],
      "role": "symbol",
      "title": "VZVirtioSoundDeviceOutputStreamConfiguration",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtiosounddeviceoutputstreamconfiguration"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSoundDeviceOutputStreamConfiguration/init()": {
      "abstract": [
        {
          "text": "Creates a new sounds device output stream configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSoundDeviceOutputStreamConfiguration/init()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "init"
        }
      ],
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtiosounddeviceoutputstreamconfiguration/init()"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSoundDeviceOutputStreamConfiguration/sink": {
      "abstract": [
        {
          "text": "An audio stream sink that defines how the host handles audio data produced by the guest.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sink"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VZAudioOutputStreamSink",
          "text": "VZAudioOutputStreamSink"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSoundDeviceOutputStreamConfiguration/sink",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sink"
        }
      ],
      "role": "symbol",
      "title": "sink",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtiosounddeviceoutputstreamconfiguration/sink"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSoundDeviceStreamConfiguration": {
      "abstract": [
        {
          "text": "An object that defines a Virtio sound device stream configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZVirtioSoundDeviceStreamConfiguration"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSoundDeviceStreamConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZVirtioSoundDeviceStreamConfiguration"
        }
      ],
      "role": "symbol",
      "title": "VZVirtioSoundDeviceStreamConfiguration",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtiosounddevicestreamconfiguration"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/creating-and-running-a-linux-virtual-machine": {
      "abstract": [
        {
          "text": "Design and run custom Linux guests on Apple silicon or Intel-based Mac Computers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/creating-and-running-a-linux-virtual-machine",
      "kind": "article",
      "role": "article",
      "title": "Creating and Running a Linux Virtual Machine",
      "type": "topic",
      "url": "/documentation/virtualization/creating-and-running-a-linux-virtual-machine"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSoundDeviceStreamConfiguration"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configurations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSoundDeviceConfiguration",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSoundDeviceInputStreamConfiguration",
        "doc://com.apple.virtualization/documentation/Virtualization/VZAudioDeviceConfiguration",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSoundDeviceStreamConfiguration"
      ],
      "title": "Configurations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-an-output-stream-configuration",
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSoundDeviceOutputStreamConfiguration/init()"
      ],
      "title": "Creating an output stream configuration"
    },
    {
      "anchor": "Accessing-the-sound-sink",
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSoundDeviceOutputStreamConfiguration/sink"
      ],
      "title": "Accessing the sound sink"
    },
    {
      "anchor": "Output-sink",
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZHostAudioOutputStreamSink",
        "doc://com.apple.virtualization/documentation/Virtualization/VZAudioOutputStreamSink"
      ],
      "title": "Output sink"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VZVirtioSoundDeviceOutputStreamConfiguration"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtioSoundDeviceOutputStreamConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtioSoundDeviceOutputStreamConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.virtualization/documentation/Virtualization"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-an-output-stream-configuration",
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSoundDeviceOutputStreamConfiguration/init()"
              ],
              "title": "Creating an output stream configuration"
            },
            {
              "anchor": "Accessing-the-sound-sink",
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSoundDeviceOutputStreamConfiguration/sink"
              ],
              "title": "Accessing the sound sink"
            },
            {
              "anchor": "Output-sink",
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/VZHostAudioOutputStreamSink",
                "doc://com.apple.virtualization/documentation/Virtualization/VZAudioOutputStreamSink"
              ],
              "title": "Output sink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSoundDeviceStreamConfiguration"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configurations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSoundDeviceConfiguration",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSoundDeviceInputStreamConfiguration",
                "doc://com.apple.virtualization/documentation/Virtualization/VZAudioDeviceConfiguration",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSoundDeviceStreamConfiguration"
              ],
              "title": "Configurations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "VZVirtioSoundDeviceOutputStreamConfiguration"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSoundDeviceStreamConfiguration",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)VZVirtioSoundDeviceStreamConfiguration",
                    "text": "VZVirtioSoundDeviceStreamConfiguration"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSoundDeviceOutputStreamConfiguration~1init()/title",
          "value": "init"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSoundDeviceOutputStreamConfiguration~1init()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "init"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZHostAudioOutputStreamSink/title",
          "value": "VZHostAudioOutputStreamSink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZHostAudioOutputStreamSink/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZHostAudioOutputStreamSink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZHostAudioOutputStreamSink/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZHostAudioOutputStreamSink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZAudioDeviceConfiguration/title",
          "value": "VZAudioDeviceConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZAudioDeviceConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZAudioDeviceConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZAudioDeviceConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZAudioDeviceConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSoundDeviceConfiguration/title",
          "value": "VZVirtioSoundDeviceConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSoundDeviceConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtioSoundDeviceConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSoundDeviceConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtioSoundDeviceConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSoundDeviceOutputStreamConfiguration~1sink/title",
          "value": "sink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSoundDeviceOutputStreamConfiguration~1sink/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSoundDeviceStreamConfiguration/title",
          "value": "VZVirtioSoundDeviceStreamConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSoundDeviceStreamConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtioSoundDeviceStreamConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSoundDeviceStreamConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtioSoundDeviceStreamConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSoundDeviceInputStreamConfiguration/title",
          "value": "VZVirtioSoundDeviceInputStreamConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSoundDeviceInputStreamConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtioSoundDeviceInputStreamConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSoundDeviceInputStreamConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtioSoundDeviceInputStreamConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSoundDeviceOutputStreamConfiguration/title",
          "value": "VZVirtioSoundDeviceOutputStreamConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSoundDeviceOutputStreamConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtioSoundDeviceOutputStreamConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSoundDeviceOutputStreamConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtioSoundDeviceOutputStreamConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZAudioOutputStreamSink/title",
          "value": "VZAudioOutputStreamSink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZAudioOutputStreamSink/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZAudioOutputStreamSink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZAudioOutputStreamSink/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZAudioOutputStreamSink"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/virtualization/vzvirtiosounddeviceoutputstreamconfiguration"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/virtualization/vzvirtiosounddeviceoutputstreamconfiguration"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
