{"abstract":[{"type":"text","text":"The configuration object for the USB Extensible Host Controller Interface (XHCI) controller."}],"topicSections":[{"anchor":"Initializers","identifiers":["doc://com.apple.virtualization/documentation/Virtualization/VZXHCIControllerConfiguration/init()"],"title":"Initializers"}],"kind":"symbol","sections":[],"relationshipsSections":[{"identifiers":["doc://com.apple.virtualization/documentation/Virtualization/VZUSBControllerConfiguration"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc://com.externally.resolved.symbol/s:s7CVarArgP","doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","doc://com.externally.resolved.symbol/c:objc(pl)NSObject"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.virtualization/documentation/Virtualization"]]},"seeAlsoSections":[{"anchor":"Configurations","identifiers":["doc://com.apple.virtualization/documentation/Virtualization/VZUSBControllerConfiguration"],"title":"Configurations","generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VZXHCIControllerConfiguration","kind":"identifier"}],"languages":["swift"]}]},{"content":[{"level":2,"anchor":"overview","type":"heading","text":"Overview"},{"inlineContent":[{"text":"Use this configuration to create a USB XHCI controller device for the guest.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"identifier":{"url":"doc://com.apple.virtualization/documentation/Virtualization/VZXHCIControllerConfiguration","interfaceLanguage":"swift"},"metadata":{"symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"VZXHCIControllerConfiguration"}],"role":"symbol","roleHeading":"Class","modules":[{"name":"Virtualization"}],"title":"VZXHCIControllerConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VZXHCIControllerConfiguration"}],"platforms":[{"beta":false,"name":"macOS","introducedAt":"15.0","unavailable":false,"deprecated":false}],"externalID":"c:objc(cs)VZXHCIControllerConfiguration"},"variants":[{"paths":["/documentation/virtualization/vzxhcicontrollerconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/virtualization/vzxhcicontrollerconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.externally.resolved.symbol/s:SH":{"type":"topic","abstract":[{"text":"A type that can be hashed into a `Hasher` to produce an integer hash value.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hashable","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SQ","text":"Equatable","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SH","title":"Hashable","url":"/documentation/Swift/Hashable"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","role":"overview","kind":"technologies","abstract":[{"text":"","type":"text"}],"type":"topic","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies"},"doc://com.apple.virtualization/documentation/Virtualization":{"type":"topic","abstract":[{"text":"Create virtual machines and run macOS and Linux-based operating systems.","type":"text"}],"role":"collection","kind":"symbol","identifier":"doc://com.apple.virtualization/documentation/Virtualization","title":"Virtualization","url":"/documentation/virtualization"},"doc://com.apple.virtualization/documentation/Virtualization/VZXHCIControllerConfiguration/init()":{"abstract":[{"type":"text","text":"Creates a USB Extensible Host Controller Interface (XHCI) configuration."}],"type":"topic","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZXHCIControllerConfiguration/init()","title":"init()","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"url":"/documentation/virtualization/vzxhcicontrollerconfiguration/init()"},"doc://com.externally.resolved.symbol/s:s7CVarArgP":{"abstract":[{"type":"text","text":"A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`."}],"title":"CVarArg","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CVarArg"}],"identifier":"doc://com.externally.resolved.symbol/s:s7CVarArgP","kind":"symbol","url":"/documentation/Swift/CVarArg","type":"topic","role":"symbol"},"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP":{"type":"topic","abstract":[{"text":"A type with a customized textual representation.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomStringConvertible","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","title":"CustomStringConvertible","url":"/documentation/Swift/CustomStringConvertible"},"doc://com.apple.virtualization/documentation/Virtualization/VZUSBControllerConfiguration":{"title":"VZUSBControllerConfiguration","role":"symbol","navigatorTitle":[{"text":"VZUSBControllerConfiguration","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"The base class for a USB controller configuration.","type":"text"}],"type":"topic","url":"/documentation/virtualization/vzusbcontrollerconfiguration","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZUSBControllerConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VZUSBControllerConfiguration","kind":"identifier"}]},"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"title":"NSObjectProtocol","role":"symbol","kind":"symbol","abstract":[{"text":"The group of methods that are fundamental to all Objective-C objects.","type":"text"}],"type":"topic","url":"/documentation/objectivec/nsobjectprotocol","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSObjectProtocol","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:SQ":{"abstract":[{"type":"text","text":"A type that can be compared for value equality."}],"title":"Equatable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Equatable"}],"identifier":"doc://com.externally.resolved.symbol/s:SQ","kind":"symbol","url":"/documentation/Swift/Equatable","type":"topic","role":"symbol"},"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP":{"type":"topic","abstract":[{"text":"A type with a customized textual representation suitable for debugging purposes.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomDebugStringConvertible","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","title":"CustomDebugStringConvertible","url":"/documentation/Swift/CustomDebugStringConvertible"},"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying":{"title":"NSCopying","role":"symbol","kind":"symbol","abstract":[{"text":"A protocol that objects adopt to provide functional copies of themselves.","type":"text"}],"type":"topic","url":"/documentation/foundation/nscopying","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSCopying","kind":"identifier"}]},"doc://com.apple.virtualization/documentation/Virtualization/VZXHCIControllerConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VZXHCIControllerConfiguration","kind":"identifier"}],"title":"VZXHCIControllerConfiguration","url":"/documentation/virtualization/vzxhcicontrollerconfiguration","role":"symbol","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZXHCIControllerConfiguration","abstract":[{"text":"The configuration object for the USB Extensible Host Controller Interface (XHCI) controller.","type":"text"}],"navigatorTitle":[{"text":"VZXHCIControllerConfiguration","kind":"identifier"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"beta":false,"name":"macOS","introducedAt":"15.0","unavailable":false,"deprecated":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Class","op":"replace"},{"path":"/metadata/title","value":"VZXHCIControllerConfiguration","op":"replace"},{"path":"/metadata/symbolKind","value":"class","op":"replace"},{"path":"/metadata/fragments","value":[{"kind":"identifier","text":"VZXHCIControllerConfiguration"}],"op":"replace"},{"path":"/metadata/navigatorTitle","value":[{"kind":"identifier","text":"VZXHCIControllerConfiguration"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.virtualization/documentation/Virtualization"]]},"op":"replace"},{"path":"/topicSections","value":[{"identifiers":["doc://com.apple.virtualization/documentation/Virtualization/VZXHCIControllerConfiguration/init()"],"title":"Initializers","anchor":"Initializers"}],"op":"replace"},{"path":"/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc://com.apple.virtualization/documentation/Virtualization/VZUSBControllerConfiguration"]}],"op":"replace"},{"path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.virtualization/documentation/Virtualization/VZUSBControllerConfiguration"],"title":"Configurations","generated":true,"anchor":"Configurations"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"declarations":[{"platforms":["macOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VZXHCIControllerConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"VZUSBControllerConfiguration","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZUSBControllerConfiguration","preciseIdentifier":"c:objc(cs)VZUSBControllerConfiguration","kind":"typeIdentifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZXHCIControllerConfiguration~1init()/title","op":"replace","value":"init"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZXHCIControllerConfiguration~1init()/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZUSBControllerConfiguration/title","op":"replace","value":"VZUSBControllerConfiguration"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZUSBControllerConfiguration/fragments","op":"replace","value":[{"text":"VZUSBControllerConfiguration","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZUSBControllerConfiguration/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"VZUSBControllerConfiguration"}]},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title","op":"replace","value":"NSObject"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZXHCIControllerConfiguration/title","op":"replace","value":"VZXHCIControllerConfiguration"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZXHCIControllerConfiguration/fragments","op":"replace","value":[{"text":"VZXHCIControllerConfiguration","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZXHCIControllerConfiguration/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"VZXHCIControllerConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}