{
  "abstract": [
    {
      "text": "Another device answered the call.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.callkit/documentation/CallKit",
        "doc://com.apple.callkit/documentation/CallKit/CXCallEndedReason"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.callkit/documentation/CallKit/CXCallEndedReason/answeredElsewhere"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CXCallEndedReason@CXCallEndedReasonAnsweredElsewhere",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "answeredElsewhere"
      }
    ],
    "modules": [
      {
        "name": "CallKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CXCallEndedReasonAnsweredElsewhere"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CXCallEndedReason.answeredElsewhere"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "answeredElsewhere"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.callkit/documentation/CallKit": {
      "abstract": [
        {
          "text": "Display the system-calling UI for your app’s VoIP services, and coordinate your calling services with other apps and the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CallKit",
      "type": "topic",
      "url": "/documentation/callkit"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXCallEndedReason": {
      "abstract": [
        {
          "text": "The reason that a call ended.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CXCallEndedReason"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXCallEndedReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXCallEndedReason"
        }
      ],
      "role": "symbol",
      "title": "CXCallEndedReason",
      "type": "topic",
      "url": "/documentation/callkit/cxcallendedreason"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXCallEndedReason/answeredElsewhere": {
      "abstract": [
        {
          "text": "Another device answered the call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "answeredElsewhere"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXCallEndedReason/answeredElsewhere",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXCallEndedReasonAnsweredElsewhere"
        }
      ],
      "role": "symbol",
      "title": "CXCallEndedReason.answeredElsewhere",
      "type": "topic",
      "url": "/documentation/callkit/cxcallendedreason/answeredelsewhere"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXCallEndedReason/declinedElsewhere": {
      "abstract": [
        {
          "text": "Another device declined the call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "declinedElsewhere"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXCallEndedReason/declinedElsewhere",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXCallEndedReasonDeclinedElsewhere"
        }
      ],
      "role": "symbol",
      "title": "CXCallEndedReason.declinedElsewhere",
      "type": "topic",
      "url": "/documentation/callkit/cxcallendedreason/declinedelsewhere"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXCallEndedReason/failed": {
      "abstract": [
        {
          "text": "An error occurred while attempting to service the call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failed"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXCallEndedReason/failed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXCallEndedReasonFailed"
        }
      ],
      "role": "symbol",
      "title": "CXCallEndedReason.failed",
      "type": "topic",
      "url": "/documentation/callkit/cxcallendedreason/failed"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXCallEndedReason/remoteEnded": {
      "abstract": [
        {
          "text": "The remote party explicitly ended the call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remoteEnded"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXCallEndedReason/remoteEnded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXCallEndedReasonRemoteEnded"
        }
      ],
      "role": "symbol",
      "title": "CXCallEndedReason.remoteEnded",
      "type": "topic",
      "url": "/documentation/callkit/cxcallendedreason/remoteended"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXCallEndedReason/unanswered": {
      "abstract": [
        {
          "text": "The call never started connecting and was never explicitly ended, such as when an outgoing or incoming call times out.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unanswered"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXCallEndedReason/unanswered",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXCallEndedReasonUnanswered"
        }
      ],
      "role": "symbol",
      "title": "CXCallEndedReason.unanswered",
      "type": "topic",
      "url": "/documentation/callkit/cxcallendedreason/unanswered"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.callkit/documentation/CallKit/CXCallEndedReason/failed",
        "doc://com.apple.callkit/documentation/CallKit/CXCallEndedReason/remoteEnded",
        "doc://com.apple.callkit/documentation/CallKit/CXCallEndedReason/unanswered",
        "doc://com.apple.callkit/documentation/CallKit/CXCallEndedReason/declinedElsewhere"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CXCallEndedReasonAnsweredElsewhere"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXCallEndedReasonAnsweredElsewhere"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.callkit/documentation/CallKit",
                "doc://com.apple.callkit/documentation/CallKit/CXCallEndedReason"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.callkit/documentation/CallKit/CXCallEndedReason/failed",
                "doc://com.apple.callkit/documentation/CallKit/CXCallEndedReason/remoteEnded",
                "doc://com.apple.callkit/documentation/CallKit/CXCallEndedReason/unanswered",
                "doc://com.apple.callkit/documentation/CallKit/CXCallEndedReason/declinedElsewhere"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "CXCallEndedReasonAnsweredElsewhere"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallEndedReason~1answeredElsewhere/title",
          "value": "CXCallEndedReasonAnsweredElsewhere"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallEndedReason~1answeredElsewhere/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXCallEndedReasonAnsweredElsewhere"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallEndedReason~1unanswered/title",
          "value": "CXCallEndedReasonUnanswered"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallEndedReason~1unanswered/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXCallEndedReasonUnanswered"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallEndedReason~1remoteEnded/title",
          "value": "CXCallEndedReasonRemoteEnded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallEndedReason~1remoteEnded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXCallEndedReasonRemoteEnded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallEndedReason~1declinedElsewhere/title",
          "value": "CXCallEndedReasonDeclinedElsewhere"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallEndedReason~1declinedElsewhere/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXCallEndedReasonDeclinedElsewhere"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallEndedReason/title",
          "value": "CXCallEndedReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallEndedReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXCallEndedReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallEndedReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CXCallEndedReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallEndedReason~1failed/title",
          "value": "CXCallEndedReasonFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallEndedReason~1failed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXCallEndedReasonFailed"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/callkit/cxcallendedreason/answeredelsewhere"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/callkit/cxcallendedreason/answeredelsewhere"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
