{
  "abstract": [
    {
      "text": "Linear keyframe values are interpolated to produce an even pace throughout the animation.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartzcore/documentation/QuartzCore",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationCalculationMode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationCalculationMode/paced"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "QuartzCore",
    "externalID": "c:@kCAAnimationPaced",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "paced"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CAAnimationCalculationMode",
        "text": "CAAnimationCalculationMode"
      }
    ],
    "modules": [
      {
        "name": "Core Animation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCAAnimationPaced"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "paced"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "paced"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationCalculationMode",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CAAnimationCalculationMode",
              "text": "CAAnimationCalculationMode"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "code": "kCAAnimationPaced",
              "type": "codeVoice"
            },
            {
              "text": " gives a linearly interpolated animation, but ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation/keyTimes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimation/timingFunction",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " are ignored and keyframe times are automatically generated to give the animation a constant velocity.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following code shows how to create a keyframe animation object using paced interpolation.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Listing 1. Creating paced key values",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let keyframeAnimation = CAKeyframeAnimation(keyPath: \"position.y\")",
            "keyframeAnimation.calculationMode = kCAAnimationPaced",
            "keyframeAnimation.values = [310, 60, 120, 60, 310]"
          ],
          "syntax": "objc",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "A layer animated with the keyframe animation created by the code above and with linearly interpolated horizontal movement would describe a path similar to the following figure.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2776792",
              "type": "image"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore": {
      "abstract": [
        {
          "text": "Render, compose, and animate visual elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Animation",
      "type": "topic",
      "url": "/documentation/quartzcore"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimation/timingFunction": {
      "abstract": [
        {
          "text": "An optional timing function defining the pacing of the animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timingFunction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CAMediaTimingFunction",
          "text": "CAMediaTimingFunction"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimation/timingFunction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "timingFunction"
        }
      ],
      "role": "symbol",
      "title": "timingFunction",
      "type": "topic",
      "url": "/documentation/quartzcore/caanimation/timingfunction"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationCalculationMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAAnimationCalculationMode"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationCalculationMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAAnimationCalculationMode"
        }
      ],
      "role": "symbol",
      "title": "CAAnimationCalculationMode",
      "type": "topic",
      "url": "/documentation/quartzcore/caanimationcalculationmode"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationCalculationMode/cubic": {
      "abstract": [
        {
          "text": "Smooth spline calculation between keyframe values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cubic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CAAnimationCalculationMode",
          "text": "CAAnimationCalculationMode"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationCalculationMode/cubic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAAnimationCubic"
        }
      ],
      "role": "symbol",
      "title": "cubic",
      "type": "topic",
      "url": "/documentation/quartzcore/caanimationcalculationmode/cubic"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationCalculationMode/cubicPaced": {
      "abstract": [
        {
          "text": "Cubic keyframe values are interpolated to produce an even pace throughout the animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cubicPaced"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CAAnimationCalculationMode",
          "text": "CAAnimationCalculationMode"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationCalculationMode/cubicPaced",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAAnimationCubicPaced"
        }
      ],
      "role": "symbol",
      "title": "cubicPaced",
      "type": "topic",
      "url": "/documentation/quartzcore/caanimationcalculationmode/cubicpaced"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationCalculationMode/discrete": {
      "abstract": [
        {
          "text": "Each keyframe value is used in turn, no interpolated values are calculated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "discrete"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CAAnimationCalculationMode",
          "text": "CAAnimationCalculationMode"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationCalculationMode/discrete",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAAnimationDiscrete"
        }
      ],
      "role": "symbol",
      "title": "discrete",
      "type": "topic",
      "url": "/documentation/quartzcore/caanimationcalculationmode/discrete"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationCalculationMode/linear": {
      "abstract": [
        {
          "text": "Simple linear calculation between keyframe values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "linear"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CAAnimationCalculationMode",
          "text": "CAAnimationCalculationMode"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationCalculationMode/linear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAAnimationLinear"
        }
      ],
      "role": "symbol",
      "title": "linear",
      "type": "topic",
      "url": "/documentation/quartzcore/caanimationcalculationmode/linear"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationCalculationMode/paced": {
      "abstract": [
        {
          "text": "Linear keyframe values are interpolated to produce an even pace throughout the animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paced"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CAAnimationCalculationMode",
          "text": "CAAnimationCalculationMode"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationCalculationMode/paced",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAAnimationPaced"
        }
      ],
      "role": "symbol",
      "title": "paced",
      "type": "topic",
      "url": "/documentation/quartzcore/caanimationcalculationmode/paced"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation/keyTimes": {
      "abstract": [
        {
          "text": "An optional array of ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " objects that define the time at which to apply a given keyframe segment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyTimes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation/keyTimes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "keyTimes"
        }
      ],
      "role": "symbol",
      "title": "keyTimes",
      "type": "topic",
      "url": "/documentation/quartzcore/cakeyframeanimation/keytimes"
    },
    "media-2776792": {
      "alt": "Tracing the path of an animation using paced key values",
      "identifier": "media-2776792",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/59fe9ad7c28a77c4f7d2456ef55d3394/media-2776792@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationCalculationMode/linear",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationCalculationMode/discrete",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationCalculationMode/cubic",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationCalculationMode/cubicPaced"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCAAnimationPaced"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAAnimationPaced"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.quartzcore/documentation/QuartzCore"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationCalculationMode/linear",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationCalculationMode/discrete",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationCalculationMode/cubic",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationCalculationMode/cubicPaced"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationCalculationMode",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CAAnimationCalculationMode",
                    "text": "CAAnimationCalculationMode"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCAAnimationPaced"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimation~1timingFunction/title",
          "value": "timingFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimation~1timingFunction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "timingFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAKeyframeAnimation~1keyTimes/title",
          "value": "keyTimes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAKeyframeAnimation~1keyTimes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "keyTimes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimationCalculationMode/title",
          "value": "CAAnimationCalculationMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimationCalculationMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAAnimationCalculationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimationCalculationMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAAnimationCalculationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimationCalculationMode~1paced/title",
          "value": "kCAAnimationPaced"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimationCalculationMode~1paced/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAAnimationPaced"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimationCalculationMode~1cubicPaced/title",
          "value": "kCAAnimationCubicPaced"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimationCalculationMode~1cubicPaced/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAAnimationCubicPaced"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimationCalculationMode~1discrete/title",
          "value": "kCAAnimationDiscrete"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimationCalculationMode~1discrete/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAAnimationDiscrete"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimationCalculationMode~1cubic/title",
          "value": "kCAAnimationCubic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimationCalculationMode~1cubic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAAnimationCubic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimationCalculationMode~1linear/title",
          "value": "kCAAnimationLinear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimationCalculationMode~1linear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAAnimationLinear"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartzcore/caanimationcalculationmode/paced"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartzcore/caanimationcalculationmode/paced"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
