{"kind":"symbol","metadata":{"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prompt","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"modules":[{"name":"UIKit"}],"navigatorTitle":[{"text":"prompt","kind":"identifier"}],"title":"prompt","role":"symbol","externalID":"c:objc(cs)UISearchBar(py)prompt","symbolKind":"property","platforms":[{"deprecated":false,"name":"iOS","unavailable":false,"introducedAt":"2.0","beta":false},{"deprecated":false,"name":"iPadOS","unavailable":false,"introducedAt":"2.0","beta":false},{"deprecated":false,"name":"Mac Catalyst","unavailable":false,"introducedAt":"13.1","beta":false},{"deprecated":false,"name":"tvOS","unavailable":false,"beta":false},{"deprecated":false,"name":"visionOS","unavailable":false,"introducedAt":"1.0","beta":false}]},"sections":[],"variants":[{"paths":["/documentation/uikit/uisearchbar/prompt"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uisearchbar/prompt"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prompt","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:SS"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","level":2,"anchor":"Discussion","type":"heading"},{"inlineContent":[{"text":"The default value is ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}]}],"seeAlsoSections":[{"generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UISearchBar/placeholder","doc://com.apple.uikit/documentation/UIKit/UISearchBar/text","doc://com.apple.uikit/documentation/UIKit/UISearchBar/searchTextField"],"title":"Getting the search text","anchor":"Getting-the-search-text"}],"abstract":[{"type":"text","text":"A single line of text displayed at the top of the search bar."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UISearchBar/prompt","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UISearchBar"]]},"references":{"doc://com.apple.uikit/documentation/UIKit/UISearchBar/placeholder":{"title":"placeholder","url":"/documentation/uikit/uisearchbar/placeholder","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBar/placeholder","type":"topic","navigatorTitle":[{"text":"placeholder","kind":"identifier"}],"abstract":[{"type":"text","text":"The string to display when there’s no other text in the text field."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"placeholder","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]},"doc://com.apple.uikit/documentation/UIKit/UISearchBar/text":{"title":"text","url":"/documentation/uikit/uisearchbar/text","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBar/text","type":"topic","navigatorTitle":[{"kind":"identifier","text":"text"}],"abstract":[{"type":"text","text":"The current or starting search text."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"text","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UISearchBar":{"abstract":[{"text":"A specialized view for receiving search-related information from the user.","type":"text"}],"title":"UISearchBar","url":"/documentation/uikit/uisearchbar","navigatorTitle":[{"text":"UISearchBar","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBar","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UISearchBar","kind":"identifier"}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UISearchBar/searchTextField":{"title":"searchTextField","url":"/documentation/uikit/uisearchbar/searchtextfield","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBar/searchTextField","type":"topic","navigatorTitle":[{"text":"searchTextField","kind":"identifier"}],"abstract":[{"type":"text","text":"The text field that the user enters a search query into."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"searchTextField","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UISearchTextField","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UISearchTextField"}]},"doc://com.apple.uikit/documentation/UIKit/UISearchBar/prompt":{"title":"prompt","url":"/documentation/uikit/uisearchbar/prompt","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBar/prompt","type":"topic","navigatorTitle":[{"kind":"identifier","text":"prompt"}],"abstract":[{"type":"text","text":"A single line of text displayed at the top of the search bar."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prompt","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]},"doc://com.externally.resolved.symbol/c:objc(cs)NSString":{"abstract":[{"type":"text","text":"A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. "}],"title":"NSString","url":"/documentation/foundation/nsstring","kind":"symbol","type":"topic","role":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","fragments":[{"kind":"text","text":"class "},{"text":"NSString","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:SS":{"identifier":"doc://com.externally.resolved.symbol/s:SS","title":"String","url":"/documentation/Swift/String","abstract":[{"type":"text","text":"A Unicode string value that is a collection of characters."}],"fragments":[{"text":"@frozen","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"String"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"unavailable":false,"introducedAt":"2.0","beta":false,"deprecated":false,"name":"iOS"},{"unavailable":false,"introducedAt":"2.0","beta":false,"deprecated":false,"name":"iPadOS"},{"unavailable":false,"introducedAt":"13.1","beta":false,"deprecated":false,"name":"Mac Catalyst"},{"unavailable":false,"beta":false,"deprecated":false,"name":"tvOS"},{"unavailable":false,"introducedAt":"1.0","beta":false,"deprecated":false,"name":"visionOS"}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Property"},{"path":"/metadata/title","op":"replace","value":"prompt"},{"path":"/metadata/symbolKind","op":"replace","value":"property"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"identifier","text":"prompt"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UISearchBar"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"anchor":"Getting-the-search-text","identifiers":["doc://com.apple.uikit/documentation/UIKit/UISearchBar/placeholder","doc://com.apple.uikit/documentation/UIKit/UISearchBar/text","doc://com.apple.uikit/documentation/UIKit/UISearchBar/searchTextField"],"title":"Getting the search text","generated":true}]},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"prompt","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}]}},{"value":"placeholder","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1placeholder/title","op":"replace"},{"value":[{"text":"placeholder","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1placeholder/fragments","op":"replace"},{"value":"text","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1text/title","op":"replace"},{"value":[{"kind":"identifier","text":"text"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1text/fragments","op":"replace"},{"value":"UISearchBar","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar/title","op":"replace"},{"value":[{"text":"UISearchBar","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar/fragments","op":"replace"},{"value":[{"text":"UISearchBar","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar/navigatorTitle","op":"replace"},{"value":"searchTextField","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1searchTextField/title","op":"replace"},{"value":[{"text":"searchTextField","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1searchTextField/fragments","op":"replace"},{"value":"prompt","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1prompt/title","op":"replace"},{"value":[{"kind":"identifier","text":"prompt"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1prompt/fragments","op":"replace"},{"value":[{"type":"text","text":"A static, plain-text Unicode string object."}],"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}