{
  "abstract": [
    {
      "text": "The background image for the scope bar.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UISearchBar"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UISearchBar/scopeBarBackgroundImage"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UISearchBar(py)scopeBarBackgroundImage",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "scopeBarBackgroundImage"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UIImage",
        "text": "UIImage"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "scopeBarBackgroundImage"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "scopeBarBackgroundImage"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "scopeBarBackgroundImage"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIImage",
              "text": "UIImage"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Images that are 1 point wide or stretchable images are stretched, otherwise the image is tiled.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage": {
      "abstract": [
        {
          "text": "An object that manages image data in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIImage"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImage"
        }
      ],
      "role": "symbol",
      "title": "UIImage",
      "type": "topic",
      "url": "/documentation/uikit/uiimage"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchBar": {
      "abstract": [
        {
          "text": "A specialized view for receiving search-related information from the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISearchBar"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchBar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISearchBar"
        }
      ],
      "role": "symbol",
      "title": "UISearchBar",
      "type": "topic",
      "url": "/documentation/uikit/uisearchbar"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchBar/backgroundImage": {
      "abstract": [
        {
          "text": "The background image for the search bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backgroundImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchBar/backgroundImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "backgroundImage"
        }
      ],
      "role": "symbol",
      "title": "backgroundImage",
      "type": "topic",
      "url": "/documentation/uikit/uisearchbar/backgroundimage"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchBar/scopeBarBackgroundImage": {
      "abstract": [
        {
          "text": "The background image for the scope bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scopeBarBackgroundImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchBar/scopeBarBackgroundImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scopeBarBackgroundImage"
        }
      ],
      "role": "symbol",
      "title": "scopeBarBackgroundImage",
      "type": "topic",
      "url": "/documentation/uikit/uisearchbar/scopebarbackgroundimage"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchBar/scopeBarButtonBackgroundImage(for:)": {
      "abstract": [
        {
          "text": "Returns the background image for the scope bar button in a given state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scopeBarButtonBackgroundImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIControl",
          "text": "UIControl"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIControlState",
          "text": "State"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchBar/scopeBarButtonBackgroundImage(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scopeBarButtonBackgroundImageForState:"
        }
      ],
      "role": "symbol",
      "title": "scopeBarButtonBackgroundImage(for:)",
      "type": "topic",
      "url": "/documentation/uikit/uisearchbar/scopebarbuttonbackgroundimage(for:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchBar/scopeBarButtonDividerImage(forLeftSegmentState:rightSegmentState:)": {
      "abstract": [
        {
          "text": "Returns the divider image to use for a given combination of left and right segment states.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scopeBarButtonDividerImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forLeftSegmentState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIControl",
          "text": "UIControl"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIControlState",
          "text": "State"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "rightSegmentState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIControl",
          "text": "UIControl"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIControlState",
          "text": "State"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchBar/scopeBarButtonDividerImage(forLeftSegmentState:rightSegmentState:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scopeBarButtonDividerImageForLeftSegmentState:rightSegmentState:"
        }
      ],
      "role": "symbol",
      "title": "scopeBarButtonDividerImage(forLeftSegmentState:rightSegmentState:)",
      "type": "topic",
      "url": "/documentation/uikit/uisearchbar/scopebarbuttondividerimage(forleftsegmentstate:rightsegmentstate:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchBar/scopeBarButtonTitleTextAttributes(for:)": {
      "abstract": [
        {
          "text": "Returns the text attributes for the search bar’s button’s title string for a given state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scopeBarButtonTitleTextAttributes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIControl",
          "text": "UIControl"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIControlState",
          "text": "State"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAttributedStringKey",
          "text": "Key"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchBar/scopeBarButtonTitleTextAttributes(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scopeBarButtonTitleTextAttributesForState:"
        }
      ],
      "role": "symbol",
      "title": "scopeBarButtonTitleTextAttributes(for:)",
      "type": "topic",
      "url": "/documentation/uikit/uisearchbar/scopebarbuttontitletextattributes(for:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchBar/setScopeBarButtonBackgroundImage(_:for:)": {
      "abstract": [
        {
          "text": "Sets the background image for the scope bar button in a given state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setScopeBarButtonBackgroundImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIControl",
          "text": "UIControl"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIControlState",
          "text": "State"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchBar/setScopeBarButtonBackgroundImage(_:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setScopeBarButtonBackgroundImage:forState:"
        }
      ],
      "role": "symbol",
      "title": "setScopeBarButtonBackgroundImage(_:for:)",
      "type": "topic",
      "url": "/documentation/uikit/uisearchbar/setscopebarbuttonbackgroundimage(_:for:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchBar/setScopeBarButtonDividerImage(_:forLeftSegmentState:rightSegmentState:)": {
      "abstract": [
        {
          "text": "Sets the divider image to use for a given combination of left and right segment states.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setScopeBarButtonDividerImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "forLeftSegmentState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIControl",
          "text": "UIControl"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIControlState",
          "text": "State"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "rightSegmentState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIControl",
          "text": "UIControl"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIControlState",
          "text": "State"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchBar/setScopeBarButtonDividerImage(_:forLeftSegmentState:rightSegmentState:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setScopeBarButtonDividerImage:forLeftSegmentState:rightSegmentState:"
        }
      ],
      "role": "symbol",
      "title": "setScopeBarButtonDividerImage(_:forLeftSegmentState:rightSegmentState:)",
      "type": "topic",
      "url": "/documentation/uikit/uisearchbar/setscopebarbuttondividerimage(_:forleftsegmentstate:rightsegmentstate:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchBar/setScopeBarButtonTitleTextAttributes(_:for:)": {
      "abstract": [
        {
          "text": "Sets the text attributes for the search bar’ button’s title string for a given state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setScopeBarButtonTitleTextAttributes"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAttributedStringKey",
          "text": "Key"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?, "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIControl",
          "text": "UIControl"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIControlState",
          "text": "State"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchBar/setScopeBarButtonTitleTextAttributes(_:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setScopeBarButtonTitleTextAttributes:forState:"
        }
      ],
      "role": "symbol",
      "title": "setScopeBarButtonTitleTextAttributes(_:for:)",
      "type": "topic",
      "url": "/documentation/uikit/uisearchbar/setscopebarbuttontitletextattributes(_:for:)"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UISearchBar/backgroundImage"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Customizing-the-scope-bar-appearance",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UISearchBar/scopeBarButtonBackgroundImage(for:)",
        "doc://com.apple.uikit/documentation/UIKit/UISearchBar/setScopeBarButtonBackgroundImage(_:for:)",
        "doc://com.apple.uikit/documentation/UIKit/UISearchBar/scopeBarButtonDividerImage(forLeftSegmentState:rightSegmentState:)",
        "doc://com.apple.uikit/documentation/UIKit/UISearchBar/setScopeBarButtonDividerImage(_:forLeftSegmentState:rightSegmentState:)",
        "doc://com.apple.uikit/documentation/UIKit/UISearchBar/scopeBarButtonTitleTextAttributes(for:)",
        "doc://com.apple.uikit/documentation/UIKit/UISearchBar/setScopeBarButtonTitleTextAttributes(_:for:)"
      ],
      "title": "Customizing the scope bar appearance"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "scopeBarBackgroundImage"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scopeBarBackgroundImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UISearchBar"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UISearchBar/backgroundImage"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Customizing-the-scope-bar-appearance",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UISearchBar/scopeBarButtonBackgroundImage(for:)",
                "doc://com.apple.uikit/documentation/UIKit/UISearchBar/setScopeBarButtonBackgroundImage(_:for:)",
                "doc://com.apple.uikit/documentation/UIKit/UISearchBar/scopeBarButtonDividerImage(forLeftSegmentState:rightSegmentState:)",
                "doc://com.apple.uikit/documentation/UIKit/UISearchBar/setScopeBarButtonDividerImage(_:forLeftSegmentState:rightSegmentState:)",
                "doc://com.apple.uikit/documentation/UIKit/UISearchBar/scopeBarButtonTitleTextAttributes(for:)",
                "doc://com.apple.uikit/documentation/UIKit/UISearchBar/setScopeBarButtonTitleTextAttributes(_:for:)"
              ],
              "title": "Customizing the scope bar appearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)UIImage",
                    "text": "UIImage"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "scopeBarBackgroundImage"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1setScopeBarButtonDividerImage(_:forLeftSegmentState:rightSegmentState:)/title",
          "value": "setScopeBarButtonDividerImage:forLeftSegmentState:rightSegmentState:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1setScopeBarButtonDividerImage(_:forLeftSegmentState:rightSegmentState:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setScopeBarButtonDividerImage:forLeftSegmentState:rightSegmentState:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/title",
          "value": "UIImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1scopeBarBackgroundImage/title",
          "value": "scopeBarBackgroundImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1scopeBarBackgroundImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scopeBarBackgroundImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1setScopeBarButtonTitleTextAttributes(_:for:)/title",
          "value": "setScopeBarButtonTitleTextAttributes:forState:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1setScopeBarButtonTitleTextAttributes(_:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setScopeBarButtonTitleTextAttributes:forState:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1setScopeBarButtonBackgroundImage(_:for:)/title",
          "value": "setScopeBarButtonBackgroundImage:forState:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1setScopeBarButtonBackgroundImage(_:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setScopeBarButtonBackgroundImage:forState:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1scopeBarButtonDividerImage(forLeftSegmentState:rightSegmentState:)/title",
          "value": "scopeBarButtonDividerImageForLeftSegmentState:rightSegmentState:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1scopeBarButtonDividerImage(forLeftSegmentState:rightSegmentState:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "scopeBarButtonDividerImageForLeftSegmentState:rightSegmentState:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1scopeBarButtonTitleTextAttributes(for:)/title",
          "value": "scopeBarButtonTitleTextAttributesForState:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1scopeBarButtonTitleTextAttributes(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "scopeBarButtonTitleTextAttributesForState:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1scopeBarButtonBackgroundImage(for:)/title",
          "value": "scopeBarButtonBackgroundImageForState:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1scopeBarButtonBackgroundImage(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "scopeBarButtonBackgroundImageForState:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar/title",
          "value": "UISearchBar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchBar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchBar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1backgroundImage/title",
          "value": "backgroundImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1backgroundImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "backgroundImage"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uisearchbar/scopebarbackgroundimage"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uisearchbar/scopebarbackgroundimage"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
