{
  "abstract": [
    {
      "text": "Returns the search text field image for a given state.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UISearchBar"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UISearchBar/searchFieldBackgroundImage(for:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UISearchBar(im)searchFieldBackgroundImageForState:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "searchFieldBackgroundImage"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "for"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UIControl",
        "text": "UIControl"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@UIControlState",
        "text": "State"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UIImage",
        "text": "UIImage"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "searchFieldBackgroundImageForState:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "searchFieldBackgroundImage(for:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "searchFieldBackgroundImage"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "for"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "state"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIControl",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIControl",
              "text": "UIControl"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@UIControlState",
              "text": "State"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIImage",
              "text": "UIImage"
            },
            {
              "kind": "text",
              "text": "?"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A control state.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "Valid states are ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/normal",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " and ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/disabled",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "state"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The search text field image to use for ",
              "type": "text"
            },
            {
              "code": "state",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIControl": {
      "abstract": [
        {
          "text": "The base class for controls, which are visual elements that convey a specific action or intention in response to user interactions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIControl"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIControl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIControl"
        }
      ],
      "role": "symbol",
      "title": "UIControl",
      "type": "topic",
      "url": "/documentation/uikit/uicontrol"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct": {
      "abstract": [
        {
          "text": "Constants describing the state of a control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "State"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "State"
        }
      ],
      "role": "symbol",
      "title": "UIControl.State",
      "type": "topic",
      "url": "/documentation/uikit/uicontrol/state-swift.struct"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/disabled": {
      "abstract": [
        {
          "text": "The disabled state of a control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIControl",
          "text": "UIControl"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIControlState",
          "text": "State"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/disabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIControlStateDisabled"
        }
      ],
      "role": "symbol",
      "title": "disabled",
      "type": "topic",
      "url": "/documentation/uikit/uicontrol/state-swift.struct/disabled"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/normal": {
      "abstract": [
        {
          "text": "The normal, or default, state of a control where the control is enabled but neither selected nor highlighted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "normal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIControl",
          "text": "UIControl"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIControlState",
          "text": "State"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/normal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIControlStateNormal"
        }
      ],
      "role": "symbol",
      "title": "normal",
      "type": "topic",
      "url": "/documentation/uikit/uicontrol/state-swift.struct/normal"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage": {
      "abstract": [
        {
          "text": "An object that manages image data in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIImage"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImage"
        }
      ],
      "role": "symbol",
      "title": "UIImage",
      "type": "topic",
      "url": "/documentation/uikit/uiimage"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchBar": {
      "abstract": [
        {
          "text": "A specialized view for receiving search-related information from the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISearchBar"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchBar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISearchBar"
        }
      ],
      "role": "symbol",
      "title": "UISearchBar",
      "type": "topic",
      "url": "/documentation/uikit/uisearchbar"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchBar/backgroundImage": {
      "abstract": [
        {
          "text": "The background image for the search bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backgroundImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchBar/backgroundImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "backgroundImage"
        }
      ],
      "role": "symbol",
      "title": "backgroundImage",
      "type": "topic",
      "url": "/documentation/uikit/uisearchbar/backgroundimage"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchBar/backgroundImage(for:barMetrics:)": {
      "abstract": [
        {
          "text": "Returns the image used for the background in a given position and with given metrics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backgroundImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIBarPosition",
          "text": "UIBarPosition"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "barMetrics"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIBarMetrics",
          "text": "UIBarMetrics"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchBar/backgroundImage(for:barMetrics:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "backgroundImageForBarPosition:barMetrics:"
        }
      ],
      "role": "symbol",
      "title": "backgroundImage(for:barMetrics:)",
      "type": "topic",
      "url": "/documentation/uikit/uisearchbar/backgroundimage(for:barmetrics:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchBar/image(for:state:)": {
      "abstract": [
        {
          "text": "Returns the image for a given search bar icon type and control state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "image"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISearchBar",
          "text": "UISearchBar"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UISearchBarIcon",
          "text": "Icon"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "state"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIControl",
          "text": "UIControl"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIControlState",
          "text": "State"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchBar/image(for:state:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageForSearchBarIcon:state:"
        }
      ],
      "role": "symbol",
      "title": "image(for:state:)",
      "type": "topic",
      "url": "/documentation/uikit/uisearchbar/image(for:state:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchBar/inputAccessoryView": {
      "abstract": [
        {
          "text": "A custom input accessory view for the keyboard of the search bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inputAccessoryView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchBar/inputAccessoryView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inputAccessoryView"
        }
      ],
      "role": "symbol",
      "title": "inputAccessoryView",
      "type": "topic",
      "url": "/documentation/uikit/uisearchbar/inputaccessoryview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchBar/positionAdjustment(for:)": {
      "abstract": [
        {
          "text": "Returns the position adjustment for a given icon.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "positionAdjustment"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISearchBar",
          "text": "UISearchBar"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UISearchBarIcon",
          "text": "Icon"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@UIOffset",
          "text": "UIOffset"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchBar/positionAdjustment(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "positionAdjustmentForSearchBarIcon:"
        }
      ],
      "role": "symbol",
      "title": "positionAdjustment(for:)",
      "type": "topic",
      "url": "/documentation/uikit/uisearchbar/positionadjustment(for:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchBar/searchFieldBackgroundImage(for:)": {
      "abstract": [
        {
          "text": "Returns the search text field image for a given state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "searchFieldBackgroundImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIControl",
          "text": "UIControl"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIControlState",
          "text": "State"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchBar/searchFieldBackgroundImage(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "searchFieldBackgroundImageForState:"
        }
      ],
      "role": "symbol",
      "title": "searchFieldBackgroundImage(for:)",
      "type": "topic",
      "url": "/documentation/uikit/uisearchbar/searchfieldbackgroundimage(for:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchBar/searchFieldBackgroundPositionAdjustment": {
      "abstract": [
        {
          "text": "The offset of the search text field background in the search bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "searchFieldBackgroundPositionAdjustment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@UIOffset",
          "text": "UIOffset"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchBar/searchFieldBackgroundPositionAdjustment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "searchFieldBackgroundPositionAdjustment"
        }
      ],
      "role": "symbol",
      "title": "searchFieldBackgroundPositionAdjustment",
      "type": "topic",
      "url": "/documentation/uikit/uisearchbar/searchfieldbackgroundpositionadjustment"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchBar/searchTextPositionAdjustment": {
      "abstract": [
        {
          "text": "The offset of the text within the search text field background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "searchTextPositionAdjustment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@UIOffset",
          "text": "UIOffset"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchBar/searchTextPositionAdjustment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "searchTextPositionAdjustment"
        }
      ],
      "role": "symbol",
      "title": "searchTextPositionAdjustment",
      "type": "topic",
      "url": "/documentation/uikit/uisearchbar/searchtextpositionadjustment"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchBar/setBackgroundImage(_:for:barMetrics:)": {
      "abstract": [
        {
          "text": "Sets the image to use for the background in a given position and with given metrics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setBackgroundImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIBarPosition",
          "text": "UIBarPosition"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "barMetrics"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIBarMetrics",
          "text": "UIBarMetrics"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchBar/setBackgroundImage(_:for:barMetrics:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setBackgroundImage:forBarPosition:barMetrics:"
        }
      ],
      "role": "symbol",
      "title": "setBackgroundImage(_:for:barMetrics:)",
      "type": "topic",
      "url": "/documentation/uikit/uisearchbar/setbackgroundimage(_:for:barmetrics:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchBar/setImage(_:for:state:)": {
      "abstract": [
        {
          "text": "Sets the image for a given search bar icon type and control state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISearchBar",
          "text": "UISearchBar"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UISearchBarIcon",
          "text": "Icon"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "state"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIControl",
          "text": "UIControl"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIControlState",
          "text": "State"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchBar/setImage(_:for:state:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setImage:forSearchBarIcon:state:"
        }
      ],
      "role": "symbol",
      "title": "setImage(_:for:state:)",
      "type": "topic",
      "url": "/documentation/uikit/uisearchbar/setimage(_:for:state:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchBar/setPositionAdjustment(_:for:)": {
      "abstract": [
        {
          "text": "Returns the position adjustment for a given icon.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setPositionAdjustment"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@UIOffset",
          "text": "UIOffset"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISearchBar",
          "text": "UISearchBar"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UISearchBarIcon",
          "text": "Icon"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchBar/setPositionAdjustment(_:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setPositionAdjustment:forSearchBarIcon:"
        }
      ],
      "role": "symbol",
      "title": "setPositionAdjustment(_:for:)",
      "type": "topic",
      "url": "/documentation/uikit/uisearchbar/setpositionadjustment(_:for:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchBar/setSearchFieldBackgroundImage(_:for:)": {
      "abstract": [
        {
          "text": "Sets the search text field image for a given state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setSearchFieldBackgroundImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIControl",
          "text": "UIControl"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIControlState",
          "text": "State"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchBar/setSearchFieldBackgroundImage(_:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setSearchFieldBackgroundImage:forState:"
        }
      ],
      "role": "symbol",
      "title": "setSearchFieldBackgroundImage(_:for:)",
      "type": "topic",
      "url": "/documentation/uikit/uisearchbar/setsearchfieldbackgroundimage(_:for:)"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Customizing-the-search-bar-appearance",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UISearchBar/backgroundImage",
        "doc://com.apple.uikit/documentation/UIKit/UISearchBar/backgroundImage(for:barMetrics:)",
        "doc://com.apple.uikit/documentation/UIKit/UISearchBar/setBackgroundImage(_:for:barMetrics:)",
        "doc://com.apple.uikit/documentation/UIKit/UISearchBar/image(for:state:)",
        "doc://com.apple.uikit/documentation/UIKit/UISearchBar/setImage(_:for:state:)",
        "doc://com.apple.uikit/documentation/UIKit/UISearchBar/positionAdjustment(for:)",
        "doc://com.apple.uikit/documentation/UIKit/UISearchBar/setPositionAdjustment(_:for:)",
        "doc://com.apple.uikit/documentation/UIKit/UISearchBar/inputAccessoryView",
        "doc://com.apple.uikit/documentation/UIKit/UISearchBar/setSearchFieldBackgroundImage(_:for:)",
        "doc://com.apple.uikit/documentation/UIKit/UISearchBar/searchFieldBackgroundPositionAdjustment",
        "doc://com.apple.uikit/documentation/UIKit/UISearchBar/searchTextPositionAdjustment"
      ],
      "title": "Customizing the search bar appearance"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "searchFieldBackgroundImageForState:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "searchFieldBackgroundImageForState:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UISearchBar"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Customizing-the-search-bar-appearance",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UISearchBar/backgroundImage",
                "doc://com.apple.uikit/documentation/UIKit/UISearchBar/backgroundImage(for:barMetrics:)",
                "doc://com.apple.uikit/documentation/UIKit/UISearchBar/setBackgroundImage(_:for:barMetrics:)",
                "doc://com.apple.uikit/documentation/UIKit/UISearchBar/image(for:state:)",
                "doc://com.apple.uikit/documentation/UIKit/UISearchBar/setImage(_:for:state:)",
                "doc://com.apple.uikit/documentation/UIKit/UISearchBar/positionAdjustment(for:)",
                "doc://com.apple.uikit/documentation/UIKit/UISearchBar/setPositionAdjustment(_:for:)",
                "doc://com.apple.uikit/documentation/UIKit/UISearchBar/inputAccessoryView",
                "doc://com.apple.uikit/documentation/UIKit/UISearchBar/setSearchFieldBackgroundImage(_:for:)",
                "doc://com.apple.uikit/documentation/UIKit/UISearchBar/searchFieldBackgroundPositionAdjustment",
                "doc://com.apple.uikit/documentation/UIKit/UISearchBar/searchTextPositionAdjustment"
              ],
              "title": "Customizing the search bar appearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)UIImage",
                    "text": "UIImage"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "identifier",
                    "text": "searchFieldBackgroundImageForState:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@UIControlState",
                    "text": "UIControlState"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "state"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A control state.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "inlineContent": [
                      {
                        "text": "Valid states are ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/normal",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " and ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct/disabled",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "state"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "The search text field image to use for ",
                    "type": "text"
                  },
                  {
                    "code": "state",
                    "type": "codeVoice"
                  },
                  {
                    "text": ".",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1backgroundImage/title",
          "value": "backgroundImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1backgroundImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "backgroundImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1setPositionAdjustment(_:for:)/title",
          "value": "setPositionAdjustment:forSearchBarIcon:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1setPositionAdjustment(_:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setPositionAdjustment:forSearchBarIcon:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1positionAdjustment(for:)/title",
          "value": "positionAdjustmentForSearchBarIcon:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1positionAdjustment(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "positionAdjustmentForSearchBarIcon:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/title",
          "value": "UIImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1searchFieldBackgroundImage(for:)/title",
          "value": "searchFieldBackgroundImageForState:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1searchFieldBackgroundImage(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "searchFieldBackgroundImageForState:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1image(for:state:)/title",
          "value": "imageForSearchBarIcon:state:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1image(for:state:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "imageForSearchBarIcon:state:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1searchTextPositionAdjustment/title",
          "value": "searchTextPositionAdjustment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1searchTextPositionAdjustment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "searchTextPositionAdjustment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl/title",
          "value": "UIControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1setImage(_:for:state:)/title",
          "value": "setImage:forSearchBarIcon:state:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1setImage(_:for:state:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setImage:forSearchBarIcon:state:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1searchFieldBackgroundPositionAdjustment/title",
          "value": "searchFieldBackgroundPositionAdjustment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1searchFieldBackgroundPositionAdjustment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "searchFieldBackgroundPositionAdjustment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1setBackgroundImage(_:for:barMetrics:)/title",
          "value": "setBackgroundImage:forBarPosition:barMetrics:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1setBackgroundImage(_:for:barMetrics:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setBackgroundImage:forBarPosition:barMetrics:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1setSearchFieldBackgroundImage(_:for:)/title",
          "value": "setSearchFieldBackgroundImage:forState:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1setSearchFieldBackgroundImage(_:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setSearchFieldBackgroundImage:forState:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1inputAccessoryView/title",
          "value": "inputAccessoryView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1inputAccessoryView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inputAccessoryView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct~1normal/title",
          "value": "UIControlStateNormal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct~1normal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIControlStateNormal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct~1disabled/title",
          "value": "UIControlStateDisabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct~1disabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIControlStateDisabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1backgroundImage(for:barMetrics:)/title",
          "value": "backgroundImageForBarPosition:barMetrics:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1backgroundImage(for:barMetrics:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "backgroundImageForBarPosition:barMetrics:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar/title",
          "value": "UISearchBar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchBar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchBar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct/title",
          "value": "UIControlState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIControlState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIControlState"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uisearchbar/searchfieldbackgroundimage(for:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uisearchbar/searchfieldbackgroundimage(for:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
