{"abstract":[{"text":"Sets the display state of the cancel button optionally with animation.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uisearchbar/setshowscancelbutton(_:animated:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uisearchbar/setshowscancelbutton(_:animated:)"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UISearchBar"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setShowsCancelButton","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"showsCancelButton","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:Sb","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"animated","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:Sb","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.documentation/documentation/swift/true"},{"text":" to display the cancel button, otherwise ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.documentation/documentation/swift/false"},{"text":".","type":"text"}]}],"name":"showsCancelButton"},{"content":[{"inlineContent":[{"text":"","type":"text"},{"identifier":"doc://com.apple.documentation/documentation/swift/true","isActive":true,"type":"reference"},{"text":" to use animation to change the display state of the cancel button, otherwise ","type":"text"},{"identifier":"doc://com.apple.documentation/documentation/swift/false","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}],"name":"animated"}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"Discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"Cancel buttons are not displayed for apps running on iPad, even when you specify ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.documentation/documentation/swift/true","type":"reference"},{"text":" for the ","type":"text"},{"code":"showsCancelButton","type":"codeVoice"},{"text":" parameter","type":"text"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UISearchBar/setShowsCancelButton(_:animated:)"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setShowsCancelButton","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"animated","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:objc(cs)UISearchBar(im)setShowsCancelButton:animated:","platforms":[{"introducedAt":"3.0","beta":false,"unavailable":false,"name":"iOS","deprecated":false},{"unavailable":false,"introducedAt":"3.0","name":"iPadOS","beta":false,"deprecated":false},{"unavailable":false,"introducedAt":"13.1","name":"Mac Catalyst","beta":false,"deprecated":false},{"unavailable":false,"introducedAt":"1.0","name":"visionOS","beta":false,"deprecated":false}],"title":"setShowsCancelButton(_:animated:)","modules":[{"name":"UIKit"}],"role":"symbol","navigatorTitle":[{"text":"setShowsCancelButton:animated:","kind":"identifier"}]},"sections":[],"seeAlsoSections":[{"anchor":"Configuring-the-search-interface","identifiers":["doc://com.apple.uikit/documentation/UIKit/UISearchBar/showsBookmarkButton","doc://com.apple.uikit/documentation/UIKit/UISearchBar/showsCancelButton","doc://com.apple.uikit/documentation/UIKit/UISearchBar/showsSearchResultsButton","doc://com.apple.uikit/documentation/UIKit/UISearchBar/isSearchResultsButtonSelected"],"generated":true,"title":"Configuring the search interface"}],"references":{"doc://com.externally.resolved.symbol/c:@T@BOOL":{"abstract":[{"text":"Type to represent a Boolean value.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","role":"symbol","url":"/documentation/objectivec/bool","kind":"symbol","type":"topic","title":"BOOL"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.documentation/documentation/swift/false":{"role":"symbol","url":"/documentation/swift/false","title":"false","identifier":"doc://com.apple.documentation/documentation/swift/false","abstract":[{"text":"A false value.","type":"text"}],"kind":"symbol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UISearchBar":{"abstract":[{"text":"A specialized view for receiving search-related information from the user.","type":"text"}],"title":"UISearchBar","url":"/documentation/uikit/uisearchbar","navigatorTitle":[{"text":"UISearchBar","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBar","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UISearchBar","kind":"identifier"}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UISearchBar/showsCancelButton":{"url":"/documentation/uikit/uisearchbar/showscancelbutton","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showsCancelButton","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBar/showsCancelButton","role":"symbol","navigatorTitle":[{"text":"showsCancelButton","kind":"identifier"}],"abstract":[{"type":"text","text":"A Boolean value indicating whether the cancel button is displayed."}],"title":"showsCancelButton","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UISearchBar/setShowsCancelButton(_:animated:)":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBar/setShowsCancelButton(_:animated:)","title":"setShowsCancelButton(_:animated:)","type":"topic","url":"/documentation/uikit/uisearchbar/setshowscancelbutton(_:animated:)","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"setShowsCancelButton:animated:"}],"abstract":[{"text":"Sets the display state of the cancel button optionally with animation.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setShowsCancelButton"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"animated","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}]},"doc://com.externally.resolved.symbol/s:Sb":{"role":"symbol","abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"type":"topic","url":"/documentation/Swift/Bool","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:Sb","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Bool"}],"title":"Bool"},"doc://com.apple.uikit/documentation/UIKit/UISearchBar/isSearchResultsButtonSelected":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSearchResultsButtonSelected"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBar/isSearchResultsButtonSelected","role":"symbol","abstract":[{"text":"A Boolean value indicating whether the search results button is selected.","type":"text"}],"kind":"symbol","title":"isSearchResultsButtonSelected","url":"/documentation/uikit/uisearchbar/issearchresultsbuttonselected","navigatorTitle":[{"text":"searchResultsButtonSelected","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UISearchBar/showsSearchResultsButton":{"url":"/documentation/uikit/uisearchbar/showssearchresultsbutton","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showsSearchResultsButton","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBar/showsSearchResultsButton","role":"symbol","navigatorTitle":[{"text":"showsSearchResultsButton","kind":"identifier"}],"abstract":[{"type":"text","text":"A Boolean value indicating whether the search results button is displayed."}],"title":"showsSearchResultsButton","type":"topic"},"doc://com.apple.documentation/documentation/swift/true":{"abstract":[{"text":"A true value.","type":"text"}],"role":"symbol","url":"/documentation/swift/true","identifier":"doc://com.apple.documentation/documentation/swift/true","type":"topic","title":"true","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UISearchBar/showsBookmarkButton":{"url":"/documentation/uikit/uisearchbar/showsbookmarkbutton","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showsBookmarkButton"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBar/showsBookmarkButton","role":"symbol","navigatorTitle":[{"text":"showsBookmarkButton","kind":"identifier"}],"abstract":[{"type":"text","text":"A Boolean value indicating whether the bookmark button is displayed."}],"title":"showsBookmarkButton","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"deprecated":false,"unavailable":false,"name":"iOS","introducedAt":"3.0","beta":false},{"name":"iPadOS","deprecated":false,"introducedAt":"3.0","unavailable":false,"beta":false},{"name":"Mac Catalyst","deprecated":false,"introducedAt":"13.1","unavailable":false,"beta":false},{"name":"visionOS","deprecated":false,"introducedAt":"1.0","unavailable":false,"beta":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Method","path":"/metadata/roleHeading"},{"op":"replace","value":"setShowsCancelButton:animated:","path":"/metadata/title"},{"op":"replace","value":"method","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setShowsCancelButton:animated:"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UISearchBar"]]},"path":"/hierarchy"},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UISearchBar/showsBookmarkButton","doc://com.apple.uikit/documentation/UIKit/UISearchBar/showsCancelButton","doc://com.apple.uikit/documentation/UIKit/UISearchBar/showsSearchResultsButton","doc://com.apple.uikit/documentation/UIKit/UISearchBar/isSearchResultsButtonSelected"],"generated":true,"title":"Configuring the search interface","anchor":"Configuring-the-search-interface"}]},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"setShowsCancelButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"showsCancelButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"animated:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"animated","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"/primaryContentSections/1","value":{"parameters":[{"name":"showsCancelButton","content":[{"inlineContent":[{"text":"","type":"text"},{"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/true","isActive":true},{"text":" to display the cancel button, otherwise ","type":"text"},{"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/false","isActive":true},{"text":".","type":"text"}],"type":"paragraph"}]},{"name":"animated","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","isActive":true,"identifier":"doc://com.apple.documentation/documentation/swift/true"},{"type":"text","text":" to use animation to change the display state of the cancel button, otherwise "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.documentation/documentation/swift/false"},{"type":"text","text":"."}]}]}],"kind":"parameters"}},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar/title","value":"UISearchBar"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar/fragments","value":[{"kind":"identifier","text":"UISearchBar"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar/navigatorTitle","value":[{"kind":"identifier","text":"UISearchBar"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1showsCancelButton/title","value":"showsCancelButton"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1showsCancelButton/fragments","value":[{"kind":"identifier","text":"showsCancelButton"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1setShowsCancelButton(_:animated:)/title","value":"setShowsCancelButton:animated:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1setShowsCancelButton(_:animated:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setShowsCancelButton:animated:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1isSearchResultsButtonSelected/title","value":"searchResultsButtonSelected"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1isSearchResultsButtonSelected/fragments","value":[{"kind":"identifier","text":"searchResultsButtonSelected"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1showsSearchResultsButton/title","op":"replace","value":"showsSearchResultsButton"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1showsSearchResultsButton/fragments","op":"replace","value":[{"text":"showsSearchResultsButton","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1showsBookmarkButton/title","op":"replace","value":"showsBookmarkButton"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1showsBookmarkButton/fragments","value":[{"text":"showsBookmarkButton","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}