{"seeAlsoSections":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UISearchBar/showsBookmarkButton","doc://com.apple.uikit/documentation/UIKit/UISearchBar/setShowsCancelButton(_:animated:)","doc://com.apple.uikit/documentation/UIKit/UISearchBar/showsSearchResultsButton","doc://com.apple.uikit/documentation/UIKit/UISearchBar/isSearchResultsButtonSelected"],"title":"Configuring the search interface","anchor":"Configuring-the-search-interface","generated":true}],"sections":[],"variants":[{"paths":["/documentation/uikit/uisearchbar/showscancelbutton"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uisearchbar/showscancelbutton"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UISearchBar/showsCancelButton","interfaceLanguage":"swift"},"metadata":{"role":"symbol","title":"showsCancelButton","platforms":[{"introducedAt":"2.0","unavailable":false,"deprecated":false,"beta":false,"name":"iOS"},{"introducedAt":"2.0","unavailable":false,"deprecated":false,"beta":false,"name":"iPadOS"},{"introducedAt":"13.1","unavailable":false,"deprecated":false,"beta":false,"name":"Mac Catalyst"},{"introducedAt":"1.0","unavailable":false,"deprecated":false,"beta":false,"name":"visionOS"}],"modules":[{"name":"UIKit"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"showsCancelButton"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showsCancelButton","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"externalID":"c:objc(cs)UISearchBar(py)showsCancelButton"},"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UISearchBar"]]},"abstract":[{"text":"A Boolean value indicating whether the cancel button is displayed.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showsCancelButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:Sb","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}],"kind":"declarations"},{"content":[{"level":2,"anchor":"Discussion","text":"Discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"When the value of this property is "},{"isActive":true,"identifier":"doc://com.apple.documentation/documentation/swift/true","type":"reference"},{"type":"text","text":", the cancel button is displayed if the app is running on iPhone. The value of this property is ignored, and no cancel button is displayed, for apps running on iPad. The default value is "},{"isActive":true,"identifier":"doc://com.apple.documentation/documentation/swift/false","type":"reference"},{"type":"text","text":"."}]}],"kind":"content"}],"references":{"doc://com.apple.uikit/documentation/UIKit/UISearchBar":{"abstract":[{"text":"A specialized view for receiving search-related information from the user.","type":"text"}],"title":"UISearchBar","url":"/documentation/uikit/uisearchbar","navigatorTitle":[{"text":"UISearchBar","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBar","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UISearchBar","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UISearchBar/setShowsCancelButton(_:animated:)":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBar/setShowsCancelButton(_:animated:)","title":"setShowsCancelButton(_:animated:)","type":"topic","url":"/documentation/uikit/uisearchbar/setshowscancelbutton(_:animated:)","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"setShowsCancelButton:animated:"}],"abstract":[{"text":"Sets the display state of the cancel button optionally with animation.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setShowsCancelButton"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"animated","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UISearchBar/showsBookmarkButton":{"url":"/documentation/uikit/uisearchbar/showsbookmarkbutton","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showsBookmarkButton"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBar/showsBookmarkButton","role":"symbol","navigatorTitle":[{"text":"showsBookmarkButton","kind":"identifier"}],"abstract":[{"type":"text","text":"A Boolean value indicating whether the bookmark button is displayed."}],"title":"showsBookmarkButton","type":"topic"},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"abstract":[{"text":"Type to represent a Boolean value.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","role":"symbol","url":"/documentation/objectivec/bool","kind":"symbol","type":"topic","title":"BOOL"},"doc://com.apple.uikit/documentation/UIKit/UISearchBar/isSearchResultsButtonSelected":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSearchResultsButtonSelected"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBar/isSearchResultsButtonSelected","role":"symbol","abstract":[{"text":"A Boolean value indicating whether the search results button is selected.","type":"text"}],"kind":"symbol","title":"isSearchResultsButtonSelected","url":"/documentation/uikit/uisearchbar/issearchresultsbuttonselected","navigatorTitle":[{"text":"searchResultsButtonSelected","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:Sb":{"role":"symbol","abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"type":"topic","url":"/documentation/Swift/Bool","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:Sb","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Bool"}],"title":"Bool"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.documentation/documentation/swift/false":{"role":"symbol","url":"/documentation/swift/false","title":"false","identifier":"doc://com.apple.documentation/documentation/swift/false","abstract":[{"text":"A false value.","type":"text"}],"kind":"symbol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.documentation/documentation/swift/true":{"abstract":[{"text":"A true value.","type":"text"}],"role":"symbol","url":"/documentation/swift/true","identifier":"doc://com.apple.documentation/documentation/swift/true","type":"topic","title":"true","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UISearchBar/showsCancelButton":{"url":"/documentation/uikit/uisearchbar/showscancelbutton","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showsCancelButton","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBar/showsCancelButton","role":"symbol","navigatorTitle":[{"text":"showsCancelButton","kind":"identifier"}],"abstract":[{"type":"text","text":"A Boolean value indicating whether the cancel button is displayed."}],"title":"showsCancelButton","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UISearchBar/showsSearchResultsButton":{"url":"/documentation/uikit/uisearchbar/showssearchresultsbutton","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showsSearchResultsButton","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBar/showsSearchResultsButton","role":"symbol","navigatorTitle":[{"text":"showsSearchResultsButton","kind":"identifier"}],"abstract":[{"type":"text","text":"A Boolean value indicating whether the search results button is displayed."}],"title":"showsSearchResultsButton","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"introducedAt":"2.0","unavailable":false,"beta":false,"deprecated":false,"name":"iOS"},{"introducedAt":"2.0","unavailable":false,"beta":false,"deprecated":false,"name":"iPadOS"},{"introducedAt":"13.1","unavailable":false,"beta":false,"deprecated":false,"name":"Mac Catalyst"},{"introducedAt":"1.0","unavailable":false,"beta":false,"deprecated":false,"name":"visionOS"}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Property"},{"op":"replace","path":"/metadata/title","value":"showsCancelButton"},{"op":"replace","path":"/metadata/symbolKind","value":"property"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"identifier","text":"showsCancelButton"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UISearchBar"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"generated":true,"title":"Configuring the search interface","identifiers":["doc://com.apple.uikit/documentation/UIKit/UISearchBar/showsBookmarkButton","doc://com.apple.uikit/documentation/UIKit/UISearchBar/setShowsCancelButton(_:animated:)","doc://com.apple.uikit/documentation/UIKit/UISearchBar/showsSearchResultsButton","doc://com.apple.uikit/documentation/UIKit/UISearchBar/isSearchResultsButtonSelected"],"anchor":"Configuring-the-search-interface"}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"showsCancelButton"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar/title","op":"replace","value":"UISearchBar"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar/fragments","op":"replace","value":[{"kind":"identifier","text":"UISearchBar"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar/navigatorTitle","op":"replace","value":[{"text":"UISearchBar","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1setShowsCancelButton(_:animated:)/title","op":"replace","value":"setShowsCancelButton:animated:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1setShowsCancelButton(_:animated:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setShowsCancelButton:animated:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1showsBookmarkButton/title","op":"replace","value":"showsBookmarkButton"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1showsBookmarkButton/fragments","op":"replace","value":[{"kind":"identifier","text":"showsBookmarkButton"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1isSearchResultsButtonSelected/title","op":"replace","value":"searchResultsButtonSelected"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1isSearchResultsButtonSelected/fragments","op":"replace","value":[{"text":"searchResultsButtonSelected","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1showsCancelButton/title","op":"replace","value":"showsCancelButton"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1showsCancelButton/fragments","op":"replace","value":[{"text":"showsCancelButton","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1showsSearchResultsButton/title","op":"replace","value":"showsSearchResultsButton"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1showsSearchResultsButton/fragments","op":"replace","value":[{"text":"showsSearchResultsButton","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}