{"seeAlsoSections":[{"anchor":"Configuring-the-search-interface","title":"Configuring the search interface","identifiers":["doc://com.apple.uikit/documentation/UIKit/UISearchBar/showsCancelButton","doc://com.apple.uikit/documentation/UIKit/UISearchBar/setShowsCancelButton(_:animated:)","doc://com.apple.uikit/documentation/UIKit/UISearchBar/showsSearchResultsButton","doc://com.apple.uikit/documentation/UIKit/UISearchBar/isSearchResultsButtonSelected"],"generated":true}],"variants":[{"paths":["/documentation/uikit/uisearchbar/showsbookmarkbutton"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uisearchbar/showsbookmarkbutton"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"],"tokens":[{"text":"@","kind":"attribute"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showsBookmarkButton","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:Sb","preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Discussion","anchor":"Discussion","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"The default value is ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/false"},{"text":".","type":"text"}]}]}],"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UISearchBar/showsBookmarkButton","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"showsBookmarkButton"}],"symbolKind":"property","role":"symbol","roleHeading":"Instance Property","platforms":[{"deprecated":false,"introducedAt":"2.0","name":"iOS","unavailable":false,"beta":false},{"deprecated":false,"introducedAt":"2.0","name":"iPadOS","unavailable":false,"beta":false},{"deprecated":false,"introducedAt":"13.1","name":"Mac Catalyst","unavailable":false,"beta":false},{"name":"visionOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"1.0"}],"title":"showsBookmarkButton","modules":[{"name":"UIKit"}],"externalID":"c:objc(cs)UISearchBar(py)showsBookmarkButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showsBookmarkButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UISearchBar"]]},"abstract":[{"text":"A Boolean value indicating whether the bookmark button is displayed.","type":"text"}],"references":{"doc://com.apple.uikit/documentation/UIKit/UISearchBar/showsSearchResultsButton":{"url":"/documentation/uikit/uisearchbar/showssearchresultsbutton","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showsSearchResultsButton","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBar/showsSearchResultsButton","role":"symbol","navigatorTitle":[{"text":"showsSearchResultsButton","kind":"identifier"}],"abstract":[{"type":"text","text":"A Boolean value indicating whether the search results button is displayed."}],"title":"showsSearchResultsButton","type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UISearchBar/showsCancelButton":{"url":"/documentation/uikit/uisearchbar/showscancelbutton","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showsCancelButton","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBar/showsCancelButton","role":"symbol","navigatorTitle":[{"text":"showsCancelButton","kind":"identifier"}],"abstract":[{"type":"text","text":"A Boolean value indicating whether the cancel button is displayed."}],"title":"showsCancelButton","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UISearchBar/setShowsCancelButton(_:animated:)":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBar/setShowsCancelButton(_:animated:)","title":"setShowsCancelButton(_:animated:)","type":"topic","url":"/documentation/uikit/uisearchbar/setshowscancelbutton(_:animated:)","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"setShowsCancelButton:animated:"}],"abstract":[{"text":"Sets the display state of the cancel button optionally with animation.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setShowsCancelButton"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"animated","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}]},"doc://com.apple.uikit/documentation/UIKit/UISearchBar/showsBookmarkButton":{"url":"/documentation/uikit/uisearchbar/showsbookmarkbutton","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showsBookmarkButton"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBar/showsBookmarkButton","role":"symbol","navigatorTitle":[{"text":"showsBookmarkButton","kind":"identifier"}],"abstract":[{"type":"text","text":"A Boolean value indicating whether the bookmark button is displayed."}],"title":"showsBookmarkButton","type":"topic"},"doc://com.externally.resolved.symbol/s:Sb":{"role":"symbol","abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"type":"topic","url":"/documentation/Swift/Bool","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:Sb","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Bool"}],"title":"Bool"},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"abstract":[{"text":"Type to represent a Boolean value.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","role":"symbol","url":"/documentation/objectivec/bool","kind":"symbol","type":"topic","title":"BOOL"},"doc://com.apple.uikit/documentation/UIKit/UISearchBar":{"abstract":[{"text":"A specialized view for receiving search-related information from the user.","type":"text"}],"title":"UISearchBar","url":"/documentation/uikit/uisearchbar","navigatorTitle":[{"text":"UISearchBar","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBar","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UISearchBar","kind":"identifier"}]},"doc://com.apple.documentation/documentation/swift/false":{"role":"symbol","url":"/documentation/swift/false","title":"false","identifier":"doc://com.apple.documentation/documentation/swift/false","abstract":[{"text":"A false value.","type":"text"}],"kind":"symbol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UISearchBar/isSearchResultsButtonSelected":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSearchResultsButtonSelected"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBar/isSearchResultsButtonSelected","role":"symbol","abstract":[{"text":"A Boolean value indicating whether the search results button is selected.","type":"text"}],"kind":"symbol","title":"isSearchResultsButtonSelected","url":"/documentation/uikit/uisearchbar/issearchresultsbuttonselected","navigatorTitle":[{"text":"searchResultsButtonSelected","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"/metadata/platforms","value":[{"beta":false,"deprecated":false,"unavailable":false,"name":"iOS","introducedAt":"2.0"},{"beta":false,"deprecated":false,"unavailable":false,"name":"iPadOS","introducedAt":"2.0"},{"beta":false,"deprecated":false,"unavailable":false,"name":"Mac Catalyst","introducedAt":"13.1"},{"name":"visionOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"1.0"}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Property"},{"op":"replace","path":"/metadata/title","value":"showsBookmarkButton"},{"op":"replace","path":"/metadata/symbolKind","value":"property"},{"op":"replace","value":[{"text":"showsBookmarkButton","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UISearchBar"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","path":"/seeAlsoSections","value":[{"anchor":"Configuring-the-search-interface","identifiers":["doc://com.apple.uikit/documentation/UIKit/UISearchBar/showsCancelButton","doc://com.apple.uikit/documentation/UIKit/UISearchBar/setShowsCancelButton(_:animated:)","doc://com.apple.uikit/documentation/UIKit/UISearchBar/showsSearchResultsButton","doc://com.apple.uikit/documentation/UIKit/UISearchBar/isSearchResultsButtonSelected"],"title":"Configuring the search interface","generated":true}]},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"showsBookmarkButton"},{"kind":"text","text":";"}]}]}},{"value":"showsSearchResultsButton","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1showsSearchResultsButton/title","op":"replace"},{"value":[{"kind":"identifier","text":"showsSearchResultsButton"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1showsSearchResultsButton/fragments","op":"replace"},{"value":"showsCancelButton","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1showsCancelButton/title","op":"replace"},{"value":[{"kind":"identifier","text":"showsCancelButton"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1showsCancelButton/fragments","op":"replace"},{"value":"setShowsCancelButton:animated:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1setShowsCancelButton(_:animated:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"setShowsCancelButton:animated:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1setShowsCancelButton(_:animated:)/fragments","op":"replace"},{"value":"showsBookmarkButton","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1showsBookmarkButton/title","op":"replace"},{"value":[{"kind":"identifier","text":"showsBookmarkButton"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1showsBookmarkButton/fragments","op":"replace"},{"value":"UISearchBar","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar/title","op":"replace"},{"value":[{"text":"UISearchBar","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar/fragments","op":"replace"},{"op":"replace","value":[{"text":"UISearchBar","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar/navigatorTitle"},{"op":"replace","value":"searchResultsButtonSelected","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1isSearchResultsButtonSelected/title"},{"op":"replace","value":[{"kind":"identifier","text":"searchResultsButtonSelected"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1isSearchResultsButtonSelected/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}