{"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UISearchBar"]]},"seeAlsoSections":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UISearchBar/placeholder","doc://com.apple.uikit/documentation/UIKit/UISearchBar/prompt","doc://com.apple.uikit/documentation/UIKit/UISearchBar/searchTextField"],"generated":true,"anchor":"Getting-the-search-text","title":"Getting the search text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"The current or starting search text.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"text"},{"kind":"text","text":": "},{"identifier":"doc://com.externally.resolved.symbol/s:SS","kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"anchor":"Discussion","type":"heading","text":"Discussion","level":2},{"inlineContent":[{"text":"The default value is ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}],"kind":"content"}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"text","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property","platforms":[{"introducedAt":"2.0","beta":false,"unavailable":false,"name":"iOS","deprecated":false},{"introducedAt":"2.0","beta":false,"unavailable":false,"name":"iPadOS","deprecated":false},{"introducedAt":"13.1","beta":false,"unavailable":false,"name":"Mac Catalyst","deprecated":false},{"beta":false,"unavailable":false,"name":"tvOS","deprecated":false},{"introducedAt":"1.0","beta":false,"unavailable":false,"name":"visionOS","deprecated":false}],"role":"symbol","title":"text","symbolKind":"property","navigatorTitle":[{"text":"text","kind":"identifier"}],"externalID":"c:objc(cs)UISearchBar(py)text","modules":[{"name":"UIKit"}]},"variants":[{"paths":["/documentation/uikit/uisearchbar/text"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uisearchbar/text"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UISearchBar/text","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.apple.uikit/documentation/UIKit/UISearchBar/placeholder":{"title":"placeholder","url":"/documentation/uikit/uisearchbar/placeholder","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBar/placeholder","type":"topic","navigatorTitle":[{"text":"placeholder","kind":"identifier"}],"abstract":[{"type":"text","text":"The string to display when there’s no other text in the text field."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"placeholder","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.externally.resolved.symbol/c:objc(cs)NSString":{"abstract":[{"type":"text","text":"A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. "}],"title":"NSString","url":"/documentation/foundation/nsstring","kind":"symbol","type":"topic","role":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","fragments":[{"kind":"text","text":"class "},{"text":"NSString","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UISearchBar":{"abstract":[{"text":"A specialized view for receiving search-related information from the user.","type":"text"}],"title":"UISearchBar","url":"/documentation/uikit/uisearchbar","navigatorTitle":[{"text":"UISearchBar","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBar","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UISearchBar","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UISearchBar/prompt":{"title":"prompt","url":"/documentation/uikit/uisearchbar/prompt","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBar/prompt","type":"topic","navigatorTitle":[{"kind":"identifier","text":"prompt"}],"abstract":[{"type":"text","text":"A single line of text displayed at the top of the search bar."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prompt","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]},"doc://com.externally.resolved.symbol/s:SS":{"identifier":"doc://com.externally.resolved.symbol/s:SS","title":"String","url":"/documentation/Swift/String","abstract":[{"type":"text","text":"A Unicode string value that is a collection of characters."}],"fragments":[{"text":"@frozen","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"String"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UISearchBar/searchTextField":{"title":"searchTextField","url":"/documentation/uikit/uisearchbar/searchtextfield","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBar/searchTextField","type":"topic","navigatorTitle":[{"text":"searchTextField","kind":"identifier"}],"abstract":[{"type":"text","text":"The text field that the user enters a search query into."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"searchTextField","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UISearchTextField","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UISearchTextField"}]},"doc://com.apple.uikit/documentation/UIKit/UISearchBar/text":{"title":"text","url":"/documentation/uikit/uisearchbar/text","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchBar/text","type":"topic","navigatorTitle":[{"kind":"identifier","text":"text"}],"abstract":[{"type":"text","text":"The current or starting search text."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"text","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"name":"iOS","beta":false,"introducedAt":"2.0","deprecated":false,"unavailable":false},{"name":"iPadOS","beta":false,"introducedAt":"2.0","deprecated":false,"unavailable":false},{"name":"Mac Catalyst","beta":false,"introducedAt":"13.1","deprecated":false,"unavailable":false},{"name":"tvOS","beta":false,"deprecated":false,"unavailable":false},{"name":"visionOS","beta":false,"introducedAt":"1.0","deprecated":false,"unavailable":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Property"},{"path":"/metadata/title","op":"replace","value":"text"},{"path":"/metadata/symbolKind","op":"replace","value":"property"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"text","kind":"identifier"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UISearchBar"]]}},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UISearchBar/placeholder","doc://com.apple.uikit/documentation/UIKit/UISearchBar/prompt","doc://com.apple.uikit/documentation/UIKit/UISearchBar/searchTextField"],"anchor":"Getting-the-search-text","title":"Getting the search text","generated":true}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"text","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1placeholder/title","value":"placeholder","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1placeholder/fragments","value":[{"text":"placeholder","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract","value":[{"text":"A static, plain-text Unicode string object.","type":"text"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar/title","value":"UISearchBar","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar/fragments","value":[{"text":"UISearchBar","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar/navigatorTitle","value":[{"text":"UISearchBar","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1prompt/title","value":"prompt","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1prompt/fragments","value":[{"text":"prompt","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1searchTextField/title","value":"searchTextField","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1searchTextField/fragments","value":[{"kind":"identifier","text":"searchTextField"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1text/title","value":"text","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1text/fragments","value":[{"kind":"identifier","text":"text"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}