{
  "abstract": [
    {
      "text": "The iCloud account’s change type.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cloudkit/documentation/CloudKit",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineAccountChangeEvent"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineAccountChangeEvent/changeType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CKSyncEngineAccountChangeEvent(py)changeType",
    "fragments": [
      {
        "kind": "identifier",
        "text": "changeType"
      }
    ],
    "modules": [
      {
        "name": "CloudKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "changeType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "changeType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "assign"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineAccountChangeType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CKSyncEngineAccountChangeType",
              "text": "CKSyncEngineAccountChangeType"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "changeType"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.cloudkit/documentation/CloudKit": {
      "abstract": [
        {
          "text": "Store structured app and user data in iCloud containers that all users of your app can share.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CloudKit",
      "type": "topic",
      "url": "/documentation/cloudkit"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineAccountChangeEvent": {
      "abstract": [
        {
          "text": "An event that provides information about a change to the device’s iCloud account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CKSyncEngineAccountChangeEvent"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineAccountChangeEvent",
      "kind": "symbol",
      "role": "symbol",
      "title": "CKSyncEngineAccountChangeEvent",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengineaccountchangeevent"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineAccountChangeEvent/changeType": {
      "abstract": [
        {
          "text": "The iCloud account’s change type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "changeType"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineAccountChangeEvent/changeType",
      "kind": "symbol",
      "role": "symbol",
      "title": "changeType",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengineaccountchangeevent/changetype"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineAccountChangeEvent/currentUser": {
      "abstract": [
        {
          "text": "The current iCloud account’s record identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "currentUser"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineAccountChangeEvent/currentUser",
      "kind": "symbol",
      "role": "symbol",
      "title": "currentUser",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengineaccountchangeevent/currentuser"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineAccountChangeEvent/previousUser": {
      "abstract": [
        {
          "text": "The previous iCloud account’s record identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "previousUser"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineAccountChangeEvent/previousUser",
      "kind": "symbol",
      "role": "symbol",
      "title": "previousUser",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengineaccountchangeevent/previoususer"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineAccountChangeType": {
      "abstract": [
        {
          "text": "Describes a change to the device’s iCloud account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKSyncEngineAccountChangeType"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineAccountChangeType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKSyncEngineAccountChangeType"
        }
      ],
      "role": "symbol",
      "title": "CKSyncEngineAccountChangeType",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengineaccountchangetype"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Understanding-the-change",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineAccountChangeType",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineAccountChangeEvent/previousUser",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineAccountChangeEvent/currentUser"
      ],
      "title": "Understanding the change"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSyncEngineAccountChangeType/title",
          "value": "CKSyncEngineAccountChangeType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSyncEngineAccountChangeType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSyncEngineAccountChangeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSyncEngineAccountChangeType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSyncEngineAccountChangeType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cloudkit/cksyncengineaccountchangeevent/changetype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
