{
  "abstract": [
    {
      "text": "The number of MIDI value maps in the variable-length portion of the struct.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremidi/documentation/CoreMIDI",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/numMaps"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@MIDIThruConnectionParams@FI@numMaps",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "numMaps"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s6UInt16V",
        "text": "UInt16"
      }
    ],
    "modules": [
      {
        "name": "Core MIDI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "numMaps"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "numMaps"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "numMaps"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt16V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt16V",
              "text": "UInt16"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremidi/documentation/CoreMIDI": {
      "abstract": [
        {
          "text": "Communicate with MIDI devices such as hardware keyboards and synthesizers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI",
      "kind": "symbol",
      "role": "collection",
      "title": "Core MIDI",
      "type": "topic",
      "url": "/documentation/coremidi"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams": {
      "abstract": [
        {
          "text": "A set of MIDI routings and transformations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIThruConnectionParams"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIThruConnectionParams"
        }
      ],
      "role": "symbol",
      "title": "MIDIThruConnectionParams",
      "type": "topic",
      "url": "/documentation/coremidi/midithruconnectionparams"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/channelMap": {
      "abstract": [
        {
          "text": "A mapping of MIDI channels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "channelMap"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/channelMap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "channelMap"
        }
      ],
      "role": "symbol",
      "title": "channelMap",
      "type": "topic",
      "url": "/documentation/coremidi/midithruconnectionparams/channelmap"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/channelPressure": {
      "abstract": [
        {
          "text": "The transformation of MIDI monophonic channel pressure events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "channelPressure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDITransform",
          "text": "MIDITransform"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/channelPressure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "channelPressure"
        }
      ],
      "role": "symbol",
      "title": "channelPressure",
      "type": "topic",
      "url": "/documentation/coremidi/midithruconnectionparams/channelpressure"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/destinations": {
      "abstract": [
        {
          "text": "All MIDI destinations for this connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "destinations"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIThruConnectionEndpoint",
          "text": "MIDIThruConnectionEndpoint"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIThruConnectionEndpoint",
          "text": "MIDIThruConnectionEndpoint"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIThruConnectionEndpoint",
          "text": "MIDIThruConnectionEndpoint"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIThruConnectionEndpoint",
          "text": "MIDIThruConnectionEndpoint"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIThruConnectionEndpoint",
          "text": "MIDIThruConnectionEndpoint"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIThruConnectionEndpoint",
          "text": "MIDIThruConnectionEndpoint"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIThruConnectionEndpoint",
          "text": "MIDIThruConnectionEndpoint"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIThruConnectionEndpoint",
          "text": "MIDIThruConnectionEndpoint"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/destinations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "destinations"
        }
      ],
      "role": "symbol",
      "title": "destinations",
      "type": "topic",
      "url": "/documentation/coremidi/midithruconnectionparams/destinations"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/filterOutAllControls": {
      "abstract": [
        {
          "text": "A value that indicates whether to filter out MIDI continuous control messages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "filterOutAllControls"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/filterOutAllControls",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "filterOutAllControls"
        }
      ],
      "role": "symbol",
      "title": "filterOutAllControls",
      "type": "topic",
      "url": "/documentation/coremidi/midithruconnectionparams/filteroutallcontrols"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/highNote": {
      "abstract": [
        {
          "text": "The note value above which the system filters out notes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "highNote"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/highNote",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "highNote"
        }
      ],
      "role": "symbol",
      "title": "highNote",
      "type": "topic",
      "url": "/documentation/coremidi/midithruconnectionparams/highnote"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/highVelocity": {
      "abstract": [
        {
          "text": "The velocity value above which the system filters out notes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "highVelocity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/highVelocity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "highVelocity"
        }
      ],
      "role": "symbol",
      "title": "highVelocity",
      "type": "topic",
      "url": "/documentation/coremidi/midithruconnectionparams/highvelocity"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/keyPressure": {
      "abstract": [
        {
          "text": "The transformation of polyphonic key pressure events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyPressure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDITransform",
          "text": "MIDITransform"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/keyPressure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "keyPressure"
        }
      ],
      "role": "symbol",
      "title": "keyPressure",
      "type": "topic",
      "url": "/documentation/coremidi/midithruconnectionparams/keypressure"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/lowNote": {
      "abstract": [
        {
          "text": "The note value below which the system filters out notes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lowNote"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/lowNote",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lowNote"
        }
      ],
      "role": "symbol",
      "title": "lowNote",
      "type": "topic",
      "url": "/documentation/coremidi/midithruconnectionparams/lownote"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/lowVelocity": {
      "abstract": [
        {
          "text": "The velocity value below which the system filters out notes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lowVelocity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/lowVelocity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lowVelocity"
        }
      ],
      "role": "symbol",
      "title": "lowVelocity",
      "type": "topic",
      "url": "/documentation/coremidi/midithruconnectionparams/lowvelocity"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/noteNumber": {
      "abstract": [
        {
          "text": "The transformation of MIDI note numbers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noteNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDITransform",
          "text": "MIDITransform"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/noteNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "noteNumber"
        }
      ],
      "role": "symbol",
      "title": "noteNumber",
      "type": "topic",
      "url": "/documentation/coremidi/midithruconnectionparams/notenumber"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/numDestinations": {
      "abstract": [
        {
          "text": "The number of valid destinations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numDestinations"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/numDestinations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "numDestinations"
        }
      ],
      "role": "symbol",
      "title": "numDestinations",
      "type": "topic",
      "url": "/documentation/coremidi/midithruconnectionparams/numdestinations"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/numMaps": {
      "abstract": [
        {
          "text": "The number of MIDI value maps in the variable-length portion of the struct.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numMaps"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/numMaps",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "numMaps"
        }
      ],
      "role": "symbol",
      "title": "numMaps",
      "type": "topic",
      "url": "/documentation/coremidi/midithruconnectionparams/nummaps"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/numSources": {
      "abstract": [
        {
          "text": "The number of valid sources.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numSources"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/numSources",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "numSources"
        }
      ],
      "role": "symbol",
      "title": "numSources",
      "type": "topic",
      "url": "/documentation/coremidi/midithruconnectionparams/numsources"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/sources": {
      "abstract": [
        {
          "text": "All MIDI sources for this connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sources"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIThruConnectionEndpoint",
          "text": "MIDIThruConnectionEndpoint"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIThruConnectionEndpoint",
          "text": "MIDIThruConnectionEndpoint"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIThruConnectionEndpoint",
          "text": "MIDIThruConnectionEndpoint"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIThruConnectionEndpoint",
          "text": "MIDIThruConnectionEndpoint"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIThruConnectionEndpoint",
          "text": "MIDIThruConnectionEndpoint"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIThruConnectionEndpoint",
          "text": "MIDIThruConnectionEndpoint"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIThruConnectionEndpoint",
          "text": "MIDIThruConnectionEndpoint"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIThruConnectionEndpoint",
          "text": "MIDIThruConnectionEndpoint"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/sources",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sources"
        }
      ],
      "role": "symbol",
      "title": "sources",
      "type": "topic",
      "url": "/documentation/coremidi/midithruconnectionparams/sources"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/velocity": {
      "abstract": [
        {
          "text": "A note velocity transformation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "velocity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDITransform",
          "text": "MIDITransform"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/velocity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "velocity"
        }
      ],
      "role": "symbol",
      "title": "velocity",
      "type": "topic",
      "url": "/documentation/coremidi/midithruconnectionparams/velocity"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/version": {
      "abstract": [
        {
          "text": "The version number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "version"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/version",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "version"
        }
      ],
      "role": "symbol",
      "title": "version",
      "type": "topic",
      "url": "/documentation/coremidi/midithruconnectionparams/version"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt16V": {
      "abstract": [
        {
          "text": "A 16-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt16"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt16V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt16",
      "type": "topic",
      "url": "/documentation/Swift/UInt16"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Connection-Parameters",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/noteNumber",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/lowNote",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/highNote",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/velocity",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/lowVelocity",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/highVelocity",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/keyPressure",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/channelPressure",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/version",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/numSources",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/sources",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/numDestinations",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/destinations",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/channelMap",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/filterOutAllControls"
      ],
      "title": "Connection Parameters"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "numMaps"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "numMaps"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremidi/documentation/CoreMIDI",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Connection-Parameters",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/noteNumber",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/lowNote",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/highNote",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/velocity",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/lowVelocity",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/highVelocity",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/keyPressure",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/channelPressure",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/version",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/numSources",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/sources",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/numDestinations",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/destinations",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/channelMap",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionParams/filterOutAllControls"
              ],
              "title": "Connection Parameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@UInt16",
                    "text": "UInt16"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "numMaps"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionParams~1channelMap/title",
          "value": "channelMap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionParams~1channelMap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "channelMap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionParams~1keyPressure/title",
          "value": "keyPressure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionParams~1keyPressure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "keyPressure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionParams~1velocity/title",
          "value": "velocity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionParams~1velocity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "velocity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionParams~1lowNote/title",
          "value": "lowNote"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionParams~1lowNote/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lowNote"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionParams~1filterOutAllControls/title",
          "value": "filterOutAllControls"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionParams~1filterOutAllControls/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "filterOutAllControls"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionParams~1destinations/title",
          "value": "destinations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionParams~1destinations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "destinations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionParams~1lowVelocity/title",
          "value": "lowVelocity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionParams~1lowVelocity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lowVelocity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionParams~1numDestinations/title",
          "value": "numDestinations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionParams~1numDestinations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "numDestinations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionParams~1channelPressure/title",
          "value": "channelPressure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionParams~1channelPressure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "channelPressure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionParams~1version/title",
          "value": "version"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionParams~1version/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "version"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionParams~1numSources/title",
          "value": "numSources"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionParams~1numSources/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "numSources"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionParams~1sources/title",
          "value": "sources"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionParams~1sources/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sources"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionParams~1highNote/title",
          "value": "highNote"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionParams~1highNote/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "highNote"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionParams~1numMaps/title",
          "value": "numMaps"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionParams~1numMaps/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "numMaps"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionParams~1highVelocity/title",
          "value": "highVelocity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionParams~1highVelocity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "highVelocity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionParams~1noteNumber/title",
          "value": "noteNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionParams~1noteNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "noteNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionParams/title",
          "value": "MIDIThruConnectionParams"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionParams/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIThruConnectionParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionParams/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIThruConnectionParams"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremidi/midithruconnectionparams/nummaps"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremidi/midithruconnectionparams/nummaps"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
