{
  "abstract": [
    {
      "text": "The Print panel includes a separate accessory view for manipulating the paper size, orientation, and scaling attributes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsPageSetupAccessory"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSPrintPanelOptions@NSPrintPanelShowsPageSetupAccessory",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "showsPageSetupAccessory"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSPrintPanel",
        "text": "NSPrintPanel"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NSPrintPanelOptions",
        "text": "Options"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSPrintPanelShowsPageSetupAccessory"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "showsPageSetupAccessory"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "showsPageSetupAccessory"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSPrintPanel",
              "text": "NSPrintPanel"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSPrintPanelOptions",
              "text": "Options"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Page setup fields that are already configured for display on the main portion of the Print panel appear there and not on this accessory panel.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel": {
      "abstract": [
        {
          "text": "The Print panel that queries the user for information about a print job.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPrintPanel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintPanel"
        }
      ],
      "role": "symbol",
      "title": "NSPrintPanel",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct": {
      "abstract": [
        {
          "text": "Constants that specify options for configuring the contents of the main Print panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Options"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Options"
        }
      ],
      "role": "symbol",
      "title": "NSPrintPanel.Options",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanel/options-swift.struct"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsCopies": {
      "abstract": [
        {
          "text": "The Print panel includes a field for manipulating the number of copies being printed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showsCopies"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintPanel",
          "text": "NSPrintPanel"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSPrintPanelOptions",
          "text": "Options"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsCopies",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintPanelShowsCopies"
        }
      ],
      "role": "symbol",
      "title": "showsCopies",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanel/options-swift.struct/showscopies"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsOrientation": {
      "abstract": [
        {
          "text": "The Print panel includes a control for manipulating the page orientation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showsOrientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintPanel",
          "text": "NSPrintPanel"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSPrintPanelOptions",
          "text": "Options"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintPanelShowsOrientation"
        }
      ],
      "role": "symbol",
      "title": "showsOrientation",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanel/options-swift.struct/showsorientation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsPageRange": {
      "abstract": [
        {
          "text": "The Print panel includes a set of fields for manipulating the range of pages being printed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showsPageRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintPanel",
          "text": "NSPrintPanel"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSPrintPanelOptions",
          "text": "Options"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsPageRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintPanelShowsPageRange"
        }
      ],
      "role": "symbol",
      "title": "showsPageRange",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanel/options-swift.struct/showspagerange"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsPageSetupAccessory": {
      "abstract": [
        {
          "text": "The Print panel includes a separate accessory view for manipulating the paper size, orientation, and scaling attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showsPageSetupAccessory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintPanel",
          "text": "NSPrintPanel"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSPrintPanelOptions",
          "text": "Options"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsPageSetupAccessory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintPanelShowsPageSetupAccessory"
        }
      ],
      "role": "symbol",
      "title": "showsPageSetupAccessory",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanel/options-swift.struct/showspagesetupaccessory"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsPaperSize": {
      "abstract": [
        {
          "text": "The Print panel includes a control for manipulating the paper size of the printer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showsPaperSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintPanel",
          "text": "NSPrintPanel"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSPrintPanelOptions",
          "text": "Options"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsPaperSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintPanelShowsPaperSize"
        }
      ],
      "role": "symbol",
      "title": "showsPaperSize",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanel/options-swift.struct/showspapersize"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsPreview": {
      "abstract": [
        {
          "text": "The Print panel displays a built-in preview of the document contents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showsPreview"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintPanel",
          "text": "NSPrintPanel"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSPrintPanelOptions",
          "text": "Options"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsPreview",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintPanelShowsPreview"
        }
      ],
      "role": "symbol",
      "title": "showsPreview",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanel/options-swift.struct/showspreview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsPrintSelection": {
      "abstract": [
        {
          "text": "The Print panel includes an additional selection option for paper range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showsPrintSelection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintPanel",
          "text": "NSPrintPanel"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSPrintPanelOptions",
          "text": "Options"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsPrintSelection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintPanelShowsPrintSelection"
        }
      ],
      "role": "symbol",
      "title": "showsPrintSelection",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanel/options-swift.struct/showsprintselection"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsScaling": {
      "abstract": [
        {
          "text": "The Print panel includes a control for scaling the printed output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showsScaling"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintPanel",
          "text": "NSPrintPanel"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSPrintPanelOptions",
          "text": "Options"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsScaling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintPanelShowsScaling"
        }
      ],
      "role": "symbol",
      "title": "showsScaling",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanel/options-swift.struct/showsscaling"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsCopies",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsPageRange",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsPaperSize",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsOrientation",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsScaling",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsPrintSelection",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsPreview"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSPrintPanelShowsPageSetupAccessory"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPanelShowsPageSetupAccessory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsCopies",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsPageRange",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsPaperSize",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsOrientation",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsScaling",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsPrintSelection",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsPreview"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSPrintPanelShowsPageSetupAccessory"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1Options-swift.struct~1showsPreview/title",
          "value": "NSPrintPanelShowsPreview"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1Options-swift.struct~1showsPreview/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPanelShowsPreview"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1Options-swift.struct/title",
          "value": "NSPrintPanelOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1Options-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPanelOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1Options-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPanelOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1Options-swift.struct~1showsPaperSize/title",
          "value": "NSPrintPanelShowsPaperSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1Options-swift.struct~1showsPaperSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPanelShowsPaperSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1Options-swift.struct~1showsCopies/title",
          "value": "NSPrintPanelShowsCopies"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1Options-swift.struct~1showsCopies/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPanelShowsCopies"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1Options-swift.struct~1showsScaling/title",
          "value": "NSPrintPanelShowsScaling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1Options-swift.struct~1showsScaling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPanelShowsScaling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1Options-swift.struct~1showsPageRange/title",
          "value": "NSPrintPanelShowsPageRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1Options-swift.struct~1showsPageRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPanelShowsPageRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1Options-swift.struct~1showsPageSetupAccessory/title",
          "value": "NSPrintPanelShowsPageSetupAccessory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1Options-swift.struct~1showsPageSetupAccessory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPanelShowsPageSetupAccessory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1Options-swift.struct~1showsOrientation/title",
          "value": "NSPrintPanelShowsOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1Options-swift.struct~1showsOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPanelShowsOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1Options-swift.struct~1showsPrintSelection/title",
          "value": "NSPrintPanelShowsPrintSelection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1Options-swift.struct~1showsPrintSelection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPanelShowsPrintSelection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel/title",
          "value": "NSPrintPanel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPanel"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsprintpanel/options-swift.struct/showspagesetupaccessory"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsprintpanel/options-swift.struct/showspagesetupaccessory"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
