{
  "abstract": [
    {
      "text": "Request and analyze risk data using server-to-server calls.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.DeviceCheck/documentation/DeviceCheck"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.DeviceCheck/documentation/DeviceCheck/assessing-fraud-risk"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "DeviceCheck"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Assessing fraud risk"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Your app uses the App Attest service to assert its authenticity. A compromised version",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "of your app running on a genuine, unmodified Apple device can’t create valid assertions.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "However, an attacker that modifies the device’s operating system might bypass restrictions.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Although modifying the operating system is difficult and an unlikely source of widespread",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "fraud, you might need to guard against an attack that uses a single compromised device",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to serve assertions to many subscribers.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "While it isn’t possible to detect fraudulent activity with absolute certainty, App",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Attest does provide a metric to assess its likelihood. Specifically, you can get",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "an approximate count of unique attestations for your app on a particular device.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "A count that’s higher than expected might be an indication of a compromised device",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "that’s serving multiple compromised instances of your app. You can use this information",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to assess your risk.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "assessing_fraud_risk-1",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To get the metric, use the receipt that your server extracts from the attestation",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "object, as described in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.DeviceCheck/documentation/DeviceCheck/validating-apps-that-connect-to-your-server",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Send the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "receipt from your server to an Apple server using an HTTP POST request. The Apple",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "server returns a new receipt that includes the metric. You can also use the new receipt",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to refresh the metric later, but be sure to do that before the receipt expires.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Create-a-request",
          "level": 3,
          "text": "Create a request",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You request a new receipt by sending an HTTP POST to an Apple server with a body",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "composed entirely of the Base64-encoded receipt you extracted from an attestation",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "object. Add a header that includes an authentication key in the form of a generated",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "JSON Web Token (JWT):",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "Authorization: <JWT>"
          ],
          "syntax": "http",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Generate the token using the same procedure you use to create a provider authentication",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "token for the Apple Push Notification service (APNs), as described in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UserNotifications/establishing-a-token-based-connection-to-apns",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Be sure to enable the DeviceCheck service when requesting the cryptographic key that",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "you use to encrypt the App Attest token.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Send the request to the ",
              "type": "text"
            },
            {
              "code": "attestationData",
              "type": "codeVoice"
            },
            {
              "text": " endpoint. For example, a ",
              "type": "text"
            },
            {
              "code": "curl",
              "type": "codeVoice"
            },
            {
              "text": " command",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "that does this using a receipt stored in a file called ",
              "type": "text"
            },
            {
              "code": "receipt.bin",
              "type": "codeVoice"
            },
            {
              "text": " might look like:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "% curl -i --verbose -H \"Authorization: <JWT>\" \\",
            "       -X POST --data-binary @receipt.bin \\",
            "       https://data-development.appattest.apple.com/v1/attestationData "
          ],
          "syntax": "shell",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Use the base URL of ",
              "type": "text"
            },
            {
              "code": "https://data-development.appattest.apple.com",
              "type": "codeVoice"
            },
            {
              "text": " shown in the example",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "above for testing. This URL accesses the sandbox environment that your app uses during",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "development. To work with apps that you’ve distributed through the App Store, TestFlight,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "or with an Enterprise Developer certificate, use a base URL of ",
              "type": "text"
            },
            {
              "code": "https://data.appattest.apple.com",
              "type": "codeVoice"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "instead. You can’t use a receipt generated in one environment to request a new receipt",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "in the other.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Parse-the-response",
          "level": 3,
          "text": "Parse the response",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If your request succeeds, the Apple server sends back a response with code ",
              "type": "text"
            },
            {
              "code": "200",
              "type": "codeVoice"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "and a body that consist of a new, Base64-encoded receipt. Store this receipt in place",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "of the one used to generate the request, because you’ll use it the next time you",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "make a request to refresh the metric. For a list of other response codes you might",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "receive instead, like ",
              "type": "text"
            },
            {
              "code": "401",
              "type": "codeVoice"
            },
            {
              "text": " for a missing or malformed token, see Understand HTTP response codes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The App Attest receipt has a structure similar to an App Store receipt, with a PKCS",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "#7 container that contains a signature, certificate chain, and an ASN.1–encoded payload.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "For information about App Store receipts, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/releasenotes/General/ValidateAppStoreReceipt/Chapters/ValidateLocally.html#//apple_ref/doc/uid/TP40010573-CH1-SW2",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "App Attest receipts use the following fields:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Field",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Value",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Example",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "2",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "App ID",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "A1B2C3D4E5.com.example.appname",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "3",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Attested Public Key",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "MIICxTCCAkugAwIBAgIGAXD4YkDCM...odjJY76fyArAeunX3FO7w=",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "4",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Client Hash",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "4f0e5a36eedd8009f25529ec10770512ddc0ba261bf439c276f0c062c3015dfb",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "5",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Token",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "NojAMV3DBZGAqbUyKSGUvrK5fcd2mkDa/6oSigTP7c8=",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "6",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Receipt Type",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "ATTEST",
                      "type": "codeVoice"
                    },
                    {
                      "text": " or ",
                      "type": "text"
                    },
                    {
                      "code": "RECEIPT",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "12",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Creation Time",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "2020-06-22T14:40:08.819Z",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "17",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Risk Metric",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "5",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "19",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Not Before",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "2020-07-22T14:40:38.819Z",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "21",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Expiration Time",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "2020-08-22T14:40:38.819Z",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        },
        {
          "anchor": "Verify-the-receipt",
          "level": 3,
          "text": "Verify the receipt",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When you receive a receipt (including the one that accompanies an attestation object)",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "— but before trusting it — check its validity:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Verify the signature.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Evalutate the trustworthiness of the signing certificate up to the ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://www.apple.com/certificateauthority/AppleRootCA-G3.cer",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "for App Attest.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Parse the ASN.1 structure that makes up the payload.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Verify that the receipt contains the App ID of your app in field 2. Your app’s",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "App ID is the concatenation of your 10-digit Team ID, a period, and the app’s bundle",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "ID.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Verify that the receipt’s creation time, given in field 12, is no more than five",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "minutes old. This helps to thwart replay attacks.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Verify that the attested public key in field 3, encoded as a DER ASN.1 object,",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "matches the one you stored after initial attestation.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "anchor": "Interpret-the-metric",
          "level": 3,
          "text": "Interpret the metric",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Field 6 of the receipt contains either the string ",
              "type": "text"
            },
            {
              "code": "ATTEST",
              "type": "codeVoice"
            },
            {
              "text": " for the receipt that comes",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "with an attestation object, or the string ",
              "type": "text"
            },
            {
              "code": "RECEIPT",
              "type": "codeVoice"
            },
            {
              "text": " for receipts that you request",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "using your server. Only the latter provide the risk metric in field 17. The receipt",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "represents the metric as a string that indicates the number of attested keys associated",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "with a given device over the past 30 days. Look for this value to be a",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "low number.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Note that the metric can grow if a user reinstalls your app, restores from a backup,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "or transfers a device to another user. For privacy reasons, App Attest keys stored",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "on device don’t survive these events, forcing your app to generate a new key on the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "same device. This growth should be modest, but you’ll have to tune your risk assessment",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "logic based on the typical numbers that you see over time. You can help to keep the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "number small by only generating new keys when absolutely necessary.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Refresh-the-metric",
          "level": 3,
          "text": "Refresh the metric",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When you want to read the latest value for the metric, create a new request using",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the most recently received receipt as the HTTP POST body, just like you did with",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the attestation receipt. Be sure to wait until after the date found in field 19.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "If you try to refresh too soon, the Apple server sends an error response with code",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "code": "304",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "On the other hand, do use the receipt before the receipt’s expiration date, found",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "in field 21. After that date, the Apple server might not honor the request. Therefore,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "if you want to receive metrics at all, you need to do so periodically.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Understand-HTTP-response-codes",
          "level": 3,
          "text": "Understand HTTP response codes",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When you communicate with the server, you may receive one of the following response",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "codes:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Code",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Descriptive String",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Meaning",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "200",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "The transaction was successful.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "304",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Not Modified",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "You made the request before the previous receipt’s “Not Before” date.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "400",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Incorrect Environment",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "You used a development receipt in production, or vice versa.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "400",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Bad Payload",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Your request has a missing or badly formatted payload.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "401",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Unauthorized",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "You used an authentication token that the Apple server can’t verify or that doesn’t match the receipt.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "404",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "No Data Found",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "No data available for the supplied receipt.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "429",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Too Many Requests",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "You sent too many requests to the server.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "500",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Server Error",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "An error occurred on the server.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "503",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Service Unavailable",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "The service is unavailable.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "assessing_fraud_risk-1": {
      "alt": "A diagram showing that your server sends receipts to an Apple server and receives metrics in return.",
      "identifier": "assessing_fraud_risk-1",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/174c88ce470d9c9b4ded3df3553d72f2/assessing_fraud_risk-1@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/a8e58f907e9c70a169cf95ba12108f6b/assessing_fraud_risk-1~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.DeviceCheck/documentation/DeviceCheck": {
      "abstract": [
        {
          "text": "Reduce fraudulent use of your services by managing device state and asserting app",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "integrity.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.DeviceCheck/documentation/DeviceCheck",
      "kind": "symbol",
      "role": "collection",
      "title": "DeviceCheck",
      "type": "topic",
      "url": "/documentation/devicecheck"
    },
    "doc://com.apple.DeviceCheck/documentation/DeviceCheck/DCAppAttestService": {
      "abstract": [
        {
          "text": "A service that you use to validate the instance of your app running on a",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DCAppAttestService"
        }
      ],
      "identifier": "doc://com.apple.DeviceCheck/documentation/DeviceCheck/DCAppAttestService",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DCAppAttestService"
        }
      ],
      "role": "symbol",
      "title": "DCAppAttestService",
      "type": "topic",
      "url": "/documentation/devicecheck/dcappattestservice"
    },
    "doc://com.apple.DeviceCheck/documentation/DeviceCheck/establishing-your-app-s-integrity": {
      "abstract": [
        {
          "text": "Ensure that requests your server receives come from legitimate instances of your",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.DeviceCheck/documentation/DeviceCheck/establishing-your-app-s-integrity",
      "kind": "article",
      "role": "article",
      "title": "Establishing your app’s integrity",
      "type": "topic",
      "url": "/documentation/devicecheck/establishing-your-app-s-integrity"
    },
    "doc://com.apple.DeviceCheck/documentation/DeviceCheck/preparing-to-use-the-app-attest-service": {
      "abstract": [
        {
          "text": "Test your implementation in a development environment and onboard users gradually.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.DeviceCheck/documentation/DeviceCheck/preparing-to-use-the-app-attest-service",
      "kind": "article",
      "role": "article",
      "title": "Preparing to use the app attest service",
      "type": "topic",
      "url": "/documentation/devicecheck/preparing-to-use-the-app-attest-service"
    },
    "doc://com.apple.DeviceCheck/documentation/DeviceCheck/validating-apps-that-connect-to-your-server": {
      "abstract": [
        {
          "text": "Verify that connections to your server come from legitimate instances of your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.DeviceCheck/documentation/DeviceCheck/validating-apps-that-connect-to-your-server",
      "kind": "article",
      "role": "article",
      "title": "Validating apps that connect to your server",
      "type": "topic",
      "url": "/documentation/devicecheck/validating-apps-that-connect-to-your-server"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.devicecheck.appattest-environment": {
      "abstract": [
        {
          "text": "The environment for an app that uses the App Attest service to validate itself.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.devicecheck.appattest-environment",
      "kind": "symbol",
      "role": "symbol",
      "title": "App Attest Environment",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.devicecheck.appattest-environment"
    },
    "doc://com.apple.documentation/documentation/UserNotifications/establishing-a-token-based-connection-to-apns": {
      "abstract": [
        {
          "text": "Secure your communications with Apple Push Notification service (APNs) by using stateless authentication tokens.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UserNotifications/establishing-a-token-based-connection-to-apns",
      "kind": "article",
      "role": "article",
      "title": "Establishing a token-based connection to APNs",
      "type": "topic",
      "url": "/documentation/UserNotifications/establishing-a-token-based-connection-to-apns"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/library/archive/releasenotes/General/ValidateAppStoreReceipt/Chapters/ValidateLocally.html#//apple_ref/doc/uid/TP40010573-CH1-SW2": {
      "identifier": "https://developer.apple.com/library/archive/releasenotes/General/ValidateAppStoreReceipt/Chapters/ValidateLocally.html#//apple_ref/doc/uid/TP40010573-CH1-SW2",
      "title": "Validating Receipts Locally",
      "titleInlineContent": [
        {
          "text": "Validating Receipts Locally",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/releasenotes/General/ValidateAppStoreReceipt/Chapters/ValidateLocally.html#//apple_ref/doc/uid/TP40010573-CH1-SW2"
    },
    "https://www.apple.com/certificateauthority/AppleRootCA-G3.cer": {
      "identifier": "https://www.apple.com/certificateauthority/AppleRootCA-G3.cer",
      "title": "Apple public root certificate",
      "titleInlineContent": [
        {
          "text": "Apple public",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "root certificate",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://www.apple.com/certificateauthority/AppleRootCA-G3.cer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "App-Attest",
      "generated": true,
      "identifiers": [
        "doc://com.apple.DeviceCheck/documentation/DeviceCheck/establishing-your-app-s-integrity",
        "doc://com.apple.DeviceCheck/documentation/DeviceCheck/validating-apps-that-connect-to-your-server",
        "doc://com.apple.DeviceCheck/documentation/DeviceCheck/preparing-to-use-the-app-attest-service",
        "doc://com.apple.DeviceCheck/documentation/DeviceCheck/DCAppAttestService",
        "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.devicecheck.appattest-environment"
      ],
      "title": "App Attest"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "App-Attest",
              "generated": true,
              "identifiers": [
                "doc://com.apple.DeviceCheck/documentation/DeviceCheck/establishing-your-app-s-integrity",
                "doc://com.apple.DeviceCheck/documentation/DeviceCheck/validating-apps-that-connect-to-your-server",
                "doc://com.apple.DeviceCheck/documentation/DeviceCheck/preparing-to-use-the-app-attest-service",
                "doc://com.apple.DeviceCheck/documentation/DeviceCheck/DCAppAttestService",
                "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.devicecheck.appattest-environment"
              ],
              "title": "App Attest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.DeviceCheck~1documentation~1DeviceCheck~1DCAppAttestService/title",
          "value": "DCAppAttestService"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.DeviceCheck~1documentation~1DeviceCheck~1DCAppAttestService/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DCAppAttestService"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.DeviceCheck~1documentation~1DeviceCheck~1DCAppAttestService/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DCAppAttestService"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/devicecheck/assessing-fraud-risk"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/devicecheck/assessing-fraud-risk"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
