{
  "abstract": [
    {
      "text": "Test your implementation in a development environment and onboard users gradually.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.DeviceCheck/documentation/DeviceCheck"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.DeviceCheck/documentation/DeviceCheck/preparing-to-use-the-app-attest-service"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "DeviceCheck"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Preparing to use the app attest service"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The App Attest service records device metrics that you can’t reset. To avoid affecting",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the real metrics for devices that you use for development, you test your implementation",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "in a sandbox environment. When you do start using App Attest in a production environment,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "use care not to overwhelm Apple’s servers with requests from too many devices at",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "once.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Test-Your-implementation",
          "level": 3,
          "text": "Test Your implementation",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "During development, you use a sandbox environment to test your adoption of App Attest.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "The App Attest service tracks the keys that you generate in this mode separately",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "from the keys generated in production mode. This allows you to generate and attest",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "any number of keys on a given device without polluting that device’s production key",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "count.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If instead you want to use the App Attest production servers during development,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "add the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.devicecheck.appattest-environment",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "entitlement to your app’s entitlements file, and set the associated value to ",
              "type": "text"
            },
            {
              "code": "production",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Regardless of how you set the entitlement, your app always operates in production",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "mode after distribution, whether through TestFlight, the App Store, or the Apple",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Developer Enterprise Program.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When sending a sandbox-generated attestation object to your server, the verification",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "procedure changes slightly. Specifically, expect to find the value ",
              "type": "text"
            },
            {
              "code": "appattestsandbox",
              "type": "codeVoice"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "in the authenticator data’s ",
              "type": "text"
            },
            {
              "code": "aaguid",
              "type": "codeVoice"
            },
            {
              "text": " field. Also, when using a sandbox-generated",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "receipt to make the server-to-server call that obtains the fraud metric, use ",
              "type": "text"
            },
            {
              "code": "https://data-development.appattest.apple.com",
              "type": "codeVoice"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "as the base URL.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "You can’t use a key or receipt from the sandbox environment in the production",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "environment, or vice versa.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "anchor": "Onboard-users-gradually",
          "level": 3,
          "text": "Onboard users gradually",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If you have a large user base, consider enabling App Attest in stages. When your",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "app calls ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.DeviceCheck/documentation/DeviceCheck/DCAppAttestService/attestKey(_:clientDataHash:completionHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "— which you typically do once per user per device — the DeviceCheck framework makes",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "a call to an Apple server to perform the attestation. Apple servers might throttle",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "attestation traffic from a particular app to avoid becoming overwhelmed if too many",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "instances of your app make this call simultaneously. That could happen if you have",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "a lot of users that simultaneously receive an app update enabling App Attest.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Instead, activate the feature for smaller groups of users over a period of time. As",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "a rule of thumb, we suggest gradually and uniformly ramping up no more than 10 million",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "users per day per app. After the initial rollout, your app makes requests only for new",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "users, new devices, and reinstallations. This kind of traffic shouldn’t result in any",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "throttling.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "To avoid encountering ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.DeviceCheck/documentation/DeviceCheck/DCAppAttestService/attestKey(_:clientDataHash:completionHandler:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "rate limits, we generally recommend that your apps call this method fewer than 100 request",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "per second across all installations of your apps. The rate limit threshold may fluctuate",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "dynamically to protect Apple’s certificate signing infrastructure. Be prepared to handle",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "these errors and to have a mechanism to pull back on requests from your apps if this occurs.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.DeviceCheck/documentation/DeviceCheck": {
      "abstract": [
        {
          "text": "Reduce fraudulent use of your services by managing device state and asserting app",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "integrity.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.DeviceCheck/documentation/DeviceCheck",
      "kind": "symbol",
      "role": "collection",
      "title": "DeviceCheck",
      "type": "topic",
      "url": "/documentation/devicecheck"
    },
    "doc://com.apple.DeviceCheck/documentation/DeviceCheck/DCAppAttestService": {
      "abstract": [
        {
          "text": "A service that you use to validate the instance of your app running on a",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DCAppAttestService"
        }
      ],
      "identifier": "doc://com.apple.DeviceCheck/documentation/DeviceCheck/DCAppAttestService",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DCAppAttestService"
        }
      ],
      "role": "symbol",
      "title": "DCAppAttestService",
      "type": "topic",
      "url": "/documentation/devicecheck/dcappattestservice"
    },
    "doc://com.apple.DeviceCheck/documentation/DeviceCheck/DCAppAttestService/attestKey(_:clientDataHash:completionHandler:)": {
      "abstract": [
        {
          "text": "Asks Apple to attest to the validity of a generated cryptographic key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attestKey"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "clientDataHash"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.DeviceCheck/documentation/DeviceCheck/DCAppAttestService/attestKey(_:clientDataHash:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attestKey:clientDataHash:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "attestKey(_:clientDataHash:completionHandler:)",
      "type": "topic",
      "url": "/documentation/devicecheck/dcappattestservice/attestkey(_:clientdatahash:completionhandler:)"
    },
    "doc://com.apple.DeviceCheck/documentation/DeviceCheck/assessing-fraud-risk": {
      "abstract": [
        {
          "text": "Request and analyze risk data using server-to-server calls.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.DeviceCheck/documentation/DeviceCheck/assessing-fraud-risk",
      "kind": "article",
      "role": "article",
      "title": "Assessing fraud risk",
      "type": "topic",
      "url": "/documentation/devicecheck/assessing-fraud-risk"
    },
    "doc://com.apple.DeviceCheck/documentation/DeviceCheck/establishing-your-app-s-integrity": {
      "abstract": [
        {
          "text": "Ensure that requests your server receives come from legitimate instances of your",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.DeviceCheck/documentation/DeviceCheck/establishing-your-app-s-integrity",
      "kind": "article",
      "role": "article",
      "title": "Establishing your app’s integrity",
      "type": "topic",
      "url": "/documentation/devicecheck/establishing-your-app-s-integrity"
    },
    "doc://com.apple.DeviceCheck/documentation/DeviceCheck/validating-apps-that-connect-to-your-server": {
      "abstract": [
        {
          "text": "Verify that connections to your server come from legitimate instances of your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.DeviceCheck/documentation/DeviceCheck/validating-apps-that-connect-to-your-server",
      "kind": "article",
      "role": "article",
      "title": "Validating apps that connect to your server",
      "type": "topic",
      "url": "/documentation/devicecheck/validating-apps-that-connect-to-your-server"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.devicecheck.appattest-environment": {
      "abstract": [
        {
          "text": "The environment for an app that uses the App Attest service to validate itself.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.devicecheck.appattest-environment",
      "kind": "symbol",
      "role": "symbol",
      "title": "App Attest Environment",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.devicecheck.appattest-environment"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "App-Attest",
      "generated": true,
      "identifiers": [
        "doc://com.apple.DeviceCheck/documentation/DeviceCheck/establishing-your-app-s-integrity",
        "doc://com.apple.DeviceCheck/documentation/DeviceCheck/validating-apps-that-connect-to-your-server",
        "doc://com.apple.DeviceCheck/documentation/DeviceCheck/assessing-fraud-risk",
        "doc://com.apple.DeviceCheck/documentation/DeviceCheck/DCAppAttestService",
        "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.devicecheck.appattest-environment"
      ],
      "title": "App Attest"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "App-Attest",
              "generated": true,
              "identifiers": [
                "doc://com.apple.DeviceCheck/documentation/DeviceCheck/establishing-your-app-s-integrity",
                "doc://com.apple.DeviceCheck/documentation/DeviceCheck/validating-apps-that-connect-to-your-server",
                "doc://com.apple.DeviceCheck/documentation/DeviceCheck/assessing-fraud-risk",
                "doc://com.apple.DeviceCheck/documentation/DeviceCheck/DCAppAttestService",
                "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.devicecheck.appattest-environment"
              ],
              "title": "App Attest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.DeviceCheck~1documentation~1DeviceCheck~1DCAppAttestService~1attestKey(_:clientDataHash:completionHandler:)/title",
          "value": "attestKey:clientDataHash:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.DeviceCheck~1documentation~1DeviceCheck~1DCAppAttestService~1attestKey(_:clientDataHash:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "attestKey:clientDataHash:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.DeviceCheck~1documentation~1DeviceCheck~1DCAppAttestService/title",
          "value": "DCAppAttestService"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.DeviceCheck~1documentation~1DeviceCheck~1DCAppAttestService/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DCAppAttestService"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.DeviceCheck~1documentation~1DeviceCheck~1DCAppAttestService/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DCAppAttestService"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/devicecheck/preparing-to-use-the-app-attest-service"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/devicecheck/preparing-to-use-the-app-attest-service"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
