{"kind":"symbol","identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolConfiguration-swift.class/init(pointSize:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uiimage/symbolconfiguration-swift.class/init(pointsize:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uiimage/symbolconfiguration-swift.class/init(pointsize:)"]}],"abstract":[{"text":"Creates a configuration object with the specified point-size information.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIImage","doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolConfiguration-swift.class"]]},"sections":[],"metadata":{"roleHeading":"Initializer","externalID":"c:objc(cs)UIImageSymbolConfiguration(cm)configurationWithPointSize:","platforms":[{"introducedAt":"13.0","deprecated":false,"name":"iOS","unavailable":false,"beta":false},{"introducedAt":"13.0","deprecated":false,"name":"iPadOS","unavailable":false,"beta":false},{"introducedAt":"13.1","deprecated":false,"name":"Mac Catalyst","unavailable":false,"beta":false},{"introducedAt":"13.0","deprecated":false,"name":"tvOS","unavailable":false,"beta":false},{"introducedAt":"1.0","deprecated":false,"name":"visionOS","unavailable":false,"beta":false},{"introducedAt":"6.0","deprecated":false,"name":"watchOS","unavailable":false,"beta":false}],"symbolKind":"init","navigatorTitle":[{"kind":"identifier","text":"configurationWithPointSize:"}],"fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"pointSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}],"modules":[{"name":"UIKit"}],"role":"symbol","title":"init(pointSize:)"},"seeAlsoSections":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolConfiguration-swift.class/init(pointSize:weight:)","doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolConfiguration-swift.class/init(pointSize:weight:scale:)","doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolConfiguration-swift.class/init(scale:)","doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolConfiguration-swift.class/init(textStyle:)","doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolConfiguration-swift.class/init(textStyle:scale:)","doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolConfiguration-swift.class/init(weight:)","doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolConfiguration-swift.class/init(font:)","doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolConfiguration-swift.class/init(font:scale:)","doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolScale","doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolWeight"],"anchor":"Creating-a-symbol-configuration","title":"Creating a symbol configuration","generated":true}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"pointSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","identifier":"doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS","watchOS"]}],"kind":"declarations"},{"parameters":[{"name":"pointSize","content":[{"inlineContent":[{"text":"The system font point size to use for the configuration.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"inlineContent":[{"text":"A new symbol configuration object with the specified information.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolConfiguration-swift.class/init(font:)":{"fragments":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"font","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIFont","text":"UIFont","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"configurationWithFont:","kind":"identifier"}],"title":"init(font:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolConfiguration-swift.class/init(font:)","type":"topic","url":"/documentation/uikit/uiimage/symbolconfiguration-swift.class/init(font:)","abstract":[{"type":"text","text":"Creates a configuration object with the specified font information."}]},"doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolConfiguration-swift.class/init(textStyle:scale:)":{"fragments":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"textStyle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"TextStyle","preciseIdentifier":"c:@T@UIFontTextStyle","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"scale","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"SymbolScale","preciseIdentifier":"c:@E@UIImageSymbolScale","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"/documentation/uikit/uiimage/symbolconfiguration-swift.class/init(textstyle:scale:)","navigatorTitle":[{"text":"configurationWithTextStyle:scale:","kind":"identifier"}],"title":"init(textStyle:scale:)","abstract":[{"type":"text","text":"Creates a configuration object with the specified font text style and scale information."}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolConfiguration-swift.class/init(textStyle:scale:)"},"doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolConfiguration-swift.class/init(weight:)":{"navigatorTitle":[{"text":"configurationWithWeight:","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolConfiguration-swift.class/init(weight:)","abstract":[{"type":"text","text":"Creates a configuration object with the specified weight information."}],"kind":"symbol","fragments":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"weight","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@UIImageSymbolWeight","text":"SymbolWeight","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"/documentation/uikit/uiimage/symbolconfiguration-swift.class/init(weight:)","title":"init(weight:)","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIImage":{"kind":"symbol","role":"symbol","title":"UIImage","navigatorTitle":[{"text":"UIImage","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIImage","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage","url":"/documentation/uikit/uiimage","abstract":[{"type":"text","text":"An object that manages image data in your app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolConfiguration-swift.class":{"kind":"symbol","role":"symbol","title":"UIImage.SymbolConfiguration","navigatorTitle":[{"text":"SymbolConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SymbolConfiguration","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolConfiguration-swift.class","url":"/documentation/uikit/uiimage/symbolconfiguration-swift.class","abstract":[{"type":"text","text":"An object that contains the specific font, size, style, and weight attributes to apply to a symbol image."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolConfiguration-swift.class/init(font:scale:)":{"abstract":[{"text":"Creates a configuration object with the specified font and scale information.","type":"text"}],"fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"font"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont","text":"UIFont"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scale"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIImageSymbolScale","text":"SymbolScale"},{"kind":"text","text":")"}],"role":"symbol","url":"/documentation/uikit/uiimage/symbolconfiguration-swift.class/init(font:scale:)","navigatorTitle":[{"kind":"identifier","text":"configurationWithFont:scale:"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolConfiguration-swift.class/init(font:scale:)","type":"topic","title":"init(font:scale:)","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolConfiguration-swift.class/init(pointSize:)":{"role":"symbol","abstract":[{"type":"text","text":"Creates a configuration object with the specified point-size information."}],"navigatorTitle":[{"text":"configurationWithPointSize:","kind":"identifier"}],"type":"topic","url":"/documentation/uikit/uiimage/symbolconfiguration-swift.class/init(pointsize:)","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolConfiguration-swift.class/init(pointSize:)","fragments":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pointSize","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(pointSize:)"},"doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolWeight":{"navigatorTitle":[{"text":"SymbolWeight","kind":"identifier"}],"title":"UIImage.SymbolWeight","url":"/documentation/uikit/uiimage/symbolweight","abstract":[{"text":"Constants that indicate which weight variant of a symbol image to use.","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SymbolWeight","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolWeight"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolConfiguration-swift.class/init(scale:)":{"type":"topic","navigatorTitle":[{"text":"configurationWithScale:","kind":"identifier"}],"fragments":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"scale","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@UIImageSymbolScale","text":"SymbolScale","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolConfiguration-swift.class/init(scale:)","abstract":[{"type":"text","text":"Creates a configuration object with the specified scale information."}],"url":"/documentation/uikit/uiimage/symbolconfiguration-swift.class/init(scale:)","title":"init(scale:)"},"doc://com.externally.resolved.symbol/c:@T@CGFloat":{"abstract":[{"type":"text","text":"The basic type for all floating-point values."}],"identifier":"doc://com.externally.resolved.symbol/c:@T@CGFloat","role":"symbol","url":"/documentation/corefoundation/cgfloat","kind":"symbol","type":"topic","title":"CGFloat"},"doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolConfiguration-swift.class/init(pointSize:weight:)":{"role":"symbol","abstract":[{"type":"text","text":"Creates a configuration object with the specified point-size and weight information."}],"navigatorTitle":[{"kind":"identifier","text":"configurationWithPointSize:weight:"}],"type":"topic","url":"/documentation/uikit/uiimage/symbolconfiguration-swift.class/init(pointsize:weight:)","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolConfiguration-swift.class/init(pointSize:weight:)","fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"pointSize"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"weight"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@UIImageSymbolWeight","kind":"typeIdentifier","text":"SymbolWeight"},{"kind":"text","text":")"}],"title":"init(pointSize:weight:)"},"doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolConfiguration-swift.class/init(textStyle:)":{"navigatorTitle":[{"kind":"identifier","text":"configurationWithTextStyle:"}],"title":"init(textStyle:)","url":"/documentation/uikit/uiimage/symbolconfiguration-swift.class/init(textstyle:)","abstract":[{"text":"Creates a configuration object with the specified font text style information.","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"textStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont","text":"UIFont"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@UIFontTextStyle","text":"TextStyle"},{"kind":"text","text":")"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolConfiguration-swift.class/init(textStyle:)"},"doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV":{"kind":"symbol","role":"symbol","title":"CGFloat","fragments":[{"kind":"text","text":"struct "},{"kind":"identifier","text":"CGFloat"}],"identifier":"doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV","url":"/documentation/corefoundation/cgfloat","abstract":[{"type":"text","text":"The basic type for floating-point scalar values in Core Graphics and related frameworks."}],"type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolConfiguration-swift.class/init(pointSize:weight:scale:)":{"type":"topic","url":"/documentation/uikit/uiimage/symbolconfiguration-swift.class/init(pointsize:weight:scale:)","navigatorTitle":[{"kind":"identifier","text":"configurationWithPointSize:weight:scale:"}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolConfiguration-swift.class/init(pointSize:weight:scale:)","kind":"symbol","abstract":[{"type":"text","text":"Creates a configuration object with the specified point-size, weight, and scale information."}],"fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"pointSize"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"weight"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@UIImageSymbolWeight","kind":"typeIdentifier","text":"SymbolWeight"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scale"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@UIImageSymbolScale","kind":"typeIdentifier","text":"SymbolScale"},{"kind":"text","text":")"}],"title":"init(pointSize:weight:scale:)"},"doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolScale":{"type":"topic","navigatorTitle":[{"text":"SymbolScale","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SymbolScale"}],"kind":"symbol","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolScale","abstract":[{"text":"Constants that indicate which scale variant of a symbol image to use.","type":"text"}],"url":"/documentation/uikit/uiimage/symbolscale","title":"UIImage.SymbolScale"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"introducedAt":"13.0","deprecated":false,"beta":false,"unavailable":false,"name":"iOS"},{"introducedAt":"13.0","deprecated":false,"beta":false,"unavailable":false,"name":"iPadOS"},{"introducedAt":"13.1","deprecated":false,"beta":false,"unavailable":false,"name":"Mac Catalyst"},{"introducedAt":"13.0","deprecated":false,"beta":false,"unavailable":false,"name":"tvOS"},{"introducedAt":"1.0","deprecated":false,"beta":false,"unavailable":false,"name":"visionOS"},{"introducedAt":"6.0","deprecated":false,"beta":false,"unavailable":false,"name":"watchOS"}]},{"path":"/metadata/roleHeading","op":"replace","value":"Type Method"},{"path":"/metadata/title","op":"replace","value":"configurationWithPointSize:"},{"path":"/metadata/symbolKind","op":"replace","value":"method"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"configurationWithPointSize:","kind":"identifier"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolConfiguration-swift.class"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"title":"Creating a symbol configuration","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolConfiguration-swift.class/init(pointSize:weight:)","doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolConfiguration-swift.class/init(pointSize:weight:scale:)","doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolConfiguration-swift.class/init(scale:)","doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolConfiguration-swift.class/init(textStyle:)","doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolConfiguration-swift.class/init(textStyle:scale:)","doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolConfiguration-swift.class/init(weight:)","doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolConfiguration-swift.class/init(font:)","doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolConfiguration-swift.class/init(font:scale:)","doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolScale","doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolWeight"],"generated":true,"anchor":"Creating-a-symbol-configuration"}]},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"configurationWithPointSize:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"c:@T@CGFloat","identifier":"doc://com.externally.resolved.symbol/c:@T@CGFloat"},{"kind":"text","text":") "},{"kind":"internalParam","text":"pointSize"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS","watchOS"]}],"kind":"declarations"}},{"value":{"parameters":[{"name":"pointSize","content":[{"inlineContent":[{"type":"text","text":"The system font point size to use for the configuration."}],"type":"paragraph"}]}],"kind":"parameters"},"path":"/primaryContentSections/1","op":"replace"},{"path":"/primaryContentSections/2","op":"replace","value":{"content":[{"anchor":"return-value","type":"heading","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"text":"A new symbol configuration object with the specified information.","type":"text"}]}],"kind":"content"}},{"value":"configurationWithFont:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolConfiguration-swift.class~1init(font:)/title","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"text":"configurationWithFont:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolConfiguration-swift.class~1init(font:)/fragments","op":"replace"},{"value":"configurationWithTextStyle:scale:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolConfiguration-swift.class~1init(textStyle:scale:)/title","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"configurationWithTextStyle:scale:"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolConfiguration-swift.class~1init(textStyle:scale:)/fragments","op":"replace"},{"value":"configurationWithWeight:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolConfiguration-swift.class~1init(weight:)/title","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"configurationWithWeight:"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolConfiguration-swift.class~1init(weight:)/fragments","op":"replace"},{"value":"UIImage","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/title","op":"replace"},{"value":[{"text":"UIImage","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/fragments","op":"replace"},{"value":[{"text":"UIImage","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/navigatorTitle","op":"replace"},{"value":"UIImageSymbolConfiguration","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolConfiguration-swift.class/title","op":"replace"},{"value":[{"kind":"identifier","text":"UIImageSymbolConfiguration"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolConfiguration-swift.class/fragments","op":"replace"},{"value":[{"text":"UIImageSymbolConfiguration","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolConfiguration-swift.class/navigatorTitle","op":"replace"},{"value":"configurationWithFont:scale:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolConfiguration-swift.class~1init(font:scale:)/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"configurationWithFont:scale:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolConfiguration-swift.class~1init(font:scale:)/fragments","op":"replace"},{"value":"configurationWithPointSize:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolConfiguration-swift.class~1init(pointSize:)/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"configurationWithPointSize:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolConfiguration-swift.class~1init(pointSize:)/fragments","op":"replace"},{"value":"UIImageSymbolWeight","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolWeight/title","op":"replace"},{"value":[{"kind":"identifier","text":"UIImageSymbolWeight"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolWeight/fragments","op":"replace"},{"value":[{"text":"UIImageSymbolWeight","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolWeight/navigatorTitle","op":"replace"},{"value":"configurationWithScale:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolConfiguration-swift.class~1init(scale:)/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"configurationWithScale:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolConfiguration-swift.class~1init(scale:)/fragments","op":"replace"},{"value":"configurationWithPointSize:weight:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolConfiguration-swift.class~1init(pointSize:weight:)/title","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"configurationWithPointSize:weight:"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolConfiguration-swift.class~1init(pointSize:weight:)/fragments","op":"replace"},{"value":"configurationWithTextStyle:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolConfiguration-swift.class~1init(textStyle:)/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"configurationWithTextStyle:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolConfiguration-swift.class~1init(textStyle:)/fragments","op":"replace"},{"value":"configurationWithPointSize:weight:scale:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolConfiguration-swift.class~1init(pointSize:weight:scale:)/title","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"configurationWithPointSize:weight:scale:"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolConfiguration-swift.class~1init(pointSize:weight:scale:)/fragments","op":"replace"},{"value":"UIImageSymbolScale","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolScale/title","op":"replace"},{"value":[{"text":"UIImageSymbolScale","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolScale/fragments","op":"replace"},{"value":[{"text":"UIImageSymbolScale","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolScale/navigatorTitle","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}