{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit",
        "doc://com.apple.passkit/documentation/PassKit/AsyncShareablePassConfiguration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/AsyncShareablePassConfiguration/init(metadata:action:content:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:16_PassKit_SwiftUI014AsyncShareableA13ConfigurationV8metadata6action7contentACyxGSaySo011PKShareableA8MetadataCG_So05PKAddfaG13PrimaryActionVxAC6ResultOyx_Gctcfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "metadata"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)PKShareablePassMetadata",
        "text": "PKShareablePassMetadata"
      },
      {
        "kind": "text",
        "text": "], "
      },
      {
        "kind": "externalParam",
        "text": "action"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@PKAddShareablePassConfigurationPrimaryAction",
        "text": "PKAddShareablePassConfigurationPrimaryAction"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "content"
      },
      {
        "kind": "text",
        "text": ": ("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:16_PassKit_SwiftUI014AsyncShareableA13ConfigurationV",
        "text": "AsyncShareablePassConfiguration"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "text": "Content"
      },
      {
        "kind": "text",
        "text": ">."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:16_PassKit_SwiftUI014AsyncShareableA13ConfigurationV6ResultO",
        "text": "Result"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "text": "Content"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "PassKit",
        "relatedModules": [
          "SwiftUI"
        ]
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(metadata:action:content:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "nonisolated"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "metadata"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.apple.passkit/documentation/PassKit/PKShareablePassMetadata",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)PKShareablePassMetadata",
              "text": "PKShareablePassMetadata"
            },
            {
              "kind": "text",
              "text": "], "
            },
            {
              "kind": "externalParam",
              "text": "action"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddShareablePassConfigurationPrimaryAction",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@PKAddShareablePassConfigurationPrimaryAction",
              "text": "PKAddShareablePassConfigurationPrimaryAction"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:7SwiftUI11ViewBuilderV",
              "kind": "attribute",
              "preciseIdentifier": "s:7SwiftUI11ViewBuilderV",
              "text": "ViewBuilder"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "externalParam",
              "text": "content"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "@escaping"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "identifier": "doc://com.apple.passkit/documentation/PassKit/AsyncShareablePassConfiguration",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:16_PassKit_SwiftUI014AsyncShareableA13ConfigurationV",
              "text": "AsyncShareablePassConfiguration"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "kind": "typeIdentifier",
              "text": "Content"
            },
            {
              "kind": "text",
              "text": ">."
            },
            {
              "identifier": "doc://com.apple.passkit/documentation/PassKit/AsyncShareablePassConfiguration/Result",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:16_PassKit_SwiftUI014AsyncShareableA13ConfigurationV6ResultO",
              "text": "Result"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "kind": "typeIdentifier",
              "text": "Content"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/AsyncShareablePassConfiguration": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AsyncShareablePassConfiguration"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/AsyncShareablePassConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AsyncShareablePassConfiguration"
        }
      ],
      "role": "symbol",
      "title": "AsyncShareablePassConfiguration",
      "type": "topic",
      "url": "/documentation/passkit/asyncshareablepassconfiguration"
    },
    "doc://com.apple.passkit/documentation/PassKit/AsyncShareablePassConfiguration/Result": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Result"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/AsyncShareablePassConfiguration/Result",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Result"
        }
      ],
      "role": "symbol",
      "title": "AsyncShareablePassConfiguration.Result",
      "type": "topic",
      "url": "/documentation/passkit/asyncshareablepassconfiguration/result"
    },
    "doc://com.apple.passkit/documentation/PassKit/AsyncShareablePassConfiguration/init(metadata:action:content:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "metadata"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKShareablePassMetadata",
          "text": "PKShareablePassMetadata"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "action"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKAddShareablePassConfigurationPrimaryAction",
          "text": "PKAddShareablePassConfigurationPrimaryAction"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "content"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:16_PassKit_SwiftUI014AsyncShareableA13ConfigurationV",
          "text": "AsyncShareablePassConfiguration"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": ">."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:16_PassKit_SwiftUI014AsyncShareableA13ConfigurationV6ResultO",
          "text": "Result"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/AsyncShareablePassConfiguration/init(metadata:action:content:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(metadata:action:content:)",
      "type": "topic",
      "url": "/documentation/passkit/asyncshareablepassconfiguration/init(metadata:action:content:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddShareablePassConfigurationPrimaryAction": {
      "abstract": [
        {
          "text": "The kind of add action that the system performs with a pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKAddShareablePassConfigurationPrimaryAction"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddShareablePassConfigurationPrimaryAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAddShareablePassConfigurationPrimaryAction"
        }
      ],
      "role": "symbol",
      "title": "PKAddShareablePassConfigurationPrimaryAction",
      "type": "topic",
      "url": "/documentation/passkit/pkaddshareablepassconfigurationprimaryaction"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKShareablePassMetadata": {
      "abstract": [
        {
          "text": "Information that you use to configure the sharing sheet for a pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKShareablePassMetadata"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKShareablePassMetadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKShareablePassMetadata"
        }
      ],
      "role": "symbol",
      "title": "PKShareablePassMetadata",
      "type": "topic",
      "url": "/documentation/passkit/pkshareablepassmetadata"
    },
    "doc://com.externally.resolved.symbol/s:7SwiftUI11ViewBuilderV": {
      "abstract": [
        {
          "text": "A custom parameter attribute that constructs views from closures.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@resultBuilder"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ViewBuilder"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:7SwiftUI11ViewBuilderV",
      "kind": "symbol",
      "role": "symbol",
      "title": "ViewBuilder",
      "type": "topic",
      "url": "/documentation/SwiftUI/ViewBuilder"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-the-configuration",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/AsyncShareablePassConfiguration/Result"
      ],
      "title": "Creating the configuration"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareablePassMetadata/title",
          "value": "PKShareablePassMetadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareablePassMetadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKShareablePassMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareablePassMetadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKShareablePassMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddShareablePassConfigurationPrimaryAction/title",
          "value": "PKAddShareablePassConfigurationPrimaryAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddShareablePassConfigurationPrimaryAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddShareablePassConfigurationPrimaryAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddShareablePassConfigurationPrimaryAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddShareablePassConfigurationPrimaryAction"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/asyncshareablepassconfiguration/init(metadata:action:content:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
