{
  "abstract": [
    {
      "text": "The calendar’s type.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.eventkit/documentation/EventKit",
        "doc://com.apple.eventkit/documentation/EventKit/EKCalendar"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/type"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)EKCalendar(py)type",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "type"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@EKCalendarType",
        "text": "EKCalendarType"
      }
    ],
    "modules": [
      {
        "name": "EventKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "type"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "type"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "type"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendarType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@EKCalendarType",
              "text": "EKCalendarType"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "CalDAV-subscribed calendars are of type ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendarType/calDAV",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " with ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/isSubscribed",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " set to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.eventkit/documentation/EventKit": {
      "abstract": [
        {
          "text": "Create, view, and edit calendar and reminder events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit",
      "kind": "symbol",
      "role": "collection",
      "title": "EventKit",
      "type": "topic",
      "url": "/documentation/eventkit"
    },
    "doc://com.apple.eventkit/documentation/EventKit/DATETIME_COMPONENTS_DO_NOT_USE()": {
      "abstract": [
        {
          "text": "A deprecated function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DATETIME_COMPONENTS_DO_NOT_USE"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/DATETIME_COMPONENTS_DO_NOT_USE()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DATETIME_COMPONENTS_DO_NOT_USE"
        }
      ],
      "role": "symbol",
      "title": "DATETIME_COMPONENTS_DO_NOT_USE()",
      "type": "topic",
      "url": "/documentation/eventkit/datetime_components_do_not_use()"
    },
    "doc://com.apple.eventkit/documentation/EventKit/DATE_COMPONENTS_DO_NOT_USE()": {
      "abstract": [
        {
          "text": "A deprecated function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DATE_COMPONENTS_DO_NOT_USE"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/DATE_COMPONENTS_DO_NOT_USE()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DATE_COMPONENTS_DO_NOT_USE"
        }
      ],
      "role": "symbol",
      "title": "DATE_COMPONENTS_DO_NOT_USE()",
      "type": "topic",
      "url": "/documentation/eventkit/date_components_do_not_use()"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKCalendar": {
      "abstract": [
        {
          "text": "A class that represents a calendar in EventKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKCalendar"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKCalendar"
        }
      ],
      "role": "symbol",
      "title": "EKCalendar",
      "type": "topic",
      "url": "/documentation/eventkit/ekcalendar"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/allowedEntityTypes": {
      "abstract": [
        {
          "text": "The entity types this calendar can contain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowedEntityTypes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKEntityMask",
          "text": "EKEntityMask"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/allowedEntityTypes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowedEntityTypes"
        }
      ],
      "role": "symbol",
      "title": "allowedEntityTypes",
      "type": "topic",
      "url": "/documentation/eventkit/ekcalendar/allowedentitytypes"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/allowsContentModifications": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether you can add, edit, and delete items in the calendar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsContentModifications"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/allowsContentModifications",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowsContentModifications"
        }
      ],
      "role": "symbol",
      "title": "allowsContentModifications",
      "type": "topic",
      "url": "/documentation/eventkit/ekcalendar/allowscontentmodifications"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/calendarIdentifier": {
      "abstract": [
        {
          "text": "A unique identifier for the calendar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "calendarIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/calendarIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "calendarIdentifier"
        }
      ],
      "role": "symbol",
      "title": "calendarIdentifier",
      "type": "topic",
      "url": "/documentation/eventkit/ekcalendar/calendaridentifier"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/cgColor": {
      "abstract": [
        {
          "text": "The calendar’s color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cgColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGColorRef",
          "text": "CGColor"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/cgColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGColor"
        }
      ],
      "role": "symbol",
      "title": "cgColor",
      "type": "topic",
      "url": "/documentation/eventkit/ekcalendar/cgcolor"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/color": {
      "abstract": [
        {
          "text": "The calendar’s color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "color"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/color",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "color"
        }
      ],
      "role": "symbol",
      "title": "color",
      "type": "topic",
      "url": "/documentation/eventkit/ekcalendar/color"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/isImmutable": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the calendar’s properties can be edited or deleted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isImmutable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/isImmutable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "immutable"
        }
      ],
      "role": "symbol",
      "title": "isImmutable",
      "type": "topic",
      "url": "/documentation/eventkit/ekcalendar/isimmutable"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/isSubscribed": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the calendar is a subscribed calendar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isSubscribed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/isSubscribed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subscribed"
        }
      ],
      "role": "symbol",
      "title": "isSubscribed",
      "type": "topic",
      "url": "/documentation/eventkit/ekcalendar/issubscribed"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/source": {
      "abstract": [
        {
          "text": "The source object representing the account to which this calendar belongs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "source"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)EKSource",
          "text": "EKSource"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/source",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "source"
        }
      ],
      "role": "symbol",
      "title": "source",
      "type": "topic",
      "url": "/documentation/eventkit/ekcalendar/source"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/supportedEventAvailabilities": {
      "abstract": [
        {
          "text": "The event availability settings supported by this calendar, as indicated by a bitmask.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportedEventAvailabilities"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKCalendarEventAvailabilityMask",
          "text": "EKCalendarEventAvailabilityMask"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/supportedEventAvailabilities",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportedEventAvailabilities"
        }
      ],
      "role": "symbol",
      "title": "supportedEventAvailabilities",
      "type": "topic",
      "url": "/documentation/eventkit/ekcalendar/supportedeventavailabilities"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/title": {
      "abstract": [
        {
          "text": "The calendar’s title.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "title"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/title",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "title"
        }
      ],
      "role": "symbol",
      "title": "title",
      "type": "topic",
      "url": "/documentation/eventkit/ekcalendar/title"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/type": {
      "abstract": [
        {
          "text": "The calendar’s type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKCalendarType",
          "text": "EKCalendarType"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "type"
        }
      ],
      "role": "symbol",
      "title": "type",
      "type": "topic",
      "url": "/documentation/eventkit/ekcalendar/type"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKCalendarEventAvailabilityMask": {
      "abstract": [
        {
          "text": "A bitmask indicating the event availability settings that the calendar can support.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKCalendarEventAvailabilityMask"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendarEventAvailabilityMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKCalendarEventAvailabilityMask"
        }
      ],
      "role": "symbol",
      "title": "EKCalendarEventAvailabilityMask",
      "type": "topic",
      "url": "/documentation/eventkit/ekcalendareventavailabilitymask"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKCalendarType": {
      "abstract": [
        {
          "text": "Possible calendar types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKCalendarType"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendarType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKCalendarType"
        }
      ],
      "role": "symbol",
      "title": "EKCalendarType",
      "type": "topic",
      "url": "/documentation/eventkit/ekcalendartype"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKCalendarType/calDAV": {
      "abstract": [
        {
          "text": "A CalDAV or iCloud calendar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "calDAV"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendarType/calDAV",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKCalendarTypeCalDAV"
        }
      ],
      "role": "symbol",
      "title": "EKCalendarType.calDAV",
      "type": "topic",
      "url": "/documentation/eventkit/ekcalendartype/caldav"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-Calendar-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.eventkit/documentation/EventKit/EKCalendarType",
        "doc://com.apple.eventkit/documentation/EventKit/EKCalendarEventAvailabilityMask",
        "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/allowsContentModifications",
        "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/cgColor",
        "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/color",
        "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/isImmutable",
        "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/title",
        "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/allowedEntityTypes",
        "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/source",
        "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/isSubscribed",
        "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/supportedEventAvailabilities",
        "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/calendarIdentifier",
        "doc://com.apple.eventkit/documentation/EventKit/DATETIME_COMPONENTS_DO_NOT_USE()",
        "doc://com.apple.eventkit/documentation/EventKit/DATE_COMPONENTS_DO_NOT_USE()"
      ],
      "title": "Accessing Calendar Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "type"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.eventkit/documentation/EventKit",
                "doc://com.apple.eventkit/documentation/EventKit/EKCalendar"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-Calendar-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.eventkit/documentation/EventKit/EKCalendarType",
                "doc://com.apple.eventkit/documentation/EventKit/EKCalendarEventAvailabilityMask",
                "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/allowsContentModifications",
                "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/cgColor",
                "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/color",
                "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/isImmutable",
                "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/title",
                "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/allowedEntityTypes",
                "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/source",
                "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/isSubscribed",
                "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/supportedEventAvailabilities",
                "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/calendarIdentifier",
                "doc://com.apple.eventkit/documentation/EventKit/DATETIME_COMPONENTS_DO_NOT_USE()",
                "doc://com.apple.eventkit/documentation/EventKit/DATE_COMPONENTS_DO_NOT_USE()"
              ],
              "title": "Accessing Calendar Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendarType",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@EKCalendarType",
                    "text": "EKCalendarType"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "type"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendar~1calendarIdentifier/title",
          "value": "calendarIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendar~1calendarIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "calendarIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendar~1isImmutable/title",
          "value": "immutable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendar~1isImmutable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "immutable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendarType~1calDAV/title",
          "value": "EKCalendarTypeCalDAV"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendarType~1calDAV/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKCalendarTypeCalDAV"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendar~1supportedEventAvailabilities/title",
          "value": "supportedEventAvailabilities"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendar~1supportedEventAvailabilities/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportedEventAvailabilities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendarType/title",
          "value": "EKCalendarType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendarType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKCalendarType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendarType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKCalendarType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendar~1cgColor/title",
          "value": "CGColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendar~1cgColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendar~1isSubscribed/title",
          "value": "subscribed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendar~1isSubscribed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "subscribed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendar~1source/title",
          "value": "source"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendar~1source/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "source"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendar~1type/title",
          "value": "type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendar~1type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendar~1allowedEntityTypes/title",
          "value": "allowedEntityTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendar~1allowedEntityTypes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowedEntityTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1DATETIME_COMPONENTS_DO_NOT_USE()/title",
          "value": "DATETIME_COMPONENTS_DO_NOT_USE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1DATETIME_COMPONENTS_DO_NOT_USE()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DATETIME_COMPONENTS_DO_NOT_USE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendar~1color/title",
          "value": "color"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendar~1color/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "color"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendar~1title/title",
          "value": "title"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendar~1title/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "title"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1DATE_COMPONENTS_DO_NOT_USE()/title",
          "value": "DATE_COMPONENTS_DO_NOT_USE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1DATE_COMPONENTS_DO_NOT_USE()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DATE_COMPONENTS_DO_NOT_USE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendar~1allowsContentModifications/title",
          "value": "allowsContentModifications"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendar~1allowsContentModifications/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowsContentModifications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendarEventAvailabilityMask/title",
          "value": "EKCalendarEventAvailabilityMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendarEventAvailabilityMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKCalendarEventAvailabilityMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendarEventAvailabilityMask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKCalendarEventAvailabilityMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendar/title",
          "value": "EKCalendar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKCalendar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendar/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKCalendar"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/eventkit/ekcalendar/type"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/eventkit/ekcalendar/type"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
