{
  "abstract": [
    {
      "text": "Provides an absolute time equivalent to the argument continuous time.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sensorkit/documentation/SensorKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.sensorkit/documentation/SensorKit/SRAbsoluteTimeFromContinuousTime"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@SRAbsoluteTimeFromContinuousTime",
    "fragments": [
      {
        "kind": "identifier",
        "text": "SRAbsoluteTimeFromContinuousTime"
      }
    ],
    "modules": [
      {
        "name": "SensorKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SRAbsoluteTimeFromContinuousTime"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "SRAbsoluteTimeFromContinuousTime"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRAbsoluteTime",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SRAbsoluteTime",
              "text": "SRAbsoluteTime"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SRAbsoluteTimeFromContinuousTime"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@uint64_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@uint64_t",
              "text": "uint64_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "cont"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The continuous time to convert.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "cont"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An absolute time equivalent to the argument continuous time.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit": {
      "abstract": [
        {
          "text": "Retrieve data and derived metrics from sensors on an iPhone, or paired Apple Watch.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SensorKit",
      "type": "topic",
      "url": "/documentation/sensorkit"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRAbsoluteTime": {
      "abstract": [
        {
          "text": "A value that describes when the system records the data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRAbsoluteTime"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRAbsoluteTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRAbsoluteTime"
        }
      ],
      "role": "symbol",
      "title": "SRAbsoluteTime",
      "type": "topic",
      "url": "/documentation/sensorkit/srabsolutetime"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRAbsoluteTime/current()": {
      "abstract": [
        {
          "text": "Provides the current absolute time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "current"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRAbsoluteTime",
          "text": "SRAbsoluteTime"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRAbsoluteTime/current()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRAbsoluteTimeGetCurrent"
        }
      ],
      "role": "symbol",
      "title": "current()",
      "type": "topic",
      "url": "/documentation/sensorkit/srabsolutetime/current()"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRAbsoluteTime/toCFAbsoluteTime()": {
      "abstract": [
        {
          "text": "Converts an absolute time to a core-foundation absolute time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "toCFAbsoluteTime"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAbsoluteTime",
          "text": "CFAbsoluteTime"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRAbsoluteTime/toCFAbsoluteTime()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRAbsoluteTimeToCFAbsoluteTime"
        }
      ],
      "role": "symbol",
      "title": "toCFAbsoluteTime()",
      "type": "topic",
      "url": "/documentation/sensorkit/srabsolutetime/tocfabsolutetime()"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRAbsoluteTimeFromCFAbsoluteTime": {
      "abstract": [
        {
          "text": "Provides an absolute time equivalent to the argument core-foundation absolute time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SRAbsoluteTimeFromCFAbsoluteTime"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRAbsoluteTimeFromCFAbsoluteTime",
      "kind": "symbol",
      "role": "symbol",
      "title": "SRAbsoluteTimeFromCFAbsoluteTime",
      "type": "topic",
      "url": "/documentation/sensorkit/srabsolutetimefromcfabsolutetime"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRAbsoluteTimeFromContinuousTime": {
      "abstract": [
        {
          "text": "Provides an absolute time equivalent to the argument continuous time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SRAbsoluteTimeFromContinuousTime"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRAbsoluteTimeFromContinuousTime",
      "kind": "symbol",
      "role": "symbol",
      "title": "SRAbsoluteTimeFromContinuousTime",
      "type": "topic",
      "url": "/documentation/sensorkit/srabsolutetimefromcontinuoustime"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRFetchRequest/from": {
      "abstract": [
        {
          "text": "Fetches sample information that occurs after this time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRAbsoluteTime",
          "text": "SRAbsoluteTime"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRFetchRequest/from",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "from"
        }
      ],
      "role": "symbol",
      "title": "from",
      "type": "topic",
      "url": "/documentation/sensorkit/srfetchrequest/from"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRFetchRequest/to": {
      "abstract": [
        {
          "text": "Fetches sample information that occurs before this time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRAbsoluteTime",
          "text": "SRAbsoluteTime"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRFetchRequest/to",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "to"
        }
      ],
      "role": "symbol",
      "title": "to",
      "type": "topic",
      "url": "/documentation/sensorkit/srfetchrequest/to"
    },
    "doc://com.externally.resolved.symbol/c:@T@uint64_t": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@uint64_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "uint64_t",
      "type": "topic",
      "url": "/documentation/kernel/uint64_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Defining-the-Time-Range",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRFetchRequest/from",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRFetchRequest/to",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRAbsoluteTime",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRAbsoluteTime/current()",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRAbsoluteTimeFromCFAbsoluteTime",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRAbsoluteTime/toCFAbsoluteTime()"
      ],
      "title": "Defining the Time Range"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAbsoluteTime~1toCFAbsoluteTime()/title",
          "value": "SRAbsoluteTimeToCFAbsoluteTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAbsoluteTime~1toCFAbsoluteTime()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRAbsoluteTimeToCFAbsoluteTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAbsoluteTime/title",
          "value": "SRAbsoluteTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAbsoluteTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRAbsoluteTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAbsoluteTime/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRAbsoluteTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAbsoluteTime~1current()/title",
          "value": "SRAbsoluteTimeGetCurrent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAbsoluteTime~1current()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRAbsoluteTimeGetCurrent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFetchRequest~1from/title",
          "value": "from"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFetchRequest~1from/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "from"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFetchRequest~1to/title",
          "value": "to"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFetchRequest~1to/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "to"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/sensorkit/srabsolutetimefromcontinuoustime"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
