{
  "abstract": [
    {
      "text": "The frequency and relative duration that the user uses their device, particular Apple apps, or websites.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sensorkit/documentation/SensorKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SRDeviceUsageReport",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SRDeviceUsageReport"
      }
    ],
    "modules": [
      {
        "name": "SensorKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SRDeviceUsageReport"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "SRDeviceUsageReport"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SRDeviceUsageReport"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/deviceUsageReport",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " sensor provides this class as its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRFetchResult/sample",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " type.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit": {
      "abstract": [
        {
          "text": "Retrieve data and derived metrics from sensors on an iPhone, or paired Apple Watch.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SensorKit",
      "type": "topic",
      "url": "/documentation/sensorkit"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample": {
      "abstract": [
        {
          "text": "The amount of ambient light in the user’s environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRAmbientLightSample"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRAmbientLightSample"
        }
      ],
      "role": "symbol",
      "title": "SRAmbientLightSample",
      "type": "topic",
      "url": "/documentation/sensorkit/srambientlightsample"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport": {
      "abstract": [
        {
          "text": "The frequency and relative duration that the user uses their device, particular Apple apps, or websites.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRDeviceUsageReport"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRDeviceUsageReport"
        }
      ],
      "role": "symbol",
      "title": "SRDeviceUsageReport",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/ApplicationUsage": {
      "abstract": [
        {
          "text": "An object that describes the user’s app activity over a period of time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ApplicationUsage"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/ApplicationUsage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ApplicationUsage"
        }
      ],
      "role": "symbol",
      "title": "SRDeviceUsageReport.ApplicationUsage",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/applicationusage"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey": {
      "abstract": [
        {
          "text": "Categories of apps or websites that the user uses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CategoryKey"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CategoryKey"
        }
      ],
      "role": "symbol",
      "title": "SRDeviceUsageReport.CategoryKey",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/categorykey"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/NotificationUsage": {
      "abstract": [
        {
          "text": "An object that describes notification frequency and the manner in which the user interacts with notifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NotificationUsage"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/NotificationUsage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NotificationUsage"
        }
      ],
      "role": "symbol",
      "title": "SRDeviceUsageReport.NotificationUsage",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/notificationusage"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/WebUsage": {
      "abstract": [
        {
          "text": "An object that describes a user’s website usage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebUsage"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/WebUsage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebUsage"
        }
      ],
      "role": "symbol",
      "title": "SRDeviceUsageReport.WebUsage",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/webusage"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/applicationUsageByCategory": {
      "abstract": [
        {
          "text": "The usage time of apps per category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationUsageByCategory"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
          "text": "CategoryKey"
        },
        {
          "kind": "text",
          "text": " : ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRApplicationUsage",
          "text": "ApplicationUsage"
        },
        {
          "kind": "text",
          "text": "]]"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/applicationUsageByCategory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applicationUsageByCategory"
        }
      ],
      "role": "symbol",
      "title": "applicationUsageByCategory",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/applicationusagebycategory"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/duration": {
      "abstract": [
        {
          "text": "The duration that the report spans.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "duration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/duration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "duration"
        }
      ],
      "role": "symbol",
      "title": "duration",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/duration"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/notificationUsageByCategory": {
      "abstract": [
        {
          "text": "The frequency of notifications per category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notificationUsageByCategory"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
          "text": "CategoryKey"
        },
        {
          "kind": "text",
          "text": " : ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRNotificationUsage",
          "text": "NotificationUsage"
        },
        {
          "kind": "text",
          "text": "]]"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/notificationUsageByCategory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "notificationUsageByCategory"
        }
      ],
      "role": "symbol",
      "title": "notificationUsageByCategory",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/notificationusagebycategory"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/totalScreenWakes": {
      "abstract": [
        {
          "text": "The total number of screen wakes for the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "totalScreenWakes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/totalScreenWakes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "totalScreenWakes"
        }
      ],
      "role": "symbol",
      "title": "totalScreenWakes",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/totalscreenwakes"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/totalUnlockDuration": {
      "abstract": [
        {
          "text": "The duration of time the device is in an unlocked state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "totalUnlockDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/totalUnlockDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "totalUnlockDuration"
        }
      ],
      "role": "symbol",
      "title": "totalUnlockDuration",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/totalunlockduration"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/totalUnlocks": {
      "abstract": [
        {
          "text": "The total number of unlocks for the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "totalUnlocks"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/totalUnlocks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "totalUnlocks"
        }
      ],
      "role": "symbol",
      "title": "totalUnlocks",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/totalunlocks"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/version": {
      "abstract": [
        {
          "text": "The version of the algorithm that the system uses to generate the report.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "version"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/version",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "version"
        }
      ],
      "role": "symbol",
      "title": "version",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/version"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/webUsageByCategory": {
      "abstract": [
        {
          "text": "The amount of time the user accesses domains per category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "webUsageByCategory"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
          "text": "CategoryKey"
        },
        {
          "kind": "text",
          "text": " : ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRWebUsage",
          "text": "WebUsage"
        },
        {
          "kind": "text",
          "text": "]]"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/webUsageByCategory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "webUsageByCategory"
        }
      ],
      "role": "symbol",
      "title": "webUsageByCategory",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/webusagebycategory"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRFetchResult/sample": {
      "abstract": [
        {
          "text": "A recording that the sensor reader fetches.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sample"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "SampleType"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRFetchResult/sample",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sample"
        }
      ],
      "role": "symbol",
      "title": "sample",
      "type": "topic",
      "url": "/documentation/sensorkit/srfetchresult/sample"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics": {
      "abstract": [
        {
          "text": "The configuration of a device’s keyboard and its usage patterns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRKeyboardMetrics"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRKeyboardMetrics"
        }
      ],
      "role": "symbol",
      "title": "SRKeyboardMetrics",
      "type": "topic",
      "url": "/documentation/sensorkit/srkeyboardmetrics"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRMediaEvent": {
      "abstract": [
        {
          "text": "A user interaction with a media object, such as an image or a video.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRMediaEvent"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRMediaEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRMediaEvent"
        }
      ],
      "role": "symbol",
      "title": "SRMediaEvent",
      "type": "topic",
      "url": "/documentation/sensorkit/srmediaevent"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRMessagesUsageReport": {
      "abstract": [
        {
          "text": "An object that describes the user’s Messages app activity over a period of time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRMessagesUsageReport"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRMessagesUsageReport",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRMessagesUsageReport"
        }
      ],
      "role": "symbol",
      "title": "SRMessagesUsageReport",
      "type": "topic",
      "url": "/documentation/sensorkit/srmessagesusagereport"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRPhoneUsageReport": {
      "abstract": [
        {
          "text": "An object that describes the user’s phone activity over a period of time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRPhoneUsageReport"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRPhoneUsageReport",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRPhoneUsageReport"
        }
      ],
      "role": "symbol",
      "title": "SRPhoneUsageReport",
      "type": "topic",
      "url": "/documentation/sensorkit/srphoneusagereport"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/deviceUsageReport": {
      "abstract": [
        {
          "text": "A sensor that provides information about device usage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceUsageReport"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRSensor",
          "text": "SRSensor"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/deviceUsageReport",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorDeviceUsageReport"
        }
      ],
      "role": "symbol",
      "title": "deviceUsageReport",
      "type": "topic",
      "url": "/documentation/sensorkit/srsensor/deviceusagereport"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRVisit": {
      "abstract": [
        {
          "text": "The user’s progress in their daily travel routine.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRVisit"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRVisit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRVisit"
        }
      ],
      "role": "symbol",
      "title": "SRVisit",
      "type": "topic",
      "url": "/documentation/sensorkit/srvisit"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRWristDetection": {
      "abstract": [
        {
          "text": "The configuration of a watch on the wearer’s wrist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRWristDetection"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRWristDetection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRWristDetection"
        }
      ],
      "role": "symbol",
      "title": "SRWristDetection",
      "type": "topic",
      "url": "/documentation/sensorkit/srwristdetection"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Interpreting-data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRMediaEvent",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRMessagesUsageReport",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRPhoneUsageReport",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRVisit",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRWristDetection"
      ],
      "title": "Interpreting data"
    }
  ],
  "topicSections": [
    {
      "anchor": "Summarizing-Device-Use",
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/duration",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/totalScreenWakes",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/totalUnlocks",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/totalUnlockDuration"
      ],
      "title": "Summarizing Device Use"
    },
    {
      "anchor": "Analyzing-App-Use",
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/applicationUsageByCategory",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/ApplicationUsage",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey"
      ],
      "title": "Analyzing App Use"
    },
    {
      "anchor": "Analyzing-Notification-Use",
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/notificationUsageByCategory",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/NotificationUsage"
      ],
      "title": "Analyzing Notification Use"
    },
    {
      "anchor": "Analyzing-Web-Use",
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/webUsageByCategory",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/WebUsage"
      ],
      "title": "Analyzing Web Use"
    },
    {
      "anchor": "Getting-algorithm-information",
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/version"
      ],
      "title": "Getting algorithm information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SRDeviceUsageReport"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageReport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageReport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sensorkit/documentation/SensorKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Summarizing-Device-Use",
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/duration",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/totalScreenWakes",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/totalUnlocks",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/totalUnlockDuration"
              ],
              "title": "Summarizing Device Use"
            },
            {
              "anchor": "Analyzing-App-Use",
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/applicationUsageByCategory",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/ApplicationUsage",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey"
              ],
              "title": "Analyzing App Use"
            },
            {
              "anchor": "Analyzing-Notification-Use",
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/notificationUsageByCategory",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/NotificationUsage"
              ],
              "title": "Analyzing Notification Use"
            },
            {
              "anchor": "Analyzing-Web-Use",
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/webUsageByCategory",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/WebUsage"
              ],
              "title": "Analyzing Web Use"
            },
            {
              "anchor": "Getting-algorithm-information",
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/version"
              ],
              "title": "Getting algorithm information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Interpreting-data",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRMediaEvent",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRMessagesUsageReport",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRPhoneUsageReport",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRVisit",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRWristDetection"
              ],
              "title": "Interpreting data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SRDeviceUsageReport"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey/title",
          "value": "SRDeviceUsageCategoryKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRVisit/title",
          "value": "SRVisit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRVisit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRVisit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRVisit/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRVisit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1WebUsage/title",
          "value": "SRWebUsage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1WebUsage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRWebUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1WebUsage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRWebUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhoneUsageReport/title",
          "value": "SRPhoneUsageReport"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhoneUsageReport/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRPhoneUsageReport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhoneUsageReport/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRPhoneUsageReport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1totalScreenWakes/title",
          "value": "totalScreenWakes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1totalScreenWakes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "totalScreenWakes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1deviceUsageReport/title",
          "value": "SRSensorDeviceUsageReport"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1deviceUsageReport/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorDeviceUsageReport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1duration/title",
          "value": "duration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1duration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "duration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1ApplicationUsage/title",
          "value": "SRApplicationUsage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1ApplicationUsage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRApplicationUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1ApplicationUsage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRApplicationUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1totalUnlockDuration/title",
          "value": "totalUnlockDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1totalUnlockDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "totalUnlockDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1webUsageByCategory/title",
          "value": "webUsageByCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1webUsageByCategory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "webUsageByCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristDetection/title",
          "value": "SRWristDetection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristDetection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRWristDetection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristDetection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRWristDetection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1NotificationUsage/title",
          "value": "SRNotificationUsage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1NotificationUsage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRNotificationUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1NotificationUsage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRNotificationUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics/title",
          "value": "SRKeyboardMetrics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRKeyboardMetrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRKeyboardMetrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1notificationUsageByCategory/title",
          "value": "notificationUsageByCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1notificationUsageByCategory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "notificationUsageByCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample/title",
          "value": "SRAmbientLightSample"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRAmbientLightSample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRAmbientLightSample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRMediaEvent/title",
          "value": "SRMediaEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRMediaEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRMediaEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRMediaEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRMediaEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFetchResult~1sample/title",
          "value": "sample"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFetchResult~1sample/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1version/title",
          "value": "version"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1version/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "version"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRMessagesUsageReport/title",
          "value": "SRMessagesUsageReport"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRMessagesUsageReport/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRMessagesUsageReport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRMessagesUsageReport/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRMessagesUsageReport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1applicationUsageByCategory/title",
          "value": "applicationUsageByCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1applicationUsageByCategory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "applicationUsageByCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport/title",
          "value": "SRDeviceUsageReport"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageReport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageReport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1totalUnlocks/title",
          "value": "totalUnlocks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1totalUnlocks/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "totalUnlocks"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/sensorkit/srdeviceusagereport"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/sensorkit/srdeviceusagereport"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
