{
  "abstract": [
    {
      "text": "A set of callbacks the framework invokes to notify the app of sensor-related events.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sensorkit/documentation/SensorKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)SRSensorReaderDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SRSensorReaderDelegate"
      }
    ],
    "modules": [
      {
        "name": "SensorKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SRSensorReaderDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "SRSensorReaderDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SRSensorReaderDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To access sensor data, assign an object as the delegate and implement its callbacks.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit": {
      "abstract": [
        {
          "text": "Retrieve data and derived metrics from sensors on an iPhone, or paired Apple Watch.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SensorKit",
      "type": "topic",
      "url": "/documentation/sensorkit"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDevice": {
      "abstract": [
        {
          "text": "A representation of a device that provides sample data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRDevice"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRDevice"
        }
      ],
      "role": "symbol",
      "title": "SRDevice",
      "type": "topic",
      "url": "/documentation/sensorkit/srdevice"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRError": {
      "abstract": [
        {
          "text": "An error that SensorKit reports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRError"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRError"
        }
      ],
      "role": "symbol",
      "title": "SRError",
      "type": "topic",
      "url": "/documentation/sensorkit/srerror"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRError/Code": {
      "abstract": [
        {
          "text": "The kinds of problems that stop a recording or a fetch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "SRError.Code",
      "type": "topic",
      "url": "/documentation/sensorkit/srerror/code"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRErrorDomain": {
      "abstract": [
        {
          "text": "An error domain that’s unique to the framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "SRErrorDomain",
      "type": "topic",
      "url": "/documentation/sensorkit/srerrordomain"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReader/delegate": {
      "abstract": [
        {
          "text": "An object that responds to sensor-related events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)SRSensorReaderDelegate",
          "text": "SRSensorReaderDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReader/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/sensorkit/srsensorreader/delegate"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate": {
      "abstract": [
        {
          "text": "A set of callbacks the framework invokes to notify the app of sensor-related events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRSensorReaderDelegate"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorReaderDelegate"
        }
      ],
      "role": "symbol",
      "title": "SRSensorReaderDelegate",
      "type": "topic",
      "url": "/documentation/sensorkit/srsensorreaderdelegate"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:didChange:)": {
      "abstract": [
        {
          "text": "Notifies the delegate of the reader’s new authorization status.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sensorReader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRSensorReader",
          "text": "SRSensorReader"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didChange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SRAuthorizationStatus",
          "text": "SRAuthorizationStatus"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:didChange:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sensorReader:didChangeAuthorizationStatus:"
        }
      ],
      "role": "symbol",
      "title": "sensorReader(_:didChange:)",
      "type": "topic",
      "url": "/documentation/sensorkit/srsensorreaderdelegate/sensorreader(_:didchange:)"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:didCompleteFetch:)": {
      "abstract": [
        {
          "text": "Provides the delegate with a completed fetch request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sensorReader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRSensorReader",
          "text": "SRSensorReader"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didCompleteFetch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRFetchRequest",
          "text": "SRFetchRequest"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:didCompleteFetch:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sensorReader:didCompleteFetch:"
        }
      ],
      "role": "symbol",
      "title": "sensorReader(_:didCompleteFetch:)",
      "type": "topic",
      "url": "/documentation/sensorkit/srsensorreaderdelegate/sensorreader(_:didcompletefetch:)"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:didFetch:)": {
      "abstract": [
        {
          "text": "Provides the delegate with one or more devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sensorReader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRSensorReader",
          "text": "SRSensorReader"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didFetch"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDevice",
          "text": "SRDevice"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:didFetch:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sensorReader:didFetchDevices:"
        }
      ],
      "role": "symbol",
      "title": "sensorReader(_:didFetch:)",
      "type": "topic",
      "url": "/documentation/sensorkit/srsensorreaderdelegate/sensorreader(_:didfetch:)"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:fetchDevicesDidFailWithError:)": {
      "abstract": [
        {
          "text": "Provides the delegate a reason when the reader fails to fetch devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sensorReader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRSensorReader",
          "text": "SRSensorReader"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "fetchDevicesDidFailWithError"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:fetchDevicesDidFailWithError:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sensorReader:fetchDevicesDidFailWithError:"
        }
      ],
      "role": "symbol",
      "title": "sensorReader(_:fetchDevicesDidFailWithError:)",
      "type": "topic",
      "url": "/documentation/sensorkit/srsensorreaderdelegate/sensorreader(_:fetchdevicesdidfailwitherror:)"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:fetching:didFetchResult:)": {
      "abstract": [
        {
          "text": "Provides the delegate with a fetch result.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sensorReader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRSensorReader",
          "text": "SRSensorReader"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "fetching"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRFetchRequest",
          "text": "SRFetchRequest"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didFetchResult"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRFetchResult",
          "text": "SRFetchResult"
        },
        {
          "kind": "text",
          "text": "<AnyObject>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:fetching:didFetchResult:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sensorReader:fetchingRequest:didFetchResult:"
        }
      ],
      "role": "symbol",
      "title": "sensorReader(_:fetching:didFetchResult:)",
      "type": "topic",
      "url": "/documentation/sensorkit/srsensorreaderdelegate/sensorreader(_:fetching:didfetchresult:)"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:fetching:failedWithError:)": {
      "abstract": [
        {
          "text": "Provides the delegate with a fetch failure reason.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sensorReader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRSensorReader",
          "text": "SRSensorReader"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "fetching"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRFetchRequest",
          "text": "SRFetchRequest"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "failedWithError"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:fetching:failedWithError:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sensorReader:fetchingRequest:failedWithError:"
        }
      ],
      "role": "symbol",
      "title": "sensorReader(_:fetching:failedWithError:)",
      "type": "topic",
      "url": "/documentation/sensorkit/srsensorreaderdelegate/sensorreader(_:fetching:failedwitherror:)"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:startRecordingFailedWithError:)": {
      "abstract": [
        {
          "text": "Provides the delegate with a reason when the reader fails to record.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sensorReader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRSensorReader",
          "text": "SRSensorReader"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "startRecordingFailedWithError"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:startRecordingFailedWithError:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sensorReader:startRecordingFailedWithError:"
        }
      ],
      "role": "symbol",
      "title": "sensorReader(_:startRecordingFailedWithError:)",
      "type": "topic",
      "url": "/documentation/sensorkit/srsensorreaderdelegate/sensorreader(_:startrecordingfailedwitherror:)"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:stopRecordingFailedWithError:)": {
      "abstract": [
        {
          "text": "Provides the delegate with a reason when the reader fails to stop recording.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sensorReader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRSensorReader",
          "text": "SRSensorReader"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "stopRecordingFailedWithError"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:stopRecordingFailedWithError:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sensorReader:stopRecordingFailedWithError:"
        }
      ],
      "role": "symbol",
      "title": "sensorReader(_:stopRecordingFailedWithError:)",
      "type": "topic",
      "url": "/documentation/sensorkit/srsensorreaderdelegate/sensorreader(_:stoprecordingfailedwitherror:)"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReaderDidStopRecording(_:)": {
      "abstract": [
        {
          "text": "Notifies the delegate when a reader stops recording.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sensorReaderDidStopRecording"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRSensorReader",
          "text": "SRSensorReader"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReaderDidStopRecording(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sensorReaderDidStopRecording:"
        }
      ],
      "role": "symbol",
      "title": "sensorReaderDidStopRecording(_:)",
      "type": "topic",
      "url": "/documentation/sensorkit/srsensorreaderdelegate/sensorreaderdidstoprecording(_:)"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReaderWillStartRecording(_:)": {
      "abstract": [
        {
          "text": "Notifies the delegate when a reader starts recording.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sensorReaderWillStartRecording"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRSensorReader",
          "text": "SRSensorReader"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReaderWillStartRecording(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sensorReaderWillStartRecording:"
        }
      ],
      "role": "symbol",
      "title": "sensorReaderWillStartRecording(_:)",
      "type": "topic",
      "url": "/documentation/sensorkit/srsensorreaderdelegate/sensorreaderwillstartrecording(_:)"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Responding-to-sensor-events",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReader/delegate"
      ],
      "title": "Responding to sensor events"
    }
  ],
  "topicSections": [
    {
      "anchor": "Checking-Authorization-Status",
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:didChange:)"
      ],
      "title": "Checking Authorization Status"
    },
    {
      "anchor": "Fetching-Devices",
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:didFetch:)",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:fetchDevicesDidFailWithError:)",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDevice"
      ],
      "title": "Fetching Devices"
    },
    {
      "anchor": "Recording-Data",
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReaderWillStartRecording(_:)",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:startRecordingFailedWithError:)",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReaderDidStopRecording(_:)",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:stopRecordingFailedWithError:)"
      ],
      "title": "Recording Data"
    },
    {
      "anchor": "Reading-Recorded-Data",
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:fetching:didFetchResult:)",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:didCompleteFetch:)",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:fetching:failedWithError:)"
      ],
      "title": "Reading Recorded Data"
    },
    {
      "anchor": "Interpreting-Errors",
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRErrorDomain",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRError",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRError/Code"
      ],
      "title": "Interpreting Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SRSensorReaderDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorReaderDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorReaderDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sensorkit/documentation/SensorKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Checking-Authorization-Status",
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:didChange:)"
              ],
              "title": "Checking Authorization Status"
            },
            {
              "anchor": "Fetching-Devices",
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:didFetch:)",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:fetchDevicesDidFailWithError:)",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDevice"
              ],
              "title": "Fetching Devices"
            },
            {
              "anchor": "Recording-Data",
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReaderWillStartRecording(_:)",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:startRecordingFailedWithError:)",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReaderDidStopRecording(_:)",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:stopRecordingFailedWithError:)"
              ],
              "title": "Recording Data"
            },
            {
              "anchor": "Reading-Recorded-Data",
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:fetching:didFetchResult:)",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:didCompleteFetch:)",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReaderDelegate/sensorReader(_:fetching:failedWithError:)"
              ],
              "title": "Reading Recorded Data"
            },
            {
              "anchor": "Interpreting-Errors",
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/SRErrorDomain",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRError/Code"
              ],
              "title": "Interpreting Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Responding-to-sensor-events",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReader/delegate"
              ],
              "title": "Responding to sensor events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SRSensorReaderDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate~1sensorReader(_:fetchDevicesDidFailWithError:)/title",
          "value": "sensorReader:fetchDevicesDidFailWithError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate~1sensorReader(_:fetchDevicesDidFailWithError:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "sensorReader:fetchDevicesDidFailWithError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRError~1Code/title",
          "value": "SRErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate~1sensorReader(_:fetching:didFetchResult:)/title",
          "value": "sensorReader:fetchingRequest:didFetchResult:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate~1sensorReader(_:fetching:didFetchResult:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "sensorReader:fetchingRequest:didFetchResult:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate~1sensorReader(_:fetching:failedWithError:)/title",
          "value": "sensorReader:fetchingRequest:failedWithError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate~1sensorReader(_:fetching:failedWithError:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "sensorReader:fetchingRequest:failedWithError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReader~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReader~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate~1sensorReader(_:didCompleteFetch:)/title",
          "value": "sensorReader:didCompleteFetch:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate~1sensorReader(_:didCompleteFetch:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "sensorReader:didCompleteFetch:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRErrorDomain/title",
          "value": "SRErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate~1sensorReader(_:didFetch:)/title",
          "value": "sensorReader:didFetchDevices:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate~1sensorReader(_:didFetch:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "sensorReader:didFetchDevices:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate~1sensorReader(_:didChange:)/title",
          "value": "sensorReader:didChangeAuthorizationStatus:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate~1sensorReader(_:didChange:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "sensorReader:didChangeAuthorizationStatus:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate/title",
          "value": "SRSensorReaderDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorReaderDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorReaderDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate~1sensorReaderWillStartRecording(_:)/title",
          "value": "sensorReaderWillStartRecording:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate~1sensorReaderWillStartRecording(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "sensorReaderWillStartRecording:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate~1sensorReader(_:startRecordingFailedWithError:)/title",
          "value": "sensorReader:startRecordingFailedWithError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate~1sensorReader(_:startRecordingFailedWithError:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "sensorReader:startRecordingFailedWithError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDevice/title",
          "value": "SRDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate~1sensorReader(_:stopRecordingFailedWithError:)/title",
          "value": "sensorReader:stopRecordingFailedWithError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate~1sensorReader(_:stopRecordingFailedWithError:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "sensorReader:stopRecordingFailedWithError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate~1sensorReaderDidStopRecording(_:)/title",
          "value": "sensorReaderDidStopRecording:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReaderDelegate~1sensorReaderDidStopRecording(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "sensorReaderDidStopRecording:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/sensorkit/srsensorreaderdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/sensorkit/srsensorreaderdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
