{
  "abstract": [
    {
      "text": "The sensors an app can read.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sensorkit/documentation/SensorKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@SRSensor",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SRSensor"
      }
    ],
    "modules": [
      {
        "name": "SensorKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SRSensor"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "SRSensor"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SRSensor"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.sensorkit/documentation/SensorKit/configuring-your-project-for-sensor-reading"
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the properties in this structure to access the different sensors.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit": {
      "abstract": [
        {
          "text": "Retrieve data and derived metrics from sensors on an iPhone, or paired Apple Watch.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SensorKit",
      "type": "topic",
      "url": "/documentation/sensorkit"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor": {
      "abstract": [
        {
          "text": "The sensors an app can read.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRSensor"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensor"
        }
      ],
      "role": "symbol",
      "title": "SRSensor",
      "type": "topic",
      "url": "/documentation/sensorkit/srsensor"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/accelerometer": {
      "abstract": [
        {
          "text": "A sensor that provides acceleration motion data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accelerometer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRSensor",
          "text": "SRSensor"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/accelerometer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorAccelerometer"
        }
      ],
      "role": "symbol",
      "title": "accelerometer",
      "type": "topic",
      "url": "/documentation/sensorkit/srsensor/accelerometer"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/ambientLightSensor": {
      "abstract": [
        {
          "text": "A sensor that provides ambient light information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ambientLightSensor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRSensor",
          "text": "SRSensor"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/ambientLightSensor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorAmbientLightSensor"
        }
      ],
      "role": "symbol",
      "title": "ambientLightSensor",
      "type": "topic",
      "url": "/documentation/sensorkit/srsensor/ambientlightsensor"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/ambientPressure": {
      "abstract": [
        {
          "text": "A sensor that provides pressure and temperature metrics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ambientPressure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRSensor",
          "text": "SRSensor"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/ambientPressure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorAmbientPressure"
        }
      ],
      "role": "symbol",
      "title": "ambientPressure",
      "type": "topic",
      "url": "/documentation/sensorkit/srsensor/ambientpressure"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/deviceUsageReport": {
      "abstract": [
        {
          "text": "A sensor that provides information about device usage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceUsageReport"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRSensor",
          "text": "SRSensor"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/deviceUsageReport",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorDeviceUsageReport"
        }
      ],
      "role": "symbol",
      "title": "deviceUsageReport",
      "type": "topic",
      "url": "/documentation/sensorkit/srsensor/deviceusagereport"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/electrocardiogram": {
      "abstract": [
        {
          "text": "A sensor that streams sample ECG sensor data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "electrocardiogram"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRSensor",
          "text": "SRSensor"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/electrocardiogram",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorElectrocardiogram"
        }
      ],
      "role": "symbol",
      "title": "electrocardiogram",
      "type": "topic",
      "url": "/documentation/sensorkit/srsensor/electrocardiogram"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/faceMetrics": {
      "abstract": [
        {
          "text": "A sensor that provides data describing a user’s face.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "faceMetrics"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRSensor",
          "text": "SRSensor"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/faceMetrics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorFaceMetrics"
        }
      ],
      "role": "symbol",
      "title": "faceMetrics",
      "type": "topic",
      "url": "/documentation/sensorkit/srsensor/facemetrics"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/heartRate": {
      "abstract": [
        {
          "text": "A sensor that provides the user’s heart rate data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "heartRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRSensor",
          "text": "SRSensor"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/heartRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorHeartRate"
        }
      ],
      "role": "symbol",
      "title": "heartRate",
      "type": "topic",
      "url": "/documentation/sensorkit/srsensor/heartrate"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a sensor from a raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/sensorkit/srsensor/init(rawvalue:)"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/keyboardMetrics": {
      "abstract": [
        {
          "text": "A sensor that provides information about keyboard usage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyboardMetrics"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRSensor",
          "text": "SRSensor"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/keyboardMetrics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorKeyboardMetrics"
        }
      ],
      "role": "symbol",
      "title": "keyboardMetrics",
      "type": "topic",
      "url": "/documentation/sensorkit/srsensor/keyboardmetrics"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/mediaEvents": {
      "abstract": [
        {
          "text": "A sensor that provides information about interactions with media, such as images and videos, in messaging apps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaEvents"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRSensor",
          "text": "SRSensor"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/mediaEvents",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorMediaEvents"
        }
      ],
      "role": "symbol",
      "title": "mediaEvents",
      "type": "topic",
      "url": "/documentation/sensorkit/srsensor/mediaevents"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/messagesUsageReport": {
      "abstract": [
        {
          "text": "A sensor that provides information about use of the Messages app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "messagesUsageReport"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRSensor",
          "text": "SRSensor"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/messagesUsageReport",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorMessagesUsageReport"
        }
      ],
      "role": "symbol",
      "title": "messagesUsageReport",
      "type": "topic",
      "url": "/documentation/sensorkit/srsensor/messagesusagereport"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/odometer": {
      "abstract": [
        {
          "text": "A sensor that provides information about speed and slope.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "odometer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRSensor",
          "text": "SRSensor"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/odometer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorOdometer"
        }
      ],
      "role": "symbol",
      "title": "odometer",
      "type": "topic",
      "url": "/documentation/sensorkit/srsensor/odometer"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/onWristState": {
      "abstract": [
        {
          "text": "A sensor that describes the watch’s position on the wrist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "onWristState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRSensor",
          "text": "SRSensor"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/onWristState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorOnWristState"
        }
      ],
      "role": "symbol",
      "title": "onWristState",
      "type": "topic",
      "url": "/documentation/sensorkit/srsensor/onwriststate"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/pedometerData": {
      "abstract": [
        {
          "text": "A sensor that provides information about the user’s steps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pedometerData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRSensor",
          "text": "SRSensor"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/pedometerData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorPedometerData"
        }
      ],
      "role": "symbol",
      "title": "pedometerData",
      "type": "topic",
      "url": "/documentation/sensorkit/srsensor/pedometerdata"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/phoneUsageReport": {
      "abstract": [
        {
          "text": "A sensor that reports the amount of time that the user is on phone calls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "phoneUsageReport"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRSensor",
          "text": "SRSensor"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/phoneUsageReport",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorPhoneUsageReport"
        }
      ],
      "role": "symbol",
      "title": "phoneUsageReport",
      "type": "topic",
      "url": "/documentation/sensorkit/srsensor/phoneusagereport"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/photoplethysmogram": {
      "abstract": [
        {
          "text": "A sensor that streams sample PPG sensor data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "photoplethysmogram"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRSensor",
          "text": "SRSensor"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/photoplethysmogram",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorPhotoplethysmogram"
        }
      ],
      "role": "symbol",
      "title": "photoplethysmogram",
      "type": "topic",
      "url": "/documentation/sensorkit/srsensor/photoplethysmogram"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/rotationRate": {
      "abstract": [
        {
          "text": "A sensor that provides rotation motion data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rotationRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRSensor",
          "text": "SRSensor"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/rotationRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorRotationRate"
        }
      ],
      "role": "symbol",
      "title": "rotationRate",
      "type": "topic",
      "url": "/documentation/sensorkit/srsensor/rotationrate"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/siriSpeechMetrics": {
      "abstract": [
        {
          "text": "A sensor that provides data describing a user’s speech to Siri.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "siriSpeechMetrics"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRSensor",
          "text": "SRSensor"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/siriSpeechMetrics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorSiriSpeechMetrics"
        }
      ],
      "role": "symbol",
      "title": "siriSpeechMetrics",
      "type": "topic",
      "url": "/documentation/sensorkit/srsensor/sirispeechmetrics"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/telephonySpeechMetrics": {
      "abstract": [
        {
          "text": "A sensor that provides data describing speech during phone calls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "telephonySpeechMetrics"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRSensor",
          "text": "SRSensor"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/telephonySpeechMetrics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorTelephonySpeechMetrics"
        }
      ],
      "role": "symbol",
      "title": "telephonySpeechMetrics",
      "type": "topic",
      "url": "/documentation/sensorkit/srsensor/telephonyspeechmetrics"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/visits": {
      "abstract": [
        {
          "text": "A sensor that provides information about frequently visited locations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "visits"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRSensor",
          "text": "SRSensor"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/visits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorVisits"
        }
      ],
      "role": "symbol",
      "title": "visits",
      "type": "topic",
      "url": "/documentation/sensorkit/srsensor/visits"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/wristTemperature": {
      "abstract": [
        {
          "text": "A sensor that provides wrist temperature while the user sleeps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wristTemperature"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRSensor",
          "text": "SRSensor"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/wristTemperature",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSensorWristTemperature"
        }
      ],
      "role": "symbol",
      "title": "wristTemperature",
      "type": "topic",
      "url": "/documentation/sensorkit/srsensor/wristtemperature"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReader/init(sensor:)": {
      "abstract": [
        {
          "text": "Initializes a new sensor reader object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "sensor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRSensor",
          "text": "SRSensor"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReader/init(sensor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithSensor:"
        }
      ],
      "role": "symbol",
      "title": "init(sensor:)",
      "type": "topic",
      "url": "/documentation/sensorkit/srsensorreader/init(sensor:)"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReader/sensor": {
      "abstract": [
        {
          "text": "The particular sensor that this object reads.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sensor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRSensor",
          "text": "SRSensor"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReader/sensor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sensor"
        }
      ],
      "role": "symbol",
      "title": "sensor",
      "type": "topic",
      "url": "/documentation/sensorkit/srsensorreader/sensor"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/configuring-your-project-for-sensor-reading": {
      "abstract": [
        {
          "text": "Add metadata to your app to attain system and user permission to access sensor data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/configuring-your-project-for-sensor-reading",
      "kind": "article",
      "role": "article",
      "title": "Configuring your project for sensor reading",
      "type": "topic",
      "url": "/documentation/sensorkit/configuring-your-project-for-sensor-reading"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-sensor-reader",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReader/init(sensor:)",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReader/sensor"
      ],
      "title": "Creating a sensor reader"
    }
  ],
  "topicSections": [
    {
      "anchor": "Reading-device-sensors",
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/deviceUsageReport",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/keyboardMetrics",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/onWristState"
      ],
      "title": "Reading device sensors"
    },
    {
      "anchor": "Reading-app-activity-sensors",
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/messagesUsageReport",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/phoneUsageReport"
      ],
      "title": "Reading app activity sensors"
    },
    {
      "anchor": "Reading-user-activity-sensors",
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/accelerometer",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/faceMetrics",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/heartRate",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/mediaEvents",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/odometer",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/pedometerData",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/rotationRate",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/siriSpeechMetrics",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/telephonySpeechMetrics",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/visits",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/wristTemperature",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/photoplethysmogram",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/electrocardiogram"
      ],
      "title": "Reading user activity sensors"
    },
    {
      "anchor": "Reading-environment-sensors",
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/ambientLightSensor",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/ambientPressure"
      ],
      "title": "Reading environment sensors"
    },
    {
      "anchor": "Creating-a-sensor",
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/init(rawValue:)"
      ],
      "title": "Creating a sensor"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SRSensor"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sensorkit/documentation/SensorKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Reading-device-sensors",
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/deviceUsageReport",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/keyboardMetrics",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/onWristState"
              ],
              "title": "Reading device sensors"
            },
            {
              "anchor": "Reading-app-activity-sensors",
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/messagesUsageReport",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/phoneUsageReport"
              ],
              "title": "Reading app activity sensors"
            },
            {
              "anchor": "Reading-user-activity-sensors",
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/accelerometer",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/faceMetrics",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/heartRate",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/mediaEvents",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/odometer",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/pedometerData",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/rotationRate",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/siriSpeechMetrics",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/telephonySpeechMetrics",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/visits",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/wristTemperature",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/photoplethysmogram",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/electrocardiogram"
              ],
              "title": "Reading user activity sensors"
            },
            {
              "anchor": "Reading-environment-sensors",
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/ambientLightSensor",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/ambientPressure"
              ],
              "title": "Reading environment sensors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-a-sensor-reader",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReader/init(sensor:)",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRSensorReader/sensor"
              ],
              "title": "Creating a sensor reader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "SRSensor"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1heartRate/title",
          "value": "SRSensorHeartRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1heartRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorHeartRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1ambientPressure/title",
          "value": "SRSensorAmbientPressure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1ambientPressure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorAmbientPressure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1rotationRate/title",
          "value": "SRSensorRotationRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1rotationRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorRotationRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1messagesUsageReport/title",
          "value": "SRSensorMessagesUsageReport"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1messagesUsageReport/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorMessagesUsageReport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1ambientLightSensor/title",
          "value": "SRSensorAmbientLightSensor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1ambientLightSensor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorAmbientLightSensor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor/title",
          "value": "SRSensor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1keyboardMetrics/title",
          "value": "SRSensorKeyboardMetrics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1keyboardMetrics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorKeyboardMetrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReader~1sensor/title",
          "value": "sensor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReader~1sensor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sensor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1odometer/title",
          "value": "SRSensorOdometer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1odometer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorOdometer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1phoneUsageReport/title",
          "value": "SRSensorPhoneUsageReport"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1phoneUsageReport/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorPhoneUsageReport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1onWristState/title",
          "value": "SRSensorOnWristState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1onWristState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorOnWristState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1deviceUsageReport/title",
          "value": "SRSensorDeviceUsageReport"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1deviceUsageReport/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorDeviceUsageReport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReader~1init(sensor:)/title",
          "value": "initWithSensor:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensorReader~1init(sensor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithSensor:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1siriSpeechMetrics/title",
          "value": "SRSensorSiriSpeechMetrics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1siriSpeechMetrics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorSiriSpeechMetrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1faceMetrics/title",
          "value": "SRSensorFaceMetrics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1faceMetrics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorFaceMetrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1mediaEvents/title",
          "value": "SRSensorMediaEvents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1mediaEvents/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorMediaEvents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1pedometerData/title",
          "value": "SRSensorPedometerData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1pedometerData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorPedometerData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1wristTemperature/title",
          "value": "SRSensorWristTemperature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1wristTemperature/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorWristTemperature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1accelerometer/title",
          "value": "SRSensorAccelerometer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1accelerometer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorAccelerometer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1photoplethysmogram/title",
          "value": "SRSensorPhotoplethysmogram"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1photoplethysmogram/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorPhotoplethysmogram"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1electrocardiogram/title",
          "value": "SRSensorElectrocardiogram"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1electrocardiogram/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorElectrocardiogram"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1telephonySpeechMetrics/title",
          "value": "SRSensorTelephonySpeechMetrics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1telephonySpeechMetrics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorTelephonySpeechMetrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1visits/title",
          "value": "SRSensorVisits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1visits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSensorVisits"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/sensorkit/srsensor"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/sensorkit/srsensor"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
