{
  "abstract": [
    {
      "text": "Declare the types of PushKit notifications your app supports and configure objects to respond to them.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pushkit/documentation/PushKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pushkit/documentation/PushKit/supporting-pushkit-notifications-in-your-app"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "PushKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Supporting PushKit Notifications in Your App"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You must configure your app to handle PushKit-related notifications, and you must supply a server to generate those notifications. In your app, you tell PushKit what types of push notifications your app handles, and you write code to respond when a notification arrives. You use your server to generate the push notifications that your app receives. When a user initiates a call with your service, your server creates a push notification request for that call and sends it to Apple Push Notification service (APNs), which delivers that notification to the user’s device.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For information about how to set up a server to generate push notifications, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UserNotifications/setting-up-a-remote-notification-server",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Enable-Push-Notification-Support-for-Your-App",
          "level": 3,
          "text": "Enable Push Notification Support for Your App",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Apps must have the proper entitlements to receive push notifications. To create these entitlements, ",
              "type": "text"
            },
            {
              "identifier": "https://help.apple.com/xcode/mac/current/#/devdfd3d04a1",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to your Xcode project. When you add this capability, Xcode adds the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/aps-environment",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to your app and configures your App ID with the push notification service for development purposes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "If you create an explicit App ID for your app, you can also add the push notification service manually by configuring the App ID from your ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/account/",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " page.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Register-Your-App-with-PushKit-at-Launch-Time",
          "level": 3,
          "text": "Register Your App with PushKit at Launch Time",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The system can’t deliver push notifications to your app until you create a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.pushkit/documentation/PushKit/PKPushRegistry",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object and specify the types of notifications you support. Typically, you create this object at launch time and store a reference to it for the duration of your app’s runtime. The following example shows how to create this object and configure it with the Voice-over-IP (VoIP) push type. During configuration, always specify a delegate object to receive notifications.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "func registerForVoIPPushes() {",
                    "    self.voipRegistry = PKPushRegistry(queue: nil)",
                    "    self.voipRegistry.delegate = self",
                    "    self.voipRegistry.desiredPushTypes = [.voIP]",
                    "}"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "- (void) registerForVoIPPushes {",
                    "   self.voipRegistry = [[PKPushRegistry alloc] initWithQueue:nil];",
                    "   self.voipRegistry.delegate = self;",
                    " ",
                    "   // Initiate registration.",
                    "   self.voipRegistry.desiredPushTypes = [NSSet setWithObject:PKPushTypeVoIP];",
                    "   }"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "inlineContent": [
            {
              "text": "Assigning a value to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.pushkit/documentation/PushKit/PKPushRegistry/desiredPushTypes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property begins the registration process, so always update that property last. The server reports the success or failure of the registration process to your delegate object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Send-the-Device-Token-to-Your-Server",
          "level": 3,
          "text": "Send the Device Token to Your Server",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In order to deliver notifications to a user device, your server must know the address of that device. PushKit provides the address to you in the form of a device token, which is an opaque data object. When you register your app’s supported push types, the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.pushkit/documentation/PushKit/PKPushRegistry",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object creates a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.pushkit/documentation/PushKit/PKPushCredentials",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object and delivers it to your delegate’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.pushkit/documentation/PushKit/PKPushRegistryDelegate/pushRegistry(_:didUpdate:for:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method. The credentials object contains the device token for the current device.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Upon receiving a device token, forward it to your server along with any other information you need to identify the user, such as their account unique identifier. To ensure the security of the user’s information, always encrypt the token and all user data before sending it over the network. On your server, store device tokens securely with the user’s other account details. Because users can run your app on multiple devices, be prepared to handle multiple tokens for each notification type your app supports.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For information about how to set up your server to handle push notifications, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UserNotifications/setting-up-a-remote-notification-server",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Generate-Push-Notifications-Using-the-Device-Token",
          "level": 3,
          "text": "Generate Push Notifications Using the Device Token",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When you have data to send to the user, generate an appropriate POST request and send it to APNs. A VoIP service generates a request each time it receives an incoming call for the user. An app with a complication might generate a request whenever it receives urgent updates for that complication.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Each POST request contains a JSON payload with the data you want to send to the user. For most notification types, you may send up to 4 KB (4096 bytes) of data in your payload, but for VoIP notifications, the limit is 5 KB (5120 bytes). Include information in the payload that your app needs to respond. For example, include the new data you want your watchOS complication to display. If you cannot fit all of the data in the payload, your app can open a network connection and fetch any additional data it needs.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For information about how to construct and send POST requests to APNs, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UserNotifications/sending-notification-requests-to-apns",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". For specific information on how to configure VoIP push notifications, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.pushkit/documentation/PushKit/responding-to-voip-notifications-from-pushkit",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/aps-environment": {
      "abstract": [
        {
          "text": "The environment for push notifications.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/aps-environment",
      "kind": "symbol",
      "role": "symbol",
      "title": "APS Environment Entitlement",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/aps-environment"
    },
    "doc://com.apple.documentation/documentation/UserNotifications/sending-notification-requests-to-apns": {
      "abstract": [
        {
          "text": "Transmit your remote notification payload and device token information to Apple Push Notification service (APNs).",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UserNotifications/sending-notification-requests-to-apns",
      "kind": "article",
      "role": "article",
      "title": "Sending notification requests to APNs",
      "type": "topic",
      "url": "/documentation/UserNotifications/sending-notification-requests-to-apns"
    },
    "doc://com.apple.documentation/documentation/UserNotifications/setting-up-a-remote-notification-server": {
      "abstract": [
        {
          "text": "Generate notifications and push them to user devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UserNotifications/setting-up-a-remote-notification-server",
      "kind": "article",
      "role": "article",
      "title": "Setting up a remote notification server",
      "type": "topic",
      "url": "/documentation/UserNotifications/setting-up-a-remote-notification-server"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pushkit/documentation/PushKit": {
      "abstract": [
        {
          "text": "Respond to push notifications related to your app’s complications, file providers, and VoIP services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pushkit/documentation/PushKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PushKit",
      "type": "topic",
      "url": "/documentation/pushkit"
    },
    "doc://com.apple.pushkit/documentation/PushKit/PKPushCredentials": {
      "abstract": [
        {
          "text": "An object that encapsulates the device token you use to deliver push notifications to your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPushCredentials"
        }
      ],
      "identifier": "doc://com.apple.pushkit/documentation/PushKit/PKPushCredentials",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPushCredentials"
        }
      ],
      "role": "symbol",
      "title": "PKPushCredentials",
      "type": "topic",
      "url": "/documentation/pushkit/pkpushcredentials"
    },
    "doc://com.apple.pushkit/documentation/PushKit/PKPushRegistry": {
      "abstract": [
        {
          "text": "An object that requests the delivery and handles the receipt of PushKit notifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPushRegistry"
        }
      ],
      "identifier": "doc://com.apple.pushkit/documentation/PushKit/PKPushRegistry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPushRegistry"
        }
      ],
      "role": "symbol",
      "title": "PKPushRegistry",
      "type": "topic",
      "url": "/documentation/pushkit/pkpushregistry"
    },
    "doc://com.apple.pushkit/documentation/PushKit/PKPushRegistry/desiredPushTypes": {
      "abstract": [
        {
          "text": "Registers the push types for this push registry object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "desiredPushTypes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPushType",
          "text": "PKPushType"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.pushkit/documentation/PushKit/PKPushRegistry/desiredPushTypes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "desiredPushTypes"
        }
      ],
      "role": "symbol",
      "title": "desiredPushTypes",
      "type": "topic",
      "url": "/documentation/pushkit/pkpushregistry/desiredpushtypes"
    },
    "doc://com.apple.pushkit/documentation/PushKit/PKPushRegistryDelegate": {
      "abstract": [
        {
          "text": "The methods that you use to handle incoming PushKit notifications and registration events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPushRegistryDelegate"
        }
      ],
      "identifier": "doc://com.apple.pushkit/documentation/PushKit/PKPushRegistryDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPushRegistryDelegate"
        }
      ],
      "role": "symbol",
      "title": "PKPushRegistryDelegate",
      "type": "topic",
      "url": "/documentation/pushkit/pkpushregistrydelegate"
    },
    "doc://com.apple.pushkit/documentation/PushKit/PKPushRegistryDelegate/pushRegistry(_:didUpdate:for:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the system updated the credentials for the specified type of push notification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pushRegistry"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPushRegistry",
          "text": "PKPushRegistry"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didUpdate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPushCredentials",
          "text": "PKPushCredentials"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPushType",
          "text": "PKPushType"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pushkit/documentation/PushKit/PKPushRegistryDelegate/pushRegistry(_:didUpdate:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pushRegistry:didUpdatePushCredentials:forType:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "pushRegistry(_:didUpdate:for:)",
      "type": "topic",
      "url": "/documentation/pushkit/pkpushregistrydelegate/pushregistry(_:didupdate:for:)"
    },
    "doc://com.apple.pushkit/documentation/PushKit/responding-to-voip-notifications-from-pushkit": {
      "abstract": [
        {
          "text": "Receive incoming Voice-over-IP (VoIP) push notifications and use them to display the system call interface to the user.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pushkit/documentation/PushKit/responding-to-voip-notifications-from-pushkit",
      "kind": "article",
      "role": "article",
      "title": "Responding to VoIP Notifications from PushKit",
      "type": "topic",
      "url": "/documentation/pushkit/responding-to-voip-notifications-from-pushkit"
    },
    "https://developer.apple.com/account/": {
      "identifier": "https://developer.apple.com/account/",
      "title": "Developer Account",
      "titleInlineContent": [
        {
          "text": "Developer Account",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/account/"
    },
    "https://help.apple.com/xcode/mac/current/#/devdfd3d04a1": {
      "identifier": "https://help.apple.com/xcode/mac/current/#/devdfd3d04a1",
      "title": "add the push notifications capability",
      "titleInlineContent": [
        {
          "text": "add the push notifications capability",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://help.apple.com/xcode/mac/current/#/devdfd3d04a1"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Registration",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pushkit/documentation/PushKit/PKPushRegistry",
        "doc://com.apple.pushkit/documentation/PushKit/PKPushRegistryDelegate",
        "doc://com.apple.pushkit/documentation/PushKit/PKPushCredentials"
      ],
      "title": "Registration"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Registration",
              "generated": true,
              "identifiers": [
                "doc://com.apple.pushkit/documentation/PushKit/PKPushRegistry",
                "doc://com.apple.pushkit/documentation/PushKit/PKPushRegistryDelegate",
                "doc://com.apple.pushkit/documentation/PushKit/PKPushCredentials"
              ],
              "title": "Registration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushkit~1documentation~1PushKit~1PKPushRegistryDelegate/title",
          "value": "PKPushRegistryDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushkit~1documentation~1PushKit~1PKPushRegistryDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPushRegistryDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushkit~1documentation~1PushKit~1PKPushRegistryDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPushRegistryDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushkit~1documentation~1PushKit~1PKPushRegistry~1desiredPushTypes/title",
          "value": "desiredPushTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushkit~1documentation~1PushKit~1PKPushRegistry~1desiredPushTypes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "desiredPushTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushkit~1documentation~1PushKit~1PKPushCredentials/title",
          "value": "PKPushCredentials"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushkit~1documentation~1PushKit~1PKPushCredentials/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPushCredentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushkit~1documentation~1PushKit~1PKPushCredentials/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPushCredentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushkit~1documentation~1PushKit~1PKPushRegistry/title",
          "value": "PKPushRegistry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushkit~1documentation~1PushKit~1PKPushRegistry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPushRegistry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushkit~1documentation~1PushKit~1PKPushRegistry/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPushRegistry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushkit~1documentation~1PushKit~1PKPushRegistryDelegate~1pushRegistry(_:didUpdate:for:)/title",
          "value": "pushRegistry:didUpdatePushCredentials:forType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushkit~1documentation~1PushKit~1PKPushRegistryDelegate~1pushRegistry(_:didUpdate:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pushRegistry:didUpdatePushCredentials:forType:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pushkit/supporting-pushkit-notifications-in-your-app"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/pushkit/supporting-pushkit-notifications-in-your-app"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
