{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://FSKit/documentation/FSKit",
        "doc://FSKit/documentation/FSKit/FSVolume/AccessMask"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/OptionSet-Implementations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "FSKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "OptionSet Implementations"
  },
  "references": {
    "doc://FSKit/documentation/FSKit": {
      "abstract": [
        {
          "text": "Implement a file system that runs in user space.",
          "type": "text"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit",
      "kind": "symbol",
      "role": "collection",
      "title": "FSKit",
      "type": "topic",
      "url": "/documentation/fskit"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/AccessMask": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AccessMask"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/AccessMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AccessMask"
        }
      ],
      "role": "symbol",
      "title": "FSVolume.AccessMask",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/accessmask"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/contains(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether a given element is a",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "member of the option set.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "Self",
            "type": "codeVoice"
          },
          {
            "text": " is ",
            "type": "text"
          },
          {
            "code": "Self.Element",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contains"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/contains(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "contains(_:)",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/accessmask/contains(_:)"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/formIntersection(_:)": {
      "abstract": [
        {
          "text": "Removes all elements of this option set that are not",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "also present in the given set.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "RawValue",
            "type": "codeVoice"
          },
          {
            "text": " conforms to ",
            "type": "text"
          },
          {
            "code": "FixedWidthInteger",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "formIntersection"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/formIntersection(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "formIntersection(_:)",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/accessmask/formintersection(_:)"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/formSymmetricDifference(_:)": {
      "abstract": [
        {
          "text": "Replaces this set with a new set containing all elements",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "contained in either this set or the given set, but not in both.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "RawValue",
            "type": "codeVoice"
          },
          {
            "text": " conforms to ",
            "type": "text"
          },
          {
            "code": "FixedWidthInteger",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "formSymmetricDifference"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/formSymmetricDifference(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "formSymmetricDifference(_:)",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/accessmask/formsymmetricdifference(_:)"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/formUnion(_:)": {
      "abstract": [
        {
          "text": "Inserts the elements of another set into this option set.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "RawValue",
            "type": "codeVoice"
          },
          {
            "text": " conforms to ",
            "type": "text"
          },
          {
            "code": "FixedWidthInteger",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "formUnion"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/formUnion(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "formUnion(_:)",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/accessmask/formunion(_:)"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/init()": {
      "abstract": [
        {
          "text": "Creates an empty option set.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "RawValue",
            "type": "codeVoice"
          },
          {
            "text": " conforms to ",
            "type": "text"
          },
          {
            "code": "FixedWidthInteger",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/accessmask/init()"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/insert(_:)": {
      "abstract": [
        {
          "text": "Adds the given element to the option set if it is not already a member.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "Self",
            "type": "codeVoice"
          },
          {
            "text": " is ",
            "type": "text"
          },
          {
            "code": "Self.Element",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insert"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": ") -> (inserted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", memberAfterInsert"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/insert(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "insert(_:)",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/accessmask/insert(_:)"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/intersection(_:)": {
      "abstract": [
        {
          "text": "Returns a new option set with only the elements contained in both this",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "set and the given set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "intersection"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/intersection(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "intersection(_:)",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/accessmask/intersection(_:)"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/remove(_:)": {
      "abstract": [
        {
          "text": "Removes the given element and all elements subsumed by it.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "Self",
            "type": "codeVoice"
          },
          {
            "text": " is ",
            "type": "text"
          },
          {
            "code": "Self.Element",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remove"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/remove(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "remove(_:)",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/accessmask/remove(_:)"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/symmetricDifference(_:)": {
      "abstract": [
        {
          "text": "Returns a new option set with the elements contained in this set or in",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "the given set, but not in both.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "symmetricDifference"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/symmetricDifference(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "symmetricDifference(_:)",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/accessmask/symmetricdifference(_:)"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/union(_:)": {
      "abstract": [
        {
          "text": "Returns a new option set of the elements contained in this set, in the",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "given set, or in both.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "union"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/union(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "union(_:)",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/accessmask/union(_:)"
    },
    "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/update(with:)": {
      "abstract": [
        {
          "text": "Inserts the given element into the set.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "Self",
            "type": "codeVoice"
          },
          {
            "text": " is ",
            "type": "text"
          },
          {
            "code": "Self.Element",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "update"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/update(with:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "update(with:)",
      "type": "topic",
      "url": "/documentation/fskit/fsvolume/accessmask/update(with:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/init()"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/contains(_:)",
        "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/formIntersection(_:)",
        "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/formSymmetricDifference(_:)",
        "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/formUnion(_:)",
        "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/insert(_:)",
        "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/intersection(_:)",
        "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/remove(_:)",
        "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/symmetricDifference(_:)",
        "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/union(_:)",
        "doc://FSKit/documentation/FSKit/FSVolume/AccessMask/update(with:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1AccessMask/title",
          "value": "FSAccessMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1AccessMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSAccessMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSVolume~1AccessMask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSAccessMask"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/fskit/fsvolume/accessmask/optionset-implementations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
