{
  "abstract": [
    {
      "text": "A code that indicates the user isn’t a subscriber, but subscriptions are available.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INMediaUserContext",
        "doc://com.apple.sirikit/documentation/Intents/INMediaUserContext/SubscriptionStatus-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INMediaUserContext/SubscriptionStatus-swift.enum/notSubscribed"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INMediaUserContextSubscriptionStatus@INMediaUserContextSubscriptionStatusNotSubscribed",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "notSubscribed"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INMediaUserContextSubscriptionStatusNotSubscribed"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "INMediaUserContext.SubscriptionStatus.notSubscribed"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "notSubscribed"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaUserContext": {
      "abstract": [
        {
          "text": "An object that provides user information to Siri.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INMediaUserContext"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaUserContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaUserContext"
        }
      ],
      "role": "symbol",
      "title": "INMediaUserContext",
      "type": "topic",
      "url": "/documentation/intents/inmediausercontext"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaUserContext/SubscriptionStatus-swift.enum": {
      "abstract": [
        {
          "text": "Constants that describe the current description status.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SubscriptionStatus"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaUserContext/SubscriptionStatus-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SubscriptionStatus"
        }
      ],
      "role": "symbol",
      "title": "INMediaUserContext.SubscriptionStatus",
      "type": "topic",
      "url": "/documentation/intents/inmediausercontext/subscriptionstatus-swift.enum"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaUserContext/SubscriptionStatus-swift.enum/notSubscribed": {
      "abstract": [
        {
          "text": "A code that indicates the user isn’t a subscriber, but subscriptions are available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notSubscribed"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaUserContext/SubscriptionStatus-swift.enum/notSubscribed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaUserContextSubscriptionStatusNotSubscribed"
        }
      ],
      "role": "symbol",
      "title": "INMediaUserContext.SubscriptionStatus.notSubscribed",
      "type": "topic",
      "url": "/documentation/intents/inmediausercontext/subscriptionstatus-swift.enum/notsubscribed"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaUserContext/SubscriptionStatus-swift.enum/subscribed": {
      "abstract": [
        {
          "text": "A code that indicates the user currently has a subscription.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subscribed"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaUserContext/SubscriptionStatus-swift.enum/subscribed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaUserContextSubscriptionStatusSubscribed"
        }
      ],
      "role": "symbol",
      "title": "INMediaUserContext.SubscriptionStatus.subscribed",
      "type": "topic",
      "url": "/documentation/intents/inmediausercontext/subscriptionstatus-swift.enum/subscribed"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaUserContext/SubscriptionStatus-swift.enum/unknown": {
      "abstract": [
        {
          "text": "A code that indicates the app doesn’t offer subscriptions or the subscription status is unavailable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaUserContext/SubscriptionStatus-swift.enum/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaUserContextSubscriptionStatusUnknown"
        }
      ],
      "role": "symbol",
      "title": "INMediaUserContext.SubscriptionStatus.unknown",
      "type": "topic",
      "url": "/documentation/intents/inmediausercontext/subscriptionstatus-swift.enum/unknown"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INMediaUserContext/SubscriptionStatus-swift.enum/unknown",
        "doc://com.apple.sirikit/documentation/Intents/INMediaUserContext/SubscriptionStatus-swift.enum/subscribed"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INMediaUserContextSubscriptionStatusNotSubscribed"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaUserContextSubscriptionStatusNotSubscribed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INMediaUserContext/SubscriptionStatus-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INMediaUserContext/SubscriptionStatus-swift.enum/unknown",
                "doc://com.apple.sirikit/documentation/Intents/INMediaUserContext/SubscriptionStatus-swift.enum/subscribed"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "INMediaUserContextSubscriptionStatusNotSubscribed"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaUserContext~1SubscriptionStatus-swift.enum~1unknown/title",
          "value": "INMediaUserContextSubscriptionStatusUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaUserContext~1SubscriptionStatus-swift.enum~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaUserContextSubscriptionStatusUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaUserContext~1SubscriptionStatus-swift.enum~1notSubscribed/title",
          "value": "INMediaUserContextSubscriptionStatusNotSubscribed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaUserContext~1SubscriptionStatus-swift.enum~1notSubscribed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaUserContextSubscriptionStatusNotSubscribed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaUserContext~1SubscriptionStatus-swift.enum~1subscribed/title",
          "value": "INMediaUserContextSubscriptionStatusSubscribed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaUserContext~1SubscriptionStatus-swift.enum~1subscribed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaUserContextSubscriptionStatusSubscribed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaUserContext~1SubscriptionStatus-swift.enum/title",
          "value": "INMediaUserContextSubscriptionStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaUserContext~1SubscriptionStatus-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaUserContextSubscriptionStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaUserContext~1SubscriptionStatus-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaUserContextSubscriptionStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaUserContext/title",
          "value": "INMediaUserContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaUserContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaUserContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaUserContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaUserContext"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inmediausercontext/subscriptionstatus-swift.enum/notsubscribed"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inmediausercontext/subscriptionstatus-swift.enum/notsubscribed"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
