{
  "abstract": [
    {
      "text": "Possible error values that can be returned from LinkPresentation APIs.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Link-Presentation/documentation/LinkPresentation",
        "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@LPErrorCode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "Link Presentation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "LPError.Code"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Code"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.Link-Presentation/documentation/LinkPresentation": {
      "abstract": [
        {
          "text": "Fetch, provide, and present rich links in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Link-Presentation/documentation/LinkPresentation",
      "kind": "symbol",
      "role": "collection",
      "title": "Link Presentation",
      "type": "topic",
      "url": "/documentation/linkpresentation"
    },
    "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError": {
      "abstract": [
        {
          "text": "An error returned by the LinkPresentation framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LPError"
        }
      ],
      "identifier": "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LPError"
        }
      ],
      "role": "symbol",
      "title": "LPError",
      "type": "topic",
      "url": "/documentation/linkpresentation/lperror"
    },
    "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code": {
      "abstract": [
        {
          "text": "Possible error values that can be returned from LinkPresentation APIs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "LPError.Code",
      "type": "topic",
      "url": "/documentation/linkpresentation/lperror/code"
    },
    "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/linkpresentation/lperror/code/init(rawvalue:)"
    },
    "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/metadataFetchCancelled": {
      "abstract": [
        {
          "text": "An error indicating that the metadata fetch was canceled by the client.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metadataFetchCancelled"
        }
      ],
      "identifier": "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/metadataFetchCancelled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LPErrorMetadataFetchCancelled"
        }
      ],
      "role": "symbol",
      "title": "LPError.Code.metadataFetchCancelled",
      "type": "topic",
      "url": "/documentation/linkpresentation/lperror/code/metadatafetchcancelled"
    },
    "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/metadataFetchFailed": {
      "abstract": [
        {
          "text": "An error indicating that a metadata fetch failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metadataFetchFailed"
        }
      ],
      "identifier": "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/metadataFetchFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LPErrorMetadataFetchFailed"
        }
      ],
      "role": "symbol",
      "title": "LPError.Code.metadataFetchFailed",
      "type": "topic",
      "url": "/documentation/linkpresentation/lperror/code/metadatafetchfailed"
    },
    "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/metadataFetchNotAllowed": {
      "abstract": [
        {
          "text": "An error indicating that the metadata fetch was not allowed due to system policies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metadataFetchNotAllowed"
        }
      ],
      "identifier": "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/metadataFetchNotAllowed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LPErrorMetadataFetchNotAllowed"
        }
      ],
      "role": "symbol",
      "title": "LPError.Code.metadataFetchNotAllowed",
      "type": "topic",
      "url": "/documentation/linkpresentation/lperror/code/metadatafetchnotallowed"
    },
    "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/metadataFetchTimedOut": {
      "abstract": [
        {
          "text": "An error indicating that the metadata fetch took longer than allowed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metadataFetchTimedOut"
        }
      ],
      "identifier": "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/metadataFetchTimedOut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LPErrorMetadataFetchTimedOut"
        }
      ],
      "role": "symbol",
      "title": "LPError.Code.metadataFetchTimedOut",
      "type": "topic",
      "url": "/documentation/linkpresentation/lperror/code/metadatafetchtimedout"
    },
    "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/unknown": {
      "abstract": [
        {
          "text": "An unknown error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LPErrorUnknown"
        }
      ],
      "role": "symbol",
      "title": "LPError.Code.unknown",
      "type": "topic",
      "url": "/documentation/linkpresentation/lperror/code/unknown"
    },
    "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPErrorDomain": {
      "abstract": [
        {
          "text": "The domain for Link Presentation errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LPErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LPErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "LPErrorDomain",
      "type": "topic",
      "url": "/documentation/linkpresentation/lperrordomain"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError",
        "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPErrorDomain"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Error-cases",
      "identifiers": [
        "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/metadataFetchCancelled",
        "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/metadataFetchFailed",
        "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/metadataFetchTimedOut",
        "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/unknown"
      ],
      "title": "Error cases"
    },
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/metadataFetchNotAllowed"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "LPErrorCode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LPErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LPErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.Link-Presentation/documentation/LinkPresentation"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Error-cases",
              "identifiers": [
                "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/metadataFetchCancelled",
                "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/metadataFetchFailed",
                "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/metadataFetchTimedOut",
                "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/unknown"
              ],
              "title": "Error cases"
            },
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code/metadataFetchNotAllowed"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPErrorDomain"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "LPErrorCode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPError~1Code/title",
          "value": "LPErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LPErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LPErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPError~1Code~1metadataFetchFailed/title",
          "value": "LPErrorMetadataFetchFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPError~1Code~1metadataFetchFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LPErrorMetadataFetchFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPError~1Code~1metadataFetchTimedOut/title",
          "value": "LPErrorMetadataFetchTimedOut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPError~1Code~1metadataFetchTimedOut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LPErrorMetadataFetchTimedOut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPError~1Code~1metadataFetchCancelled/title",
          "value": "LPErrorMetadataFetchCancelled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPError~1Code~1metadataFetchCancelled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LPErrorMetadataFetchCancelled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPError~1Code~1metadataFetchNotAllowed/title",
          "value": "LPErrorMetadataFetchNotAllowed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPError~1Code~1metadataFetchNotAllowed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LPErrorMetadataFetchNotAllowed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPError~1Code~1unknown/title",
          "value": "LPErrorUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPError~1Code~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LPErrorUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPErrorDomain/title",
          "value": "LPErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LPErrorDomain"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/linkpresentation/lperror/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/linkpresentation/lperror/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
