{
  "abstract": [
    {
      "text": "A joint name that represents the back of the right knee.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.vision/documentation/Vision",
        "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation",
        "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName/rightBackKnee"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "Vision",
    "externalID": "c:@VNAnimalBodyPoseObservationJointNameRightBackKnee",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "rightBackKnee"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)VNAnimalBodyPoseObservation",
        "text": "VNAnimalBodyPoseObservation"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@VNAnimalBodyPoseObservationJointName",
        "text": "JointName"
      }
    ],
    "modules": [
      {
        "name": "Vision"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VNAnimalBodyPoseObservationJointNameRightBackKnee"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "rightBackKnee"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "rightBackKnee"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)VNAnimalBodyPoseObservation",
              "text": "VNAnimalBodyPoseObservation"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@VNAnimalBodyPoseObservationJointName",
              "text": "JointName"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.vision/documentation/Vision": {
      "abstract": [
        {
          "text": "Apply computer vision algorithms to perform a variety of tasks on input images and videos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision",
      "kind": "symbol",
      "role": "collection",
      "title": "Vision",
      "type": "topic",
      "url": "/documentation/vision"
    },
    "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation": {
      "abstract": [
        {
          "text": "An observation that provides the animal body points the analysis recognizes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNAnimalBodyPoseObservation"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNAnimalBodyPoseObservation"
        }
      ],
      "role": "symbol",
      "title": "VNAnimalBodyPoseObservation",
      "type": "topic",
      "url": "/documentation/vision/vnanimalbodyposeobservation"
    },
    "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName": {
      "abstract": [
        {
          "text": "The joint names for an animal body pose.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JointName"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JointName"
        }
      ],
      "role": "symbol",
      "title": "VNAnimalBodyPoseObservation.JointName",
      "type": "topic",
      "url": "/documentation/vision/vnanimalbodyposeobservation/jointname"
    },
    "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName/leftBackElbow": {
      "abstract": [
        {
          "text": "A joint name that represents the back of the left elbow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftBackElbow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNAnimalBodyPoseObservation",
          "text": "VNAnimalBodyPoseObservation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNAnimalBodyPoseObservationJointName",
          "text": "JointName"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName/leftBackElbow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNAnimalBodyPoseObservationJointNameLeftBackElbow"
        }
      ],
      "role": "symbol",
      "title": "leftBackElbow",
      "type": "topic",
      "url": "/documentation/vision/vnanimalbodyposeobservation/jointname/leftbackelbow"
    },
    "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName/leftBackKnee": {
      "abstract": [
        {
          "text": "A joint name that represents the back of the left knee.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftBackKnee"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNAnimalBodyPoseObservation",
          "text": "VNAnimalBodyPoseObservation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNAnimalBodyPoseObservationJointName",
          "text": "JointName"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName/leftBackKnee",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNAnimalBodyPoseObservationJointNameLeftBackKnee"
        }
      ],
      "role": "symbol",
      "title": "leftBackKnee",
      "type": "topic",
      "url": "/documentation/vision/vnanimalbodyposeobservation/jointname/leftbackknee"
    },
    "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName/leftBackPaw": {
      "abstract": [
        {
          "text": "A joint name that represents the back of the left paw.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftBackPaw"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNAnimalBodyPoseObservation",
          "text": "VNAnimalBodyPoseObservation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNAnimalBodyPoseObservationJointName",
          "text": "JointName"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName/leftBackPaw",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNAnimalBodyPoseObservationJointNameLeftBackPaw"
        }
      ],
      "role": "symbol",
      "title": "leftBackPaw",
      "type": "topic",
      "url": "/documentation/vision/vnanimalbodyposeobservation/jointname/leftbackpaw"
    },
    "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName/leftFrontElbow": {
      "abstract": [
        {
          "text": "A joint name that represents the front of the left elbow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftFrontElbow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNAnimalBodyPoseObservation",
          "text": "VNAnimalBodyPoseObservation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNAnimalBodyPoseObservationJointName",
          "text": "JointName"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName/leftFrontElbow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNAnimalBodyPoseObservationJointNameLeftFrontElbow"
        }
      ],
      "role": "symbol",
      "title": "leftFrontElbow",
      "type": "topic",
      "url": "/documentation/vision/vnanimalbodyposeobservation/jointname/leftfrontelbow"
    },
    "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName/leftFrontKnee": {
      "abstract": [
        {
          "text": "A joint name that represents the front of the left knee.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftFrontKnee"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNAnimalBodyPoseObservation",
          "text": "VNAnimalBodyPoseObservation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNAnimalBodyPoseObservationJointName",
          "text": "JointName"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName/leftFrontKnee",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNAnimalBodyPoseObservationJointNameLeftFrontKnee"
        }
      ],
      "role": "symbol",
      "title": "leftFrontKnee",
      "type": "topic",
      "url": "/documentation/vision/vnanimalbodyposeobservation/jointname/leftfrontknee"
    },
    "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName/leftFrontPaw": {
      "abstract": [
        {
          "text": "A joint name that represents the front of the left paw.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftFrontPaw"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNAnimalBodyPoseObservation",
          "text": "VNAnimalBodyPoseObservation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNAnimalBodyPoseObservationJointName",
          "text": "JointName"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName/leftFrontPaw",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNAnimalBodyPoseObservationJointNameLeftFrontPaw"
        }
      ],
      "role": "symbol",
      "title": "leftFrontPaw",
      "type": "topic",
      "url": "/documentation/vision/vnanimalbodyposeobservation/jointname/leftfrontpaw"
    },
    "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName/rightBackElbow": {
      "abstract": [
        {
          "text": "A joint name that represents the back of the right elbow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightBackElbow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNAnimalBodyPoseObservation",
          "text": "VNAnimalBodyPoseObservation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNAnimalBodyPoseObservationJointName",
          "text": "JointName"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName/rightBackElbow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNAnimalBodyPoseObservationJointNameRightBackElbow"
        }
      ],
      "role": "symbol",
      "title": "rightBackElbow",
      "type": "topic",
      "url": "/documentation/vision/vnanimalbodyposeobservation/jointname/rightbackelbow"
    },
    "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName/rightBackKnee": {
      "abstract": [
        {
          "text": "A joint name that represents the back of the right knee.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightBackKnee"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNAnimalBodyPoseObservation",
          "text": "VNAnimalBodyPoseObservation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNAnimalBodyPoseObservationJointName",
          "text": "JointName"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName/rightBackKnee",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNAnimalBodyPoseObservationJointNameRightBackKnee"
        }
      ],
      "role": "symbol",
      "title": "rightBackKnee",
      "type": "topic",
      "url": "/documentation/vision/vnanimalbodyposeobservation/jointname/rightbackknee"
    },
    "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName/rightBackPaw": {
      "abstract": [
        {
          "text": "A joint name that represents the back of the right paw.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightBackPaw"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNAnimalBodyPoseObservation",
          "text": "VNAnimalBodyPoseObservation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNAnimalBodyPoseObservationJointName",
          "text": "JointName"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName/rightBackPaw",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNAnimalBodyPoseObservationJointNameRightBackPaw"
        }
      ],
      "role": "symbol",
      "title": "rightBackPaw",
      "type": "topic",
      "url": "/documentation/vision/vnanimalbodyposeobservation/jointname/rightbackpaw"
    },
    "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName/rightFrontElbow": {
      "abstract": [
        {
          "text": "A joint name that represents the front of the right elbow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightFrontElbow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNAnimalBodyPoseObservation",
          "text": "VNAnimalBodyPoseObservation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNAnimalBodyPoseObservationJointName",
          "text": "JointName"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName/rightFrontElbow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNAnimalBodyPoseObservationJointNameRightFrontElbow"
        }
      ],
      "role": "symbol",
      "title": "rightFrontElbow",
      "type": "topic",
      "url": "/documentation/vision/vnanimalbodyposeobservation/jointname/rightfrontelbow"
    },
    "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName/rightFrontKnee": {
      "abstract": [
        {
          "text": "A joint name that represents the front of the right knee.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightFrontKnee"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNAnimalBodyPoseObservation",
          "text": "VNAnimalBodyPoseObservation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNAnimalBodyPoseObservationJointName",
          "text": "JointName"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName/rightFrontKnee",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNAnimalBodyPoseObservationJointNameRightFrontKnee"
        }
      ],
      "role": "symbol",
      "title": "rightFrontKnee",
      "type": "topic",
      "url": "/documentation/vision/vnanimalbodyposeobservation/jointname/rightfrontknee"
    },
    "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName/rightFrontPaw": {
      "abstract": [
        {
          "text": "A joint name that represents the front of the right paw.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightFrontPaw"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNAnimalBodyPoseObservation",
          "text": "VNAnimalBodyPoseObservation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNAnimalBodyPoseObservationJointName",
          "text": "JointName"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName/rightFrontPaw",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNAnimalBodyPoseObservationJointNameRightFrontPaw"
        }
      ],
      "role": "symbol",
      "title": "rightFrontPaw",
      "type": "topic",
      "url": "/documentation/vision/vnanimalbodyposeobservation/jointname/rightfrontpaw"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-Leg-Joint-Names",
      "generated": true,
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName/leftBackElbow",
        "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName/leftFrontElbow",
        "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName/rightFrontElbow",
        "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName/rightBackElbow",
        "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName/leftBackKnee",
        "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName/leftFrontKnee",
        "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName/rightFrontKnee",
        "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName/leftBackPaw",
        "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName/leftFrontPaw",
        "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName/rightBackPaw",
        "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName/rightFrontPaw"
      ],
      "title": "Getting the Leg Joint Names"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VNAnimalBodyPoseObservationJointNameRightBackKnee"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNAnimalBodyPoseObservationJointNameRightBackKnee"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.vision/documentation/Vision"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-Leg-Joint-Names",
              "generated": true,
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName/leftBackElbow",
                "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName/leftFrontElbow",
                "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName/rightFrontElbow",
                "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName/rightBackElbow",
                "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName/leftBackKnee",
                "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName/leftFrontKnee",
                "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName/rightFrontKnee",
                "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName/leftBackPaw",
                "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName/leftFrontPaw",
                "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName/rightBackPaw",
                "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName/rightFrontPaw"
              ],
              "title": "Getting the Leg Joint Names"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.vision/documentation/Vision/VNAnimalBodyPoseObservation/JointName",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@VNAnimalBodyPoseObservationJointName",
                    "text": "VNAnimalBodyPoseObservationJointName"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "VNAnimalBodyPoseObservationJointNameRightBackKnee"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation~1JointName~1leftBackPaw/title",
          "value": "VNAnimalBodyPoseObservationJointNameLeftBackPaw"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation~1JointName~1leftBackPaw/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNAnimalBodyPoseObservationJointNameLeftBackPaw"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation~1JointName/title",
          "value": "VNAnimalBodyPoseObservationJointName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation~1JointName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNAnimalBodyPoseObservationJointName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation~1JointName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNAnimalBodyPoseObservationJointName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation~1JointName~1rightFrontElbow/title",
          "value": "VNAnimalBodyPoseObservationJointNameRightFrontElbow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation~1JointName~1rightFrontElbow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNAnimalBodyPoseObservationJointNameRightFrontElbow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation~1JointName~1leftFrontKnee/title",
          "value": "VNAnimalBodyPoseObservationJointNameLeftFrontKnee"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation~1JointName~1leftFrontKnee/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNAnimalBodyPoseObservationJointNameLeftFrontKnee"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation~1JointName~1rightFrontPaw/title",
          "value": "VNAnimalBodyPoseObservationJointNameRightFrontPaw"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation~1JointName~1rightFrontPaw/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNAnimalBodyPoseObservationJointNameRightFrontPaw"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation~1JointName~1leftFrontElbow/title",
          "value": "VNAnimalBodyPoseObservationJointNameLeftFrontElbow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation~1JointName~1leftFrontElbow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNAnimalBodyPoseObservationJointNameLeftFrontElbow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation~1JointName~1rightFrontKnee/title",
          "value": "VNAnimalBodyPoseObservationJointNameRightFrontKnee"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation~1JointName~1rightFrontKnee/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNAnimalBodyPoseObservationJointNameRightFrontKnee"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation~1JointName~1leftFrontPaw/title",
          "value": "VNAnimalBodyPoseObservationJointNameLeftFrontPaw"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation~1JointName~1leftFrontPaw/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNAnimalBodyPoseObservationJointNameLeftFrontPaw"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation~1JointName~1leftBackElbow/title",
          "value": "VNAnimalBodyPoseObservationJointNameLeftBackElbow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation~1JointName~1leftBackElbow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNAnimalBodyPoseObservationJointNameLeftBackElbow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation~1JointName~1rightBackKnee/title",
          "value": "VNAnimalBodyPoseObservationJointNameRightBackKnee"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation~1JointName~1rightBackKnee/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNAnimalBodyPoseObservationJointNameRightBackKnee"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation/title",
          "value": "VNAnimalBodyPoseObservation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNAnimalBodyPoseObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNAnimalBodyPoseObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation~1JointName~1leftBackKnee/title",
          "value": "VNAnimalBodyPoseObservationJointNameLeftBackKnee"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation~1JointName~1leftBackKnee/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNAnimalBodyPoseObservationJointNameLeftBackKnee"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation~1JointName~1rightBackElbow/title",
          "value": "VNAnimalBodyPoseObservationJointNameRightBackElbow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation~1JointName~1rightBackElbow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNAnimalBodyPoseObservationJointNameRightBackElbow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation~1JointName~1rightBackPaw/title",
          "value": "VNAnimalBodyPoseObservationJointNameRightBackPaw"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNAnimalBodyPoseObservation~1JointName~1rightBackPaw/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNAnimalBodyPoseObservationJointNameRightBackPaw"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/vision/vnanimalbodyposeobservation/jointname/rightbackknee"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/vision/vnanimalbodyposeobservation/jointname/rightbackknee"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
