{
  "abstract": [
    {
      "text": "A closed arrowhead line ending, consisting of a triangle with the acute vertex at the line end and filled with the annotation’s interior color, if any.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pdfkit/documentation/PDFKit",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle/closedArrow"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PDFLineStyle@kPDFLineStyleClosedArrow",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "closedArrow"
      }
    ],
    "modules": [
      {
        "name": "PDFKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kPDFLineStyleClosedArrow"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "PDFLineStyle.closedArrow"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "closedArrow"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit": {
      "abstract": [
        {
          "text": "Display and manipulate PDF documents in your apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PDFKit",
      "type": "topic",
      "url": "/documentation/pdfkit"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle": {
      "abstract": [
        {
          "text": "The following constants specify the available line ending styles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFLineStyle"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFLineStyle"
        }
      ],
      "role": "symbol",
      "title": "PDFLineStyle",
      "type": "topic",
      "url": "/documentation/pdfkit/pdflinestyle"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle/circle": {
      "abstract": [
        {
          "text": "A circular line ending filled with the annotation’s interior color, if any.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "circle"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle/circle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFLineStyleCircle"
        }
      ],
      "role": "symbol",
      "title": "PDFLineStyle.circle",
      "type": "topic",
      "url": "/documentation/pdfkit/pdflinestyle/circle"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle/closedArrow": {
      "abstract": [
        {
          "text": "A closed arrowhead line ending, consisting of a triangle with the acute vertex at the line end and filled with the annotation’s interior color, if any.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "closedArrow"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle/closedArrow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFLineStyleClosedArrow"
        }
      ],
      "role": "symbol",
      "title": "PDFLineStyle.closedArrow",
      "type": "topic",
      "url": "/documentation/pdfkit/pdflinestyle/closedarrow"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle/diamond": {
      "abstract": [
        {
          "text": "A diamond-shaped line ending filled with the annotation’s interior color, if any.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "diamond"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle/diamond",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFLineStyleDiamond"
        }
      ],
      "role": "symbol",
      "title": "PDFLineStyle.diamond",
      "type": "topic",
      "url": "/documentation/pdfkit/pdflinestyle/diamond"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle/none": {
      "abstract": [
        {
          "text": "No line ending.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFLineStyleNone"
        }
      ],
      "role": "symbol",
      "title": "PDFLineStyle.none",
      "type": "topic",
      "url": "/documentation/pdfkit/pdflinestyle/none"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle/openArrow": {
      "abstract": [
        {
          "text": "An open arrowhead line ending, composed from two short lines meeting in an acute angle at the line end.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "openArrow"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle/openArrow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFLineStyleOpenArrow"
        }
      ],
      "role": "symbol",
      "title": "PDFLineStyle.openArrow",
      "type": "topic",
      "url": "/documentation/pdfkit/pdflinestyle/openarrow"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle/square": {
      "abstract": [
        {
          "text": "A square line ending filled with the annotation’s interior color, if any.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "square"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle/square",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFLineStyleSquare"
        }
      ],
      "role": "symbol",
      "title": "PDFLineStyle.square",
      "type": "topic",
      "url": "/documentation/pdfkit/pdflinestyle/square"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle/none",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle/square",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle/circle",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle/diamond",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle/openArrow"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kPDFLineStyleClosedArrow"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFLineStyleClosedArrow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.pdfkit/documentation/PDFKit",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle/none",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle/square",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle/circle",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle/diamond",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFLineStyle/openArrow"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kPDFLineStyleClosedArrow"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFLineStyle/title",
          "value": "PDFLineStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFLineStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFLineStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFLineStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFLineStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFLineStyle~1none/title",
          "value": "kPDFLineStyleNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFLineStyle~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFLineStyleNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFLineStyle~1circle/title",
          "value": "kPDFLineStyleCircle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFLineStyle~1circle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFLineStyleCircle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFLineStyle~1diamond/title",
          "value": "kPDFLineStyleDiamond"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFLineStyle~1diamond/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFLineStyleDiamond"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFLineStyle~1square/title",
          "value": "kPDFLineStyleSquare"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFLineStyle~1square/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFLineStyleSquare"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFLineStyle~1closedArrow/title",
          "value": "kPDFLineStyleClosedArrow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFLineStyle~1closedArrow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFLineStyleClosedArrow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFLineStyle~1openArrow/title",
          "value": "kPDFLineStyleOpenArrow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFLineStyle~1openArrow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFLineStyleOpenArrow"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pdfkit/pdflinestyle/closedarrow"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/pdfkit/pdflinestyle/closedarrow"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
