{
  "abstract": [
    {
      "text": "Starts capturing any of your app’s Metal commands that are in the specified capture scope.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.metal/documentation/Metal/MTLCaptureManager/startCapture(with:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLCaptureManager"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLCaptureManager/startCapture(scope:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MTLCaptureManager(im)startCaptureWithScope:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "startCapture"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "scope"
      },
      {
        "kind": "text",
        "text": ": any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(pl)MTLCaptureScope",
        "text": "MTLCaptureScope"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "startCaptureWithScope:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.0",
        "introducedAt": "11.0",
        "message": "Use startCaptureWithDescriptor:error: instead",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.0",
        "introducedAt": "11.0",
        "message": "Use startCaptureWithDescriptor:error: instead",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "message": "Use startCaptureWithDescriptor:error: instead",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.15",
        "introducedAt": "10.13",
        "message": "Use startCaptureWithDescriptor:error: instead",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.0",
        "introducedAt": "11.0",
        "message": "Use startCaptureWithDescriptor:error: instead",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "Use startCaptureWithDescriptor:error: instead",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "startCapture(scope:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "startCapture"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "scope"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "captureScope"
            },
            {
              "kind": "text",
              "text": ": any "
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLCaptureScope",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)MTLCaptureScope",
              "text": "MTLCaptureScope"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The capture scope to use.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "captureScope"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCaptureManager": {
      "abstract": [
        {
          "text": "An instance you use to capture Metal command data in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLCaptureManager"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCaptureManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCaptureManager"
        }
      ],
      "role": "symbol",
      "title": "MTLCaptureManager",
      "type": "topic",
      "url": "/documentation/metal/mtlcapturemanager"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCaptureManager/startCapture(commandQueue:)": {
      "abstract": [
        {
          "text": "Starts capturing any of your app’s Metal commands that are executed by the command queue.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startCapture"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "commandQueue"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLCommandQueue",
          "text": "MTLCommandQueue"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCaptureManager/startCapture(commandQueue:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startCaptureWithCommandQueue:"
        }
      ],
      "role": "symbol",
      "title": "startCapture(commandQueue:)",
      "type": "topic",
      "url": "/documentation/metal/mtlcapturemanager/startcapture(commandqueue:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCaptureManager/startCapture(device:)": {
      "abstract": [
        {
          "text": "Starts capturing any of your app’s Metal commands that are executed by the device object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startCapture"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "device"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLDevice",
          "text": "MTLDevice"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCaptureManager/startCapture(device:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startCaptureWithDevice:"
        }
      ],
      "role": "symbol",
      "title": "startCapture(device:)",
      "type": "topic",
      "url": "/documentation/metal/mtlcapturemanager/startcapture(device:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCaptureManager/startCapture(scope:)": {
      "abstract": [
        {
          "text": "Starts capturing any of your app’s Metal commands that are in the specified capture scope.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startCapture"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "scope"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLCaptureScope",
          "text": "MTLCaptureScope"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCaptureManager/startCapture(scope:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startCaptureWithScope:"
        }
      ],
      "role": "symbol",
      "title": "startCapture(scope:)",
      "type": "topic",
      "url": "/documentation/metal/mtlcapturemanager/startcapture(scope:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCaptureManager/startCapture(with:)": {
      "abstract": [
        {
          "text": "Starts capturing any of your app’s Metal commands, with the capture session defined by a descriptor object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startCapture"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTLCaptureDescriptor",
          "text": "MTLCaptureDescriptor"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCaptureManager/startCapture(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startCaptureWithDescriptor:error:"
        }
      ],
      "role": "symbol",
      "title": "startCapture(with:)",
      "type": "topic",
      "url": "/documentation/metal/mtlcapturemanager/startcapture(with:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCaptureScope": {
      "abstract": [
        {
          "text": "A protocol that defines custom boundaries for a GPU frame capture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLCaptureScope"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCaptureScope",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCaptureScope"
        }
      ],
      "role": "symbol",
      "title": "MTLCaptureScope",
      "type": "topic",
      "url": "/documentation/metal/mtlcapturescope"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Starting-Capture",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLCaptureManager/startCapture(with:)",
        "doc://com.apple.metal/documentation/Metal/MTLCaptureManager/startCapture(device:)",
        "doc://com.apple.metal/documentation/Metal/MTLCaptureManager/startCapture(commandQueue:)"
      ],
      "title": "Starting Capture"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.0",
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.0",
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.15",
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.0",
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "startCaptureWithScope:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startCaptureWithScope:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal",
                "doc://com.apple.metal/documentation/Metal/MTLCaptureManager"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Starting-Capture",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLCaptureManager/startCapture(with:)",
                "doc://com.apple.metal/documentation/Metal/MTLCaptureManager/startCapture(device:)",
                "doc://com.apple.metal/documentation/Metal/MTLCaptureManager/startCapture(commandQueue:)"
              ],
              "title": "Starting Capture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "startCaptureWithScope:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Qoobjc(pl)MTLCaptureScope",
                    "text": "id<MTLCaptureScope>"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "captureScope"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The capture scope to use.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "captureScope"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.metal/documentation/Metal/MTLCaptureManager/startCapture(with:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " instead.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCaptureManager~1startCapture(with:)/title",
          "value": "startCaptureWithDescriptor:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCaptureManager~1startCapture(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startCaptureWithDescriptor:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCaptureManager~1startCapture(commandQueue:)/title",
          "value": "startCaptureWithCommandQueue:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCaptureManager~1startCapture(commandQueue:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startCaptureWithCommandQueue:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCaptureScope/title",
          "value": "MTLCaptureScope"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCaptureScope/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCaptureScope"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCaptureScope/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCaptureScope"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCaptureManager/title",
          "value": "MTLCaptureManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCaptureManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCaptureManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCaptureManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCaptureManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCaptureManager~1startCapture(device:)/title",
          "value": "startCaptureWithDevice:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCaptureManager~1startCapture(device:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startCaptureWithDevice:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCaptureManager~1startCapture(scope:)/title",
          "value": "startCaptureWithScope:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCaptureManager~1startCapture(scope:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startCaptureWithScope:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlcapturemanager/startcapture(scope:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlcapturemanager/startcapture(scope:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
