{
  "abstract": [
    {
      "text": "Codes that identify errors in Nearby Interaction.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NIErrorCode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "Nearby Interaction"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.3",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "NIError.Code"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Code"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This enumeration uses ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NISessionDelegate/session(_:didInvalidateWith:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to collect the errors the framework provides to the delegate.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction": {
      "abstract": [
        {
          "text": "Locate and interact with nearby devices using identifiers, distance, and direction.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction",
      "kind": "symbol",
      "role": "collection",
      "title": "Nearby Interaction",
      "type": "topic",
      "url": "/documentation/nearbyinteraction"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError": {
      "abstract": [
        {
          "text": "An error Nearby Interaction reports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NIError"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NIError"
        }
      ],
      "role": "symbol",
      "title": "NIError",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nierror"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code": {
      "abstract": [
        {
          "text": "Codes that identify errors in Nearby Interaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "NIError.Code",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nierror/code"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/accessoryPeerDeviceUnavailable": {
      "abstract": [
        {
          "text": "An error that indicates the peer Bluetooth accessory isn’t connected or paired.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessoryPeerDeviceUnavailable"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/accessoryPeerDeviceUnavailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NIErrorCodeAccessoryPeerDeviceUnavailable"
        }
      ],
      "role": "symbol",
      "title": "NIError.Code.accessoryPeerDeviceUnavailable",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nierror/code/accessorypeerdeviceunavailable"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/activeExtendedDistanceSessionsLimitExceeded": {
      "abstract": [
        {
          "text": "An error that indicates the device exceeds the available number of active extended distance sessions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activeExtendedDistanceSessionsLimitExceeded"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/activeExtendedDistanceSessionsLimitExceeded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NIErrorCodeActiveExtendedDistanceSessionsLimitExceeded"
        }
      ],
      "role": "symbol",
      "title": "NIError.Code.activeExtendedDistanceSessionsLimitExceeded",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nierror/code/activeextendeddistancesessionslimitexceeded"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/activeSessionsLimitExceeded": {
      "abstract": [
        {
          "text": "An error code that indicates that the app reached the maximum number of sessions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activeSessionsLimitExceeded"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/activeSessionsLimitExceeded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NIErrorCodeActiveSessionsLimitExceeded"
        }
      ],
      "role": "symbol",
      "title": "NIError.Code.activeSessionsLimitExceeded",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nierror/code/activesessionslimitexceeded"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/incompatiblePeerDevice": {
      "abstract": [
        {
          "text": "An error that indicates the peer device isn’t compatible with this Nearby Interaction session instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "incompatiblePeerDevice"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/incompatiblePeerDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NIErrorCodeIncompatiblePeerDevice"
        }
      ],
      "role": "symbol",
      "title": "NIError.Code.incompatiblePeerDevice",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nierror/code/incompatiblepeerdevice"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nierror/code/init(rawvalue:)"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/invalidARConfiguration": {
      "abstract": [
        {
          "text": "An error that indicates the framework can’t begin Camera Assistance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidARConfiguration"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/invalidARConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NIErrorCodeInvalidARConfiguration"
        }
      ],
      "role": "symbol",
      "title": "NIError.Code.invalidARConfiguration",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nierror/code/invalidarconfiguration"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/invalidConfiguration": {
      "abstract": [
        {
          "text": "An error code that indicates that the nearby-interaction configuration isn’t valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidConfiguration"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/invalidConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NIErrorCodeInvalidConfiguration"
        }
      ],
      "role": "symbol",
      "title": "NIError.Code.invalidConfiguration",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nierror/code/invalidconfiguration"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/resourceUsageTimeout": {
      "abstract": [
        {
          "text": "An error code that indicates that the framework timed out the session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resourceUsageTimeout"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/resourceUsageTimeout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NIErrorCodeResourceUsageTimeout"
        }
      ],
      "role": "symbol",
      "title": "NIError.Code.resourceUsageTimeout",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nierror/code/resourceusagetimeout"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/sessionFailed": {
      "abstract": [
        {
          "text": "An error code that indicates that the session failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sessionFailed"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/sessionFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NIErrorCodeSessionFailed"
        }
      ],
      "role": "symbol",
      "title": "NIError.Code.sessionFailed",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nierror/code/sessionfailed"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/unsupportedPlatform": {
      "abstract": [
        {
          "text": "An error code that indicates that the framework doesn’t support the device platform.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedPlatform"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/unsupportedPlatform",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NIErrorCodeUnsupportedPlatform"
        }
      ],
      "role": "symbol",
      "title": "NIError.Code.unsupportedPlatform",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nierror/code/unsupportedplatform"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/userDidNotAllow": {
      "abstract": [
        {
          "text": "An error code that indicates that the user declined the request to share their relative position with nearby devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userDidNotAllow"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/userDidNotAllow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NIErrorCodeUserDidNotAllow"
        }
      ],
      "role": "symbol",
      "title": "NIError.Code.userDidNotAllow",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nierror/code/userdidnotallow"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIErrorDomain": {
      "abstract": [
        {
          "text": "A unique error domain for Nearby Interaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NIErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NIErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "NIErrorDomain",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nierrordomain"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NISessionDelegate/session(_:didInvalidateWith:)": {
      "abstract": [
        {
          "text": "Notifies you of an invalidated session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "session"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NISession",
          "text": "NISession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didInvalidateWith"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NISessionDelegate/session(_:didInvalidateWith:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "session:didInvalidateWithError:"
        }
      ],
      "role": "symbol",
      "title": "session(_:didInvalidateWith:)",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nisessiondelegate/session(_:didinvalidatewith:)"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIErrorDomain"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Errors",
      "identifiers": [
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/activeSessionsLimitExceeded",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/invalidConfiguration",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/resourceUsageTimeout",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/sessionFailed",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/unsupportedPlatform",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/userDidNotAllow",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/invalidARConfiguration",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/accessoryPeerDeviceUnavailable",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/incompatiblePeerDevice",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/activeExtendedDistanceSessionsLimitExceeded"
      ],
      "title": "Errors"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NIErrorCode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NIErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NIErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Errors",
              "identifiers": [
                "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/activeSessionsLimitExceeded",
                "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/invalidConfiguration",
                "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/resourceUsageTimeout",
                "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/sessionFailed",
                "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/unsupportedPlatform",
                "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/userDidNotAllow",
                "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/invalidARConfiguration",
                "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/accessoryPeerDeviceUnavailable",
                "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/incompatiblePeerDevice",
                "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIError/Code/activeExtendedDistanceSessionsLimitExceeded"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIErrorDomain"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NIErrorCode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIError~1Code~1activeExtendedDistanceSessionsLimitExceeded/title",
          "value": "NIErrorCodeActiveExtendedDistanceSessionsLimitExceeded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIError~1Code~1activeExtendedDistanceSessionsLimitExceeded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NIErrorCodeActiveExtendedDistanceSessionsLimitExceeded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIError~1Code~1unsupportedPlatform/title",
          "value": "NIErrorCodeUnsupportedPlatform"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIError~1Code~1unsupportedPlatform/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NIErrorCodeUnsupportedPlatform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIErrorDomain/title",
          "value": "NIErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NIErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIError~1Code~1sessionFailed/title",
          "value": "NIErrorCodeSessionFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIError~1Code~1sessionFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NIErrorCodeSessionFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIError~1Code~1resourceUsageTimeout/title",
          "value": "NIErrorCodeResourceUsageTimeout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIError~1Code~1resourceUsageTimeout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NIErrorCodeResourceUsageTimeout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIError~1Code~1incompatiblePeerDevice/title",
          "value": "NIErrorCodeIncompatiblePeerDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIError~1Code~1incompatiblePeerDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NIErrorCodeIncompatiblePeerDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NISessionDelegate~1session(_:didInvalidateWith:)/title",
          "value": "session:didInvalidateWithError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NISessionDelegate~1session(_:didInvalidateWith:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "session:didInvalidateWithError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIError~1Code~1invalidARConfiguration/title",
          "value": "NIErrorCodeInvalidARConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIError~1Code~1invalidARConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NIErrorCodeInvalidARConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIError~1Code/title",
          "value": "NIErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NIErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NIErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIError~1Code~1accessoryPeerDeviceUnavailable/title",
          "value": "NIErrorCodeAccessoryPeerDeviceUnavailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIError~1Code~1accessoryPeerDeviceUnavailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NIErrorCodeAccessoryPeerDeviceUnavailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIError~1Code~1invalidConfiguration/title",
          "value": "NIErrorCodeInvalidConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIError~1Code~1invalidConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NIErrorCodeInvalidConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIError~1Code~1activeSessionsLimitExceeded/title",
          "value": "NIErrorCodeActiveSessionsLimitExceeded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIError~1Code~1activeSessionsLimitExceeded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NIErrorCodeActiveSessionsLimitExceeded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIError~1Code~1userDidNotAllow/title",
          "value": "NIErrorCodeUserDidNotAllow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIError~1Code~1userDidNotAllow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NIErrorCodeUserDidNotAllow"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/nearbyinteraction/nierror/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/nearbyinteraction/nierror/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
