{
  "abstract": [
    {
      "text": "How text is displayed when an element is in focus.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.tvmlkit/documentation/TVMLKit",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElementStyle"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.tvmlkit/documentation/TVMLKit/label-state-values"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "TVMLKit"
      }
    ],
    "role": "collectionGroup",
    "title": "Label State Values"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "code": [
            "NSString *const TVTextHighlightStyleShowOnHighlight;",
            "NSString *const TVTextHighlightStyleMarqueeOnHighlight;",
            "NSString *const TVTextHighlightStyleMarqueeAndShowOnHighlight;"
          ],
          "syntax": null,
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit": {
      "abstract": [
        {
          "text": "Create client-server apps by incorporating JavaScript and TVML files in your binary app.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit",
      "kind": "symbol",
      "role": "collection",
      "title": "TVMLKit",
      "type": "topic",
      "url": "/documentation/tvmlkit"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextHighlightStyleMarqueeAndShowOnHighlight": {
      "abstract": [
        {
          "text": "The text will scroll across the screen if the text is longer than the available space.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextHighlightStyleMarqueeAndShowOnHighlight",
      "kind": "article",
      "role": "article",
      "title": "TVTextHighlightStyleMarqueeAndShowOnHighlight",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvtexthighlightstylemarqueeandshowonhighlight"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextHighlightStyleMarqueeOnHighlight": {
      "abstract": [
        {
          "text": "Any text that is longer than the available space is truncated.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextHighlightStyleMarqueeOnHighlight",
      "kind": "article",
      "role": "article",
      "title": "TVTextHighlightStyleMarqueeOnHighlight",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvtexthighlightstylemarqueeonhighlight"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextHighlightStyleShowOnHighlight": {
      "abstract": [
        {
          "text": "Any text that is longer than the available space will scroll across the screen.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextHighlightStyleShowOnHighlight",
      "kind": "article",
      "role": "article",
      "title": "TVTextHighlightStyleShowOnHighlight",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvtexthighlightstyleshowonhighlight"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElementStyle": {
      "abstract": [
        {
          "text": "A style applied to a view element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVViewElementStyle"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElementStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVViewElementStyle"
        }
      ],
      "role": "symbol",
      "title": "TVViewElementStyle",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvviewelementstyle"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/rating-style-values": {
      "abstract": [
        {
          "text": "The size of the star image used for a rating element.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/rating-style-values",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Rating Style Values",
      "type": "topic",
      "url": "/documentation/tvmlkit/rating-style-values"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/text-style-values": {
      "abstract": [
        {
          "text": "Font size and weight.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/text-style-values",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Text Style Values",
      "type": "topic",
      "url": "/documentation/tvmlkit/text-style-values"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/transition-style-values": {
      "abstract": [
        {
          "text": "The type of transition to apply to an element.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/transition-style-values",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Transition Style Values",
      "type": "topic",
      "url": "/documentation/tvmlkit/transition-style-values"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Element-Styles",
      "generated": true,
      "identifiers": [
        "doc://com.apple.tvmlkit/documentation/TVMLKit/transition-style-values",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/rating-style-values",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/text-style-values"
      ],
      "title": "Element Styles"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextHighlightStyleShowOnHighlight",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextHighlightStyleMarqueeOnHighlight",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextHighlightStyleMarqueeAndShowOnHighlight"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextHighlightStyleShowOnHighlight",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextHighlightStyleMarqueeOnHighlight",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextHighlightStyleMarqueeAndShowOnHighlight"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Element-Styles",
              "generated": true,
              "identifiers": [
                "doc://com.apple.tvmlkit/documentation/TVMLKit/transition-style-values",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/rating-style-values",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/text-style-values"
              ],
              "title": "Element Styles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVViewElementStyle/title",
          "value": "TVViewElementStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVViewElementStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVViewElementStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVViewElementStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVViewElementStyle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/tvmlkit/label-state-values"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/tvmlkit/label-state-values"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
