{
  "abstract": [
    {
      "text": "Font size and weight.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.tvmlkit/documentation/TVMLKit",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElementStyle"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.tvmlkit/documentation/TVMLKit/text-style-values"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "TVMLKit"
      }
    ],
    "role": "collectionGroup",
    "title": "Text Style Values"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "code": [
            "NSString *const TVTextStyleTitle1;",
            "NSString *const TVTextStyleTitle2;",
            "NSString *const TVTextStyleTitle3;",
            "NSString *const TVTextStyleHeadline;",
            "NSString *const TVTextStyleSubtitle1;",
            "NSString *const TVTextStyleSubtitle2;",
            "NSString *const TVTextStyleSubtitle3;",
            "NSString *const TVTextStyleCallout;",
            "NSString *const TVTextStyleBody;",
            "NSString *const TVTextStyleSubhead;",
            "NSString *const TVTextStyleFootnote;",
            "NSString *const TVTextStyleCaption1;",
            "NSString *const TVTextStyleCaption2;"
          ],
          "syntax": null,
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit": {
      "abstract": [
        {
          "text": "Create client-server apps by incorporating JavaScript and TVML files in your binary app.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit",
      "kind": "symbol",
      "role": "collection",
      "title": "TVMLKit",
      "type": "topic",
      "url": "/documentation/tvmlkit"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextStyleBody": {
      "abstract": [
        {
          "text": "Use the ",
          "type": "text"
        },
        {
          "code": "body",
          "type": "codeVoice"
        },
        {
          "text": " font size and weight.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextStyleBody",
      "kind": "article",
      "role": "article",
      "title": "TVTextStyleBody",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvtextstylebody"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextStyleCallout": {
      "abstract": [
        {
          "text": "Use the ",
          "type": "text"
        },
        {
          "code": "callout",
          "type": "codeVoice"
        },
        {
          "text": " font size and weight.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextStyleCallout",
      "kind": "article",
      "role": "article",
      "title": "TVTextStyleCallout",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvtextstylecallout"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextStyleCaption1": {
      "abstract": [
        {
          "text": "Use the ",
          "type": "text"
        },
        {
          "code": "caption1",
          "type": "codeVoice"
        },
        {
          "text": " font size and weight.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextStyleCaption1",
      "kind": "article",
      "role": "article",
      "title": "TVTextStyleCaption1",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvtextstylecaption1"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextStyleCaption2": {
      "abstract": [
        {
          "text": "Use the ",
          "type": "text"
        },
        {
          "code": "caption2",
          "type": "codeVoice"
        },
        {
          "text": " font size and weight.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextStyleCaption2",
      "kind": "article",
      "role": "article",
      "title": "TVTextStyleCaption2",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvtextstylecaption2"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextStyleFootnote": {
      "abstract": [
        {
          "text": "Use the ",
          "type": "text"
        },
        {
          "code": "footnote",
          "type": "codeVoice"
        },
        {
          "text": " font size and weight.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextStyleFootnote",
      "kind": "article",
      "role": "article",
      "title": "TVTextStyleFootnote",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvtextstylefootnote"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextStyleHeadline": {
      "abstract": [
        {
          "text": "Use the ",
          "type": "text"
        },
        {
          "code": "headline",
          "type": "codeVoice"
        },
        {
          "text": " font size and weight.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextStyleHeadline",
      "kind": "article",
      "role": "article",
      "title": "TVTextStyleHeadline",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvtextstyleheadline"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextStyleSubhead": {
      "abstract": [
        {
          "text": "Use the ",
          "type": "text"
        },
        {
          "code": "subhead",
          "type": "codeVoice"
        },
        {
          "text": " font size and weight.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextStyleSubhead",
      "kind": "article",
      "role": "article",
      "title": "TVTextStyleSubhead",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvtextstylesubhead"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextStyleSubtitle1": {
      "abstract": [
        {
          "text": "Use the ",
          "type": "text"
        },
        {
          "code": "subtitle1",
          "type": "codeVoice"
        },
        {
          "text": " font size and weight.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextStyleSubtitle1",
      "kind": "article",
      "role": "article",
      "title": "TVTextStyleSubtitle1",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvtextstylesubtitle1"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextStyleSubtitle2": {
      "abstract": [
        {
          "text": "Use the ",
          "type": "text"
        },
        {
          "code": "subtitle2",
          "type": "codeVoice"
        },
        {
          "text": " font size and weight.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextStyleSubtitle2",
      "kind": "article",
      "role": "article",
      "title": "TVTextStyleSubtitle2",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvtextstylesubtitle2"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextStyleSubtitle3": {
      "abstract": [
        {
          "text": "Use the ",
          "type": "text"
        },
        {
          "code": "subtitle3",
          "type": "codeVoice"
        },
        {
          "text": " font size and weight.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextStyleSubtitle3",
      "kind": "article",
      "role": "article",
      "title": "TVTextStyleSubtitle3",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvtextstylesubtitle3"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextStyleTitle1": {
      "abstract": [
        {
          "text": "Use the ",
          "type": "text"
        },
        {
          "code": "title1",
          "type": "codeVoice"
        },
        {
          "text": " font size and weight.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextStyleTitle1",
      "kind": "article",
      "role": "article",
      "title": "TVTextStyleTitle1",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvtextstyletitle1"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextStyleTitle2": {
      "abstract": [
        {
          "text": "Use the ",
          "type": "text"
        },
        {
          "code": "title2",
          "type": "codeVoice"
        },
        {
          "text": " font size and weight.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextStyleTitle2",
      "kind": "article",
      "role": "article",
      "title": "TVTextStyleTitle2",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvtextstyletitle2"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextStyleTitle3": {
      "abstract": [
        {
          "text": "Use the ",
          "type": "text"
        },
        {
          "code": "title3",
          "type": "codeVoice"
        },
        {
          "text": " font size and weight.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextStyleTitle3",
      "kind": "article",
      "role": "article",
      "title": "TVTextStyleTitle3",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvtextstyletitle3"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElementStyle": {
      "abstract": [
        {
          "text": "A style applied to a view element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVViewElementStyle"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElementStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVViewElementStyle"
        }
      ],
      "role": "symbol",
      "title": "TVViewElementStyle",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvviewelementstyle"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/label-state-values": {
      "abstract": [
        {
          "text": "How text is displayed when an element is in focus.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/label-state-values",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Label State Values",
      "type": "topic",
      "url": "/documentation/tvmlkit/label-state-values"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/rating-style-values": {
      "abstract": [
        {
          "text": "The size of the star image used for a rating element.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/rating-style-values",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Rating Style Values",
      "type": "topic",
      "url": "/documentation/tvmlkit/rating-style-values"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/transition-style-values": {
      "abstract": [
        {
          "text": "The type of transition to apply to an element.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/transition-style-values",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Transition Style Values",
      "type": "topic",
      "url": "/documentation/tvmlkit/transition-style-values"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Element-Styles",
      "generated": true,
      "identifiers": [
        "doc://com.apple.tvmlkit/documentation/TVMLKit/transition-style-values",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/rating-style-values",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/label-state-values"
      ],
      "title": "Element Styles"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextStyleTitle1",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextStyleTitle2",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextStyleTitle3",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextStyleHeadline",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextStyleSubtitle1",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextStyleSubtitle2",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextStyleSubtitle3",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextStyleCallout",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextStyleBody",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextStyleSubhead",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextStyleFootnote",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextStyleCaption1",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextStyleCaption2"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextStyleTitle1",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextStyleTitle2",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextStyleTitle3",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextStyleHeadline",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextStyleSubtitle1",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextStyleSubtitle2",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextStyleSubtitle3",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextStyleCallout",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextStyleBody",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextStyleSubhead",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextStyleFootnote",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextStyleCaption1",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTextStyleCaption2"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Element-Styles",
              "generated": true,
              "identifiers": [
                "doc://com.apple.tvmlkit/documentation/TVMLKit/transition-style-values",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/rating-style-values",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/label-state-values"
              ],
              "title": "Element Styles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVViewElementStyle/title",
          "value": "TVViewElementStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVViewElementStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVViewElementStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVViewElementStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVViewElementStyle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/tvmlkit/text-style-values"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/tvmlkit/text-style-values"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
