{
  "abstract": [
    {
      "text": "The type of transition to apply to an element.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.tvmlkit/documentation/TVMLKit",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElementStyle"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.tvmlkit/documentation/TVMLKit/transition-style-values"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "TVMLKit"
      }
    ],
    "role": "collectionGroup",
    "title": "Transition Style Values"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "code": [
            "NSString *const TVTransitionDissolve;",
            "NSString *const TVTransitionMagicMove;",
            "NSString *const TVTransitionNone;",
            "NSString *const TVTransitionPush;",
            "NSString *const TVTransitionWipe;"
          ],
          "syntax": null,
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit": {
      "abstract": [
        {
          "text": "Create client-server apps by incorporating JavaScript and TVML files in your binary app.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit",
      "kind": "symbol",
      "role": "collection",
      "title": "TVMLKit",
      "type": "topic",
      "url": "/documentation/tvmlkit"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTransitionDissolve": {
      "abstract": [
        {
          "text": "The element stays in place and a dissolve effect is applied.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTransitionDissolve",
      "kind": "article",
      "role": "article",
      "title": "TVTransitionDissolve",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvtransitiondissolve"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTransitionMagicMove": {
      "abstract": [
        {
          "text": "The magic move transition is to be used.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTransitionMagicMove",
      "kind": "article",
      "role": "article",
      "title": "TVTransitionMagicMove",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvtransitionmagicmove"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTransitionNone": {
      "abstract": [
        {
          "text": "No transition effect is to be applied.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTransitionNone",
      "kind": "article",
      "role": "article",
      "title": "TVTransitionNone",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvtransitionnone"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTransitionPush": {
      "abstract": [
        {
          "text": "The element is pushed onto the screen.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTransitionPush",
      "kind": "article",
      "role": "article",
      "title": "TVTransitionPush",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvtransitionpush"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTransitionWipe": {
      "abstract": [
        {
          "text": "The element is wiped from the screen.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTransitionWipe",
      "kind": "article",
      "role": "article",
      "title": "TVTransitionWipe",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvtransitionwipe"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElementStyle": {
      "abstract": [
        {
          "text": "A style applied to a view element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVViewElementStyle"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElementStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVViewElementStyle"
        }
      ],
      "role": "symbol",
      "title": "TVViewElementStyle",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvviewelementstyle"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/label-state-values": {
      "abstract": [
        {
          "text": "How text is displayed when an element is in focus.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/label-state-values",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Label State Values",
      "type": "topic",
      "url": "/documentation/tvmlkit/label-state-values"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/rating-style-values": {
      "abstract": [
        {
          "text": "The size of the star image used for a rating element.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/rating-style-values",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Rating Style Values",
      "type": "topic",
      "url": "/documentation/tvmlkit/rating-style-values"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/text-style-values": {
      "abstract": [
        {
          "text": "Font size and weight.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/text-style-values",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Text Style Values",
      "type": "topic",
      "url": "/documentation/tvmlkit/text-style-values"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Element-Styles",
      "generated": true,
      "identifiers": [
        "doc://com.apple.tvmlkit/documentation/TVMLKit/rating-style-values",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/label-state-values",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/text-style-values"
      ],
      "title": "Element Styles"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTransitionDissolve",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTransitionMagicMove",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTransitionNone",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTransitionPush",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTransitionWipe"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTransitionDissolve",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTransitionMagicMove",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTransitionNone",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTransitionPush",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVTransitionWipe"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Element-Styles",
              "generated": true,
              "identifiers": [
                "doc://com.apple.tvmlkit/documentation/TVMLKit/rating-style-values",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/label-state-values",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/text-style-values"
              ],
              "title": "Element Styles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVViewElementStyle/title",
          "value": "TVViewElementStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVViewElementStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVViewElementStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVViewElementStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVViewElementStyle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/tvmlkit/transition-style-values"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/tvmlkit/transition-style-values"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
