{
  "abstract": [
    {
      "text": "An object that bridges the UI, navigation stack, storage, and event handling from JavaScript.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Please use SwiftUI or UIKit",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.tvmlkit/documentation/TVMLKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)TVApplicationController",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "TVApplicationController"
      }
    ],
    "modules": [
      {
        "name": "TVMLKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "TVApplicationController"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "9.0",
        "message": "Please use SwiftUI or UIKit",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "TVApplicationController"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "TVApplicationController"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.tvmlkit/documentation/TVMLKit/creating-tvml-elements"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "TVApplicationController",
              "type": "codeVoice"
            },
            {
              "text": " class establishes the JavaScript environment and provides a centralized point of control and coordination between the JavaScript environment and tvOS.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit": {
      "abstract": [
        {
          "text": "Create client-server apps by incorporating JavaScript and TVML files in your binary app.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit",
      "kind": "symbol",
      "role": "collection",
      "title": "TVMLKit",
      "type": "topic",
      "url": "/documentation/tvmlkit"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController": {
      "abstract": [
        {
          "text": "An object that bridges the UI, navigation stack, storage, and event handling from JavaScript.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVApplicationController"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVApplicationController"
        }
      ],
      "role": "symbol",
      "title": "TVApplicationController",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvapplicationcontroller"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController/context": {
      "abstract": [
        {
          "text": "The launch information for the application controller.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "context"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TVApplicationControllerContext",
          "text": "TVApplicationControllerContext"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController/context",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "context"
        }
      ],
      "role": "symbol",
      "title": "context",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvapplicationcontroller/context"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController/delegate": {
      "abstract": [
        {
          "text": "The delegate of the app controller object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)TVApplicationControllerDelegate",
          "text": "TVApplicationControllerDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvapplicationcontroller/delegate"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController/evaluate(inJavaScriptContext:completion:)": {
      "abstract": [
        {
          "text": "Evaluates a block in the JavaScript execution queue.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "evaluate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "inJavaScriptContext"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)JSContext",
          "text": "JSContext"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController/evaluate(inJavaScriptContext:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "evaluateInJavaScriptContext:completion:"
        }
      ],
      "role": "symbol",
      "title": "evaluate(inJavaScriptContext:completion:)",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvapplicationcontroller/evaluate(injavascriptcontext:completion:)"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController/init(context:window:delegate:)": {
      "abstract": [
        {
          "text": "Initializes and returns an app controller.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "context"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TVApplicationControllerContext",
          "text": "TVApplicationControllerContext"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "window"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIWindow",
          "text": "UIWindow"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)TVApplicationControllerDelegate",
          "text": "TVApplicationControllerDelegate"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController/init(context:window:delegate:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithContext:window:delegate:"
        }
      ],
      "role": "symbol",
      "title": "init(context:window:delegate:)",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvapplicationcontroller/init(context:window:delegate:)"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController/navigationController": {
      "abstract": [
        {
          "text": "The navigation controller that is bridged from JavaScript to tvOS.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "navigationController"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UINavigationController",
          "text": "UINavigationController"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController/navigationController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "navigationController"
        }
      ],
      "role": "symbol",
      "title": "navigationController",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvapplicationcontroller/navigationcontroller"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController/stop()": {
      "abstract": [
        {
          "text": "Ends the app life cycle.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stop"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController/stop()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stop"
        }
      ],
      "role": "symbol",
      "title": "stop()",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvapplicationcontroller/stop()"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController/window": {
      "abstract": [
        {
          "text": "A reference to the window supplied when the app controller was initialized.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "window"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIWindow",
          "text": "UIWindow"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController/window",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "window"
        }
      ],
      "role": "symbol",
      "title": "window",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvapplicationcontroller/window"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationControllerContext": {
      "abstract": [
        {
          "text": "Launch information provided to the TV application controller.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVApplicationControllerContext"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationControllerContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVApplicationControllerContext"
        }
      ],
      "role": "symbol",
      "title": "TVApplicationControllerContext",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvapplicationcontrollercontext"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationControllerDelegate": {
      "abstract": [
        {
          "text": "A protocol used to observe and manage the different states of an application controller.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVApplicationControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVApplicationControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "TVApplicationControllerDelegate",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvapplicationcontrollerdelegate"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/creating-tvml-elements": {
      "abstract": [
        {
          "text": "Avoid rewriting complex and often used elements by creating a simplified custom element.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/creating-tvml-elements",
      "kind": "article",
      "role": "article",
      "title": "Creating TVML Elements",
      "type": "topic",
      "url": "/documentation/tvmlkit/creating-tvml-elements"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/implementing-a-hybrid-tv-app-with-tvmlkit": {
      "abstract": [
        {
          "text": "Display content options with document view controllers and fetch and populate content with TVMLKit JS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/implementing-a-hybrid-tv-app-with-tvmlkit",
      "kind": "article",
      "role": "sampleCode",
      "title": "Implementing a Hybrid TV App with TVMLKit",
      "type": "topic",
      "url": "/documentation/tvmlkit/implementing-a-hybrid-tv-app-with-tvmlkit"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "JavaScript-Environment",
      "generated": true,
      "identifiers": [
        "doc://com.apple.tvmlkit/documentation/TVMLKit/implementing-a-hybrid-tv-app-with-tvmlkit",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationControllerContext"
      ],
      "title": "JavaScript Environment"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-New-App-Controller",
      "identifiers": [
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController/init(context:window:delegate:)"
      ],
      "title": "Creating a New App Controller"
    },
    {
      "anchor": "Controlling-and-Handling-Events",
      "identifiers": [
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController/evaluate(inJavaScriptContext:completion:)",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController/stop()"
      ],
      "title": "Controlling and Handling Events"
    },
    {
      "anchor": "Getting-the-Delegate",
      "identifiers": [
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController/delegate",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationControllerDelegate"
      ],
      "title": "Getting the Delegate"
    },
    {
      "anchor": "Examining-App-Controller-Properties",
      "identifiers": [
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController/context",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController/navigationController",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController/window"
      ],
      "title": "Examining App Controller Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "TVApplicationController"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVApplicationController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVApplicationController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.tvmlkit/documentation/TVMLKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-New-App-Controller",
              "identifiers": [
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController/init(context:window:delegate:)"
              ],
              "title": "Creating a New App Controller"
            },
            {
              "anchor": "Controlling-and-Handling-Events",
              "identifiers": [
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController/evaluate(inJavaScriptContext:completion:)",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController/stop()"
              ],
              "title": "Controlling and Handling Events"
            },
            {
              "anchor": "Getting-the-Delegate",
              "identifiers": [
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController/delegate",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationControllerDelegate"
              ],
              "title": "Getting the Delegate"
            },
            {
              "anchor": "Examining-App-Controller-Properties",
              "identifiers": [
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController/context",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController/navigationController",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationController/window"
              ],
              "title": "Examining App Controller Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "JavaScript-Environment",
              "generated": true,
              "identifiers": [
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVApplicationControllerContext"
              ],
              "title": "JavaScript Environment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "TVApplicationController"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Please use SwiftUI or UIKit",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationController/title",
          "value": "TVApplicationController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVApplicationController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVApplicationController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationController~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationController~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationController~1window/title",
          "value": "window"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationController~1window/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "window"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationController~1navigationController/title",
          "value": "navigationController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationController~1navigationController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "navigationController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationController~1init(context:window:delegate:)/title",
          "value": "initWithContext:window:delegate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationController~1init(context:window:delegate:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithContext:window:delegate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationController~1context/title",
          "value": "context"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationController~1context/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "context"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationControllerDelegate/title",
          "value": "TVApplicationControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVApplicationControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVApplicationControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationController~1stop()/title",
          "value": "stop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationController~1stop()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "stop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationControllerContext/title",
          "value": "TVApplicationControllerContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationControllerContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVApplicationControllerContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationControllerContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVApplicationControllerContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationController~1evaluate(inJavaScriptContext:completion:)/title",
          "value": "evaluateInJavaScriptContext:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVApplicationController~1evaluate(inJavaScriptContext:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "evaluateInJavaScriptContext:completion:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/tvmlkit/tvapplicationcontroller"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/tvmlkit/tvapplicationcontroller"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
