{
  "abstract": [
    {
      "text": "Methods to manage updates, events, and errors from the document view controller.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Please use SwiftUI or UIKit",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.tvmlkit/documentation/TVMLKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVDocumentViewControllerDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)TVDocumentViewControllerDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "TVDocumentViewControllerDelegate"
      }
    ],
    "modules": [
      {
        "name": "TVMLKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "TVDocumentViewControllerDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "13.0",
        "message": "Please use SwiftUI or UIKit",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "TVDocumentViewControllerDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "TVDocumentViewControllerDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit": {
      "abstract": [
        {
          "text": "Create client-server apps by incorporating JavaScript and TVML files in your binary app.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit",
      "kind": "symbol",
      "role": "collection",
      "title": "TVMLKit",
      "type": "topic",
      "url": "/documentation/tvmlkit"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVDocumentViewController/delegate": {
      "abstract": [
        {
          "text": "The delegate for handling events in the document view controller.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)TVDocumentViewControllerDelegate",
          "text": "TVDocumentViewControllerDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVDocumentViewController/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvdocumentviewcontroller/delegate"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVDocumentViewControllerDelegate": {
      "abstract": [
        {
          "text": "Methods to manage updates, events, and errors from the document view controller.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVDocumentViewControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVDocumentViewControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVDocumentViewControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "TVDocumentViewControllerDelegate",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvdocumentviewcontrollerdelegate"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVDocumentViewControllerDelegate/documentViewController(_:didFailUpdateWithError:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the document failed to update.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TVDocumentViewController",
          "text": "TVDocumentViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didFailUpdateWithError"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVDocumentViewControllerDelegate/documentViewController(_:didFailUpdateWithError:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentViewController:didFailUpdateWithError:"
        }
      ],
      "role": "symbol",
      "title": "documentViewController(_:didFailUpdateWithError:)",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvdocumentviewcontrollerdelegate/documentviewcontroller(_:didfailupdatewitherror:)"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVDocumentViewControllerDelegate/documentViewController(_:didUpdateWithContext:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the document has been updated with a specified context.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TVDocumentViewController",
          "text": "TVDocumentViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didUpdateWithContext"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVDocumentViewControllerDelegate/documentViewController(_:didUpdateWithContext:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentViewController:didUpdateWithContext:"
        }
      ],
      "role": "symbol",
      "title": "documentViewController(_:didUpdateWithContext:)",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvdocumentviewcontrollerdelegate/documentviewcontroller(_:didupdatewithcontext:)"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVDocumentViewControllerDelegate/documentViewController(_:handleEvent:with:)": {
      "abstract": [
        {
          "text": "Handles events natively from document view controllers.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TVDocumentViewController",
          "text": "TVDocumentViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "handleEvent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TVDocumentViewController",
          "text": "TVDocumentViewController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@TVDocumentEvent",
          "text": "Event"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TVViewElement",
          "text": "TVViewElement"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVDocumentViewControllerDelegate/documentViewController(_:handleEvent:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentViewController:handleEvent:withElement:"
        }
      ],
      "role": "symbol",
      "title": "documentViewController(_:handleEvent:with:)",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvdocumentviewcontrollerdelegate/documentviewcontroller(_:handleevent:with:)"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVDocumentViewControllerDelegate/documentViewControllerDidUpdate(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the document has been updated.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentViewControllerDidUpdate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TVDocumentViewController",
          "text": "TVDocumentViewController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVDocumentViewControllerDelegate/documentViewControllerDidUpdate(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentViewControllerDidUpdate:"
        }
      ],
      "role": "symbol",
      "title": "documentViewControllerDidUpdate(_:)",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvdocumentviewcontrollerdelegate/documentviewcontrollerdidupdate(_:)"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVDocumentViewControllerDelegate/documentViewControllerWillUpdate(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the document will be updated.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentViewControllerWillUpdate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TVDocumentViewController",
          "text": "TVDocumentViewController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVDocumentViewControllerDelegate/documentViewControllerWillUpdate(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentViewControllerWillUpdate:"
        }
      ],
      "role": "symbol",
      "title": "documentViewControllerWillUpdate(_:)",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvdocumentviewcontrollerdelegate/documentviewcontrollerwillupdate(_:)"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-Interactions-with-the-Document",
      "generated": true,
      "identifiers": [
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVDocumentViewController/delegate"
      ],
      "title": "Managing Interactions with the Document"
    }
  ],
  "topicSections": [
    {
      "anchor": "Managing-Document-Updates",
      "identifiers": [
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVDocumentViewControllerDelegate/documentViewControllerWillUpdate(_:)",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVDocumentViewControllerDelegate/documentViewControllerDidUpdate(_:)",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVDocumentViewControllerDelegate/documentViewController(_:didUpdateWithContext:)"
      ],
      "title": "Managing Document Updates"
    },
    {
      "anchor": "Responding-to-Errors",
      "identifiers": [
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVDocumentViewControllerDelegate/documentViewController(_:didFailUpdateWithError:)"
      ],
      "title": "Responding to Errors"
    },
    {
      "anchor": "Handling-Events",
      "identifiers": [
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVDocumentViewControllerDelegate/documentViewController(_:handleEvent:with:)"
      ],
      "title": "Handling Events"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "TVDocumentViewControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVDocumentViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVDocumentViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.tvmlkit/documentation/TVMLKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Managing-Document-Updates",
              "identifiers": [
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVDocumentViewControllerDelegate/documentViewControllerWillUpdate(_:)",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVDocumentViewControllerDelegate/documentViewControllerDidUpdate(_:)",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVDocumentViewControllerDelegate/documentViewController(_:didUpdateWithContext:)"
              ],
              "title": "Managing Document Updates"
            },
            {
              "anchor": "Responding-to-Errors",
              "identifiers": [
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVDocumentViewControllerDelegate/documentViewController(_:didFailUpdateWithError:)"
              ],
              "title": "Responding to Errors"
            },
            {
              "anchor": "Handling-Events",
              "identifiers": [
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVDocumentViewControllerDelegate/documentViewController(_:handleEvent:with:)"
              ],
              "title": "Handling Events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-Interactions-with-the-Document",
              "generated": true,
              "identifiers": [
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVDocumentViewController/delegate"
              ],
              "title": "Managing Interactions with the Document"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "TVDocumentViewControllerDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Please use SwiftUI or UIKit",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVDocumentViewControllerDelegate~1documentViewController(_:didUpdateWithContext:)/title",
          "value": "documentViewController:didUpdateWithContext:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVDocumentViewControllerDelegate~1documentViewController(_:didUpdateWithContext:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "documentViewController:didUpdateWithContext:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVDocumentViewControllerDelegate~1documentViewControllerWillUpdate(_:)/title",
          "value": "documentViewControllerWillUpdate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVDocumentViewControllerDelegate~1documentViewControllerWillUpdate(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "documentViewControllerWillUpdate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVDocumentViewControllerDelegate~1documentViewControllerDidUpdate(_:)/title",
          "value": "documentViewControllerDidUpdate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVDocumentViewControllerDelegate~1documentViewControllerDidUpdate(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "documentViewControllerDidUpdate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVDocumentViewControllerDelegate/title",
          "value": "TVDocumentViewControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVDocumentViewControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVDocumentViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVDocumentViewControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVDocumentViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVDocumentViewController~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVDocumentViewController~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVDocumentViewControllerDelegate~1documentViewController(_:didFailUpdateWithError:)/title",
          "value": "documentViewController:didFailUpdateWithError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVDocumentViewControllerDelegate~1documentViewController(_:didFailUpdateWithError:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "documentViewController:didFailUpdateWithError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVDocumentViewControllerDelegate~1documentViewController(_:handleEvent:with:)/title",
          "value": "documentViewController:handleEvent:withElement:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVDocumentViewControllerDelegate~1documentViewController(_:handleEvent:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "documentViewController:handleEvent:withElement:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/tvmlkit/tvdocumentviewcontrollerdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/tvmlkit/tvdocumentviewcontrollerdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
