{
  "abstract": [
    {
      "text": "Location of an element relative to the screen or its containing element.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Please use SwiftUI or UIKit",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.tvmlkit/documentation/TVMLKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@TVElementPosition",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "TVElementPosition"
      }
    ],
    "modules": [
      {
        "name": "TVMLKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "TVElementPosition"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "9.0",
        "message": "Please use SwiftUI or UIKit",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "TVElementPosition"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "TVElementPosition"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit": {
      "abstract": [
        {
          "text": "Create client-server apps by incorporating JavaScript and TVML files in your binary app.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit",
      "kind": "symbol",
      "role": "collection",
      "title": "TVMLKit",
      "type": "topic",
      "url": "/documentation/tvmlkit"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementAlignment": {
      "abstract": [
        {
          "text": "Location of an item inside of an element on the horizontal axis.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVElementAlignment"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementAlignment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVElementAlignment"
        }
      ],
      "role": "symbol",
      "title": "TVElementAlignment",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvelementalignment"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementContentAlignment": {
      "abstract": [
        {
          "text": "Location of items inside of an element on the vertical axis.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVElementContentAlignment"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementContentAlignment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVElementContentAlignment"
        }
      ],
      "role": "symbol",
      "title": "TVElementContentAlignment",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvelementcontentalignment"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition": {
      "abstract": [
        {
          "text": "Location of an element relative to the screen or its containing element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVElementPosition"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVElementPosition"
        }
      ],
      "role": "symbol",
      "title": "TVElementPosition",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvelementposition"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/bottom": {
      "abstract": [
        {
          "text": "Position the element at the bottom of the containing element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottom"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/bottom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVElementPositionBottom"
        }
      ],
      "role": "symbol",
      "title": "TVElementPosition.bottom",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvelementposition/bottom"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/bottomLeading": {
      "abstract": [
        {
          "text": "Position the element in the bottom-leading edge of the containing element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottomLeading"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/bottomLeading",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVElementPositionBottomLeading"
        }
      ],
      "role": "symbol",
      "title": "TVElementPosition.bottomLeading",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvelementposition/bottomleading"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/bottomLeft": {
      "abstract": [
        {
          "text": "Position the element in the bottom-left of the containing element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottomLeft"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/bottomLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVElementPositionBottomLeft"
        }
      ],
      "role": "symbol",
      "title": "TVElementPosition.bottomLeft",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvelementposition/bottomleft"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/bottomRight": {
      "abstract": [
        {
          "text": "Position the element in the bottom-right of the containing element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottomRight"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/bottomRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVElementPositionBottomRight"
        }
      ],
      "role": "symbol",
      "title": "TVElementPosition.bottomRight",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvelementposition/bottomright"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/bottomTrailing": {
      "abstract": [
        {
          "text": "Position the element in the bottom-trailing edge of the containing element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottomTrailing"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/bottomTrailing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVElementPositionBottomTrailing"
        }
      ],
      "role": "symbol",
      "title": "TVElementPosition.bottomTrailing",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvelementposition/bottomtrailing"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/center": {
      "abstract": [
        {
          "text": "Position the element in the center of its containing element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "center"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/center",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVElementPositionCenter"
        }
      ],
      "role": "symbol",
      "title": "TVElementPosition.center",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvelementposition/center"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/footer": {
      "abstract": [
        {
          "text": "Position the element in the footer area of the containing element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "footer"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/footer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVElementPositionFooter"
        }
      ],
      "role": "symbol",
      "title": "TVElementPosition.footer",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvelementposition/footer"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/header": {
      "abstract": [
        {
          "text": "Position the element in the header area of the containing element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "header"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/header",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVElementPositionHeader"
        }
      ],
      "role": "symbol",
      "title": "TVElementPosition.header",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvelementposition/header"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/init(rawValue:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvelementposition/init(rawvalue:)"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/leading": {
      "abstract": [
        {
          "text": "Position the element in the leading edge of the containing element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leading"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/leading",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVElementPositionLeading"
        }
      ],
      "role": "symbol",
      "title": "TVElementPosition.leading",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvelementposition/leading"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/left": {
      "abstract": [
        {
          "text": "Position the element along the left side of the containing element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "left"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/left",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVElementPositionLeft"
        }
      ],
      "role": "symbol",
      "title": "TVElementPosition.left",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvelementposition/left"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/right": {
      "abstract": [
        {
          "text": "Position the element along the right side of the containing element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "right"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/right",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVElementPositionRight"
        }
      ],
      "role": "symbol",
      "title": "TVElementPosition.right",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvelementposition/right"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/top": {
      "abstract": [
        {
          "text": "Position the element at the top of the containing element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "top"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/top",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVElementPositionTop"
        }
      ],
      "role": "symbol",
      "title": "TVElementPosition.top",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvelementposition/top"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/topLeading": {
      "abstract": [
        {
          "text": "Position the element in the top-leading edge of the containing element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "topLeading"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/topLeading",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVElementPositionTopLeading"
        }
      ],
      "role": "symbol",
      "title": "TVElementPosition.topLeading",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvelementposition/topleading"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/topLeft": {
      "abstract": [
        {
          "text": "Position the element in the top-left of the containing element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "topLeft"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/topLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVElementPositionTopLeft"
        }
      ],
      "role": "symbol",
      "title": "TVElementPosition.topLeft",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvelementposition/topleft"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/topRight": {
      "abstract": [
        {
          "text": "Position the element in the top-right of the containing element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "topRight"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/topRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVElementPositionTopRight"
        }
      ],
      "role": "symbol",
      "title": "TVElementPosition.topRight",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvelementposition/topright"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/topTrailing": {
      "abstract": [
        {
          "text": "Position the element in the top-trailing edge of the containing element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "topTrailing"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/topTrailing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVElementPositionTopTrailing"
        }
      ],
      "role": "symbol",
      "title": "TVElementPosition.topTrailing",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvelementposition/toptrailing"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/trailing": {
      "abstract": [
        {
          "text": "Position the element in the trailing edge of the containing element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trailing"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/trailing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVElementPositionTrailing"
        }
      ],
      "role": "symbol",
      "title": "TVElementPosition.trailing",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvelementposition/trailing"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/undefined": {
      "abstract": [
        {
          "text": "The position has not been defined.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "undefined"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/undefined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVElementPositionUndefined"
        }
      ],
      "role": "symbol",
      "title": "TVElementPosition.undefined",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvelementposition/undefined"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElementStyle/alignment": {
      "abstract": [
        {
          "text": "A value indicating how an item is aligned inside of an element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alignment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@TVElementAlignment",
          "text": "TVElementAlignment"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElementStyle/alignment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "alignment"
        }
      ],
      "role": "symbol",
      "title": "alignment",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvviewelementstyle/alignment"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElementStyle/contentAlignment": {
      "abstract": [
        {
          "text": "A value indicating how items inside of an element are aligned.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentAlignment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@TVElementContentAlignment",
          "text": "TVElementContentAlignment"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElementStyle/contentAlignment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentAlignment"
        }
      ],
      "role": "symbol",
      "title": "contentAlignment",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvviewelementstyle/contentalignment"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElementStyle/focusMargin": {
      "abstract": [
        {
          "text": "The amount of space, in pixels, a custom cell requires when it comes into focus.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "focusMargin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@UIEdgeInsets",
          "text": "UIEdgeInsets"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElementStyle/focusMargin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "focusMargin"
        }
      ],
      "role": "symbol",
      "title": "focusMargin",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvviewelementstyle/focusmargin"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElementStyle/interitemSpacing": {
      "abstract": [
        {
          "text": "The spacing, in pixels, between items inside of an element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interitemSpacing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElementStyle/interitemSpacing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "interitemSpacing"
        }
      ],
      "role": "symbol",
      "title": "interitemSpacing",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvviewelementstyle/interitemspacing"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElementStyle/margin": {
      "abstract": [
        {
          "text": "The amount of space, in pixels, between the element and other elements.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "margin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@UIEdgeInsets",
          "text": "UIEdgeInsets"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElementStyle/margin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "margin"
        }
      ],
      "role": "symbol",
      "title": "margin",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvviewelementstyle/margin"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElementStyle/padding": {
      "abstract": [
        {
          "text": "The amount of space, in pixels, between the border and the contents of the element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "padding"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@UIEdgeInsets",
          "text": "UIEdgeInsets"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElementStyle/padding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "padding"
        }
      ],
      "role": "symbol",
      "title": "padding",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvviewelementstyle/padding"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElementStyle/position": {
      "abstract": [
        {
          "text": "A value indicating the position of the element relative to the screen or its containing element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "position"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@TVElementPosition",
          "text": "TVElementPosition"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElementStyle/position",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "position"
        }
      ],
      "role": "symbol",
      "title": "position",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvviewelementstyle/position"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Aligning-and-Positioning-an-Element",
      "generated": true,
      "identifiers": [
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElementStyle/alignment",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementAlignment",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElementStyle/contentAlignment",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementContentAlignment",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElementStyle/focusMargin",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElementStyle/interitemSpacing",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElementStyle/margin",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElementStyle/padding",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElementStyle/position"
      ],
      "title": "Aligning and Positioning an Element"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/undefined",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/center",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/top",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/bottom",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/left",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/right",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/topLeft",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/topRight",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/bottomLeft",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/bottomRight",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/header",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/footer",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/leading",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/trailing",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/topLeading",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/topTrailing",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/bottomLeading",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/bottomTrailing"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "TVElementPosition"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.tvmlkit/documentation/TVMLKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/undefined",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/center",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/top",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/bottom",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/left",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/right",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/topLeft",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/topRight",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/bottomLeft",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/bottomRight",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/header",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/footer",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/leading",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/trailing",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/topLeading",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/topTrailing",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/bottomLeading",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementPosition/bottomTrailing"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Aligning-and-Positioning-an-Element",
              "generated": true,
              "identifiers": [
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElementStyle/alignment",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementAlignment",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElementStyle/contentAlignment",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementContentAlignment",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElementStyle/focusMargin",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElementStyle/interitemSpacing",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElementStyle/margin",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElementStyle/padding",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElementStyle/position"
              ],
              "title": "Aligning and Positioning an Element"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "TVElementPosition"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Please use SwiftUI or UIKit",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1top/title",
          "value": "TVElementPositionTop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1top/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementPositionTop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1header/title",
          "value": "TVElementPositionHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1header/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementPositionHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVViewElementStyle~1padding/title",
          "value": "padding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVViewElementStyle~1padding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "padding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVViewElementStyle~1position/title",
          "value": "position"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVViewElementStyle~1position/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "position"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1undefined/title",
          "value": "TVElementPositionUndefined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1undefined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementPositionUndefined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVViewElementStyle~1margin/title",
          "value": "margin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVViewElementStyle~1margin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "margin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVViewElementStyle~1interitemSpacing/title",
          "value": "interitemSpacing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVViewElementStyle~1interitemSpacing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "interitemSpacing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition/title",
          "value": "TVElementPosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1topRight/title",
          "value": "TVElementPositionTopRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1topRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementPositionTopRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1bottomLeft/title",
          "value": "TVElementPositionBottomLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1bottomLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementPositionBottomLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVViewElementStyle~1alignment/title",
          "value": "alignment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVViewElementStyle~1alignment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "alignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1bottomTrailing/title",
          "value": "TVElementPositionBottomTrailing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1bottomTrailing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementPositionBottomTrailing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1topLeading/title",
          "value": "TVElementPositionTopLeading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1topLeading/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementPositionTopLeading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementContentAlignment/title",
          "value": "TVElementContentAlignment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementContentAlignment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementContentAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementContentAlignment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementContentAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1topLeft/title",
          "value": "TVElementPositionTopLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1topLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementPositionTopLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVViewElementStyle~1focusMargin/title",
          "value": "focusMargin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVViewElementStyle~1focusMargin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "focusMargin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementAlignment/title",
          "value": "TVElementAlignment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementAlignment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementAlignment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1center/title",
          "value": "TVElementPositionCenter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1center/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementPositionCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1left/title",
          "value": "TVElementPositionLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1left/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementPositionLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1bottomLeading/title",
          "value": "TVElementPositionBottomLeading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1bottomLeading/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementPositionBottomLeading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1bottomRight/title",
          "value": "TVElementPositionBottomRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1bottomRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementPositionBottomRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1right/title",
          "value": "TVElementPositionRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1right/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementPositionRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1bottom/title",
          "value": "TVElementPositionBottom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1bottom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementPositionBottom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1topTrailing/title",
          "value": "TVElementPositionTopTrailing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1topTrailing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementPositionTopTrailing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1trailing/title",
          "value": "TVElementPositionTrailing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1trailing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementPositionTrailing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1footer/title",
          "value": "TVElementPositionFooter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1footer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementPositionFooter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVViewElementStyle~1contentAlignment/title",
          "value": "contentAlignment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVViewElementStyle~1contentAlignment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contentAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1leading/title",
          "value": "TVElementPositionLeading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementPosition~1leading/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementPositionLeading"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/tvmlkit/tvelementposition"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/tvmlkit/tvelementposition"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
