{
  "abstract": [
    {
      "text": "Describes any changes to the DOM tree after it has been reparsed.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Please use SwiftUI or UIKit",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.tvmlkit/documentation/TVMLKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementUpdateType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@TVElementUpdateType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "TVElementUpdateType"
      }
    ],
    "modules": [
      {
        "name": "TVMLKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "TVElementUpdateType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "9.0",
        "message": "Please use SwiftUI or UIKit",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "TVElementUpdateType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "TVElementUpdateType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit": {
      "abstract": [
        {
          "text": "Create client-server apps by incorporating JavaScript and TVML files in your binary app.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit",
      "kind": "symbol",
      "role": "collection",
      "title": "TVMLKit",
      "type": "topic",
      "url": "/documentation/tvmlkit"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementUpdateType": {
      "abstract": [
        {
          "text": "Describes any changes to the DOM tree after it has been reparsed.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVElementUpdateType"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementUpdateType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVElementUpdateType"
        }
      ],
      "role": "symbol",
      "title": "TVElementUpdateType",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvelementupdatetype"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementUpdateType/children": {
      "abstract": [
        {
          "text": "The order of child nodes have been updated due to the addition, removal, or replacement of child nodes.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "children"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementUpdateType/children",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVElementUpdateTypeChildren"
        }
      ],
      "role": "symbol",
      "title": "TVElementUpdateType.children",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvelementupdatetype/children"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementUpdateType/init(rawValue:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementUpdateType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvelementupdatetype/init(rawvalue:)"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementUpdateType/node": {
      "abstract": [
        {
          "text": "The current node and its subtree have been modified.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "node"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementUpdateType/node",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVElementUpdateTypeSelf"
        }
      ],
      "role": "symbol",
      "title": "TVElementUpdateType.node",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvelementupdatetype/node"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementUpdateType/none": {
      "abstract": [
        {
          "text": "The tree structure did not change.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementUpdateType/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVElementUpdateTypeNone"
        }
      ],
      "role": "symbol",
      "title": "TVElementUpdateType.none",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvelementupdatetype/none"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementUpdateType/styles": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "styles"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementUpdateType/styles",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVElementUpdateTypeStyles"
        }
      ],
      "role": "symbol",
      "title": "TVElementUpdateType.styles",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvelementupdatetype/styles"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementUpdateType/subtree": {
      "abstract": [
        {
          "text": "A subtree element has been updated without affecting the order of any immediate children.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subtree"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementUpdateType/subtree",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVElementUpdateTypeSubtree"
        }
      ],
      "role": "symbol",
      "title": "TVElementUpdateType.subtree",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvelementupdatetype/subtree"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElement/attributes": {
      "abstract": [
        {
          "text": "The attributes associated with a view element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attributes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElement/attributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attributes"
        }
      ],
      "role": "symbol",
      "title": "attributes",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvviewelement/attributes"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElement/autoHighlightIdentifier": {
      "abstract": [
        {
          "text": "A string identifying the element that is initially in focus.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "autoHighlightIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElement/autoHighlightIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "autoHighlightIdentifier"
        }
      ],
      "role": "symbol",
      "title": "autoHighlightIdentifier",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvviewelement/autohighlightidentifier"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElement/children": {
      "abstract": [
        {
          "text": "An array containing the child elements of the element currently being inspected.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "children"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TVViewElement",
          "text": "TVViewElement"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElement/children",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "childViewElements"
        }
      ],
      "role": "symbol",
      "title": "children",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvviewelement/children"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElement/identifier": {
      "abstract": [
        {
          "text": "A string containing the unique identifier for an element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElement/identifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "elementIdentifier"
        }
      ],
      "role": "symbol",
      "title": "identifier",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvviewelement/identifier"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElement/isDisabled": {
      "abstract": [
        {
          "text": "Boolean value indicating whether the current element being inspected is disabled.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isDisabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElement/isDisabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "disabled"
        }
      ],
      "role": "symbol",
      "title": "isDisabled",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvviewelement/isdisabled"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElement/name": {
      "abstract": [
        {
          "text": "A string containing the element’s name.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElement/name",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "elementName"
        }
      ],
      "role": "symbol",
      "title": "name",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvviewelement/name"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElement/parent": {
      "abstract": [
        {
          "text": "The parent of the current node.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "parent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TVViewElement",
          "text": "TVViewElement"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElement/parent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "parentViewElement"
        }
      ],
      "role": "symbol",
      "title": "parent",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvviewelement/parent"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElement/style": {
      "abstract": [
        {
          "text": "The style applied to an element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "style"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TVViewElementStyle",
          "text": "TVViewElementStyle"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElement/style",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "style"
        }
      ],
      "role": "symbol",
      "title": "style",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvviewelement/style"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElement/updateType": {
      "abstract": [
        {
          "text": "The value that describes any changes to the DOM tree after it has been reparsed.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@TVElementUpdateType",
          "text": "TVElementUpdateType"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElement/updateType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updateType"
        }
      ],
      "role": "symbol",
      "title": "updateType",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvviewelement/updatetype"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-a-View-Element",
      "generated": true,
      "identifiers": [
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElement/autoHighlightIdentifier",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElement/attributes",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElement/children",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElement/isDisabled",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElement/identifier",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElement/name",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElement/parent",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElement/style",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElement/updateType"
      ],
      "title": "Inspecting a View Element"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementUpdateType/none",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementUpdateType/subtree",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementUpdateType/children",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementUpdateType/node"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementUpdateType/styles"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementUpdateType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "TVElementUpdateType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementUpdateType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementUpdateType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.tvmlkit/documentation/TVMLKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementUpdateType/none",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementUpdateType/subtree",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementUpdateType/children",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementUpdateType/node"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVElementUpdateType/styles"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Inspecting-a-View-Element",
              "generated": true,
              "identifiers": [
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElement/autoHighlightIdentifier",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElement/attributes",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElement/children",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElement/isDisabled",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElement/identifier",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElement/name",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElement/parent",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElement/style",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElement/updateType"
              ],
              "title": "Inspecting a View Element"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "TVElementUpdateType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Please use SwiftUI or UIKit",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementUpdateType~1node/title",
          "value": "TVElementUpdateTypeSelf"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementUpdateType~1node/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementUpdateTypeSelf"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVViewElement~1name/title",
          "value": "elementName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVViewElement~1name/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "elementName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVViewElement~1children/title",
          "value": "childViewElements"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVViewElement~1children/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "childViewElements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementUpdateType~1none/title",
          "value": "TVElementUpdateTypeNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementUpdateType~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementUpdateTypeNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVViewElement~1parent/title",
          "value": "parentViewElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVViewElement~1parent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "parentViewElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementUpdateType/title",
          "value": "TVElementUpdateType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementUpdateType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementUpdateType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementUpdateType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementUpdateType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVViewElement~1isDisabled/title",
          "value": "disabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVViewElement~1isDisabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "disabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVViewElement~1attributes/title",
          "value": "attributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVViewElement~1attributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "attributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementUpdateType~1subtree/title",
          "value": "TVElementUpdateTypeSubtree"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementUpdateType~1subtree/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementUpdateTypeSubtree"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementUpdateType~1children/title",
          "value": "TVElementUpdateTypeChildren"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementUpdateType~1children/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementUpdateTypeChildren"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementUpdateType~1styles/title",
          "value": "TVElementUpdateTypeStyles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVElementUpdateType~1styles/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVElementUpdateTypeStyles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVViewElement~1style/title",
          "value": "style"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVViewElement~1style/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "style"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVViewElement~1autoHighlightIdentifier/title",
          "value": "autoHighlightIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVViewElement~1autoHighlightIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "autoHighlightIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVViewElement~1updateType/title",
          "value": "updateType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVViewElement~1updateType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "updateType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVViewElement~1identifier/title",
          "value": "elementIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVViewElement~1identifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "elementIdentifier"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/tvmlkit/tvelementupdatetype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/tvmlkit/tvelementupdatetype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
