{
  "abstract": [
    {
      "text": "A protocol that defines methods used to create views and view controllers.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Please use SwiftUI or UIKit",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.tvmlkit/documentation/TVMLKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVInterfaceCreating"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)TVInterfaceCreating",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "TVInterfaceCreating"
      }
    ],
    "modules": [
      {
        "name": "TVMLKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "TVInterfaceCreating"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "9.0",
        "message": "Please use SwiftUI or UIKit",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "TVInterfaceCreating"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "TVInterfaceCreating"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.tvmlkit/documentation/TVMLKit/creating-tvml-elements"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This protocol contains methods used to create views and view controllers from a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElement",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit": {
      "abstract": [
        {
          "text": "Create client-server apps by incorporating JavaScript and TVML files in your binary app.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit",
      "kind": "symbol",
      "role": "collection",
      "title": "TVMLKit",
      "type": "topic",
      "url": "/documentation/tvmlkit"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVBrowserViewController": {
      "abstract": [
        {
          "text": "A view controller that presents content in a browsable, full-screen format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVBrowserViewController"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVBrowserViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVBrowserViewController"
        }
      ],
      "role": "symbol",
      "title": "TVBrowserViewController",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvbrowserviewcontroller"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVDocumentViewController": {
      "abstract": [
        {
          "text": "A view controller that represents a TVMLKit document.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVDocumentViewController"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVDocumentViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVDocumentViewController"
        }
      ],
      "role": "symbol",
      "title": "TVDocumentViewController",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvdocumentviewcontroller"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVInterfaceCreating": {
      "abstract": [
        {
          "text": "A protocol that defines methods used to create views and view controllers.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVInterfaceCreating"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVInterfaceCreating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVInterfaceCreating"
        }
      ],
      "role": "symbol",
      "title": "TVInterfaceCreating",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvinterfacecreating"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVInterfaceCreating/collectionViewCellClass(for:)": {
      "abstract": [
        {
          "text": "Returns a collection view cell for the specified element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "collectionViewCellClass"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TVViewElement",
          "text": "TVViewElement"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8AnyClassa",
          "text": "AnyClass"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVInterfaceCreating/collectionViewCellClass(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "collectionViewCellClassForElement:"
        }
      ],
      "role": "symbol",
      "title": "collectionViewCellClass(for:)",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvinterfacecreating/collectionviewcellclass(for:)"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVInterfaceCreating/makeView(element:existingView:)": {
      "abstract": [
        {
          "text": "Returns a view for a view element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "element"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TVViewElement",
          "text": "TVViewElement"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "existingView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVInterfaceCreating/makeView(element:existingView:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "viewForElement:existingView:"
        }
      ],
      "role": "symbol",
      "title": "makeView(element:existingView:)",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvinterfacecreating/makeview(element:existingview:)"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVInterfaceCreating/makeViewController(element:existingViewController:)": {
      "abstract": [
        {
          "text": "Returns a view controller for a view element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "element"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TVViewElement",
          "text": "TVViewElement"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "existingViewController"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVInterfaceCreating/makeViewController(element:existingViewController:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "viewControllerForElement:existingViewController:"
        }
      ],
      "role": "symbol",
      "title": "makeViewController(element:existingViewController:)",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvinterfacecreating/makeviewcontroller(element:existingviewcontroller:)"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVInterfaceCreating/playerViewController(for:)": {
      "abstract": [
        {
          "text": "Returns the custom player user interface for a custom player.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playerViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TVPlayer",
          "text": "TVPlayer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVInterfaceCreating/playerViewController(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "playerViewControllerForPlayer:"
        }
      ],
      "role": "symbol",
      "title": "playerViewController(for:)",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvinterfacecreating/playerviewcontroller(for:)"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVInterfaceCreating/resourceImage(name:)": {
      "abstract": [
        {
          "text": "Returns the image for the given resource",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resourceImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVInterfaceCreating/resourceImage(name:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageForResource:"
        }
      ],
      "role": "symbol",
      "title": "resourceImage(name:)",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvinterfacecreating/resourceimage(name:)"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVInterfaceCreating/resourceURL(name:)": {
      "abstract": [
        {
          "text": "Returns a URL for the given resource.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resourceURL"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVInterfaceCreating/resourceURL(name:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "URLForResource:"
        }
      ],
      "role": "symbol",
      "title": "resourceURL(name:)",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvinterfacecreating/resourceurl(name:)"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVInterfaceFactory": {
      "abstract": [
        {
          "text": "A factory for the creation of views and view controllers.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVInterfaceFactory"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVInterfaceFactory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVInterfaceFactory"
        }
      ],
      "role": "symbol",
      "title": "TVInterfaceFactory",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvinterfacefactory"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElement": {
      "abstract": [
        {
          "text": "A representation of a read-only DOM node.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVViewElement"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVViewElement"
        }
      ],
      "role": "symbol",
      "title": "TVViewElement",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvviewelement"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/creating-tvml-elements": {
      "abstract": [
        {
          "text": "Avoid rewriting complex and often used elements by creating a simplified custom element.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/creating-tvml-elements",
      "kind": "article",
      "role": "article",
      "title": "Creating TVML Elements",
      "type": "topic",
      "url": "/documentation/tvmlkit/creating-tvml-elements"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVInterfaceFactory"
      ],
      "kind": "relationships",
      "title": "Conforming Types",
      "type": "conformingTypes"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Views-and-View-Controllers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElement",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVInterfaceFactory",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVBrowserViewController",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVDocumentViewController"
      ],
      "title": "Views and View Controllers"
    }
  ],
  "topicSections": [
    {
      "anchor": "Retrieving-Resource-Information",
      "identifiers": [
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVInterfaceCreating/resourceImage(name:)",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVInterfaceCreating/resourceURL(name:)"
      ],
      "title": "Retrieving Resource Information"
    },
    {
      "anchor": "Updating-View-Information",
      "identifiers": [
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVInterfaceCreating/makeViewController(element:existingViewController:)",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVInterfaceCreating/makeView(element:existingView:)",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVInterfaceCreating/collectionViewCellClass(for:)",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVInterfaceCreating/playerViewController(for:)"
      ],
      "title": "Updating View Information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "TVInterfaceCreating"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVInterfaceCreating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVInterfaceCreating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.tvmlkit/documentation/TVMLKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Retrieving-Resource-Information",
              "identifiers": [
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVInterfaceCreating/resourceImage(name:)",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVInterfaceCreating/resourceURL(name:)"
              ],
              "title": "Retrieving Resource Information"
            },
            {
              "anchor": "Updating-View-Information",
              "identifiers": [
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVInterfaceCreating/makeViewController(element:existingViewController:)",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVInterfaceCreating/makeView(element:existingView:)",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVInterfaceCreating/collectionViewCellClass(for:)",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVInterfaceCreating/playerViewController(for:)"
              ],
              "title": "Updating View Information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVInterfaceFactory"
              ],
              "kind": "relationships",
              "title": "Conforming Types",
              "type": "conformingTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Views-and-View-Controllers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVViewElement",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVInterfaceFactory",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVBrowserViewController",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVDocumentViewController"
              ],
              "title": "Views and View Controllers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "TVInterfaceCreating"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Please use SwiftUI or UIKit",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVBrowserViewController/title",
          "value": "TVBrowserViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVBrowserViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVBrowserViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVBrowserViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVBrowserViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVInterfaceCreating~1makeView(element:existingView:)/title",
          "value": "viewForElement:existingView:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVInterfaceCreating~1makeView(element:existingView:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "viewForElement:existingView:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVInterfaceCreating~1makeViewController(element:existingViewController:)/title",
          "value": "viewControllerForElement:existingViewController:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVInterfaceCreating~1makeViewController(element:existingViewController:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "viewControllerForElement:existingViewController:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVInterfaceCreating/title",
          "value": "TVInterfaceCreating"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVInterfaceCreating/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVInterfaceCreating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVInterfaceCreating/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVInterfaceCreating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVViewElement/title",
          "value": "TVViewElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVViewElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVViewElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVViewElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVViewElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVDocumentViewController/title",
          "value": "TVDocumentViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVDocumentViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVDocumentViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVDocumentViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVDocumentViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVInterfaceCreating~1resourceImage(name:)/title",
          "value": "imageForResource:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVInterfaceCreating~1resourceImage(name:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "imageForResource:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVInterfaceCreating~1collectionViewCellClass(for:)/title",
          "value": "collectionViewCellClassForElement:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVInterfaceCreating~1collectionViewCellClass(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "collectionViewCellClassForElement:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVInterfaceFactory/title",
          "value": "TVInterfaceFactory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVInterfaceFactory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVInterfaceFactory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVInterfaceFactory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVInterfaceFactory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVInterfaceCreating~1resourceURL(name:)/title",
          "value": "URLForResource:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVInterfaceCreating~1resourceURL(name:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "URLForResource:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVInterfaceCreating~1playerViewController(for:)/title",
          "value": "playerViewControllerForPlayer:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVInterfaceCreating~1playerViewController(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "playerViewControllerForPlayer:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/tvmlkit/tvinterfacecreating"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/tvmlkit/tvinterfacecreating"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
