{
  "abstract": [
    {
      "text": "A single audio or video item associated with the Apple TV JavaScript player.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Please use SwiftUI or UIKit",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.tvmlkit/documentation/TVMLKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)TVMediaItem",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "TVMediaItem"
      }
    ],
    "modules": [
      {
        "name": "TVMLKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "TVMediaItem"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "12.0",
        "message": "Please use SwiftUI or UIKit",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "TVMediaItem"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "TVMediaItem"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A ",
              "type": "text"
            },
            {
              "code": "TVMediaItem",
              "type": "codeVoice"
            },
            {
              "text": " object contains read-only information about a media item associated with the JavaScript player. You can use this information with your own custom ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVPlayer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects exposed through a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. For example, you can retrieve audio track information from the JavaScript player and play the track through a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/AVFoundation/AVPlayer": {
      "abstract": [
        {
          "text": "An object that provides the interface to control the player’s transport behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayer"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVPlayer",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVPlayer",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVPlayer"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit": {
      "abstract": [
        {
          "text": "Create client-server apps by incorporating JavaScript and TVML files in your binary app.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit",
      "kind": "symbol",
      "role": "collection",
      "title": "TVMLKit",
      "type": "topic",
      "url": "/documentation/tvmlkit"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem": {
      "abstract": [
        {
          "text": "A single audio or video item associated with the Apple TV JavaScript player.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVMediaItem"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVMediaItem"
        }
      ],
      "role": "symbol",
      "title": "TVMediaItem",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvmediaitem"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/ContentRatingDomain-swift.struct": {
      "abstract": [
        {
          "text": "A value identifying the media’s content rating domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ContentRatingDomain"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/ContentRatingDomain-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ContentRatingDomain"
        }
      ],
      "role": "symbol",
      "title": "TVMediaItem.ContentRatingDomain",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvmediaitem/contentratingdomain-swift.struct"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/HighlightGroup": {
      "abstract": [
        {
          "text": "A container for groups of highlights for a media item.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HighlightGroup"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/HighlightGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HighlightGroup"
        }
      ],
      "role": "symbol",
      "title": "TVMediaItem.HighlightGroup",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvmediaitem/highlightgroup"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/MediaType": {
      "abstract": [
        {
          "text": "A value indicating whether the media is audio or video.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MediaType"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/MediaType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MediaType"
        }
      ],
      "role": "symbol",
      "title": "TVMediaItem.MediaType",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvmediaitem/mediatype"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/TimeRange": {
      "abstract": [
        {
          "text": "An object that defines a time range in a media item.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TimeRange"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/TimeRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TimeRange"
        }
      ],
      "role": "symbol",
      "title": "TVMediaItem.TimeRange",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvmediaitem/timerange"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/artworkImageURL": {
      "abstract": [
        {
          "text": "The URL path to the artwork that accompanies the media item.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "artworkImageURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/artworkImageURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "artworkImageURL"
        }
      ],
      "role": "symbol",
      "title": "artworkImageURL",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvmediaitem/artworkimageurl"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/containsExplicitContent": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the item contains adult-oriented content.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "containsExplicitContent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/containsExplicitContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "containsExplicitContent"
        }
      ],
      "role": "symbol",
      "title": "containsExplicitContent",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvmediaitem/containsexplicitcontent"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/contentRatingDomain-swift.property": {
      "abstract": [
        {
          "text": "The media domain that the rating applies to.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentRatingDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TVMediaItem",
          "text": "TVMediaItem"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@TVMediaItemContentRatingDomain",
          "text": "ContentRatingDomain"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/contentRatingDomain-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentRatingDomain"
        }
      ],
      "role": "symbol",
      "title": "contentRatingDomain",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvmediaitem/contentratingdomain-swift.property"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/contentRatingRanking": {
      "abstract": [
        {
          "text": "The rating for a video item.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentRatingRanking"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/contentRatingRanking",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentRatingRanking"
        }
      ],
      "role": "symbol",
      "title": "contentRatingRanking",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvmediaitem/contentratingranking"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/highlightGroups": {
      "abstract": [
        {
          "text": "An array containing groups of individual highlights in a media item.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "highlightGroups"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TVMediaItem",
          "text": "TVMediaItem"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TVHighlightGroup",
          "text": "HighlightGroup"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/highlightGroups",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "highlightGroups"
        }
      ],
      "role": "symbol",
      "title": "highlightGroups",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvmediaitem/highlightgroups"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/interstitials": {
      "abstract": [
        {
          "text": "An array of time intervals that indicate where to insert media items into another, single media item.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interstitials"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TVMediaItem",
          "text": "TVMediaItem"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TVTimeRange",
          "text": "TimeRange"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/interstitials",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "interstitials"
        }
      ],
      "role": "symbol",
      "title": "interstitials",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvmediaitem/interstitials"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/itemDescription": {
      "abstract": [
        {
          "text": "The description for a media item.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "itemDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/itemDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "itemDescription"
        }
      ],
      "role": "symbol",
      "title": "itemDescription",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvmediaitem/itemdescription"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/resumeTime": {
      "abstract": [
        {
          "text": "The number of seconds from the beginning of a media item to the point where that media item begins playing.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resumeTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/resumeTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resumeTime"
        }
      ],
      "role": "symbol",
      "title": "resumeTime",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvmediaitem/resumetime"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/subtitle": {
      "abstract": [
        {
          "text": "The subtitle for a media item.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subtitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/subtitle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subtitle"
        }
      ],
      "role": "symbol",
      "title": "subtitle",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvmediaitem/subtitle"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/title": {
      "abstract": [
        {
          "text": "The title for a media item.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "title"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/title",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "title"
        }
      ],
      "role": "symbol",
      "title": "title",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvmediaitem/title"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/type": {
      "abstract": [
        {
          "text": "The type of media item.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TVMediaItem",
          "text": "TVMediaItem"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@TVMediaItemType",
          "text": "MediaType"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "type"
        }
      ],
      "role": "symbol",
      "title": "type",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvmediaitem/type"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/url": {
      "abstract": [
        {
          "text": "The URL path to the media item.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "url"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/url",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "url"
        }
      ],
      "role": "symbol",
      "title": "url",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvmediaitem/url"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/userInfo": {
      "abstract": [
        {
          "text": "User-defined metadata, like a developer-specific identifier, for a media item.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userInfo"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/userInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "userInfo"
        }
      ],
      "role": "symbol",
      "title": "userInfo",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvmediaitem/userinfo"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer": {
      "abstract": [
        {
          "text": "A customizable native media player used to control playback from the JavaScript player used in an Apple TV client-server app.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVPlayer"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVPlayer"
        }
      ],
      "role": "symbol",
      "title": "TVPlayer",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvplayer"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaylist": {
      "abstract": [
        {
          "text": "A collection of media items associated with the Apple TV JavaScript player.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVPlaylist"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaylist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVPlaylist"
        }
      ],
      "role": "symbol",
      "title": "TVPlaylist",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvplaylist"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Custom-Player",
      "generated": true,
      "identifiers": [
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaylist",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer"
      ],
      "title": "Custom Player"
    }
  ],
  "topicSections": [
    {
      "anchor": "Rating-Media-Content",
      "identifiers": [
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/containsExplicitContent",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/contentRatingDomain-swift.property",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/ContentRatingDomain-swift.struct",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/contentRatingRanking"
      ],
      "title": "Rating Media Content"
    },
    {
      "anchor": "Identifying-Media-Items",
      "identifiers": [
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/artworkImageURL",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/itemDescription",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/subtitle",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/title",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/type",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/MediaType",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/url",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/userInfo"
      ],
      "title": "Identifying Media Items"
    },
    {
      "anchor": "Setting-Timing-Options",
      "identifiers": [
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/highlightGroups",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/HighlightGroup",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/interstitials",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/TimeRange",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/resumeTime"
      ],
      "title": "Setting Timing Options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "TVMediaItem"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVMediaItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVMediaItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.tvmlkit/documentation/TVMLKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Rating-Media-Content",
              "identifiers": [
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/containsExplicitContent",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/contentRatingDomain-swift.property",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/ContentRatingDomain-swift.struct",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/contentRatingRanking"
              ],
              "title": "Rating Media Content"
            },
            {
              "anchor": "Identifying-Media-Items",
              "identifiers": [
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/artworkImageURL",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/itemDescription",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/subtitle",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/title",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/type",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/MediaType",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/url",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/userInfo"
              ],
              "title": "Identifying Media Items"
            },
            {
              "anchor": "Setting-Timing-Options",
              "identifiers": [
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/highlightGroups",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/HighlightGroup",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/interstitials",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/TimeRange",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/resumeTime"
              ],
              "title": "Setting Timing Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Custom-Player",
              "generated": true,
              "identifiers": [
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaylist",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer"
              ],
              "title": "Custom Player"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "TVMediaItem"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Please use SwiftUI or UIKit",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1contentRatingDomain-swift.property/title",
          "value": "contentRatingDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1contentRatingDomain-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contentRatingDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1itemDescription/title",
          "value": "itemDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1itemDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "itemDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1userInfo/title",
          "value": "userInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1userInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "userInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1ContentRatingDomain-swift.struct/title",
          "value": "TVMediaItemContentRatingDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1ContentRatingDomain-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVMediaItemContentRatingDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1ContentRatingDomain-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVMediaItemContentRatingDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1type/title",
          "value": "type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1highlightGroups/title",
          "value": "highlightGroups"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1highlightGroups/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "highlightGroups"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1url/title",
          "value": "url"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1url/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "url"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1resumeTime/title",
          "value": "resumeTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1resumeTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "resumeTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1containsExplicitContent/title",
          "value": "containsExplicitContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1containsExplicitContent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "containsExplicitContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlayer/title",
          "value": "TVPlayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVPlayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVPlayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1TimeRange/title",
          "value": "TVTimeRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1TimeRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVTimeRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1TimeRange/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVTimeRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVPlayer/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVPlayer"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1title/title",
          "value": "title"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1title/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "title"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1HighlightGroup/title",
          "value": "TVHighlightGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1HighlightGroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVHighlightGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1HighlightGroup/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVHighlightGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1subtitle/title",
          "value": "subtitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1subtitle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "subtitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlaylist/title",
          "value": "TVPlaylist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlaylist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVPlaylist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlaylist/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVPlaylist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1contentRatingRanking/title",
          "value": "contentRatingRanking"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1contentRatingRanking/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contentRatingRanking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem/title",
          "value": "TVMediaItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVMediaItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVMediaItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1MediaType/title",
          "value": "TVMediaItemType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1MediaType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVMediaItemType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1MediaType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVMediaItemType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1artworkImageURL/title",
          "value": "artworkImageURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1artworkImageURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "artworkImageURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1interstitials/title",
          "value": "interstitials"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1interstitials/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "interstitials"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/tvmlkit/tvmediaitem"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/tvmlkit/tvmediaitem"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
