{
  "abstract": [
    {
      "text": "The user information used in a custom playback event.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Please use SwiftUI or UIKit",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.tvmlkit/documentation/TVMLKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaybackCustomEventUserInfo"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)TVPlaybackCustomEventUserInfo",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "TVPlaybackCustomEventUserInfo"
      }
    ],
    "modules": [
      {
        "name": "TVMLKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "TVPlaybackCustomEventUserInfo"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "12.0",
        "message": "Please use SwiftUI or UIKit",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "TVPlaybackCustomEventUserInfo"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "TVPlaybackCustomEventUserInfo"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit": {
      "abstract": [
        {
          "text": "Create client-server apps by incorporating JavaScript and TVML files in your binary app.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit",
      "kind": "symbol",
      "role": "collection",
      "title": "TVMLKit",
      "type": "topic",
      "url": "/documentation/tvmlkit"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaybackCustomEventUserInfo": {
      "abstract": [
        {
          "text": "The user information used in a custom playback event.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVPlaybackCustomEventUserInfo"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaybackCustomEventUserInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVPlaybackCustomEventUserInfo"
        }
      ],
      "role": "symbol",
      "title": "TVPlaybackCustomEventUserInfo",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvplaybackcustomeventuserinfo"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaybackCustomEventUserInfo/expectsReturnValue": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the custom event expects to contain a return value.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "expectsReturnValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaybackCustomEventUserInfo/expectsReturnValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "expectsReturnValue"
        }
      ],
      "role": "symbol",
      "title": "expectsReturnValue",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvplaybackcustomeventuserinfo/expectsreturnvalue"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaybackCustomEventUserInfo/init(properties:expectsReturnValue:)": {
      "abstract": [
        {
          "text": "Create a new custom playback event user info dictionary.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "properties"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@TVPlaybackEventProperty",
          "text": "TVPlaybackEventProperty"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?, "
        },
        {
          "kind": "externalParam",
          "text": "expectsReturnValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaybackCustomEventUserInfo/init(properties:expectsReturnValue:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithProperties:expectsReturnValue:"
        }
      ],
      "role": "symbol",
      "title": "init(properties:expectsReturnValue:)",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvplaybackcustomeventuserinfo/init(properties:expectsreturnvalue:)"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaybackCustomEventUserInfo/returnValue": {
      "abstract": [
        {
          "text": "The return value type for the custom event.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "returnValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaybackCustomEventUserInfo/returnValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "returnValue"
        }
      ],
      "role": "symbol",
      "title": "returnValue",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvplaybackcustomeventuserinfo/returnvalue"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaybackEvent": {
      "abstract": [
        {
          "text": "Extend this structure to send your custom playback events to the JavaScript environment.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVPlaybackEvent"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaybackEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVPlaybackEvent"
        }
      ],
      "role": "symbol",
      "title": "TVPlaybackEvent",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvplaybackevent"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaybackEventMarshaling": {
      "abstract": [
        {
          "text": "A protocol used for sending and receiving information across the JavaScript bridge.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVPlaybackEventMarshaling"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaybackEventMarshaling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVPlaybackEventMarshaling"
        }
      ],
      "role": "symbol",
      "title": "TVPlaybackEventMarshaling",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvplaybackeventmarshaling"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaybackEventProperty": {
      "abstract": [
        {
          "text": "Extend this structure to create your own custom playback event properties.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVPlaybackEventProperty"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaybackEventProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVPlaybackEventProperty"
        }
      ],
      "role": "symbol",
      "title": "TVPlaybackEventProperty",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvplaybackeventproperty"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaybackState": {
      "abstract": [
        {
          "text": "The possible states of a player.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVPlaybackState"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaybackState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVPlaybackState"
        }
      ],
      "role": "symbol",
      "title": "TVPlaybackState",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvplaybackstate"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/dispatch(event:userInfo:completion:)": {
      "abstract": [
        {
          "text": "Dispatches custom playback events to the JavaScript environment.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dispatch"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "event"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@TVPlaybackEvent",
          "text": "TVPlaybackEvent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "userInfo"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)TVPlaybackEventMarshaling",
          "text": "TVPlaybackEventMarshaling"
        },
        {
          "kind": "text",
          "text": ")?, "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/dispatch(event:userInfo:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatchEvent:userInfo:completion:"
        }
      ],
      "role": "symbol",
      "title": "dispatch(event:userInfo:completion:)",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvplayer/dispatch(event:userinfo:completion:)"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/next()": {
      "abstract": [
        {
          "text": "Plays the next media item in the playlist.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "next"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/next()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "next"
        }
      ],
      "role": "symbol",
      "title": "next()",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvplayer/next()"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/pause()": {
      "abstract": [
        {
          "text": "Pauses the currently playing item.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pause"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/pause()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pause"
        }
      ],
      "role": "symbol",
      "title": "pause()",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvplayer/pause()"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/previous()": {
      "abstract": [
        {
          "text": "Plays the previous media item in the playlist.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "previous"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/previous()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "previous"
        }
      ],
      "role": "symbol",
      "title": "previous()",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvplayer/previous()"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/state": {
      "abstract": [
        {
          "text": "The current state of the player.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "state"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@TVPlaybackState",
          "text": "TVPlaybackState"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/state",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "state"
        }
      ],
      "role": "symbol",
      "title": "state",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvplayer/state"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaybackEventMarshaling"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Controlling-Playback",
      "generated": true,
      "identifiers": [
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/next()",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/pause()",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/previous()",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/state",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaybackState",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/dispatch(event:userInfo:completion:)",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaybackEvent",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaybackEventMarshaling"
      ],
      "title": "Controlling Playback"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-User-Info-for-Custom-Playback-Events",
      "identifiers": [
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaybackCustomEventUserInfo/init(properties:expectsReturnValue:)",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaybackEventProperty",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaybackCustomEventUserInfo/expectsReturnValue",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaybackCustomEventUserInfo/returnValue"
      ],
      "title": "Creating User Info for Custom Playback Events"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "TVPlaybackCustomEventUserInfo"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVPlaybackCustomEventUserInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVPlaybackCustomEventUserInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.tvmlkit/documentation/TVMLKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-User-Info-for-Custom-Playback-Events",
              "identifiers": [
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaybackCustomEventUserInfo/init(properties:expectsReturnValue:)",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaybackEventProperty",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaybackCustomEventUserInfo/expectsReturnValue",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaybackCustomEventUserInfo/returnValue"
              ],
              "title": "Creating User Info for Custom Playback Events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaybackEventMarshaling"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Controlling-Playback",
              "generated": true,
              "identifiers": [
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/next()",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/pause()",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/previous()",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/state",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaybackState",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/dispatch(event:userInfo:completion:)",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaybackEvent",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaybackEventMarshaling"
              ],
              "title": "Controlling Playback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "TVPlaybackCustomEventUserInfo"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Please use SwiftUI or UIKit",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlaybackState/title",
          "value": "TVPlaybackState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlaybackState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVPlaybackState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlaybackState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVPlaybackState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlaybackEvent/title",
          "value": "TVPlaybackEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlaybackEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVPlaybackEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlaybackEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVPlaybackEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlayer~1next()/title",
          "value": "next"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlayer~1next()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "next"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlaybackCustomEventUserInfo/title",
          "value": "TVPlaybackCustomEventUserInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlaybackCustomEventUserInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVPlaybackCustomEventUserInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlaybackCustomEventUserInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVPlaybackCustomEventUserInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlayer~1dispatch(event:userInfo:completion:)/title",
          "value": "dispatchEvent:userInfo:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlayer~1dispatch(event:userInfo:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "dispatchEvent:userInfo:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlaybackEventMarshaling/title",
          "value": "TVPlaybackEventMarshaling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlaybackEventMarshaling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVPlaybackEventMarshaling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlaybackEventMarshaling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVPlaybackEventMarshaling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlaybackCustomEventUserInfo~1returnValue/title",
          "value": "returnValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlaybackCustomEventUserInfo~1returnValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "returnValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlayer~1previous()/title",
          "value": "previous"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlayer~1previous()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "previous"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlaybackCustomEventUserInfo~1expectsReturnValue/title",
          "value": "expectsReturnValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlaybackCustomEventUserInfo~1expectsReturnValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "expectsReturnValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlaybackCustomEventUserInfo~1init(properties:expectsReturnValue:)/title",
          "value": "initWithProperties:expectsReturnValue:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlaybackCustomEventUserInfo~1init(properties:expectsReturnValue:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithProperties:expectsReturnValue:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlayer~1state/title",
          "value": "state"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlayer~1state/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "state"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlaybackEventProperty/title",
          "value": "TVPlaybackEventProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlaybackEventProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVPlaybackEventProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlaybackEventProperty/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVPlaybackEventProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlayer~1pause()/title",
          "value": "pause"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlayer~1pause()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pause"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/tvmlkit/tvplaybackcustomeventuserinfo"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/tvmlkit/tvplaybackcustomeventuserinfo"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
