{
  "abstract": [
    {
      "text": "A customizable native media player used to control playback from the JavaScript player used in an Apple TV client-server app.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Please use SwiftUI or UIKit",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.tvmlkit/documentation/TVMLKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)TVPlayer",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "TVPlayer"
      }
    ],
    "modules": [
      {
        "name": "TVMLKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "TVPlayer"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "12.0",
        "message": "Please use SwiftUI or UIKit",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "TVPlayer"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "TVPlayer"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You create a new ",
              "type": "text"
            },
            {
              "code": "TVPlayer",
              "type": "codeVoice"
            },
            {
              "text": " object using your custom ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVPlayer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. You can then play media items that are associated with the JavaScript media player using the new player. For example, you can add gestures, overlays, and other custom features to your TV player.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/AVFoundation/AVPlayer": {
      "abstract": [
        {
          "text": "An object that provides the interface to control the player’s transport behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayer"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVPlayer",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVPlayer",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVPlayer"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit": {
      "abstract": [
        {
          "text": "Create client-server apps by incorporating JavaScript and TVML files in your binary app.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit",
      "kind": "symbol",
      "role": "collection",
      "title": "TVMLKit",
      "type": "topic",
      "url": "/documentation/tvmlkit"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem": {
      "abstract": [
        {
          "text": "A single audio or video item associated with the Apple TV JavaScript player.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVMediaItem"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVMediaItem"
        }
      ],
      "role": "symbol",
      "title": "TVMediaItem",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvmediaitem"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaybackCustomEventUserInfo": {
      "abstract": [
        {
          "text": "The user information used in a custom playback event.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVPlaybackCustomEventUserInfo"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaybackCustomEventUserInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVPlaybackCustomEventUserInfo"
        }
      ],
      "role": "symbol",
      "title": "TVPlaybackCustomEventUserInfo",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvplaybackcustomeventuserinfo"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaybackEvent": {
      "abstract": [
        {
          "text": "Extend this structure to send your custom playback events to the JavaScript environment.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVPlaybackEvent"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaybackEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVPlaybackEvent"
        }
      ],
      "role": "symbol",
      "title": "TVPlaybackEvent",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvplaybackevent"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaybackEventMarshaling": {
      "abstract": [
        {
          "text": "A protocol used for sending and receiving information across the JavaScript bridge.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVPlaybackEventMarshaling"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaybackEventMarshaling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVPlaybackEventMarshaling"
        }
      ],
      "role": "symbol",
      "title": "TVPlaybackEventMarshaling",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvplaybackeventmarshaling"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaybackState": {
      "abstract": [
        {
          "text": "The possible states of a player.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVPlaybackState"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaybackState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVPlaybackState"
        }
      ],
      "role": "symbol",
      "title": "TVPlaybackState",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvplaybackstate"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer": {
      "abstract": [
        {
          "text": "A customizable native media player used to control playback from the JavaScript player used in an Apple TV client-server app.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVPlayer"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVPlayer"
        }
      ],
      "role": "symbol",
      "title": "TVPlayer",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvplayer"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/currentMediaItem": {
      "abstract": [
        {
          "text": "The currently selected media item.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentMediaItem"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TVMediaItem",
          "text": "TVMediaItem"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/currentMediaItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentMediaItem"
        }
      ],
      "role": "symbol",
      "title": "currentMediaItem",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvplayer/currentmediaitem"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/dispatch(event:userInfo:completion:)": {
      "abstract": [
        {
          "text": "Dispatches custom playback events to the JavaScript environment.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dispatch"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "event"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@TVPlaybackEvent",
          "text": "TVPlaybackEvent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "userInfo"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)TVPlaybackEventMarshaling",
          "text": "TVPlaybackEventMarshaling"
        },
        {
          "kind": "text",
          "text": ")?, "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/dispatch(event:userInfo:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatchEvent:userInfo:completion:"
        }
      ],
      "role": "symbol",
      "title": "dispatch(event:userInfo:completion:)",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvplayer/dispatch(event:userinfo:completion:)"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/init(player:)": {
      "abstract": [
        {
          "text": "Creates a new customizable player from an existing player.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "player"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVPlayer",
          "text": "AVPlayer"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/init(player:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithPlayer:"
        }
      ],
      "role": "symbol",
      "title": "init(player:)",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvplayer/init(player:)"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/next()": {
      "abstract": [
        {
          "text": "Plays the next media item in the playlist.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "next"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/next()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "next"
        }
      ],
      "role": "symbol",
      "title": "next()",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvplayer/next()"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/nextMediaItem": {
      "abstract": [
        {
          "text": "The next media item in the playlist.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nextMediaItem"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TVMediaItem",
          "text": "TVMediaItem"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/nextMediaItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nextMediaItem"
        }
      ],
      "role": "symbol",
      "title": "nextMediaItem",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvplayer/nextmediaitem"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/pause()": {
      "abstract": [
        {
          "text": "Pauses the currently playing item.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pause"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/pause()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pause"
        }
      ],
      "role": "symbol",
      "title": "pause()",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvplayer/pause()"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/player": {
      "abstract": [
        {
          "text": "The customizable media player.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "player"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVPlayer",
          "text": "AVPlayer"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/player",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "player"
        }
      ],
      "role": "symbol",
      "title": "player",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvplayer/player"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/playlist": {
      "abstract": [
        {
          "text": "The playlist for the media player.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playlist"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TVPlaylist",
          "text": "TVPlaylist"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/playlist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "playlist"
        }
      ],
      "role": "symbol",
      "title": "playlist",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvplayer/playlist"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/present(animated:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "present"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "animated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/present(animated:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "presentWithAnimation:"
        }
      ],
      "role": "symbol",
      "title": "present(animated:)",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvplayer/present(animated:)"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/previous()": {
      "abstract": [
        {
          "text": "Plays the previous media item in the playlist.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "previous"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/previous()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "previous"
        }
      ],
      "role": "symbol",
      "title": "previous()",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvplayer/previous()"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/previousMediaItem": {
      "abstract": [
        {
          "text": "The previously selected media item.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "previousMediaItem"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TVMediaItem",
          "text": "TVMediaItem"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/previousMediaItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "previousMediaItem"
        }
      ],
      "role": "symbol",
      "title": "previousMediaItem",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvplayer/previousmediaitem"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/setCurrentMediaItem(toItemAtIndex:)": {
      "abstract": [
        {
          "text": "Sets the current media item to the designated media item.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setCurrentMediaItem"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "toItemAtIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/setCurrentMediaItem(toItemAtIndex:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "changeToMediaItemAtIndex:"
        }
      ],
      "role": "symbol",
      "title": "setCurrentMediaItem(toItemAtIndex:)",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvplayer/setcurrentmediaitem(toitematindex:)"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/state": {
      "abstract": [
        {
          "text": "The current state of the player.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "state"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@TVPlaybackState",
          "text": "TVPlaybackState"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/state",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "state"
        }
      ],
      "role": "symbol",
      "title": "state",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvplayer/state"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaylist": {
      "abstract": [
        {
          "text": "A collection of media items associated with the Apple TV JavaScript player.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVPlaylist"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaylist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVPlaylist"
        }
      ],
      "role": "symbol",
      "title": "TVPlaylist",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvplaylist"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Custom-Player",
      "generated": true,
      "identifiers": [
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaylist"
      ],
      "title": "Custom Player"
    }
  ],
  "topicSections": [
    {
      "anchor": "Setting-Up-the-Player",
      "identifiers": [
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/init(player:)",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/player",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/playlist"
      ],
      "title": "Setting Up the Player"
    },
    {
      "anchor": "Controlling-Playback",
      "identifiers": [
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/next()",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/pause()",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/previous()",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/state",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaybackState",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/dispatch(event:userInfo:completion:)",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaybackEvent",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaybackEventMarshaling",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaybackCustomEventUserInfo"
      ],
      "title": "Controlling Playback"
    },
    {
      "anchor": "Inspecting-Media-Items",
      "identifiers": [
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/setCurrentMediaItem(toItemAtIndex:)",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/previousMediaItem",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/currentMediaItem",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/nextMediaItem"
      ],
      "title": "Inspecting Media Items"
    },
    {
      "anchor": "Instance-Methods",
      "identifiers": [
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/present(animated:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "TVPlayer"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVPlayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVPlayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.tvmlkit/documentation/TVMLKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Setting-Up-the-Player",
              "identifiers": [
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/init(player:)",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/player",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/playlist"
              ],
              "title": "Setting Up the Player"
            },
            {
              "anchor": "Controlling-Playback",
              "identifiers": [
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/next()",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/pause()",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/previous()",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/state",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaybackState",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/dispatch(event:userInfo:completion:)",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaybackEvent",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaybackEventMarshaling",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaybackCustomEventUserInfo"
              ],
              "title": "Controlling Playback"
            },
            {
              "anchor": "Inspecting-Media-Items",
              "identifiers": [
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/setCurrentMediaItem(toItemAtIndex:)",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/previousMediaItem",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/currentMediaItem",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/nextMediaItem"
              ],
              "title": "Inspecting Media Items"
            },
            {
              "anchor": "Instance-Methods",
              "identifiers": [
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlayer/present(animated:)"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Custom-Player",
              "generated": true,
              "identifiers": [
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVPlaylist"
              ],
              "title": "Custom Player"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "TVPlayer"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Please use SwiftUI or UIKit",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlayer~1present(animated:)/title",
          "value": "presentWithAnimation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlayer~1present(animated:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "presentWithAnimation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlaybackEvent/title",
          "value": "TVPlaybackEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlaybackEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVPlaybackEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlaybackEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVPlaybackEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlayer~1previous()/title",
          "value": "previous"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlayer~1previous()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "previous"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlayer~1pause()/title",
          "value": "pause"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlayer~1pause()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pause"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlayer~1dispatch(event:userInfo:completion:)/title",
          "value": "dispatchEvent:userInfo:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlayer~1dispatch(event:userInfo:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "dispatchEvent:userInfo:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlayer/title",
          "value": "TVPlayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVPlayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVPlayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlayer~1player/title",
          "value": "player"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlayer~1player/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "player"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlayer~1nextMediaItem/title",
          "value": "nextMediaItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlayer~1nextMediaItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nextMediaItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlayer~1next()/title",
          "value": "next"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlayer~1next()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "next"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlaylist/title",
          "value": "TVPlaylist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlaylist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVPlaylist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlaylist/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVPlaylist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlaybackEventMarshaling/title",
          "value": "TVPlaybackEventMarshaling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlaybackEventMarshaling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVPlaybackEventMarshaling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlaybackEventMarshaling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVPlaybackEventMarshaling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlayer~1previousMediaItem/title",
          "value": "previousMediaItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlayer~1previousMediaItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "previousMediaItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlaybackCustomEventUserInfo/title",
          "value": "TVPlaybackCustomEventUserInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlaybackCustomEventUserInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVPlaybackCustomEventUserInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlaybackCustomEventUserInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVPlaybackCustomEventUserInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlayer~1currentMediaItem/title",
          "value": "currentMediaItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlayer~1currentMediaItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentMediaItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlayer~1setCurrentMediaItem(toItemAtIndex:)/title",
          "value": "changeToMediaItemAtIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlayer~1setCurrentMediaItem(toItemAtIndex:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "changeToMediaItemAtIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlaybackState/title",
          "value": "TVPlaybackState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlaybackState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVPlaybackState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlaybackState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVPlaybackState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVPlayer/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVPlayer"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlayer~1playlist/title",
          "value": "playlist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlayer~1playlist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "playlist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem/title",
          "value": "TVMediaItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVMediaItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVMediaItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlayer~1state/title",
          "value": "state"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlayer~1state/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "state"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlayer~1init(player:)/title",
          "value": "initWithPlayer:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVPlayer~1init(player:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithPlayer:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/tvmlkit/tvplayer"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/tvmlkit/tvplayer"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
