{
  "abstract": [
    {
      "text": "Constants that identify playback suspension reasons.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension/Reason-swift.struct"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AVFoundation",
    "externalID": "c:@T@AVCoordinatedPlaybackSuspensionReason",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Reason"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Reason"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "AVCoordinatedPlaybackSuspension.Reason"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Reason"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension": {
      "abstract": [
        {
          "text": "An object that represents a temporary suspension of coordinated playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCoordinatedPlaybackSuspension"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCoordinatedPlaybackSuspension"
        }
      ],
      "role": "symbol",
      "title": "AVCoordinatedPlaybackSuspension",
      "type": "topic",
      "url": "/documentation/avfoundation/avcoordinatedplaybacksuspension"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension/Reason-swift.struct": {
      "abstract": [
        {
          "text": "Constants that identify playback suspension reasons.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Reason"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension/Reason-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Reason"
        }
      ],
      "role": "symbol",
      "title": "AVCoordinatedPlaybackSuspension.Reason",
      "type": "topic",
      "url": "/documentation/avfoundation/avcoordinatedplaybacksuspension/reason-swift.struct"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension/Reason-swift.struct/audioSessionInterrupted": {
      "abstract": [
        {
          "text": "The system interrupts a participant’s audio session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audioSessionInterrupted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCoordinatedPlaybackSuspension",
          "text": "AVCoordinatedPlaybackSuspension"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVCoordinatedPlaybackSuspensionReason",
          "text": "Reason"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension/Reason-swift.struct/audioSessionInterrupted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCoordinatedPlaybackSuspensionReasonAudioSessionInterrupted"
        }
      ],
      "role": "symbol",
      "title": "audioSessionInterrupted",
      "type": "topic",
      "url": "/documentation/avfoundation/avcoordinatedplaybacksuspension/reason-swift.struct/audiosessioninterrupted"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension/Reason-swift.struct/coordinatedPlaybackNotPossible": {
      "abstract": [
        {
          "text": "It’s not possible for a participant to start or resume coordinated playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "coordinatedPlaybackNotPossible"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCoordinatedPlaybackSuspension",
          "text": "AVCoordinatedPlaybackSuspension"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVCoordinatedPlaybackSuspensionReason",
          "text": "Reason"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension/Reason-swift.struct/coordinatedPlaybackNotPossible",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCoordinatedPlaybackSuspensionReasonCoordinatedPlaybackNotPossible"
        }
      ],
      "role": "symbol",
      "title": "coordinatedPlaybackNotPossible",
      "type": "topic",
      "url": "/documentation/avfoundation/avcoordinatedplaybacksuspension/reason-swift.struct/coordinatedplaybacknotpossible"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension/Reason-swift.struct/init(_:)": {
      "abstract": [
        {
          "text": "Creates a suspension with a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension/Reason-swift.struct/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcoordinatedplaybacksuspension/reason-swift.struct/init(_:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension/Reason-swift.struct/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a suspension with a raw string value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension/Reason-swift.struct/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcoordinatedplaybacksuspension/reason-swift.struct/init(rawvalue:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension/Reason-swift.struct/playingInterstitial": {
      "abstract": [
        {
          "text": "A participant is playing content other than the primary content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playingInterstitial"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCoordinatedPlaybackSuspension",
          "text": "AVCoordinatedPlaybackSuspension"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVCoordinatedPlaybackSuspensionReason",
          "text": "Reason"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension/Reason-swift.struct/playingInterstitial",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCoordinatedPlaybackSuspensionReasonPlayingInterstitial"
        }
      ],
      "role": "symbol",
      "title": "playingInterstitial",
      "type": "topic",
      "url": "/documentation/avfoundation/avcoordinatedplaybacksuspension/reason-swift.struct/playinginterstitial"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension/Reason-swift.struct/stallRecovery": {
      "abstract": [
        {
          "text": "The player object is buffering media data after a stall.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stallRecovery"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCoordinatedPlaybackSuspension",
          "text": "AVCoordinatedPlaybackSuspension"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVCoordinatedPlaybackSuspensionReason",
          "text": "Reason"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension/Reason-swift.struct/stallRecovery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCoordinatedPlaybackSuspensionReasonStallRecovery"
        }
      ],
      "role": "symbol",
      "title": "stallRecovery",
      "type": "topic",
      "url": "/documentation/avfoundation/avcoordinatedplaybacksuspension/reason-swift.struct/stallrecovery"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension/Reason-swift.struct/userActionRequired": {
      "abstract": [
        {
          "text": "A playback object requires user intervention to resume playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userActionRequired"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCoordinatedPlaybackSuspension",
          "text": "AVCoordinatedPlaybackSuspension"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVCoordinatedPlaybackSuspensionReason",
          "text": "Reason"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension/Reason-swift.struct/userActionRequired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCoordinatedPlaybackSuspensionReasonUserActionRequired"
        }
      ],
      "role": "symbol",
      "title": "userActionRequired",
      "type": "topic",
      "url": "/documentation/avfoundation/avcoordinatedplaybacksuspension/reason-swift.struct/useractionrequired"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension/Reason-swift.struct/userIsChangingCurrentTime": {
      "abstract": [
        {
          "text": "A participant is actively changing the current time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userIsChangingCurrentTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCoordinatedPlaybackSuspension",
          "text": "AVCoordinatedPlaybackSuspension"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVCoordinatedPlaybackSuspensionReason",
          "text": "Reason"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension/Reason-swift.struct/userIsChangingCurrentTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCoordinatedPlaybackSuspensionReasonUserIsChangingCurrentTime"
        }
      ],
      "role": "symbol",
      "title": "userIsChangingCurrentTime",
      "type": "topic",
      "url": "/documentation/avfoundation/avcoordinatedplaybacksuspension/reason-swift.struct/userischangingcurrenttime"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension/beginDate": {
      "abstract": [
        {
          "text": "The time the suspension begins.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beginDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension/beginDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beginDate"
        }
      ],
      "role": "symbol",
      "title": "beginDate",
      "type": "topic",
      "url": "/documentation/avfoundation/avcoordinatedplaybacksuspension/begindate"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension/reason-swift.property": {
      "abstract": [
        {
          "text": "The reason for the suspension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reason"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCoordinatedPlaybackSuspension",
          "text": "AVCoordinatedPlaybackSuspension"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVCoordinatedPlaybackSuspensionReason",
          "text": "Reason"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension/reason-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reason"
        }
      ],
      "role": "symbol",
      "title": "reason",
      "type": "topic",
      "url": "/documentation/avfoundation/avcoordinatedplaybacksuspension/reason-swift.property"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-a-Suspension",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension/beginDate",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension/reason-swift.property"
      ],
      "title": "Inspecting a Suspension"
    }
  ],
  "topicSections": [
    {
      "anchor": "Suspension-Reasons",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension/Reason-swift.struct/audioSessionInterrupted",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension/Reason-swift.struct/coordinatedPlaybackNotPossible",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension/Reason-swift.struct/playingInterstitial",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension/Reason-swift.struct/stallRecovery",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension/Reason-swift.struct/userActionRequired",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension/Reason-swift.struct/userIsChangingCurrentTime"
      ],
      "title": "Suspension Reasons"
    },
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension/Reason-swift.struct/init(_:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension/Reason-swift.struct/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVCoordinatedPlaybackSuspensionReason"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCoordinatedPlaybackSuspensionReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCoordinatedPlaybackSuspensionReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Suspension-Reasons",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension/Reason-swift.struct/audioSessionInterrupted",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension/Reason-swift.struct/coordinatedPlaybackNotPossible",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension/Reason-swift.struct/playingInterstitial",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension/Reason-swift.struct/stallRecovery",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension/Reason-swift.struct/userActionRequired",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension/Reason-swift.struct/userIsChangingCurrentTime"
              ],
              "title": "Suspension Reasons"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Inspecting-a-Suspension",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension/beginDate",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension/reason-swift.property"
              ],
              "title": "Inspecting a Suspension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVCoordinatedPlaybackSuspensionReason"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCoordinatedPlaybackSuspension~1Reason-swift.struct~1playingInterstitial/title",
          "value": "AVCoordinatedPlaybackSuspensionReasonPlayingInterstitial"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCoordinatedPlaybackSuspension~1Reason-swift.struct~1playingInterstitial/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCoordinatedPlaybackSuspensionReasonPlayingInterstitial"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCoordinatedPlaybackSuspension~1Reason-swift.struct~1stallRecovery/title",
          "value": "AVCoordinatedPlaybackSuspensionReasonStallRecovery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCoordinatedPlaybackSuspension~1Reason-swift.struct~1stallRecovery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCoordinatedPlaybackSuspensionReasonStallRecovery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCoordinatedPlaybackSuspension~1Reason-swift.struct~1coordinatedPlaybackNotPossible/title",
          "value": "AVCoordinatedPlaybackSuspensionReasonCoordinatedPlaybackNotPossible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCoordinatedPlaybackSuspension~1Reason-swift.struct~1coordinatedPlaybackNotPossible/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCoordinatedPlaybackSuspensionReasonCoordinatedPlaybackNotPossible"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCoordinatedPlaybackSuspension~1Reason-swift.struct~1userIsChangingCurrentTime/title",
          "value": "AVCoordinatedPlaybackSuspensionReasonUserIsChangingCurrentTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCoordinatedPlaybackSuspension~1Reason-swift.struct~1userIsChangingCurrentTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCoordinatedPlaybackSuspensionReasonUserIsChangingCurrentTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCoordinatedPlaybackSuspension/title",
          "value": "AVCoordinatedPlaybackSuspension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCoordinatedPlaybackSuspension/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCoordinatedPlaybackSuspension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCoordinatedPlaybackSuspension/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCoordinatedPlaybackSuspension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCoordinatedPlaybackSuspension~1Reason-swift.struct/title",
          "value": "AVCoordinatedPlaybackSuspensionReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCoordinatedPlaybackSuspension~1Reason-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCoordinatedPlaybackSuspensionReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCoordinatedPlaybackSuspension~1Reason-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCoordinatedPlaybackSuspensionReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCoordinatedPlaybackSuspension~1Reason-swift.struct~1userActionRequired/title",
          "value": "AVCoordinatedPlaybackSuspensionReasonUserActionRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCoordinatedPlaybackSuspension~1Reason-swift.struct~1userActionRequired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCoordinatedPlaybackSuspensionReasonUserActionRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCoordinatedPlaybackSuspension~1Reason-swift.struct~1audioSessionInterrupted/title",
          "value": "AVCoordinatedPlaybackSuspensionReasonAudioSessionInterrupted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCoordinatedPlaybackSuspension~1Reason-swift.struct~1audioSessionInterrupted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCoordinatedPlaybackSuspensionReasonAudioSessionInterrupted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCoordinatedPlaybackSuspension~1beginDate/title",
          "value": "beginDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCoordinatedPlaybackSuspension~1beginDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "beginDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCoordinatedPlaybackSuspension~1reason-swift.property/title",
          "value": "reason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCoordinatedPlaybackSuspension~1reason-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reason"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avcoordinatedplaybacksuspension/reason-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avcoordinatedplaybacksuspension/reason-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
