{
  "abstract": [
    {
      "text": "Invalidates the type description for the given project type.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.photokit/documentation/PhotosUI",
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescriptionInvalidator"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescriptionInvalidator/invalidateTypeDescription(for:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)PHProjectTypeDescriptionInvalidator(im)invalidateTypeDescriptionForProjectType:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "invalidateTypeDescription"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "for"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@PHProjectType",
        "text": "PHProjectType"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "PhotosUI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "invalidateTypeDescriptionForProjectType:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "invalidateTypeDescription(for:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "invalidateTypeDescription"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "for"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "projectType"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@PHProjectType",
              "text": "PHProjectType"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The project type to invalidate.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "projectType"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If you call this method for project types other than ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectType/undefined",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", you must implement ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescriptionDataSource/typeDescription(for:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " with functionality for the invalidated project type.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.photokit/documentation/PhotosUI": {
      "abstract": [
        {
          "text": "Present a person’s photo library using a picker interface, display Live Photos, or extend the Photos app with custom functionality.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI",
      "kind": "symbol",
      "role": "collection",
      "title": "PhotosUI",
      "type": "topic",
      "url": "/documentation/photosui"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectType": {
      "abstract": [
        {
          "text": "The type descriptor of a project extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHProjectType"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectType"
        }
      ],
      "role": "symbol",
      "title": "PHProjectType",
      "type": "topic",
      "url": "/documentation/photosui/phprojecttype"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectType/undefined": {
      "abstract": [
        {
          "text": "An undefined project type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "undefined"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PHProjectType",
          "text": "PHProjectType"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectType/undefined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectTypeUndefined"
        }
      ],
      "role": "symbol",
      "title": "undefined",
      "type": "topic",
      "url": "/documentation/photosui/phprojecttype/undefined"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescriptionDataSource/typeDescription(for:)": {
      "abstract": [
        {
          "text": "Provides the updated project type description for previously invalidated project types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "typeDescription"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PHProjectType",
          "text": "PHProjectType"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHProjectTypeDescription",
          "text": "PHProjectTypeDescription"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescriptionDataSource/typeDescription(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "typeDescriptionForProjectType:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "typeDescription(for:)",
      "type": "topic",
      "url": "/documentation/photosui/phprojecttypedescriptiondatasource/typedescription(for:)"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescriptionInvalidator": {
      "abstract": [
        {
          "text": "A protocol that you use to tell the project when and how to invalidate type and footer text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHProjectTypeDescriptionInvalidator"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescriptionInvalidator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectTypeDescriptionInvalidator"
        }
      ],
      "role": "symbol",
      "title": "PHProjectTypeDescriptionInvalidator",
      "type": "topic",
      "url": "/documentation/photosui/phprojecttypedescriptioninvalidator"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescriptionInvalidator/invalidateFooterText(forSubtypesOf:)": {
      "abstract": [
        {
          "text": "Invalidates the footer text for the subtypes of the given project type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidateFooterText"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forSubtypesOf"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PHProjectType",
          "text": "PHProjectType"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescriptionInvalidator/invalidateFooterText(forSubtypesOf:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "invalidateFooterTextForSubtypesOfProjectType:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "invalidateFooterText(forSubtypesOf:)",
      "type": "topic",
      "url": "/documentation/photosui/phprojecttypedescriptioninvalidator/invalidatefootertext(forsubtypesof:)"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescriptionInvalidator/invalidateTypeDescription(for:)": {
      "abstract": [
        {
          "text": "Invalidates the type description for the given project type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidateTypeDescription"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PHProjectType",
          "text": "PHProjectType"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescriptionInvalidator/invalidateTypeDescription(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "invalidateTypeDescriptionForProjectType:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "invalidateTypeDescription(for:)",
      "type": "topic",
      "url": "/documentation/photosui/phprojecttypedescriptioninvalidator/invalidatetypedescription(for:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Invalidating-a-Project-Type",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescriptionInvalidator/invalidateFooterText(forSubtypesOf:)"
      ],
      "title": "Invalidating a Project Type"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "invalidateTypeDescriptionForProjectType:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "invalidateTypeDescriptionForProjectType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.photokit/documentation/PhotosUI",
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescriptionInvalidator"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Invalidating-a-Project-Type",
              "generated": true,
              "identifiers": [
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescriptionInvalidator/invalidateFooterText(forSubtypesOf:)"
              ],
              "title": "Invalidating a Project Type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "invalidateTypeDescriptionForProjectType:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectType",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@PHProjectType",
                    "text": "PHProjectType"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "projectType"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The project type to invalidate.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "projectType"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectType/title",
          "value": "PHProjectType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTypeDescriptionDataSource~1typeDescription(for:)/title",
          "value": "typeDescriptionForProjectType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTypeDescriptionDataSource~1typeDescription(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "typeDescriptionForProjectType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectType~1undefined/title",
          "value": "PHProjectTypeUndefined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectType~1undefined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectTypeUndefined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTypeDescriptionInvalidator/title",
          "value": "PHProjectTypeDescriptionInvalidator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTypeDescriptionInvalidator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectTypeDescriptionInvalidator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTypeDescriptionInvalidator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectTypeDescriptionInvalidator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTypeDescriptionInvalidator~1invalidateTypeDescription(for:)/title",
          "value": "invalidateTypeDescriptionForProjectType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTypeDescriptionInvalidator~1invalidateTypeDescription(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "invalidateTypeDescriptionForProjectType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTypeDescriptionInvalidator~1invalidateFooterText(forSubtypesOf:)/title",
          "value": "invalidateFooterTextForSubtypesOfProjectType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTypeDescriptionInvalidator~1invalidateFooterText(forSubtypesOf:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "invalidateFooterTextForSubtypesOfProjectType:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/photosui/phprojecttypedescriptioninvalidator/invalidatetypedescription(for:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/photosui/phprojecttypedescriptioninvalidator/invalidatetypedescription(for:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
