{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notDetermined","kind":"identifier"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"]}],"kind":"declarations"},{"mentions":["doc://com.apple.photokit/documentation/PhotoKit/delivering-an-enhanced-privacy-experience-in-your-photos-app"],"kind":"mentions"},{"content":[{"type":"heading","anchor":"Discussion","level":2,"text":"Discussion"},{"inlineContent":[{"type":"text","text":"The framework automatically prompts for user authorization when you attempt to fetch assets, asset collections, or collection lists. Alternatively, you may call the "},{"identifier":"doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/requestAuthorization(for:handler:)","type":"reference","isActive":true},{"type":"text","text":" method to prompt the user for authorization at a time of your choosing."}],"type":"paragraph"}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.photokit/documentation/Photos/PHAuthorizationStatus/notDetermined"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.photokit/documentation/Photos","doc://com.apple.photokit/documentation/Photos/PHAuthorizationStatus"]]},"metadata":{"navigatorTitle":[{"text":"PHAuthorizationStatusNotDetermined","kind":"identifier"}],"modules":[{"name":"Photos"}],"role":"symbol","roleHeading":"Case","platforms":[{"name":"iOS","introducedAt":"8.0","deprecated":false,"beta":false,"unavailable":false},{"unavailable":false,"deprecated":false,"beta":false,"name":"iPadOS","introducedAt":"8.0"},{"unavailable":false,"deprecated":false,"beta":false,"name":"Mac Catalyst","introducedAt":"13.1"},{"unavailable":false,"deprecated":false,"beta":false,"name":"macOS","introducedAt":"10.13"},{"unavailable":false,"deprecated":false,"beta":false,"name":"tvOS","introducedAt":"10.0"},{"unavailable":false,"deprecated":false,"beta":false,"name":"visionOS","introducedAt":"1.0"}],"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notDetermined","kind":"identifier"}],"externalID":"c:@E@PHAuthorizationStatus@PHAuthorizationStatusNotDetermined","title":"PHAuthorizationStatus.notDetermined"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["/documentation/photos/phauthorizationstatus/notdetermined"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/photos/phauthorizationstatus/notdetermined"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"The user hasn’t set the app’s authorization status."}],"seeAlsoSections":[{"title":"Status Types","generated":true,"identifiers":["doc://com.apple.photokit/documentation/Photos/PHAuthorizationStatus/restricted","doc://com.apple.photokit/documentation/Photos/PHAuthorizationStatus/denied","doc://com.apple.photokit/documentation/Photos/PHAuthorizationStatus/authorized","doc://com.apple.photokit/documentation/Photos/PHAuthorizationStatus/limited"],"anchor":"Status-Types"}],"sections":[],"kind":"symbol","references":{"doc://com.apple.photokit/documentation/Photos/PHAuthorizationStatus/limited":{"identifier":"doc://com.apple.photokit/documentation/Photos/PHAuthorizationStatus/limited","navigatorTitle":[{"text":"PHAuthorizationStatusLimited","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"limited","kind":"identifier"}],"abstract":[{"type":"text","text":"The user authorized this app for limited photo library access."}],"url":"/documentation/photos/phauthorizationstatus/limited","role":"symbol","title":"PHAuthorizationStatus.limited","type":"topic","kind":"symbol"},"doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/requestAuthorization(for:handler:)":{"title":"requestAuthorization(for:handler:)","navigatorTitle":[{"text":"requestAuthorizationForAccessLevel:handler:","kind":"identifier"}],"url":"/documentation/photos/phphotolibrary/requestauthorization(for:handler:)","type":"topic","abstract":[{"text":"Prompts the user to grant the app permission to access the photo library.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestAuthorization","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@PHAccessLevel","text":"PHAccessLevel","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"handler","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:@E@PHAuthorizationStatus","text":"PHAuthorizationStatus","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","identifier":"doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/requestAuthorization(for:handler:)"},"doc://com.apple.photokit/documentation/Photos/PHAuthorizationStatus":{"role":"symbol","title":"PHAuthorizationStatus","type":"topic","abstract":[{"text":"Information about your app’s authorization to access the user’s photo library.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"PHAuthorizationStatus"}],"identifier":"doc://com.apple.photokit/documentation/Photos/PHAuthorizationStatus","url":"/documentation/photos/phauthorizationstatus","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PHAuthorizationStatus"}]},"doc://com.apple.photokit/documentation/Photos/PHAuthorizationStatus/restricted":{"identifier":"doc://com.apple.photokit/documentation/Photos/PHAuthorizationStatus/restricted","navigatorTitle":[{"text":"PHAuthorizationStatusRestricted","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"restricted","kind":"identifier"}],"abstract":[{"type":"text","text":"The app isn’t authorized to access the photo library, and the user can’t grant such permission."}],"url":"/documentation/photos/phauthorizationstatus/restricted","role":"symbol","title":"PHAuthorizationStatus.restricted","type":"topic","kind":"symbol"},"doc://com.apple.photokit/documentation/Photos/PHAuthorizationStatus/authorized":{"identifier":"doc://com.apple.photokit/documentation/Photos/PHAuthorizationStatus/authorized","navigatorTitle":[{"text":"PHAuthorizationStatusAuthorized","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"authorized","kind":"identifier"}],"abstract":[{"type":"text","text":"The user explicitly granted this app access to the photo library."}],"url":"/documentation/photos/phauthorizationstatus/authorized","role":"symbol","title":"PHAuthorizationStatus.authorized","type":"topic","kind":"symbol"},"doc://com.apple.photokit/documentation/Photos/PHAuthorizationStatus/notDetermined":{"identifier":"doc://com.apple.photokit/documentation/Photos/PHAuthorizationStatus/notDetermined","navigatorTitle":[{"text":"PHAuthorizationStatusNotDetermined","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notDetermined","kind":"identifier"}],"abstract":[{"type":"text","text":"The user hasn’t set the app’s authorization status."}],"url":"/documentation/photos/phauthorizationstatus/notdetermined","role":"symbol","title":"PHAuthorizationStatus.notDetermined","type":"topic","kind":"symbol"},"doc://com.apple.photokit/documentation/Photos/PHAuthorizationStatus/denied":{"abstract":[{"text":"The user explicitly denied this app access to the photo library.","type":"text"}],"role":"symbol","type":"topic","title":"PHAuthorizationStatus.denied","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"denied","kind":"identifier"}],"identifier":"doc://com.apple.photokit/documentation/Photos/PHAuthorizationStatus/denied","kind":"symbol","navigatorTitle":[{"text":"PHAuthorizationStatusDenied","kind":"identifier"}],"url":"/documentation/photos/phauthorizationstatus/denied"},"doc://com.apple.photokit/documentation/Photos":{"title":"Photos","role":"collection","kind":"symbol","identifier":"doc://com.apple.photokit/documentation/Photos","abstract":[{"type":"text","text":"Work with image and video assets that the Photos app manages, including those from iCloud Photos and Live Photos."}],"type":"topic","url":"/documentation/photos"},"doc://com.apple.photokit/documentation/PhotoKit/delivering-an-enhanced-privacy-experience-in-your-photos-app":{"title":"Delivering an Enhanced Privacy Experience in Your Photos App","url":"/documentation/photokit/delivering-an-enhanced-privacy-experience-in-your-photos-app","type":"topic","abstract":[{"text":"Adopt the latest privacy enhancements to deliver advanced user-privacy controls.","type":"text"}],"kind":"article","role":"article","identifier":"doc://com.apple.photokit/documentation/PhotoKit/delivering-an-enhanced-privacy-experience-in-your-photos-app"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","kind":"technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","url":"/documentation/technologies"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"unavailable":false,"deprecated":false,"name":"iOS","beta":false,"introducedAt":"8.0"},{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"8.0","name":"iPadOS"},{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"13.1","name":"Mac Catalyst"},{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"10.13","name":"macOS"},{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"10.0","name":"tvOS"},{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"1.0","name":"visionOS"}],"op":"replace","path":"/metadata/platforms"},{"value":"Enumeration Case","op":"replace","path":"/metadata/roleHeading"},{"value":"PHAuthorizationStatusNotDetermined","op":"replace","path":"/metadata/title"},{"value":"case","op":"replace","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"PHAuthorizationStatusNotDetermined","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.photokit/documentation/Photos","doc://com.apple.photokit/documentation/Photos/PHAuthorizationStatus"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","path":"/seeAlsoSections","value":[{"title":"Status Types","generated":true,"identifiers":["doc://com.apple.photokit/documentation/Photos/PHAuthorizationStatus/restricted","doc://com.apple.photokit/documentation/Photos/PHAuthorizationStatus/denied","doc://com.apple.photokit/documentation/Photos/PHAuthorizationStatus/authorized","doc://com.apple.photokit/documentation/Photos/PHAuthorizationStatus/limited"],"anchor":"Status-Types"}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"PHAuthorizationStatusNotDetermined"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"PHAuthorizationStatusLimited","op":"replace","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAuthorizationStatus~1limited/title"},{"value":[{"text":"PHAuthorizationStatusLimited","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAuthorizationStatus~1limited/fragments"},{"value":"requestAuthorizationForAccessLevel:handler:","op":"replace","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary~1requestAuthorization(for:handler:)/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"requestAuthorizationForAccessLevel:handler:"}],"op":"replace","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary~1requestAuthorization(for:handler:)/fragments"},{"op":"replace","value":"PHAuthorizationStatus","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAuthorizationStatus/title"},{"op":"replace","value":[{"kind":"identifier","text":"PHAuthorizationStatus"}],"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAuthorizationStatus/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"PHAuthorizationStatus"}],"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAuthorizationStatus/navigatorTitle"},{"op":"replace","value":"PHAuthorizationStatusRestricted","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAuthorizationStatus~1restricted/title"},{"op":"replace","value":[{"kind":"identifier","text":"PHAuthorizationStatusRestricted"}],"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAuthorizationStatus~1restricted/fragments"},{"op":"replace","value":"PHAuthorizationStatusAuthorized","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAuthorizationStatus~1authorized/title"},{"op":"replace","value":[{"kind":"identifier","text":"PHAuthorizationStatusAuthorized"}],"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAuthorizationStatus~1authorized/fragments"},{"op":"replace","value":"PHAuthorizationStatusNotDetermined","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAuthorizationStatus~1notDetermined/title"},{"op":"replace","value":[{"kind":"identifier","text":"PHAuthorizationStatusNotDetermined"}],"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAuthorizationStatus~1notDetermined/fragments"},{"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAuthorizationStatus~1denied/title","value":"PHAuthorizationStatusDenied","op":"replace"},{"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAuthorizationStatus~1denied/fragments","value":[{"text":"PHAuthorizationStatusDenied","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}