{
  "abstract": [
    {
      "text": "Errors you might encounter when configuring or using a virtual machine.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.virtualization/documentation/Virtualization",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@VZErrorCode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "Virtualization"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "VZError.Code"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Code"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The domain for these errors is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZErrorDomain",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". When an error originates in a different component, the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nserror",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object contains the domain of that component.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/foundation/nserror": {
      "abstract": [
        {
          "text": "Information about an error condition including a domain, a domain-specific error code, and application-specific information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nserror",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSError",
      "type": "topic",
      "url": "/documentation/foundation/nserror"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.virtualization/documentation/Virtualization": {
      "abstract": [
        {
          "text": "Create virtual machines and run macOS and Linux-based operating systems.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization",
      "kind": "symbol",
      "role": "collection",
      "title": "Virtualization",
      "type": "topic",
      "url": "/documentation/virtualization"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError": {
      "abstract": [
        {
          "text": "Errors that you might encounter when configuring or using a VM.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZError"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZError"
        }
      ],
      "role": "symbol",
      "title": "VZError",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code": {
      "abstract": [
        {
          "text": "Errors you might encounter when configuring or using a virtual machine.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "VZError.Code",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/code"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/deviceAlreadyAttached": {
      "abstract": [
        {
          "text": "The device already has an attachment to the VM.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceAlreadyAttached"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/deviceAlreadyAttached",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZErrorDeviceAlreadyAttached"
        }
      ],
      "role": "symbol",
      "title": "VZError.Code.deviceAlreadyAttached",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/code/devicealreadyattached"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/deviceInitializationFailure": {
      "abstract": [
        {
          "text": "A device initialization failure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceInitializationFailure"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/deviceInitializationFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZErrorDeviceInitializationFailure"
        }
      ],
      "role": "symbol",
      "title": "VZError.Code.deviceInitializationFailure",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/code/deviceinitializationfailure"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/deviceNotFound": {
      "abstract": [
        {
          "text": "The framework can’t find the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceNotFound"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/deviceNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZErrorDeviceNotFound"
        }
      ],
      "role": "symbol",
      "title": "VZError.Code.deviceNotFound",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/code/devicenotfound"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/code/init(rawvalue:)"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/installationFailed": {
      "abstract": [
        {
          "text": "An error occurred during installation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "installationFailed"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/installationFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZErrorInstallationFailed"
        }
      ],
      "role": "symbol",
      "title": "VZError.Code.installationFailed",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/code/installationfailed"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/installationRequiresUpdate": {
      "abstract": [
        {
          "text": "The VM requires a software update in order to complete the installation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "installationRequiresUpdate"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/installationRequiresUpdate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZErrorInstallationRequiresUpdate"
        }
      ],
      "role": "symbol",
      "title": "VZError.Code.installationRequiresUpdate",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/code/installationrequiresupdate"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/internalError": {
      "abstract": [
        {
          "text": "An internal error, such as the VM unexpectedly stopping.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "internalError"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/internalError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZErrorInternal"
        }
      ],
      "role": "symbol",
      "title": "VZError.Code.internalError",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/code/internalerror"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidDiskImage": {
      "abstract": [
        {
          "text": "An invalid disk-image error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidDiskImage"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidDiskImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZErrorInvalidDiskImage"
        }
      ],
      "role": "symbol",
      "title": "VZError.Code.invalidDiskImage",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/code/invaliddiskimage"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidRestoreImage": {
      "abstract": [
        {
          "text": "The restore image is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidRestoreImage"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidRestoreImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZErrorInvalidRestoreImage"
        }
      ],
      "role": "symbol",
      "title": "VZError.Code.invalidRestoreImage",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/code/invalidrestoreimage"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidRestoreImageCatalog": {
      "abstract": [
        {
          "text": "The restore image catalog is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidRestoreImageCatalog"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidRestoreImageCatalog",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZErrorInvalidRestoreImageCatalog"
        }
      ],
      "role": "symbol",
      "title": "VZError.Code.invalidRestoreImageCatalog",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/code/invalidrestoreimagecatalog"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidVirtualMachineConfiguration": {
      "abstract": [
        {
          "text": "An invalid configuration error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidVirtualMachineConfiguration"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidVirtualMachineConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZErrorInvalidVirtualMachineConfiguration"
        }
      ],
      "role": "symbol",
      "title": "VZError.Code.invalidVirtualMachineConfiguration",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/code/invalidvirtualmachineconfiguration"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidVirtualMachineState": {
      "abstract": [
        {
          "text": "An invalid state error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidVirtualMachineState"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidVirtualMachineState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZErrorInvalidVirtualMachineState"
        }
      ],
      "role": "symbol",
      "title": "VZError.Code.invalidVirtualMachineState",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/code/invalidvirtualmachinestate"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidVirtualMachineStateTransition": {
      "abstract": [
        {
          "text": "An invalid state transition error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidVirtualMachineStateTransition"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidVirtualMachineStateTransition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZErrorInvalidVirtualMachineStateTransition"
        }
      ],
      "role": "symbol",
      "title": "VZError.Code.invalidVirtualMachineStateTransition",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/code/invalidvirtualmachinestatetransition"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/networkBlockDeviceDisconnected": {
      "abstract": [
        {
          "text": "The network block device client disconnected from the server.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "networkBlockDeviceDisconnected"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/networkBlockDeviceDisconnected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZErrorNetworkBlockDeviceDisconnected"
        }
      ],
      "role": "symbol",
      "title": "VZError.Code.networkBlockDeviceDisconnected",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/code/networkblockdevicedisconnected"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/networkBlockDeviceNegotiationFailed": {
      "abstract": [
        {
          "text": "The connection or the negotiation with the network block device server failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "networkBlockDeviceNegotiationFailed"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/networkBlockDeviceNegotiationFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZErrorNetworkBlockDeviceNegotiationFailed"
        }
      ],
      "role": "symbol",
      "title": "VZError.Code.networkBlockDeviceNegotiationFailed",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/code/networkblockdevicenegotiationfailed"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/networkError": {
      "abstract": [
        {
          "text": "A network error, such as a failed connection error, occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "networkError"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/networkError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZErrorNetworkError"
        }
      ],
      "role": "symbol",
      "title": "VZError.Code.networkError",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/code/networkerror"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/noSupportedRestoreImagesInCatalog": {
      "abstract": [
        {
          "text": "The restore image catalog has no supported restore images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noSupportedRestoreImagesInCatalog"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/noSupportedRestoreImagesInCatalog",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZErrorNoSupportedRestoreImagesInCatalog"
        }
      ],
      "role": "symbol",
      "title": "VZError.Code.noSupportedRestoreImagesInCatalog",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/code/nosupportedrestoreimagesincatalog"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/notSupported": {
      "abstract": [
        {
          "text": "The host computer or operating system isn’t supported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notSupported"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/notSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZErrorNotSupported"
        }
      ],
      "role": "symbol",
      "title": "VZError.Code.notSupported",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/code/notsupported"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/operationCancelled": {
      "abstract": [
        {
          "text": "The code that indicates user canceled the installation of Rosetta or the app canceled the installation of a guest OS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "operationCancelled"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/operationCancelled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZErrorOperationCancelled"
        }
      ],
      "role": "symbol",
      "title": "VZError.Code.operationCancelled",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/code/operationcancelled"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/outOfDiskSpace": {
      "abstract": [
        {
          "text": "The host is out of disk space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outOfDiskSpace"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/outOfDiskSpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZErrorOutOfDiskSpace"
        }
      ],
      "role": "symbol",
      "title": "VZError.Code.outOfDiskSpace",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/code/outofdiskspace"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/restore": {
      "abstract": [
        {
          "text": "The VM failed to restore from save file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "restore"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/restore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZErrorRestore"
        }
      ],
      "role": "symbol",
      "title": "VZError.Code.restore",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/code/restore"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/restoreImageCatalogLoadFailed": {
      "abstract": [
        {
          "text": "The restore image catalog failed to load.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "restoreImageCatalogLoadFailed"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/restoreImageCatalogLoadFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZErrorRestoreImageCatalogLoadFailed"
        }
      ],
      "role": "symbol",
      "title": "VZError.Code.restoreImageCatalogLoadFailed",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/code/restoreimagecatalogloadfailed"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/restoreImageLoadFailed": {
      "abstract": [
        {
          "text": "The restore image failed to load.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "restoreImageLoadFailed"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/restoreImageLoadFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZErrorRestoreImageLoadFailed"
        }
      ],
      "role": "symbol",
      "title": "VZError.Code.restoreImageLoadFailed",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/code/restoreimageloadfailed"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/save": {
      "abstract": [
        {
          "text": "The VM failed to save to the save file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "save"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/save",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZErrorSave"
        }
      ],
      "role": "symbol",
      "title": "VZError.Code.save",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/code/save"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/usbControllerNotFound": {
      "abstract": [
        {
          "text": "The framework can’t find the controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "usbControllerNotFound"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/usbControllerNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZErrorUSBControllerNotFound"
        }
      ],
      "role": "symbol",
      "title": "VZError.Code.usbControllerNotFound",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/code/usbcontrollernotfound"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/virtualMachineLimitExceeded": {
      "abstract": [
        {
          "text": "Unable to create an additional VM.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "virtualMachineLimitExceeded"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/virtualMachineLimitExceeded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZErrorVirtualMachineLimitExceeded"
        }
      ],
      "role": "symbol",
      "title": "VZError.Code.virtualMachineLimitExceeded",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/code/virtualmachinelimitexceeded"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/installationFailed": {
      "abstract": [
        {
          "text": "An error occurred during installation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "installationFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11VZErrorCodeLeV",
          "text": "VZError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VZErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/installationFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "installationFailed",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/installationfailed"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/installationRequiresUpdate": {
      "abstract": [
        {
          "text": "The framework canceled the installation because the host requires a software update in order to complete the installation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "installationRequiresUpdate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11VZErrorCodeLeV",
          "text": "VZError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VZErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/installationRequiresUpdate",
      "kind": "symbol",
      "role": "symbol",
      "title": "installationRequiresUpdate",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/installationrequiresupdate"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/internalError": {
      "abstract": [
        {
          "text": "An internal error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "internalError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11VZErrorCodeLeV",
          "text": "VZError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VZErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/internalError",
      "kind": "symbol",
      "role": "symbol",
      "title": "internalError",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/internalerror"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidDiskImage": {
      "abstract": [
        {
          "text": "An invalid disk-image error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidDiskImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11VZErrorCodeLeV",
          "text": "VZError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VZErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidDiskImage",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidDiskImage",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/invaliddiskimage"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidRestoreImage": {
      "abstract": [
        {
          "text": "The restore image is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidRestoreImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11VZErrorCodeLeV",
          "text": "VZError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VZErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidRestoreImage",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidRestoreImage",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/invalidrestoreimage"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidRestoreImageCatalog": {
      "abstract": [
        {
          "text": "The restore image catalog is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidRestoreImageCatalog"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11VZErrorCodeLeV",
          "text": "VZError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VZErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidRestoreImageCatalog",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidRestoreImageCatalog",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/invalidrestoreimagecatalog"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidVirtualMachineConfiguration": {
      "abstract": [
        {
          "text": "An invalid configuration error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidVirtualMachineConfiguration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11VZErrorCodeLeV",
          "text": "VZError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VZErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidVirtualMachineConfiguration",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidVirtualMachineConfiguration",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/invalidvirtualmachineconfiguration"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidVirtualMachineState": {
      "abstract": [
        {
          "text": "An invalid state error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidVirtualMachineState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11VZErrorCodeLeV",
          "text": "VZError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VZErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidVirtualMachineState",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidVirtualMachineState",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/invalidvirtualmachinestate"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidVirtualMachineStateTransition": {
      "abstract": [
        {
          "text": "An invalid state transition error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidVirtualMachineStateTransition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11VZErrorCodeLeV",
          "text": "VZError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VZErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidVirtualMachineStateTransition",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidVirtualMachineStateTransition",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/invalidvirtualmachinestatetransition"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/networkError": {
      "abstract": [
        {
          "text": "A network error, such as a failed connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "networkError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11VZErrorCodeLeV",
          "text": "VZError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VZErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/networkError",
      "kind": "symbol",
      "role": "symbol",
      "title": "networkError",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/networkerror"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/noSupportedRestoreImagesInCatalog": {
      "abstract": [
        {
          "text": "The restore image catalog has no supported restore images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noSupportedRestoreImagesInCatalog"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11VZErrorCodeLeV",
          "text": "VZError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VZErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/noSupportedRestoreImagesInCatalog",
      "kind": "symbol",
      "role": "symbol",
      "title": "noSupportedRestoreImagesInCatalog",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/nosupportedrestoreimagesincatalog"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/notSupported": {
      "abstract": [
        {
          "text": "The operation isn’t supported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notSupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11VZErrorCodeLeV",
          "text": "VZError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VZErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/notSupported",
      "kind": "symbol",
      "role": "symbol",
      "title": "notSupported",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/notsupported"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/operationCancelled": {
      "abstract": [
        {
          "text": "The user canceled the installation of Rosetta or the app canceled the installation of a guest OS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "operationCancelled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11VZErrorCodeLeV",
          "text": "VZError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VZErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/operationCancelled",
      "kind": "symbol",
      "role": "symbol",
      "title": "operationCancelled",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/operationcancelled"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/outOfDiskSpace": {
      "abstract": [
        {
          "text": "The host is out of disk space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outOfDiskSpace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11VZErrorCodeLeV",
          "text": "VZError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VZErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/outOfDiskSpace",
      "kind": "symbol",
      "role": "symbol",
      "title": "outOfDiskSpace",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/outofdiskspace"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/restoreImageCatalogLoadFailed": {
      "abstract": [
        {
          "text": "The restore image catalog failed to load.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "restoreImageCatalogLoadFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11VZErrorCodeLeV",
          "text": "VZError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VZErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/restoreImageCatalogLoadFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "restoreImageCatalogLoadFailed",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/restoreimagecatalogloadfailed"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZErrorDomain": {
      "abstract": [
        {
          "text": "The error domain for the Virtualization framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "VZErrorDomain",
      "type": "topic",
      "url": "/documentation/virtualization/vzerrordomain"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-error-codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/internalError",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidVirtualMachineConfiguration",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidVirtualMachineState",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidVirtualMachineStateTransition",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidDiskImage",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/networkError",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/notSupported",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/outOfDiskSpace",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/operationCancelled",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/installationFailed",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/installationRequiresUpdate",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidRestoreImage",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidRestoreImageCatalog",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/noSupportedRestoreImagesInCatalog",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/restoreImageCatalogLoadFailed"
      ],
      "title": "Getting the error codes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Error-codes",
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/internalError",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidVirtualMachineConfiguration",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidVirtualMachineState",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidVirtualMachineStateTransition",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidDiskImage",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/virtualMachineLimitExceeded",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/networkError",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/notSupported",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/outOfDiskSpace",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/operationCancelled",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/installationFailed",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/installationRequiresUpdate",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidRestoreImage",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidRestoreImageCatalog",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/noSupportedRestoreImagesInCatalog",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/restoreImageCatalogLoadFailed",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/restoreImageLoadFailed",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/networkBlockDeviceNegotiationFailed",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/networkBlockDeviceDisconnected",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/restore",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/save",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/deviceAlreadyAttached",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/deviceInitializationFailure",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/deviceNotFound",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/usbControllerNotFound",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/internalError",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidVirtualMachineConfiguration",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidVirtualMachineState",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidVirtualMachineStateTransition",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidDiskImage",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/virtualMachineLimitExceeded",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/networkError",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/notSupported",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/outOfDiskSpace",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/operationCancelled",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/installationFailed",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/installationRequiresUpdate",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidRestoreImage",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidRestoreImageCatalog",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/noSupportedRestoreImagesInCatalog",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/restoreImageCatalogLoadFailed",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/restoreImageLoadFailed",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/networkBlockDeviceNegotiationFailed",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/networkBlockDeviceDisconnected",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/restore",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/save",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/deviceAlreadyAttached",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/deviceInitializationFailure",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/deviceNotFound",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/usbControllerNotFound"
      ],
      "title": "Error codes"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VZErrorCode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.virtualization/documentation/Virtualization"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Error-codes",
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/internalError",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidVirtualMachineConfiguration",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidVirtualMachineState",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidVirtualMachineStateTransition",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidDiskImage",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/virtualMachineLimitExceeded",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/networkError",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/notSupported",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/outOfDiskSpace",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/operationCancelled",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/installationFailed",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/installationRequiresUpdate",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidRestoreImage",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidRestoreImageCatalog",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/noSupportedRestoreImagesInCatalog",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/restoreImageCatalogLoadFailed",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/restoreImageLoadFailed",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/networkBlockDeviceNegotiationFailed",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/networkBlockDeviceDisconnected",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/restore",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/save",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/deviceAlreadyAttached",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/deviceInitializationFailure",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/deviceNotFound",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/usbControllerNotFound",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/internalError",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidVirtualMachineConfiguration",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidVirtualMachineState",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidVirtualMachineStateTransition",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidDiskImage",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/virtualMachineLimitExceeded",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/networkError",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/notSupported",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/outOfDiskSpace",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/operationCancelled",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/installationFailed",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/installationRequiresUpdate",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidRestoreImage",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidRestoreImageCatalog",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/noSupportedRestoreImagesInCatalog",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/restoreImageCatalogLoadFailed",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/restoreImageLoadFailed",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/networkBlockDeviceNegotiationFailed",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/networkBlockDeviceDisconnected",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/restore",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/save",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/deviceAlreadyAttached",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/deviceInitializationFailure",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/deviceNotFound",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/usbControllerNotFound"
              ],
              "title": "Error codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "VZErrorCode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZErrorDomain/title",
          "value": "VZErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1deviceAlreadyAttached/title",
          "value": "VZErrorDeviceAlreadyAttached"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1deviceAlreadyAttached/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZErrorDeviceAlreadyAttached"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1invalidVirtualMachineConfiguration/title",
          "value": "VZErrorInvalidVirtualMachineConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1invalidVirtualMachineConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZErrorInvalidVirtualMachineConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1invalidRestoreImage/title",
          "value": "VZErrorInvalidRestoreImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1invalidRestoreImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZErrorInvalidRestoreImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1virtualMachineLimitExceeded/title",
          "value": "VZErrorVirtualMachineLimitExceeded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1virtualMachineLimitExceeded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZErrorVirtualMachineLimitExceeded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1invalidVirtualMachineStateTransition/title",
          "value": "VZErrorInvalidVirtualMachineStateTransition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1invalidVirtualMachineStateTransition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZErrorInvalidVirtualMachineStateTransition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1outOfDiskSpace/title",
          "value": "VZErrorOutOfDiskSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1outOfDiskSpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZErrorOutOfDiskSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1networkError/title",
          "value": "VZErrorNetworkError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1networkError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZErrorNetworkError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1deviceNotFound/title",
          "value": "VZErrorDeviceNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1deviceNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZErrorDeviceNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1networkBlockDeviceNegotiationFailed/title",
          "value": "VZErrorNetworkBlockDeviceNegotiationFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1networkBlockDeviceNegotiationFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZErrorNetworkBlockDeviceNegotiationFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1installationFailed/title",
          "value": "VZErrorInstallationFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1installationFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZErrorInstallationFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1internalError/title",
          "value": "VZErrorInternal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1internalError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZErrorInternal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1restore/title",
          "value": "VZErrorRestore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1restore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZErrorRestore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1noSupportedRestoreImagesInCatalog/title",
          "value": "VZErrorNoSupportedRestoreImagesInCatalog"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1noSupportedRestoreImagesInCatalog/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZErrorNoSupportedRestoreImagesInCatalog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1operationCancelled/title",
          "value": "VZErrorOperationCancelled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1operationCancelled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZErrorOperationCancelled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1invalidRestoreImageCatalog/title",
          "value": "VZErrorInvalidRestoreImageCatalog"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1invalidRestoreImageCatalog/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZErrorInvalidRestoreImageCatalog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1invalidVirtualMachineState/title",
          "value": "VZErrorInvalidVirtualMachineState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1invalidVirtualMachineState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZErrorInvalidVirtualMachineState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1installationRequiresUpdate/title",
          "value": "VZErrorInstallationRequiresUpdate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1installationRequiresUpdate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZErrorInstallationRequiresUpdate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1deviceInitializationFailure/title",
          "value": "VZErrorDeviceInitializationFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1deviceInitializationFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZErrorDeviceInitializationFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1invalidDiskImage/title",
          "value": "VZErrorInvalidDiskImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1invalidDiskImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZErrorInvalidDiskImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1networkBlockDeviceDisconnected/title",
          "value": "VZErrorNetworkBlockDeviceDisconnected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1networkBlockDeviceDisconnected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZErrorNetworkBlockDeviceDisconnected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1notSupported/title",
          "value": "VZErrorNotSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1notSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZErrorNotSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1usbControllerNotFound/title",
          "value": "VZErrorUSBControllerNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1usbControllerNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZErrorUSBControllerNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1save/title",
          "value": "VZErrorSave"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1save/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZErrorSave"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code/title",
          "value": "VZErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1restoreImageCatalogLoadFailed/title",
          "value": "VZErrorRestoreImageCatalogLoadFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1restoreImageCatalogLoadFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZErrorRestoreImageCatalogLoadFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1restoreImageLoadFailed/title",
          "value": "VZErrorRestoreImageLoadFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1restoreImageLoadFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZErrorRestoreImageLoadFailed"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/virtualization/vzerror/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/virtualization/vzerror/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
