{
  "abstract": [
    {
      "text": "An invalid state transition error.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.virtualization/documentation/Virtualization",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidVirtualMachineStateTransition"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC11VZErrorCodeLeV36invalidVirtualMachineStateTransitionSoAAVvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "invalidVirtualMachineStateTransition"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SC11VZErrorCodeLeV",
        "text": "VZError"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@VZErrorCode",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "Virtualization"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "invalidVirtualMachineStateTransition"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "invalidVirtualMachineStateTransition"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SC11VZErrorCodeLeV",
              "text": "VZError"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@VZErrorCode",
              "text": "Code"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This error occurs when you attempt to change the state of the virtual machine in an invalid way. For example, it occurs when you attempt to start a virtual machine when its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/canStart",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/false",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.virtualization/documentation/Virtualization": {
      "abstract": [
        {
          "text": "Create virtual machines and run macOS and Linux-based operating systems.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization",
      "kind": "symbol",
      "role": "collection",
      "title": "Virtualization",
      "type": "topic",
      "url": "/documentation/virtualization"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError": {
      "abstract": [
        {
          "text": "Errors that you might encounter when configuring or using a VM.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZError"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZError"
        }
      ],
      "role": "symbol",
      "title": "VZError",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code": {
      "abstract": [
        {
          "text": "Errors you might encounter when configuring or using a virtual machine.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "VZError.Code",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/code"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/installationFailed": {
      "abstract": [
        {
          "text": "An error occurred during installation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "installationFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11VZErrorCodeLeV",
          "text": "VZError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VZErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/installationFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "installationFailed",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/installationfailed"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/installationRequiresUpdate": {
      "abstract": [
        {
          "text": "The framework canceled the installation because the host requires a software update in order to complete the installation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "installationRequiresUpdate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11VZErrorCodeLeV",
          "text": "VZError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VZErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/installationRequiresUpdate",
      "kind": "symbol",
      "role": "symbol",
      "title": "installationRequiresUpdate",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/installationrequiresupdate"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/internalError": {
      "abstract": [
        {
          "text": "An internal error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "internalError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11VZErrorCodeLeV",
          "text": "VZError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VZErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/internalError",
      "kind": "symbol",
      "role": "symbol",
      "title": "internalError",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/internalerror"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidDiskImage": {
      "abstract": [
        {
          "text": "An invalid disk-image error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidDiskImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11VZErrorCodeLeV",
          "text": "VZError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VZErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidDiskImage",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidDiskImage",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/invaliddiskimage"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidRestoreImage": {
      "abstract": [
        {
          "text": "The restore image is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidRestoreImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11VZErrorCodeLeV",
          "text": "VZError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VZErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidRestoreImage",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidRestoreImage",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/invalidrestoreimage"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidRestoreImageCatalog": {
      "abstract": [
        {
          "text": "The restore image catalog is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidRestoreImageCatalog"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11VZErrorCodeLeV",
          "text": "VZError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VZErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidRestoreImageCatalog",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidRestoreImageCatalog",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/invalidrestoreimagecatalog"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidVirtualMachineConfiguration": {
      "abstract": [
        {
          "text": "An invalid configuration error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidVirtualMachineConfiguration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11VZErrorCodeLeV",
          "text": "VZError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VZErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidVirtualMachineConfiguration",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidVirtualMachineConfiguration",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/invalidvirtualmachineconfiguration"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidVirtualMachineState": {
      "abstract": [
        {
          "text": "An invalid state error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidVirtualMachineState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11VZErrorCodeLeV",
          "text": "VZError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VZErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidVirtualMachineState",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidVirtualMachineState",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/invalidvirtualmachinestate"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidVirtualMachineStateTransition": {
      "abstract": [
        {
          "text": "An invalid state transition error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidVirtualMachineStateTransition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11VZErrorCodeLeV",
          "text": "VZError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VZErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidVirtualMachineStateTransition",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidVirtualMachineStateTransition",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/invalidvirtualmachinestatetransition"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/networkError": {
      "abstract": [
        {
          "text": "A network error, such as a failed connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "networkError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11VZErrorCodeLeV",
          "text": "VZError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VZErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/networkError",
      "kind": "symbol",
      "role": "symbol",
      "title": "networkError",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/networkerror"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/noSupportedRestoreImagesInCatalog": {
      "abstract": [
        {
          "text": "The restore image catalog has no supported restore images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noSupportedRestoreImagesInCatalog"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11VZErrorCodeLeV",
          "text": "VZError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VZErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/noSupportedRestoreImagesInCatalog",
      "kind": "symbol",
      "role": "symbol",
      "title": "noSupportedRestoreImagesInCatalog",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/nosupportedrestoreimagesincatalog"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/notSupported": {
      "abstract": [
        {
          "text": "The operation isn’t supported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notSupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11VZErrorCodeLeV",
          "text": "VZError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VZErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/notSupported",
      "kind": "symbol",
      "role": "symbol",
      "title": "notSupported",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/notsupported"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/operationCancelled": {
      "abstract": [
        {
          "text": "The user canceled the installation of Rosetta or the app canceled the installation of a guest OS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "operationCancelled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11VZErrorCodeLeV",
          "text": "VZError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VZErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/operationCancelled",
      "kind": "symbol",
      "role": "symbol",
      "title": "operationCancelled",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/operationcancelled"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/outOfDiskSpace": {
      "abstract": [
        {
          "text": "The host is out of disk space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outOfDiskSpace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11VZErrorCodeLeV",
          "text": "VZError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VZErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/outOfDiskSpace",
      "kind": "symbol",
      "role": "symbol",
      "title": "outOfDiskSpace",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/outofdiskspace"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/restoreImageCatalogLoadFailed": {
      "abstract": [
        {
          "text": "The restore image catalog failed to load.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "restoreImageCatalogLoadFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11VZErrorCodeLeV",
          "text": "VZError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VZErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/restoreImageCatalogLoadFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "restoreImageCatalogLoadFailed",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/restoreimagecatalogloadfailed"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/restoreImageLoadFailed": {
      "abstract": [
        {
          "text": "The restore image failed to load.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "restoreImageLoadFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11VZErrorCodeLeV",
          "text": "VZError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VZErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/restoreImageLoadFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "restoreImageLoadFailed",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/restoreimageloadfailed"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/canStart": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether you can start the VM.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canStart"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/canStart",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canStart"
        }
      ],
      "role": "symbol",
      "title": "canStart",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachine/canstart"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-error-codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/internalError",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidVirtualMachineConfiguration",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidVirtualMachineState",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidDiskImage",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/networkError",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/notSupported",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/outOfDiskSpace",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/operationCancelled",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/installationFailed",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/installationRequiresUpdate",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidRestoreImage",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidRestoreImageCatalog",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/noSupportedRestoreImagesInCatalog",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/restoreImageCatalogLoadFailed",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/restoreImageLoadFailed"
      ],
      "title": "Getting the error codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code/title",
          "value": "VZErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1canStart/title",
          "value": "canStart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1canStart/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "canStart"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/virtualization/vzerror/invalidvirtualmachinestatetransition"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
