{"sections":[],"metadata":{"roleHeading":"Type Property","role":"symbol","platforms":[{"deprecated":false,"beta":false,"name":"macOS","introducedAt":"14.0","unavailable":false}],"title":"save","modules":[{"name":"Virtualization"}],"externalID":"s:SC11VZErrorCodeLeV4saveSoAAVvpZ","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"save"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SC11VZErrorCodeLeV","text":"VZError"},{"kind":"text","text":"."},{"text":"Code","preciseIdentifier":"c:@E@VZErrorCode","kind":"typeIdentifier"}],"symbolKind":"property"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.virtualization/documentation/Virtualization","doc://com.apple.virtualization/documentation/Virtualization/VZError"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"save","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SC11VZErrorCodeLeV","text":"VZError","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZError","kind":"typeIdentifier"},{"text":".","kind":"text"},{"identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZError/Code","preciseIdentifier":"c:@E@VZErrorCode","text":"Code","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"abstract":[{"text":"The VM failed to save to the save file.","type":"text"}],"seeAlsoSections":[{"generated":true,"anchor":"Getting-the-error-codes","identifiers":["doc://com.apple.virtualization/documentation/Virtualization/VZError/internalError","doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidVirtualMachineConfiguration","doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidVirtualMachineState","doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidVirtualMachineStateTransition","doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidDiskImage","doc://com.apple.virtualization/documentation/Virtualization/VZError/networkError","doc://com.apple.virtualization/documentation/Virtualization/VZError/notSupported","doc://com.apple.virtualization/documentation/Virtualization/VZError/outOfDiskSpace","doc://com.apple.virtualization/documentation/Virtualization/VZError/operationCancelled","doc://com.apple.virtualization/documentation/Virtualization/VZError/installationFailed","doc://com.apple.virtualization/documentation/Virtualization/VZError/installationRequiresUpdate","doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidRestoreImage","doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidRestoreImageCatalog","doc://com.apple.virtualization/documentation/Virtualization/VZError/noSupportedRestoreImagesInCatalog","doc://com.apple.virtualization/documentation/Virtualization/VZError/restoreImageCatalogLoadFailed"],"title":"Getting the error codes"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.virtualization/documentation/Virtualization/VZError/save","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/virtualization/vzerror/save"]}],"references":{"doc://com.apple.virtualization/documentation/Virtualization/VZError/save":{"role":"symbol","title":"save","url":"/documentation/virtualization/vzerror/save","type":"topic","abstract":[{"text":"The VM failed to save to the save file.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"save","kind":"identifier"},{"text":": ","kind":"text"},{"text":"VZError","preciseIdentifier":"s:SC11VZErrorCodeLeV","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Code","preciseIdentifier":"c:@E@VZErrorCode","kind":"typeIdentifier"}],"identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZError/save","kind":"symbol"},"doc://com.apple.virtualization/documentation/Virtualization/VZError/notSupported":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"notSupported"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SC11VZErrorCodeLeV","kind":"typeIdentifier","text":"VZError"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@VZErrorCode","kind":"typeIdentifier","text":"Code"}],"title":"notSupported","url":"/documentation/virtualization/vzerror/notsupported","role":"symbol","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZError/notSupported","abstract":[{"type":"text","text":"The operation isn’t supported."}],"kind":"symbol","type":"topic"},"doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidVirtualMachineConfiguration":{"type":"topic","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidVirtualMachineConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"VZError","preciseIdentifier":"s:SC11VZErrorCodeLeV","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Code","preciseIdentifier":"c:@E@VZErrorCode","kind":"typeIdentifier"}],"url":"/documentation/virtualization/vzerror/invalidvirtualmachineconfiguration","title":"invalidVirtualMachineConfiguration","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidVirtualMachineConfiguration","role":"symbol","abstract":[{"type":"text","text":"An invalid configuration error."}]},"doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidVirtualMachineStateTransition":{"url":"/documentation/virtualization/vzerror/invalidvirtualmachinestatetransition","title":"invalidVirtualMachineStateTransition","type":"topic","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invalidVirtualMachineStateTransition"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SC11VZErrorCodeLeV","kind":"typeIdentifier","text":"VZError"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@VZErrorCode","kind":"typeIdentifier","text":"Code"}],"identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidVirtualMachineStateTransition","abstract":[{"type":"text","text":"An invalid state transition error."}],"role":"symbol"},"doc://com.apple.virtualization/documentation/Virtualization/VZError/Code":{"type":"topic","abstract":[{"text":"Errors you might encounter when configuring or using a virtual machine.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Code","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZError/Code","title":"VZError.Code","navigatorTitle":[{"text":"Code","kind":"identifier"}],"url":"/documentation/virtualization/vzerror/code"},"doc://com.apple.virtualization/documentation/Virtualization/VZError/noSupportedRestoreImagesInCatalog":{"abstract":[{"text":"The restore image catalog has no supported restore images.","type":"text"}],"title":"noSupportedRestoreImagesInCatalog","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"noSupportedRestoreImagesInCatalog","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SC11VZErrorCodeLeV","text":"VZError","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@VZErrorCode","text":"Code","kind":"typeIdentifier"}],"identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZError/noSupportedRestoreImagesInCatalog","kind":"symbol","url":"/documentation/virtualization/vzerror/nosupportedrestoreimagesincatalog","type":"topic","role":"symbol"},"doc://com.apple.virtualization/documentation/Virtualization/VZError/installationRequiresUpdate":{"abstract":[{"type":"text","text":"The framework canceled the installation because the host requires a software update in order to complete the installation."}],"title":"installationRequiresUpdate","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"installationRequiresUpdate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SC11VZErrorCodeLeV","kind":"typeIdentifier","text":"VZError"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@VZErrorCode","kind":"typeIdentifier","text":"Code"}],"identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZError/installationRequiresUpdate","kind":"symbol","url":"/documentation/virtualization/vzerror/installationrequiresupdate","type":"topic","role":"symbol"},"doc://com.apple.virtualization/documentation/Virtualization/VZError":{"abstract":[{"type":"text","text":"Errors that you might encounter when configuring or using a VM."}],"title":"VZError","navigatorTitle":[{"kind":"identifier","text":"VZError"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"VZError"}],"identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZError","kind":"symbol","url":"/documentation/virtualization/vzerror","type":"topic","role":"symbol"},"doc://com.apple.virtualization/documentation/Virtualization/VZError/internalError":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"internalError"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SC11VZErrorCodeLeV","kind":"typeIdentifier","text":"VZError"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@VZErrorCode","kind":"typeIdentifier","text":"Code"}],"title":"internalError","url":"/documentation/virtualization/vzerror/internalerror","role":"symbol","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZError/internalError","abstract":[{"type":"text","text":"An internal error occurred."}],"kind":"symbol","type":"topic"},"doc://com.apple.virtualization/documentation/Virtualization/VZError/networkError":{"type":"topic","abstract":[{"type":"text","text":"A network error, such as a failed connection."}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"networkError"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SC11VZErrorCodeLeV","kind":"typeIdentifier","text":"VZError"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@VZErrorCode","kind":"typeIdentifier","text":"Code"}],"role":"symbol","kind":"symbol","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZError/networkError","title":"networkError","url":"/documentation/virtualization/vzerror/networkerror"},"doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidVirtualMachineState":{"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidVirtualMachineState","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SC11VZErrorCodeLeV","text":"VZError","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@VZErrorCode","text":"Code","kind":"typeIdentifier"}],"identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidVirtualMachineState","abstract":[{"text":"An invalid state error.","type":"text"}],"role":"symbol","title":"invalidVirtualMachineState","kind":"symbol","url":"/documentation/virtualization/vzerror/invalidvirtualmachinestate"},"doc://com.apple.virtualization/documentation/Virtualization":{"type":"topic","abstract":[{"text":"Create virtual machines and run macOS and Linux-based operating systems.","type":"text"}],"role":"collection","kind":"symbol","identifier":"doc://com.apple.virtualization/documentation/Virtualization","title":"Virtualization","url":"/documentation/virtualization"},"doc://com.apple.virtualization/documentation/Virtualization/VZError/restoreImageCatalogLoadFailed":{"abstract":[{"type":"text","text":"The restore image catalog failed to load."}],"title":"restoreImageCatalogLoadFailed","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"restoreImageCatalogLoadFailed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"VZError","preciseIdentifier":"s:SC11VZErrorCodeLeV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Code","preciseIdentifier":"c:@E@VZErrorCode"}],"identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZError/restoreImageCatalogLoadFailed","kind":"symbol","url":"/documentation/virtualization/vzerror/restoreimagecatalogloadfailed","type":"topic","role":"symbol"},"doc://com.apple.virtualization/documentation/Virtualization/VZError/installationFailed":{"abstract":[{"text":"An error occurred during installation.","type":"text"}],"title":"installationFailed","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"installationFailed"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SC11VZErrorCodeLeV","kind":"typeIdentifier","text":"VZError"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@VZErrorCode","kind":"typeIdentifier","text":"Code"}],"identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZError/installationFailed","kind":"symbol","url":"/documentation/virtualization/vzerror/installationfailed","type":"topic","role":"symbol"},"doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidRestoreImage":{"title":"invalidRestoreImage","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The restore image is invalid."}],"type":"topic","url":"/documentation/virtualization/vzerror/invalidrestoreimage","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidRestoreImage","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidRestoreImage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"VZError","preciseIdentifier":"s:SC11VZErrorCodeLeV","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Code","preciseIdentifier":"c:@E@VZErrorCode","kind":"typeIdentifier"}]},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","role":"overview","kind":"technologies","abstract":[{"text":"","type":"text"}],"type":"topic","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies"},"doc://com.apple.virtualization/documentation/Virtualization/VZError/operationCancelled":{"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"operationCancelled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"VZError","preciseIdentifier":"s:SC11VZErrorCodeLeV","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Code","preciseIdentifier":"c:@E@VZErrorCode","kind":"typeIdentifier"}],"identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZError/operationCancelled","abstract":[{"text":"The user canceled the installation of Rosetta or the app canceled the installation of a guest OS.","type":"text"}],"role":"symbol","title":"operationCancelled","kind":"symbol","url":"/documentation/virtualization/vzerror/operationcancelled"},"doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidDiskImage":{"type":"topic","title":"invalidDiskImage","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidDiskImage","role":"symbol","url":"/documentation/virtualization/vzerror/invaliddiskimage","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invalidDiskImage"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SC11VZErrorCodeLeV","kind":"typeIdentifier","text":"VZError"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@VZErrorCode","kind":"typeIdentifier","text":"Code"}],"kind":"symbol","abstract":[{"text":"An invalid disk-image error.","type":"text"}]},"doc://com.apple.virtualization/documentation/Virtualization/VZError/outOfDiskSpace":{"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"outOfDiskSpace"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SC11VZErrorCodeLeV","kind":"typeIdentifier","text":"VZError"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@VZErrorCode","kind":"typeIdentifier","text":"Code"}],"identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZError/outOfDiskSpace","abstract":[{"type":"text","text":"The host is out of disk space."}],"role":"symbol","title":"outOfDiskSpace","kind":"symbol","url":"/documentation/virtualization/vzerror/outofdiskspace"},"doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidRestoreImageCatalog":{"url":"/documentation/virtualization/vzerror/invalidrestoreimagecatalog","title":"invalidRestoreImageCatalog","type":"topic","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invalidRestoreImageCatalog"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SC11VZErrorCodeLeV","kind":"typeIdentifier","text":"VZError"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@VZErrorCode","kind":"typeIdentifier","text":"Code"}],"identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZError/invalidRestoreImageCatalog","abstract":[{"text":"The restore image catalog is invalid.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"VZErrorCode","op":"replace","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code/title"},{"value":[{"kind":"identifier","text":"VZErrorCode"}],"op":"replace","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code/fragments"},{"value":[{"kind":"identifier","text":"VZErrorCode"}],"op":"replace","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code/navigatorTitle"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}