{"sections":[],"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/passthroughViews","interfaceLanguage":"swift"},"variants":[{"paths":["/documentation/uikit/uipopoverpresentationcontroller/passthroughviews"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uipopoverpresentationcontroller/passthroughviews"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"passthroughViews","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"passthroughViews","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"navigatorTitle":[{"text":"passthroughViews","kind":"identifier"}],"roleHeading":"Instance Property","role":"symbol","symbolKind":"property","platforms":[{"unavailable":false,"introducedAt":"8.0","deprecated":false,"beta":false,"name":"iOS"},{"unavailable":false,"introducedAt":"8.0","deprecated":false,"beta":false,"name":"iPadOS"},{"beta":false,"deprecated":false,"name":"Mac Catalyst","introducedAt":"13.1","unavailable":false},{"beta":false,"deprecated":false,"name":"visionOS","introducedAt":"1.0","unavailable":false}],"externalID":"c:objc(cs)UIPopoverPresentationController(py)passthroughViews","modules":[{"name":"UIKit"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"passthroughViews"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView","identifier":"doc://com.apple.uikit/documentation/UIKit/UIView"},{"kind":"text","text":"]? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"]}]},{"kind":"content","content":[{"anchor":"Discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"When a popover is active, interactions with other views are normally disabled until the popover is dismissed. Assigning an array of ","type":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIView","type":"reference","isActive":true},{"text":" objects to this property causes UIKit to continue dispatching touch event to the views you specified.","type":"text"}]}]}],"kind":"symbol","seeAlsoSections":[{"title":"Configuring the popover appearance","anchor":"Configuring-the-popover-appearance","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/popoverLayoutMargins","doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/backgroundColor","doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/popoverBackgroundViewClass","doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/canOverlapSourceViewRect"],"generated":true}],"abstract":[{"text":"An array of views that the user can interact with while the popover is visible.","type":"text"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController"]]},"references":{"doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/popoverLayoutMargins":{"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"popoverLayoutMargins","kind":"identifier"}],"title":"popoverLayoutMargins","url":"/documentation/uikit/uipopoverpresentationcontroller/popoverlayoutmargins","abstract":[{"text":"The margins that define the portion of the screen in which it is permissible to display the popover.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/popoverLayoutMargins","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"popoverLayoutMargins","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@UIEdgeInsets","kind":"typeIdentifier","text":"UIEdgeInsets"}]},"doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/passthroughViews":{"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"passthroughViews"}],"title":"passthroughViews","url":"/documentation/uikit/uipopoverpresentationcontroller/passthroughviews","abstract":[{"text":"An array of views that the user can interact with while the popover is visible.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/passthroughViews","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"passthroughViews"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"kind":"text","text":"]?"}]},"doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/popoverBackgroundViewClass":{"kind":"symbol","abstract":[{"type":"text","text":"The class to use for displaying the popover background content."}],"url":"/documentation/uikit/uipopoverpresentationcontroller/popoverbackgroundviewclass","navigatorTitle":[{"kind":"identifier","text":"popoverBackgroundViewClass"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"popoverBackgroundViewClass"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)UIPopoverBackgroundViewMethods","kind":"typeIdentifier","text":"UIPopoverBackgroundViewMethods"},{"kind":"text","text":".Type)?"}],"title":"popoverBackgroundViewClass","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/popoverBackgroundViewClass","role":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIView":{"title":"UIView","kind":"symbol","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIView","abstract":[{"text":"An object that manages the content for a rectangular area on the screen.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"UIView","kind":"identifier"}],"url":"/documentation/uikit/uiview","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIView","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController":{"title":"UIPopoverPresentationController","url":"/documentation/uikit/uipopoverpresentationcontroller","role":"symbol","type":"topic","abstract":[{"type":"text","text":"An object that manages the display of content in a popover."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIPopoverPresentationController"}],"navigatorTitle":[{"kind":"identifier","text":"UIPopoverPresentationController"}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/canOverlapSourceViewRect":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canOverlapSourceViewRect","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"canOverlapSourceViewRect","kind":"identifier"}],"abstract":[{"type":"text","text":"A Boolean value indicating whether the popover can overlap its view rectangle."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/canOverlapSourceViewRect","url":"/documentation/uikit/uipopoverpresentationcontroller/canoverlapsourceviewrect","type":"topic","title":"canOverlapSourceViewRect","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/backgroundColor":{"abstract":[{"type":"text","text":"The color of the popover’s backdrop view."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"kind":"text","text":"?"}],"kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"backgroundColor"}],"title":"backgroundColor","url":"/documentation/uikit/uipopoverpresentationcontroller/backgroundcolor","identifier":"doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/backgroundColor"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"beta":false,"deprecated":false,"introducedAt":"8.0","name":"iOS","unavailable":false},{"beta":false,"deprecated":false,"introducedAt":"8.0","name":"iPadOS","unavailable":false},{"beta":false,"deprecated":false,"name":"Mac Catalyst","introducedAt":"13.1","unavailable":false},{"beta":false,"deprecated":false,"name":"visionOS","introducedAt":"1.0","unavailable":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Property","op":"replace"},{"path":"/metadata/title","value":"passthroughViews","op":"replace"},{"path":"/metadata/symbolKind","value":"property","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"passthroughViews","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"title":"Configuring the popover appearance","generated":true,"anchor":"Configuring-the-popover-appearance","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/popoverLayoutMargins","doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/backgroundColor","doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/popoverBackgroundViewClass","doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/canOverlapSourceViewRect"]}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<UIView *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"passthroughViews","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationController~1popoverLayoutMargins/title","value":"popoverLayoutMargins","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationController~1popoverLayoutMargins/fragments","value":[{"kind":"identifier","text":"popoverLayoutMargins"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationController~1passthroughViews/title","value":"passthroughViews","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationController~1passthroughViews/fragments","value":[{"text":"passthroughViews","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationController~1popoverBackgroundViewClass/title","value":"popoverBackgroundViewClass","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationController~1popoverBackgroundViewClass/fragments","value":[{"text":"popoverBackgroundViewClass","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/title","value":"UIView","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/fragments","value":[{"text":"UIView","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/navigatorTitle","value":[{"text":"UIView","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationController/title","value":"UIPopoverPresentationController","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationController/fragments","value":[{"kind":"identifier","text":"UIPopoverPresentationController"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationController/navigatorTitle","value":[{"text":"UIPopoverPresentationController","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationController~1canOverlapSourceViewRect/title","value":"canOverlapSourceViewRect","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationController~1canOverlapSourceViewRect/fragments","value":[{"text":"canOverlapSourceViewRect","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationController~1backgroundColor/title","value":"backgroundColor","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationController~1backgroundColor/fragments","value":[{"text":"backgroundColor","kind":"identifier"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}