{
  "abstract": [
    {
      "text": "Returns a text selection that expands to the nearest boundaries for selection granularity and an enclosing point you specify.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation/textSelection(for:enclosing:inContainerAt:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSTextSelectionNavigation(im)textSelectionForSelectionGranularity:enclosingPoint:inContainerAtLocation:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "textSelection"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "for"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSTextSelection",
        "text": "NSTextSelection"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NSTextSelectionGranularity",
        "text": "Granularity"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "enclosing"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@CGPoint",
        "text": "CGPoint"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "inContainerAt"
      },
      {
        "kind": "text",
        "text": ": any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(pl)NSTextLocation",
        "text": "NSTextLocation"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSTextSelection",
        "text": "NSTextSelection"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "textSelectionForSelectionGranularity:enclosingPoint:inContainerAtLocation:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "textSelection(for:enclosing:inContainerAt:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "textSelection"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "for"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "selectionGranularity"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextSelection",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSTextSelection",
              "text": "NSTextSelection"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextSelection/Granularity-swift.enum",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSTextSelectionGranularity",
              "text": "Granularity"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "enclosing"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "point"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@S@CGPoint",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@CGPoint",
              "text": "CGPoint"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "inContainerAt"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "location"
            },
            {
              "kind": "text",
              "text": ": any "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextLocation",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSTextLocation",
              "text": "NSTextLocation"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextSelection",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSTextSelection",
              "text": "NSTextSelection"
            },
            {
              "kind": "text",
              "text": "?"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "One of the available ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextSelection/Granularity-swift.enum",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " options.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "selectionGranularity"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The point that encloses the text.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "point"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextLocation",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " that describes the container.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "location"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A new ",
              "type": "text"
            },
            {
              "code": "NSTextSelection",
              "type": "codeVoice"
            },
            {
              "text": ", or ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " if the text selection is not found.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextLocation": {
      "abstract": [
        {
          "text": "An interface you implement that represents an abstract location inside your document’s content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextLocation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextLocation"
        }
      ],
      "role": "symbol",
      "title": "NSTextLocation",
      "type": "topic",
      "url": "/documentation/appkit/nstextlocation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextSelection": {
      "abstract": [
        {
          "text": "A class that represents a single logical selection context that corresponds to an insertion point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextSelection"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextSelection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextSelection"
        }
      ],
      "role": "symbol",
      "title": "NSTextSelection",
      "type": "topic",
      "url": "/documentation/appkit/nstextselection"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextSelection/Granularity-swift.enum": {
      "abstract": [
        {
          "text": "Values that describe the different granularities available to make a selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Granularity"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextSelection/Granularity-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Granularity"
        }
      ],
      "role": "symbol",
      "title": "NSTextSelection.Granularity",
      "type": "topic",
      "url": "/documentation/appkit/nstextselection/granularity-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation": {
      "abstract": [
        {
          "text": "An interface you use to expose methods for obtaining results from actions performed on text selections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextSelectionNavigation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextSelectionNavigation"
        }
      ],
      "role": "symbol",
      "title": "NSTextSelectionNavigation",
      "type": "topic",
      "url": "/documentation/appkit/nstextselectionnavigation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation/Destination": {
      "abstract": [
        {
          "text": "Values that affect how the framework handles navigation across different textual boundaries during a selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Destination"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation/Destination",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Destination"
        }
      ],
      "role": "symbol",
      "title": "NSTextSelectionNavigation.Destination",
      "type": "topic",
      "url": "/documentation/appkit/nstextselectionnavigation/destination"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation/Direction": {
      "abstract": [
        {
          "text": "Values that describe the direction of a selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Direction"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation/Direction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Direction"
        }
      ],
      "role": "symbol",
      "title": "NSTextSelectionNavigation.Direction",
      "type": "topic",
      "url": "/documentation/appkit/nstextselectionnavigation/direction"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation/Modifier": {
      "abstract": [
        {
          "text": "Values that describe how the framework handles different kinds of selection modifiers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Modifier"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation/Modifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Modifier"
        }
      ],
      "role": "symbol",
      "title": "NSTextSelectionNavigation.Modifier",
      "type": "topic",
      "url": "/documentation/appkit/nstextselectionnavigation/modifier"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation/allowsNonContiguousRanges": {
      "abstract": [
        {
          "text": "Determines if the instance could produce selections with multiple noncontiguous selections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsNonContiguousRanges"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation/allowsNonContiguousRanges",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowsNonContiguousRanges"
        }
      ],
      "role": "symbol",
      "title": "allowsNonContiguousRanges",
      "type": "topic",
      "url": "/documentation/appkit/nstextselectionnavigation/allowsnoncontiguousranges"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation/rotatesCoordinateSystemForLayoutOrientation": {
      "abstract": [
        {
          "text": "Determines if the framework rotates the coordinate system to match the layout orientation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rotatesCoordinateSystemForLayoutOrientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation/rotatesCoordinateSystemForLayoutOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rotatesCoordinateSystemForLayoutOrientation"
        }
      ],
      "role": "symbol",
      "title": "rotatesCoordinateSystemForLayoutOrientation",
      "type": "topic",
      "url": "/documentation/appkit/nstextselectionnavigation/rotatescoordinatesystemforlayoutorientation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation/textSelection(for:enclosing:inContainerAt:)": {
      "abstract": [
        {
          "text": "Returns a text selection that expands to the nearest boundaries for selection granularity and an enclosing point you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textSelection"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextSelection",
          "text": "NSTextSelection"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTextSelectionGranularity",
          "text": "Granularity"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "enclosing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "inContainerAt"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSTextLocation",
          "text": "NSTextLocation"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextSelection",
          "text": "NSTextSelection"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation/textSelection(for:enclosing:inContainerAt:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textSelectionForSelectionGranularity:enclosingPoint:inContainerAtLocation:"
        }
      ],
      "role": "symbol",
      "title": "textSelection(for:enclosing:inContainerAt:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextselectionnavigation/textselection(for:enclosing:incontainerat:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@S@CGPoint": {
      "abstract": [
        {
          "text": "A structure that contains a point in a two-dimensional coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "CGPoint"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@S@CGPoint",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGPoint",
      "type": "topic",
      "url": "/documentation/corefoundation/cgpoint"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Selection-characteristics",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation/allowsNonContiguousRanges",
        "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation/rotatesCoordinateSystemForLayoutOrientation",
        "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation/Modifier",
        "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation/Destination",
        "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation/Direction"
      ],
      "title": "Selection characteristics"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "textSelectionForSelectionGranularity:enclosingPoint:inContainerAtLocation:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textSelectionForSelectionGranularity:enclosingPoint:inContainerAtLocation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Selection-characteristics",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation/allowsNonContiguousRanges",
                "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation/rotatesCoordinateSystemForLayoutOrientation",
                "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation/Modifier",
                "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation/Destination",
                "doc://com.apple.appkit/documentation/AppKit/NSTextSelectionNavigation/Direction"
              ],
              "title": "Selection characteristics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextSelection",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSTextSelection",
                    "text": "NSTextSelection"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "identifier",
                    "text": "textSelectionForSelectionGranularity:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextSelection/Granularity-swift.enum",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@NSTextSelectionGranularity",
                    "text": "NSTextSelectionGranularity"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "selectionGranularity"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "enclosingPoint:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@S@CGPoint",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@CGPoint",
                    "text": "CGPoint"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "point"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "inContainerAtLocation:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Qoobjc(pl)NSTextLocation",
                    "text": "id<NSTextLocation>"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "location"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "One of the available ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextSelection/Granularity-swift.enum",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " options.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "selectionGranularity"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The point that encloses the text.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "point"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextLocation",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " that describes the container.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "location"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A new ",
                    "type": "text"
                  },
                  {
                    "code": "NSTextSelection",
                    "type": "codeVoice"
                  },
                  {
                    "text": ", or ",
                    "type": "text"
                  },
                  {
                    "code": "nil",
                    "type": "codeVoice"
                  },
                  {
                    "text": " if the text selection is not found.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextSelectionNavigation~1rotatesCoordinateSystemForLayoutOrientation/title",
          "value": "rotatesCoordinateSystemForLayoutOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextSelectionNavigation~1rotatesCoordinateSystemForLayoutOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rotatesCoordinateSystemForLayoutOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextSelectionNavigation~1allowsNonContiguousRanges/title",
          "value": "allowsNonContiguousRanges"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextSelectionNavigation~1allowsNonContiguousRanges/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowsNonContiguousRanges"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextSelectionNavigation/title",
          "value": "NSTextSelectionNavigation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextSelectionNavigation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionNavigation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextSelectionNavigation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionNavigation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextSelection/title",
          "value": "NSTextSelection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextSelection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextSelection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextSelectionNavigation~1Direction/title",
          "value": "NSTextSelectionNavigationDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextSelectionNavigation~1Direction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionNavigationDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextSelectionNavigation~1Direction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionNavigationDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextSelectionNavigation~1textSelection(for:enclosing:inContainerAt:)/title",
          "value": "textSelectionForSelectionGranularity:enclosingPoint:inContainerAtLocation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextSelectionNavigation~1textSelection(for:enclosing:inContainerAt:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textSelectionForSelectionGranularity:enclosingPoint:inContainerAtLocation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextSelection~1Granularity-swift.enum/title",
          "value": "NSTextSelectionGranularity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextSelection~1Granularity-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionGranularity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextSelection~1Granularity-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionGranularity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextSelectionNavigation~1Destination/title",
          "value": "NSTextSelectionNavigationDestination"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextSelectionNavigation~1Destination/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionNavigationDestination"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextSelectionNavigation~1Destination/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionNavigationDestination"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextLocation/title",
          "value": "NSTextLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextLocation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextSelectionNavigation~1Modifier/title",
          "value": "NSTextSelectionNavigationModifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextSelectionNavigation~1Modifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionNavigationModifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextSelectionNavigation~1Modifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionNavigationModifier"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nstextselectionnavigation/textselection(for:enclosing:incontainerat:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nstextselectionnavigation/textselection(for:enclosing:incontainerat:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
