{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText",
        "doc://com.apple.coretext/documentation/CoreText/CTLineBreakMode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/CTLineBreakMode/byCharWrapping"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CTLineBreakMode@kCTLineBreakByCharWrapping",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "byCharWrapping"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCTLineBreakByCharWrapping"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CTLineBreakMode.byCharWrapping"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "byCharWrapping"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Wrapping occurs before the first character that doesn’t fit.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTLineBreakMode": {
      "abstract": [
        {
          "text": "These constants specify what happens when a line is too long for its frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTLineBreakMode"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLineBreakMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTLineBreakMode"
        }
      ],
      "role": "symbol",
      "title": "CTLineBreakMode",
      "type": "topic",
      "url": "/documentation/coretext/ctlinebreakmode"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTLineBreakMode/byCharWrapping": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "byCharWrapping"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLineBreakMode/byCharWrapping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTLineBreakByCharWrapping"
        }
      ],
      "role": "symbol",
      "title": "CTLineBreakMode.byCharWrapping",
      "type": "topic",
      "url": "/documentation/coretext/ctlinebreakmode/bycharwrapping"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTLineBreakMode/byClipping": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "byClipping"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLineBreakMode/byClipping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTLineBreakByClipping"
        }
      ],
      "role": "symbol",
      "title": "CTLineBreakMode.byClipping",
      "type": "topic",
      "url": "/documentation/coretext/ctlinebreakmode/byclipping"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTLineBreakMode/byTruncatingHead": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "byTruncatingHead"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLineBreakMode/byTruncatingHead",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTLineBreakByTruncatingHead"
        }
      ],
      "role": "symbol",
      "title": "CTLineBreakMode.byTruncatingHead",
      "type": "topic",
      "url": "/documentation/coretext/ctlinebreakmode/bytruncatinghead"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTLineBreakMode/byTruncatingMiddle": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "byTruncatingMiddle"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLineBreakMode/byTruncatingMiddle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTLineBreakByTruncatingMiddle"
        }
      ],
      "role": "symbol",
      "title": "CTLineBreakMode.byTruncatingMiddle",
      "type": "topic",
      "url": "/documentation/coretext/ctlinebreakmode/bytruncatingmiddle"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTLineBreakMode/byTruncatingTail": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "byTruncatingTail"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLineBreakMode/byTruncatingTail",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTLineBreakByTruncatingTail"
        }
      ],
      "role": "symbol",
      "title": "CTLineBreakMode.byTruncatingTail",
      "type": "topic",
      "url": "/documentation/coretext/ctlinebreakmode/bytruncatingtail"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTLineBreakMode/byWordWrapping": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "byWordWrapping"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLineBreakMode/byWordWrapping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTLineBreakByWordWrapping"
        }
      ],
      "role": "symbol",
      "title": "CTLineBreakMode.byWordWrapping",
      "type": "topic",
      "url": "/documentation/coretext/ctlinebreakmode/bywordwrapping"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTLineBreakMode/byWordWrapping",
        "doc://com.apple.coretext/documentation/CoreText/CTLineBreakMode/byClipping",
        "doc://com.apple.coretext/documentation/CoreText/CTLineBreakMode/byTruncatingHead",
        "doc://com.apple.coretext/documentation/CoreText/CTLineBreakMode/byTruncatingTail",
        "doc://com.apple.coretext/documentation/CoreText/CTLineBreakMode/byTruncatingMiddle"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCTLineBreakByCharWrapping"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTLineBreakByCharWrapping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretext/documentation/CoreText",
                "doc://com.apple.coretext/documentation/CoreText/CTLineBreakMode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTLineBreakMode/byWordWrapping",
                "doc://com.apple.coretext/documentation/CoreText/CTLineBreakMode/byClipping",
                "doc://com.apple.coretext/documentation/CoreText/CTLineBreakMode/byTruncatingHead",
                "doc://com.apple.coretext/documentation/CoreText/CTLineBreakMode/byTruncatingTail",
                "doc://com.apple.coretext/documentation/CoreText/CTLineBreakMode/byTruncatingMiddle"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCTLineBreakByCharWrapping"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineBreakMode~1byTruncatingHead/title",
          "value": "kCTLineBreakByTruncatingHead"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineBreakMode~1byTruncatingHead/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTLineBreakByTruncatingHead"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineBreakMode~1byClipping/title",
          "value": "kCTLineBreakByClipping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineBreakMode~1byClipping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTLineBreakByClipping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineBreakMode/title",
          "value": "CTLineBreakMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineBreakMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTLineBreakMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineBreakMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTLineBreakMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineBreakMode~1byCharWrapping/title",
          "value": "kCTLineBreakByCharWrapping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineBreakMode~1byCharWrapping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTLineBreakByCharWrapping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineBreakMode~1byTruncatingTail/title",
          "value": "kCTLineBreakByTruncatingTail"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineBreakMode~1byTruncatingTail/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTLineBreakByTruncatingTail"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineBreakMode~1byWordWrapping/title",
          "value": "kCTLineBreakByWordWrapping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineBreakMode~1byWordWrapping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTLineBreakByWordWrapping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineBreakMode~1byTruncatingMiddle/title",
          "value": "kCTLineBreakByTruncatingMiddle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineBreakMode~1byTruncatingMiddle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTLineBreakByTruncatingMiddle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/ctlinebreakmode/bycharwrapping"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/ctlinebreakmode/bycharwrapping"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
