{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/bottom"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint","doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bottom","kind":"identifier"}],"languages":["swift"]}]}],"kind":"symbol","abstract":[{"type":"text","text":"The bottom of the object’s alignment rectangle."}],"variants":[{"paths":["/documentation/uikit/nslayoutconstraint/attribute/bottom"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/nslayoutconstraint/attribute/bottom"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"anchor":"Constants","generated":true,"title":"Constants","identifiers":["doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/left","doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/right","doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/top","doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/leading","doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/trailing","doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/width","doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/height","doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/centerX","doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/centerY","doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/lastBaseline","doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/firstBaseline","doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/leftMargin","doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/rightMargin","doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/topMargin","doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/bottomMargin"]}],"metadata":{"platforms":[{"name":"iOS","deprecated":false,"beta":false,"unavailable":false},{"name":"iPadOS","deprecated":false,"beta":false,"unavailable":false},{"name":"Mac Catalyst","deprecated":false,"beta":false,"unavailable":false},{"name":"tvOS","deprecated":false,"beta":false,"unavailable":false},{"name":"visionOS","deprecated":false,"beta":false,"unavailable":false}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bottom","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"UIKit"}],"title":"NSLayoutConstraint.Attribute.bottom","navigatorTitle":[{"text":"NSLayoutAttributeBottom","kind":"identifier"}],"role":"symbol","externalID":"c:@E@NSLayoutAttribute@NSLayoutAttributeBottom","symbolKind":"case"},"references":{"doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/topMargin":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topMargin","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The object’s top margin."}],"url":"/documentation/uikit/nslayoutconstraint/attribute/topmargin","title":"NSLayoutConstraint.Attribute.topMargin","navigatorTitle":[{"text":"NSLayoutAttributeTopMargin","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/topMargin","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/leading":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"leading"}],"abstract":[{"text":"The leading edge of the object’s alignment rectangle.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/leading","role":"symbol","url":"/documentation/uikit/nslayoutconstraint/attribute/leading","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSLayoutAttributeLeading"}],"type":"topic","title":"NSLayoutConstraint.Attribute.leading"},"doc://com.apple.uikit/documentation/UIKit/NSLayoutAttribute/NSLayoutAttributeBaseline":{"fragments":[{"text":"NSLayoutAttributeBaseline","kind":"identifier"}],"title":"NSLayoutAttributeBaseline","identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutAttribute/NSLayoutAttributeBaseline","role":"symbol","type":"topic","url":"/documentation/uikit/nslayoutattribute/nslayoutattributebaseline","abstract":[{"text":"The object’s baseline.","type":"text"}],"kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/lastBaseline":{"role":"symbol","abstract":[{"type":"text","text":"The object’s baseline."}],"navigatorTitle":[{"kind":"identifier","text":"NSLayoutAttributeLastBaseline"}],"type":"topic","url":"/documentation/uikit/nslayoutconstraint/attribute/lastbaseline","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/lastBaseline","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"lastBaseline"}],"title":"NSLayoutConstraint.Attribute.lastBaseline"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/top":{"abstract":[{"type":"text","text":"The top of the object’s alignment rectangle."}],"navigatorTitle":[{"kind":"identifier","text":"NSLayoutAttributeTop"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/top","url":"/documentation/uikit/nslayoutconstraint/attribute/top","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"top"}],"role":"symbol","title":"NSLayoutConstraint.Attribute.top","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSLayoutConstraint","kind":"identifier"}],"title":"NSLayoutConstraint","identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint","role":"symbol","type":"topic","url":"/documentation/uikit/nslayoutconstraint","abstract":[{"text":"The relationship between two user interface objects that must be satisfied by the constraint-based layout system.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"NSLayoutConstraint","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/bottom":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottom"}],"abstract":[{"type":"text","text":"The bottom of the object’s alignment rectangle."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/bottom","role":"symbol","url":"/documentation/uikit/nslayoutconstraint/attribute/bottom","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSLayoutAttributeBottom"}],"type":"topic","title":"NSLayoutConstraint.Attribute.bottom"},"doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/leftMargin":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"leftMargin","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The object’s left margin."}],"url":"/documentation/uikit/nslayoutconstraint/attribute/leftmargin","title":"NSLayoutConstraint.Attribute.leftMargin","navigatorTitle":[{"text":"NSLayoutAttributeLeftMargin","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/leftMargin","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/centerY":{"url":"/documentation/uikit/nslayoutconstraint/attribute/centery","identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/centerY","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSLayoutAttributeCenterY"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"centerY"}],"type":"topic","title":"NSLayoutConstraint.Attribute.centerY","kind":"symbol","abstract":[{"text":"The center along the y-axis of the object’s alignment rectangle.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/left":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"left","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The left side of the object’s alignment rectangle."}],"url":"/documentation/uikit/nslayoutconstraint/attribute/left","title":"NSLayoutConstraint.Attribute.left","navigatorTitle":[{"text":"NSLayoutAttributeLeft","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/left","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/width":{"abstract":[{"text":"The width of the object’s alignment rectangle.","type":"text"}],"navigatorTitle":[{"text":"NSLayoutAttributeWidth","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/width","url":"/documentation/uikit/nslayoutconstraint/attribute/width","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"width","kind":"identifier"}],"role":"symbol","title":"NSLayoutConstraint.Attribute.width","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/right":{"navigatorTitle":[{"text":"NSLayoutAttributeRight","kind":"identifier"}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"right","kind":"identifier"}],"url":"/documentation/uikit/nslayoutconstraint/attribute/right","abstract":[{"text":"The right side of the object’s alignment rectangle.","type":"text"}],"title":"NSLayoutConstraint.Attribute.right","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/right","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute":{"abstract":[{"type":"text","text":"The part of the object’s visual representation that should be used to get the value for the constraint."}],"navigatorTitle":[{"kind":"identifier","text":"Attribute"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute","url":"/documentation/uikit/nslayoutconstraint/attribute","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Attribute"}],"role":"symbol","title":"NSLayoutConstraint.Attribute","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/trailing":{"abstract":[{"type":"text","text":"The trailing edge of the object’s alignment rectangle."}],"navigatorTitle":[{"text":"NSLayoutAttributeTrailing","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/trailing","url":"/documentation/uikit/nslayoutconstraint/attribute/trailing","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trailing","kind":"identifier"}],"role":"symbol","title":"NSLayoutConstraint.Attribute.trailing","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/rightMargin":{"navigatorTitle":[{"text":"NSLayoutAttributeRightMargin","kind":"identifier"}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rightMargin","kind":"identifier"}],"url":"/documentation/uikit/nslayoutconstraint/attribute/rightmargin","abstract":[{"text":"The object’s right margin.","type":"text"}],"title":"NSLayoutConstraint.Attribute.rightMargin","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/rightMargin","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/firstBaseline":{"abstract":[{"type":"text","text":"The object’s baseline."}],"navigatorTitle":[{"text":"NSLayoutAttributeFirstBaseline","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/firstBaseline","url":"/documentation/uikit/nslayoutconstraint/attribute/firstbaseline","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"firstBaseline","kind":"identifier"}],"role":"symbol","title":"NSLayoutConstraint.Attribute.firstBaseline","type":"topic"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/bottomMargin":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bottomMargin","kind":"identifier"}],"abstract":[{"type":"text","text":"The object’s bottom margin."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/bottomMargin","role":"symbol","url":"/documentation/uikit/nslayoutconstraint/attribute/bottommargin","kind":"symbol","navigatorTitle":[{"text":"NSLayoutAttributeBottomMargin","kind":"identifier"}],"type":"topic","title":"NSLayoutConstraint.Attribute.bottomMargin"},"doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/height":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"height"}],"title":"NSLayoutConstraint.Attribute.height","identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/height","role":"symbol","type":"topic","url":"/documentation/uikit/nslayoutconstraint/attribute/height","abstract":[{"text":"The height of the object’s alignment rectangle.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSLayoutAttributeHeight"}]},"doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/centerX":{"abstract":[{"type":"text","text":"The center along the x-axis of the object’s alignment rectangle."}],"navigatorTitle":[{"kind":"identifier","text":"NSLayoutAttributeCenterX"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/centerX","url":"/documentation/uikit/nslayoutconstraint/attribute/centerx","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"centerX"}],"role":"symbol","title":"NSLayoutConstraint.Attribute.centerX","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"name":"iOS","deprecated":false,"beta":false,"unavailable":false},{"name":"iPadOS","deprecated":false,"beta":false,"unavailable":false},{"name":"Mac Catalyst","deprecated":false,"beta":false,"unavailable":false},{"name":"tvOS","deprecated":false,"beta":false,"unavailable":false},{"name":"visionOS","deprecated":false,"beta":false,"unavailable":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"/metadata/title","op":"replace","value":"NSLayoutAttributeBottom"},{"path":"/metadata/symbolKind","op":"replace","value":"case"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"NSLayoutAttributeBottom","kind":"identifier"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/left","doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/right","doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/top","doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/leading","doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/trailing","doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/width","doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/height","doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/centerX","doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/centerY","doc://com.apple.uikit/documentation/UIKit/NSLayoutAttribute/NSLayoutAttributeBaseline","doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/lastBaseline","doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/firstBaseline","doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/leftMargin","doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/rightMargin","doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/topMargin"],"title":"Constants","anchor":"Constants","generated":true}]},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"kind":"identifier","text":"NSLayoutAttributeBottom"}]}]}},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1topMargin/title","op":"replace","value":"NSLayoutAttributeTopMargin"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1topMargin/fragments","op":"replace","value":[{"text":"NSLayoutAttributeTopMargin","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1leading/title","op":"replace","value":"NSLayoutAttributeLeading"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1leading/fragments","op":"replace","value":[{"kind":"identifier","text":"NSLayoutAttributeLeading"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1lastBaseline/title","op":"replace","value":"NSLayoutAttributeLastBaseline"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1lastBaseline/fragments","op":"replace","value":[{"kind":"identifier","text":"NSLayoutAttributeLastBaseline"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1top/title","op":"replace","value":"NSLayoutAttributeTop"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1top/fragments","op":"replace","value":[{"kind":"identifier","text":"NSLayoutAttributeTop"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint/title","op":"replace","value":"NSLayoutConstraint"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint/fragments","op":"replace","value":[{"kind":"identifier","text":"NSLayoutConstraint"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NSLayoutConstraint"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1bottom/title","op":"replace","value":"NSLayoutAttributeBottom"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1bottom/fragments","op":"replace","value":[{"text":"NSLayoutAttributeBottom","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1leftMargin/title","op":"replace","value":"NSLayoutAttributeLeftMargin"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1leftMargin/fragments","op":"replace","value":[{"kind":"identifier","text":"NSLayoutAttributeLeftMargin"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1centerY/title","op":"replace","value":"NSLayoutAttributeCenterY"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1centerY/fragments","op":"replace","value":[{"kind":"identifier","text":"NSLayoutAttributeCenterY"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1left/title","op":"replace","value":"NSLayoutAttributeLeft"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1left/fragments","op":"replace","value":[{"text":"NSLayoutAttributeLeft","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1width/title","op":"replace","value":"NSLayoutAttributeWidth"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1width/fragments","op":"replace","value":[{"text":"NSLayoutAttributeWidth","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1right/title","op":"replace","value":"NSLayoutAttributeRight"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1right/fragments","op":"replace","value":[{"text":"NSLayoutAttributeRight","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute/title","op":"replace","value":"NSLayoutAttribute"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute/fragments","op":"replace","value":[{"kind":"identifier","text":"NSLayoutAttribute"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NSLayoutAttribute"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1trailing/title","op":"replace","value":"NSLayoutAttributeTrailing"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1trailing/fragments","op":"replace","value":[{"kind":"identifier","text":"NSLayoutAttributeTrailing"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1rightMargin/title","op":"replace","value":"NSLayoutAttributeRightMargin"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1rightMargin/fragments","op":"replace","value":[{"text":"NSLayoutAttributeRightMargin","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1firstBaseline/title","op":"replace","value":"NSLayoutAttributeFirstBaseline"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1firstBaseline/fragments","op":"replace","value":[{"kind":"identifier","text":"NSLayoutAttributeFirstBaseline"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1bottomMargin/title","op":"replace","value":"NSLayoutAttributeBottomMargin"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1bottomMargin/fragments","op":"replace","value":[{"kind":"identifier","text":"NSLayoutAttributeBottomMargin"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1height/title","op":"replace","value":"NSLayoutAttributeHeight"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1height/fragments","op":"replace","value":[{"text":"NSLayoutAttributeHeight","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1centerX/title","op":"replace","value":"NSLayoutAttributeCenterX"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1centerX/fragments","op":"replace","value":[{"text":"NSLayoutAttributeCenterX","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}