{"relationshipsSections":[{"identifiers":["doc://com.apple.accelerate/documentation/Accelerate/AccelerateBuffer","doc://com.apple.accelerate/documentation/Accelerate/AccelerateMatrixBuffer","doc://com.apple.accelerate/documentation/Accelerate/AccelerateMutableBuffer","doc://com.apple.accelerate/documentation/Accelerate/AccelerateMutableMatrixBuffer","doc://com.externally.resolved.symbol/s:s8CopyableP"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PixelBuffer","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Format","kind":"genericParameter"},{"text":"> ","kind":"text"},{"text":"where","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Format","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"PixelFormat","kind":"typeIdentifier","identifier":"doc://com.apple.accelerate/documentation/Accelerate/PixelFormat","preciseIdentifier":"s:10Accelerate11PixelFormatP"}],"languages":["swift"]}]},{"mentions":["doc://com.apple.accelerate/documentation/Accelerate/enhancing-image-contrast-with-histogram-manipulation","doc://com.apple.accelerate/documentation/Accelerate/applying-vimage-operations-to-regions-of-interest","doc://com.apple.accelerate/documentation/Accelerate/building-a-basic-image-conversion-workflow","doc://com.apple.accelerate/documentation/Accelerate/optimizing-image-processing-performance","doc://com.apple.accelerate/documentation/Accelerate/applying-color-transforms-to-images-with-a-multidimensional-lookup-table","doc://com.apple.accelerate/documentation/Accelerate/converting-bitmap-data-between-core-graphics-images-and-vimage-buffers","doc://com.apple.accelerate/documentation/Accelerate/converting-chroma-subsampled-images"],"kind":"mentions"},{"kind":"content","content":[{"type":"heading","level":2,"text":"Overview","anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use a "},{"type":"reference","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer","isActive":true},{"type":"text","text":" to represent an image from a "},{"type":"reference","identifier":"doc://com.apple.documentation/documentation/coregraphics/cgimage","isActive":true},{"type":"text","text":" instance, a "},{"type":"reference","identifier":"doc://com.apple.documentation/documentation/CoreVideo/CVPixelBuffer","isActive":true},{"type":"text","text":" structure, or a collection of raw pixel values. Pixel buffers are typed by their bits per channel and number of channels. For example, "},{"type":"reference","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage/Interleaved8x4","isActive":true},{"type":"text","text":" indicates a 4-channel, 8-bit-per-channel pixel buffer that contains image data such as RGBA or CMYK."}]},{"type":"paragraph","inlineContent":[{"text":"Pixel buffers expose methods that are available for the buffer’s pixel format. For example, the fast box convolution functions are only available for one- and four-channel 8-bit per channel buffers:","type":"text"}]},{"syntax":"swift","type":"codeListing","code":[" let src = vImage.PixelBuffer<vImage.Interleaved8x4>(cgImage: cgImage,","                                                     cgImageFormat: &cgImageFormat)"," let dest = vImage.PixelBuffer<vImage.Interleaved8x4>(src.size)",""," src.boxConvolve(kernelSize: vImage.Size(width: 64, height: 64),","                 edgeMode: .truncateKernel,","                 destination: dest)"]},{"type":"paragraph","inlineContent":[{"text":"Typed pixel buffers provide a simple API to convert between pixel formats. For example, the following code converts 8-bit unsigned integer pixels to 32-bit floating point pixels:","type":"text"}]},{"syntax":"swift","type":"codeListing","code":[" let src = vImage.PixelBuffer<vImage.Interleaved8x4>(cgImage: cgImage,","                                                     cgImageFormat: &cgImageFormat)"," let dest = vImage.PixelBuffer<vImage.InterleavedFx4>(size: src.size)",""," src.convert(to: dest)"]},{"type":"paragraph","inlineContent":[{"text":"vImage pixel buffers manage their memory, therefore, you don’t need to call ","type":"text"},{"identifier":"doc://com.apple.documentation/documentation/Swift/UnsafeMutableRawPointer/deallocate()","isActive":true,"type":"reference"},{"text":" when you’re finished with the buffer.","type":"text"}]}]}],"seeAlsoSections":[{"identifiers":["doc://com.apple.accelerate/documentation/Accelerate/using-vimage-pixel-buffers-to-generate-video-effects","doc://com.apple.accelerate/documentation/Accelerate/applying-tone-curve-adjustments-to-images","doc://com.apple.accelerate/documentation/Accelerate/adjusting-the-brightness-and-contrast-of-an-image","doc://com.apple.accelerate/documentation/Accelerate/adjusting-the-hue-of-an-image","doc://com.apple.accelerate/documentation/Accelerate/sharing-texture-data-between-the-model-io-framework-and-the-vimage-library","doc://com.apple.accelerate/documentation/Accelerate/calculating-the-dominant-colors-in-an-image"],"generated":true,"anchor":"vImage-Pixel-Buffers","title":"vImage Pixel Buffers"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer"},"metadata":{"symbolKind":"struct","navigatorTitle":[{"kind":"identifier","text":"PixelBuffer"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PixelBuffer"}],"title":"vImage.PixelBuffer","extendedModule":"Accelerate","role":"symbol","externalID":"s:10Accelerate6vImageO11PixelBufferV","roleHeading":"Structure","modules":[{"name":"Accelerate"}],"platforms":[{"beta":false,"name":"iOS","introducedAt":"16.0","deprecated":false,"unavailable":false},{"beta":false,"name":"iPadOS","introducedAt":"16.0","deprecated":false,"unavailable":false},{"beta":false,"name":"Mac Catalyst","deprecated":false,"unavailable":false},{"beta":false,"name":"macOS","introducedAt":"13.0","deprecated":false,"unavailable":false},{"beta":false,"name":"tvOS","introducedAt":"16.0","deprecated":false,"unavailable":false},{"beta":false,"name":"visionOS","deprecated":false,"unavailable":false},{"beta":false,"name":"watchOS","introducedAt":"9.0","deprecated":false,"unavailable":false}]},"sections":[],"abstract":[{"type":"text","text":"An image buffer that stores an image’s pixel data, dimensions, bit depth, and number of channels."}],"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.accelerate/documentation/Accelerate","doc://com.apple.accelerate/documentation/Accelerate/vImage"]]},"topicSections":[{"identifiers":["doc://com.apple.accelerate/documentation/Accelerate/creating-vimage-pixel-buffers","doc://com.apple.accelerate/documentation/Accelerate/pixel-formats","doc://com.apple.accelerate/documentation/Accelerate/working-with-underlying-data"],"anchor":"Pixel-buffer-essentials","title":"Pixel buffer essentials"},{"identifiers":["doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/width","doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/height","doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/size","doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/channelCount","doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/rowStride","doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/byteCountPerPixel","doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/count","doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/array"],"anchor":"Inspecting-a-pixel-buffer","title":"Inspecting a pixel buffer"},{"identifiers":["doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/copy(to:)","doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/copy(to:cvImageFormat:cgImageFormat:)","doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/makeCGImage(cgImageFormat:)","doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/withCVPixelBuffer(readOnly:body:)"],"anchor":"Pixel-buffer-methods","title":"Pixel buffer methods"},{"identifiers":["doc://com.apple.accelerate/documentation/Accelerate/applying-geometric-operations-to-pixel-buffers","doc://com.apple.accelerate/documentation/Accelerate/applying-color-transforms-to-pixel-buffers","doc://com.apple.accelerate/documentation/Accelerate/blending-and-compositing-pixel-buffers","doc://com.apple.accelerate/documentation/Accelerate/convolving-and-applying-morphology","doc://com.apple.accelerate/documentation/Accelerate/thresholding-and-clipping-pixel-buffer-values","doc://com.apple.accelerate/documentation/Accelerate/calculating-and-transforming-histograms","doc://com.apple.accelerate/documentation/Accelerate/converting-pixel-buffers","doc://com.apple.accelerate/documentation/Accelerate/interleaving-and-deinterleaving-pixel-buffers","doc://com.apple.accelerate/documentation/Accelerate/cropping-and-working-with-regions-of-interest","doc://com.apple.accelerate/documentation/Accelerate/applying-channel-operations","doc://com.apple.accelerate/documentation/Accelerate/applying-arithmetic-operations"],"anchor":"Pixel-buffer-operations","title":"Pixel buffer operations"},{"identifiers":["doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/applyLookup(_:destination:)-3yi7i","doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/applyLookup(_:destination:)-6498m","doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/applyLookup(_:destination:)-715aw","doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/applyMorphology(operation:destination:)-1aqer","doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/applyMorphology(operation:destination:)-5al25","doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/convolve(with:bias:edgeMode:destination:)-7no5n","doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/separableConvolve(horizontalKernel:verticalKernel:bias:edgeMode:destination:)-15dhm"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"},{"identifiers":["doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/AccelerateBuffer-Implementations","doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/AccelerateMatrixBuffer-Implementations","doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/AccelerateMutableMatrixBuffer-Implementations"],"generated":true,"anchor":"Default-Implementations","title":"Default Implementations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/accelerate/vimage/pixelbuffer"]}],"references":{"doc://com.apple.accelerate/documentation/Accelerate/using-vimage-pixel-buffers-to-generate-video-effects":{"type":"topic","kind":"article","role":"sampleCode","abstract":[{"text":"Render real-time video effects with the vImage Pixel Buffer.","type":"text"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/using-vimage-pixel-buffers-to-generate-video-effects","title":"Using vImage pixel buffers to generate video effects","url":"/documentation/accelerate/using-vimage-pixel-buffers-to-generate-video-effects"},"doc://com.apple.accelerate/documentation/Accelerate/optimizing-image-processing-performance":{"url":"/documentation/accelerate/optimizing-image-processing-performance","kind":"article","identifier":"doc://com.apple.accelerate/documentation/Accelerate/optimizing-image-processing-performance","role":"article","abstract":[{"type":"text","text":"Improve your app’s performance by converting image buffer formats from interleaved to planar."}],"type":"topic","title":"Optimizing image-processing performance"},"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/byteCountPerPixel":{"conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"code":"Format","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"StaticPixelFormat","type":"codeVoice"},{"text":".","type":"text"}]},"abstract":[{"text":"Returns the number of bytes per pixel.","type":"text"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/byteCountPerPixel","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"byteCountPerPixel","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"role":"symbol","url":"/documentation/accelerate/vimage/pixelbuffer/bytecountperpixel","kind":"symbol","title":"byteCountPerPixel"},"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/width":{"title":"width","role":"symbol","type":"topic","abstract":[{"text":"The width of the pixel buffer.","type":"text"}],"kind":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/width","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"width","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"url":"/documentation/accelerate/vimage/pixelbuffer/width"},"doc://com.apple.accelerate/documentation/Accelerate/applying-channel-operations":{"type":"topic","abstract":[{"type":"text","text":"Extract, flatten, permute, and overwrite the individual color channels of a pixel buffer."}],"title":"Applying channel operations","kind":"article","url":"/documentation/accelerate/applying-channel-operations","role":"collectionGroup","identifier":"doc://com.apple.accelerate/documentation/Accelerate/applying-channel-operations"},"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/rowStride":{"title":"rowStride","role":"symbol","type":"topic","abstract":[{"text":"The width, in pixels, of the underlying memory, including any additional row byte padding.","type":"text"}],"kind":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/rowStride","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rowStride","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"conformance":{"constraints":[{"code":"Format","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"StaticPixelFormat","type":"codeVoice"},{"text":".","type":"text"}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}]},"url":"/documentation/accelerate/vimage/pixelbuffer/rowstride"},"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/size":{"title":"size","role":"symbol","type":"topic","abstract":[{"text":"The size of the pixel buffer.","type":"text"}],"kind":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/size","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"size","kind":"identifier"},{"text":": ","kind":"text"},{"text":"vImage","preciseIdentifier":"s:10Accelerate6vImageO","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Size","preciseIdentifier":"s:10Accelerate6vImageO4SizeV","kind":"typeIdentifier"}],"url":"/documentation/accelerate/vimage/pixelbuffer/size"},"doc://com.apple.accelerate/documentation/Accelerate/cropping-and-working-with-regions-of-interest":{"kind":"article","url":"/documentation/accelerate/cropping-and-working-with-regions-of-interest","identifier":"doc://com.apple.accelerate/documentation/Accelerate/cropping-and-working-with-regions-of-interest","title":"Cropping and working with regions of interest","type":"topic","role":"collectionGroup","abstract":[{"text":"Crop images and apply operations to regions of interest.","type":"text"}]},"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer":{"type":"topic","abstract":[{"type":"text","text":"An image buffer that stores an image’s pixel data, dimensions, bit depth, and number of channels."}],"role":"symbol","url":"/documentation/accelerate/vimage/pixelbuffer","title":"vImage.PixelBuffer","navigatorTitle":[{"kind":"identifier","text":"PixelBuffer"}],"kind":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PixelBuffer"}]},"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/height":{"title":"height","role":"symbol","type":"topic","abstract":[{"text":"The height of the pixel buffer.","type":"text"}],"kind":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/height","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"height","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"url":"/documentation/accelerate/vimage/pixelbuffer/height"},"doc://com.apple.accelerate/documentation/Accelerate/AccelerateMutableMatrixBuffer":{"navigatorTitle":[{"text":"AccelerateMutableMatrixBuffer","kind":"identifier"}],"abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AccelerateMutableMatrixBuffer","kind":"identifier"}],"title":"AccelerateMutableMatrixBuffer","type":"topic","role":"symbol","kind":"symbol","url":"/documentation/accelerate/acceleratemutablematrixbuffer","identifier":"doc://com.apple.accelerate/documentation/Accelerate/AccelerateMutableMatrixBuffer","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"code":"Format","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"StaticPixelFormat","type":"codeVoice"},{"type":"text","text":"."}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]}},"doc://com.apple.accelerate/documentation/Accelerate/applying-geometric-operations-to-pixel-buffers":{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/applying-geometric-operations-to-pixel-buffers","type":"topic","role":"collectionGroup","abstract":[{"type":"text","text":"Reflect, shear, rotate, scale, and apply affine transforms to image data."}],"kind":"article","title":"Applying geometric operations to pixel buffers","url":"/documentation/accelerate/applying-geometric-operations-to-pixel-buffers"},"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/applyMorphology(operation:destination:)-1aqer":{"abstract":[{"text":"Applies a morphology operation to the buffer.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applyMorphology","kind":"identifier"},{"text":"(","kind":"text"},{"text":"operation","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Accelerate6vImageO","text":"vImage","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:10Accelerate6vImageO19MorphologyOperationO","text":"MorphologyOperation","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Format"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:10Accelerate11PixelFormatP13ComponentTypeQa","text":"ComponentType"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"destination"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Accelerate6vImageO","text":"vImage"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:10Accelerate6vImageO11PixelBufferV","text":"PixelBuffer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Format"},{"kind":"text","text":">)"}],"title":"applyMorphology(operation:destination:)","type":"topic","role":"symbol","kind":"symbol","url":"/documentation/accelerate/vimage/pixelbuffer/applymorphology(operation:destination:)-1aqer","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/applyMorphology(operation:destination:)-1aqer","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"Format"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"MultiplePlanePixelFormat"},{"type":"text","text":", "},{"type":"codeVoice","code":"Format.ComponentType"},{"type":"text","text":" is "},{"type":"codeVoice","code":"Float"},{"type":"text","text":", and "},{"type":"codeVoice","code":"Format.PlanarPixelFormat.ComponentType"},{"type":"text","text":" is "},{"type":"codeVoice","code":"Float"},{"type":"text","text":"."}]}},"doc://com.apple.accelerate/documentation/Accelerate/vImage":{"abstract":[{"type":"text","text":"An enumeration that acts as a namespace for Swift overlays to vImage."}],"navigatorTitle":[{"text":"vImage","kind":"identifier"}],"title":"vImage","type":"topic","kind":"symbol","url":"/documentation/accelerate/vimage","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"vImage","kind":"identifier"}]},"doc://com.apple.documentation/documentation/CoreVideo/CVPixelBuffer":{"kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CVPixelBuffer"},{"text":" = ","kind":"text"},{"text":"CVImageBuffer","kind":"typeIdentifier","preciseIdentifier":"c:@T@CVImageBufferRef"}],"type":"topic","identifier":"doc://com.apple.documentation/documentation/CoreVideo/CVPixelBuffer","url":"/documentation/CoreVideo/CVPixelBuffer","abstract":[{"text":"A reference to a Core Video pixel buffer object.","type":"text"}],"role":"symbol","title":"CVPixelBuffer"},"doc://com.apple.accelerate/documentation/Accelerate":{"abstract":[{"text":"Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.","type":"text"}],"type":"topic","title":"Accelerate","identifier":"doc://com.apple.accelerate/documentation/Accelerate","kind":"symbol","url":"/documentation/accelerate","role":"collection"},"doc://com.apple.accelerate/documentation/Accelerate/AccelerateMutableBuffer":{"navigatorTitle":[{"text":"AccelerateMutableBuffer","kind":"identifier"}],"abstract":[{"text":"A type that represents a mutable buffer.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AccelerateMutableBuffer","kind":"identifier"}],"title":"AccelerateMutableBuffer","type":"topic","role":"symbol","kind":"symbol","url":"/documentation/accelerate/acceleratemutablebuffer","identifier":"doc://com.apple.accelerate/documentation/Accelerate/AccelerateMutableBuffer","conformance":{"constraints":[{"type":"codeVoice","code":"Format"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"StaticPixelFormat"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]}},"doc://com.apple.accelerate/documentation/Accelerate/AccelerateMatrixBuffer":{"navigatorTitle":[{"text":"AccelerateMatrixBuffer","kind":"identifier"}],"abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AccelerateMatrixBuffer","kind":"identifier"}],"title":"AccelerateMatrixBuffer","type":"topic","role":"symbol","kind":"symbol","url":"/documentation/accelerate/acceleratematrixbuffer","identifier":"doc://com.apple.accelerate/documentation/Accelerate/AccelerateMatrixBuffer","conformance":{"constraints":[{"type":"codeVoice","code":"Format"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"StaticPixelFormat"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]}},"doc://com.apple.accelerate/documentation/Accelerate/convolving-and-applying-morphology":{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/convolving-and-applying-morphology","type":"topic","role":"collectionGroup","abstract":[{"type":"text","text":"Apply convolution, dilation, or erosion to a pixel buffer."}],"kind":"article","title":"Convolving and applying morphology","url":"/documentation/accelerate/convolving-and-applying-morphology"},"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/convolve(with:bias:edgeMode:destination:)-7no5n":{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/convolve(with:bias:edgeMode:destination:)-7no5n","title":"convolve(with:bias:edgeMode:destination:)","url":"/documentation/accelerate/vimage/pixelbuffer/convolve(with:bias:edgemode:destination:)-7no5n","abstract":[],"role":"symbol","conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}],"constraints":[{"code":"Format","type":"codeVoice"},{"text":" is ","type":"text"},{"code":"vImage.Interleaved8x4","type":"codeVoice"},{"text":".","type":"text"}]},"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"convolve"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"vImage","preciseIdentifier":"s:10Accelerate6vImageO"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ConvolutionKernel2D","preciseIdentifier":"s:10Accelerate6vImageO19ConvolutionKernel2DV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"bias"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"edgeMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"vImage","preciseIdentifier":"s:10Accelerate6vImageO"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"EdgeMode","preciseIdentifier":"s:10Accelerate6vImageO8EdgeModeO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Pixel_8888","preciseIdentifier":"c:@T@Pixel_8888"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"destination"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"vImage","preciseIdentifier":"s:10Accelerate6vImageO"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"PixelBuffer","preciseIdentifier":"s:10Accelerate6vImageO11PixelBufferV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Format"},{"kind":"text","text":">)"}]},"doc://com.apple.accelerate/documentation/Accelerate/converting-chroma-subsampled-images":{"title":"Converting chroma-subsampled images","identifier":"doc://com.apple.accelerate/documentation/Accelerate/converting-chroma-subsampled-images","role":"article","kind":"article","url":"/documentation/accelerate/converting-chroma-subsampled-images","abstract":[{"text":"Create vImage buffers with the correct dimensions to convert to and from images with subsampled chroma information.","type":"text"}],"type":"topic"},"doc://com.apple.accelerate/documentation/Accelerate/adjusting-the-brightness-and-contrast-of-an-image":{"type":"topic","title":"Adjusting the brightness and contrast of an image","role":"sampleCode","kind":"article","identifier":"doc://com.apple.accelerate/documentation/Accelerate/adjusting-the-brightness-and-contrast-of-an-image","abstract":[{"type":"text","text":"Use a gamma function to apply a linear or exponential curve."}],"url":"/documentation/accelerate/adjusting-the-brightness-and-contrast-of-an-image"},"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/separableConvolve(horizontalKernel:verticalKernel:bias:edgeMode:destination:)-15dhm":{"url":"/documentation/accelerate/vimage/pixelbuffer/separableconvolve(horizontalkernel:verticalkernel:bias:edgemode:destination:)-15dhm","abstract":[],"type":"topic","kind":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/separableConvolve(horizontalKernel:verticalKernel:bias:edgeMode:destination:)-15dhm","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"separableConvolve"},{"kind":"text","text":"("},{"kind":"externalParam","text":"horizontalKernel"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"verticalKernel"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"bias"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"},{"kind":"text","text":", "},{"kind":"externalParam","text":"edgeMode"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Accelerate6vImageO","kind":"typeIdentifier","text":"vImage"},{"kind":"text","text":"."},{"preciseIdentifier":"s:10Accelerate6vImageO8EdgeModeO","kind":"typeIdentifier","text":"EdgeMode"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@T@Pixel_8888","kind":"typeIdentifier","text":"Pixel_8888"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"destination"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Accelerate6vImageO","kind":"typeIdentifier","text":"vImage"},{"kind":"text","text":"."},{"preciseIdentifier":"s:10Accelerate6vImageO11PixelBufferV","kind":"typeIdentifier","text":"PixelBuffer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Format"},{"kind":"text","text":">)"}],"conformance":{"constraints":[{"type":"codeVoice","code":"Format"},{"type":"text","text":" is "},{"type":"codeVoice","code":"vImage.Interleaved8x4"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"title":"separableConvolve(horizontalKernel:verticalKernel:bias:edgeMode:destination:)"},"doc://com.apple.accelerate/documentation/Accelerate/building-a-basic-image-conversion-workflow":{"url":"/documentation/accelerate/building-a-basic-image-conversion-workflow","type":"topic","role":"article","title":"Building a basic image conversion workflow","kind":"article","abstract":[{"text":"Learn the fundamentals of the convert-any-to-any function by converting a CMYK image to an RGB image.","type":"text"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/building-a-basic-image-conversion-workflow"},"doc://com.apple.accelerate/documentation/Accelerate/thresholding-and-clipping-pixel-buffer-values":{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/thresholding-and-clipping-pixel-buffer-values","type":"topic","role":"collectionGroup","abstract":[{"type":"text","text":"Limit the values in a pixel buffer to a threshold or a range."}],"kind":"article","title":"Thresholding and clipping pixel buffer values","url":"/documentation/accelerate/thresholding-and-clipping-pixel-buffer-values"},"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/applyLookup(_:destination:)-3yi7i":{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/applyLookup(_:destination:)-3yi7i","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applyLookup","kind":"identifier"},{"text":"([","kind":"text"},{"text":"Pixel_16U","preciseIdentifier":"c:@T@Pixel_16U","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"destination","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"vImage","preciseIdentifier":"s:10Accelerate6vImageO","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"PixelBuffer","preciseIdentifier":"s:10Accelerate6vImageO11PixelBufferV","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"vImage","preciseIdentifier":"s:10Accelerate6vImageO","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Planar16U","preciseIdentifier":"s:10Accelerate6vImageO9Planar16UV","kind":"typeIdentifier"},{"text":">)","kind":"text"}],"role":"symbol","kind":"symbol","type":"topic","url":"/documentation/accelerate/vimage/pixelbuffer/applylookup(_:destination:)-3yi7i","conformance":{"constraints":[{"code":"Format","type":"codeVoice"},{"text":" is ","type":"text"},{"code":"vImage.Planar8","type":"codeVoice"},{"text":".","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}]},"title":"applyLookup(_:destination:)"},"doc://com.apple.accelerate/documentation/Accelerate/creating-vimage-pixel-buffers":{"url":"/documentation/accelerate/creating-vimage-pixel-buffers","role":"collectionGroup","kind":"article","type":"topic","title":"Creating vImage pixel buffers","identifier":"doc://com.apple.accelerate/documentation/Accelerate/creating-vimage-pixel-buffers","abstract":[{"text":"Allocate and initialize pixel buffers from raw pixel data, Core Graphics images, and Core Video buffers.","type":"text"}]},"doc://com.apple.accelerate/documentation/Accelerate/AccelerateBuffer":{"navigatorTitle":[{"text":"AccelerateBuffer","kind":"identifier"}],"abstract":[{"text":"A type that represents an immutable buffer.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AccelerateBuffer","kind":"identifier"}],"title":"AccelerateBuffer","type":"topic","role":"symbol","kind":"symbol","url":"/documentation/accelerate/acceleratebuffer","identifier":"doc://com.apple.accelerate/documentation/Accelerate/AccelerateBuffer","conformance":{"constraints":[{"type":"codeVoice","code":"Format"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"StaticPixelFormat"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]}},"doc://com.apple.accelerate/documentation/Accelerate/applying-tone-curve-adjustments-to-images":{"role":"sampleCode","identifier":"doc://com.apple.accelerate/documentation/Accelerate/applying-tone-curve-adjustments-to-images","abstract":[{"type":"text","text":"Use the vImage library’s polynomial transform to apply tone curve adjustments to images."}],"url":"/documentation/accelerate/applying-tone-curve-adjustments-to-images","kind":"article","type":"topic","title":"Applying tone curve adjustments to images"},"doc://com.apple.accelerate/documentation/Accelerate/pixel-formats":{"kind":"article","abstract":[{"text":"Specify a pixel buffer’s bit depth, number of channels, and data storage format.","type":"text"}],"role":"collectionGroup","title":"Pixel formats","url":"/documentation/accelerate/pixel-formats","type":"topic","identifier":"doc://com.apple.accelerate/documentation/Accelerate/pixel-formats"},"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/channelCount":{"title":"channelCount","role":"symbol","type":"topic","abstract":[{"text":"Returns the number of channels.","type":"text"}],"kind":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/channelCount","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"channelCount","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"conformance":{"constraints":[{"code":"Format","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"StaticPixelFormat","type":"codeVoice"},{"text":".","type":"text"}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}]},"url":"/documentation/accelerate/vimage/pixelbuffer/channelcount"},"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/array":{"conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"type":"codeVoice","code":"Format"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"StaticPixelFormat"},{"type":"text","text":"."}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"abstract":[{"text":"An array of ","type":"text"},{"type":"codeVoice","code":"width * height * channelCount"},{"text":" values that’s a copy of the buffer’s visible contents.","type":"text"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/array","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"array","kind":"identifier"},{"text":": [","kind":"text"},{"text":"Format","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"ComponentType","kind":"typeIdentifier","preciseIdentifier":"s:10Accelerate11PixelFormatP13ComponentTypeQa"},{"text":"]","kind":"text"}],"role":"symbol","url":"/documentation/accelerate/vimage/pixelbuffer/array","kind":"symbol","title":"array"},"doc://com.apple.accelerate/documentation/Accelerate/applying-vimage-operations-to-regions-of-interest":{"role":"article","type":"topic","url":"/documentation/accelerate/applying-vimage-operations-to-regions-of-interest","identifier":"doc://com.apple.accelerate/documentation/Accelerate/applying-vimage-operations-to-regions-of-interest","kind":"article","abstract":[{"text":"Limit the effect of vImage operations to rectangular regions of interest.","type":"text"}],"title":"Applying vImage operations to regions of interest"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","kind":"technologies","url":"/documentation/technologies","abstract":[{"text":"","type":"text"}],"type":"topic"},"doc://com.apple.accelerate/documentation/Accelerate/applying-color-transforms-to-images-with-a-multidimensional-lookup-table":{"url":"/documentation/accelerate/applying-color-transforms-to-images-with-a-multidimensional-lookup-table","kind":"article","role":"article","abstract":[{"type":"text","text":"Precompute translation values to optimize color space conversion and other pointwise operations."}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/applying-color-transforms-to-images-with-a-multidimensional-lookup-table","title":"Applying color transforms to images with a multidimensional lookup table","type":"topic"},"doc://com.apple.documentation/documentation/coregraphics/cgimage":{"role":"symbol","identifier":"doc://com.apple.documentation/documentation/coregraphics/cgimage","type":"topic","url":"/documentation/coregraphics/cgimage","fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"CGImage"}],"abstract":[{"text":"A bitmap image or image mask.","type":"text"}],"title":"CGImage","kind":"symbol"},"doc://com.apple.accelerate/documentation/Accelerate/applying-arithmetic-operations":{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/applying-arithmetic-operations","url":"/documentation/accelerate/applying-arithmetic-operations","type":"topic","title":"Applying arithmetic operations","abstract":[{"type":"text","text":"Multiply the pixel values of a buffer by scalar values or matrices."}],"role":"collectionGroup","kind":"article"},"doc://com.apple.accelerate/documentation/Accelerate/applying-color-transforms-to-pixel-buffers":{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/applying-color-transforms-to-pixel-buffers","url":"/documentation/accelerate/applying-color-transforms-to-pixel-buffers","type":"topic","title":"Applying color transforms to pixel buffers","abstract":[{"type":"text","text":"Adjust the colors of an image by applying gamma, polynomials, or multidimensional lookup."}],"role":"collectionGroup","kind":"article"},"doc://com.apple.accelerate/documentation/Accelerate/converting-bitmap-data-between-core-graphics-images-and-vimage-buffers":{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/converting-bitmap-data-between-core-graphics-images-and-vimage-buffers","role":"article","kind":"article","abstract":[{"text":"Pass image data between Core Graphics and vImage to create and manipulate images.","type":"text"}],"title":"Converting bitmap data between Core Graphics images and vImage buffers","url":"/documentation/accelerate/converting-bitmap-data-between-core-graphics-images-and-vimage-buffers","type":"topic"},"doc://com.apple.accelerate/documentation/Accelerate/vImage/Interleaved8x4":{"abstract":[{"text":"A four-channel, 8-bit-per-channel interleaved buffer.","type":"text"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Interleaved8x4","kind":"identifier"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage/Interleaved8x4","kind":"symbol","navigatorTitle":[{"text":"Interleaved8x4","kind":"identifier"}],"type":"topic","url":"/documentation/accelerate/vimage/interleaved8x4","title":"vImage.Interleaved8x4"},"doc://com.externally.resolved.symbol/s:s8CopyableP":{"abstract":[{"type":"text","text":"A type whose values can be implicitly or explicitly copied."}],"title":"Copyable","type":"topic","kind":"symbol","url":"/documentation/Swift/Copyable","identifier":"doc://com.externally.resolved.symbol/s:s8CopyableP","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Copyable"}]},"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/withCVPixelBuffer(readOnly:body:)":{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/withCVPixelBuffer(readOnly:body:)","title":"withCVPixelBuffer(readOnly:body:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"withCVPixelBuffer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"readOnly","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"body","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:@T@CVPixelBufferRef","text":"CVPixelBuffer","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"url":"/documentation/accelerate/vimage/pixelbuffer/withcvpixelbuffer(readonly:body:)","conformance":{"constraints":[{"type":"codeVoice","code":"Format"},{"type":"text","text":" is "},{"type":"codeVoice","code":"vImage.Interleaved8x4"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"kind":"symbol","abstract":[{"text":"Calls the given closure with a locked 32-bit BGRA Core Video Pixel Buffer.","type":"text"}],"role":"symbol"},"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/AccelerateMutableMatrixBuffer-Implementations":{"kind":"article","url":"/documentation/accelerate/vimage/pixelbuffer/acceleratemutablematrixbuffer-implementations","abstract":[],"title":"AccelerateMutableMatrixBuffer Implementations","type":"topic","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/AccelerateMutableMatrixBuffer-Implementations","role":"collectionGroup"},"doc://com.apple.documentation/documentation/Swift/UnsafeMutableRawPointer/deallocate()":{"kind":"symbol","url":"/documentation/Swift/UnsafeMutableRawPointer/deallocate()","abstract":[{"type":"text","text":"Deallocates the previously allocated memory block referenced by this pointer."}],"title":"deallocate()","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deallocate","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc://com.apple.documentation/documentation/Swift/UnsafeMutableRawPointer/deallocate()","role":"symbol"},"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/applyMorphology(operation:destination:)-5al25":{"abstract":[{"text":"Applies a morphology operation to the buffer.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"applyMorphology"},{"text":"(","kind":"text"},{"text":"operation","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Accelerate6vImageO","text":"vImage","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:10Accelerate6vImageO19MorphologyOperationO","text":"MorphologyOperation","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"Format"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ComponentType","preciseIdentifier":"s:10Accelerate11PixelFormatP13ComponentTypeQa"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"destination"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"vImage","preciseIdentifier":"s:10Accelerate6vImageO"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"PixelBuffer","preciseIdentifier":"s:10Accelerate6vImageO11PixelBufferV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Format"},{"kind":"text","text":">)"}],"title":"applyMorphology(operation:destination:)","type":"topic","role":"symbol","kind":"symbol","url":"/documentation/accelerate/vimage/pixelbuffer/applymorphology(operation:destination:)-5al25","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/applyMorphology(operation:destination:)-5al25","conformance":{"constraints":[{"code":"Format","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"MultiplePlanePixelFormat","type":"codeVoice"},{"type":"text","text":", "},{"code":"Format.ComponentType","type":"codeVoice"},{"type":"text","text":" is "},{"code":"UInt8","type":"codeVoice"},{"type":"text","text":", and "},{"code":"Format.PlanarPixelFormat.ComponentType","type":"codeVoice"},{"type":"text","text":" is "},{"code":"UInt8","type":"codeVoice"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]}},"doc://com.apple.accelerate/documentation/Accelerate/calculating-the-dominant-colors-in-an-image":{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/calculating-the-dominant-colors-in-an-image","kind":"article","role":"sampleCode","url":"/documentation/accelerate/calculating-the-dominant-colors-in-an-image","type":"topic","title":"Calculating the dominant colors in an image","abstract":[{"type":"text","text":"Find the main colors in an image by implementing k-means clustering using the Accelerate framework."}]},"doc://com.apple.accelerate/documentation/Accelerate/sharing-texture-data-between-the-model-io-framework-and-the-vimage-library":{"kind":"article","type":"topic","url":"/documentation/accelerate/sharing-texture-data-between-the-model-io-framework-and-the-vimage-library","title":"Sharing texture data between the Model I/O framework and the vImage library","role":"sampleCode","identifier":"doc://com.apple.accelerate/documentation/Accelerate/sharing-texture-data-between-the-model-io-framework-and-the-vimage-library","abstract":[{"type":"text","text":"Use Model I/O and vImage to composite a photograph over a"},{"text":" ","type":"text"},{"text":"computer-generated sky.","type":"text"}]},"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/applyLookup(_:destination:)-6498m":{"role":"symbol","url":"/documentation/accelerate/vimage/pixelbuffer/applylookup(_:destination:)-6498m","conformance":{"constraints":[{"code":"Format","type":"codeVoice"},{"type":"text","text":" is "},{"code":"vImage.PlanarF","type":"codeVoice"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/applyLookup(_:destination:)-6498m","title":"applyLookup(_:destination:)","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"applyLookup","kind":"identifier"},{"text":"([","kind":"text"},{"text":"Pixel_8","preciseIdentifier":"c:@T@Pixel_8","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"destination","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Accelerate6vImageO","text":"vImage","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:10Accelerate6vImageO11PixelBufferV","text":"PixelBuffer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"vImage","preciseIdentifier":"s:10Accelerate6vImageO"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Planar8","preciseIdentifier":"s:10Accelerate6vImageO7Planar8V"},{"kind":"text","text":">)"}],"type":"topic"},"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/makeCGImage(cgImageFormat:)":{"conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"code":"Format","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"StaticPixelFormat","type":"codeVoice"},{"type":"text","text":"."}]},"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"makeCGImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cgImageFormat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@vImage_CGImageFormat","text":"vImage_CGImageFormat"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CGImageRef","text":"CGImage"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Returns a Core Graphics image from the pixel buffer’s contents."}],"role":"symbol","type":"topic","url":"/documentation/accelerate/vimage/pixelbuffer/makecgimage(cgimageformat:)","kind":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/makeCGImage(cgImageFormat:)","title":"makeCGImage(cgImageFormat:)"},"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/count":{"conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"code":"Format","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"StaticPixelFormat","type":"codeVoice"},{"text":".","type":"text"}]},"abstract":[{"text":"The total number of pixels multiplied by the number of channels in the buffer, including any row padding.","type":"text"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/count","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"count","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"role":"symbol","url":"/documentation/accelerate/vimage/pixelbuffer/count","kind":"symbol","title":"count"},"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/copy(to:)":{"abstract":[{"text":"Copies the contents of the pixel buffer to another pixel buffer.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"copy"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Accelerate6vImageO","text":"vImage","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:10Accelerate6vImageO11PixelBufferV","text":"PixelBuffer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"Format"},{"kind":"text","text":">)"}],"title":"copy(to:)","type":"topic","role":"symbol","kind":"symbol","url":"/documentation/accelerate/vimage/pixelbuffer/copy(to:)","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/copy(to:)","conformance":{"constraints":[{"type":"codeVoice","code":"Format"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"StaticPixelFormat"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]}},"doc://com.apple.accelerate/documentation/Accelerate/enhancing-image-contrast-with-histogram-manipulation":{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/enhancing-image-contrast-with-histogram-manipulation","abstract":[{"text":"Enhance and adjust the contrast of an image with histogram equalization and contrast stretching.","type":"text"}],"title":"Enhancing image contrast with histogram manipulation","type":"topic","kind":"article","url":"/documentation/accelerate/enhancing-image-contrast-with-histogram-manipulation","role":"article"},"doc://com.apple.accelerate/documentation/Accelerate/working-with-underlying-data":{"abstract":[{"text":"Access a pixel buffer’s underlying pixel data.","type":"text"}],"role":"collectionGroup","title":"Working with underlying data","identifier":"doc://com.apple.accelerate/documentation/Accelerate/working-with-underlying-data","kind":"article","type":"topic","url":"/documentation/accelerate/working-with-underlying-data"},"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/applyLookup(_:destination:)-715aw":{"conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}],"constraints":[{"code":"Format","type":"codeVoice"},{"text":" is ","type":"text"},{"code":"vImage.Planar8","type":"codeVoice"},{"text":".","type":"text"}]},"url":"/documentation/accelerate/vimage/pixelbuffer/applylookup(_:destination:)-715aw","abstract":[],"type":"topic","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/applyLookup(_:destination:)-715aw","kind":"symbol","title":"applyLookup(_:destination:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applyLookup","kind":"identifier"},{"text":"([","kind":"text"},{"preciseIdentifier":"c:@T@Pixel_F","text":"Pixel_F","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"destination","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Accelerate6vImageO","text":"vImage","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:10Accelerate6vImageO11PixelBufferV","text":"PixelBuffer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:10Accelerate6vImageO","text":"vImage","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:10Accelerate6vImageO7PlanarFV","text":"PlanarF","kind":"typeIdentifier"},{"text":">)","kind":"text"}],"role":"symbol"},"doc://com.apple.accelerate/documentation/Accelerate/converting-pixel-buffers":{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/converting-pixel-buffers","url":"/documentation/accelerate/converting-pixel-buffers","type":"topic","title":"Converting pixel buffers","abstract":[{"type":"text","text":"Convert pixel buffer data between different bit-depths."}],"role":"collectionGroup","kind":"article"},"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/AccelerateBuffer-Implementations":{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/AccelerateBuffer-Implementations","title":"AccelerateBuffer Implementations","role":"collectionGroup","kind":"article","url":"/documentation/accelerate/vimage/pixelbuffer/acceleratebuffer-implementations","type":"topic","abstract":[]},"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/AccelerateMatrixBuffer-Implementations":{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/AccelerateMatrixBuffer-Implementations","title":"AccelerateMatrixBuffer Implementations","role":"collectionGroup","kind":"article","url":"/documentation/accelerate/vimage/pixelbuffer/acceleratematrixbuffer-implementations","type":"topic","abstract":[]},"doc://com.apple.accelerate/documentation/Accelerate/adjusting-the-hue-of-an-image":{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/adjusting-the-hue-of-an-image","type":"topic","role":"sampleCode","kind":"article","url":"/documentation/accelerate/adjusting-the-hue-of-an-image","abstract":[{"type":"text","text":"Convert an image to L*a*b* color space and apply hue adjustment."}],"title":"Adjusting the hue of an image"},"doc://com.apple.accelerate/documentation/Accelerate/blending-and-compositing-pixel-buffers":{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/blending-and-compositing-pixel-buffers","type":"topic","role":"collectionGroup","abstract":[{"text":"Composite two pixel buffers to create a single image.","type":"text"}],"kind":"article","title":"Blending and compositing pixel buffers","url":"/documentation/accelerate/blending-and-compositing-pixel-buffers"},"doc://com.apple.accelerate/documentation/Accelerate/calculating-and-transforming-histograms":{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/calculating-and-transforming-histograms","type":"topic","role":"collectionGroup","abstract":[{"text":"Enhance and adjust the contrast of an image with histogram equalization, contrast stretching, and specification.","type":"text"}],"kind":"article","title":"Calculating and transforming histograms","url":"/documentation/accelerate/calculating-and-transforming-histograms"},"doc://com.apple.accelerate/documentation/Accelerate/interleaving-and-deinterleaving-pixel-buffers":{"abstract":[{"type":"text","text":"Convert pixel buffer data between interleaved and planar formats."}],"role":"collectionGroup","type":"topic","url":"/documentation/accelerate/interleaving-and-deinterleaving-pixel-buffers","identifier":"doc://com.apple.accelerate/documentation/Accelerate/interleaving-and-deinterleaving-pixel-buffers","kind":"article","title":"Interleaving and deinterleaving pixel buffers"},"doc://com.apple.accelerate/documentation/Accelerate/PixelFormat":{"url":"/documentation/accelerate/pixelformat","navigatorTitle":[{"text":"PixelFormat","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PixelFormat","kind":"identifier"}],"abstract":[{"type":"text","text":"A pixel buffer pixel format."}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/PixelFormat","title":"PixelFormat","type":"topic"},"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/copy(to:cvImageFormat:cgImageFormat:)":{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/copy(to:cvImageFormat:cgImageFormat:)","title":"copy(to:cvImageFormat:cgImageFormat:)","role":"symbol","conformance":{"constraints":[{"code":"Format","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"SinglePlanePixelFormat","type":"codeVoice"},{"text":".","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}]},"kind":"symbol","url":"/documentation/accelerate/vimage/pixelbuffer/copy(to:cvimageformat:cgimageformat:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"copy","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CVPixelBufferRef","text":"CVPixelBuffer","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"cvImageFormat","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"vImageCVImageFormat","preciseIdentifier":"c:@T@vImageCVImageFormatRef"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cgImageFormat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"vImage_CGImageFormat","preciseIdentifier":"c:@S@vImage_CGImageFormat"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"type":"topic","abstract":[{"text":"Copies the contents of a pixel buffer to a Core Video pixel buffer.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"CVPixelBufferRef","path":"/references/doc:~1~1com.apple.documentation~1documentation~1CoreVideo~1CVPixelBuffer/title"},{"value":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CVImageBufferRef","text":"CVImageBufferRef"},{"kind":"text","text":" "},{"kind":"identifier","text":"CVPixelBufferRef"},{"kind":"text","text":";"}],"op":"replace","path":"/references/doc:~1~1com.apple.documentation~1documentation~1CoreVideo~1CVPixelBuffer/fragments"},{"op":"replace","value":"CGImageRef","path":"/references/doc:~1~1com.apple.documentation~1documentation~1coregraphics~1cgimage/title"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}