{
  "abstract": [
    {
      "text": "A tag indicating that the token is a determiner.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/determiner"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "NaturalLanguage",
    "externalID": "c:@NLTagDeterminer",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "determiner"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NLTag",
        "text": "NLTag"
      }
    ],
    "modules": [
      {
        "name": "Natural Language"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NLTagDeterminer"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "determiner"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "determiner"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NLTag",
              "text": "NLTag"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Determiners clarify nouns. Common determiners are articles (like ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "a",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "the",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": "), demonstratives (like ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "this",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "that",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": "), quantifiers (like ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "all",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "some",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": "), and possessives (like ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "your",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "their",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ").",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage": {
      "abstract": [
        {
          "text": "Analyze natural language text and deduce its language-specific metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage",
      "kind": "symbol",
      "role": "collection",
      "title": "Natural Language",
      "type": "topic",
      "url": "/documentation/naturallanguage"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag": {
      "abstract": [
        {
          "text": "A token type, lexical class, name, lemma, language, or script returned by a linguistic tagger for natural language text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NLTag"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTag"
        }
      ],
      "role": "symbol",
      "title": "NLTag",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltag"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/adjective": {
      "abstract": [
        {
          "text": "A tag indicating that the token is an adjective",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjective"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLTag",
          "text": "NLTag"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/adjective",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagAdjective"
        }
      ],
      "role": "symbol",
      "title": "adjective",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltag/adjective"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/adverb": {
      "abstract": [
        {
          "text": "A tag indicating that the token is an adverb.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adverb"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLTag",
          "text": "NLTag"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/adverb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagAdverb"
        }
      ],
      "role": "symbol",
      "title": "adverb",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltag/adverb"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/classifier": {
      "abstract": [
        {
          "text": "A tag indicating that the token is a classifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "classifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLTag",
          "text": "NLTag"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/classifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagClassifier"
        }
      ],
      "role": "symbol",
      "title": "classifier",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltag/classifier"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/conjunction": {
      "abstract": [
        {
          "text": "A tag indicating that the token is a conjunction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "conjunction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLTag",
          "text": "NLTag"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/conjunction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagConjunction"
        }
      ],
      "role": "symbol",
      "title": "conjunction",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltag/conjunction"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/determiner": {
      "abstract": [
        {
          "text": "A tag indicating that the token is a determiner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "determiner"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLTag",
          "text": "NLTag"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/determiner",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagDeterminer"
        }
      ],
      "role": "symbol",
      "title": "determiner",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltag/determiner"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/idiom": {
      "abstract": [
        {
          "text": "A tag indicating that the token is an idiom.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "idiom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLTag",
          "text": "NLTag"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/idiom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagIdiom"
        }
      ],
      "role": "symbol",
      "title": "idiom",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltag/idiom"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/interjection": {
      "abstract": [
        {
          "text": "A tag indicating that the token is an interjection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interjection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLTag",
          "text": "NLTag"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/interjection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagInterjection"
        }
      ],
      "role": "symbol",
      "title": "interjection",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltag/interjection"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/noun": {
      "abstract": [
        {
          "text": "A tag indicating that the token is a noun.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noun"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLTag",
          "text": "NLTag"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/noun",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagNoun"
        }
      ],
      "role": "symbol",
      "title": "noun",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltag/noun"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/number": {
      "abstract": [
        {
          "text": "A tag indicating that the token is a number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "number"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLTag",
          "text": "NLTag"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/number",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagNumber"
        }
      ],
      "role": "symbol",
      "title": "number",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltag/number"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/openQuote": {
      "abstract": [
        {
          "text": "A tag indicating that the token is an open quote.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "openQuote"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLTag",
          "text": "NLTag"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/openQuote",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagOpenQuote"
        }
      ],
      "role": "symbol",
      "title": "openQuote",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltag/openquote"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/otherWord": {
      "abstract": [
        {
          "text": "A tag indicating that the token is a word other than a kind described by other lexical classes (noun, verb, adjective, adverb, pronoun, determiner, particle, preposition, number, conjunction, interjection, classifier, and idiom).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "otherWord"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLTag",
          "text": "NLTag"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/otherWord",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagOtherWord"
        }
      ],
      "role": "symbol",
      "title": "otherWord",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltag/otherword"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/particle": {
      "abstract": [
        {
          "text": "A tag indicating that the token is a particle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "particle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLTag",
          "text": "NLTag"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/particle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagParticle"
        }
      ],
      "role": "symbol",
      "title": "particle",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltag/particle"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/preposition": {
      "abstract": [
        {
          "text": "A tag indicating that the token is a preposition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preposition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLTag",
          "text": "NLTag"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/preposition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagPreposition"
        }
      ],
      "role": "symbol",
      "title": "preposition",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltag/preposition"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/pronoun": {
      "abstract": [
        {
          "text": "A tag indicating that the token is a pronoun.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pronoun"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLTag",
          "text": "NLTag"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/pronoun",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagPronoun"
        }
      ],
      "role": "symbol",
      "title": "pronoun",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltag/pronoun"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/sentenceTerminator": {
      "abstract": [
        {
          "text": "A tag indicating that the token is punctuation at the end of a sentence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sentenceTerminator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLTag",
          "text": "NLTag"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/sentenceTerminator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagSentenceTerminator"
        }
      ],
      "role": "symbol",
      "title": "sentenceTerminator",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltag/sentenceterminator"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/verb": {
      "abstract": [
        {
          "text": "A tag indicating that the token is a verb.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "verb"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLTag",
          "text": "NLTag"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/verb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagVerb"
        }
      ],
      "role": "symbol",
      "title": "verb",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltag/verb"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Lexical-classes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/noun",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/verb",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/adjective",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/adverb",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/pronoun",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/particle",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/preposition",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/number",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/conjunction",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/interjection",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/classifier",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/idiom",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/otherWord",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/sentenceTerminator",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/openQuote"
      ],
      "title": "Lexical classes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NLTagDeterminer"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagDeterminer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Lexical-classes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/noun",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/verb",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/adjective",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/adverb",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/pronoun",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/particle",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/preposition",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/number",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/conjunction",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/interjection",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/classifier",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/idiom",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/otherWord",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/sentenceTerminator",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag/openQuote"
              ],
              "title": "Lexical classes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTag",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NLTag",
                    "text": "NLTag"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NLTagDeterminer"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1adverb/title",
          "value": "NLTagAdverb"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1adverb/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagAdverb"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1idiom/title",
          "value": "NLTagIdiom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1idiom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagIdiom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1verb/title",
          "value": "NLTagVerb"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1verb/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagVerb"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1sentenceTerminator/title",
          "value": "NLTagSentenceTerminator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1sentenceTerminator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagSentenceTerminator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1preposition/title",
          "value": "NLTagPreposition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1preposition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagPreposition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1openQuote/title",
          "value": "NLTagOpenQuote"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1openQuote/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagOpenQuote"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1pronoun/title",
          "value": "NLTagPronoun"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1pronoun/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagPronoun"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1otherWord/title",
          "value": "NLTagOtherWord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1otherWord/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagOtherWord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1particle/title",
          "value": "NLTagParticle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1particle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagParticle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1conjunction/title",
          "value": "NLTagConjunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1conjunction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagConjunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag/title",
          "value": "NLTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1adjective/title",
          "value": "NLTagAdjective"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1adjective/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagAdjective"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1classifier/title",
          "value": "NLTagClassifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1classifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagClassifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1interjection/title",
          "value": "NLTagInterjection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1interjection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagInterjection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1number/title",
          "value": "NLTagNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1number/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1determiner/title",
          "value": "NLTagDeterminer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1determiner/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagDeterminer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1noun/title",
          "value": "NLTagNoun"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTag~1noun/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagNoun"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/naturallanguage/nltag/determiner"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/naturallanguage/nltag/determiner"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
