{
  "abstract": [
    {
      "text": "Provides the framework with an existing AR session to use for Camera Assistance.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NISession"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NISession/setARSession(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NISession(im)setARSession:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "setARSession"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)ARSession",
        "text": "ARSession"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Nearby Interaction"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "setARSession:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "setARSession(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "setARSession"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "session"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)ARSession",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)ARSession",
              "text": "ARSession"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An existing AR session configured as follows:",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "items": [
                {
                  "content": [
                    {
                      "inlineContent": [
                        {
                          "text": "A world-tracking configuration (",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/ARKit/ARWorldTrackingConfiguration",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": ") with ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/ARKit/ARConfiguration/worldAlignment-swift.property",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " ",
                          "type": "text"
                        },
                        {
                          "code": "=",
                          "type": "codeVoice"
                        },
                        {
                          "text": " ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/ARKit/ARConfiguration/WorldAlignment-swift.enum/gravity",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": ", ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/ARKit/ARWorldTrackingConfiguration/isCollaborationEnabled",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " ",
                          "type": "text"
                        },
                        {
                          "code": "=",
                          "type": "codeVoice"
                        },
                        {
                          "text": " ",
                          "type": "text"
                        },
                        {
                          "code": "false",
                          "type": "codeVoice"
                        },
                        {
                          "text": ", ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/ARKit/ARWorldTrackingConfiguration/userFaceTrackingEnabled",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " ",
                          "type": "text"
                        },
                        {
                          "code": "=",
                          "type": "codeVoice"
                        },
                        {
                          "text": " ",
                          "type": "text"
                        },
                        {
                          "code": "false",
                          "type": "codeVoice"
                        },
                        {
                          "text": ", and ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/ARKit/ARWorldTrackingConfiguration/initialWorldMap",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " ",
                          "type": "text"
                        },
                        {
                          "code": "=",
                          "type": "codeVoice"
                        },
                        {
                          "text": " ",
                          "type": "text"
                        },
                        {
                          "code": "nil",
                          "type": "codeVoice"
                        },
                        {
                          "text": ".",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                },
                {
                  "content": [
                    {
                      "inlineContent": [
                        {
                          "text": "A delegate that returns ",
                          "type": "text"
                        },
                        {
                          "code": "false",
                          "type": "codeVoice"
                        },
                        {
                          "text": " for ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/ARKit/ARSessionObserver/sessionShouldAttemptRelocalization(_:)",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": ".",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                }
              ],
              "type": "unorderedList"
            }
          ],
          "name": "session"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Set the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyPeerConfiguration/isCameraAssistanceEnabled",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " flag to ",
              "type": "text"
            },
            {
              "code": "true",
              "type": "codeVoice"
            },
            {
              "text": " before calling this function. If you enable the flag and run a nearby-interaction session without calling ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NISession/setARSession(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", the framework creates an internal ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/ARKit/ARSession",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance to which the app has no access.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/ARKit/ARConfiguration/WorldAlignment-swift.enum/gravity": {
      "abstract": [
        {
          "text": "The coordinate system’s y-axis is parallel to gravity, and its origin is the initial position of the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gravity"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ARKit/ARConfiguration/WorldAlignment-swift.enum/gravity",
      "kind": "symbol",
      "role": "symbol",
      "title": "ARConfiguration.WorldAlignment.gravity",
      "type": "topic",
      "url": "/documentation/ARKit/ARConfiguration/WorldAlignment-swift.enum/gravity"
    },
    "doc://com.apple.documentation/documentation/ARKit/ARConfiguration/worldAlignment-swift.property": {
      "abstract": [
        {
          "text": "A value specifying how the session maps real-world device motion into a 3D scene coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "worldAlignment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARConfiguration",
          "text": "ARConfiguration"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ARWorldAlignment",
          "text": "WorldAlignment"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ARKit/ARConfiguration/worldAlignment-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "worldAlignment",
      "type": "topic",
      "url": "/documentation/ARKit/ARConfiguration/worldAlignment-swift.property"
    },
    "doc://com.apple.documentation/documentation/ARKit/ARSession": {
      "abstract": [
        {
          "text": "The object that manages the major tasks associated with every AR experience, such as motion tracking, camera passthrough, and image analysis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARSession"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ARKit/ARSession",
      "kind": "symbol",
      "role": "symbol",
      "title": "ARSession",
      "type": "topic",
      "url": "/documentation/ARKit/ARSession"
    },
    "doc://com.apple.documentation/documentation/ARKit/ARSessionObserver/sessionShouldAttemptRelocalization(_:)": {
      "abstract": [
        {
          "text": "Asks the delegate whether to attempt recovery of world-tracking state after an interruption.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "optional"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sessionShouldAttemptRelocalization"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "session"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARSession",
          "text": "ARSession"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ARKit/ARSessionObserver/sessionShouldAttemptRelocalization(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "sessionShouldAttemptRelocalization(_:)",
      "type": "topic",
      "url": "/documentation/ARKit/ARSessionObserver/sessionShouldAttemptRelocalization(_:)"
    },
    "doc://com.apple.documentation/documentation/ARKit/ARWorldTrackingConfiguration": {
      "abstract": [
        {
          "text": "A configuration that tracks the position of a device in relation to objects in the environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARWorldTrackingConfiguration"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ARKit/ARWorldTrackingConfiguration",
      "kind": "symbol",
      "role": "symbol",
      "title": "ARWorldTrackingConfiguration",
      "type": "topic",
      "url": "/documentation/ARKit/ARWorldTrackingConfiguration"
    },
    "doc://com.apple.documentation/documentation/ARKit/ARWorldTrackingConfiguration/initialWorldMap": {
      "abstract": [
        {
          "text": "The state from a previous AR session to attempt to resume with this session configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "initialWorldMap"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARWorldMap",
          "text": "ARWorldMap"
        },
        {
          "kind": "text",
          "text": "? { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ARKit/ARWorldTrackingConfiguration/initialWorldMap",
      "kind": "symbol",
      "role": "symbol",
      "title": "initialWorldMap",
      "type": "topic",
      "url": "/documentation/ARKit/ARWorldTrackingConfiguration/initialWorldMap"
    },
    "doc://com.apple.documentation/documentation/ARKit/ARWorldTrackingConfiguration/isCollaborationEnabled": {
      "abstract": [
        {
          "text": "A flag that opts you in to a peer-to-peer multiuser AR experience.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isCollaborationEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ARKit/ARWorldTrackingConfiguration/isCollaborationEnabled",
      "kind": "symbol",
      "role": "symbol",
      "title": "isCollaborationEnabled",
      "type": "topic",
      "url": "/documentation/ARKit/ARWorldTrackingConfiguration/isCollaborationEnabled"
    },
    "doc://com.apple.documentation/documentation/ARKit/ARWorldTrackingConfiguration/userFaceTrackingEnabled": {
      "abstract": [
        {
          "text": "A flag that determines whether ARKit tracks the user’s face in a world-tracking session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userFaceTrackingEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ARKit/ARWorldTrackingConfiguration/userFaceTrackingEnabled",
      "kind": "symbol",
      "role": "symbol",
      "title": "userFaceTrackingEnabled",
      "type": "topic",
      "url": "/documentation/ARKit/ARWorldTrackingConfiguration/userFaceTrackingEnabled"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction": {
      "abstract": [
        {
          "text": "Locate and interact with nearby devices using identifiers, distance, and direction.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction",
      "kind": "symbol",
      "role": "collection",
      "title": "Nearby Interaction",
      "type": "topic",
      "url": "/documentation/nearbyinteraction"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObjectWorldTransformNotAvailable": {
      "abstract": [
        {
          "text": "A constant that indicates that the framework is unable to provide a world transform for a nearby object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NINearbyObjectWorldTransformNotAvailable"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObjectWorldTransformNotAvailable",
      "kind": "symbol",
      "role": "symbol",
      "title": "NINearbyObjectWorldTransformNotAvailable",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/ninearbyobjectworldtransformnotavailable"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyPeerConfiguration/isCameraAssistanceEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that combines the spatial awareness of ARKit with Nearby Interaction to improve the accuracy of a nearby object’s position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isCameraAssistanceEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyPeerConfiguration/isCameraAssistanceEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cameraAssistanceEnabled"
        }
      ],
      "role": "symbol",
      "title": "isCameraAssistanceEnabled",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/ninearbypeerconfiguration/iscameraassistanceenabled"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NISession": {
      "abstract": [
        {
          "text": "An object that identifies a unique connection between two peer devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NISession"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NISession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NISession"
        }
      ],
      "role": "symbol",
      "title": "NISession",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nisession"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NISession/setARSession(_:)": {
      "abstract": [
        {
          "text": "Provides the framework with an existing AR session to use for Camera Assistance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setARSession"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARSession",
          "text": "ARSession"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NISession/setARSession(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setARSession:"
        }
      ],
      "role": "symbol",
      "title": "setARSession(_:)",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nisession/setarsession(_:)"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NISession/worldTransform(for:)": {
      "abstract": [
        {
          "text": "Returns a world transform to integrate a nearby object in an AR experience.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "worldTransform"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NINearbyObject",
          "text": "NINearbyObject"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float4x4",
          "text": "simd_float4x4"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NISession/worldTransform(for:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "worldTransform(for:)",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nisession/worldtransform(for:)"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NISession/worldTransformForObject:": {
      "abstract": [
        {
          "text": "Returns a world transform to integrate a nearby object in an AR experience.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "worldTransformForObject:"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NISession/worldTransformForObject:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "worldTransformForObject:"
        }
      ],
      "role": "symbol",
      "title": "worldTransformForObject:",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nisession/worldtransformforobject:"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)ARSession": {
      "abstract": [
        {
          "text": "The object that manages the major tasks associated with every AR experience, such as motion tracking, camera passthrough, and image analysis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARSession"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)ARSession",
      "kind": "symbol",
      "role": "symbol",
      "title": "ARSession",
      "type": "topic",
      "url": "/documentation/ARKit/ARSession"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Utilizing-Camera-Assistance",
      "generated": true,
      "identifiers": [
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NISession/worldTransform(for:)"
      ],
      "title": "Utilizing Camera Assistance"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "setARSession:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setARSession:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction",
                "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NISession"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Utilizing-Camera-Assistance",
              "generated": true,
              "identifiers": [
                "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NISession/worldTransformForObject:",
                "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObjectWorldTransformNotAvailable"
              ],
              "title": "Utilizing Camera Assistance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "setARSession:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)ARSession",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)ARSession",
                    "text": "ARSession"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "session"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An existing AR session configured as follows:",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "items": [
                      {
                        "content": [
                          {
                            "inlineContent": [
                              {
                                "text": "A world-tracking configuration (",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.documentation/documentation/ARKit/ARWorldTrackingConfiguration",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": ") with ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.documentation/documentation/ARKit/ARConfiguration/worldAlignment-swift.property",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " ",
                                "type": "text"
                              },
                              {
                                "code": "=",
                                "type": "codeVoice"
                              },
                              {
                                "text": " ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.documentation/documentation/ARKit/ARConfiguration/WorldAlignment-swift.enum/gravity",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": ", ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.documentation/documentation/ARKit/ARWorldTrackingConfiguration/isCollaborationEnabled",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " ",
                                "type": "text"
                              },
                              {
                                "code": "=",
                                "type": "codeVoice"
                              },
                              {
                                "text": " ",
                                "type": "text"
                              },
                              {
                                "code": "false",
                                "type": "codeVoice"
                              },
                              {
                                "text": ", ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.documentation/documentation/ARKit/ARWorldTrackingConfiguration/userFaceTrackingEnabled",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " ",
                                "type": "text"
                              },
                              {
                                "code": "=",
                                "type": "codeVoice"
                              },
                              {
                                "text": " ",
                                "type": "text"
                              },
                              {
                                "code": "false",
                                "type": "codeVoice"
                              },
                              {
                                "text": ", and ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.documentation/documentation/ARKit/ARWorldTrackingConfiguration/initialWorldMap",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " ",
                                "type": "text"
                              },
                              {
                                "code": "=",
                                "type": "codeVoice"
                              },
                              {
                                "text": " ",
                                "type": "text"
                              },
                              {
                                "code": "nil",
                                "type": "codeVoice"
                              },
                              {
                                "text": ".",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      },
                      {
                        "content": [
                          {
                            "inlineContent": [
                              {
                                "text": "A delegate that returns ",
                                "type": "text"
                              },
                              {
                                "code": "false",
                                "type": "codeVoice"
                              },
                              {
                                "text": " for ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.documentation/documentation/ARKit/ARSessionObserver/sessionShouldAttemptRelocalization(_:)",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": ".",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      }
                    ],
                    "type": "unorderedList"
                  }
                ],
                "name": "session"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ARKit~1ARSession/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ARSession"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)ARSession/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ARSession"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ARKit~1ARWorldTrackingConfiguration~1initialWorldMap/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "strong"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)ARWorldMap",
              "text": "ARWorldMap"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "initialWorldMap"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ARKit~1ARConfiguration~1worldAlignment-swift.property/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "assign"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@ARWorldAlignment",
              "text": "ARWorldAlignment"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "worldAlignment"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NISession~1setARSession(_:)/title",
          "value": "setARSession:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NISession~1setARSession(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setARSession:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NISession/title",
          "value": "NISession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NISession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NISession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NISession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NISession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ARKit~1ARConfiguration~1WorldAlignment-swift.enum~1gravity/title",
          "value": "ARWorldAlignmentGravity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ARKit~1ARConfiguration~1WorldAlignment-swift.enum~1gravity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARWorldAlignmentGravity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ARKit~1ARWorldTrackingConfiguration~1userFaceTrackingEnabled/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "assign"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "getter"
            },
            {
              "kind": "text",
              "text": "="
            },
            {
              "kind": "identifier",
              "text": "userFaceTrackingEnabled"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "userFaceTrackingEnabled"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ARKit~1ARSessionObserver~1sessionShouldAttemptRelocalization(_:)/title",
          "value": "sessionShouldAttemptRelocalization:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ARKit~1ARSessionObserver~1sessionShouldAttemptRelocalization(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "sessionShouldAttemptRelocalization:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)ARSession",
              "text": "ARSession"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "session"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ARKit~1ARWorldTrackingConfiguration/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ARWorldTrackingConfiguration"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)ARConfiguration",
              "text": "ARConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyPeerConfiguration~1isCameraAssistanceEnabled/title",
          "value": "cameraAssistanceEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyPeerConfiguration~1isCameraAssistanceEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cameraAssistanceEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ARKit~1ARWorldTrackingConfiguration~1isCollaborationEnabled/title",
          "value": "collaborationEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ARKit~1ARWorldTrackingConfiguration~1isCollaborationEnabled/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "assign"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "getter"
            },
            {
              "kind": "text",
              "text": "="
            },
            {
              "kind": "identifier",
              "text": "isCollaborationEnabled"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "collaborationEnabled"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/nearbyinteraction/nisession/setarsession(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/nearbyinteraction/nisession/setarsession(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
