{
  "abstract": [
    {
      "text": "Creates a new matrix with the specified matrix.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "This conversion is no longer necessary; use ",
          "type": "text"
        },
        {
          "code": "cmatrix",
          "type": "codeVoice"
        },
        {
          "text": " directly.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd",
        "doc://com.apple.accelerate/documentation/simd/simd_float3x3"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_float3x3/init(_:)-7ymye"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "simd",
    "externalID": "s:So13simd_float3x3a0A0EyA2Bcfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@simd_float3x3",
        "text": "simd_float3x3"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "4.0",
        "message": "This conversion is no longer necessary; use `cmatrix` directly.",
        "name": "Swift",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "cmatrix"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float3x3",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@simd_float3x3",
              "text": "simd_float3x3"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_determinant(_:)-2m4vm": {
      "abstract": [
        {
          "text": "Returns the determinant of the specified matrix.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matrix_determinant"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float3x3",
          "text": "simd_float3x3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_determinant(_:)-2m4vm",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_determinant(_:)",
      "type": "topic",
      "url": "/documentation/simd/matrix_determinant(_:)-2m4vm"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_equal(_:_:)-14gko": {
      "abstract": [
        {
          "text": "Returns true if every element in a matrix is exactly equal to the corresponding element in a second matrix, and otherwise returns false.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matrix_equal"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float3x3",
          "text": "simd_float3x3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float3x3",
          "text": "simd_float3x3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_equal(_:_:)-14gko",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_equal(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/matrix_equal(_:_:)-14gko"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_from_columns(_:_:_:)-4c7qb": {
      "abstract": [
        {
          "text": "Returns a new matrix with the specified columns.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matrix_from_columns"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD3V",
          "text": "SIMD3"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD3V",
          "text": "SIMD3"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD3V",
          "text": "SIMD3"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float3x3",
          "text": "simd_float3x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_from_columns(_:_:_:)-4c7qb",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_from_columns(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/matrix_from_columns(_:_:_:)-4c7qb"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_from_diagonal(_:)-61643": {
      "abstract": [
        {
          "text": "Returns a new matrix with the specified vector on the main diagonal.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matrix_from_diagonal"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD3V",
          "text": "SIMD3"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float3x3",
          "text": "simd_float3x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_from_diagonal(_:)-61643",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_from_diagonal(_:)",
      "type": "topic",
      "url": "/documentation/simd/matrix_from_diagonal(_:)-61643"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_invert(_:)-15kif": {
      "abstract": [
        {
          "text": "Returns the inverse of the specified matrix.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matrix_invert"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float3x3",
          "text": "simd_float3x3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float3x3",
          "text": "simd_float3x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_invert(_:)-15kif",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_invert(_:)",
      "type": "topic",
      "url": "/documentation/simd/matrix_invert(_:)-15kif"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_transpose(_:)-9pl1z": {
      "abstract": [
        {
          "text": "Returns the transpose of a matrix.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matrix_transpose"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float3x3",
          "text": "simd_float3x3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:4simd8float3x3a",
          "text": "float3x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_transpose(_:)-9pl1z",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_transpose(_:)",
      "type": "topic",
      "url": "/documentation/simd/matrix_transpose(_:)-9pl1z"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float3x3": {
      "abstract": [
        {
          "text": "A matrix of three columns and three rows that contains single-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_float3x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float3x3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_float3x3"
        }
      ],
      "role": "symbol",
      "title": "simd_float3x3",
      "type": "topic",
      "url": "/documentation/simd/simd_float3x3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float3x3/cmatrix": {
      "abstract": [
        {
          "text": "Returns the matrix as the corresponding C matrix type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cmatrix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float3x3",
          "text": "simd_float3x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float3x3/cmatrix",
      "kind": "symbol",
      "role": "symbol",
      "title": "cmatrix",
      "type": "topic",
      "url": "/documentation/simd/simd_float3x3/cmatrix"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_float3x3/init(_:)-7ymye": {
      "abstract": [
        {
          "text": "Creates a new matrix with the specified matrix.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_float3x3",
          "text": "simd_float3x3"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_float3x3/init(_:)-7ymye",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_float3x3/init(_:)-7ymye"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated-Symbols",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/matrix_invert(_:)-15kif",
        "doc://com.apple.accelerate/documentation/simd/matrix_from_diagonal(_:)-61643",
        "doc://com.apple.accelerate/documentation/simd/matrix_determinant(_:)-2m4vm",
        "doc://com.apple.accelerate/documentation/simd/matrix_equal(_:_:)-14gko",
        "doc://com.apple.accelerate/documentation/simd/matrix_from_columns(_:_:_:)-4c7qb",
        "doc://com.apple.accelerate/documentation/simd/matrix_transpose(_:)-9pl1z",
        "doc://com.apple.accelerate/documentation/simd/simd_float3x3/cmatrix"
      ],
      "title": "Deprecated Symbols"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float3x3/title",
          "value": "simd_float3x3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float3x3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float3x3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_float3x3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_float3x3"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_float3x3/init(_:)-7ymye"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
