{
  "abstract": [
    {
      "text": "Returns the database with the specified scope.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cloudkit/documentation/CloudKit",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer/database(with:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "CloudKit",
    "externalID": "c:objc(cs)CKContainer(im)databaseWithDatabaseScope:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "database"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "with"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CKDatabase",
        "text": "CKDatabase"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@CKDatabaseScope",
        "text": "Scope"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CKDatabase",
        "text": "CKDatabase"
      }
    ],
    "modules": [
      {
        "name": "CloudKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "databaseWithDatabaseScope:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "database(with:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "database"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "with"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "databaseScope"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabase",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CKDatabase",
              "text": "CKDatabase"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabase/Scope",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CKDatabaseScope",
              "text": "Scope"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabase",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CKDatabase",
              "text": "CKDatabase"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The database’s scope. See ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabase/Scope",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " for the available options.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "databaseScope"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.cloudkit/documentation/CloudKit": {
      "abstract": [
        {
          "text": "Store structured app and user data in iCloud containers that all users of your app can share.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CloudKit",
      "type": "topic",
      "url": "/documentation/cloudkit"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer": {
      "abstract": [
        {
          "text": "A conduit to your app’s databases.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKContainer"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKContainer"
        }
      ],
      "role": "symbol",
      "title": "CKContainer",
      "type": "topic",
      "url": "/documentation/cloudkit/ckcontainer"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer/database(with:)": {
      "abstract": [
        {
          "text": "Returns the database with the specified scope.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "database"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKDatabase",
          "text": "CKDatabase"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CKDatabaseScope",
          "text": "Scope"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKDatabase",
          "text": "CKDatabase"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer/database(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "databaseWithDatabaseScope:"
        }
      ],
      "role": "symbol",
      "title": "database(with:)",
      "type": "topic",
      "url": "/documentation/cloudkit/ckcontainer/database(with:)"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer/privateCloudDatabase": {
      "abstract": [
        {
          "text": "The user’s private database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "privateCloudDatabase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKDatabase",
          "text": "CKDatabase"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer/privateCloudDatabase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "privateCloudDatabase"
        }
      ],
      "role": "symbol",
      "title": "privateCloudDatabase",
      "type": "topic",
      "url": "/documentation/cloudkit/ckcontainer/privateclouddatabase"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer/publicCloudDatabase": {
      "abstract": [
        {
          "text": "The app’s public database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "publicCloudDatabase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKDatabase",
          "text": "CKDatabase"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer/publicCloudDatabase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "publicCloudDatabase"
        }
      ],
      "role": "symbol",
      "title": "publicCloudDatabase",
      "type": "topic",
      "url": "/documentation/cloudkit/ckcontainer/publicclouddatabase"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer/sharedCloudDatabase": {
      "abstract": [
        {
          "text": "The database that contains shared data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sharedCloudDatabase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKDatabase",
          "text": "CKDatabase"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer/sharedCloudDatabase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sharedCloudDatabase"
        }
      ],
      "role": "symbol",
      "title": "sharedCloudDatabase",
      "type": "topic",
      "url": "/documentation/cloudkit/ckcontainer/sharedclouddatabase"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabase": {
      "abstract": [
        {
          "text": "An object that represents a collection of record zones and subscriptions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKDatabase"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKDatabase"
        }
      ],
      "role": "symbol",
      "title": "CKDatabase",
      "type": "topic",
      "url": "/documentation/cloudkit/ckdatabase"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabase/Scope": {
      "abstract": [
        {
          "text": "Constants that represent the scope of a database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Scope"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabase/Scope",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Scope"
        }
      ],
      "role": "symbol",
      "title": "CKDatabase.Scope",
      "type": "topic",
      "url": "/documentation/cloudkit/ckdatabase/scope"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-Public-and-Private-Databases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer/privateCloudDatabase",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer/publicCloudDatabase",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer/sharedCloudDatabase"
      ],
      "title": "Getting the Public and Private Databases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "databaseWithDatabaseScope:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "databaseWithDatabaseScope:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.cloudkit/documentation/CloudKit",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-Public-and-Private-Databases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer/privateCloudDatabase",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer/publicCloudDatabase",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer/sharedCloudDatabase"
              ],
              "title": "Getting the Public and Private Databases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabase",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)CKDatabase",
                    "text": "CKDatabase"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "identifier",
                    "text": "databaseWithDatabaseScope:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabase/Scope",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@CKDatabaseScope",
                    "text": "CKDatabaseScope"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "databaseScope"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The database’s scope. See ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabase/Scope",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " for the available options.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "databaseScope"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKContainer~1privateCloudDatabase/title",
          "value": "privateCloudDatabase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKContainer~1privateCloudDatabase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "privateCloudDatabase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKContainer~1publicCloudDatabase/title",
          "value": "publicCloudDatabase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKContainer~1publicCloudDatabase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "publicCloudDatabase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKContainer~1sharedCloudDatabase/title",
          "value": "sharedCloudDatabase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKContainer~1sharedCloudDatabase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sharedCloudDatabase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKContainer~1database(with:)/title",
          "value": "databaseWithDatabaseScope:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKContainer~1database(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "databaseWithDatabaseScope:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKContainer/title",
          "value": "CKContainer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKContainer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKContainer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKDatabase/title",
          "value": "CKDatabase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKDatabase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKDatabase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKDatabase/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKDatabase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKDatabase~1Scope/title",
          "value": "CKDatabaseScope"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKDatabase~1Scope/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKDatabaseScope"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKDatabase~1Scope/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKDatabaseScope"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cloudkit/ckcontainer/database(with:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cloudkit/ckcontainer/database(with:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
