{
  "abstract": [
    {
      "text": "Tells the file provider extension that the set of pending items has changed.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.fileprovider/documentation/FileProvider",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderReplicatedExtension"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderReplicatedExtension/pendingItemsDidChange(completionHandler:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NSFileProviderReplicatedExtension(im)pendingItemsDidChangeWithCompletionHandler:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "pendingItemsDidChange"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "completionHandler"
      },
      {
        "kind": "text",
        "text": ": () -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s4Voida",
        "text": "Void"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "File Provider"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "pendingItemsDidChangeWithCompletionHandler:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.3",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "pendingItemsDidChange(completionHandler:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "pendingItemsDidChange"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "completionHandler"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "@escaping"
            },
            {
              "kind": "text",
              "text": " () -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        },
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "pendingItemsDidChange"
            },
            {
              "kind": "text",
              "text": "() "
            },
            {
              "kind": "keyword",
              "text": "async"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A block that you call after you finish processing the changes.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "completionHandler"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "You can implement this method as a synchronous method that takes a completion handler, as shown on this page, or as an asynchronous method that has the following declaration:",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "code": [
                "optional func pendingItemsDidChange() async"
              ],
              "syntax": "swift",
              "type": "codeListing"
            },
            {
              "inlineContent": [
                {
                  "text": "For information about concurrency and asynchronous code in Swift, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/Swift/calling-objective-c-apis-asynchronously",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "The system calls this method whenever the set of pending items changes. It updates the pending set regularly, but only when there are meaningful changes, such as:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "New items are now pending.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The system has successfully synced one or more pending items.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The domain version changed when the pending item set wasn’t empty.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "To enumerate the pending set, create an object that adopts the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderEnumerationObserver",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderChangeObserver",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocols. Then pass this item to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderManager/enumeratorForPendingItems()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method on a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderManager",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance for your domain. The system then calls your observer object’s methods when the pending set changes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Calls to the observer object may not happen immediately. Don’t use the pending set to detect changes.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Tip",
          "style": "tip",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/Swift/calling-objective-c-apis-asynchronously": {
      "abstract": [
        {
          "text": "Learn how functions and methods that take a completion handler are converted to Swift asynchronous functions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Swift/calling-objective-c-apis-asynchronously",
      "kind": "article",
      "role": "article",
      "title": "Calling Objective-C APIs Asynchronously",
      "type": "topic",
      "url": "/documentation/Swift/calling-objective-c-apis-asynchronously"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider": {
      "abstract": [
        {
          "text": "An extension other apps use to access files and folders managed by your app and synced with a remote storage.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider",
      "kind": "symbol",
      "role": "collection",
      "title": "File Provider",
      "type": "topic",
      "url": "/documentation/fileprovider"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderChangeObserver": {
      "abstract": [
        {
          "text": "An observer that receives changes and deletions during enumeration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderChangeObserver"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderChangeObserver",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderChangeObserver"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderChangeObserver",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileproviderchangeobserver"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderEnumerationObserver": {
      "abstract": [
        {
          "text": "An observer that receives batches of items during enumeration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderEnumerationObserver"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderEnumerationObserver",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderEnumerationObserver"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderEnumerationObserver",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileproviderenumerationobserver"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderManager": {
      "abstract": [
        {
          "text": "A manager object that you use to communicate with the file provider from either your app or your File Provider extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderManager"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderManager"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderManager",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidermanager"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderManager/enumeratorForPendingItems()": {
      "abstract": [
        {
          "text": "Returns an enumerator for the set of pending items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enumeratorForPendingItems"
        },
        {
          "kind": "text",
          "text": "() -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSFileProviderPendingSetEnumerator",
          "text": "NSFileProviderPendingSetEnumerator"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderManager/enumeratorForPendingItems()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enumeratorForPendingItems"
        }
      ],
      "role": "symbol",
      "title": "enumeratorForPendingItems()",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidermanager/enumeratorforpendingitems()"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderReplicatedExtension": {
      "abstract": [
        {
          "text": "A File Provider extension in which the system replicates the contents on disk.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderReplicatedExtension"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderReplicatedExtension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderReplicatedExtension"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderReplicatedExtension",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileproviderreplicatedextension"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderReplicatedExtension/pendingItemsDidChange(completionHandler:)": {
      "abstract": [
        {
          "text": "Tells the file provider extension that the set of pending items has changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pendingItemsDidChange"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": () -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderReplicatedExtension/pendingItemsDidChange(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pendingItemsDidChangeWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "pendingItemsDidChange(completionHandler:)",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileproviderreplicatedextension/pendingitemsdidchange(completionhandler:)"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.3",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "pendingItemsDidChangeWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pendingItemsDidChangeWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.fileprovider/documentation/FileProvider",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderReplicatedExtension"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "pendingItemsDidChangeWithCompletionHandler:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " (^)()) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "completionHandler"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A block that you call after you finish processing the changes.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "completionHandler"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderManager/title",
          "value": "NSFileProviderManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderReplicatedExtension/title",
          "value": "NSFileProviderReplicatedExtension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderReplicatedExtension/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderReplicatedExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderReplicatedExtension/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderReplicatedExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderEnumerationObserver/title",
          "value": "NSFileProviderEnumerationObserver"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderEnumerationObserver/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderEnumerationObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderEnumerationObserver/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderEnumerationObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderChangeObserver/title",
          "value": "NSFileProviderChangeObserver"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderChangeObserver/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderChangeObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderChangeObserver/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderChangeObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderReplicatedExtension~1pendingItemsDidChange(completionHandler:)/title",
          "value": "pendingItemsDidChangeWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderReplicatedExtension~1pendingItemsDidChange(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pendingItemsDidChangeWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderManager~1enumeratorForPendingItems()/title",
          "value": "enumeratorForPendingItems"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderManager~1enumeratorForPendingItems()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "enumeratorForPendingItems"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/fileprovider/nsfileproviderreplicatedextension/pendingitemsdidchange(completionhandler:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/fileprovider/nsfileproviderreplicatedextension/pendingitemsdidchange(completionhandler:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
