{
  "abstract": [
    {
      "text": "Constants that specify the color range of the image renderer context.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat/Range"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "UIKit",
    "externalID": "c:@E@UIGraphicsImageRendererFormatRange",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Range"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Range"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "UIGraphicsImageRendererFormat.Range"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Range"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat": {
      "abstract": [
        {
          "text": "A set of drawing attributes that represents the configuration of an image renderer context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsImageRendererFormat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsImageRendererFormat"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsImageRendererFormat",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsimagerendererformat"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat/Range": {
      "abstract": [
        {
          "text": "Constants that specify the color range of the image renderer context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Range"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat/Range",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Range"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsImageRendererFormat.Range",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsimagerendererformat/range"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat/Range/automatic": {
      "abstract": [
        {
          "text": "The system automatically chooses the image renderer context’s pixel format according to the color range of its content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automatic"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat/Range/automatic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsImageRendererFormatRangeAutomatic"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsImageRendererFormat.Range.automatic",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsimagerendererformat/range/automatic"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat/Range/extended": {
      "abstract": [
        {
          "text": "The image renderer context supports wide color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extended"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat/Range/extended",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsImageRendererFormatRangeExtended"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsImageRendererFormat.Range.extended",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsimagerendererformat/range/extended"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat/Range/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat/Range/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsimagerendererformat/range/init(rawvalue:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat/Range/standard": {
      "abstract": [
        {
          "text": "The image renderer context doesn’t support extended colors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "standard"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat/Range/standard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsImageRendererFormatRangeStandard"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsImageRendererFormat.Range.standard",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsimagerendererformat/range/standard"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat/Range/unspecified": {
      "abstract": [
        {
          "text": "The image renderer context doesn’t specify a color range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat/Range/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsImageRendererFormatRangeUnspecified"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsImageRendererFormat.Range.unspecified",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsimagerendererformat/range/unspecified"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat/opaque": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the underlying Core Graphics context has an alpha channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "opaque"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat/opaque",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "opaque"
        }
      ],
      "role": "symbol",
      "title": "opaque",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsimagerendererformat/opaque"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat/preferredRange": {
      "abstract": [
        {
          "text": "The preferred color range of the image renderer context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIGraphicsImageRendererFormat",
          "text": "UIGraphicsImageRendererFormat"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIGraphicsImageRendererFormatRange",
          "text": "Range"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat/preferredRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preferredRange"
        }
      ],
      "role": "symbol",
      "title": "preferredRange",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsimagerendererformat/preferredrange"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat/prefersExtendedRange": {
      "abstract": [
        {
          "text": "A Boolean value that specifies whether the bitmap context uses extended color.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prefersExtendedRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat/prefersExtendedRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "prefersExtendedRange"
        }
      ],
      "role": "symbol",
      "title": "prefersExtendedRange",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsimagerendererformat/prefersextendedrange"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat/scale": {
      "abstract": [
        {
          "text": "The display scale of the image renderer context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat/scale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scale"
        }
      ],
      "role": "symbol",
      "title": "scale",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsimagerendererformat/scale"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-the-renderer-attributes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat/opaque",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat/scale",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat/preferredRange",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat/prefersExtendedRange"
      ],
      "title": "Configuring the renderer attributes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat/Range/automatic",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat/Range/extended",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat/Range/standard",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat/Range/unspecified"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat/Range/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIGraphicsImageRendererFormatRange"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsImageRendererFormatRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsImageRendererFormatRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat/Range/automatic",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat/Range/extended",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat/Range/standard",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat/Range/unspecified"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-the-renderer-attributes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat/opaque",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat/scale",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat/preferredRange",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat/prefersExtendedRange"
              ],
              "title": "Configuring the renderer attributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIGraphicsImageRendererFormatRange"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRendererFormat~1Range~1automatic/title",
          "value": "UIGraphicsImageRendererFormatRangeAutomatic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRendererFormat~1Range~1automatic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsImageRendererFormatRangeAutomatic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRendererFormat/title",
          "value": "UIGraphicsImageRendererFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRendererFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsImageRendererFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRendererFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsImageRendererFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRendererFormat~1Range~1extended/title",
          "value": "UIGraphicsImageRendererFormatRangeExtended"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRendererFormat~1Range~1extended/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsImageRendererFormatRangeExtended"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRendererFormat~1Range~1unspecified/title",
          "value": "UIGraphicsImageRendererFormatRangeUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRendererFormat~1Range~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsImageRendererFormatRangeUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRendererFormat~1opaque/title",
          "value": "opaque"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRendererFormat~1opaque/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "opaque"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRendererFormat~1scale/title",
          "value": "scale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRendererFormat~1scale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRendererFormat~1Range~1standard/title",
          "value": "UIGraphicsImageRendererFormatRangeStandard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRendererFormat~1Range~1standard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsImageRendererFormatRangeStandard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRendererFormat~1preferredRange/title",
          "value": "preferredRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRendererFormat~1preferredRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "preferredRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRendererFormat~1Range/title",
          "value": "UIGraphicsImageRendererFormatRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRendererFormat~1Range/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsImageRendererFormatRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRendererFormat~1Range/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsImageRendererFormatRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRendererFormat~1prefersExtendedRange/title",
          "value": "prefersExtendedRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRendererFormat~1prefersExtendedRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "prefersExtendedRange"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uigraphicsimagerendererformat/range"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uigraphicsimagerendererformat/range"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
