{
  "abstract": [
    {
      "text": "An asynchronous sequence that provides the attachment’s data.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKit/HKAttachmentDataReader"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKAttachmentDataReader/bytes"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:9HealthKit22HKAttachmentDataReaderC5bytesSo0C0CAAE10AsyncBytesVvp",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "bytes"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)HKAttachment",
        "text": "HKAttachment"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:So12HKAttachmentC9HealthKitE10AsyncBytesV",
        "text": "AsyncBytes"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "bytes"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "bytes"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAttachment",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)HKAttachment",
              "text": "HKAttachment"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAttachment/AsyncBytes",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:So12HKAttachmentC9HealthKitE10AsyncBytesV",
              "text": "AsyncBytes"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this property to access the file’s contents as an asynchronous sequence of bytes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Asynchronously access the attachment's bytes.",
            "var data = Data()",
            "do {",
            "    for try await byte in dataReader.bytes {",
            "        // Use the bytes here.",
            "        data.append(byte)",
            "    }",
            "} catch {",
            "    // Handle the error here.",
            "    fatalError(\"*** An error occurred while reading the attachment's data: \\(error.localizedDescription) ***\")",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKAttachment": {
      "abstract": [
        {
          "text": "A file that is attached to a sample in the HealthKit store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKAttachment"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAttachment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKAttachment"
        }
      ],
      "role": "symbol",
      "title": "HKAttachment",
      "type": "topic",
      "url": "/documentation/healthkit/hkattachment"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKAttachment/AsyncBytes": {
      "abstract": [
        {
          "text": "An asynchronous sequence that returns the attached file as a series of bytes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AsyncBytes"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAttachment/AsyncBytes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AsyncBytes"
        }
      ],
      "role": "symbol",
      "title": "HKAttachment.AsyncBytes",
      "type": "topic",
      "url": "/documentation/healthkit/hkattachment/asyncbytes"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKAttachmentDataReader": {
      "abstract": [
        {
          "text": "A reader that provides access to an attachment’s data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKAttachmentDataReader"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAttachmentDataReader",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKAttachmentDataReader"
        }
      ],
      "role": "symbol",
      "title": "HKAttachmentDataReader",
      "type": "topic",
      "url": "/documentation/healthkit/hkattachmentdatareader"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKAttachmentDataReader/bytes": {
      "abstract": [
        {
          "text": "An asynchronous sequence that provides the attachment’s data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bytes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKAttachment",
          "text": "HKAttachment"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So12HKAttachmentC9HealthKitE10AsyncBytesV",
          "text": "AsyncBytes"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAttachmentDataReader/bytes",
      "kind": "symbol",
      "role": "symbol",
      "title": "bytes",
      "type": "topic",
      "url": "/documentation/healthkit/hkattachmentdatareader/bytes"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKAttachmentDataReader/data": {
      "abstract": [
        {
          "text": "The abstract’s data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "data"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAttachmentDataReader/data",
      "kind": "symbol",
      "role": "symbol",
      "title": "data",
      "type": "topic",
      "url": "/documentation/healthkit/hkattachmentdatareader/data"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKAttachmentDataReader/progress": {
      "abstract": [
        {
          "text": "An object you can use to track the progress while reading an attachment’s data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "progress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSProgress",
          "text": "Progress"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAttachmentDataReader/progress",
      "kind": "symbol",
      "role": "symbol",
      "title": "progress",
      "type": "topic",
      "url": "/documentation/healthkit/hkattachmentdatareader/progress"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reading-attachment-data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKAttachmentDataReader/data",
        "doc://com.apple.healthkit/documentation/HealthKit/HKAttachmentDataReader/progress"
      ],
      "title": "Reading attachment data"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAttachment/title",
          "value": "HKAttachment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAttachment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAttachment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKAttachment"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkattachmentdatareader/bytes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
