{
  "abstract": [
    {
      "text": "The largest presentation size.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UINSToolbarItemPresentationSize"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UINSToolbarItemPresentationSize/large"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UINSToolbarItemPresentationSize@UINSToolbarItemPresentationSizeLarge",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "large"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UINSToolbarItemPresentationSizeLarge"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UINSToolbarItemPresentationSize.large"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "large"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINSToolbarItemPresentationSize": {
      "abstract": [
        {
          "text": "Constants that specify the presentation size of a toolbar item in an AppKit toolbar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UINSToolbarItemPresentationSize"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINSToolbarItemPresentationSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UINSToolbarItemPresentationSize"
        }
      ],
      "role": "symbol",
      "title": "UINSToolbarItemPresentationSize",
      "type": "topic",
      "url": "/documentation/uikit/uinstoolbaritempresentationsize"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINSToolbarItemPresentationSize/large": {
      "abstract": [
        {
          "text": "The largest presentation size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "large"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINSToolbarItemPresentationSize/large",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UINSToolbarItemPresentationSizeLarge"
        }
      ],
      "role": "symbol",
      "title": "UINSToolbarItemPresentationSize.large",
      "type": "topic",
      "url": "/documentation/uikit/uinstoolbaritempresentationsize/large"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINSToolbarItemPresentationSize/regular": {
      "abstract": [
        {
          "text": "The default, regular presentation size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "regular"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINSToolbarItemPresentationSize/regular",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UINSToolbarItemPresentationSizeRegular"
        }
      ],
      "role": "symbol",
      "title": "UINSToolbarItemPresentationSize.regular",
      "type": "topic",
      "url": "/documentation/uikit/uinstoolbaritempresentationsize/regular"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINSToolbarItemPresentationSize/small": {
      "abstract": [
        {
          "text": "The smallest presentation size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "small"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINSToolbarItemPresentationSize/small",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UINSToolbarItemPresentationSizeSmall"
        }
      ],
      "role": "symbol",
      "title": "UINSToolbarItemPresentationSize.small",
      "type": "topic",
      "url": "/documentation/uikit/uinstoolbaritempresentationsize/small"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINSToolbarItemPresentationSize/unspecified": {
      "abstract": [
        {
          "text": "An unspecified presentation size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINSToolbarItemPresentationSize/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UINSToolbarItemPresentationSizeUnspecified"
        }
      ],
      "role": "symbol",
      "title": "UINSToolbarItemPresentationSize.unspecified",
      "type": "topic",
      "url": "/documentation/uikit/uinstoolbaritempresentationsize/unspecified"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UINSToolbarItemPresentationSize/regular",
        "doc://com.apple.uikit/documentation/UIKit/UINSToolbarItemPresentationSize/small",
        "doc://com.apple.uikit/documentation/UIKit/UINSToolbarItemPresentationSize/unspecified"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UINSToolbarItemPresentationSizeLarge"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UINSToolbarItemPresentationSizeLarge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UINSToolbarItemPresentationSize"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UINSToolbarItemPresentationSize/regular",
                "doc://com.apple.uikit/documentation/UIKit/UINSToolbarItemPresentationSize/small",
                "doc://com.apple.uikit/documentation/UIKit/UINSToolbarItemPresentationSize/unspecified"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UINSToolbarItemPresentationSizeLarge"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINSToolbarItemPresentationSize/title",
          "value": "UINSToolbarItemPresentationSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINSToolbarItemPresentationSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UINSToolbarItemPresentationSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINSToolbarItemPresentationSize/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UINSToolbarItemPresentationSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINSToolbarItemPresentationSize~1unspecified/title",
          "value": "UINSToolbarItemPresentationSizeUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINSToolbarItemPresentationSize~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UINSToolbarItemPresentationSizeUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINSToolbarItemPresentationSize~1regular/title",
          "value": "UINSToolbarItemPresentationSizeRegular"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINSToolbarItemPresentationSize~1regular/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UINSToolbarItemPresentationSizeRegular"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINSToolbarItemPresentationSize~1small/title",
          "value": "UINSToolbarItemPresentationSizeSmall"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINSToolbarItemPresentationSize~1small/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UINSToolbarItemPresentationSizeSmall"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINSToolbarItemPresentationSize~1large/title",
          "value": "UINSToolbarItemPresentationSizeLarge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINSToolbarItemPresentationSize~1large/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UINSToolbarItemPresentationSizeLarge"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uinstoolbaritempresentationsize/large"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uinstoolbaritempresentationsize/large"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
