{
  "abstract": [
    {
      "text": "Possible values for the ",
      "type": "text"
    },
    {
      "code": "result",
      "type": "codeVoice"
    },
    {
      "text": " parameter of the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.social/documentation/Social/SLComposeViewController/completionHandler",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " property.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.social/documentation/Social"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.social/documentation/Social/SLComposeViewControllerResult"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SLComposeViewControllerResult",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SLComposeViewControllerResult"
      }
    ],
    "modules": [
      {
        "name": "Social"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SLComposeViewControllerResult"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "SLComposeViewControllerResult"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SLComposeViewControllerResult"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.social/documentation/Social": {
      "abstract": [
        {
          "text": "Post content to supported social networking services, using standard system interfaces.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.social/documentation/Social",
      "kind": "symbol",
      "role": "collection",
      "title": "Social",
      "type": "topic",
      "url": "/documentation/social"
    },
    "doc://com.apple.social/documentation/Social/SLComposeViewController/completionHandler": {
      "abstract": [
        {
          "text": "The handler to call when the user is done composing a post.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SLComposeViewControllerCompletionHandler",
          "text": "SLComposeViewControllerCompletionHandler"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.social/documentation/Social/SLComposeViewController/completionHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "completionHandler"
        }
      ],
      "role": "symbol",
      "title": "completionHandler",
      "type": "topic",
      "url": "/documentation/social/slcomposeviewcontroller/completionhandler"
    },
    "doc://com.apple.social/documentation/Social/SLComposeViewControllerCompletionHandler": {
      "abstract": [
        {
          "text": "Defines a handler to call when the user finishes composing a post.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SLComposeViewControllerCompletionHandler"
        }
      ],
      "identifier": "doc://com.apple.social/documentation/Social/SLComposeViewControllerCompletionHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SLComposeViewControllerCompletionHandler"
        }
      ],
      "role": "symbol",
      "title": "SLComposeViewControllerCompletionHandler",
      "type": "topic",
      "url": "/documentation/social/slcomposeviewcontrollercompletionhandler"
    },
    "doc://com.apple.social/documentation/Social/SLComposeViewControllerResult": {
      "abstract": [
        {
          "text": "Possible values for the ",
          "type": "text"
        },
        {
          "code": "result",
          "type": "codeVoice"
        },
        {
          "text": " parameter of the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.social/documentation/Social/SLComposeViewController/completionHandler",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SLComposeViewControllerResult"
        }
      ],
      "identifier": "doc://com.apple.social/documentation/Social/SLComposeViewControllerResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SLComposeViewControllerResult"
        }
      ],
      "role": "symbol",
      "title": "SLComposeViewControllerResult",
      "type": "topic",
      "url": "/documentation/social/slcomposeviewcontrollerresult"
    },
    "doc://com.apple.social/documentation/Social/SLComposeViewControllerResult/cancelled": {
      "abstract": [
        {
          "text": "The view controller is dismissed without sending the post.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancelled"
        }
      ],
      "identifier": "doc://com.apple.social/documentation/Social/SLComposeViewControllerResult/cancelled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SLComposeViewControllerResultCancelled"
        }
      ],
      "role": "symbol",
      "title": "SLComposeViewControllerResult.cancelled",
      "type": "topic",
      "url": "/documentation/social/slcomposeviewcontrollerresult/cancelled"
    },
    "doc://com.apple.social/documentation/Social/SLComposeViewControllerResult/done": {
      "abstract": [
        {
          "text": "The view controller is dismissed and the message is being sent in the background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "done"
        }
      ],
      "identifier": "doc://com.apple.social/documentation/Social/SLComposeViewControllerResult/done",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SLComposeViewControllerResultDone"
        }
      ],
      "role": "symbol",
      "title": "SLComposeViewControllerResult.done",
      "type": "topic",
      "url": "/documentation/social/slcomposeviewcontrollerresult/done"
    },
    "doc://com.apple.social/documentation/Social/SLComposeViewControllerResult/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.social/documentation/Social/SLComposeViewControllerResult/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/social/slcomposeviewcontrollerresult/init(rawvalue:)"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Processing-the-Results",
      "generated": true,
      "identifiers": [
        "doc://com.apple.social/documentation/Social/SLComposeViewController/completionHandler",
        "doc://com.apple.social/documentation/Social/SLComposeViewControllerCompletionHandler"
      ],
      "title": "Processing the Results"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.social/documentation/Social/SLComposeViewControllerResult/cancelled",
        "doc://com.apple.social/documentation/Social/SLComposeViewControllerResult/done"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.social/documentation/Social/SLComposeViewControllerResult/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SLComposeViewControllerResult"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SLComposeViewControllerResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SLComposeViewControllerResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.social/documentation/Social"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.social/documentation/Social/SLComposeViewControllerResult/cancelled",
                "doc://com.apple.social/documentation/Social/SLComposeViewControllerResult/done"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Processing-the-Results",
              "generated": true,
              "identifiers": [
                "doc://com.apple.social/documentation/Social/SLComposeViewController/completionHandler",
                "doc://com.apple.social/documentation/Social/SLComposeViewControllerCompletionHandler"
              ],
              "title": "Processing the Results"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SLComposeViewControllerResult"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLComposeViewControllerResult/title",
          "value": "SLComposeViewControllerResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLComposeViewControllerResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SLComposeViewControllerResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLComposeViewControllerResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SLComposeViewControllerResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLComposeViewControllerResult~1done/title",
          "value": "SLComposeViewControllerResultDone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLComposeViewControllerResult~1done/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SLComposeViewControllerResultDone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLComposeViewControllerResult~1cancelled/title",
          "value": "SLComposeViewControllerResultCancelled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLComposeViewControllerResult~1cancelled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SLComposeViewControllerResultCancelled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLComposeViewController~1completionHandler/title",
          "value": "completionHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLComposeViewController~1completionHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "completionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLComposeViewControllerCompletionHandler/title",
          "value": "SLComposeViewControllerCompletionHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLComposeViewControllerCompletionHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SLComposeViewControllerCompletionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLComposeViewControllerCompletionHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SLComposeViewControllerCompletionHandler"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/social/slcomposeviewcontrollerresult"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/social/slcomposeviewcontrollerresult"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
