{
  "abstract": [
    {
      "text": "An object that you use to assemble an HTTP request for communicating with a social media service.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.social/documentation/Social"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.social/documentation/Social/SLRequest"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SLRequest",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SLRequest"
      }
    ],
    "modules": [
      {
        "name": "Social"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SLRequest"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "SLRequest"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SLRequest"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The SLRequest object encapsulates the properties of an HTTP request, providing a convenient template for you to make requests. You send a request to a social networking service to perform some operation on behalf of the user or to retrieve user information.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "HTTP requests have these common components: an HTTP request method (GET, POST, PUT, or DELETE), a URL identifying the operation to perform, a set of query parameters, and an optional multipart POST body that contains additional data. The values for these properties depend on the request you are sending and the target service provider. Refer to each supported social networking site’s documentation for possible values. Links to documentation are provided in Table 1.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.social/documentation/Social/SLRequest/init(forServiceType:requestMethod:url:parameters:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method to initialize a newly created ",
              "type": "text"
            },
            {
              "code": "SLRequest",
              "type": "codeVoice"
            },
            {
              "text": " object passing the required property values. Use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.social/documentation/Social/SLRequest/addMultipartData(_:withName:type:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to optionally specify a multipart POST body. After you create your request, use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.social/documentation/Social/SLRequest/perform(handler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method to send the request, specifying the handler to call when the request is done.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you already have a sending mechanism, you can use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.social/documentation/Social/SLRequest/preparedURLRequest()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method to create the request that you send using an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsurlconnection",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. If the request requires user authorization, set the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.social/documentation/Social/SLRequest/account",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property to an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Accounts/ACAccount",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Table 1  Social Services Individual Documentation Sites",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Facebook",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "https://developers.facebook.com/docs/",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Sina Weibo",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "http://open.weibo.com/wiki/",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Twitter",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "https://dev.twitter.com/docs",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "LinkedIn",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "https://developer.linkedin.com/rest",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "For Sina Weibo integration, users must have the Chinese keyboard enabled. Users can enable this keyboard in Settings > General > Keyboard. If a Chinese keyboard is not enabled, users won’t be prompted to sign in to their Sina Weibo account.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/Accounts/ACAccount": {
      "abstract": [
        {
          "text": "The information associated with one of the user’s accounts.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACAccount"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Accounts/ACAccount",
      "kind": "symbol",
      "role": "symbol",
      "title": "ACAccount",
      "type": "topic",
      "url": "/documentation/Accounts/ACAccount"
    },
    "doc://com.apple.documentation/documentation/foundation/nsurlconnection": {
      "abstract": [
        {
          "text": "An object that enables you to start and stop URL requests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSURLConnection"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsurlconnection",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSURLConnection",
      "type": "topic",
      "url": "/documentation/foundation/nsurlconnection"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.social/documentation/Social": {
      "abstract": [
        {
          "text": "Post content to supported social networking services, using standard system interfaces.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.social/documentation/Social",
      "kind": "symbol",
      "role": "collection",
      "title": "Social",
      "type": "topic",
      "url": "/documentation/social"
    },
    "doc://com.apple.social/documentation/Social/SLRequest": {
      "abstract": [
        {
          "text": "An object that you use to assemble an HTTP request for communicating with a social media service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SLRequest"
        }
      ],
      "identifier": "doc://com.apple.social/documentation/Social/SLRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SLRequest"
        }
      ],
      "role": "symbol",
      "title": "SLRequest",
      "type": "topic",
      "url": "/documentation/social/slrequest"
    },
    "doc://com.apple.social/documentation/Social/SLRequest/account": {
      "abstract": [
        {
          "text": "Account information used to authenticate the request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "account"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ACAccount",
          "text": "ACAccount"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.social/documentation/Social/SLRequest/account",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "account"
        }
      ],
      "role": "symbol",
      "title": "account",
      "type": "topic",
      "url": "/documentation/social/slrequest/account"
    },
    "doc://com.apple.social/documentation/Social/SLRequest/addMultipartData(_:withName:type:)": {
      "abstract": [
        {
          "text": "Specifies a named multipart POST body for this request.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addMultipartData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "withName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.social/documentation/Social/SLRequest/addMultipartData(_:withName:type:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addMultipartData:withName:type:"
        }
      ],
      "role": "symbol",
      "title": "addMultipartData(_:withName:type:)",
      "type": "topic",
      "url": "/documentation/social/slrequest/addmultipartdata(_:withname:type:)"
    },
    "doc://com.apple.social/documentation/Social/SLRequest/addMultipartData(_:withName:type:filename:)": {
      "abstract": [
        {
          "text": "Specifies a named multipart POST body for this request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addMultipartData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "withName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "filename"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.social/documentation/Social/SLRequest/addMultipartData(_:withName:type:filename:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addMultipartData:withName:type:filename:"
        }
      ],
      "role": "symbol",
      "title": "addMultipartData(_:withName:type:filename:)",
      "type": "topic",
      "url": "/documentation/social/slrequest/addmultipartdata(_:withname:type:filename:)"
    },
    "doc://com.apple.social/documentation/Social/SLRequest/init(forServiceType:requestMethod:url:parameters:)": {
      "abstract": [
        {
          "text": "Initializes a newly created request object with the specified properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "!("
        },
        {
          "kind": "externalParam",
          "text": "forServiceType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "requestMethod"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SLRequestMethod",
          "text": "SLRequestMethod"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "url"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "parameters"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!)"
        }
      ],
      "identifier": "doc://com.apple.social/documentation/Social/SLRequest/init(forServiceType:requestMethod:url:parameters:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestForServiceType:requestMethod:URL:parameters:"
        }
      ],
      "role": "symbol",
      "title": "init(forServiceType:requestMethod:url:parameters:)",
      "type": "topic",
      "url": "/documentation/social/slrequest/init(forservicetype:requestmethod:url:parameters:)"
    },
    "doc://com.apple.social/documentation/Social/SLRequest/parameters": {
      "abstract": [
        {
          "text": "The parameters for this request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "parameters"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!"
        }
      ],
      "identifier": "doc://com.apple.social/documentation/Social/SLRequest/parameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "parameters"
        }
      ],
      "role": "symbol",
      "title": "parameters",
      "type": "topic",
      "url": "/documentation/social/slrequest/parameters"
    },
    "doc://com.apple.social/documentation/Social/SLRequest/perform(handler:)": {
      "abstract": [
        {
          "text": "Performs an asynchronous request and calls the specified handler when done.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "perform"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "handler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SLRequestHandler",
          "text": "SLRequestHandler"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.social/documentation/Social/SLRequest/perform(handler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "performRequestWithHandler:"
        }
      ],
      "role": "symbol",
      "title": "perform(handler:)",
      "type": "topic",
      "url": "/documentation/social/slrequest/perform(handler:)"
    },
    "doc://com.apple.social/documentation/Social/SLRequest/preparedURLRequest()": {
      "abstract": [
        {
          "text": "Returns an authorized URL request that can be sent using an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsurlconnection",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preparedURLRequest"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation10URLRequestV",
          "text": "URLRequest"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.social/documentation/Social/SLRequest/preparedURLRequest()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preparedURLRequest"
        }
      ],
      "role": "symbol",
      "title": "preparedURLRequest()",
      "type": "topic",
      "url": "/documentation/social/slrequest/preparedurlrequest()"
    },
    "doc://com.apple.social/documentation/Social/SLRequest/requestMethod": {
      "abstract": [
        {
          "text": "The method to use for this request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestMethod"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SLRequestMethod",
          "text": "SLRequestMethod"
        }
      ],
      "identifier": "doc://com.apple.social/documentation/Social/SLRequest/requestMethod",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestMethod"
        }
      ],
      "role": "symbol",
      "title": "requestMethod",
      "type": "topic",
      "url": "/documentation/social/slrequest/requestmethod"
    },
    "doc://com.apple.social/documentation/Social/SLRequest/url": {
      "abstract": [
        {
          "text": "The destination URL for this request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "url"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.social/documentation/Social/SLRequest/url",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "URL"
        }
      ],
      "role": "symbol",
      "title": "url",
      "type": "topic",
      "url": "/documentation/social/slrequest/url"
    },
    "doc://com.apple.social/documentation/Social/SLRequestHandler": {
      "abstract": [
        {
          "text": "The callback handler for a request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SLRequestHandler"
        }
      ],
      "identifier": "doc://com.apple.social/documentation/Social/SLRequestHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SLRequestHandler"
        }
      ],
      "role": "symbol",
      "title": "SLRequestHandler",
      "type": "topic",
      "url": "/documentation/social/slrequesthandler"
    },
    "doc://com.apple.social/documentation/Social/SLRequestMethod": {
      "abstract": [
        {
          "text": "Indicates the request method used in the request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SLRequestMethod"
        }
      ],
      "identifier": "doc://com.apple.social/documentation/Social/SLRequestMethod",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SLRequestMethod"
        }
      ],
      "role": "symbol",
      "title": "SLRequestMethod",
      "type": "topic",
      "url": "/documentation/social/slrequestmethod"
    },
    "doc://com.apple.social/documentation/Social/SLServiceTypeFacebook": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SLServiceTypeFacebook"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.social/documentation/Social/SLServiceTypeFacebook",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SLServiceTypeFacebook"
        }
      ],
      "role": "symbol",
      "title": "SLServiceTypeFacebook",
      "type": "topic",
      "url": "/documentation/social/slservicetypefacebook"
    },
    "doc://com.apple.social/documentation/Social/SLServiceTypeLinkedIn": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SLServiceTypeLinkedIn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.social/documentation/Social/SLServiceTypeLinkedIn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SLServiceTypeLinkedIn"
        }
      ],
      "role": "symbol",
      "title": "SLServiceTypeLinkedIn",
      "type": "topic",
      "url": "/documentation/social/slservicetypelinkedin"
    },
    "doc://com.apple.social/documentation/Social/SLServiceTypeSinaWeibo": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SLServiceTypeSinaWeibo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.social/documentation/Social/SLServiceTypeSinaWeibo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SLServiceTypeSinaWeibo"
        }
      ],
      "role": "symbol",
      "title": "SLServiceTypeSinaWeibo",
      "type": "topic",
      "url": "/documentation/social/slservicetypesinaweibo"
    },
    "doc://com.apple.social/documentation/Social/SLServiceTypeTencentWeibo": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SLServiceTypeTencentWeibo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.social/documentation/Social/SLServiceTypeTencentWeibo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SLServiceTypeTencentWeibo"
        }
      ],
      "role": "symbol",
      "title": "SLServiceTypeTencentWeibo",
      "type": "topic",
      "url": "/documentation/social/slservicetypetencentweibo"
    },
    "doc://com.apple.social/documentation/Social/SLServiceTypeTwitter": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SLServiceTypeTwitter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.social/documentation/Social/SLServiceTypeTwitter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SLServiceTypeTwitter"
        }
      ],
      "role": "symbol",
      "title": "SLServiceTypeTwitter",
      "type": "topic",
      "url": "/documentation/social/slservicetypetwitter"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "http://open.weibo.com/wiki/": {
      "identifier": "http://open.weibo.com/wiki/",
      "title": "http://open.weibo.com/wiki/",
      "titleInlineContent": [
        {
          "text": "http://open.weibo.com/wiki/",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "http://open.weibo.com/wiki/"
    },
    "https://dev.twitter.com/docs": {
      "identifier": "https://dev.twitter.com/docs",
      "title": "https://dev.twitter.com/docs",
      "titleInlineContent": [
        {
          "text": "https://dev.twitter.com/docs",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://dev.twitter.com/docs"
    },
    "https://developer.linkedin.com/rest": {
      "identifier": "https://developer.linkedin.com/rest",
      "title": "https://developer.linkedin.com/rest",
      "titleInlineContent": [
        {
          "text": "https://developer.linkedin.com/rest",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.linkedin.com/rest"
    },
    "https://developers.facebook.com/docs/": {
      "identifier": "https://developers.facebook.com/docs/",
      "title": "https://developers.facebook.com/docs/",
      "titleInlineContent": [
        {
          "text": "https://developers.facebook.com/docs/",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developers.facebook.com/docs/"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Initializing-Requests",
      "identifiers": [
        "doc://com.apple.social/documentation/Social/SLRequest/init(forServiceType:requestMethod:url:parameters:)",
        "doc://com.apple.social/documentation/Social/SLServiceTypeFacebook",
        "doc://com.apple.social/documentation/Social/SLServiceTypeTwitter",
        "doc://com.apple.social/documentation/Social/SLServiceTypeSinaWeibo",
        "doc://com.apple.social/documentation/Social/SLServiceTypeLinkedIn",
        "doc://com.apple.social/documentation/Social/SLServiceTypeTencentWeibo"
      ],
      "title": "Initializing Requests"
    },
    {
      "anchor": "Sending-a-Request",
      "identifiers": [
        "doc://com.apple.social/documentation/Social/SLRequest/perform(handler:)",
        "doc://com.apple.social/documentation/Social/SLRequestHandler"
      ],
      "title": "Sending a Request"
    },
    {
      "anchor": "Providing-User-Credentials",
      "identifiers": [
        "doc://com.apple.social/documentation/Social/SLRequest/account"
      ],
      "title": "Providing User Credentials"
    },
    {
      "anchor": "Getting-the-Request-Details",
      "identifiers": [
        "doc://com.apple.social/documentation/Social/SLRequest/preparedURLRequest()",
        "doc://com.apple.social/documentation/Social/SLRequest/requestMethod",
        "doc://com.apple.social/documentation/Social/SLRequestMethod",
        "doc://com.apple.social/documentation/Social/SLRequest/url",
        "doc://com.apple.social/documentation/Social/SLRequest/parameters"
      ],
      "title": "Getting the Request Details"
    },
    {
      "anchor": "Adding-Data-to-the-Request",
      "identifiers": [
        "doc://com.apple.social/documentation/Social/SLRequest/addMultipartData(_:withName:type:filename:)",
        "doc://com.apple.social/documentation/Social/SLRequest/addMultipartData(_:withName:type:)"
      ],
      "title": "Adding Data to the Request"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SLRequest"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SLRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SLRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.social/documentation/Social"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Initializing-Requests",
              "identifiers": [
                "doc://com.apple.social/documentation/Social/SLRequest/init(forServiceType:requestMethod:url:parameters:)",
                "doc://com.apple.social/documentation/Social/SLServiceTypeFacebook",
                "doc://com.apple.social/documentation/Social/SLServiceTypeTwitter",
                "doc://com.apple.social/documentation/Social/SLServiceTypeSinaWeibo",
                "doc://com.apple.social/documentation/Social/SLServiceTypeLinkedIn",
                "doc://com.apple.social/documentation/Social/SLServiceTypeTencentWeibo"
              ],
              "title": "Initializing Requests"
            },
            {
              "anchor": "Sending-a-Request",
              "identifiers": [
                "doc://com.apple.social/documentation/Social/SLRequest/perform(handler:)",
                "doc://com.apple.social/documentation/Social/SLRequestHandler"
              ],
              "title": "Sending a Request"
            },
            {
              "anchor": "Providing-User-Credentials",
              "identifiers": [
                "doc://com.apple.social/documentation/Social/SLRequest/account"
              ],
              "title": "Providing User Credentials"
            },
            {
              "anchor": "Getting-the-Request-Details",
              "identifiers": [
                "doc://com.apple.social/documentation/Social/SLRequest/preparedURLRequest()",
                "doc://com.apple.social/documentation/Social/SLRequest/requestMethod",
                "doc://com.apple.social/documentation/Social/SLRequestMethod",
                "doc://com.apple.social/documentation/Social/SLRequest/url",
                "doc://com.apple.social/documentation/Social/SLRequest/parameters"
              ],
              "title": "Getting the Request Details"
            },
            {
              "anchor": "Adding-Data-to-the-Request",
              "identifiers": [
                "doc://com.apple.social/documentation/Social/SLRequest/addMultipartData(_:withName:type:filename:)",
                "doc://com.apple.social/documentation/Social/SLRequest/addMultipartData(_:withName:type:)"
              ],
              "title": "Adding Data to the Request"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SLRequest"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLServiceTypeFacebook/title",
          "value": "SLServiceTypeFacebook"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLServiceTypeFacebook/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SLServiceTypeFacebook"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLRequestHandler/title",
          "value": "SLRequestHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLRequestHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SLRequestHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLRequestHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SLRequestHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Accounts~1ACAccount/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ACAccount"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLServiceTypeTwitter/title",
          "value": "SLServiceTypeTwitter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLServiceTypeTwitter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SLServiceTypeTwitter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLRequest~1preparedURLRequest()/title",
          "value": "preparedURLRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLRequest~1preparedURLRequest()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "preparedURLRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLRequest~1url/title",
          "value": "URL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLRequest~1url/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "URL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLRequest~1init(forServiceType:requestMethod:url:parameters:)/title",
          "value": "requestForServiceType:requestMethod:URL:parameters:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLRequest~1init(forServiceType:requestMethod:url:parameters:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "requestForServiceType:requestMethod:URL:parameters:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLRequest~1account/title",
          "value": "account"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLRequest~1account/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "account"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLRequestMethod/title",
          "value": "SLRequestMethod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLRequestMethod/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SLRequestMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLRequestMethod/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SLRequestMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLRequest~1addMultipartData(_:withName:type:filename:)/title",
          "value": "addMultipartData:withName:type:filename:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLRequest~1addMultipartData(_:withName:type:filename:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addMultipartData:withName:type:filename:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLServiceTypeTencentWeibo/title",
          "value": "SLServiceTypeTencentWeibo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLServiceTypeTencentWeibo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SLServiceTypeTencentWeibo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLServiceTypeLinkedIn/title",
          "value": "SLServiceTypeLinkedIn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLServiceTypeLinkedIn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SLServiceTypeLinkedIn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLRequest/title",
          "value": "SLRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SLRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SLRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLRequest~1addMultipartData(_:withName:type:)/title",
          "value": "addMultipartData:withName:type:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLRequest~1addMultipartData(_:withName:type:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addMultipartData:withName:type:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLServiceTypeSinaWeibo/title",
          "value": "SLServiceTypeSinaWeibo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLServiceTypeSinaWeibo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SLServiceTypeSinaWeibo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLRequest~1parameters/title",
          "value": "parameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLRequest~1parameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "parameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLRequest~1perform(handler:)/title",
          "value": "performRequestWithHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLRequest~1perform(handler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "performRequestWithHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLRequest~1requestMethod/title",
          "value": "requestMethod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLRequest~1requestMethod/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "requestMethod"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/social/slrequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/social/slrequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
