{
  "abstract": [
    {
      "text": "The version of the video to request.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.photokit/documentation/Photos",
        "doc://com.apple.photokit/documentation/Photos/PHVideoRequestOptions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.photokit/documentation/Photos/PHVideoRequestOptions/version"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PHVideoRequestOptions(py)version",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "version"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@PHVideoRequestOptionsVersion",
        "text": "PHVideoRequestOptionsVersion"
      }
    ],
    "modules": [
      {
        "name": "Photos"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "version"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "version"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "version"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHVideoRequestOptionsVersion",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@PHVideoRequestOptionsVersion",
              "text": "PHVideoRequestOptionsVersion"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If a video asset has been edited, use this property to request a video with or without adjustments.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The default option is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHVideoRequestOptionsVersion/current",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHVideoRequestOptionsVersion",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.photokit/documentation/Photos": {
      "abstract": [
        {
          "text": "Work with image and video assets that the Photos app manages, including those from iCloud Photos and Live Photos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos",
      "kind": "symbol",
      "role": "collection",
      "title": "Photos",
      "type": "topic",
      "url": "/documentation/photos"
    },
    "doc://com.apple.photokit/documentation/Photos/PHVideoRequestOptions": {
      "abstract": [
        {
          "text": "A set of options affecting the delivery of video asset data that you request from an image manager.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHVideoRequestOptions"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHVideoRequestOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHVideoRequestOptions"
        }
      ],
      "role": "symbol",
      "title": "PHVideoRequestOptions",
      "type": "topic",
      "url": "/documentation/photos/phvideorequestoptions"
    },
    "doc://com.apple.photokit/documentation/Photos/PHVideoRequestOptions/deliveryMode": {
      "abstract": [
        {
          "text": "A mode specifying the requested video quality and delivery priority.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deliveryMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHVideoRequestOptionsDeliveryMode",
          "text": "PHVideoRequestOptionsDeliveryMode"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHVideoRequestOptions/deliveryMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deliveryMode"
        }
      ],
      "role": "symbol",
      "title": "deliveryMode",
      "type": "topic",
      "url": "/documentation/photos/phvideorequestoptions/deliverymode"
    },
    "doc://com.apple.photokit/documentation/Photos/PHVideoRequestOptions/version": {
      "abstract": [
        {
          "text": "The version of the video to request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "version"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHVideoRequestOptionsVersion",
          "text": "PHVideoRequestOptionsVersion"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHVideoRequestOptions/version",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "version"
        }
      ],
      "role": "symbol",
      "title": "version",
      "type": "topic",
      "url": "/documentation/photos/phvideorequestoptions/version"
    },
    "doc://com.apple.photokit/documentation/Photos/PHVideoRequestOptionsDeliveryMode": {
      "abstract": [
        {
          "text": "Options for delivering requested video data, used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.photokit/documentation/Photos/PHVideoRequestOptions/deliveryMode",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHVideoRequestOptionsDeliveryMode"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHVideoRequestOptionsDeliveryMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHVideoRequestOptionsDeliveryMode"
        }
      ],
      "role": "symbol",
      "title": "PHVideoRequestOptionsDeliveryMode",
      "type": "topic",
      "url": "/documentation/photos/phvideorequestoptionsdeliverymode"
    },
    "doc://com.apple.photokit/documentation/Photos/PHVideoRequestOptionsVersion": {
      "abstract": [
        {
          "text": "Options for requesting a video asset with or without adjustments, used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.photokit/documentation/Photos/PHVideoRequestOptions/version",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHVideoRequestOptionsVersion"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHVideoRequestOptionsVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHVideoRequestOptionsVersion"
        }
      ],
      "role": "symbol",
      "title": "PHVideoRequestOptionsVersion",
      "type": "topic",
      "url": "/documentation/photos/phvideorequestoptionsversion"
    },
    "doc://com.apple.photokit/documentation/Photos/PHVideoRequestOptionsVersion/current": {
      "abstract": [
        {
          "text": "Request the most recent version of the video asset, reflecting all edits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "current"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHVideoRequestOptionsVersion/current",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHVideoRequestOptionsVersionCurrent"
        }
      ],
      "role": "symbol",
      "title": "PHVideoRequestOptionsVersion.current",
      "type": "topic",
      "url": "/documentation/photos/phvideorequestoptionsversion/current"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Specifying-Video-Request-Options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHVideoRequestOptionsVersion",
        "doc://com.apple.photokit/documentation/Photos/PHVideoRequestOptions/deliveryMode",
        "doc://com.apple.photokit/documentation/Photos/PHVideoRequestOptionsDeliveryMode"
      ],
      "title": "Specifying Video Request Options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "version"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "version"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.photokit/documentation/Photos",
                "doc://com.apple.photokit/documentation/Photos/PHVideoRequestOptions"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Specifying-Video-Request-Options",
              "generated": true,
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHVideoRequestOptionsVersion",
                "doc://com.apple.photokit/documentation/Photos/PHVideoRequestOptions/deliveryMode",
                "doc://com.apple.photokit/documentation/Photos/PHVideoRequestOptionsDeliveryMode"
              ],
              "title": "Specifying Video Request Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "assign"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.photokit/documentation/Photos/PHVideoRequestOptionsVersion",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@PHVideoRequestOptionsVersion",
                    "text": "PHVideoRequestOptionsVersion"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "version"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHVideoRequestOptionsVersion/title",
          "value": "PHVideoRequestOptionsVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHVideoRequestOptionsVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHVideoRequestOptionsVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHVideoRequestOptionsVersion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHVideoRequestOptionsVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHVideoRequestOptions/title",
          "value": "PHVideoRequestOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHVideoRequestOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHVideoRequestOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHVideoRequestOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHVideoRequestOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHVideoRequestOptions~1deliveryMode/title",
          "value": "deliveryMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHVideoRequestOptions~1deliveryMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "deliveryMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHVideoRequestOptionsDeliveryMode/title",
          "value": "PHVideoRequestOptionsDeliveryMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHVideoRequestOptionsDeliveryMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHVideoRequestOptionsDeliveryMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHVideoRequestOptionsDeliveryMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHVideoRequestOptionsDeliveryMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHVideoRequestOptions~1version/title",
          "value": "version"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHVideoRequestOptions~1version/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "version"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHVideoRequestOptionsVersion~1current/title",
          "value": "PHVideoRequestOptionsVersionCurrent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHVideoRequestOptionsVersion~1current/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHVideoRequestOptionsVersionCurrent"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/photos/phvideorequestoptions/version"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/photos/phvideorequestoptions/version"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
