{
  "abstract": [
    {
      "text": "Register to receive remote notifications from the Apple Push Notification service (APNs).",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.watchkit/documentation/WatchKit",
        "doc://com.apple.watchkit/documentation/WatchKit/WKApplication"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.watchkit/documentation/WatchKit/WKApplication/registerForRemoteNotifications()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)WKApplication(im)registerForRemoteNotifications",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "registerForRemoteNotifications"
      },
      {
        "kind": "text",
        "text": "()"
      }
    ],
    "modules": [
      {
        "name": "WatchKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "registerForRemoteNotifications"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "registerForRemoteNotifications()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "registerForRemoteNotifications"
            },
            {
              "kind": "text",
              "text": "()"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Before calling this method, you must enable your WatchKit extension’s Push Notification capability, as described in ",
              "type": "text"
            },
            {
              "identifier": "https://help.apple.com/xcode/mac/current/#/devdfd3d04a1",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Call this method to register a device with APNs. If registration succeeds, the system calls your app delegate’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/didRegisterForRemoteNotifications(withDeviceToken:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method and passes it a device token. Pass this token to the provider server you use to generate remote notifications for this device. If registration fails, the system calls your app delegate’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/didFailToRegisterForRemoteNotificationsWithError(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method instead.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Device tokens may change, so don’t cache the device token on the device. Instead, register for remote notifications every time your app launches. If the device token hasn’t changed, registration happens quickly.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "To display alerts, play sounds, or perform other user-facing actions, you must also request authorization using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UserNotifications/UNUserNotificationCenter",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UserNotifications/UNUserNotificationCenter/requestAuthorization(options:completionHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method. If you don’t request and receive authorization for your app’s interactions, the system delivers all remote notifications to your app silently.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If your watchOS app has an iOS companion, always send notifications to both watchOS and the paired iOS device. As long as the payloads are identical, the system recognizes the duplicates, and only displays one notification to the user.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more information on setting up remote notifications, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UserNotifications/setting-up-a-remote-notification-server",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UserNotifications/registering-your-app-with-apns",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/UserNotifications/UNUserNotificationCenter": {
      "abstract": [
        {
          "text": "The central object for managing notification-related activities for your app or app extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UNUserNotificationCenter"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UserNotifications/UNUserNotificationCenter",
      "kind": "symbol",
      "role": "symbol",
      "title": "UNUserNotificationCenter",
      "type": "topic",
      "url": "/documentation/UserNotifications/UNUserNotificationCenter"
    },
    "doc://com.apple.documentation/documentation/UserNotifications/UNUserNotificationCenter/requestAuthorization(options:completionHandler:)": {
      "abstract": [
        {
          "text": "Requests a person’s authorization to allow local and remote notifications for your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestAuthorization"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UNAuthorizationOptions",
          "text": "UNAuthorizationOptions"
        },
        {
          "kind": "text",
          "text": " = [], "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "@escaping"
        },
        {
          "kind": "text",
          "text": " ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UserNotifications/UNUserNotificationCenter/requestAuthorization(options:completionHandler:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "requestAuthorization(options:completionHandler:)",
      "type": "topic",
      "url": "/documentation/UserNotifications/UNUserNotificationCenter/requestAuthorization(options:completionHandler:)"
    },
    "doc://com.apple.documentation/documentation/UserNotifications/registering-your-app-with-apns": {
      "abstract": [
        {
          "text": "Communicate with Apple Push Notification service (APNs) and receive a unique device token that identifies your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UserNotifications/registering-your-app-with-apns",
      "kind": "article",
      "role": "article",
      "title": "Registering your app with APNs",
      "type": "topic",
      "url": "/documentation/UserNotifications/registering-your-app-with-apns"
    },
    "doc://com.apple.documentation/documentation/UserNotifications/setting-up-a-remote-notification-server": {
      "abstract": [
        {
          "text": "Generate notifications and push them to user devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UserNotifications/setting-up-a-remote-notification-server",
      "kind": "article",
      "role": "article",
      "title": "Setting up a remote notification server",
      "type": "topic",
      "url": "/documentation/UserNotifications/setting-up-a-remote-notification-server"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.watchkit/documentation/WatchKit": {
      "abstract": [
        {
          "text": "Build watchOS apps that use features the app delegate monitors or controls, such as background tasks and extended runtime sessions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WatchKit",
      "type": "topic",
      "url": "/documentation/watchkit"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKApplication": {
      "abstract": [
        {
          "text": "The centralized point of control and coordination for apps with a single watchOS app target.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKApplication"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKApplication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKApplication"
        }
      ],
      "role": "symbol",
      "title": "WKApplication",
      "type": "topic",
      "url": "/documentation/watchkit/wkapplication"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKApplication/isRegisteredForRemoteNotifications": {
      "abstract": [
        {
          "text": "A Boolean value that indicates if the app has successfully registered for remote notifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isRegisteredForRemoteNotifications"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKApplication/isRegisteredForRemoteNotifications",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "registeredForRemoteNotifications"
        }
      ],
      "role": "symbol",
      "title": "isRegisteredForRemoteNotifications",
      "type": "topic",
      "url": "/documentation/watchkit/wkapplication/isregisteredforremotenotifications"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKApplication/registerForRemoteNotifications()": {
      "abstract": [
        {
          "text": "Register to receive remote notifications from the Apple Push Notification service (APNs).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "registerForRemoteNotifications"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKApplication/registerForRemoteNotifications()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "registerForRemoteNotifications"
        }
      ],
      "role": "symbol",
      "title": "registerForRemoteNotifications()",
      "type": "topic",
      "url": "/documentation/watchkit/wkapplication/registerforremotenotifications()"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKApplication/unregisterForRemoteNotifications()": {
      "abstract": [
        {
          "text": "Unregister for all remote notifications received from Apple Push Notification service (APNs).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unregisterForRemoteNotifications"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKApplication/unregisterForRemoteNotifications()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "unregisterForRemoteNotifications"
        }
      ],
      "role": "symbol",
      "title": "unregisterForRemoteNotifications()",
      "type": "topic",
      "url": "/documentation/watchkit/wkapplication/unregisterforremotenotifications()"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/didFailToRegisterForRemoteNotificationsWithError(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that Apple Push Notification service (APNs) can’t successfully complete the registration process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didFailToRegisterForRemoteNotificationsWithError"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/didFailToRegisterForRemoteNotificationsWithError(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "didFailToRegisterForRemoteNotificationsWithError:"
        }
      ],
      "role": "symbol",
      "title": "didFailToRegisterForRemoteNotificationsWithError(_:)",
      "type": "topic",
      "url": "/documentation/watchkit/wkapplicationdelegate/didfailtoregisterforremotenotificationswitherror(_:)"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/didRegisterForRemoteNotifications(withDeviceToken:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the app successfully registered with Apple Push Notification service (APNs).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didRegisterForRemoteNotifications"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withDeviceToken"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/didRegisterForRemoteNotifications(withDeviceToken:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "didRegisterForRemoteNotificationsWithDeviceToken:"
        }
      ],
      "role": "symbol",
      "title": "didRegisterForRemoteNotifications(withDeviceToken:)",
      "type": "topic",
      "url": "/documentation/watchkit/wkapplicationdelegate/didregisterforremotenotifications(withdevicetoken:)"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "https://help.apple.com/xcode/mac/current/#/devdfd3d04a1": {
      "identifier": "https://help.apple.com/xcode/mac/current/#/devdfd3d04a1",
      "title": "Enable push notifications",
      "titleInlineContent": [
        {
          "text": "Enable push notifications",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://help.apple.com/xcode/mac/current/#/devdfd3d04a1"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Registering-for-remote-notifications",
      "generated": true,
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKApplication/unregisterForRemoteNotifications()",
        "doc://com.apple.watchkit/documentation/WatchKit/WKApplication/isRegisteredForRemoteNotifications"
      ],
      "title": "Registering for remote notifications"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "registerForRemoteNotifications"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "registerForRemoteNotifications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.watchkit/documentation/WatchKit",
                "doc://com.apple.watchkit/documentation/WatchKit/WKApplication"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Registering-for-remote-notifications",
              "generated": true,
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKApplication/unregisterForRemoteNotifications()",
                "doc://com.apple.watchkit/documentation/WatchKit/WKApplication/isRegisteredForRemoteNotifications"
              ],
              "title": "Registering for remote notifications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "registerForRemoteNotifications"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UserNotifications~1UNUserNotificationCenter/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UNUserNotificationCenter"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplication~1isRegisteredForRemoteNotifications/title",
          "value": "registeredForRemoteNotifications"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplication~1isRegisteredForRemoteNotifications/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "registeredForRemoteNotifications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplication/title",
          "value": "WKApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplication/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplication~1registerForRemoteNotifications()/title",
          "value": "registerForRemoteNotifications"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplication~1registerForRemoteNotifications()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "registerForRemoteNotifications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate~1didFailToRegisterForRemoteNotificationsWithError(_:)/title",
          "value": "didFailToRegisterForRemoteNotificationsWithError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate~1didFailToRegisterForRemoteNotificationsWithError(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "didFailToRegisterForRemoteNotificationsWithError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UserNotifications~1UNUserNotificationCenter~1requestAuthorization(options:completionHandler:)/title",
          "value": "requestAuthorizationWithOptions:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UserNotifications~1UNUserNotificationCenter~1requestAuthorization(options:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "requestAuthorizationWithOptions:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@UNAuthorizationOptions",
              "text": "UNAuthorizationOptions"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "options"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "completionHandler:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": " (^)("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "granted"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSError",
              "text": "NSError"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "error"
            },
            {
              "kind": "text",
              "text": ")) "
            },
            {
              "kind": "internalParam",
              "text": "completionHandler"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplication~1unregisterForRemoteNotifications()/title",
          "value": "unregisterForRemoteNotifications"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplication~1unregisterForRemoteNotifications()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "unregisterForRemoteNotifications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate~1didRegisterForRemoteNotifications(withDeviceToken:)/title",
          "value": "didRegisterForRemoteNotificationsWithDeviceToken:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate~1didRegisterForRemoteNotifications(withDeviceToken:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "didRegisterForRemoteNotificationsWithDeviceToken:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/watchkit/wkapplication/registerforremotenotifications()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/watchkit/wkapplication/registerforremotenotifications()"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
