{
  "abstract": [
    {
      "text": "The directionality of user interface elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit",
        "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/userInterfaceDirectionPolicy"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)WKWebViewConfiguration(py)userInterfaceDirectionPolicy",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "userInterfaceDirectionPolicy"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@WKUserInterfaceDirectionPolicy",
        "text": "WKUserInterfaceDirectionPolicy"
      }
    ],
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "userInterfaceDirectionPolicy"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "userInterfaceDirectionPolicy"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "userInterfaceDirectionPolicy"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.webkit/documentation/WebKit/WKUserInterfaceDirectionPolicy",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@WKUserInterfaceDirectionPolicy",
              "text": "WKUserInterfaceDirectionPolicy"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The default value is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.webkit/documentation/WebKit/WKUserInterfaceDirectionPolicy/content",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". For other possible values, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.webkit/documentation/WebKit/WKUserInterfaceDirectionPolicy",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKUserInterfaceDirectionPolicy": {
      "abstract": [
        {
          "text": "The policy that determines the directionality of user interface elements in a web view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKUserInterfaceDirectionPolicy"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKUserInterfaceDirectionPolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKUserInterfaceDirectionPolicy"
        }
      ],
      "role": "symbol",
      "title": "WKUserInterfaceDirectionPolicy",
      "type": "topic",
      "url": "/documentation/webkit/wkuserinterfacedirectionpolicy"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKUserInterfaceDirectionPolicy/content": {
      "abstract": [
        {
          "text": "The directionality follows the CSS/HTML/XHTML specifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "content"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKUserInterfaceDirectionPolicy/content",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKUserInterfaceDirectionPolicyContent"
        }
      ],
      "role": "symbol",
      "title": "WKUserInterfaceDirectionPolicy.content",
      "type": "topic",
      "url": "/documentation/webkit/wkuserinterfacedirectionpolicy/content"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration": {
      "abstract": [
        {
          "text": "A collection of properties that you use to initialize a web view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKWebViewConfiguration"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebViewConfiguration"
        }
      ],
      "role": "symbol",
      "title": "WKWebViewConfiguration",
      "type": "topic",
      "url": "/documentation/webkit/wkwebviewconfiguration"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/userInterfaceDirectionPolicy": {
      "abstract": [
        {
          "text": "The directionality of user interface elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userInterfaceDirectionPolicy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKUserInterfaceDirectionPolicy",
          "text": "WKUserInterfaceDirectionPolicy"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration/userInterfaceDirectionPolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "userInterfaceDirectionPolicy"
        }
      ],
      "role": "symbol",
      "title": "userInterfaceDirectionPolicy",
      "type": "topic",
      "url": "/documentation/webkit/wkwebviewconfiguration/userinterfacedirectionpolicy"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Selecting-user-interface-directionality",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKUserInterfaceDirectionPolicy"
      ],
      "title": "Selecting user interface directionality"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "userInterfaceDirectionPolicy"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "userInterfaceDirectionPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.webkit/documentation/WebKit",
                "doc://com.apple.webkit/documentation/WebKit/WKWebViewConfiguration"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Selecting-user-interface-directionality",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKUserInterfaceDirectionPolicy"
              ],
              "title": "Selecting user interface directionality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.webkit/documentation/WebKit/WKUserInterfaceDirectionPolicy",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@WKUserInterfaceDirectionPolicy",
                    "text": "WKUserInterfaceDirectionPolicy"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "userInterfaceDirectionPolicy"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration/title",
          "value": "WKWebViewConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebViewConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebViewConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserInterfaceDirectionPolicy~1content/title",
          "value": "WKUserInterfaceDirectionPolicyContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserInterfaceDirectionPolicy~1content/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKUserInterfaceDirectionPolicyContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserInterfaceDirectionPolicy/title",
          "value": "WKUserInterfaceDirectionPolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserInterfaceDirectionPolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKUserInterfaceDirectionPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKUserInterfaceDirectionPolicy/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKUserInterfaceDirectionPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1userInterfaceDirectionPolicy/title",
          "value": "userInterfaceDirectionPolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebViewConfiguration~1userInterfaceDirectionPolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "userInterfaceDirectionPolicy"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/wkwebviewconfiguration/userinterfacedirectionpolicy"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/webkit/wkwebviewconfiguration/userinterfacedirectionpolicy"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
