{
  "abstract": [
    {
      "text": "An error that the message encoder encountered while determining the encoding status for the outgoing message.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mailkit/documentation/MailKit",
        "doc://com.apple.mailkit/documentation/MailKit/MEOutgoingMessageEncodingStatus"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mailkit/documentation/MailKit/MEOutgoingMessageEncodingStatus/securityError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MEOutgoingMessageEncodingStatus(py)securityError",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "securityError"
      },
      {
        "kind": "text",
        "text": ": (any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5ErrorP",
        "text": "Error"
      },
      {
        "kind": "text",
        "text": ")?"
      }
    ],
    "modules": [
      {
        "name": "MailKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "securityError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "securityError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "securityError"
            },
            {
              "kind": "text",
              "text": ": (any "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5ErrorP",
              "text": "Error"
            },
            {
              "kind": "text",
              "text": ")? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mailkit/documentation/MailKit": {
      "abstract": [
        {
          "text": "Secure, customize, and act on email messages that users send and receive.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MailKit",
      "type": "topic",
      "url": "/documentation/mailkit"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEOutgoingMessageEncodingStatus": {
      "abstract": [
        {
          "text": "An object that contains information about security measures the user can apply when composing a message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEOutgoingMessageEncodingStatus"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEOutgoingMessageEncodingStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEOutgoingMessageEncodingStatus"
        }
      ],
      "role": "symbol",
      "title": "MEOutgoingMessageEncodingStatus",
      "type": "topic",
      "url": "/documentation/mailkit/meoutgoingmessageencodingstatus"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEOutgoingMessageEncodingStatus/addressesFailingEncryption": {
      "abstract": [
        {
          "text": "An array of email addresses that prevent the message security handler from signing the message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addressesFailingEncryption"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MEEmailAddress",
          "text": "MEEmailAddress"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEOutgoingMessageEncodingStatus/addressesFailingEncryption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addressesFailingEncryption"
        }
      ],
      "role": "symbol",
      "title": "addressesFailingEncryption",
      "type": "topic",
      "url": "/documentation/mailkit/meoutgoingmessageencodingstatus/addressesfailingencryption"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEOutgoingMessageEncodingStatus/canEncrypt": {
      "abstract": [
        {
          "text": "A Boolean value that indicates the message security handler can encrypt the outgoing message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canEncrypt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEOutgoingMessageEncodingStatus/canEncrypt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canEncrypt"
        }
      ],
      "role": "symbol",
      "title": "canEncrypt",
      "type": "topic",
      "url": "/documentation/mailkit/meoutgoingmessageencodingstatus/canencrypt"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEOutgoingMessageEncodingStatus/canSign": {
      "abstract": [
        {
          "text": "A Boolean value that indicates the message security handler can digitally sign the outgoing message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canSign"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEOutgoingMessageEncodingStatus/canSign",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canSign"
        }
      ],
      "role": "symbol",
      "title": "canSign",
      "type": "topic",
      "url": "/documentation/mailkit/meoutgoingmessageencodingstatus/cansign"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEOutgoingMessageEncodingStatus/init(canSign:canEncrypt:securityError:addressesFailingEncryption:)": {
      "abstract": [
        {
          "text": "Creates an object that describes whether the message security handler can encrypt or sign an outgoing message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "canSign"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "canEncrypt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "securityError"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?, "
        },
        {
          "kind": "externalParam",
          "text": "addressesFailingEncryption"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MEEmailAddress",
          "text": "MEEmailAddress"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEOutgoingMessageEncodingStatus/init(canSign:canEncrypt:securityError:addressesFailingEncryption:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithCanSign:canEncrypt:securityError:addressesFailingEncryption:"
        }
      ],
      "role": "symbol",
      "title": "init(canSign:canEncrypt:securityError:addressesFailingEncryption:)",
      "type": "topic",
      "url": "/documentation/mailkit/meoutgoingmessageencodingstatus/init(cansign:canencrypt:securityerror:addressesfailingencryption:)"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEOutgoingMessageEncodingStatus/securityError": {
      "abstract": [
        {
          "text": "An error that the message encoder encountered while determining the encoding status for the outgoing message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "securityError"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEOutgoingMessageEncodingStatus/securityError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "securityError"
        }
      ],
      "role": "symbol",
      "title": "securityError",
      "type": "topic",
      "url": "/documentation/mailkit/meoutgoingmessageencodingstatus/securityerror"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Providing-Encoding-Status",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mailkit/documentation/MailKit/MEOutgoingMessageEncodingStatus/init(canSign:canEncrypt:securityError:addressesFailingEncryption:)",
        "doc://com.apple.mailkit/documentation/MailKit/MEOutgoingMessageEncodingStatus/canSign",
        "doc://com.apple.mailkit/documentation/MailKit/MEOutgoingMessageEncodingStatus/canEncrypt",
        "doc://com.apple.mailkit/documentation/MailKit/MEOutgoingMessageEncodingStatus/addressesFailingEncryption"
      ],
      "title": "Providing Encoding Status"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "securityError"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "securityError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mailkit/documentation/MailKit",
                "doc://com.apple.mailkit/documentation/MailKit/MEOutgoingMessageEncodingStatus"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Providing-Encoding-Status",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mailkit/documentation/MailKit/MEOutgoingMessageEncodingStatus/init(canSign:canEncrypt:securityError:addressesFailingEncryption:)",
                "doc://com.apple.mailkit/documentation/MailKit/MEOutgoingMessageEncodingStatus/canSign",
                "doc://com.apple.mailkit/documentation/MailKit/MEOutgoingMessageEncodingStatus/canEncrypt",
                "doc://com.apple.mailkit/documentation/MailKit/MEOutgoingMessageEncodingStatus/addressesFailingEncryption"
              ],
              "title": "Providing Encoding Status"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSError",
                    "text": "NSError"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "securityError"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEOutgoingMessageEncodingStatus~1canEncrypt/title",
          "value": "canEncrypt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEOutgoingMessageEncodingStatus~1canEncrypt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "canEncrypt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEOutgoingMessageEncodingStatus~1init(canSign:canEncrypt:securityError:addressesFailingEncryption:)/title",
          "value": "initWithCanSign:canEncrypt:securityError:addressesFailingEncryption:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEOutgoingMessageEncodingStatus~1init(canSign:canEncrypt:securityError:addressesFailingEncryption:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithCanSign:canEncrypt:securityError:addressesFailingEncryption:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEOutgoingMessageEncodingStatus~1addressesFailingEncryption/title",
          "value": "addressesFailingEncryption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEOutgoingMessageEncodingStatus~1addressesFailingEncryption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "addressesFailingEncryption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEOutgoingMessageEncodingStatus~1canSign/title",
          "value": "canSign"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEOutgoingMessageEncodingStatus~1canSign/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "canSign"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEOutgoingMessageEncodingStatus/title",
          "value": "MEOutgoingMessageEncodingStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEOutgoingMessageEncodingStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEOutgoingMessageEncodingStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEOutgoingMessageEncodingStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEOutgoingMessageEncodingStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEOutgoingMessageEncodingStatus~1securityError/title",
          "value": "securityError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEOutgoingMessageEncodingStatus~1securityError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "securityError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mailkit/meoutgoingmessageencodingstatus/securityerror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mailkit/meoutgoingmessageencodingstatus/securityerror"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
