{
  "abstract": [
    {
      "text": "Enumerates over a given range of the string and calls the specified block for each token.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTokenizer"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTokenizer/enumerateTokensInRange:usingBlock:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NLTokenizer(im)enumerateTokensInRange:usingBlock:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "enumerateTokensInRange:usingBlock:"
      }
    ],
    "modules": [
      {
        "name": "Natural Language"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "enumerateTokensInRange:usingBlock:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "enumerateTokensInRange:usingBlock:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "enumerateTokensInRange:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@S@_NSRange",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@_NSRange",
              "text": "NSRange"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "range"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "usingBlock:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": " (^)("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@S@_NSRange",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@_NSRange",
              "text": "NSRange"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "tokenRange"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTokenizer/Attributes",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NLTokenizerAttributes",
              "text": "NLTokenizerAttributes"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "flags"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "stop"
            },
            {
              "kind": "text",
              "text": ")) "
            },
            {
              "kind": "internalParam",
              "text": "block"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The range of the string to tokenize.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "range"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The closure to call after each token; return false if processing should stop.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "block"
        }
      ]
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/tokenizing-natural-language-text"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage": {
      "abstract": [
        {
          "text": "Analyze natural language text and deduce its language-specific metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage",
      "kind": "symbol",
      "role": "collection",
      "title": "Natural Language",
      "type": "topic",
      "url": "/documentation/naturallanguage"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTokenizer": {
      "abstract": [
        {
          "text": "A tokenizer that segments natural language text into semantic units.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NLTokenizer"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTokenizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTokenizer"
        }
      ],
      "role": "symbol",
      "title": "NLTokenizer",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltokenizer"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTokenizer/Attributes": {
      "abstract": [
        {
          "text": "Hints about the contents of the string for the tokenizer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Attributes"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTokenizer/Attributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Attributes"
        }
      ],
      "role": "symbol",
      "title": "NLTokenizer.Attributes",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltokenizer/attributes"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTokenizer/enumerateTokensInRange:usingBlock:": {
      "abstract": [
        {
          "text": "Enumerates over a given range of the string and calls the specified block for each token.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "enumerateTokensInRange:usingBlock:"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTokenizer/enumerateTokensInRange:usingBlock:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enumerateTokensInRange:usingBlock:"
        }
      ],
      "role": "symbol",
      "title": "enumerateTokensInRange:usingBlock:",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltokenizer/enumeratetokensinrange:usingblock:"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTokenizer/tokenRangeAtIndex:": {
      "abstract": [
        {
          "text": "Finds the range of the token at the given index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "tokenRangeAtIndex:"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTokenizer/tokenRangeAtIndex:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tokenRangeAtIndex:"
        }
      ],
      "role": "symbol",
      "title": "tokenRangeAtIndex:",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltokenizer/tokenrangeatindex:"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTokenizer/tokenRangeForRange:": {
      "abstract": [
        {
          "text": "Finds the entire range of all tokens contained completely or partially within the specified range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "tokenRangeForRange:"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTokenizer/tokenRangeForRange:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tokenRangeForRange:"
        }
      ],
      "role": "symbol",
      "title": "tokenRangeForRange:",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltokenizer/tokenrangeforrange:"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTokenizer/tokensForRange:": {
      "abstract": [
        {
          "text": "Tokenizes the string within the provided range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "tokensForRange:"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTokenizer/tokensForRange:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tokensForRange:"
        }
      ],
      "role": "symbol",
      "title": "tokensForRange:",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltokenizer/tokensforrange:"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/tokenizing-natural-language-text": {
      "abstract": [
        {
          "text": "Enumerate the words in a string.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/tokenizing-natural-language-text",
      "kind": "article",
      "role": "article",
      "title": "Tokenizing natural language text",
      "type": "topic",
      "url": "/documentation/naturallanguage/tokenizing-natural-language-text"
    },
    "doc://com.externally.resolved.symbol/c:@S@_NSRange": {
      "abstract": [
        {
          "text": "A Swift-only concrete structure that backs the range type alias.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "_NSRange"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@S@_NSRange",
      "kind": "symbol",
      "role": "symbol",
      "title": "_NSRange",
      "type": "topic",
      "url": "/documentation/foundation/nsrange-jio"
    },
    "doc://com.externally.resolved.symbol/c:@T@BOOL": {
      "abstract": [
        {
          "text": "Type to represent a Boolean value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
      "kind": "symbol",
      "role": "symbol",
      "title": "BOOL",
      "type": "topic",
      "url": "/documentation/objectivec/bool"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerating-the-tokens",
      "generated": true,
      "identifiers": [
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTokenizer/tokensForRange:",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTokenizer/tokenRangeAtIndex:",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTokenizer/tokenRangeForRange:"
      ],
      "title": "Enumerating the tokens"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTokenizer~1Attributes/title",
          "value": "NLTokenizerAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTokenizer~1Attributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTokenizerAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTokenizer~1Attributes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTokenizerAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTokenizer/title",
          "value": "NLTokenizer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTokenizer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTokenizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTokenizer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTokenizer"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/naturallanguage/nltokenizer/enumeratetokensinrange:usingblock:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
