{
  "abstract": [
    {
      "text": "The log level that captures error information.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLLogLevel"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLLogLevel/error"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLLogLevel@MTLLogLevelError",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "error"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLLogLevelError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MTLLogLevel.error"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "error"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLLogLevel": {
      "abstract": [
        {
          "text": "The supported log levels for shader logging.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLLogLevel"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLLogLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLLogLevel"
        }
      ],
      "role": "symbol",
      "title": "MTLLogLevel",
      "type": "topic",
      "url": "/documentation/metal/mtlloglevel"
    },
    "doc://com.apple.metal/documentation/Metal/MTLLogLevel/debug": {
      "abstract": [
        {
          "text": "The log level that captures diagnostic information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "debug"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLLogLevel/debug",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLLogLevelDebug"
        }
      ],
      "role": "symbol",
      "title": "MTLLogLevel.debug",
      "type": "topic",
      "url": "/documentation/metal/mtlloglevel/debug"
    },
    "doc://com.apple.metal/documentation/Metal/MTLLogLevel/error": {
      "abstract": [
        {
          "text": "The log level that captures error information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "error"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLLogLevel/error",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLLogLevelError"
        }
      ],
      "role": "symbol",
      "title": "MTLLogLevel.error",
      "type": "topic",
      "url": "/documentation/metal/mtlloglevel/error"
    },
    "doc://com.apple.metal/documentation/Metal/MTLLogLevel/fault": {
      "abstract": [
        {
          "text": "The log level that captures fault information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fault"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLLogLevel/fault",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLLogLevelFault"
        }
      ],
      "role": "symbol",
      "title": "MTLLogLevel.fault",
      "type": "topic",
      "url": "/documentation/metal/mtlloglevel/fault"
    },
    "doc://com.apple.metal/documentation/Metal/MTLLogLevel/info": {
      "abstract": [
        {
          "text": "The log level that captures additional information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "info"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLLogLevel/info",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLLogLevelInfo"
        }
      ],
      "role": "symbol",
      "title": "MTLLogLevel.info",
      "type": "topic",
      "url": "/documentation/metal/mtlloglevel/info"
    },
    "doc://com.apple.metal/documentation/Metal/MTLLogLevel/notice": {
      "abstract": [
        {
          "text": "The log level that captures notifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notice"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLLogLevel/notice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLLogLevelNotice"
        }
      ],
      "role": "symbol",
      "title": "MTLLogLevel.notice",
      "type": "topic",
      "url": "/documentation/metal/mtlloglevel/notice"
    },
    "doc://com.apple.metal/documentation/Metal/MTLLogLevel/undefined": {
      "abstract": [
        {
          "text": "The log level when the log level hasn’t been configured.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "undefined"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLLogLevel/undefined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLLogLevelUndefined"
        }
      ],
      "role": "symbol",
      "title": "MTLLogLevel.undefined",
      "type": "topic",
      "url": "/documentation/metal/mtlloglevel/undefined"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLLogLevel/debug",
        "doc://com.apple.metal/documentation/Metal/MTLLogLevel/info",
        "doc://com.apple.metal/documentation/Metal/MTLLogLevel/notice",
        "doc://com.apple.metal/documentation/Metal/MTLLogLevel/fault",
        "doc://com.apple.metal/documentation/Metal/MTLLogLevel/undefined"
      ],
      "title": "Enumeration Cases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLLogLevelError"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLLogLevelError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal",
                "doc://com.apple.metal/documentation/Metal/MTLLogLevel"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLLogLevel/debug",
                "doc://com.apple.metal/documentation/Metal/MTLLogLevel/info",
                "doc://com.apple.metal/documentation/Metal/MTLLogLevel/notice",
                "doc://com.apple.metal/documentation/Metal/MTLLogLevel/fault",
                "doc://com.apple.metal/documentation/Metal/MTLLogLevel/undefined"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MTLLogLevelError"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLogLevel~1info/title",
          "value": "MTLLogLevelInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLogLevel~1info/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLLogLevelInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLogLevel~1fault/title",
          "value": "MTLLogLevelFault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLogLevel~1fault/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLLogLevelFault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLogLevel/title",
          "value": "MTLLogLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLogLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLLogLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLogLevel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLLogLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLogLevel~1notice/title",
          "value": "MTLLogLevelNotice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLogLevel~1notice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLLogLevelNotice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLogLevel~1error/title",
          "value": "MTLLogLevelError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLogLevel~1error/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLLogLevelError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLogLevel~1undefined/title",
          "value": "MTLLogLevelUndefined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLogLevel~1undefined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLLogLevelUndefined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLogLevel~1debug/title",
          "value": "MTLLogLevelDebug"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLogLevel~1debug/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLLogLevelDebug"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlloglevel/error"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlloglevel/error"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
