{
  "abstract": [
    {
      "text": "Returns a new template from the provided image, fill fraction, and ring style.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.clockkit/documentation/ClockKit",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateUtilitarianSmallRingImage"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateUtilitarianSmallRingImage/templateWithImageProvider:fillFraction:ringStyle:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CLKComplicationTemplateUtilitarianSmallRingImage(cm)templateWithImageProvider:fillFraction:ringStyle:",
    "fragments": [
      {
        "kind": "text",
        "text": "+ "
      },
      {
        "kind": "identifier",
        "text": "templateWithImageProvider:fillFraction:ringStyle:"
      }
    ],
    "modules": [
      {
        "name": "ClockKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "templateWithImageProvider:fillFraction:ringStyle:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.0",
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "templateWithImageProvider:fillFraction:ringStyle:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "+ ("
            },
            {
              "kind": "keyword",
              "text": "instancetype"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "templateWithImageProvider:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKImageProvider",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CLKImageProvider",
              "text": "CLKImageProvider"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "imageProvider"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "fillFraction:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:f",
              "text": "float"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "fillFraction"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ringStyle:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationRingStyle",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CLKComplicationRingStyle",
              "text": "CLKComplicationRingStyle"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "ringStyle"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The image provider for the main image. The system renders the image as a tinted template image, a bitmap image where only the opacity of the image matters. For more information, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/UIKit/providing-images-for-different-appearances#Create-tintable-images-using-template-images",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "imageProvider"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A value between ",
                  "type": "text"
                },
                {
                  "code": "0.0",
                  "type": "codeVoice"
                },
                {
                  "text": " and ",
                  "type": "text"
                },
                {
                  "code": "1.0",
                  "type": "codeVoice"
                },
                {
                  "text": " that indicates how much of the ring fills.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "fillFraction"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The ring’s style. For a complete list of styles, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationRingStyle",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "ringStyle"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.clockkit/documentation/ClockKit": {
      "abstract": [
        {
          "text": "Display app-specific data on the clock face.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ClockKit",
      "type": "topic",
      "url": "/documentation/clockkit"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationRingStyle": {
      "abstract": [
        {
          "text": "Constants indicating the appearance of a progress ring.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationRingStyle"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationRingStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationRingStyle"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationRingStyle",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationringstyle"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateUtilitarianSmallRingImage": {
      "abstract": [
        {
          "text": "A template for displaying an image encircled by a configurable progress ring",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateUtilitarianSmallRingImage"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateUtilitarianSmallRingImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateUtilitarianSmallRingImage"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationTemplateUtilitarianSmallRingImage",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplateutilitariansmallringimage"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateUtilitarianSmallRingImage/init(imageProvider:fillFraction:ringStyle:)": {
      "abstract": [
        {
          "text": "Creates a new template from the provided image, fill fraction, and ring style.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "imageProvider"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLKImageProvider",
          "text": "CLKImageProvider"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "fillFraction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "ringStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLKComplicationRingStyle",
          "text": "CLKComplicationRingStyle"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateUtilitarianSmallRingImage/init(imageProvider:fillFraction:ringStyle:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithImageProvider:fillFraction:ringStyle:"
        }
      ],
      "role": "symbol",
      "title": "init(imageProvider:fillFraction:ringStyle:)",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplateutilitariansmallringimage/init(imageprovider:fillfraction:ringstyle:)"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateUtilitarianSmallRingImage/templateWithImageProvider:fillFraction:ringStyle:": {
      "abstract": [
        {
          "text": "Returns a new template from the provided image, fill fraction, and ring style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "templateWithImageProvider:fillFraction:ringStyle:"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateUtilitarianSmallRingImage/templateWithImageProvider:fillFraction:ringStyle:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "templateWithImageProvider:fillFraction:ringStyle:"
        }
      ],
      "role": "symbol",
      "title": "templateWithImageProvider:fillFraction:ringStyle:",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplateutilitariansmallringimage/templatewithimageprovider:fillfraction:ringstyle:"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKImageProvider": {
      "abstract": [
        {
          "text": "An image displayed by a complication.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKImageProvider"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKImageProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKImageProvider"
        }
      ],
      "role": "symbol",
      "title": "CLKImageProvider",
      "type": "topic",
      "url": "/documentation/clockkit/clkimageprovider"
    },
    "doc://com.apple.documentation/documentation/UIKit/providing-images-for-different-appearances#Create-tintable-images-using-template-images": {
      "abstract": [
        {
          "text": "Supply image resources appropriate for light and dark appearances and for high-contrast environments.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/providing-images-for-different-appearances#Create-tintable-images-using-template-images",
      "kind": "article",
      "role": "article",
      "title": "Providing images for different appearances",
      "type": "topic",
      "url": "/documentation/UIKit/providing-images-for-different-appearances"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-the-Template",
      "generated": true,
      "identifiers": [
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateUtilitarianSmallRingImage/init(imageProvider:fillFraction:ringStyle:)"
      ],
      "title": "Creating the Template"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateUtilitarianSmallRingImage/title",
          "value": "CLKComplicationTemplateUtilitarianSmallRingImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateUtilitarianSmallRingImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateUtilitarianSmallRingImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateUtilitarianSmallRingImage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateUtilitarianSmallRingImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKImageProvider/title",
          "value": "CLKImageProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKImageProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKImageProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKImageProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKImageProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationRingStyle/title",
          "value": "CLKComplicationRingStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationRingStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationRingStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationRingStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationRingStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateUtilitarianSmallRingImage~1init(imageProvider:fillFraction:ringStyle:)/title",
          "value": "initWithImageProvider:fillFraction:ringStyle:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateUtilitarianSmallRingImage~1init(imageProvider:fillFraction:ringStyle:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithImageProvider:fillFraction:ringStyle:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/clockkit/clkcomplicationtemplateutilitariansmallringimage/templatewithimageprovider:fillfraction:ringstyle:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
