{
  "abstract": [
    {
      "text": "Error codes the CallKit framework returns.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.callkit/documentation/CallKit",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CXErrorCodeCallDirectoryManagerError",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "CallKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "CXErrorCodeCallDirectoryManagerError.Code"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Code"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.callkit/documentation/CallKit": {
      "abstract": [
        {
          "text": "Display the system-calling UI for your app’s VoIP services, and coordinate your calling services with other apps and the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CallKit",
      "type": "topic",
      "url": "/documentation/callkit"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryManager/EnabledStatus": {
      "abstract": [
        {
          "text": "The enabled status of a Call Directory app extension, as reported by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryManager/getEnabledStatusForExtension(withIdentifier:completionHandler:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EnabledStatus"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryManager/EnabledStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EnabledStatus"
        }
      ],
      "role": "symbol",
      "title": "CXCallDirectoryManager.EnabledStatus",
      "type": "topic",
      "url": "/documentation/callkit/cxcalldirectorymanager/enabledstatus"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryManager/getEnabledStatusForExtension(withIdentifier:completionHandler:)": {
      "abstract": [
        {
          "text": "Asynchronously returns the enabled status of the extension with the specified identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getEnabledStatusForExtension"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CXCallDirectoryManager",
          "text": "CXCallDirectoryManager"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CXCallDirectoryEnabledStatus",
          "text": "EnabledStatus"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryManager/getEnabledStatusForExtension(withIdentifier:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getEnabledStatusForExtensionWithIdentifier:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "getEnabledStatusForExtension(withIdentifier:completionHandler:)",
      "type": "topic",
      "url": "/documentation/callkit/cxcalldirectorymanager/getenabledstatusforextension(withidentifier:completionhandler:)"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct": {
      "abstract": [
        {
          "text": "Errors when interacting with a call directory manager.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CXErrorCodeCallDirectoryManagerError"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeCallDirectoryManagerError"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeCallDirectoryManagerError",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Error codes the CallKit framework returns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeCallDirectoryManagerError.Code",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct/code"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/currentlyLoading": {
      "abstract": [
        {
          "text": "The call directory manager is loading the app extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentlyLoading"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/currentlyLoading",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeCallDirectoryManagerErrorCurrentlyLoading"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeCallDirectoryManagerError.Code.currentlyLoading",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct/code/currentlyloading"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/duplicateEntries": {
      "abstract": [
        {
          "text": "There are duplicate entries in the call directory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "duplicateEntries"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/duplicateEntries",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeCallDirectoryManagerErrorDuplicateEntries"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeCallDirectoryManagerError.Code.duplicateEntries",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct/code/duplicateentries"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/entriesOutOfOrder": {
      "abstract": [
        {
          "text": "The entries in the call directory are out of order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "entriesOutOfOrder"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/entriesOutOfOrder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeCallDirectoryManagerErrorEntriesOutOfOrder"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeCallDirectoryManagerError.Code.entriesOutOfOrder",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct/code/entriesoutoforder"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/extensionDisabled": {
      "abstract": [
        {
          "text": "The call directory extension isn’t enabled by the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extensionDisabled"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/extensionDisabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeCallDirectoryManagerErrorExtensionDisabled"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeCallDirectoryManagerError.Code.extensionDisabled",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct/code/extensiondisabled"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct/code/init(rawvalue:)"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/loadingInterrupted": {
      "abstract": [
        {
          "text": "The call directory manager was interrupted while loading the app extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loadingInterrupted"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/loadingInterrupted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeCallDirectoryManagerErrorLoadingInterrupted"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeCallDirectoryManagerError.Code.loadingInterrupted",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct/code/loadinginterrupted"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/maximumEntriesExceeded": {
      "abstract": [
        {
          "text": "There are too many entries in the call directory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumEntriesExceeded"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/maximumEntriesExceeded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeCallDirectoryManagerErrorMaximumEntriesExceeded"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeCallDirectoryManagerError.Code.maximumEntriesExceeded",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct/code/maximumentriesexceeded"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/noExtensionFound": {
      "abstract": [
        {
          "text": "The call directory manager could not find a corresponding app extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noExtensionFound"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/noExtensionFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeCallDirectoryManagerErrorNoExtensionFound"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeCallDirectoryManagerError.Code.noExtensionFound",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct/code/noextensionfound"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/unexpectedIncrementalRemoval": {
      "abstract": [
        {
          "text": "A request occurred before confirming incremental loading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unexpectedIncrementalRemoval"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/unexpectedIncrementalRemoval",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeCallDirectoryManagerErrorUnexpectedIncrementalRemoval"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeCallDirectoryManagerError.Code.unexpectedIncrementalRemoval",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct/code/unexpectedincrementalremoval"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/unknown": {
      "abstract": [
        {
          "text": "An unknown error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeCallDirectoryManagerErrorUnknown"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeCallDirectoryManagerError.Code.unknown",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct/code/unknown"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorDomainCallDirectoryManager": {
      "abstract": [
        {
          "text": "Domain for errors when interacting with a call directory manager.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CXErrorDomainCallDirectoryManager"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorDomainCallDirectoryManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorDomainCallDirectoryManager"
        }
      ],
      "role": "symbol",
      "title": "CXErrorDomainCallDirectoryManager",
      "type": "topic",
      "url": "/documentation/callkit/cxerrordomaincalldirectorymanager"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryManager/EnabledStatus",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorDomainCallDirectoryManager"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/unknown",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/noExtensionFound",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/currentlyLoading",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/loadingInterrupted",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/entriesOutOfOrder",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/duplicateEntries",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/maximumEntriesExceeded",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/extensionDisabled",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/unexpectedIncrementalRemoval"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CXErrorCodeCallDirectoryManagerError"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeCallDirectoryManagerError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeCallDirectoryManagerError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.callkit/documentation/CallKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/unknown",
                "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/noExtensionFound",
                "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/currentlyLoading",
                "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/loadingInterrupted",
                "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/entriesOutOfOrder",
                "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/duplicateEntries",
                "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/maximumEntriesExceeded",
                "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/extensionDisabled",
                "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code/unexpectedIncrementalRemoval"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryManager/EnabledStatus",
                "doc://com.apple.callkit/documentation/CallKit/CXErrorDomainCallDirectoryManager"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CXErrorCodeCallDirectoryManagerError"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeCallDirectoryManagerError-swift.struct~1Code~1loadingInterrupted/title",
          "value": "CXErrorCodeCallDirectoryManagerErrorLoadingInterrupted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeCallDirectoryManagerError-swift.struct~1Code~1loadingInterrupted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeCallDirectoryManagerErrorLoadingInterrupted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeCallDirectoryManagerError-swift.struct~1Code~1duplicateEntries/title",
          "value": "CXErrorCodeCallDirectoryManagerErrorDuplicateEntries"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeCallDirectoryManagerError-swift.struct~1Code~1duplicateEntries/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeCallDirectoryManagerErrorDuplicateEntries"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorDomainCallDirectoryManager/title",
          "value": "CXErrorDomainCallDirectoryManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorDomainCallDirectoryManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorDomainCallDirectoryManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeCallDirectoryManagerError-swift.struct~1Code~1currentlyLoading/title",
          "value": "CXErrorCodeCallDirectoryManagerErrorCurrentlyLoading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeCallDirectoryManagerError-swift.struct~1Code~1currentlyLoading/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeCallDirectoryManagerErrorCurrentlyLoading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeCallDirectoryManagerError-swift.struct~1Code~1unknown/title",
          "value": "CXErrorCodeCallDirectoryManagerErrorUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeCallDirectoryManagerError-swift.struct~1Code~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeCallDirectoryManagerErrorUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeCallDirectoryManagerError-swift.struct~1Code~1unexpectedIncrementalRemoval/title",
          "value": "CXErrorCodeCallDirectoryManagerErrorUnexpectedIncrementalRemoval"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeCallDirectoryManagerError-swift.struct~1Code~1unexpectedIncrementalRemoval/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeCallDirectoryManagerErrorUnexpectedIncrementalRemoval"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeCallDirectoryManagerError-swift.struct~1Code~1extensionDisabled/title",
          "value": "CXErrorCodeCallDirectoryManagerErrorExtensionDisabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeCallDirectoryManagerError-swift.struct~1Code~1extensionDisabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeCallDirectoryManagerErrorExtensionDisabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeCallDirectoryManagerError-swift.struct~1Code~1maximumEntriesExceeded/title",
          "value": "CXErrorCodeCallDirectoryManagerErrorMaximumEntriesExceeded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeCallDirectoryManagerError-swift.struct~1Code~1maximumEntriesExceeded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeCallDirectoryManagerErrorMaximumEntriesExceeded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallDirectoryManager~1getEnabledStatusForExtension(withIdentifier:completionHandler:)/title",
          "value": "getEnabledStatusForExtensionWithIdentifier:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallDirectoryManager~1getEnabledStatusForExtension(withIdentifier:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "getEnabledStatusForExtensionWithIdentifier:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallDirectoryManager~1EnabledStatus/title",
          "value": "CXCallDirectoryEnabledStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallDirectoryManager~1EnabledStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXCallDirectoryEnabledStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallDirectoryManager~1EnabledStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CXCallDirectoryEnabledStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeCallDirectoryManagerError-swift.struct~1Code~1entriesOutOfOrder/title",
          "value": "CXErrorCodeCallDirectoryManagerErrorEntriesOutOfOrder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeCallDirectoryManagerError-swift.struct~1Code~1entriesOutOfOrder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeCallDirectoryManagerErrorEntriesOutOfOrder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeCallDirectoryManagerError-swift.struct~1Code/title",
          "value": "CXErrorCodeCallDirectoryManagerError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeCallDirectoryManagerError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeCallDirectoryManagerError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeCallDirectoryManagerError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeCallDirectoryManagerError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeCallDirectoryManagerError-swift.struct~1Code~1noExtensionFound/title",
          "value": "CXErrorCodeCallDirectoryManagerErrorNoExtensionFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeCallDirectoryManagerError-swift.struct~1Code~1noExtensionFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeCallDirectoryManagerErrorNoExtensionFound"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
