{
  "abstract": [
    {
      "text": "The entries in the call directory are out of order.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.callkit/documentation/CallKit",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/entriesOutOfOrder"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC36CXErrorCodeCallDirectoryManagerErrorLeV17entriesOutOfOrderSoAAVvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "entriesOutOfOrder"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SC36CXErrorCodeCallDirectoryManagerErrorLeV",
        "text": "CXErrorCodeCallDirectoryManagerError"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@CXErrorCodeCallDirectoryManagerError",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "CallKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "entriesOutOfOrder"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "entriesOutOfOrder"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SC36CXErrorCodeCallDirectoryManagerErrorLeV",
              "text": "CXErrorCodeCallDirectoryManagerError"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CXErrorCodeCallDirectoryManagerError",
              "text": "Code"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.callkit/documentation/CallKit": {
      "abstract": [
        {
          "text": "Display the system-calling UI for your app’s VoIP services, and coordinate your calling services with other apps and the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CallKit",
      "type": "topic",
      "url": "/documentation/callkit"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct": {
      "abstract": [
        {
          "text": "Errors when interacting with a call directory manager.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CXErrorCodeCallDirectoryManagerError"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeCallDirectoryManagerError"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeCallDirectoryManagerError",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Error codes the CallKit framework returns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeCallDirectoryManagerError.Code",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct/code"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/currentlyLoading": {
      "abstract": [
        {
          "text": "The call directory manager is loading the app extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentlyLoading"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC36CXErrorCodeCallDirectoryManagerErrorLeV",
          "text": "CXErrorCodeCallDirectoryManagerError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CXErrorCodeCallDirectoryManagerError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/currentlyLoading",
      "kind": "symbol",
      "role": "symbol",
      "title": "currentlyLoading",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct/currentlyloading"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/duplicateEntries": {
      "abstract": [
        {
          "text": "There are duplicate entries in the call directory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "duplicateEntries"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC36CXErrorCodeCallDirectoryManagerErrorLeV",
          "text": "CXErrorCodeCallDirectoryManagerError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CXErrorCodeCallDirectoryManagerError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/duplicateEntries",
      "kind": "symbol",
      "role": "symbol",
      "title": "duplicateEntries",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct/duplicateentries"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/entriesOutOfOrder": {
      "abstract": [
        {
          "text": "The entries in the call directory are out of order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "entriesOutOfOrder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC36CXErrorCodeCallDirectoryManagerErrorLeV",
          "text": "CXErrorCodeCallDirectoryManagerError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CXErrorCodeCallDirectoryManagerError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/entriesOutOfOrder",
      "kind": "symbol",
      "role": "symbol",
      "title": "entriesOutOfOrder",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct/entriesoutoforder"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/extensionDisabled": {
      "abstract": [
        {
          "text": "The call directory extension isn’t in an enabled state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extensionDisabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC36CXErrorCodeCallDirectoryManagerErrorLeV",
          "text": "CXErrorCodeCallDirectoryManagerError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CXErrorCodeCallDirectoryManagerError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/extensionDisabled",
      "kind": "symbol",
      "role": "symbol",
      "title": "extensionDisabled",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct/extensiondisabled"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/loadingInterrupted": {
      "abstract": [
        {
          "text": "The system interrupted the call directory manager while loading the app extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loadingInterrupted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC36CXErrorCodeCallDirectoryManagerErrorLeV",
          "text": "CXErrorCodeCallDirectoryManagerError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CXErrorCodeCallDirectoryManagerError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/loadingInterrupted",
      "kind": "symbol",
      "role": "symbol",
      "title": "loadingInterrupted",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct/loadinginterrupted"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/maximumEntriesExceeded": {
      "abstract": [
        {
          "text": "There are too many entries in the call directory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumEntriesExceeded"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC36CXErrorCodeCallDirectoryManagerErrorLeV",
          "text": "CXErrorCodeCallDirectoryManagerError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CXErrorCodeCallDirectoryManagerError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/maximumEntriesExceeded",
      "kind": "symbol",
      "role": "symbol",
      "title": "maximumEntriesExceeded",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct/maximumentriesexceeded"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/noExtensionFound": {
      "abstract": [
        {
          "text": "The call directory manager can’t find a corresponding app extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noExtensionFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC36CXErrorCodeCallDirectoryManagerErrorLeV",
          "text": "CXErrorCodeCallDirectoryManagerError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CXErrorCodeCallDirectoryManagerError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/noExtensionFound",
      "kind": "symbol",
      "role": "symbol",
      "title": "noExtensionFound",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct/noextensionfound"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/unexpectedIncrementalRemoval": {
      "abstract": [
        {
          "text": "A request occurred before confirming incremental loading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unexpectedIncrementalRemoval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC36CXErrorCodeCallDirectoryManagerErrorLeV",
          "text": "CXErrorCodeCallDirectoryManagerError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CXErrorCodeCallDirectoryManagerError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/unexpectedIncrementalRemoval",
      "kind": "symbol",
      "role": "symbol",
      "title": "unexpectedIncrementalRemoval",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct/unexpectedincrementalremoval"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/unknown": {
      "abstract": [
        {
          "text": "An unknown error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC36CXErrorCodeCallDirectoryManagerErrorLeV",
          "text": "CXErrorCodeCallDirectoryManagerError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CXErrorCodeCallDirectoryManagerError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/unknown",
      "kind": "symbol",
      "role": "symbol",
      "title": "unknown",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct/unknown"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/unknown",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/noExtensionFound",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/currentlyLoading",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/loadingInterrupted",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/duplicateEntries",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/maximumEntriesExceeded",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/extensionDisabled",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/unexpectedIncrementalRemoval"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeCallDirectoryManagerError-swift.struct~1Code/title",
          "value": "CXErrorCodeCallDirectoryManagerError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeCallDirectoryManagerError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeCallDirectoryManagerError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeCallDirectoryManagerError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeCallDirectoryManagerError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct/entriesoutoforder"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
