{"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.coremedia/documentation/CoreMedia","doc://com.apple.coremedia/documentation/CoreMedia/CMTimeRange"]]},"identifier":{"url":"doc://com.apple.coremedia/documentation/CoreMedia/CMTimeRange/intersection(_:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"identifiers":["doc://com.apple.coremedia/documentation/CoreMedia/CMTimeRange/union(_:)"],"anchor":"Combining-Time-Ranges","generated":true,"title":"Combining Time Ranges"}],"metadata":{"symbolKind":"method","roleHeading":"Instance Method","role":"symbol","title":"intersection(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"intersection"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CMTimeRange","preciseIdentifier":"c:@SA@CMTimeRange"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CMTimeRange","preciseIdentifier":"c:@SA@CMTimeRange"}],"platforms":[{"name":"iOS","deprecated":false,"introducedAt":"4.0","beta":false,"unavailable":false},{"name":"iPadOS","deprecated":false,"introducedAt":"4.0","beta":false,"unavailable":false},{"name":"Mac Catalyst","deprecated":false,"beta":false,"unavailable":false},{"name":"macOS","deprecated":false,"introducedAt":"10.7","beta":false,"unavailable":false},{"name":"tvOS","deprecated":false,"introducedAt":"9.0","beta":false,"unavailable":false},{"name":"visionOS","deprecated":false,"introducedAt":"1.0","beta":false,"unavailable":false},{"name":"watchOS","deprecated":false,"introducedAt":"6.0","beta":false,"unavailable":false}],"externalID":"s:So11CMTimeRangea9CoreMediaE12intersectionyA2BF","modules":[{"name":"Core Media"}],"extendedModule":"CoreMedia"},"abstract":[{"type":"text","text":"Returns a new time range with the time elements that are common to both this time range and the given time range."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"intersection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"otherRange","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CMTimeRange","kind":"typeIdentifier","preciseIdentifier":"c:@SA@CMTimeRange","identifier":"doc://com.apple.coremedia/documentation/CoreMedia/CMTimeRange"},{"text":") -> ","kind":"text"},{"text":"CMTimeRange","kind":"typeIdentifier","preciseIdentifier":"c:@SA@CMTimeRange","identifier":"doc://com.apple.coremedia/documentation/CoreMedia/CMTimeRange"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"]}],"kind":"declarations"},{"parameters":[{"name":"otherRange","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A time range to intersect."}]}]}],"kind":"parameters"},{"kind":"content","content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"A time range that represents the largest intersection of the input.","type":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/coremedia/cmtimerange/intersection(_:)"]}],"kind":"symbol","references":{"doc://com.apple.documentation/documentation/technologies":{"abstract":[{"text":"","type":"text"}],"type":"topic","role":"overview","kind":"technologies","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies"},"doc://com.apple.coremedia/documentation/CoreMedia":{"url":"/documentation/coremedia","abstract":[{"type":"text","text":"Represent time-based audio-visual assets with essential data types."}],"identifier":"doc://com.apple.coremedia/documentation/CoreMedia","title":"Core Media","role":"collection","type":"topic","kind":"symbol"},"doc://com.apple.coremedia/documentation/CoreMedia/CMTimeRange/intersection(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"intersection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CMTimeRange","preciseIdentifier":"c:@SA@CMTimeRange","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"CMTimeRange","preciseIdentifier":"c:@SA@CMTimeRange","kind":"typeIdentifier"}],"url":"/documentation/coremedia/cmtimerange/intersection(_:)","kind":"symbol","abstract":[{"text":"Returns a new time range with the time elements that are common to both this time range and the given time range.","type":"text"}],"title":"intersection(_:)","role":"symbol","type":"topic","identifier":"doc://com.apple.coremedia/documentation/CoreMedia/CMTimeRange/intersection(_:)"},"doc://com.apple.coremedia/documentation/CoreMedia/CMTimeRange/union(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"union"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@SA@CMTimeRange","text":"CMTimeRange"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@SA@CMTimeRange","text":"CMTimeRange"}],"url":"/documentation/coremedia/cmtimerange/union(_:)","kind":"symbol","abstract":[{"text":"Returns a new time range with the time elements of both this time range and the given time range.","type":"text"}],"title":"union(_:)","role":"symbol","type":"topic","identifier":"doc://com.apple.coremedia/documentation/CoreMedia/CMTimeRange/union(_:)"},"doc://com.apple.coremedia/documentation/CoreMedia/CMTimeRange":{"navigatorTitle":[{"kind":"identifier","text":"CMTimeRange"}],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CMTimeRange"}],"url":"/documentation/coremedia/cmtimerange","role":"symbol","abstract":[{"text":"A structure that represents a time range.","type":"text"}],"identifier":"doc://com.apple.coremedia/documentation/CoreMedia/CMTimeRange","type":"topic","title":"CMTimeRange"}},"variantOverrides":[{"patch":[{"op":"replace","value":"CMTimeRange","path":"/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeRange/title"},{"op":"replace","value":[{"text":"CMTimeRange","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeRange/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"CMTimeRange"}],"path":"/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeRange/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}