{
  "abstract": [
    {
      "text": "The singleton thumbnail generator instance.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing",
        "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/shared"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)QLThumbnailGenerator(cpy)sharedGenerator",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "shared"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)QLThumbnailGenerator",
        "text": "QLThumbnailGenerator"
      }
    ],
    "modules": [
      {
        "name": "Quick Look Thumbnailing"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "sharedGenerator"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "shared"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "shared"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)QLThumbnailGenerator",
              "text": "QLThumbnailGenerator"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing": {
      "abstract": [
        {
          "text": "Generate thumbnails for common file types and add a Thumbnail Extension to your app to enable others to create thumbnails of your custom files.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing",
      "kind": "symbol",
      "role": "collection",
      "title": "Quick Look Thumbnailing",
      "type": "topic",
      "url": "/documentation/quicklookthumbnailing"
    },
    "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator": {
      "abstract": [
        {
          "text": "An object that generates thumbnail images based on provided requirements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLThumbnailGenerator"
        }
      ],
      "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLThumbnailGenerator"
        }
      ],
      "role": "symbol",
      "title": "QLThumbnailGenerator",
      "type": "topic",
      "url": "/documentation/quicklookthumbnailing/qlthumbnailgenerator"
    },
    "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/shared": {
      "abstract": [
        {
          "text": "The singleton thumbnail generator instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shared"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)QLThumbnailGenerator",
          "text": "QLThumbnailGenerator"
        }
      ],
      "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator/shared",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sharedGenerator"
        }
      ],
      "role": "symbol",
      "title": "shared",
      "type": "topic",
      "url": "/documentation/quicklookthumbnailing/qlthumbnailgenerator/shared"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "sharedGenerator"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sharedGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing",
                "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "class"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.quicklookthumbnailing/documentation/QuickLookThumbnailing/QLThumbnailGenerator",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)QLThumbnailGenerator",
                    "text": "QLThumbnailGenerator"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "sharedGenerator"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailGenerator~1shared/title",
          "value": "sharedGenerator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailGenerator~1shared/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sharedGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailGenerator/title",
          "value": "QLThumbnailGenerator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailGenerator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLThumbnailGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookthumbnailing~1documentation~1QuickLookThumbnailing~1QLThumbnailGenerator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLThumbnailGenerator"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quicklookthumbnailing/qlthumbnailgenerator/shared"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quicklookthumbnailing/qlthumbnailgenerator/shared"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
