{
  "abstract": [
    {
      "text": "Returns the range of the marked text.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSTextInput"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSTextInput/markedRange"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NSTextInput(im)markedRange",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "markedRange"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "markedRange"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.6",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "markedRange"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@S@_NSRange",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@_NSRange",
              "text": "NSRange"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "markedRange"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The range of marked text.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The returned range measures from the start of the receiver’s text storage. The return value’s ",
              "type": "text"
            },
            {
              "code": "location",
              "type": "codeVoice"
            },
            {
              "text": " is ",
              "type": "text"
            },
            {
              "code": "NSNotFound",
              "type": "codeVoice"
            },
            {
              "text": ", and its ",
              "type": "text"
            },
            {
              "code": "length",
              "type": "codeVoice"
            },
            {
              "text": " is 0 if and only if ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInput/hasMarkedText",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " returns ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/false",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInput": {
      "abstract": [
        {
          "text": "A set of methods that text views need to implement to interact properly with the text input management system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextInput"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextInput"
        }
      ],
      "role": "symbol",
      "title": "NSTextInput",
      "type": "topic",
      "url": "/documentation/appkit/nstextinput"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInput/hasMarkedText": {
      "abstract": [
        {
          "text": "Returns a Boolean value indicating whether or not the receiver has marked text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "hasMarkedText"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInput/hasMarkedText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hasMarkedText"
        }
      ],
      "role": "symbol",
      "title": "hasMarkedText",
      "type": "topic",
      "url": "/documentation/appkit/nstextinput/hasmarkedtext"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInput/markedRange": {
      "abstract": [
        {
          "text": "Returns the range of the marked text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "markedRange"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInput/markedRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "markedRange"
        }
      ],
      "role": "symbol",
      "title": "markedRange",
      "type": "topic",
      "url": "/documentation/appkit/nstextinput/markedrange"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInput/selectedRange": {
      "abstract": [
        {
          "text": "Returns the range of selected text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "selectedRange"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInput/selectedRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectedRange"
        }
      ],
      "role": "symbol",
      "title": "selectedRange",
      "type": "topic",
      "url": "/documentation/appkit/nstextinput/selectedrange"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInput/setMarkedText:selectedRange:": {
      "abstract": [
        {
          "text": "Replaces currently marked text in the receiver’s text storage with the given string and sets the selection to the given range, computed from the beginning of the marked text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setMarkedText:selectedRange:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInput/setMarkedText:selectedRange:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setMarkedText:selectedRange:"
        }
      ],
      "role": "symbol",
      "title": "setMarkedText:selectedRange:",
      "type": "topic",
      "url": "/documentation/appkit/nstextinput/setmarkedtext:selectedrange:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInput/unmarkText": {
      "abstract": [
        {
          "text": "Removes any marking from pending input text and disposes of the marked text as it wishes. The text view should accept the marked text as if it had been inserted normally.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "unmarkText"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInput/unmarkText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "unmarkText"
        }
      ],
      "role": "symbol",
      "title": "unmarkText",
      "type": "topic",
      "url": "/documentation/appkit/nstextinput/unmarktext"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInput/validAttributesForMarkedText": {
      "abstract": [
        {
          "text": "Returns an array of names for the attributes supported by the receiver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "validAttributesForMarkedText"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInput/validAttributesForMarkedText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "validAttributesForMarkedText"
        }
      ],
      "role": "symbol",
      "title": "validAttributesForMarkedText",
      "type": "topic",
      "url": "/documentation/appkit/nstextinput/validattributesformarkedtext"
    },
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@S@_NSRange": {
      "abstract": [
        {
          "text": "A Swift-only concrete structure that backs the range type alias.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "_NSRange"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@S@_NSRange",
      "kind": "symbol",
      "role": "symbol",
      "title": "_NSRange",
      "type": "topic",
      "url": "/documentation/foundation/nsrange-jio"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Marked-text",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextInput/hasMarkedText",
        "doc://com.apple.appkit/documentation/AppKit/NSTextInput/selectedRange",
        "doc://com.apple.appkit/documentation/AppKit/NSTextInput/setMarkedText:selectedRange:",
        "doc://com.apple.appkit/documentation/AppKit/NSTextInput/unmarkText",
        "doc://com.apple.appkit/documentation/AppKit/NSTextInput/validAttributesForMarkedText"
      ],
      "title": "Marked text"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInput/title",
          "value": "NSTextInput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInput"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nstextinput/markedrange"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
