{"abstract":[{"type":"text","text":"A CredentialSession event has triggered a UIKit scene creation."}],"metadata":{"platforms":[{"name":"iOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"17.4"},{"name":"iPadOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"17.4"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"credentialSessionEvent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:30_SecureElementCredential_UIKit0C23SessionWindowSceneEventO","text":"CredentialSessionWindowSceneEvent"},{"kind":"text","text":"?"}],"symbolKind":"property","title":"credentialSessionEvent","modules":[{"name":"SecureElementCredential","relatedModules":["UIKit"]}],"roleHeading":"Instance Property","role":"symbol","extendedModule":"UIKit","externalID":"s:So24UISceneConnectionOptionsC30_SecureElementCredential_UIKitE22credentialSessionEventAC0fi11WindowSceneJ0OSgvp"},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"@preconcurrency","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"credentialSessionEvent","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CredentialSessionWindowSceneEvent","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:30_SecureElementCredential_UIKit0C23SessionWindowSceneEventO","preciseIdentifier":"s:30_SecureElementCredential_UIKit0C23SessionWindowSceneEventO"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS","iPadOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIScene","doc://com.apple.uikit/documentation/UIKit/UIScene/ConnectionOptions"]]},"kind":"symbol","variants":[{"paths":["/documentation/uikit/uiscene/connectionoptions/credentialsessionevent"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIScene/ConnectionOptions/credentialSessionEvent","interfaceLanguage":"swift"},"references":{"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIScene/ConnectionOptions/credentialSessionEvent":{"type":"topic","kind":"symbol","role":"symbol","title":"credentialSessionEvent","url":"/documentation/uikit/uiscene/connectionoptions/credentialsessionevent","abstract":[{"type":"text","text":"A CredentialSession event has triggered a UIKit scene creation."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIScene/ConnectionOptions/credentialSessionEvent","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"credentialSessionEvent"},{"kind":"text","text":": "},{"preciseIdentifier":"s:30_SecureElementCredential_UIKit0C23SessionWindowSceneEventO","kind":"typeIdentifier","text":"CredentialSessionWindowSceneEvent"},{"kind":"text","text":"?"}]},"doc://com.externally.resolved.symbol/s:30_SecureElementCredential_UIKit0C23SessionWindowSceneEventO":{"type":"topic","url":"/documentation/SecureElementCredential/CredentialSessionWindowSceneEvent","identifier":"doc://com.externally.resolved.symbol/s:30_SecureElementCredential_UIKit0C23SessionWindowSceneEventO","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CredentialSessionWindowSceneEvent"}],"title":"CredentialSessionWindowSceneEvent","abstract":[{"type":"text","text":"An event that a credential session sends to a UIKit scene."}],"role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIScene/ConnectionOptions":{"role":"symbol","abstract":[{"text":"A data object containing information about the reasons why UIKit created the scene.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConnectionOptions","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIScene/ConnectionOptions","title":"UIScene.ConnectionOptions","navigatorTitle":[{"text":"ConnectionOptions","kind":"identifier"}],"type":"topic","kind":"symbol","url":"/documentation/uikit/uiscene/connectionoptions"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIScene":{"abstract":[{"type":"text","text":"An object that represents one instance of your app’s user interface."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UIScene"}],"title":"UIScene","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIScene"}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIScene","url":"/documentation/uikit/uiscene"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScene~1ConnectionOptions/title","value":"UISceneConnectionOptions","op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScene~1ConnectionOptions/fragments","value":[{"text":"UISceneConnectionOptions","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScene~1ConnectionOptions/navigatorTitle","value":[{"text":"UISceneConnectionOptions","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScene/title","value":"UIScene"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScene/fragments","value":[{"text":"UIScene","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScene/navigatorTitle","value":[{"kind":"identifier","text":"UIScene"}]}]}],"diffAvailability":{"major":{"change":"added","platform":"Xcode","versions":["16.0","16.3 beta 2"]}},"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}