{
  "abstract": [
    {
      "text": "The balance an account reaches before you apply the automatic reload amount.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit",
        "doc://com.apple.passkit/documentation/PassKit/PKAutomaticReloadPaymentSummaryItem"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKAutomaticReloadPaymentSummaryItem/thresholdAmount"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PKAutomaticReloadPaymentSummaryItem(py)thresholdAmount",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "thresholdAmount"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSDecimalNumber",
        "text": "NSDecimalNumber"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "thresholdAmount"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "thresholdAmount"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "thresholdAmount"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSDecimalNumber",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSDecimalNumber",
              "text": "NSDecimalNumber"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You automatically apply the reload amount to the account when the account balance drops below the threshold amount.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentSummaryItem/amount",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property to specify the reload amount.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAutomaticReloadPaymentSummaryItem": {
      "abstract": [
        {
          "text": "An object that defines a summary item for an automatic reload or refill payment, such as a store card top-up.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKAutomaticReloadPaymentSummaryItem"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAutomaticReloadPaymentSummaryItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAutomaticReloadPaymentSummaryItem"
        }
      ],
      "role": "symbol",
      "title": "PKAutomaticReloadPaymentSummaryItem",
      "type": "topic",
      "url": "/documentation/passkit/pkautomaticreloadpaymentsummaryitem"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAutomaticReloadPaymentSummaryItem/thresholdAmount": {
      "abstract": [
        {
          "text": "The balance an account reaches before you apply the automatic reload amount.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "thresholdAmount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDecimalNumber",
          "text": "NSDecimalNumber"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAutomaticReloadPaymentSummaryItem/thresholdAmount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "thresholdAmount"
        }
      ],
      "role": "symbol",
      "title": "thresholdAmount",
      "type": "topic",
      "url": "/documentation/passkit/pkautomaticreloadpaymentsummaryitem/thresholdamount"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentSummaryItem/amount": {
      "abstract": [
        {
          "text": "The summary item’s amount.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "amount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDecimalNumber",
          "text": "NSDecimalNumber"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentSummaryItem/amount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "amount"
        }
      ],
      "role": "symbol",
      "title": "amount",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentsummaryitem/amount"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSDecimalNumber": {
      "abstract": [
        {
          "text": "An object for representing and performing arithmetic on base-10 numbers that bridges to ; use  when you need reference semantics or other Foundation-specific behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSDecimalNumber"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSDecimalNumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSDecimalNumber",
      "type": "topic",
      "url": "/documentation/foundation/nsdecimalnumber"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "thresholdAmount"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "thresholdAmount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit",
                "doc://com.apple.passkit/documentation/PassKit/PKAutomaticReloadPaymentSummaryItem"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSDecimalNumber",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSDecimalNumber",
                    "text": "NSDecimalNumber"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "thresholdAmount"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSDecimalNumber/abstract",
          "value": [
            {
              "text": "An object for representing and performing arithmetic on base-10 numbers.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAutomaticReloadPaymentSummaryItem~1thresholdAmount/title",
          "value": "thresholdAmount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAutomaticReloadPaymentSummaryItem~1thresholdAmount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "thresholdAmount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAutomaticReloadPaymentSummaryItem/title",
          "value": "PKAutomaticReloadPaymentSummaryItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAutomaticReloadPaymentSummaryItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAutomaticReloadPaymentSummaryItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAutomaticReloadPaymentSummaryItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAutomaticReloadPaymentSummaryItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentSummaryItem~1amount/title",
          "value": "amount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentSummaryItem~1amount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "amount"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkautomaticreloadpaymentsummaryitem/thresholdamount"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pkautomaticreloadpaymentsummaryitem/thresholdamount"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
