{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.quartzcore/documentation/QuartzCore/CAPropertyAnimation/isCumulative","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isCumulative","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","identifier":"doc://com.externally.resolved.symbol/s:Sb","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"},{"content":[{"type":"heading","anchor":"Discussion","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"If "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/true"},{"type":"text","text":", then the value of the property is the value at the end of the previous repeat cycle, plus the value of the current repeat cycle. If "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/false"},{"type":"text","text":", the value of the property is simply the value calculated for the current repeat cycle. The default is "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/false"},{"type":"text","text":"."}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/quartzcore/capropertyanimation/iscumulative"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/quartzcore/capropertyanimation/iscumulative"]}],"kind":"symbol","sections":[],"seeAlsoSections":[{"identifiers":["doc://com.apple.quartzcore/documentation/QuartzCore/CAPropertyAnimation/isAdditive","doc://com.apple.quartzcore/documentation/QuartzCore/CAPropertyAnimation/valueFunction"],"anchor":"Property-Value-Calculation-Behavior","title":"Property Value Calculation Behavior","generated":true}],"abstract":[{"type":"text","text":"Determines if the value of the property is the value at the end of the previous repeat cycle, plus the value of the current repeat cycle."}],"metadata":{"role":"symbol","platforms":[{"beta":false,"deprecated":false,"name":"iOS","unavailable":false,"introducedAt":"2.0"},{"beta":false,"deprecated":false,"name":"iPadOS","unavailable":false,"introducedAt":"2.0"},{"beta":false,"deprecated":false,"name":"Mac Catalyst","unavailable":false,"introducedAt":"13.1"},{"beta":false,"deprecated":false,"name":"macOS","unavailable":false,"introducedAt":"10.5"},{"beta":false,"deprecated":false,"name":"tvOS","unavailable":false,"introducedAt":"9.0"},{"beta":false,"deprecated":false,"name":"visionOS","unavailable":false,"introducedAt":"1.0"}],"title":"isCumulative","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isCumulative","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"symbolKind":"property","externalID":"c:objc(cs)CAPropertyAnimation(py)cumulative","navigatorTitle":[{"text":"cumulative","kind":"identifier"}],"modules":[{"name":"Core Animation"}],"roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.quartzcore/documentation/QuartzCore","doc://com.apple.quartzcore/documentation/QuartzCore/CAPropertyAnimation"]]},"references":{"doc://com.apple.quartzcore/documentation/QuartzCore/CAPropertyAnimation/isAdditive":{"role":"symbol","url":"/documentation/quartzcore/capropertyanimation/isadditive","title":"isAdditive","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Determines if the value specified by the animation is added to the current render tree value to produce the new render tree value."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAdditive"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"text":"additive","kind":"identifier"}],"identifier":"doc://com.apple.quartzcore/documentation/QuartzCore/CAPropertyAnimation/isAdditive"},"doc://com.externally.resolved.symbol/s:Sb":{"title":"Bool","abstract":[{"text":"A value type whose instances are either `true` or `false`.","type":"text"}],"kind":"symbol","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Bool","kind":"identifier"}],"role":"symbol","type":"topic","url":"/documentation/Swift/Bool","identifier":"doc://com.externally.resolved.symbol/s:Sb"},"doc://com.apple.quartzcore/documentation/QuartzCore/CAPropertyAnimation":{"role":"symbol","url":"/documentation/quartzcore/capropertyanimation","title":"CAPropertyAnimation","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"An abstract subclass for creating animations that manipulate the value of layer properties."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CAPropertyAnimation"}],"navigatorTitle":[{"kind":"identifier","text":"CAPropertyAnimation"}],"identifier":"doc://com.apple.quartzcore/documentation/QuartzCore/CAPropertyAnimation"},"doc://com.apple.documentation/documentation/technologies":{"kind":"technologies","type":"topic","title":"Technologies","abstract":[{"text":"","type":"text"}],"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","url":"/documentation/technologies"},"doc://com.apple.documentation/documentation/swift/true":{"title":"true","type":"topic","kind":"symbol","identifier":"doc://com.apple.documentation/documentation/swift/true","role":"symbol","abstract":[{"text":"A true value.","type":"text"}],"url":"/documentation/swift/true"},"doc://com.apple.quartzcore/documentation/QuartzCore/CAPropertyAnimation/valueFunction":{"role":"symbol","url":"/documentation/quartzcore/capropertyanimation/valuefunction","title":"valueFunction","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"An optional value function that is applied to interpolated values."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"valueFunction","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CAValueFunction","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CAValueFunction"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"valueFunction","kind":"identifier"}],"identifier":"doc://com.apple.quartzcore/documentation/QuartzCore/CAPropertyAnimation/valueFunction"},"doc://com.apple.quartzcore/documentation/QuartzCore":{"abstract":[{"type":"text","text":"Render, compose, and animate visual elements."}],"url":"/documentation/quartzcore","type":"topic","identifier":"doc://com.apple.quartzcore/documentation/QuartzCore","kind":"symbol","title":"Core Animation","role":"collection"},"doc://com.apple.documentation/documentation/swift/false":{"type":"topic","abstract":[{"text":"A false value.","type":"text"}],"title":"false","kind":"symbol","identifier":"doc://com.apple.documentation/documentation/swift/false","url":"/documentation/swift/false","role":"symbol"},"doc://com.apple.quartzcore/documentation/QuartzCore/CAPropertyAnimation/isCumulative":{"role":"symbol","url":"/documentation/quartzcore/capropertyanimation/iscumulative","title":"isCumulative","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Determines if the value of the property is the value at the end of the previous repeat cycle, plus the value of the current repeat cycle."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isCumulative"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"cumulative"}],"identifier":"doc://com.apple.quartzcore/documentation/QuartzCore/CAPropertyAnimation/isCumulative"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"name":"iOS","deprecated":false,"unavailable":false,"introducedAt":"2.0","beta":false},{"name":"iPadOS","deprecated":false,"unavailable":false,"introducedAt":"2.0","beta":false},{"name":"Mac Catalyst","deprecated":false,"unavailable":false,"introducedAt":"13.1","beta":false},{"name":"macOS","deprecated":false,"unavailable":false,"introducedAt":"10.5","beta":false},{"name":"tvOS","deprecated":false,"unavailable":false,"introducedAt":"9.0","beta":false},{"name":"visionOS","beta":false,"introducedAt":"1.0","unavailable":false,"deprecated":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Property","path":"/metadata/roleHeading"},{"op":"replace","value":"cumulative","path":"/metadata/title"},{"op":"replace","value":"property","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"cumulative"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.quartzcore/documentation/QuartzCore","doc://com.apple.quartzcore/documentation/QuartzCore/CAPropertyAnimation"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"title":"Property Value Calculation Behavior","anchor":"Property-Value-Calculation-Behavior","generated":true,"identifiers":["doc://com.apple.quartzcore/documentation/QuartzCore/CAPropertyAnimation/isAdditive","doc://com.apple.quartzcore/documentation/QuartzCore/CAPropertyAnimation/valueFunction"]}],"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"getter","kind":"keyword"},{"text":"=","kind":"text"},{"text":"isCumulative","kind":"identifier"},{"text":") ","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"cumulative","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"/primaryContentSections/0"},{"op":"replace","value":"additive","path":"/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAPropertyAnimation~1isAdditive/title"},{"op":"replace","value":[{"kind":"identifier","text":"additive"}],"path":"/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAPropertyAnimation~1isAdditive/fragments"},{"op":"replace","value":"CAPropertyAnimation","path":"/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAPropertyAnimation/title"},{"op":"replace","value":[{"text":"CAPropertyAnimation","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAPropertyAnimation/fragments"},{"op":"replace","value":[{"text":"CAPropertyAnimation","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAPropertyAnimation/navigatorTitle"},{"op":"replace","value":"valueFunction","path":"/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAPropertyAnimation~1valueFunction/title"},{"op":"replace","value":[{"text":"valueFunction","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAPropertyAnimation~1valueFunction/fragments"},{"op":"replace","value":"cumulative","path":"/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAPropertyAnimation~1isCumulative/title"},{"op":"replace","value":[{"text":"cumulative","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAPropertyAnimation~1isCumulative/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}