{
  "abstract": [
    {
      "text": "A string that identifies the type of data your app or third-party SDK collects.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration",
        "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyCollectedDataTypes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyCollectedDataTypes/NSPrivacyCollectedDataType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:App_Privacy_Configuration.NSPrivacyCollectedDataTypes.NSPrivacyCollectedDataType",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSPrivacyCollectedDataType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "NSPrivacyCollectedDataType"
  },
  "primaryContentSections": [
    {
      "details": {
        "ideTitle": "Collected Data Type",
        "name": "NSPrivacyCollectedDataType",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "string"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "kind": "possibleValues",
      "title": "Possible Values",
      "values": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Name, such as first or last name.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "NSPrivacyCollectedDataTypeName"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Email address, including but not limited to a hashed email address.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "NSPrivacyCollectedDataTypeEmailAddress"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Phone number, including but not limited to a hashed phone number.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "NSPrivacyCollectedDataTypePhoneNumber"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Physical address, such as home address, physical address, or mailing address.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "NSPrivacyCollectedDataTypePhysicalAddress"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Other user contact info; any other information that can be used to contact the user outside the app.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "NSPrivacyCollectedDataTypeOtherUserContactInfo"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Health and medical data, including but not limited to data from the Clinical Health Records API, HealthKit API, MovementDisorderAPIs, or health-related human subject research or any other user provided health or medical data.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "NSPrivacyCollectedDataTypeHealth"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Fitness and exercise data, including but not limited to the Motion and Fitness API.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "NSPrivacyCollectedDataTypeFitness"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Payment info; such as form of payment, payment card number, or bank account number. If your app uses a payment service, the payment information is entered outside your app, and you as the developer never have access to the payment information, it is not collected and does not need to be disclosed.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "NSPrivacyCollectedDataTypePaymentInfo"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Credit info, such as credit score.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "NSPrivacyCollectedDataTypeCreditInfo"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Other financial info; such as salary, income, assets, debts, or any other financial information.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "NSPrivacyCollectedDataTypeOtherFinancialInfo"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Precise location; information that describes the location of a user or device with the same or greater resolution as a latitude and longitude with three or more decimal places.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "NSPrivacyCollectedDataTypePreciseLocation"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Coarse location; information that describes the location of a user or device with lower resolution than a latitude and longitude with three or more decimal places, such as Approximate Location Services.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "NSPrivacyCollectedDataTypeCoarseLocation"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Sensitive information; such as racial or ethnic data, sexual orientation, pregnancy or childbirth information, disability, religious or philosophical beliefs, trade union membership, political opinion, genetic information, or biometric data.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "NSPrivacyCollectedDataTypeSensitiveInfo"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Contacts; such as a list of contacts in the user’s phone, address book, or social graph.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "NSPrivacyCollectedDataTypeContacts"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Emails or text messages; including subject line, sender, recipients, and contents of the email or message.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "NSPrivacyCollectedDataTypeEmailsOrTextMessages"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The user’s photos or videos.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "NSPrivacyCollectedDataTypePhotosorVideos"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The user’s voice or sound recordings.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "NSPrivacyCollectedDataTypeAudioData"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Gameplay content; such as saved games, multiplayer matching or gameplay logic, or user-generated content in-game.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "NSPrivacyCollectedDataTypeGameplayContent"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Data generated by the user during a customer support request.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "NSPrivacyCollectedDataTypeCustomerSupport"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Any other user-generated content.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "NSPrivacyCollectedDataTypeOtherUserContent"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Browsing history; information about content the user has viewed that is not part of the app, such as websites.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "NSPrivacyCollectedDataTypeBrowsingHistory"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Information about searches performed in the app.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "NSPrivacyCollectedDataTypeSearchHistory"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "User ID; such as screen name, handle, account ID, assigned user ID, customer number, or other user- or account-level ID that can be used to identify a particular user or account.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "NSPrivacyCollectedDataTypeUserID"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Device ID; such as the device’s advertising identifier, or other device-level ID.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "NSPrivacyCollectedDataTypeDeviceID"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An account’s or individual’s purchases or purchase tendencies.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "NSPrivacyCollectedDataTypePurchaseHistory"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Product interaction; such as app launches, taps, clicks, scrolling information, music listening data, video views, saved place in a game, video, or song, or other information about how the user interacts with the app.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "NSPrivacyCollectedDataTypeProductInteraction"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Advertising data; such as information about the advertisements the user has seen.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "NSPrivacyCollectedDataTypeAdvertisingData"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Any other data about user activity in the app.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "NSPrivacyCollectedDataTypeOtherUsageData"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Crash data, such as crash logs.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "NSPrivacyCollectedDataTypeCrashData"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Performance data, such as launch time, freeze rate, or energy use.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "NSPrivacyCollectedDataTypePerformanceData"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Any other data collected for the purposes of measuring technical diagnostics related to the app.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "NSPrivacyCollectedDataTypeOtherDiagnosticData"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Environment scanning; such as mesh, planes, scene classification, and/or image detection of the user’s surroundings.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "NSPrivacyCollectedDataTypeEnvironmentScanning"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The user’s hand structure and hand movements.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "NSPrivacyCollectedDataTypeHands"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The user’s head movement.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "NSPrivacyCollectedDataTypeHead"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Any other data types not mentioned.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "NSPrivacyCollectedDataTypeOtherDataTypes"
        }
      ]
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.bundleresources/documentation/BundleResources/describing-data-use-in-privacy-manifests"
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Choose the value that matches the data your app or third-party SDK collects.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration": {
      "abstract": [
        {
          "text": "A data structure that represents the root object in a privacy manifest file.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration",
      "kind": "symbol",
      "name": "App Privacy Configuration",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "App Privacy Configuration"
        }
      ],
      "role": "symbol",
      "title": "App Privacy Configuration",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/app-privacy-configuration"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyCollectedDataTypes": {
      "abstract": [
        {
          "text": "A list of dictionaries that report the categories of private data your app or third-party SDK collects.",
          "type": "text"
        }
      ],
      "ideTitle": "Privacy Nutrition Label Types",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyCollectedDataTypes",
      "kind": "symbol",
      "name": "NSPrivacyCollectedDataTypes",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrivacyCollectedDataTypes"
        }
      ],
      "role": "symbol",
      "title": "NSPrivacyCollectedDataTypes",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/app-privacy-configuration/nsprivacycollecteddatatypes"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyCollectedDataTypes/NSPrivacyCollectedDataType": {
      "abstract": [
        {
          "text": "A string that identifies the type of data your app or third-party SDK collects.",
          "type": "text"
        }
      ],
      "ideTitle": "Collected Data Type",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyCollectedDataTypes/NSPrivacyCollectedDataType",
      "kind": "symbol",
      "name": "NSPrivacyCollectedDataType",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrivacyCollectedDataType"
        }
      ],
      "role": "symbol",
      "title": "NSPrivacyCollectedDataType",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/app-privacy-configuration/nsprivacycollecteddatatypes/nsprivacycollecteddatatype"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyCollectedDataTypes/NSPrivacyCollectedDataTypePurposes": {
      "abstract": [
        {
          "text": "An array of strings that identify reasons your app or third-party SDK collects private data.",
          "type": "text"
        }
      ],
      "ideTitle": "Collection Purposes",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyCollectedDataTypes/NSPrivacyCollectedDataTypePurposes",
      "kind": "symbol",
      "name": "NSPrivacyCollectedDataTypePurposes",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrivacyCollectedDataTypePurposes"
        }
      ],
      "role": "symbol",
      "title": "NSPrivacyCollectedDataTypePurposes",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/app-privacy-configuration/nsprivacycollecteddatatypes/nsprivacycollecteddatatypepurposes"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/describing-data-use-in-privacy-manifests": {
      "abstract": [
        {
          "text": "Declare the data collected by your app or by third-party SDKs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/describing-data-use-in-privacy-manifests",
      "kind": "article",
      "role": "article",
      "title": "Describing data use in privacy manifests",
      "type": "topic",
      "url": "/documentation/bundleresources/describing-data-use-in-privacy-manifests"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reporting-categories-of-collected-data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyCollectedDataTypes/NSPrivacyCollectedDataTypePurposes"
      ],
      "title": "Reporting categories of collected data"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSPrivacyCollectedDataType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrivacyCollectedDataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration",
                "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyCollectedDataTypes"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reporting-categories-of-collected-data",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyCollectedDataTypes/NSPrivacyCollectedDataTypePurposes"
              ],
              "title": "Reporting categories of collected data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration~1NSPrivacyCollectedDataTypes/title",
          "value": "NSPrivacyCollectedDataTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration~1NSPrivacyCollectedDataTypes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrivacyCollectedDataTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration/title",
          "value": "App Privacy Configuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "App Privacy Configuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration~1NSPrivacyCollectedDataTypes~1NSPrivacyCollectedDataType/title",
          "value": "NSPrivacyCollectedDataType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration~1NSPrivacyCollectedDataTypes~1NSPrivacyCollectedDataType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrivacyCollectedDataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration~1NSPrivacyCollectedDataTypes~1NSPrivacyCollectedDataTypePurposes/title",
          "value": "NSPrivacyCollectedDataTypePurposes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration~1NSPrivacyCollectedDataTypes~1NSPrivacyCollectedDataTypePurposes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrivacyCollectedDataTypePurposes"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/app-privacy-configuration/nsprivacycollecteddatatypes/nsprivacycollecteddatatype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/app-privacy-configuration/nsprivacycollecteddatatypes/nsprivacycollecteddatatype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
