{
  "abstract": [
    {
      "text": "Delivers the latest acceleration data to the delegate.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIAccelerometerDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIAccelerometerDelegate/accelerometer:didAccelerate:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)UIAccelerometerDelegate(im)accelerometer:didAccelerate:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "accelerometer:didAccelerate:"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "accelerometer:didAccelerate:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "5.0",
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "5.0",
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "accelerometer:didAccelerate:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "accelerometer:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccelerometer",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIAccelerometer",
              "text": "UIAccelerometer"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "accelerometer"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "didAccelerate:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAcceleration",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIAcceleration",
              "text": "UIAcceleration"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "acceleration"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The application-wide accelerometer object.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "accelerometer"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The most recent acceleration data.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "acceleration"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The shared ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccelerometer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object invokes this method at the desired interval, providing your delegate with updated acceleration data each time.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This method is always invoked on your application’s main thread when it is in the NSDefaultRunLoopMode run loop mode.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAcceleration": {
      "abstract": [
        {
          "text": "An acceleration event that represents immediate, three-dimensional acceleration data.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIAcceleration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAcceleration",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIAcceleration",
      "type": "topic",
      "url": "/documentation/uikit/uiacceleration"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccelerometer": {
      "abstract": [
        {
          "text": "An object that lets you register to receive acceleration-related data from the onboard hardware.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIAccelerometer"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccelerometer",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIAccelerometer",
      "type": "topic",
      "url": "/documentation/uikit/uiaccelerometer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccelerometerDelegate": {
      "abstract": [
        {
          "text": "The interface for receiving acceleration-related data from the system.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIAccelerometerDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccelerometerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccelerometerDelegate"
        }
      ],
      "role": "symbol",
      "title": "UIAccelerometerDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uiaccelerometerdelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccelerometerDelegate/accelerometer:didAccelerate:": {
      "abstract": [
        {
          "text": "Delivers the latest acceleration data to the delegate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "accelerometer:didAccelerate:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccelerometerDelegate/accelerometer:didAccelerate:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accelerometer:didAccelerate:"
        }
      ],
      "role": "symbol",
      "title": "accelerometer:didAccelerate:",
      "type": "topic",
      "url": "/documentation/uikit/uiaccelerometerdelegate/accelerometer:didaccelerate:"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccelerometerDelegate/title",
          "value": "UIAccelerometerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccelerometerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccelerometerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccelerometerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccelerometerDelegate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiaccelerometerdelegate/accelerometer:didaccelerate:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
