{
  "abstract": [
    {
      "text": "The USB interface’s current alternative setting value.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iousbhost/documentation/IOUSBHost",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostInterfacePropertyKey"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostInterfacePropertyKey/alternateSetting"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "IOUSBHost",
    "externalID": "c:@IOUSBHostInterfacePropertyKeyAlternateSetting",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "alternateSetting"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@IOUSBHostInterfacePropertyKey",
        "text": "IOUSBHostInterfacePropertyKey"
      }
    ],
    "modules": [
      {
        "name": "IOUSBHost"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "IOUSBHostInterfacePropertyKeyAlternateSetting"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "alternateSetting"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "alternateSetting"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostInterfacePropertyKey",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@IOUSBHostInterfacePropertyKey",
              "text": "IOUSBHostInterfacePropertyKey"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost": {
      "abstract": [
        {
          "text": "Create host-mode user space drivers for USB devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost",
      "kind": "symbol",
      "role": "collection",
      "title": "IOUSBHost",
      "type": "topic",
      "url": "/documentation/iousbhost"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostInterfacePropertyKey": {
      "abstract": [
        {
          "text": "Properties of a USB interface that describe its state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostInterfacePropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostInterfacePropertyKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostInterfacePropertyKey"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostInterfacePropertyKey",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostinterfacepropertykey"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostInterfacePropertyKey/alternateSetting": {
      "abstract": [
        {
          "text": "The USB interface’s current alternative setting value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alternateSetting"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOUSBHostInterfacePropertyKey",
          "text": "IOUSBHostInterfacePropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostInterfacePropertyKey/alternateSetting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostInterfacePropertyKeyAlternateSetting"
        }
      ],
      "role": "symbol",
      "title": "alternateSetting",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostinterfacepropertykey/alternatesetting"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "IOUSBHostInterfacePropertyKeyAlternateSetting"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostInterfacePropertyKeyAlternateSetting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iousbhost/documentation/IOUSBHost"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostInterfacePropertyKey",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@IOUSBHostInterfacePropertyKey",
                    "text": "IOUSBHostInterfacePropertyKey"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "IOUSBHostInterfacePropertyKeyAlternateSetting"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostInterfacePropertyKey/title",
          "value": "IOUSBHostInterfacePropertyKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostInterfacePropertyKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostInterfacePropertyKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostInterfacePropertyKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostInterfacePropertyKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostInterfacePropertyKey~1alternateSetting/title",
          "value": "IOUSBHostInterfacePropertyKeyAlternateSetting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostInterfacePropertyKey~1alternateSetting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostInterfacePropertyKeyAlternateSetting"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iousbhost/iousbhostinterfacepropertykey/alternatesetting"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iousbhost/iousbhostinterfacepropertykey/alternatesetting"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
