{
  "abstract": [
    {
      "text": "The latest sample of device-motion data.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremotion/documentation/CoreMotion",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/deviceMotion"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CMMotionManager(py)deviceMotion",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "deviceMotion"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CMDeviceMotion",
        "text": "CMDeviceMotion"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "Core Motion"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "deviceMotion"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "deviceMotion"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "deviceMotion"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMDeviceMotion",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CMDeviceMotion",
              "text": "CMDeviceMotion"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.coremotion/documentation/CoreMotion/getting-processed-device-motion-data"
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If no device-motion data is available, the value of this property is ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ". An app that is receiving device-motion data after calling ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/startDeviceMotionUpdates()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " periodically checks the value of this property and processes the device-motion data.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremotion/documentation/CoreMotion": {
      "abstract": [
        {
          "text": "Process accelerometer, gyroscope, pedometer, and environment-related events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Motion",
      "type": "topic",
      "url": "/documentation/coremotion"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMDeviceMotion": {
      "abstract": [
        {
          "text": "Encapsulated measurements of the attitude, rotation rate, and acceleration of a device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMDeviceMotion"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMDeviceMotion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMDeviceMotion"
        }
      ],
      "role": "symbol",
      "title": "CMDeviceMotion",
      "type": "topic",
      "url": "/documentation/coremotion/cmdevicemotion"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMDeviceMotionHandler": {
      "abstract": [
        {
          "text": "The type of block callback for handling device-motion data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMDeviceMotionHandler"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMDeviceMotionHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMDeviceMotionHandler"
        }
      ],
      "role": "symbol",
      "title": "CMDeviceMotionHandler",
      "type": "topic",
      "url": "/documentation/coremotion/cmdevicemotionhandler"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager": {
      "abstract": [
        {
          "text": "The object for starting and managing motion services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMMotionManager"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMotionManager"
        }
      ],
      "role": "symbol",
      "title": "CMMotionManager",
      "type": "topic",
      "url": "/documentation/coremotion/cmmotionmanager"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/deviceMotion": {
      "abstract": [
        {
          "text": "The latest sample of device-motion data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceMotion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CMDeviceMotion",
          "text": "CMDeviceMotion"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/deviceMotion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deviceMotion"
        }
      ],
      "role": "symbol",
      "title": "deviceMotion",
      "type": "topic",
      "url": "/documentation/coremotion/cmmotionmanager/devicemotion"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/deviceMotionUpdateInterval": {
      "abstract": [
        {
          "text": "The interval, in seconds, for providing device-motion updates to the block handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceMotionUpdateInterval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/deviceMotionUpdateInterval",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deviceMotionUpdateInterval"
        }
      ],
      "role": "symbol",
      "title": "deviceMotionUpdateInterval",
      "type": "topic",
      "url": "/documentation/coremotion/cmmotionmanager/devicemotionupdateinterval"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/showsDeviceMovementDisplay": {
      "abstract": [
        {
          "text": "Controls whether the device-movement display is shown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showsDeviceMovementDisplay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/showsDeviceMovementDisplay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "showsDeviceMovementDisplay"
        }
      ],
      "role": "symbol",
      "title": "showsDeviceMovementDisplay",
      "type": "topic",
      "url": "/documentation/coremotion/cmmotionmanager/showsdevicemovementdisplay"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/startDeviceMotionUpdates()": {
      "abstract": [
        {
          "text": "Starts device-motion updates without a block handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startDeviceMotionUpdates"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/startDeviceMotionUpdates()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startDeviceMotionUpdates"
        }
      ],
      "role": "symbol",
      "title": "startDeviceMotionUpdates()",
      "type": "topic",
      "url": "/documentation/coremotion/cmmotionmanager/startdevicemotionupdates()"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/startDeviceMotionUpdates(to:withHandler:)": {
      "abstract": [
        {
          "text": "Starts device-motion updates on an operation queue and using a specified block handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startDeviceMotionUpdates"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSOperationQueue",
          "text": "OperationQueue"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMDeviceMotionHandler",
          "text": "CMDeviceMotionHandler"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/startDeviceMotionUpdates(to:withHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startDeviceMotionUpdatesToQueue:withHandler:"
        }
      ],
      "role": "symbol",
      "title": "startDeviceMotionUpdates(to:withHandler:)",
      "type": "topic",
      "url": "/documentation/coremotion/cmmotionmanager/startdevicemotionupdates(to:withhandler:)"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/startDeviceMotionUpdates(using:)": {
      "abstract": [
        {
          "text": "Starts device-motion updates using a reference frame but without a block handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startDeviceMotionUpdates"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "using"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CMAttitudeReferenceFrame",
          "text": "CMAttitudeReferenceFrame"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/startDeviceMotionUpdates(using:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startDeviceMotionUpdatesUsingReferenceFrame:"
        }
      ],
      "role": "symbol",
      "title": "startDeviceMotionUpdates(using:)",
      "type": "topic",
      "url": "/documentation/coremotion/cmmotionmanager/startdevicemotionupdates(using:)"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/startDeviceMotionUpdates(using:to:withHandler:)": {
      "abstract": [
        {
          "text": "Starts device-motion updates on an operation queue and using a specified reference frame and block handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startDeviceMotionUpdates"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "using"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CMAttitudeReferenceFrame",
          "text": "CMAttitudeReferenceFrame"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSOperationQueue",
          "text": "OperationQueue"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMDeviceMotionHandler",
          "text": "CMDeviceMotionHandler"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/startDeviceMotionUpdates(using:to:withHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startDeviceMotionUpdatesUsingReferenceFrame:toQueue:withHandler:"
        }
      ],
      "role": "symbol",
      "title": "startDeviceMotionUpdates(using:to:withHandler:)",
      "type": "topic",
      "url": "/documentation/coremotion/cmmotionmanager/startdevicemotionupdates(using:to:withhandler:)"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/stopDeviceMotionUpdates()": {
      "abstract": [
        {
          "text": "Stops device-motion updates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stopDeviceMotionUpdates"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/stopDeviceMotionUpdates()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stopDeviceMotionUpdates"
        }
      ],
      "role": "symbol",
      "title": "stopDeviceMotionUpdates()",
      "type": "topic",
      "url": "/documentation/coremotion/cmmotionmanager/stopdevicemotionupdates()"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/getting-processed-device-motion-data": {
      "abstract": [
        {
          "text": "Retrieve motion data that the system processed to remove environmental bias, such as the effects of gravity.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/getting-processed-device-motion-data",
      "kind": "article",
      "role": "article",
      "title": "Getting processed device-motion data",
      "type": "topic",
      "url": "/documentation/coremotion/getting-processed-device-motion-data"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-Device-Motion-Updates",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/showsDeviceMovementDisplay",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/deviceMotionUpdateInterval",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/startDeviceMotionUpdates(using:to:withHandler:)",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/startDeviceMotionUpdates(to:withHandler:)",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/startDeviceMotionUpdates(using:)",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/startDeviceMotionUpdates()",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/stopDeviceMotionUpdates()",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMDeviceMotionHandler"
      ],
      "title": "Managing Device Motion Updates"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "deviceMotion"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "deviceMotion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremotion/documentation/CoreMotion",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-Device-Motion-Updates",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/showsDeviceMovementDisplay",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/deviceMotionUpdateInterval",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/startDeviceMotionUpdates(using:to:withHandler:)",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/startDeviceMotionUpdates(to:withHandler:)",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/startDeviceMotionUpdates(using:)",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/startDeviceMotionUpdates()",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/stopDeviceMotionUpdates()",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMDeviceMotionHandler"
              ],
              "title": "Managing Device Motion Updates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMDeviceMotion",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)CMDeviceMotion",
                    "text": "CMDeviceMotion"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "deviceMotion"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMotionManager~1startDeviceMotionUpdates()/title",
          "value": "startDeviceMotionUpdates"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMotionManager~1startDeviceMotionUpdates()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startDeviceMotionUpdates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMotionManager~1startDeviceMotionUpdates(using:to:withHandler:)/title",
          "value": "startDeviceMotionUpdatesUsingReferenceFrame:toQueue:withHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMotionManager~1startDeviceMotionUpdates(using:to:withHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startDeviceMotionUpdatesUsingReferenceFrame:toQueue:withHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMotionManager~1stopDeviceMotionUpdates()/title",
          "value": "stopDeviceMotionUpdates"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMotionManager~1stopDeviceMotionUpdates()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "stopDeviceMotionUpdates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMotionManager~1showsDeviceMovementDisplay/title",
          "value": "showsDeviceMovementDisplay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMotionManager~1showsDeviceMovementDisplay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "showsDeviceMovementDisplay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMotionManager/title",
          "value": "CMMotionManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMotionManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMotionManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMotionManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMotionManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMotionManager~1deviceMotionUpdateInterval/title",
          "value": "deviceMotionUpdateInterval"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMotionManager~1deviceMotionUpdateInterval/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "deviceMotionUpdateInterval"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMotionManager~1startDeviceMotionUpdates(using:)/title",
          "value": "startDeviceMotionUpdatesUsingReferenceFrame:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMotionManager~1startDeviceMotionUpdates(using:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startDeviceMotionUpdatesUsingReferenceFrame:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMotionManager~1deviceMotion/title",
          "value": "deviceMotion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMotionManager~1deviceMotion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "deviceMotion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMDeviceMotion/title",
          "value": "CMDeviceMotion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMDeviceMotion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMDeviceMotion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMDeviceMotion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMDeviceMotion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMotionManager~1startDeviceMotionUpdates(to:withHandler:)/title",
          "value": "startDeviceMotionUpdatesToQueue:withHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMotionManager~1startDeviceMotionUpdates(to:withHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startDeviceMotionUpdatesToQueue:withHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMDeviceMotionHandler/title",
          "value": "CMDeviceMotionHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMDeviceMotionHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMDeviceMotionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMDeviceMotionHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMDeviceMotionHandler"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremotion/cmmotionmanager/devicemotion"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremotion/cmmotionmanager/devicemotion"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
