{
  "abstract": [
    {
      "text": "Starts magnetometer updates on an operation queue and with a specified handler.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremotion/documentation/CoreMotion",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/startMagnetometerUpdates(to:withHandler:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CMMotionManager(im)startMagnetometerUpdatesToQueue:withHandler:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "startMagnetometerUpdates"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "to"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSOperationQueue",
        "text": "OperationQueue"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "withHandler"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CMMagnetometerHandler",
        "text": "CMMagnetometerHandler"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Core Motion"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "startMagnetometerUpdatesToQueue:withHandler:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "startMagnetometerUpdates(to:withHandler:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "startMagnetometerUpdates"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "to"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "queue"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSOperationQueue",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSOperationQueue",
              "text": "OperationQueue"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "withHandler"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "handler"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "@escaping"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMagnetometerHandler",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMMagnetometerHandler",
              "text": "CMMagnetometerHandler"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An operation queue provided by the caller. Because the processed events might arrive at a high rate, using the main operation queue is not recommended.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "queue"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A block that is invoked with each update to handle new magnetometer data. The block must conform to the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMagnetometerHandler",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " type.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "handler"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You must call ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/stopMagnetometerUpdates()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " when you no longer want your app to process magnetometer updates.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremotion/documentation/CoreMotion": {
      "abstract": [
        {
          "text": "Process accelerometer, gyroscope, pedometer, and environment-related events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Motion",
      "type": "topic",
      "url": "/documentation/coremotion"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMMagnetometerHandler": {
      "abstract": [
        {
          "text": "The type of block callback for handling magnetometer data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMMagnetometerHandler"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMagnetometerHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMagnetometerHandler"
        }
      ],
      "role": "symbol",
      "title": "CMMagnetometerHandler",
      "type": "topic",
      "url": "/documentation/coremotion/cmmagnetometerhandler"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager": {
      "abstract": [
        {
          "text": "The object for starting and managing motion services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMMotionManager"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMotionManager"
        }
      ],
      "role": "symbol",
      "title": "CMMotionManager",
      "type": "topic",
      "url": "/documentation/coremotion/cmmotionmanager"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/magnetometerData": {
      "abstract": [
        {
          "text": "The latest sample of magnetometer data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "magnetometerData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CMMagnetometerData",
          "text": "CMMagnetometerData"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/magnetometerData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "magnetometerData"
        }
      ],
      "role": "symbol",
      "title": "magnetometerData",
      "type": "topic",
      "url": "/documentation/coremotion/cmmotionmanager/magnetometerdata"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/magnetometerUpdateInterval": {
      "abstract": [
        {
          "text": "The interval, in seconds, at which the system delivers magnetometer data to the block handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "magnetometerUpdateInterval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/magnetometerUpdateInterval",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "magnetometerUpdateInterval"
        }
      ],
      "role": "symbol",
      "title": "magnetometerUpdateInterval",
      "type": "topic",
      "url": "/documentation/coremotion/cmmotionmanager/magnetometerupdateinterval"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/startMagnetometerUpdates()": {
      "abstract": [
        {
          "text": "Starts magnetometer updates without a block handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startMagnetometerUpdates"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/startMagnetometerUpdates()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startMagnetometerUpdates"
        }
      ],
      "role": "symbol",
      "title": "startMagnetometerUpdates()",
      "type": "topic",
      "url": "/documentation/coremotion/cmmotionmanager/startmagnetometerupdates()"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/startMagnetometerUpdates(to:withHandler:)": {
      "abstract": [
        {
          "text": "Starts magnetometer updates on an operation queue and with a specified handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startMagnetometerUpdates"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSOperationQueue",
          "text": "OperationQueue"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMMagnetometerHandler",
          "text": "CMMagnetometerHandler"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/startMagnetometerUpdates(to:withHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startMagnetometerUpdatesToQueue:withHandler:"
        }
      ],
      "role": "symbol",
      "title": "startMagnetometerUpdates(to:withHandler:)",
      "type": "topic",
      "url": "/documentation/coremotion/cmmotionmanager/startmagnetometerupdates(to:withhandler:)"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/stopMagnetometerUpdates()": {
      "abstract": [
        {
          "text": "Stops magnetometer updates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stopMagnetometerUpdates"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/stopMagnetometerUpdates()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stopMagnetometerUpdates"
        }
      ],
      "role": "symbol",
      "title": "stopMagnetometerUpdates()",
      "type": "topic",
      "url": "/documentation/coremotion/cmmotionmanager/stopmagnetometerupdates()"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSOperationQueue": {
      "abstract": [
        {
          "text": "A queue that regulates the execution of operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "OperationQueue"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSOperationQueue",
      "kind": "symbol",
      "role": "symbol",
      "title": "OperationQueue",
      "type": "topic",
      "url": "/documentation/foundation/operationqueue"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-Magnetometer-Updates",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/magnetometerUpdateInterval",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/startMagnetometerUpdates()",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/stopMagnetometerUpdates()",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/magnetometerData",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMMagnetometerHandler"
      ],
      "title": "Managing Magnetometer Updates"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "startMagnetometerUpdatesToQueue:withHandler:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startMagnetometerUpdatesToQueue:withHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremotion/documentation/CoreMotion",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-Magnetometer-Updates",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/magnetometerUpdateInterval",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/startMagnetometerUpdates()",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/stopMagnetometerUpdates()",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMMotionManager/magnetometerData",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMMagnetometerHandler"
              ],
              "title": "Managing Magnetometer Updates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "startMagnetometerUpdatesToQueue:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSOperationQueue",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSOperationQueue",
                    "text": "NSOperationQueue"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "queue"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "withHandler:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMagnetometerHandler",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CMMagnetometerHandler",
                    "text": "CMMagnetometerHandler"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "handler"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An operation queue provided by the caller. Because the processed events might arrive at a high rate, using the main operation queue is not recommended.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "queue"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A block that is invoked with each update to handle new magnetometer data. The block must conform to the ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMagnetometerHandler",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " type.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "handler"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMotionManager~1magnetometerData/title",
          "value": "magnetometerData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMotionManager~1magnetometerData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "magnetometerData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMotionManager~1stopMagnetometerUpdates()/title",
          "value": "stopMagnetometerUpdates"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMotionManager~1stopMagnetometerUpdates()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "stopMagnetometerUpdates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMotionManager~1startMagnetometerUpdates()/title",
          "value": "startMagnetometerUpdates"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMotionManager~1startMagnetometerUpdates()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startMagnetometerUpdates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSOperationQueue/title",
          "value": "NSOperationQueue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMotionManager~1startMagnetometerUpdates(to:withHandler:)/title",
          "value": "startMagnetometerUpdatesToQueue:withHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMotionManager~1startMagnetometerUpdates(to:withHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startMagnetometerUpdatesToQueue:withHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMotionManager~1magnetometerUpdateInterval/title",
          "value": "magnetometerUpdateInterval"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMotionManager~1magnetometerUpdateInterval/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "magnetometerUpdateInterval"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMagnetometerHandler/title",
          "value": "CMMagnetometerHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMagnetometerHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMagnetometerHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMagnetometerHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMagnetometerHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMotionManager/title",
          "value": "CMMotionManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMotionManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMotionManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMotionManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMotionManager"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremotion/cmmotionmanager/startmagnetometerupdates(to:withhandler:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremotion/cmmotionmanager/startmagnetometerupdates(to:withhandler:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
