{
  "abstract": [
    {
      "text": "Creates a new tagged buffer from tags and an existing sample buffer.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBuffer"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBuffer/init(tags:sampleBuffer:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:9CoreMedia14CMTaggedBufferV4tags06sampleD0ACSayAA5CMTagCG_So08CMSampleD3Refatcfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "tags"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:9CoreMedia5CMTagC",
        "text": "CMTag"
      },
      {
        "kind": "text",
        "text": "], "
      },
      {
        "kind": "externalParam",
        "text": "sampleBuffer"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CMSampleBufferRef",
        "text": "CMSampleBuffer"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(tags:sampleBuffer:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "tags"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:9CoreMedia5CMTagC",
              "text": "CMTag"
            },
            {
              "kind": "text",
              "text": "], "
            },
            {
              "kind": "externalParam",
              "text": "sampleBuffer"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMSampleBufferRef",
              "text": "CMSampleBuffer"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The tags to assign to the buffer.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "tags"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A sample buffer to associate with the tags.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "sampleBuffer"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer": {
      "abstract": [
        {
          "text": "A reference to a buffer of media data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSampleBuffer"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSampleBuffer"
        }
      ],
      "role": "symbol",
      "title": "CMSampleBuffer",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class": {
      "abstract": [
        {
          "text": "A tag to set additional metadata on media buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTag"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTag"
        }
      ],
      "role": "symbol",
      "title": "CMTag",
      "type": "topic",
      "url": "/documentation/coremedia/cmtag-swift.class"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBuffer": {
      "abstract": [
        {
          "text": "An instance of a media buffer containing metadata tags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTaggedBuffer"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTaggedBuffer"
        }
      ],
      "role": "symbol",
      "title": "CMTaggedBuffer",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaggedbuffer"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBuffer/init(tags:buffer:)": {
      "abstract": [
        {
          "text": "Creates a new tagged buffer from tags and an existing media buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "tags"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9CoreMedia5CMTagC",
          "text": "CMTag"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "buffer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9CoreMedia14CMTaggedBufferV",
          "text": "CMTaggedBuffer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9CoreMedia14CMTaggedBufferV0D0O",
          "text": "Buffer"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBuffer/init(tags:buffer:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(tags:buffer:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaggedbuffer/init(tags:buffer:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBuffer/init(tags:pixelBuffer:)": {
      "abstract": [
        {
          "text": "Creates a new tagged buffer from tags and an existing pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "tags"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9CoreMedia5CMTagC",
          "text": "CMTag"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "pixelBuffer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBuffer/init(tags:pixelBuffer:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(tags:pixelBuffer:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaggedbuffer/init(tags:pixelbuffer:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBuffer/init(tags:sampleBuffer:)": {
      "abstract": [
        {
          "text": "Creates a new tagged buffer from tags and an existing sample buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "tags"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9CoreMedia5CMTagC",
          "text": "CMTag"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "sampleBuffer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSampleBufferRef",
          "text": "CMSampleBuffer"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBuffer/init(tags:sampleBuffer:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(tags:sampleBuffer:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaggedbuffer/init(tags:samplebuffer:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-Tagged-Buffers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBuffer/init(tags:buffer:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBuffer/init(tags:pixelBuffer:)"
      ],
      "title": "Creating Tagged Buffers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMSampleBuffer/title",
          "value": "CMSampleBufferRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMSampleBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSampleBufferRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMSampleBuffer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSampleBufferRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmtaggedbuffer/init(tags:samplebuffer:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
