{
  "abstract": [
    {
      "text": "A menu created when the user clicks on the extension’s toolbar button.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Finder-Sync/documentation/FinderSync",
        "doc://com.apple.Finder-Sync/documentation/FinderSync/FIMenuKind"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIMenuKind/toolbarItemMenu"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@FIMenuKind@FIMenuKindToolbarItemMenu",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "toolbarItemMenu"
      }
    ],
    "modules": [
      {
        "name": "Finder Sync"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "FIMenuKindToolbarItemMenu"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "FIMenuKind.toolbarItemMenu"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "toolbarItemMenu"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.Finder-Sync/documentation/FinderSync": {
      "abstract": [
        {
          "text": "Modify the Finder’s user interface to express file synchronization and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync",
      "kind": "symbol",
      "role": "collection",
      "title": "Finder Sync",
      "type": "topic",
      "url": "/documentation/findersync"
    },
    "doc://com.apple.Finder-Sync/documentation/FinderSync/FIMenuKind": {
      "abstract": [
        {
          "text": "The different kinds of custom menus that the Finder Sync extension can",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "provide.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FIMenuKind"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIMenuKind",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FIMenuKind"
        }
      ],
      "role": "symbol",
      "title": "FIMenuKind",
      "type": "topic",
      "url": "/documentation/findersync/fimenukind"
    },
    "doc://com.apple.Finder-Sync/documentation/FinderSync/FIMenuKind/contextualMenuForContainer": {
      "abstract": [
        {
          "text": "A shortcut menu created when the user control-clicks on the Finder",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "window’s background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contextualMenuForContainer"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIMenuKind/contextualMenuForContainer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FIMenuKindContextualMenuForContainer"
        }
      ],
      "role": "symbol",
      "title": "FIMenuKind.contextualMenuForContainer",
      "type": "topic",
      "url": "/documentation/findersync/fimenukind/contextualmenuforcontainer"
    },
    "doc://com.apple.Finder-Sync/documentation/FinderSync/FIMenuKind/contextualMenuForItems": {
      "abstract": [
        {
          "text": "A shortcut menu created when the user control-clicks on an item or a",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "group of selected items inside the Finder window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contextualMenuForItems"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIMenuKind/contextualMenuForItems",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FIMenuKindContextualMenuForItems"
        }
      ],
      "role": "symbol",
      "title": "FIMenuKind.contextualMenuForItems",
      "type": "topic",
      "url": "/documentation/findersync/fimenukind/contextualmenuforitems"
    },
    "doc://com.apple.Finder-Sync/documentation/FinderSync/FIMenuKind/contextualMenuForSidebar": {
      "abstract": [
        {
          "text": "A shortcut menu created when the user control-clicks on an item in the",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "sidebar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contextualMenuForSidebar"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIMenuKind/contextualMenuForSidebar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FIMenuKindContextualMenuForSidebar"
        }
      ],
      "role": "symbol",
      "title": "FIMenuKind.contextualMenuForSidebar",
      "type": "topic",
      "url": "/documentation/findersync/fimenukind/contextualmenuforsidebar"
    },
    "doc://com.apple.Finder-Sync/documentation/FinderSync/FIMenuKind/toolbarItemMenu": {
      "abstract": [
        {
          "text": "A menu created when the user clicks on the extension’s toolbar button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "toolbarItemMenu"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIMenuKind/toolbarItemMenu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FIMenuKindToolbarItemMenu"
        }
      ],
      "role": "symbol",
      "title": "FIMenuKind.toolbarItemMenu",
      "type": "topic",
      "url": "/documentation/findersync/fimenukind/toolbaritemmenu"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Finder-Sync/documentation/FinderSync/FIMenuKind/contextualMenuForItems",
        "doc://com.apple.Finder-Sync/documentation/FinderSync/FIMenuKind/contextualMenuForContainer",
        "doc://com.apple.Finder-Sync/documentation/FinderSync/FIMenuKind/contextualMenuForSidebar"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "FIMenuKindToolbarItemMenu"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FIMenuKindToolbarItemMenu"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.Finder-Sync/documentation/FinderSync",
                "doc://com.apple.Finder-Sync/documentation/FinderSync/FIMenuKind"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.Finder-Sync/documentation/FinderSync/FIMenuKind/contextualMenuForItems",
                "doc://com.apple.Finder-Sync/documentation/FinderSync/FIMenuKind/contextualMenuForContainer",
                "doc://com.apple.Finder-Sync/documentation/FinderSync/FIMenuKind/contextualMenuForSidebar"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "FIMenuKindToolbarItemMenu"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIMenuKind/title",
          "value": "FIMenuKind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIMenuKind/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FIMenuKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIMenuKind/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FIMenuKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIMenuKind~1contextualMenuForContainer/title",
          "value": "FIMenuKindContextualMenuForContainer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIMenuKind~1contextualMenuForContainer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FIMenuKindContextualMenuForContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIMenuKind~1contextualMenuForItems/title",
          "value": "FIMenuKindContextualMenuForItems"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIMenuKind~1contextualMenuForItems/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FIMenuKindContextualMenuForItems"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIMenuKind~1contextualMenuForSidebar/title",
          "value": "FIMenuKindContextualMenuForSidebar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIMenuKind~1contextualMenuForSidebar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FIMenuKindContextualMenuForSidebar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIMenuKind~1toolbarItemMenu/title",
          "value": "FIMenuKindToolbarItemMenu"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIMenuKind~1toolbarItemMenu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FIMenuKindToolbarItemMenu"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/findersync/fimenukind/toolbaritemmenu"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/findersync/fimenukind/toolbaritemmenu"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
