{
  "abstract": [
    {
      "text": "Returns an IOBluetoothSDPUUIDRef representation of the target IOBluetoothSDPUUID object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothSDPUUID"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothSDPUUID/getSDPUUIDRef"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)IOBluetoothSDPUUID(im)getSDPUUIDRef",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "getSDPUUIDRef"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "getSDPUUIDRef"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.7",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "getSDPUUIDRef"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothSDPUUIDRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@IOBluetoothSDPUUIDRef",
              "text": "IOBluetoothSDPUUIDRef"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "getSDPUUIDRef"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Returns an IOBluetoothSDPUUIDRef representation of the target IOBluetoothSDPUUID object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothSDPUUID": {
      "abstract": [
        {
          "text": "An NSData subclass that represents a UUID as defined in the Bluetooth SDP spec.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothSDPUUID"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothSDPUUID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothSDPUUID"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothSDPUUID",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothsdpuuid"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothSDPUUID/getSDPUUIDRef": {
      "abstract": [
        {
          "text": "Returns an IOBluetoothSDPUUIDRef representation of the target IOBluetoothSDPUUID object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "getSDPUUIDRef"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothSDPUUID/getSDPUUIDRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getSDPUUIDRef"
        }
      ],
      "role": "symbol",
      "title": "getSDPUUIDRef",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothsdpuuid/getsdpuuidref"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothSDPUUIDRef": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothSDPUUIDRef"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothSDPUUIDRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothSDPUUIDRef"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothSDPUUIDRef",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothsdpuuidref"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothSDPUUIDRef/title",
          "value": "IOBluetoothSDPUUIDRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothSDPUUIDRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothSDPUUIDRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothSDPUUIDRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothSDPUUIDRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothSDPUUID/title",
          "value": "IOBluetoothSDPUUID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothSDPUUID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothSDPUUID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothSDPUUID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothSDPUUID"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/iobluetoothsdpuuid/getsdpuuidref"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
