{
  "abstract": [
    {
      "text": "An object that describes how a CloudKit operation behaves.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cloudkit/documentation/CloudKit",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKOperation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cloudkit/documentation/CloudKit/CKOperation/Configuration-swift.class"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "CloudKit",
    "externalID": "c:objc(cs)CKOperationConfiguration",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Configuration"
      }
    ],
    "modules": [
      {
        "name": "CloudKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Configuration"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CKOperation.Configuration"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Configuration"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "All of the properties in ",
              "type": "text"
            },
            {
              "code": "CKOperationConfiguration",
              "type": "codeVoice"
            },
            {
              "text": " have a default value. When determining which properties to apply to a CloudKit operation, consult the operation’s configuration property, as well as the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/defaultConfiguration",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property of the group that the operation belongs to. These properties combine through the following rules:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Group default configuration value",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Operation configuration value",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Value applied to operation",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "default value",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "default value",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "default value",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "default value",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "explicit value",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "operation.configuration explicit value",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "explicit value",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "default value",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "group.defaultConfiguration explicit value",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "explicit value",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "explicit value",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "operation.configuration explicit value",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.cloudkit/documentation/CloudKit": {
      "abstract": [
        {
          "text": "Store structured app and user data in iCloud containers that all users of your app can share.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CloudKit",
      "type": "topic",
      "url": "/documentation/cloudkit"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKOperation": {
      "abstract": [
        {
          "text": "The abstract base class for all operations that execute in a database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKOperation"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKOperation"
        }
      ],
      "role": "symbol",
      "title": "CKOperation",
      "type": "topic",
      "url": "/documentation/cloudkit/ckoperation"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKOperation/Configuration-swift.class": {
      "abstract": [
        {
          "text": "An object that describes how a CloudKit operation behaves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Configuration"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKOperation/Configuration-swift.class",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Configuration"
        }
      ],
      "role": "symbol",
      "title": "CKOperation.Configuration",
      "type": "topic",
      "url": "/documentation/cloudkit/ckoperation/configuration-swift.class"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKOperation/Configuration-swift.class/allowsCellularAccess": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether operations that use this configuration can send data over the cellular network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsCellularAccess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKOperation/Configuration-swift.class/allowsCellularAccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowsCellularAccess"
        }
      ],
      "role": "symbol",
      "title": "allowsCellularAccess",
      "type": "topic",
      "url": "/documentation/cloudkit/ckoperation/configuration-swift.class/allowscellularaccess"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKOperation/Configuration-swift.class/container": {
      "abstract": [
        {
          "text": "The configuration’s container.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "container"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKContainer",
          "text": "CKContainer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKOperation/Configuration-swift.class/container",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "container"
        }
      ],
      "role": "symbol",
      "title": "container",
      "type": "topic",
      "url": "/documentation/cloudkit/ckoperation/configuration-swift.class/container"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKOperation/Configuration-swift.class/isLongLived": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the operations that use this configuration are long-lived.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isLongLived"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKOperation/Configuration-swift.class/isLongLived",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "longLived"
        }
      ],
      "role": "symbol",
      "title": "isLongLived",
      "type": "topic",
      "url": "/documentation/cloudkit/ckoperation/configuration-swift.class/islonglived"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKOperation/Configuration-swift.class/qualityOfService": {
      "abstract": [
        {
          "text": "The priority that the system uses when it allocates resources to the operations that use this configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "qualityOfService"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSQualityOfService",
          "text": "QualityOfService"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKOperation/Configuration-swift.class/qualityOfService",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "qualityOfService"
        }
      ],
      "role": "symbol",
      "title": "qualityOfService",
      "type": "topic",
      "url": "/documentation/cloudkit/ckoperation/configuration-swift.class/qualityofservice"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKOperation/Configuration-swift.class/timeoutIntervalForRequest": {
      "abstract": [
        {
          "text": "The maximum amount of time that a request can take.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeoutIntervalForRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKOperation/Configuration-swift.class/timeoutIntervalForRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "timeoutIntervalForRequest"
        }
      ],
      "role": "symbol",
      "title": "timeoutIntervalForRequest",
      "type": "topic",
      "url": "/documentation/cloudkit/ckoperation/configuration-swift.class/timeoutintervalforrequest"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKOperation/Configuration-swift.class/timeoutIntervalForResource": {
      "abstract": [
        {
          "text": "The maximum amount of time that a resource request can take.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeoutIntervalForResource"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKOperation/Configuration-swift.class/timeoutIntervalForResource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "timeoutIntervalForResource"
        }
      ],
      "role": "symbol",
      "title": "timeoutIntervalForResource",
      "type": "topic",
      "url": "/documentation/cloudkit/ckoperation/configuration-swift.class/timeoutintervalforresource"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKOperation/configuration-swift.property": {
      "abstract": [
        {
          "text": "The operation’s configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKOperation",
          "text": "CKOperation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKOperationConfiguration",
          "text": "Configuration"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKOperation/configuration-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "configuration"
        }
      ],
      "role": "symbol",
      "title": "configuration",
      "type": "topic",
      "url": "/documentation/cloudkit/ckoperation/configuration-swift.property"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKOperation/group": {
      "abstract": [
        {
          "text": "The operation’s group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "group"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKOperationGroup",
          "text": "CKOperationGroup"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKOperation/group",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "group"
        }
      ],
      "role": "symbol",
      "title": "group",
      "type": "topic",
      "url": "/documentation/cloudkit/ckoperation/group"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKOperation/longLivedOperationWasPersistedBlock": {
      "abstract": [
        {
          "text": "The closure to execute when the server begins to store callbacks for the long-lived operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "longLivedOperationWasPersistedBlock"
        },
        {
          "kind": "text",
          "text": ": (() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKOperation/longLivedOperationWasPersistedBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "longLivedOperationWasPersistedBlock"
        }
      ],
      "role": "symbol",
      "title": "longLivedOperationWasPersistedBlock",
      "type": "topic",
      "url": "/documentation/cloudkit/ckoperation/longlivedoperationwaspersistedblock"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/defaultConfiguration": {
      "abstract": [
        {
          "text": "The default configuration for operations in the group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultConfiguration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKOperation",
          "text": "CKOperation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKOperationConfiguration",
          "text": "Configuration"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/defaultConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultConfiguration"
        }
      ],
      "role": "symbol",
      "title": "defaultConfiguration",
      "type": "topic",
      "url": "/documentation/cloudkit/ckoperationgroup/defaultconfiguration"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-the-Operations-Configuration",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKOperation/configuration-swift.property",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKOperation/group",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKOperation/longLivedOperationWasPersistedBlock"
      ],
      "title": "Managing the Operation’s Configuration"
    }
  ],
  "topicSections": [
    {
      "anchor": "Preparing-a-Configuration",
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKOperation/Configuration-swift.class/allowsCellularAccess",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKOperation/Configuration-swift.class/container",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKOperation/Configuration-swift.class/isLongLived",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKOperation/Configuration-swift.class/qualityOfService",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKOperation/Configuration-swift.class/timeoutIntervalForRequest",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKOperation/Configuration-swift.class/timeoutIntervalForResource"
      ],
      "title": "Preparing a Configuration"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CKOperationConfiguration"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKOperationConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKOperationConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.cloudkit/documentation/CloudKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Preparing-a-Configuration",
              "identifiers": [
                "doc://com.apple.cloudkit/documentation/CloudKit/CKOperation/Configuration-swift.class/allowsCellularAccess",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKOperation/Configuration-swift.class/container",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKOperation/Configuration-swift.class/isLongLived",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKOperation/Configuration-swift.class/qualityOfService",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKOperation/Configuration-swift.class/timeoutIntervalForRequest",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKOperation/Configuration-swift.class/timeoutIntervalForResource"
              ],
              "title": "Preparing a Configuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-the-Operations-Configuration",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cloudkit/documentation/CloudKit/CKOperation/configuration-swift.property",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKOperation/group",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKOperation/longLivedOperationWasPersistedBlock"
              ],
              "title": "Managing the Operation’s Configuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CKOperationConfiguration"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperation~1Configuration-swift.class~1timeoutIntervalForResource/title",
          "value": "timeoutIntervalForResource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperation~1Configuration-swift.class~1timeoutIntervalForResource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "timeoutIntervalForResource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup~1defaultConfiguration/title",
          "value": "defaultConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup~1defaultConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "defaultConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperation~1Configuration-swift.class~1isLongLived/title",
          "value": "longLived"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperation~1Configuration-swift.class~1isLongLived/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "longLived"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperation~1longLivedOperationWasPersistedBlock/title",
          "value": "longLivedOperationWasPersistedBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperation~1longLivedOperationWasPersistedBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "longLivedOperationWasPersistedBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperation~1Configuration-swift.class/title",
          "value": "CKOperationConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperation~1Configuration-swift.class/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKOperationConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperation~1Configuration-swift.class/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKOperationConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperation~1Configuration-swift.class~1qualityOfService/title",
          "value": "qualityOfService"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperation~1Configuration-swift.class~1qualityOfService/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "qualityOfService"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperation~1configuration-swift.property/title",
          "value": "configuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperation~1configuration-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "configuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperation~1group/title",
          "value": "group"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperation~1group/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "group"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperation~1Configuration-swift.class~1allowsCellularAccess/title",
          "value": "allowsCellularAccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperation~1Configuration-swift.class~1allowsCellularAccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowsCellularAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperation/title",
          "value": "CKOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperation~1Configuration-swift.class~1timeoutIntervalForRequest/title",
          "value": "timeoutIntervalForRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperation~1Configuration-swift.class~1timeoutIntervalForRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "timeoutIntervalForRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperation~1Configuration-swift.class~1container/title",
          "value": "container"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperation~1Configuration-swift.class~1container/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "container"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cloudkit/ckoperation/configuration-swift.class"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cloudkit/ckoperation/configuration-swift.class"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
