{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security",
        "doc://com.apple.security/documentation/Security/CSSM_APPLE_CL_CSR_REQUEST"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/CSSM_APPLE_CL_CSR_REQUEST/cspHand"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@SA@CSSM_APPLE_CL_CSR_REQUEST@FI@cspHand",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "cspHand"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CSSM_CSP_HANDLE",
        "text": "CSSM_CSP_HANDLE"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "cspHand"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "cspHand"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "cspHand"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/CSSM_CSP_HANDLE",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CSSM_CSP_HANDLE",
              "text": "CSSM_CSP_HANDLE"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_CL_CSR_REQUEST": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_APPLE_CL_CSR_REQUEST"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_CL_CSR_REQUEST",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_APPLE_CL_CSR_REQUEST"
        }
      ],
      "role": "symbol",
      "title": "CSSM_APPLE_CL_CSR_REQUEST",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_cl_csr_request"
    },
    "doc://com.apple.security/documentation/Security/CSSM_APPLE_CL_CSR_REQUEST/cspHand": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cspHand"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CSSM_CSP_HANDLE",
          "text": "CSSM_CSP_HANDLE"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_APPLE_CL_CSR_REQUEST/cspHand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cspHand"
        }
      ],
      "role": "symbol",
      "title": "cspHand",
      "type": "topic",
      "url": "/documentation/security/cssm_apple_cl_csr_request/csphand"
    },
    "doc://com.apple.security/documentation/Security/CSSM_CSP_HANDLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_CSP_HANDLE"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_CSP_HANDLE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_CSP_HANDLE"
        }
      ],
      "role": "symbol",
      "title": "CSSM_CSP_HANDLE",
      "type": "topic",
      "url": "/documentation/security/cssm_csp_handle"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "cspHand"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cspHand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.security/documentation/Security",
                "doc://com.apple.security/documentation/Security/CSSM_APPLE_CL_CSR_REQUEST"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "identifier": "doc://com.apple.security/documentation/Security/CSSM_CSP_HANDLE",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CSSM_CSP_HANDLE",
                    "text": "CSSM_CSP_HANDLE"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "cspHand"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_CL_CSR_REQUEST~1cspHand/title",
          "value": "cspHand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_CL_CSR_REQUEST~1cspHand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cspHand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_CL_CSR_REQUEST/title",
          "value": "CSSM_APPLE_CL_CSR_REQUEST"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_CL_CSR_REQUEST/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_APPLE_CL_CSR_REQUEST"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_APPLE_CL_CSR_REQUEST/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_APPLE_CL_CSR_REQUEST"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_CSP_HANDLE/title",
          "value": "CSSM_CSP_HANDLE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_CSP_HANDLE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_CSP_HANDLE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_CSP_HANDLE/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_CSP_HANDLE"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/cssm_apple_cl_csr_request/csphand"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/security/cssm_apple_cl_csr_request/csphand"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
