{
  "abstract": [
    {
      "text": "Provides the start time of the filter’s image input clip.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "FxPlug",
      "versions": [
        "4.0",
        "4.2.9"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/startTimeOfInput(toFilter:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)FxTimingAPI_v4(im)startTimeOfInputToFilter:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "startTimeOfInput"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "toFilter"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@CMTime",
        "text": "CMTime"
      },
      {
        "kind": "text",
        "text": ">!)"
      }
    ],
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "startTimeOfInputToFilter:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "4.0",
        "name": "FxPlug"
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "startTimeOfInput(toFilter:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Unsupported OS: FxPlug"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "startTimeOfInput"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "toFilter"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "startTime"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@SA@CMTime",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@CMTime",
              "text": "CMTime"
            },
            {
              "kind": "text",
              "text": ">!)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The time when the filter’s image input object starts, in ",
                  "type": "text"
                },
                {
                  "code": "CMTime",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "startTime"
        }
      ]
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/understanding-time-in-fxplug"
      ]
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In Motion, this value represents the start time of the clip to which the user applies the effect, relative to the timeline time. This start time accounts for any trimming or retiming. It is the start time on the timeline of the first visible frame of the object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In Final Cut Pro, this value represents the start time of the object relative to its native start, after retiming or trimming. For example, if the user trimmed the clip’s head by 10 seconds, then the start time is 10 seconds. If the user then retimes the clip by 200-percent, the start time is 5 seconds.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/understanding-time-in-fxplug": {
      "abstract": [
        {
          "text": "Learn about time handling in host apps and plug-ins.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/understanding-time-in-fxplug",
      "kind": "article",
      "role": "article",
      "title": "Understanding time in FxPlug",
      "type": "topic",
      "url": "/documentation/professional-video-applications/understanding-time-in-fxplug"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4": {
      "abstract": [
        {
          "text": "A protocol that defines the methods provided by the host, so that a plug-in can query the timing properties of its input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxTimingAPI_v4"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxTimingAPI_v4"
        }
      ],
      "role": "symbol",
      "title": "FxTimingAPI_v4",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxtimingapi_v4"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/durationTime(_:ofImageParameter:)": {
      "abstract": [
        {
          "text": "Provides the duration of the clip the user assigns to the given image parameter for the effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "durationTime"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "externalParam",
          "text": "ofImageParameter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/durationTime(_:ofImageParameter:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "durationTime:ofImageParameter:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "durationTime(_:ofImageParameter:)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxtimingapi_v4/durationtime(_:ofimageparameter:)"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/durationTime(forEffect:)": {
      "abstract": [
        {
          "text": "Provides the duration time for the effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "durationTime"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forEffect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ">!)"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/durationTime(forEffect:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "durationTimeForEffect:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "durationTime(forEffect:)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxtimingapi_v4/durationtime(foreffect:)"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/durationTimeOfInput(toFilter:)": {
      "abstract": [
        {
          "text": "Provides the duration of the filter’s image input clip.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "durationTimeOfInput"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "toFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ">!)"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/durationTimeOfInput(toFilter:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "durationTimeOfInputToFilter:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "durationTimeOfInput(toFilter:)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxtimingapi_v4/durationtimeofinput(tofilter:)"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/fieldOrderForInput(toFilter:)": {
      "abstract": [
        {
          "text": "Returns the field order of the filter input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fieldOrderForInput"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "toFilter"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)FxTileableEffect",
          "text": "FxTileableEffect"
        },
        {
          "kind": "text",
          "text": ")!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FxFieldOrder",
          "text": "FxFieldOrder"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/fieldOrderForInput(toFilter:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fieldOrderForInputToFilter:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "fieldOrderForInput(toFilter:)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxtimingapi_v4/fieldorderforinput(tofilter:)"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/frameDuration(_:)": {
      "abstract": [
        {
          "text": "Provides the native frame duration of the object to which the effect is applied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frameDuration"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ">!)"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/frameDuration(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "frameDuration:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "frameDuration(_:)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxtimingapi_v4/frameduration(_:)"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/imageTime(_:forParameterID:fromTimelineTime:)": {
      "abstract": [
        {
          "text": "Converts from timeline time of the given parameter to image time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageTime"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "externalParam",
          "text": "forParameterID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "fromTimelineTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/imageTime(_:forParameterID:fromTimelineTime:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageTime:forParameterID:fromTimelineTime:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "imageTime(_:forParameterID:fromTimelineTime:)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxtimingapi_v4/imagetime(_:forparameterid:fromtimelinetime:)"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/inPointTimeOfTimeline(forEffect:)": {
      "abstract": [
        {
          "text": "The in point of the timeline on which the user applies the effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inPointTimeOfTimeline"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forEffect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ">!)"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/inPointTimeOfTimeline(forEffect:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inPointTimeOfTimelineForEffect:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "inPointTimeOfTimeline(forEffect:)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxtimingapi_v4/inpointtimeoftimeline(foreffect:)"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/inputTime(_:fromTimelineTime:)": {
      "abstract": [
        {
          "text": "Converts from timeline time to time of the filter’s image input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inputTime"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "externalParam",
          "text": "fromTimelineTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/inputTime(_:fromTimelineTime:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inputTime:fromTimelineTime:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "inputTime(_:fromTimelineTime:)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxtimingapi_v4/inputtime(_:fromtimelinetime:)"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/outPointTimeOfTimeline(forEffect:)": {
      "abstract": [
        {
          "text": "The out point of the timeline on which the user applies the effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outPointTimeOfTimeline"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forEffect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ">!)"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/outPointTimeOfTimeline(forEffect:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "outPointTimeOfTimelineForEffect:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "outPointTimeOfTimeline(forEffect:)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxtimingapi_v4/outpointtimeoftimeline(foreffect:)"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/sampleDuration(_:)": {
      "abstract": [
        {
          "text": "Provides the native sample duration of the object to which the effect is applied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sampleDuration"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ">!)"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/sampleDuration(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sampleDuration:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "sampleDuration(_:)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxtimingapi_v4/sampleduration(_:)"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/start(_:ofImageParameter:)": {
      "abstract": [
        {
          "text": "Provides the start time of the clip the user assigned to the given image parameter for the effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "start"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "externalParam",
          "text": "ofImageParameter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/start(_:ofImageParameter:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startTime:ofImageParameter:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "start(_:ofImageParameter:)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxtimingapi_v4/start(_:ofimageparameter:)"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/startTime(forEffect:)": {
      "abstract": [
        {
          "text": "Provides the start time for the effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startTime"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forEffect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ">!)"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/startTime(forEffect:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startTimeForEffect:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "startTime(forEffect:)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxtimingapi_v4/starttime(foreffect:)"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/startTimeOfInput(toFilter:)": {
      "abstract": [
        {
          "text": "Provides the start time of the filter’s image input clip.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startTimeOfInput"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "toFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ">!)"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/startTimeOfInput(toFilter:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startTimeOfInputToFilter:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "startTimeOfInput(toFilter:)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxtimingapi_v4/starttimeofinput(tofilter:)"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/timelineFpsNumerator(for:)": {
      "abstract": [
        {
          "text": "The numerator of the timeline’s frame rate where the user applies the effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timelineFpsNumerator"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)FxTileableEffect",
          "text": "FxTileableEffect"
        },
        {
          "kind": "text",
          "text": ")!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/timelineFpsNumerator(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "timelineFpsNumeratorForEffect:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "timelineFpsNumerator(for:)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxtimingapi_v4/timelinefpsnumerator(for:)"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/timelineTime(_:fromImageTime:forParameterID:)": {
      "abstract": [
        {
          "text": "Converts from image time of the given parameter to timeline time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timelineTime"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "externalParam",
          "text": "fromImageTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "forParameterID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/timelineTime(_:fromImageTime:forParameterID:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "timelineTime:fromImageTime:forParameterID:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "timelineTime(_:fromImageTime:forParameterID:)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxtimingapi_v4/timelinetime(_:fromimagetime:forparameterid:)"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/timelineTime(_:fromInputTime:)": {
      "abstract": [
        {
          "text": "Converts from input time of the filter’s image input to timeline time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timelineTime"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "externalParam",
          "text": "fromInputTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/timelineTime(_:fromInputTime:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "timelineTime:fromInputTime:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "timelineTime(_:fromInputTime:)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxtimingapi_v4/timelinetime(_:frominputtime:)"
    },
    "doc://com.externally.resolved.symbol/c:@SA@CMTime": {
      "abstract": [
        {
          "text": "A structure that represents time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@SA@CMTime",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTime",
      "type": "topic",
      "url": "/documentation/CoreMedia/CMTime"
    },
    "doc://com.externally.resolved.symbol/s:Sp": {
      "abstract": [
        {
          "text": "A pointer for accessing and manipulating data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sp",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutablePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutablePointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-Timing-Values",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/frameDuration(_:)",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/sampleDuration(_:)",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/startTime(forEffect:)",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/durationTime(forEffect:)",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/durationTimeOfInput(toFilter:)",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/start(_:ofImageParameter:)",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/durationTime(_:ofImageParameter:)",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/inPointTimeOfTimeline(forEffect:)",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/outPointTimeOfTimeline(forEffect:)",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/timelineTime(_:fromInputTime:)",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/timelineTime(_:fromImageTime:forParameterID:)",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/inputTime(_:fromTimelineTime:)",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/imageTime(_:forParameterID:fromTimelineTime:)",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/fieldOrderForInput(toFilter:)",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/timelineFpsNumerator(for:)"
      ],
      "title": "Accessing Timing Values"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "startTimeOfInputToFilter:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startTimeOfInputToFilter:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-Timing-Values",
              "generated": true,
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/frameDuration(_:)",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/sampleDuration(_:)",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/startTime(forEffect:)",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/durationTime(forEffect:)",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/durationTimeOfInput(toFilter:)",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/start(_:ofImageParameter:)",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/durationTime(_:ofImageParameter:)",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/inPointTimeOfTimeline(forEffect:)",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/outPointTimeOfTimeline(forEffect:)",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/timelineTime(_:fromInputTime:)",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/timelineTime(_:fromImageTime:forParameterID:)",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/inputTime(_:fromTimelineTime:)",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/imageTime(_:forParameterID:fromTimelineTime:)",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/fieldOrderForInput(toFilter:)",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTimingAPI_v4/timelineFpsNumerator(for:)"
              ],
              "title": "Accessing Timing Values"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Unsupported OS: FxPlug"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "startTimeOfInputToFilter:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@SA@CMTime",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@SA@CMTime",
                    "text": "CMTime"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "startTime"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The time when the filter’s image input object starts, in ",
                        "type": "text"
                      },
                      {
                        "code": "CMTime",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "startTime"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxTimingAPI_v4~1fieldOrderForInput(toFilter:)/title",
          "value": "fieldOrderForInputToFilter:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxTimingAPI_v4~1fieldOrderForInput(toFilter:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "fieldOrderForInputToFilter:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxTimingAPI_v4~1durationTime(forEffect:)/title",
          "value": "durationTimeForEffect:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxTimingAPI_v4~1durationTime(forEffect:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "durationTimeForEffect:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxTimingAPI_v4~1timelineFpsNumerator(for:)/title",
          "value": "timelineFpsNumeratorForEffect:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxTimingAPI_v4~1timelineFpsNumerator(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "timelineFpsNumeratorForEffect:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxTimingAPI_v4~1startTime(forEffect:)/title",
          "value": "startTimeForEffect:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxTimingAPI_v4~1startTime(forEffect:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startTimeForEffect:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxTimingAPI_v4~1inputTime(_:fromTimelineTime:)/title",
          "value": "inputTime:fromTimelineTime:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxTimingAPI_v4~1inputTime(_:fromTimelineTime:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "inputTime:fromTimelineTime:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxTimingAPI_v4~1timelineTime(_:fromInputTime:)/title",
          "value": "timelineTime:fromInputTime:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxTimingAPI_v4~1timelineTime(_:fromInputTime:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "timelineTime:fromInputTime:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxTimingAPI_v4/title",
          "value": "FxTimingAPI_v4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxTimingAPI_v4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxTimingAPI_v4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxTimingAPI_v4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxTimingAPI_v4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxTimingAPI_v4~1durationTimeOfInput(toFilter:)/title",
          "value": "durationTimeOfInputToFilter:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxTimingAPI_v4~1durationTimeOfInput(toFilter:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "durationTimeOfInputToFilter:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxTimingAPI_v4~1frameDuration(_:)/title",
          "value": "frameDuration:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxTimingAPI_v4~1frameDuration(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "frameDuration:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxTimingAPI_v4~1inPointTimeOfTimeline(forEffect:)/title",
          "value": "inPointTimeOfTimelineForEffect:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxTimingAPI_v4~1inPointTimeOfTimeline(forEffect:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "inPointTimeOfTimelineForEffect:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxTimingAPI_v4~1startTimeOfInput(toFilter:)/title",
          "value": "startTimeOfInputToFilter:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxTimingAPI_v4~1startTimeOfInput(toFilter:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startTimeOfInputToFilter:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxTimingAPI_v4~1start(_:ofImageParameter:)/title",
          "value": "startTime:ofImageParameter:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxTimingAPI_v4~1start(_:ofImageParameter:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startTime:ofImageParameter:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxTimingAPI_v4~1imageTime(_:forParameterID:fromTimelineTime:)/title",
          "value": "imageTime:forParameterID:fromTimelineTime:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxTimingAPI_v4~1imageTime(_:forParameterID:fromTimelineTime:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "imageTime:forParameterID:fromTimelineTime:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxTimingAPI_v4~1sampleDuration(_:)/title",
          "value": "sampleDuration:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxTimingAPI_v4~1sampleDuration(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "sampleDuration:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@SA@CMTime/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " { ... } "
            },
            {
              "kind": "identifier",
              "text": "CMTime"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxTimingAPI_v4~1outPointTimeOfTimeline(forEffect:)/title",
          "value": "outPointTimeOfTimelineForEffect:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxTimingAPI_v4~1outPointTimeOfTimeline(forEffect:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "outPointTimeOfTimelineForEffect:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxTimingAPI_v4~1timelineTime(_:fromImageTime:forParameterID:)/title",
          "value": "timelineTime:fromImageTime:forParameterID:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxTimingAPI_v4~1timelineTime(_:fromImageTime:forParameterID:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "timelineTime:fromImageTime:forParameterID:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxTimingAPI_v4~1durationTime(_:ofImageParameter:)/title",
          "value": "durationTime:ofImageParameter:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxTimingAPI_v4~1durationTime(_:ofImageParameter:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "durationTime:ofImageParameter:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional_video_applications/fxtimingapi_v4/starttimeofinput(tofilter:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/professional_video_applications/fxtimingapi_v4/starttimeofinput(tofilter:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
