{
  "abstract": [
    {
      "text": "Provides information about the vehicle’s power level.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INGetCarPowerLevelStatusIntentResponseObserver"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INGetCarPowerLevelStatusIntentResponseObserver/didUpdate(getCarPowerLevelStatus:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)INGetCarPowerLevelStatusIntentResponseObserver(im)getCarPowerLevelStatusResponseDidUpdate:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "didUpdate"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "getCarPowerLevelStatus"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)INGetCarPowerLevelStatusIntentResponse",
        "text": "INGetCarPowerLevelStatusIntentResponse"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "getCarPowerLevelStatusResponseDidUpdate:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "didUpdate(getCarPowerLevelStatus:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "didUpdate"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "getCarPowerLevelStatus"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "response"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetCarPowerLevelStatusIntentResponse",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)INGetCarPowerLevelStatusIntentResponse",
              "text": "INGetCarPowerLevelStatusIntentResponse"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The response object that contains current power level information.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "response"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You call this method to deliver updated power level information to Maps, which only requests updates during an active navigation session. During that session, Maps regularly asks for the vehicle’s power level status using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetCarPowerLevelStatusIntent",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Only call this method when there’s an abrupt change in the vehicle’s battery charge—a 3 percent or greater drop—since handling the last intent.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetCarPowerLevelStatusIntent": {
      "abstract": [
        {
          "text": "A request for the current power level of the user’s car.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INGetCarPowerLevelStatusIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetCarPowerLevelStatusIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INGetCarPowerLevelStatusIntent"
        }
      ],
      "role": "symbol",
      "title": "INGetCarPowerLevelStatusIntent",
      "type": "topic",
      "url": "/documentation/intents/ingetcarpowerlevelstatusintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetCarPowerLevelStatusIntentResponse": {
      "abstract": [
        {
          "text": "Your app’s response to a request for the vehicle power level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INGetCarPowerLevelStatusIntentResponse"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetCarPowerLevelStatusIntentResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INGetCarPowerLevelStatusIntentResponse"
        }
      ],
      "role": "symbol",
      "title": "INGetCarPowerLevelStatusIntentResponse",
      "type": "topic",
      "url": "/documentation/intents/ingetcarpowerlevelstatusintentresponse"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetCarPowerLevelStatusIntentResponseObserver": {
      "abstract": [
        {
          "text": "The interface for providing updates of a vehicle’s power level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INGetCarPowerLevelStatusIntentResponseObserver"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetCarPowerLevelStatusIntentResponseObserver",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INGetCarPowerLevelStatusIntentResponseObserver"
        }
      ],
      "role": "symbol",
      "title": "INGetCarPowerLevelStatusIntentResponseObserver",
      "type": "topic",
      "url": "/documentation/intents/ingetcarpowerlevelstatusintentresponseobserver"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetCarPowerLevelStatusIntentResponseObserver/didUpdate(getCarPowerLevelStatus:)": {
      "abstract": [
        {
          "text": "Provides information about the vehicle’s power level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didUpdate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "getCarPowerLevelStatus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INGetCarPowerLevelStatusIntentResponse",
          "text": "INGetCarPowerLevelStatusIntentResponse"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetCarPowerLevelStatusIntentResponseObserver/didUpdate(getCarPowerLevelStatus:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getCarPowerLevelStatusResponseDidUpdate:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "didUpdate(getCarPowerLevelStatus:)",
      "type": "topic",
      "url": "/documentation/intents/ingetcarpowerlevelstatusintentresponseobserver/didupdate(getcarpowerlevelstatus:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "getCarPowerLevelStatusResponseDidUpdate:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "getCarPowerLevelStatusResponseDidUpdate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INGetCarPowerLevelStatusIntentResponseObserver"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "getCarPowerLevelStatusResponseDidUpdate:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetCarPowerLevelStatusIntentResponse",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)INGetCarPowerLevelStatusIntentResponse",
                    "text": "INGetCarPowerLevelStatusIntentResponse"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "response"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The response object that contains current power level information.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "response"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetCarPowerLevelStatusIntentResponseObserver~1didUpdate(getCarPowerLevelStatus:)/title",
          "value": "getCarPowerLevelStatusResponseDidUpdate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetCarPowerLevelStatusIntentResponseObserver~1didUpdate(getCarPowerLevelStatus:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "getCarPowerLevelStatusResponseDidUpdate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetCarPowerLevelStatusIntent/title",
          "value": "INGetCarPowerLevelStatusIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetCarPowerLevelStatusIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetCarPowerLevelStatusIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetCarPowerLevelStatusIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetCarPowerLevelStatusIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetCarPowerLevelStatusIntentResponse/title",
          "value": "INGetCarPowerLevelStatusIntentResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetCarPowerLevelStatusIntentResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetCarPowerLevelStatusIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetCarPowerLevelStatusIntentResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetCarPowerLevelStatusIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetCarPowerLevelStatusIntentResponseObserver/title",
          "value": "INGetCarPowerLevelStatusIntentResponseObserver"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetCarPowerLevelStatusIntentResponseObserver/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetCarPowerLevelStatusIntentResponseObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetCarPowerLevelStatusIntentResponseObserver/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetCarPowerLevelStatusIntentResponseObserver"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/ingetcarpowerlevelstatusintentresponseobserver/didupdate(getcarpowerlevelstatus:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/ingetcarpowerlevelstatusintentresponseobserver/didupdate(getcarpowerlevelstatus:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
