{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeFlags"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeFlags/kSMPTETimeUnknown"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SMPTETimeFlags@kSMPTETimeUnknown",
    "fragments": [
      {
        "kind": "identifier",
        "text": "kSMPTETimeUnknown"
      }
    ],
    "modules": [
      {
        "name": "Core Audio Types"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kSMPTETimeUnknown"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "10.11",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      },
      {
        "beta": false,
        "introducedAt": "3.0",
        "name": "watchOS"
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "symbolKind": "case",
    "title": "kSMPTETimeUnknown"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "kSMPTETimeUnknown"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes": {
      "abstract": [
        {
          "text": "Use specialized data types to interact with audio streams, complex buffers, and audiovisual timestamps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio Types",
      "type": "topic",
      "url": "/documentation/coreaudiotypes"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeFlags": {
      "abstract": [
        {
          "text": "A structure that defines SMPTE time flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SMPTETimeFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SMPTETimeFlags"
        }
      ],
      "role": "symbol",
      "title": "SMPTETimeFlags",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/smptetimeflags"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeFlags/kSMPTETimeUnknown": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSMPTETimeUnknown"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeFlags/kSMPTETimeUnknown",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSMPTETimeUnknown",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/smptetimeflags/ksmptetimeunknown"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeFlags/running": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "running"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SMPTETimeFlags",
          "text": "SMPTETimeFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeFlags/running",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSMPTETimeRunning"
        }
      ],
      "role": "symbol",
      "title": "running",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/smptetimeflags/running"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeFlags/valid": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "valid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SMPTETimeFlags",
          "text": "SMPTETimeFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeFlags/valid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSMPTETimeValid"
        }
      ],
      "role": "symbol",
      "title": "valid",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/smptetimeflags/valid"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeFlags/running",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeFlags/valid"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETimeFlags~1running/title",
          "value": "kSMPTETimeRunning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETimeFlags~1running/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSMPTETimeRunning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETimeFlags~1valid/title",
          "value": "kSMPTETimeValid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETimeFlags~1valid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSMPTETimeValid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETimeFlags/title",
          "value": "SMPTETimeFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETimeFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SMPTETimeFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETimeFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SMPTETimeFlags"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudiotypes/smptetimeflags/ksmptetimeunknown"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
