{
  "abstract": [
    {
      "text": "An angle in radians that indicates the azimuthal direction to the nearby object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject/horizontalAngle-9ibky"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NINearbyObject(py)horizontalAngle",
    "fragments": [
      {
        "kind": "identifier",
        "text": "horizontalAngle"
      }
    ],
    "modules": [
      {
        "name": "Nearby Interaction"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "horizontalAngle"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "horizontalAngle"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:f",
              "text": "float"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "horizontalAngle"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The framework sets a value of this property when ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyPeerConfiguration/isCameraAssistanceEnabled",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " is ",
              "type": "text"
            },
            {
              "code": "true",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The value of this property is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObjectAngleNotAvailable",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " when direction is unavailable, such as when the app runs on Apple Watch.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction": {
      "abstract": [
        {
          "text": "Locate and interact with nearby devices using identifiers, distance, and direction.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction",
      "kind": "symbol",
      "role": "collection",
      "title": "Nearby Interaction",
      "type": "topic",
      "url": "/documentation/nearbyinteraction"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject": {
      "abstract": [
        {
          "text": "Location information for a peer device in an interaction session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NINearbyObject"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NINearbyObject"
        }
      ],
      "role": "symbol",
      "title": "NINearbyObject",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/ninearbyobject"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject/VerticalDirectionEstimate-swift.enum": {
      "abstract": [
        {
          "text": "Estimations of a nearby object’s vertical position in relation to the user’s device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VerticalDirectionEstimate"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject/VerticalDirectionEstimate-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VerticalDirectionEstimate"
        }
      ],
      "role": "symbol",
      "title": "NINearbyObject.VerticalDirectionEstimate",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/ninearbyobject/verticaldirectionestimate-swift.enum"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject/direction-5xcld": {
      "abstract": [
        {
          "text": "A vector that points from the user’s device in the direction of the peer device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "direction"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject/direction-5xcld",
      "kind": "symbol",
      "role": "symbol",
      "title": "direction",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/ninearbyobject/direction-5xcld"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject/horizontalAngle-9ibky": {
      "abstract": [
        {
          "text": "An angle in radians that indicates the azimuthal direction to the nearby object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "horizontalAngle"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject/horizontalAngle-9ibky",
      "kind": "symbol",
      "role": "symbol",
      "title": "horizontalAngle",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/ninearbyobject/horizontalangle-9ibky"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject/verticalDirectionEstimate-swift.property": {
      "abstract": [
        {
          "text": "The estimation of a nearby object’s vertical position as it relates to the user’s device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "verticalDirectionEstimate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NINearbyObject",
          "text": "NINearbyObject"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NINearbyObjectVerticalDirectionEstimate",
          "text": "VerticalDirectionEstimate"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject/verticalDirectionEstimate-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "verticalDirectionEstimate"
        }
      ],
      "role": "symbol",
      "title": "verticalDirectionEstimate",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/ninearbyobject/verticaldirectionestimate-swift.property"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObjectAngleNotAvailable": {
      "abstract": [
        {
          "text": "A value that indicates that a nearby object’s horizontal angle is unavailable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NINearbyObjectAngleNotAvailable"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObjectAngleNotAvailable",
      "kind": "symbol",
      "role": "symbol",
      "title": "NINearbyObjectAngleNotAvailable",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/ninearbyobjectanglenotavailable"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObjectDirectionNotAvailable": {
      "abstract": [
        {
          "text": "A value that indicates that a nearby object’s direction is unavailable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NINearbyObjectDirectionNotAvailable"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObjectDirectionNotAvailable",
      "kind": "symbol",
      "role": "symbol",
      "title": "NINearbyObjectDirectionNotAvailable",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/ninearbyobjectdirectionnotavailable"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyPeerConfiguration/isCameraAssistanceEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that combines the spatial awareness of ARKit with Nearby Interaction to improve the accuracy of a nearby object’s position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isCameraAssistanceEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyPeerConfiguration/isCameraAssistanceEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cameraAssistanceEnabled"
        }
      ],
      "role": "symbol",
      "title": "isCameraAssistanceEnabled",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/ninearbypeerconfiguration/iscameraassistanceenabled"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Acquiring-relative-direction",
      "generated": true,
      "identifiers": [
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject/direction-5xcld",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObjectDirectionNotAvailable",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObjectAngleNotAvailable",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject/verticalDirectionEstimate-swift.property",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject/VerticalDirectionEstimate-swift.enum"
      ],
      "title": "Acquiring relative direction"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyPeerConfiguration~1isCameraAssistanceEnabled/title",
          "value": "cameraAssistanceEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyPeerConfiguration~1isCameraAssistanceEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cameraAssistanceEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyObject/title",
          "value": "NINearbyObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NINearbyObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyObject/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NINearbyObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyObject~1VerticalDirectionEstimate-swift.enum/title",
          "value": "NINearbyObjectVerticalDirectionEstimate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyObject~1VerticalDirectionEstimate-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NINearbyObjectVerticalDirectionEstimate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyObject~1VerticalDirectionEstimate-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NINearbyObjectVerticalDirectionEstimate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyObject~1verticalDirectionEstimate-swift.property/title",
          "value": "verticalDirectionEstimate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyObject~1verticalDirectionEstimate-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "verticalDirectionEstimate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/nearbyinteraction/ninearbyobject/horizontalangle-9ibky"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
