{
  "abstract": [
    {
      "text": "Create and inspect layers that encapsulate operations and configuration details to receive, process, and output tensors.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mlcompute/documentation/MLCompute"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mlcompute/documentation/MLCompute/layers"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "ML Compute"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Layers"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute": {
      "abstract": [
        {
          "text": "Accelerate training and validation of neural networks across the CPU and one or more GPUs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute",
      "kind": "symbol",
      "role": "collection",
      "title": "ML Compute",
      "type": "topic",
      "url": "/documentation/mlcompute"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer": {
      "abstract": [
        {
          "text": "A layer that applies an activation function to the source tensor and produces an output.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCActivationLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationlayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticLayer": {
      "abstract": [
        {
          "text": "A layer that performs an arithmetic operation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCArithmeticLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticlayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCBatchNormalizationLayer": {
      "abstract": [
        {
          "text": "A layer that normalizes a batch of inputs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCBatchNormalizationLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCBatchNormalizationLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCBatchNormalizationLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCBatchNormalizationLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcbatchnormalizationlayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonLayer": {
      "abstract": [
        {
          "text": "A layer that performs elementwise comparison of two tensors.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCComparisonLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCComparisonLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCComparisonLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlccomparisonlayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCConcatenationLayer": {
      "abstract": [
        {
          "text": "A layer that combines tensors into a single tensor.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCConcatenationLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCConcatenationLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCConcatenationLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCConcatenationLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcconcatenationlayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCConvolutionLayer": {
      "abstract": [
        {
          "text": "A layer that applies a convolution over a signal.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCConvolutionLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCConvolutionLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCConvolutionLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCConvolutionLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcconvolutionlayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCDropoutLayer": {
      "abstract": [
        {
          "text": "A layer that deactivates neurons randomly to avoid overfitting.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCDropoutLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCDropoutLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCDropoutLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCDropoutLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcdropoutlayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCEmbeddingLayer": {
      "abstract": [
        {
          "text": "A layer that stores a word embedding.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCEmbeddingLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCEmbeddingLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCEmbeddingLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCEmbeddingLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcembeddinglayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCFullyConnectedLayer": {
      "abstract": [
        {
          "text": "A layer that connects each input to each output within its layer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCFullyConnectedLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCFullyConnectedLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCFullyConnectedLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCFullyConnectedLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcfullyconnectedlayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCGatherLayer": {
      "abstract": [
        {
          "text": "A layer that fetches data at the locations you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCGatherLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCGatherLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCGatherLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCGatherLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcgatherlayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCGramMatrixLayer": {
      "abstract": [
        {
          "text": "A layer that computes the uncentered cross-correlation values between the spacial planes of each feature channel of a tensor.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCGramMatrixLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCGramMatrixLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCGramMatrixLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCGramMatrixLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcgrammatrixlayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCGroupNormalizationLayer": {
      "abstract": [
        {
          "text": "A layer that divides the channels into groups for normalization.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCGroupNormalizationLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCGroupNormalizationLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCGroupNormalizationLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCGroupNormalizationLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcgroupnormalizationlayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCInstanceNormalizationLayer": {
      "abstract": [
        {
          "text": "A layer that normalizes all features of one channel.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCInstanceNormalizationLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCInstanceNormalizationLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCInstanceNormalizationLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCInstanceNormalizationLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcinstancenormalizationlayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer": {
      "abstract": [
        {
          "text": "A layer that represents long short-term memory (LSTM) networks.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCLSTMLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCLSTMLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCLSTMLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclstmlayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayer": {
      "abstract": [
        {
          "text": "The base class for all framework layers.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayerNormalizationLayer": {
      "abstract": [
        {
          "text": "A layer that applies layer normalization over inputs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCLayerNormalizationLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayerNormalizationLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCLayerNormalizationLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCLayerNormalizationLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclayernormalizationlayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer": {
      "abstract": [
        {
          "text": "A layer that estimates the inaccuracies of the model to reduce the loss on the next evaluation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCLossLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCLossLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCLossLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclosslayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCMatMulLayer": {
      "abstract": [
        {
          "text": "A layer that multiplies matrices.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCMatMulLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCMatMulLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCMatMulLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCMatMulLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcmatmullayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCMultiheadAttentionLayer": {
      "abstract": [
        {
          "text": "A multihead, scaled dot-product attention layer that attends to one or more entries in the input key-value pairs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCMultiheadAttentionLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCMultiheadAttentionLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCMultiheadAttentionLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCMultiheadAttentionLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcmultiheadattentionlayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingLayer": {
      "abstract": [
        {
          "text": "A layer that pads a tensor with the padding sizes you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCPaddingLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCPaddingLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCPaddingLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpaddinglayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingPolicy-3hic8": {
      "abstract": [
        {
          "text": "A padding policy that you specify for a convolution or pooling layer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCPaddingPolicy"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingPolicy-3hic8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCPaddingPolicy"
        }
      ],
      "role": "symbol",
      "title": "MLCPaddingPolicy",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpaddingpolicy-3hic8"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingType": {
      "abstract": [
        {
          "text": "A padding type that you specify for a padding layer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCPaddingType"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCPaddingType"
        }
      ],
      "role": "symbol",
      "title": "MLCPaddingType",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpaddingtype"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPlatform": {
      "abstract": [
        {
          "text": "A utility class for setting global properties in the framework.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCPlatform"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPlatform",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCPlatform"
        }
      ],
      "role": "symbol",
      "title": "MLCPlatform",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcplatform"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingLayer": {
      "abstract": [
        {
          "text": "A layer that summarizes the average presence of a feature.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCPoolingLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCPoolingLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCPoolingLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolinglayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionLayer": {
      "abstract": [
        {
          "text": "A layer that reduces tensor values across a specific dimension to a scalar value.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCReductionLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCReductionLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCReductionLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcreductionlayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCReshapeLayer": {
      "abstract": [
        {
          "text": "A layer that reshapes a tensor with the shape you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCReshapeLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCReshapeLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCReshapeLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCReshapeLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcreshapelayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCScatterLayer": {
      "abstract": [
        {
          "text": "A layer that updates the output at an index you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCScatterLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCScatterLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCScatterLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCScatterLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcscatterlayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCSelectionLayer": {
      "abstract": [
        {
          "text": "A layer for selecting elements from two tensors.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCSelectionLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCSelectionLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCSelectionLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCSelectionLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcselectionlayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCSliceLayer": {
      "abstract": [
        {
          "text": "A layer that extracts a slice from a tensor.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCSliceLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCSliceLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCSliceLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCSliceLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcslicelayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCSoftmaxLayer": {
      "abstract": [
        {
          "text": "A layer that outputs a probability distribution as attention weights.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCSoftmaxLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCSoftmaxLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCSoftmaxLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCSoftmaxLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcsoftmaxlayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCSplitLayer": {
      "abstract": [
        {
          "text": "A layer that splits a tensor value into a list of subtensors.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCSplitLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCSplitLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCSplitLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCSplitLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcsplitlayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor": {
      "abstract": [
        {
          "text": "The data object you use throughout the framework.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCTensor"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCTensor"
        }
      ],
      "role": "symbol",
      "title": "MLCTensor",
      "type": "topic",
      "url": "/documentation/mlcompute/mlctensor"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCTransposeLayer": {
      "abstract": [
        {
          "text": "A layer that permutes the dimensions you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCTransposeLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTransposeLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCTransposeLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCTransposeLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlctransposelayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCUpsampleLayer": {
      "abstract": [
        {
          "text": "A layer that applies upsampling with the shape you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCUpsampleLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCUpsampleLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCUpsampleLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCUpsampleLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcupsamplelayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossLayer": {
      "abstract": [
        {
          "text": "A layer that estimates loss for the YOLO algorithm.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCYOLOLossLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCYOLOLossLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCYOLOLossLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcyololosslayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/training-and-validation": {
      "abstract": [
        {
          "text": "Create, train, and validate a graph to produce acceptable prediction results.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/training-and-validation",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Training and Validation",
      "type": "topic",
      "url": "/documentation/mlcompute/training-and-validation"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Components",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPlatform",
        "doc://com.apple.mlcompute/documentation/MLCompute/training-and-validation"
      ],
      "title": "Components"
    }
  ],
  "topicSections": [
    {
      "anchor": "Activation-Layers",
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCMultiheadAttentionLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCSoftmaxLayer"
      ],
      "title": "Activation Layers"
    },
    {
      "anchor": "Math-Layers",
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCMatMulLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCFullyConnectedLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCGramMatrixLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonLayer"
      ],
      "title": "Math Layers"
    },
    {
      "anchor": "Transformation-Layers",
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCTransposeLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCConcatenationLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCReshapeLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCSliceLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCSplitLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCScatterLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCSelectionLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCGatherLayer"
      ],
      "title": "Transformation Layers"
    },
    {
      "anchor": "Normalization-Layers",
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayerNormalizationLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCBatchNormalizationLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCGroupNormalizationLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCInstanceNormalizationLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCDropoutLayer"
      ],
      "title": "Normalization Layers"
    },
    {
      "anchor": "Convolution-and-Recurrent-Layers",
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCConvolutionLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCUpsampleLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCEmbeddingLayer"
      ],
      "title": "Convolution and Recurrent Layers"
    },
    {
      "anchor": "Loss-Layers",
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossLayer"
      ],
      "title": "Loss Layers"
    },
    {
      "anchor": "Base-Layer",
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayer"
      ],
      "title": "Base Layer"
    },
    {
      "anchor": "Supporting-Types",
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingPolicy-3hic8",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingType"
      ],
      "title": "Supporting Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Activation-Layers",
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCMultiheadAttentionLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCSoftmaxLayer"
              ],
              "title": "Activation Layers"
            },
            {
              "anchor": "Math-Layers",
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCMatMulLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCFullyConnectedLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCGramMatrixLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonLayer"
              ],
              "title": "Math Layers"
            },
            {
              "anchor": "Transformation-Layers",
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCTransposeLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCConcatenationLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCReshapeLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCSliceLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCSplitLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCScatterLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCSelectionLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCGatherLayer"
              ],
              "title": "Transformation Layers"
            },
            {
              "anchor": "Normalization-Layers",
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayerNormalizationLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCBatchNormalizationLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCGroupNormalizationLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCInstanceNormalizationLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCDropoutLayer"
              ],
              "title": "Normalization Layers"
            },
            {
              "anchor": "Convolution-and-Recurrent-Layers",
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCConvolutionLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCUpsampleLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCEmbeddingLayer"
              ],
              "title": "Convolution and Recurrent Layers"
            },
            {
              "anchor": "Loss-Layers",
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossLayer"
              ],
              "title": "Loss Layers"
            },
            {
              "anchor": "Base-Layer",
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayer"
              ],
              "title": "Base Layer"
            },
            {
              "anchor": "Supporting-Types",
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingType"
              ],
              "title": "Supporting Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Components",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCPlatform",
                "doc://com.apple.mlcompute/documentation/MLCompute/training-and-validation"
              ],
              "title": "Components"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCReductionLayer/title",
          "value": "MLCReductionLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCReductionLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCReductionLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCReductionLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCReductionLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCGramMatrixLayer/title",
          "value": "MLCGramMatrixLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCGramMatrixLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCGramMatrixLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCGramMatrixLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCGramMatrixLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCSelectionLayer/title",
          "value": "MLCSelectionLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCSelectionLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCSelectionLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCSelectionLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCSelectionLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCFullyConnectedLayer/title",
          "value": "MLCFullyConnectedLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCFullyConnectedLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCFullyConnectedLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCFullyConnectedLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCFullyConnectedLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPaddingType/title",
          "value": "MLCPaddingType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPaddingType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCPaddingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPaddingType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCPaddingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCSoftmaxLayer/title",
          "value": "MLCSoftmaxLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCSoftmaxLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCSoftmaxLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCSoftmaxLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCSoftmaxLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPaddingLayer/title",
          "value": "MLCPaddingLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPaddingLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCPaddingLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPaddingLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCPaddingLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCComparisonLayer/title",
          "value": "MLCComparisonLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCComparisonLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCComparisonLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCComparisonLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCComparisonLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPlatform/title",
          "value": "MLCPlatform"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPlatform/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCPlatform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPlatform/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCPlatform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCReshapeLayer/title",
          "value": "MLCReshapeLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCReshapeLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCReshapeLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCReshapeLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCReshapeLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCDropoutLayer/title",
          "value": "MLCDropoutLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCDropoutLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCDropoutLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCDropoutLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCDropoutLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCGroupNormalizationLayer/title",
          "value": "MLCGroupNormalizationLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCGroupNormalizationLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCGroupNormalizationLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCGroupNormalizationLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCGroupNormalizationLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLayer/title",
          "value": "MLCLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCConvolutionLayer/title",
          "value": "MLCConvolutionLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCConvolutionLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCConvolutionLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCConvolutionLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCConvolutionLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCEmbeddingLayer/title",
          "value": "MLCEmbeddingLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCEmbeddingLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCEmbeddingLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCEmbeddingLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCEmbeddingLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCBatchNormalizationLayer/title",
          "value": "MLCBatchNormalizationLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCBatchNormalizationLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCBatchNormalizationLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCBatchNormalizationLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCBatchNormalizationLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossLayer/title",
          "value": "MLCYOLOLossLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCYOLOLossLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCYOLOLossLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMLayer/title",
          "value": "MLCLSTMLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLSTMLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLSTMLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCSplitLayer/title",
          "value": "MLCSplitLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCSplitLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCSplitLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCSplitLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCSplitLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCMultiheadAttentionLayer/title",
          "value": "MLCMultiheadAttentionLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCMultiheadAttentionLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCMultiheadAttentionLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCMultiheadAttentionLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCMultiheadAttentionLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLayerNormalizationLayer/title",
          "value": "MLCLayerNormalizationLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLayerNormalizationLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLayerNormalizationLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLayerNormalizationLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLayerNormalizationLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCConcatenationLayer/title",
          "value": "MLCConcatenationLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCConcatenationLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCConcatenationLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCConcatenationLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCConcatenationLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCGatherLayer/title",
          "value": "MLCGatherLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCGatherLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCGatherLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCGatherLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCGatherLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer/title",
          "value": "MLCActivationLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossLayer/title",
          "value": "MLCLossLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLossLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLossLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTransposeLayer/title",
          "value": "MLCTransposeLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTransposeLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCTransposeLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTransposeLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCTransposeLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCMatMulLayer/title",
          "value": "MLCMatMulLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCMatMulLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCMatMulLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCMatMulLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCMatMulLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPoolingLayer/title",
          "value": "MLCPoolingLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPoolingLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCPoolingLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPoolingLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCPoolingLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCInstanceNormalizationLayer/title",
          "value": "MLCInstanceNormalizationLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCInstanceNormalizationLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCInstanceNormalizationLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCInstanceNormalizationLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCInstanceNormalizationLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCScatterLayer/title",
          "value": "MLCScatterLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCScatterLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCScatterLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCScatterLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCScatterLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCSliceLayer/title",
          "value": "MLCSliceLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCSliceLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCSliceLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCSliceLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCSliceLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticLayer/title",
          "value": "MLCArithmeticLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensor/title",
          "value": "MLCTensor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCTensor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCTensor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCUpsampleLayer/title",
          "value": "MLCUpsampleLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCUpsampleLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCUpsampleLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCUpsampleLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCUpsampleLayer"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mlcompute/layers"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mlcompute/layers"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
