{
  "abstract": [
    {
      "text": "Constants that describe an arithmetic operation.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mlcompute/documentation/MLCompute"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MLCArithmeticOperation",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MLCArithmeticOperation"
      }
    ],
    "modules": [
      {
        "name": "ML Compute"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MLCArithmeticOperation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.3",
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MLCArithmeticOperation"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperation"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute": {
      "abstract": [
        {
          "text": "Accelerate training and validation of neural networks across the CPU and one or more GPUs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute",
      "kind": "symbol",
      "role": "collection",
      "title": "ML Compute",
      "type": "topic",
      "url": "/documentation/mlcompute"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticLayer/init(operation:)": {
      "abstract": [
        {
          "text": "Creates an arithmetic layer with the operation you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "operation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCArithmeticOperation",
          "text": "MLCArithmeticOperation"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticLayer/init(operation:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layerWithOperation:"
        }
      ],
      "role": "symbol",
      "title": "init(operation:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticlayer/init(operation:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation": {
      "abstract": [
        {
          "text": "Constants that describe an arithmetic operation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperation"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperation"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/MLCArithmeticOperationCount": {
      "abstract": [
        {
          "text": "The total number of arithmetic operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationCount"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/MLCArithmeticOperationCount",
      "kind": "symbol",
      "role": "symbol",
      "title": "MLCArithmeticOperationCount",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/mlcarithmeticoperationcount"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/acos": {
      "abstract": [
        {
          "text": "Calculates the element-wise inverse cosine of the input.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "acos"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/acos",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationAcos"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.acos",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/acos"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/acosh": {
      "abstract": [
        {
          "text": "Calculates the element-wise inverse hyperbolic cosine of the input.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "acosh"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/acosh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationAcosh"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.acosh",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/acosh"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/add": {
      "abstract": [
        {
          "text": "Calculates the element-wise sum of the inputs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "add"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/add",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationAdd"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.add",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/add"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/asin": {
      "abstract": [
        {
          "text": "Calculates the element-wise inverse sine of the input.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "asin"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/asin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationAsin"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.asin",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/asin"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/asinh": {
      "abstract": [
        {
          "text": "Calculates the element-wise inverse hyperbolic sine of the input.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "asinh"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/asinh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationAsinh"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.asinh",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/asinh"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/atan": {
      "abstract": [
        {
          "text": "Calculates the element-wise inverse tangent of the input.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "atan"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/atan",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationAtan"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.atan",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/atan"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/atanh": {
      "abstract": [
        {
          "text": "Calculates the element-wise inverse hyperbolic tangent of the input.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "atanh"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/atanh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationAtanh"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.atanh",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/atanh"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/ceil": {
      "abstract": [
        {
          "text": "Calculates the element-wise ceiling of the inputs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ceil"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/ceil",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationCeil"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.ceil",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/ceil"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/cos": {
      "abstract": [
        {
          "text": "Calculates the element-wise cosine of the input.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cos"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/cos",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationCos"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.cos",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/cos"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/cosh": {
      "abstract": [
        {
          "text": "Calculates the element-wise hyperbolic cosine of the input.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cosh"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/cosh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationCosh"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.cosh",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/cosh"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/debugDescription": {
      "abstract": [
        {
          "text": "A textual description of the arithmetic operation you use for debugging.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "debugDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/debugDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationDebugDescription"
        }
      ],
      "role": "symbol",
      "title": "debugDescription",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/debugdescription"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/divide": {
      "abstract": [
        {
          "text": "Calculates the element-wise division of the inputs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "divide"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/divide",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationDivide"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.divide",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/divide"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/divideNoNaN": {
      "abstract": [
        {
          "text": "Calculates the element-wise division of the inputs, and returns ",
          "type": "text"
        },
        {
          "code": "0",
          "type": "codeVoice"
        },
        {
          "text": " if the denominator is ",
          "type": "text"
        },
        {
          "code": "0",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "divideNoNaN"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/divideNoNaN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationDivideNoNaN"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.divideNoNaN",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/dividenonan"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/exp": {
      "abstract": [
        {
          "text": "Calculates the element-wise result of the exponent raised to the power of the input.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exp"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/exp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationExp"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.exp",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/exp"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/exp2": {
      "abstract": [
        {
          "text": "Calculates the element-wise result of the number 2 raised to the power of the input.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exp2"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/exp2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationExp2"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.exp2",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/exp2"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/floor": {
      "abstract": [
        {
          "text": "Calculates the element-wise floor of the inputs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "floor"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/floor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationFloor"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.floor",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/floor"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/init(rawValue:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/init(rawvalue:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/log": {
      "abstract": [
        {
          "text": "Calculates the element-wise natural logarithm of the input.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "log"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/log",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationLog"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.log",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/log"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/log2": {
      "abstract": [
        {
          "text": "Calculates the element-wise base 2 logarithm of the input.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "log2"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/log2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationLog2"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.log2",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/log2"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/max": {
      "abstract": [
        {
          "text": "Calculates the element-wise maximum the inputs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "max"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/max",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationMax"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.max",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/max"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/min": {
      "abstract": [
        {
          "text": "Calculates the element-wise minimum of the inputs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "min"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/min",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationMin"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.min",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/min"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/multiply": {
      "abstract": [
        {
          "text": "Calculates the element-wise product of the inputs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "multiply"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/multiply",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationMultiply"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.multiply",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/multiply"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/multiplyNoNaN": {
      "abstract": [
        {
          "text": "Calculates the element-wise product of the inputs, and returns ",
          "type": "text"
        },
        {
          "code": "0",
          "type": "codeVoice"
        },
        {
          "text": " when the result isn’t a number or infinity.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "multiplyNoNaN"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/multiplyNoNaN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationMultiplyNoNaN"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.multiplyNoNaN",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/multiplynonan"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/pow": {
      "abstract": [
        {
          "text": "Calculates the element-wise first input raised to the power of the second input.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pow"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/pow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationPow"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.pow",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/pow"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/round": {
      "abstract": [
        {
          "text": "Calculates the element-wise rounding of the inputs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "round"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/round",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationRound"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.round",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/round"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/rsqrt": {
      "abstract": [
        {
          "text": "Calculates the element-wise reciprocal of the square root of the input.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rsqrt"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/rsqrt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationRsqrt"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.rsqrt",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/rsqrt"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/sin": {
      "abstract": [
        {
          "text": "Calculates the element-wise sine of the input.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sin"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/sin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationSin"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.sin",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/sin"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/sinh": {
      "abstract": [
        {
          "text": "Calculates the element-wise hyperbolic sine of the input.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sinh"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/sinh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationSinh"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.sinh",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/sinh"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/sqrt": {
      "abstract": [
        {
          "text": "Calculates the element-wise square root of the input.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sqrt"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/sqrt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationSqrt"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.sqrt",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/sqrt"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/subtract": {
      "abstract": [
        {
          "text": "Calculates the element-wise difference between the inputs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subtract"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/subtract",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationSubtract"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.subtract",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/subtract"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/tan": {
      "abstract": [
        {
          "text": "Calculates the element-wise tangent of the input.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tan"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/tan",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationTan"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.tan",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/tan"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/tanh": {
      "abstract": [
        {
          "text": "Calculates the element-wise hyperbolic tangent of the input.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tanh"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/tanh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationTanh"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.tanh",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/tanh"
    },
    "doc://com.externally.resolved.symbol/c:@T@int32_t": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@int32_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "int32_t",
      "type": "topic",
      "url": "/documentation/kernel/int32_t"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-Arithmetic-Layers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticLayer/init(operation:)"
      ],
      "title": "Creating Arithmetic Layers"
    }
  ],
  "topicSections": [
    {
      "anchor": "Basic-Operations",
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/add",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/subtract",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/multiply",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/multiplyNoNaN",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/divide",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/divideNoNaN",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/min",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/max"
      ],
      "title": "Basic Operations"
    },
    {
      "anchor": "Rounding-Operations",
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/floor",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/round",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/ceil"
      ],
      "title": "Rounding Operations"
    },
    {
      "anchor": "Trigonometric-Operations",
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/sin",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/cos",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/tan",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/asin",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/acos",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/atan",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/sinh",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/cosh",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/tanh",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/asinh",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/acosh",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/atanh"
      ],
      "title": "Trigonometric Operations"
    },
    {
      "anchor": "Advanced-Operations",
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/sqrt",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/rsqrt",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/pow",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/exp",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/exp2",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/log",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/log2"
      ],
      "title": "Advanced Operations"
    },
    {
      "anchor": "Debugging",
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/debugDescription"
      ],
      "title": "Debugging"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MLCArithmeticOperation"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mlcompute/documentation/MLCompute"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Basic-Operations",
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/add",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/subtract",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/multiply",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/multiplyNoNaN",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/divide",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/divideNoNaN",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/min",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/max"
              ],
              "title": "Basic Operations"
            },
            {
              "anchor": "Rounding-Operations",
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/floor",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/round",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/ceil"
              ],
              "title": "Rounding Operations"
            },
            {
              "anchor": "Trigonometric-Operations",
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/sin",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/cos",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/tan",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/asin",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/acos",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/atan",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/sinh",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/cosh",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/tanh",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/asinh",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/acosh",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/atanh"
              ],
              "title": "Trigonometric Operations"
            },
            {
              "anchor": "Advanced-Operations",
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/sqrt",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/rsqrt",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/pow",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/exp",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/exp2",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/log",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/log2"
              ],
              "title": "Advanced Operations"
            },
            {
              "anchor": "Debugging",
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/MLCArithmeticOperationCount",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/debugDescription"
              ],
              "title": "Debugging"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-Arithmetic-Layers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticLayer/init(operation:)"
              ],
              "title": "Creating Arithmetic Layers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MLCArithmeticOperation"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@int32_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@int32_t",
                    "text": "int32_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "add",
          "path": "/deprecationSummary",
          "value": []
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1acosh/title",
          "value": "MLCArithmeticOperationAcosh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1acosh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationAcosh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1cosh/title",
          "value": "MLCArithmeticOperationCosh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1cosh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationCosh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1multiply/title",
          "value": "MLCArithmeticOperationMultiply"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1multiply/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationMultiply"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1ceil/title",
          "value": "MLCArithmeticOperationCeil"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1ceil/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationCeil"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1log2/title",
          "value": "MLCArithmeticOperationLog2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1log2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationLog2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1divideNoNaN/title",
          "value": "MLCArithmeticOperationDivideNoNaN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1divideNoNaN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationDivideNoNaN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1add/title",
          "value": "MLCArithmeticOperationAdd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1add/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationAdd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1tan/title",
          "value": "MLCArithmeticOperationTan"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1tan/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationTan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1exp2/title",
          "value": "MLCArithmeticOperationExp2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1exp2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationExp2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1asin/title",
          "value": "MLCArithmeticOperationAsin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1asin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationAsin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1multiplyNoNaN/title",
          "value": "MLCArithmeticOperationMultiplyNoNaN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1multiplyNoNaN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationMultiplyNoNaN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1tanh/title",
          "value": "MLCArithmeticOperationTanh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1tanh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationTanh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1atanh/title",
          "value": "MLCArithmeticOperationAtanh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1atanh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationAtanh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1floor/title",
          "value": "MLCArithmeticOperationFloor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1floor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationFloor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1acos/title",
          "value": "MLCArithmeticOperationAcos"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1acos/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationAcos"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1cos/title",
          "value": "MLCArithmeticOperationCos"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1cos/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationCos"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation/title",
          "value": "MLCArithmeticOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1sin/title",
          "value": "MLCArithmeticOperationSin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1sin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationSin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1log/title",
          "value": "MLCArithmeticOperationLog"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1log/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationLog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1sinh/title",
          "value": "MLCArithmeticOperationSinh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1sinh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationSinh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1debugDescription/title",
          "value": "MLCArithmeticOperationDebugDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1debugDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationDebugDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1exp/title",
          "value": "MLCArithmeticOperationExp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1exp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationExp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1rsqrt/title",
          "value": "MLCArithmeticOperationRsqrt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1rsqrt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationRsqrt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1sqrt/title",
          "value": "MLCArithmeticOperationSqrt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1sqrt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationSqrt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1min/title",
          "value": "MLCArithmeticOperationMin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1min/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationMin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1subtract/title",
          "value": "MLCArithmeticOperationSubtract"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1subtract/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationSubtract"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1round/title",
          "value": "MLCArithmeticOperationRound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1round/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationRound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticLayer~1init(operation:)/title",
          "value": "layerWithOperation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticLayer~1init(operation:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "layerWithOperation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1asinh/title",
          "value": "MLCArithmeticOperationAsinh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1asinh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationAsinh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1divide/title",
          "value": "MLCArithmeticOperationDivide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1divide/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationDivide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1atan/title",
          "value": "MLCArithmeticOperationAtan"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1atan/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationAtan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1max/title",
          "value": "MLCArithmeticOperationMax"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1max/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationMax"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1pow/title",
          "value": "MLCArithmeticOperationPow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1pow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationPow"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mlcompute/mlcarithmeticoperation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mlcompute/mlcarithmeticoperation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
