{
  "abstract": [
    {
      "text": "An activation type that you specify for an activation descriptor.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mlcompute/documentation/MLCompute"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MLCActivationType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MLCActivationType"
      }
    ],
    "modules": [
      {
        "name": "ML Compute"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MLCActivationType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.3",
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MLCActivationType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MLCActivationType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute": {
      "abstract": [
        {
          "text": "Accelerate training and validation of neural networks across the CPU and one or more GPUs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute",
      "kind": "symbol",
      "role": "collection",
      "title": "ML Compute",
      "type": "topic",
      "url": "/documentation/mlcompute"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationDescriptor/init(type:)": {
      "abstract": [
        {
          "text": "Creates an activation descriptor with the activation type you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCActivationType",
          "text": "MLCActivationType"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationDescriptor/init(type:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "descriptorWithType:"
        }
      ],
      "role": "symbol",
      "title": "init(type:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationdescriptor/init(type:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationDescriptor/init(type:a:)": {
      "abstract": [
        {
          "text": "Creates an activation descriptor with the activation type and parameter a that you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCActivationType",
          "text": "MLCActivationType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "a"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationDescriptor/init(type:a:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "descriptorWithType:a:"
        }
      ],
      "role": "symbol",
      "title": "init(type:a:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationdescriptor/init(type:a:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationDescriptor/init(type:a:b:)": {
      "abstract": [
        {
          "text": "Creates an activation descriptor with the activation type and parameters a and b that you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCActivationType",
          "text": "MLCActivationType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "a"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "b"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationDescriptor/init(type:a:b:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "descriptorWithType:a:b:"
        }
      ],
      "role": "symbol",
      "title": "init(type:a:b:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationdescriptor/init(type:a:b:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationDescriptor/init(type:a:b:c:)": {
      "abstract": [
        {
          "text": "Creates an activation descriptor with the activation type and parameters a, b, and c that you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCActivationType",
          "text": "MLCActivationType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "a"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "b"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "c"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationDescriptor/init(type:a:b:c:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "descriptorWithType:a:b:c:"
        }
      ],
      "role": "symbol",
      "title": "init(type:a:b:c:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationdescriptor/init(type:a:b:c:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType": {
      "abstract": [
        {
          "text": "An activation type that you specify for an activation descriptor.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCActivationType"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationType"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationType",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationtype"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/MLCActivationTypeCount": {
      "abstract": [
        {
          "text": "The count of activation types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MLCActivationTypeCount"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/MLCActivationTypeCount",
      "kind": "symbol",
      "role": "symbol",
      "title": "MLCActivationTypeCount",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationtype/mlcactivationtypecount"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/absolute": {
      "abstract": [
        {
          "text": "An activation type that implements the absolute activation function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "absolute"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/absolute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationTypeAbsolute"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationType.absolute",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationtype/absolute"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/celu": {
      "abstract": [
        {
          "text": "An activation type that implements the CELU activation function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "celu"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/celu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationTypeCELU"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationType.celu",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationtype/celu"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/clamp": {
      "abstract": [
        {
          "text": "An activation type that implements the clamp activation function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clamp"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/clamp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationTypeClamp"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationType.clamp",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationtype/clamp"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/debugDescription": {
      "abstract": [
        {
          "text": "A textual description of the activation type, suitable for debugging.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "debugDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/debugDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationTypeDebugDescription"
        }
      ],
      "role": "symbol",
      "title": "debugDescription",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationtype/debugdescription"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/elu": {
      "abstract": [
        {
          "text": "An activation type that implements the exponential linear unit activation function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "elu"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/elu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationTypeELU"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationType.elu",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationtype/elu"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/gelu": {
      "abstract": [
        {
          "text": "An activation type that implements the gaussian error linear unit activation function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gelu"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/gelu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationTypeGELU"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationType.gelu",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationtype/gelu"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/hardShrink": {
      "abstract": [
        {
          "text": "An activation type that implements the hard shrink activation function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hardShrink"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/hardShrink",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationTypeHardShrink"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationType.hardShrink",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationtype/hardshrink"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/hardSigmoid": {
      "abstract": [
        {
          "text": "An activation type that implements the hard sigmoid activation function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hardSigmoid"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/hardSigmoid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationTypeHardSigmoid"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationType.hardSigmoid",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationtype/hardsigmoid"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/hardSwish": {
      "abstract": [
        {
          "text": "An activation type that implements the hard swish activation function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hardSwish"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/hardSwish",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationTypeHardSwish"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationType.hardSwish",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationtype/hardswish"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/init(rawValue:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationtype/init(rawvalue:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/linear": {
      "abstract": [
        {
          "text": "An activation type that implements the linear activation function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "linear"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/linear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationTypeLinear"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationType.linear",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationtype/linear"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/logSigmoid": {
      "abstract": [
        {
          "text": "An activation type that implements the log sigmoid activation function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "logSigmoid"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/logSigmoid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationTypeLogSigmoid"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationType.logSigmoid",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationtype/logsigmoid"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/none": {
      "abstract": [
        {
          "text": "An activation type that implements the identity function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationTypeNone"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationType.none",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationtype/none"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/relu": {
      "abstract": [
        {
          "text": "An activation type that implements the rectified linear unit activation function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "relu"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/relu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationTypeReLU"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationType.relu",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationtype/relu"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/relun": {
      "abstract": [
        {
          "text": "An activation type that implements the ReLUN activation function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "relun"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/relun",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationTypeReLUN"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationType.relun",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationtype/relun"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/selu": {
      "abstract": [
        {
          "text": "An activation type that implements the scaled exponential linear unit activation function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selu"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/selu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationTypeSELU"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationType.selu",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationtype/selu"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/sigmoid": {
      "abstract": [
        {
          "text": "An activation type that implements the sigmoid activation function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sigmoid"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/sigmoid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationTypeSigmoid"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationType.sigmoid",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationtype/sigmoid"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/softPlus": {
      "abstract": [
        {
          "text": "An activation type that implements the soft plus activation function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "softPlus"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/softPlus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationTypeSoftPlus"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationType.softPlus",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationtype/softplus"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/softShrink": {
      "abstract": [
        {
          "text": "An activation type that implements the soft shrink activation function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "softShrink"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/softShrink",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationTypeSoftShrink"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationType.softShrink",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationtype/softshrink"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/softSign": {
      "abstract": [
        {
          "text": "An activation type that implements the parametric soft sign activation function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "softSign"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/softSign",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationTypeSoftSign"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationType.softSign",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationtype/softsign"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/tanh": {
      "abstract": [
        {
          "text": "An activation type that implements the hyperbolic tangent activation function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tanh"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/tanh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationTypeTanh"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationType.tanh",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationtype/tanh"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/tanhShrink": {
      "abstract": [
        {
          "text": "An activation type that implements the hyperbolic tangent shrink activation function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tanhShrink"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/tanhShrink",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationTypeTanhShrink"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationType.tanhShrink",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationtype/tanhshrink"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/threshold": {
      "abstract": [
        {
          "text": "An activation type that implements the threshold activation function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "threshold"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/threshold",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationTypeThreshold"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationType.threshold",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationtype/threshold"
    },
    "doc://com.externally.resolved.symbol/c:@T@int32_t": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@int32_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "int32_t",
      "type": "topic",
      "url": "/documentation/kernel/int32_t"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-Activation-Descriptors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationDescriptor/init(type:)",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationDescriptor/init(type:a:)",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationDescriptor/init(type:a:b:)",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationDescriptor/init(type:a:b:c:)"
      ],
      "title": "Creating Activation Descriptors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/absolute",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/celu",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/clamp",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/elu",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/gelu",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/hardShrink",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/hardSigmoid",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/hardSwish",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/linear",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/logSigmoid",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/none",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/relu",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/relun",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/selu",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/sigmoid",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/softPlus",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/softShrink",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/softSign",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/tanh",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/tanhShrink",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/threshold",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/debugDescription"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MLCActivationType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mlcompute/documentation/MLCompute"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/absolute",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/celu",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/clamp",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/elu",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/gelu",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/hardShrink",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/hardSigmoid",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/hardSwish",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/linear",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/logSigmoid",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/none",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/relu",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/relun",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/selu",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/sigmoid",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/softPlus",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/softShrink",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/softSign",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/tanh",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/tanhShrink",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/threshold",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/MLCActivationTypeCount",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/debugDescription"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-Activation-Descriptors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationDescriptor/init(type:)",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationDescriptor/init(type:a:)",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationDescriptor/init(type:a:b:)",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationDescriptor/init(type:a:b:c:)"
              ],
              "title": "Creating Activation Descriptors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MLCActivationType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@int32_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@int32_t",
                    "text": "int32_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "add",
          "path": "/deprecationSummary",
          "value": []
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1softPlus/title",
          "value": "MLCActivationTypeSoftPlus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1softPlus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationTypeSoftPlus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1selu/title",
          "value": "MLCActivationTypeSELU"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1selu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationTypeSELU"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1debugDescription/title",
          "value": "MLCActivationTypeDebugDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1debugDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationTypeDebugDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1celu/title",
          "value": "MLCActivationTypeCELU"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1celu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationTypeCELU"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1absolute/title",
          "value": "MLCActivationTypeAbsolute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1absolute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationTypeAbsolute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1clamp/title",
          "value": "MLCActivationTypeClamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1clamp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationTypeClamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1threshold/title",
          "value": "MLCActivationTypeThreshold"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1threshold/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationTypeThreshold"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1softSign/title",
          "value": "MLCActivationTypeSoftSign"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1softSign/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationTypeSoftSign"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1linear/title",
          "value": "MLCActivationTypeLinear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1linear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationTypeLinear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1elu/title",
          "value": "MLCActivationTypeELU"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1elu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationTypeELU"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType/title",
          "value": "MLCActivationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1relu/title",
          "value": "MLCActivationTypeReLU"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1relu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationTypeReLU"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1hardSwish/title",
          "value": "MLCActivationTypeHardSwish"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1hardSwish/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationTypeHardSwish"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1logSigmoid/title",
          "value": "MLCActivationTypeLogSigmoid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1logSigmoid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationTypeLogSigmoid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1hardShrink/title",
          "value": "MLCActivationTypeHardShrink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1hardShrink/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationTypeHardShrink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1softShrink/title",
          "value": "MLCActivationTypeSoftShrink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1softShrink/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationTypeSoftShrink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1gelu/title",
          "value": "MLCActivationTypeGELU"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1gelu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationTypeGELU"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationDescriptor~1init(type:a:b:c:)/title",
          "value": "descriptorWithType:a:b:c:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationDescriptor~1init(type:a:b:c:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "descriptorWithType:a:b:c:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1hardSigmoid/title",
          "value": "MLCActivationTypeHardSigmoid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1hardSigmoid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationTypeHardSigmoid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1relun/title",
          "value": "MLCActivationTypeReLUN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1relun/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationTypeReLUN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationDescriptor~1init(type:a:b:)/title",
          "value": "descriptorWithType:a:b:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationDescriptor~1init(type:a:b:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "descriptorWithType:a:b:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1none/title",
          "value": "MLCActivationTypeNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationTypeNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationDescriptor~1init(type:)/title",
          "value": "descriptorWithType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationDescriptor~1init(type:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "descriptorWithType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationDescriptor~1init(type:a:)/title",
          "value": "descriptorWithType:a:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationDescriptor~1init(type:a:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "descriptorWithType:a:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1tanh/title",
          "value": "MLCActivationTypeTanh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1tanh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationTypeTanh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1sigmoid/title",
          "value": "MLCActivationTypeSigmoid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1sigmoid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationTypeSigmoid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1tanhShrink/title",
          "value": "MLCActivationTypeTanhShrink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1tanhShrink/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationTypeTanhShrink"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mlcompute/mlcactivationtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mlcompute/mlcactivationtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
