{
  "abstract": [
    {
      "text": "A comparison operation.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mlcompute/documentation/MLCompute"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MLCComparisonOperation",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MLCComparisonOperation"
      }
    ],
    "modules": [
      {
        "name": "ML Compute"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MLCComparisonOperation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.5",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.5",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.5",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.3",
        "introducedAt": "11.3",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.5",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MLCComparisonOperation"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MLCComparisonOperation"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute": {
      "abstract": [
        {
          "text": "Accelerate training and validation of neural networks across the CPU and one or more GPUs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute",
      "kind": "symbol",
      "role": "collection",
      "title": "ML Compute",
      "type": "topic",
      "url": "/documentation/mlcompute"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonLayer/init(operation:)": {
      "abstract": [
        {
          "text": "Creates a comparison layer with the operation you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "operation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCComparisonOperation",
          "text": "MLCComparisonOperation"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonLayer/init(operation:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layerWithOperation:"
        }
      ],
      "role": "symbol",
      "title": "init(operation:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlccomparisonlayer/init(operation:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation": {
      "abstract": [
        {
          "text": "A comparison operation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCComparisonOperation"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCComparisonOperation"
        }
      ],
      "role": "symbol",
      "title": "MLCComparisonOperation",
      "type": "topic",
      "url": "/documentation/mlcompute/mlccomparisonoperation"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/MLCComparisonOperationCount": {
      "abstract": [
        {
          "text": "A number that represents the operation count.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MLCComparisonOperationCount"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/MLCComparisonOperationCount",
      "kind": "symbol",
      "role": "symbol",
      "title": "MLCComparisonOperationCount",
      "type": "topic",
      "url": "/documentation/mlcompute/mlccomparisonoperation/mlccomparisonoperationcount"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/debugDescription": {
      "abstract": [
        {
          "text": "A textual description of the comparison operation, suitable for debugging.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "debugDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/debugDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCComparisonOperationDebugDescription"
        }
      ],
      "role": "symbol",
      "title": "debugDescription",
      "type": "topic",
      "url": "/documentation/mlcompute/mlccomparisonoperation/debugdescription"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/equal": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "equal"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/equal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCComparisonOperationEqual"
        }
      ],
      "role": "symbol",
      "title": "MLCComparisonOperation.equal",
      "type": "topic",
      "url": "/documentation/mlcompute/mlccomparisonoperation/equal"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/greater": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "greater"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/greater",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCComparisonOperationGreater"
        }
      ],
      "role": "symbol",
      "title": "MLCComparisonOperation.greater",
      "type": "topic",
      "url": "/documentation/mlcompute/mlccomparisonoperation/greater"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/greaterOrEqual": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "greaterOrEqual"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/greaterOrEqual",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCComparisonOperationGreaterOrEqual"
        }
      ],
      "role": "symbol",
      "title": "MLCComparisonOperation.greaterOrEqual",
      "type": "topic",
      "url": "/documentation/mlcompute/mlccomparisonoperation/greaterorequal"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/init(rawValue:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlccomparisonoperation/init(rawvalue:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/less": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "less"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/less",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCComparisonOperationLess"
        }
      ],
      "role": "symbol",
      "title": "MLCComparisonOperation.less",
      "type": "topic",
      "url": "/documentation/mlcompute/mlccomparisonoperation/less"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/lessOrEqual": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lessOrEqual"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/lessOrEqual",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCComparisonOperationLessOrEqual"
        }
      ],
      "role": "symbol",
      "title": "MLCComparisonOperation.lessOrEqual",
      "type": "topic",
      "url": "/documentation/mlcompute/mlccomparisonoperation/lessorequal"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/logicalAND": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "logicalAND"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/logicalAND",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCComparisonOperationLogicalAND"
        }
      ],
      "role": "symbol",
      "title": "MLCComparisonOperation.logicalAND",
      "type": "topic",
      "url": "/documentation/mlcompute/mlccomparisonoperation/logicaland"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/logicalNAND": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "logicalNAND"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/logicalNAND",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCComparisonOperationLogicalNAND"
        }
      ],
      "role": "symbol",
      "title": "MLCComparisonOperation.logicalNAND",
      "type": "topic",
      "url": "/documentation/mlcompute/mlccomparisonoperation/logicalnand"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/logicalNOR": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "logicalNOR"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/logicalNOR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCComparisonOperationLogicalNOR"
        }
      ],
      "role": "symbol",
      "title": "MLCComparisonOperation.logicalNOR",
      "type": "topic",
      "url": "/documentation/mlcompute/mlccomparisonoperation/logicalnor"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/logicalNOT": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "logicalNOT"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/logicalNOT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCComparisonOperationLogicalNOT"
        }
      ],
      "role": "symbol",
      "title": "MLCComparisonOperation.logicalNOT",
      "type": "topic",
      "url": "/documentation/mlcompute/mlccomparisonoperation/logicalnot"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/logicalOR": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "logicalOR"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/logicalOR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCComparisonOperationLogicalOR"
        }
      ],
      "role": "symbol",
      "title": "MLCComparisonOperation.logicalOR",
      "type": "topic",
      "url": "/documentation/mlcompute/mlccomparisonoperation/logicalor"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/logicalXOR": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "logicalXOR"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/logicalXOR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCComparisonOperationLogicalXOR"
        }
      ],
      "role": "symbol",
      "title": "MLCComparisonOperation.logicalXOR",
      "type": "topic",
      "url": "/documentation/mlcompute/mlccomparisonoperation/logicalxor"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/notEqual": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notEqual"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/notEqual",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCComparisonOperationNotEqual"
        }
      ],
      "role": "symbol",
      "title": "MLCComparisonOperation.notEqual",
      "type": "topic",
      "url": "/documentation/mlcompute/mlccomparisonoperation/notequal"
    },
    "doc://com.externally.resolved.symbol/c:@T@int32_t": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@int32_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "int32_t",
      "type": "topic",
      "url": "/documentation/kernel/int32_t"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-Comparison-Layers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonLayer/init(operation:)"
      ],
      "title": "Creating Comparison Layers"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/equal",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/greater",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/greaterOrEqual",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/less",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/lessOrEqual",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/logicalAND",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/logicalNAND",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/logicalNOR",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/logicalNOT",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/logicalOR",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/logicalXOR",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/notEqual",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/debugDescription"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MLCComparisonOperation"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCComparisonOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCComparisonOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mlcompute/documentation/MLCompute"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/equal",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/greater",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/greaterOrEqual",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/less",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/lessOrEqual",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/logicalAND",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/logicalNAND",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/logicalNOR",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/logicalNOT",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/logicalOR",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/logicalXOR",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/notEqual",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/debugDescription",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonOperation/MLCComparisonOperationCount"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-Comparison-Layers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonLayer/init(operation:)"
              ],
              "title": "Creating Comparison Layers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MLCComparisonOperation"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@int32_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@int32_t",
                    "text": "int32_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "add",
          "path": "/deprecationSummary",
          "value": []
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCComparisonOperation~1logicalNOT/title",
          "value": "MLCComparisonOperationLogicalNOT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCComparisonOperation~1logicalNOT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCComparisonOperationLogicalNOT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCComparisonOperation~1debugDescription/title",
          "value": "MLCComparisonOperationDebugDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCComparisonOperation~1debugDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCComparisonOperationDebugDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCComparisonOperation~1logicalNAND/title",
          "value": "MLCComparisonOperationLogicalNAND"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCComparisonOperation~1logicalNAND/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCComparisonOperationLogicalNAND"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCComparisonOperation~1equal/title",
          "value": "MLCComparisonOperationEqual"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCComparisonOperation~1equal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCComparisonOperationEqual"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCComparisonOperation~1notEqual/title",
          "value": "MLCComparisonOperationNotEqual"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCComparisonOperation~1notEqual/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCComparisonOperationNotEqual"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCComparisonOperation~1greaterOrEqual/title",
          "value": "MLCComparisonOperationGreaterOrEqual"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCComparisonOperation~1greaterOrEqual/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCComparisonOperationGreaterOrEqual"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCComparisonOperation~1logicalNOR/title",
          "value": "MLCComparisonOperationLogicalNOR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCComparisonOperation~1logicalNOR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCComparisonOperationLogicalNOR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCComparisonOperation~1logicalAND/title",
          "value": "MLCComparisonOperationLogicalAND"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCComparisonOperation~1logicalAND/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCComparisonOperationLogicalAND"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCComparisonOperation/title",
          "value": "MLCComparisonOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCComparisonOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCComparisonOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCComparisonOperation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCComparisonOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCComparisonOperation~1logicalOR/title",
          "value": "MLCComparisonOperationLogicalOR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCComparisonOperation~1logicalOR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCComparisonOperationLogicalOR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCComparisonOperation~1logicalXOR/title",
          "value": "MLCComparisonOperationLogicalXOR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCComparisonOperation~1logicalXOR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCComparisonOperationLogicalXOR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCComparisonOperation~1lessOrEqual/title",
          "value": "MLCComparisonOperationLessOrEqual"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCComparisonOperation~1lessOrEqual/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCComparisonOperationLessOrEqual"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCComparisonOperation~1less/title",
          "value": "MLCComparisonOperationLess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCComparisonOperation~1less/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCComparisonOperationLess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCComparisonOperation~1greater/title",
          "value": "MLCComparisonOperationGreater"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCComparisonOperation~1greater/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCComparisonOperationGreater"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCComparisonLayer~1init(operation:)/title",
          "value": "layerWithOperation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCComparisonLayer~1init(operation:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "layerWithOperation:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mlcompute/mlccomparisonoperation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mlcompute/mlccomparisonoperation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
