{
  "abstract": [
    {
      "text": "A clipping type the system applies to a gradient.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mlcompute/documentation/MLCompute"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mlcompute/documentation/MLCompute/MLCGradientClippingType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MLCGradientClippingType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MLCGradientClippingType"
      }
    ],
    "modules": [
      {
        "name": "ML Compute"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MLCGradientClippingType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.3",
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MLCGradientClippingType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MLCGradientClippingType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute": {
      "abstract": [
        {
          "text": "Accelerate training and validation of neural networks across the CPU and one or more GPUs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute",
      "kind": "symbol",
      "role": "collection",
      "title": "ML Compute",
      "type": "topic",
      "url": "/documentation/mlcompute"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCGradientClippingType": {
      "abstract": [
        {
          "text": "A clipping type the system applies to a gradient.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCGradientClippingType"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCGradientClippingType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCGradientClippingType"
        }
      ],
      "role": "symbol",
      "title": "MLCGradientClippingType",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcgradientclippingtype"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCGradientClippingType/byGlobalNorm": {
      "abstract": [
        {
          "text": "An option that clips by global norm.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "byGlobalNorm"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCGradientClippingType/byGlobalNorm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCGradientClippingTypeByGlobalNorm"
        }
      ],
      "role": "symbol",
      "title": "MLCGradientClippingType.byGlobalNorm",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcgradientclippingtype/byglobalnorm"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCGradientClippingType/byNorm": {
      "abstract": [
        {
          "text": "An option that clips by norm.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "byNorm"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCGradientClippingType/byNorm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCGradientClippingTypeByNorm"
        }
      ],
      "role": "symbol",
      "title": "MLCGradientClippingType.byNorm",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcgradientclippingtype/bynorm"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCGradientClippingType/byValue": {
      "abstract": [
        {
          "text": "An option that clips by value.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "byValue"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCGradientClippingType/byValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCGradientClippingTypeByValue"
        }
      ],
      "role": "symbol",
      "title": "MLCGradientClippingType.byValue",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcgradientclippingtype/byvalue"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCGradientClippingType/debugDescription": {
      "abstract": [
        {
          "text": "A textual description of the gradient clipping type, suitable for debugging.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "debugDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCGradientClippingType/debugDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCGradientClippingTypeDebugDescription"
        }
      ],
      "role": "symbol",
      "title": "debugDescription",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcgradientclippingtype/debugdescription"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCGradientClippingType/init(rawValue:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCGradientClippingType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcgradientclippingtype/init(rawvalue:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/appliesGradientClipping": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether you apply gradient clipping.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appliesGradientClipping"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/appliesGradientClipping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "appliesGradientClipping"
        }
      ],
      "role": "symbol",
      "title": "appliesGradientClipping",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcoptimizer/appliesgradientclipping"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/customGlobalNorm": {
      "abstract": [
        {
          "text": "A custom norm the system uses in place of the global norm.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "customGlobalNorm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/customGlobalNorm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "customGlobalNorm"
        }
      ],
      "role": "symbol",
      "title": "customGlobalNorm",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcoptimizer/customglobalnorm"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/gradientClipMax": {
      "abstract": [
        {
          "text": "The maximum gradient value before the optimizer rescales the gradient, if you enable gradient clipping.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gradientClipMax"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/gradientClipMax",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gradientClipMax"
        }
      ],
      "role": "symbol",
      "title": "gradientClipMax",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcoptimizer/gradientclipmax"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/gradientClipMin": {
      "abstract": [
        {
          "text": "The minimum gradient value before the optimizer rescales the gradient, if you enable gradient clipping.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gradientClipMin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/gradientClipMin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gradientClipMin"
        }
      ],
      "role": "symbol",
      "title": "gradientClipMin",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcoptimizer/gradientclipmin"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/gradientClippingType": {
      "abstract": [
        {
          "text": "The type of clipping the system applies to the gradient.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gradientClippingType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCGradientClippingType",
          "text": "MLCGradientClippingType"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/gradientClippingType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gradientClippingType"
        }
      ],
      "role": "symbol",
      "title": "gradientClippingType",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcoptimizer/gradientclippingtype"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/gradientRescale": {
      "abstract": [
        {
          "text": "The rescale value the optimizer applies to gradients during updates.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gradientRescale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/gradientRescale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gradientRescale"
        }
      ],
      "role": "symbol",
      "title": "gradientRescale",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcoptimizer/gradientrescale"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/learningRate": {
      "abstract": [
        {
          "text": "The learning rate.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "learningRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/learningRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "learningRate"
        }
      ],
      "role": "symbol",
      "title": "learningRate",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcoptimizer/learningrate"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/maximumClippingNorm": {
      "abstract": [
        {
          "text": "The maximum clipping value.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumClippingNorm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/maximumClippingNorm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maximumClippingNorm"
        }
      ],
      "role": "symbol",
      "title": "maximumClippingNorm",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcoptimizer/maximumclippingnorm"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/regularizationScale": {
      "abstract": [
        {
          "text": "The regularization scale.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "regularizationScale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/regularizationScale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "regularizationScale"
        }
      ],
      "role": "symbol",
      "title": "regularizationScale",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcoptimizer/regularizationscale"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/regularizationType": {
      "abstract": [
        {
          "text": "The regularization type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "regularizationType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCRegularizationType",
          "text": "MLCRegularizationType"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/regularizationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "regularizationType"
        }
      ],
      "role": "symbol",
      "title": "regularizationType",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcoptimizer/regularizationtype"
    },
    "doc://com.externally.resolved.symbol/c:@T@int32_t": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@int32_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "int32_t",
      "type": "topic",
      "url": "/documentation/kernel/int32_t"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-an-Optimizer",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/learningRate",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/gradientRescale",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/appliesGradientClipping",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/gradientClipMax",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/gradientClipMin",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/regularizationScale",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/regularizationType",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/gradientClippingType",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/maximumClippingNorm",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/customGlobalNorm"
      ],
      "title": "Inspecting an Optimizer"
    }
  ],
  "topicSections": [
    {
      "anchor": "Gradient-Clipping-Types",
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCGradientClippingType/byValue",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCGradientClippingType/byNorm",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCGradientClippingType/byGlobalNorm",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCGradientClippingType/debugDescription"
      ],
      "title": "Gradient Clipping Types"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCGradientClippingType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MLCGradientClippingType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCGradientClippingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCGradientClippingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mlcompute/documentation/MLCompute"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Gradient-Clipping-Types",
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCGradientClippingType/byValue",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCGradientClippingType/byNorm",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCGradientClippingType/byGlobalNorm",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCGradientClippingType/debugDescription"
              ],
              "title": "Gradient Clipping Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Inspecting-an-Optimizer",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/learningRate",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/gradientRescale",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/appliesGradientClipping",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/gradientClipMax",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/gradientClipMin",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/regularizationScale",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/regularizationType",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/gradientClippingType",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/maximumClippingNorm",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/customGlobalNorm"
              ],
              "title": "Inspecting an Optimizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MLCGradientClippingType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@int32_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@int32_t",
                    "text": "int32_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "add",
          "path": "/deprecationSummary",
          "value": []
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizer~1gradientClipMin/title",
          "value": "gradientClipMin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizer~1gradientClipMin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gradientClipMin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizer~1gradientRescale/title",
          "value": "gradientRescale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizer~1gradientRescale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gradientRescale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCGradientClippingType/title",
          "value": "MLCGradientClippingType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCGradientClippingType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCGradientClippingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCGradientClippingType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCGradientClippingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizer~1regularizationScale/title",
          "value": "regularizationScale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizer~1regularizationScale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "regularizationScale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCGradientClippingType~1byGlobalNorm/title",
          "value": "MLCGradientClippingTypeByGlobalNorm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCGradientClippingType~1byGlobalNorm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCGradientClippingTypeByGlobalNorm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizer~1regularizationType/title",
          "value": "regularizationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizer~1regularizationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "regularizationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCGradientClippingType~1byValue/title",
          "value": "MLCGradientClippingTypeByValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCGradientClippingType~1byValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCGradientClippingTypeByValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCGradientClippingType~1byNorm/title",
          "value": "MLCGradientClippingTypeByNorm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCGradientClippingType~1byNorm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCGradientClippingTypeByNorm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCGradientClippingType~1debugDescription/title",
          "value": "MLCGradientClippingTypeDebugDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCGradientClippingType~1debugDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCGradientClippingTypeDebugDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizer~1gradientClipMax/title",
          "value": "gradientClipMax"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizer~1gradientClipMax/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gradientClipMax"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizer~1appliesGradientClipping/title",
          "value": "appliesGradientClipping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizer~1appliesGradientClipping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "appliesGradientClipping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizer~1customGlobalNorm/title",
          "value": "customGlobalNorm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizer~1customGlobalNorm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "customGlobalNorm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizer~1gradientClippingType/title",
          "value": "gradientClippingType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizer~1gradientClippingType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gradientClippingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizer~1learningRate/title",
          "value": "learningRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizer~1learningRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "learningRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizer~1maximumClippingNorm/title",
          "value": "maximumClippingNorm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizer~1maximumClippingNorm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maximumClippingNorm"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mlcompute/mlcgradientclippingtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mlcompute/mlcgradientclippingtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
