{
  "abstract": [
    {
      "text": "A layer that estimates the inaccuracies of the model to reduce the loss on the next evaluation.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mlcompute/documentation/MLCompute"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MLCLossLayer",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MLCLossLayer"
      }
    ],
    "modules": [
      {
        "name": "ML Compute"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MLCLossLayer"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.3",
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MLCLossLayer"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MLCLossLayer"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute": {
      "abstract": [
        {
          "text": "Accelerate training and validation of neural networks across the CPU and one or more GPUs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute",
      "kind": "symbol",
      "role": "collection",
      "title": "ML Compute",
      "type": "topic",
      "url": "/documentation/mlcompute"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayer": {
      "abstract": [
        {
          "text": "The base class for all framework layers.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossDescriptor": {
      "abstract": [
        {
          "text": "A configuration object you use to create a loss layer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCLossDescriptor"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCLossDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MLCLossDescriptor",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclossdescriptor"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer": {
      "abstract": [
        {
          "text": "A layer that estimates the inaccuracies of the model to reduce the loss on the next evaluation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCLossLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCLossLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCLossLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclosslayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/categoricalCrossEntropy(reductionType:labelSmoothing:classCount:weight:)": {
      "abstract": [
        {
          "text": "Creates a categorical cross entropy loss layer with the reduction type, label smoothing, number of classes, and weight you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "categoricalCrossEntropy"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "reductionType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCReductionType",
          "text": "MLCReductionType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "labelSmoothing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "classCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "weight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/categoricalCrossEntropy(reductionType:labelSmoothing:classCount:weight:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "categoricalCrossEntropyLossWithReductionType:labelSmoothing:classCount:weight:"
        }
      ],
      "role": "symbol",
      "title": "categoricalCrossEntropy(reductionType:labelSmoothing:classCount:weight:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclosslayer/categoricalcrossentropy(reductiontype:labelsmoothing:classcount:weight:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/categoricalCrossEntropy(reductionType:labelSmoothing:classCount:weights:)": {
      "abstract": [
        {
          "text": "Creates a categorical cross entropy loss layer with the reduction type, label smoothing, number of classes, and weights you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "categoricalCrossEntropy"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "reductionType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCReductionType",
          "text": "MLCReductionType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "labelSmoothing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "classCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "weights"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCTensor",
          "text": "MLCTensor"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/categoricalCrossEntropy(reductionType:labelSmoothing:classCount:weights:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "categoricalCrossEntropyLossWithReductionType:labelSmoothing:classCount:weights:"
        }
      ],
      "role": "symbol",
      "title": "categoricalCrossEntropy(reductionType:labelSmoothing:classCount:weights:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclosslayer/categoricalcrossentropy(reductiontype:labelsmoothing:classcount:weights:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/cosineDistance(reductionType:weight:)": {
      "abstract": [
        {
          "text": "Creates a cosine distance loss layer with the reduction type and weight you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cosineDistance"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "reductionType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCReductionType",
          "text": "MLCReductionType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "weight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/cosineDistance(reductionType:weight:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cosineDistanceLossWithReductionType:weight:"
        }
      ],
      "role": "symbol",
      "title": "cosineDistance(reductionType:weight:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclosslayer/cosinedistance(reductiontype:weight:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/cosineDistance(reductionType:weights:)": {
      "abstract": [
        {
          "text": "Creates a cosine distance loss layer with the reduction type and weights you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cosineDistance"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "reductionType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCReductionType",
          "text": "MLCReductionType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "weights"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCTensor",
          "text": "MLCTensor"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/cosineDistance(reductionType:weights:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cosineDistanceLossWithReductionType:weights:"
        }
      ],
      "role": "symbol",
      "title": "cosineDistance(reductionType:weights:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclosslayer/cosinedistance(reductiontype:weights:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/descriptor": {
      "abstract": [
        {
          "text": "The configuration object you use to create the loss layer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "descriptor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCLossDescriptor",
          "text": "MLCLossDescriptor"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/descriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "descriptor"
        }
      ],
      "role": "symbol",
      "title": "descriptor",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclosslayer/descriptor"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/hingeLoss(reductionType:weight:)": {
      "abstract": [
        {
          "text": "Creates a hinge loss layer with the reduction type and weight you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hingeLoss"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "reductionType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCReductionType",
          "text": "MLCReductionType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "weight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/hingeLoss(reductionType:weight:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hingeLossWithReductionType:weight:"
        }
      ],
      "role": "symbol",
      "title": "hingeLoss(reductionType:weight:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclosslayer/hingeloss(reductiontype:weight:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/hingeLoss(reductionType:weights:)": {
      "abstract": [
        {
          "text": "Creates a hinge loss layer with the reduction type and weights you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hingeLoss"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "reductionType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCReductionType",
          "text": "MLCReductionType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "weights"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCTensor",
          "text": "MLCTensor"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/hingeLoss(reductionType:weights:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hingeLossWithReductionType:weights:"
        }
      ],
      "role": "symbol",
      "title": "hingeLoss(reductionType:weights:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclosslayer/hingeloss(reductiontype:weights:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/huberLoss(reductionType:delta:weight:)": {
      "abstract": [
        {
          "text": "Creates a huber loss layer with the reduction type, delta, and weight you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "huberLoss"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "reductionType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCReductionType",
          "text": "MLCReductionType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "delta"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "weight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/huberLoss(reductionType:delta:weight:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "huberLossWithReductionType:delta:weight:"
        }
      ],
      "role": "symbol",
      "title": "huberLoss(reductionType:delta:weight:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclosslayer/huberloss(reductiontype:delta:weight:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/huberLoss(reductionType:delta:weights:)": {
      "abstract": [
        {
          "text": "Creates a huber loss layer with the reduction type, delta, and weights you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "huberLoss"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "reductionType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCReductionType",
          "text": "MLCReductionType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "delta"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "weights"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCTensor",
          "text": "MLCTensor"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/huberLoss(reductionType:delta:weights:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "huberLossWithReductionType:delta:weights:"
        }
      ],
      "role": "symbol",
      "title": "huberLoss(reductionType:delta:weights:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclosslayer/huberloss(reductiontype:delta:weights:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/init(descriptor:)": {
      "abstract": [
        {
          "text": "Creates a loss layer with the descriptor you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "descriptor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCLossDescriptor",
          "text": "MLCLossDescriptor"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/init(descriptor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layerWithDescriptor:"
        }
      ],
      "role": "symbol",
      "title": "init(descriptor:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclosslayer/init(descriptor:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/init(descriptor:weights:)": {
      "abstract": [
        {
          "text": "Creates a loss layer with the descriptor and weights you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "descriptor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCLossDescriptor",
          "text": "MLCLossDescriptor"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "weights"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCTensor",
          "text": "MLCTensor"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/init(descriptor:weights:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layerWithDescriptor:weights:"
        }
      ],
      "role": "symbol",
      "title": "init(descriptor:weights:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclosslayer/init(descriptor:weights:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/log(reductionType:epsilon:weight:)": {
      "abstract": [
        {
          "text": "Creates a log loss layer with the reduction type, epsilon, and weight you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "log"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "reductionType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCReductionType",
          "text": "MLCReductionType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "epsilon"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "weight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/log(reductionType:epsilon:weight:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "logLossWithReductionType:epsilon:weight:"
        }
      ],
      "role": "symbol",
      "title": "log(reductionType:epsilon:weight:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclosslayer/log(reductiontype:epsilon:weight:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/log(reductionType:epsilon:weights:)": {
      "abstract": [
        {
          "text": "Creates a log loss layer with the reduction type, epsilon, and weights you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "log"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "reductionType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCReductionType",
          "text": "MLCReductionType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "epsilon"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "weights"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCTensor",
          "text": "MLCTensor"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/log(reductionType:epsilon:weights:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "logLossWithReductionType:epsilon:weights:"
        }
      ],
      "role": "symbol",
      "title": "log(reductionType:epsilon:weights:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclosslayer/log(reductiontype:epsilon:weights:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/meanAbsoluteError(reductionType:weight:)": {
      "abstract": [
        {
          "text": "Creates a mean absolute loss layer with the reduction type and weight.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "meanAbsoluteError"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "reductionType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCReductionType",
          "text": "MLCReductionType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "weight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/meanAbsoluteError(reductionType:weight:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "meanAbsoluteErrorLossWithReductionType:weight:"
        }
      ],
      "role": "symbol",
      "title": "meanAbsoluteError(reductionType:weight:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclosslayer/meanabsoluteerror(reductiontype:weight:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/meanAbsoluteError(reductionType:weights:)": {
      "abstract": [
        {
          "text": "Creates a mean absolute loss layer with the reduction type and weights you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "meanAbsoluteError"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "reductionType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCReductionType",
          "text": "MLCReductionType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "weights"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCTensor",
          "text": "MLCTensor"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/meanAbsoluteError(reductionType:weights:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "meanAbsoluteErrorLossWithReductionType:weights:"
        }
      ],
      "role": "symbol",
      "title": "meanAbsoluteError(reductionType:weights:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclosslayer/meanabsoluteerror(reductiontype:weights:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/meanSquaredError(reductionType:weight:)": {
      "abstract": [
        {
          "text": "Creates a mean squared loss layer with the reduction type and weight you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "meanSquaredError"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "reductionType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCReductionType",
          "text": "MLCReductionType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "weight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/meanSquaredError(reductionType:weight:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "meanSquaredErrorLossWithReductionType:weight:"
        }
      ],
      "role": "symbol",
      "title": "meanSquaredError(reductionType:weight:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclosslayer/meansquarederror(reductiontype:weight:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/meanSquaredError(reductionType:weights:)": {
      "abstract": [
        {
          "text": "Creates a mean squared loss layer with the reduction type and weights you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "meanSquaredError"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "reductionType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCReductionType",
          "text": "MLCReductionType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "weights"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCTensor",
          "text": "MLCTensor"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/meanSquaredError(reductionType:weights:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "meanSquaredErrorLossWithReductionType:weights:"
        }
      ],
      "role": "symbol",
      "title": "meanSquaredError(reductionType:weights:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclosslayer/meansquarederror(reductiontype:weights:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/sigmoidCrossEntropy(reductionType:labelSmoothing:weight:)": {
      "abstract": [
        {
          "text": "Creates a sigmoid cross entropy loss layer with the reduction type, label smoothing, and weight you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sigmoidCrossEntropy"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "reductionType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCReductionType",
          "text": "MLCReductionType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "labelSmoothing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "weight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/sigmoidCrossEntropy(reductionType:labelSmoothing:weight:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sigmoidCrossEntropyLossWithReductionType:labelSmoothing:weight:"
        }
      ],
      "role": "symbol",
      "title": "sigmoidCrossEntropy(reductionType:labelSmoothing:weight:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclosslayer/sigmoidcrossentropy(reductiontype:labelsmoothing:weight:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/sigmoidCrossEntropy(reductionType:labelSmoothing:weights:)": {
      "abstract": [
        {
          "text": "Creates a sigmoid cross entropy loss layer with the reduction type, label smoothing, and weights you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sigmoidCrossEntropy"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "reductionType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCReductionType",
          "text": "MLCReductionType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "labelSmoothing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "weights"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCTensor",
          "text": "MLCTensor"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/sigmoidCrossEntropy(reductionType:labelSmoothing:weights:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sigmoidCrossEntropyLossWithReductionType:labelSmoothing:weights:"
        }
      ],
      "role": "symbol",
      "title": "sigmoidCrossEntropy(reductionType:labelSmoothing:weights:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclosslayer/sigmoidcrossentropy(reductiontype:labelsmoothing:weights:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/softmaxCrossEntropy(reductionType:labelSmoothing:classCount:weight:)": {
      "abstract": [
        {
          "text": "Creates a softmax cross entropy loss layer with the reduction type, label smoothing, number of classes, and weight you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "softmaxCrossEntropy"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "reductionType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCReductionType",
          "text": "MLCReductionType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "labelSmoothing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "classCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "weight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/softmaxCrossEntropy(reductionType:labelSmoothing:classCount:weight:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "softmaxCrossEntropyLossWithReductionType:labelSmoothing:classCount:weight:"
        }
      ],
      "role": "symbol",
      "title": "softmaxCrossEntropy(reductionType:labelSmoothing:classCount:weight:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclosslayer/softmaxcrossentropy(reductiontype:labelsmoothing:classcount:weight:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/softmaxCrossEntropy(reductionType:labelSmoothing:classCount:weights:)": {
      "abstract": [
        {
          "text": "Creates a softmax cross entropy loss layer with the reduction type, label smoothing, number of classes, and weights you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "softmaxCrossEntropy"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "reductionType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCReductionType",
          "text": "MLCReductionType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "labelSmoothing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "classCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "weights"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCTensor",
          "text": "MLCTensor"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/softmaxCrossEntropy(reductionType:labelSmoothing:classCount:weights:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "softmaxCrossEntropyLossWithReductionType:labelSmoothing:classCount:weights:"
        }
      ],
      "role": "symbol",
      "title": "softmaxCrossEntropy(reductionType:labelSmoothing:classCount:weights:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclosslayer/softmaxcrossentropy(reductiontype:labelsmoothing:classcount:weights:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/weights": {
      "abstract": [
        {
          "text": "The loss label weights tensor.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "weights"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCTensor",
          "text": "MLCTensor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/weights",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "weights"
        }
      ],
      "role": "symbol",
      "title": "weights",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclosslayer/weights"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossType": {
      "abstract": [
        {
          "text": "A loss function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCLossType"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCLossType"
        }
      ],
      "role": "symbol",
      "title": "MLCLossType",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclosstype"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossLayer": {
      "abstract": [
        {
          "text": "A layer that estimates loss for the YOLO algorithm.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCYOLOLossLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCYOLOLossLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCYOLOLossLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcyololosslayer"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayer"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossLayer"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Loss-Layers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossLayer"
      ],
      "title": "Loss Layers"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-Loss-Layers-with-Descriptors",
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/init(descriptor:)",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/init(descriptor:weights:)",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossDescriptor",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossType"
      ],
      "title": "Creating Loss Layers with Descriptors"
    },
    {
      "anchor": "Creating-Loss-Layers-with-Scalar-Weights",
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/softmaxCrossEntropy(reductionType:labelSmoothing:classCount:weight:)",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/categoricalCrossEntropy(reductionType:labelSmoothing:classCount:weight:)",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/sigmoidCrossEntropy(reductionType:labelSmoothing:weight:)",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/log(reductionType:epsilon:weight:)",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/huberLoss(reductionType:delta:weight:)",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/meanAbsoluteError(reductionType:weight:)",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/meanSquaredError(reductionType:weight:)",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/hingeLoss(reductionType:weight:)",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/cosineDistance(reductionType:weight:)"
      ],
      "title": "Creating Loss Layers with Scalar Weights"
    },
    {
      "anchor": "Creating-Loss-Layers-with-Tensor-Weights",
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/softmaxCrossEntropy(reductionType:labelSmoothing:classCount:weights:)",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/categoricalCrossEntropy(reductionType:labelSmoothing:classCount:weights:)",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/sigmoidCrossEntropy(reductionType:labelSmoothing:weights:)",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/log(reductionType:epsilon:weights:)",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/huberLoss(reductionType:delta:weights:)",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/meanAbsoluteError(reductionType:weights:)",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/meanSquaredError(reductionType:weights:)",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/hingeLoss(reductionType:weights:)",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/cosineDistance(reductionType:weights:)"
      ],
      "title": "Creating Loss Layers with Tensor Weights"
    },
    {
      "anchor": "Inspecting-Loss-Layers",
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/descriptor",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/weights"
      ],
      "title": "Inspecting Loss Layers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.3",
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MLCLossLayer"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLossLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLossLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mlcompute/documentation/MLCompute"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-Loss-Layers-with-Descriptors",
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/init(descriptor:)",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/init(descriptor:weights:)",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossDescriptor",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossType"
              ],
              "title": "Creating Loss Layers with Descriptors"
            },
            {
              "anchor": "Creating-Loss-Layers-with-Scalar-Weights",
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/softmaxCrossEntropy(reductionType:labelSmoothing:classCount:weight:)",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/categoricalCrossEntropy(reductionType:labelSmoothing:classCount:weight:)",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/sigmoidCrossEntropy(reductionType:labelSmoothing:weight:)",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/log(reductionType:epsilon:weight:)",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/huberLoss(reductionType:delta:weight:)",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/meanAbsoluteError(reductionType:weight:)",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/meanSquaredError(reductionType:weight:)",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/hingeLoss(reductionType:weight:)",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/cosineDistance(reductionType:weight:)"
              ],
              "title": "Creating Loss Layers with Scalar Weights"
            },
            {
              "anchor": "Creating-Loss-Layers-with-Tensor-Weights",
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/softmaxCrossEntropy(reductionType:labelSmoothing:classCount:weights:)",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/categoricalCrossEntropy(reductionType:labelSmoothing:classCount:weights:)",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/sigmoidCrossEntropy(reductionType:labelSmoothing:weights:)",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/log(reductionType:epsilon:weights:)",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/huberLoss(reductionType:delta:weights:)",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/meanAbsoluteError(reductionType:weights:)",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/meanSquaredError(reductionType:weights:)",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/hingeLoss(reductionType:weights:)",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/cosineDistance(reductionType:weights:)"
              ],
              "title": "Creating Loss Layers with Tensor Weights"
            },
            {
              "anchor": "Inspecting-Loss-Layers",
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/descriptor",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer/weights"
              ],
              "title": "Inspecting Loss Layers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayer"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossLayer"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Loss-Layers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossLayer"
              ],
              "title": "Loss Layers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MLCLossLayer"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayer",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MLCLayer",
                    "text": "MLCLayer"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossLayer~1log(reductionType:epsilon:weights:)/title",
          "value": "logLossWithReductionType:epsilon:weights:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossLayer~1log(reductionType:epsilon:weights:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "logLossWithReductionType:epsilon:weights:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossLayer~1init(descriptor:weights:)/title",
          "value": "layerWithDescriptor:weights:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossLayer~1init(descriptor:weights:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "layerWithDescriptor:weights:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossLayer~1hingeLoss(reductionType:weights:)/title",
          "value": "hingeLossWithReductionType:weights:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossLayer~1hingeLoss(reductionType:weights:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "hingeLossWithReductionType:weights:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossLayer~1meanSquaredError(reductionType:weight:)/title",
          "value": "meanSquaredErrorLossWithReductionType:weight:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossLayer~1meanSquaredError(reductionType:weight:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "meanSquaredErrorLossWithReductionType:weight:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLayer/title",
          "value": "MLCLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossLayer~1log(reductionType:epsilon:weight:)/title",
          "value": "logLossWithReductionType:epsilon:weight:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossLayer~1log(reductionType:epsilon:weight:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "logLossWithReductionType:epsilon:weight:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossLayer/title",
          "value": "MLCYOLOLossLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCYOLOLossLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCYOLOLossLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossLayer~1init(descriptor:)/title",
          "value": "layerWithDescriptor:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossLayer~1init(descriptor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "layerWithDescriptor:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossDescriptor/title",
          "value": "MLCLossDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLossDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLossDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossLayer~1hingeLoss(reductionType:weight:)/title",
          "value": "hingeLossWithReductionType:weight:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossLayer~1hingeLoss(reductionType:weight:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "hingeLossWithReductionType:weight:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossLayer~1categoricalCrossEntropy(reductionType:labelSmoothing:classCount:weights:)/title",
          "value": "categoricalCrossEntropyLossWithReductionType:labelSmoothing:classCount:weights:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossLayer~1categoricalCrossEntropy(reductionType:labelSmoothing:classCount:weights:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "categoricalCrossEntropyLossWithReductionType:labelSmoothing:classCount:weights:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossLayer~1softmaxCrossEntropy(reductionType:labelSmoothing:classCount:weights:)/title",
          "value": "softmaxCrossEntropyLossWithReductionType:labelSmoothing:classCount:weights:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossLayer~1softmaxCrossEntropy(reductionType:labelSmoothing:classCount:weights:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "softmaxCrossEntropyLossWithReductionType:labelSmoothing:classCount:weights:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossLayer~1softmaxCrossEntropy(reductionType:labelSmoothing:classCount:weight:)/title",
          "value": "softmaxCrossEntropyLossWithReductionType:labelSmoothing:classCount:weight:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossLayer~1softmaxCrossEntropy(reductionType:labelSmoothing:classCount:weight:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "softmaxCrossEntropyLossWithReductionType:labelSmoothing:classCount:weight:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossLayer~1huberLoss(reductionType:delta:weight:)/title",
          "value": "huberLossWithReductionType:delta:weight:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossLayer~1huberLoss(reductionType:delta:weight:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "huberLossWithReductionType:delta:weight:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossLayer~1cosineDistance(reductionType:weight:)/title",
          "value": "cosineDistanceLossWithReductionType:weight:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossLayer~1cosineDistance(reductionType:weight:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "cosineDistanceLossWithReductionType:weight:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossLayer~1huberLoss(reductionType:delta:weights:)/title",
          "value": "huberLossWithReductionType:delta:weights:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossLayer~1huberLoss(reductionType:delta:weights:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "huberLossWithReductionType:delta:weights:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossLayer~1meanSquaredError(reductionType:weights:)/title",
          "value": "meanSquaredErrorLossWithReductionType:weights:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossLayer~1meanSquaredError(reductionType:weights:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "meanSquaredErrorLossWithReductionType:weights:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossLayer~1meanAbsoluteError(reductionType:weight:)/title",
          "value": "meanAbsoluteErrorLossWithReductionType:weight:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossLayer~1meanAbsoluteError(reductionType:weight:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "meanAbsoluteErrorLossWithReductionType:weight:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossLayer~1categoricalCrossEntropy(reductionType:labelSmoothing:classCount:weight:)/title",
          "value": "categoricalCrossEntropyLossWithReductionType:labelSmoothing:classCount:weight:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossLayer~1categoricalCrossEntropy(reductionType:labelSmoothing:classCount:weight:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "categoricalCrossEntropyLossWithReductionType:labelSmoothing:classCount:weight:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossLayer~1cosineDistance(reductionType:weights:)/title",
          "value": "cosineDistanceLossWithReductionType:weights:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossLayer~1cosineDistance(reductionType:weights:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "cosineDistanceLossWithReductionType:weights:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossLayer~1descriptor/title",
          "value": "descriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossLayer~1descriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "descriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossLayer~1sigmoidCrossEntropy(reductionType:labelSmoothing:weight:)/title",
          "value": "sigmoidCrossEntropyLossWithReductionType:labelSmoothing:weight:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossLayer~1sigmoidCrossEntropy(reductionType:labelSmoothing:weight:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "sigmoidCrossEntropyLossWithReductionType:labelSmoothing:weight:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossType/title",
          "value": "MLCLossType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLossType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLossType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossLayer~1weights/title",
          "value": "weights"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossLayer~1weights/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "weights"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossLayer~1sigmoidCrossEntropy(reductionType:labelSmoothing:weights:)/title",
          "value": "sigmoidCrossEntropyLossWithReductionType:labelSmoothing:weights:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossLayer~1sigmoidCrossEntropy(reductionType:labelSmoothing:weights:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "sigmoidCrossEntropyLossWithReductionType:labelSmoothing:weights:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossLayer~1meanAbsoluteError(reductionType:weights:)/title",
          "value": "meanAbsoluteErrorLossWithReductionType:weights:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossLayer~1meanAbsoluteError(reductionType:weights:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "meanAbsoluteErrorLossWithReductionType:weights:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossLayer/title",
          "value": "MLCLossLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLossLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLossLayer"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mlcompute/mlclosslayer"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mlcompute/mlclosslayer"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
