{
  "abstract": [
    {
      "text": "A layer that applies layer normalization over inputs.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mlcompute/documentation/MLCompute"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayerNormalizationLayer"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MLCLayerNormalizationLayer",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MLCLayerNormalizationLayer"
      }
    ],
    "modules": [
      {
        "name": "ML Compute"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MLCLayerNormalizationLayer"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.3",
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MLCLayerNormalizationLayer"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MLCLayerNormalizationLayer"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute": {
      "abstract": [
        {
          "text": "Accelerate training and validation of neural networks across the CPU and one or more GPUs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute",
      "kind": "symbol",
      "role": "collection",
      "title": "ML Compute",
      "type": "topic",
      "url": "/documentation/mlcompute"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCBatchNormalizationLayer": {
      "abstract": [
        {
          "text": "A layer that normalizes a batch of inputs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCBatchNormalizationLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCBatchNormalizationLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCBatchNormalizationLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCBatchNormalizationLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcbatchnormalizationlayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCDropoutLayer": {
      "abstract": [
        {
          "text": "A layer that deactivates neurons randomly to avoid overfitting.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCDropoutLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCDropoutLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCDropoutLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCDropoutLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcdropoutlayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCGroupNormalizationLayer": {
      "abstract": [
        {
          "text": "A layer that divides the channels into groups for normalization.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCGroupNormalizationLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCGroupNormalizationLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCGroupNormalizationLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCGroupNormalizationLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcgroupnormalizationlayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCInstanceNormalizationLayer": {
      "abstract": [
        {
          "text": "A layer that normalizes all features of one channel.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCInstanceNormalizationLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCInstanceNormalizationLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCInstanceNormalizationLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCInstanceNormalizationLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcinstancenormalizationlayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayer": {
      "abstract": [
        {
          "text": "The base class for all framework layers.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayerNormalizationLayer": {
      "abstract": [
        {
          "text": "A layer that applies layer normalization over inputs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCLayerNormalizationLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayerNormalizationLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCLayerNormalizationLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCLayerNormalizationLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclayernormalizationlayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayerNormalizationLayer/beta": {
      "abstract": [
        {
          "text": "The beta tensor.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beta"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCTensor",
          "text": "MLCTensor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayerNormalizationLayer/beta",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beta"
        }
      ],
      "role": "symbol",
      "title": "beta",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclayernormalizationlayer/beta"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayerNormalizationLayer/betaParameter": {
      "abstract": [
        {
          "text": "The beta tensor parameter you use for optimizer updates.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "betaParameter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCTensorParameter",
          "text": "MLCTensorParameter"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayerNormalizationLayer/betaParameter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "betaParameter"
        }
      ],
      "role": "symbol",
      "title": "betaParameter",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclayernormalizationlayer/betaparameter"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayerNormalizationLayer/gamma": {
      "abstract": [
        {
          "text": "The gamma tensor.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gamma"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCTensor",
          "text": "MLCTensor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayerNormalizationLayer/gamma",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gamma"
        }
      ],
      "role": "symbol",
      "title": "gamma",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclayernormalizationlayer/gamma"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayerNormalizationLayer/gammaParameter": {
      "abstract": [
        {
          "text": "The gamma tensor parameter you use for optimizer updates.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gammaParameter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCTensorParameter",
          "text": "MLCTensorParameter"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayerNormalizationLayer/gammaParameter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gammaParameter"
        }
      ],
      "role": "symbol",
      "title": "gammaParameter",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclayernormalizationlayer/gammaparameter"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayerNormalizationLayer/init(normalizedShape:beta:gamma:varianceEpsilon:)-28e6g": {
      "abstract": [
        {
          "text": "Creates a normalization layer with a shape, optional beta and gamma tensors, and variance epsilon you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "normalizedShape"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "beta"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCTensor",
          "text": "MLCTensor"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "gamma"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCTensor",
          "text": "MLCTensor"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "varianceEpsilon"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayerNormalizationLayer/init(normalizedShape:beta:gamma:varianceEpsilon:)-28e6g",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(normalizedShape:beta:gamma:varianceEpsilon:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclayernormalizationlayer/init(normalizedshape:beta:gamma:varianceepsilon:)-28e6g"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayerNormalizationLayer/init(normalizedShape:beta:gamma:varianceEpsilon:)-5i2aa": {
      "abstract": [
        {
          "text": "Creates a normalization layer with a shape, beta and gamma tensors, and variance epsilon you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "normalizedShape"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "beta"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCTensor",
          "text": "MLCTensor"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "gamma"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCTensor",
          "text": "MLCTensor"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "varianceEpsilon"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayerNormalizationLayer/init(normalizedShape:beta:gamma:varianceEpsilon:)-5i2aa",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(normalizedShape:beta:gamma:varianceEpsilon:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclayernormalizationlayer/init(normalizedshape:beta:gamma:varianceepsilon:)-5i2aa"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayerNormalizationLayer/layerWithNormalizedShape:beta:gamma:varianceEpsilon:": {
      "abstract": [
        {
          "text": "Creates a normalization layer with a shape, beta and gamma tensors, and variance epsilon you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "layerWithNormalizedShape:beta:gamma:varianceEpsilon:"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayerNormalizationLayer/layerWithNormalizedShape:beta:gamma:varianceEpsilon:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layerWithNormalizedShape:beta:gamma:varianceEpsilon:"
        }
      ],
      "role": "symbol",
      "title": "layerWithNormalizedShape:beta:gamma:varianceEpsilon:",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclayernormalizationlayer/layerwithnormalizedshape:beta:gamma:varianceepsilon:"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayerNormalizationLayer/normalizedShape-2cz6k": {
      "abstract": [
        {
          "text": "The shape of the axes where normalization occurs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "normalizedShape"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayerNormalizationLayer/normalizedShape-2cz6k",
      "kind": "symbol",
      "role": "symbol",
      "title": "normalizedShape",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclayernormalizationlayer/normalizedshape-2cz6k"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayerNormalizationLayer/normalizedShape-8ujvv": {
      "abstract": [
        {
          "text": "The shape of the axes where normalization occurs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "normalizedShape"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayerNormalizationLayer/normalizedShape-8ujvv",
      "kind": "symbol",
      "role": "symbol",
      "title": "normalizedShape",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclayernormalizationlayer/normalizedshape-8ujvv"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayerNormalizationLayer/varianceEpsilon": {
      "abstract": [
        {
          "text": "The variance epsilon you use for numerical stability.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "varianceEpsilon"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayerNormalizationLayer/varianceEpsilon",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "varianceEpsilon"
        }
      ],
      "role": "symbol",
      "title": "varianceEpsilon",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclayernormalizationlayer/varianceepsilon"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayer"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Normalization-Layers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCBatchNormalizationLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCGroupNormalizationLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCInstanceNormalizationLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCDropoutLayer"
      ],
      "title": "Normalization Layers"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-Layer-Normalization-Layers",
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayerNormalizationLayer/init(normalizedShape:beta:gamma:varianceEpsilon:)-5i2aa",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayerNormalizationLayer/init(normalizedShape:beta:gamma:varianceEpsilon:)-28e6g"
      ],
      "title": "Creating Layer Normalization Layers"
    },
    {
      "anchor": "Inspecting-Layer-Normalization-Layers",
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayerNormalizationLayer/normalizedShape-8ujvv",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayerNormalizationLayer/beta",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayerNormalizationLayer/gamma",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayerNormalizationLayer/varianceEpsilon",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayerNormalizationLayer/betaParameter",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayerNormalizationLayer/gammaParameter"
      ],
      "title": "Inspecting Layer Normalization Layers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.3",
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MLCLayerNormalizationLayer"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLayerNormalizationLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLayerNormalizationLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mlcompute/documentation/MLCompute"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Inspecting-Layer-Normalization-Layers",
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayerNormalizationLayer/normalizedShape-2cz6k",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayerNormalizationLayer/beta",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayerNormalizationLayer/gamma",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayerNormalizationLayer/varianceEpsilon",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayerNormalizationLayer/betaParameter",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayerNormalizationLayer/gammaParameter"
              ],
              "title": "Inspecting Layer Normalization Layers"
            },
            {
              "anchor": "Type-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayerNormalizationLayer/layerWithNormalizedShape:beta:gamma:varianceEpsilon:"
              ],
              "title": "Type Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayer"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Normalization-Layers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCBatchNormalizationLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCGroupNormalizationLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCInstanceNormalizationLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCDropoutLayer"
              ],
              "title": "Normalization Layers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MLCLayerNormalizationLayer"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayer",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MLCLayer",
                    "text": "MLCLayer"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLayerNormalizationLayer/title",
          "value": "MLCLayerNormalizationLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLayerNormalizationLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLayerNormalizationLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLayerNormalizationLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLayerNormalizationLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLayerNormalizationLayer~1gamma/title",
          "value": "gamma"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLayerNormalizationLayer~1gamma/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gamma"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLayerNormalizationLayer~1beta/title",
          "value": "beta"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLayerNormalizationLayer~1beta/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "beta"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLayerNormalizationLayer~1betaParameter/title",
          "value": "betaParameter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLayerNormalizationLayer~1betaParameter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "betaParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCBatchNormalizationLayer/title",
          "value": "MLCBatchNormalizationLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCBatchNormalizationLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCBatchNormalizationLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCBatchNormalizationLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCBatchNormalizationLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLayer/title",
          "value": "MLCLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCDropoutLayer/title",
          "value": "MLCDropoutLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCDropoutLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCDropoutLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCDropoutLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCDropoutLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLayerNormalizationLayer~1varianceEpsilon/title",
          "value": "varianceEpsilon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLayerNormalizationLayer~1varianceEpsilon/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "varianceEpsilon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLayerNormalizationLayer~1gammaParameter/title",
          "value": "gammaParameter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLayerNormalizationLayer~1gammaParameter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gammaParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCGroupNormalizationLayer/title",
          "value": "MLCGroupNormalizationLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCGroupNormalizationLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCGroupNormalizationLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCGroupNormalizationLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCGroupNormalizationLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCInstanceNormalizationLayer/title",
          "value": "MLCInstanceNormalizationLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCInstanceNormalizationLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCInstanceNormalizationLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCInstanceNormalizationLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCInstanceNormalizationLayer"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mlcompute/mlclayernormalizationlayer"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mlcompute/mlclayernormalizationlayer"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
