{
  "abstract": [
    {
      "text": "The base class for all framework layers.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mlcompute/documentation/MLCompute"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayer"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MLCLayer",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MLCLayer"
      }
    ],
    "modules": [
      {
        "name": "ML Compute"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MLCLayer"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.3",
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MLCLayer"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MLCLayer"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This class defines a polymorphic interface for ",
              "type": "text"
            },
            {
              "code": "MLCLayer",
              "type": "codeVoice"
            },
            {
              "text": " subclasses. There are subclasses for each supported neural network layer type. Use the appropriate subclass initializer to create a layer object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute": {
      "abstract": [
        {
          "text": "Accelerate training and validation of neural networks across the CPU and one or more GPUs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute",
      "kind": "symbol",
      "role": "collection",
      "title": "ML Compute",
      "type": "topic",
      "url": "/documentation/mlcompute"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer": {
      "abstract": [
        {
          "text": "A layer that applies an activation function to the source tensor and produces an output.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCActivationLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationlayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticLayer": {
      "abstract": [
        {
          "text": "A layer that performs an arithmetic operation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCArithmeticLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticlayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCBatchNormalizationLayer": {
      "abstract": [
        {
          "text": "A layer that normalizes a batch of inputs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCBatchNormalizationLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCBatchNormalizationLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCBatchNormalizationLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCBatchNormalizationLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcbatchnormalizationlayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonLayer": {
      "abstract": [
        {
          "text": "A layer that performs elementwise comparison of two tensors.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCComparisonLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCComparisonLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCComparisonLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlccomparisonlayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCConcatenationLayer": {
      "abstract": [
        {
          "text": "A layer that combines tensors into a single tensor.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCConcatenationLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCConcatenationLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCConcatenationLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCConcatenationLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcconcatenationlayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCConvolutionLayer": {
      "abstract": [
        {
          "text": "A layer that applies a convolution over a signal.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCConvolutionLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCConvolutionLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCConvolutionLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCConvolutionLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcconvolutionlayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCDropoutLayer": {
      "abstract": [
        {
          "text": "A layer that deactivates neurons randomly to avoid overfitting.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCDropoutLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCDropoutLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCDropoutLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCDropoutLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcdropoutlayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCEmbeddingLayer": {
      "abstract": [
        {
          "text": "A layer that stores a word embedding.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCEmbeddingLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCEmbeddingLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCEmbeddingLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCEmbeddingLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcembeddinglayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCFullyConnectedLayer": {
      "abstract": [
        {
          "text": "A layer that connects each input to each output within its layer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCFullyConnectedLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCFullyConnectedLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCFullyConnectedLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCFullyConnectedLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcfullyconnectedlayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCGatherLayer": {
      "abstract": [
        {
          "text": "A layer that fetches data at the locations you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCGatherLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCGatherLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCGatherLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCGatherLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcgatherlayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCGramMatrixLayer": {
      "abstract": [
        {
          "text": "A layer that computes the uncentered cross-correlation values between the spacial planes of each feature channel of a tensor.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCGramMatrixLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCGramMatrixLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCGramMatrixLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCGramMatrixLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcgrammatrixlayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCGroupNormalizationLayer": {
      "abstract": [
        {
          "text": "A layer that divides the channels into groups for normalization.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCGroupNormalizationLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCGroupNormalizationLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCGroupNormalizationLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCGroupNormalizationLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcgroupnormalizationlayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCInstanceNormalizationLayer": {
      "abstract": [
        {
          "text": "A layer that normalizes all features of one channel.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCInstanceNormalizationLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCInstanceNormalizationLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCInstanceNormalizationLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCInstanceNormalizationLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcinstancenormalizationlayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer": {
      "abstract": [
        {
          "text": "A layer that represents long short-term memory (LSTM) networks.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCLSTMLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCLSTMLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCLSTMLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclstmlayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayer": {
      "abstract": [
        {
          "text": "The base class for all framework layers.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayer/deviceType": {
      "abstract": [
        {
          "text": "A device type that indicates where the system executes the layer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCDeviceType",
          "text": "MLCDeviceType"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayer/deviceType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deviceType"
        }
      ],
      "role": "symbol",
      "title": "deviceType",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclayer/devicetype"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayer/isDebuggingEnabled": {
      "abstract": [
        {
          "text": "A Boolean that indicates whether you choose to debug the layer when executing a graph that includes it.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isDebuggingEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayer/isDebuggingEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isDebuggingEnabled"
        }
      ],
      "role": "symbol",
      "title": "isDebuggingEnabled",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclayer/isdebuggingenabled"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayer/label": {
      "abstract": [
        {
          "text": "A string that helps identify this layer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "label"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayer/label",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "label"
        }
      ],
      "role": "symbol",
      "title": "label",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclayer/label"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayer/layerID": {
      "abstract": [
        {
          "text": "A unique number that identifies each layer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layerID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayer/layerID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layerID"
        }
      ],
      "role": "symbol",
      "title": "layerID",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclayer/layerid"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayer/supportsDataType(_:on:)": {
      "abstract": [
        {
          "text": "Returns a Boolean that indicates whether instances of this layer accept source tensors for the data type and device that you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsDataType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCDataType",
          "text": "MLCDataType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "on"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCDevice",
          "text": "MLCDevice"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayer/supportsDataType(_:on:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsDataType:onDevice:"
        }
      ],
      "role": "symbol",
      "title": "supportsDataType(_:on:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclayer/supportsdatatype(_:on:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayerNormalizationLayer": {
      "abstract": [
        {
          "text": "A layer that applies layer normalization over inputs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCLayerNormalizationLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayerNormalizationLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCLayerNormalizationLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCLayerNormalizationLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclayernormalizationlayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer": {
      "abstract": [
        {
          "text": "A layer that estimates the inaccuracies of the model to reduce the loss on the next evaluation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCLossLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCLossLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCLossLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclosslayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCMatMulLayer": {
      "abstract": [
        {
          "text": "A layer that multiplies matrices.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCMatMulLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCMatMulLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCMatMulLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCMatMulLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcmatmullayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCMultiheadAttentionLayer": {
      "abstract": [
        {
          "text": "A multihead, scaled dot-product attention layer that attends to one or more entries in the input key-value pairs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCMultiheadAttentionLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCMultiheadAttentionLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCMultiheadAttentionLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCMultiheadAttentionLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcmultiheadattentionlayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingLayer": {
      "abstract": [
        {
          "text": "A layer that pads a tensor with the padding sizes you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCPaddingLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCPaddingLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCPaddingLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpaddinglayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingLayer": {
      "abstract": [
        {
          "text": "A layer that summarizes the average presence of a feature.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCPoolingLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCPoolingLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCPoolingLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolinglayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionLayer": {
      "abstract": [
        {
          "text": "A layer that reduces tensor values across a specific dimension to a scalar value.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCReductionLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCReductionLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCReductionLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcreductionlayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCReshapeLayer": {
      "abstract": [
        {
          "text": "A layer that reshapes a tensor with the shape you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCReshapeLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCReshapeLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCReshapeLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCReshapeLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcreshapelayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCScatterLayer": {
      "abstract": [
        {
          "text": "A layer that updates the output at an index you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCScatterLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCScatterLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCScatterLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCScatterLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcscatterlayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCSelectionLayer": {
      "abstract": [
        {
          "text": "A layer for selecting elements from two tensors.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCSelectionLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCSelectionLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCSelectionLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCSelectionLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcselectionlayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCSliceLayer": {
      "abstract": [
        {
          "text": "A layer that extracts a slice from a tensor.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCSliceLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCSliceLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCSliceLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCSliceLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcslicelayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCSoftmaxLayer": {
      "abstract": [
        {
          "text": "A layer that outputs a probability distribution as attention weights.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCSoftmaxLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCSoftmaxLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCSoftmaxLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCSoftmaxLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcsoftmaxlayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCSplitLayer": {
      "abstract": [
        {
          "text": "A layer that splits a tensor value into a list of subtensors.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCSplitLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCSplitLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCSplitLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCSplitLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcsplitlayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCTransposeLayer": {
      "abstract": [
        {
          "text": "A layer that permutes the dimensions you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCTransposeLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTransposeLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCTransposeLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCTransposeLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlctransposelayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCUpsampleLayer": {
      "abstract": [
        {
          "text": "A layer that applies upsampling with the shape you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCUpsampleLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCUpsampleLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCUpsampleLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCUpsampleLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcupsamplelayer"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCBatchNormalizationLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCConcatenationLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCConvolutionLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCDropoutLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCEmbeddingLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCFullyConnectedLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCGatherLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCGramMatrixLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCGroupNormalizationLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCInstanceNormalizationLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayerNormalizationLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCMatMulLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCMultiheadAttentionLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCReshapeLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCScatterLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCSelectionLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCSliceLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCSoftmaxLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCSplitLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCTransposeLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCUpsampleLayer"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Inspecting-a-Layer",
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayer/layerID",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayer/label",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayer/isDebuggingEnabled",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayer/deviceType",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayer/supportsDataType(_:on:)"
      ],
      "title": "Inspecting a Layer"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.3",
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MLCLayer"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mlcompute/documentation/MLCompute"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Inspecting-a-Layer",
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayer/layerID",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayer/label",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayer/isDebuggingEnabled",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayer/deviceType",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayer/supportsDataType(_:on:)"
              ],
              "title": "Inspecting a Layer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCBatchNormalizationLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCComparisonLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCConcatenationLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCConvolutionLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCDropoutLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCEmbeddingLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCFullyConnectedLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCGatherLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCGramMatrixLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCGroupNormalizationLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCInstanceNormalizationLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayerNormalizationLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLossLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCMatMulLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCMultiheadAttentionLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCPaddingLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCReshapeLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCScatterLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCSelectionLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCSliceLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCSoftmaxLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCSplitLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCTransposeLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCUpsampleLayer"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MLCLayer"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCComparisonLayer/title",
          "value": "MLCComparisonLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCComparisonLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCComparisonLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCComparisonLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCComparisonLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCSplitLayer/title",
          "value": "MLCSplitLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCSplitLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCSplitLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCSplitLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCSplitLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer/title",
          "value": "MLCActivationLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTransposeLayer/title",
          "value": "MLCTransposeLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTransposeLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCTransposeLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTransposeLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCTransposeLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCSliceLayer/title",
          "value": "MLCSliceLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCSliceLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCSliceLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCSliceLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCSliceLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLayerNormalizationLayer/title",
          "value": "MLCLayerNormalizationLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLayerNormalizationLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLayerNormalizationLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLayerNormalizationLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLayerNormalizationLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCGatherLayer/title",
          "value": "MLCGatherLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCGatherLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCGatherLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCGatherLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCGatherLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCReshapeLayer/title",
          "value": "MLCReshapeLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCReshapeLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCReshapeLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCReshapeLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCReshapeLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCGramMatrixLayer/title",
          "value": "MLCGramMatrixLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCGramMatrixLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCGramMatrixLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCGramMatrixLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCGramMatrixLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticLayer/title",
          "value": "MLCArithmeticLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCUpsampleLayer/title",
          "value": "MLCUpsampleLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCUpsampleLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCUpsampleLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCUpsampleLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCUpsampleLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCDropoutLayer/title",
          "value": "MLCDropoutLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCDropoutLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCDropoutLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCDropoutLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCDropoutLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLayer~1supportsDataType(_:on:)/title",
          "value": "supportsDataType:onDevice:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLayer~1supportsDataType(_:on:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "supportsDataType:onDevice:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCEmbeddingLayer/title",
          "value": "MLCEmbeddingLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCEmbeddingLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCEmbeddingLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCEmbeddingLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCEmbeddingLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMLayer/title",
          "value": "MLCLSTMLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLSTMLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLSTMLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCBatchNormalizationLayer/title",
          "value": "MLCBatchNormalizationLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCBatchNormalizationLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCBatchNormalizationLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCBatchNormalizationLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCBatchNormalizationLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCMatMulLayer/title",
          "value": "MLCMatMulLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCMatMulLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCMatMulLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCMatMulLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCMatMulLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossLayer/title",
          "value": "MLCLossLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLossLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLossLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLossLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLayer~1label/title",
          "value": "label"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLayer~1label/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "label"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCMultiheadAttentionLayer/title",
          "value": "MLCMultiheadAttentionLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCMultiheadAttentionLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCMultiheadAttentionLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCMultiheadAttentionLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCMultiheadAttentionLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCConcatenationLayer/title",
          "value": "MLCConcatenationLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCConcatenationLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCConcatenationLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCConcatenationLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCConcatenationLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCConvolutionLayer/title",
          "value": "MLCConvolutionLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCConvolutionLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCConvolutionLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCConvolutionLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCConvolutionLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCReductionLayer/title",
          "value": "MLCReductionLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCReductionLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCReductionLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCReductionLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCReductionLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLayer~1isDebuggingEnabled/title",
          "value": "isDebuggingEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLayer~1isDebuggingEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "isDebuggingEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCScatterLayer/title",
          "value": "MLCScatterLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCScatterLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCScatterLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCScatterLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCScatterLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPaddingLayer/title",
          "value": "MLCPaddingLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPaddingLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCPaddingLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPaddingLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCPaddingLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLayer/title",
          "value": "MLCLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLayer~1deviceType/title",
          "value": "deviceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLayer~1deviceType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "deviceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCSelectionLayer/title",
          "value": "MLCSelectionLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCSelectionLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCSelectionLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCSelectionLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCSelectionLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCGroupNormalizationLayer/title",
          "value": "MLCGroupNormalizationLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCGroupNormalizationLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCGroupNormalizationLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCGroupNormalizationLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCGroupNormalizationLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCInstanceNormalizationLayer/title",
          "value": "MLCInstanceNormalizationLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCInstanceNormalizationLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCInstanceNormalizationLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCInstanceNormalizationLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCInstanceNormalizationLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLayer~1layerID/title",
          "value": "layerID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLayer~1layerID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "layerID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCSoftmaxLayer/title",
          "value": "MLCSoftmaxLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCSoftmaxLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCSoftmaxLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCSoftmaxLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCSoftmaxLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPoolingLayer/title",
          "value": "MLCPoolingLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPoolingLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCPoolingLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPoolingLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCPoolingLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCFullyConnectedLayer/title",
          "value": "MLCFullyConnectedLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCFullyConnectedLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCFullyConnectedLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCFullyConnectedLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCFullyConnectedLayer"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mlcompute/mlclayer"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mlcompute/mlclayer"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
