{
  "abstract": [
    {
      "text": "The base class for all framework optimizers.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mlcompute/documentation/MLCompute"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MLCOptimizer",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MLCOptimizer"
      }
    ],
    "modules": [
      {
        "name": "ML Compute"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MLCOptimizer"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.3",
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MLCOptimizer"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MLCOptimizer"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute": {
      "abstract": [
        {
          "text": "Accelerate training and validation of neural networks across the CPU and one or more GPUs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute",
      "kind": "symbol",
      "role": "collection",
      "title": "ML Compute",
      "type": "topic",
      "url": "/documentation/mlcompute"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCAdamOptimizer": {
      "abstract": [
        {
          "text": "An optimizer that represents the adaptive moment estimation algorithm.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCAdamOptimizer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCAdamOptimizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCAdamOptimizer"
        }
      ],
      "role": "symbol",
      "title": "MLCAdamOptimizer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcadamoptimizer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCAdamWOptimizer": {
      "abstract": [
        {
          "text": "An optimizer that represents the Adam algorithm with weight decay.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCAdamWOptimizer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCAdamWOptimizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCAdamWOptimizer"
        }
      ],
      "role": "symbol",
      "title": "MLCAdamWOptimizer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcadamwoptimizer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCGradientClippingType": {
      "abstract": [
        {
          "text": "A clipping type the system applies to a gradient.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCGradientClippingType"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCGradientClippingType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCGradientClippingType"
        }
      ],
      "role": "symbol",
      "title": "MLCGradientClippingType",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcgradientclippingtype"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer": {
      "abstract": [
        {
          "text": "The base class for all framework optimizers.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCOptimizer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCOptimizer"
        }
      ],
      "role": "symbol",
      "title": "MLCOptimizer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcoptimizer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/appliesGradientClipping": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether you apply gradient clipping.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appliesGradientClipping"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/appliesGradientClipping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "appliesGradientClipping"
        }
      ],
      "role": "symbol",
      "title": "appliesGradientClipping",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcoptimizer/appliesgradientclipping"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/customGlobalNorm": {
      "abstract": [
        {
          "text": "A custom norm the system uses in place of the global norm.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "customGlobalNorm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/customGlobalNorm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "customGlobalNorm"
        }
      ],
      "role": "symbol",
      "title": "customGlobalNorm",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcoptimizer/customglobalnorm"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/gradientClipMax": {
      "abstract": [
        {
          "text": "The maximum gradient value before the optimizer rescales the gradient, if you enable gradient clipping.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gradientClipMax"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/gradientClipMax",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gradientClipMax"
        }
      ],
      "role": "symbol",
      "title": "gradientClipMax",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcoptimizer/gradientclipmax"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/gradientClipMin": {
      "abstract": [
        {
          "text": "The minimum gradient value before the optimizer rescales the gradient, if you enable gradient clipping.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gradientClipMin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/gradientClipMin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gradientClipMin"
        }
      ],
      "role": "symbol",
      "title": "gradientClipMin",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcoptimizer/gradientclipmin"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/gradientClippingType": {
      "abstract": [
        {
          "text": "The type of clipping the system applies to the gradient.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gradientClippingType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCGradientClippingType",
          "text": "MLCGradientClippingType"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/gradientClippingType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gradientClippingType"
        }
      ],
      "role": "symbol",
      "title": "gradientClippingType",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcoptimizer/gradientclippingtype"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/gradientRescale": {
      "abstract": [
        {
          "text": "The rescale value the optimizer applies to gradients during updates.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gradientRescale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/gradientRescale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gradientRescale"
        }
      ],
      "role": "symbol",
      "title": "gradientRescale",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcoptimizer/gradientrescale"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/learningRate": {
      "abstract": [
        {
          "text": "The learning rate.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "learningRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/learningRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "learningRate"
        }
      ],
      "role": "symbol",
      "title": "learningRate",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcoptimizer/learningrate"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/maximumClippingNorm": {
      "abstract": [
        {
          "text": "The maximum clipping value.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumClippingNorm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/maximumClippingNorm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maximumClippingNorm"
        }
      ],
      "role": "symbol",
      "title": "maximumClippingNorm",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcoptimizer/maximumclippingnorm"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/regularizationScale": {
      "abstract": [
        {
          "text": "The regularization scale.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "regularizationScale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/regularizationScale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "regularizationScale"
        }
      ],
      "role": "symbol",
      "title": "regularizationScale",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcoptimizer/regularizationscale"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/regularizationType": {
      "abstract": [
        {
          "text": "The regularization type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "regularizationType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCRegularizationType",
          "text": "MLCRegularizationType"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/regularizationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "regularizationType"
        }
      ],
      "role": "symbol",
      "title": "regularizationType",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcoptimizer/regularizationtype"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCRMSPropOptimizer": {
      "abstract": [
        {
          "text": "An optimizer that represents the root mean square propagation algorithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCRMSPropOptimizer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCRMSPropOptimizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCRMSPropOptimizer"
        }
      ],
      "role": "symbol",
      "title": "MLCRMSPropOptimizer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcrmspropoptimizer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCSGDOptimizer": {
      "abstract": [
        {
          "text": "An optimizer that represents the stochastic gradient decent algorithm.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCSGDOptimizer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCSGDOptimizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCSGDOptimizer"
        }
      ],
      "role": "symbol",
      "title": "MLCSGDOptimizer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcsgdoptimizer"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCAdamOptimizer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCAdamWOptimizer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCRMSPropOptimizer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCSGDOptimizer"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Optimizer-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCSGDOptimizer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCRMSPropOptimizer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCAdamOptimizer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCAdamWOptimizer"
      ],
      "title": "Optimizer Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Inspecting-an-Optimizer",
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/learningRate",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/gradientRescale",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/appliesGradientClipping",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/gradientClipMax",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/gradientClipMin",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/regularizationScale",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/regularizationType",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/gradientClippingType",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCGradientClippingType",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/maximumClippingNorm",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/customGlobalNorm"
      ],
      "title": "Inspecting an Optimizer"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.3",
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MLCOptimizer"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCOptimizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCOptimizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mlcompute/documentation/MLCompute"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Inspecting-an-Optimizer",
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/learningRate",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/gradientRescale",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/appliesGradientClipping",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/gradientClipMax",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/gradientClipMin",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/regularizationScale",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/regularizationType",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/gradientClippingType",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCGradientClippingType",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/maximumClippingNorm",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer/customGlobalNorm"
              ],
              "title": "Inspecting an Optimizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCAdamOptimizer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCAdamWOptimizer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCRMSPropOptimizer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCSGDOptimizer"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Optimizer-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCSGDOptimizer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCRMSPropOptimizer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCAdamOptimizer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCAdamWOptimizer"
              ],
              "title": "Optimizer Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MLCOptimizer"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizer~1gradientRescale/title",
          "value": "gradientRescale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizer~1gradientRescale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gradientRescale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizer/title",
          "value": "MLCOptimizer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCOptimizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCOptimizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCRMSPropOptimizer/title",
          "value": "MLCRMSPropOptimizer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCRMSPropOptimizer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCRMSPropOptimizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCRMSPropOptimizer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCRMSPropOptimizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizer~1maximumClippingNorm/title",
          "value": "maximumClippingNorm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizer~1maximumClippingNorm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maximumClippingNorm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizer~1customGlobalNorm/title",
          "value": "customGlobalNorm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizer~1customGlobalNorm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "customGlobalNorm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizer~1gradientClipMax/title",
          "value": "gradientClipMax"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizer~1gradientClipMax/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gradientClipMax"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizer~1regularizationType/title",
          "value": "regularizationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizer~1regularizationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "regularizationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizer~1gradientClipMin/title",
          "value": "gradientClipMin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizer~1gradientClipMin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gradientClipMin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCAdamWOptimizer/title",
          "value": "MLCAdamWOptimizer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCAdamWOptimizer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCAdamWOptimizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCAdamWOptimizer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCAdamWOptimizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizer~1gradientClippingType/title",
          "value": "gradientClippingType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizer~1gradientClippingType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gradientClippingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCAdamOptimizer/title",
          "value": "MLCAdamOptimizer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCAdamOptimizer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCAdamOptimizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCAdamOptimizer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCAdamOptimizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizer~1learningRate/title",
          "value": "learningRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizer~1learningRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "learningRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCSGDOptimizer/title",
          "value": "MLCSGDOptimizer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCSGDOptimizer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCSGDOptimizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCSGDOptimizer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCSGDOptimizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizer~1regularizationScale/title",
          "value": "regularizationScale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizer~1regularizationScale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "regularizationScale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCGradientClippingType/title",
          "value": "MLCGradientClippingType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCGradientClippingType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCGradientClippingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCGradientClippingType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCGradientClippingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizer~1appliesGradientClipping/title",
          "value": "appliesGradientClipping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizer~1appliesGradientClipping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "appliesGradientClipping"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mlcompute/mlcoptimizer"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mlcompute/mlcoptimizer"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
