{
  "abstract": [
    {
      "text": "A pooling function type for a pooling layer.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mlcompute/documentation/MLCompute"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingType-8hrit"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MLCPoolingType",
    "fragments": [
      {
        "kind": "identifier",
        "text": "MLCPoolingType"
      }
    ],
    "modules": [
      {
        "name": "ML Compute"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MLCPoolingType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MLCPoolingType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MLCPoolingType"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@int32_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@int32_t",
              "text": "int32_t"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute": {
      "abstract": [
        {
          "text": "Accelerate training and validation of neural networks across the CPU and one or more GPUs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute",
      "kind": "symbol",
      "role": "collection",
      "title": "ML Compute",
      "type": "topic",
      "url": "/documentation/mlcompute"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor": {
      "abstract": [
        {
          "text": "A configuration object you use to create a pooling layer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCPoolingDescriptor"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCPoolingDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MLCPoolingDescriptor",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingdescriptor"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingLayer/init(descriptor:)": {
      "abstract": [
        {
          "text": "Creates a pooling layer with the descriptor you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "descriptor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCPoolingDescriptor",
          "text": "MLCPoolingDescriptor"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingLayer/init(descriptor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layerWithDescriptor:"
        }
      ],
      "role": "symbol",
      "title": "init(descriptor:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolinglayer/init(descriptor:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingType-8hrit": {
      "abstract": [
        {
          "text": "A pooling function type for a pooling layer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MLCPoolingType"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingType-8hrit",
      "kind": "symbol",
      "role": "symbol",
      "title": "MLCPoolingType",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingtype-8hrit"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingType-8hrit/MLCPoolingTypeAverage": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MLCPoolingTypeAverage"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingType-8hrit/MLCPoolingTypeAverage",
      "kind": "symbol",
      "role": "symbol",
      "title": "MLCPoolingTypeAverage",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingtype-8hrit/mlcpoolingtypeaverage"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingType-8hrit/MLCPoolingTypeCount": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MLCPoolingTypeCount"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingType-8hrit/MLCPoolingTypeCount",
      "kind": "symbol",
      "role": "symbol",
      "title": "MLCPoolingTypeCount",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingtype-8hrit/mlcpoolingtypecount"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingType-8hrit/MLCPoolingTypeL2Norm": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MLCPoolingTypeL2Norm"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingType-8hrit/MLCPoolingTypeL2Norm",
      "kind": "symbol",
      "role": "symbol",
      "title": "MLCPoolingTypeL2Norm",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingtype-8hrit/mlcpoolingtypel2norm"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingType-8hrit/MLCPoolingTypeMax": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MLCPoolingTypeMax"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingType-8hrit/MLCPoolingTypeMax",
      "kind": "symbol",
      "role": "symbol",
      "title": "MLCPoolingTypeMax",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingtype-8hrit/mlcpoolingtypemax"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingTypeDebugDescription": {
      "abstract": [
        {
          "text": "A textual description of the pooling type, suitable for debugging.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MLCPoolingTypeDebugDescription"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingTypeDebugDescription",
      "kind": "symbol",
      "role": "symbol",
      "title": "MLCPoolingTypeDebugDescription",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingtypedebugdescription"
    },
    "doc://com.externally.resolved.symbol/c:@T@int32_t": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@int32_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "int32_t",
      "type": "topic",
      "url": "/documentation/kernel/int32_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-Pooling-Layers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingLayer/init(descriptor:)",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor"
      ],
      "title": "Creating Pooling Layers"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingType-8hrit/MLCPoolingTypeMax",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingType-8hrit/MLCPoolingTypeL2Norm",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingType-8hrit/MLCPoolingTypeAverage",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingType-8hrit/MLCPoolingTypeCount",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingTypeDebugDescription"
      ],
      "title": "Enumeration Cases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPoolingLayer~1init(descriptor:)/title",
          "value": "layerWithDescriptor:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPoolingLayer~1init(descriptor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "layerWithDescriptor:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPoolingDescriptor/title",
          "value": "MLCPoolingDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPoolingDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCPoolingDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPoolingDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCPoolingDescriptor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mlcompute/mlcpoolingtype-8hrit"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
