{
  "abstract": [
    {
      "text": "A configuration object you use to create a pooling layer.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mlcompute/documentation/MLCompute"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MLCPoolingDescriptor",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MLCPoolingDescriptor"
      }
    ],
    "modules": [
      {
        "name": "ML Compute"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MLCPoolingDescriptor"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.3",
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MLCPoolingDescriptor"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MLCPoolingDescriptor"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute": {
      "abstract": [
        {
          "text": "Accelerate training and validation of neural networks across the CPU and one or more GPUs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute",
      "kind": "symbol",
      "role": "collection",
      "title": "ML Compute",
      "type": "topic",
      "url": "/documentation/mlcompute"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor": {
      "abstract": [
        {
          "text": "A configuration object you use to create a pooling layer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCPoolingDescriptor"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCPoolingDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MLCPoolingDescriptor",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingdescriptor"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/averagePoolingDescriptorWithKernelSizes:strides:dilationRates:paddingPolicy:paddingSizes:countIncludesPadding:": {
      "abstract": [
        {
          "text": "Creates an average pooling descriptor with the kernel sizes, strides, dilution rates, padding policy and sizes, and zero padding option you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "averagePoolingDescriptorWithKernelSizes:strides:dilationRates:paddingPolicy:paddingSizes:countIncludesPadding:"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/averagePoolingDescriptorWithKernelSizes:strides:dilationRates:paddingPolicy:paddingSizes:countIncludesPadding:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "averagePoolingDescriptorWithKernelSizes:strides:dilationRates:paddingPolicy:paddingSizes:countIncludesPadding:"
        }
      ],
      "role": "symbol",
      "title": "averagePoolingDescriptorWithKernelSizes:strides:dilationRates:paddingPolicy:paddingSizes:countIncludesPadding:",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingdescriptor/averagepoolingdescriptorwithkernelsizes:strides:dilationrates:paddingpolicy:paddingsizes:countincludespadding:"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/averagePoolingDescriptorWithKernelSizes:strides:paddingPolicy:paddingSizes:countIncludesPadding:": {
      "abstract": [
        {
          "text": "Creates an average pooling descriptor with the kernel sizes, strides, padding policy, padding sizes, and zero padding option that you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "averagePoolingDescriptorWithKernelSizes:strides:paddingPolicy:paddingSizes:countIncludesPadding:"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/averagePoolingDescriptorWithKernelSizes:strides:paddingPolicy:paddingSizes:countIncludesPadding:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "averagePoolingDescriptorWithKernelSizes:strides:paddingPolicy:paddingSizes:countIncludesPadding:"
        }
      ],
      "role": "symbol",
      "title": "averagePoolingDescriptorWithKernelSizes:strides:paddingPolicy:paddingSizes:countIncludesPadding:",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingdescriptor/averagepoolingdescriptorwithkernelsizes:strides:paddingpolicy:paddingsizes:countincludespadding:"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/countIncludesPadding": {
      "abstract": [
        {
          "text": "A Boolean that indicates whether you include zero padding in the averaging calculation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "countIncludesPadding"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/countIncludesPadding",
      "kind": "symbol",
      "role": "symbol",
      "title": "countIncludesPadding",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingdescriptor/countincludespadding"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/dilationRateInX": {
      "abstract": [
        {
          "text": "The kernel dilation rate, or stride of elements, in x.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dilationRateInX"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/dilationRateInX",
      "kind": "symbol",
      "role": "symbol",
      "title": "dilationRateInX",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingdescriptor/dilationrateinx"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/dilationRateInY": {
      "abstract": [
        {
          "text": "The kernel dilation rate, or stride of elements, in y.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dilationRateInY"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/dilationRateInY",
      "kind": "symbol",
      "role": "symbol",
      "title": "dilationRateInY",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingdescriptor/dilationrateiny"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/dilationRates": {
      "abstract": [
        {
          "text": "A tuple that contains the dilation rates for y and x.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dilationRates"
        },
        {
          "kind": "text",
          "text": ": (y"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", x"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/dilationRates",
      "kind": "symbol",
      "role": "symbol",
      "title": "dilationRates",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingdescriptor/dilationrates"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/init(type:kernelSizes:strides:dilationRates:paddingPolicy:)": {
      "abstract": [
        {
          "text": "Creates a pooling descriptor with the pooling function type, kernel sizes, strides, dilation rates, and padding policy that you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9MLCompute14MLCPoolingTypeO",
          "text": "MLCPoolingType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "kernelSizes"
        },
        {
          "kind": "text",
          "text": ": (height"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", width"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "), "
        },
        {
          "kind": "externalParam",
          "text": "strides"
        },
        {
          "kind": "text",
          "text": ": (y"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", x"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "), "
        },
        {
          "kind": "externalParam",
          "text": "dilationRates"
        },
        {
          "kind": "text",
          "text": ": (y"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", x"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "), "
        },
        {
          "kind": "externalParam",
          "text": "paddingPolicy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9MLCompute16MLCPaddingPolicyO",
          "text": "MLCPaddingPolicy"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/init(type:kernelSizes:strides:dilationRates:paddingPolicy:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(type:kernelSizes:strides:dilationRates:paddingPolicy:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingdescriptor/init(type:kernelsizes:strides:dilationrates:paddingpolicy:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/kernelHeight": {
      "abstract": [
        {
          "text": "The pooling kernel size in y.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kernelHeight"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/kernelHeight",
      "kind": "symbol",
      "role": "symbol",
      "title": "kernelHeight",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingdescriptor/kernelheight"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/kernelSizes": {
      "abstract": [
        {
          "text": "A tuple that contains the kernel sizes for height and width.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kernelSizes"
        },
        {
          "kind": "text",
          "text": ": (height"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", width"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/kernelSizes",
      "kind": "symbol",
      "role": "symbol",
      "title": "kernelSizes",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingdescriptor/kernelsizes"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/kernelWidth": {
      "abstract": [
        {
          "text": "The pooling kernel size in x.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kernelWidth"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/kernelWidth",
      "kind": "symbol",
      "role": "symbol",
      "title": "kernelWidth",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingdescriptor/kernelwidth"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/l2NormPoolingDescriptorWithKernelSizes:strides:dilationRates:paddingPolicy:paddingSizes:": {
      "abstract": [
        {
          "text": "Creates a descriptor for an L2 norm pooling function with the kernel sizes, strides, dilation rates, padding policy, and padding sizes you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "l2NormPoolingDescriptorWithKernelSizes:strides:dilationRates:paddingPolicy:paddingSizes:"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/l2NormPoolingDescriptorWithKernelSizes:strides:dilationRates:paddingPolicy:paddingSizes:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "l2NormPoolingDescriptorWithKernelSizes:strides:dilationRates:paddingPolicy:paddingSizes:"
        }
      ],
      "role": "symbol",
      "title": "l2NormPoolingDescriptorWithKernelSizes:strides:dilationRates:paddingPolicy:paddingSizes:",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingdescriptor/l2normpoolingdescriptorwithkernelsizes:strides:dilationrates:paddingpolicy:paddingsizes:"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/l2NormPoolingDescriptorWithKernelSizes:strides:paddingPolicy:paddingSizes:": {
      "abstract": [
        {
          "text": "Creates a descriptor for an L2 norm pooling function with the kernel sizes, strides, padding policy, and padding sizes that you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "l2NormPoolingDescriptorWithKernelSizes:strides:paddingPolicy:paddingSizes:"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/l2NormPoolingDescriptorWithKernelSizes:strides:paddingPolicy:paddingSizes:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "l2NormPoolingDescriptorWithKernelSizes:strides:paddingPolicy:paddingSizes:"
        }
      ],
      "role": "symbol",
      "title": "l2NormPoolingDescriptorWithKernelSizes:strides:paddingPolicy:paddingSizes:",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingdescriptor/l2normpoolingdescriptorwithkernelsizes:strides:paddingpolicy:paddingsizes:"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/maxPoolingDescriptorWithKernelSizes:strides:dilationRates:paddingPolicy:paddingSizes:": {
      "abstract": [
        {
          "text": "Creates a descriptor for a max pooling function with the kernel sizes, strides, dilation rates, padding policy, and padding sizes that you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "maxPoolingDescriptorWithKernelSizes:strides:dilationRates:paddingPolicy:paddingSizes:"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/maxPoolingDescriptorWithKernelSizes:strides:dilationRates:paddingPolicy:paddingSizes:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maxPoolingDescriptorWithKernelSizes:strides:dilationRates:paddingPolicy:paddingSizes:"
        }
      ],
      "role": "symbol",
      "title": "maxPoolingDescriptorWithKernelSizes:strides:dilationRates:paddingPolicy:paddingSizes:",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingdescriptor/maxpoolingdescriptorwithkernelsizes:strides:dilationrates:paddingpolicy:paddingsizes:"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/maxPoolingDescriptorWithKernelSizes:strides:paddingPolicy:paddingSizes:": {
      "abstract": [
        {
          "text": "Creates a descriptor for a max pooling function with the kernel sizes, strides, padding policy, and padding sizes that you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "maxPoolingDescriptorWithKernelSizes:strides:paddingPolicy:paddingSizes:"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/maxPoolingDescriptorWithKernelSizes:strides:paddingPolicy:paddingSizes:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maxPoolingDescriptorWithKernelSizes:strides:paddingPolicy:paddingSizes:"
        }
      ],
      "role": "symbol",
      "title": "maxPoolingDescriptorWithKernelSizes:strides:paddingPolicy:paddingSizes:",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingdescriptor/maxpoolingdescriptorwithkernelsizes:strides:paddingpolicy:paddingsizes:"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/paddingPolicy-1e6rg": {
      "abstract": [
        {
          "text": "The padding policy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "paddingPolicy"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/paddingPolicy-1e6rg",
      "kind": "symbol",
      "role": "symbol",
      "title": "paddingPolicy",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingdescriptor/paddingpolicy-1e6rg"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/paddingPolicy-7p8a2": {
      "abstract": [
        {
          "text": "The padding policy.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paddingPolicy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9MLCompute16MLCPaddingPolicyO",
          "text": "MLCPaddingPolicy"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/paddingPolicy-7p8a2",
      "kind": "symbol",
      "role": "symbol",
      "title": "paddingPolicy",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingdescriptor/paddingpolicy-7p8a2"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/paddingSizeInX": {
      "abstract": [
        {
          "text": "The padding size in x, left and right, to use if the padding policy is to use padding size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "paddingSizeInX"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/paddingSizeInX",
      "kind": "symbol",
      "role": "symbol",
      "title": "paddingSizeInX",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingdescriptor/paddingsizeinx"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/paddingSizeInY": {
      "abstract": [
        {
          "text": "The padding size in y, top and bottom, to use if the padding policy is to use padding size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "paddingSizeInY"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/paddingSizeInY",
      "kind": "symbol",
      "role": "symbol",
      "title": "paddingSizeInY",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingdescriptor/paddingsizeiny"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/poolingDescriptorWithType:kernelSize:stride:": {
      "abstract": [
        {
          "text": "Creates a pooling descriptor with the pooling function, kernel size, and stride you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "poolingDescriptorWithType:kernelSize:stride:"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/poolingDescriptorWithType:kernelSize:stride:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "poolingDescriptorWithType:kernelSize:stride:"
        }
      ],
      "role": "symbol",
      "title": "poolingDescriptorWithType:kernelSize:stride:",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingdescriptor/poolingdescriptorwithtype:kernelsize:stride:"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/poolingType-4ni07": {
      "abstract": [
        {
          "text": "The pooling operation type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "poolingType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9MLCompute14MLCPoolingTypeO",
          "text": "MLCPoolingType"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/poolingType-4ni07",
      "kind": "symbol",
      "role": "symbol",
      "title": "poolingType",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingdescriptor/poolingtype-4ni07"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/poolingType-9daku": {
      "abstract": [
        {
          "text": "The pooling operation type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "poolingType"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/poolingType-9daku",
      "kind": "symbol",
      "role": "symbol",
      "title": "poolingType",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingdescriptor/poolingtype-9daku"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/strideInX": {
      "abstract": [
        {
          "text": "The stride of the kernel in x.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "strideInX"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/strideInX",
      "kind": "symbol",
      "role": "symbol",
      "title": "strideInX",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingdescriptor/strideinx"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/strideInY": {
      "abstract": [
        {
          "text": "The stride of the kernel in y.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "strideInY"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/strideInY",
      "kind": "symbol",
      "role": "symbol",
      "title": "strideInY",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingdescriptor/strideiny"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/strides": {
      "abstract": [
        {
          "text": "A tuple that contains the kernel strides for y and x.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "strides"
        },
        {
          "kind": "text",
          "text": ": (y"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", x"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/strides",
      "kind": "symbol",
      "role": "symbol",
      "title": "strides",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingdescriptor/strides"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingLayer/init(descriptor:)": {
      "abstract": [
        {
          "text": "Creates a pooling layer with the descriptor you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "descriptor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCPoolingDescriptor",
          "text": "MLCPoolingDescriptor"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingLayer/init(descriptor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layerWithDescriptor:"
        }
      ],
      "role": "symbol",
      "title": "init(descriptor:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolinglayer/init(descriptor:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingType-8hrit": {
      "abstract": [
        {
          "text": "A pooling function type for a pooling layer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MLCPoolingType"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingType-8hrit",
      "kind": "symbol",
      "role": "symbol",
      "title": "MLCPoolingType",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingtype-8hrit"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingType-wb8j": {
      "abstract": [
        {
          "text": "A pooling function type for a pooling layer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCPoolingType"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingType-wb8j",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCPoolingType"
        }
      ],
      "role": "symbol",
      "title": "MLCPoolingType",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolingtype-wb8j"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-Pooling-Layers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingLayer/init(descriptor:)",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingType-wb8j"
      ],
      "title": "Creating Pooling Layers"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-Pooling-Descriptors",
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/init(type:kernelSizes:strides:dilationRates:paddingPolicy:)"
      ],
      "title": "Creating Pooling Descriptors"
    },
    {
      "anchor": "Inspecting-Pooling-Descriptors",
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/poolingType-4ni07",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/kernelSizes",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/strides",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/dilationRates",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/paddingPolicy-7p8a2"
      ],
      "title": "Inspecting Pooling Descriptors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.3",
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MLCPoolingDescriptor"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCPoolingDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCPoolingDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mlcompute/documentation/MLCompute"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-Pooling-Descriptors",
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/maxPoolingDescriptorWithKernelSizes:strides:paddingPolicy:paddingSizes:",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/maxPoolingDescriptorWithKernelSizes:strides:dilationRates:paddingPolicy:paddingSizes:",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/averagePoolingDescriptorWithKernelSizes:strides:paddingPolicy:paddingSizes:countIncludesPadding:",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/averagePoolingDescriptorWithKernelSizes:strides:dilationRates:paddingPolicy:paddingSizes:countIncludesPadding:",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/l2NormPoolingDescriptorWithKernelSizes:strides:paddingPolicy:paddingSizes:",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/l2NormPoolingDescriptorWithKernelSizes:strides:dilationRates:paddingPolicy:paddingSizes:",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/poolingDescriptorWithType:kernelSize:stride:"
              ],
              "title": "Creating Pooling Descriptors"
            },
            {
              "anchor": "Inspecting-Pooling-Descriptors",
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/poolingType-9daku",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/kernelWidth",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/kernelHeight",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/strideInX",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/strideInY",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/dilationRateInX",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/dilationRateInY",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/paddingPolicy-1e6rg",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/paddingSizeInX",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/paddingSizeInY",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingDescriptor/countIncludesPadding"
              ],
              "title": "Inspecting Pooling Descriptors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-Pooling-Layers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingLayer/init(descriptor:)",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingType-8hrit"
              ],
              "title": "Creating Pooling Layers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MLCPoolingDescriptor"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPoolingDescriptor/title",
          "value": "MLCPoolingDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPoolingDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCPoolingDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPoolingDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCPoolingDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPoolingLayer~1init(descriptor:)/title",
          "value": "layerWithDescriptor:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPoolingLayer~1init(descriptor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "layerWithDescriptor:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mlcompute/mlcpoolingdescriptor"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mlcompute/mlcpoolingdescriptor"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
