{
  "abstract": [
    {
      "text": "Constants that describe a reduction operation type.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mlcompute/documentation/MLCompute"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MLCReductionType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MLCReductionType"
      }
    ],
    "modules": [
      {
        "name": "ML Compute"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MLCReductionType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.3",
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MLCReductionType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MLCReductionType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute": {
      "abstract": [
        {
          "text": "Accelerate training and validation of neural networks across the CPU and one or more GPUs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute",
      "kind": "symbol",
      "role": "collection",
      "title": "ML Compute",
      "type": "topic",
      "url": "/documentation/mlcompute"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionLayer/init(reductionType:dimension:)": {
      "abstract": [
        {
          "text": "Creates a reduction layer using the reduction type and dimension you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "reductionType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCReductionType",
          "text": "MLCReductionType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "dimension"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionLayer/init(reductionType:dimension:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layerWithReductionType:dimension:"
        }
      ],
      "role": "symbol",
      "title": "init(reductionType:dimension:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcreductionlayer/init(reductiontype:dimension:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionLayer/init(reductionType:dimensions:)": {
      "abstract": [
        {
          "text": "Creates a reduction layer using the reduction type and dimensions you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "reductionType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCReductionType",
          "text": "MLCReductionType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "dimensions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionLayer/init(reductionType:dimensions:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(reductionType:dimensions:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcreductionlayer/init(reductiontype:dimensions:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionLayer/layerWithReductionType:dimensions:": {
      "abstract": [
        {
          "text": "Creates a reduction layer using the reduction type and dimensions you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "layerWithReductionType:dimensions:"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionLayer/layerWithReductionType:dimensions:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layerWithReductionType:dimensions:"
        }
      ],
      "role": "symbol",
      "title": "layerWithReductionType:dimensions:",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcreductionlayer/layerwithreductiontype:dimensions:"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionType": {
      "abstract": [
        {
          "text": "Constants that describe a reduction operation type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCReductionType"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCReductionType"
        }
      ],
      "role": "symbol",
      "title": "MLCReductionType",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcreductiontype"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionType/MLCReductionTypeCount": {
      "abstract": [
        {
          "text": "The total number of reduction operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MLCReductionTypeCount"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionType/MLCReductionTypeCount",
      "kind": "symbol",
      "role": "symbol",
      "title": "MLCReductionTypeCount",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcreductiontype/mlcreductiontypecount"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionType/all": {
      "abstract": [
        {
          "text": "A reduction operation that applies to all dimensions.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "all"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionType/all",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCReductionTypeAll"
        }
      ],
      "role": "symbol",
      "title": "MLCReductionType.all",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcreductiontype/all"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionType/any": {
      "abstract": [
        {
          "text": "A reduction operation that applies to any dimension.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "any"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionType/any",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCReductionTypeAny"
        }
      ],
      "role": "symbol",
      "title": "MLCReductionType.any",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcreductiontype/any"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionType/argMax": {
      "abstract": [
        {
          "text": "A reduction operation that applies to the maximum dimension you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "argMax"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionType/argMax",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCReductionTypeArgMax"
        }
      ],
      "role": "symbol",
      "title": "MLCReductionType.argMax",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcreductiontype/argmax"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionType/argMin": {
      "abstract": [
        {
          "text": "A reduction operation that applies to the minimum dimension you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "argMin"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionType/argMin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCReductionTypeArgMin"
        }
      ],
      "role": "symbol",
      "title": "MLCReductionType.argMin",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcreductiontype/argmin"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionType/debugDescription": {
      "abstract": [
        {
          "text": "A textual description of the reduction operation you use for debugging.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "debugDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionType/debugDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCReductionTypeDebugDescription"
        }
      ],
      "role": "symbol",
      "title": "debugDescription",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcreductiontype/debugdescription"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionType/init(rawValue:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcreductiontype/init(rawvalue:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionType/l1Norm": {
      "abstract": [
        {
          "text": "A reduction operation that applies a lasso regularization penalty.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "l1Norm"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionType/l1Norm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCReductionTypeL1Norm"
        }
      ],
      "role": "symbol",
      "title": "MLCReductionType.l1Norm",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcreductiontype/l1norm"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionType/max": {
      "abstract": [
        {
          "text": "A reduction operation that applies to the maximum dimension.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "max"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionType/max",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCReductionTypeMax"
        }
      ],
      "role": "symbol",
      "title": "MLCReductionType.max",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcreductiontype/max"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionType/mean": {
      "abstract": [
        {
          "text": "A reduction operation that applies to the mean of the dimensions.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mean"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionType/mean",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCReductionTypeMean"
        }
      ],
      "role": "symbol",
      "title": "MLCReductionType.mean",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcreductiontype/mean"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionType/min": {
      "abstract": [
        {
          "text": "A reduction operation that applies to the minimum dimension.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "min"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionType/min",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCReductionTypeMin"
        }
      ],
      "role": "symbol",
      "title": "MLCReductionType.min",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcreductiontype/min"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionType/none": {
      "abstract": [
        {
          "text": "A reduction operation that applies no reduction.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionType/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCReductionTypeNone"
        }
      ],
      "role": "symbol",
      "title": "MLCReductionType.none",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcreductiontype/none"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionType/sum": {
      "abstract": [
        {
          "text": "A reduction operation that applies to the sum of the dimensions.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sum"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionType/sum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCReductionTypeSum"
        }
      ],
      "role": "symbol",
      "title": "MLCReductionType.sum",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcreductiontype/sum"
    },
    "doc://com.externally.resolved.symbol/c:@T@int32_t": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@int32_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "int32_t",
      "type": "topic",
      "url": "/documentation/kernel/int32_t"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-Reduction-Layers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionLayer/init(reductionType:dimension:)",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionLayer/init(reductionType:dimensions:)"
      ],
      "title": "Creating Reduction Layers"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionType/all",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionType/any",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionType/argMax",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionType/argMin",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionType/max",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionType/mean",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionType/min",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionType/none",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionType/sum",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionType/l1Norm",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionType/debugDescription"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MLCReductionType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCReductionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCReductionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mlcompute/documentation/MLCompute"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionType/all",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionType/any",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionType/argMax",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionType/argMin",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionType/max",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionType/mean",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionType/min",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionType/none",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionType/sum",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionType/l1Norm",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionType/MLCReductionTypeCount",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionType/debugDescription"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-Reduction-Layers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionLayer/init(reductionType:dimension:)",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCReductionLayer/layerWithReductionType:dimensions:"
              ],
              "title": "Creating Reduction Layers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MLCReductionType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@int32_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@int32_t",
                    "text": "int32_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "add",
          "path": "/deprecationSummary",
          "value": []
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCReductionType~1argMax/title",
          "value": "MLCReductionTypeArgMax"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCReductionType~1argMax/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCReductionTypeArgMax"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCReductionType~1min/title",
          "value": "MLCReductionTypeMin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCReductionType~1min/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCReductionTypeMin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCReductionType~1sum/title",
          "value": "MLCReductionTypeSum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCReductionType~1sum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCReductionTypeSum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCReductionType~1argMin/title",
          "value": "MLCReductionTypeArgMin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCReductionType~1argMin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCReductionTypeArgMin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCReductionType~1l1Norm/title",
          "value": "MLCReductionTypeL1Norm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCReductionType~1l1Norm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCReductionTypeL1Norm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCReductionType~1any/title",
          "value": "MLCReductionTypeAny"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCReductionType~1any/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCReductionTypeAny"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCReductionType/title",
          "value": "MLCReductionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCReductionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCReductionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCReductionType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCReductionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCReductionType~1debugDescription/title",
          "value": "MLCReductionTypeDebugDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCReductionType~1debugDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCReductionTypeDebugDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCReductionType~1all/title",
          "value": "MLCReductionTypeAll"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCReductionType~1all/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCReductionTypeAll"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCReductionType~1none/title",
          "value": "MLCReductionTypeNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCReductionType~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCReductionTypeNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCReductionType~1mean/title",
          "value": "MLCReductionTypeMean"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCReductionType~1mean/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCReductionTypeMean"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCReductionLayer~1init(reductionType:dimension:)/title",
          "value": "layerWithReductionType:dimension:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCReductionLayer~1init(reductionType:dimension:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "layerWithReductionType:dimension:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCReductionType~1max/title",
          "value": "MLCReductionTypeMax"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCReductionType~1max/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCReductionTypeMax"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mlcompute/mlcreductiontype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mlcompute/mlcreductiontype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
