{
  "abstract": [
    {
      "text": "An encapsulation of the memory that tensor data uses.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mlcompute/documentation/MLCompute"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorData"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MLCTensorData",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MLCTensorData"
      }
    ],
    "modules": [
      {
        "name": "ML Compute"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MLCTensorData"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.3",
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MLCTensorData"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MLCTensorData"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "A tensor data instance doesn’t take ownership of the ",
                  "type": "text"
                },
                {
                  "code": "bytes",
                  "type": "codeVoice"
                },
                {
                  "text": " pointer and therefore won’t free it upon deallocation.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute": {
      "abstract": [
        {
          "text": "Accelerate training and validation of neural networks across the CPU and one or more GPUs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute",
      "kind": "symbol",
      "role": "collection",
      "title": "ML Compute",
      "type": "topic",
      "url": "/documentation/mlcompute"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCDataType": {
      "abstract": [
        {
          "text": "A tensor data type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCDataType"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCDataType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCDataType"
        }
      ],
      "role": "symbol",
      "title": "MLCDataType",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcdatatype"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCRandomInitializerType": {
      "abstract": [
        {
          "text": "An initializer type you use to create a tensor with random data.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCRandomInitializerType"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCRandomInitializerType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCRandomInitializerType"
        }
      ],
      "role": "symbol",
      "title": "MLCRandomInitializerType",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcrandominitializertype"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(descriptor:)": {
      "abstract": [
        {
          "text": "Creates a tensor without data, using the descriptor you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "descriptor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCTensorDescriptor",
          "text": "MLCTensorDescriptor"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(descriptor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tensorWithDescriptor:"
        }
      ],
      "role": "symbol",
      "title": "init(descriptor:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlctensor/init(descriptor:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(descriptor:data:)": {
      "abstract": [
        {
          "text": "Creates a tensor with the descriptor and data you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "descriptor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCTensorDescriptor",
          "text": "MLCTensorDescriptor"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "data"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCTensorData",
          "text": "MLCTensorData"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(descriptor:data:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tensorWithDescriptor:data:"
        }
      ],
      "role": "symbol",
      "title": "init(descriptor:data:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlctensor/init(descriptor:data:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(descriptor:fillWithData:)": {
      "abstract": [
        {
          "text": "Creates a tensor with the descriptor and scalar value you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "descriptor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCTensorDescriptor",
          "text": "MLCTensorDescriptor"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "fillWithData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(descriptor:fillWithData:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tensorWithDescriptor:fillWithData:"
        }
      ],
      "role": "symbol",
      "title": "init(descriptor:fillWithData:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlctensor/init(descriptor:fillwithdata:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(descriptor:randomInitializerType:)": {
      "abstract": [
        {
          "text": "Creates a tensor with the descriptor and random initializer type you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "descriptor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCTensorDescriptor",
          "text": "MLCTensorDescriptor"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "randomInitializerType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCRandomInitializerType",
          "text": "MLCRandomInitializerType"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(descriptor:randomInitializerType:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tensorWithDescriptor:randomInitializerType:"
        }
      ],
      "role": "symbol",
      "title": "init(descriptor:randomInitializerType:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlctensor/init(descriptor:randominitializertype:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorData": {
      "abstract": [
        {
          "text": "An encapsulation of the memory that tensor data uses.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCTensorData"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCTensorData"
        }
      ],
      "role": "symbol",
      "title": "MLCTensorData",
      "type": "topic",
      "url": "/documentation/mlcompute/mlctensordata"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorData/bytes": {
      "abstract": [
        {
          "text": "A buffer that conains data.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bytes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorData/bytes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bytes"
        }
      ],
      "role": "symbol",
      "title": "bytes",
      "type": "topic",
      "url": "/documentation/mlcompute/mlctensordata/bytes"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorData/init(bytesNoCopy:length:)": {
      "abstract": [
        {
          "text": "Creates a tensor data instance with the buffer of data and length of bytes you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "bytesNoCopy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "length"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorData/init(bytesNoCopy:length:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dataWithBytesNoCopy:length:"
        }
      ],
      "role": "symbol",
      "title": "init(bytesNoCopy:length:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlctensordata/init(bytesnocopy:length:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorData/init(bytesNoCopy:length:deallocator:)": {
      "abstract": [
        {
          "text": "Creates a tensor data instance with a data buffer, byte length, and custom deallocator closure you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "bytesNoCopy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "length"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "deallocator"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorData/init(bytesNoCopy:length:deallocator:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dataWithBytesNoCopy:length:deallocator:"
        }
      ],
      "role": "symbol",
      "title": "init(bytesNoCopy:length:deallocator:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlctensordata/init(bytesnocopy:length:deallocator:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorData/init(immutableBytesNoCopy:length:)": {
      "abstract": [
        {
          "text": "Creates a tensor data instance with the buffer of immutable data and length of bytes you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "immutableBytesNoCopy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "length"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorData/init(immutableBytesNoCopy:length:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dataWithImmutableBytesNoCopy:length:"
        }
      ],
      "role": "symbol",
      "title": "init(immutableBytesNoCopy:length:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlctensordata/init(immutablebytesnocopy:length:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorData/length": {
      "abstract": [
        {
          "text": "The number of bytes you choose to hold for this tensor data instance.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "length"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorData/length",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "length"
        }
      ],
      "role": "symbol",
      "title": "length",
      "type": "topic",
      "url": "/documentation/mlcompute/mlctensordata/length"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorDescriptor": {
      "abstract": [
        {
          "text": "A configuration object you use to create a tensor.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCTensorDescriptor"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCTensorDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MLCTensorDescriptor",
      "type": "topic",
      "url": "/documentation/mlcompute/mlctensordescriptor"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-Tensors-with-Descriptors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(descriptor:)",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(descriptor:data:)",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(descriptor:fillWithData:)",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(descriptor:randomInitializerType:)",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorDescriptor",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCDataType",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCRandomInitializerType"
      ],
      "title": "Creating Tensors with Descriptors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-Tensor-Data",
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorData/init(bytesNoCopy:length:)",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorData/init(bytesNoCopy:length:deallocator:)",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorData/init(immutableBytesNoCopy:length:)"
      ],
      "title": "Creating Tensor Data"
    },
    {
      "anchor": "Inspecting-Tensor-Data",
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorData/bytes",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorData/length"
      ],
      "title": "Inspecting Tensor Data"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.3",
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MLCTensorData"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCTensorData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCTensorData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mlcompute/documentation/MLCompute"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-Tensor-Data",
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorData/init(bytesNoCopy:length:)",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorData/init(bytesNoCopy:length:deallocator:)",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorData/init(immutableBytesNoCopy:length:)"
              ],
              "title": "Creating Tensor Data"
            },
            {
              "anchor": "Inspecting-Tensor-Data",
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorData/bytes",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorData/length"
              ],
              "title": "Inspecting Tensor Data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-Tensors-with-Descriptors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(descriptor:)",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(descriptor:data:)",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(descriptor:fillWithData:)",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor/init(descriptor:randomInitializerType:)",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorDescriptor",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCDataType",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCRandomInitializerType"
              ],
              "title": "Creating Tensors with Descriptors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MLCTensorData"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensorData~1bytes/title",
          "value": "bytes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensorData~1bytes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bytes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensorData~1init(bytesNoCopy:length:deallocator:)/title",
          "value": "dataWithBytesNoCopy:length:deallocator:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensorData~1init(bytesNoCopy:length:deallocator:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "dataWithBytesNoCopy:length:deallocator:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCRandomInitializerType/title",
          "value": "MLCRandomInitializerType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCRandomInitializerType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCRandomInitializerType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCRandomInitializerType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCRandomInitializerType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCDataType/title",
          "value": "MLCDataType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCDataType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCDataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCDataType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCDataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensorData~1init(bytesNoCopy:length:)/title",
          "value": "dataWithBytesNoCopy:length:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensorData~1init(bytesNoCopy:length:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "dataWithBytesNoCopy:length:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensorData/title",
          "value": "MLCTensorData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensorData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCTensorData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensorData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCTensorData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensor~1init(descriptor:)/title",
          "value": "tensorWithDescriptor:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensor~1init(descriptor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "tensorWithDescriptor:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensor~1init(descriptor:data:)/title",
          "value": "tensorWithDescriptor:data:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensor~1init(descriptor:data:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "tensorWithDescriptor:data:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensorDescriptor/title",
          "value": "MLCTensorDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensorDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCTensorDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensorDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCTensorDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensorData~1init(immutableBytesNoCopy:length:)/title",
          "value": "dataWithImmutableBytesNoCopy:length:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensorData~1init(immutableBytesNoCopy:length:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "dataWithImmutableBytesNoCopy:length:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensorData~1length/title",
          "value": "length"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensorData~1length/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "length"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensor~1init(descriptor:fillWithData:)/title",
          "value": "tensorWithDescriptor:fillWithData:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensor~1init(descriptor:fillWithData:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "tensorWithDescriptor:fillWithData:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensor~1init(descriptor:randomInitializerType:)/title",
          "value": "tensorWithDescriptor:randomInitializerType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensor~1init(descriptor:randomInitializerType:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "tensorWithDescriptor:randomInitializerType:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mlcompute/mlctensordata"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mlcompute/mlctensordata"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
