{
  "abstract": [
    {
      "text": "A layer that applies upsampling with the shape you specify.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mlcompute/documentation/MLCompute"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mlcompute/documentation/MLCompute/MLCUpsampleLayer"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MLCUpsampleLayer",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MLCUpsampleLayer"
      }
    ],
    "modules": [
      {
        "name": "ML Compute"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MLCUpsampleLayer"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.3",
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MLCUpsampleLayer"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MLCUpsampleLayer"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute": {
      "abstract": [
        {
          "text": "Accelerate training and validation of neural networks across the CPU and one or more GPUs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute",
      "kind": "symbol",
      "role": "collection",
      "title": "ML Compute",
      "type": "topic",
      "url": "/documentation/mlcompute"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCConvolutionLayer": {
      "abstract": [
        {
          "text": "A layer that applies a convolution over a signal.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCConvolutionLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCConvolutionLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCConvolutionLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCConvolutionLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcconvolutionlayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCEmbeddingLayer": {
      "abstract": [
        {
          "text": "A layer that stores a word embedding.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCEmbeddingLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCEmbeddingLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCEmbeddingLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCEmbeddingLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcembeddinglayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer": {
      "abstract": [
        {
          "text": "A layer that represents long short-term memory (LSTM) networks.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCLSTMLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCLSTMLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCLSTMLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclstmlayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayer": {
      "abstract": [
        {
          "text": "The base class for all framework layers.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingLayer": {
      "abstract": [
        {
          "text": "A layer that summarizes the average presence of a feature.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCPoolingLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCPoolingLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCPoolingLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcpoolinglayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCSampleMode": {
      "abstract": [
        {
          "text": "A sampling mode for an upsample layer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCSampleMode"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCSampleMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCSampleMode"
        }
      ],
      "role": "symbol",
      "title": "MLCSampleMode",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcsamplemode"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCUpsampleLayer": {
      "abstract": [
        {
          "text": "A layer that applies upsampling with the shape you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCUpsampleLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCUpsampleLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCUpsampleLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCUpsampleLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcupsamplelayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCUpsampleLayer/alignsCorners": {
      "abstract": [
        {
          "text": "A Boolean that indicates whether the layer aligns the corner pixels of the input and output tensors.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alignsCorners"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCUpsampleLayer/alignsCorners",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "alignsCorners"
        }
      ],
      "role": "symbol",
      "title": "alignsCorners",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcupsamplelayer/alignscorners"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCUpsampleLayer/init(shape:)": {
      "abstract": [
        {
          "text": "Creates an upsample layer with the shape you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "shape"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCUpsampleLayer/init(shape:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(shape:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcupsamplelayer/init(shape:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCUpsampleLayer/init(shape:sampleMode:alignsCorners:)": {
      "abstract": [
        {
          "text": "Creates an upsample layer with the shape, upsampling algorithm, and corner alignment option you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "shape"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "sampleMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCSampleMode",
          "text": "MLCSampleMode"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "alignsCorners"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCUpsampleLayer/init(shape:sampleMode:alignsCorners:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(shape:sampleMode:alignsCorners:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcupsamplelayer/init(shape:samplemode:alignscorners:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCUpsampleLayer/layerWithShape:": {
      "abstract": [
        {
          "text": "Creates an upsample layer with the shape you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "layerWithShape:"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCUpsampleLayer/layerWithShape:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layerWithShape:"
        }
      ],
      "role": "symbol",
      "title": "layerWithShape:",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcupsamplelayer/layerwithshape:"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCUpsampleLayer/layerWithShape:sampleMode:alignsCorners:": {
      "abstract": [
        {
          "text": "Creates an upsample layer with the shape, upsampling algorithm, and corner alignement option you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "layerWithShape:sampleMode:alignsCorners:"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCUpsampleLayer/layerWithShape:sampleMode:alignsCorners:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layerWithShape:sampleMode:alignsCorners:"
        }
      ],
      "role": "symbol",
      "title": "layerWithShape:sampleMode:alignsCorners:",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcupsamplelayer/layerwithshape:samplemode:alignscorners:"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCUpsampleLayer/sampleMode": {
      "abstract": [
        {
          "text": "The upsampling algorithm type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sampleMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCSampleMode",
          "text": "MLCSampleMode"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCUpsampleLayer/sampleMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sampleMode"
        }
      ],
      "role": "symbol",
      "title": "sampleMode",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcupsamplelayer/samplemode"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCUpsampleLayer/shape-61n1u": {
      "abstract": [
        {
          "text": "An array that contains the dimensions of the result tensor.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shape"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCUpsampleLayer/shape-61n1u",
      "kind": "symbol",
      "role": "symbol",
      "title": "shape",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcupsamplelayer/shape-61n1u"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCUpsampleLayer/shape-7j6sf": {
      "abstract": [
        {
          "text": "An array that contains the dimensions of the result tensor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "shape"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCUpsampleLayer/shape-7j6sf",
      "kind": "symbol",
      "role": "symbol",
      "title": "shape",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcupsamplelayer/shape-7j6sf"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayer"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Convolution-and-Recurrent-Layers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCConvolutionLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingLayer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCEmbeddingLayer"
      ],
      "title": "Convolution and Recurrent Layers"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-Upsample-Layers",
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCUpsampleLayer/init(shape:)",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCUpsampleLayer/init(shape:sampleMode:alignsCorners:)",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCSampleMode"
      ],
      "title": "Creating Upsample Layers"
    },
    {
      "anchor": "Inspecting-Upsample-Layers",
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCUpsampleLayer/shape-61n1u",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCUpsampleLayer/sampleMode",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCUpsampleLayer/alignsCorners"
      ],
      "title": "Inspecting Upsample Layers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.3",
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MLCUpsampleLayer"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCUpsampleLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCUpsampleLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mlcompute/documentation/MLCompute"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-Upsample-Layers",
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCUpsampleLayer/layerWithShape:",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCUpsampleLayer/layerWithShape:sampleMode:alignsCorners:",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCSampleMode"
              ],
              "title": "Creating Upsample Layers"
            },
            {
              "anchor": "Inspecting-Upsample-Layers",
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCUpsampleLayer/shape-7j6sf",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCUpsampleLayer/sampleMode",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCUpsampleLayer/alignsCorners"
              ],
              "title": "Inspecting Upsample Layers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayer"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Convolution-and-Recurrent-Layers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCConvolutionLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCPoolingLayer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCEmbeddingLayer"
              ],
              "title": "Convolution and Recurrent Layers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MLCUpsampleLayer"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLayer",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MLCLayer",
                    "text": "MLCLayer"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCUpsampleLayer/title",
          "value": "MLCUpsampleLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCUpsampleLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCUpsampleLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCUpsampleLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCUpsampleLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPoolingLayer/title",
          "value": "MLCPoolingLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPoolingLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCPoolingLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPoolingLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCPoolingLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCEmbeddingLayer/title",
          "value": "MLCEmbeddingLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCEmbeddingLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCEmbeddingLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCEmbeddingLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCEmbeddingLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMLayer/title",
          "value": "MLCLSTMLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLSTMLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLSTMLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLayer/title",
          "value": "MLCLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCUpsampleLayer~1alignsCorners/title",
          "value": "alignsCorners"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCUpsampleLayer~1alignsCorners/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "alignsCorners"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCSampleMode/title",
          "value": "MLCSampleMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCSampleMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCSampleMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCSampleMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCSampleMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCUpsampleLayer~1sampleMode/title",
          "value": "sampleMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCUpsampleLayer~1sampleMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sampleMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCConvolutionLayer/title",
          "value": "MLCConvolutionLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCConvolutionLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCConvolutionLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCConvolutionLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCConvolutionLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mlcompute/mlcupsamplelayer"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mlcompute/mlcupsamplelayer"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
