{
  "abstract": [
    {
      "text": "The configuration object you use to create the YOLO loss layer.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mlcompute/documentation/MLCompute"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MLCYOLOLossDescriptor",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MLCYOLOLossDescriptor"
      }
    ],
    "modules": [
      {
        "name": "ML Compute"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MLCYOLOLossDescriptor"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.3",
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MLCYOLOLossDescriptor"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MLCYOLOLossDescriptor"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute": {
      "abstract": [
        {
          "text": "Accelerate training and validation of neural networks across the CPU and one or more GPUs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute",
      "kind": "symbol",
      "role": "collection",
      "title": "ML Compute",
      "type": "topic",
      "url": "/documentation/mlcompute"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor": {
      "abstract": [
        {
          "text": "The configuration object you use to create the YOLO loss layer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCYOLOLossDescriptor"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCYOLOLossDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MLCYOLOLossDescriptor",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcyololossdescriptor"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/anchorBoxCount": {
      "abstract": [
        {
          "text": "The number of anchor boxes you use to detect an object in each grid cell.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "anchorBoxCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/anchorBoxCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "anchorBoxCount"
        }
      ],
      "role": "symbol",
      "title": "anchorBoxCount",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcyololossdescriptor/anchorboxcount"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/anchorBoxes": {
      "abstract": [
        {
          "text": "Data that contains the width and height for all the anchor boxes.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "anchorBoxes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/anchorBoxes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "anchorBoxes"
        }
      ],
      "role": "symbol",
      "title": "anchorBoxes",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcyololossdescriptor/anchorboxes"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/init(anchorBoxes:anchorBoxCount:)": {
      "abstract": [
        {
          "text": "Creates a YOLO loss filter descriptor with the anchor box data and number of anchor boxes you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "anchorBoxes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "anchorBoxCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/init(anchorBoxes:anchorBoxCount:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "descriptorWithAnchorBoxes:anchorBoxCount:"
        }
      ],
      "role": "symbol",
      "title": "init(anchorBoxes:anchorBoxCount:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcyololossdescriptor/init(anchorboxes:anchorboxcount:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/maximumIOUForObjectAbsence": {
      "abstract": [
        {
          "text": "The negative intersection over union (IOU).",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumIOUForObjectAbsence"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/maximumIOUForObjectAbsence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maximumIOUForObjectAbsence"
        }
      ],
      "role": "symbol",
      "title": "maximumIOUForObjectAbsence",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcyololossdescriptor/maximumiouforobjectabsence"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/minimumIOUForObjectPresence": {
      "abstract": [
        {
          "text": "The positive intersection over union (IOU).",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minimumIOUForObjectPresence"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/minimumIOUForObjectPresence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "minimumIOUForObjectPresence"
        }
      ],
      "role": "symbol",
      "title": "minimumIOUForObjectPresence",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcyololossdescriptor/minimumiouforobjectpresence"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/scaleClassLoss": {
      "abstract": [
        {
          "text": "The scale factor you use for loss when there are no object classes, and for loss gradient.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaleClassLoss"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/scaleClassLoss",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scaleClassLoss"
        }
      ],
      "role": "symbol",
      "title": "scaleClassLoss",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcyololossdescriptor/scaleclassloss"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/scaleNoObjectConfidenceLoss": {
      "abstract": [
        {
          "text": "The scale factor you use for no object confidence loss and loss gradient.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaleNoObjectConfidenceLoss"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/scaleNoObjectConfidenceLoss",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scaleNoObjectConfidenceLoss"
        }
      ],
      "role": "symbol",
      "title": "scaleNoObjectConfidenceLoss",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcyololossdescriptor/scalenoobjectconfidenceloss"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/scaleObjectConfidenceLoss": {
      "abstract": [
        {
          "text": "The scale factor you use for object confidence loss and loss gradient.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaleObjectConfidenceLoss"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/scaleObjectConfidenceLoss",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scaleObjectConfidenceLoss"
        }
      ],
      "role": "symbol",
      "title": "scaleObjectConfidenceLoss",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcyololossdescriptor/scaleobjectconfidenceloss"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/scaleSpatialPositionLoss": {
      "abstract": [
        {
          "text": "The scale factor you use for spatial position loss and loss gradient.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaleSpatialPositionLoss"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/scaleSpatialPositionLoss",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scaleSpatialPositionLoss"
        }
      ],
      "role": "symbol",
      "title": "scaleSpatialPositionLoss",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcyololossdescriptor/scalespatialpositionloss"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/scaleSpatialSizeLoss": {
      "abstract": [
        {
          "text": "The scale factor you use for spatial size loss and loss gradient.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaleSpatialSizeLoss"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/scaleSpatialSizeLoss",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scaleSpatialSizeLoss"
        }
      ],
      "role": "symbol",
      "title": "scaleSpatialSizeLoss",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcyololossdescriptor/scalespatialsizeloss"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/shouldRescore": {
      "abstract": [
        {
          "text": "A Boolean that indicates whether the layer scales the object confidence loss by the intersection over union (IOU) overlap.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shouldRescore"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/shouldRescore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shouldRescore"
        }
      ],
      "role": "symbol",
      "title": "shouldRescore",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcyololossdescriptor/shouldrescore"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossLayer/init(descriptor:)": {
      "abstract": [
        {
          "text": "Creates a YOLO loss layer with the descriptor you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "descriptor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCYOLOLossDescriptor",
          "text": "MLCYOLOLossDescriptor"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossLayer/init(descriptor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layerWithDescriptor:"
        }
      ],
      "role": "symbol",
      "title": "init(descriptor:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcyololosslayer/init(descriptor:)"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-YOLO-Loss-Layers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossLayer/init(descriptor:)"
      ],
      "title": "Creating YOLO Loss Layers"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-YOLO-Loss-Descriptors",
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/init(anchorBoxes:anchorBoxCount:)"
      ],
      "title": "Creating YOLO Loss Descriptors"
    },
    {
      "anchor": "Inspecting-YOLO-Loss-Descriptors",
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/anchorBoxCount",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/anchorBoxes",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/maximumIOUForObjectAbsence",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/minimumIOUForObjectPresence",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/scaleClassLoss",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/scaleObjectConfidenceLoss",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/scaleNoObjectConfidenceLoss",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/scaleSpatialPositionLoss",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/scaleSpatialSizeLoss",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/shouldRescore"
      ],
      "title": "Inspecting YOLO Loss Descriptors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.3",
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MLCYOLOLossDescriptor"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCYOLOLossDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCYOLOLossDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mlcompute/documentation/MLCompute"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-YOLO-Loss-Descriptors",
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/init(anchorBoxes:anchorBoxCount:)"
              ],
              "title": "Creating YOLO Loss Descriptors"
            },
            {
              "anchor": "Inspecting-YOLO-Loss-Descriptors",
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/anchorBoxCount",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/anchorBoxes",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/maximumIOUForObjectAbsence",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/minimumIOUForObjectPresence",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/scaleClassLoss",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/scaleObjectConfidenceLoss",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/scaleNoObjectConfidenceLoss",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/scaleSpatialPositionLoss",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/scaleSpatialSizeLoss",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/shouldRescore"
              ],
              "title": "Inspecting YOLO Loss Descriptors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-YOLO-Loss-Layers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossLayer/init(descriptor:)"
              ],
              "title": "Creating YOLO Loss Layers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MLCYOLOLossDescriptor"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossDescriptor~1scaleSpatialSizeLoss/title",
          "value": "scaleSpatialSizeLoss"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossDescriptor~1scaleSpatialSizeLoss/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scaleSpatialSizeLoss"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossDescriptor~1scaleClassLoss/title",
          "value": "scaleClassLoss"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossDescriptor~1scaleClassLoss/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scaleClassLoss"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossDescriptor~1init(anchorBoxes:anchorBoxCount:)/title",
          "value": "descriptorWithAnchorBoxes:anchorBoxCount:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossDescriptor~1init(anchorBoxes:anchorBoxCount:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "descriptorWithAnchorBoxes:anchorBoxCount:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossDescriptor~1minimumIOUForObjectPresence/title",
          "value": "minimumIOUForObjectPresence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossDescriptor~1minimumIOUForObjectPresence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "minimumIOUForObjectPresence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossDescriptor~1anchorBoxes/title",
          "value": "anchorBoxes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossDescriptor~1anchorBoxes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "anchorBoxes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossDescriptor~1scaleObjectConfidenceLoss/title",
          "value": "scaleObjectConfidenceLoss"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossDescriptor~1scaleObjectConfidenceLoss/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scaleObjectConfidenceLoss"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossDescriptor~1scaleSpatialPositionLoss/title",
          "value": "scaleSpatialPositionLoss"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossDescriptor~1scaleSpatialPositionLoss/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scaleSpatialPositionLoss"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossLayer~1init(descriptor:)/title",
          "value": "layerWithDescriptor:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossLayer~1init(descriptor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "layerWithDescriptor:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossDescriptor~1anchorBoxCount/title",
          "value": "anchorBoxCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossDescriptor~1anchorBoxCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "anchorBoxCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossDescriptor~1shouldRescore/title",
          "value": "shouldRescore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossDescriptor~1shouldRescore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "shouldRescore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossDescriptor~1scaleNoObjectConfidenceLoss/title",
          "value": "scaleNoObjectConfidenceLoss"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossDescriptor~1scaleNoObjectConfidenceLoss/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scaleNoObjectConfidenceLoss"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossDescriptor/title",
          "value": "MLCYOLOLossDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCYOLOLossDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCYOLOLossDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossDescriptor~1maximumIOUForObjectAbsence/title",
          "value": "maximumIOUForObjectAbsence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossDescriptor~1maximumIOUForObjectAbsence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maximumIOUForObjectAbsence"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mlcompute/mlcyololossdescriptor"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mlcompute/mlcyololossdescriptor"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
