{
  "abstract": [
    {
      "text": "Create an optimizer to use with the training graph.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mlcompute/documentation/MLCompute",
        "doc://com.apple.mlcompute/documentation/MLCompute/training-and-validation",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCTrainingGraph"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mlcompute/documentation/MLCompute/optimizers"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "ML Compute"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Optimizers"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute": {
      "abstract": [
        {
          "text": "Accelerate training and validation of neural networks across the CPU and one or more GPUs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute",
      "kind": "symbol",
      "role": "collection",
      "title": "ML Compute",
      "type": "topic",
      "url": "/documentation/mlcompute"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCAdamOptimizer": {
      "abstract": [
        {
          "text": "An optimizer that represents the adaptive moment estimation algorithm.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCAdamOptimizer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCAdamOptimizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCAdamOptimizer"
        }
      ],
      "role": "symbol",
      "title": "MLCAdamOptimizer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcadamoptimizer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCAdamWOptimizer": {
      "abstract": [
        {
          "text": "An optimizer that represents the Adam algorithm with weight decay.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCAdamWOptimizer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCAdamWOptimizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCAdamWOptimizer"
        }
      ],
      "role": "symbol",
      "title": "MLCAdamWOptimizer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcadamwoptimizer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer": {
      "abstract": [
        {
          "text": "The base class for all framework optimizers.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCOptimizer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCOptimizer"
        }
      ],
      "role": "symbol",
      "title": "MLCOptimizer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcoptimizer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizerDescriptor": {
      "abstract": [
        {
          "text": "A configuration object you use to create an optimizer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCOptimizerDescriptor"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizerDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCOptimizerDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MLCOptimizerDescriptor",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcoptimizerdescriptor"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCRMSPropOptimizer": {
      "abstract": [
        {
          "text": "An optimizer that represents the root mean square propagation algorithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCRMSPropOptimizer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCRMSPropOptimizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCRMSPropOptimizer"
        }
      ],
      "role": "symbol",
      "title": "MLCRMSPropOptimizer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcrmspropoptimizer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCRegularizationType": {
      "abstract": [
        {
          "text": "A regularization function to use with an optimizer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCRegularizationType"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCRegularizationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCRegularizationType"
        }
      ],
      "role": "symbol",
      "title": "MLCRegularizationType",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcregularizationtype"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCSGDOptimizer": {
      "abstract": [
        {
          "text": "An optimizer that represents the stochastic gradient decent algorithm.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCSGDOptimizer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCSGDOptimizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCSGDOptimizer"
        }
      ],
      "role": "symbol",
      "title": "MLCSGDOptimizer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcsgdoptimizer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorParameter": {
      "abstract": [
        {
          "text": "A tensor parameter object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCTensorParameter"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorParameter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCTensorParameter"
        }
      ],
      "role": "symbol",
      "title": "MLCTensorParameter",
      "type": "topic",
      "url": "/documentation/mlcompute/mlctensorparameter"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCTrainingGraph": {
      "abstract": [
        {
          "text": "A training graph that you create from one or more graph objects plus additional layers you add directly to the training graph.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCTrainingGraph"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTrainingGraph",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCTrainingGraph"
        }
      ],
      "role": "symbol",
      "title": "MLCTrainingGraph",
      "type": "topic",
      "url": "/documentation/mlcompute/mlctraininggraph"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCTrainingGraph/init(graphObjects:lossLayer:optimizer:)": {
      "abstract": [
        {
          "text": "Creates a training graph with the layers from the graph objects, loss layer, and optimizer you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "graphObjects"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCGraph",
          "text": "MLCGraph"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "lossLayer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCLayer",
          "text": "MLCLayer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "optimizer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCOptimizer",
          "text": "MLCOptimizer"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTrainingGraph/init(graphObjects:lossLayer:optimizer:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "graphWithGraphObjects:lossLayer:optimizer:"
        }
      ],
      "role": "symbol",
      "title": "init(graphObjects:lossLayer:optimizer:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlctraininggraph/init(graphobjects:losslayer:optimizer:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/training-and-validation": {
      "abstract": [
        {
          "text": "Create, train, and validate a graph to produce acceptable prediction results.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/training-and-validation",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Training and Validation",
      "type": "topic",
      "url": "/documentation/mlcompute/training-and-validation"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-Training-Graphs",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCTrainingGraph/init(graphObjects:lossLayer:optimizer:)",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorParameter"
      ],
      "title": "Creating Training Graphs"
    }
  ],
  "topicSections": [
    {
      "anchor": "Optimizer-Types",
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCSGDOptimizer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCRMSPropOptimizer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCAdamOptimizer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCAdamWOptimizer",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer"
      ],
      "title": "Optimizer Types"
    },
    {
      "anchor": "Supporting-Types",
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizerDescriptor",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCRegularizationType"
      ],
      "title": "Supporting Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Optimizer-Types",
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCSGDOptimizer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCRMSPropOptimizer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCAdamOptimizer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCAdamWOptimizer",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizer"
              ],
              "title": "Optimizer Types"
            },
            {
              "anchor": "Supporting-Types",
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizerDescriptor",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCRegularizationType"
              ],
              "title": "Supporting Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-Training-Graphs",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCTrainingGraph/init(graphObjects:lossLayer:optimizer:)",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorParameter"
              ],
              "title": "Creating Training Graphs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCRegularizationType/title",
          "value": "MLCRegularizationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCRegularizationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCRegularizationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCRegularizationType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCRegularizationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTrainingGraph/title",
          "value": "MLCTrainingGraph"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTrainingGraph/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCTrainingGraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTrainingGraph/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCTrainingGraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCAdamOptimizer/title",
          "value": "MLCAdamOptimizer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCAdamOptimizer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCAdamOptimizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCAdamOptimizer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCAdamOptimizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCRMSPropOptimizer/title",
          "value": "MLCRMSPropOptimizer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCRMSPropOptimizer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCRMSPropOptimizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCRMSPropOptimizer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCRMSPropOptimizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensorParameter/title",
          "value": "MLCTensorParameter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensorParameter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCTensorParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensorParameter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCTensorParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizer/title",
          "value": "MLCOptimizer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCOptimizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCOptimizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCAdamWOptimizer/title",
          "value": "MLCAdamWOptimizer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCAdamWOptimizer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCAdamWOptimizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCAdamWOptimizer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCAdamWOptimizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCSGDOptimizer/title",
          "value": "MLCSGDOptimizer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCSGDOptimizer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCSGDOptimizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCSGDOptimizer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCSGDOptimizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTrainingGraph~1init(graphObjects:lossLayer:optimizer:)/title",
          "value": "graphWithGraphObjects:lossLayer:optimizer:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTrainingGraph~1init(graphObjects:lossLayer:optimizer:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "graphWithGraphObjects:lossLayer:optimizer:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizerDescriptor/title",
          "value": "MLCOptimizerDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizerDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCOptimizerDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizerDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCOptimizerDescriptor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mlcompute/optimizers"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mlcompute/optimizers"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
