{
  "abstract": [
    {
      "text": "Obtain a preconfigured activation layer with common behavior.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mlcompute/documentation/MLCompute",
        "doc://com.apple.mlcompute/documentation/MLCompute/layers",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mlcompute/documentation/MLCompute/preconfigured-activation-layers"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "ML Compute"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Preconfigured Activation Layers"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use a factory to receive a preconfigured activation layer for various activation types.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute": {
      "abstract": [
        {
          "text": "Accelerate training and validation of neural networks across the CPU and one or more GPUs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute",
      "kind": "symbol",
      "role": "collection",
      "title": "ML Compute",
      "type": "topic",
      "url": "/documentation/mlcompute"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationDescriptor": {
      "abstract": [
        {
          "text": "A configuration object you use to create an activation layer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCActivationDescriptor"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationDescriptor",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationdescriptor"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer": {
      "abstract": [
        {
          "text": "A layer that applies an activation function to the source tensor and produces an output.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCActivationLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationlayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/absolute": {
      "abstract": [
        {
          "text": "Creates an instance of an absolute activation layer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "absolute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCActivationLayer",
          "text": "MLCActivationLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/absolute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "absoluteLayer"
        }
      ],
      "role": "symbol",
      "title": "absolute",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationlayer/absolute"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/celu": {
      "abstract": [
        {
          "text": "Creates an instance of a CELU activation layer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "celu"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCActivationLayer",
          "text": "MLCActivationLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/celu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "celuLayer"
        }
      ],
      "role": "symbol",
      "title": "celu",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationlayer/celu"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/celu(a:)": {
      "abstract": [
        {
          "text": "Creates an instance of a CELU activation layer using the alpha value you specify for the CELU formation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "celu"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "a"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/celu(a:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "celuLayerWithA:"
        }
      ],
      "role": "symbol",
      "title": "celu(a:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationlayer/celu(a:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/clamp(min:max:)": {
      "abstract": [
        {
          "text": "Creates an instance of a clamp activation layer using the minimum and maximum values you specify for the clamp formation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clamp"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "min"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "max"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/clamp(min:max:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "clampLayerWithMinValue:maxValue:"
        }
      ],
      "role": "symbol",
      "title": "clamp(min:max:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationlayer/clamp(min:max:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/elu": {
      "abstract": [
        {
          "text": "Creates an instance of a parametric ELU activation layer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "elu"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCActivationLayer",
          "text": "MLCActivationLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/elu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "eluLayer"
        }
      ],
      "role": "symbol",
      "title": "elu",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationlayer/elu"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/elu(a:)": {
      "abstract": [
        {
          "text": "Creates an instance of an ELU activation layer using the alpha value you specify for the ELU formation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "elu"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "a"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/elu(a:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "eluLayerWithA:"
        }
      ],
      "role": "symbol",
      "title": "elu(a:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationlayer/elu(a:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/gelu": {
      "abstract": [
        {
          "text": "Creates an instance of a GELU activation layer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gelu"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCActivationLayer",
          "text": "MLCActivationLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/gelu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "geluLayer"
        }
      ],
      "role": "symbol",
      "title": "gelu",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationlayer/gelu"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/hardShrink": {
      "abstract": [
        {
          "text": "Creates an instance of a hard shrink activation layer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hardShrink"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCActivationLayer",
          "text": "MLCActivationLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/hardShrink",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hardShrinkLayer"
        }
      ],
      "role": "symbol",
      "title": "hardShrink",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationlayer/hardshrink"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/hardShrink(a:)": {
      "abstract": [
        {
          "text": "Creates an instance of a hard shrink activation layer using the lambda value you specify for the hard shrink formation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hardShrink"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "a"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/hardShrink(a:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hardShrinkLayerWithA:"
        }
      ],
      "role": "symbol",
      "title": "hardShrink(a:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationlayer/hardshrink(a:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/hardSigmoid": {
      "abstract": [
        {
          "text": "Creates an instance of a hard sigmoid activation layer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hardSigmoid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCActivationLayer",
          "text": "MLCActivationLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/hardSigmoid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hardSigmoidLayer"
        }
      ],
      "role": "symbol",
      "title": "hardSigmoid",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationlayer/hardsigmoid"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/hardSwish": {
      "abstract": [
        {
          "text": "Creates an instance of a hard swish activation layer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hardSwish"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCActivationLayer",
          "text": "MLCActivationLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/hardSwish",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hardSwishLayer"
        }
      ],
      "role": "symbol",
      "title": "hardSwish",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationlayer/hardswish"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/init(descriptor:)": {
      "abstract": [
        {
          "text": "Creates an activation layer with the descriptor you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "descriptor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCActivationDescriptor",
          "text": "MLCActivationDescriptor"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/init(descriptor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layerWithDescriptor:"
        }
      ],
      "role": "symbol",
      "title": "init(descriptor:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationlayer/init(descriptor:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/leakyReLU": {
      "abstract": [
        {
          "text": "Creates an instance of a leaky ReLU activation layer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leakyReLU"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCActivationLayer",
          "text": "MLCActivationLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/leakyReLU",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "leakyReLULayer"
        }
      ],
      "role": "symbol",
      "title": "leakyReLU",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationlayer/leakyrelu"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/leakyReLU(negativeSlope:)": {
      "abstract": [
        {
          "text": "Creates an instance of a leaky ReLU activation layer using the angle of the negative slope you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leakyReLU"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "negativeSlope"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/leakyReLU(negativeSlope:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "leakyReLULayerWithNegativeSlope:"
        }
      ],
      "role": "symbol",
      "title": "leakyReLU(negativeSlope:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationlayer/leakyrelu(negativeslope:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/linear(scale:bias:)": {
      "abstract": [
        {
          "text": "Creates an instance of a linear activation layer using the scale factor and bias value you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "linear"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "scale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "bias"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/linear(scale:bias:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "linearLayerWithScale:bias:"
        }
      ],
      "role": "symbol",
      "title": "linear(scale:bias:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationlayer/linear(scale:bias:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/logSigmoid": {
      "abstract": [
        {
          "text": "Creates an instance of a log sigmoid activation layer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "logSigmoid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCActivationLayer",
          "text": "MLCActivationLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/logSigmoid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "logSigmoidLayer"
        }
      ],
      "role": "symbol",
      "title": "logSigmoid",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationlayer/logsigmoid"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/relu": {
      "abstract": [
        {
          "text": "Creates an instance of a ReLU activation layer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "relu"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCActivationLayer",
          "text": "MLCActivationLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/relu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reluLayer"
        }
      ],
      "role": "symbol",
      "title": "relu",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationlayer/relu"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/relu6": {
      "abstract": [
        {
          "text": "Creates an instance of a ReLU6 activation layer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "relu6"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCActivationLayer",
          "text": "MLCActivationLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/relu6",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "relu6Layer"
        }
      ],
      "role": "symbol",
      "title": "relu6",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationlayer/relu6"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/relun(a:b:)": {
      "abstract": [
        {
          "text": "Creates an instance of a ReLUN activation layer using the alpha and beta values you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "relun"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "a"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "b"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/relun(a:b:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "relunLayerWithA:b:"
        }
      ],
      "role": "symbol",
      "title": "relun(a:b:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationlayer/relun(a:b:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/selu": {
      "abstract": [
        {
          "text": "Creates an instance of a SELU activation layer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selu"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCActivationLayer",
          "text": "MLCActivationLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/selu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "seluLayer"
        }
      ],
      "role": "symbol",
      "title": "selu",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationlayer/selu"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/sigmoid": {
      "abstract": [
        {
          "text": "Creates an instance of a sigmoid activation layer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sigmoid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCActivationLayer",
          "text": "MLCActivationLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/sigmoid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sigmoidLayer"
        }
      ],
      "role": "symbol",
      "title": "sigmoid",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationlayer/sigmoid"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/softPlus": {
      "abstract": [
        {
          "text": "Creates an instance of a parametric soft plus activation layer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "softPlus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCActivationLayer",
          "text": "MLCActivationLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/softPlus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "softPlusLayer"
        }
      ],
      "role": "symbol",
      "title": "softPlus",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationlayer/softplus"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/softPlus(beta:)": {
      "abstract": [
        {
          "text": "Creates an instance of a soft plus activation layer using the beta value you specify for the soft plus formation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "softPlus"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "beta"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/softPlus(beta:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "softPlusLayerWithBeta:"
        }
      ],
      "role": "symbol",
      "title": "softPlus(beta:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationlayer/softplus(beta:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/softShrink": {
      "abstract": [
        {
          "text": "Creates an instance of a soft shrink activation layer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "softShrink"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCActivationLayer",
          "text": "MLCActivationLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/softShrink",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "softShrinkLayer"
        }
      ],
      "role": "symbol",
      "title": "softShrink",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationlayer/softshrink"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/softShrink(a:)": {
      "abstract": [
        {
          "text": "Creates an instance of a soft shrink activation layer using the lambda value you specify for the soft shrink formation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "softShrink"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "a"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/softShrink(a:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "softShrinkLayerWithA:"
        }
      ],
      "role": "symbol",
      "title": "softShrink(a:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationlayer/softshrink(a:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/softSign": {
      "abstract": [
        {
          "text": "Creates an instance of a parametric soft sign activation layer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "softSign"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCActivationLayer",
          "text": "MLCActivationLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/softSign",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "softSignLayer"
        }
      ],
      "role": "symbol",
      "title": "softSign",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationlayer/softsign"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/tanh": {
      "abstract": [
        {
          "text": "Creates an instance of a hyperbolic tangent activation layer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tanh"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCActivationLayer",
          "text": "MLCActivationLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/tanh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tanhLayer"
        }
      ],
      "role": "symbol",
      "title": "tanh",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationlayer/tanh"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/tanhShrink": {
      "abstract": [
        {
          "text": "Creates an instance of a tanh shrink activation layer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tanhShrink"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCActivationLayer",
          "text": "MLCActivationLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/tanhShrink",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tanhShrinkLayer"
        }
      ],
      "role": "symbol",
      "title": "tanhShrink",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationlayer/tanhshrink"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/threshold(_:replacement:)": {
      "abstract": [
        {
          "text": "Creates an instance of a threshold activation layer using the threshold and replacement values you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "threshold"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "replacement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/threshold(_:replacement:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "thresholdLayerWithThreshold:replacement:"
        }
      ],
      "role": "symbol",
      "title": "threshold(_:replacement:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationlayer/threshold(_:replacement:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/layers": {
      "abstract": [
        {
          "text": "Create and inspect layers that encapsulate operations and configuration details to receive, process, and output tensors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/layers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Layers",
      "type": "topic",
      "url": "/documentation/mlcompute/layers"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-Activation-Layers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/init(descriptor:)",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationDescriptor"
      ],
      "title": "Creating Activation Layers"
    }
  ],
  "topicSections": [
    {
      "anchor": "Factory-Methods",
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/celu(a:)",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/clamp(min:max:)",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/elu(a:)",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/hardShrink(a:)",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/leakyReLU(negativeSlope:)",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/linear(scale:bias:)",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/relun(a:b:)",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/softPlus(beta:)",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/softShrink(a:)",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/threshold(_:replacement:)"
      ],
      "title": "Factory Methods"
    },
    {
      "anchor": "Factory-Properties",
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/absolute",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/celu",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/elu",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/gelu",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/hardShrink",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/hardSigmoid",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/hardSwish",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/leakyReLU",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/logSigmoid",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/relu",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/relu6",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/selu",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/sigmoid",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/softPlus",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/softShrink",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/softSign",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/tanh",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/tanhShrink"
      ],
      "title": "Factory Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Factory-Methods",
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/celu(a:)",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/clamp(min:max:)",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/elu(a:)",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/hardShrink(a:)",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/leakyReLU(negativeSlope:)",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/linear(scale:bias:)",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/relun(a:b:)",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/softPlus(beta:)",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/softShrink(a:)",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/threshold(_:replacement:)"
              ],
              "title": "Factory Methods"
            },
            {
              "anchor": "Factory-Properties",
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/absolute",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/celu",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/elu",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/gelu",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/hardShrink",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/hardSigmoid",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/hardSwish",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/leakyReLU",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/logSigmoid",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/relu",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/relu6",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/selu",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/sigmoid",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/softPlus",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/softShrink",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/softSign",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/tanh",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/tanhShrink"
              ],
              "title": "Factory Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-Activation-Layers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationLayer/init(descriptor:)",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationDescriptor"
              ],
              "title": "Creating Activation Layers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1hardSwish/title",
          "value": "hardSwishLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1hardSwish/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hardSwishLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1hardSigmoid/title",
          "value": "hardSigmoidLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1hardSigmoid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hardSigmoidLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1elu/title",
          "value": "eluLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1elu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "eluLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1softPlus(beta:)/title",
          "value": "softPlusLayerWithBeta:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1softPlus(beta:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "softPlusLayerWithBeta:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1elu(a:)/title",
          "value": "eluLayerWithA:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1elu(a:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "eluLayerWithA:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1softShrink(a:)/title",
          "value": "softShrinkLayerWithA:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1softShrink(a:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "softShrinkLayerWithA:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1tanh/title",
          "value": "tanhLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1tanh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tanhLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1linear(scale:bias:)/title",
          "value": "linearLayerWithScale:bias:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1linear(scale:bias:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "linearLayerWithScale:bias:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1leakyReLU/title",
          "value": "leakyReLULayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1leakyReLU/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "leakyReLULayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1softSign/title",
          "value": "softSignLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1softSign/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "softSignLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1celu(a:)/title",
          "value": "celuLayerWithA:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1celu(a:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "celuLayerWithA:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1tanhShrink/title",
          "value": "tanhShrinkLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1tanhShrink/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tanhShrinkLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1absolute/title",
          "value": "absoluteLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1absolute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "absoluteLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1hardShrink(a:)/title",
          "value": "hardShrinkLayerWithA:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1hardShrink(a:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "hardShrinkLayerWithA:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1gelu/title",
          "value": "geluLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1gelu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "geluLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1clamp(min:max:)/title",
          "value": "clampLayerWithMinValue:maxValue:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1clamp(min:max:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "clampLayerWithMinValue:maxValue:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1softPlus/title",
          "value": "softPlusLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1softPlus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "softPlusLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1hardShrink/title",
          "value": "hardShrinkLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1hardShrink/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hardShrinkLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1leakyReLU(negativeSlope:)/title",
          "value": "leakyReLULayerWithNegativeSlope:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1leakyReLU(negativeSlope:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "leakyReLULayerWithNegativeSlope:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1celu/title",
          "value": "celuLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1celu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "celuLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1softShrink/title",
          "value": "softShrinkLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1softShrink/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "softShrinkLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1relu6/title",
          "value": "relu6Layer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1relu6/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "relu6Layer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1relun(a:b:)/title",
          "value": "relunLayerWithA:b:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1relun(a:b:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "relunLayerWithA:b:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationDescriptor/title",
          "value": "MLCActivationDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1selu/title",
          "value": "seluLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1selu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "seluLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1relu/title",
          "value": "reluLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1relu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reluLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1sigmoid/title",
          "value": "sigmoidLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1sigmoid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sigmoidLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1init(descriptor:)/title",
          "value": "layerWithDescriptor:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1init(descriptor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "layerWithDescriptor:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1logSigmoid/title",
          "value": "logSigmoidLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1logSigmoid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "logSigmoidLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1threshold(_:replacement:)/title",
          "value": "thresholdLayerWithThreshold:replacement:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer~1threshold(_:replacement:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "thresholdLayerWithThreshold:replacement:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer/title",
          "value": "MLCActivationLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationLayer"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mlcompute/preconfigured-activation-layers"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mlcompute/preconfigured-activation-layers"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
