{
  "abstract": [
    {
      "text": "Create, train, and validate a graph to produce acceptable prediction results.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mlcompute/documentation/MLCompute"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mlcompute/documentation/MLCompute/training-and-validation"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "ML Compute"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Training and Validation"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute": {
      "abstract": [
        {
          "text": "Accelerate training and validation of neural networks across the CPU and one or more GPUs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute",
      "kind": "symbol",
      "role": "collection",
      "title": "ML Compute",
      "type": "topic",
      "url": "/documentation/mlcompute"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCDevice": {
      "abstract": [
        {
          "text": "An object that represents the CPU or one or more GPUs the framework uses to execute a neural network.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCDevice"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCDevice"
        }
      ],
      "role": "symbol",
      "title": "MLCDevice",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcdevice"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCGraph": {
      "abstract": [
        {
          "text": "A graph of layers you use to build a training or inference graph.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCGraph"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCGraph",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCGraph"
        }
      ],
      "role": "symbol",
      "title": "MLCGraph",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcgraph"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCInferenceGraph": {
      "abstract": [
        {
          "text": "An inference graph created from one or more MLCGraph instances plus additional layers added directly to the inference graph.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCInferenceGraph"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCInferenceGraph",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCInferenceGraph"
        }
      ],
      "role": "symbol",
      "title": "MLCInferenceGraph",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcinferencegraph"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCPlatform": {
      "abstract": [
        {
          "text": "A utility class for setting global properties in the framework.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCPlatform"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCPlatform",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCPlatform"
        }
      ],
      "role": "symbol",
      "title": "MLCPlatform",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcplatform"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor": {
      "abstract": [
        {
          "text": "The data object you use throughout the framework.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCTensor"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCTensor"
        }
      ],
      "role": "symbol",
      "title": "MLCTensor",
      "type": "topic",
      "url": "/documentation/mlcompute/mlctensor"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCTrainingGraph": {
      "abstract": [
        {
          "text": "A training graph that you create from one or more graph objects plus additional layers you add directly to the training graph.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCTrainingGraph"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTrainingGraph",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCTrainingGraph"
        }
      ],
      "role": "symbol",
      "title": "MLCTrainingGraph",
      "type": "topic",
      "url": "/documentation/mlcompute/mlctraininggraph"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/layers": {
      "abstract": [
        {
          "text": "Create and inspect layers that encapsulate operations and configuration details to receive, process, and output tensors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/layers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Layers",
      "type": "topic",
      "url": "/documentation/mlcompute/layers"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Components",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCPlatform",
        "doc://com.apple.mlcompute/documentation/MLCompute/layers"
      ],
      "title": "Components"
    }
  ],
  "topicSections": [
    {
      "anchor": "Devices",
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCDevice"
      ],
      "title": "Devices"
    },
    {
      "anchor": "Graphs",
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCGraph",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCTrainingGraph",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCInferenceGraph"
      ],
      "title": "Graphs"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Devices",
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCDevice"
              ],
              "title": "Devices"
            },
            {
              "anchor": "Graphs",
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCGraph",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCTrainingGraph",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCInferenceGraph"
              ],
              "title": "Graphs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Components",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCPlatform",
                "doc://com.apple.mlcompute/documentation/MLCompute/layers"
              ],
              "title": "Components"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCInferenceGraph/title",
          "value": "MLCInferenceGraph"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCInferenceGraph/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCInferenceGraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCInferenceGraph/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCInferenceGraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCDevice/title",
          "value": "MLCDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensor/title",
          "value": "MLCTensor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCTensor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCTensor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCGraph/title",
          "value": "MLCGraph"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCGraph/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCGraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCGraph/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCGraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPlatform/title",
          "value": "MLCPlatform"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPlatform/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCPlatform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCPlatform/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCPlatform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTrainingGraph/title",
          "value": "MLCTrainingGraph"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTrainingGraph/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCTrainingGraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTrainingGraph/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCTrainingGraph"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mlcompute/training-and-validation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mlcompute/training-and-validation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
